### ISSUE TITLE
nextcloudcmd 2.3.2 not syncing hidden objects on Ubuntu 16.04

### ISSUE THREAD

**Issue by njvdh** [nextcloud/desktop#100]
Directories and files having a name starting with a dot are not synced, commandline option "-h" is included.
This concerns the commandline client **nextcloudcmd**, as the GUI-client nextcloud works as expected.
I wanted to use the commandline client to sync a directory-tree on a VM with a nextcloud-server.

**Comment by camilasan** [comment]
Hi! Is there a specific reason for not using the latest desktop client?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by bronger** [comment]
Using nextcloudcmd version 3.16.4, I’m still seeing this issue. Option “`-h`” is effectless. Please reopen.
