### ISSUE TITLE
Windows client too fast upload shown.

### ISSUE THREAD

**Issue by GAS85** [nextcloud/desktop#1003]
First of all thanks you, upload speed is dramaticly increased with a new NC Client!

### Expected behaviour
By upload user can see real time upload speed. That works correctly in NC Client 2.3.

### Actual behaviour
New client do upload quite fast, but showing speed at least twice higher than it could be.

### Steps to reproduce
1. Get NC Server connected with e.g. 60 Mbps.
2. Put huge files into NC folder to get Client do some work.
3. Open client and see that upload speed will shown around 13 MB/s what is around 104 Mbps, or almost twice bigger than it can be.
physically connected 60 Mbps.
Compression is disabled on service AND large _encrypted_ files (as were here) could not have such a huge compression ratio.

![nc_client_too_fast](https://user-images.githubusercontent.com/6813635/50902809-36a60300-141c-11e9-9923-421be40e5c8d.png)

### Client configuration
Client version: 2.5.1

Operating system: Windows 10

OS language: EN

### Server configuration

Operating system: Ubuntu 16.04

Web server: Apache 2.4.34

Database: MySQL 5.7.23

PHP version: 7.0.30

Nextcloud version: 14.0.3

Updated from an older Nextcloud/ownCloud or fresh install: Updated from older

Where did you install Nextcloud from: Official

Storage backend (external storage): HDD Local

**Comment by FlexW** [comment]
Does this issue still exist with the latest client (version 3.2.0)?

**Comment by GAS85** [comment]
Tested in v3 and speed seems correct now.
