### ISSUE TITLE
[2.5.1 ElementaryOS] snap directory files cannot be opened in libreoffice

### ISSUE THREAD

**Issue by boetk** [nextcloud/desktop#1005]
I installed Nextcloud using your snap and thus the latest version of your software. 

### Expected behaviour
I would expect Libreoffice to be able to open .ods files in snap nextcloud directory but wasn't. Libreoffice just shows Cannot access (file path). 

### Actual behaviour
Could not open .ods files using libreoffice 6.1 with the files in the snap nextcloud directory (default location) on my machine. I tried chaning ownership to my user and giving chmod 777 access, but to no avail.

### Steps to reproduce
1. Install nextcloud-client using snap
2. login and sync all files 
3. Try open a file using libreoffice

Fix to the issue was just to install it without using snap, since it was pretty important to be able to open files in the directory.

### Client configuration
Client version: 2.5.1

Operating system: Elementary OS

OS language: US-english

Do not know these, since I just reinstalled outside of snap.
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server: 

Database:

PHP version:

Nextcloud version: 2.5.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
The snap version is not maintained by us. Please file a issue to the packager.
