### ISSUE TITLE
Can't run nextcloud client on Win7 64

### ISSUE THREAD

**Issue by nick-denry** [nextcloud/desktop#1008]
### Expected behaviour
Client running ok after fresh install on Windows 7 x64.

### Actual behaviour
Nexctloud.exe crashed with error 0xc000007b

### Steps to reproduce
1. Install client with official installer from nextcloud.com
2. Try to run
3. Get error message

### Client configuration
Client version: 2.5.1

Operating system: Windows 7 64 bit

OS language: Ru

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: 
C:\Program Files(x86)\Nextcloud

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

Get this message while try to run after fresh installation.
![n1](https://user-images.githubusercontent.com/1450983/50987180-f462eb80-1519-11e9-8f64-49c323e1f41b.png)

I've check nextcloud.exe with dependency walker and got that it requires BluetoothApis.dll that missing on my system.

![n2](https://user-images.githubusercontent.com/1450983/50987308-5e7b9080-151a-11e9-9b78-b9d31a1206d9.png)

BluetoothApis.dll is required for QtWebEngineCore and maybe somehow related with https://bugreports.qt.io/browse/QTBUG-59412

![n3](https://user-images.githubusercontent.com/1450983/50987484-cfbb4380-151a-11e9-9ef4-6ee8b5c4a759.png)

BluetoothApis.dll is not provided with Windows7.

Anyway, I've add BluetoothApis.dll to system32, dependency gone, but still get error 0xc000007b

**Comment by eboth** [comment]
I don't have BluetoothApis.dll on my W7 system either, and 2.5.1 runs OK here, so that's not the problem (as you confirmed yourself).

**Comment by nick-denry** [comment]
How can I else check why this error happens? I've tried some versions backwards, 2.3.2.1 works well.

**Comment by nick-denry** [comment]
Works after upgrade to W10
