### ISSUE TITLE
Extra trailing / on webdav URL prevents connecting

### ISSUE THREAD

**Issue by virtualdxs** [nextcloud/desktop#101]
I'm running 13.0.0beta3 on my server using Caddy with the following (relevant) config:

        rewrite {
                r ^/nextcloud/(?:\.htaccess|data|config|db_structure\.xml|README)
                to /403
        }

        rewrite {
                r ^/nextcloud/remote.php/(webdav|caldav|carddav|dav)/(.+?)(\/?)$
                to /nextcloud/remote.php/{1}/{2}
        }

        rewrite {
                r ^/nextcloud/remote.php/(webdav|caldav|carddav|dav)(\/?)$
                to /nextcloud/remote.php/{1}
        }

        redir /.well-known/carddav /nextcloud/remote.php/carddav 301
        redir /.well-known/caldav /nextcloud/remote.php/caldav 301

        rewrite {
                r ^/nextcloud/index.php/.*$
                to /nextcloud/index.php?{query}
        }

When I try to link the Nextcloud client, it fails complaining that `https://k7dxs.xyz/nextcloud/remote.php/webdav//` returns a 503 error. I open it in my web browser and it does, in fact, return 503 (if authenticated). When I remove the trailing `/`, it gives me the expected message that it's not for opening in a web browser.

**Comment by jlelse** [comment]
This may fix it: https://github.com/caddyserver/examples/pull/117

**Comment by virtualdxs** [comment]
@jlelse That should definitely work around it, and I will definitely be using that. That being said, I would like to leave this issue open until there is a real fix, since it's a bug on the client.

**Comment by jlelse** [comment]
Same issue seems to exist in Android client

**Comment by jlelse** [comment]
@rullzer So we don't need the special handling in the config file anymore?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
