### ISSUE TITLE
Windows 2.5.1 client https not using https

### ISSUE THREAD

**Issue by ms308680** [nextcloud/desktop#1010]
### Expected behavior
In a previous version (I am sorry I do not remember which), the desktop client kept the https://cloud.example.com address for a secure connection between the computer and the server.

### Actual behavior
When you connect to a next cloud server, it asks for a web address to the server.  I input a https://cloud.example.com address, which it seems like it accepts, but after full setup, it drops the "s". (this behavior is across 6 computers)

### Steps to reproduce
1.Install latest version 2.5.1
2.Connect to https://cloud.example.com (HTTPS is enabled, with a valid certificate on the server)
3.open nextcloud to see it using http://cloud.example.com

### Client configuration
Client version:2.5.1

Operating system:
Windows 10 1803 Pro and Home
Windows 10 1809 Pro and Home
Windows 7 Pro and Home all current updates

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
default C:\Program Files (x86)\Nextcloud

### Logs

1. Client logfile:
File log.txt
cannot be opened for writing
The log output can not be saved!

I do not see where to put suggestions... a quick suggestion about the taskbar icon, when left clicked, if the behavior can be set by a setting in the general settings for it to perform whatever action they want (in case there are other things people want it to do).  In my case, it would be nice for it to open the nextcloud folder on the computer instead of the settings.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
