### ISSUE TITLE
Feature request : Show the last sync execution datetime

### ISSUE THREAD

**Issue by ymolinet** [nextcloud/desktop#1016]
Hi,

Is it possible to add the last sync execution datetime near the sync.
Some folder could be indicate as correctly sync but don't have synced from a long of time (another sync could take a long time).

Maybe another icon could be necessary to increase the user attention.

Thanks,
Yannick

**Comment by DominiqueFuchs** [comment]
Thanks to @javierllorente and #1039 this is now implemented 🎉
