### ISSUE TITLE
Feature request: support for retina displays

### ISSUE THREAD

**Issue by valentinocossar** [nextcloud/desktop#1017]
Hi,

Is it possible to add support for retina displays resolution?
This is a screenshot of the actual icon on macOS.

<img width="31" alt="schermata 2019-01-13 alle 19 12 18" src="https://user-images.githubusercontent.com/4087384/51089069-52384300-1767-11e9-9e8f-f7630b756ff7.png">

Also in settings, there are icons that not support retina displays.

Thanks,
Valentino

**Comment by janprzy** [comment]
In my case, the menu bar icon supports retina displays. However, it does not automatically switch. When I switch from a non-retina to a retina display, the icon will appear pixelated until I restart the Nextcloud client.

**Comment by DivineDominion** [comment]
Wondered about the same, and restarting the app does reload/display resources @2x resolution just fine.

Am not comfortable with the app source, yet, but a trail to follow is Qt 5.5's auto-scaling features, which apparently are not used here, yet. https://doc.qt.io/qt-5/highdpi.html
