### ISSUE TITLE
"Recent Changes" in indicator does nothing(Ubuntu/Linux)

### ISSUE THREAD

**Issue by DroWnThePoor** [nextcloud/desktop#102]
![nextcissue](https://user-images.githubusercontent.com/16339020/34329777-de9dcc28-e8da-11e7-8fa7-cc725003b06b.png)

I'm running Elementary OS Loki 0.4 which is built on Ubuntu 16.04 LTS.

On the ownCloud version, simply highlighting this would bring down a list of recently changed files, as does the Dropbox indicator, but that isn't happening here. 
Furthermore, clicking this item does not open the settings window or do anything at all.
Is this a bug?

**Comment by selivan** [comment]
Ubuntu 16.04 LTS
Nextcloud client 2.3.3 (latest available from PPA)

"Recent Changes" menu element does nothing.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by camilasan** [comment]
if you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
