### ISSUE TITLE
Win64 Desktop Client - no OPENSSL_Applink

### ISSUE THREAD

**Issue by xt1040** [nextcloud/desktop#1020]
### Expected behaviour
Nextcloud syncs end-to-end encrypted folders

### Actual behaviour
At start, Nextcloud client crashes with OPENSSL error. See image below

![image](https://user-images.githubusercontent.com/45565682/51113102-34b7b780-1801-11e9-98f4-877f669d70c2.png)

### Steps to reproduce
1. Install latest Nextcloud Windows desktop client
2. Start client
3. Client crashes at startup when syncing folders with the message shown above

### Client configuration
Client version: 2.5.1

Operating system: Windows 7 - 64-bit

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

1. Client logfile: 

OCC::Application::setupLogging 	"################## Nextcloud locale:[de_AT] ui_lang:[] version:[2.5.1final (build 20181204)] os:[Windows 7 SP 1 (6.1)]"
[OCC::Application::setupTranslations 	Using "de_DE" translation
[OCC::SocketApi::SocketApi 	server started, listening at  "\\\\.\\pipe\\ownCloud-S"
[OCC::FolderMan::FolderMan 	setting remote poll timer interval to 30000 msec
[unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_new
[unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_free
[unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
[unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
[unknown 	QSslSocket: cannot resolve SSL_CONF_CTX_finish
[unknown 	QSslSocket: cannot resolve SSL_CONF_cmd
[unknown 	QSslSocket: cannot resolve SSL_set_alpn_protos
[unknown 	QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
[unknown 	QSslSocket: cannot resolve SSL_get0_alpn_selected

**Comment by DanScharon** [comment]
still the case with 2.5.2

**Comment by new251** [comment]
We simply do not care about such "minor" issues. Help yourself and use another solution.

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
