### ISSUE TITLE
symbolic links in shell integration not followed

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/desktop#1022]
# Expected behaviour
If a folder is synchronized in the desktop client, and a symbolic link is created to that folder on the client side, then shell integration solutions should represent the link and its children as a folder being synchronized.

# Actual behaviour
Tested in Nemo, icons and context menu do not appear for the symbolic link or its children.

# Steps to reproduce
1. Configure a folder for client synchronization.
1. Open the folder in Nemo, and confirm shell integration recognizes the folder as a synchronization target.
2. Make a symbolic link to the folder on the client.
3. Open the symbolic link in Nemo.  No shell integration appears.

# Client configuration

**Client version**: 
2.5.1

**Operating system**:
Linux Mint 19.1

**OS language**:
English

**Qt version** used by client package (Linux only, see also Settings dialog):
`libqt5`

**Client package** (From Nextcloud or distro) (Linux only):
`nextcloud-client`, `nextcloud-client-nemo`

**Installation path of client**:
`/usr/share/nemo-python/extensions/`

-----------

_(Note: I understand that symbolic links are not presently supported by Nextcloud, but generally it would be useful if the desktop client, during synchronization, would follow links at the top level of a share.  It would seem that doing so requires no serious design change, because the client would simply resolve the symbolic link dynamically as the effective local target for the pairing with the designated server folder. 
 If two shares resolve to the same target, then the client can simply report an error.)_

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?I tested it on Nautilus and it seem to work.

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
