### ISSUE TITLE
_conflict files after nextcloud restore

### ISSUE THREAD

**Issue by michelsalla** [nextcloud/desktop#1026]
### Expected behaviour
I had to restore nextcoud and I expected that the new files and files modified since the backup will be transferred again on the server as if the nextcloud agent was disconnected during the changes

### Actual behaviour
i had to do a nextcoud restore on yesterday, i did maintenance: data-fingerprint and restarted the server nextcloud.
the agent was well resynchosized and the files created since the backup have been successfully transferred but the modified files have been replaced by the old version and the _conflict files have appeared instead

### Steps to reproduce
1. backup nextcloud data an data base
2. create a new file and modify an exitant file
3. restore nextcloud and do maintenance: data-fingerprint
4. wait for the agent to reconnect
5. the new file is transferred but the edit file is in _conflict

### Client configuration
Client version:2.3.3 and 2.5

Operating system: W10

OS language: french

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
