### ISSUE TITLE
How get an older version? (bionic 2.3.2 or 2.3.2)

### ISSUE THREAD

**Issue by natrius** [nextcloud/desktop#1028]
The 2.5.0 or 2.5.1 client is simply not working with KDE Neon (=Ubuntu) right now and i'm aware that it might need some time to resolve the issue #888 .

But HOW can i install an old version like 2.3.2 or 2.3.3 -> they worked. 
I wanted to install with ''apt-get install pkg=version'' and to find out what version is needed ''apt-cache policy nextcloud-client'' and unfortunately there is just 2.5.1 available, also good to see in the ppa itself (https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) where there is just 2.5.1 for Bionic Beaver available. 

Make the older versions available again somehow so i can try to install the old version, connect to my server and update via the ppa.

**Comment by VoidStructure** [comment]
You can do that with the flatpak version of the desktop client: First install the nextcloud client via flathub or discover. After that get the available versions via `flatpak remote-info --log flathub org.nextcloud.Nextcloud`. Copy the commit hash from the version to which you want fallback to and "update" the nextcloud app to the older version via 
``flatpak update --commit=c64a9f921a09faf9281c6f2fa876b5cceb45622fbecdd992377dc25694a1fbb4 org.nextcloud.Nextcloud`` (updates to 2.3.3).

**Comment by rolandixor** [comment]
I'm using the snap build from now on. The current builds are causing too many issues on my system, not only preventing syncing, but actually locking up the system and putting me at risk of data loss.

**Comment by user23498723452** [comment]
@rolandixor Do you have to do anything special to gain access to files?  Are there limits where the client works?  My files are all in my Ubuntu profile directory.  And does the client auto-start at login?

**Comment by rolandixor** [comment]
Everything works as you would expect, except nautilus integration (which was working when I first installed the snap, but no longer works after restarting the client).

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
