### ISSUE TITLE
libssp-0.dll is missing

### ISSUE THREAD

**Issue by dagayaru** [nextcloud/desktop#103]
[Enabling stack-protector-strong on Windows](https://github.com/nextcloud/client/commit/586fd346ead9aaa21aace8b2ffd616f0cc249a9e) makes Nextcloud client loading libssp-0.dll which might be missing. May be some additional redistributables going to be reqiured for stack-protector-strong.. Don't know exactly.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this warning? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
