### ISSUE TITLE
how to stop repeated "help nextcloud" notification?

### ISSUE THREAD

**Issue by r2evans** [nextcloud/desktop#1030]
### Expected behaviour

A "reasonable" notification schedule asking me to provide telemetry data to nextcloud.com. Though subjective, I'd think weekly. I could probably cope with daily. But more-often-than-hourly is too much.

### Actual behaviour

A dozen or so times per day my desktop client pops a notification asking me to "Help Nextcloud" (with usage statistics). I have it disabled in the server.

### Steps to reproduce
1. Have telemetry data disabled in the server ("Usage survey", deselect monthly upload)
2. Wait a few minutes, the desktop app will ask me again.

I updated both the server (from 13 to 14 to 15 within 48 hours) and the client (from 2.5.0 to 2.5.1) about the same time, so I am not certain from where the pestering is originating. I'm offering it as an issue here because I suggest that the client should remember the last time I received the notification and "shushed" it. (I don't know if there is anything passed back to the server from this notification; if there is, then this issue is also with nextcloud/server, not just nextcloud/desktop.)

### Client configuration

Client version: 2.5.1final (build 20181204)

Operating system: win10

OS language: English (US)

Installation path of client: `c:\Program Files (x86)\Nextcloud\`

### Server configuration

<details><summary>config.php</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.activedecisionsupport.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritewebroot": "\/cloud",
        "overwrite.cli.url": "https:\/\/my.domain.com\/cloud",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "lost_password_link": "disabled"
    }
}
```

</details>

Operating system: ubuntu 16.04

Web server: apache

Database: postgres

PHP version:

```
PHP 7.3.1 (cli) (built: Jan 11 2019 00:31:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies
```

Nextcloud version: nextcloud:15.0.2-apache docker image

Storage backend (external storage): native/mount

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

<details><summary>Client logfile</summary>

```
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://my.domain.com/cloud/remote.php/dav/files/my.user/") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	2 "" "https://my.domain.com/cloud/ocs/v2.php/apps/notifications/api/v2/notifications?format=json" has X-Request-ID "e786cc63-66cd-461a-92f2-948e372c24c2"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://my.domain.com/cloud" + "ocs/v2.php/apps/notifications/api/v2/notifications" "OCC::ServerNotificationHandler"
[OCC::AccessManager::createRequest 	2 "" "https://my.otherdomain.com/oc/ocs/v2.php/apps/notifications/api/v2/notifications?format=json" has X-Request-ID "9bfa6426-1b1b-407f-9485-b233cc5cafba"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://my.otherdomain.com/oc" + "ocs/v2.php/apps/notifications/api/v2/notifications" "OCC::ServerNotificationHandler"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://my.domain.com/cloud/remote.php/dav/files/my.user/" for changes via ETag check. (time since last sync: 954 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://my.domain.com/cloud/remote.php/dav/files/my.user/" has X-Request-ID "966a3bdf-2597-4ed4-a5a7-37a3bfb69977"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://my.domain.com/cloud" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://my.domain.com/cloud/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") FINISHED WITH STATUS "OK"
[OCC::ActivityListModel::addNotificationToActivityList 	Notification successfully added to the notification list:  "Help improve Nextcloud"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://my.domain.com/cloud/remote.php/dav/files/my.user/") FINISHED WITH STATUS "OK"
```

</details>

  (This log shows that I have two instances of nextcloud configured and running. In this instance, I've had `my.otherdomain.com` paused for the last few hours, so I believe it is not contributing to this. It is a nextcloud-14 instance.)

2. Web server error log: (nothing remarkable)

3. Server logfile: nextcloud log (nothing remarkable)

**Comment by r2evans** [comment]
This might be related (or even the underlying cause): in the web interface, I have the "help nextcloud" notification with a "Not Now" button. When I click it, I get a "Failed to perform action" error. Digging deeper, it's because it is targeting an HTTP endpoint vice HTTPS.

I have nextcloud running on HTTPS in a docker container, with a SSL-proxy (traefik). Within my `config.php`, I have (among others):

```
'overwritewebroot' => '/cloud',                                                                                                                                                                                     'overwrite.cli.url' => 'https://my.domain.com/cloud',
```

and everything else seems to work, so perhaps the issue is in the server, and the client is just propagating the symptom.

**Comment by r2evans** [comment]
That was it ... I added

```
'overwriteprotocol' => 'https',
```

(to the server's `config.php`) in addition to the other overwrite rules and the symptom went away.

**Comment by davidnewhall** [comment]
I uninstalled the app because this notification wouldn't go away. Clicking it doesn't do anything. Not sure how to help you, but you can help me by not polluting my screen.

**Comment by regulator-g** [comment]
thanks adding that https overwrite resolved it for me, I seriously got bombarded by those notifications on all my devices

**Comment by GlassedSilver** [comment]
Please re-open, the notification appears on my clients still despite the config.php rule being in place.

Also I would kindly ask to consider that instead of offering a "not now" option to give a "don't ask again" option, at the very least as a tickbox that overrides the "not now" path.

I also don't think that it's wise to offer an opt-out ONLY server-wide, if anything a user should always have the ability to deny telemetry.

How is this unresolved for 6 years?

**Comment by markcst** [comment]
> Please re-open, the notification appears on my clients still despite the config.php rule being in place.
> 
> Also I would kindly ask to consider that instead of offering a "not now" option to give a "don't ask again" option, at the very least as a tickbox that overrides the "not now" path.
> 
> I also don't think that it's wise to offer an opt-out ONLY server-wide, if anything a user should always have the ability to deny telemetry.
> 
> How is this unresolved for 6 years?

Hi! I think this is still a thing? I'm currently experiencing it, and of course I have the `config.php` in place too, also with the `overwriteprotocol' => 'https'` positioned in that file.

Please, Nextcloud team, fix this 🙏
