### ISSUE TITLE
Client crash when a local folder sync is in a specific state

### ISSUE THREAD

**Issue by jmaspons** [nextcloud/desktop#1031]
### Expected behaviour
The client should not crash in any case

### Actual behaviour
Nexcloud client crash when syncing a specific folder in a specific state. The same folder in other systems get synced without problems.

### Steps to reproduce
1. Get a folder in a broken state. No idea how to get there. Maybe a partial/not finished sync.
2. The client crash when trying to sync the folder. If you pause the sync of the specific folder, it works without problems (edit nextcloud.cfg file if you don't have time to pause through the gui).
3. When the problematic folder is unselected for sync, removed and activated again the problem disappears.

### Client configuration
Client version: 2.5.1-20181204.111806~bionic1

Operating system: Linux (Neon 18.04)

OS language: catalan

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: the default for http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic/main

### Server configuration

Operating system: Linux (Ubuntu 18.04)

Web server: apache2

Database: mariadb

PHP version: 7.2.10

Nextcloud version: 15.0.2.0

### Logs
https://gist.github.com/jmaspons/741d9973ab142cbcea4d6f507b76a4a1

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
