### ISSUE TITLE
Application 2.5.1 does not start on Win10 after some windows updates

### ISSUE THREAD

**Issue by skorobogachev** [nextcloud/desktop#1033]
### Expected behaviour
Desktop application should start

### Actual behaviour
After some Win10 updates application does not start at all

### Steps to reproduce
1. Install the latest Win10 updates (Nov18 or Dec18)
2. Try to run NextCloud Desktop
(That is only assumption that win updates influence)

### Client configuration
Client version: 2.5.1

Operating system:
Windows 10

OS language:
Eng US /Rus

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
