### ISSUE TITLE
Snap Builds outdated

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/desktop#1034]
Latest release for nextcloud-client on snapcraft.io is 2.3.3 🤔 Is there an issue with the build?

Ref.: https://snapcraft.io/nextcloud-client

@camilasan @rullzer

**Comment by edent** [comment]
Agreed. The Snap version also has a broken tray icon (Ubuntu 19.04)

**Comment by lverissimo** [comment]
hello, what happened to this snap? I can no longer find nextcloud-client snap,

**Comment by rudiservo** [comment]
No one seems to be updating the nextcloud snap anymore, they now use ppa.
it would be nice to at least give a heads up

**Comment by mgallien** [comment]
There is no current plan to work on Snap package. Closing this issue until we revisit that.
