### ISSUE TITLE
Cannot login with password or token

### ISSUE THREAD

**Issue by jellykells** [nextcloud/desktop#1038]
### Expected behaviour
After authorizing desktop client with password or app token, Nextcloud client should allow access.

### Actual behaviour
Client redirects to Log In/Authorization page again, even though session is shown in Nextcloud account panel.

### Steps to reproduce
1. Enter account credentials or app token in client
2. Click "Grant access"

### Client configuration
Client version: Version 2.5.1final (build 20181204)

Operating system: Windows 7 x64 SP1

OS language: en-US

Installation path of client: %programfiles(x86)%/Nextcloud

### Server configuration

Operating system: Ubuntu 18.04.1 Bionic

I'm running the Nextcloud snap package on the server

**Comment by Schneehexe** [comment]
I'm hanging on here because the desktop client is behaving the same way for me.

Windows 7, x64 SP1.
Nextcloud Desktop Client Version 2.5.1final (build 20181204)

Nextcloud Server 15.02

Server configuration detail
Operating system: Linux 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64
Web server: Apache (apache2handler)
Database: mysql 5.7.20
PHP version: 7.2.13-1+020181207100623.13+jessie1.gbpf57305

**Comment by evaryont** [comment]
I'm also running into this issue.

Client: `"Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)"` on Windows 10
Server: 15.0.2.0 in nextcloud docker container, powered by PostgreSQL with an nginx reverse proxy for HTTPS

**Comment by pedrxd** [comment]
Same here. I receive 405 error when the desktop try to login:  
"GET /index.php/login/flow/apptoken HTTP/1.1" 405 
Any other device that was logged before work fine, but news ones doesn't work. It doesn't work on android to.

**Comment by ahuckenbeck** [comment]
Same here on MAC. Nextcloud Client 2.5.1. Nextcloud instance is running in a docker container on Ubuntu 18.04 behind haproxy.

**Comment by rullzer** [comment]
Since I guess you are all ebind a proxy and have pure http in there.

Try settting: `'overwriteprotocol' => 'https'` in your config.php

**Comment by ahuckenbeck** [comment]
> Try settting: `'overwriteprotocol' => 'https'` in your config.php

That did the trick. Thank you!

**Comment by BillSchenk** [comment]
We were having similar issues with OSX client 2.5.1 on Nextcloud 15.x and 14.x. adding

> Try settting: `'overwriteprotocol' => 'https'` in your config.php

fixed the issue.

**Comment by jellykells** [comment]
> Since I guess you are all ebind a proxy and have pure http in there.
> 
> Try settting: `'overwriteprotocol' => 'https'` in your config.php

This solution works. I opted to enable https behind my proxy and that also solved the issue.

**Comment by vgdh** [comment]
Many thanks! It work!
