### ISSUE TITLE
SyncEngine::treewalkFile() can make errors

### ISSUE THREAD

**Issue by dagayaru** [nextcloud/desktop#104]
The line src/libsync/syncengine.cpp:595 doesn't join names with "/". It produces warnings like

> 12-25 17:14:39:237 [ warning sync.fileitem ]:   Failed to query the 'inode' for file "D:/Cloud/testempty.txt"

for file `D:/Cloud/test/empty.txt`. And some other file jobs may fail with wrong path.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
