### ISSUE TITLE
installer initiates reboot without user intervention

### ISSUE THREAD

**Issue by MiG29** [nextcloud/desktop#1040]
The Win10 2.5.1 client installer appears to initiate a reboot without user intervention:

The process C:\Program Files (x86)\Nextcloud\i18n\vcredist_x64.exe (computername) has initiated the restart of computer computername on behalf of user computername\LocalAdmin for the following reason: Application: Installation (Planned)
 Reason Code: 0x80040002
 Shutdown Type: restart
 Comment:

**Comment by moorsey** [comment]
Can confirm this, I think it is the C++ distributable that causes this, have seen it with other installers at work that force a reboot with no user prompt.  With NextCloud, this has happened on all four Win10 PCs I installed it on

**Comment by camilasan** [comment]
Please, try this installer: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.1.5037-daily-20190125.exe
Let me know if it works for you!
Thanks

**Comment by Fr3llD** [comment]
Could you fix this for the preview client as well?
https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview.exe

Is linked from https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration/

**Comment by camilasan** [comment]
Does it reboot for you @Dennis360ict? It should be fixed for the preview too.

**Comment by catscarlet** [comment]
I just scaried. I thought I got some virus that makes computer reboot, and then I found it was Nextcloud client installer.

**Comment by freezze** [comment]
This still occours. Please fix this on downloadable client from web.

**Comment by Dennis360ict** [comment]
@camilasan, sorry for the late reply. I had a monster project which drained me of all sanity. But I'm back now. 

I just tested it on a fresh Windows server 2016 (10.0.14393) and I didn't get a reboot with the following client:
https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview.exe
Windows shows the file version to be 2.5.0.5040

I found different other things, but I will create new issues for those.

**Comment by camilasan** [comment]
Is this still an issue? It should have been fixed. Here it is a link to the latest: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.3.5718-daily-20190806-Release.exe

**Comment by mgallien** [comment]
This is no longer the case. This bug has been fixed, I am closing the issue.

**Comment by Maxplosion** [comment]
Just had this happen on W10 with update to version 3.4.4
