### ISSUE TITLE
Error message spam due to temporarily locked file

### ISSUE THREAD

**Issue by Yournished** [nextcloud/desktop#1041]
I'm using the Windows client.

Nextcloud inherits a problem that Owncloud had in that it has very poor detection of file locks. When a file is being worked on, occasionally it fails to sync it, and then reacts by creating distracting balloon popups. The icon changes to a red X, and the log is flooded with false positive messages.

Firstly this is annoying. I frequently end up using programs that quickly create, write and then delete several files. This creates dozen of popups that mean nothing, because the only issue is that Nextcloud jumped the gun and tried to sync too soon, and in a few seconds surely the sync will be attempted again and everything will be fine.

Second, it is dangerous. The large number of false messages trains the user to ignore them, such that when a genuine sync error occurs, the user may overlook it assuming that it is yet another false alarm. It also makes genuine troubleshooting a pain, because one must sift through endless false error messages.

The core issue is that:
* Nextcloud windows client is bad at detecting file locks, and rushes to sync files without waiting for them to be unlocked, which fails
* Nextcloud treats these trivial failures as an important error message that demands the user's immediate attention and warrants being recorded in the log

Firstly, Nextcloud client should do a better job of detecting files that are locked. Perhaps the issue is that the files is being locked and unlocked in rapid succession, such that Nextcloud assumes the file is free now, and begins syncing only for the other program to come back and lock it again. The simplest solution is to allow a "cool off period": If a file has been edited recently, wait a few seconds or even minutes before trying to sync it. The cool off period can be a parameter in the client setting for users who wish to change it. I personally would prefer an even 15 minute delay in syncing instead of dealing with constant false errors.

Second, Nexctloud should not instantly raise an error every time a file cannot be synced due to an error. This is obviously something that happens frequently in normal usage, and is not due the same attention as a genuine error. Either the error should be raised when there is **repeated** failure to sync a file **over a long time period**  (eg. an hour), or the errors arising from this should be reported under a different category to allow filtering them. I suspect the former option would be simpler.

Please resolve this issue as it detracts from usability of the client and also obscures genuine errors.

**Comment by Railsimulatornet** [comment]
Same problem here :/

**Comment by GieltjE** [comment]
On a side note it would be great if we could add an exclusion list for specified files and extensions which are just completely ignored when locked (e.g. for files that are open when people use profiles that they transfer around).

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases
