### ISSUE TITLE
Nextcloud 2.5.1 installer on Windows 10 refuses to open

### ISSUE THREAD

**Issue by MShekow** [nextcloud/desktop#1044]
### Expected behaviour
Launching the installer does not work on a Windows 10 v1803 machine built by https://github.com/boxcutter/windows - this box builder script preconfigures Windows in some specific ways such that no UAC prompts are shown.
I'm not sure which (hidden) Windows setting causes this. Once I go to "Change user account control settings" and move the slider to some setting and then back to "Never notify", and restart the machine, the Nextcloud installer opens as expected again. This UAC setting alone does not seem to cause the issue. There might be another, hidden Windows setting (maybe found in the group policies or registry?) that causes the Nextcloud installer to refuse opening.

Other installers (e.g. ownCloud's installer) work fine.

### Actual behaviour
A dialog is shown that asks me to provide the password of "Administrator" (which I don't know). Using the preconfigured user ("vagrant", which has admin privileges) does not work. Finally the message "This installer requires admin access, try again" is shown.

### Steps to reproduce
1. Build a Windows 10 x64 evaluation using https://github.com/boxcutter/windows
2. Start a machine using the built box. Don't modify any settings.
3. Download Nextcloud installer and try to start it.

### Client configuration
Client version: 2.5.1

Operating system: Windows 10 v1803 x64 (evaluation)

OS language: English

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
