### ISSUE TITLE
Can't added new account on Windows 10 client, or register window ignors Proxy settings

### ISSUE THREAD

**Issue by GAS85** [nextcloud/desktop#1046]
Problem is that I have already 2 Accounts bounded via NC Client and try to added 3rd one. After entering URL I see an error Page. 2 other accounts are from the same domain and same NC installation.

### Expected behaviour
When user open NC Client and click on Added he is shown dialog to enter domain/URL. After this User being redirected to login flows and able to enter user name and password/token.

### Actual behaviour
After entering URL and click on next - an error page accrues. Besides this URL ended with "/" will not be overwritten and URL will be wrong in any way.
![image](https://user-images.githubusercontent.com/6813635/51826838-4fe9f300-22e8-11e9-810a-7776becf5926.png)

![image](https://user-images.githubusercontent.com/6813635/51826843-52e4e380-22e8-11e9-93ff-851e466ef41e.png)

Direct accessing https://DOMAIN/index.php/login/flow will cause 200 - "Access Forbidden Invalid request".

### Steps to reproduce
1. Have already 2 Accounts on Client
2. Click on added new
3. Enter URL and see an error on next page

### Client configuration
Client version: 2.5.1

Operating system: Windows 10

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Users\USERNAME\Other Prog\Nextcloud

### Server configuration

Operating system: Ubuntu 16.04

Web server: Apache Apache 2.4.34

Database: 5.7.24

PHP version: 7.0.32

Nextcloud version: 15.0.2.0

Storage backend (external storage): local

### Logs

```[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://DOMAIN" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://DOMAIN/remote.php/dav/files/work2/") FINISHED WITH STATUS "OK"
[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone 	Setting QNAM proxy to be system proxy "3://HE100255.emea1.cds.t-internal.com:8080"
[OCC::AccessManager::createRequest 	2 "" "https://DOMAIN/status.php" has X-Request-ID "2122a610-084b-464c-85d3-0fb2a7b5a0dd"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://DOMAIN" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Облака, белогривые лошарки","version":"15.0.2.0","versionstring":"15.0.2"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x263ea4d7f30)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://DOMAIN/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://DOMAIN/remote.php/webdav/" has X-Request-ID "ec47b8aa-caa2-4d08-979f-3c7082530fd7"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://DOMAIN" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://DOMAIN/remote.php/webdav/" has X-Request-ID "8ecc0edf-87f3-4d5f-b204-7cdbec324e35"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://DOMAIN" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://DOMAIN/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://DOMAIN/index.php/login/flow"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://DOMAIN" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unknown error"
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://DOMAIN/remote.php/dav/files/work2/") FINISHED WITH STATUS "OK"
```

1. Web server error log: No logs for this issue

2. Server logfile: nextcloud log (data/nextcloud.log): 
[nextcloud.log](https://github.com/nextcloud/desktop/files/2802432/nextcloud.log)

**Comment by GAS85** [comment]
Just find out that "Register with a Provider" also does not work:

![image](https://user-images.githubusercontent.com/6813635/51836177-e8d83880-22ff-11e9-8d6a-edc523784193.png)

**Comment by Volker-K** [comment]
seems to be same problem as here; https://github.com/nextcloud/desktop/issues/901

**Comment by GAS85** [comment]
And regression in compare to Client version 2.3.

**Comment by Volker-K** [comment]
And still the same in 2.5.2

**Comment by Volker-K** [comment]
btw this topic is still on "needs triage" since November, 28 in https://github.com/nextcloud/desktop/issues/901

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.

**Comment by Volker-K** [comment]
In fact the latest version works as expeced: consistent use of system wide proxy.
I appreciate the virtual files option very much. Makes everything a lot easyer.
