### ISSUE TITLE
Windows: Client Sync fails on other partition than C:

### ISSUE THREAD

**Issue by mrlaberlaber** [nextcloud/desktop#1047]
Sync with v2.5.1 fails but works fine with ownCloud Client 1.4.3 on **partition other than C:**

No problems with other software accessing other partition

### Expected behaviour
- syncing files as in version 2.4.3 (it works there; but neither with ownCloud Client 2.5.1 --> same errors)
![image](https://user-images.githubusercontent.com/8301641/51830648-a0fde500-22f0-11e9-8b88-fd9f79c8e02c.png)

### Actual behaviour
- if trying to sync existing sync folder:
![image](https://user-images.githubusercontent.com/8301641/51830274-c50cf680-22ef-11e9-8dfd-ea5d29a2ef7f.png)
- if trying to create new folder from Nextcloud's 'Add Fiolder Sync Connection':
![image](https://user-images.githubusercontent.com/8301641/51830347-eb329680-22ef-11e9-9f81-b1d52e459bf1.png)
- if trying to sync existing folder:
![image](https://user-images.githubusercontent.com/8301641/51830423-17e6ae00-22f0-11e9-87cc-645f34463080.png)

### Steps to reproduce
1. reformat entire partition
2. install nextcloud client
3. trying to setup sync folder

### Client configuration
Client version: 2.5.1

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: standard

### Logs
[OCC::FolderMan::slotFolderSyncStarted 	>========== Sync started for folder [D:\test2] of account [...] with remote [...]
[OCC::SyncEngine::startSync 	There are 321782435840 bytes available at "D:/test2/"
[OCC::SyncEngine::startSync 	New sync (no sync journal exists)
[OCC::SyncEngine::startSync 	"Using Qt 5.11.1 SSL library OpenSSL 1.0.1h 5 Jun 2014 on Windows 10 (10.0)"
[OCC::SqlDatabase::openHelper 	Error: "unable to open database file" for "D:/test2/._sync_93c1e0115b70.db"
[OCC::SqlDatabase::openHelper 	CANTOPEN extended errcode:  14
[OCC::SqlDatabase::openHelper 	CANTOPEN system errno:  2
[OCC::SyncJournalDb::checkConnect 	Error opening the db:  "unable to open database file"
[OCC::SyncEngine::startSync 	No way to create a sync journal!
[OCC::ActivityWidget::addError 	Item  "D:\\test2"  retrieved resulted in  "Unable to open or create the local sync database. Make sure you have write access in the sync folder."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Unable to open or create the local sync database. Make sure you have write access in the sync folder."
[OCC::SyncJournalDb::close 	Closing DB "D:/test2/._sync_93c1e0115b70.db"
[OCC::SyncEngine::finalize 	CSync run took  0 ms
[OCC::Folder::slotSyncFinished 	Client version 2.5.1final (build 20181204)  Qt 5.11.1  SSL  OpenSSL 1.0.1h 5 Jun 2014
[OCC::Folder::slotSyncFinished 	SyncEngine finished with ERROR
[OCC::Folder::showSyncResultPopup 	Folder sync result:  2
[OCC::Folder::slotSyncFinished 	the last 2 syncs failed

**Comment by mrlaberlaber** [comment]
Was caused by misbehaving Windows Defender -> Ransomware Protection -> Controlled Folder Access

**Comment by executed** [comment]
**Windows Defender** is _very likely_ the culprit here in some cases when this is the first time Nextcloud syncs the directory - but this is a week already since Nexcloud syncs my folder and I still get the error.
My problem description and **fix** is described in [this](https://help.nextcloud.com/t/unable-to-sync-documents-or-pictures-folders-from-desktop-client-windows-10/77688) thread.
