### ISSUE TITLE
"Recent Changes" List should not show a file multiple times

### ISSUE THREAD

**Issue by rgra** [nextcloud/desktop#1049]
### Expected behaviour
Recent changes tray menu should only show the latest change per file. This clutters the menu and makes it impossible to quickly open previously changed files.

### Actual behaviour
A file get an entry for each change. If the file is changed 10 times the tray menu is full with changes of that file.

### Steps to reproduce
1. Put a file in a synced folder
2. Change the file and save it
3. It will create an entry in the recent changes list
4. Change the file again and save it
5. You will have another entry for the same 

### Client configuration
Client version: 2.3.3

Operating system: Windows

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
