### ISSUE TITLE
Non-English character not showing correctly in Virtual Drive

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#1052]
### Expected behaviour
After opening virtual drive, all folder using Chinese character should shown properly.
i.e. 电影, 音乐, 我的照片

### Actual behaviour
All folder name uses Chinese characters are in gibberish of different length.

### Steps to reproduce
1. Create a folder with Chinese Character
2. Open Virtual Drive

### Client configuration
Client version:  Virtual Drive Preview

Operating system: Win10 Pro 64bits

OS language: Chinese

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by janneuu** [comment]
Not all European characters are showing correctly, either. The first folder in my virtual drive is called äänitteet, ![not Ã¤Ã¤nitteet](https://user-images.githubusercontent.com/2725725/52059931-db2ae900-2573-11e9-83fd-cee9df9f864d.jpg).

**Comment by janneuu** [comment]
I can, but the folder with the character encoding issue is empty on the virtual drive, although it is not empty on the server.

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
