### ISSUE TITLE
Absence of public key for the ubuntu bionic ppa

### ISSUE THREAD

**Issue by KevinNadaud** [nextcloud/desktop#1055]
### Expected behaviour
The adding of the ppa should work

### Actual behaviour
When adding the ppa, an error is shown concerning the gpg key:
`W:GPG error: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 60EE47FBAD3DD469, E:The repository 'http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic InRelease' is not signed.`

### Steps to reproduce
1. Open a terminal and write: sudo add-apt-repository ppa:nextcloud-devs/client

I'm using Linux Mint 19.1 which is based on Ubuntu 18.04, Bionic. I don't know if the bug is related to the distribution.

**Comment by rullzer** [comment]
@ivaradi

**Comment by ivaradi** [comment]
It could be related to the distribution, or there was some temporary outage of the key server when you added the PPA. See, e.g., this issue: https://github.com/nextcloud/client_theming/issues/118

**Comment by KevinNadaud** [comment]
Thanks for the quick answer ! I will retry later.
