### ISSUE TITLE
Unable to open files in virtual drive [Windows]

### ISSUE THREAD

**Issue by jacky35** [nextcloud/desktop#1056]
The virtual drive does not seem to work properly.
I can navigate in the server tree, but I can not open any file.

I found that the files had a value of 0.
you can see an example by following this link
http://dl.free.fr/jjGahildL

--
Client configuration
Client version: Virtual Drive Preview
Operating system: Win7 Pro 64bits

--
Server Nextcloud 15.0.2

--
Log
--

`[OCC::MirrorFindFiles 	long __cdecl OCC::MirrorFindFiles(const wchar_t *,int (__cdecl *)(struct _WIN32_FIND_DATAW *,struct _DOKAN_FILE_INFO *),struct _DOKAN_FILE_INFO *)  FileName:  "/Documents"
[OCC::Vfs_windows::instance 	class OCC::Vfs_windows *__cdecl OCC::Vfs_windows::instance(void)  instance:   OCC::Vfs_windows(0x868cfa0)
[OCC::MirrorFindFiles 	 gfds QSFileName:  "/Documents" DokanFileInfo->ProcessId :  1904  GetCurrentProcess():  4294967295  getExplorerID():  1904
[OCC::Vfs_windows::contentsOfDirectoryAtPath 	gfds path:  "/Documents"
[OCC::Vfs_windows::contentsOfDirectoryAtPath 	class QStringList *__cdecl OCC::Vfs_windows::contentsOfDirectoryAtPath(class QString,class QMap<class QString,class QVariant> &)  rootPath:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles"
[OCC::DiscoveryFolderFileList::doGetFolderContent 	void __cdecl OCC::DiscoveryFolderFileList::doGetFolderContent(const class QString &) Sub path:  "/Documents"
[OCC::DiscoveryFolderFileList::doGetFolderContent 	void __cdecl OCC::DiscoveryFolderFileList::doGetFolderContent(const class QString &) Full path:  "/Documents"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "http://nextcloud.xxx.fr/remote.php/dav/files/jacky/Documents" has X-Request-ID "4dc72112-cf64-41a7-8a06-a408fc21c1ce"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "http://nextcloud.xxx.fr" + "/Documents" "OCC::DiscoverySingleDirectoryJob"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Erreur inconnue"
[OCC::LsColJob::finished 	LSCOL of QUrl("http://nextcloud.xxx.fr/remote.php/dav/files/jacky/Documents") FINISHED WITH STATUS "OK"
[OCC::Vfs_windows::contentsOfDirectoryAtPath 	class QStringList *__cdecl OCC::Vfs_windows::contentsOfDirectoryAtPath(class QString,class QMap<class QString,class QVariant> &)  paso1:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles"
[OCC::Vfs_windows::contentsOfDirectoryAtPath 	class QStringList *__cdecl OCC::Vfs_windows::contentsOfDirectoryAtPath(class QString,class QMap<class QString,class QVariant> &)  paso3:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles"
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.odt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/About.txt"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/Nextcloud Flyer.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::SyncWrapper::getRelativePath 	Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Local Path:  "C:/Users/Utilisateur/AppData/Roaming/Nextcloud/cachedFiles/Documents/User Data Manifesto.pdf"
[OCC::SyncWrapper::getRelativePath 	Folder Relative Path:  ""
[OCC::MirrorFindFiles 	long __cdecl OCC::MirrorFindFiles(const wchar_t *,int (__cdecl *)(struct _WIN32_FIND_DATAW *,struct _DOKAN_FILE_INFO *),struct _DOKAN_FILE_INFO *)  FileName:  "/Documents"
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  1048704
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  1048704
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  1048704
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  128
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  128
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  1179785
[OCC::Vfs_windows::instance 	class OCC::Vfs_windows *__cdecl OCC::Vfs_windows::instance(void)  instance:   OCC::Vfs_windows(0x868cfa0)
[OCC::Vfs_windows::instance 	class OCC::Vfs_windows *__cdecl OCC::Vfs_windows::instance(void)  instance:   OCC::Vfs_windows(0x868cfa0)
[OCC::MirrorCreateFile 	long __cdecl OCC::MirrorCreateFile(const wchar_t *,struct _DOKAN_IO_SECURITY_CONTEXT *,unsigned long,unsigned long,unsigned long,unsigned long,unsigned long,struct _DOKAN_FILE_INFO *)  OPEN_EXISTING FileName:  "\\Documents\\Nextcloud Flyer.pdf"  error:  0  creationDisposition:  3  DesiredAccess:  128`

**Comment by rodrigoscoelho** [comment]
the same here.

**Comment by Milokita** [comment]
encountered similar problems

**Comment by bjquinn** [comment]
Same, but with Win10 64 bit, Nextcloud 15.0.2.  I was able to read the default Nextcloud manual PDF, but not the default Photos.  If I upload a file, I can read that file, but it doesn't upload to the server.

**Comment by teknoprep** [comment]
same here

**Comment by warnerbryce** [comment]
You should test the new V2 version on the releases section. It should work now.

**Comment by claell** [comment]
Can somebody confirm this is no longer a problem with the current version? Seems like this can be closed then.

**Comment by warnerbryce** [comment]
Dev is in a dead point at this moment. 
@camilasan should tell us where the Virtual Drive is in the dev plan... 
🧐

**Comment by claell** [comment]
@warnerbryce That seems to be offtopic. My question was, whether this specific issue is still happening, so this can be closed.

**Comment by warnerbryce** [comment]
For some users this V2 works but others it still don’t work.

**Comment by claell** [comment]
Can you link a source where other users are stating that they have or don't have this issue with v2?

**Comment by warnerbryce** [comment]
This topic and a lot more on the help.nextcloud.com 
https://help.nextcloud.com/t/nextcloud-virtualdrive-techpreview-v2-tls-initialization-failed-error/60105?u=nemskiller
https://help.nextcloud.com/t/nextcloud-im-heimnetzwerk-ohne-sync-auf-jedem-client/69957?u=nemskiller

**Comment by claell** [comment]
> https://help.nextcloud.com/t/nextcloud-virtualdrive-techpreview-v2-tls-initialization-failed-error/60105?u=nemskiller

Is about authentication, this issue is about not being able to open files.

> https://help.nextcloud.com/t/nextcloud-im-heimnetzwerk-ohne-sync-auf-jedem-client/69957?u=nemskiller

This is not even about virtual drive.

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
