### ISSUE TITLE
Virtual drive fails to create/map if X: already exists

### ISSUE THREAD

**Issue by jonathonwiebe** [nextcloud/desktop#1058]
### Expected behaviour
Prompt to chose another letter or error if X: drive is already mapped to another location.

### Actual behaviour
Installer finishes and then mapping X: silently fails, opening Nextcloud app gives no options to chose a folder or driver letter, files do not sync, app window shows blank.

### Steps to reproduce
1. Map at network drive to X:
2. Install virtualdrive preview
3. Open nextcloud client window

### Client configuration
Client version:
2.5.0techpreview build 20190128
Operating system:
Windows 10 1803 x64
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
5.11.1

**Comment by camilasan** [comment]
We have changed our approach and now the virtual file system is set by syncing folder: https://help.nextcloud.com/t/help-test-our-desktop-client/
