### ISSUE TITLE
File won't sync with connection timed out after editing music file's metadata

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/desktop#1059]
### Expected behaviour
I can edit the file however I like and it still gets synced.

### Actual behaviour
Randomly it doesn't and I get a connection time out until I delete the file from the server.

![image](https://user-images.githubusercontent.com/1641362/52040527-009a0180-2538-11e9-8fcd-0b63073697e4.png)

### Steps to reproduce
1. Have some music (so far only happened with FLACs), use some editor (I used deadbeef) to edit metadata like album name.
2. Nextcloud will randomly refuse to work with some files. It seems to be a client error as I can't spot a server error in the logs

### Client configuration
Client version: 2.5.1 (git 2018-12-19)

Operating system: Arch Linux

OS language: en_US.UTF-8 UTF-8

Qt version used by client package (Linux only, see also Settings dialog):
Built from Git revision b37cbe on Dec 19 2018, 13:52:15 using Qt 5.12.0, OpenSSL 1.1.1a 20 Nov 2018

Client package (From Nextcloud or distro) (Linux only):
AUR (user repo)

Installation path of client:
Whatever the user repo uses

### Server configuration
Operating system: Arch Linux

Database: MariaDB

PHP version: 7.3.1

Nextcloud version: 7.3.1

Storage backend (external storage):
etx4, not external

### Logs

1. Client logfile: https://haste.rys.pw/raw/fuvitewoxi - I have two servers, cloud and cloud2. The cloud2 is the problematic one in the logs. (Although I was able to reproduce on the other server also)

2. Web server error log:
nginx, empty.

3. Server logfile: nextcloud log (data/nextcloud.log):

https://haste.rys.pw/ecutiyacuc.json

These 4 logs which may or may not be related to the problematic files.

**Comment by Temtaime** [comment]
Same here, happens when editing files, randomly.
No info in the server logs, seems to be trouble with the client ?

**Comment by G-Pereira** [comment]
Happening to me as well NC 16.0.3

**Comment by G-Pereira** [comment]
I don't want to delete the files since I have no backup. What should i do?

**Comment by Victor-Morel** [comment]
Same issue for me, with Nextcloud 16.0.3 and a Linux client 2.5.2.
After updating my metadata using picard MusicBrainz, I couldn't upload my music (.mp3 mainly).

What I did was to reupload everything in a separate folder, then to delete the initial one, but you need enough space on the server.

**Comment by danimayordm** [comment]
Same for me, is this problem happening with files larger than 10MB?
I have the same problem when editing Word files, but this only happens when I edit files larger than 10MB.
Any solution?

**Comment by jstdoit** [comment]
+1 same for me. windows 10 with  NC 2.6.1stable-build20191105

**Comment by DanWiseProgramming** [comment]
Please fix this - it is really annoying and renders the desktop application useless.

**Comment by 15110123** [comment]
Same issue. Happened to Powerpoint file as well. Please fix it anyone.

**Comment by dangmai** [comment]
I also run into this issue with the Nextcloud Desktop client, and I found that it mainly happens when the file is larger than the chunk size specified by the client. My workaround is to choose a bigger chunk size using the environment variable `OWNCLOUD_CHUNK_SIZE` as documented [here](https://docs.nextcloud.com/desktop/2.3/advancedusage.html#environment-variables). By default it is set to 5MB, and my FLAC files tend to be much bigger than that which leads to timeouts. I basically "disable" chunking by setting it to an arbitrarily large value (500MB), and my FLAC files are uploaded correctly now.

**Comment by 15110123** [comment]
@dangmai Wow. Your solution actually works! I used to have this issue when using Owncloud client before, and spending a whole day researching on Owncloud and Nextcloud forums didn't help much. Thank you! :D

**Comment by mburnicki** [comment]
> My workaround is to choose a bigger chunk size using the environment variable `OWNCLOUD_CHUNK_SIZE` as documented [here](https://docs.nextcloud.com/desktop/2.3/advancedusage.html#environment-variables). By default it is set to 5MB, and my FLAC files tend to be much bigger than that which leads to timeouts. I basically "disable" chunking by setting it to an arbitrarily large value (500MB), and my FLAC files are uploaded correctly now.

Thanks for the valuable hint. I've just setup a new Linux machine and re-used the data partition which had already been used by the previous Linux installation/NC client, i.e. all the files were already synchronized.

However, after I had configured the new, but previously existing connection, the client started to check files, showed lots of errors in the activities, and said it needed 4 days to re-synchronize to the server. :-(

After I had stopped the client and restarted it with OWNCLOUD_CHUNK_SIZE=500MB, the inital synchronization went without errors, and was finished after a couple of minutes. So this really helped.

**Comment by mburnicki** [comment]
> My workaround is to choose a bigger chunk size using the environment variable `OWNCLOUD_CHUNK_SIZE` as documented [here](https://docs.nextcloud.com/desktop/2.3/advancedusage.html#environment-variables).

That page also says that it should be possible to add the setting to the client's configuration file, and that this could be done using the **_Nextcloud configuration dialog_**.
However, I don't see where I can open this dialog. If I just open the settings for a connection, I don't see a way to edit this. Or is this option only available in certain client versions? I'm currently using 
client 2.5.3git, which is provided by my Linux Distribution (openSUSE 15.1).

**Comment by FlexW** [comment]
@C0rn3j  Does this issue still exist in the latest version (3.2.0 at the moment)?

**Comment by vohzd** [comment]
@FlexW Happens on Desktop 3.2.1 on Win10 still.

Synchronising ~5000 files with lots being >50GB
