### ISSUE TITLE
Context menu entry for public share link only available after 2 sync runs

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/desktop#1061]
* configure the desktop as a synced folder
* take a screenshot (that is saved on the desktop)
* let the desktop client sync the file (usually immediately)
* right click on the file and open the "Nextcloud" menu
* expected: there is an entry with "Copy public share link"
* actual: there is no such entry, but one with "Sharing not allowed for this file"
* if you wait until the next sync run is done (after 30 seconds or when you click "Sync this folder now" in the desktop client) then the entry is there

What it looks like:
<img width="748" alt="bildschirmfoto 2019-01-28 um 11 50 57" src="https://user-images.githubusercontent.com/245432/52062548-ff38fb00-2570-11e9-9c7e-13e40e37340e.png">

What it should looks like:
<img width="760" alt="bildschirmfoto 2019-01-31 um 15 56 49" src="https://user-images.githubusercontent.com/245432/52062523-f516fc80-2570-11e9-81e3-de9e50610b47.png">

@rullzer @camilasan Could you reproduce this on your system? Or is this macOS related?

**Comment by MorrisJobke** [comment]
> * configure the desktop as a synced folder

I just tested and it is the same for the root folder as well as sub folders.

**Comment by Peac** [comment]
I can confirm this on Ubuntu 18.04 with client version 2.5.1

I also confirm that this doesn't need a special folder. Just put a new file anywhere and the bug will occur.

**Comment by tobias-lambrecht** [comment]
If you enable the file sharing link before any sync has been finished as described in #14075 this would also solve this bug.

**Comment by biva** [comment]
Hello, I can't see this context menu (I don't see "Sharing not allowed for this file" either). I just see the context menu for private link :( Is it on a beta version?

Version: 2.5.2git (build 20190319) on Windows 10 64 bits
NC 15.0.7 on Debian 9.9 (stretch)

**Comment by biva** [comment]
Hello, am I the only one who doesn't see this context menu? Thanks for your support :)

**Comment by biva** [comment]
I see the context menu now, with 2.5.3
