### ISSUE TITLE
Share by mail creates broken link

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/desktop#1064]
### Expected behaviour

1. Open a file's contextmenu
2. Expand "Nextcloud"
3. Click on "[Send private link by email...](https://github.com/nextcloud/desktop/blob/ae7ad8fb4f900d40a084e68c05177f9770a587ce/translations/client_en.ts#L2861)"
4. Your default mailer opens and a shared link is already put in
### Actual behaviour

1. Open a file's contextmenu
2. Expand "Nextcloud"
3. Click on "[Send private link by email...](https://github.com/nextcloud/desktop/blob/ae7ad8fb4f900d40a084e68c05177f9770a587ce/translations/client_en.ts#L2861)"
4. Your default mailer opens and the **shared link is broken**
Link sounds: https://:444/index.php/f/12345

### Steps to reproduce
1. Map your Nextcloud on a different port than default HTTPS (443)
2. Try to share a link like I described

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system: Win10.1803

OS language: DE

Installation path of client: default

### Server configuration

Operating system: ubuntu server

Web server: nginx

Database: mysql

PHP version: 7.2.2

Nextcloud version: 15.0.2

### Logs
https://gist.github.com/Somebodyisnobody/4bd689cb685a99b80ac5dd5199a537ef

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by Somebodyisnobody** [comment]
Sorry, I have revised my infrastructure in the time ago and now use the port 443 😉. If you let the issue "rot" over two years here you can really not expect that I now try to reproduce it again. You should have come one and a half years ago...
