### ISSUE TITLE
v2.5.1 process continue to run in ram/process when nextcloud gui killed

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/desktop#1070]
OS win10pro.

When nextcloud app 2.5.1 is shutdown, process stay in ram, as active.
ex: if hdd read sync is launch, it will continue forever.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by stratege1401** [comment]
Sorry, no can do... Cause:
- client updated to latest, issue no more present.
