### ISSUE TITLE
HTTP/2 protocol error

### ISSUE THREAD

**Issue by mfeske** [nextcloud/desktop#1072]
### Expected behaviour
By Installing under Ubuntu theire is an error "HTTP/2 protocol error"

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. Download Nextcloud-2.5.1-x86_64.AppImage
2. start installation
3. url from server
4. choose folder 
5. start

### Client configuration
Client version:
2.5.1

Operating system:
Ubuntu
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by nem0nxt** [comment]
I have this issue too. Ubuntu 18.04.

**Comment by ohrie** [comment]
I have this issue too on Manjaro 18 via package manager installed.

**Comment by DCsunset** [comment]
Same issue too on Windows 10 using nextcloud client 2.5.1.

**Comment by ohrie** [comment]
Looks like it's not an Client problem. Same with 2.5.0. Since I've upgraded to Server Version 15.0.5 I have this error. Before that with 15.0.2 everything was ok.

**Comment by enoch85** [comment]
I can reproduce this error on a fresh installation with the Nextcloud VM scripts. 

Nextcloud version 15.0.7
Client 2.5.2

This is the configuration in question:
```
# Enable HTTP/2 server wide
print_text_in_color "$ICyan" "Enabling HTTP/2 server wide..."
cat << HTTP2_ENABLE > "$HTTP2_CONF"
<IfModule http2_module>
    Protocols h2 h2c http/1.1
    H2Direct on
</IfModule>
HTTP2_ENABLE
print_text_in_color "$IGreen" "$HTTP2_CONF was successfully created"
a2enmod http2
restart_webserver
```

**Comment by xianx** [comment]
I cannot also sync files for this bug. Please fix it. Owncloud fixed it from their latest client https://techtun.es/drFf5W and nextcloud is overlooking it.

**Comment by bityoda** [comment]
Same for me it's annoying.

**Comment by tflidd** [comment]
> I cannot also sync files for this bug. Please fix it. Owncloud fixed it from their latest client https://techtun.es/drFf5W and nextcloud is overlooking it.

It would be better to link the specific github issue and pull request. I only found this one:
https://github.com/owncloud/client/pull/6353
but it is already backported to Nextcloud:
https://github.com/nextcloud/desktop/commit/e82869d10e2b5d06932799453b591916b5be6f73

There were other issues with configuration problems. This command turned out to be helpful if the server is responding correctly:

`curl --head --http2 https://<my_server/`

It should give a `HTTP/2 200` status and shouldn't throw an error.

**Comment by enoch85** [comment]
> It should give a HTTP/2 200 status and shouldn't throw an error.

In my case both my domains that are having issues throws `HTTP/2 200`, an they are still having issues with the client. Using the latest and the greatest of course.

**Comment by Lars1963** [comment]
I do encounter the same problem with client 2.5.3 RC2 on Windows 10 Pro.
As far I could find, it mainly happens with jpg an png files >1 MB

**Comment by Lars1963** [comment]
@camilasan Could this be related to / same issue as https://github.com/owncloud/client/issues/7020 ?

**Comment by enoch85** [comment]
I think this can be closed casue I think I found the cause. 

Everyone that have files_antivirus enabled, raise your hand. :raised_hand_with_fingers_splayed: 

I noticed that `clamav` was really heavy on my CPU when I uploaded files in the client and I also had plenty of issues with HTTP/2 protocol error, so I thought, "wonder what happens if I disable the `files_antivirus` app?" 

Well, **no more issues**, and the syncing got much faster.

**Comment by Lars1963** [comment]
You might have a point there: I also have `files_antivirus` active, allthough my machine has more then anough cpu- and ram-power. It really shouldn't be a problem. 

Question remains also, if the desktopclient or the files_antivirus app have a problem in combination which each other.

**Comment by enoch85** [comment]
> allthough my machine has more then enough cpu- and ram-power. It really shouldn't be a problem.

I ran this test on a [pretty decent Xeon CPU](https://www.cpubenchmark.net/cpu.php?cpu=Intel+Xeon+E5-2690+v2+%40+3.00GHz&id=2057) with 12 cores added to the system, so I think that doesn't matter, rather the files_antivirus app that have some flawed code. My best guess anyway.

**Comment by enoch85** [comment]
@Lars1963 

Pretty funny that your avatar raises the hand btw. :D 

> Everyone that have the app files_antivirus enabled, raise your hand.

**Comment by Lars1963** [comment]
I raised a issue on https://github.com/nextcloud/files_antivirus. May be someone over there has a idea.

**Comment by enoch85** [comment]
I'm closing this as it's most probably are related to the `files_antivirus` app or clamav. 

Please reopen if you experience issues not related to the above.

**Comment by xianx** [comment]
This is not antivirus issue. Nexcloud Client throw error when HTTPS/2 is enabled on server. Where antivirus came to this issue? I dont understand. Its related to HTTPS/2 support on Nextcloud Desktop Client.

**Comment by enoch85** [comment]
@xianx so you are not running `files_antivirus`?

**Comment by xianx** [comment]
@enoch85 nope.

**Comment by xianx** [comment]
On owncloud https://techtun.es/GeykDW they removed it https://techtun.es/OwBBvw

**Comment by acs-ferreira** [comment]
Subsidiary question, any of you are using nGinx as HTTP server?
In my case, im' using nGinx and not having that problem.

**Comment by Lars1963** [comment]
Yes, I'm using NGINX and having this problem. Only solution for now is disabling http2-support for NGINX. This problem is also otherwise mentioned in combination with NGINX.

**Comment by enoch85** [comment]
@acs-ferreira I use Nginx as Reverse Proxy, and HTTP/2 is enabled on both sides.

**Comment by acs-ferreira** [comment]
OK, so this is not Webserver related. I'm also using `files_antivirus` app (ClamAV daemon not on the same server) and i can't reproduce...

**Comment by felinira** [comment]
I have this error too, no files_antivirus app and protocol error. Is there anything I can check to find out more? Server logs don't say anything...

**Comment by kibrovic** [comment]
Having the same issue on multiple devices:

OS: Debian 10 and Windows 10

Nextcloud version 2.5.1git
Using Qt 5.11.3, built against Qt 5.11.3
Using 'OpenSSL 1.1.1d  10 Sep 2019'

Windows is using 2.6.0

Server: nginx

For now, I'm downgrading to **2.3.3** which doesn't cause this problem.

Log on [gist](https://gist.github.com/kibrovic/d7836102e6b31734104c5605bf3c4dcb#file-http2_protocol_error-log)

File names replaced with FILE1,2,3. Problematic file is **FILE1**. I didn't include rest of the files throwing error (log show same thing).

It seems that problem is [Qt http2 stack](https://bugreports.qt.io/browse/QTBUG-73947). [OwnCloud disabled it](https://github.com/owncloud/client/releases/tag/v2.5.4)

**Comment by MacLemon** [comment]
Same problem started popping up here recently.

## Server
- Nextcloud 16.0.4, 16.0.5, 17.0.1
- OS: FreeBSD 12.0
- nginx 1.17.6
- PHP 7.2.24
- HTTP/2 enabled

## Nextcloud Client
- macOS 10.12.16 (High Sierra)
- NextCloud app 2.6.0, 2.6.1

## Verififed Workaround
- Downgrade to NextCloud Client 2.5.3release (build 20190724) without making any changes to the server setup. (Works fine with HTTP/S and Nextcloud 17.0.1)

**Comment by phonon112358** [comment]
Same issue here... 
I use the Windows client (Version 2.6.2stable-Win64 (build 20191224)).
On my server, I have Debian 10, nginx 1.14.2, php 7.3, nextcloud 17.0.2.

To me, it seems that only some file formats aren't synchronised (e.g. .jpg), but others work (e.g. .pdf, .doc, .odt)... can you confirm? 

As workaround, I disabled http2 in my nginx configuration for now. Everything works fine now.
However, I hope that this issue will be resolved soon!!!

**Comment by daPhipz** [comment]
The workaround to use 2.5.3release did not work for me unfortunately, but I saw there is a new 2.7.0beta1 released just some days ago. It does work for me!
I use the AppImage and run Manjaro Linux with KDE.

**Comment by lucker999** [comment]
I can confirm that for some file extensions (for instance .sh) the windows client (Version 2.6.2stable-Win64 (build 20191224)) refuses to sync with server Nextcloud 18.0 on OS: FreeBSD 12.1-p2, PHP 7.3 with http2 enabled.

Also confirm that downgrading to 2.5.3daily-Win64 (build 20190725) completely eliminated the problem.

**Comment by EugenVau** [comment]
![image](https://user-images.githubusercontent.com/13468459/73834738-8e27c580-480c-11ea-9278-4c7e18833a84.png)
😱

**Comment by misch7** [comment]
> Also confirm that downgrading to 2.5.3daily-Win64 (build 20190725) completely eliminated the problem.

With #1823 in the 2.6.4 release HTTP/2 will be disabled by default for now and may be enabled manually by supplying the environment variable: `OWNCLOUD_HTTP2_ENABLED=1`
