### ISSUE TITLE
High CPU usage after wake from sleep with no connection

### ISSUE THREAD

**Issue by mrmotallebi** [nextcloud/desktop#1075]
### Expected behaviour
~0% CPU

### Actual behaviour
100% CPU on one core (thread)

### Steps to reproduce
1. Let NC sync completely
2. Let PC go to sleep while connected to internet
3. Disconnect internet connection before waking up

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system: Win 7 (64-bit)

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\

### Logs

Nothing unusual in logs. Nothing logged before and after sleep.

```
#=#=#=#=# Propagation starts 2019-02-06T12:26:46Z (last step: 789 msec, total: 789 msec)
#=#=#=# Syncrun finished 2019-02-06T12:26:46Z (last step: 22 msec, total: 812 msec)
#=#=#=# Syncrun started 2019-02-06T14:57:35Z
#=#=#=# Syncrun finished 2019-02-06T14:57:36Z (last step: 720 msec, total: 720 msec)
#=#=#=# Syncrun started 2019-02-06T14:57:50Z
#=#=#=# Syncrun finished 2019-02-06T14:57:51Z (last step: 724 msec, total: 724 msec)
#=#=#=# Syncrun started 2019-02-06T14:58:55Z
#=#=#=# Syncrun finished 2019-02-06T14:58:56Z (last step: 695 msec, total: 695 msec
```

**Comment by faulix** [comment]
Did you wait for some time to see whether it goes back to regular CPU usage?

There are also others having cpu issues: https://github.com/nextcloud/desktop/issues/942

**Comment by mrmotallebi** [comment]
The problem didn't solve with time (gave it more than 10 mins) , but after reconnecting to the network, the CPU usage dropped again (to ~0%).

Meanwhile, before reconnecting to the network it shows an error icon in the taskbar with the last three errors in the activity tab being: "Host unreachable" or "Host not found".

Looks like there's an uncontrolled while loop in the code trying to check if the server's online.

**Comment by toweih** [comment]
duplicate?
https://github.com/nextcloud/desktop/issues/942

**Comment by mrmotallebi** [comment]
Closing since it's for older versions.
