### ISSUE TITLE
Unable to sync .textClipping files under MacOS

### ISSUE THREAD

**Issue by phaus** [nextcloud/desktop#1076]
### Expected behaviour

* A `.textClipping` file is within a directory that is sync by the latest sync client (Version Version 2.5.1final (build 20181204)).
* The sync client shows an error 500 from the server - so maybe it might als a server issue, but my assumption is, that the clients uses posix methods to determine the file size (which is 0). 
Also see [Getting the contents of a textClipping file ](https://discussions.apple.com/thread/1446074).
* The file is not copied to the server. It will be set to zero bytes, if I force a client resync.

### Actual behaviour

* A `.textClipping` file is within a directory that is sync by the latest sync client (Version Version 2.5.1final (build 20181204)).
* The client syncs the file to the server, where it is saves as a text representation + resource-metadata.
* The Client is able to recreate a `.textClipping` file wen syncing the file back to another desktop.

### Steps to reproduce

1. Extracting [Steps to reproduce.textClipping.zip](https://github.com/nextcloud/desktop/files/2847308/Steps.to.reproduce.textClipping.zip) to a folder.
2. Create a folder sync with the desktop sync client

### Client configuration
Client version: (Version Version 2.5.1final (build 20181204))

Operating system: MacOS 10.14.3

OS language: German

Installation path of client:
/Applications/nextcloud.app

### Server configuration

Operating system:
4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

Web server:
nginx                             1.15.8-1~stretch

Database:
mysql                            1:10.3.12+maria~stretch

PHP version:
php                               7.3.1-1+0~20190113101756.25+stretch~1.gbp15aaa9

Nextcloud version:
15.0.4

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```
{
  "reqId": "iLRBc8ARSy3EBf6S8HsN",
  "level": 3,
  "time": "2019-02-09T00:59:09+01:00",
  "remoteAddr": "…",
  "user": "philipp",
  "app": "no app in context",
  "method": "PUT",
  "url": "/remote.php/webdav/Desktop/txt/Product%20Key%20fu%CC%88r%20Datacent.textClipping",
  "message": {
    "Exception": "Sabre\\DAV\\Exception",
    "Message": "Error while copying file to target location (copied bytes: 0, expected filesize: 0 )",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 156,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1096,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "Product Key für Datacent.textClipping",
          null
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 525,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "Desktop/txt/Product Key für Datacent.textClipping",
          null,
          null
        ]
      },
      {
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://cloud.consolving.de/remote.php/webdav/Desktop/txt/Product%20Key%20fu%CC%88r%20Datacent.textClipping",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpPut"
          ],
          [
            {
              "absoluteUrl": "https://cloud.consolving.de/remote.php/webdav/Desktop/txt/Product%20Key%20fu%CC%88r%20Datacent.textClipping",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "absoluteUrl": "https://cloud.consolving.de/remote.php/webdav/Desktop/txt/Product%20Key%20fu%CC%88r%20Datacent.textClipping",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://cloud.consolving.de/remote.php/webdav/Desktop/txt/Product%20Key%20fu%CC%88r%20Datacent.textClipping",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php",
        "line": 80,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 163,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
    "Line": 191,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0",
  "version": "15.0.4.0"
}
```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
If I understand correct, `.textClipping` files are special to macOS? We try to not synchronise any files that are platform specific because it is too complicated. We probably should add this filename to the ignore list.
