### ISSUE TITLE
Nextcloud does not automatically login on Arch/KDE.

### ISSUE THREAD

**Issue by null-von-sushi** [nextcloud/desktop#1077]
### Expected behaviour
Nextcloud should log in on application startup after having logged in previously.

### Actual behaviour
Nextcloud desktop always opens the "You have been logged out of user@example.com. Please login again" window/website which asks me to log in before "granting Mozilla/5.0 (Linux) mirall/2.5.1git (Nextcloud) access to your user account". To use Nextcloud desktop I then have to manually log in again.

### Steps to reproduce
1. Login to Nextcloud, set up client.
2. Quit Nextcloud Desktop and restart it
3. Be annoyed by login prompt :)

### Client configuration
Client version:
`2.5.1git` (package name on Arch is `nextcloud-client` w. version `2.5.1-2`)

Operating system:
Arch Linux

OS language:
English. Either US or UK, cannot remember sorry. 

Qt version used by client package (Linux only, see also Settings dialog):
5.12.1

Client package (From Nextcloud or distro) (Linux only):
From community repository on Arch, however Nextcloud Desktop says "This release was supplied by Nextcloud GmbH" in the settings.

Installation path of client:
Binary is at `/usr/bin/nextcloud`
A bunch more files (internationalization files I think) are at `/usr/share/nextcloud`
.so files are in `/usr/lib/nextcloud/`

### Server configuration

Operating system: CentOS

Web server: nginx

Database: mariadb

PHP version: Very sorry, but no idea. CentOS packages are kind of a mess. I am just glad it works. I think it's php version 70?

Nextcloud version:
Not sure where to find this sorry. It's somewhat recent though.

Storage backend (external storage): Yes

### Logs
Not sure what logs apply here, I do not think that this is a server issue as it works on my laptop (also Arch-based Linux)

**Comment by baez90** [comment]
Which DE are you using?

I had the same problem.
When I started the client from a terminal like this: `nextcloud --logwindow` I noticed that the application fails to fetch the credentials to contact the NextCloud server.
A few Google calls later I recognized that I had no keyring daemon running in my i3wm setup.
I installed the `gnome-keyring` package like described [here](https://wiki.archlinux.org/index.php/GNOME/Keyring) and I configured it to auto start after login (neither with pam nor with xinitrc because I was too lazy to do that, I just added an entry to my i3 config).

Now it works like a charm :wink:

**Comment by null-von-sushi** [comment]
I use KDE. I did disable kwallet though since it's useless to me (I have Full Disk Encryption and use KeepassXC for passwords), but I didn't consider that it may be a keyring issue since I did the same on my laptop and that still works fine. That said, I have gnome-keyring still installed from back when I was using GNOME, which is probably why it works. 

Either way, installing gnome-keyring, starting it's daemon and then retrying did indeed make Nextcloud work as expected. Thanks a lot!

**Comment by Iolaum** [comment]
I had the same problem when I was running Fedora 30. It is based on the GNOME DE but I don't know if it has the `gnome-keyring` package. I 've since moved to Fedora MATE 30 which does have that package installed and did not have the same problem.
