### ISSUE TITLE
Nextcloud client is trying to connect to owncloud server to check status

### ISSUE THREAD

**Issue by facundobatista** [nextcloud/desktop#1078]
First installation of the client, tried to use. Can't use it at all, as the first thing it does is to try to check the status of the server, and fails.

When it starts, it says "Connect to Nextcloud" and there is a text entry labeled "Server Address", where I put `http://fantomix/` (this is a machine in my LAN, where the server is running).

### Expected behaviour
It should try to get the status from `http://fantomix/nextcloud/status.php` (which I tried in a browser and returns the proper info)

### Actual behaviour
It tries to get the status from `http://fantomix/owncloud/status.php`, which doesn't exist

### Steps to reproduce
1. Start client 
2. Put `http://fantomix/` in "Server Address" text entry

### Client configuration
Client version: 2.3.3+gitab40efe

Operating system: KDE Neon on Ubuntu Bionic

OS language: Spanish

Qt version used by client package (Linux only, see also Settings dialog): unknown, as it's a snap

Client package (From Nextcloud or distro) (Linux only): installed from stable channel  (`snap install nextcloud-client`)

Installation path of client: /snap/nextcloud-client/

Full result from `nextcloud-client --logfile log.txt`: 

```
02-10 20:15:32:655 21914 OCC::Application::setupLogging: "################## Nextcloud es_AR (es_AR) 2.3.3 on Ubuntu Core 16"
02-10 20:15:32:655 21914 OCC::Application::slotParseMessage: Running for 849.284 sec
02-10 20:15:32:655 21914 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
```

**Comment by lucode** [comment]
Not sure if this is retated to this bug: https://help.nextcloud.com/t/issue-login-in-with-the-desktop-client-when-using-sso-saml-with-keycloak/47063/3

**Comment by facundobatista** [comment]
I don't think it relates to any kind of login problem, as what happens to me is before any authentication (it's the first thing the desktop gui does, I don't get to put any user/password...)

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists? Please keep in mind that it is not supported to use the Nextcloud client with the ownCloud server.

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
