### ISSUE TITLE
Ignore directories based on path

### ISSUE THREAD

**Issue by ustervbo** [nextcloud/desktop#1082]
I would like to be able to exclude some sub-directories from synchronization, but include others with the same name. A similar problem was posted at https://help.nextcloud.com/t/specific-folder-in-ignore-list/33761

### Expected behaviour
The pattern 'packrat/lib/' should exclude the directory lib in and only if it is a sub-directory of packrat. All other 'lib' directories should be synchronized.

### Actual behaviour
Nothing is ignored. 

### Steps to reproduce
1. Add a path pattern to sync-exclude.lst
2. Sync

### Client configuration
Client version:
Nextcloud version 2.5.1git

Operating system:
Kubuntu 18.04

OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
Qt version 5.6.2

Client package (From Nextcloud or distro) (Linux only):
Nextcloud

Installation path of client:
/usr/lib/x86_64-linux-gnu/nextcloud

**Comment by GieltjE** [comment]
It would be nice to have some better documentation to, e.g. how to exclude a specific file (including full path).

**Comment by ustervbo** [comment]
As far as I understand the documentation, `fnmatch` is used to check for exclusion - and thereby ignoring all paths (`fnmatch` is just for file names).

`glob` on the other hand also takes paths into consideration. Maybe the solution is as simple as that.

**Comment by dodancs** [comment]
I would also like to have a single workspace folder with all of my configurations for different SFTP and other hosts, without any other files being synced. The folder structure is something like this:

Root: Workspaces
- Host 1
  - .vscode: here are some settings files, which I wish to sync
  - bin
  - etc
  - home
  - lib
  - mnt
  - root
  - tmp
  - ...

I only want to sync .vscode folder, excluding all the other folders and files in each host's folder. This would allow me to just open VSCode and open the workspace folder, and each of my PCs would have their own "cache" of the host's files, but the "cache" would not be synced.

**Comment by ledufakademy** [comment]
same issue here , why Nextcloud client do not allow sync with  .vscode folder ? (i'm using Visual studio code)
this is  very strange, isn't it ?

**Comment by QazCetelic** [comment]
> As far as I understand the documentation, `fnmatch` is used to check for exclusion - and thereby ignoring all paths (`fnmatch` is just for file names).
> 
> `glob` on the other hand also takes paths into consideration. Maybe the solution is as simple as that.

It seems like `fnmatch` hasn't been used since 5 years ago because of a difference in behavior on Windows. 585d2b20bdc5dcdb76c696b4e0306ddd3ce19329. I'm unable to find a single file where `fnmatch` is used with GitHub search.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
