### ISSUE TITLE
Remove inability to add folder sync connection when syncing root

### ISSUE THREAD

**Issue by plinss** [nextcloud/desktop#109]
Currently when adding a folder sync connection you get a warning "You are already syncing all your files." if there is an existing sync connection to the server root and the "Continue" button is disabled. 

Please remove this restriction. Firstly, there are valid use cases for having a sync connection to the root along with other sync connections, e.g. a single "default" sync folder, and project specific sync folders that need to be placed in other locations (and file system links are undesirable).

Secondly, the user can already work around this restriction by removing the root sync connection, adding the sub-folder sync connection, and then re-adding the root sync connection. The user then needs to remember which sub-folders have been excluded form the root sync, which is a pain.

If there is a valid implementation reason to prevent syncing folders to multiple locations, then at least allow adding folder sync connections to sub-folders that are already excluded from the root (or other) sync (or have the addition of the new sync folder disable that folder in the other sync).

**Comment by jacobandersen** [comment]
Constantly banging my head against the table because of this problem. I would definitely vote for this issue — it is a stupid restriction, and the workaround is annoying and unnecessarily time consuming.

**Comment by justyns** [comment]
I've been running into this a lot lately as well.  I have my root folder (excluding one directory) synced to a Nextcloud directory one drive, but then I also have a Backups directory that I sync from a different bigger drive.
I was able to use the workaround @plinss mentioned, but it isn't ideal for new users.  My vote would be for either an option in the settings "Allow folder sync connections in addition to root folder sync" or to not disable the button and just give the user a warning instead.

**Comment by mschoenebeck** [comment]
Same here! I'm syncing my entire home folder between different machines using Nextcloud. Works awesome. But adding specific sync connections for shared folders or something inside my home folder is not possible anymore because of the root sync.. That's sad. Having the option for multiple sync connections would be great!

**Comment by plinss** [comment]
Can confirm this is no longer an issue in the current release.
