### ISSUE TITLE
Bug for Linux in ignored files/folders

### ISSUE THREAD

**Issue by Arvi89** [nextcloud/desktop#1093]
### Expected behaviour
On my windows laptop, I've set some ignore rule like "*/vendor" so my php projects don't sync the vendor folder (did the same with cache and log). But, on my laptop with Ubuntu, it still syncs my data.

### Actual behaviour
It should not sync the folder.

### Steps to reproduce
1. Set a ignore pattern with "*/vendor"
2. Create a folder, inside create a vendor folder, then put something in it
3. It will be synced to your cloud

### Client configuration
Client version: 2.5.1

Operating system:
Ubuntu 18.0.4

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
(Not having the laptop with me now, will update later)

Client package (From Nextcloud or distro) (Linux only):
Downloaded with the ppa repository.

Installation path of client:

**Comment by camilasan** [comment]
Hi, I couldn't reproduce it. i just tried with the latest version and it worked for me.
Could you try our rc? https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.2.20190205-rc1-x86_64.AppImage
Thanks
