### ISSUE TITLE
Virtualdrive not working with Dockers cert

### ISSUE THREAD

**Issue by slayerbrk** [nextcloud/desktop#1095]
### Expected behavior
Login screen appears on the first load

### Actual behavior
Screen show
"This site can’t be reached
The webpage at https://192.168.1.3/index.php/login/flow might be temporarily down or it may have moved permanently to a new web address.
ERR_CERT_AUTHORITY_INVALID"

### Steps to reproduce
1.install unraid docker image of next cloud
2.try to initiate virtual drive beta

### Client configuration

Operating system: Windows 10

OS language: English

### Server configuration

Operating system: Unraid

Nextcloud version: 15.0.2

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
