### ISSUE TITLE
Download bandwidth limit is ignored in Windows client

### ISSUE THREAD

**Issue by Showmaster3000** [nextcloud/desktop#1096]
### Expected behaviour
Limit the download bandwidth using the value set in network > download bandwidth

### Actual behaviour
setting of download bandwidth is ignored, full available bandwidth is used
in my tests I tried different values (400 KB/s, 350, 200), max. connection bandwidth around 680 KB/s
tried to set value before starting sync, but no difference to set/change it during sync

### Steps to reproduce
1. set download bandwidth in network settings to value below max. of internet connection
2. sync remote folder with local one containg f.e. a large file
3. look at download rate during syncronisation of the internet connection (f.e. using router monitor)

### Client configuration
Client version: 2.5.1 and 2.5.2.5117 rc1 (uninstalled old version during upgrade to rc1)

Operating system: Windows 7 Prof. x64

OS language: german

### Server configuration

Operating system: Ubuntu 14.04

Web server: Apache 2.2

Database: MySQL 5.5.62

PHP version: 7.2.15

Nextcloud version: Nextcloud 15.0.2

**Comment by phpdrill** [comment]
I can confirm that the download width limit does not work 100 %.

From my tests,
the download speed takes some time to adapt (up to 50 secs, when changing from 50 to 200 KBytes/s),
but then settles around the limit.

Perhaps we can speed up the adaption process a little bit?

**Comment by bernd-wechner** [comment]
I have just tried to throttle mine to 1kByte/sec up and down (a trickle) and can see Nextcloud's client using 10kBytes+/sec on the resource monitor. Not really satisfactory.

I'm using Windows 10 and its Resource Monitor to watch it.

If I pause synchronization it continues at 10+ kBytes/sec for a while then steadies to under 100 Bytes/sec ... which seems to be what dropbox, and onedrive are doing as well. Presumably some pulse of life signal given I have synchronization paused.
