### ISSUE TITLE
Starting and stopping an unrelated Docker container, opens and closes Nextcloud Client

### ISSUE THREAD

**Issue by SeaDude** [nextcloud/desktop#11]
I know it sounds weird but here is the scenario: 

* Nextcloud Client v2.3.2. Freshly installed on my machine. Never connected. Currently closed.
* Docker v17.09.0-ce, build afdb6d4. Freshly installed on my machine. 
* `sudo docker pull ubuntu`
* `docker run -it ubuntu:latest /bin/bash` and NEXTCLOUD CLIENT OPENS! on my machine!!
* Close Nextcloud Client on my machine.
* Commit something simple to docker instance: `sudo docker commit -m "added hello wizzle" romantic\_bartik hello\_wizzle`
* `exit` in container terminal
* NEXTCLOUD CLIENT OPENS AGAIN! on my machine.

Not sure what this means at all because i'm just learning. But thought it warranted an issue report for those in the know.

**Comment by camilasan** [comment]
Afaik it looks weird. Do you still have this problem?

**Comment by rullzer** [comment]
I can't see how this is related to the client.
