### ISSUE TITLE
Syncing files fails with connection closed - Client versions 2.5.x

### ISSUE THREAD

**Issue by nonamedotc** [nextcloud/desktop#1101]
**Problem description**

I have a local nextcloud server running the latest stable version (15.0.4 as of Feb 17, 2019) on RHEL 7.6. This server does not have end-to-end encryption enabled. Runs on apache.

Everything works perfectly as far as client 2.3.3 goes. However, with 2.5.x, I can no longer sync large files. Nothing has changed on the server side. The EXACT same files can sync just fine with **client 2.3.3** but **not with 2.5.x.**

I only have linux systems (Fedora 29) and I have tried client packages provided by both Fedora repos and appimage from nextcloud.com client download page.

Running the client using

> nextcloud --logdir ~/nclogs

I got the following in the logs,

```php
    |[OCC::PUTFileJob::finished |PUT of "https://local.nextcloud.site/nextcloud/remote.php/dav/uploads/testuser/3117544601/00000003" FINISHED WITH STATUS "RemoteHostClosedError Connection closed" QVariant(Invalid) QVariant(Invalid)|
    |---|---|
    |[OCC::PropagateItemJob::done |Could not complete propagation of "largefiles/120mb.txt" by OCC::PropagateUploadFileNG(0x55d7a71c9ea0) with status 2 and error: "Connection closed"|
    |[OCC::ActivityWidget::slotItemCompleted |Item  "largefiles/120mb.txt"  retrieved resulted in  "Connection closed"|
    |[OCC::ActivityWidget::slotItemCompleted |Item  "largefiles/120mb.txt"  retrieved resulted in error  "Connection closed"|
    |[OCC::ActivityListModel::addErrorToActivityList |Error successfully added to the notification list:  "Connection closed"|
```

A related issue filed earlier is now closed as OP's server config problem -https://github.com/nextcloud/desktop/issues/966

Any suggestions on how to fix this?

I have since tried setting up my server with PHP-FPM. No change in behavior. Client version 2.3.3 works, 2.5.x does not work.

### Expected behaviour
Files should sync without problems

### Actual behaviour
Tell us what happens instead

### Client configuration
Client version:
2.5.x

Operating system:
Linux

Client package (From Nextcloud or distro) (Linux only):
Appimage from nextcloud.com

Fedora 29+

**Comment by nonamedotc** [comment]
Update: I can manually upload a "large" file using the web interface. Only the client seems to fail.

Client downloads the uploaded file without any issues.

**Comment by patgrosse** [comment]
I have the same problem. Did you find a solution @nonamedotc ?
I use the latest Docker image (nextcloud:apache, 3624348a30042a34950fdc4ecd4b3682f6b0fca3b004dac1418b64fc2c9910c6) behind a reverse proxy. My clients run on Fedora 30 and Windows 10, both show the same behavior. Everything was fine a few month ago and I think I haven't changed a thing in the configuration since then.

**Comment by robfuscator** [comment]
I can confirm this problem, got the same issue on Arch Linux. Smaller files like text files are usually not a problem, but uploading stuff like audio files fails with _Connection Closed_.

Client: 2.5.2 (2.3 works)
Server: Docker (nextcloud:production-apache)

I suggest reopening this issue.

**Comment by patgrosse** [comment]
I managed to pin down the problem to the reverse proxy. I don't know what nextcloud changed in the desktop client, maybe they increased the chunk size or something related to it.

I'm using an apache as reverse proxy and fixed the problem by increasing the timeout. Settings in the `ProxyPass` directive and a change to `Timeout` did not help, instead I used the `mod_reqtimeout` module with the following setting:

`RequestReadTimeout handshake=5 header=10 body=30,MinRate=1000`

Values are chosen more or less randomly by trial and error.

**Comment by Snuggle** [comment]
I'm having this issue with Nginx and can't seem to fix it. 😦

**Comment by robfuscator** [comment]
The workaround suggested by @patgrosse works for me - maybe there's something similar available on nginx?

**Comment by Mustangman1966** [comment]
I'm having this issue with Nextcloud Snap on my Ubuntuserver 18.4.3 and can't seem to fix it.

**Comment by tobiasmuecksch** [comment]
I'm having the same issue with Traefik. Any solutions?

**Comment by Mustangman1966** [comment]
I have a work around, but you need a VPN. 
When you use a VPN the connection will work.

**Comment by jcastro** [comment]
Same problem here

**Comment by Tokukarin** [comment]
I had the same problem, I used Cloudflare, had to switch back to my reverse proxy (nginx).

And for prople searching how to fix it on nginx, this is it:
proxy_read_timeout 310s;

**Comment by mlopezcoria** [comment]
I have the same problem using nginx as reverse proxy (nginx proxy manager). I read that one should add `proxy_read_timeout 310s;` to nginx configuration but I don't know where to put it. I tried adding it in Advanced tab in Edit Proxy Host options but it didn't work.
