### ISSUE TITLE
Windows 10: add support for HTTP/2

### ISSUE THREAD

**Issue by j-ed** [nextcloud/desktop#1103]
## Expected behavior
The desktop client should establish a HTTP/2.0 connection if it is supported by the server.

## Current behavior
The desktop client sticks to HTTP/1.1 although the server supports HTTP/2.0.

### Steps to reproduce
1. Use the desktop client and check the server log.

## Log entries
 Here are some log messages from the servers log file which unterpin it:
```
... "PROPFIND /remote.php/dav/files/<user>/ HTTP/1.1" 207 435 "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)" 1586 1465
... "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)" 1408 449
... "GET /ocs/v2.php/cloud/activity?start=0&count=100&format=json HTTP/1.1" 200 20373 "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)" 1383 21374
```
#### Server Configuration
OS: Linux 3.16.62
Web server: Apache2 2.4.37
Database: MariaDB 10.2.21
PHP version: 7.2.14
Nextcloud version: 15.0.4

#### Client Configuration
Nextcloud app version: 2.5.1final (build 20181204)
Operating system: Windows 10 Pro (German)

**Comment by mgallien** [comment]
This is already done but conditioned by the environment variable `OWNCLOUD_HTTP2_ENABLED` being equal to `1`.
Please ensure you do not get errors after enabling it as it is not a `default` configuration and there may be some issues.
