### ISSUE TITLE
nextcloud-client v. 

### ISSUE THREAD

**Issue by heis2201** [nextcloud/desktop#1106]
### Expected behaviour
nextcloud-client usually starts when I login to my Gnome on Fedora and automatically connects to two hosts that my client is set up with. This used to work fine until recently.

### Actual behaviour
nextcloud-client does not establish a connection with either of the two servers

(I will be attaching a screenshot of some server error message below. Not sure this is relevant and/or related to the client issue.)

### Steps to reproduce
1. Reboot Fedora
2. Login
3. See nextcloud-client

### Client configuration
Client version:
Nextcloud version 2.5.1git
Git revision b37cbea5cc12b01d9baa0e36a996c873acdeea00
Using Qt 5.11.3, built against Qt 5.11.3
Using 'OpenSSL 1.1.1a FIPS  20 Nov 2018'

Operating system:
Fedora 29

OS language:
english/german

Qt version used by client package (Linux only, see also Settings dialog):
5.11.3

Client package (From Nextcloud or distro) (Linux only):
from distro repo

Installation path of client:
/usr/bin/nextcloud
/usr/bin/nextcloudcmd
/usr/lib/.build-id
/usr/lib/.build-id/08
/usr/lib/.build-id/08/2932cb9fb95b9601323b15ea97ee9e6555390
/usr/lib/.build-id/14
/usr/lib/.build-id/14/b4e4722394bdc5481c8ecb8d5566305bd4399e
/usr/share/appdata/nextcloud.appdata.xml
/usr/share/applications/nextcloud.desktop

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:
Nextcloud 15.0.4

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

![nextcloud15_error](https://user-images.githubusercontent.com/17801574/53199162-a19f4800-361e-11e9-8598-5b05e31a8bf1.jpg)

.

**Comment by camilasan** [comment]
Hi @heis2201 ! Do you have any client logs?

**Comment by heis2201** [comment]
Hi Camila, yes, I do. Is there a way to submit them to you without posting them publicly?

**Comment by heis2201** [comment]
Here is some anonymized log. Thanks for taking a look!

```
[OCC::ConnectionValidator::slotStatusFound 	** Application: ownCloud found:  QUrl("https://x.next-cloud.org")  with version  "15.0.4" ( "15.0.4.0" )
[OCC::ConnectionValidator::setAndCheckServerVersion 	QUrl("https://x.next-cloud.org") has server version "15.0.4.0"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://x.next-cloud.org/remote.php/webdav/" has X-Request-ID "be5bc27c-a3ec-4817-8027-e58ae671a1ce"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://x.next-cloud.org" + "/" "OCC::ConnectionValidator"
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication" QVariant(int, 401)
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://x.next-cloud.org/remote.php/webdav/") FINISHED WITH STATUS "AuthenticationRequiredError Host requires authentication"
[OCC::PropfindJob::finished 	*not* successful, http result code is 401 ""
[OCC::ConnectionValidator::slotAuthFailed 	******** Password is wrong! QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication"
[OCC::AccountState::slotInvalidCredentials 	Invalid credentials for "https://x.next-cloud.org" asking user
[OCC::FolderMan::slotAccountStateChanged 	Account "@x.next-cloud.org" disconnected or paused, terminating or descheduling sync folders
[OCC::AccountState::slotCredentialsAsked 	Credentials asked for "https://x.next-cloud.org" are they ready? true
[OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://x.next-cloud.org/status.php" has X-Request-ID "cfbe3851-16d8-4541-a8c5-0d4284219844"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://x.next-cloud.org" + "status.php" "OCC::ConnectionValidator"
```


It seems weird since I haven't changed the password at all 
```

OCC::ConnectionValidator::slotStatusFound 	** Application: ownCloud found:  QUrl("https://y.domain.abc")  with version  "10.0.1" ( "9.1.1.5" )
[OCC::ConnectionValidator::setAndCheckServerVersion 	QUrl("https://y.domain.abc") has server version "9.1.1.5"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://y.domain.abc/remote.php/webdav/" has X-Request-ID "fce03242-65c3-4134-a806-0246be86dbec"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://y.domain.abc" + "/" "OCC::ConnectionValidator"
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Nextcloud","version":"15.0.4.0","versionstring":"15.0.4"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x55cd6eddb0b0)
```

On the second one, I admit, the server software is terribly out of date, but it suddenly stopped working. (after upgrade of Fedora 28-->29

**Comment by camilasan** [comment]
Hi! Could you try our latest RC https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.2.20190205-rc1-x86_64.AppImage? I have reasons to believe this is the same issues that has been reported before... and it should be fixed in the 2.5.2? Thanks.

**Comment by heis2201** [comment]
Puh, I am not sure I am able to test the AppImage. Will running two clients of nc (one rpm, one AppImage) create a mega mess? Also, what the heck is AppImage? My system has learned to understand flatpak and snap in the past couple of years... AppImage... don't know.

**Comment by heis2201** [comment]
My distro has made version 2.5.2 available in their repos. Unfortunately, the connection problem has not been solved using that version.

**Comment by heis2201** [comment]
Setting

````authType=webflow```` in `nextcloud.cfg` solved the problem for me.

See downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1700162

**Comment by thsnielsen** [comment]
Had same problem
AuthenticationRequiredError
and
authType=webflow in nextcloud.cfg also solved the problem for me.

**Comment by FlexW** [comment]
Does the issue still apply? If yes, please reopen it.
