### ISSUE TITLE
show conflict files in subfolder

### ISSUE THREAD

**Issue by jeffli678** [nextcloud/desktop#1107]
Currently, the yellow conflict icon only tells me the top level folder has a conflict. But I have some difficulties finding which files are causing the conflict. I get too many "file xxx is ignored" information in the activity tab, so I cannot find which files are conflicting. 

To resolve the issue, I would suggest using the yellow conflict icon on second level folders, third level folders, until the last level of folder. For example, if the files on the Desktop has conflicts, show a conflict icon on those folder(s) contain the files causing a conflict.

**Comment by camilasan** [comment]
Hi @jeffli678! Thanks for the feedback. Could you provide some screenshots with the issue?

**Comment by jeffli678** [comment]
Hi, I will try to make a screenshot. But I am actually suggesting a new future -- so I cannot possibly come up with a screenshot for that. What I can do is to show what it currently looks like, and then try my best to explain why the current appearance is not good and how it can be improved.

**Comment by camilasan** [comment]
> I get too many "file xxx is ignored" information in the activity tab, so I cannot find which files are conflicting.

We actually meant screenshots of the current state ;-)

**Comment by jeffli678** [comment]
My apology for the late reply. I am impressed that you are still chasing after this issue. Thanks for your insistence!

It is actually not complex: the activity tab has too many messages and it is not easy to find which files are conflicting. 

![Screenshot from 2019-08-13 23-34-42](https://user-images.githubusercontent.com/3380590/62956085-d4cfd080-be24-11e9-9f18-3c007d04f991.png)

In the initial issue I opened, I cited the "xxx file is ignored" messages. In the screenshot, however, you will see plenty of "You created file xxx" messages. It is noteworthy that in this particular screenshot, the number of messages is acceptable. However, it is also common that my .git folder is ignored (due to its hidden property) and a lot of messages fill this tab and navigating through it is difficult.  

I hope I explained everything clearly. 

Before I switched to nextcloud, I was using a similar product called Seafile. I remember it handles such conflicts elegantly. However, I cannot remember the exact way. 

Here is the way I handle conflicting files now: I directly open the SQLite database generated by nextcloud and browser the relevant table which records the pairs of conflicting files. It is a hack, ^_^.

**Comment by jancborchardt** [comment]
Right, so 2 things:

1. Conflict notifications should be above other notifications like ignored files in the Activity view. They require action and could otherwise lead to data loss or duplication. @camilasan ok? :)

2. As said above:
> About the mass of "file is ignored" notifications, we have a separate discussion to solve that at https://github.com/nextcloud/desktop/issues/889#issuecomment-443032646

**Comment by wolfspyre** [comment]
Taking a step back might be a valuable exercise here...

When the user is directed to inspect the activity tab because conflicts exist, they’re presented with a view that has a horrible signal to noise ratio.

Perhaps the activity panel should have the option to filter elements by classifications of activity, or by importance, or if the activity involved has an expectation of user involvement to rectify homeostasis? IE: think of the activity panel as a call to action, and use that mentality to drive what should be prominently displayed and how...

Or perhaps it might make sense to have a conflicts and errors tab? 

Just some unsolicited $.03 from the peanut gallery :)

**Comment by jancborchardt** [comment]
> Perhaps the activity panel should have the option to filter elements by classifications of activity
> Or perhaps it might make sense to have a conflicts and errors tab?

We did use to have it like this and it made the interface more complex and more confusing to figure out where to look.

 This is why we changed to the single stream. The only issue is that we are not fully done on that – we need to polish and adjust for all the cases.

As written in **Activity tray and activity list design improvements #889**

> - We are not going to split the activity view again. We are just not done with it yet.
> - Warnings for symlinks should be grouped into only one row. `Symbolic links are not supported in syncing: keeporsweep.py, nextcloud-update.sh, and 3 others`. Alternatively, symlinks on macOS and Linux should just be synced. #605 
> - Warnings for ignored files should not even be there? Because they are ignored, they should be ignored everywhere. (At most, again just one row: `Files not synced because of ignore list rules: ._DS_Store, .gitblasomething, and 200 more`)

**Comment by jancborchardt** [comment]
Closing in favor of Activity tray and activity list design improvements #889
