### ISSUE TITLE
Folders ending in space not synchronized

### ISSUE THREAD

**Issue by ChessSpider** [nextcloud/desktop#1113]
### Expected behaviour
All shared folders are synchronized to the desktop using the nextcloud client

### Actual behaviour
Not all shared folders are synchronized. 

I have found two folders which were shared with a user, which were not synchronized. The foldernames ended in a space. After renaming one of these folders, that folder would immediately correctly synchronize to other users.

### Steps to reproduce
1. Unknown, specifically. 
2. But create shared folders, and share these with multiple other users
3. And create continue using it
4. And some folders will not sync

### Client configuration
Client version: both nextcloud 2.5.1 and 2.3.3.1

Operating system:  windows

OS language:  English & Dutch

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
program files

### Server configuration

Operating system:  linux, docker
Web server:   php-fpm w/ nginx
Database: mariadb
PHP version: 7.2
Nextcloud version: 15.0.4
Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`no entries in logfiles related to the missing folder, including the nextcloud client. Can post, but not in public  issuetracker`

**Comment by Wikinaut** [comment]
Perhaps this is related to not escaped spaces like https://github.com/nextcloud/desktop/issues/1018

**Comment by SiM** [comment]
I am experiencing the same issue on windows 10 and 7, tested on 2.3.3 and 2.5.2 version. 
On Linux, everything works fine.

**Comment by webafrancois** [comment]
Same bug with the 2.6.2 windows version.

Here, the "Logigrammes " folder is ending with a space and not synchronized.
We rename this folder on the cloud and it appear in the local folder after synchronisation.

Some logs  : 

`[OCC::ActivityListModel::addSyncFileItemToActivityList 	Successfully added to the activity list:  ""
[OCC::FolderWatcher::changeDetected 	Detected changes in paths: QSet("C:/Users/AnneclaireD/Documents/D Qualité Réseau/Decret qualité FP 2019/Textes legislatifs/decret_2019-565_du_6juin2019_référentiel_qualité_formation[1].pdf")
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "D Qualité Réseau/Logigrammes " by OCC::PropagateIgnoreJob(0x1dbbb63ef30)
[OCC::PropagateItemJob::done 	Could not complete propagation of "D Qualité Réseau/Logigrammes " by OCC::PropagateIgnoreJob(0x1dbbb63ef30) with status 6 and error: "Le nom du fichier se fini par des espaces."
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE+SWM:C:\\Users\\AnneclaireD\\Documents\\D Qualité Réseau\\Logigrammes " to QLocalSocket(0x1dbb995c390)
[OCC::ActivityWidget::slotItemCompleted 	Item  "D Qualité Réseau/Logigrammes "  retrieved resulted in  "Le nom du fichier se fini par des espaces."
[OCC::ActivityWidget::slotItemCompleted 	Item  "D Qualité Réseau/Logigrammes "  retrieved resulted in error  "Le nom du fichier se fini par des espaces."
[OCC::ActivityListModel::addIgnoredFileToList 	First checking for duplicates then add file to the notification list of ignored files:  "D Qualité Réseau/Logigrammes "
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "D Qualité Réseau/._.DS_Store" by OCC::PropagateIgnoreJob(0x1dbc30eb5a0)`
