### ISSUE TITLE
2.5.1 windows client fails to log users (infinite gear spinning)

### ISSUE THREAD

**Issue by Tom31100** [nextcloud/desktop#1114]
### Expected behaviour
entering login and password should allow to go to the end of connexion process
Note 1 : I can see the access has been granted in my web interface
Note 2 : It works with admin account
Note 3 : it works with owncloud client 2.5.3

### Actual behaviour
After enterring credentials, a spinnin "connecting" wheel does never stop
### Steps to reproduce
simply install client 2.5.1 for windows and try to connect to your nextcloud server 

1- enter the adress of your server
2- Clic on "connect" button
3- enter login and password for the user
4- clic on grant acces
5- wait endlesslly

### Client configuration
Client version: 2.5.1

Operating system: windows 10 last upgrade

OS language: French

Installation path of client: 

### Server configuration

Operating system:

Web server: provided by partner

Database:

PHP version:

Nextcloud version: 15.04

Storage backend (external storage): NO

### Logs

2. Web server error log:
[core] Warning: Login failed: 'Ths+PRI' (Remote IP: 'xx5.xxx.XX9.xx')

PROPFIND /remote.php/webdav/
from 185.217.119.29 at 2019-02-27T09:46:30+01:00

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by victorbw** [comment]
does the username have a whitespace? like: "Patrick Steward"?

**Comment by Tom31100** [comment]
Yes it does

**Comment by Tom31100** [comment]
And the admin doesn't... It could explain why i Can login with admin and
not other acounts...

**Comment by Tom31100** [comment]
Maybe we could add it to the bug list :

spaces in login name (like "Patrick Steward") prevent nextcloud 2.5.1 windows client to connect to the server ?

**Comment by victorbw** [comment]
glad you've found the related topic! please check out the new RC which @rullzer provided.
