### ISSUE TITLE
Remote poll intervall is limited to values greater or equal to 5 seconds

### ISSUE THREAD

**Issue by sschuerz** [nextcloud/desktop#1115]
### Expected behaviour
* The client polls the remote server using the configured remote poll intervall, even if an interval shorter than 5 second is configured

### Actual behaviour
* The configured remote poll interval is not effective, if an interval shorter than 5 second is configured
* Instead the default remote poll interval (30000 = 30 seconds) is effective in this case

### Steps to reproduce
1. Set `remotePollInterval` to a value < 5000 (= 5 seconds) in the configuration file as documented here: https://docs.nextcloud.com/desktop/2.5/advancedusage.html

### Client configuration
Client version:
* 2.5.1final

Operating system:
* Windows 10, but seems to be OS independent

OS language:
* ?

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

```
...
[OCC::ConfigFile::remotePollInterval 	Remote Interval is less than 5 seconds, reverting to 30000
...
```

2. Web server error log:
* Not relevant

3. Server logfile: nextcloud log (data/nextcloud.log):
* Not relevant

### Further information

There seems to be a hard coded limit of 5 seconds, see `ConfigFile::setRemotePollInterval`.

I cannot find this in the documentation and the reason for this limit is not obivous for me.

I think there is no real danger of someone setting it to a "too small" value by accident (and causing an unwanted high request frequency), since this configuration can only be changed directly in the configuration file.

**Comment by camilasan** [comment]
Done.
