### ISSUE TITLE
Nextcloud client can not delete files

### ISSUE THREAD

**Issue by Sveeeeeen** [nextcloud/desktop#1120]
Hello,

I just have a problem on one of my client. I am using 2 clients with the same nextcloud folders. On my Laptop everything is fine. If I delete files on my Laptop these files should be removed on my PC too. The client is trying it but it stop with a error:
"Verschieben in den Papierkorb ist auf dieser Platform nicht möglich".

What is the problem here? I doesnt looks like a permission problem.

**Comment by Laeusel** [comment]
I guess this is a permission problem very well.

Do you use two different accounts via sharing Folders, or the same account on both machines?
In the first case both accounts needs permission to edit and delete.

Is the issue also present if you try it vice versa?

**Comment by Sveeeeeen** [comment]
I think so too. But I don't know what's wrong. My Windows user has full permissions. And the client should be able to delete files in my opinion... even if I run the  client as admin I still have the problem.
I am using the same account on the PC/Laptop.



> Is the issue also present if you try it vice versa?
No. Laptop is able to delete files. This problem occurs only on my PC.

**Comment by camilasan** [comment]
You are saying you delete files in your computer but the operation is not propagated to the server? This is looking like a server response. Please, could you update this issue with server and client logs of when you get this message? Thanks!

**Comment by Sveeeeeen** [comment]
> You are saying you delete files in your computer but the operation is not propagated to the server? This is looking like a server response. Please, could you update this issue with server and client logs of when you get this message? Thanks!

No. My server is fine! But one of my client is not able to delete the files locally if I change something on another client.

Error: "Verschieben in den Papierkorb ist auf dieser Platform nicht möglich".

But the permissions seems to be OK. My local user is the owner of the file and has all rights.

**Comment by camilasan** [comment]
As I said, could yo update the issue with the client logs?

**Comment by Sveeeeeen** [comment]
> As I said, could yo update the issue with the client logs?

Is this helpfull?

> #=#=#=#=# Propagation starts 2019-03-05T14:53:56Z (last step: 53739 msec, total: 53739 msec)
||bilder/Kamera/IMG_20190201_185419.jpg|INST_REMOVE|Down|1549043660||2956233||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_194600.jpg|INST_REMOVE|Down|1549219560||1620318||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_195318.jpg|INST_REMOVE|Down|1549219999||1531665||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_195335.jpg|INST_REMOVE|Down|1549220015||1535152||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_195405.jpg|INST_REMOVE|Down|1549220046||1593361||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_195431.jpg|INST_REMOVE|Down|1549220072||1389234||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_195612.jpg|INST_REMOVE|Down|1549220172||983070||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||
||bilder/Kamera/IMG_20190203_203350.jpg|INST_REMOVE|Down|1549222431||1341110||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||

**Comment by camilasan** [comment]
Do you have a log file in the same folder as your configuration?

**Comment by Sveeeeeen** [comment]
> Do you have a log file in the same folder as your configuration?

You want the complete file?
[nextcloud_sync.log](https://github.com/nextcloud/desktop/files/2931491/nextcloud_sync.log)

**Comment by Laeusel** [comment]
Hi,
the files you want to delete have not the same code, there is missing something in the middle:

**Fail-Example from your Log:**
12:03:01||ip_sperren.txt|INST_NEW|Up|1479591653|**_ffefa83dcfdc3cafe94e9675290e7938_**|6807|01544644ocj7frawqct8|4||201|0|0||||

||ip_sperren.txt|INST_REMOVE|Down|1479591653||6807||2|Verschieben in den Papierkorb ist auf dieser Plattform nicht möglich|0|0|0||||

**Success-Example from your Log:**
14:05:24||external/Scripte/c++|INST_NEW|Up|1542539149||4096|00000576oc6zlm221z0f|4||201|0|0||||

||external/Scripte/c++|INST_REMOVE|Down|1542539149||4096|00000576oc6zlm221z0f|4||0|0|0||||

Maybe you should try to do a complete rescan of your Data-Folder(s) to fix DB-issues.

**Comment by Sveeeeeen** [comment]
How can I do a rescan? Just delete the .db file inside of the folder?

**Comment by Laeusel** [comment]
With the occ-commands:

sudo -u www-data php *YOUR_OWN_PATH*/nextcloud/occ files:cleanup
sudo -u  www-data php *YOUR_OWN_PATH*/nextcloud/occ files:scan --all -v

*YOU_OWN_PATH* depends on your own installation, maybe you are using another like www-data user too.

**Comment by Sveeeeeen** [comment]
So the only way is to use the occ command?
I do not have access to the files/occ command. 

I am using Hetzner as provider for Nextcloud.

**Comment by Laeusel** [comment]
Ok, sorry.
Thought you were the serveradmin...

For me it looks like your sync want to handle **_ip_sperren.txt_** -for example- like a folder.
Try to create a new file with the same name to the same place and look what happens.
Nextcloud should create a new Hash for the filename while syncing.
Maybe this will help.

**Comment by Sveeeeeen** [comment]
I am still facing this issue:

I tried the following. I copied a file into my local nextcloud folder. Wait for Sync.
Deleted this file with help of the nextcloud webinterface.

Still, the same problem. Nextcloud is unable to delete this file on my local system.
