### ISSUE TITLE
Cannot log in after removing the account

### ISSUE THREAD

**Issue by IzabelaBakollari** [nextcloud/desktop#1121]
### Expected behaviour
Login page should appear. 

### Actual behaviour
After I removed my account I cannot log in again when open Nextcloud from the command line or desktop icon. Only works if I check Launch on startup and restart the computer.

### Steps to reproduce
1. Open nextcloud from command line or desktop icon

### Client configuration
Client version: 2.5.1git

Operating system: Debian testing with KDE Plasma

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt5

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop from the Debian package manager
Installation path of client: /usr/bin/nextcloud

![screenshot_20190301_200640](https://user-images.githubusercontent.com/7606423/53660261-b9e61700-3c5d-11e9-8f97-cc08c97a812d.png)

**Comment by Wikinaut** [comment]
Does your account user name contain a space?

**Comment by IzabelaBakollari** [comment]
No, the username is only one name. I tried again to reproduce the problem, it was working. Should I close the issue?

**Comment by camilasan** [comment]
Thanks @IzabelaBakollari. Before we consider closing it, could you update the issue with the client logs?

**Comment by catscarlet** [comment]
Well I got an issue and I think it's relevant.

I'm using AppImage and at first I failed to connect to my server, then I closed it.
After that when I tried to open again, this happened:

![53220851_375285379728692_3463435328998941284_n](https://user-images.githubusercontent.com/10594035/53820105-20dd3600-3fa6-11e9-83e2-46e3a65fe397.jpg)

No chance to add server.

I also tried removing ~/.config/Nextcloud , but nothing changed.

Stucked.

**Comment by catscarlet** [comment]
OK.
I restarted my computer and this problem disappeared.
The issue caused failure to connect to server didn't occur after I update my server to v13.

**Comment by IzabelaBakollari** [comment]
My server is v.13. I attached the logs from the day i noticed the problem. Same with me, when I restart the computer the problem solves.

`

Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-05T22:57:41+0100
-- | -- | -- | --
Warning | core | Trusted domain error. "209.17.96.242" tried to access using "www.cloud.izabela.pro" as host. | 2019-03-05T22:35:29+0100
Warning | core | Trusted domain error. "209.17.96.250" tried to access using "www.cloud.izabela.pro" as host. | 2019-03-05T00:23:53+0100
Warning | core | Trusted domain error. "209.17.96.210" tried to access using "www.cloud.izabela.pro" as host. | 2019-03-04T21:28:26+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T18:24:43+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T18:24:43+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T17:15:58+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T17:15:58+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T15:14:37+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T15:14:37+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T12:43:45+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T12:43:45+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:45:16+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:45:16+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:10:46+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:10:46+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:08:18+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T11:08:18+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T10:54:17+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T10:54:17+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T06:23:15+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T06:23:15+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T00:46:44+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T00:46:44+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T00:13:40+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-04T00:13:40+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T23:37:19+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T23:37:19+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T20:21:27+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T20:21:27+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T18:33:37+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T18:33:37+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T17:25:28+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T17:25:28+0100
Warning | core | Login failed: 'izabela' (Remote IP: '185.200.214.157') | 2019-03-03T17:25:14+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T16:48:31+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T16:48:31+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T15:21:13+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T15:21:13+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T10:09:37+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T10:09:37+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T01:09:44+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-03T01:09:44+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-02T19:18:20+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-02T19:18:20+0100
Error | PHP | idn_to_ascii() expects parameter 3 to be integer, string given at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-02T18:08:48+0100
Error | PHP | Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' at /home/izabela/cloud.izabela.pro/lib/private/Mail/Mailer.php#212 | 2019-03-02T18:08:48+0100
Warning | core | Trusted domain error. "209.17.96.218" tried to access using "www.cloud.izabela.pro" as host. | 2019-03-02T16:30:04+0100
Warning | core | Trusted domain error. "209.17.96.218" tried to access using "www.cloud.izabela.pro" as host. | 2019-03-02T16:30:04+0100

`

`
