### ISSUE TITLE
Usability: Confusing error message when files were deleted on the server

### ISSUE THREAD

**Issue by bllngr** [nextcloud/desktop#1123]
This concerns the following error message that is shown when files were deleted **on the server**:

![2019-03-04 15_44_27-2019-03-04 11_04_21-download new files_ png - irfanview selection_ 0 0 502 x](https://user-images.githubusercontent.com/303458/53740556-c0120880-3e94-11e9-82fe-5bf4aa2aa6e5.png)

### Expected behaviour
The message should be clear what the state will be on the local machine and on the client.

### Actual behaviour
This error message is confusing, as there is no action that resembles the options presented in the text. For me, it was not clear what will happen if I select "Download new files":

* What files?
* Why are they new? The dialog said they have been deleted
* Download them from where, to where?

### Client configuration
Client version:
2.5.1 final

Operating system:
Windows 10 1803

OS language:
US English

**Comment by darmbrust** [comment]
see https://github.com/nextcloud/desktop/issues/1198#issuecomment-504583381 as well.  This dialog needs a complete rework with all use cases taken into account.

**Comment by FlexW** [comment]
Could you please test with the newest version (3.2.2). I think the dialog is now more clear. It is now also disabled by default.
