### ISSUE TITLE
Sync different folders for different devices while using RoamingProfile

### ISSUE THREAD

**Issue by klatka** [nextcloud/desktop#1124]
### Expected behaviour
Sync different folders for different devices using the same active directory user and roaming profile

### Actual behaviour
Every change of the sync folders will be committed to all devices..

The config file of the sync client which contains folder to sync is saved in the roaming profile of the user i use for every device...

### Steps to reproduce
1. Install sync client and select folders to get synced on devices A & B with the same AD-User
2. Log out from device A
3. Select other folders on device B
4. Log in to device B

Possible solutions (from #47) :
Create a persistent possibility to configure the default filepath of the config file (e.g. a INI file in the program directory of the client, or a Registry-Key under HKLM).

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system: Win10 64Bit

**Comment by klatka** [comment]
**Workaround**

1. 

Exclude the `AppData\Roaming\Nextcloud` folder from syncing in your GPO

2.

Delete the `AppData\Roaming\Nextcloud` folder in your RoamingProfile on your server

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently, there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
