### ISSUE TITLE
Xubuntu: systray icon menu disappears unless holding mouse button

### ISSUE THREAD

**Issue by pjotrek-b** [nextcloud/desktop#1126]
### Expected behaviour
Single click (left button) on icon in system tray should open a menu.
The menu window should stay open, until I either choose an option or exit the menu.

### Actual behaviour
The menu only stays open *while* I keep the mouse button pressed and immediately closes when releasing the button.

Even worse: Single-clicking it (like other systray menus) selects an arbitrary option, depending where the mouse cursor was, when button was released.
Most often, this is of the bottom items "Quit Nextcloud" or "Pause all synchronization".

Checked for existing issues/duplicates, but couldn't find a match.
It doesn't seem like #833, although [user "m4lvin" mentions similar behavior than this in KDE](https://github.com/nextcloud/desktop/issues/833#issuecomment-439071032).

### Steps to reproduce
1. Single-click the systray icon.
Menu will flash open - and then disappear. Possibly exiting Nextcloud client.

### Client configuration
Client version: 2.5.1git

Operating systems:
Xubuntu 16.04.6 + 18.04 (both 64bit)

OS language:
en_US.

Qt version used by client package (Linux only, see also Settings dialog):
Don't see this in "About" section or anywhere else in Settings :disappointed:
Sorry.

Client package (From Nextcloud or distro) (Linux only):
"This release was supplied by Nextcloud GmbH"

**Comment by obsidiannonparity** [comment]
I can confirm this issue. Xubuntu is not my normal distribution but I was testing an unrelated application on it in a virtual machine and I did notice this.

**Comment by m4lvin** [comment]
This also happens under KDE 5.8.6 in Debian Stretch with the clients 2.5.1 and 2.5.2.
