### ISSUE TITLE
Mac Sync Client stuck at Grant Access

### ISSUE THREAD

**Issue by andy-chin** [nextcloud/desktop#1127]
### Actual behaviour
Click Grant Access, but there is nothing happen.
No problem logging in thru web and mobile apps. 

### Steps to reproduce
1. New account...
2. Log in
3. Grant access

### Client configuration
Client version: 2.5.1.20181204

Operating system: macOS 10.14.3

OS language: English (US)

**Comment by AdrianBan** [comment]
Same issue with Linux client 2.5.1 and NextCloud latest version.
I've tried all settings in Apache and in Nextcloud server config.php without success.

**Comment by beatrubi** [comment]
Tested:
* Official 2.5.2git (build 20190319) git-Revision 56c905 on OS X
* Arch Linux nextcloud-client 2.5.2-1

Result:
* Hangs while authenticating against Nextcloud 15.0.5
* Successful authentication against Nextcloud 13.0.4

So there seems to be an issue on the server side which is shown as a regression in the client.

**Comment by in0rdr** [comment]
Tested:

* On Arch Linux with **[Nextcloud Client v2.5.3-rc1](https://github.com/nextcloud/desktop/releases/tag/v2.5.3-rc1)**

Result:

* Hangs while authenticating against Nextcloud **16.0.0.9**

**Comment by in0rdr** [comment]
The problem was the "re-authentication" feature/option of the `user_saml` Nextcloud-App. `user_saml.general-use_saml_auth_for_desktop` is enabled by default, which leads to the following error message when a user logs in with a sync-client:
```
May 11 11:08:35 Nextcloud[21900]: {core} {"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Middleware\/MiddlewareDispatcher.php","line":95,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginController"},"grantPage"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginController"},"grantPage"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginController"},"grantPage"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginController","grantPage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.ClientFlowLogin.grantPage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.ClientFlowLogin.grantPage"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.ClientFlowLogin.grantPage"}]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login\/flow\/grant"]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/nextcloud\/lib\/private\/AppFramework\/Middleware\/Security\/SecurityMiddleware.php","Line":143,"CustomMessage":"--"}
```
Because it tells me `Current user is not logged in`, I figured it would be okay not to authenticate twice. Disabling the Option in the GUI in `"Admin" > "Settings" > "SSO & SAML Authentication" > "Use SAML auth for the https://example.com desktop clients (requires user re-authentication)"` or issuing the following `occ` command resolves this re-authentication issue:
```
sudo -u <APACHE_USER> <PATH_TO_PHP_BIN>/php <NC_PATH>/occ config:app:set --value 0 user_saml general-use_saml_auth_for_desktop
```

**Comment by in0rdr** [comment]
See also https://github.com/nextcloud/user_saml/issues/167

**Comment by misch7** [comment]
Please try our recent 2.6 release and re-open this ticket if the problem still persists with it:
https://nextcloud.com/install/#install-clients

If you use NC server 16.x and up, the new Login Flow v2 authentication is available and the login takes place in your standard browser.

**Comment by raeisi** [comment]
I still have same problem on new mac os

**Comment by nmihaica** [comment]
> I still have same problem on new mac os

adding in ubuntu 16.04

**Comment by nmihaica** [comment]
2.6.1 worked on debian 9.5 stretch, here is [manual](https://soultrace.net/nextcloud-client-on-debian-stretch-9-5/). Guess reverting back should make it work on ubuntu.
