### ISSUE TITLE
Unable to read current status

### ISSUE THREAD

**Issue by rafiwui** [nextcloud/desktop#1128]
### Expected behaviour
Color of the output text should stay black so it is visible

### Actual behaviour
As soon as there appears some error when uploading files, the color of the status text is changed to white:
![image](https://user-images.githubusercontent.com/9059431/53972988-323a5580-4100-11e9-9b60-2c6d6a5012c2.png)

### Steps to reproduce
1. Generate an error
2. Make sure upload is continued
3. Don't see what's happening at the moment

### Client configuration
Client version: Version 2.5.1final (build 20181204)

Operating system: Windows

OS language: German

**Comment by r19u0me1** [comment]
I also observed this behaviour in Windows client v2.6.1 (build 20191105).

The color of the status text is always white after any error (red) or alert (yellow) has been output. It seams, that text color is changed to white for the error/alert message and not switched back to black for the status text.

**Comment by FlexW** [comment]
Sorry I'm not able to understand what the problem is. Could you clarify it? Does the issue still exist with the latest client (version 3.2.0 at the moment)?
