### ISSUE TITLE
Windows 10 client does not sync folders containing a question mark in the name

### ISSUE THREAD

**Issue by dartmann** [nextcloud/desktop#1129]
In advance I want to reference the [issue](https://github.com/nextcloud/server/issues/14550) I created on the server repo, falsly. Just for completeness.

### Expected behaviour
The client should sync created folders containing a question mark in the name. Another solution would be to warn a user that a question mark in a folder title is not valid for Windows and therefore can not be synced on this OS until it is renamed.

### Actual behaviour
The Windows client does not sync the folder and tells me that everything is in sync.

### Steps to reproduce
- Create a folder with a question mark in the name (on other OS than Windows).
- Folder is not synced on Windows 10 client but all other (tested only macOS and Android).

### Client configuration
Client version: 2.5.1.final

Operating system: Windows 10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: default

### Server configuration
Should not be relevant. I would catch this up, if necessary.

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
I think questions marks are not allowed in file names of Windows file systems. You might want to check out this pull request https://github.com/nextcloud/desktop/pull/3022
