### ISSUE TITLE
The file could not downloaded completly on .xml and .json files

### ISSUE THREAD

**Issue by Simonmicro** [nextcloud/desktop#1134]
### Expected behaviour
The file should be downloaded and everything is fine.

### Actual behaviour
The file gets partially (?) downloaded and then throws the error "The file could not downloaded completly." inside the desktop sync client. After that a new message appears with "File removed (start upload) [the files path].\~sdfhdf2346skdfs" (after the '\~' comes some random chars). Because of that the client will stuck on these files and loops over them - and throw every time a desktop notification.

###My guess what that causes
The client wants to download the new version and fails (i don't know why). But the client has downloaded the file to a temporary name (e.g. "name.\~gtas45m234lk2") and now queues the file to gets reuploaded, but because the temporary file is then deleted this will trigger the "regular download", which failes again.

### Steps to reproduce
Good question. It happens for me only from time to time, so i only can suppose the following:
1. Create on client A an .xml file and let it sync
2. Lets the file get downloaded on client B and edit it multiple times, while it syncs (? - I really don't know how to trigger, so i guess this should MAYBE work).
3. Back to client A: Now the file should get stuck - only "fix" is to delete the file on client A and lets it redownloaded.

###Workaround
Go to client A and delete the file there. It will get redownloaded and everything works fine again.

### Client configuration
Client version: 2.5.1git

Operating system:
Lubuntu 18.04.2
Linux Mint 19.1

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
?Where in the settings dialog?

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client

Installation path of client:
`whereis nextcloud`
`nextcloud: /usr/bin/nextcloud /usr/lib/x86_64-linux-gnu/nextcloud /usr/share/nextcloud`

### Server configuration
**Not relevant**

Operating system:
debian 9 - stretch

Web server:
apache2

Database:
mariadb

PHP version:
PHP 7.0.33-0+deb9u3

Nextcloud version:
15.0.5

Storage backend (external storage):
**Not used**

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
**It has been cutted down to containing some lines with the error (and masked to hide personal information)...**
https://gist.github.com/Simonmicro/49bcde7ef4e946de6097d7f717dac247

2. Web server error log:
**Nothing here**

3. Server logfile: nextcloud log (data/nextcloud.log):
**Nothing here**

**Comment by Simonmicro** [comment]
Little update: Now it happens on json files too.

**Comment by FlexW** [comment]
Are you still affected by this issue with a recent client version (3.2.1)?
