### ISSUE TITLE
Red Error when Server/Client offline instead of grey

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/desktop#1135]
Right now the red cross (2.5.1 final build 20181204 Windows 10) is shown when the client has no connection to Server (either client has no Internet or server is off).

Problem:
You can't see if there is an error.

Before the nextcloud Icon was Grey (color setting, not monochrome) so I could see there is no Connection.

Right now it says (translating from German):
While opening one of the folder accured an Error. Host www.mynextcloud.private could not be found.

German: Beim Öffnen eines Ordners ist ein Fehler aufgetreten. Host www.mynextcloud.private konnte nicht gefunden werden

This Error commes more than ones.

Is there an offline Icon or is this a bug? In previous Version (maybe 2.3.1 don't know which I had before) this Error didn't came.

**Comment by jancborchardt** [comment]
Agree with @jonathanmmm here that offline / server not found state is not an error state. It should show the grey icon as before – not the error icon.

cc @camilasan @juliushaertl what do you think? Or what was the reason for the change?

**Comment by jonathanmmm** [comment]
Were this icons changed? I have not followed if I got the red error icon when the server is offline.
