### ISSUE TITLE
Wrong location of linux config file

### ISSUE THREAD

**Issue by sciurius** [nextcloud/desktop#1137]
Despite the documentation, the Linux nextCloud client looks for its config file in `$HOME/.local/share/data/Nextcloud'.

**Comment by phpdrill** [comment]
Which linux distribution are you using?

The code uses QStandardPaths::AppConfigLocation for UNIX,
which should default to one of these directories:
~/.config/<APPNAME>
/etc/xdg/<APPNAME>

The code also notes that this variable (AppConfigLocation) is configurable with the XDG_CONFIG_HOME environment variable.

Sources:
https://github.com/nextcloud/desktop.git/src/libsync/configfile.cpp:300
https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by sciurius** [comment]
I'm using Fedora 29. Further investigation shows that Fedora 29 ships nextcloud-client 2.3.3, which is basically a 2 years old rebranded owncloud-client. I manually built nextcloud-client 2.5.1 and now it uses `~/.config/Nextcloud` -- after first importing (moving) the config data from `~/.local/share/Nextcloud`. Neat.

Sorry for the confusion. I thought I was running a bleeding edge distro.
