### ISSUE TITLE
Password Update Issue

### ISSUE THREAD

**Issue by Sharlvz** [nextcloud/desktop#1138]
Background
We use LDAP integration into Microsoft AD. We have policies that force users to change passwords every 30 days. The user changes the password at login after which the NC Client password must be updated.

### Expected behaviour
When a password is changed I expect the NC client to prompt the user for the new password. Once entered the cached password should be updated and the client should continue to sync as normal.

### Actual behaviour
When the password is changed the NC client pops up a box asking for both the username and password in windows that resembles the web login. When these are entered the user is simply logged into the web access in this window but the client is not updated and therefore remains disconnected.

### Steps to reproduce
1 User is prompted to update his password by windows
2 User changes password
3 After login NextCloud client gives a popup (like OC used to) but asks for both username and password in a new window (instead of just a password update like owncloud did.)
4 User enters username and new password, and is logged into the Nextcloud instance instead of the client being updated.
5 User is never able to update the password
6 Client remains disconnected

### Client configuration
Client version: NC 2.5.1

Operating system:
Both Windows and Mac effected

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
n/a

Client package (From Nextcloud or distro) (Linux only):
n/a

Installation path of client:
defaults

### Server configuration

Operating system: ubuntu 16.04

Web server: apache  2.4.18

Database: MySQL

PHP version: 7.0.33

Nextcloud version: 10.0.6 stable

Storage backend (external storage): Local

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
Are you still affected by this issue with a recent client version (3.2.1)?
