### ISSUE TITLE
Add note to recipient

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#1139]
On the server:
![share](https://user-images.githubusercontent.com/241266/54546358-cf6c7800-49a3-11e9-9c8d-3e5200b5c150.png)

On the desktop client, we would add a text field on the 3 dots menu:
![share-desktop](https://user-images.githubusercontent.com/241266/54546562-3e49d100-49a4-11e9-8351-b68523c2611e.png)

@IzabelaBakollari  the parameter to the request is "note" (src/gui/ocssharejob.cpp)

@jancborchardt do you think we need some mockup for this?

**Comment by jancborchardt** [comment]
Yup, this would be an entry in the 3-dot menu of a share. :) Best look at how it’s done in the web interface for how the flow should be like.

**Comment by jancborchardt** [comment]
If the inline input as in the web interface is not possible, an alternative would be to still have the "Note to recipient" entry in the menu which would then open a modal window with the text box. 

Just let me know what works and what doesn't. :)

**Comment by IzabelaBakollari** [comment]
Inline input below the user/group would be a good solution, similar to Password and Expriation date.

![example](https://user-images.githubusercontent.com/7606423/54686956-bdf9ac00-4b1a-11e9-8689-7d897fce50de.jpg)

**Comment by IzabelaBakollari** [comment]
Also something useful would be a small delete button next to each input arrow.

**Comment by IzabelaBakollari** [comment]
@jancborchardt where do you think the note would look better? Below the username menu or below Share link, under Password entry?

**Comment by jancborchardt** [comment]
> @jancborchardt where do you think the note would look better? Below the username menu or below Share link, under Password entry?

Below the share link under the Expiration date. :) Then it’s symmetric to the web interface.

**Comment by claucambra** [comment]
This has been a part of the share dialog at least since the redesign from a while ago :)
