### ISSUE TITLE
Windows client shows black screen on log in

### ISSUE THREAD

**Issue by skaa** [nextcloud/desktop#1141]
### Expected behaviour
Login normally.

### Actual behaviour
After inputing server address, client shows black screen.

### Steps to reproduce
1. Open client, press Login
2. Input server address, press Next
Client opens window with black page. The behavior is the same as reported [here]( https://help.nextcloud.com/t/desktop-client-black-screen-after-server-connection/39647/4) with error
`QOpenGLFramebufferObject: Unsupported framebuffer format.`
in log window. And process nextcloud.exe takes 100% of single CPU core.

### Client configuration
Client version: 2.5.1.20181204

Operating system: Windows 8.1

OS language: Russian

**Comment by affinityv** [comment]
I've seen this on remote connections too; I worked around it by guessing where to click and use KeePass auto-type to enter username and password.  This was both on Win7 RDP and also Windows Server 2012R2 RDP.

**Comment by ReinhardBiegelIntech** [comment]
Same, except the background is white in my case.

**Comment by pschonmann** [comment]
I have same problem but with @ in password.
In my case its caused by "RDP bug"
https://superuser.com/questions/1149165/altgr-randomly-stops-working-on-windows-10

When i disconnect from all RDP sessions, its working again.

**Comment by splashote** [comment]
Same on Windows 7.

**Comment by ReinhardBiegelIntech** [comment]
Fixed for me with 2.5.2

**Comment by pschonmann** [comment]
Win 7 on Remote and Client side 2.5.2, black window over RDP

**Comment by hagbartus** [comment]
Same here with RDP to a Win 2008 Server. I dont know why they have to render the login page with OpenGL 2+ which is not supported by Windows Remote Desktop.. 
I use that bash script from https://social.technet.microsoft.com/Forums/windowsserver/en-US/c8295ef8-3711-4576-9293-2c4965280165/opengl-and-remote-desktop?forum=winserverTS 
as a workaround, but its still very annoying..

**Comment by skaa** [comment]
> I worked around it by guessing where to click and use KeePass auto-type to enter username and password

@affinityv can you post your auto-type keystroke sequence?

**Comment by iamdroppy** [comment]
Same here.

**Comment by sggalan** [comment]
Changing to 32 bit color depth may solve the problem in some cases (mine at least). The issue is obviuosly related to color depth in the framebuffer settings. Remote desktop connections use to force/change to low color depth so unexpected problems may arise when configuring nexcloud remotely.

**Comment by m3lt0r** [comment]
Also happens with archlinuxarm on a rpi4 with i3 as the window manager.

**Comment by nescravana** [comment]
The same happens in a MacBook Air OSX 10.15.4 , nextcloud client v.2.6.4satable (b 20200303). The login screen appears during less than a second, being replaced by a black screen with a top horizontal blue bar (a couple of pixels with).

**Comment by nescravana** [comment]
WORKAROUND (working on client v.2.6.4satable (b 20200303) on OSX 10.15.4  and nextcloud server v15.0.2.):
uninstall nextcloud client v2.6.4, install nextcloud client v2.6.0 (you can get it from https://download.nextcloud.com/desktop/releases/Mac/Installer/), add you accounts, remove nextcloud client v2.6.0 and install v2.6.4 again! 
All accounts are still operational.

**Comment by FlexW** [comment]
Does this issue still exist with a recent client version (3.2.1)?
