### ISSUE TITLE
Could NOT find Qt5Keychain (missing: QTKEYCHAIN_LIBRARY)

### ISSUE THREAD

**Issue by phpdrill** [nextcloud/desktop#1143]
### Expected behaviour
Cmake for nextcloud desktop client should run without an error.

### Actual behaviour
Cmake shows the error 'Could NOT find Qt5Keychain (missing: QTKEYCHAIN_LIBRARY)'.

### Steps to reproduce
1.
add Qt5.12.2, zlib-1.2.3-bin, openssl-1.0.2 and qtkeychain-master to Environment Variables
2.
git clone https://github.com/nextcloud/desktop.git
cd desktop
mkdir build
cd build
as described at (https://github.com/nextcloud/desktop)
3.
Run 'cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=..\..\install -DCMAKE_BUILD_TYPE=Debug',
as described at [#426](https://github.com/nextcloud/desktop/issues/426), comment by camilasan, 2018-06-17.

Problem:
https://github.com/frankosterfeld/qtkeychain only contains the files needed for QTKEYCHAIN_INCLUDE_DIR.

There are different instructions out there how to compile qtkeychain, but - and this is the main problem - none of them result in the creation of a lib file, which would be needed for QTKEYCHAIN_LIBRARY:
https://github.com/frankosterfeld/qtkeychain/wiki, Compilation on Windows
https://github.com/owncloud/client/blob/master/doc/building.rst, Windows Development Build, Step 5

### Client configuration
Client version: commit 37f709fe342461941bfb84a24bfad30b175624cd

Operating system: Windows 10 Pro, 64 bit

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Users\\[username]\documents\projects\desktop

**Comment by phpdrill** [comment]
After hours of trying, I found the solution:

Instead of compiling qtkeychain with
`cmake -G "MinGW Makefiles" .`
`mingw32-make`
--> doesn't work (creates 32bit qt5keychain.dll.a),

I built it, similarly to and inspired by the instructions at https://github.com/nextcloud/desktop, "Compile and install", "Windows", with
`cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=path-to-install-folder/`
`cmake --build . --target install`
--> works like a charm (creates 64bit lib).

After adding the path with the lib and include folders to my Environment Variables, I was able to compile and install nextcloud desktop client with
`cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=path-to-install-folder/ -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1`
`cmake --build . --config Debug --target install`
as described at https://github.com/nextcloud/desktop, "Compile and install", "Windows".

**Comment by sobhanb-eth** [comment]
@phpdrill can you please tell me how did you get the qt5Keychain built? i tried everything nothing seems to work, can you please guide me in building it please?
