### ISSUE TITLE
nextcloudcmd doesn't watch remote changes

### ISSUE THREAD

**Issue by devel0** [nextcloud/desktop#1144]
### Expected behaviour

nextcloudcmd doesn't have a flag to maintain the process in a loop forever and sync watching local and remote changes. I wrote a simple set of [bash scripts](https://github.com/devel0/docker-cloud/tree/master/cloud_sync_cmdline) for Linux that would workaround this issue until it can be integrated directly into nextcloudcmd that useful mostly for headless server mode. Some [README](https://github.com/devel0/docker-cloud) info here.

### Actual behaviour

execute nextcloudcmd sync local vs remote only when called then it stop ( ie. it doesn't watch for remote changes )

**Comment by EricWVGG** [comment]
related: https://github.com/qcif/nextcloud-sync-cron

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
