### ISSUE TITLE
sever replied not acceptable

### ISSUE THREAD

**Issue by silent-mobius** [nextcloud/desktop#1145]
### Expected behaviour
Tell us what should happen
just installed nextcloud 15 - trying to upload data to server: getting --> "server replied: not acceptable"
### Actual behaviour
connected with desktop client for linux on centos7.6
### Steps to reproduce
1. yum   install nextcloud-client -y 
2.nextcloud-client &
3.

### Client configuration
Client version:  2.3.3

Operating system: Centos7.6

OS language: english

Qt version used by client package (Linux only, see also Settings dialog): 5.9.2

Client package (From Nextcloud or distro) (Linux only): from Nextcloud epel repo(fedora)

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Operating system:

Web server: apache2

Database: mariadb

PHP version: 7

Nextcloud version: 15

Storage backend (external storage): hostgator

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
Could you please try a more recent server version (22) and client version (3.2.2) and see if the problem still exists? If not, please close the issue.
