### ISSUE TITLE
IP FOR DEFAULT

### ISSUE THREAD

**Issue by andresdev16** [nextcloud/desktop#1148]
Hello, If I want the client to read only one ip by default, where in the code could I configure that?

**Comment by FlexW** [comment]
Sorry, I can not understand what you want. Please keep in mind that this is not a support forum. If you need help, please go to help.nextcloud.com

**Comment by andresdev16** [comment]
@FlexW I mean, the client asks you for a server URL when you start for the first time, that's your nextcloud server URL. I want to set up an URL for default for my desktop client, how can I do that?

**Comment by FlexW** [comment]
That is just possible if you compile the client yourself, or if you are a paying customer of Nextcloud, we will do this for you.
