### ISSUE TITLE
QNetworkReplyHttpImpl

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/desktop#115]
nextcloud client can't connect to server since I upload pictures from mobile app. I guess this is the cause because connection was ok before.

**Expected behaviour**
nextcloud-client can connect to server

**What happens**
nextcloud-client stay grey "Not connected"
* all I tested from different way:
  * web gui access is ok with the same account
  * smartphone app access is ok with the same access
  * I tried to "disconnect" and then "reconnect", password asked without error but stay disconnected
  * **connection ok from windows** install 2.3.3
  * connection ok to another nextcloud instance on the same server
* technical infos:
  * nextcloud-client version: 2.3.3 from ppa, also tested with 2.3.3 and 2.3.2 from AppImage, same result.
  * installed on xUbuntu 17.10, up to date
  * server 12.0.3 on Debian 9, apache 2.4, MariaDB

**nextcloud --logfile /home/user/nc.log**
```
01-08 19:28:57:301 5100 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 3
01-08 19:29:04:665 5100 unknown: QIODevice::read (QNetworkReplyHttpImpl): device not open
```

**Server log** : nothing

It looks like something went wrong with client on xUbuntu, but it seams related to data on server!

**Comment by esprit-libre** [comment]
I also tested:
* same instance, same account, owncloud-client 2.4.0: same result, not connected
* same instance, other account, nextcloud-client 2.3.3: connected and syncing

**Comment by esprit-libre** [comment]
Last but not least...
* I have the same problem on another computer which synchronize the same folders
* I try to suppress account config, and then recreate it, and it works !

So my workaround is to suppress and then recreate account config, but something happened because my both linux desktop fail connection at the same time... Any idea ?

**Comment by DominiqueFuchs** [comment]
@esprit-libre It's been quite some time and both desktop and mobile apps went through fundamental improvements and changes since then. I'd assume that this issue is no longer relevant?

**Comment by esprit-libre** [comment]
Hello,
you're right I don't have the problem anymore since I deleted and recreated the config. The problem did not appear since that.
I close the issue.
