### ISSUE TITLE
How to run/debug the client for Linux?

### ISSUE THREAD

**Issue by phpdrill** [nextcloud/desktop#1151]
I was able to compile the client on Linux, as described in the wiki.

But now, how can I run and debug the client (on Linux)?

Which is the recommended/official way to develop for Linux (IDE, etc.)?

OS: Debian 9

**Comment by phpdrill** [comment]
Okay, I found a solution.

With the following command I was able to start, run and debug the project in Code::Blocks.

`cmake -G "CodeBlocks - Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=path-to-install-folder/ -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1`
`make install`

Would it be possible to add these lines as example for a working IDE for Linux in the wiki?

**Comment by FlexW** [comment]
The desktop client can be started like any other application on Linux.
