### ISSUE TITLE
Chunked upload not working / chunkSize setting ignored

### ISSUE THREAD

**Issue by Whissi** [nextcloud/desktop#1152]
### Expected behaviour
I should be able to upload files >10MB using Desktop client.

### Actual behaviour
I am unable to do that. Server reports too large body,

### Steps to reproduce
1. Make sure your webserver is limiting max body size for `^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/)` to ~12MB which should be enough according to documentation [for client](https://docs.nextcloud.com/desktop/2.5/advancedusage.html#configuration-file) [for web](https://docs.nextcloud.com/).
2. Make sure that you can upload files a 1GB file via web and confirm chunked transfer in browser developer tool's network tab,
3. Put the same file into your folder on your local disk you synchronize with NextCloud client

### Client configuration
Client version: 2.5.0, 2.5.1, 2.5.2 is failing

Operating system: Windows 7/10

OS language: English

Installation path of client: `C:\Program Files (x86)\Nextcloud\nextcloud.exe`

### Server configuration
Operating system: Gentoo GNU/Linux

Web server: nginx/1.15.9

PHP version: 7.3.3

Nextcloud version: 15.0.5

Storage backend (external storage): Server disk, no extern storage

### Logs

1. Client logfile:
```
#=#=#=# Syncrun started 2019-03-19T20:04:30Z
#=#=#=#=# Propagation starts 2019-03-19T20:04:31Z (last step: 1638 msec, total: 1638 msec)
||synctest//test1.dat|INST_NEW|Up|1552998581||1030087344||2|Error transferring https://example.org/remote.php/dav/uploads/myusername/3478485999/00000001 - server replied: |413|0|0||||
#=#=#=# Syncrun finished 2019-03-19T20:04:43Z (last step: 11376 msec, total: 13015 msec)
```
2. Web server error log:
```
2019/03/19 21:04:42 [error] 7461#7461: *179339 client intended to send too large body: 42321239 bytes, client: 1.2.3.4, server: example.org, request: "PUT /remote.php/dav/uploads/myusername/3478485999/00000001 HTTP/2.0", host: "example.org"
```

3. Server logfile: nextcloud log (data/nextcloud.log): No errors logged - normal because webserver blocked request.

* Because desktop client is using same endpoint like web browser (`/remote.php/dav...`) I can say for sure that my server configuration is working as expect.
* According to documentation, client should use 5MB chunks by default - that's not the case or I wouldn't see that error.
* I tried to add `chunkSize=10485760` to `[General]` in my `nextcloud.cfg` on the Desktop but it looks like the client is ignoring that setting.
* It was working when I started with Nextcloud (~v12). Server configuration, aside regular webserver/PHP update, wasn't touched. So it's either a client software problem or a server software issue.

**Comment by Whissi** [comment]
It works when I downgrade back to v2.3.3.1. So this is clearly a client issue.

**Comment by wiswedel** [comment]
Might be connected to https://github.com/nextcloud/server/pull/7056 which came in with Nextcloud 13.

Documentation for that server setting coming in via https://github.com/nextcloud/documentation/pull/5401

**Comment by Whissi** [comment]
I am not sure if I understand this comment, jfyi:
```
php -d memory_limit=-1 occ -v config:app:get files max_chunk_size
```
returned nothing so I run
```
$ php -d memory_limit=-1 occ -v config:app:set files max_chunk_size --value 10485760
Config value max_chunk_size for app files set to 10485760
```
which is now also returned by the previous value.

I restarted Nextcloud client (using v3.0.3 at the moment) and put a 206MB file in my Nextcloud folder to sync up but server rejected with
> client intended to send too large body: 100000000 bytes

error. So still no chunking is happening. I don't even have `chunkSize` in my `nextcloud.cfg` at the moment so default value of 5242880 (=5MB) should be used. Server allows up to 12M.

Could you please elaborate how the server setting I just set is used? Are clients supposed to fetch this setting for example?

**Comment by FlexW** [comment]
That is most likely a server configuration issue. Does the issue still exist wit a recent server (22) and a recent client (3.2.2)? If not, please close the issue.
