### ISSUE TITLE
Copy private link missing domain

### ISSUE THREAD

**Issue by caillou** [nextcloud/desktop#1156]
### Expected behaviour

When copying a private link from the `macOS`, the domain should be present/

### Actual behaviour

The generated link does not include a domain, e.g. `https://:443/index.php/f/185`

### Steps to reproduce

1. Install the `2.5.1final (build 20181204)` desktop client on `macOS`
2. Right-click on a file in the Finder.
3. Click `Copy private link to clipboard.`

### Client configuration

Client version: `2.5.1final (build 20181204)`

Operating system: `macOS 10.14.3 (18D109)`

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): `-`

Client package (From Nextcloud or distro) (Linux only): `-`

Installation path of client: `/Applications/nextcloud.app`

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?

**Comment by caillou** [comment]
🎉  Seems to work now. Thank you!
