### ISSUE TITLE
Connect to Nextcloud: Change buttons to more descriptive wording

### ISSUE THREAD

**Issue by jdittrich** [nextcloud/desktop#1158]
### Expected behaviour
As a new user, I want to set up the client with my nextcloud sync client app. 

### What I did 
1) I installed the sync app.
2) In the "Connect to nextcloud"-dialog I have two choices: 
     - Register with a provider
     - LogIn 

![image](https://user-images.githubusercontent.com/3416487/54878788-9c0d6b80-4e31-11e9-834b-860faa6ad173.png)

I assumed that "Register with a provider" means that I can connect to a service if I do not host myself, so I choose this (as I do not self-host), similar to what  [DavX5](https://www.davx5.com/) or [gnome 3 online accounts is doing](http://ubuntuhandbook.org/wp-content/uploads/2019/02/gnome-online-accounts-600x342.jpg).

However, it seems to be that at "Register…" I can create a new nextcloud space at a provider. 

### Possible fix

Change button labels to: 

"Register for a nextcloud"
"Connect to existing nextcloud"

This would be longer labels, but there is plenty of space.

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system:Ubuntu 18.04

Client package (From Nextcloud or distro) (Linux only): AppImage

**Comment by jdittrich** [comment]
ping @jancborchardt

**Comment by jancborchardt** [comment]
Sorry for the late reply here too @jdittrich. :)

- The "Register" button should actually say "Sign up with a provider" as we call it "Simple Sign up".
- We used to have the "Log in" button called "Connect" but as far as I remember it felt confusing and we changed it to log in since that is universal language for that function. Yes, we do have the step inbetween of putting in your server address, but it is a "Log in" action. Maybe "Log in to your Nextcloud"?

**Comment by jdittrich** [comment]
> …"Log in to your Nextcloud"

Makes sense, would have it improved for me. 

> "Sign up with a provider"

not sure if this would have solved the problem: In my case "provider" could have been my existing one or a new one. (it has a bit stabilized that _sign up → new account_ and _sign in → existing account_ which matches the current wording, but it is still confusing). 

Given that the action is done only once, a brief explanatory text might help (since a perfect 1-3 word label is sometimes not possible to find)
