### ISSUE TITLE
Connect to nextcloud - login/register: Carousel confusing

### ISSUE THREAD

**Issue by jdittrich** [nextcloud/desktop#1159]
### Expected behaviour
As a new user, I want to set up the client with my nextcloud sync client app. 

### What I did 
1) I installed the sync app.
2) Use the  the "Connect to nextcloud"-dialog

![image](https://user-images.githubusercontent.com/3416487/54878766-7e400680-4e31-11e9-82b9-47b4826047d2.png)

There is a large blue icon and text that changes from time to time in a carousel pattern. I consider this a minor issue, but it is slightly confusing (does what is shown influence what I "register" or "login" to?). Also, [carousels are known to be a source of usability problems](https://www.nngroup.com/articles/designing-effective-carousels/).

### Possible fix
Consider ditching the carousel in favor for a short text outlining the advantages of nextcloud. 

The space for text could also be used to explain the options below. 

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system:Ubuntu 18.04

Client package (From Nextcloud or distro) (Linux only): AppImage

**Comment by FlexW** [comment]
I think this issue does not apply anymore. The wizard has been redone, and slideshow does not move forward automatically anymore.
