### ISSUE TITLE
Connect to Nextcloud Wizard: Go back at login screen

### ISSUE THREAD

**Issue by jdittrich** [nextcloud/desktop#1161]
### User Story 

I want to setup my nextcloud

### What I did

At the "connect to nextcloud"-Wizard I clicked login (see #1158) and was confused. I wanted to go back, but the only thing I could do was closing the wizard.

### Possible solution

Provide  a back button fitting the back/next pattern. 

There is a "Register…" button present, doing basically the same, but it looks as if it relates to the URL provision, not like an alternative to it.

**Comment by FlexW** [comment]
This should be solved with https://github.com/nextcloud/desktop/pull/2895
