### ISSUE TITLE
Version 2.5.1final (build 20181204, login-nothing happens

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/desktop#1162]
### Actual behaviour
I have installed the latest version of the desktop client. I had the outdated version removed automatically.
A permission request was displayed in the browser window that I filled out. The credentials were definitely correct.
Nothing would fit in the Windows client afterwards. At the top left you see "No connection to Nextcloud on...".

#1038 ('overwriteprotocol' => 'https') is set up in config.php.

### Client configuration
Client version: Version 2.5.1final (build 20181204

Operating system: Win 7 Serv. Pack 1

OS language: German

Installation path of client:
"C:\Program Files (x86)\Nextcloud\nextcloud.exe"

### Server configuration
Apache
PHP 7,2

Nextcloud version: 15.05

**Comment by Wastl2IT** [comment]
Same here on 3 PCs, each running Win 10. Client Version 2.5.2 didn't solve it.

**Comment by Schneehexe** [comment]
Unfortunately, nothing happens, and there is no answer.
Meanwhile I have version 15.07 on the server and 5.5.2git as client (build 20190319).
The same problem still, the client can't login?
Is someone working on a solution or do I have to install an older client version again?

**Comment by Wastl2IT** [comment]
du musst auf 2.3.3 zurückgehen. seit 2.5.0 geht es mir wie dir, egal welche Version, incl. NC16.

**Comment by freechelmi** [comment]
Can you show a screenshot of the login windows when it fails ? 

Do you have some https reverse proxy in front ?

**Comment by Wastl2IT** [comment]
2.5.2 is working for me, now. But the setting "use system-proxy" does not work. I have to configure it manually

**Comment by Schneehexe** [comment]
Hello,

Thank you so much for wanting to help. But I may join my previous speaker and can say that version 2.5.2 is now working for me without having to make any settings.

It's really impressive how much faster the synchronization is now.

So everything's fine, topic is done for me anyway.

**Comment by Volker-K** [comment]
possibly same error as here https://github.com/nextcloud/desktop/issues/901 ?

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
