### ISSUE TITLE
linux desktop client slowness

### ISSUE THREAD

**Issue by obsidiannonparity** [nextcloud/desktop#1165]
### Expected behaviour
fast download speeds
### Actual behaviour
slow download speeds. average around 10Mbps
### Steps to reproduce
1.Download 2.5.1 nextcloud and install(or use appimage)
2. Sync files
3.

### Client configuration
Client version:2.5.1

Operating system: Ubuntu 18.04

Client package (From Nextcloud or distro) (Linux only): tried both

Installation path of client: currently using appimage 2.5.1

If I revert to the 2.3.3 appimage speeds return to normal . I found an issue about sync errors that mentioned disabling ssl. I tried that in the 2.5.1 installation as a test and that has normal speeds again but switching back to https and it is slow. 

I only tested 2.3.3 with ssl enabled but it had fast speeds. I was hitting 250 to 300 Mbps instead of the 10Mbps with ssl enabled on 2.5.1

Server error logs are virtually blank and nothing was added during my most recent testing window.

**Comment by FreeMinded** [comment]
I'm also having issues with the Nextcloud client 2.5. The interface often freezes completely. It recovers after some time, sometimes. But it also crashes quite often and needs to be started again. I have version 2.5.2-20190319.015224~bionic1 from the nextcloud-devs/client PPA installed.
I'm happy to provide additional info.

**Comment by dctrud** [comment]
I also experience low sync speeds with 2.5.2. I am syncing from a co-lo server with 100Mb/s connection. Downloading large multi GB files, I observe ~70-80Mb/s downstream when my client is the 2.3.3 AppImage. With `2.5.2-20190319.015224~bionic1` from the PPA I see <10Mb/s.

**Comment by otakugenx** [comment]
I am running 2.6.1git on Linux Mint Cinnamon 19.3 and it is so slow.  I just set this machine up and I am syncing 12GB and it is going apx 500k.  I am syncing to a major Nextcloud provider.

**Comment by cieska** [comment]
I lived with this for ages. My client on OpenSUSE KDE from suse's official repo. Larger files may be catching with some sped but photos or smaller pictures takes forever to sync on Gb LAN. I have for example 10GB Pictures folder with 60000 files and 1000 folders this took about two or three days to sync. My desktop with decent Xeon CPU. when syncing one core spiking 100% for 70% cycles. LAN activity pretty much 0% just spike every 5s and you can see one file synced. My server 4core  Atom pretty much idle. 
For example, now I'm syncing 12GB photo folder from which 6GB was already on the server, it took 12h already and showing another 3-4untill finish. 
Screenshot attached with system monitor CPU usage there is spikes for 100% are from  NX client and on the left CPU usage of my server. 
My system usually up to date. Now with 16.0.x version. Apache. Ubuntu 18.0.4 usually up to date. 

![Screenshot_20200108_002744](https://user-images.githubusercontent.com/41318524/71940524-8abe0180-31ae-11ea-84d8-fbfd3b8e17df.jpg)

**Comment by claell** [comment]
@obsidiannonparity and @dctrud as you seem to be the only ones that actually made sure that this issue was caused by the client and not for example a slow server, is this still happening for you with current versions?

In the other cases, can you make sure that the client is causing your problems? Regardless there at least has been a problem, just wanting to know, whether it is still there.

**Comment by dctrud** [comment]
@claell I have not seen an issue more recently - but I am now using Fedora 31's packaged client... `2.6.4-1.fc31`

**Comment by cieska** [comment]
Since then there are lots of updates vent through and there was always slowness on the client site to check if it's everything in sync. I don't guarantee but I think since server version 20.0.x (when it become stable) Nextcloud got wings. Desktop client and the web become more snaps and responsible. 
I have no issues at the moment.
