### ISSUE TITLE
Incorrect time stamps in activity 

### ISSUE THREAD

**Issue by sciurius** [nextcloud/desktop#1166]
Desktop client 2.5.1 on Fedora 29.

### Expected behaviour
The activity window should show when activities took place.

### Actual behaviour
It often shows just "now".
For older entries, it is something similar to "2 days ago".
This is virtually useless. Please provide a (preference to select a) iso6801 time stamp.

(Just an example. The README.txt files were synched with one hour in between yet all show "now".)

![scrot20190325190444](https://user-images.githubusercontent.com/1118804/54943412-1c62c800-4f29-11e9-8f3e-b97248268bef.png)

**Comment by geez0x1** [comment]
I am seeing the same issue, with 2.5.1git from the Debian repositories. Every single file in Activity says "now", even those synced more than 5 days ago.

**Comment by sciurius** [comment]
Since there is no response I did it my way.

[nextcloud-client-lognow.patch](https://github.com/nextcloud/desktop/files/3190935/nextcloud-client-lognow.patch.txt)

**Comment by sciurius** [comment]
Fixed in 2.6.2.
