### ISSUE TITLE
Big files do not upload ("chunks on server do not sum up") due to QT bug

### ISSUE THREAD

**Issue by tribut** [nextcloud/desktop#1171]
### Expected behaviour
Big files should upload when server supports http2.

### Actual behaviour
Upload fails with "server replied: (Chunks on server do not sum up to X but to Y bytes)". See [this bug report against the owncloud client](https://github.com/owncloud/client/issues/7020). The problem is apparently caused by a [bug in QT](https://bugreports.qt.io/browse/QTBUG-73947), so I would appreciate if you could release a version that disables http2 until this is fixed ([patch from owncloud](https://github.com/owncloud/client/commit/a58e43998d5fde3feef00934f1b81bbe4dfb6ac2)).

### Client configuration
Client version: 2.5.2git

Operating system: Ubuntu cosmic

OS language: en_US

Qt version used by client package (Linux only, see also Settings dialog): 5.11.3

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: /usr/bin/nextcloud

**Comment by tribut** [comment]
Disabling http2 by using

~~~
Protocols http/1.1
~~~

in the appropriate vhost is a workaround, for anyone also experiencing this.

**Comment by btong** [comment]
@tribut thanks for the workaround, it worked for me. would be good if there were no workaround necessary.

I was using nginx with http2 as a proxy to my nextcloud instance running through apache. with http2 disabled I can do large file uploads again.

**Comment by mgallien** [comment]
Please can you test with latest release because if I understand correctly this bug is now fixed because the Qt version that we are using includes the fix for HTTP2 ?
