### ISSUE TITLE
Unusable error message

### ISSUE THREAD

**Issue by iav** [nextcloud/desktop#1173]
Some error occures, I don't know what error.
Message unreadable:
![2019-03-29 00_50_55-](https://user-images.githubusercontent.com/325961/55198179-a1fea600-51bd-11e9-9ad2-2185a17cab9b.png)
sorry, I have no access to server logs.
Windows 7/64,
Nextcloud client Version 2.5.1final (build 20181204). 
Built from Git revision b37cbe on Dec 4 2018, 13:30:31 using Qt 5.11.1, OpenSSL 1.0.1h 5 Jun 2014

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.
