### ISSUE TITLE
Feature request - Password Protect user interface 

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/desktop#1174]
Hi

I have a request to add a password for user interface on windows client. We are using nextcloud as a simple and realible backup tool for syncing user files from desktops to nextcloud server. But unfortunately we’ve hot few ‘experts’ that making changes in nextcloud desktop clinet configuration and basically the backup is no longer working. The simple password that would protect desktop client configuration would be great.

**Comment by jospoortvliet** [comment]
This is a valid feature, and could be done. But just to set expectations, looking at our roadmap - unless a volunteer does this, we won't have time for this for at least a year, probably much more, unless there is customer demand.

**Comment by mdeyerin** [comment]
Bump. I'd like to see this feature as well.

**Comment by Rello** [comment]
Hello,
I am closing this as it is not on our roadmap
