### ISSUE TITLE
Make client multithreaded

### ISSUE THREAD

**Issue by realies** [nextcloud/desktop#1177]
Currently client version `2.5.1final` it only goes up to 100%-105% usage on a 4 core/8 thread macOS system where max usage is 800%. This indicates that most of the work done by the client is single threaded and not optimised for multicore/multithreaded hardware.

This not only makes the client not scale up in performance by the most significant way new computer systems get better, but makes one of the cores significantly hotter than the rest, ramping up power usage and cooling systems more than it could have if it the load was spread over the available cores. This is especially important for mobile systems.

**Comment by STonEDSTonE** [comment]
Thats a very good idea, i would also like to see that!

**Comment by FlexW** [comment]
That is a good idea. We are already optimise the code and try to utilise newer hardware. Unfortunate it is a long process and it is not always easily possible to use multiple cores for every task. I will close the ticket because this a never ending story.

**Comment by realies** [comment]
@FlexW, this is not a never-ending story. Even if gradual, you can refer to this issue in upcoming changes and planning. Please reopen the issue.

**Comment by ChenSun-Phys** [comment]
Agreed. I'm in a situation where I believe the initial upload is bottlenecked by the client. I'd imagine that with multi-thread enabled it could make the initial indexing much faster. I also vote for reopening this issue.
