### ISSUE TITLE
Force sync does not reattempt failed uploads

### ISSUE THREAD

**Issue by realies** [nextcloud/desktop#1178]
Uploads that fail with `413 Requested Entity Too Large` due to reverse proxy or web-server configuration limitations are not retried when the force sync option is selected. The client activity log falsely displays new messages timestamped as `now` when force sync is reattempted even when the reverse proxy or web server configuration limitations are lifted. Renaming or changing files that can't be uploaded makes the client reattempt the upload which is the expected behaviour when the upload fails for some reason and force sync is selected.

Server: 15.0.5, Client: 2.5.1final on macOS 10.14.3

**Comment by kylepaulsen** [comment]
I'm no expert, but this is what I figured out:

Look for a hidden .db file in the root nextcloud folder you chose to sync from. It might be named something like: `._sync_4c7450a8f62e.db`

If you quit nextcloud and either move this file out (or delete it) and then restart nextcloud, it should resync all failed files. Keep in mind this .db file has some settings data you might have set up.

Alternatively you can use a sqlite database viewer/editor like https://sqliteonline.com/ and load up that database file. You can run `DELETE FROM 'blacklist';` as a command to remove all error logs from that DB file (these are the records that prevent the client from trying to resync right away). Place the edited db file back and run nextcloud and it should try syncing the failed files again.

**Comment by FlexW** [comment]
Does this issue still apply with a recent server (21) and recent client (3.2.2)?
