### ISSUE TITLE
Make it possible to "Selective sync" from the file manager

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/desktop#118]
Would be nice to have this in the context menu. Brought up by my wife in a discussion why DB is so much easier to use than Nextcloud.

**Comment by pieter-groeneweg** [comment]
"File Manager" as in the browser UI? Right?

Yes I really would appreciate that.
ie. Nextcloud now allows group folders. That is awesome. However, they tend to grow big.
It would be nice if the client would only sync the folders coming from the skeleton. And it's subs (to the 500MB max)
It is of course great that the desktop client allows to select what to sync, but it is after you discovered your tiny netbook just synced a new folder and downloaded 499MB of images.... :(

So none skeleton and group folders should not be synced by default only if user allows (preferrably from brower UI) and a possibility to exclude folders also from the web ui...

**Comment by nickvergessen** [comment]
> "File Manager" as in the browser UI? Right?

No, your local file manager: windows explorer, ubuntu nautilus, linux mint nemo, ...

**Comment by pieter-groeneweg** [comment]
But it always comes after it is synced in the first place... As content owner and as admin I would like to have a feature to determine and decide what can be synced or not... as user I don't want to discover a 499MB sync job after it happened... it would be nice if that could be managed from the browser UI so it can be configured beforehand...

**Comment by AndrewBucklin** [comment]
Or even better:  Files on demand [#17](https://github.com/nextcloud/client/issues/17)

**Comment by michaelstingl** [comment]
Main thread is here: https://github.com/nextcloud/desktop/issues/184

BTW Upstream project is experimenting with this in the [2.5.0 alpha1](https://owncloud.org/news/owncloud-client-goes-virtual-sync-files-demand/). Please help testing and provide feedback.

**Comment by jospoortvliet** [comment]
The best solution would be a fuse mount, which is what Dropbox uses. A work-around is the files-on-demand thing ownCloud did, which has a series of issues but is easier to add to the current client. We're trying to figure out what the best way to do this is.
