### ISSUE TITLE
[REQ] Share by mail (public link)

### ISSUE THREAD

**Issue by silvershadowcc** [nextcloud/desktop#1180]
Hi, I would very much like to see the share by mail function added to the desktop client. It is included in the mobile app as well.

So when right-clicking a file and selecting the share option, not only being able to choose a user or (remote), but also (mail) when entering an email address. Then it could be sent through smtp used in the website.

**Comment by biva** [comment]
Would you like this within Thunderbird? See https://github.com/nextcloud/nextcloud-filelink/issues/52

**Comment by silvershadowcc** [comment]
@er-vin It appears as though this feature has been added (in 3.1.1. at least).

**Comment by er-vin** [comment]
Yes indeed, that's thanks to @allexzander work.
