### ISSUE TITLE
Double-slash issue still in 2.5.1final

### ISSUE THREAD

**Issue by jernst** [nextcloud/desktop#1181]
I just retested this: https://github.com/nextcloud/server/issues/10084
and the double-slash issue still produces a 500. Per the comments in that thread, it is a client issue so I am filing this here.

**Comment by sidoudou** [comment]
I think it reappeared in 2.5.2
After updating my windows client (which I haven't updated for several months) to 2.5.2 everything worked fine except for renaming or moving any file (doing it through the android app for example works just fine).
It shows a forbidden 403 error on the log and says that the full path //remote.php/dav/files..... bais out of base uri.
Everything went back to normal after I removed the trailing slash from the account url in nexcloud.cfg

**Comment by camilasan** [comment]
I recalled thins being fixed. Did you try 2.5.3rc1?

**Comment by sidoudou** [comment]
Well as I said, I'm on 2.5.2 and following the stable channel so I wasn't aware of the 2.5.3rc1. I might give it a try later and restore the trailing slash in the config file to see what happens.
Have you tried to replicate the bug using the 2.5.2 ?

**Comment by KevCanon** [comment]
I got the same problem with `//remote.php/dav/files..... is out of base uri` in version 2.6.1stable-Win64 (build 20191105)

**Comment by FlexW** [comment]
Is this still relevant? If yes, please reopen the ticket.
