### ISSUE TITLE
Client at 100% when IPv6 is not seen

### ISSUE THREAD

**Issue by bfrmtx** [nextcloud/desktop#1183]
### Expected behaviour
If server not seen - do nothing

### Actual behaviour
Client polls with 100% CPU

### Steps to reproduce
1. Connect to server using IPv6
2. sync - goes well
3. Connect to a network where this IPv6 is NOT reachable (e.g. IPv4 ONLY network)
4. client runs at 100% CPU

### Client configuration
Client version: Version 2.5.1git. 

Operating system:
SuSE Linux Tumbleweed

OS language:
english

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5

Client package (From Nextcloud or distro) (Linux only):
Version 2.5.1git. 

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by toweih** [comment]
duplicate?
https://github.com/nextcloud/desktop/issues/942

**Comment by bfrmtx** [comment]
That sounds similar - I guess it is the same reason
Since my network falls back to IPV4 too often, I tried the "hardcoded" IPV6
