### ISSUE TITLE
MacOS Finder Sidebar Icon Issue

### ISSUE THREAD

**Issue by rawbertp** [nextcloud/desktop#1187]
### Expected behaviour
I don't know what the Finder sidebar icon (favorites) actually should look like, probably like a nice little folder or so.

### Actual behaviour
A boring gray box is shown instead.
<img width="186" alt="Bildschirmfoto 2019-04-05 um 10 33 30" src="https://user-images.githubusercontent.com/12150805/55615070-c561bc00-578e-11e9-9d69-46a8904d8355.png">

### Steps to reproduce
1. Set up a synced folder in NC client
2. Open finder

### Client configuration
Client version: 2.5.1final (build 20181204)

Operating system: macOS Mojave 10.14.4 (18E226)

OS language: German

**Comment by mylos** [comment]
Same problem on my Mac as well.
Client version: 2.5.1final (build 20181204)
Operating system: macOS Mojave 10.14.4 (18E226)
OS language: English

**Comment by rawbertp** [comment]
BTW it is working as expected with the Owncloud desktop client, so this definitely is an issue within the Nextcloud fork.

**Comment by maghog** [comment]
Same problem:
Client Version 2.5.2git (build 20190319)
macOS v10.13.6

**Comment by Javihache** [comment]
Same Problem with 2.5.1final (build 20181204) on Mac OS Mojave 10.14.5

**Comment by ntompson** [comment]
Same problem for me. Client version 2.5.2git (build 20190319), macOS Mojave 10.14.5. I wonder: what should the icon look like?

**Comment by gt-h6k** [comment]
The sidebar is a gray icon because is not transparent background.
Resolved using logo icon without background color.


https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15-SW15
>3.Create a complete set of sidebar icons. These icons must be template images—monochromatic images that are drawn just using black and transparency. The icons must use the following filenames and sizes:

**Comment by tobiasKaminsky** [comment]
PR was merged too late, will be in 2.5.4 (if) or 2.6.
