### ISSUE TITLE
GUI behaviour, cut off,  2.5.1 Windows, Build 20181204

### ISSUE THREAD

**Issue by victorbw** [nextcloud/desktop#1188]
### Expected behaviour
connect with any account via client (windows: 2.5.1 b20181204)
allow your connection
connect & sync

### Actual behaviour
the gui is cutting off any button that is quite important to allow any kind of interaction with the server (allow etc).

### Steps to reproduce
1. uknown dependencies, use windows client version 2.5.1 build 20181204

### Client configuration
Client version: Windows 2.5.1 build 20181204

Operating system: Windows 10

OS language: Swiss-German

Installation path of client: C:\program files(x86)

Web server: httpd /apache 2.4

Database: mariadb 10.3.14

PHP version: 7.2

Nextcloud version: 14.06

### Logs

1. Client logfile: no error entries which could be related to gui 

2. Web server error log: no errors

3. Server logfile: no errors

![grafik](https://user-images.githubusercontent.com/8447071/55624406-044f3c00-57a6-11e9-90a0-a21fb331a839.png)

and yes, this is the whole gui, which means nothing is cut off.

Am I missing something?

**Comment by FlexW** [comment]
Does the issue still apply? If yes, feel free to open it again.
