### ISSUE TITLE
No nextcloud icon in mate-panel 1.12.2-1

### ISSUE THREAD

**Issue by sgargel** [nextcloud/desktop#119]
Launching `nextcloud` client I expect a tray icon but is not shown.

Nextcloud client version is:

Nextcloud it_IT () 2.3.3 on Ubuntu 16.04.3 LTS

````
$ dpkg -l | grep mate-panel && apt-cache show mate-panel
ii  gir1.2-mate-panel                                  1.12.2-1                                     amd64        GObject introspection data for MATE panel
ii  libmate-panel-applet-4-1                           1.12.2-1                                     amd64        library for MATE Panel applets
rc  libmate-panel-applet4-1                            1.8.0-0+trusty                               amd64        library for MATE Panel applets
ii  mate-panel                                         1.12.2-1                                     amd64        launcher and docking facility for MATE
ii  mate-panel-common                                  1.12.2-1                                     all          launcher and docking facility for MATE (common files)
Package: mate-panel
Priority: optional
Section: universe/x11
Installed-Size: 1586
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: MATE Packaging Team <pkg-mate-team@lists.alioth.debian.org>
Architecture: amd64
Version: 1.12.2-1
Replaces: mate-panel-common (<< 1.1.1-4)
Depends: libmate-panel-applet-4-1 (= 1.12.2-1), mate-desktop, mate-menus, mate-panel-common (= 1.12.2-1), mate-polkit, menu-xdg, python, dconf-gsettings-backend | gsettings-backend, libatk1.0-0 (>= 1.12.4), libc6 (>= 2.14), libcairo2 (>= 1.2.4), libcanberra-gtk0 (>= 0.17), libcanberra0 (>= 0.2), libdbus-glib-1-2 (>= 0.78), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.3), libgtk2.0-0 (>= 2.24.0), libice6 (>= 1:1.0.0), libmate-desktop-2-17 (>= 1.10.0), libmate-menu2 (>= 1.6.0), libmateweather1 (>= 1.6.2), libpango-1.0-0 (>= 1.18.0), librsvg2-2 (>= 2.14.4), libsm6, libwnck22 (>= 1:2.30.2-0ubuntu3), libx11-6, libxrandr2 (>= 2:1.2.99.3)
Breaks: mate-panel-common (<< 1.1.1-4)
Filename: pool/universe/m/mate-panel/mate-panel_1.12.2-1_amd64.deb
Size: 416904
MD5sum: cf4f567a4ddacb913a3e651ae7e8e2bd
SHA1: b449e8a67fc3ee1dfd41f98d8fac28ef6eccbe05
SHA256: 0f992566c6f3d8107e7209b44349be184c0fda435a49e9d9fdb7c6553b4b4384
Description-en: launcher and docking facility for MATE
 The MATE Panel is an essential part of the MATE Desktop, providing
 toolbar-like “panels” which can be attached to the sides of your desktop.
 They are used to launch applications and embed a number of other
 functions, such as quick launch icons, the clock, the notification area,
 volume controls and the battery charge indicator, and utilities ranging
 from weather forecast to system monitoring.
Description-md5: 9334d503600c11dc5d1bebf83b94366d
Homepage: http://www.mate-desktop.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 3y
Task: ubuntu-mate-core, ubuntu-mate-desktop, ubuntu-mate-cloudtop
````

**Comment by OtherSystems** [comment]
same problem on 18.04.1 when using snap.

**Comment by elvisef** [comment]
Same issue with version 1.16:

> mate-panel:
>   Zainstalowana: 1.16.2-1
>   Kandydująca:   1.16.2-1
>   Tabela wersji:
>  *** 1.16.2-1 500
>         500 http://ftp.pl.debian.org/debian stretch/main amd64 Packages
>         500 http://deb.debian.org/debian stretch/main amd64 Packages
>         100 /var/lib/dpkg/status
>

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).
There has been so many changes on the tray in recent releases...

**Comment by elvisef** [comment]
Alright. I will recheck this today. Thanks for info.

**Comment by mgallien** [comment]
> Alright. I will recheck this today. Thanks for info.

Did you had a chance to check ?

**Comment by sgargel** [comment]
Nextcloud AppImage on Ubuntu 20.04 is working.

**Comment by elvisef** [comment]
Sorry for the delay. I totally forgot about this (work, work work...).
Now I use an updated version of Debian, it's 10.x and the Nextcloud desktop icon IS visible.

Attaching screenshot from my desktop.
![2021-07-17_17-55](https://user-images.githubusercontent.com/25976749/126042737-73ec5651-009c-47e5-96a9-cc31d12d1926.png)

Software versions installed:

> mate-panel:
  Installed: 1.20.5-1
  Candidate: 1.20.5-1
  Version table:
 *** 1.20.5-1 500
        500 http://ftp.agh.edu.pl/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status


> nextcloud-desktop:
  Installed: 2.5.1-3+deb10u1
  Candidate: 2.5.1-3+deb10u1
  Version table:
 *** 2.5.1-3+deb10u1 500
        500 http://ftp.agh.edu.pl/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

So If this information is useful, maybe the problem was linked to a specific version ?
