### ISSUE TITLE
Client building No Windows installer being built NSIS 

### ISSUE THREAD

**Issue by plages** [nextcloud/desktop#1193]
### Expected behaviour
The Windows installer being built

### Actual behaviour
Only Linux binaries (.tar.Z, .tar.gz and .sh) are generated

### Steps to reproduce
1.follow the instructions for manually cross compiling as per the building.rst

2. do:
make .. -DCMAKE_BUILD_TYPE="Debug" ../client -DCMAKE_PREFIX_PATH=/usr/include/qt5/Qt5WebEngineWidgets;/usr/lib64/cmake -DCMAKE_TOOLCHAIN_FILE=../client/admin/win/Toolchain-mingw32-openSUSE.cmake -DOPENSSL_INCLUDE_DIR=/usr/include -DOPENSSL_ROOT_DIR=/usr/lib64 -DQTKEYCHAIN_INCLUDE_DIR=/usr/i686-w64-mingw32/sys-root/mingw/ -DQTKEYCHAIN_LIBRARY=/usr/lib64/libqt5keychain.so.1 -DLIBCLOUDPROVIDERS_INCLUDE_DIR=/usr/include/cloudproviders/ -DLIBCLOUDPROVIDERS_LIBRARY=/usr/lib64/libcloudproviders.so.0 

I've come to this after several errors. The build itself is succesfull but as described below no NSIS package is generated.

3. do: make package.
result:
  1%] Automatic MOC for target ocsync
[  1%] Built target ocsync_autogen
[ 11%] Built target ocsync
[ 11%] Automatic MOC for target kloudsync
[ 11%] Built target kloudsync_autogen
[ 29%] Built target kloudsync
[ 30%] Automatic MOC and UIC for target updater
[ 30%] Built target updater_autogen
[ 32%] Built target updater
[ 32%] Automatic MOC and UIC for target kloud
[ 32%] Built target kloud_autogen
[ 97%] Built target kloud
[ 98%] Automatic MOC for target kloudcmd
[ 98%] Built target kloudcmd_autogen
[100%] Built target kloudcmd
Run CPack packaging tool...
CPack: Create package using STGZ
CPack: Install projects
CPack: - Run preinstall target for: client
CPack: - Install project: client
CPack: Create package
CPack: - package: /home/philip/client-build/client-2.5.2.0git-Linux.sh generated.
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: client
CPack: - Install project: client
CPack: Create package
CPack: - package: /home/philip/client-build/client-2.5.2.0git-Linux.tar.gz generated.
CPack: Create package using TZ
CPack: Install projects
CPack: - Run preinstall target for: client
CPack: - Install project: client
CPack: Create package
CPack: - package: /home/philip/client-build/client-2.5.2.0git-Linux.tar.Z generated.

i've renamed the application to kloud but also did this without any modifications...
..with the same result.
So no NSIS generation whatsoever is happening

### Client configuration
Client version: 2.5.2.0

Operating system: OpenSuse Leap 15.0

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.9

Client package (From Nextcloud or distro) (Linux only):
N/A
Installation path of client:
N/A

### Logs

[CMakeOutput.log](https://github.com/nextcloud/desktop/files/3058844/CMakeOutput.log)

**Comment by camilasan** [comment]
I am not sure if I understand it... are you trying to follow the instructions here https://github.com/nextcloud/client-building? You need the NSIS script to create the installer.

**Comment by plages** [comment]
hi camilasan thanks for your reply and sorry for the late response.Those are indeed the instructions i'm trying to follow. In the past i have succesfully managed to built the client but even so i'm pretty much a noob. Is the NSIS script not included in the source?
Are there instructions about the NSIS script?
