### ISSUE TITLE
delete Changelog

### ISSUE THREAD

**Issue by r2evans** [nextcloud/desktop#1194]
I suggest you either maintain `Changelog` or delete it. If deleted, it will still be available for those who want historical tracking, but otherwise it's an inaccurate reference.

(I recognize there is https://github.com/nextcloud/desktop/wiki/2.5-series-changelog that appears to be up-to-date. I'm not asking "where is the changelog", just identifying an inconsistency or relic.)

### Expected behaviour

`Changelog` shows recent changes.

### Actual behaviour

The [latest substantive change](https://github.com/nextcloud/desktop/commit/e82869d10e2b5d06932799453b591916b5be6f73#diff-02f0b547c2779d25cff89672135f20e3) was over a year ago, version 2.4.1.

**Comment by camilasan** [comment]
Good point. Thanks.

**Comment by camilasan** [comment]
Problem solved.
