### ISSUE TITLE
New functionnality :: force users to tag all files (desktop client app)

### ISSUE THREAD

**Issue by databird** [nextcloud/desktop#1196]
Hello all,

We desire to add a new functionnality on NextCloud client (MacOS & Windows) to force user to tag all synced files.

Desired behavior :
- When a user sync a file (new or existing), check if this file is tagged
- If file is not tagged, display a popup (on Desktop) to let user tag (with collaborative tags) the uploaded/saved file
- If file is already tagged, display a popup with actual tags and let user change or keep tags
This popup must remain visible with the list of untagged files

If someone can do that (we can even pay for that job) you can contact me.

Thanks in advance !

**Comment by camilasan** [comment]
Hi @databird ! We offer professional services and development like this. You can contact Nextcloud sales at https://nextcloud.com/enterprise/buy/. 
Greetings,
Camila

**Comment by joshtrichards** [comment]
Closing this here as this enhancement request seems to be a custom need rather than a general need.
