### ISSUE TITLE
Icon in Windows Explorer - like Dropbox, OneDrive etc.

### ISSUE THREAD

**Issue by gidhap** [nextcloud/desktop#120]
Hi,
here is my problem:
I just set up Nextcloud, created Group Folder, groups and users, assigned Access rights and did some testing. So far everything Looks fine, however there is one thing stopping me from deploying it to multiple users. It is the fact that I don’t get an Icon or shortcut in Windows Explorer or on the Desktop.

After the Setup of the client is completed, there is this menue to use browser or open the local Explorer. If I choose the Explorer it is fine, however. As soon as the window is closed, there is no link / Icon available to get back to the nextcloud Directory.

Of course I know where the nextcloud directory is located, but I have to roll out the Client to several users, I mean USERS, no admins, no PC skills beside using Office and the Win File Explorer.
And I have no Access to their PCs, they are far away, all across the Country. 

Dropbox, OneDrive, SynologyDrive, all working flawless with this respect, offering a Symbol in the WIN Explorer.

Having this Icon is a "must have" I'd say.

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/client/issues/5295

You could give it a try in the [2.5.0 daily builds](https://download.owncloud.com/desktop/daily/?C=M;O=D) of the ownCloud upstream project.

**Comment by gidhap** [comment]
THANKS !
I used todays testpilotcloud-2.5.0.8981-nightly20180112-setup.exe and - here you go
<img width="254" alt="owncloud_testpilot" src="https://user-images.githubusercontent.com/28500973/34907301-a7e9f600-f87c-11e7-906d-1b8d3cae0986.PNG">

**Comment by janvanl** [comment]
Hi,
I was looking for this and updated the nextcloud-client to version 2.5.1 on Windows 10 pro.
First the install hang at the end, after a restart everything works but I do not see the symbol like in the last post from gidhap. Do I need to mark a chechbox and which one?
regards,
Jan

**Comment by GrameJunior** [comment]
@janvanl I had the same problem.

Before you install the new version, uninstall the old version and delete all nextcloud folders in Appdata.

**Comment by camilasan** [comment]
Since we are working on it - https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration - I will close this issue.

**Comment by claell** [comment]
Reopening, since it does not seem to be available right now.

**Comment by claell** [comment]
@linucksrox This seems to be a problem with this feature or a feature request to improve it. Since this is only for the original feature request and not follow-ups, it would be great, if you created a new issue with this instead. Then the progress and discussion of that can be tracked there.

@camilasan Not sure, is this available now, so can this be closed?

**Comment by er-vin** [comment]
Yep, this should work, I clearly see it here. :-)
