### ISSUE TITLE
Sub-folder's files givening "Checksum" error after downgrade to 2.3.3

### ISSUE THREAD

**Issue by brianWreaves** [nextcloud/desktop#1202]
On MacOS, can 2.5.1 safely be downgraded to 2.3.3?
 
I've done this and NC15 it's now syncing again.  Now I have one new but lingering issue. One parent folder's sub-folders and all its files are synced but are displaying, "The downloaded file does not match the checksum, it will be resumed." That doesn't even make sense to me, the "resumed".  It appears to be cancelling.
 
To troubleshoot, I download the entire folder from NC15 and replaced local files, but no-dice.
 
Any idea if this is a result of downgrading?
 
### Expected behaviour
Complete syncing of files.

### Actual behaviour
Displaying, "The downloaded file does not match the checksum, it will be resumed."

### Steps to reproduce
1.  Allow client to sync

### Client configuration
Client version:  2.3.3

Operating system: MacOS 10.14.4

OS language:  English

**Comment by camilasan** [comment]
I believe it should just work. What was your problem with 2.5.1?

**Comment by brianWreaves** [comment]
I have it sorted now.  I just moved the files locally to a new folder, waited for it to sync and them moved it back.
 
2.5.1 simply wouldn't complete sync and would end up corrupting the db which took NC down all together.
