### ISSUE TITLE
Where to download just nextcloudcmd?

### ISSUE THREAD

**Issue by edent** [nextcloud/desktop#1203]
### Expected behaviour
I want to download `nextcloudcmd` to run on a home server.  This is a client machine - it does not run Nextcloud Server.

### Actual behaviour
I try to run the .appimage file provided. I get the error:

```
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

### Steps to reproduce
1. Download .appimage
2. `chmod +x nextcloud.appimage`
3. `./nextcloud.appimage`
4. Error

### Client configuration
Client version:https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.5.2-x86_64.AppImage

Operating system: Ubuntu 16.04

Client package (From Nextcloud or distro) (Linux only): https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.5.2-x86_64.AppImage

**Comment by lambtho12** [comment]
I have been using Nextcloud client without any issue for a few month on Manjaro Linux.
Yesterday I started to get a QXcbConnection issue as well and can not log in anymore in the client.
Note sure if it is related or not. Here is the error log:
```qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 38538, resource id: 44113947, major code: 3 (GetWindowAttributes), minor code: 0```

**Comment by camilasan** [comment]
We don't distribute nextcloudcmd separated. Sure, it can be improved...

**Comment by anudeepND** [comment]
@camilasan Any update on this?

**Comment by metafarion** [comment]
This would be nice to have for to have on headless servers where the full desktop client package pulls in a ton of X-related dependencies.

I would also accept a fully daemonized client :-D

**Comment by edent** [comment]
It has been a year since I opened this issue. Any news on getting the latest nextcloudcmd? My headless client is stuck on 2.5.3. Thanks.

**Comment by octlabs** [comment]
For CentOS 8 there is no RPM anymore and the AppImage requires QT on my headless server.
It would be nice to deliver "nextcloudcmd"

**Comment by er-vin** [comment]
> For CentOS 8 there is no RPM anymore and the AppImage requires QT on my headless server.
> It would be nice to deliver "nextcloudcmd"

FYI it would depend on Qt still since nextcloudcmd is a QCoreApplication. Granted it wouldn't depend on the GUI parts of Qt but still.

**Comment by bezunartea** [comment]
Any updates on this? If not, is there a previous version headless version we can use?

**Comment by wieluk** [comment]
sudo apt install nextcloud-desktop-cmd ?

**Comment by nabaco** [comment]
I have a suggestion how solve this issue:
You could make the AppImage smart enough to start one binary or another according to it's name. Just replace the AppRun to a shell script that checks ${0}, and according to that starts nextcloud or nextcloudcmd. Of course it also means to not delete nextcloudcmd from the AppImage like you do today.
This will allow me to have the AppImage as usual, and add a symbolic link to it which is called nextcloudcmd.

I have to say that this will make it possible to use Nextcloud on headless servers to sync files.

**Comment by z0noxz** [comment]
If sync is all you are after, wouldn't `davfs2` (to mount a webdav instance) and `rsync` (used in two times to two-way sync) suffice?
```
mount -t davfs -ouid=<userid> https://<address>/remote.php/dav/files/<directory> /mnt/dav
rsync -avzru --delete-excluded ~/mystuff /mnt/dav
rsync -avzru --delete-excluded /mnt/dav ~/mystuff
umount /mnt/dav
```

**Comment by nabaco** [comment]
@z0noxz - my main usecase is to run on a server where I don't have root privileges. So mounting anything is out of scope.
I did try unison in the past, but did not like the results. Not to mention the OCaml version issues headache.
Furthermore, will using such utilities bypass meta-data updates, such as file history?

**Comment by mgallien** [comment]
I am going to close this since the latest version of the AppImage is bundling the nextcloudcmd executable and appimage provide a way to run this without needing elevated privileges.
I guess the easiest way is to do this
```
./Nextcloud-3.3.2-x86_64.AppImage --appimage-mount
>> /tmp/.mount_Nextcl8vSqmV
cd /tmp/.mount_Nextcl8vSqmV/usr/bin
export LD_LIBRARY_PATH=/tmp/.mount_Nextcl8vSqmV/usr/lib
./nextcloudcmd
```
I guess we have no other way to distribute nextcloudcmd alone and in a way that is maintainable by us and compatible with our current process.
