### ISSUE TITLE
Windows client keeps renaming files to upper case resulting in conflicts and data loss!

### ISSUE THREAD

**Issue by curioustwo** [nextcloud/desktop#1204]
The Nextcloud client on Windows keeps on renaming files to upper case. I am using this with QOwnnotes. However, I tested the issue by not running the QOwnnotes app and I have disabled the Notes APP on Nextcloud server to make sure that it is not causing any issues. 

### Expected behaviour
No renaming of files/notes

### Actual behaviour
File renamed to all UPPER case.

### Steps to reproduce
1. On Linux I make a modification to one of my notes. The name of the note file is "Todos.md".
2) Linux Nextcloud client syncs the files and I check in the file browser on my Nextcloud server web interface and the file is updated and the name of the file is still "Todos.md".
3) On windows I stop sync and then restart sync (to trigger sync). The file is downloaded and then renamed to "TODOS.MD".

This is _extremely_ annoying and dangerous. Can you please keep the file name the same as on the server? I see no reason why you should be renaming files.

### Client configuration
Client version: 2.5.1final (btw, I see that there are newer versions released but the app says that I am all up-2-date!)

Operating system: Windows 10

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
c:\ProgramData\Microsoft\Windows\Start Menu\Programs

**Comment by camilasan** [comment]
Hi! That is odd. I am sorry for the issue but I believe this is something in the Notes app. The desktop client doesn't rename files. This is coming from the server.

**Comment by curioustwo** [comment]
The first lines in my note is:
Todos
=====

(not capitalized)

I will reproduce the issue again. Like I said I closed the notes app (QOwnNotes) and disabled the Qonwnotes API on the Nextcloud server when I tested. But I will test again and verify! :-)

Thanks!

**Comment by curioustwo** [comment]
I think I found the root cause. The notes were synced to a Veracrypt encrypted volume on my Windows machine. The encrypted volume were using FAT32. Does not seem to be happy about that. I created a new volume using ExtFAT file system and now it seems like the issue is gone.

Btw, what is the deal with this arbitrary 238MB free size limit? Nextcloud client on Windows refuses to sync if the disk space is below this. Can you please at a minimum allow to override this?
