### ISSUE TITLE
Trouble syncing with Desktop client 2.5.2

### ISSUE THREAD

**Issue by nginfo9** [nextcloud/desktop#1205]
### Expected behaviour
Tell us what should happen
Sync all the folders and files.

### Actual behaviour
Tell us what happens instead
Hangs on verifying folders and app crashes or says : "An error occurred while opening a folder."

### Steps to reproduce
1. Open fresh installed Nextcloud;
2. Connecting to server with client's account;
3. Choose folders to sync;
4. It begins checking and verifying but no folders created in Nextcloud's folder;
5. We tried the "No proxy" trick but doesn't work;
6. We tried to remove the account and reconnect it, but no luck;
7. We tried older client's version but doesn't work;
8. We are out of idea.

### Client configuration
Client version: 2.5.2

Operating system: Windows 10 Pro 

OS language: Canadian French

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: Ubuntu server 16.04

Web server: Nginx 1.13.9

Database: MariaDB mysql 15.1 distrib 10.0.34

PHP version: 7.2.3-1

Nextcloud version: 15.0.7

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

```

[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://cloud.franksullivan.com/remote.php/dav/files/cmorote/" has X-Request-ID "1eae2b68-580e-4eaa-a2ab-d13963d6560d"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://cloud.franksullivan.com" + "/" "OCC::QuotaInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://cloud.franksullivan.com/remote.php/dav/files/cmorote/") FINISHED WITH STATUS "OK"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://cloud.franksullivan.com/remote.php/dav/files/cmorote/" for changes via ETag check. (time since last sync: 5826 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://cloud.franksullivan.com/remote.php/dav/files/cmorote/" has X-Request-ID "e71546d6-86cb-406a-9983-58629dd41405"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://cloud.franksullivan.com" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://cloud.franksullivan.com/remote.php/dav/files/cmorote/") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://cloud.franksullivan.com/remote.php/dav/files/cmorote/" has X-Request-ID "5a43e69f-d43e-469f-bb85-1d13543d01e8"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://cloud.franksullivan.com" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://cloud.franksullivan.com/remote.php/dav/files/cmorote/") FINISHED WITH STATUS "OK"

```

2. Web server error log: 

```

2019/04/15 08:21:51 [warn] 1665#1665: *9312 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/3/01/0000000013 while reading upst$
2019/04/15 08:21:51 [warn] 1665#1665: *9402 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/4/01/0000000014 while reading upst$
2019/04/15 08:21:53 [warn] 1665#1665: *9402 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/5/01/0000000015 while reading upst$
2019/04/15 08:21:56 [warn] 1665#1665: *9312 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/6/01/0000000016 while reading upst$
2019/04/15 08:21:56 [warn] 1665#1665: *9402 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/7/01/0000000017 while reading upst$
2019/04/15 08:22:01 [warn] 1665#1665: *9312 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/8/01/0000000018 while reading upst$
2019/04/15 08:27:46 [warn] 1665#1665: *9312 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/9/01/0000000019 while reading upst$
2019/04/15 13:22:38 [warn] 1665#1665: *24539 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/0/02/0000000020 while reading ups$
2019/04/15 13:25:42 [warn] 1667#1667: *24597 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/02/0000000021 while reading ups$
2019/04/15 13:25:50 [warn] 1665#1665: *24705 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/2/02/0000000022 while reading ups$
2019/04/15 13:26:27 [warn] 1668#1668: *24735 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/3/02/0000000023 while reading ups$
2019/04/15 15:06:11 [warn] 1668#1668: *30937 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/4/02/0000000024 while reading ups$

```

3. Server logfile: nextcloud log (data/nextcloud.log): empty

**Comment by nginfo9** [comment]
Any news?

**Comment by camilasan** [comment]
This is most likely a response from the server. Could you share the whole log files?

**Comment by camilasan** [comment]
Could you share the whole desktop client log? Do you have the right permissions to access the folder locally and on the server (firewall etc)?

**Comment by nginfo9** [comment]
For the client's logs, I provided the whole output from F12 command.
Yes we do have permissions to access the folder locally or on the server.
For the firewall, nothing is blocked.

Just so you know, the problem appears now to be general, on all workstations/clients.

**Comment by 0x47** [comment]
I get this same error message just by running the desktop client for some time (few hours), not even up/downloading anything during that time. This happens to me for months and I could not find the reason so far. After some more time, the desktop client finally segfaults.

![screenshot](https://user-images.githubusercontent.com/3926232/57575806-5fc5b700-7441-11e9-9891-baa9664bd20e.png)

**Comment by nginfo9** [comment]
@0x47 We experience the same error and after some time, the client crashes.
We are switching to a new server and we will see if it is more stable.

**Comment by nginfo9** [comment]
Hello, 

we just migrated the server to another more powerful running on ubuntu server 18.04 with PHP7.3, NGINX 1.15.9 and mariadb 10.3.14. Upgraded NC server to 16.0.1 and still have the same error.

I tried to connect webdav with windows mapping but the mapping stop after a reboot.

I am out of idea...

Thanks,

**Comment by krudas74** [comment]
I just upgraded to 16.01 and tried to sync with 2.5.2.5231 and it is synchronising at the moment.
Ubuntu 18.04.2 LTS
PHP 7.2.17
Server version: Apache/2.4.29
MariaDB 10.1.38

**Comment by nginfo9** [comment]
So far it seems to work fine. the migration on another server helped but I figure out that loopback nat was a problem.

I configured internal DNS for the external hostname to point directly on the internal server. It helped alot.

Thanks,

**Comment by BigMackTech** [comment]
The new 2.5 windows, android, ios client/App sync for me with Nextcloud 16, but doesn't show external storage for sync.  If I down grade to client version 2.3 I can sync external storage.  This going to be fixed?  Appears to just be a client side issue.

**Comment by 0x47** [comment]
I don't think it is a server issue (for me at least) as this does not happen for any Windows desktop clients. The "error" occurred while opening the local Nextcloud folder, not the server folder.

**Comment by 0x47** [comment]
Potential temporary fix is to use the official ownClient desktop client instead of the Nextcloud one (see https://github.com/nextcloud/desktop/issues/1182#issuecomment-503648102).

**Comment by 0x47** [comment]
This is still happening with version 2.6.1git, server version 17.0.1. OwnCloud client still working flawlessly.

**Comment by wayneoutthere** [comment]
I know this is closed and old, but I wanted to put a post here that let's everyone know that I solved this on an Ubuntu Snap install of Nextcloud with a system `sudo apt update` and `sudo apt upgrade` believe it or not..  must have had an incompatible package or something but after updated it was fine again.  Hope this  note helps.

**Comment by mgallien** [comment]
@nginfo9 Are you still having an issue or can I close this ticket ?
To investigate that we will need the logs that had been asked by @camilasan

**Comment by BigMackTech** [comment]
I am good.  I am running Version 19 with no issues currently.
