### ISSUE TITLE
Typo on Windows sync setup page

### ISSUE THREAD

**Issue by alexjustesen** [nextcloud/desktop#1206]
### Expected behaviour
"There is not enough"...

### Actual behaviour
"There is no enough"...

### Steps to reproduce
1. Download Windows installer from nextcloud.com
2. Install Windows client for Nextcloud.
3. Typo will show on the configuration page for sync settings

### Client configuration
Client version: 2.5.2

Operating system: Win10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.11.1

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client:

### Server configuration
n/a

**Comment by mx-psi** [comment]
This issue was fixed in commit b36626d50a83248473b10a75b56b36c1cea8b2e4 and it should be closed

**Comment by misch7** [comment]
@mx-psi Right, good catch, thanks! :-)

Checked it in current master to be sure and it has been fixed, closing this here.
