### ISSUE TITLE
Opaque menu item background on launch

### ISSUE THREAD

**Issue by fastjack** [nextcloud/desktop#1208]
### Expected behaviour
After launching the Nextcloud desktop app the background of the menu item should be transparent.
<img width="66" alt="Item-0_und_Item-0" src="https://user-images.githubusercontent.com/14481/56317837-05954700-615e-11e9-8dac-695fc0e4fd8f.png">

### Actual behaviour
Directly after launching the Nextcloud desktop app the menu item shows a black opaque background.
<img width="75" alt="Item-0_und_Item-01" src="https://user-images.githubusercontent.com/14481/56318065-a84dc580-615e-11e9-95f2-b98c2722f225.png">

Only after clicking on the menu item once the background becomes transparent.

### Steps to reproduce
1. Launch Nextcloud desktop app
2. There is no step 2

### Client configuration
Client version: 2.5.3rc1 (build 20190412) and earlier in 2.5.1

Operating system: macOS 10.14.4

OS language: German

Installation path of client: /Applications

**Comment by claucambra** [comment]
Hi, does this issue still appear with the latest version of the desktop client? I was unable to reproduce on Catalina with the current version of the client

**Comment by fastjack** [comment]
I can't reproduce it any more either. It seems to have been fixed

**Comment by claucambra** [comment]
Thank you for checking!
