### ISSUE TITLE
build error on macOS

### ISSUE THREAD

**Issue by zealoussnow** [nextcloud/desktop#1211]
### Expected behaviour

build success

### Actual behaviour

When I run `make`, I got error as following
```
[ 91%] Linking CXX executable ../../bin/nextcloud.app/Contents/MacOS/nextcloud
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/nextcloud.app/Contents/MacOS/nextcloud] Error 1
make[1]: *** [src/gui/CMakeFiles/nextcloud.dir/all] Error 2
make: *** [all] Error 2
```

### Steps to reproduce
1. set environment
``` 
export Qt5_DIR="/usr/local/Cellar/qt5/5.7.0/lib/cmake/Qt5"
export Qt5LinguistTools_DIR="/usr/local/Cellar/qt/5.7.0/lib/cmake/Qt5LinguistTools/"
```
2. do cmake
```
cmake .. -DNO_SHIBBOLETH=1 -DQTKEYCHAIN_LIBRARY=~/SDCard/OpenSource/nextcloud/qtkeychain-0.9.1/build/libqt5keychain.dylib -DQTKEYCHAIN_INCLUDE_DIR=~/SDCard/OpenSource/nextcloud/qtkeychain-0.9.1/  -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1b
```
3. make target
```
make
```
### Client configuration
Client version: 

```
master branch

git describe --tags
v2.5.3-rc1-5-gf32d83e
```

Operating system:

```
macOS 10.12.6
```

OS language: en_US

**Comment by zealoussnow** [comment]
Sorry, I forgot update submoules.

**Comment by pnyers** [comment]
> Sorry, I forgot update submoules.

Hi zealoussnow,

I have similar compiling error:

[ 79%] Linking CXX shared library libnextcloudsync.dylib
Undefined symbols for architecture x86_64:
  "_RSA_pkey_ctx_ctrl", referenced from:
      OCC::EncryptionHelper::decryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::EncryptionHelper::encryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::ClientSideEncryption::generateKeyPair() in clientsideencryption.cpp.o
  "_X509_REQ_get_subject_name", referenced from:
      OCC::ClientSideEncryption::generateCSR(evp_pkey_st*) in clientsideencryption.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libsync/libnextcloudsync.2.5.3.dylib] Error 1
make[1]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/all] Error 2
make: *** [all] Error 2


The cmake line:

cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client/desktop/  -DNO_SHIBBOLETH=1 . -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake/ -DQTKEYCHAIN_LIBRARY=/usr/local/opt/qtkeychain/lib/libqt5keychain.0.9.1.dylib -DQTKEYCHAIN_INCLUDE_DIR=/usr/local/opt/qtkeychain/include/qt5keychain/ 


Do you have any idea what is wrong?
It makes me crazy i can't figure out.

Thanks in advance!

**Comment by zealoussnow** [comment]
@pnyers I update all submodules, and rebuild it.
```bash
[nextcloud desktop git:(release-2.5.2)*]$ git submodule init
[nextcloud desktop git:(release-2.5.2)*]$ git submodule update
```
