### ISSUE TITLE
[Bug] Picking directory outside of /home in "First Setup Wizard"

### ISSUE THREAD

**Issue by fabian727** [nextcloud/desktop#1213]
I am using version 2.3.3 under Ubuntu 19.04 (at least the bash command "nextcloud-client --version" states this.

`
Qt: Session management error: None of the authentication protocols specified are supported
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.608\" (uid=1000 pid=4777 comm=\"nextcloud --version \" label=\"snap.nextcloud-client.nextcloud-client (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=995 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.608\" (uid=1000 pid=4777 comm=\"nextcloud --version \" label=\"snap.nextcloud-client.nextcloud-client (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=995 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
Nextcloud version 2.3.3
Using Qt 5.5.1, built against Qt 5.5.1
Using 'OpenSSL 1.0.2g  1 Mar 2016'
`

User Interface says version "2.5.1git"

### Expected behaviour
1. Install nextcloud
2. configure /media/mydirectory/nextcloud as syncing directory
3. nextcloud syncs all files

### Actual behaviour

- file browser does not list /media, but typing into slot is possible and installation will succeed
- the command "sudo snap connect nextcloud-client:removable-media", which would grant access to "/media" is not possible and fails in "      error: snap "nextcloud-client" has no plug named "removable-media"    "

### Steps to reproduce
1. install
2. try to configure "/media/..."

### Client configuration
Client version: as stated I think 2.5.1git
Operating system: Ubuntu 19.04 (upgrade of previous versions ... )
OS language: english
Qt version used by client package (Linux only, see also Settings dialog): does not show, but I think commandline output at top will answer
Client package (From Nextcloud or distro) (Linux only): snap
Installation path of client: default, so cannot state as not picked

After installation the user will be able to pick up any (really any) directory he wants. So there is a security issue in snap too ...

**Comment by camilasan** [comment]
Hi! Do you have the issue with 2.5.3 rc1?
https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.3.20190412-rc1-x86_64.AppImage
Could you try it?
Thanks

**Comment by fabian727** [comment]
the "--version" qt bug seems fixed.
also the directory "/media/username" is listed. Great work
I couldn't check the rights listed in snap as I just run your application and didn't install it.
