### ISSUE TITLE
Beta Desktop Client Crashes

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#1215]
### Expected behaviour
I am trying to create a shortcut for a directory within the Nextcloud virtual drive, the shortcut should be created without issue.

### Actual behaviour
The Nextcloud client crashes and it causes Explorer to throw out errors

### Steps to reproduce
1. Install tech Preview of Nextcloud Client
2. Upload various directories into Nextcloud Client
3. Create a shortcut on Desktop for a particular directory

### Client configuration
Client version: Tech Preview of Nextcloud Desktop

Operating system: Windows 7 Professional 64-bit

### Server configuration

Operating system: Ubuntu 18.04

Web server: NGiNX

Database: MariaDB

PHP version: 7

Nextcloud version: 15.0.7

### Logs

Screenshot: https://i.imgur.com/NQW32CA.png

Log:

```
Files that help describe the problem:
  C:\Users\User\AppData\Local\Temp\WER167F.tmp.WERInternalMetadata.xml
  C:\Users\User\AppData\Local\Temp\WER2243.tmp.appcompat.txt
  C:\Users\User\AppData\Local\Temp\WER22A1.tmp.mdmp

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by c0fe** [comment]
So I do not know what the issue was but after purging Nextcloud client with Smarty Uninstaller I ended up reinstalling the tech preview and it has been working so far.

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
