### ISSUE TITLE
Everytime a new link when open a share in Windows

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/desktop#1217]
Hello,
I have several Nextcloud 15 installations and in all systems is the same problem. When I add a share in Windows, it makes everytime a new share. I can not access the shares I created before. When I look in the web frontend, I can see all the created shares but not in Windows.
In Nextcloud 13, I could see in Windows the created shares.
System
Nextcloud 15.0.7
Ubuntu 18.04. LTS
Apache 2
Mysql
PHP 7.2
Windows 10
Windows Client 2.5.1final (build 20181204)

**Comment by camilasan** [comment]
I have fixe it on 2.5.3 rc1:
https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.3.20190412-rc1-x86_64.AppImage
https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-2.5.3-rc1-20190412.exe
https://download.nextcloud.com/desktop/prereleases/Mac/Nextcloud-qt5.9.2-2.5.3.20190412rc1.pkg

#1179
