### ISSUE TITLE
feature request: show sharing status in windows explorer icon

### ISSUE THREAD

**Issue by rbicker** [nextcloud/desktop#122]
Hi

It would be great if it was possible to determine if a folder was shared directly within windows explorer. So for example, when I share a folder in the webinterface, it looks like this:
![nextcloud-1](https://user-images.githubusercontent.com/12236145/34947841-a42abbcc-fa0b-11e7-9e92-deba19258044.png)

But in windows explorer, it looks like any other folder in my nextcloud data directory:
![nextcloud-2](https://user-images.githubusercontent.com/12236145/34947861-b2d2004a-fa0b-11e7-9e66-3223730d6c69.png)

Dropbox for example solves this, not by doing an overlay but by changing the folder icon itself:
![dropbox](https://user-images.githubusercontent.com/12236145/34947984-1b56150c-fa0c-11e7-88bc-ebca624d97c4.png)

Thank you!

**Comment by borsti67** [comment]
I'd like to add the Owncloud-client already has this feature (shows sync and sharing status). May be it is possible to adapt this?

(It would be fantastic to be able to change the sharing options via context menu, but that's another story)

**Comment by Weasy666** [comment]
Isn't this already integrated? I see this on shared folders.
![grafik](https://user-images.githubusercontent.com/11967542/97413370-ff5f5980-1902-11eb-84d8-58cc5f20eefe.png)

**Comment by er-vin** [comment]
Indeed... Didn't look much into it but that's there.
