### ISSUE TITLE
Non stopping "help to improve" popups

### ISSUE THREAD

**Issue by maxklock** [nextcloud/desktop#1220]
### Expected behaviour
I would like to get the "help to improve" ((Hilf Nextcloud zu verbessern)) popup just one time and when I click on it, it should open an survey or other kind of feedback tool.

### Actual behaviour
I get the "help to improve" (Hilf Nextcloud zu verbessern) at least one time per hour and when I click on it, nothing happens.

### Steps to reproduce
1. Start Nextcloud Client (Autostart)
2. Wait

### Client configuration
Client version: Version 2.5.2git (build 20190319)

Operating system: Windows 10 Pro, 1809

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

**Comment by camilasan** [comment]
Please check #1030. There is a configuration you need to change in the server. Thanks.
