### ISSUE TITLE
Installed windows binaries not signed

### ISSUE THREAD

**Issue by Bodup** [nextcloud/desktop#1226]
The installed binaries (not talking about the installer) aren't signed. (See [image](https://imgur.com/a/8IYJ2uk))

**Comment by camilasan** [comment]
Which version is it and where did you download it from?

**Comment by Bodup** [comment]
2.5.2, from [download.nextcloud.com](https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.2-setup.exe) (https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.2-setup.exe)

**Comment by camilasan** [comment]
Ok, I will check it, thanks.

**Comment by csware** [comment]
For opensource project you can get a "cheap" certificate from certum (https://www.certum.pl/pl/cert_oferta_Open_Source_Signing/).

**Comment by misch7** [comment]
The latest release now uses signed binaries. I also extended code signing to include important DLL's like OpenSSL and the uninstaller now also gets signed:

https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.3-setup.exe

Since this solves the issue I will close it. 😺
