### ISSUE TITLE
2.5.2 Client crashes after starting sync, kdewallet

### ISSUE THREAD

**Issue by vc7ee** [nextcloud/desktop#1227]
### Steps to reproduce
1. I logged in to the client with an app password (since I have U2F enabled)
2. Everything went well, except it said that I had not enough storage on the device (not true)
3. After pressing sync, it minimized to topicons redux for a moment and then crashed
4. After opening the appimage again (log starts here), I am presented with this:
![image](https://user-images.githubusercontent.com/38327267/56986983-c6aeba80-6b7b-11e9-818d-a6969e9ddfc9.png)
5. After logging it, it goes to tray and crashes as before.

### Client configuration
Client version: 2.5.2

Operating system: Fedora 30

OS language: English

Qt version used by client package: qt5-qtwayland-5.12.1-1.fc30

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: /home/v/appimage/
### Logs
$ ./Nextcloud-2.5.2-x86_64.AppImage --logfile (rknxlog.txt](https://gist.github.com/vc7ee/44ee1a8cc7c609c40b4da1d041eae926)
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Received signal 11 SEGV_MAPERR 000000000021
Segmentation fault (core dumped)
***
Terminal indicates problems with qt, from https://github.com/bitcoin/bitcoin/issues/15677:
$ sudo dnf install qt5-qtwayland
[sudo] password for v: 
Last metadata expiration check: 0:15:51 ago on Tue 30 Apr 2019 10:00:38 PM EEST.
Package qt5-qtwayland-5.12.1-1.fc30.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
***
Running this from bitcoin issue removes the qt message:
$ QT_QPA_PLATFORM="xcb" ./Nextcloud-2.5.2-x86_64.AppImage 
Received signal 11 SEGV_MAPERR 000000000021
Segmentation fault (core dumped)

Edit:
Version installed with dnf gets me logged in, but after opening the client again (rebooting) it logged me out.
[This prerelease](https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.3.20190412-rc1-x86_64.AppImage) wanted me to create a kdewallet. Even tough the kdewallet app crashed first few times, after loading for a while, it managed to load up and I was able to create a wallet.
Since that, the prerelease worked fine. I installed the version from dnf again and that is aswell working fine. The version from nextcloud.com/install is also working fine.

2.5.3 Fixes this, tough the kdewallet seemed to be slow, inpatient users may experience problems.

**Comment by vc7ee** [comment]
Related #1011

**Comment by camilasan** [comment]
Thanks for updating the issue. I will close it then.

**Comment by vc7ee** [comment]
2.5.3. seems slow, I was playing around with 2.5.2 and kwallet, **do not install kwallet**, it (broke gnome-keyring)[https://forum.level1techs.com/t/enter-password-to-unlock-your-keyring/143247]

**Comment by BloodyAltair** [comment]
Anything new about this problem?

**Comment by vc7ee** [comment]
Nope, nextcloud only works with kwallet, but kwallet brakes gnome-keyring until os reinstall (didn't find an another solution in months). Right now I use rclone via webdav.

**Comment by mattlewis53** [comment]
`Received signal 11 SEGV_MAPERR 000000000021`

It's mid-August and you still cannot use the AppImage on Gnome because of this issue. This makes the whole Nextcloud stack a pain in the rear to use and with no apparent fix in sight has left many searching for a new solution. Can we get an update on this?

**Comment by jtagcat** [comment]
@camilasan reopen the issue?
