### ISSUE TITLE
Cannot add folder sync connection in virtual drive 

### ISSUE THREAD

**Issue by Bockeman** [nextcloud/desktop#1228]
### Expected behaviour
- I have a self-hosted Nextcloud server that will contain 10's TB of video data.
- I have several individual video files that are over 30GB.
- I want a Nextcloud virtual drive to be located on my F: drive because the default C: drive
    C:\Users\...\AppData\Roaming\Nextcloud\cachedFiles
    does not have enough free space for even one of these large video files.
- Even my F: drive is not large enough to contain all of the video data, hence why I need a virtual drive.
- I only expect to sync large files when network bandwidth permits.

### Actual behaviour
- There is no "Add Folder Sync Connection" for the virtual drive, as there is with the Nextcloud client.
- There is a "Remove folder sync connection", which I tried, and does remove the one connection.
- But then there is no way to restore it or add another connection.
- Now I am left with an empty virtual drive and no way to even restore it to the one default connection.
- I uninstalled Nextcloud and re-installed. Surprisingly, that restored my previous settings, but worse,  that did not restore the one default connection.
- I searched for nextcloud in the registry, but could not locate anything relevant.

### Steps to reproduce
1. Install tech Preview of Nextcloud Client
2. Remove folder sync connection
3. Attempt to add a folder sync connection

### Client configuration
Client version: 2.5.0techpreview (build 20190128)
Dokan 1.2.2.1000
Operating system: Windows 7 Ultra 64-bit

### Server configuration
Operating system: Fedora 29 32-bit
Web server: Apache
Database: MariaDB
PHP version: 7
Nextcloud version: 15.0.7

### Logs
Location of relevant log files not known.

**Comment by camilasan** [comment]
We have changed our approach and now the virtual file system is set by syncing folder: https://help.nextcloud.com/t/help-test-our-desktop-client/
