### ISSUE TITLE
Windows client 2.5.2 doesn't install x86 files on x86 systems

### ISSUE THREAD

**Issue by polytan02** [nextcloud/desktop#1230]
Hi,

I'm on windows 10 x86.
After downloading the windows client and installing it, it refuses to launch as the software is not compatible. Apparently x64 files are installed instead of x86.

This issue is also present on 2.5.0 and 2.5.1 .... so it fails since last year November.

Can we get a fix pretty please ?

**Comment by polytan02** [comment]
Hi,

I'm on windows 10 x86.
After downloading the windows client and installing it, it refuses to launch as the software is not compatible. Apparently x64 files are installed instead of x86.

This issue is also present on 2.5.0 and 2.5.1 .... so it fails since last year November.

Can we get a fix pretty please ?

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/nextcloud/desktop/issues/840 . Close here?
