### ISSUE TITLE
The Transifex export script doesn't converge

### ISSUE THREAD

**Issue by tintou** [nextcloud/desktop#1232]
Everyday, the transifex script creates a commit that undo the commit from the previous day, it oscillates between [de → de_DE](https://github.com/nextcloud/desktop/commit/a5b65a73a8198830744a68da3b33da62c554c98f) and [de_DE → de](https://github.com/nextcloud/desktop/commit/26b9bf0281a9615a7457aec9124a1914c574fa55)

**Comment by camilasan** [comment]
Any idea why @rullzer?

**Comment by camilasan** [comment]
It has been fixed.
