### ISSUE TITLE
No daily builds for Windows since 20190409

### ISSUE THREAD

**Issue by piojan** [nextcloud/desktop#1243]
Looks like there are no new daily builds for Windows since 20190409:
https://download.nextcloud.com/desktop/daily/Windows/

**Comment by thechonta** [comment]
and the Syncclient is maby broken.
#15156
#15033

**Comment by camilasan** [comment]
Fixed: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.3.5421-daily-20190509.exe
