### ISSUE TITLE
Desktopclient is Possably broken with SMB Backend

### ISSUE THREAD

**Issue by thechonta** [nextcloud/desktop#1246]
nextcloud/server#15156
nextcloud/server#15033
Operating system:Ubuntu 18.04
**Web server:Apache 2.4.29
**Database:mariadb Ver 15.1
**PHP version:7.2.15
**Nextcloud version:15.0.7
**Desktopclient 2.5.0++
**Client OS:Windows 10/ Windows 7
**SMB Server 2016

User A changes an file or create an file in an subfolder, no changes will be noticed for user B.
If user B browses to the file, than it will be synced.

The expected behavior is, that user A changes an file or creates something on the share (per client or browser), user B will sync the data to his desktop as well.
A view minutes after i was upgrading from 15.0.4 to 15.0.7 it worked like this but than all of a sudden it stopped working.
There no errors in the Logfiles of the nextcloud so far.

If the share set up with username and password saved in the nextcloud, than it works. But than the accessenumeration on the fileserver could not be used.
Because the fact, that changes on the first level got noticed, as log as it was initiated per client are synced, shows that it should work also for subfolder as well.
The nextcloud should know what file was changed and provide the clients the information so the clients can check the backend store.

**Comment by michaelstingl** [comment]
Related to https://github.com/nextcloud/desktop/issues/201 ?

**Comment by thechonta** [comment]
Yes it is related to https://github.com/nextcloud/desktop/issues/201
The Problem is, that the Server cant scan the Files on the Backend, if the credentials are sotred in the Database.
Only if the backend is connect per specific username and password it is possible.
Problem you cant use something like Accessnumeration....

The client should inform the Server about changes that are done and the server should inform all other clients about changes and the clients should than sync the files.
The same if there is some changes over the webfrontend, the server should sent information to the desktop clients.
But something in this communication is broken.

sudo -u www-data php occ files:scan --all does not work for external store (in my case smb and in database saved credentials)

if you could set an user that does the scan of the store and found changes will used for all other users as well would be fantastic.

**Comment by thechonta** [comment]
push push, still not working :-)

**Comment by thechonta** [comment]
Hallo,

just installed Nextcloud-2.5.3.5440-daily-20190528.exe
The Problem is still not solved but has changed a little bit.

A edit an .txt file in a Subfolder 3 Level below the share, B will not get a notice of that and nothing is synced.
B edit another file on the Same Level OR below the changes of A will syned to B,
but the Changes of B will not synced to A.

A edits an .docx file in a Subfolder 3 Level below the share, B will not get a notice of that and nothing is synced.
B edit another file on the Same Level OR below the changes of A will syned to B,
but the Changes of B will not synced to A.

On the Toplevel of the Schare edit and create actions will shared between the users. (Only testet with .xlsx and .txt)
It would be nice if this would work for all Levels of a share. 

**Comment by thechonta** [comment]
Push Push Push

**Comment by thechonta** [comment]
Tested Nextcloud Server 15.0.4.0
PHP: 7.2
Ubuntu 18.04.2
SMB Backend on Server 2012, Credential saved in Database.
Authbackend: LDAP (AD)
Clients: Nextcloud-2.2.3.4-, Nextcloud-2.2.4.2, Nextcloud-2.3.1.8, Nextcloud-2.3.2.1, Nextcloud-2.3.3.1, Nextcloud-2.5.1, Nextcloud-2.5.3.5526-daily-20190614
As long there is only one User that uses the Client to Sync date between Server and Client and the changes are only made by the Client the sync will work.

The moment there are two users that sync and changes the same data it will not work.
User A changes, and the Changes are synced to the Server but User B will never get any changes as long he changes some file in the same Folder itself. In this moment magically the changes made by User A will also synced but user A will not get the Changes of user B….

Also as normal there are changes on the Fileserver itself, there will no sync between Server and User, as long there is some changes by the User….

Expected is there is a change on the User A User B will get the changes synced. B changes something A will also get the information.
Also if something is changed on the external storage by User C, it should by synced to the Nextcloud user A and B.

The server should manage all changes of the users in the database and the clients should look the server database for changes off all data of all users they have access.
And on the server should be possible to set a sync-user to check the external storage for changes, and store it in the database to inform all the users.

**Comment by mgallien** [comment]
As far as I understand this issue is not in the desktop client but rather in the server handling of external storage.
Could you please see if recent server releases have fixed your problem ?
I am closing the issue from desktop client side since this is probably only related to server handling of external storage.
