### ISSUE TITLE
Conflict file when working with VIM

### ISSUE THREAD

**Issue by pjotrek-b** [nextcloud/desktop#1250]
### Expected behaviour
I'm editing textfiles that are located in a nextcloud-synced folder with the VIM editor. I expect no error warning from nextcloud when I do that.

### Actual behaviour
I do edit my nextcloud files with VIM a lot, and every time I save the file I get a "conflict file" warning from the nextcloud client. Is there any way to configure this error not to be triggered in this case?

Thank you very much in advance for any hints! :smile:

### Steps to reproduce
1. Create a textfile in a nextcloud folder.
2. Edit that file with vim: keep it open, edit and regurarily save (:w) it.
3. When working on a file like that, a nextcloud popup message appears with a conflicting file error of the file you've opened in vim.

### Client configuration
Client version:
2.5.2-20190319.015224~xenial1

Operating system:
Xubuntu Xenial (16.04.3)

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
Couldn't find it in the settings dialog... Sorry.

Client package (From Nextcloud or distro) (Linux only):
(PPA) deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu xenial main

Installation path of client:
/usr/bin

**Comment by pjotrek-b** [comment]
I'm also getting "the file has changed since last reading it" warnings in vim, when I try to save the file.

**Comment by Req** [comment]
Sounds like this could be related to https://github.com/nextcloud/desktop/issues/943 - my users keep getting conflicts when working on simple excel files even when they are the are the only user in the system

**Comment by pjotrek-b** [comment]
Oh, yes btw I forgot to mention: I *am* the only person editing that file. :wink:
I currently always delete the conflict file, and haven't noticed to have lost any changes.

**Comment by mgallien** [comment]
I have just tested that with the latest version and could not reproduce.

Please can you test with the latest stable release ?
