### ISSUE TITLE
Both strings appear as plurals

### ISSUE THREAD

**Issue by yarons** [nextcloud/desktop#1252]
https://github.com/nextcloud/desktop/blob/ae0b1ce3d6bae9fa4a7f1e0a6b795a32a49be641/src/common/utility.cpp#L436-L440

These two strings appear individually as a plural string (hashes):
0d9e9c60e0ee5da1b86a879c6292c77c
fe464d3b777e67ef74f5f379452fa756

Links:
https://www.transifex.com/nextcloud/nextcloud/translate/#he/client/156989441
https://www.transifex.com/nextcloud/nextcloud/translate/#he/client/156989422

Thanks :)

**Comment by camilasan** [comment]
If we understand it right: in Hebrew 'day' and 'days' are the same? We can't fix that, the text and code is taking into account other languages too.

**Comment by yarons** [comment]
Nope, I meant these are two distinct singular strings instead of an actual plural string which makes it difficult to translate to other languages such as Arabic, Ukrainian, Polish and several others, Hebrew is among them indeed.
