### ISSUE TITLE
compiling failed on mac

### ISSUE THREAD

**Issue by pnyers** [nextcloud/desktop#1254]
### Expected behaviour
make install should be done well.

### Actual behaviour

 cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/

make install

THEN:...

[ 76%] Building CXX object src/libsync/CMakeFiles/nextcloudsync.dir/creds/credentialscommon.cpp.o
[ 78%] Building CXX object src/libsync/CMakeFiles/nextcloudsync.dir/creds/httpcredentials.cpp.o
[ 79%] Linking CXX shared library libnextcloudsync.dylib
Undefined symbols for architecture x86_64:
  "_RSA_pkey_ctx_ctrl", referenced from:
      OCC::EncryptionHelper::decryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::EncryptionHelper::encryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::ClientSideEncryption::generateKeyPair() in clientsideencryption.cpp.o
  "_X509_REQ_get_subject_name", referenced from:
      OCC::ClientSideEncryption::generateCSR(evp_pkey_st*) in clientsideencryption.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libsync/libnextcloudsync.2.5.3.dylib] Error 1
make[1]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/all] Error 2
make: *** [all] Error 2

### Steps to reproduce
I just followed the steps (compile and install on osx):
https://github.com/nextcloud/desktop

### Client configuration
Client version: newest nextcloud desktop client from git

Operating system: MacOS Mojave

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
 cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/

**Comment by camilasan** [comment]
Do you also have the desktop client installed?

**Comment by pnyers** [comment]
Do you mean a running client? Yes.

**Comment by camilasan** [comment]
Then I would remove it. It might be mixing libs of the compiled with the one installed. I would also check what you have set in your env vars (PATH etc)

**Comment by pnyers** [comment]
How can i remove it well? Is it enought if i just remove the app from the Applications? I can't see uninstall options.

**Comment by camilasan** [comment]
> Is it enought if i just remove the app from the Applications?

I think so, isn't that how mac OS works?

**Comment by pnyers** [comment]
I thought it's got installed libs in Library or something and it is not removed when i remove from the Applications. Btw i removed from the Applications but same issue.

This is the build:

bash-3.2$ cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1 -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@1.1/include/ -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake/ -DQTKEYCHAIN_LIBRARY=/usr/local/opt/qtkeychain/lib/libqt5keychain.0.9.1.dylib -DQTKEYCHAIN_INCLUDE_DIR=/usr/local/opt/qtkeychain/include/qt5keychain/

CMake Warning (dev) at NEXTCLOUD.cmake:6 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:7 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:9 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:30 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:31 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:12 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build of crashreporter disabled.
-- GIT_SHA1 b6c0f9db5d034f06959821b833618d0c9ae37585
Compiling without shibboleth
-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing: PDFLATEX_EXECUTABLE) 
================> LIBCLOUDPROVIDERS_LIBRARY-NOTFOUND
-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
CMake Warning (dev) at NEXTCLOUD.cmake:6 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  NextcloudCPack.cmake:8 (include)
  CMakeLists.txt:198 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:7 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  NextcloudCPack.cmake:8 (include)
  CMakeLists.txt:198 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:9 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  NextcloudCPack.cmake:8 (include)
  CMakeLists.txt:198 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:30 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  NextcloudCPack.cmake:8 (include)
  CMakeLists.txt:198 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at NEXTCLOUD.cmake:31 (set):
  implicitly converting 'string' to 'STRING' type.
Call Stack (most recent call first):
  NextcloudCPack.cmake:8 (include)
  CMakeLists.txt:198 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using own sqlite3 from /Users/maxerhostingkft./nextcloud-desktop-client/desktop/src/3rdparty/sqlite3
-- Using own sqlite3 from /Users/maxerhostingkft./nextcloud-desktop-client/desktop/src/3rdparty/sqlite3
-- OWNCLOUD_SIDEBAR_ICONS: Nextcloud: /Users/maxerhostingkft./nextcloud-desktop-client/desktop/theme/colored/16-Nextcloud-sidebar.png;/Users/maxerhostingkft./nextcloud-desktop-client/desktop/theme/colored/18-Nextcloud-sidebar.png;/Users/maxerhostingkft./nextcloud-desktop-client/desktop/theme/colored/32-Nextcloud-sidebar.png;/Users/maxerhostingkft./nextcloud-desktop-client/desktop/theme/colored/36-Nextcloud-sidebar.png;/Users/maxerhostingkft./nextcloud-desktop-client/desktop/theme/colored/64-Nextcloud-sidebar.png
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/maxerhostingkft./nextcloud-desktop-client/desktop/src



Then this is the make:

bash-3.2$ make install
[  1%] Automatic MOC for target ocsync
[  1%] Built target ocsync_autogen
[ 29%] Built target ocsync
[ 30%] Automatic MOC for target nextcloudsync
[ 30%] Built target nextcloudsync_autogen
[ 31%] Linking CXX shared library libnextcloudsync.dylib
Undefined symbols for architecture x86_64:
  "_RSA_pkey_ctx_ctrl", referenced from:
      OCC::EncryptionHelper::decryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::EncryptionHelper::encryptStringAsymmetric(evp_pkey_st*, QByteArray const&) in clientsideencryption.cpp.o
      OCC::ClientSideEncryption::generateKeyPair() in clientsideencryption.cpp.o
  "_X509_REQ_get_subject_name", referenced from:
      OCC::ClientSideEncryption::generateCSR(evp_pkey_st*) in clientsideencryption.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libsync/libnextcloudsync.2.5.3.dylib] Error 1
make[1]: *** [src/libsync/CMakeFiles/nextcloudsync.dir/all] Error 2
make: *** [all] Error 2

**Comment by pnyers** [comment]
I think some path is not good but i can't figure out.
Have you got a working example?

**Comment by pnyers** [comment]
Do you have any idea? I am fighting since two weeks with this sh*t, but the poor docs cannot help. I just can't figure out why can't compile this.

Anybody?

**Comment by yunlhan** [comment]
@pnyers I had a similar problem this morning when I compiled it. I fixed it by replacing `-DOPENSSL_LIBRARIES` constant with an explicit `-DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl\@1.1/lib/libcrypto.dylib`. I also wrote a bash script. You can check it out [here](https://chipnotized.org/debian.html#macosx1011).

**Comment by kfkonrad** [comment]
@yunlhan the link in your comment is dead, can you comment with your precise installation steps here? I'm facing the same problem as pnyers here, btw

**Comment by yunlhan** [comment]
I'm moving and my server is traveling with me. It may be back online in a
few days. My internet access is limited at the moment. Sorry for the
inconvenience.

**Comment by yunlhan** [comment]
@kfkonrad I pasted below the script I wrote to compile the Mac client. 

 
         #!/usr/bin/env bash
         set -e
         set -o pipefail

         cd ~/Downloads
         rm -rf qtkeychain
         mkdir -pv qtkeychain && cd "$_"
         unzip ../qtkeychain-master.zip
         mkdir -pv build && cd "$_"
         cmake \
         -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk" \ 
         -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 \ 
         -DCMAKE_INSTALL_PREFIX=~/Downloads/qtkeychain/install \
         -DCMAKE_PREFIX_PATH=/usr/local/Qt-5.10.1/lib/cmake/ ../qtkeychain-master
         sudo make install
         cd .. && rm -rf build

         cd ~/Downloads
         #git clone git://github.com/nextcloud/desktop.git
         cd desktop
         #git submodule init
         #git submodule update
         git checkout stable-2.5.2
         mkdir -pv build && cd "$_"
         cmake \
         -DCMAKE_INSTALL_PREFIX=~/Downloads/nextcloud-desktop-client \
         -DCMAKE_BUILD_TYPE=Release -DNO_SHIBBOLETH=1 \
         -DQTKEYCHAIN_LIBRARY=~/Downloads/qtkeychain/install/lib/libqt5keychain.dylib \
         -DQTKEYCHAIN_INCLUDE_DIR=~/Downloads/qtkeychain/install/include/qt5keychain/ \
         -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl\@1.1/ \ 
         -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl\@1.1/include/ \ 
         -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl\@1.1/lib/libcrypto.dylib \ 
         -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl\@1.1/lib/libssl.dylib \
         -DCMAKE_PREFIX_PATH=/usr/local/Qt-5.10.1/lib/cmake/ ..
         make -j17 install
         cd .. && rm -rf build

**Comment by gsberre** [comment]
Tx, for the great script, my only problem is that the client looks like an old ugly pc application. Any idea's?

**Comment by misch7** [comment]
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

I'm working on new build scripts and I want to document the building process when everything is done and we have a stable 2.6.1 release.

@gsberre: A tip regarding the oldish look: Usually this happens when a Qt styling plugin is missing. For Qt 5.12.5 I also had to modify the deployment script to add a library, see here: https://github.com/nextcloud/desktop/pull/1515

**Comment by claucambra** [comment]
Hello, this issue is now very old and the build procedure for the client has changed quite a bit over the last 4 years. I will close this issue; feel free to reopen if needed
