### ISSUE TITLE
macOS: Desktop Client is telling the user that it is up to date but it is not

### ISSUE THREAD

**Issue by HigH-HawK** [nextcloud/desktop#1255]
### Expected behaviour
The update feature in the desktop client should tell you, if there is a new version available.

### Actual behaviour
The update feature in the desktop client always tells the user "No updates available. Your installation is at the latest version."

### Steps to reproduce
1. Go to the settings of the desktop client
2. Click the "General" tab
3. Look at the bottom of the window in "Updates" section

### Client configuration
Client version: 2.5.1final (that's the latest I can refer to but we also have others like 2.3.3 who have the same issue)

Operating system: macOS Mojave (10.14.4)

OS language: English

### Logs

Unfortunately the log files don't show any particular sign of this issue. I guess this is due to the check always delivering a `false`, so that the client always says that it is up to date.

**Comment by jonasgarstick** [comment]
Unfortunately the auto update function does not work properly since a long time with macOS. I always downloaded and installed manually but so many users are not tech oriented and yesterday I have seen a desktop client version 2.3.3 which was "up to date".

Version 2.5.2 already released:
![version](https://user-images.githubusercontent.com/17829368/57858913-39fa3280-77f2-11e9-8ea9-e50cdb42bb99.png)

**Comment by danb35** [comment]
Working auto-update would be nice, but a failing check for updates (especially one that says you're using the latest version, when you aren't) is just inexcusable.

**Comment by PhilLab** [comment]
Same happens with the Windows client:

![image](https://user-images.githubusercontent.com/1710255/63275681-3fa85e00-c2a2-11e9-8757-a3b6bc862d76.png)


I have 2.5.1 installed and 2.5.3 is the current latest version. I have killed and restarted the Nextcloud client, but it still says I was up to date

**Comment by misch7** [comment]
Hey,

I'm investigating the issue. Already managed to at least show the new client at our download page:
https://nextcloud.com/install/#install-clients

Please download and update it from there to apply it ASAP, so you don't have to wait ;-)

Unfortunately killing and restarting doesn't work at the moment because the problem is at server side, as some of you guessed already. It always reports "hey, you're up-to-date".

**Comment by HigH-HawK** [comment]
Hey misch,

thank you for looking into this. I downloaded the current client from the website and am using it since Monday this week. The only issue which still persists is, that the NC icon is still a grey box in the Finder and the context menu is still missing but that was not part of this issue or the changelog, so I didn't expect it to be fixed.

Would be nice though to get these things back in one of the next versions. However I guess this has also something to do with the newer versions of macOS (High Sierra / Mojave)

**Comment by e-alfred** [comment]
The updater server is not fixed until now, therefore no new updates of the client is shown on any desktop: https://github.com/nextcloud/client_updater_server/issues/24

**Comment by danb35** [comment]
There are no new details to provide--the client continues to be inexcusably broken in this regard.

**Comment by camilasan** [comment]
The 2.6.0 will have this fixed and you will get a notification + link to download the next release after it.

**Comment by jonathanmmm** [comment]
I have updated from 2.3.x to 2.5.x and I got erros and such (like not wanting to upload specific .odt files, saying timeout, but only for one user, same machine, other Windows account and file synced), so I downgraded again. Maybe the reason is that 2.5.x is just not the production stable version.

**Comment by camilasan** [comment]
#1002

**Comment by misch7** [comment]
For Linux and Windows this issue has been fixed (for details see https://github.com/nextcloud/desktop/issues/927#issuecomment-538642639).

Unfortunately for Mac there is more work to do within the client. So hopefully we will get this working in the 2.6.1 release then.

**Comment by misch7** [comment]
> Hey misch,
> 
> thank you for looking into this. I downloaded the current client from the website and am using it since Monday this week. The only issue which still persists is, that the NC icon is still a grey box in the Finder and the context menu is still missing but that was not part of this issue or the changelog, so I didn't expect it to be fixed.
> 
> Would be nice though to get these things back in one of the next versions. However I guess this has also something to do with the newer versions of macOS (High Sierra / Mojave)


Hey @HigH-HawK, there are some design changes in our recent 2.6.0 release:

https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-2.6.0.20190927.pkg

Did you try it already and have the problems been fixed, you mentioned?

**Comment by jonasgarstick** [comment]
> > Hey misch,
> > thank you for looking into this. I downloaded the current client from the website and am using it since Monday this week. The only issue which still persists is, that the NC icon is still a grey box in the Finder and the context menu is still missing but that was not part of this issue or the changelog, so I didn't expect it to be fixed.
> > Would be nice though to get these things back in one of the next versions. However I guess this has also something to do with the newer versions of macOS (High Sierra / Mojave)
> 
> Hey @HigH-HawK, there are some design changes in our recent 2.6.0 release:
> 
> https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-2.6.0.20190927.pkg
> 
> Did you try it already and have the problems been fixed, you mentioned?

With 2.6.0 the Nextcloud icon is back finally and after a forced Finder restart the context menu also works 👍

**Comment by HigH-HawK** [comment]
Hey @misch7 

Thanks for the update, just downloaded and installed the new version. I can also confirm that the icon in the Finder is a Nextcloud icon again instead of that ugly grey box. The context menu is working as well, so I am happy :) Well done and thank you!

**Comment by huste** [comment]
> 
> 
> For Linux and Windows this issue has been fixed (for details see [#927 (comment)](https://github.com/nextcloud/desktop/issues/927#issuecomment-538642639)).

Unfortunately, the currently installed version (2.6.1. on my Windows 10 desktop) does not show the need to upgrade. It worked from a really old version to 2.6.1 but fails again now.
