### ISSUE TITLE
Desktop Client Share Options Not Showing Up

### ISSUE THREAD

**Issue by eatyourpeas747** [nextcloud/desktop#1258]
### Expected behaviour
Tell us what should happen
When I click on the 3 dots next to the trash can to change sharing options it should bring up the options.

### Actual behaviour
The triangle moves about 1 pixel but doesnt show a menu

### Steps to reproduce
1.Click on file to share in windows explorer
2.Select a person to share with and then hit the 3 dots
3.

### Client configuration
Client version:2.5.2

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

![nextclouda1](https://user-images.githubusercontent.com/33262930/57876175-b84ed880-77e2-11e9-8619-cf55c1ddf44d.PNG)

**Comment by Mojo90** [comment]
Client version: `Version 2.5.2git (build 20190319)`
Operating System: `macOS Mojave 10.14.3 (18D109)` (Dark Mode)
OS language: English

I even do not see the nextcloud sharing item which is shown in the doc [here](https://docs.nextcloud.com/desktop/2.5/navigating.html#sharing-from-your-desktop).

That is how it looks for me: 
<img width="446" alt="Screenshot 2019-06-09 at 23 17 17" src="https://user-images.githubusercontent.com/2122156/59164418-c0ade100-8b0c-11e9-808f-1719d5432c03.png">

**Comment by michaelstingl** [comment]
> Operating System: `macOS Mojave 10.14.3 (18D109)` (Dark Mode)

@Mojo90 your macOS Mojave issue looks like https://github.com/nextcloud/desktop/issues/762
(verify with the workaround: 🍎 > Force Quit … > Finder – (needed after every reboot))
