### ISSUE TITLE
No confirmation is asked before syncing large files despite the clients settings

### ISSUE THREAD

**Issue by NinaNC** [nextcloud/desktop#126]
via Facebook, let me know if I need to forward questions

"I've installed NextCloud 2.3.3. (build1) on a Win10 PC.

Despite the client setting “request confirmation before synchronization folders larger than xx MB” I got no warning message, and a file of more than 2MB synchronizes.

Very expensive when relying on mobile data by Smarphone."

The issue was already present with the ownCloud client.

**Comment by JRMBXL** [comment]
![nextcloud](https://user-images.githubusercontent.com/35529375/35043798-3dd3e914-fb8e-11e7-8943-4cc32829b8ee.PNG)

**Comment by JRMBXL** [comment]
the answer is that the limit only concern adding à folder to synchronise and note a single file ?! ?! 

https://help.nextcloud.com/t/client-2-3-3-no-confirmation-asked-before-sync-of-big-files/25953

**Comment by DominiqueFuchs** [comment]
@jancborchardt do you think a

1. change of this option (wording and code) to apply it to single file sizes or
2. additional setting to apply file limits complementing the folder setting

would make sense (or break intentions of the NC workflow)? I must admit, before reading this issue I didn't _read_ the sentence word by word, too (and always assumed this setting would limit _everything_ bigger than the threshold). Even though it is pretty clear here, I imagine potentially more people being confused why the limit doesn't work.

**Comment by jancborchardt** [comment]
Yeah, it’s confusing that it says "folders" and then doesn’t work for files.

I’d propose:
- Change the wording to "files/folders"
- Enforce the setting for both files and folders if it’s set
- The default stays the same, _not_ enabled and at 500 MB preset

Makes sense @DominiqueFuchs?

**Comment by DominiqueFuchs** [comment]
@camilasan FYI

**Comment by Rello** [comment]
Client integration changed since this request. will need to be reevaluated if still relevant
