### ISSUE TITLE
Client crashes if synced filesystem / directory is locally not available

### ISSUE THREAD

**Issue by jenoe** [nextcloud/desktop#1260]
### Context
some of the synced folders are in an encrypryted disk volume and therefore not available temporarily until I entered the password.

### Expected behaviour
if the folders to be synced are not available I expect the client to hold on syncing of those folders and continues with other available folders. it should restart syncing as soon as the folders are available again.

### Actual behaviour
If i lock my pc the ecncrypted disk will be dismounted for security reasons. somewhen then the client crashes.

if i restart the client if the folders are still dismounted it shows the expected behaviour: errors for those folders that are not available "unable to find local sync folder".

### Steps to reproduce
1. folders get dismounted (for certain reasons)
2. nextcloud tries to sync and crashes
3. manually restarting nextcloud
4. shows that "unable to find local sync folder"
5. mounting of folders
6. resyncing starts after a bit

### Client configuration
Client version: 2.5.2
Operating system: Win 10
OS language: german
Installation path of client: C:\Program Files (x86)\Nextcloud

**Comment by jenoe** [comment]
this issue still exists.

**Comment by mgallien** [comment]
There are two points in your report.
The first is a crash when you make some synced folder unavailable. Can you still reproduce it ?

The second one is about an improvement to automatically pause/resume sync when folders are available or missing.

Let's start by the crash. Can you still reproduce it with the latest version ?

**Comment by jenoe** [comment]
sorry, for my late reply. 
yes, also with the latest client for win the problem still exists.

workflow to reproduce:

* all folders/shares mounted
* nextloud in sync
* on share / folder unmounted
* when i try to reopen the client or just wait for some time the client crashes
