### ISSUE TITLE
Five problems with the installation procedure

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [nextcloud/desktop#1263]
### Expected behaviour
None of 1-5 below.

### Actual behaviour
1. Upon running the (Windows) installer of the desktop application, and choosing the 'login' (as against 'register with a provider' option), I was prompted for a web server address. Earlier, and via the web, I had signed up with Webco hosting for a nextcloud account; yet, I was unprepared to be asked for a web server address. I wondered whether it is what my hosting provider - which whom I had signed up a few minutes earlier - called the 'webDAV address'. So I entered that.

2. The NextCloud application responded to that input (the webDAV address) by doing, only, the following: it displayed a window where I could sign up with a hosting provider. (Nor - call this (2b) - was there a _back_ button up that window.)

3. I supplied the sign-up window with the host credentials that I had created already. Seemingly the result was that the provider *recreated* those credentials!

4. The server address input box shows an icon that denotes an insecure server. The box shows that icon by default in the sense that it shows it before one types anything. I believe that behaviour unhelpful.

5. Once I had managed to progress within the installation procedure, the default folder set up to sync was one . . that did not exist yet; hence the UI warned that that folder has zero free bytes. I believe that behaviour (or those behaviours) unhelpful.

I imagine that I am about to go through some similar difficulties (viz., 1-3) in a moment, when I install the Linux client on my Linux computer. (Still, I am excited to try nextcloud.) **EDIT**: ah, on _Linux_, I did _not_ have problem 3. Nor did I have problem 5b on Linux, in that, though the suggested sync folder did not exist, it was marked as having free space. I suppose that on Windows there was no write access to the suggested path; that does not mean nothing needs changing here. 

### Steps to reproduce
Please see above.

### Client configuration
Client version: 2.5.2

Operating system: Windows 8.1 Home x64

OS language: English (UK)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

"C:\Program Files (x86)\Nextcloud\nextcloud.exe"

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?

**Comment by LinuxOnTheDesktop** [comment]
I gave up on NextCloud, because of these problems, long ago, I am afraid.

**Comment by mgallien** [comment]
I am sorry for you
