### ISSUE TITLE
Installing on Linux: fails to connect, sometimes hanging and crashing-to-desktop; icon problem

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [nextcloud/desktop#1264]
### Expected behaviour
I should be able to get the app to work.

### Actual behaviour
The following two problems, _in addition_ to the problems detailed at #1263.
1. 'No connection to NextCloud at [name of my hosting provider]'. On _Windows_, giving the app the same provider details worked. Is the problem here on Linux a firewall problem? Is there documentation about firewall settings for NextCloud clients? Yet, I disabled my firewall and still I see that error message. Moreover, or at least the first time I tried this step, NextCloud crashed to the desktop.

2. The NextCloud icon is positioned wrongly. This may nor may not be a Mint or Cinnamon problem as against your problem. Here is an image of the relevant part of my screen:

![Untitled](https://user-images.githubusercontent.com/47056543/57974395-37910780-79af-11e9-8f56-bd259e9403b4.png)

Perhaps NextCloud is trying to elbow out Dropbox. Given the problems I am having, it may not succede!

### Steps to reproduce
Please see above.

### Client configuration
Client version: All the app says is that it is the latest version. I used the AppImage (because the PPA for Ubuntu - I am on Mint - warned that I should not use it).

Operating system: Mint 19.1 x64 Cinnamon

OS language: English (UK)

Qt version used by client package (Linux only, see also Settings dialog): 5.11.0

Client package (From Nextcloud or distro) (Linux only): 2.5.2git

Installation path of client: well, it is an AppImage - on my local drive.

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by LinuxOnTheDesktop** [comment]
And now I see the following (username redacted). Does it mean that there is (still) a problem. _Or_ does it mean that was a problem but now it has been solved?

![Untitled](https://user-images.githubusercontent.com/47056543/57974684-40d0a300-79b4-11e9-89b1-b0e31d0970bd.png)

So far as I can tell, it means there is still a problem. Or at least there *is* still a problem: files are not syncing. Moreover, the sync folder has been renamed, wrongly, and I find no way to change that folder from within the app. Dear me.

**Comment by xelcho** [comment]
I am having the same issues here. ubuntu 18.04 w kde desktop. I'll add that I downloaded the 2.5.0 appimage version and it worked fine.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?
