### ISSUE TITLE
User disabled 

### ISSUE THREAD

**Issue by jasonbrown1965** [nextcloud/desktop#1265]
### Expected behaviour
Log into nextcloud desktop client with username and password

### Actual behaviour
Password box greys out with error text = "User disabled" 

### Steps to reproduce
1. Close client
2. Reopen client
3. Attempt to sign in and sync
4. Result - stalled on sync

### Client configuration
Client version: 2.5.2
 
Operating system:
Windows 7 Pro

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
"C:\Program Files\Nextcloud32\nextcloud.exe"

**Comment by FlexW** [comment]
I think this bug does not apply anymore because Flow2 is now used.
