### ISSUE TITLE
Build descriptions in Wiki are outdated

### ISSUE THREAD

**Issue by csware** [nextcloud/desktop#1268]
The build descriptions in the Wiki are outdated. Please update.

For example https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client states that OpenSSL 1.1 is required and that the libs are available on https://indy.fulgan.com/SSL/. That is not the case, there onyl OpenSSL 1.0 is available (how comes that the official version 2.5.2 is linked to OpenSSL 1.0 when the source requires 1.1?)

Also what components of Qt are required?

It would be great to have a detailed descripton on how to build with VS2017/VS2019 on Windows.

**Comment by csware** [comment]
* https://github.com/csware/nextcloud-desktop-wiki/commits/windows-outdated (https://github.com/csware/nextcloud-desktop-wiki/compare/master...windows-outdated)
* https://github.com/csware/nextcloud-desktop-wiki/commits/build-linux (https://github.com/csware/nextcloud-desktop-wiki/compare/master...build-linux)

**Comment by codeling** [comment]
I would also be interested in this. I tried looking into building OpenSSL myself but this seems to be a major endeavour as well, as it requires Perl and apparently some obscure "dmake" build tool for which I couldn't find any pre-built binaries...

**Comment by edgeboyo** [comment]
If anyone on Windows has trouble fining OpenSSL 1.1.x binaries, since the link on the Wiki leads to 1.0.x, here's some with an installer: [https://slproweb.com/products/Win32OpenSSL.html](https://slproweb.com/products/Win32OpenSSL.html)

**Comment by mgallien** [comment]
We have been improving build system to better report error when initializing the build tree.
The wiki page has probably been updated since you reported this issue because it is now up to date.
