### ISSUE TITLE
Client downloads files again when they are copied over from another machine

### ISSUE THREAD

**Issue by Popkornium18** [nextcloud/desktop#1270]
### Expected behaviour
Client detects local files and does not download anything.

### Actual behaviour
The client downloads every file again.

### Steps to reproduce
1. Copy a couple hundred GBs from your old machine to your new one
2. Connect the Nextcloud client on your new machine to your server
3. The client ends up downloading everything again instead of realizing that every file is already present in the folder

### Client configuration
Client version: 2.5.2

Operating system: Arch Linux

OS language: German

Qt version used by client package: 5.12.3

Client package: distro

Installation path of client: /usr/bin/nextcloud

### Server configuration

Operating system: Debian 9

Web server: Apache 2.4.25

Database: MariaDB 10.1.38

PHP version: 7.3

Nextcloud version: 16.0.1

If you need any further information I'd be happy to provide it.

**Comment by mgallien** [comment]
Can you test if you can reproduce with the latest version ?
If the issue is fixed, can you close the issue ?

**Comment by Popkornium18** [comment]
Works as expected, thanks!
