### ISSUE TITLE
login error with windows and ios client

### ISSUE THREAD

**Issue by dssfranz** [nextcloud/desktop#1272]
We are using nextcloud 14.0.10  ( apache 2.4.37, php 7.3 , mariadb5.5)  behind a transparent proxy ( pound, handles ssl)  in a FreeBSD (10.4) jail.
and we are running in a subfolder like  https://example.com/nextcloud 

Login via Browser works fine, but with the actual clients for Windows and Ios the following error message appears:

Not Found

The requested URL /nextcloud&user:xxxxx&password:24vCFUKMh9dnrWqk0X3KcYIUlCE4eG9cejdyaDLJpe6TaZENFTk6XxSFJDfjWdqGY0HdcB7f was not found on this server.

The Android-client doesn‘t show this behavior.

As a workaround , we are using the owncloud-clients for Windows and Ios without any problems.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?
