### ISSUE TITLE
Permanent Sync & high CPU load on MacOS

### ISSUE THREAD

**Issue by solick** [nextcloud/desktop#1274]
Nextcloud 2.5.2 client for MacOS uses permanent high cpu load (> 95%) and never stops syncing.

### Expected behaviour
Should not use much CPU capacity. have periods where client does not need to sync

### Actual behaviour
Is permanently syncing & consumes more than 95% cpu load

### Steps to reproduce
1. Have 2 NC server under management
2. just sync

### Client configuration
Client version: 2.5.2

Operating system: MacOS 10.14.5

OS language: German

Installation path of client:

### Server configuration
NC 15.0.7

Operating system: Ubuntu 18.04

Web server: Nginx

Database: Mysql 5.7.23

PHP version: php-fpm 7.0

Nextcloud version: 15.0.7

Storage backend (external storage):

**Comment by ja573** [comment]
Does it actually sync? Some people (including me) are experiencing https://github.com/nextcloud/desktop/issues/1133 in linux

**Comment by solick** [comment]
@ja573 on mac macbook I switched back to version 2.3.3 which is working fine. On my iMac I use the 5.2 version and it works but this is a very potent machine with 32 GB RAM. I think the process for sync in the 5.x version consumes to much energy to work fine on notebooks

**Comment by ja573** [comment]
Thanks @solick - I switched back to 2.5.0, but it's true that it's too heavy, I'll give 2.3.3 a try. I'd expect more people complaining about this.

**Comment by bruman** [comment]
I am having the same issue with 2.5.2 on the Mac. I am syncing 43G and approximately 96,000 files. It would take multiple days to complete a sync and at the end of it the Mac OS would report the Nexcloud client is not responding. I switched back to 2.3.3 and the sync completed with in a couple hours. I am only syncing a subset of the files from nextcloud my user account on the server has 162G and 478,000 files.

**Comment by solick** [comment]
Its strange, sometimes it is working and sometimes it takes hours and days. I have two next clouds in the client managed and from time to time the one is completely blocking the client preventing the other NC to sync. I was wandering if there is a cyclic complete rescan and if it is possible to disable this?

**Comment by ja573** [comment]
Well I guess that's needed for consistency - the question is why is it faster in previous versions :thinking:

**Comment by solick** [comment]
So i gave up and rolled back to 2.3.3
Have a 2 days sync behind me and still seeing high cpu load and sync activities and also non responding of the client over hours!

**Comment by samuel-emrys** [comment]
I'm having the same issue on 2.6.0 after just upgrading from 2.3.3. I start the client and CPU usage goes to 100% and becomes non-responsive. It seems like it does eventually become responsive again, but while it's syncing I can't have any interaction with the client at all; is the client not threaded at all?

**Comment by misch7** [comment]
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

Perhaps it solves the issue due to the Qt upgrade or other fixes?

**Comment by vpiskunov** [comment]
Similar issue here perhaps? On 2.6.1stable (20191105) CPU is jumping all the time from 0 to 25-47% literally every second, meaning unusable on MacBook whilst on battery power at all. Any remedy?

**Comment by Upperholme** [comment]
I've just updated to 2.6.1 on my ageing Macbook Pro and it is chewing up CPU and energy. The previous version that I had installed (2.5.x?) seemed to run fine, but it's not sensible for me to keep this running now - fans spinning all the time and the machine getting very hot. It would be great to see a fix for this.

**Comment by ad5030** [comment]
Same for me : I've just updated to 2.6.1 and CPU is jumping all the time to 20-40%. With more keychain access !

**Comment by mibocs** [comment]
Same. Cpu load is always around 10%...

**Comment by samuel-emrys** [comment]
I'm still getting very high cpu usage on 2.6.4stable (build 20200303). It's much more intermittent now, but every 30 seconds or so it spins up to 100% CPU usage and locks the gui entirely. This is making the gui very difficult to use. It's not very inspiring that this issue has persisted over multiple major releases of the client.

I'm on macOS Mojave 10.14.5

**Comment by mgallien** [comment]
@solick could you please test again with our latest release (3.4.1 at the moment) ?

**Comment by mibocs** [comment]
@mgallien 
> could you please test again with our latest release (3.4.1 at the moment) ?
I have tested it with version 3.4.4 and CPU usage is now 0 i.e zero, so it seems to be working well. Good job, Big THANKS!
