### ISSUE TITLE
Confusing message when clearing local directory

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#1277]
### Expected behaviour

To prevent accidental deletion of files, nextcloud presents understandable messages to the user.

### Actual behaviour

![image](https://user-images.githubusercontent.com/571494/58472018-99870500-8145-11e9-80b5-30f395abd967.png)

The client first explains that local files have been deleted and that change will be synced to the server. To recover from a possible error, it offers me to "keep local files", which have been deleted, or "download new files", of which there are none (the action happened on the local machine and was about _removing_ files, not adding  _new_ ones).

This doesn't make sense. 

### Steps to reproduce
1. Delete all files in local directory
2. Sync client detects the change
3. This alert box appears.

### Client configuration
Client version: 2.5.2git

Operating system: Ubuntu 18.04

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): `ii nextcloud-client 2.5.2-20190319.015224~bionic1 amd64 Nextcloud desktop sync client` from ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client: `/usr/bin/nextcloud`

**Comment by curiousDTU** [comment]
duplicate issue please see  issue #1198

**Comment by darmbrust** [comment]
see further comments here https://github.com/nextcloud/desktop/issues/1198#issuecomment-504583381

This message is displayed in many confusing contexts, and the options make no sense in many.

**Comment by FlexW** [comment]
@despens Could you please test again? I think this bug is solved. If yes, could you please close it?

**Comment by despens** [comment]
With version 3.2.2 of the desktop sync client, this dialog does not appear anymore when deleting all contents of a synced folder. Instead, the client for a brief moment shows the message "Reconciling changes" before going into a state of perpetual "preparing to sync" for that folder. This is blocking other folder sync connections to progress syncing. This remains the case after restarting the nextcloud desktop client or chosing "Force sync now". The files are not being deleted or moved to trash on the nextcloud server.

**Comment by despens** [comment]
Thanks @mgallien, I would like to provide my logs, but the client generates a zip archive larger than 60 MB. Could you tell me how I can clear legacy logs before exporting?

I have reproduced the behavior in question a few times now and probably the logs would help identifying the issue.

**Comment by mgallien** [comment]
> Thanks @mgallien, I would like to provide my logs, but the client generates a zip archive larger than 60 MB. Could you tell me how I can clear legacy logs before exporting?
> 
> I have reproduced the behavior in question a few times now and probably the logs would help identifying the issue. The desktop client is hanging for the emptied folder in this state:
> 
> ![Screenshot-20210610105958-742x97](https://user-images.githubusercontent.com/571494/121497042-52da6f80-c9db-11eb-8dee-51f1ca892c87.png)

the log by default are cleared after 24 hours

if needed I should be able to create a directory for you to upload the archive anyway even if it is big
