### ISSUE TITLE
Desktop Client on Windows Crashes

### ISSUE THREAD

**Issue by holzfelix** [nextcloud/desktop#1279]
Hi I have the Issue that the windows client crashes right after entering the server url to and clicking on next.

W10 current version
chrome
client 2.5.2

microsoft surface

anybody out there with the same issue?

Thanks in advance.

**Comment by camilasan** [comment]
Hi! Does the same happen 2.5.3 rc1?

**Comment by TobiasDev** [comment]
I have the same issue in the same version but on Ubuntu. It just keeps crashing so I can't sync all my files.

**Comment by holzfelix** [comment]
> Hi! Does the same happen 2.5.3 rc1?

yes still same issue with 2.5.3 rc1

**Comment by benhartwich** [comment]
Hi,

this problem happens also at my nextclouds. I´ve tried the nextcloud on windows 10 64 bit and windows 2012 r2. The app crashes after a few days suddenly. I´m using different group folders, which could be the reason why nextcloud becomes unstable. I´ve attached the windows error:
![2019-06-18_10h38_08](https://user-images.githubusercontent.com/4061954/59666934-23127b80-91b6-11e9-8db0-56f15899418e.png)
![2019-06-18_10h38_28](https://user-images.githubusercontent.com/4061954/59666935-23127b80-91b6-11e9-95c6-05949620d5b1.png)

**Comment by benhartwich** [comment]
It happened again with version 2.5.1 and I can provide a dump: https://cloud.speibox.de/s/xKPPS5DSYWyw3Gt
Please write me a personal message for providing the download password.

**Comment by rleo79** [comment]
Same problem happens here:

Nome dell'applicazione che ha generato l'errore: nextcloud.exe, versione: 2.5.2.5231, timestamp: 0x5c90e346
Nome del modulo che ha generato l'errore: nextcloudsync.dll, versione: 0.0.0.0, timestamp: 0x5c90e1f4
Codice eccezione: 0xc0000005
Offset errore 0x0000000000046093
ID processo che ha generato l'errore: 0x1654
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d528190d2a62b5
Percorso dell'applicazione che ha generato l'errore: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Percorso del modulo che ha generato l'errore: C:\Program Files (x86)\Nextcloud\nextcloudsync.dll
ID segnalazione: 3c1dfaf8-940d-11e9-8fb0-000c29c27527

OS: Windows 7 Pro

**Comment by jabratn** [comment]
Testing with Windows 10 IOT: crashes with all v2.5.x.
(v2.3.3.1 starts up and works as expected).

Example crash from event viewer:
Version=1
EventType=APPCRASH
EventTime=132070535154692352
ReportType=2
Consent=1
ReportIdentifier=f2b292b1-a166-11e9-98c3-00e04c68007c
IntegratorReportIdentifier=293b37e7-ce7c-4633-a6f2-e92b3abf782a
NsAppName=nextcloud.exe
AppSessionGuid=00001bfc-0001-0052-325b-ddb47335d501
TargetAppId=W:0006d2c705b8a75e8744e17a10c2f5f09dd500000908!00002857e10b9b5f9438b4e31fd388b7c14254784379!nextcloud.exe
TargetAppVer=2019//03//19:12:40:38!0!nextcloud.exe
BootId=4294967295
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=nextcloud.exe
Sig[1].Name=Application Version
Sig[1].Value=2.5.2.5231
Sig[2].Name=Application Timestamp
Sig[2].Value=5c90e346
Sig[3].Name=Fault Module Name
Sig[3].Value=ig9icd64.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=25.20.100.6373
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5bda123a
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=000000000001fd1e
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.14393.2.0.0.256.125
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=eb99
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=eb998c16b8d81440043318d9febfc6cf
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=c066
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=c0663ca4ebb8a593f16458c77172080a
UI[2]=C:\Program Files (x86)\Nextcloud\nextcloud.exe
UI[3]=Nextcloud has stopped working
UI[4]=Windows can check online for a solution to the problem the next time you go online.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\Nextcloud\nextcloud.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\apphelp.dll
LoadedModule[5]=C:\Windows\System32\ucrtbase.dll
LoadedModule[6]=C:\Windows\System32\SHELL32.dll
LoadedModule[7]=C:\Windows\System32\msvcrt.dll
LoadedModule[8]=C:\Windows\System32\cfgmgr32.dll
LoadedModule[9]=C:\Windows\System32\windows.storage.dll
LoadedModule[10]=C:\Windows\System32\combase.dll
LoadedModule[11]=C:\Windows\System32\RPCRT4.dll
LoadedModule[12]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[13]=C:\Windows\System32\powrprof.dll
LoadedModule[14]=C:\Program Files (x86)\Nextcloud\Qt5Xml.dll
LoadedModule[15]=C:\Windows\System32\advapi32.dll
LoadedModule[16]=C:\Windows\System32\sechost.dll
LoadedModule[17]=C:\Windows\System32\shlwapi.dll
LoadedModule[18]=C:\Windows\System32\GDI32.dll
LoadedModule[19]=C:\Windows\System32\gdi32full.dll
LoadedModule[20]=C:\Windows\System32\USER32.dll
LoadedModule[21]=C:\Windows\System32\win32u.dll
LoadedModule[22]=C:\Windows\System32\kernel.appcore.dll
LoadedModule[23]=C:\Windows\System32\shcore.dll
LoadedModule[24]=C:\Program Files (x86)\Nextcloud\nextcloudsync.dll
LoadedModule[25]=C:\Windows\System32\profapi.dll
LoadedModule[26]=C:\Program Files (x86)\Nextcloud\ocsync.dll
LoadedModule[27]=C:\Windows\System32\ole32.dll
LoadedModule[28]=C:\Program Files (x86)\Nextcloud\qt5keychain.dll
LoadedModule[29]=C:\Program Files (x86)\Nextcloud\Qt5WebEngineWidgets.dll
LoadedModule[30]=C:\Program Files (x86)\Nextcloud\Qt5WebEngineCore.dll
LoadedModule[31]=C:\Program Files (x86)\Nextcloud\Qt5Network.dll
LoadedModule[32]=C:\Windows\System32\WS2_32.dll
LoadedModule[33]=C:\Windows\System32\CRYPT32.dll
LoadedModule[34]=C:\Windows\System32\MSASN1.dll
LoadedModule[35]=C:\Program Files (x86)\Nextcloud\Qt5Widgets.dll
LoadedModule[36]=C:\Program Files (x86)\Nextcloud\Qt5Gui.dll
LoadedModule[37]=C:\Program Files (x86)\Nextcloud\Qt5Core.dll
LoadedModule[38]=C:\Program Files (x86)\Nextcloud\MSVCP140.dll
LoadedModule[39]=C:\Program Files (x86)\Nextcloud\VCRUNTIME140.dll
LoadedModule[40]=C:\Program Files (x86)\Nextcloud\libcrypto-1_1-x64.dll
LoadedModule[41]=C:\Program Files (x86)\Nextcloud\Qt5Quick.dll
LoadedModule[42]=C:\Program Files (x86)\Nextcloud\Qt5PrintSupport.dll
LoadedModule[43]=C:\Windows\System32\COMDLG32.dll
LoadedModule[44]=C:\Program Files (x86)\Nextcloud\Qt5QuickWidgets.dll
LoadedModule[45]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[46]=C:\Windows\System32\NSI.dll
LoadedModule[47]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[48]=C:\Windows\SYSTEM32\MPR.dll
LoadedModule[49]=C:\Windows\SYSTEM32\NETAPI32.dll
LoadedModule[50]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[51]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[52]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[53]=C:\Windows\SYSTEM32\UxTheme.dll
LoadedModule[54]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[55]=C:\Program Files (x86)\Nextcloud\MSVCR120.dll
LoadedModule[56]=C:\Windows\SYSTEM32\WINSPOOL.DRV
LoadedModule[57]=C:\Program Files (x86)\Nextcloud\Qt5Qml.dll
LoadedModule[58]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.14393.2457_none_a13eaee9d8fd5c07\COMCTL32.dll
LoadedModule[59]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[60]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[61]=C:\Windows\System32\msvcp_win.dll
LoadedModule[62]=C:\Windows\System32\PSAPI.DLL
LoadedModule[63]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[64]=C:\Program Files (x86)\Nextcloud\Qt5WebChannel.dll
LoadedModule[65]=C:\Program Files (x86)\Nextcloud\Qt5Positioning.dll
LoadedModule[66]=C:\Windows\SYSTEM32\NETUTILS.DLL
LoadedModule[67]=C:\Windows\SYSTEM32\dbghelp.dll
LoadedModule[68]=C:\Windows\SYSTEM32\USP10.dll
LoadedModule[69]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[70]=C:\Windows\SYSTEM32\Secur32.dll
LoadedModule[71]=C:\Windows\SYSTEM32\urlmon.dll
LoadedModule[72]=C:\Windows\SYSTEM32\WINHTTP.dll
LoadedModule[73]=C:\Windows\SYSTEM32\DWrite.dll
LoadedModule[74]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[75]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[76]=C:\Windows\SYSTEM32\HID.DLL
LoadedModule[77]=C:\Windows\SYSTEM32\iertutil.dll
LoadedModule[78]=C:\Windows\SYSTEM32\dxva2.dll
LoadedModule[79]=C:\Windows\SYSTEM32\SRVCLI.DLL
LoadedModule[80]=C:\Windows\SYSTEM32\d3d9.dll
LoadedModule[81]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[82]=C:\Windows\SYSTEM32\SSPICLI.DLL
LoadedModule[83]=C:\Windows\System32\IMM32.DLL
LoadedModule[84]=C:\Program Files (x86)\Nextcloud\platforms\qwindows.dll
LoadedModule[85]=C:\Program Files\Common Files\microsoft shared\ink\tiptsf.dll
LoadedModule[86]=C:\Windows\SYSTEM32\opengl32.dll
LoadedModule[87]=C:\Windows\SYSTEM32\GLU32.dll
LoadedModule[88]=C:\Windows\SYSTEM32\DDRAW.dll
LoadedModule[89]=C:\Windows\SYSTEM32\DCIMAN32.dll
LoadedModule[90]=C:\Windows\System32\MSCTF.dll
LoadedModule[91]=C:\Windows\System32\DriverStore\FileRepository\ki130483.inf_amd64_c995e45e5ae6396c\ig9icd64.dll
LoadedModule[92]=C:\Windows\System32\DriverStore\FileRepository\ki130483.inf_amd64_c995e45e5ae6396c\igdgmm64.dll
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=Nextcloud
AppPath=C:\Program Files (x86)\Nextcloud\nextcloud.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=09949773DC0EFEE330865CEDE4EAD22C
MetadataHash=-220251221

**Comment by biva** [comment]
If it's a similar issue as https://github.com/nextcloud/desktop/issues/2266#issuecomment-690979080, I advise you to delete these folders:

    C:\Users\yourname\AppData\Local\Nextcloud
    C:\Users\yourname\AppData\Roaming\Nextcloud

**Comment by tkafka** [comment]
Hello, this seems to be relevant bug in QT: https://bugreports.qt.io/browse/QTBUG-50371?focusedCommentId=329417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel
