### ISSUE TITLE
Negation for file ignore patterns?

### ISSUE THREAD

**Issue by cl0ne** [nextcloud/desktop#128]
Hi,

It would be nice to have negation support for ignore patterns, for example as in `.gitignore` files (`!` in front of the pattern).

Use case: encfs XML file starts with dot, so it's hidden. I want to sync this file while ignoring other hidden files/dirs.

Probably, related to #26.

**Comment by zippytiff** [comment]
is the ignore files feature considered working in this 2.5.x ?

ZT

**Comment by alexx518** [comment]
I have tested the negation support of wildcards on windows client in the version 2.5.1final (build 20181204) and it's not working.

**Comment by microtronics** [comment]
Also interested in this feature

**Comment by Rello** [comment]
Client integration changed since this request. will need to be reevaluated if still relevant
