### ISSUE TITLE
Cannot build because QtKeychain requires Qt4?!

### ISSUE THREAD

**Issue by b0bh00d** [nextcloud/desktop#1281]
I just switched to Nextcloud from ownCloud, and I'm wanting to fix a bug in the desktop client that is driving me nuts.  It's a common problem with Qt widgets, and being a Qt developer, I know exactly how to address it.  However...

After spending hours yesterday getting the pieces in place to build this project--Qt 5.12.3, CMake, Visual Studio, ZLib, etc.--and after spending time to get the correct build steps in place (the Wiki for this is woefully sparse and less than helpful), I run into a build error that it's missing "keychain.h."  Ok, this project requires QtKeychain (https://github.com/frankosterfeld/qtkeychain)--something else missing from the Nextcloud build Wiki--so, I download it and try to build it locally when--lo and behold--it complains that it requires Qt 4!

`Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x`

This can't be correct.  I've tried numerous configuration settings to try to get it to find my 5.12.3 install, but it simply won't work.

The "issue" I'm reporting here with Nextcloud Desktop is that its Wiki build instructions (https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client) need to be clearer and more complete.  I want to contribute, but the bar to building is a bit too high.  I'm perfectly willing to take the time to _build_ third-party dependencies, but I have no patience to be frustrated by them.  Help _us_ help _you_, please.

(btw, https://github.com/nextcloud/desktop/issues/570 from _last year_ appears to also relate to my complaint.)

**Comment by wdehoog** [comment]
Sorry I cannot help you with your specific error but I noticed that here are multiple build instructions. Maybe you can also take a look at https://github.com/nextcloud/client-building

**Comment by misch7** [comment]
Hey @b0bh00d ,

I faced the same issues, trying to build the client on Windows (for 32-bit actually) and I got lost the same way. All the instructions are outdated or at least not complete. But I figured out how to add the missing pieces and fix the puzzle. ;-)
Over the last weeks I spent a lot of my spare time to create a new and easy way to build on Windows for everybody.
This weekend I'm going to release my work after some finishing touches. I'm just posting this to save your time, don't waste your time and risk more headache! ;)

**Comment by misch7** [comment]
As promised, try this:
https://github.com/misch7/nextcloud-client-building

Happy building! ;-)

**Comment by misch7** [comment]
I recently built the client on macOS and stumbled upon the same error too (again):

> `Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x`

This usually happens when the "qmake" tool cannot be found in the PATH system environment variable.

qmake resides in the "bin" folder of the desired Qt version, in your case this would be by default:

`C:\Qt\5.12.3\msvc2017_64\bin` (for 64-bit building with VS 2017) or
`C:\Qt\5.12.3\msvc2017\bin` (for 32-bit building with VS 2017)

Also take a look at the "qtenv2.bat" scripts in their respective "bin" folder. They set the PATH for you and may be invoked either by directly calling them in Git bash or by including them with a "call" statement within a Batch file.

**Comment by camilasan** [comment]
Hi @b0bh00d, did you try @misch7's instructions?

**Comment by robertolanuti** [comment]
Hi,

I was having the same issue: 
`Found` unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x`

That was a QT path issue. After fixed that, I have got another issue:
```
CMake Error at C:/Nextcloud/tools/cmake/share/cmake-3.14/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.12.5" from C:/Qt/msvc2017/bin/qmake.exe,
  this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:97 (find_package)

```

**Comment by misch7** [comment]
> I was having the same issue:
> `Found` unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x`
> 
> That was a QT path issue and I have fixed that.

True, a very lovely one to finally figure out ^^

See above (here in this issue): https://github.com/nextcloud/desktop/issues/1281#issuecomment-503352669

> Now I'm having the following issue:
> 
> ```
> CMake Error at C:/Nextcloud/tools/cmake/share/cmake-3.14/Modules/FindQt4.cmake:1314 (message):
>   Found unsuitable Qt version "5.12.5" from C:/Qt/msvc2017/bin/qmake.exe,
>   this code requires Qt 4.x
> Call Stack (most recent call first):
>   CMakeLists.txt:97 (find_package)
> ```

@robertolanuti Take a look here, that's used to create our daily and release builds:
https://github.com/nextcloud/client-building

Maybe you get a clue what's wrong when you compare your build instructions with it ;-)

**Comment by robertolanuti** [comment]
Thank you very much @misch7 for your quick reply: I have now fixed the issue: actually the Qt installation was not right (it was missing few files).

It is now going ahead with the build... hopefully will be alright.

Thanks again @misch7 !
