### ISSUE TITLE
Client doesn't start on boot in macOS

### ISSUE THREAD

**Issue by danb35** [nextcloud/desktop#1282]
### Expected behaviour
When my computer running macOS Mojave 10.14.5 boots, the Nextcloud client should automatically start as it does on Windows computers.

### Actual behaviour
The client does not start on boot and must be manually started.

### Steps to reproduce
1. Install the latest client on macOS Mojave 10.14.5
2. Reboot the computer
3. Observe that the client does not start

### Client configuration
Client version: 2.5.2, though the behavior was the same with 2.5.1 and probably prior versions.

Operating system: macOS Mojave 10.14.5

OS language: US English

Installation path of client: /Applications/

**Comment by FlexW** [comment]
Could you please test with a more recent version (3.2.2) if the problem still exists? If not, please close the issue.
