### ISSUE TITLE
Minor spanish translation bug

### ISSUE THREAD

**Issue by ftoledo** [nextcloud/desktop#1283]
"4 minutes(s) izquierda" shoud be "4 minuto(s) restantes"

Desktop version 2.5.1git from debian stretch-bakports repository

![imagen](https://user-images.githubusercontent.com/95441/58707978-d2fd8180-838c-11e9-8c25-30f70deadfad.png)

**Comment by mgallien** [comment]
Are you still experiencing this translation bug ?
If translation is better now, please can you close the bug ?
