### ISSUE TITLE
High CPU load with 2.5.x clients on Fedora 30

### ISSUE THREAD

**Issue by Aurelien-** [nextcloud/desktop#1285]
Nextcloud 2.5.x clients for Fedora 30 use permanent high cpu load (one core 100%).

Expected behaviour: Should not use much CPU capacity.
Actual behaviour :Permanent 100% cpu load
Steps to reproduce:

    Have 2 NC servers under management
    Start Nextcloud client.

Client configuration
Client version: 2.5.0, 2.5.2
Operating system: Fedora 30
OS language: French
Installation path of client:

Server configuration
Docker images from https://github.com/nextcloud/docker with nginx/fpm/MariaDB/ 
NC 15.0.7
Operating system: Debian 9
Web server: Nginx
Database: MariaDb 10.3.14
PHP version: php-fpm 7.3.4
Nextcloud version: 15.0.7
Storage backend (external storage): s3ql

Nextcloud-client 2.3.3 was working fine on Fedora 29, but 2.5.0 on Fedora 29 had a similar issue.

**Comment by tflidd** [comment]
There are some more reports with the 2.5 branch on linux desktops:
https://help.nextcloud.com/t/high-cpu-load-linux-desktop-client/33628

**Comment by mcvayokay** [comment]
Still an issue on desktop client 2.6.2 and Fedora 31.  100% CPU usage on one core at all times, and the file sync never actually progresses.

**Comment by sweichwald** [comment]
I also encountered essentially permanent sync and high CPU load for clients 2.5.x and 2.6.x on *buntu and arch for nextcloud server 19.0.1.1 (and earlier) as reported here and in similar mac https://github.com/nextcloud/desktop/issues/1274 and micisoft https://github.com/nextcloud/desktop/issues/853 issues. https://github.com/nextcloud/desktop/issues/1983 may possibly be related, too.

The problem may be related to federated shares and this server issue https://github.com/nextcloud/server/issues/19647. In my case, the client was performing a full sync every minute as the server reported a new ETag for the federated shares irrespective of whether there were any changes. (In fact it is more subtle, as the problem only occurs if you are receiving end of the federated share and at least once failed to delete a file from the federated share, cf. https://github.com/nextcloud/server/issues/19647.)

If one is using federated shares and suffering from this cause of high client CPU load, one should see
* regular and frequent (i.e. ~once every minute)
  * repetitions of `slotRunEtagJob` followed by `ETag CHANGED` lines when running `nextcloud --logdebug --logfile -`, 
  * syncrun activity logged in `~/.local/share/Nextcloud/*.log`,
* the webclient showing "last modified < 1 min" for the affected federated share folders when entering those and immediately moving up to the parent directory again,
* __the CPU load dropping upon removal of the federated shares or excluding them from synchronisation in the client.__

**Comment by FelixSchwarz** [comment]
Fedora 33+ currently ships nextcloud 3.0.3 and I don't see high CPU load here. Is this still an issue when using the latest version?

**Comment by zachsmith** [comment]
I am still seeing this on Fedora 33 with 3.1.1
