### ISSUE TITLE
is there an 'always use client file' option regarding conflicts?

### ISSUE THREAD

**Issue by stevenba20807** [nextcloud/desktop#1288]
I have had to stop using Nextcloud on my production machine because not infrequently 50 to 200 files get incorrectly marked _conflict-.  They are always **newer** than the ones Nextcloud downloads from the cloud. 
Is there a desktop option for either "always keep local file" or "always keep newer file"?
If not, can it be incorporated?
The current functionality has caused permanent loss of data as it is not easily apparent to the users that a file is no longer current.  These files are not seen by the end user, only by the running application.
Thanks,
Steve

**Comment by veddox** [comment]
Same issue here. Gets especially nasty when the NC client scrambles files in a `.git` directory, but is generally a pain in the neck. The client is otherwise a phenomenally useful app, would be very glad to see this fixed!

**Comment by veddox** [comment]
Related to #943 - the difficulties arise when a file is erroneously synchronised with the remote. However, there may be scenarios in which one wants to declare a "master machine" that is not the server, so a configurable option is desirable anyway.

**Comment by zippytiff** [comment]
yes please ! i love nextcloud, but the biggest issue has been with the client, it just makes life so difficult and is next to impossible to get a green tick to say everything has sync'd, there is always an issue with some file or other....

**Comment by Larsene** [comment]
please ! this bug (#943 ) is very annoying. Perfering the file from the client instead of renaming the file to replace it with an older version from the server is so boring.

**Comment by pietrodito** [comment]
Same problem here with annoying conflicts. @veddox To use .git inside Nextcloud check that thread about bare repository: https://stackoverflow.com/a/62086608/6537892

**Comment by FlexW** [comment]
There is no such option at the moment and it's not planned to implement one. However, you a free to provide a pull request for this functionality yourself.
