### ISSUE TITLE
Auto-Upload All Files

### ISSUE THREAD

**Issue by ghbjklhv** [nextcloud/desktop#1291]
**Feature**: Automatically upload all images and documents
**Why?**: Although, I personally prefer keeping what I upload and keep locally separate my family really liked the tools in proprietary alternatives like [Google Photos](https://www.wikipedia.org/wiki/Google_Photos). 
They would automatically search for any document or image and upload it, regardless if it was in the provider's native folder.

Obviously, this feature should be opt-in only but, I think it would help make migrating a lot easier.

_____________________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75130680-feature-auto-upload-all-files)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by Rello** [comment]
Hello,

the client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.

Thank you for your support
