### ISSUE TITLE
"403 Forbidden" to "MOVE" files

### ISSUE THREAD

**Issue by koying** [nextcloud/desktop#1293]
I have been experiencing this issue in 2.5.2 and earlier: https://github.com/owncloud/core/issues/33119

Could I suggest you backport the fix ?
https://github.com/owncloud/client/pull/6834

Thanks

**Comment by dvdgsng** [comment]
This happens for me after upgrading the client to _2.6.0stable-Win64 (build 20190927)_ and upgrading server to _16.0.5_. Only happens with files larger than 10MB, which require being uploaded in chunks.

**Comment by GuyPaddock** [comment]
Also see:
https://github.com/nextcloud/server/issues/17980

**Comment by chesio** [comment]
Hi,

I got the very same error on my Nextcloud installation and although in my case it has not been related to a bug in Nextcloud, I'm leaving a note just in case someone with the same issue arrives here looking for a piece of advice (as I did).

I had the webserver (Nginx) configured to block access to **hidden files** and since the MOVE requests operate on a hidden file, they had been blocked. As simple as that, but took me hours to figure it out...

**Comment by n9986** [comment]
Apologies for creating noise here, but...

@chesio That was it! I had a config that blocked hidden files and I was so frustrated after hours of debugging! Thank you so much for having it recorded here! :) After dozens of pages I found this!

**Comment by maxpull** [comment]
> Hi,
> 
> I got the very same error on my Nextcloud installation and although in my case it has not been related to a bug in Nextcloud, I'm leaving a note just in case someone with the same issue arrives here looking for a piece of advice (as I did).
> 
> I had the webserver (Nginx) configured to block access to **hidden files** and since the MOVE requests operate on a hidden file, they had been blocked. As simple as that, but took me hours to figure it out...

Did you just ignore it or did you find a way around this?

**Comment by chesio** [comment]
> > Hi,
> > I got the very same error on my Nextcloud installation and although in my case it has not been related to a bug in Nextcloud, I'm leaving a note just in case someone with the same issue arrives here looking for a piece of advice (as I did).
> > I had the webserver (Nginx) configured to block access to **hidden files** and since the MOVE requests operate on a hidden file, they had been blocked. As simple as that, but took me hours to figure it out...
> 
> Did you just ignore it or did you find a way around this?

I've added a rule to `nginx.conf` to allow access to hidden files under `/remote.php/dav/uploads/...` path:
```nginx
location ~ ^/remote\.php/dav/uploads/.*/\.file$ {
    allow all;
}
```

**Comment by thiswillbeyourgithub** [comment]
I was having the same issue, what solved it for me was wrong permissions : www-data was not allowed to write on my external mount.

**Comment by joaonunatingscode** [comment]
> I was having the same issue, what solved it for me was wrong permissions : www-data was not allowed to write on my external mount.

This was my problem. Fixing permissions was the fix.
For anyone else also having this problem take a look at [this](https://help.nextcloud.com/t/change-ownership-of-nextcloud-files-root-to-www-data/150657/4).
