### ISSUE TITLE
Linux client doesn't sync contents of renamed directory

### ISSUE THREAD

**Issue by shadowlmd** [nextcloud/desktop#1294]
### Expected behaviour
Everything that happens inside Nextcloud folder must be synced with server.

### Actual behaviour
Some changes inside Nextcloud folder are ignored.

### Steps to reproduce
1. Create directory, for example, test_dir - it will be synced
2. Rename this directory, for example to renamed_dir - this change will be synced
3. Put any file into renamed_dir - in will NOT by synced

### Client configuration
Client version: 2.5.2git

Operating system: Ubuntu 16.04 64-bit

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.5.1+dfsg-16ubuntu7.6

Client package (From Nextcloud or distro) (Linux only): From Nextcloud

Installation path of client: /usr/bin/nextcloud

I am testing Linux desktop client under Ubuntu 16.04. It is installed from https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client, latest version (2.5.2git). Everything works smoothly, but sometimes client doesn’t notice files added or deleted from some directories. For example, I have created a directory “Test”, moved some picture into it almost instantly, directory was synced, picture wasn’t. There is nothing in logs when this happens. Also, the only way to force client actually upload the file is restart the client. When restarted, it finds the file and uploads it successfully.

**Comment by michaelstingl** [comment]
Related to https://github.com/nextcloud/desktop/issues/1000 ?

**Comment by shadowlmd** [comment]
No, doesn't look like #1000 to me. I didn't even try to move big directory structures, just created directory and moved file into it. And other simple stuff like that, for example, editing/moving/renaming files while they were synchronizing.

**Comment by andreaslink-de** [comment]
> Related to #1000 ?

I guess it's the same and that makes me (as a Linux user) afraid that this one is not fixed within the [2.5.3 milestone](https://github.com/nextcloud/desktop/milestone/7?closed=1). I can also second the same behavior and reproduce the error.

**Comment by nof8** [comment]
I have the same issue. Just created a folder and saved 200Kb file into it. Folder has been synced, but the file haven't.
Force sync from GUI doesn't help. Renaming a file doesn't help. Only restarting client helps.

I have Nextcloud-2.5.2-x86_64.AppImage under Linux Mint 19.1

**Comment by IngoQ** [comment]
Same here:

- created a new directory locally
- created some files in them (<10kb in sum)
- directory is synced, files are not
- no entry in the activtivity log (neither folder nor files)
- forcing sync does nothing
- folder size is reported as 0 by Nextcloud-client
- on client restart they are synced immediatly

I am running Nextcloud 2.5.2git from the PPA on Linux Mint 19.1

**Comment by shadowlmd** [comment]
I have found steps to reproduce the issue.

1. Create directory, for example, test_dir - it will be synced
2. Rename this directory, for example to renamed_dir - this change will be synced
3. Put any file into renamed_dir - in will NOT by synced

**Comment by shadowlmd** [comment]
Nice bugfixing strategy.

**Comment by shadowlmd** [comment]
What kind of info this bug report still needs?

**Comment by chainria** [comment]
This ACTUALLY led to data loss multiple times already. If you need more information, please tell us what you need.
It really is that simple as outlined before. Right now I am taking great care to not rename folders "too quickly" because of this bug.

**Comment by mgallien** [comment]
> What kind of info this bug report still needs?

I cannot reproduce it.

Without that, I am unable to fix it.

Please provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)
Thanks!
