### ISSUE TITLE
virtualdrive tech preview installer error 

### ISSUE THREAD

**Issue by dennisTGC** [nextcloud/desktop#1297]
### Expected behaviour
No errors during installation

### Actual behaviour
The following error appeared:
![20190611_1312_infra385-1](https://user-images.githubusercontent.com/12065502/59268407-e3dfaa00-8c4c-11e9-832c-45ebb8bdec18.png)

### Steps to reproduce
1. Install clean windows server 2016 (version 10.0.14393)
2. download techpreview client (version 2.5.0.5040) and install
3. while installing the error appears. 
4. After the installation, the nextcloud client and virtualdrive seems to work fine.

### Client configuration
Client version:

Operating system: Windows Server 2016 (version 10.0.14393)

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): 
https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview.exe (2.5.0.5040)

Installation path of client: default

### Server configuration

Nextcloud version: 14.0.8

Storage backend (external storage): locally mounted storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
> I didn't find any installer logs

2. Web server error log: not applicable

3. Server logfile: nextcloud log (data/nextcloud.log): not applicable

### Other
I have a snapshot saved, so I can repeat/test all suggestions. Just let me know what to do.

**Comment by Dennis360ict** [comment]
This still exists in de virtualdrive-v2 client:
https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview-v2.exe

**Comment by FlexW** [comment]
I think this does not apply anymore
