### ISSUE TITLE
virtualdrive shows empty text file 

### ISSUE THREAD

**Issue by dennisTGC** [nextcloud/desktop#1298]
### Expected behaviour
after installing the virtual drive techpreview, I open the X:\Documents\about.txt file and after it opens i should be able to view the contents.

### Actual behaviour
notepad opens and shows an empty file (no content). If i view the file from the webui, it shows that the file is not empty.

### Steps to reproduce
1. Install clean Windows server 2016 
2. install virtual drive tech preview
3. connect to nextcloud server
4. open explorer and doubleclick x:\documents\about.txt

### Client configuration
Client version: virtual drive tech preview 2.5.0.5040:
https://download.nextcloud.com/desktop/prereleases/virtualdrive/Nextcloud-virtualdrive-techpreview.exe

Operating system: freshly installed Windows server 2016 (version 10.0.14393)

OS language: english

Qt version used by client package (Linux only, see also Settings dialog): na

Client package (From Nextcloud or distro) (Linux only): na

Installation path of client: default

### Server configuration

Nextcloud version: 14.0.8

Storage backend (external storage): locally mounted storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[20190611-log1.txt](https://github.com/nextcloud/desktop/files/3276322/20190611-log1.txt)

2. Web server error log:
Only 1 entry (in debug mode):

_Fatal | webdav | OCA\DAV\Connector\Sabre\Exception\InvalidPath: Een lege bestandsnaam is niet toegestaan/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1178: OCA\DAV\Connector\Sabre\Directory->getChild(null)/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 594: Sabre\DAV\Server->createCollection("", Sabre\DAV\MkCol {})Sabre\DAV\CorePlugin->httpMkcol(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:MKCOL", [ Sabre\HTTP ... }])/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/html/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/html/remote.php - line 163: require_once("/var/www/ht ... p")
-- | -- | --_

There's some dutch in there:
"een lge bestandsnaam is niet toeggestaan" ~= an empty file name is not allowed

3. Server logfile: nextcloud log (data/nextcloud.log):
Only 1 entry of today:

_{"reqId":"utGmC1xQynrg51P9ukFI","level":4,"time":"2019-06-11T13:17:21+02:00","remoteAddr":"10.71.128.11","user":"dennis","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/","message":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\InvalidPath","Message":"Een lege bestandsnaam is niet toegestaan","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1178,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":[null]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":594,"function":"createCollection","class":"Sabre\\DAV\\Server","type":"->","args":["",{"__class__":"Sabre\\DAV\\MkCol"}]},{"function":"httpMkcol","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/ncdemo-06.thegood.cloud\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMkcol"],[{"absoluteUrl":"http:\/\/ncdemo-06.thegood.cloud\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MKCOL",[{"absoluteUrl":"http:\/\/ncdemo-06.thegood.cloud\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/ncdemo-06.thegood.cloud\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/remote.php","line":163,"args":["\/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":227,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.0techpreview (build 20190128) (Nextcloud)","version":"14.0.8.2"}_

**Comment by Dennis360ict** [comment]
Interesting:
- the .pdf and mp4 video in the root of the X:\ drive do open without any problems. 
- the files in the folders (X:\Photos and X:\Documents) don't work. 
- all the files show as 0 kb files, until they are downloaded. I think this is by design?
- i found a commit which could explain this?
https://github.com/nextcloud/desktop/commit/706cfe88d0b8e98347372c32db7d462f4a26ee58

**Comment by warnerbryce** [comment]
Hello @Dennis360ict i don't know how you finally get your Nextcloud Test Drive working, 
I would be interested how you made it. 

The client you've installed, was made in January 2019, then a commit was made on 4th of Feb. 
But nothing more. 
I think @camilasan left the ship and needed some holidays. 
@jospoortvliet told us some more work will be made for making a V2 of the Virtual Drive version of Nextcloud. On the road map you have : Release of V2 test version for May 2019 and final version for Septembre 2019.
I think they have a lot of problem to solve issues of this client or maybe not enought working force for that. 

You should Uninstall this version that is bundled with bugs and not usable at all, and wait for the V2 for making more testing.

**Comment by Dennis360ict** [comment]
Hi, 

I saw the same, not much activity and planned V2 or september. Also only 3 issues about this functionality. But as this is very important to our business customers, I decided to take my responsibility and do some testing. 

We have a scenario for which this functionality is key for us: In a lot of businesses they work allday together with a limited set of files. Like a financial of planning team. In their case they work with a set of files who need to be the single source of truth. Syncing here is counterproductive for them. For now they work online in the webgui or we sync to a networkdrive who sync's the files later to nextcloud with nextcloudcmd. But these are not optimal solutions, where the virtualdrive functionality would solve this. 

Let me know if I can help in any way. I'm not a programmer, but I can test!

**Comment by warnerbryce** [comment]
You should download the source code of the 12th of April : https://github.com/nextcloud/desktop/releases/tag/techpreview-v1
And compile it yourself ... follow instructions in this readme more down on the page : https://github.com/nextcloud/desktop/tree/techpreview-v1
Or you can ask a nice person on the help.nextcloud.com to compile it for you. 
I don't have the tools for making it myself for you sorry.

**Comment by Dennis360ict** [comment]
I thaught of that, but the last commit on that source was also 4 months ago..

Sent from my iPhone

On 11 Jun 2019, at 15:28, warnerbryce <notifications@github.com<mailto:notifications@github.com>> wrote:


You should download the source code of the 12th of April : https://github.com/nextcloud/desktop/releases/tag/techpreview-v1
And compile it yourself ... follow instructions in this readme more down on the page : https://github.com/nextcloud/desktop/tree/techpreview-v1
Or you can ask a nice person on the help.nextcloud.com<http://help.nextcloud.com> to compile it for you.
I don't have the tools for making it myself for you sorry.

**Comment by Dennis360ict** [comment]
So other problems #1559 prevent me from testing the found issues above. Will test as soon as i can login with the v2 client.

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
