### ISSUE TITLE
Known file extension in folder name breaks the Windows client syncing

### ISSUE THREAD

**Issue by Nuudel1** [nextcloud/desktop#1299]
### Expected behaviour
Sync without errors

### Actual behaviour
ERROR during  csync_update :  "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!"

### Steps to reproduce
1. Create folder with some known file extension. For example "temp.c", "temp.exe" or "temp.js". 
2. Reboot NC Windows client (should happen also when next sync)
3. Error message appears in client
4. Remove folder thru website or mobile client
5. Run "Force sync now" for Windows client and error disappears and sync completes.

### Client configuration
Buggy one:
Win clients: 2.5.1, 2.5.2 and 2.5.3.5522-daily-20190610
Working one:
Android: 3.6.2

Operating system:
Win7 Ultimate

OS language:
English

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: 16.0.1
Ubuntu 18.0.4 LTS
PHP: 7.2.19
Apache: 2.4.29

Storage backend (external storage):
Local storage

### Logs
1. Client logfile: 
[_csync_detect_update 	Database entry found for temp, compare: 1554632757 <-> 1554632757, etag: 5ca9d035ef502 <-> 5ca9d035ef502, inode: 0 <-> 185527, size: 0 <-> 0, perms: fd <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	Reading from database: temp
[_csync_detect_update 	file: temp, instruction: INSTRUCTION_NONE <<=
[fill_tree_from_db 	16 entries read below path temp from db.
[_csync_detect_update 	Checking for rename based on fileid 00030054oc34tuapcsof
[_csync_detect_update 	file: temp.exe, instruction: INSTRUCTION_NEW <<=
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://<servername.com>/remote.php/dav/files/User/temp.exe" has X-Request-ID "c7c63b59-2ff0-4b80-a310-05c9b7f4a2f1"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://<servername.com>" + "/temp.exe" "OCC::DiscoverySingleDirectoryJob"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::LsColJob::finished 	LSCOL of QUrl("https://<servername.com>/remote.php/dav/files/User/temp.exe") FINISHED WITH STATUS "OK"
[OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot 	LSCOL job error "Unknown error" 207 QNetworkReply::NetworkError(NoError)
[csync_ftw 	opendir failed for temp.exe - errno 10011
[OCC::SyncEngine::handleSyncError 	ERROR during  csync_update :  "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!"
[OCC::ActivityWidget::addError 	Item  "Nextcloud_User"  retrieved resulted in  "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!"

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):
No issues in server log.

**Comment by claell** [comment]
@Nuudel1 So you created the files remotely on the Nextcloud Server and they create an error in the Windows client?

Also, does this still happen with the current version of the client?

**Comment by Nuudel1** [comment]
@claell  I created a "temp.c" named folder in Nextcloud local folder with Windows Explorer and reboot NC windows client. It will start sync and report an error described in first message.

Tested it again and it seems to happen with version 2.6.4 stable-win64 (build 20200303) also. Deleting "temp.c" folder thru Windows Explorer is not resolving the error (NC win client stays at invalid stage). For resolving the issue one needs to go and delete created folder thru website / linux / mobile etc. So it seems that folder get's uploaded to server properly but when fetching some information back from the server NC win client is hitting to some error.

Please let me know if more details needed.

**Comment by claell** [comment]
@Nuudel1 Thanks for providing that details.

To me this issue sounds a bit uncommon, as this seems to be a pretty common use case, however it has not been reported before.

Maybe there is something special about your setup. What I could suggest would be to try removing everything related to the client from your PC and set it up again.

Also, as the error message shows some error seemingly related to the reply it gets from the server, it might be worth to try with a different server version (if possible); maybe you can setup a test instance at a free hoster.

Unfortunately at the moment that is all that I can suggest.

**Comment by Nuudel1** [comment]
@claell To highlight, issue is only with folders named like that. Maybe someone else could try this also (steps to re-produce in first msg), as it's fairly simple to test compared to build up test env for this. Althought, I can already confirm that behavior is the same with my other PC having same client version.

**Comment by claell** [comment]
@Nuudel1 yes, I noticed that right after writing my answer and edited it accordingly.

Probably you are right and this can be reproduced also with the latest nextcloud server version. Unfortunately I don't have a sync client setup and thus cannot quickly test this.

**Comment by theroch** [comment]
Expected behaviour

Sync without errors
Actual behaviour

ERROR during sync : "A HTTP transmission error happened. Server error: PROPFIND reply is not XML formatted!"
Steps to reproduce

    Create folder with a dot and an extension. For example "invoke.d", "index.xml" or "sample.c".
    Force sync
    Error message appears in client
    Remove folder thru website or mobile client
    Run "Force sync now" for Windows client and error disappears and sync completes.

Client configuration

Buggy one:
Win clients: 3.3.5 x64

Operating system:
Win 10 x64

OS language:
German

Installation path of client:
C:\Program Files\Nextcloud
Server configuration

Nextcloud version: 21.05
Ubuntu 20.0.4 LTS
PHP: 7.4
Apache: 2.4

Storage backend (external storage):
smb storage share

**Comment by basruel** [comment]
I would like to reopen this issue.

I am running Nextcloud Server 32.0.3 with the Nextcloud Desktop Client 4.0.4 on macOS, and I am still experiencing the same synchronization problem with directories containing source code.

The issue occurs when a directory name contains a dot (.). In my case, one of the module directories is named chart.js. When this directory is present, the Nextcloud desktop client fails to synchronize the folder correctly.

Renaming the directory to remove the dot (for example chart-js) allows the synchronization to proceed normally, which suggests that the client incorrectly handles directory names containing dots and interprets them as files or applies file-extension–related logic.

This behavior breaks synchronization workflows for development projects, where directory names such as *.js, *.php, or *.go are common.



SCOL job error "Erreur inconnue" 207 QNetworkReply::NoError
2025-12-27 17:15:59:083 [ warning nextcloud.sync.discovery /Volumes/builds/35935/macos-35935/src/libsync/discoveryphase.cpp:597 ]:	Server error: PROPFIND reply is not XML formatted!
2025-12-27 17:15:59:083 [ warning nextcloud.sync.discovery /Volumes/builds/35935/macos-35935/src/libsync/discovery.cpp:2317 ]:	Server error in directory "SINQ/developpement/FPQ/stable/fpqui/src/src/scss/vendors/chart.js" 207
2025-12-27 17:15:59:083 [ warning nextcloud.sync.discovery /Volumes/builds/35935/macos-35935/src/libsync/discovery.cpp:2331 ]:	Error: "Le serveur a renvoyé une réponse inattendue et illisible. Veuillez contacter l'administrateur de votre serveur."
2025-12-27 17:15:59:083 [ warning nextcloud.gui.activity /Volumes/builds/35935/macos-35935/src/gui/tray/usermodel.cpp:658 ]:	Item  "Nextcloud"  retrieved resulted in  "Le serveur a renvoyé une réponse inattendue et illisible. Veuillez contacter l'administrateur de votre serveur."
