### ISSUE TITLE
Feature request: Remote delete move to local recycle bin on sync

### ISSUE THREAD

**Issue by TRPB** [nextcloud/desktop#130]
At the moment, if I delete a file on one device, it's deleted on all of them. I realise nextcloud isn't really a backup tool but it would be nice to have an option to move deleted files to the recycle bin/trash.

Currently this happens:

1. File is synced across devices
2. File is deleted on one deveice
3. After sync file is deleted from all devices with no way to get it back

It would be nicer if:

1. File is synced across devices
2. File is deleted on one deveice
3. After sync, the file is moved to the recycle bin/trash folder. If it was deleted by mistake it's in the recycle bin on all my devices.

I'm on linux so I don't know whether this happens on other clients already

**Comment by michaelstingl** [comment]
@TomBZombie You could check the progress that is going on in the upstream project: https://github.com/owncloud/client/pull/6265 . Maybe you could offer your help testing…

**Comment by MichaIng** [comment]
I just though as well this would be nice. The feature is available on Linux client already, but not yet on Windows.

Any existing request or work on implementing this for Windows desktop client as well? Couldn't find one so far.
