### ISSUE TITLE
Unable to build Windows Client using Docker

### ISSUE THREAD

**Issue by supportreq** [nextcloud/desktop#1303]
I am trying to build the Windows Client using Docker build instructions. I am getting the following error:

➜ docker git:(master) docker build . -t nextcloud-client-win32:2.5.3
Sending build context to Docker daemon 4.608kB
Step 1/14 : FROM opensuse:42.1
manifest for opensuse:42.1 not found

Building this on a Mac..

Please advice.

**Comment by kjjam** [comment]
try` FROM opensuse/leap`
