### ISSUE TITLE
updating a public link creates a new one

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#1304]
Tested with the sync client v.2.5.1git and c.nc.com

Steps:

* create a public link (a default expire date will be set)
* change the expire date
* close the share dialog and open it again
* expire date is reset to the initial value (only one share is shown)
* go to the web interface and open the share details for the file
* two public links are shown, one with the initial expire date and one with the new expire date

I can repeat this multiple times. Everytime I update the public link on the desktop a new one will be created (only visible in the web interface)

**Comment by camilasan** [comment]
No reproducible anymore. I has been fixed. 2.6.4 or 2.6.5 (just tested from master)
