### ISSUE TITLE
v2.5.2 not showing notifications for new/changed files

### ISSUE THREAD

**Issue by FelixBuehler** [nextcloud/desktop#1305]
### Expected behaviour
Changing a file, meaning uploading over Web, shared folder, other computer etc. should result in the client showing me a notification"file.xyz was downloaded".

### Actual behaviour
I'm not getting these notifications on v2.5.2.
2.3.3.1 is working fine

### Steps to reproduce
1. Install v2.5.2
2. Sync everything
3. Upload a file from another instance, e.g. web GUI
4. Wait??
5. Nothing happens

### Client configuration
Client version:
2.5.2

Operating system:
Windows 8.1 Enterprise

OS language:
german

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version: 16.0.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: This is 60MB big and 3 Mio lines long. Anything particular interesting?
2. Web server error log:
No errors
3. Server logfile: nextcloud log (data/nextcloud.log):
No errors

**Comment by Kiaatix** [comment]
Same as #1197
Unfortunately not a bug but expected behaviour...

**Comment by FlexW** [comment]
@FelixBuehler Does the issue still exist in the latest version of the client? If not, please close the issue.
