### ISSUE TITLE
Linux client can not handle proxy authentication errors, DOS on proxy

### ISSUE THREAD

**Issue by abochmann** [nextcloud/desktop#1306]
When the Nextcloud Linux desktop client tries to access updates.nextcloud.org through an authenticating proxy, and the proxy credentials are invalid, it retries the failed connection immediately. We've seen over 400 CONNECT requests per second from a single client on the upstream proxy server.

### Expected behaviour
Client backs off from excessive retries when proxy requests to updates.nextcloud.org fail.

### Actual behaviour
Client retries connections as fast as the host system permits, with no time limit.

### Steps to reproduce
1. set up proxy server with proxy authentication enabled
2. install desktop client, configure proxy for internet access
3. provide invalid or no credentials
4. enable update check

### Client configuration
Unfortunately I have no information on the actual client version being used at this time, as I only was dealing with the problem on the proxy operations side. I'll try to get more detailed data tomorrow.

**Comment by abochmann** [comment]
Seems the client being used was provided by the distribution: 2.5.2-20190319.015224~disco1

The user had provided invalid proxy credentials in the client configuration.

**Comment by claell** [comment]
Adding #1577 as somewhat related issue where nextcloud immediately retries when a connection fails (different context though).
