### ISSUE TITLE
Cant connect with a IP URL (not a Domain Name)

### ISSUE THREAD

**Issue by Mirabeau2Code** [nextcloud/desktop#1307]
Hi !

It seem that i can't connect to my server installation with the Windows Desktop

I dont have a domain name for my remote server where NextCloud was installed.
i "think" that the error message (**_URL Invalide_**) is because **i use a IP** not a domain Name
The server part it ok.

I will take a look at the source code, and if possible try to make a correction if it is possible.

But have you ever had a problem?

### Client configuration
_Client version:_ 2.5.2
_Operating system:_ Windows 7 and Windows 10 (1809)  _Not yet tested on Linux_
OS language: French
Installation path of client: D:\\APP\Nextcloud

**Comment by FlexW** [comment]
Connecting with a ip address should work. Does the issue still exist for you?
