### ISSUE TITLE
All files are download again even if they exists

### ISSUE THREAD

**Issue by gabrielklein** [nextcloud/desktop#1308]
### Expected behaviour
Synchronize only the files that are not yet downloaded.

### Actual behaviour
Sometime all files (138 GB) are downloaded again even if the file is exactly the same.

If I close and restart the client, the temporary files (with something like ~da5c21 in the name) are deleted and all files are marked as "synchronized" as expected!

Please note that I have an IPv4 and IPv6 (that are fully working).

### Steps to reproduce
1. I go on a network where I only have an IPV4
2. I go back home where I have an IPV4 and IPV6. Please note that the server is running on http 2.0!
3. I wait some hours and I start to see activities on the client. The client is not "green" anymore.
4. If I look on the apache2 logs, I see that all files are downloaded again.

2a02:xxxx:xxxx:b890:xxxx:xxxx:b98b:6ff6 - - [19/Jun/2019:21:31:55 +0200] "PROPFIND /remote.php/dav/files/gabriel/Conseil%20General/2018 HTTP/2.0" 207 6133 "-" "Mozilla/5.0 (Linux) mirall/2.5.2git (Nextcloud)"

### Client configuration
Client version: 2.5.2git

Operating system: Ubuntu 19.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): both

Installation path of client: default one of the distro

### Server configuration

Nextcloud version:16.0.1 (All check passed). http 2.0!! 

Storage backend (external storage): no

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
I have restarted the client, so no relevant logs anymore

2. Web server error log:
Some "access denied" problems. But normally everything is working perfectly

[Wed Jun 19 21:04:27.462583 2019] [authz_core:error] [pid 15360:tid 140599221131008] [client 2a02:....:8440:991c:1ac6:c348:53948] AH01630: client denied by server configuration: /home/nextcloud/nextcloud/config
[Wed Jun 19 21:09:47.485515 2019] [authz_core:error] [pid 15359:tid 140599187560192] [client 2a02:....:8440:991c:1ac6:c348:53948] AH01630: client denied by server configuration: /home/nextcloud/nextcloud/config
[Wed Jun 19 21:12:27.517210 2019] [authz_core:error] [pid 15360:tid 140599212738304] [client 2a02:....:8440:991c:1ac6:c348:53948] AH01630: client denied by server configuration: /home/nextcloud/nextcloud/config

3. Server logfile: nextcloud log (data/nextcloud.log):
Nothing relevant

**Comment by vincentqb** [comment]
Also, the files that are already there are overwritten. Folders are also overwritten instead of merged.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?
