### ISSUE TITLE
Public link creation from Windows main menu

### ISSUE THREAD

**Issue by biva** [nextcloud/desktop#1312]
I love the Public Link feature: it avoids to share large files per email, with a lot of advantages:
- saves bandwidth on poor internet connections
- avoids loading the mailbox with unnecessary GB
- avoids storing the file on 6 different potential locations (original file on my disc, my local mailbox, my server mailbox, recipient's server mailbox, recipient's local mailbox, recipient's folder)
- have always the most recent version with the same link (when working on a file with several partners, my correspondent can download the most recent version at any time, without asking me to send it again)

But the ways to create the link and copy it are not yet optimized in my experience, with a lot of steps (on Windows):
1. Go to the folder
2. Click right
3. Find Nextcloud in the context menu
4. Click share
5. Tick the box
6. Click Copy
7. Close the share windows

Easier ways are discussed in different issues:
1. Public link creation and copy directly from the Right-click context menu: for the moment, I don't see this feature on my version (2.5.2) and there are ongoing issues: https://github.com/nextcloud/desktop/issues/858 and https://github.com/nextcloud/desktop/issues/1061
2. Automatically provide a link within Thunderbird with Filelink: https://github.com/nextcloud/nextcloud-filelink/issues/52
3. Share by mail (public link) proposed by @silvershadowcc : https://github.com/nextcloud/desktop/issues/1180

I would like to suggest another feature in Windows. When you press the *Windows* key, you can type the name of a file, it is directly proposed in the Windows menu, and on the right, you have a kind of *Context Window* that shows the file location, and offer the option to copy the full path of the file:
![image](https://user-images.githubusercontent.com/9964305/60038817-e1cd1080-967a-11e9-9ae5-6aa2adc0d11b.png)

It would be super useful and handy to have another option there, like *Create public link and Copy it* (or only *Copy public link* if it already exists)

**Comment by biva** [comment]
I see the public link creation from the right-click menu now (with 2.5.3). Do you think this solution on Windows main menu would be doable?

**Comment by biva** [comment]
Does anybody consider that this feature could be interesting?

**Comment by biva** [comment]
@er-vin why did you close this issue?

**Comment by er-vin** [comment]
Because it's stale, there are means to get to the feature and the otherwise integration in the windows search pane isn't going to happen.
