### ISSUE TITLE
Not possible to see all accounts in the client without resizing the window beyond the screen size

### ISSUE THREAD

**Issue by rolandixor** [nextcloud/desktop#1316]
### Expected behaviour
Since the window isn't really expected to be resized, the tabs should be vertical, similar to KDE and Gnome system settings, as opposed to horizontal, and allow for scrolling.

### Actual behaviour
Instead, you have to resize the client window in order to see all of the accounts.

### Steps to reproduce
1. Use the client with more than 5 accounts at the same time.

### Client configuration
Client version: 2.5.2 git

**Comment by rolandixor** [comment]
This is not quite the same bug as https://github.com/nextcloud/desktop/issues/91.

**Comment by FlexW** [comment]
@jancborchardt do we want to improve that?

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
