### ISSUE TITLE
Error when try to rename file in e2ee directory

### ISSUE THREAD

**Issue by vsychov** [nextcloud/desktop#1317]
### Expected behaviour
Files in e2ee directory, renamed.

### Actual behaviour
Error when try rename file in e2ee directory

### Steps to reproduce
1. Create directory
2. Encrypt it
3. Create file
4. Wait until this will synced
5. Try to rename

### Client configuration
Client version: `2.5.2git (build 20190319)  Qt 5.9.2  SSL  OpenSSL 1.0.2q  20 Nov 2018`
Operating system: `Mac OS X`

### Server configuration
Nextcloud version: 16.0.1

### Logs
Web server error log:
```
127.0.0.1 - admin [26/Jun/2019:15:58:53 +0000] "PROPFIND /remote.php/dav/files/admin/ HTTP/1.1" 207 1409 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)" "-"
127.0.0.1 - admin [26/Jun/2019:15:58:54 +0000] "MOVE /remote.php/dav/files/admin/Photos/IMG_20190626_161812.jpg HTTP/1.1" 404 259 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.2git (build 20190319) (Nextcloud)" "-"
80
```

**Comment by mgallien** [comment]
Can you still reproduce this issue with the latest release ?
