### ISSUE TITLE
Confusing choices when new too-large directory isn't synced

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#1319]
### Expected behaviour

When a directory that is too large to sync appears on nextcloud server, a clear message should be presented to the user on what the possible options are.

The sync client would present a meaningful view of the new unsynced directory or directories and provide a way to activate syncing via a checkbox right next to the message. "Sync all" or "Sync none" shouldn't be presented as options.

### Actual behaviour

The options presented are confusing.

![Screenshot-20190629080319-684x128](https://user-images.githubusercontent.com/571494/60381738-de120300-9a59-11e9-8833-5a1453ddc908.png)

- "Synchronize all": is this affecting any other unsynced directories? Clicking this button in the context of "too large directory encountered" seems dangerous.
- "Synchronize none": disable syncing overall??
- "Apply manual changes": Nothing was manually changed, just a huge directory appeared on the server???

### Client configuration
Client version:  2.5.2git

Operating system: Ubuntu 18.04

OS language: en-us

### Server configuration

Nextcloud version: 16.0.1

Storage backend (external storage): primary storage is object storage via minio

**Comment by rioncarter** [comment]
Just want to chime in here and "+1" this issue. After installing the NextCloud desktop client on a new system I ran into this. Don't want to lose data so I haven't pressed any of the buttons yet.

**Comment by despens** [comment]
Coming back here to say that the new mini-sized "main dialog" doesn't help much with this problem. Any messages or notifications that are longer than 5 words are clipped and there is no way to display the full line or react adequately. Clicking on any file-related message just opens the browser at the root of my nextcloud instance, which doesn't make much sense.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
