### ISSUE TITLE
Sync fails completly if a federated share is not working

### ISSUE THREAD

**Issue by kolaente** [nextcloud/desktop#1320]
### Expected behaviour

Syncing should work without problems, ignoring federated shares which don't work.

### Actual behaviour

A cryptic error without any information tells me "An HTTP transmission error occured. Data is missing." (Original localized was "Es hat sich ein HTTP-Übertragungsfehler ereignet. Bei der Server-Dateierkennungsantwort fehlen Daten.")

The local logs tell me this:
```
[OCC::DiscoverySingleDirectoryJob::directoryListingIteratedSlot 	Missing properties: "vm.ova" 0 0 0 "WDNVRS" "" "00144792ocadc83b19e7"
[csync_ftw 	opendir failed for  - errno 10011
```
Where the file `vm.ova` is a file which was shared to me via federation from an _own_ cloud.
When I look in the web interface, that file has a size of 0B, when I try to delete the file from the webinterface, I get the same cryptic error. However, in the server logs is now an entry which indicates there was an 500 server error on the other side. I'll try to get some server logs from them and update here.

### Client configuration
Client version: 2.5.2git, rev 56c905

Operating system: Antergos (Arch)

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.12.4

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: `/usr/bin/nextcloud`

### Server configuration

Nextcloud version: 15.0.5 via docker

Storage backend (external storage): local

### Logs

https://gist.github.com/kolaente/53714f2c40de73a63d4dd84783abd06d

**Comment by FlexW** [comment]
Does the issue still exist with a recent server and client version (3.2.1)?

**Comment by kolaente** [comment]
I don't think it is. That's gotta be one of these issues where I don't even remember I opened them :sweat_smile: 
I think I don't even have that share anymore.
