### ISSUE TITLE
Custom Nextcloud protocol on Desktop

### ISSUE THREAD

**Issue by signalkraft** [nextcloud/desktop#1321]
First off: I would like to contribute this, if interest is there. That's why I put this request in Github, even though it does not fit the bug template. I hope that's the right place for it?

My feature suggestion is to register a custom protocol such as `nc://` in the desktop client, similar to the intents that are already being used in the Android app AFAIK. Another example are [magnet URIs](https://en.wikipedia.org/wiki/Magnet_URI_scheme).

A custom Nextcloud app would then generate these custom URIs and hand them over to the desktop client on click in the browser (or an email) through OS-specific URI-handlers. On first glance, this would require these handlers for the desktop client:

* https://msdn.microsoft.com/en-us/windows/desktop/aa767914
* http://edoceo.com/howto/xfce-custom-uri-handler
* https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102207-TPXREF115

Admins should be able to configure the behavior of link sharing:
* Default behavior but an additional option / button for custom URIs
* Only custom URIs
* Hybrid of both

Hybrid would generate links similar to OneNote's when copying pages from the desktop client: `onenote:https://...sharepoint.com/.... Web View: https://...`.

Another configuration option could control whether the file should be opened over WebDAV or in the local file system (which would need to handle unsycned files / folders).

The resulting UX should especially improve life of employees in companies or other teams that share links via email or Slack. In my experience the current workflow is close to this:

* I finish working on a file in Excel / Photoshop and would like to share it with somebody
* I copy the private URL in the sync client and paste it into an Email
* The recipient opens the URL and sees the file in the Nextcloud web app
* He/she navigates to his own local copy in the file system based on the breadcrumbs he sees in the web app

Along the way authors might misunderstand public / private URLs, might not find the share button in the web / desktop UI and just copy their local path or the browser URL. Recipients might download the file from the UI and work on a local copy that isn't going to be synchronized, or they might not find the local file because it is not synced yet.

The new workflow would be:

* I copy the private URL in the sync client and paste it into an Email
* My clipboard contains a web link, or custom URI, or both (depending on admin's settings)
* The recipient can click on the custom URI, which gets handed over to the desktop client, which opens the file in the default app, or opens the folder in the file browser

This avoids confusion about the location of the file, it encourages users to work on sycned copies, and it isn't OS-specific - such as WebDAV links I can send to my Linux-using colleagues, but not Windows users.

Another nice-to-have feature would be fallback to the browser app through custom protocol handlers: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

That would mean that the custom URI has to start with `web+...`.

Please point out if this idea suits the scope of the desktop client, or if I should contribute this as a standalone app / addon, of if there are existing discussions about this that I couldn't find.

**Comment by jospoortvliet** [comment]
Very interesting idea! @jancborchardt @nextcloud/designers  probably have thoughts about it ;-)

Thanks for offering to implement it. Would you be able to do that cross-platform, you think?

**Comment by jancborchardt** [comment]
This would be the call of @rullzer @MorrisJobke I assume?

Design-wise my first thought is that it should be called `nextcloud://…` instead of cryptic `nc://…` ;)

**Comment by mgallien** [comment]
@signalkraft are you still interested to work on that ?
That could be really interesting to get.

**Comment by signalkraft** [comment]
@mgallien interested yes, but in my work we've since switched off of Nextcloud. One of the reasons was that editing files locally from links was much more complicated than in Sharepoint. So I'm not likely to find the time soon.

**Comment by mkrecek234** [comment]
Would be MUCH appreciated. Exactly what is required for proper collaboration on all possible file types and editing applications👍🏼

**Comment by mgallien** [comment]
@tobiasKaminsky interesting future feature

**Comment by bbceg** [comment]
> A bit easier approach, and therefore faster to implement might be: Having an "open locally" button on public links, which then uses nextcloud://server/fileId to pass it to Desktop.
> 
> Downside is that user has to go via web.

Seems like a good MVP to me. Can always improve on it later when time permits...

**Comment by claucambra** [comment]
We now have edit locally :)

**Comment by bbceg** [comment]
@claucambra Thanks for the heads up.

One issue I'm seeing: If I share an internal link it opens the browser and downloads the file before I get a chance to select "Edit locally". Is there any way to either prevent the download or force the link to open via the client without going via the browser?
