### ISSUE TITLE
desktop client stuck on creating sync with server v16

### ISSUE THREAD

**Issue by zmi1** [nextcloud/desktop#1325]
We seem to have a problem in the mysql database I guess, but the problem occurs with the desktop client (windows & mac), so I report it here. We have a server with mysql db, and upgraded to v16 over time. After seeing the problems we have, I completely reinstalled nextcloud v16 on the server, only importet the old mysql db, so I believe the problem is there.
So what I do is, create a new sync on a desktop client, enter server, user, pwd, and after it says "Kontozugriff" (account access) with "Zugriff gewähren" (grant access), I press the button but its stuck forever. It doesnt matter if its an old user or a newly created. See the error message from the log below.

### Steps to reproduce
1. I guess if you want to reproduce you need a DB dump from me, which has sensitive data, so I would only send it to a developer
2. Import the DB in a new  v16 installation
3. try to use desktop sync with any user

### Client configuration
Client version: Version 2.5.1final (build 20181204)
Operating system: mac (but also reported from windows and mobile desktop)
OS language: german

### Server configuration
Nextcloud version: 16.0.1

Storage backend (external storage): localdisk

### Logs
1. Client logfile: 
[OCC::PropfindJob::finished     PROPFIND of QUrl("https://cloud.xxx.at/remote.php/webdav/") FINISHED WITH STATUS "RemoteHostClosedError Verbindung beendet"
[OCC::PropfindJob::finished     *not* successful, http result code is 0 ""

2. Web server error log: nothing to see

3. Server logfile: nextcloud log (data/nextcloud.log):
too big, nothing interesting found

**Comment by IronicBadger** [comment]
Can confirm. Using mysql and v16, seeing similar behaviour.

**Comment by iautom8things** [comment]
So I'm coming from Owncloud.  I initially tried upgrading, had enough issues that I said f*$@ it, let's just start fresh.  Can't get the desktop client to authenticate.  This is with a fresh db/docker set up with the `latest` image.  I'll give postgres a try.

**Comment by iautom8things** [comment]
Yup, switching to postgres didn't help.
![nextcloud_login_issue](https://user-images.githubusercontent.com/522040/61163786-07a94080-a4d6-11e9-9e9f-1c687e064203.gif)

**Comment by pelzvieh** [comment]
Is it possible that the problem was introduced to the client between version 2.5.0daily (build 20181112) and 2.5.2? I'm trying to connect two MacOS clients to one server, admittedly using two accounts in nextcloud. On the client running 2.5.0daily, no problem. The client running 2.5.2 just shows a static ca. 33% progress bar after hitting "grant access".
I'm using LDAP backend and SAML SSO so I assumed some hidden problems with one of the accounts. But I took tcpdump of the communication, and the last response of the server looks like success to me, but the client doesn't seem to handle it:
```
HTTP/1.1 303 See Other
Date: Tue, 23 Jul 2019 13:41:32 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache, no-store, must-revalidate
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self'
Location: nc://login/server:https://example.org/nextcloud&user:therightone&password:1enthyB14s0fCharactersAndNumber5
Content-Length: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Keep-Alive: timeout=5, max=90
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```

That redirect to a magical protocol "nc" is not handled by the newer client.

**Comment by mgallien** [comment]
Can you test with the latest release and check that you can reproduce this issue ?
