### ISSUE TITLE
[Win10] User config disappear at startup

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/desktop#1326]
### Steps to reproduce
1. On a Windows 10 (1809), log in with local admin account
2. Install Nextcloud
3. Log out then log in with local user account
4. Configure Nextcloud-client
5. Wait for sync
6. Restart computer
7. Nextcloud is not configured anymore

### Expected behaviour
I expect that user configuration is persistent

### Actual behaviour
Users have to configure the software after each restart of the machine

### Client configuration
Client version: 2.5.2 (same problem with 2.3 version)

Operating system: Windows 10 (1809)

OS language: French

Installation path of client: C:\Users\MyUser\Nextcloud

### Logs

I don't have yet but I asked for them

**Comment by mgallien** [comment]
Can you still reproduce this issue with the latest release ?
