### ISSUE TITLE
Segmentation fault after Login to Nextcloud server of University

### ISSUE THREAD

**Issue by CakeUser321** [nextcloud/desktop#1330]
### Expected behaviour
When logging in to the server of the university I am attending, the nextcloud application should start to synchronize my nextcloud folder.  

### Actual behaviour
In ~85% of all attempts the application crashes with a segmentation fault. 

### Steps to reproduce
1. Start application via bash (me@myMachine:~/Downloads$ ./Nextcloud-2.5.2-x86_64.AppImage)
2. Log in to TU Dresden server https://cloudstore.zih.tu-dresden.de/index.php/login
3. enjoy the segmentation fault

```
Received signal 11 SEGV_MAPERR 000000000021
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

### Client configuration
Client version: 2.5.2, 64-bit, build20190319

Operating system: Linux myMachine 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 5.11.0

Client package (From Nextcloud or distro) (Linux only): nextcloud app image

Installation path of client: /home/me/Downloads

### Server configuration

Nextcloud version: /

Storage backend (external storage): /

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

https://gist.github.com/CakeUser321/0e997efd4769406fd75cec9917bf4514

2. Web server error log: / 

3. Server logfile: nextcloud log (data/nextcloud.log): /

**Comment by dtto** [comment]
I can confirm this bug on my machine, which is running Debian Buster, client v. 2.5.2. The two NC instances are both updated to 16.0.3. I actually cannot get the client to start at all, it just keeps segfaulting.

**Comment by DominiqueFuchs** [comment]
Please continue segfault appearences and post further information in #241 , thanks!
