### ISSUE TITLE
Unexpected 200 return code - client freaks out

### ISSUE THREAD

**Issue by mistergibson** [nextcloud/desktop#1334]
I am attempting to sync a 1.1GB file to my NC16 dir. It uploads all the way, but AT THE END it freaks out because it is getting a 200 return code it does not expect.

### Expected behaviour
Sync 1.1GB file and be happy

### Actual behaviour
"Unexpected return code from the server (200). Skipping ..."

### Steps to reproduce
1.  Launch nextcloud client
2.  Either wait for next sync, OR force sync now --> same result consistently.
3.

### Client configuration
Client version:
Version 2.5.2git (2.5.2-20190319.015224~bionic1)

Operating system:
Linux : Linux Mint 19.1

OS language:
English-US

Qt version used by client package (Linux only, see also Settings dialog):
QT5

Client package (From Nextcloud or distro) (Linux only):
distro (2.5.2-20190319.015224~bionic1)

Installation path of client:
/usr/bin/nextcloud

### Server configuration
(skipped -- all other smaller files sync normally)

Nextcloud version:
16.0.1

Storage backend (external storage):
(N/A)
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`

[OCC::Application::setupLogging 	"################## Nextcloud locale:[en_US] ui_lang:[en_US] version:[2.5.2git] os:[Linux Mint 19.1
]"
[OCC::Application::slotParseMessage 	Running for 157051 sec
[OCC::Folder::slotRunEtagJob 	Trying to check "https://cdc.csproject.org/cloud/remote.php/dav/files/mistergibson/" for changes via ETag c
heck. (time since last sync: 984 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://cdc.csproject.org/cloud/remote.php/dav/files/mistergibson/" has X-Request-ID 
"58b08611-8324-4d9d-a886-02ecf8c360fc"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://cdc.csproject.org/cloud" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://cdc.csproject.org/cloud/remote.php/dav/files/mistergibson/") FINISHED WITH ST
ATUS "OK"

2. Web server error log:
No errors reported.
I do get complaints as the file transfer is on-going that the request headers do not specify the Content-Type properly. But it is a notice only.

3. Server logfile: nextcloud log (data/nextcloud.log):
No log entries about the transfer at all.

Note: It is my understanding that code 200 is the web server saying 'OK' and 'all is well'. Perhaps you need to code the client to take 'Yes' for an answer. Just Say'n.

**Comment by mistergibson** [comment]
Update: I was running mod_security2 on my apache2 install. It evidently sends a 200 code at the end of the transfer. Although disabling it fixed the basic freaking out -- your client really *should* be able to accept a 200 code an move on with life w/o freaking out. Also, you really *should* specify the Content-Type in your segment envelope headers. You might consider this for future releases? I'll leave this open for your response. thanks in advance.

**Comment by qdanmerchant** [comment]
I have this problem too since using the mod_security2 mod on apache2. The problem is not just with large files, I have the problem with small files too being uploaded with the desktop client. The files transfer fine getting to 100% and the the error message "Unexpected return code from server (200)".

**Comment by er-vin** [comment]
Could we have a debug log snippet of that one with a 3.0.1 client please? This changed a bit and could help pinpointing it.
