### ISSUE TITLE
win10 Client failed to detect "move file" when moving few hundreds photos

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#1335]
### Expected behaviour
When rename a parent folder of about 400 photos in 5 child foldrers
Client should be aware of photos are moved and update

### Actual behaviour
Client did nothing only if I update the metadata of all files using lightroom then it starts to delete and re-upload.
Changing parent folder in win10 will cause a mixed of move and delete&upload behavior
PS: The folder name contains Chinese
### Steps to reproduce
1. Rename a parent folder with many child folder and files

### Client configuration
Client version:

Operating system: Win10

OS language: Chinese

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version:
2.5.2git
Storage backend (external storage): 
Local storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
No new entry happens

2. Web server error log: 
  No error

3. Server logfile: nextcloud log (data/nextcloud.log):
 No error

**Comment by freechelmi** [comment]
You mix 2 issues here ? 

- Update metada ( which means modify file )  -> Should be a "modify" on server.

- Rename folder -> Results in delete/Reupload on your server of every file ?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
