### ISSUE TITLE
Switching Activity back to "added","deleted" etc rather than synced

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#1336]
### Expected behaviour
The activity should says "uploaded" "deleted" etc

### Actual behaviour
Everything now becomes "synced"

### Client configuration
Client version: 2.5.3rc2

Operating system: win10

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by smatthie** [comment]
I support this request. It is really annoying that there is no easy way to see if a file was actually uploaded or downloaded and this is often useful or important to know so that I can check if nextcloud does the right thing.

**Comment by Milokita** [comment]
> 
> 
> I support this request. It is really annoying that there is no easy way to see if a file was actually uploaded or downloaded and this is often useful or important to know so that I can check if nextcloud does the right thing.

Now in NC 2.6.4, the activity says "added" " deleted" rather than "synced", you can give it a try
