### ISSUE TITLE
Folder Rights

### ISSUE THREAD

**Issue by dchemaly** [nextcloud/desktop#1338]
### Expected behaviour
Client doesnt verify rights per folder as the web based client 
### Actual behaviour
Tell us what happens instead
for example if I have 2 folders
Folder 1 
            -> Folder 2

It only uses rights from Folder 1 and not Folder 2. So if I said a user can delete in Folder 1 but not Folder 2 it ignores the rights of Folder 2 and applies rules from Folder 1

### Steps to reproduce
1. Assign delete rights on main folder
2. Change user rights on sub folder not to delete
3. Desktop client still allows deletion in sub folder

### Client configuration
Client version:

Version 2.5.2git

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
Is this still an issue with the newest client version (3.2.1)?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
