### ISSUE TITLE
macOS Client deletes folders of unchecked sync items

### ISSUE THREAD

**Issue by maxstiller** [nextcloud/desktop#134]
Hello everyone,
i got the following issue: When working in a synchronized folder on macOS, .DS_Store files are created. If you uncheck those folders in the Nextcloud Client settings, every file on the Mac gets removed but the .DS_Store files which leaves the synchronized folders in a "not synchronized" state. If the user finally deletes the folder in which the .DS_Store files are located, the complete folder gets deleted on the server, too, although it has already been unchecked in the settings. Nextcloud Client Version 2.3.3.

**Comment by lbayerlein** [comment]
+1

**Comment by DominiqueFuchs** [comment]
I think I can explain this:

If you uncheck a folder, it will principally be removed from the local tree (as of client >= 2.5 this has to be confirmed by the user, confirmation dialog appears). However, there is a check in the sync-engine that prevent deletion of folder with ignored files in it. This is to prevent confusion and possible data loss in case specific files were set to _not sync_ and the synced folder _without_ these files gets deleted on the remote. If the folder would be removed from the local tree as a consequence of the remote deletion, the ignored (not synced) files in the local folder would be lost, too.

Now to your specific case: .DS_Store files are in the default exclusion list of the client (as can be checked by opening the exclusion list from the settings tab). My guess is that this security-check in the code-behind conflicts with your scenario where the folder with the ignored files gets kind of stuck.

As soon as I find the time, I'll take a look into this and see if there's a more elegant solution to this.
