### ISSUE TITLE
AppImage client does not include all translation files (I need zh-CN)

### ISSUE THREAD

**Issue by suokunlong** [nextcloud/desktop#1340]
### Expected behaviour
The official AppImage package should include all translation files. For me, my system language is Simplified Chinese (zh-CN), but it is not included in the package.

### Actual behaviour
No zh_CN translation in AppImage.

**Comment by suokunlong** [comment]
I decompressed the appimage, and find:

$ ls ./usr/translations/
qt_ar.qm  qt_da.qm  qt_fi.qm  qt_hu.qm  qt_lv.qm  qt_uk.qm
qt_bg.qm  qt_de.qm  qt_fr.qm  qt_it.qm  qt_pl.qm  qtwebengine_locales
qt_ca.qm  qt_en.qm  qt_gd.qm  qt_ja.qm  qt_ru.qm  qt_zh_TW.qm
qt_cs.qm  qt_es.qm  qt_he.qm  qt_ko.qm  qt_sk.qm

zh_CN is on https://github.com/nextcloud/desktop/tree/master/translations, but not included in the appimage.

**Comment by FlexW** [comment]
Does the issue still apply? If yes, please reopen it again.
