### ISSUE TITLE
client  nothing else than the background

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#1341]
Nextcloud client window shows nothing else than the background. See screenshot

![nextcloud](https://user-images.githubusercontent.com/5477747/61206046-e624a080-a6f1-11e9-8744-b6937e782590.jpg)

### Client configuration
Client version: 2.5.2

Operating system: Fedora 30

Qt version used by client package: 5.12.4

Client package: Fedora, and I am the maintainer

**Comment by tbschommer** [comment]
Same effect with client version 2.6.0-fix1 on KDE Frameworks 5.63.0, Qt version 5.12.4.

Only after resizing does the window show proper output.

**Comment by texstar** [comment]
Same effect with client version 2.6.0-fix1 on KDE Frameworks 5.63.0, Qt version 5.12.4.

**Comment by FlexW** [comment]
Do you still have this issue with the latest version (3.2.1)? If no, please close the issue.
