### ISSUE TITLE
Continuous crash of NextCloud sync on Windows

### ISSUE THREAD

**Issue by hjohanns** [nextcloud/desktop#1350]
Hello,
I am trying to address a user problem where in the NC client log, the message below continuously appears:
00:00:325 16800 OCC::SyncJournalDb::commitTransaction: ERROR committing to the database:  "cannot commit - no transaction is active"
00:00:326 16800 OCC::SyncJournalDb::startTransaction: Database Transaction is running, not starting another one!

So it seems it cannot commit anything because a Transaction is running.
Is it possible to stop the client and reset the Transaction state, in case there would be a "ghost" transaction left by previous crash?

Thanks a lot
hubert j.

### Expected behaviour
I would expect a clean Sync to finish once

### Actual behaviour
NextCloud sync never finishes because client crashes before.

### Steps to reproduce
1. Install client
2. Connect to server
3. Launch sync

### Client configuration
Client version: 2.5

Operating system: Windows

OS language: French

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
00:00:325 16800 OCC::SyncJournalDb::commitTransaction: ERROR committing to the database:  "cannot commit - no transaction is active"
00:00:326 16800 OCC::SyncJournalDb::startTransaction: Database Transaction is running, not starting another one!

No log on this on server.

**Comment by lemmy04** [comment]
I had the same issue, now with version 2.5.3 of the client it seems to be better, but I can't say for sure yet

**Comment by lemmy04** [comment]
ok even 2.5.3 still crashes quietly - i actually have to check my notification area and move the mouse over the icon to see it disappear.

**Comment by djamps** [comment]
2.5.x crashes regularly for us, so it's a no-go.   Can't expect clients to check if the client has silently quit every day.   We're stuck on 2.3.3 for the forseeable future.

**Comment by mgallien** [comment]
Can you still reproduce this issue with the latest version ?

**Comment by lemmy04** [comment]
I haven't seen this happen for quite some time now.
