### ISSUE TITLE
Files in new created folder do not get synced! (client->server)

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/desktop#1351]
### Expected behaviour
Files should be uploaded to server

### Actual behaviour
files in new created folder did not get uploaded

### Steps to reproduce
1. On client filesystem create a new folder and rename it to something useful (demo1 in my case)
2. Drag and drop some files or documents to that created folder
3. The files are not recognized bi the sync client!

### Client configuration
Client version: Version 2.5.2git. (Linux Mint)

Operating system: Linux Mint 19.1 Tessa 64bit

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): table dev-ppa

Installation path of client: 

### Server configuration

Nextcloud version: 16.0.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

Screenshot:
![Auswahl_20190723_12:27:51](https://user-images.githubusercontent.com/2804301/61705130-83608400-ad45-11e9-9c11-d24d73cb7873.jpg)

Hint:
After terminating the client and restarting is the file gets synced!

**Comment by judos** [comment]
Seems like I got the same issue.
OS: Win10
Client: Version 2.5.2git (build 20190319)

The weird thing with me is when I click on the menu in nextcloud client and select "force synchronisation" for this shared folder, the changes still don't get recognized. As soon as I restart nextcloud client however it perfectly works.
Seems like a caching problem for me. Nextcloud probably periodically checks for changes in the folders. When you copy in a folder with files, nextcloud immediately sees the folder and caches it that this is an empty folder and after the files are also copied in, nextcloud doesn't update due to caching the information earlier. Something like this...

**Comment by isdneuroimaging** [comment]
I see a similar behaviour! After putting a folder to the Nextcloud folder, first, only folders are synchronized (all subfolders!). But files are only uploaded after restarting the desktop client.

**Comment by Germano0** [comment]
Please test 2.6.0 RC1, the problem you are experiencing could be the same https://github.com/nextcloud/desktop/issues/1000 that has already been fixed

**Comment by judos** [comment]
Hey @Germano0, thx for the hint. Seems fixed to me.

**Comment by adrb** [comment]
For me update to 2.6.0stable build 20190927 with NC14 didn't change anything on Debian10. What's interesting the same version on Win10, seems fine. It seems to me that on Linux it detects change inside of wrong directory name, please see relevant logs. Here you have rename for directory "nextcloud_client_bug_1351" to "nextcloud_client_bug_1351_rename" and then new file "new_file.txt" is being created:

`[OCC::AbstractNetworkJob::start 	OCC::MoveJob created for "https://drive" + "/nextcloud_client_bug_1351" "OCC::PropagateRemoteMove"
[OCC::MoveJob::finished 	MOVE of QUrl("https://drive/remote.php/dav/files/60bc8ca5-a4cc-41d0-bb5e-f23fb25d3eaf/nextcloud_client_bug_1351") FINISHED WITH STATUS "OK"
[OCC::SyncJournalDb::setFileRecord 	Updating file record for path: "nextcloud_client_bug_1351_rename" inode: 12976162 modtime: 1570791272 type: 2 etag: "5da05e686ac9f" fileId: "00084602ocpxaribd9zi" remotePerm: "DNVCKR" fileSize: 0 checksum: "" e2eMangledName: ""
[OCC::PropagateItemJob::done 	Completed propagation of "nextcloud_client_bug_1351_rename" by OCC::PropagateRemoteMove(0x55e6bf7ca160) with status 4
[OCC::ActivityWidget::slotItemCompleted 	Item  "nextcloud_client_bug_1351"  retrieved resulted in  ""
[OCC::ActivityWidget::slotItemCompleted 	Item  "nextcloud_client_bug_1351"  retrieved successfully.
[OCC::SyncJournalDb::setFileRecord 	Updating file record for path: "nextcloud_client_bug_1351_rename" inode: 12976162 modtime: 1570791272 type: 2 etag: "5da05e686ac9f" fileId: "00084602ocpxaribd9zi" remotePerm: "DNVCKR" fileSize: 0 checksum: "" e2eMangledName: ""
[_csync_detect_update 	Database entry found for nextcloud_client_bug_1351_rename, compare: 1570791016 <-> 1570791272, etag: 5da05e686ac9f <-> 5da05e686ac9f, inode: 0 <-> 12976162, size: 0 <-> 0, perms: fd <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	Reading from database: nextcloud_client_bug_1351_rename
[_csync_detect_update 	file: nextcloud_client_bug_1351_rename, instruction: INSTRUCTION_NONE <<=
[fill_tree_from_db 	0 entries read below path nextcloud_client_bug_1351_rename from db.
[OCC::FolderWatcher::changeDetected 	Detected changes in paths: QSet("/mnt/data/drive/nextcloud_client_bug_1351/new_file.txt")
[_csync_detect_update 	Database entry found for nextcloud_client_bug_1351_rename, compare: 1570791449 <-> 1570791272, etag:  <-> 5da05e686ac9f, inode: 12976162 <-> 12976162, size: 4096 <-> 0, perms: 0 <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	file: nextcloud_client_bug_1351_rename, instruction: INSTRUCTION_EVAL <<=
[fill_tree_from_db 	0 entries read below path nextcloud_client_bug_1351_rename from db.
[_csync_detect_update 	Database entry found for nextcloud_client_bug_1351_rename, compare: 1570791016 <-> 1570791272, etag: 5da05e686ac9f <-> 5da05e686ac9f, inode: 0 <-> 12976162, size: 0 <-> 0, perms: fd <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	Reading from database: nextcloud_client_bug_1351_rename
[_csync_detect_update 	file: nextcloud_client_bug_1351_rename, instruction: INSTRUCTION_NONE <<=
[fill_tree_from_db 	0 entries read below path nextcloud_client_bug_1351_rename from db.`

**Comment by adrb** [comment]
I prepare [patch](https://github.com/nextcloud/desktop/pull/1522) addressing that problem

**Comment by Golffies** [comment]
I opened a bug report under #1681. My report is a duplicate od this older one.

**Comment by allexzander** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/2853 and will be released in 3.2
