### ISSUE TITLE
Latest release: windows download is missing

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#1352]
I'm trying to download the windows version of the latest nextcloud cllient from https://github.com/nextcloud/desktop/releases but all I get for the 2.5.3 version is an error 404...

**Comment by lemmy04** [comment]
actually, the Mac OS and Linux download links are also broken...

**Comment by camilasan** [comment]
Yes, I am still building it actually, it is only tagged at the moment. I will make the builds available tomorrow.

**Comment by lemmy04** [comment]
that explains that.

I hope the new version doesn't crash all the time anymore - and handles conflicting files better...

**Comment by lemmy04** [comment]
hm.. is there any actual difference between the latest binary from the daily builds server, and the one which will be available through https://nextcloud.com/install/#install-clients?

**Comment by camilasan** [comment]
Technically not yet.

**Comment by camilasan** [comment]
Links properly places: https://github.com/nextcloud/desktop/releases/tag/v2.5.3
