### ISSUE TITLE
NC windows client does not react to ACL permission changes

### ISSUE THREAD

**Issue by advpk** [nextcloud/desktop#1353]
### Expected behaviour
Existing ACL Group Folder 'DirA' with two subfolders 'DirB' and 'DirC' with full access rights for group 'X' containing 'User1' and 'User2'.
Both users have fully synced the hierarchy and all files with their local drive using NC client.
Now I create a new access rule for 'User2' for subfolder 'DirC': read access -> 'deny'
Expected: Subfolder 'DirC' is deleted from the local drive of 'User2' by the NC client

### Actual behaviour
NC windows client does not react on the change of permission.
Only after 'User2' restarts the NC client the 'DirC' disappears, but only from the list of folders for selective sync, however the content of the folder is still not deleted on the local drive.

### Steps to reproduce
1. Remove read access for a subfolder for one person of the group
2. Restart the nc client
3. 

### Client configuration
Client version: Version 2.3.3 (build1)

Operating system: Windows 10

OS language: German (DE)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version: 16.0.3

Storage backend (external storage): NFS

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by TheRealTripleB** [comment]
Hello,
I have the same problem here with the Mac client. 

Server version: 19.0.7
Group-Folders Version: 7.1.1
Mac Client Version: 3.1.1

Exactly the same behavior as described above. Unfortunately I can't find any errors in the console.
I can reproduce the problem on 3 different Mac.

Has anyone looked at this problem before? Doesn't look like the bug will be fixed in the near future.

**Comment by er-vin** [comment]
I guess we'd need debug logs to investigate this. I wonder how the now denied folder appears in the discovery.

**Comment by TheRealTripleB** [comment]
I did the following on my end to reproduce the problem.

Server version: 19.0.7
Group-Folders version: 7.1.1
Mac client version: 3.1.1
MacOS version: 10.15.7

In Chrome Browser under Preferences -> Group Folders I created a folder "FOLDER" and added Group1 with User1, as well as an Admin group (the admin I am creating this group folder with is in this group). For this test, both groups got write/share/delete permissions at this point. In the right column I activated the "Advanced Permissions" and specified the admin group. 
Then I go as admin into the Files App and create the following subfolders in the folder:
FOLDER
    - 2020
        - Project1
        - Project2
    - 2021
        - Project1
        - Project2
        - Project3
        - Project4

At this point, my Mac client (User1 logged in) has already synchronized the directories and that is correct. Then, as admin in the Files app, I set the permissions for User1 on the "2020" folder by clicking on the Share menu and setting the Read/Write/Create/Delete/Share permissions all to Deny. When I log in as User1 in the browser and go to the "FOLDER" folder in the Files app, I only see the "2021" folder with the projects in it, as requested. However, on the Mac client (User1 logged in) I still see the "2020" folder. But in the syncronistaion overview of the Nextcloud app on the client, the folder has already disappeared. Waiting does not help from this point on, even after 4 days the client on the Mac had not taken over that on the "2020" folder no permissions exist. 

If I set at the top level for the folder "FOLDER" also all permissions for the User1 to Deny. Logically, the folder "FOLDER" disappears from the client. After I remove this restriction on the top level, the folder is resynchronized and the correct permissions are applied. So the folder "2020" is not visible. However, the whole folder is removed and resynchronized.

In this example I have allowed all permissions on the top level and restricted the permissions on a subfolder. The problem also occurs when I do the whole thing the other way around. So no rights on top level and write rights on subfolders. Changes are not taken over in the Finder.


Attached is the log file (Mac Client User1 logged in) from the first few minutes after I restricted the permissions on the "2020" folder. I replaced my username with <USER> and the server address with <SERVER>.


Just let me know if you need more files or information.

[20210119_1246_owncloud.log](https://github.com/nextcloud/desktop/files/5836623/20210119_1246_owncloud.log)
