### ISSUE TITLE
NextCloud Client is not creating log files on Windows when using the --logdir option

### ISSUE THREAD

**Issue by schneidr** [nextcloud/desktop#1358]
### Expected behaviour
According to [the documentation](https://docs.nextcloud.com/desktop/2.5/troubleshooting.html#saving-files-directly), the client is supposed to create log files in the given dir when run with `--logdir` option.

### Actual behaviour
No log files are created

### Steps to reproduce
1. Create a directory `C:\temp\`
2. Start Nextcloud client with `C:\Program Files (x86)\Nextcloud\nextcloud.exe --logdir C:\temp --logexpire 48` 
3. Check the directory. No log file.

### Client configuration
Client version: 2.5.2git (build 20190319)

Operating system: Windows 10 Enterprise 1903

OS language: English

Installation path of client: `C:\Program Files (x86)\Nextcloud`

### Notes
The parameter `--logfile` works fine. It's not a permission problem.

**Comment by camilasan** [comment]
I just tried it and it works. I have Windows 10 in a VM. I executed ```nextcloud.exe --logdir C:\log``` in cmd.exe. Where are you executing it? I am using the latest code from master. Could you try our latest 2.5.3 release?

**Comment by schneidr** [comment]
No, it doesn't work for me with 2.5.3daily-win64 (build 20190725).
Using the parameter `--logfile` it creates a log file in the same directory.

**Comment by schneidr** [comment]
The same with 2.5.3daily-Win64 (build 20190808)

**Comment by BUFU1610** [comment]
Same here on Windows Client 3.0.3. --logfile is working, --logdir is not.
