### ISSUE TITLE
Nextcloud Client synchronisation automatically deletes files and folders when sync is switched off

### ISSUE THREAD

**Issue by Fohlenrolle** [nextcloud/desktop#1362]
I moved all my photos to my synch folder and after that started sorting and moving photos from different folders into others (all files from "Camera" folder into subfolders "2019", "2018" etc.). While I was moving the files I switched synch off to not have double files because synch process was running. Nextcloud client now started to delete all (!) files in synched "Camera" folder while many files were not synched yet. Many photos (beloved memories) now are gone forever as I wanted to use Nextcloud server as a backup but instead client deleted files completely. This behavior doesn't make sense.

### Expected behaviour
When synchronisation is switched off / stopping synchronisation, it should do just that - only stopping synch process. It should not delete any file in the HDD-folder automatically, it should just stop synching. At least there should be a dialog which asks if something should be deleted or you should be able to switch off this behavior in options. NC client should at least check which files are synched already and only delete those, not deleting files that are not synched, leaving them untouched. IMO client should not delete anything, never - only if files are moved or deleted manually it should synch that change only. There should be an option in settings to forbid NC client to delete files if synch is disabled.

### Actual behaviour
All files in a synched folder are deleted automatically from HDD. Doesn't matter if some files are not synched in that folder - just everything in this folder is deleted, even not synched files that therefore get lost.

### Steps to reproduce
1. Place files in Nextcloud synch folder, start synchronisation
2. While synch is in progress and some files are not synched, disable synchronisation for that particular folder
3. Contents of that folder get deleted completely (yellow "(!)" on files, then get deleted)

### Client configuration
Client version: 2.5.3git (477614)

Operating system:
Arch Linux

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
5.13.0

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client 2.5.3-2

Installation path of client:
(default)

Nextcloud version:
16.0.3

**Comment by camilasan** [comment]
> I moved all my photos to my synch folder and after that started sorting and moving photos from different folders into others (all files from "Camera" folder into subfolders "2019", "2018" etc.). While I was moving the files I switched synch off to not have double files because synch process was running. 

The sync engine should recognize that the files were moved. You didn't have to stop the sync for that.

**Comment by camilasan** [comment]
> While synch is in progress and some files are not synched, disable synchronisation for that particular folder

You mean while the file is being moved by your OS, right? The sync engine doesn't know that, I believe there is no way to know atm.

**Comment by camilasan** [comment]
Also I would recommend the reading of this thread: https://help.nextcloud.com/t/nextcloud-is-not-a-backup-system/5143/6

**Comment by Fohlenrolle** [comment]
To clarify: You got 10 files in synch folder on your hard disk. While synch is in progress and 6 files are synched and 4 are not synched yet, you stop synch process. Immediately all 10 files get deleted by NC client. It will just remove anything in synch folder, even files that are not synched. Stopping synch should not remove any file at all on my hard disk, while actually it does delete every file on hard disk, synched or not.

**Comment by Fohlenrolle** [comment]
Just tried again, and indeed NC client informs about wiping whole folder when turning off synch (missed that at first, sorry).
So this is not a bug but a feature proposal. There should be an option to leave files in local synch folders untouched when turning off synch for that folder instead of either
a) move the folder locally out of synch folder to stop synch, which then will produce an error message in client
b) letting NC client delete the folder including contents

Means (proposal):
Instead of the client asking to delete everything when synch is stopped there could be a possibility (instead of only confirm deletion):
c) just ask if data should be deleted locally or not - adding just a "No" or "Don't delete" button to the dialog appearing in client when turning off synch instead of leaving the user no choice but deletion of the folder.

**Comment by GoetheG** [comment]
Unfortunately Nextcloud is not as easy to use and notas stable as Dropbox :(. There is always some error not tomention the end-to-end-encryption problem. I really hope that this'll change.

**Comment by claell** [comment]
@Fohlenrolle as you correctly identified, this is rather a feature request, can you update the title and description accordingly?

**Comment by keunes** [comment]
@mgallien @claell I have the same issue/feature request, and others have expressed this as well [in the forum](https://help.nextcloud.com/t/stopping-sync-without-removing-the-local-folder/37899). In the forum people linked to the [equivalent issue in the OwnCloud client repo](https://github.com/owncloud/client/issues/2502).

I expected there to be an issue for this in Nextcloud's GitHub, and here we are :) It was just a bit hard to find, so it would be helpful if the title of this issue were adjusted. Given that the original reporter didn't follow up on your suggestion, I was wondering if you might be willing/able to do that. I was thinking of `Allow to stop sync of a sub-folder without deleting the local copy`.

**Comment by keunes** [comment]
Just to add my use-case: I had set up sync for my main Documents folder, and added a new subfolder for git work. As it's a new local folder, it got added and synced automatically (as expected). My git stuff is synchronised already via GitHub, and to avoid duplicate files I wanted simply to disable synchronisation, then delete the remote copy.
Ideally, the client asks me what I want to do:
* delete local files (keep remote files)
* keep local files (delete remote files*)
`*` copies on downloaded on other machines will remain available and will have to be deleted manually.

Many thanks to everyone working on the client and other parts of Nextcloud!

**Comment by keunes** [comment]
Related: #1238

**Comment by b12f** [comment]
Duplicate: https://github.com/nextcloud/desktop/issues/1238

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
