### ISSUE TITLE
symbolic link warnings obscure other warnings

### ISSUE THREAD

**Issue by nilsbecker** [nextcloud/desktop#1363]
I use Nextcloud to synchronize directories which contain internal symlinks. I do not plan to manually curate the directories I sync for symlinks; that would make Nextcloud almost useless to me.  Until a solution for symlink syncing is found, it should be possible to silence the associated warnings.

### Expected behaviour
Warnings that symlinks could not be synced should appear once and then it should be possible to silence them, e.g. "Do not show this warning again".
In that way, other, meaningful warnings would not get drowned in a sea of uninformative "symlinks not supported" warnings

### Actual behaviour
The log is flooded with "symlink" warnings

### Steps to reproduce
1. create directory with symlinks
2. sync
3. on every sync attempts, observe new uninformative warnings.

### Client configuration
Client version:
latest: version 2.5.2git

Operating system: OS X

**Comment by joshgiesbrecht** [comment]
Bump. This is making my activity log useless on Linux as well.

**Comment by joshgiesbrecht** [comment]
Files included in the ignore list are also flagging warnings, which seems even more useless. (Why is it notifying me about things I told it to ignore?)

**Comment by jancborchardt** [comment]
@nilsbecker @joshgiesbrecht @janvlug it’s your lucky day, this was fixed by https://github.com/nextcloud/desktop/pull/1523 :) :tada:
