### ISSUE TITLE
Sync fails when Nextcloud isn't installed in the root folder

### ISSUE THREAD

**Issue by k4200** [nextcloud/desktop#1365]
### Expected behaviour
The desktop app starts to sync files.

### Actual behaviour
The following error is displayed:
```
No connection to Nextcloud at https://example.com. Server replied "404 Not Found to "PROPFIND https://example.com/remote.php/webdav/"
```

### Steps to reproduce

1. Install Nextcloud to serve at `https://example.com/nextcloud`
1. Start the mac desktop app
1. Click on "Login" button
1. Enter `https://example.com/nextcloud` in "Server Address", then click on "Next"
1. Click on "Grant access" button on the web page inside the desktop app
1. Fill in "Username or email" and "Password", then click on "Log in →"
1. Leave everything as the default, then click on "Connect..." button

Then the error happens.

### Client configuration

Client version: Nextcloud-2.5.3.20190724.pkg
Operating system: macOS Mojave 10.14.6
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): n/a
Client package (From Nextcloud or distro) (Linux only): n/a
Installation path of client: /Applications/

### Server configuration
Nextcloud version:
Storage backend (external storage):

### Logs

1. Client logfile: https://gist.github.com/k4200/588ac7070e80b0b5c28502b7eda45d11

<img width="788" alt="nextcloud-sync-error" src="https://user-images.githubusercontent.com/539941/62177624-93e5af80-b380-11e9-94c6-e44ef6cebac8.png">

2. Web server error log: I see some 404s. The paths should be `/nextcloud/remote.php/webdav/`, not `/remote.php/webdav/`
```
n.n.n.n - - [31/Jul/2019:11:14:20 +0900] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 2105 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0"
n.n.n.n - - [31/Jul/2019:11:14:27 +0900] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 404 229 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.3release (build 20190724) (Nextcloud)"
n.n.n.n - - [31/Jul/2019:11:14:27 +0900] "GET /status.php HTTP/1.1" 404 208 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.3release (build 20190724) (Nextcloud)"
n.n.n.n - administrator [31/Jul/2019:11:14:27 +0900] "GET /nextcloud/status.php HTTP/1.1" 200 146 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.3release (build 20190724) (Nextcloud)"
n.n.n.n - - [31/Jul/2019:11:14:28 +0900] "PROPFIND /remote.php/webdav/ HTTP/1.1" 404 216 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.3release (build 20190724) (Nextcloud)"
n.n.n.n - - [31/Jul/2019:11:14:29 +0900] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 404 229 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.3release (build 20190724) (Nextcloud)"
```

3. Server logfile: nextcloud log (data/nextcloud.log): No log for the time frame of the error

**Comment by joshtrichards** [comment]
This hasn't been an issue for a long time. If you're still experiencing this, it's likely a configuration issue.
