### ISSUE TITLE
Segfault while browsing folder tree in client

### ISSUE THREAD

**Issue by aneyeforsecrets** [nextcloud/desktop#1367]
### Expected behaviour
Not for the client to crash

### Actual behaviour
Client crashed and the KDE crash handler offered to gather information

### Steps to reproduce
1. Open Nextcloud-Client
2. Browse file hierarchy (not consistent!)
3. Crash

### Client configuration
Client version:
Version 2.5.2git.
This release was supplied by Nextcloud GmbH
Built from Git revision 56c905 using Qt 5.13.0, OpenSSL 1.1.1c 28 May 2019

Operating system:
OpenSUSE Tumbleweed Snapshot 30072019

OS language: en_US (de_DE locals)

Qt version used by client package (Linux only, see also Settings dialog):
5.13.0

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Nextcloud version: 16.0.3

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

Backtrace: https://gist.github.com/aneyeforsecrets/3cf3ef1589831741204396ee4c35adf0

**Comment by camilasan** [comment]
Hi @aneyeforsecrets, do you have the same behavior with 2.5.3? https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.5.3-x86_64.AppImage

**Comment by DominiqueFuchs** [comment]
Please provide information about further segfault occurences in #241 , thanks!
