### ISSUE TITLE
Nextcloud Client cannot handle unmounted folders on Windows.

### ISSUE THREAD

**Issue by twatzl** [nextcloud/desktop#1368]
So I use veracrypt on an external hard disk. However you should also be able to reproduce the behaviour with any external drive, even USB drive.

First of all configure one sync folder on the external device.

When I have my ext hd not attached and the folder is marked as "Unable to find local folder" then clicking the "Add Folder Sync Connection" button causes Nextcloud to crash.

If I mount my external drive I can add new folders just fine. Also the logs do not contain any error messages. 

You should be able to reproduce using an ordinary USB drive, if not try to put a VeraCrypt volume on the USB drive.

If you have any questions feel free to ask.

### Expected behaviour
Adding folders should work fine, Nextcloud client should not crash.

### Actual behaviour
Nextcloud crashes, adding a folder does not work.

### Client configuration
Client version: 2.5.2

Operating system: Windows 10 Pro 1809

Installation path of client: G:/<default nextcloud path>

**Comment by violoncelloCH** [comment]
I can confirm this behavior to not be dependent on vera-crypt. Having a folder-sync connection on one external drive which is not attached/mounted currently leads to the crash when clicking "add folder sync". As crashing it's meant that the window closes immediately and the icon in the tray also vanishes as soon as you hover it.

**Comment by diatomm** [comment]
I can also confirm this behavior. Would log information be helpful?
