### ISSUE TITLE
Release 2.5.3 is not mentioned on homepage

### ISSUE THREAD

**Issue by bjoernv** [nextcloud/desktop#1370]
The current NC client release is 2.5.3, but https://nextcloud.com/install/#install-clients shows 2.5.2.

**Comment by Kiaatix** [comment]
The Nextcloud launchpad PPA is still on version 2.5.2 too!

**Comment by affinityv** [comment]
Is 2.5.3 not considered a stable release?

**Comment by misch7** [comment]
The 2.5.3 is the current stable release.

I also noticed the links didn‘t change when it got released.

We‘re currently implementing a new release cycle to provide releases in shorter time periods. Anyways I‘ll try to ping the team to update the links. ;-)

**Comment by misch7** [comment]
Hey guys,

I'm happy to confirm the 2.5.3 downloads are now shown at our download page 😼 

Thanks for pointing that out, I'll close the issue now.

**Comment by misch7** [comment]
@Kiaatix I will fix that too ;)
