### ISSUE TITLE
"Not connected" bug

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/desktop#1375]
### Problem
After logging in to Windows desktop, the Nextcloud app will say it's not able to find/connect to the computer, shown by the icon here:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/62820405-2ac22100-bb64-11e9-868e-f301691e118d.png)

I tried syncing a file and it worked successfuly, and the icon turned to the "green checkmark" once again - so it's not that serious and it seems the sync is working. But if I don't do it, the icon will not turn green and will still say the connection is not established even though it is.

NOTE: I use a VPN with a kill-switch that cuts the connection for a few seconds immediately after logging-in.

### Steps to reproduce
1. Put PC to sleep
2. Wake up & Log in
3. Observe nextcloud connection status

### Client configuration
Client version: 2.5.2git

Operating system: w10

### Server configuration

Nextcloud version: 15

**Comment by GoetheG** [comment]
Same here. Andwith 2.5.3 too.

**Comment by mgallien** [comment]
I am not sure if that would be considered a bug or an enhancement.
So if I understand correctly, the connection that is used by the client is closed soon after the start. That would explain the red error icon. In that case, when connection is again possible the icon could be turned automatically to the green icon.
Can you please test with latest release before we can see what would improve the situation for you ?
