### ISSUE TITLE
Crash on Linux Mint from Flathub install after address input

### ISSUE THREAD

**Issue by karozagorus** [nextcloud/desktop#1378]
https://github.com/nextcloud/desktop/issues/1036

Because you guys scrubbed it under a rug, I'm gonna be re-opening the same issue because nothing was changed or fixed. Flathub install still failes, and PPA installation is not able to access the file system for some reason.

**Comment by claell** [comment]
@karozagorus I reopened the original issue, so this can be closed, I guess.
