### ISSUE TITLE
only the first contact in a contactList.vcf downloaded

### ISSUE THREAD

**Issue by damdamce** [nextcloud/desktop#138]
I stored a backup of my phone contacts on the server as a normal file (not webdav). When i download the file through normal synchronisation, it gets truncated to the first contact.

My platform:
Linux Mint 18.2 (Ubuntu 16.04) with KDE updated via the neo distribution.
Nextcloud client 2.3.3
server 12.0.5

**Comment by rullzer** [comment]
Mmmm this sounds like a server bug. As the client doesn't care about the content.

Does it also happen if you download the file in the browser?

**Comment by damdamce** [comment]
No, it doesn't happen in the browser. I used it to verify the file is there and complete.

**Comment by rullzer** [comment]
Mmmm weird. Could you craete a dummy file that has the same behaviour and share that? Because my  quick test works.

**Comment by damdamce** [comment]
Sure:
[contacts_min.tar.gz](https://github.com/nextcloud/client/files/1670436/contacts_min.tar.gz)

Just to be sure that we are on the same page, steps to reproduce:
1. go to a test folder through the browser
2. click the "+" and upload file
3. use the sync client to sync that test folder

I compressed the file so github has no chance to change any characters.

**Comment by damdamce** [comment]
Not sure it matters, but i also use web dav + the contacts plugin on the same installation. syncing those works fine with thunderbird.

**Comment by rullzer** [comment]
@damdamce thanks. I've added it to my todo and will soonish (tm) try to figure out what is going on here ;)

**Comment by damdamce** [comment]
Cool. Were you able to reproduce?

**Comment by michaelstingl** [comment]
@rullzer Data corruption and no response for more than two months?

**Related:**
- nextcloud/server#6711
- nextcloud/server#7226

Checksums would prevent download of corrupted data (as seen in [upstream project](https://github.com/owncloud/client)):

![owncloud](https://user-images.githubusercontent.com/214010/38638907-ff6d276a-3dcf-11e8-8c60-77ff110027ae.png)

**Comment by camilasan** [comment]
@damdamce Sorry for the late reply. Did you try the same with Nextcloud server 13? Do you still have the problem?

**Comment by rullzer** [comment]
Should be fixed in https://github.com/nextcloud/server/pull/9268
