### ISSUE TITLE
openSUSE/KDE: connection error on booting (auto start, with WiFi)

### ISSUE THREAD

**Issue by guoyunhe** [nextcloud/desktop#1380]
### Expected behaviour
When booting into system, it may take some time to connect to the WiFi. Nextcloud client should wait for WiFi connection. When internet is connected, it should retry sync.

### Actual behaviour
Nextcloud client will fail sync and complain about "server not found at ..., timeout". And it will never retry when WiFi is connected.

![Screenshot_20190815_103102](https://user-images.githubusercontent.com/5836790/63079807-0db49600-bf48-11e9-8897-5f60a73b62a3.png)

### Steps to reproduce
1. Install Nextcloud client on openSUSE Tumbelweed.
2. Set auto start on boot.
3. Reboot system in WiFi environment, no wired connection.

### Client configuration
Client version:

Operating system: openSUSE Tumbleweed

OS language: Chinese Simplified

Qt version used by client package (Linux only, see also Settings dialog): 5.13.0

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: 

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by MrManor** [comment]
+1 using Opensuse 15.1, with KDE

**Comment by javierllorente** [comment]
If I disconnect my laptop from the WiFi and reconnect to it, the desktop client automatically reconnects to my Nextcloud server.
I can't reproduce the case you mention since my laptop connects to the WiFi very quickly after boot up.
Tested with openSUSE Tumbleweed 20190909, Qt 5.13.1, Nextcloud client 2.5.3

**Comment by guoyunhe** [comment]
I also feel, this is not always reproduceable. But it happens sometime, depending on WiFi.

**Comment by javierllorente** [comment]
Nextcloud client's http timeout default value is 5 minutes.
Have you seen the same behaviour on other applications?

**Comment by guoyunhe** [comment]
No. Other applications, like Telegram, always keep retrying after 10s, 20s, 60s, 3min, 5min, 7min...

**Comment by javierllorente** [comment]
`ConnectionValidator` checks for connection every 32 seconds `(DefaultCallingIntervalMsec).` Anyways, logs would be very helpful.

**Comment by MrManor** [comment]
On my system the problem seems to occur often when my labtop is moved between, - or started up on a different network, requiring changed network settings, changed default gateway, changed active interface ect. Sometimes even the ip for the Nextcloud host is changed (from the indside 172.16..something - and on the road is should connect to my public ip). 
Then I most often end up with this box. Which is weird as I can  click the link shown in the error and Firefox opens Nextclouds webpage without problems.
![nextcloud-nc](https://user-images.githubusercontent.com/4838974/65369958-0d4ca080-dc54-11e9-8157-c98605454952.png)
the message roughly translates to "_Host blabla not found_"

@javierllorente  I will try to capture a log next next time I move to new network.

**Comment by javierllorente** [comment]
I have been able to reproduce the behaviour mentioned on this issue; booted up without automatic connection to my WiFi and, afterwards, I connected to it.
```
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://domain.org/nextcloud/status.php" has X-Request-ID "ebb4bd70-3c94-43cd-9b68-b82360efd94e"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://domain.org/nextcloud" + "status.php" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::HostNotFoundError "Equipo domain.org no encontrado" QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::HostNotFoundError
[OCC::WebFlowCredentials::stillValid 	"Equipo domain.org no encontrado"
[OCC::CheckServerJob::finished 	error: status.php replied  0 ""
[OCC::ConnectionValidator::slotNoStatusFound 	QNetworkReply::HostNotFoundError "Equipo domain.org no encontrado" ""
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::HostNotFoundError
[OCC::WebFlowCredentials::stillValid 	"Equipo domain.org no encontrado"
[OCC::FolderMan::slotAccountStateChanged 	Account "javier@domain.org" disconnected or paused, terminating or descheduling sync folders
```

**Comment by javierllorente** [comment]
Unfortunately, this is hard to reproduce. I can't reproduce it any more (so far) using the method explained above.

**Comment by guoyunhe** [comment]
I also found, when it is not able to connect to server, its CPU usage is high. (12% of a 8-core CPU, almost maximum of a core).

**Comment by MrManor** [comment]
For me I think the problem had disappeared after one of the resent updates. Now I am more often required to perform a 2 factor login (which is also annoying, but another case) but apart from that connection seems to work now.

**Comment by guoyunhe** [comment]
The largest change I got this error is when cold boot (the laptop has been powered off for a while and then you boot into system). If I restart, logout/login, sleep/resume, the problem isn't appearing.

**Comment by guoyunhe** [comment]
I have been watching the log output these days. It seems like:

1. In some situation, WiFi connection takes a very long time to establish.
2. The connection has several stages: establish connection, authentication, get ip address.
3. When WiFi authentication is done, nextcloud immediately started to fetch server status. But here is no IP address, yet. So it failed and says it "terminating or descheduling sync folders". This means it won't try again in future.

**Comment by guoyunhe** [comment]
Just checked the code https://github.com/nextcloud/desktop/blob/v2.6.0/src/gui/application.cpp#L237

Nextcloud will anyway check for connection every 32 seconds. Here might be something affected the timer. Otherwise, it must retry connection.

I found myself cannot reproduce the issue when I wanted to. It only happens when I am not testing it...

**Comment by guoyunhe** [comment]
Today, after my first cold boot to the system and manually connect to WiFi, I reproduced the issue. And nextcloud client does retry every 32 seconds. But it gets UnknownNetworkError (@javierllorente got HostNotFoundError):

```
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://cloud.guoyunhe.me/status.php" has X-Request-ID "4bdfdecb-d41c-48cf-a222-568cb81900aa"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://cloud.guoyunhe.me" + "status.php" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::UnknownNetworkError "网络不能访问" QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownNetworkError
[OCC::WebFlowCredentials::stillValid 	"网络不能访问"
[OCC::CheckServerJob::finished 	error: status.php replied  0 ""
[OCC::ConnectionValidator::slotNoStatusFound 	QNetworkReply::UnknownNetworkError "网络不能访问" ""
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownNetworkError
[OCC::WebFlowCredentials::stillValid 	"网络不能访问"
[OCC::FolderMan::slotAccountStateChanged 	Account "guoyunhe@cloud.guoyunhe.me" disconnected or paused, terminating or descheduling sync folders
```

However, the network is indeed connected and other applications, manually started, can access internet.

Another application that has similar issue is Konversation (KDE's IRC client). If I make it auto-start on boot, it cannot connect to IRC servers. I have to quit and restart. They both use the Qt Network library to detect connection before sending request.

**Comment by javierllorente** [comment]
@guoyunhe It sounds like a Qt bug for me as well. Thanks for reporting it upstream; [QTBUG-79556](https://bugreports.qt.io/browse/QTBUG-79556)
