### ISSUE TITLE
Appimage generates non-functional autostart entry

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#1381]
The appimage generates an autostart entry with the exec line 
Exec=/tmp/.mount_Nextcl2hFTBK/usr/bin/nextcloud
which is of course going to fail,  as the image will not be mounted until started. So the correct autostart line should contain the path to the appimage itself

**Comment by probonopd** [comment]
@Stale

**Comment by vasyugan** [comment]
Hello, just pinging to keep this issue open. Still unresolved

**Comment by rottmann** [comment]
Confirmed, under Linux Mint 19.2 it creates an autostart path to `/tmp/....`

**Comment by probonopd** [comment]
Looks like the autostart file tries to launch something that is inside the AppImage, rather than the AppImage itself. This is guaranteed to fail if the AppImage since has been unmounted.

The code should check whether the `APPIMAGE` and `APPDIR` environment variables are present and set, and if so, set `APPIMAGE` as the value or the `Exec=` key in the autostart file.

**Comment by Erriez** [comment]
`Nextcloud-2.6.4-x86_64.AppImage` generates an invalid startup entry on Ubuntu 18.04.4 LTS as well with `Launch on System Startup` enabled. We need a workaround for this problem which still exists for a long time:

![NextcloudSettings](https://user-images.githubusercontent.com/8849873/77821382-2db95400-70ea-11ea-8b5e-2c3368990055.png)

`Ubuntu Startup Application`:
![Ubuntu1804StartupApplication](https://user-images.githubusercontent.com/8849873/77821308-715f8e00-70e9-11ea-9980-c77a8a202379.png)

`Nextcloud startup entry`:
![NextcloudStartupEntry](https://user-images.githubusercontent.com/8849873/77821314-80ded700-70e9-11ea-93f2-38c38cb85aff.png)

Path refers to Temp directory which is cleared after a system restart.
Invalid path: `/tmp/.mount_NextclSiNPzF/usr/bin/nextcloud`

What is the correct syntax to start the app image at system startup?

**Comment by vasyugan** [comment]
> What is the correct syntax to start the app image at system startup?

That would be the path of the AppImage whereever you saved it.

**Comment by probonopd** [comment]
Nextcloud could check for the presence of the `$APPIMAGE` variable and use that as the path for writing the autostart path, if present.

**Comment by Erriez** [comment]
> > What is the correct syntax to start the app image at system startup?
> 
> That would be the path of the AppImage whereever you saved it.

Thanks for your suggestion, this workaround works for me.

I found another workaround by installing the Nextcloud client on Ubuntu from PPA instead of the AppImage:

https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
```
sudo add-apt-repository ppa:nextcloud-devs/client
sudo apt-get update
sudo apt install nextcloud-client
```

**Comment by vasyugan** [comment]
> I found another workaround by installing the Nextcloud client on Ubuntu from PPA instead of the > AppImage:

That's working around the the bug in the flatpak by not using the flatpak. Sure, but for others who don't use Ubuntu, this is not really an option.

**Comment by suokunlong** [comment]
Duplicate of #434.
