### ISSUE TITLE
linux client crashes for no discernable reason

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#1382]
### Expected behaviour
I would expect the client not to crash

### Actual behaviour
the client crashes

### Steps to reproduce
1. install nextcloud client on linux
2. configure syncinc
3. ?
4. client crashes

### Client configuration
Client version:
2.5.3 built from source

Operating system:
openSUSE 15.0 / Plasma

OS language:
german

Qt version used by client package (Linux only, see also Settings dialog):
Built from Git revision 477614 using Qt 5.13.0, OpenSSL 1.1.0i-fips 14 Aug 2018

Client package (From Nextcloud or distro) (Linux only):
distro package

Installation path of client:
/usr/bin

### Logs

https://gist.github.com/lemmy04/2b3409177a7ebe2efed153a6a97ccede

**Comment by giancarlogiesa** [comment]
i think to have the same problem with the same 2.5.3
Linux distribution: Debian 10
Installed: from ufficial Debian package
language: italian

the CPU go to 100% and will never end the job or simply crash

i think that can be a GUI problem because i read on Debian forum that an user can run the client from terminal without problems

**Comment by lemmy04** [comment]
well i'm having the same problems on windows as well, client crashes quietly without any error message - in fact the only way to know that it crashed is to open the windows system tray, and put your mouse pointer over the nextcloud icon - if it disappears the client had crashed some time ago, and you need to restart it. And there is no way of knowing when it crashed and how much syncing is necessary to get "up to scratch".

**Comment by bstin** [comment]
I also have Debian 10 and have noticed that after upgrading to 2.5.3 client suddenly the tray icon will disappear and syncs no longer happen (although running ps -ax still shows Nextcloud client running...zombie?)

I have reverted to 2.5.2 for this reason.

**Comment by lemmy04** [comment]
2.5.2 wasn't any better for me...

**Comment by Ezwen** [comment]
I have a Linux Mint 19 user who experiences multiple silent crashes per day of the desktop client 2.5.3 (flatpak version). I asked him to provide some logs, but the logs don't show anything about the crash, and the last four messages are all of the type `[OCC::FolderWatcher::changeDetected 	Detected changes in paths ...`. No apparent error, no seg fault, nothing.

Very mysterious…

**Comment by DominiqueFuchs** [comment]
The fix for this issue was merged yesterday. If you'd like to try this out, you can install the daily build containing this changes - would be great if someone of the affected users here can report back on this 😄 Thanks to @mawasak !

**Comment by lemmy04** [comment]
I've just built it myself on OBS, lets see how it works.
Would this also fix the similar crashes happening on windows?

**Comment by lemmy04** [comment]
looking at the change itself, this might even fix the sync conflicts that I keep having with files that change a lot. now i'm kinda excited.

**Comment by DominiqueFuchs** [comment]
@lemmy04 May be, but a look at the log files would be required to check if the corresponding error originates from this specific circumstance (regarding the __other sync issues__). Thanks for reporting back here!

**Comment by lemmy04** [comment]
well, problem with that is that for some reasons I do not get any logfiles - they are always just empty...

**Comment by lemmy04** [comment]
hm so the latest windows daily build just crashed "out of the blue".
nextcloud-2.7.0.5832-daily-20190920-Release.exe  <-- that one.

where would I find logfiles of they exist?

**Comment by DominiqueFuchs** [comment]
Sorry that you are experiencing issues with the client build - wondering why bc I just built an installer package from master 10 minutes ago, but on windows. Check this page for ways to obtain logs on the client:

https://docs.nextcloud.com/desktop/2.5/troubleshooting.html#log-files

**Comment by lemmy04** [comment]
i'm not 100% sure yet but so far the linux client has been behaving ok. lets give this some more time before I close it tho.

**Comment by lemmy04** [comment]
I've been running the 2.6.0 client for a few days now, no more crashes - fix confirmed.

**Comment by TBoneStaek** [comment]
> 
> 
> I've been running the 2.6.0 client for a few days now, no more crashes - fix confirmed.

You mentioned earlier that you were having this issue on Windows but then mentioned that the Linux client was working for a few days with the 2.6.0 version. I'm having the exact same issue on Windows 10 64 with Nextcloud client version 2.6.4. It will run in system tray and the only way to know if it crashes after a few days is to hover over the icon and then it disappears. Then I have to restart it and it will run a day or so longer, then repeat.
