### ISSUE TITLE
NextCloud Client (Windows 10) 2.5.2 keeps crashing

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/desktop#1386]
I'm trying to sync my NextCloud folder to my Windows 10 PC, however, the NextCloud client keeps crashing. I don't get any error or anything, it just looks like it syncs and then disappears and closes. If I try to restart it, it keeps crashing every single time I try to open it after about 20-30 sec.

**Comment by misch7** [comment]
Did you try the more recent 2.5.3 release?

https://nextcloud.com/install/#install-clients
https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.5.3-setup.exe

Using the old 2.3.3 also involves using an outdated OpenSSL version.

Also you could try one of our daily builds to see if the issue still happens?
There are a lot of changes to make use of more current libraries for the new release:
https://download.nextcloud.com/desktop/daily/Windows/

**Comment by lemmy04** [comment]
I'm having the same problems ever since 2.5.0 rolled around, currently on 2.5.3 and crashing both on linux and on windows all the time.
Also, I get "conflicted" files all the time with files that have not actually changed for a week or so, and when I look the content IS in fact different. So ... I'm gonna roll back to 2.3.3 as well.

**Comment by mpass3** [comment]
Same issue on Windows. It started when I tried to sync a new large folder. Only Error I get is that it lost connection to account" on Nextcloud client, and my encryption request box pops up, then it closes.

**Comment by djamps** [comment]
Clean windows 10 install with client 2.6.2, initial sync hangs then fails ("cancelled") on larger folders.   Installed 2.3.3 and it syncs perfectly.

**Comment by TobiasDev** [comment]
I have also started running into this problem again. Both on Manjaro linux and Ubuntu

**Comment by TBoneStaek** [comment]
I've been having this same problem on my Windows client. It's been driving me nuts. It seemingly fails after a few hours. No message or error, just hover over the icon in the system tray and it disappears. I'm running the latest client 2.6.4 stable for Windows 10 x64.

**Comment by laarisyko** [comment]
Hi, we have the same behaviour here. For 2.6.4. it crashes several times a day. The version 2.7.0beta1 crashed almost every hour. It seems, that there is a majour problem, because we had the same situation for several of the privious versions. Any idea, how to solve this? This bug acutally renders Nextcloud useless for most users, unfortunalty .

**Comment by TBoneStaek** [comment]
> 
> 
> Hi, we have the same behaviour here. For 2.6.4. it crashes several times a day. The version 2.7.0beta1 crashed almost every hour. It seems, that there is a majour problem, because we had the same situation for several of the privious versions. Any idea, how to solve this? This bug acutally renders Nextcloud useless for most users, unfortunalty .

Yes, it's definitely been for a few versions now. Every time I update the client I hope it'll be fixed but alas...

**Comment by vansante** [comment]
I had the same issue, my client (2.6.2) kept on crashing and with the last log line always being:
```
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file C:\stack\windows\desktop\src\libsync\owncloudpropagator.cpp, line 835
```
I had a little look at the code and after some digging I found that the crash vanished when I set the `chunkingParallelUploadDisabled` capability on the server to `true` to ensure no concurrent chunks are being uploaded (I am using the old non NG upload style). This can also be done by setting an upload speed limit I think. This strengthened my belief there is an error somewhere in the parallel uploading code.

The crash seems to trigger when parallel uploading is enabled and one of the chunk upload threads encounters an error http status code (I got a `405`).

I hope this helps anyone :)

**Comment by laarisyko** [comment]
@vansante This sounds like a potential solution for the time beeing. Coud you please walk us through the steps. So where do we need to change what setting?

Many thanks for your help!

**Comment by vansante** [comment]
Hmm it seems that the upload NG code has no easy way to disable to the parallel chunk uploads. So for that the code just needs to be fixed Im afraid.

**Comment by BR0KK** [comment]
Its still present in the newest client. Just updated and it crashes after a few seconds. 

Will there be a fix?

**Comment by BR0KK** [comment]
in version 2.3.3 this beavior is gone.... But using an old client can not be the solution for this?

**Comment by SolarDesalination** [comment]
> in version 2.3.3 this beavior is gone.... But using an old client can not be the solution for this?

It's considered a regression. Using an old client is a temporary solution but the bug needs to be open to fix new versions.

**Comment by BR0KK** [comment]
How do we reopen this issue then or is it still opened? Any devs looking into this?

**Comment by SolarDesalination** [comment]
> How do we reopen this issue then or is it still opened? Any devs looking into this?

It's still open. Suggest reading the history. Apparently fixed and will be pushed in next desktop client release. 🙌

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by hoatienii** [comment]
same error with newest desktop client

**Comment by pmsoares** [comment]
Also having the same problem, with NextCloud desktop for Windows 10, version 3.2.2
Installed in two different machines, same problem.
Using a hosted NextCloud server.

Please help solving this problem.

**Comment by FlexW** [comment]
@hoatienii @pmsoares It is very well possible that you have a totally different problem than @TobiasDev. Please open a new issue and provide as much information as possible. Otherwise no one will be able to help you.

**Comment by bjmi** [comment]
What reverse proxy is used at frontend?
I had this issue a long time too but after switching from IIS (Windows) to Nginx (Linux) the crashes gone and I'm not affected by this anymore.

**Comment by maxpull** [comment]
> Also having the same problem, with NextCloud desktop for Windows 10, version 3.2.2
> Installed in two different machines, same problem.
> Using a hosted NextCloud server.
> 
> Please help solving this problem.

Same here, did you open a new issue? Can you link it to me please?

thx

**Comment by pmsoares** [comment]
> > Also having the same problem, with NextCloud desktop for Windows 10, version 3.2.2
> > Installed in two different machines, same problem.
> > Using a hosted NextCloud server.
> > Please help solving this problem.
> 
> Same here, did you open a new issue? Can you link it to me please?
> 
> thx

Hi.
I didn't open a new issue. I installed version 3.1.3 and it solved the problem.
I'll wait for a new major update for the latest version to test if the problem is solved.

**Comment by mattgroves** [comment]
I also have this issue on WIndows 10 with 3.3.0 - downgrading to 3.1.3 solved the problem. No new issue opened.
