### ISSUE TITLE
Each time file deleted, dialog box appears forcing human confirmation. [Download new files] or [Keep local files].

### ISSUE THREAD

**Issue by vadershade** [nextcloud/desktop#1387]
### Expected behaviour
Tell us what should happen
sync file deletions without human interraction
### Actual behaviour
Tell us what happens instead
dialog box is popping up whenever a file is deleted an asking for a yes/no confirmation to delete file across the nextcloud sync universe. two options in dialog box [Download new files] or [Keep local files]. Dialog box appears on all computers where the file was synced.
### Steps to reproduce
1. create file in nextcloud
2. delete file in nextcloud
3. user must then answer the dialog box to dismiss it.

### Client configuration
Client version: 2.5.3

Operating system: macOS

OS language: Englis

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 16.0.4

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

![nextcloudnag](https://user-images.githubusercontent.com/54476199/63638571-0e3fe180-c658-11e9-8277-281fb47e267a.png)

**Comment by FlexW** [comment]
You just need to set the `promptDeleteAllFiles=false` in the configuration file `nextcloud.cfg`. On macOS you can find this file in `/Users/USER/Library/Preferences/Nextcloud`.
