### ISSUE TITLE
OVA install script references dead goo.gl links

### ISSUE THREAD

**Issue by celerletum** [nextcloud/desktop#1388]
Script in OVA install package has goo.gl links that no longer work.

![image](https://user-images.githubusercontent.com/24758209/63643587-452deb80-c688-11e9-9ab7-68be22816fb5.png)

**Comment by mgallien** [comment]
This is not related to the Nextcloud desktop  client. Closing.
If you still have an issue, please check Nextcloud Virtual Machine project https://github.com/nextcloud/vm
