### ISSUE TITLE
[Feature Requests]: Per Folder custom sync time

### ISSUE THREAD

**Issue by blade1989** [nextcloud/desktop#1395]
### Expected behaviour
Please add this features in Nexcloud: Have the desktop client display a custom time sync options, per folder. 

**Options**:
sync every: 
 - Live sync
 - X second
 - X min
 - X hour
 - X week
 - X month
 - X year

### Actual behaviour
I have a projects folder, which I edit code in lots of time, sometimes i save files within a second or two, multiple times, which Nextcloud does not like, because it sometimes creates a backup of the file i was editing as 'filename-*conflict*-.php'. This brings to much noice to my project files.

### Steps to reproduce
1. Edit files multiple times within seconds,
2.
3.

### Client configuration
Client version:

Operating system: Ubuntu 18.04 bionic

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Version 2.5.2git

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Milokita** [comment]
You really should try using GIT

**Comment by blade1989** [comment]
@Milokita I use git. its just that I don't commit every code that I am live testing. 

I'm always afraid that my PC is gonna crash, and the function/design/structure that I was live testing, is gonna get lost. I am lazy, don't wanna code everything again.

Besides the example I just gave, this feature will be a highly used one for other people, whit other development setup and or backup structure.

**Comment by mgallien** [comment]
There are two things in your report.
First you are talking about a bug when editing files when you regularly save, Nextcloud would report some conflicts. Can you try with the latest version ?

As for the configuration of the sync period, as an user, I am not sure I would like that. I just want Nextcloud to work without having to fiddle with it. Syncing once a year does not make sense. That could make sense for big deployments to reduce the load on the server (tuning the interval for a few seconds or minutes).

Remember that Nextcloud is not a backup software. It seems that this is what you would want to use. Indeed, `git` is highly tuned to do that for source code.

**Comment by blade1989** [comment]
@mgallien yes, even with the latest version(`3.2.1`), I get a copy of the conflicting file in the following format in the same dir: `file (conflicted copy 2020-04-07 160359).odt`. 

Once a year was an example I just used. Although once a minute seems more appropriate. 

Nextcloud is indeed not a backup software, but this feature makea sense in more setting than one. 

when I'm heavily working on LibreOffice documents, I get a conflicted copy of the document file. 
So this feature make sense when files are modified faster then they could be uploaded. 

As a workaround I could use the nextcloud cmd and execute it via cron once a minute. But, this is a nice to have as a none default setting for users that keep getting conflicted copy files.

**Comment by mgallien** [comment]
@blade1989 Thanks for the reply.

Please provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)
Thanks!
