### ISSUE TITLE
Ubuntu PPA not updated

### ISSUE THREAD

**Issue by simonspa** [nextcloud/desktop#1396]
### Expected behaviour
The Ubuntu PPA advertised on the Nextcloud.com website should provide the latest release of the desktop client.

### Actual behaviour
Builds apparently stopped a few months ago and the last version available is 2.5.2:
https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

**Comment by ivaradi** [comment]
There was indeed a problem with regular builds, so we missed 2.5.3. However, builds to the beta repository resumed some time ago (although, temporarily, they fail currently due to another reason (see #1392)), so hopefully 2.5.4 will be available in the stable repo as well.

**Comment by mark-orion** [comment]
@ivaradi thanks for the info. And thanks for providing a PPA for the client. I definitely prefer a PPA to the likes of AppImages, Snaps and Flatpaks.

**Comment by NicolasGoeddel** [comment]
I can not find version 2.5.3 in the nextcloud-dev ppa. Is there only the AppImage available at the moment? What's the issue with bringing the ppa up-to-date?
I would also be okay to use Snap, but I don't know how. A `snap search nextcloud` on Ubuntu 19.04 only gives me a lot of Nextcloud servers but no client.

**Comment by MegaV0lt** [comment]
Please update the PPA with 2.5.3

**Comment by DominiqueFuchs** [comment]
@MegaV0lt @NicolasGoeddel as described in the answers above, PPA is very much alive thanks to @ivaradi .

2.5.3 build broke due to a compatibility change, but as soon as we release a new stable version (2.6.0 RC1 already out, won't take long) this should be available again.
If you want to, you can try out the cutting-edge version at [client-beta PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client-beta)

**Comment by Stijn98s** [comment]
2.6.0 is still not released in the ppa repository.

**Comment by DominiqueFuchs** [comment]
@Stijn98s it is now - the stable version was released just a few days ago.

I assume this issue can be closed, as we are back on trag with the latest stable on the PPA repo

**Comment by Stijn98s** [comment]
Yes, cool. this issue can be closed
