### ISSUE TITLE
Windows client 2.5.3 Network job timeout

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#1397]
### Expected behaviour
File synced to sever

### Actual behaviour
The server upload hangs and then times out
but the web upload is working correctly through browser

### Steps to reproduce
1. Change a synced file
2. Repeat the process and there is chance happening
3.

### Client configuration
Client version: 2.5.3

Operating system: Win10

OS language: Chinese

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:/Program Files/

### Server configuration

Nextcloud version: 16.0.4 (It also happens in lower version)

Storage backend (external storage): Local 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
`
[OCC::AbstractNetworkJob::slotTimeout 	Network job timeout QUrl("https://REMOVED/remote.php/dav/files/REMOVED/影像记忆/已整理/2017年-12月_哈尔滨/20171226_115621.jpg")
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::OperationCanceledError "连接超时" QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::OperationCanceledError
[OCC::WebFlowCredentials::stillValid 	"Operation canceled"
[OCC::PUTFileJob::finished 	PUT of "https://REMOVED/remote.php/dav/files/REMOVED/影像记忆/已整理/2017年-12月_哈尔滨/20171226_115621.jpg" FINISHED WITH STATUS "OperationCanceledError 连接超时" QVariant(Invalid) QVariant(Invalid)
[unknown 	QIODevice::read (QNetworkReplyHttpImpl): device not open
[OCC::PropagateItemJob::done 	Could not complete propagation of "已整理/2017年-12月_哈尔滨/20171226_115621.jpg" by OCC::PropagateUploadFileV1(0x17b9c6037d0) with status 1 and error: "连接超时"
[OCC::ActivityWidget::addError 	Item  "REMOVED"  retrieved resulted in  "连接超时"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "连接超时"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:REMOVED" to QLocalSocket(0x17b9abb73f0)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC+SWM:REMOVED\\已整理" to QLocalSocket(0x17b9abb73f0)
[OCC::ActivityWidget::slotItemCompleted 	Item  "已整理/2017年-12月_哈尔滨/20171226_115621.jpg"  retrieved resulted in  "连接超时"
[OCC::ActivityWidget::slotItemCompleted 	Item  "已整理/2017年-12月_哈尔滨/20171226_115621.jpg"  retrieved resulted in error  "连接超时"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "连接超时"
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_SYNC propagation of "已整理/2017年-12月_哈尔滨/20171227_094320.jpg" by OCC::PropagateUploadFileV1(0x17b9d49fbe0)
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::OperationCanceledError "Operation canceled" QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::OperationCanceledError
[OCC::WebFlowCredentials::stillValid 	"Operation canceled"
[OCC::PUTFileJob::finished 	PUT of "https://REMOVED/remote.php/dav/files/REMOVED/影像记忆/已整理/2017年-12月_哈尔滨/20171226_115616.jpg" FINISHED WITH STATUS "OperationCanceledError Operation canceled" QVariant(Invalid) QVariant(Invalid)
[unknown 	QIODevice::read (QNetworkReplyHttpImpl): device not open
[OCC::PropagateItemJob::done 	Could not complete propagation of "已整理/2017年-12月_哈尔滨/20171226_115616.jpg" by OCC::PropagateUploadFileV1(0x17b9d49d2d0) with status 3 and error: "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "已整理/2017年-12月_哈尔滨/20171226_115616.jpg"  retrieved resulted in  "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "已整理/2017年-12月_哈尔滨/20171226_115616.jpg"  retrieved resulted in error  "Operation canceled"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Operation canceled"
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_SYNC propagation of "已整理/2017年-12月_哈尔滨/20171227_094428.jpg" by OCC::PropagateUploadFileV1(0x17b9d4a14a0)
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_SYNC propagation of "已整理/2017年-12月_哈尔滨/20171227_104302.jpg" by OCC::PropagateUploadFileV1(0x17b9d49d000)
[OCC::SyncJournalDb::close 	Closing DB "REMOVED/._sync_c8e40016c6dc.db"
[OCC::SyncEngine::finalize 	CSync run took  329091 ms
[OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.24.0"
[OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE+SWM:REMOVED\\已整理" to QLocalSocket(0x17b9abb73f0)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:REMOVED" to QLocalSocket(0x17b9abb73f0)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:REMOVED" to QLocalSocket(0x17b9abb73f0)
[OCC::Folder::slotSyncFinished 	Client version 2.5.3daily-Win64 (build 20190725)  Qt 5.12.3  SSL  OpenSSL 1.0.2s  28 May 2019
[OCC::Folder::slotSyncFinished 	SyncEngine finished with ERROR
[OCC::Folder::showSyncResultPopup 	Folder sync result:  3
[OCC::Folder::slotSyncFinished 	the last 1 syncs failed
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:REMOVED" to QLocalSocket(0x17b9abb73f0)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:REMOVED" to QLocalSocket(0x17b9abb73f0)
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://REMOVED/remote.php/dav/files/REMOVED/影像记忆" :  "Error"
[OCC::FolderMan::slotFolderSyncFinished 	<========== Sync finished for folder [P:\???????] of account [REMOVED@REMOVED] with remote [https://REMOVED/remote.php/dav/files/REMOVED/???????]
`

2. Web server error log:
No related error
3. Server logfile: nextcloud log (data/nextcloud.log):
`
"message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 4202782 got 204800","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1130,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":["*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":513,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/REMOVED\/remote.php\/dav\/files\/REMOVED\/%E5%BD%B1%E5%83%8F%E8%AE%B0%E5%BF%86\/%E5%B7%B2%E6%95%B4%E7%90%86\/2017%E5%B9%B4-12%E6%9C%88_%E5%93%88%E5%B0%94%E6%BB%A8\/20171226_115616.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/REMOVED\/remote.php\/dav\/files\REMOVED/%E5%BD%B1%E5%83%8F%E8%AE%B0%E5%BF%86\/%E5%B7%B2%E6%95%B4%E7%90%86\/2017%E5%B9%B4-12%E6%9C%88_%E5%93%88%E5%B0%94%E6%BB%A8\/20171226_115616.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/REMOVED\/remote.php\/dav\/files\/REMOVED\/%E5%BD%B1%E5%83%8F%E8%AE%B0%E5%BF%86\/%E5%B7%B2%E6%95%B4%E7%90%86\/2017%E5%B9%B4-12%E6%9C%88_%E5%93%88%E5%B0%94%E6%BB%A8\/20171226_115616.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/REMOVED\/remote.php\/dav\/files\/REMOVED\/%E5%BD%B1%E5%83%8F%E8%AE%B0%E5%BF%86\/%E5%B7%B2%E6%95%B4%E7%90%86\/2017%E5%B9%B4-12%E6%9C%88_%E5%93%88%E5%B0%94%E6%BB%A8\/20171226_115616.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/html\/remote.php","line":163,"args":["\/var\/www\/html\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":228,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.3daily-Win64 (build 20190725) (Nextcloud)","version":"16.0.4.1"}
`

**Comment by Milokita** [comment]
Possible similarity: https://github.com/nextcloud/desktop/issues/771#issue-376502695

**Comment by Milokita** [comment]
Delete the sync and readding the folder to sync the problem consists

**Comment by GoetheG** [comment]
Completely buggy peace of software unfortunately.

**Comment by aneyeforsecrets** [comment]
I have a similar issue, interestingly repeatingly with the same file(s).

https://gist.github.com/aneyeforsecrets/7bacbf28ad3d7ef325ac67ce9315dca3

Specifically: C:\\Users\\me\\Nextcloud\\Anki\\IN0011 - Einführung in die Theoretische Informatik.apkg

Version 2.5.3daily-Win64 (build 20190725)

Server running in the local network with version 16.0.4

**Comment by rio-** [comment]
Any news on this issue?

**Comment by Milokita** [comment]
> 
> 
> Any news on this issue?
problem still therer
https://github.com/nextcloud/desktop/issues/1025#issuecomment-547111740

**Comment by warnerbryce** [comment]
Still the same problem with 2.6.1 and 2.6.3 for windows 10. 
I just get back to 2.3.3 whaou everthing works. 

Come on @camilasan we can’t stay like this with a sync client that have been released in Nov.2017 !

**Comment by Milokita** [comment]
> 
> 
> Still the same problem with 2.6.1 and 2.6.3 for windows 10.
> I just get back to 2.3.3 whaou everthing works.
> 
> Come on @camilasan we can’t stay like this with a sync client that have been released in Nov.2017 !

you can disable the http2 for now in your server, or uses the owncloud version as both oc and nc uses webdav

**Comment by misch7** [comment]
> > Still the same problem with 2.6.1 and 2.6.3 for windows 10.
> > I just get back to 2.3.3 whaou everthing works.
> > Come on @camilasan we can’t stay like this with a sync client that have been released in Nov.2017 !
> 
> you can disable the http2 for now in your server, or uses the owncloud version as both oc and nc uses webdav

With #1823 in the 2.6.4 release HTTP/2 will be disabled by default for now, thanks @Milokita
