### ISSUE TITLE
Windows 10: List of available Nextcloud files/folders not shown

### ISSUE THREAD

**Issue by j-ed** [nextcloud/desktop#14]
## Expected behavior
The desktop client should show all available Nextcloud files and folders so that they can be selected for synchronization.

## Current behavior
The desktop client doesn't show any Nextcloud files or folders on a Windows 10 PC.

<img width="501" alt="20171015_nc-desktop-app-folder-empty" src="https://user-images.githubusercontent.com/2572764/31586937-bb9d4e26-b1d8-11e7-8bcc-471f59eea6b2.PNG">

## Already tested
1. removed and reinstalled Nextcloud desktop app -> result doesn't change. 😞 
2. tried to access the Nextcloud account from different Win10 user account -> result doesn't change. 😞  
3. tried to access the Nextcloud account from a Win7 Pro system -> worked 😄 

### Steps to reproduce
1. Install the Nextcloud desktop app
2. Enter the login credentials (I'm using a dedicated app password)
3. Select 'Add folder for synchronization'
4. Choose the default local folder and press 'Continue'.
5. The list of remote folders is empty and pressing the 'Update' doesn't change the result.

## Log entries
Nothing special has been logged.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.28
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.0.3

#### Client Configuration
Browser: Mozilla Firefox 56.0
Nextcloud app version: 2.3.2 (build 1)
Operating system: Windows 10 Pro

**Comment by j-ed** [comment]
For a short period of time files/folders for one desktop user have been displayed yesterday. Unfortunately I don't know it it had happened. Today the latest Windows 10 update has been installed and after that the client wasn't able to find any folder on the server again.

I reinstalled the software again and found out, that folders are shown if I run the Nextcloud app as a domain administrator on the PC but if I run it as a normal user no remote files/folders are shown.
It looks like the app has some problems to read/write to some local files if it as run as a normal user.

Does someone has an idea how I could solve the problem or at least identify the root cause of the problem?

**Comment by j-ed** [comment]
I've upgrade the Nextcloud desktop client to `v2.3.3.1-beta` but the problem still persists. Then I've installed the **`ownCloud desktop app v2.3.3.8250`** and what a wonder the missing files/folders were shown again and I was able to select files/folders for synchronization.
What does the ownCloud desktop client have what is missing in the Nextcloud desktop client?

**Comment by tcanabrava** [comment]
Nothing, it's the same + theme.

**Comment by camilasan** [comment]
Is that still the case? @tcanabrava @j-ed

**Comment by j-ed** [comment]
@camilasan I cannot replicate the problem on my current Win 10 PC with NC desktop v2.5.1, so I would recommend to close this issue.
