### ISSUE TITLE
Virtual Drive installation error

### ISSUE THREAD

**Issue by metsuke0** [nextcloud/desktop#1400]
### Expected behaviour
The Virtual Drive Tech Preview would install with no errors.

### Actual behaviour
The Nextcloud client setup runs and after installing the Dokan portion it runs into a Windows Installer error.  The install finishes, but I am unable download any files.

### Steps to reproduce
1. Download virtual drive tech preview
2. Install

### Client configuration
Client version:
Nextcloud 2.5.0.5040 - techpreview

Operating system:
Windows 10 Home 1803

OS language:
English

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version:
16.0.4
Storage backend (external storage):
ZFS

Here is the error I get when I install.
https://imgur.com/a/x6QeWu8

**Comment by warnerbryce** [comment]
please do a search on github / nextcloud forum before posting.

**Comment by metsuke0** [comment]
Duplicate of https://github.com/nextcloud/desktop/issues/1056.
