### ISSUE TITLE
Deleting items in Groupfolders always leads to Trasmission errors on other clients

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/desktop#1403]
### Expected behaviour
Directories and files deleted by user a in a groupfolder should disappear from other users that have it synced.

### Actual behaviour
The other users get a HTTP transmission error and their sync stops

### Steps to reproduce
1. Create a groupfolder and put files and folders in it (folders are more affected)
2. Have two or more users sync them on any platform with at least Desktop version 2.5
3. Get a trasmission error like below:

[OCC::DiscoverySingleDirectoryJob::directoryListingIteratedSlot 	Missing properties: "Save the date" 2 0 1567506709 "DNVS" "" "-0000001oc11jaqjg0af"
[csync_ftw 	opendir failed for  - errno 10011
[OCC::SyncEngine::handleSyncError 	ERROR during  csync_update :  "Er trad een HTTP transmissiefout plaats. In de reactie van de bestandenontdekker van de server ontbreken gegevens."
[OCC::ActivityWidget::addError 	Item  "Nextcloud"  retrieved resulted in  "Er trad een HTTP transmissiefout plaats. In de reactie van de bestandenontdekker van de server ontbreken gegevens."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Er trad een HTTP transmissiefout plaats. In de reactie van de bestandenontdekker van de server ontbreken gegevens."

### Client configuration
Client version: 2.5.3

Operating system:
Server: Ubuntu 18.04
Client: Any of Mac, Linux. Windows

OS language: english or dutc

### Server configuration

Nextcloud version: 16.0

Storage backend (external storage): local files but groupfolders

**Comment by gvansanden** [comment]
In the database:
select * from oc_mounts where mount_point like '%Save the%';
 id  | storage_id | root_id |               user_id                |                        mount_point                         | mount_id 
-----+------------+---------+--------------------------------------+------------------------------------------------------------+----------
 521 |          1 |   38093 | 9293B906-7797-40B5-A2AD-E4EE231CDFEB | /9293B906-7797-40B5-A2AD-E4EE231CDFEB/files/Save the date/ |         

 fileid | storage |                       path                        |            path_hash             | parent |           name            | mimetype | mimepart |   size   |   mtime    | storage_mtime | encrypted | unencrypted_size |     etag      | permissions | checksum 
--------+---------+---------------------------------------------------+----------------------------------+--------+---------------------------+----------+----------+----------+------------+---------------+-----------+------------------+---------------+-------------+----------
  38093 |       1 | __groupfolders/trash/12/Save the date.d1566933387 | 6bf7148a90ddd1e3cc0526395347326b |  78988 | Save the date.d1566933387 |        2 |        1 | 42705450 | 1566312286 |    1566297791 |         0 |                0 | 5d5c075e42249 |          31 | 

Deleting both and the files in trash on disk clears the error

**Comment by gvansanden** [comment]
So, the way deletes are handled for groupfolders, trigger another known sync bug.

**Comment by gvansanden** [comment]
This query will show if and which files are having this issue:

select * from oc_mounts where root_id in (select fileid from oc_filecache where path like '%__groupfolders/trash%');

**Comment by mgallien** [comment]
Please can you test again with the latest version ?

**Comment by gvansanden** [comment]
@mgallien I stopped using Group Folders on all setups that use sync at the end of 2019, I can also not quickly test it as it only seems to occur on sites where more than one user work on the same groupfolder.

**Comment by mgallien** [comment]
> @mgallien I stopped using Group Folders on all setups that use sync at the end of 2019, I can also not quickly test it as it only seems to occur on sites where more than one user work on the same groupfolder.

no problem
thanks for the answer and the time you had put on this issue

I will now close the issue but please feel free to report other problems you would have (or ping us on this one if you would still be impacted in the future)
