### ISSUE TITLE
Connection timeout to server when ipv6 is not disabled (includes workaround)

### ISSUE THREAD

**Issue by katakombi** [nextcloud/desktop#1406]
### Expected behaviour

The desktop client starts, logs into the configured account and keeps syncing (systray icon green) 
A readily configured Nextcloud account should continue to work regardless of the system having ipv4 or ipv4+ipv6 support. 

### Actual behaviour
The desktop client starts, tries to connect to the server and runs into a timeout (systray icon gray)

### Steps to reproduce
1. Install LinuxMint 18.3
2. Take arbitrary AppImage build (>= 2.5.2)
3. Setup your account. Your setup will fail due to connection timeout.

### Workaround
edit `/etc/sysctl.conf`
append
```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
`sysctl -p`
restart nextcloud desktop client

### Client configuration
Client version: 2.5.2git, 2.5.3 AppImage, 2.5.3 daily build

Operating system: Linux Mint 18.3

OS language: US (C)

Qt version used by client package (Linux only, see also Settings dialog):
5.9.5

Client package (From Nextcloud or distro) (Linux only):
both from repo and from appimage

### Server configuration

https://nx3893.your-next.cloud/status.php

**Comment by katakombi** [comment]
additional note: after applying the workaround you need to relogin.

**Comment by mgallien** [comment]
Sorry, this is more of a support question than a bug report. And that means you should either ask help from the volunteers on the forum at [help.nextcloud.com](help.nextcloud.com) (who can help you debug and turn it in a bug report if it is a bug) or, if this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/) and we help you fix it in a few hours or days (according to the SLA).
