### ISSUE TITLE
POPos: NextCloud client 2.5.2 and 2.5.3 crashes when I enter my provider address

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/desktop#1410]
I just installed popOS on my desktop computer to use as my daily driver, however, as soon as I press enter when I have written my NextCloud provider address the app instantly crashes. 

It says something in the terminal about a signal 6 error.

Anyone know how I can fix this?

**Comment by camilasan** [comment]
We have released for a RC for 2.6 with a new login flow: https://github.com/nextcloud/desktop/releases/

Could you check if the error still occurs in 2.6.rc1?

**Comment by TobiasDev** [comment]
Will test and let you know!

**Comment by misch7** [comment]
Please try our recent 2.6 release and re-open this ticket if the problem still persists with it:
https://nextcloud.com/install/#install-clients
