### ISSUE TITLE
Not Acceptable on Delete / Rename but no file present

### ISSUE THREAD

**Issue by roger-gitter** [nextcloud/desktop#1411]
### Expected behaviour
file name disappears when file deleted
can not rename

### Actual behaviour
error message: "Not Acceptable" appears in black bar at bottom of droid app screen.
the names for two deleted files continue to appear, both with web interface and on the droid app. They do not appear in the Nextcloud folder on my Ubuntu Linux PC.

### Steps to reproduce
1. Try to delete
2. The error always occurs. the file names stay behind
3. Tried renaming file - same error.
Note that I see no errors in the error log on my server and the files are not present on server or elsewhere.

### Client configuration
Client version: Desktop: 15.0.7  /  Android 3.7.2  /  Linux version 2.3.3 (build 1)

Operating system: Linux and Android

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /usr/bin/nextcloud  (Linux)

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):
[owncloudsync (copy).log](https://github.com/nextcloud/desktop/files/3592732/owncloudsync.copy.log)

/Roger

**Comment by camilasan** [comment]
Hi @roger-gitter! Is this a problem you found in the Android app? 
What do you mean with "the names for two deleted files continue to appear"? You can't delete files in your Android device? The desktop client doesn't have control over your files in your syncing folder. 

And you are using an outdated version of the desktop client. We have a much newer version released (2.5.3)  and a RC for 2.6. Please, try it: https://github.com/nextcloud/desktop/releases/

cc @tobiasKaminsky

**Comment by roger-gitter** [comment]
Hi, Carrie.

I am leaving on a trip so I can not update right now. BUT, I think you missed 
the point! The files do not exist on any platform: PC, cloud server, or my 
Droid. It is the FILE NAMES that linger. I can not get rid of them. Please 
re-read my submission.

Thanks for looking at this. I will be away and largely disconnected from the 
Internet for 17 days.

--
Roger W. Broseus - Linux User
     Email: RogerB@bronord.com
     Web Site: www.bronord.com

**Comment by camilasan** [comment]
Hi John ;) 

were those files shared with you by another user? That would explain why you can not get rid of them or how they showed up. You might not have permission to delete it.

**Comment by roger-gitter** [comment]
No. No sharing. Only renamed. I repeat: no files present. Just names.

-- Roger Broseus
Pls excuse auto-correction induzed tiepos.

-----Original Message-----

**Comment by camilasan** [comment]
In this case we can try to look in the logs of the client:
```
Client logfile: Output of nextcloud --logwindow or nextcloud --logfile log.txt
(On Windows using cmd.exe, you might need to first cd into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
```
