### ISSUE TITLE
conflict detection seems to be broken

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#1416]
### Expected behaviour

- conflicts should be detected **correctly**
- Once the conflicts have been fixed on the filesystem, this should **also** be detected and synchronisation should commence properly.

### Actual behaviour

- client detects a conflict
- user fixes the conflict
- client still detects the conflict even when the aconflicting files had been removed
- synchronisation is stopped until user restarts the nextcloud client

### Steps to reproduce

1. synchronize something where files get written A LOT
2. wait until synchronisation shows a conflict for a file
3. manually fix the conflict, for example by deleting the conflicting file on your local disk
4. force synchronisation for the folder that it happened in
5. observe the client still showing that conflict even though those files are gone

### Client configuration
Client version:
any client version since 2.5.x

Operating system:
Linux, Windows

OS language:
english, german

Qt version used by client package (Linux only, see also Settings dialog):
there is no QT version info in the settings dialog?

Client package (From Nextcloud or distro) (Linux only):
several different: distro, self-built, official from nextcloud, daily builds from nextcloud

Installation path of client:
on linux: /usr
on windows: the default c:\program files

### Server configuration

Nextcloud version:
16.0.4

### Logs

1. Client logfile:
for some reason I can never get any client logfiles...

2. Web server error log:
no errors on the webserver

3. Server logfile: nextcloud log (data/nextcloud.log):
nothing special to see in there either

### my thought:

how finegrained are timestamps stored within nextcloud?
in my case the folders that keep having these conflicts are my thunderbird profile, and a folder structure where I'm keeping chat logs. Both change a lot, so maybe what happens is that a file gets synced into my cloud, then changed locally within the same second - and then we have two different versions of the file with the same timestamp, and **boom**, conflict.

**Comment by camilasan** [comment]
#1628

**Comment by mgallien** [comment]
Can you please test again with the latest version. That should have been fixed.
