### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by chummumm** [nextcloud/desktop#1421]
### Expected behaviour
Tell us what should happen
Login
### Actual behaviour
Tell us what happens instead
After I typed in my address it shows that I have to chose a TLS certification manually.
### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:
win10
OS language:
Chinese
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

D://Program Files//NEXTCLOUD
### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
We have improved the login flow in the release candidate for 2.6: https://download.nextcloud.com/desktop/prereleases/Windows/nextcloud-2.6.0.5818-rc1-20190907.exe

Please, try it and let us know if you still have this issue.

**Comment by misch7** [comment]
Please try our recent 2.6 release and re-open this ticket if the problem still persists with it:
https://nextcloud.com/install/#install-clients

In 2.6 we've implemented client SSL certificates and TLS 1.3 which might be the cause of your login issue.
