### ISSUE TITLE
Virtual drive tech preview v2 - dokan1.dll not found

### ISSUE THREAD

**Issue by tomdereub** [nextcloud/desktop#1423]
# Expected behaviour
I installed the virtual drive tech preview V2 on windows 10, and want to launch it.

### Actual behaviour
When I launch nextcloud, I get this error message: "Impossible d'exécuter le code, car dokan1.dll est introuvable. La réinstallation du programme peut corriger ce problème."

### Steps to reproduce
1. Install on Windows 10 and try

### Client configuration
Client version: Virtual drive tech preview V2

Operating system: Windows 10

OS language: French

Installation path of client: default

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
