### ISSUE TITLE
Icons sometimes broken with V. 2.7.0-dailiy (x64) (20190917)

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/desktop#1424]
### Expected behaviour
Nextcloud icon, folder icon and file icon should be displayed in Windows-Explorer

### Actual behaviour
Folder and file icon are shown as a "blank page" icon and Nextcloud icon is overlayed by a blank page icon

### Steps to reproduce
1. Install nextcloud-2.7.0.5829-daily-20190917-Release.exe
2. Start Nextcloud-Client

### Client configuration
Client version: nextcloud-2.7.0.5829-daily-20190917-Release.exe

Operating system: Windows 10 Pro (1803)

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.12.4, OpenSSL 1.1.1c 28 May 2019

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 14.0.14

**Comment by DominiqueFuchs** [comment]
Hi @blu-IT ,
are you talking about the overlay icons for the folder/file icons only, or do you experience the same issue with the sidebar integration (navigation pane on the left side in Windows explorer), systray, etc.?

**Comment by blu-IT** [comment]
Hi,

I had this problem also in the sidebar in Windows Explorer.
But after a restart of the computer until now I did not expierence the issue any more.

Regards



Am 19. September 2019 13:43:51 MESZ schrieb Dominique Fuchs <notifications@github.com>:
>Hi @blu-IT ,
>are you talking about the overlay icons for the folder/file icons only,
>or do you experience the same issue with the sidebar integration
>(navigation pane on the left side in Windows explorer), systray, etc.?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/desktop/issues/1424#issuecomment-533092859

-- 
Diese Nachricht wurde von einem mobilen Gerät versendet.
