### ISSUE TITLE
Connection timed out for open MS word documents

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/desktop#1426]
Hi

I'm getting a error message showing "connection timed out" for the word (docx) documents that are open.
I believe that this behavior is knew. It's an issue or the end user (me) needs to do something so that the file is synced even while open.

thanks

Win7, MS office 2010 and latest stable NC client.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Could you please try with the latest version of the Nextcloud Desktop client ?

If I understand correctly, you are getting an error message when you are editing a Word document in a folder shared via Nextcloud ?
