### ISSUE TITLE
Nextcloud Client don´t sync Files that are larger then ~20MB

### ISSUE THREAD

**Issue by Der-Daniel-ist-da** [nextcloud/desktop#1428]
I have the latest Version, Server: Version: 16.0.4.1
Client 2.5.3

The upload from the Webbroser is o.K., the Client sync the Files local to my Computer too.
But the Client does not upload the bigger files.

<details><summary>Log File</summary>
<p>
OCC::SyncEngine::slotDiscoveryJobFinished 	#### Discovery end ####################################################  353 ms
[OCC::ActivityListModel::removeActivityFromActivityList 	Activity/Notification/Error successfully dismissed:  "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/2522388838/00000001 - server replied:  (übersprungen aufgrund des früheren Fehlers, erneuter Versuch in 24 Stunden)"
[OCC::ActivityListModel::removeActivityFromActivityList 	Trying to remove Activity/Notification/Error from view... 
[OCC::ActivityListModel::removeActivityFromActivityList 	Activity/Notification/Error successfully removed from the list.
[OCC::ActivityListModel::removeActivityFromActivityList 	Updating Activity/Notification/Error view.
[_csync_merge_algorithm_visitor 	INSTRUCTION_UPDATE_METADATA    client dir:  Daniel
[_csync_merge_algorithm_visitor 	INSTRUCTION_NEW                client file: Daniel/windowsfullage.exe
[csync_reconcile 	Reconciliation for local replica took  0.002 seconds visiting  4811  files.
[csync_reconcile 	Reconciliation for remote replica took  0.001 seconds visiting  4810  files.
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Reconcile end ####################################################  360 ms
[OCC::SyncEngine::slotDiscoveryJobFinished 	Permissions of the root folder:  "DNVCKR"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:OK:C:\\Users\\myname\\Nextcloud\\Daniel" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullage.exe" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullage.exe" to QLocalSocket(0x1fab2d23280)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:C:\\Users\\myname\\Nextcloud\\Daniel" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:NOP:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullagent.exe" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:NOP:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullagent.exe" to QLocalSocket(0x1fab2d23280)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:C:\\Users\\myname\\Nextcloud\\Daniel" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:NOP:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullagent.exe" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:NOP:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullagent.exe" to QLocalSocket(0x1fab2d23280)
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Post-Reconcile end ####################################################  392 ms
[OCC::Folder::slotSyncStarted 	#### Propagation start ####################################################
[OCC::SocketApi::slotUpdateFolderView 	Not sending UPDATE_VIEW for "1" because status() is 3
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://cloud.company.de/remote.php/dav/files/myname/" :  "Sync Running"
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_NEW propagation of "Daniel/windowsfullage.exe" by OCC::PropagateUploadFileNG(0x1fab2eb1fe0)
[OCC::PropagateUploadFileCommon::startUploadFile 	Running the compute checksum
[OCC::PropagateUploadFileCommon::slotComputeContentChecksum 	Tryint to compute the checksum of the file
[OCC::PropagateUploadFileCommon::slotComputeContentChecksum 	Still trying to understand if this is the local file or the uploaded one
[OCC::ComputeChecksum::start 	Computing "SHA1" checksum of "C:/Users/myname/Nextcloud/Daniel/windowsfullage.exe" in a thread
[OCC::ComputeChecksum::start 	Computing "" checksum of "C:/Users/myname/Nextcloud/Daniel/windowsfullage.exe" in a thread
[OCC::AccessManager::createRequest 	6 "MKCOL" "https://cloud.company.de/remote.php/dav/uploads/myname/418832298" has X-Request-ID "6fd462e0-ced9-4862-8a90-7e19cad50b2d"
[OCC::AbstractNetworkJob::start 	OCC::MkColJob created for "https://cloud.company.de" + "" "OCC::PropagateUploadFileNG"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::MkColJob::finished 	MKCOL of QUrl("https://cloud.company.de/remote.php/dav/uploads/myname/418832298") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	3 "" "https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000000" has X-Request-ID "63ff682c-3310-4219-b672-c3ee56cb6b74"
[OCC::AbstractNetworkJob::start 	OCC::PUTFileJob created for "https://cloud.company.de" + "" "OCC::PropagateUploadFileNG"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PUTFileJob::finished 	PUT of "https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000000" FINISHED WITH STATUS "OK" QVariant(int, 201) QVariant(QString, "")
[OCC::PropagateUploadFileNG::slotPutFinished 	Chunked upload of 10000000 bytes took 431 ms, desired is 60000 ms, expected good chunk size is 1392111368 bytes and nudged next chunk size to  100000000 bytes
[OCC::AccessManager::createRequest 	3 "" "https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001" has X-Request-ID "da22c0a5-247c-457a-9a07-5079becceb05"
[OCC::AbstractNetworkJob::start 	OCC::PUTFileJob created for "https://cloud.company.de" + "" "OCC::PropagateUploadFileNG"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::UnknownContentError "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: " QVariant(int, 413)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownContentError
[OCC::WebFlowCredentials::stillValid 	"Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: "
[OCC::PUTFileJob::finished 	PUT of "https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001" FINISHED WITH STATUS "UnknownContentError Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: " QVariant(int, 413) QVariant(QString, "")
[OCC::createBlacklistEntry 	Fatal Error condition 413 , maximum blacklist ignore time!
[OCC::SyncJournalDb::setErrorBlacklistEntry 	Setting blacklist entry for  "Daniel/windowsfullage.exe" 1 "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: " 1568791372 86400 1566539386 "" "" 0
[OCC::PropagateItemJob::done 	Could not complete propagation of "Daniel/windowsfullage.exe" by OCC::PropagateUploadFileNG(0x1fab2eb1fe0) with status 2 and error: "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: "
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:C:\\Users\\myname\\Nextcloud\\Daniel" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:ERROR:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullage.exe" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:ERROR:C:\\Users\\myname\\Nextcloud\\Daniel\\windowsfullage.exe" to QLocalSocket(0x1fab2d23280)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:C:\\Users\\myname\\Nextcloud\\Daniel" to QLocalSocket(0x1faae81d090)
[OCC::ActivityWidget::slotItemCompleted 	Item  "Daniel/windowsfullage.exe"  retrieved resulted in  "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: "
[OCC::ActivityWidget::slotItemCompleted 	Item  "Daniel/windowsfullage.exe"  retrieved resulted in error  "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: "
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Error transferring https://cloud.company.de/remote.php/dav/uploads/myname/418832298/00000001 - server replied: "
[OCC::SyncJournalDb::close 	Closing DB "C:/Users/myname/Nextcloud/._sync_2f0af8ee15a3.db"
[OCC::SyncEngine::finalize 	CSync run took  2514 ms
[OCC::Folder::slotSyncFinished 	Client version 2.5.3daily-Win64 (build 20190725)  Qt 5.12.3  SSL  OpenSSL 1.0.2s  28 May 2019
[OCC::Folder::slotSyncFinished 	SyncEngine finished with ERROR
[OCC::Folder::showSyncResultPopup 	Folder sync result:  3
[OCC::Folder::slotSyncFinished 	the last 1 syncs failed
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\myname\\Nextcloud" to QLocalSocket(0x1faae820830)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\myname\\Nextcloud" to QLocalSocket(0x1faae81d090)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\myname\\Nextcloud" to QLocalSocket(0x1fab2d23280)
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://cloud.company.de/remote.php/dav/files/myname/" :  "Error"
[OCC::FolderMan::slotFolderSyncFinished 	<========== Sync finished for folder [Nextcloud] of account [myname@cloud.company.de] with remote [https://cloud.company.de/remote.php/dav/files/myname/]
</p>
</details>

**Comment by enoch85** [comment]
@Der-Daniel-ist-da Just to confirm: Did you enable some of the extra security settings in the VM?

**Comment by Der-Daniel-ist-da** [comment]
No extra security settings :(
I will try the old Client, because the other users can upload big files.

**Comment by Der-Daniel-ist-da** [comment]
I install the Client Version 2.3.3 and it works. I think the Problem is solved.
Thanks

**Comment by camilasan** [comment]
I think we still need to figure this out. 2.3.3 has an outdated OpenSSL.

**Comment by papjul** [comment]
I think it is a duplicate of #1171. This may also be a duplicate of #1182 (I'm still testing, will post my results later).
Since #1171 was opened, various fixes were released on Qt side and on Owncloud Client side, that's why people switched to Owncloud Client.

**Comment by Der-Daniel-ist-da** [comment]
i also try 2.6, same problem there

**Comment by gacpac** [comment]
Ohh So I'm crazy!

I've been pulling my hair for months!! the application only works uploading for 2.3.3 any other app won't work. Haven't tried the Beta though
