### ISSUE TITLE
The client is either slow at syncing, or doesn't sync (e.g. group folders), despite updates showing in desktop client. Client changes sync immediately though

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [nextcloud/desktop#1430]
### Expected behaviour
Upon creating/editing/etc a file on either the web client or another client, then the other clients should immediately (or within a few seconds) sync to the latest edits.

### Actual behaviour
The clients either take a while to sync or never sync until either forced or a local file in the NextCloud folder is updated. Here's a full explanation:

I have a few users setup and about 40GB of files in a group folder that's shared between them. I also have a few user folders setup amounting to about 50MB. I have the Windows client setup on a few computers, set to sync everything. The "confirm for files over 500MB" and "confirm for external storage" are unticked.

When I make changes on the web interface the client either takes about 30 seconds to a minute to update, or simply doesn't. I am not sure if this is related to the group folder of it it's just random. For example the following:

- A folder called "Business Admin" in the root of the user, it syncs files made in it in about 30 seconds.
- A folder called "Caerphilly Observer", a group folder in the root. File changes in here never automatically sync.
- Another folder called "CO" in the root of the user, sometimes files do sync here, sometimes they don't, again about 30-60 seconds. This folder isn't any bigger than the "Business Admin" one.
- Any files created in the root of the user sync in about 30 seconds.

What's more confusing is that if I create e.g. a new folder in "Caerphilly Observer", then it will appear in the little synced folders list on the desktop client, but it still won't update the actual files or folders.

All of these will sync just fine (and quickly) if I click force sync. They will also all sync if I somehow update the NextCloud folder. For example if I create or edit a file in the "Caerphilly Observer" folder then it will immediately sync that to the server, it will also then immediately sync everything else that has changed from the server.

I have tried using both the NextCloud desktop client as well as the ownCloud client, both have the same issues leading me to believe that it's potentially an issue with the server?

### Steps to reproduce
1. Obtain Windows client and sync a user with a group folder and local files
2. Edit the files in the group folder or local folder
3. Takes a while to sync or never does

### Client configuration
Client version: Tried 2.3, 2.5, 2.7, and ownCloud 2.5, 2.6

Operating system: Windows

OS language: English

### Server configuration

Nextcloud version: Nextcloud 16

Storage backend (external storage): I have simply moved the default storage to an iSCSI drive from FreeNAS.

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: [nc.log](https://github.com/nextcloud/desktop/files/3632117/nc.log)

2. Web server error log: [error.log](https://github.com/nextcloud/desktop/files/3632147/error.log) [error_2.log](https://github.com/nextcloud/desktop/files/3632148/error_2.log) (more if needed)

3. Server logfile: [nextcloud.log](https://github.com/nextcloud/desktop/files/3632150/nextcloud.log)

**Comment by patricksebastien** [comment]
Having this major issue too. My users complains that the Windows desktop client is not syncing anymore since my update (from NextCloud 15 to NextCloud 16). The **Mac client works** (doesn't have this important bug).

Tried with 2.3.3.1 and official version + v2.6.0-rc1 = all not syncing automatically.

Nextcloud: 16.0.4
Groupfolder: 4.1.0

Not sure if the bug is in the desktop client, nextcloud or groupfolder? Someone could investigate so that we know if we need to open an issue on nextcloud or groupfolder?

If it's in the client, is there a version with a force sync called every 30 sec? That would be a life saver while waiting for a fix.

**Comment by CaerphillyMediaLtd** [comment]
> Having this major issue too. My users complains that the Windows desktop client is not syncing anymore since my update (from NextCloud 15 to NextCloud 16). The **Mac client works**.

Strange, I tried the Linux client and it didn't seem to work.

> Tried with 2.3.3.1 and official version + v2.6.0-rc1 = all not syncing automatically.
> 
> Nextcloud: 16.0.4
> Groupfolder: 4.1.0
> 
> Not sure if the bug is in the desktop client, nextcloud or groupfolder? Someone could investigate so that we know if we need to open an issue on nextcloud or groupfolder?

I came to the conclusion that it's likely not the plugin. Syncs outside of the group folder are generally slow, and I've also found that some folders outside of the group folders also just seem to refuse to ever sync automatically. It seems random but consistent which folders will and won't automatically sync.

> If it's in the client, is there a version with a force sync called every 30 sec? That would be a life saver while waiting for a fix.

Not that I'm aware of. I wrote a little python Windows service to just write to a file in the NextCloud directory every X seconds. You need the pywin32 package, and you can install the service via "python run.py install".

It accepts arguments (in order of preference) first from the custom argument box when starting a service manually from services.msc, then from the command line (so you can edit how it's called in the registry if you like), then from the defaults at the top of the file. It should do anyway, I ended up just setting them in the file since it was easier. The arguments are in the order they appear at the top of the file, that is [update file location], [update time in seconds], [time to wait after an error], [whether to hide the file (make sure you enable uploading hidden files if you set it to true].

It's not a very elegant solution, but it doesn't slow the system down and works very quickly (tested it with a ~40GB group folder). If you don't want that extra file being synced (it is kind of ugly), you could modify it to update some file system information on another existing file. All you have to do to trigger an update is cause any sort of file update on a synced file in the sync directory. There might even be a windows call to just update the folder, but I don't want to bother spending much time on an ugly fix I hope I won't be using for too long.

https://gist.github.com/CaerphillyMediaLtd/769597c61c9d1551bd7dbb993faa8c42

**Comment by patricksebastien** [comment]
Thanks for the script, I think I will compile my own version of the desktop client and call the force sync every 30 seconds or so. Hopefully this will be fix soon.

**Comment by CaerphillyMediaLtd** [comment]
Nice, that is a better solution, I didn't go that route because it'd take longer to setup, test, etc. But when you do do it, please do share it here.

**Comment by misch7** [comment]
Did you also try our 2.6.0 release build?

https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.6.0-setup.exe

We've upgraded to Qt 5.12.5 for this build and it solved a lot of issues (UI + crashes) caused by the previous version 5.12.4.

(RC1 did not contain this upgrade.)

**Comment by CaerphillyMediaLtd** [comment]
Yes it behaves the same. As @patricksebastien pointed out, it seems to have appeared in server version 16.

**Comment by HorstBort** [comment]
I'm experiencing the same issue.

NC Server 22.2.3
Groupfolders 10.0.0
Desktop Client: 3.4.0 (Windows and Ubuntu)

Is there any way to force a sync periodically as a quick workaround?

**Comment by HorstBort** [comment]
Update: Running `occ groupfolders:scan $my_folder_id` immediately triggers a sync.
