### ISSUE TITLE
l10n: Remove string from Transifex resource

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#1431]
https://github.com/nextcloud/desktop/blob/1138118d8e9f830cf729961d46d5ca35c7493727/src/gui/ignorelisttablewidget.ui#L14

"IgnoreListTableWidget" should not be translated, or?

**Comment by DominiqueFuchs** [comment]
Thanks for the hint! Resolved by pending PR #1441

**Comment by misch7** [comment]
PR https://github.com/nextcloud/desktop/pull/1441 merged :-)
