### ISSUE TITLE
Virtual Drive Preview v2 Partially Successful on Windows 10 Pro v1903

### ISSUE THREAD

**Issue by kismetgerald** [nextcloud/desktop#1432]
### Hello folks,

I too have tried to test v2 of the Virtual Drive preview client, but my installation - though successful (_somewhat_) - yielded no fruitful results. In summary, the Dokan install appears to have been partial (_explained below_), and the Nextcloud client fails to connect to my server (_citing a TLS handshake error_).

### This is my PC environment:

![Snap 2019-09-20 at 00 08 01](https://user-images.githubusercontent.com/14914151/65334853-4708a300-db91-11e9-84ee-3c37ef88af2f.png)

### Dokan Installation Error
This appears after clicking the **“Finish”** button for the Dokan installer. For all intents and purposes, it appears the installation is successful (_as I can see it listed in Programs and Features_), yet still this error pops up right after you click “Finish”.

![Snap 2019-09-19 at 23 28 12](https://user-images.githubusercontent.com/14914151/65334976-80411300-db91-11e9-8933-e6134038cc80.png)

### Nextcloud Desktop Client Stuck in Waiting State
After rebooting the PC (_following the Dokan installation_), the Nextcloud desktop client still remains in a “_waiting to start sync state_”. With v1 of the preview build, it shows no errors. With v2, it shows “_TLS handshake failed_”.

![Snap 2019-09-19 at 23 40 46](https://user-images.githubusercontent.com/14914151/65335047-ae265780-db91-11e9-8b12-949aeb0e858e.png)

### Exit button hides below taskbar
Finally, I noticed that when you right-click on the taskbar icon the **“Exit”** button immediately sinks below the taskbar - making it difficult to quit the client.

![Snap 2019-09-19 at 23 46 56](https://user-images.githubusercontent.com/14914151/65335111-cf874380-db91-11e9-8095-255520490459.png)

Hope you guys are able to resolve the problems above so I can test. I like the idea of the Virtual Drive, but hope that it functions in the same way as Dropbox currently functions.

**Comment by Frank360ict** [comment]
Exactly the same happende to my installation. Got the very same Windwows warning and could not finish the install wizard. After restarting my system the Client could not sync. Warning: TLS initialization failed. System:
![pastedImage](https://user-images.githubusercontent.com/55845085/65705088-05439500-e088-11e9-9537-bc9ad5d7cedc.png)
 Windows 10 Home v1903

**Comment by warnerbryce** [comment]
For your problem @Frank360ict you have to verify in your Nextcloud server if T.L.S 1.3 is ON. 
The Tech V2 preview accept only this new protocol. 
It's a shame they should do a T.L.S. 1.2 and 1.3 compatibility.

**Comment by mr-manuel** [comment]
Hello,
I have the same problem. My server doesn't accept the TLS 1.3 version. Is there any chance that TLS 1.2 will be supported, maybe with an extra flag in the settings?

**Comment by Frank360ict** [comment]
> For your problem @Frank360ict you have to verify in your Nextcloud server if T.L.S 1.3 is ON.
> The Tech V2 preview accept only this new protocol.
> It's a shame they should do a T.L.S. 1.2 and 1.3 compatibility.

Sorry for the late response, but TLS 1.3 is on and yet I still have the same problems. Still I get the windows warning while doing a clean install and after opening Nextcloud client I still get the warning TLS initialization failed....

**Comment by dverzolla** [comment]
@kismetgerald @Frank360ict 
Did you guys have success using nextCloud + Dokan for virtual file system?

**Comment by Frank360ict** [comment]
Hi David,
No I did not succeed. I’m now testing the owncloud client for virtual file system, which so far seem to be working fine with nextcloud.

Regards,
Frank

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
