### ISSUE TITLE
windows client fails to redraw on "un-minimize", then crashes when you try to interact with the UI after forcing a redraw

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#1436]
### Expected behaviour
"it should not crash". Sorry, can't put it any better than this.

### Actual behaviour
the client crashes

### Steps to reproduce
1. Run the client minimized in the windows tray
2. Get the window to show
3. Observe the window to actually be completely blank until you resize it to force a redraw
4. switch to the activity tab
5. try to scroll the content of the activity tab using yoiur mousewheel
6. client locks up for a few seconds, then crashes

### Client configuration
Client version:
Daily build of september 20, 2019

Operating system:
Windows 10

OS language:
German

Installation path of client:
C:\Program Files (X86)\nextcloud

### Logs
1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

No client logfile for the latest crash - I am running the client with --logdir and --logexpire but that seems to get ignored by the instance that gets autostarted by windows.

### Notes
The crash fix for the linux client mentioned in #1382 does not have any influence on this.

**Comment by lemmy04** [comment]
detail:

the crash happens reproducibly whenever the window faield to populate after getting it back from the tray, and *that* in turn needs the client to have been running for maybe 10-15 minutes to happen.

**Comment by lemmy04** [comment]
the same "crash when scrolling" just happened even with the main window properly redrawn after un-minimize.
For reasons beyond my understanding the client has stopped logging completely, even though I *am* running it with --logdir d:\......

**Comment by lemmy04** [comment]
here is the most current client log:
https://pastebin.com/em3jZT22

**Comment by lemmy04** [comment]
and here's another log from a similar crash:
https://pastebin.com/2g8544mR

**Comment by lemmy04** [comment]
annoying detail: when you enable "start with windows" in the client you get a running instance that does not have any --logdir or --logexpire options even though you have set those on the entry in windows start menu.
workaround: disable "start with windows" in the client, then place a copy of the start menu entry (or a link to it) in the startup folder. hint: enter shell:startup in the filemanager address bar.

**Comment by misch7** [comment]
@lemmy04 Thanks for pointing out to this.

The redraw issue (a.k.a. white window issue) has been fixed (#1445), this will get into the 2.6 release.

I'm still investigating the crash.

**Comment by lemmy04** [comment]
So in the latest daily builds this should be fixed now? Gotta try, will report.

**Comment by lemmy04** [comment]
redraw is fixed in 2.6.0 on windows
