### ISSUE TITLE
Activity windows is confusing if there are many ignored files

### ISSUE THREAD

**Issue by bjoernv** [nextcloud/desktop#1437]
### Expected behaviour
The activity window should show only real activity, e.g. new, updated and removed files. The user expects activities like in the activity tab of the NC web application.

### Actual behaviour
If many files and directories are ignored (setup with "Edit ignored files" or with ignored directories in the tree view) the NC client activity tab shows so much messages about ignored files, that it is difficult and time consuming to find the real activity. The issue was introduced between Nextcloud 2.3.3 and 2.5.0

### Steps to reproduce
1. Create a directory with files with ending .tmp
2. Go to "Edit ignored files" and create an entry for *.tmp
3. Create a sub-directory with some files
4. Exclude this sub-directory in tree view 
5. Start synchronization
6. Update some of the *.tmp files and files in the sub-directory
7. Go to activity tab

### Client configuration
Client version:
2.5.3
(Nextcloud version 2.5.3git
Git revision 477614b8c954836327eb136be1c035627f09760b
Using Qt 5.13.1, built against Qt 5.13.1
Using 'OpenSSL 1.1.1c  28 May 2019')

Operating system:
openSUSE Tumbleweed 20190921

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.13.1

Client package (From Nextcloud or distro) (Linux only):
network / openSUSE_Tumbleweed

Installation path of client:
/usr/bin/nextcloud

### Server configuration
Nextcloud version:
14.0.14
(also tested with 15.0.11)

Storage backend (external storage):
no

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(this is too much data, mostly private)
The activity windows shows messages like

```Ignored because of the "choose what to sync" blacklist
    my-directory/my-subdirectory
    
    (!) my-directory/file1.tmp
    now
    
    (!) my-directory/file2.tmp
    now

    (!) is the yellow icon with a "!"```

**Comment by Orbital-Bit** [comment]
it would be very helpful to filter the activity window, 
an ability to focus on one type of event when needed.

**Comment by camilasan** [comment]
PR #1523 fixes it.
