### ISSUE TITLE
Disable specific type of notification and alerts

### ISSUE THREAD

**Issue by Mte90** [nextcloud/desktop#1440]
### Expected behaviour
Disable the kind of notification like file not uploaded because ignored or connection expired.

### Actual behaviour
I am getting all the notifications...

**Comment by bjoernv** [comment]
This is related to #1437.

**Comment by camilasan** [comment]
PR fixes it partially #1523

**Comment by ilippert** [comment]
This feature might include, if I understand the intend well, that the user could be allowed, similar to https://github.com/nextcloud/android/issues/3855, to signal "OK I know, don't remind anymore" for notifications about updateable client version.

In my case, I use nextcloud coming from Fedora repos and it takes a while until client updates get into the repo. Right now every time I log in and my nextcloud client starts, I am shown the notification that the client is outdated. I know that; would be great if I can I tell the app that.

I do not want to hijack this feature-request; please let me know if this does not fit here.

**Comment by jospoortvliet** [comment]
@ilippert that is indeed something else - I believe the devs of the Fedora package can disable this check when building the client, but I'm no super expert on this.

**Comment by jospoortvliet** [comment]
wrt the original issue - I think the better solution is to make alerts better and smarter, not add configuration. As this is already quite an old issue and we made many improvements I'll close this now...
