### ISSUE TITLE
nextcloud windows client 2.5.3 and 2.6.0 when start as in remote desktop session will CANNOT start 

### ISSUE THREAD

**Issue by ericohao** [nextcloud/desktop#1448]
### Expected behaviour
Normal Start

### Actual behaviour
with a MessageBox say :"Error: LoadLibrary failed with error 87:The parameter is incorrect."

### Steps to reproduce
1.Normal Success Install nextcloud windows client 2.5.3(2.5.2).
2.Restart the computer without login.
3.On another computer remote desktop connect the computer and login,and click to start nextcloud windows client.

### Client configuration
Client version:2.5.3

Operating system:
Windows 10
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by misch7** [comment]
There is a new release 2.6.0, just published on Friday:
https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.6.0-setup.exe

Downloads for all platforms:
https://github.com/nextcloud/desktop/releases/tag/v2.6.0

Could you give it a try and get back here with the results? ;-)

**Comment by ericohao** [comment]
Thank you every much.I tested.But , still the same. Thanks a lot .

**Comment by delumerlino** [comment]
Same here. Follow discussion

**Comment by t-b-x** [comment]
Subscribe for 2.6.0 when using Remote Desktop, than error occurs. When using e.g. Teamviewer, Client starts normally.

**Comment by nanaya** [comment]
Same error on fresh windows 10 install using remote desktop. Nextcloud client version 2.6.2.

**Comment by uwedisch** [comment]
Filename is: atig6pxx.dll

It's located in Windows directory.

**Comment by m4t7e0** [comment]
Same issue:
2.6.2stable-Win64 (build 20191224) running on Windows 10 1909, if i open nextcloud via Microsoft RDP i get "Error: LoadLibrary failed with error 87:The parameter is incorrect.". if i'm running on desktop i can run it and than without close the session i can use the rdp.
Looks like a rdp compatibility bug

**Comment by Volker-K** [comment]
Same here. Client works when started from local session, then you can even connect via RDP and it's ok. Startet from an RDP it crashes.

**Comment by Plattenthaler** [comment]
Same here. Exact the same as Volker-K described.

**Comment by thehijacker** [comment]
Same issue for me. I work from home and need RDP connection over VPN to my work computer. From time to time I need to reboot it. When I login over RDP the Nextcloud client will not start with that exact name. If I reboot and login from behind computer the client will start. Any solution for this?

**Comment by ericohao** [comment]
On Windows 10: If running this app over a remote desktop and you have an AMD/ATI card, simply disable the real graphics card in Device Manager and restart the application (not the computer).  [https://github.com/alacritty/alacritty/issues/1976](url)

**Comment by Volker-K** [comment]
> On Windows 10: If running this app over a remote desktop and you have an AMD/ATI card, simply disable the real graphics card in Device Manager and restart the application (not the computer). [https://github.com/alacritty/alacritty/issues/1976](url)

That's one way.
I've tried setting
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services]
"bEnumerateHWBeforeSW"=dword:00000001

It worked.

**Comment by ericohao** [comment]
Thanks. I think it is a problem of QT , several other application with QT in remote desktop session report the same message and cannot load , for example OpenSCAD. @Volker-K

**Comment by Volker-K** [comment]
@ericohao It's a problem of QT caused by a misspelled dll-name insinde the registry. So lots of Nividia drivers for AMD/ATI systems will cause this error. QT tries something that should normally work and obviously does with other graphics cards.

**Comment by tkafka** [comment]
Here seems to be  the relevant QT bug: https://bugreports.qt.io/browse/QTBUG-50371?focusedCommentId=329417&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel

**Comment by peeter123** [comment]
I found a workaround by placing opengl32.dll from the MESA windows builds (https://github.com/pal1000/mesa-dist-win/releases/) in the Nextcloud installation directory.
