### ISSUE TITLE
nextcloud-client: OCC::PropagatorCompositeJob::scheduleSelfOrChild(): nextcloud killed by SIGSEGV

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#1450]
Fedora/RHEL/CentOS nextcloud-client maintainer here. I am getting a tons of user bugreports about the following crash, even on 2.5.3

Version-Release number of selected component:
nextcloud-client-2.5.2-2.fc30

Additional info:
reporter:       libreport-2.10.0
backtrace_rating: 4
cmdline:        /usr/bin/nextcloud
crash_function: OCC::PropagatorCompositeJob::scheduleSelfOrChild
executable:     /usr/bin/nextcloud
journald_cursor: s=0dbcc102fbf242c3b0a94abe00b9c18d;i=da0fd;b=9d61131853bb4941b2e3f435d706e47c;m=335c24452;t=58b5e5e2e5c5d;x=1df72eede116fa13
kernel:         5.1.8-300.fc30.x86_64
rootdir:        /
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (10 frames)
 #0 OCC::PropagatorCompositeJob::scheduleSelfOrChild at /usr/include/qt5/QtCore/qarraydata.h:211
 #1 OCC::PropagateDirectory::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:921
 #2 OCC::PropagatorCompositeJob::possiblyRunNextJob at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.h:274
 #3 OCC::PropagatorCompositeJob::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:783
 #4 OCC::PropagateDirectory::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:921
 #5 OCC::PropagatorCompositeJob::possiblyRunNextJob at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.h:274
 #6 OCC::PropagatorCompositeJob::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:783
 #7 OCC::PropagateDirectory::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:921
 #8 OCC::PropagatorCompositeJob::possiblyRunNextJob at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.h:274
 #9 OCC::PropagatorCompositeJob::scheduleSelfOrChild at /usr/src/debug/nextcloud-client-2.5.2-2.fc30.x86_64/src/libsync/owncloudpropagator.cpp:783

Fedora bugreport https://bugzilla.redhat.com/show_bug.cgi?id=1720836

**Comment by mawasak** [comment]
Hi,
I think that this is the same as #1382.
I run about 20 test sessions and I get dump with PropagatorCompositeJob::slotSubJobFinished most the times. I get dump with PropagatorCompositeJob::scheduleSelfOrChild only three times. But in application log every time I get crash I had ASSERT warning in logs before crash (as described in fix to #1382).
When fix to #1382 is applied I am not able crash app using test cases which caused crash app earlier.

@Germano0 - logs are not attached by your users to check this ASSERT warning - but users can create logs as needed using options to nextcloud during start as:
--logflush --logdir /tmp/logs/ --logdebug
log files are write as gz files in logdir oprion.

**Comment by Germano0** [comment]
@mawasak 
> logs are not attached by your users to check this ASSERT warning - but users can create logs as needed using options to nextcloud during start as:
> --logflush --logdir /tmp/logs/ --logdebug
> log files are write as gz files in logdir oprion.

https://bugzilla.redhat.com/attachment.cgi?id=1621427

**Comment by mawasak** [comment]
Thanks for logs  @Germano0 
In logs there is line 

> [OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file /builddir/build/BUILD/desktop-2.5.3/src/libsync/owncloudpropagator.cpp, line 835

before crash so... this is as in #1382 case
