### ISSUE TITLE
Windows client crashes when scrolling in the activity tab

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#1455]
### Expected behaviour
"it should not crash"

### Actual behaviour
"it crashes"

### Steps to reproduce
1. un-minimize the client
2. switch to the activity tab
3. scroll with your mouisewheel, client crashes

### Client configuration
Version 2.7.0daily-Win64 (build 20190926).

Operating system:
Windows 10 Pro 1903

OS language:
German

Installation path of client:
c:\program files (x86)\nextcloud

### Logs
client logs show nothing special other than normal sync activity

Contrary to my previous belief it does seem to be a separate bug from #1436

**Comment by lemmy04** [comment]
I'm not 100% sure because it is very hard to reproduce - but it almost seems that the client crashes if you try to scroll the activity tab **while a sync is happening.**

**Comment by lemmy04** [comment]
on further trying - not. I've been scrolling just fine during syncs by now and had crashes in between.

**Comment by misch7** [comment]
👍 for the behaviour description - all has been said 😹 

Could you try our recent daily build:
https://download.nextcloud.com/desktop/daily/Windows/nextcloud-2.7.0.5839-daily-20190927-Release.exe

And also today's 2.6 release:
https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.6.0-setup.exe

I upgraded over night to Qt 5.12.5 and I really suspect the previous Qt 5.12.4 to cause the crash. (It also caused other issues like the "white window" issue, that has been solved by the Qt devs in .5).

Looking forward to your feedback :-)

**Comment by lemmy04** [comment]
I just installed the 2.6.0 client, lets see how it behaves.

**Comment by lemmy04** [comment]
2.6.0 client on windows seems to behave fine so far - no crashes and no sync conflicts anymore either. closing this for now.
