### ISSUE TITLE
Lose Folder in Windows

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/desktop#1463]
Hi, i have a shared folder from my other account. When i move this folder in Windows to another Location (in the Nextcloud folder), the shared link is missing and never Comes back. And when i check off the hook in the Windows GUI which folder will be synced, the folder will not be removed. I delete the Folder be myself and check on the hook, but the folder never comes back.

Sry for my bad english!

**Comment by FlexW** [comment]
Are you still affected by this issue with a recent version (3.2.1)? If yes, could you please explain more clearly what the problem is, and how it should work?
