### ISSUE TITLE
Nextcloud sync and override persistent local files on PC 

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/desktop#1468]
Hello,

I have setup my Netbook at Home with Windows 10. Then I copy all files from my old Desktop PC to the Netbook. 

Anyone an idea what’s wrong? 

The Folder called 

- Pictures
- Documents
- Video
- Music

After copying alle folder and files to the correct location at the netbook I installed the Nextcloud Sync Client. 

I setup the same syncfolder at the client and Nextcloud starts to sync.

**The issue:**

The client starts to sync and download all Files again to the Netbook! The Client seems to override the local files and folders.
No detection of persistent Data.

**Installation:**

- Nextcloud 17.0.0
- latest Nextcloud Sync Client (32bit)
- Ubuntu 18.04.3 LTS Server

**Netbook:**

- Windows 10 (32bit)

**Comment by FlexW** [comment]
This should not happen. Does this issue still persist in the most recent client (3.2.1)?

**Comment by Happyfeet01** [comment]
Not happen anymore.

Forgot to close it. Sorry
