### ISSUE TITLE
lack of file sharing menu space in Italian

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/desktop#1472]
According to the enclosure circled in red, in the last release of the application on 2 and 3 October the wording in the drop-down menu in Italian "Share TramiteNextcloud" lacks a space, it should exit "Share Via Nextcloud" with the space between the three words.

![Immagine](https://user-images.githubusercontent.com/35575744/66138787-7db5d300-e5ff-11e9-8e7c-2cf4a88b06a2.png)

**Comment by tigernero79** [comment]
news?

**Comment by jancborchardt** [comment]
The "Share via " at https://github.com/nextcloud/desktop/blob/04a9f0313a75d96a286b85002ca06bef3fa0a976/src/gui/socketapi.cpp#L626 should most likely have the space not as part of the translatable string as it could be missed by translators.

Marking as good first issue. Meanwhile this could be fixed specifically for Italian in the translations on Transifex: https://www.transifex.com/nextcloud/nextcloud/
