### ISSUE TITLE
Broken link to documentation of newest release

### ISSUE THREAD

**Issue by ModischFabrications** [nextcloud/desktop#1479]
The link to the documentation of the newest release (2.6) is broken.

### Expected behaviour
https://nextcloud.com/install/?pk_campaign=clientupdate#install-clients

Clicking on the "documentation" link should take you to the documentation.
![image](https://user-images.githubusercontent.com/25404728/66258793-b09bca80-e7a9-11e9-97c2-ad6f392b2b02.png)

https://docs.nextcloud.com/desktop/2.6

### Actual behaviour
The link leads to nowhere with the message "File not found."

![image](https://user-images.githubusercontent.com/25404728/66258806-d0cb8980-e7a9-11e9-9c21-628ead4b7a8e.png)

### Steps to reproduce
1. "Get Update" with Nextcloud Desktop
2. Click link "Documentation

### Client configuration
Version 2.5.3daily-Win64 (build 20190725)

Operating system:
Windows

OS language:
English

**Comment by misch7** [comment]
Thanks for reporting! 👍 

We're already aware of it and I filed a pull request to fix this. It will be fixed next week ;-)

https://github.com/nextcloud/nextcloud.com/pull/1166

In the meantime in case you need it, here's the correct link:
https://docs.nextcloud.com/desktop/2.5/
