### ISSUE TITLE
MacOS Finder Extension not working any more

### ISSUE THREAD

**Issue by djquazzi** [nextcloud/desktop#148]
**Steps to reproduce**

Disabled / re-enabled extension in System Preferences
Reinstalled MacOS app
Restarted machine

**Expected behaviour**

Right clinking a file in the Finder displays Nextcloud options (Sharing)

**Actual behaviour**

Nextcloud options do not appear.

Found in log:

_Jan 31 08:55:27 daniel com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.1440[334]): Service exited due to signal: Terminated: 15 sent by killall[706]_

MacOS High Sierra 10.13.3
MacOS Nextcloud desktop app v. 2.3.3 (build 84)

**Comment by DominiqueFuchs** [comment]
Hi @djquazzi it's been a long time but nonetheless: Do you still experience this issue? Can't reproduce it with the latest stable client (2.5.3) on macOS Mojave, assuming that this is fixed with the implementations from the 2.5 release.

**Comment by djquazzi** [comment]
Seems fine. MacOS Mojave 10.14.6 and v2.5.3
