### ISSUE TITLE
The icon is too small on HiDPI displays.

### ISSUE THREAD

**Issue by vladipus** [nextcloud/desktop#1486]
This is the tray icon I get for Nextcloud. Other icons are fine, but the Nextcloud's is too tiny.
![image](https://user-images.githubusercontent.com/468323/66311583-7c461c80-e917-11e9-8578-ee9b7c4a01df.png)

**Comment by jancborchardt** [comment]
@juliushaertl @camilasan @misch7 any idea here? :)

**Comment by jancborchardt** [comment]
Also @vladipus what operating system is that, and which version of the Nextcloud desktop client do you use?

**Comment by vladipus** [comment]
> Also @vladipus what operating system is that, and which version of the Nextcloud desktop client do you use?

Sorry. It was Ubuntu. Not sure about the version though...

**Comment by FlexW** [comment]
@vladipus does the problem still exist?

**Comment by vladipus** [comment]
Seems to look alright now.
