### ISSUE TITLE
folder and file icons on windows desktop client 2.6.0

### ISSUE THREAD

**Issue by steel4me** [nextcloud/desktop#1488]
Who  decided to make all folder or file icons WHITE? Please, it is very complicated to see any difference between folders and files. Please remove that and let windows make default icons for folders and files OR, at least give me an option where i can disable these new icon styles.

![image](https://user-images.githubusercontent.com/26707054/66373152-37b69180-e9a8-11e9-9b90-c5e2626f75c2.png)

**Comment by wscheicher** [comment]
Same problem here.
Is it possible to as a workaround somehow disable the icon overlay?

**Comment by supremesyntax** [comment]
> Who decided to make all folder or file icons WHITE? Please, it is very complicated to see any difference between folders and files. Please remove that and let windows make default icons for folders and files OR, at least give me an option where i can disable these new icon styles.
> 
> ![image](https://user-images.githubusercontent.com/26707054/66373152-37b69180-e9a8-11e9-9b90-c5e2626f75c2.png)

Did you reboot after installing the client?

**Comment by steel4me** [comment]
> Did you reboot after installing the client?

Not 100% sure, i will have a look! Sorry...

**Comment by Robotvasya** [comment]
Same problem. Overlayed icons doesn't show

![nxtclowdicn](https://user-images.githubusercontent.com/56023619/66640184-e3bedd80-ec31-11e9-936c-4238cec4b564.png)
Win7 x64

**Comment by steel4me** [comment]
It was bugged somehow. I uninstalled, reboot. Reinstalled, reboot and i have my Icon's back.
Maybe when you forget to reboot Icons are not correctly set.

**Comment by supremesyntax** [comment]
@steel4me i would leave this open as this is a bug. if a reboot is needed there should be a hint in the installer.

**Comment by Robotvasya** [comment]
I checked. This issue appears after update. Clean install helped.
