### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by 6wheels** [nextcloud/desktop#1489]
### Expected behaviour
Downloading 2.6 shoud work.

### Actual behaviour
The browser cannot load the page (timeout).

### Steps to reproduce
1. Go to the Release page
2. Click on Linux, Mac OS or Windows page

### Client configuration
Client version: 2.5 but it does not matter

**Comment by johkoenig** [comment]
https://nextcloud.com/install/#install-clients works (at least for me).
Can you please specify the download location you've tried?

**Comment by TacoNaco47** [comment]
Same problem here. It doesn't work via this download link; https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.6.0-setup.exe, when you click on the "Windows 7, 8.x and 10" icon over https://nextcloud.com/install/#install-clients. 
It gets stuck at 37.7 MB out of 120 MB (see the right side of the following screenshot).

![image](https://user-images.githubusercontent.com/42797589/66454570-83307480-ea68-11e9-920e-14e70702eebd.png) 

When you download it directly via the web directory (https://download.nextcloud.com/desktop/releases/Windows/) it somehow works flawlessly.

**Comment by johkoenig** [comment]
Hm, strange. I can't reproduce that. Download works flawlessly with Firefox and Chrome on my pc. 
@camilasan: can you forward to the hostmaster of nextcloud.com?

**Comment by misch7** [comment]
I don't have this problem, downloads work as expected.

So I guess it's rather a connection issue with your client / browser / network.

Please try it on a different machine and also using another internet connection somewhere else, mobile etc.

I'll forward this to our system administrators but close the ticket because downloads work in general.
