### ISSUE TITLE
Better explanation for encryption passphrase

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#149]
![image](https://user-images.githubusercontent.com/5836855/35621641-642968f8-0685-11e8-82fe-845b78bd036f.png)

On android we use:
All 12 words together make a very strong password, letting only you view and make use of your encrypted files. Please write it down and keep it somewhere safe.

and as title:
Make note of your 12 word encryption password

**Comment by rullzer** [comment]
Also, it should not be hidden behind the show details.

I just picked a quick and easy dialog to show.

**Comment by tobiasKaminsky** [comment]
> Also, it should not be hidden behind the show details.

I think the workflow on android is quite nice:
- show an info about e2e, alongside with passphrase
- if this is confirmed, only then store the keys

So if the person cannot note it down or is at an insecure place, he ca still reject/cancel.

**Comment by tobiasKaminsky** [comment]
---> probably better in #155

**Comment by rullzer** [comment]
So you can't yet show your mnemonic (we do store it). But the RFC states we should be able to show it:

https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#initial-device (bottom of the section)

> The mnemonic is stored in the keychain of the device.
>
> In case a user loses their device they can easily recover by using the mnemonic passphrase. The mnemonic passphrase can also be shown in the client settings in case the user forgets their mnemonic. Displaying the mnemonic requires the user to enter their PIN/fingerprint again on mobile devices.

**Comment by rullzer** [comment]
We should actually change the box here... to directly show the phrase. Maybe even a copy box etc.

**Comment by jospoortvliet** [comment]
That would be nice. I propose this text:

To protect your Cryptocraphic Identity, we encrypt it with a mnemonic of 12 dictionary words. Please note these down and keep them safe. They will be needed to add other devices to your account (like your mobile phone or laptop).

(insert words here)

You can always request to see these 12 words again from the settings menu.

**Comment by rullzer** [comment]
@juliushaertl if you are up for it ;) Would be great if we can make this look a bit better :D
