### ISSUE TITLE
Provide signed dmg package for Mac OS

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#1490]
Releasing Mac OS packages with signed .dmg file is a secure way to ship software to users. The .pkg file used nowadays causes Mac OS to complain about the unknown producer of the file

**Comment by misch7** [comment]
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

I'm working on new build scripts and so I also updated the packaging tool used to build the installer. Perhaps it has solved this issue? :)

Btw: As part of updating the build system I'm also thinking about ways to provide a DMG, at least in addition to the installer package.

**Comment by TP75** [comment]
> As part of updating the build system I'm also thinking about ways to provide a DMG, at least in addition to the installer package.

Would be welcome.

However, please continue in providing the '.pkg' in parallel to the '.dmg' installer.  The '.pkg' allows for remote distribution and installation by help of e.g. Apple Remote Control.

**Comment by er-vin** [comment]
Starting with 3.0.2 we're signing the pkg and the dmg is notarized, thus closing this one.
