### ISSUE TITLE
Virtual Drive not allowing logging in when using untrusted certificate

### ISSUE THREAD

**Issue by EmilyLove26** [nextcloud/desktop#1492]
### Expected behaviour
Should show login screen

### Actual behaviour
![image](https://user-images.githubusercontent.com/7028351/66477521-52e7d680-ea66-11e9-860a-d77a17f5efba.png)

### Steps to reproduce
1. Connect to Server Address via Internal IP (https://192.168.86.100)
2. Trust untrusted certificate
3. Get error message in screenshot above

### Client configuration
Client version: Version 2.5.0 techpreview (build 20190128)
Built from Git revision b38b82 on Jan 28 2019, 11:07:47 using Qt 5.11.1, OpenSSL 1.0.1h 5 Jun 2014

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
