### ISSUE TITLE
Linux client - re-granting access necessary on restart of the app

### ISSUE THREAD

**Issue by chwba** [nextcloud/desktop#1493]
### Expected behaviour
1. Add two new accounts to the client.
2. Quit the client
3. Restart the client
4. The client is still logged in to that account

### Actual behaviour
1. Add two new accounts to the client.
2. Quit the app
3. Restart the app
4. The client is not logged in to both accounts anymore and asks to relogin/grant access again

### Steps to reproduce
1. Install debian 10 (buster)
2. (maybe) install https://github.com/TheAssassin/AppImageLauncher
3. Install the latest linux client using the appimage from https://nextcloud.com/install/#install-clients
4. Add two new nextcloud accounts to the client
5. Quit the app
6. Restart the app

### Client configuration
Client version:  2.6.0stable (build 20190927)

Operating system: Debian GNU/Linux 10 (buster)

OS language: English (US)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Latest Appimage from here: https://nextcloud.com/install/#install-clients

Installation path of client: /home/chwba/Applications/Nextcloud-2.6.0-x86_64_1b1ce82c5926d8d950b6047391bf66a5.AppImage

### Logs
Client Logs:
1. Initial: https://gist.github.com/d1ab09ffec982ce67f3fd21b477e9972#file-initial-log
2. After quitting and restarting the the app: https://gist.github.com/f73bbcdaec20c10ed2b0f32fea58876c#file-log_after_quit_app-log
3. After quitting and restarting the app once again: https://gist.github.com/dc06a6d5824959028dad19ed862f84bb#file-log_after_quit_app_2-log
4. After quitting and restarting one last time: https://gist.github.com/048417222ba6ae10f82420c7554feb85#file-log_after_quit_app_3-log

**Comment by chwba** [comment]
1. For all attacks, It keeps iterating over invalid tokens in all attacks, therefore when an invalid token is found it must get erased from the current token buffer and storage permanently and added to an invalid list.
2. Hardcode 10 messages per token every 30 seconds.
3. When running the guild fetcher, for some guilds it keeps retrying getting the member information infinitely.
4. For the guild fetcher if the selected token fails due to ratelimit/invalid or alike it must fetch a new token in order to be able to continue the process

**Comment by chwba** [comment]
bump

**Comment by misch7** [comment]
Hey,

have you also tried our latest 2.6.1 RC1 build?

https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.6.1.20191018-rc1-x86_64.AppImage

We‘ve added an additional library for keyring support in this specific build - perhaps this solves your issue too?

**Comment by chwba** [comment]
Yes, it works, thank  you very much

**Comment by kamazeuci** [comment]
I am having same problem on NextCloud client 3.2.4 on Endeavour OS with i3WM.

**Comment by FlexW** [comment]
@kamazeuci Make sure you have your keychain configured and unlocked properly on login.
