### ISSUE TITLE
Confusing when all local files deleted

### ISSUE THREAD

**Issue by dctrud** [nextcloud/desktop#1494]
### Expected behaviour
If you accidentally or purposefully empty your local Nextcloud folder then the dialog prompting whether to propagate those changes to the server (i.e. delete files on the server), or re-download from the server should be clear, e.g.

_All the files in your local sync folder 'Nextcloud' were deleted_

_Do you want to 'synchronize deletions' to the server, making such files unavailable unless restored, or 'download files' from the server to restore all files on the server to your local folder?_

### Actual behaviour
The dialog doesn't clearly explain what each button will do. This could result in a user making the incorrect choice for their need:

![image](https://user-images.githubusercontent.com/4522799/66521700-49379080-eab1-11e9-97b6-3cde67a34fbf.png)

### Steps to reproduce
1. Empty your Nextcloud sync folder
2. Start the Nextcloud client

(NB. this happened to me as my nextcloud data is on a separate fs which had failed to mount - so was easy for me to recover without having to choose an option from the dialog).

### Client configuration
Client version:

Operating system: Debian

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop-2.5.1-3+deb10u1

Installation path of client: /usr/bin/nextcloud

**Comment by misch7** [comment]
This has been fixed in our recent 2.6 release :-)

For details see: https://github.com/nextcloud/desktop/pull/1434

If your distro doesn't have it yet, you may try our AppImage:
https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.6.0-x86_64.AppImage
