### ISSUE TITLE
Linux - login doesn't work - browser verification problem

### ISSUE THREAD

**Issue by Floyer007** [nextcloud/desktop#1497]
### Expected behaviour
1. Start Nextcloud
2. Enter Server-Address
3. Login
4. Sync files

### Actual behaviour
1. Start Nextcloud
2. Enter Server-Address
3. The attached error appears.
--> Nextcloud cant open the browser. Both Buttons don't do anything.

![NC-Login-Error](https://user-images.githubusercontent.com/8080648/66550537-ee03ad80-eb45-11e9-9629-13f29c2fd57c.jpg)

### Steps to reproduce
1. Start Nextcloud
2. Enter Server-Address
3. The attached error apears.

### Client configuration
Client version:
Version 2.6.0 from Ubuntu PPA.

Operating system:
Linux Mint 19.2
5.0.0-25-generic
26~18.04.1-Ubuntu

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
It isn't displayed.

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client for ubuntu

Installation path of client:
/usr/bin/nextcloud

### Server configuration
Nextcloud version:
16.0.5

### Logs
Client logfile:

[OCC::AccessManager::createRequest 	4 "" "https://MYDOMAIN.de/index.php/login/v2" has X-Request-ID "848eea71-8f60-4f6f-9c6b-d6b41069c365"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://MYDOMAIN.de" + "" "OCC::Account"
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(UnknownContentError) "Server hat \"411 Length Required\" auf \"POST https://MYDOMAIN.de/index.php/login/v2\" geantwortet" QVariant(int, 411)
[OCC::Flow2Auth::openBrowser()::<lambda 	Error when getting the loginUrl QJsonObject({"error":null,"login":null}) "Fehler beim Zugriff auf den 'Token'-Endpunkt: <br><em>Error transferring https://MYDOMAIN.de/index.php/login/v2 - server replied: Length Required</em>"

**Comment by misch7** [comment]
Thanks for reporting! 👍 

This just has been fixed today already and will get into our 2.6.1 release: https://github.com/nextcloud/desktop/issues/1473#issuecomment-540325976

:-)

**Comment by Floyer007** [comment]
Oh, I didn't checked the commits before.
Thank you!
