### ISSUE TITLE
Client synchronisation is not always triggered when a user changes contents of a shared folder

### ISSUE THREAD

**Issue by TalviT** [nextcloud/desktop#1499]
### Expected behaviour
When one user changes the contents of a shared folder, the affected files are synchronized by the client for the other users.
In other words, if the activation feed says that a file has been changed, it should trigger synchronization.

### Actual behaviour
Users who are not the owner of the shared folder will only see the changes in the web browser or the client's activity feed, but their files will remain unchanged.

### Steps to reproduce
Setup:
* User "Test 1" is the owner of the folder "Shared".
* Test 1 shares Shared with user "Test 2".
-> Test 2 sees in the web browser and in the activity feed of the client that Test 1 shared Shared with Test 2.
-> The folder Shared appears immediately in the directory of Test 1.
-> The Shared folder does not appear in the Test 2 directory.

Further testing steps:
* Test 2 creates a file "foo" in the root directory or Test 2 forces a synchronization in the client or Test 2 restarts the client.
-> The shared folder Shared appears.

* Test 2 creates a file "file_from_test_2" in Shared.
-> Test 1 gets the file immediately.

* Test 1 deletes this file again.
-> Test 2 sees in the web browser and in the activity feed of the client that the file has been deleted.
-> The file is not deleted from the directory.

* Test 2 deletes the file "foo" from the root directory or Test 2 forces a synchronization in the client or Test 2 restarts the client.
-> The Shared folder is empty again.

### Client configuration
Client version: 2.5.3 and 2.6.0

Operating system:
Manjaro Linux

OS language:
German (de_DE)

Qt version used by client package:
5.13.0 (distro), 5.12.1 (appimage), 5.12.5 (flatpak)

Client package:
distro package (v2.5.3), AppImage from Nextcloud (v2.6.0) and Flatpak (flathub – v2.6.0).

Installation path of client:
Default from package manager/download directory in case of appimage?

### Server configuration
Nextcloud version:
17.0.0

**Comment by TP75** [comment]
may relate to [Sync with desktop client not working with GF 4.1.0 and Nextcloud 16.0.4 #597](https://github.com/nextcloud/groupfolders/issues/597)

**Comment by FlexW** [comment]
Does this issue still persist in the most recent version (3.2.1)?
