### ISSUE TITLE
Add indicator that folder is encrypted

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/desktop#150]
The UI should indicate that a folder is encrypted, both in the sync settings and as folder emblem in file managers.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/blob/b6e84b66fd72e2dd86caae00cb3788036fd12008/drawable_resources/decrypt.svg
https://github.com/nextcloud/android/blob/b6e84b66fd72e2dd86caae00cb3788036fd12008/drawable_resources/encrypt.svg

Those are the svg files that @jancborchardt gave to me. Maybe those can be used?

**Comment by tcanabrava** [comment]
yes. adding those.

**Comment by jancborchardt** [comment]
Yep – thanks @tobiasKaminsky, exactly those files should be used. :)

**Comment by awesome-manuel** [comment]
As of 64cbc884740f20bc08d188675bce3b4b82070863 this is still open.

**Comment by tcanabrava** [comment]
@awesome-manuel  how do you think they should display? on the context menu I do a http call to see the current state of the folder and display the possible actions now. if it's always displaying the possibilities I need to trigger the http call every second or so as any other client can change the status of the folder.

**Comment by tcanabrava** [comment]
@camilasan - it's done, updating the info today.

**Comment by awesome-manuel** [comment]
@tcanabrava I agree that polling all the time is not so good. On the other hand the remote folder could also be deleted at any time by another device and you don't poll for this either. Anyway a non empty folder cannot get encrypted by someone else. So I think if you poll once when the view is initialized, put the correct icon and update the state as soon as the user is trying to change the encryption this should be fine.
Right now there is a checkbox, the globe icon and some text for each folder. The encryption icon could be added beneath the globe.

**Comment by juliushaertl** [comment]
@tcanabrava Doesn't the webdav response have some property regarding the encryption status when the folder list is fetched from the server? So we can just show the status in the list as an icon, because having it just in the right-click menu is not that obvious.

**Comment by jancborchardt** [comment]
Yeah, the encryption status should absolutely be shown directly as an overlay icon (like the sync status or share status).

**Comment by awesome-manuel** [comment]
Thinking about this, I think there is something to consider (maybe a new issue). The client must never trust the server about the encryption status of a folder. This is especially true if the server marks a previously encrypted folder to be unencrypted. If the client accepts this and syncs with this folder, all user data will be sent to the server unencrypted.

**Comment by camilasan** [comment]
> @camilasan - it's done, updating the info today.

Where @tcanabrava? :)

**Comment by jancborchardt** [comment]
@juliushaertl is it also shown in the file manager as overlay icon? Cause https://github.com/nextcloud/desktop/pull/437 is only about the settings dialog.

**Comment by juliushaertl** [comment]
@jancborchardt For now it is only shown in the folder list inside the settings. :+1: Let's keep this open.

**Comment by rullzer** [comment]
@jancborchardt could you provide some overlay icon for this then?

**Comment by jancborchardt** [comment]
@rullzer is it still the case that this icon needs to be combined with another icon because there’s a limit on overlay icons? (I remember that being the case with the share overlay.) If so, where are these icons?

The icon to use would be icon-password (the lock) https://docs.nextcloud.com/server/14/developer_manual/design/icons.html

**Comment by rullzer** [comment]
Ah right the windows limitations. I'll look intot hat first because if it is full already then we are just out of luck I guess...

**Comment by Rello** [comment]
Client integration changed since this request. will need to be reevaluated if still relevant
