### ISSUE TITLE
NC 2.6.0 client shows an unstable GUI window on Mac OS X after first config

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1501]
EDIT: 

 * re-opened for similar issues: #1602

 * NC desktop App **macOS** -- Version **2.6.1stable (build 291105)**

### Expected behaviour
The NC client should show a stable GUI window.

### Actual behaviour
The NC client repeatedly shows an unstable GUI window with mixed content of otherwise different sub-views.

### Steps to reproduce
1. establish a fresh client to the environment of an user account
2. select Network view after configuration
3. change to Server view

Apparently happens to fresh configured client only.  De-selecting the client and opening of a new NC client window continued this GUI issue.  Later application of the client seems to be stable.

### Client configuration
Client version: _2.6.0stable (build 20190927)_

Operating system: 

1. _MacOS X / macOS Mojave 10.14.6_
1. _Mac OS X / macOS HighSierra 10.13.6_

OS language: 
1. _German (Deutsch / DE)_
2. _Dutch (Nederlands / NL)_

_presumably more if not all languages or independent from OS locale & language_

Qt version used by client package (Linux only, see also Settings dialog): _Qt 5.9.2_

Client package (From Nextcloud or distro) (Linux only): _n.a._

Installation path of client:
`/Applications/nextcloud.app`

### Server configuration

Nextcloud version: _16.0.4.1_ & _16.0.5.1_

Storage backend (external storage): _n.a._

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile:  _n.a._

2. Web server error log: _n.a._

3. Server logfile: nextcloud log (data/nextcloud.log): _n.a._

### Screenshot

![screenshot_2019-10-10b](https://user-images.githubusercontent.com/31193257/66653281-f3412500-ec37-11e9-9ddc-47e758ab5aad.png)

**Comment by TP75** [comment]
This issue shows a similar behaviour after first setup in an OS locale environment different from the a.m. German example.  NC 2.6.0 client and Mac OS X / macOS HighSierra 10.13.6

**Comment by misch7** [comment]
Hey,

we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).

You may give it a try:
https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

Would be good to know if the problem was caused by the older Qt versions used in the previous builds.

**Comment by TP75** [comment]
Please also have a look at the b.m. issue and certain comment:

Desktop client not syncing changes # 597 (as referenced above) includes the 2.6.1 RC1 client apparently.

> Alright. Reproduced it now also on
> 
>     * Server 16.0.5
> 
>     * Group Folders 4.1.3
> 
>     * Desktop client 2.6.0 (and 2.6.1 RC1)
> 
> 
> and also on
> 
>     * Server 17.0.0
> 
>     * Group Folders 5.0.3
> 
>     * Desktop client 2.6.0 (and 2.6.1 RC1)
> 
> 
> Extra info: once _any_ change is made to a normal folder on the server (or another connected client), the group folder sync gets triggered also - but not if changes on the server have been made within a group folder only.

However, I will give it a try and will come back on the results and the GUI on MacOS X issue.

**Comment by TP75** [comment]
@misch7 Thank you very much.

### Conclusion

The intermediate NC Client Version 2.6.1rc1 (build 20191018) showed a behaviour as expected. The intermediate NC client **shows a stable GUI window** on Mac OS X / macOS again.

### Client configuration
Client version: _Version 2.6.1rc1 (build 20191018)_

Operating system: 

1. _MacOS X / macOS Mojave 10.14.6_
1. _Mac OS X / macOS HighSierra 10.13.6_

OS language: 
1. _German (Deutsch / DE)_

_Note: NL results pending_

Qt version used by client package (Linux only, see also Settings dialog): _Qt 5.12.5_

### Server configuration

Nextcloud version: _16.0.5.1_

### Brief description of tests:
1. MacOS X / macOS Mojave 10.14.6
- delete old installation i.e. removal of app folder from `/Applications` and clean trash basket
- remote install by help of Apple Remote Control
- establish a fresh new local user account
- login to this user account and make a new NC client setup
- play around with the NC client GUI window
2. Mac OS X / macOS HighSierra 10.13.6
- do not delete old installation
- local install from admin account
- establish a fresh new local user account
- login to this user account and make a new NC client setup
- play around with the NC client GUI window

### Further remarks:

Other issues were identified for the RC1 version besides the a.m. original issue (which is resolved).  I may identify the other issues by tickets of their own in the near future.

**Comment by TP75** [comment]
The major GUI issue of the NC client 2.6.0 version can be called **resolved** by the NC client 2.6.1 RC1 version.

**Comment by TP75** [comment]
#1602

**Comment by misch7** [comment]
Here's a new test build, based on PR #1651 (macOS 10.12+):
https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.5-2.7.0.20191201daily.pkg

**Comment by TP75** [comment]
> Here's a new test build, based on PR #1651 (macOS 10.12+):
> https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.12.5-2.7.0.20191201daily.pkg

THX

I'll give it a look and some trial when I find the time. However: Why 2.7.0 and not 2.6.2 if I may?

**Comment by misch7** [comment]
> I'll give it a look and some trial when I find the time.

👍 

> However: Why 2.7.0 and not 2.6.2 if I may?

This is just our development branch version; Next release is 2.6.2

> Anyway, added to: https://help.nextcloud.com/t/macos-nc-2-7-0-bucket-list/64890

This is no public test candidate - just a test build (patched daily) - please don't advertise it as such on the forums, it's not considered stable for general testing.

But thanks for your community efforts, keep up with 2.6 :-)

**Comment by TP75** [comment]
See https://help.nextcloud.com/t/nc-2-7-0-macos-test-candidate/65432
