### ISSUE TITLE
Update changelog for 2.6.0 and link it on the homepage

### ISSUE THREAD

**Issue by tflidd** [nextcloud/desktop#1506]
Follow up of this topic, the changelog was not updated for the 2.6.0 release:
https://github.com/nextcloud/desktop/issues/1369#issuecomment-541301594

Also this should be linked on the desktop download page (extra issue)

**Comment by FlexW** [comment]
@tflidd Was the issue resolved with the pull request that was merged? If yes, please close the issue.

**Comment by tflidd** [comment]
Was fixed with https://github.com/nextcloud/desktop/pull/2774
