### ISSUE TITLE
"Help" and "For more information" links to a empty page

### ISSUE THREAD

**Issue by frelis** [nextcloud/desktop#1507]
On the about section of the the link does not exist
in the about section:
"Version 2.6.0stable-Win64 (build 20190927). For more information please click **here**."

When I click in "here" go to this link: https://docs.nextcloud.com/desktop/2.6/
and the content is "File not found."

**Comment by jancborchardt** [comment]
@rullzer how is the documentation building process here? cc @camilasan @misch7
