### ISSUE TITLE
Client is crashing when accessing "wrong" encrypted files

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#151]
- user tobi has encrypted files / metadata with key A
- I removed for testing purpose key A from server
- client is showing new passphrase and then crashing on syn

If the client cannot decrypt those files, it should at least do not crash.
On android the crypted files are shown. It is not a perfect solution, but at least the user sees that it is an encrypted folder which encrypted files that failed to decrypt.

**Comment by rullzer** [comment]
Yes, we still crash hard. We should error out and just not handle this file as encrypted probably yes.

**Comment by tcanabrava** [comment]
I'm fixing this.

**Comment by camilasan** [comment]
How do you remove the key from the server? Is it fixed @tcanabrava?

**Comment by camilasan** [comment]
@tcanabrava?

**Comment by tcanabrava** [comment]
Should be fixed. If it's crashing should be another bug. @tobiasKaminsky  can you please test again?
I'v added quite a bit of code to make sure we don't crash.

**Comment by tobiasKaminsky** [comment]
@tcanabrava sure, is there a recent client I can use? 
Or can you give me a quick instruction how to compile it myself on Linux?

**Comment by er-vin** [comment]
I confirm this doesn't crash anymore, you get an error on sync regarding the impacted file(s).
