### ISSUE TITLE
Disable updates check on build time

### ISSUE THREAD

**Issue by Germano0** [nextcloud/desktop#1512]
Nextcloud client has a `new updates available` alert. In Linux distributions we don't need such alert since we already take care of shipping new updates.
We need a compilation flag to disable such alert.

**Comment by TP75** [comment]
Good proposal. IMHO this compilation flag should also aim to disable internal update checks to the NC app store and thus avoid unneccessary ip communication in the background for Linux.

**Comment by Highview-Lucas** [comment]
+1 for windows builds, we run SCCM so all of our software versions are managed.

I've a bunch of users on a version that always reinstalls itself instead of the updated version - I couldn't find a bug for it, I'll have to make one when I have an affected user on hand again.

**Comment by michaelstingl** [comment]
Existing methods doesn't work for you?
https://docs.nextcloud.com/desktop/2.5/autoupdate.html#preventing-automatic-updates

**Comment by TP75** [comment]
@michaelstingl  Thank you. Good point.

> Existing methods doesn't work for you?
> https://docs.nextcloud.com/desktop/2.5/autoupdate.html#preventing-automatic-updates

Generally such features should be '**opt-in**' and not 'opt-out' as is the accepted policy on Privacy options in the EU.

**Comment by Germano0** [comment]
This is how updates check should be handled, not in user configuration file
https://src.fedoraproject.org/rpms/keepassxc/blob/master/f/keepassxc.spec#_71

**Comment by claell** [comment]
Should be implemented with #1847 according to https://github.com/nextcloud/desktop/issues/1799#issuecomment-596322139. Can someone confirm that?

**Comment by claucambra** [comment]
There is now a compile-time flag to enable/disable the updater, so I will close this issue. Thanks for opening :)
