### ISSUE TITLE
Cannot attach new account to sync client

### ISSUE THREAD

**Issue by VolkerKamin** [nextcloud/desktop#1517]
### Expected behaviour
When I add an account to a fresh Windows 10 install, it should find files and sync them.
When I add an account to an existing Windows 7 install, it should find files and sync them.

### Actual behaviour
There are two error scenarios:
a) When trying to select folders to sync, the client states that there are no files / folders on the server.
b) Sometimes login using password does not work (token status invalid). This can be circumvented by manually creating "App-PINs": see error a).

**Important**
I can add accounts that just live under "https://mydomain". However, in the error case, the URL I enter (and which correctly brings me to the login web page) is "https://foodomain/barcloud"

**Important**
An existing account of the same on the Win7 machine is still operational! I just cannot add new accounts. It seems to replace "foodomain/barcloud" with "foodomain/nextcloud" which breaks everything.

### Steps to reproduce
1. setup server where cloud is not unter "domain/nextcloud" but "domain/foocloud"
2. try to connect new user account
3. try to select folders to sync (or don't, even if you say to sync everything it does not work)

### Client configuration
Client version: Version 2.6.0stable-Win64 (build 20190927)

Operating system: Win10 (new machine) and Win7 (reproduced on old machine)

OS language: German

Installation path of client: default as suggested by installer

### Server configuration
Nextcloud version: 12.0.0

Storage backend (external storage): unknown / I am not the server operator

**Comment by VolkerKamin** [comment]
Suggestion: make those red error boxes copy & paste capable

Client says:
Keine Verbindung zu Nextcloud auf https://mydomain Server hat "404 Not Found" auf "GET https://mydomain/nextcloud/status.php" geantwortet.

Which is perfectly OK server-wise. The URL I entered upon login was "mydomain/foocloud" not "mydomain" or "mydomain/nextcloud".

As stated above: this seems to be in issue in the code that creates the local user account. An already exiting account (same server and user) is still operational on my old computer, which runs the same client version. When I try to add the same account a second time to the old computer, I see the same error as on the new computer: a second account which accesses the wrong URL. At the same time, the old account on the old computer (same server and user) keeps working like a charm.

**Comment by VolkerKamin** [comment]
# Workaround

In %APPDATA%\Nextcloud\nextcloud.cfg there is a line that reads
> 0\url=https://mydomain

After changing it to
> 0\url=https://mydomain/foocloud
everything worked fine.

It seems the sync client version 2.6.0stable-Win64 (build 20190927) does not properly populate this field upon account setup.

**Comment by TP75** [comment]
> Nextcloud version: 12.0.0

This seems to be a rather **outdated server configuration**.

https://nextcloud.com/changelog/

- Nextcloud 17
- Nextcloud 16
- Nextcloud 15
- Nextcloud 14 (unsupported!)
- Nextcloud 13 (unsupported!)
- Nextcloud 12 (unsupported!)

**Comment by VolkerKamin** [comment]
> > Nextcloud version: 12.0.0
> 
> This seems to be a rather **outdated server configuration**.

Yes, but since the **client** software clearly changes the user input to something that only works in the default case, I do not see how the server version is relevant here.

Do you have any basis to assume that this **client** error will not be triggered on newer server versions? To me, this kind of post sounds like "I did not really care to read your bug report, so here is my reason for ignoring it."

**Comment by TP75** [comment]
> the sync client version 2.6.0stable-Win64 (build 20190927)

see the article [New NC desktop **2.6.1** available online](https://help.nextcloud.com/t/new-nc-desktop-2-6-1-available-online/63641) in the user forum

Hope this helps.
😄

**Comment by TP75** [comment]
> In %APPDATA%\Nextcloud\nextcloud.cfg there is a line that reads
> 
> > 0\url=https://mydomain
> 
> After changing it to
> 
> > 0\url=https://mydomain/foocloud
> 
> everything worked fine.

Good to learn of your solution. Congrats.

However, comparing your initial issue report and the workaround IMHO there may be some inconsistencies in the strings and values of parameters. Furthermore, are you sure this was not a human error and/or inadvertent change of NC desktop Vlient preferences by using both the CLI and the GUI in a.m. scenario?

Just curious. My five cents.

**Comment by mgallien** [comment]
I am not sure I understand what is the problem here.
Could you please check if you can reproduce it as it works for me (adding a new account to an already configured one) ?
