### ISSUE TITLE
New version check never concludes

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/desktop#1519]
### Expected behaviour
The check should either fail or succeed with new or no new versions.

### Actual behaviour
Client is "Checking update server..." indefinitely with no feedback.

### Steps to reproduce
1. Open the "General" tab in the client
2. Wait a definite amount of time for the update check to finish
3.

### Client configuration
Client version: 2.6.0stable-Win64

Operating system: Windows 8

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\Nextcloud\

### Server configuration

Nextcloud version: 17

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
The 'nextcloud --logwindow' simply opens the Nextcloud client on the tab with update check.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by InfamousUser** [comment]
Hmm... interesting that 64 bit version gets installed under Program Files (x86)...

**Comment by misch7** [comment]
@InfamousUser This is because you updated your existing installation and Setup uses your previous location.

Has been fixed in 2.5.3 but you'd need to uninstall and do a fresh install to change the path.


Regarding your original issue: Did you restart both your computer (reboot) and the client? Usually the "Checking update server..." message is related to connection issues or the system / client running to long without being restarted.

**Comment by TP75** [comment]
> Has been fixed in 2.5.3 but you'd need to uninstall and do a fresh install to change the path.

@misch7 May I ask if the apparent **need to uninstall and do a fresh install**'  is limited to  MS Win only or is covering all OS platforms the client may be installed on?

**Comment by InfamousUser** [comment]
@misch7 Okay I uninstalled properly and reinstalled 2.6.0 again, now it works. Something must have gone wrong during one of the new version installations because it wasn't working since several versions back. And you're right, I do keep my PC without restart for several weeks, the only other thing that has an issue is Chrome having memory leaks so requires occasional restart. No restart after this reinstall tho, worked immediately. Thanks!

**Comment by misch7** [comment]
@TP75: This is only related to the Windows installer. And your client settings and synced will be kept when you reinstall the client.

@InfamousUser: Nice that this solved the issue 👍

It’s always a good idea to reboot your system from time to time. Especially on Windows, as it tends to trash itself after a while and you‘ll notice some apps misbehaving or even refuse to start.
And system updates (security etc.) would require reboots either way ;-)

**Comment by TP75** [comment]
> This is only related to the Windows installer. And your client settings and synced will be kept when you reinstall the client.

@misch7 Thank you. I was aware of the NC client continuity in settings and sync. However, you clarified on my question '**need to uninstall and do a fresh install**' specifically.

So no need to uninstall and do a fresh install besides Windows. I am good with this.

**Comment by InfamousUser** [comment]
Well on Windows an uninstall isn't needed either normally but something must've gone wrong with my update.

@misch7 Yeah, reboots are a good idea so I reboot it at least monthly. I install updates every few months so it's not an issue. :) I must say I haven't had issues with anything else for a long time, mostly it's app bugs. I've probably jynxed it now...
