### ISSUE TITLE
Offer qr code for encryption passphrase

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/desktop#152]
Nothing urgent, but when setting up an encrypted folder on the client it would be awesome if users can just scan a qr code with their mobile device instead of typing that passphrase.

cc @nextcloud/android @nextcloud/ios Since that would also need some implementation on the mobile side.

**Comment by jospoortvliet** [comment]
Let's start making the current setup dialog less ugly 🙈 and have a way to get the code to be shown again? couldn't find that.

**Comment by tobiasKaminsky** [comment]
Might be related to #157, but I understand the passphrase as showing it only one time.
So if you do not want to setup desktop client and mobile at exact the same time, this will not work...

At least on android we do not have anything like qr code implemented yet and doing this for "only" setup is a little overhead I think.

**Comment by dantti** [comment]
IMHO if the user session is open on a Plasma desktop you can easily open KWallet and see the passphrase (which is what I did to get it for a second machine), taking a photo of the user screen with the passphrase text vs a Qr code doesn't seem to be different from a security POV.

For the sake of giving a bit more work to the ill-intentioned user I'd suggest asking the account password to show both text and Qr.

**Comment by comradekingu** [comment]
@tobiasKaminsky Expanding on that
I don't know if obligatory print it out and hang it somewhere is a feature of a bug.
If it was time-restricted maybe, or folder amount.

You give out a QR-code, and that possibly facilitates quite a few use-cases.

**Comment by Rello** [comment]
Closing for now. we will reevaluate dependent on the future client strategies
