### ISSUE TITLE
QNetworkReply::ServiceUnavailableError "Error transferring xyz - server replied: " QVariant(int, 503)

### ISSUE THREAD

**Issue by Defcon0** [nextcloud/desktop#1525]
### Expected behaviour

Upload of the file should work.

### Actual behaviour

It doesn't

### Steps to reproduce

The file can only be provided by mail or a non public system since it contains customer data. I can't upload it here at github.

### Client configuration
Client version:
2.6.0

Operating system:
Windows 10

OS language:
German

Installation path of client:

C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 17

Storage backend (external storage): ?

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

https://gist.github.com/Defcon0/5244f963a0f5ce12da08c456fe252ef4#file-gistfile1-txt

2. Web server error log:

Contains no entry at the given time.

3. Server logfile: nextcloud log (data/nextcloud.log):

https://gist.github.com/Defcon0/5244f963a0f5ce12da08c456fe252ef4#file-gistfile2-txt

**Comment by mgallien** [comment]
Can you still reproduce the issue ?
