### ISSUE TITLE
Group Folders are handled like external storages on desktop client

### ISSUE THREAD

**Issue by benbrummer** [nextcloud/desktop#1535]
### Expected behaviour
Group foulders should be synced automatically

### Actual behaviour
The client displays a message "There are folders that were not synchronized because they are external storages: SOME GROUP-FOLDER

### Steps to reproduce
1. Create a group folder and add a group to it
2. Connect a nextcloud desktop client
3. Group Folder will not be synced as Nextcloud Client thinks i8t is an external storage

### Client configuration
Client version: 2.6.0

Operating system:
Windows 10
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files\Nextcloud

### Server configuration

Nextcloud version:
17.0.0
Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Daksol** [comment]
See related item https://github.com/nextcloud/desktop/issues/1967
