### ISSUE TITLE
No synchronization for files with two points colon ":" in the name

### ISSUE THREAD

**Issue by quentinDupont** [nextcloud/desktop#1537]
### Expected behaviour
Synchronizing my file called "Test:mytest.pdf"

### Actual behaviour
Every file with ":" in the name are not being synchronized in Windows desktop client.

### Steps to reproduce
1. Online rename a file with ":" in the name
2. Wait or synchronize your computer
3. Nothing is being synchronized

### Client configuration
Client version:
Just installed windows latest Version 2.6

In Linux client, the synchronization is working with this kind of file so it's not a problem of the server.

Thanks in advance !

**Comment by x86dev** [comment]
I guess this is due to the limitation of Windows, as a colon (:) is not allowed as part of a file name (nor paths). The question is, though, how Nextcloud should react to that, as on non-Windows systems a colon within a path should work on most file systems.

**Comment by quentinDupont** [comment]
> I guess this is due to the limitation of Windows, as a colon (:) is not allowed as part of a file name (nor paths). The question is, though, how Nextcloud should react to that, as on non-Windows systems a colon within a path should work on most file systems.

I don't have a good solution in mind..
If we forbid to name file with colon in the name in web interface, it can't block user in Linux client to name his file with colon, then it's uploaded and.. not download in Windows Client..

A "translating" system will be very confusing (if you translate colon with "-" in Windows client for example)..

So i don't have solution in my mind at the moment.
We should look at how it's handle in Google Drive and other solutions

**Comment by x86dev** [comment]
Just define a common character set for all platforms which gets validated. Everything else not matching this character set simply will be ignored. Logging this then would be useful though.

**Comment by claell** [comment]
This seems to be a duplicate of #464. Please confirm and close this issue if that is the case. Discussion can continued in the original issue then.

**Comment by quentinDupont** [comment]
Same issue indeed ! I close this one
