### ISSUE TITLE
Upload of encrypted file remove all other content

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#154]
Steps to reproduce
- copy a file into an encrypted folder, wich already contains files
- see desktop client in "wait..." state
- close & restart client
- newest file gets encrypted & uploaded
- all other files are removed locally, but remain on server & are accessible on android
- close & restart client
- get all files again

![image](https://user-images.githubusercontent.com/5836855/35625453-b80c0a18-0692-11e8-9e8d-de6b80ca1751.png)

**Comment by camilasan** [comment]
Couldn't reproduce it. Could you try it too @rullzer @tcanabrava @dantti?

**Comment by camilasan** [comment]
which PR @dantti? :)

**Comment by dantti** [comment]
This https://github.com/nextcloud/client/pull/234, since it was after there's a chance it's working now

**Comment by tcanabrava** [comment]
@tobiasKaminsky can you test again? I did not managed to reproduce

**Comment by tobiasKaminsky** [comment]
@tcanabrava sure, is there a recent client I can use? 
Or can you give me a quick instruction how to compile it myself on Linux?

**Comment by er-vin** [comment]
I can't seem to reproduce it either. I'll consider it gone.
