### ISSUE TITLE
Client crashes on right click while setting up a sync folder

### ISSUE THREAD

**Issue by octfx** [nextcloud/desktop#1540]
### Expected behaviour
Right clicking a folder in the "Select Source folder" window should open the folder dialog.

### Actual behaviour
The Nextcloud client crashes.

### Steps to reproduce
1. Open the Nextcloud client
2. Add a new sync folder
3. Right click on a folder in the selection window

### Client configuration
Client version: 2.6.0 stable

Operating system: Winwows 10 pro x64

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: 16.0.5

**Comment by squalo80** [comment]
On my installation, there is the same issue. Tested on 2 different clients. Same configuration

**Comment by octfx** [comment]
Bug seems to be fixed, at least with client version 3.2.1
