### ISSUE TITLE
update impressum w most recent copyright

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1542]
### Expected behaviour
The impressum view shows a NC logo and the most recent copyright information.

### Actual behaviour
The copyright information seems to be outdated and no logo or reasonable text.

### Steps to reproduce
1. Choose the 'Einstellungen' i.e. 'Settings' view of the NC desktop client
1. Select the 'Allgemein' i.e. 'General' icon and view
2. Select the 'Impressum' button in the lower half of the 'General' view

### Client configuration
Client version: _Version **2.6.1rc1** (build 20191018)_

Operating system: _Mac OS X / macOS Mojave 10.14.6_

OS language: _German (Deutsch / DE)_

Qt version used by client package: _Qt 5.12.5_

### Server configuration

Nextcloud version: _16.0.5.1_

### Brief description:

1. Check correctness and update the resp. year in the two lines of copyright text.
1. Consider a Nextcloud logo and/or a more impressive 'impressum' text.

![screenshot_client_2019-10-19b01_impressum](https://user-images.githubusercontent.com/31193257/67240148-257d2e80-f451-11e9-87b1-2add2ec9beb6.png)

**Comment by TP75** [comment]
still **open** for _2.6.1stable_ unfortunately

**Comment by misch7** [comment]
Solved by PR #1641
