### ISSUE TITLE
Correct Client Build instructions?

### ISSUE THREAD

**Issue by Highview-Lucas** [nextcloud/desktop#1546]
which are the current / correct build instructions?

https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client

or 

https://github.com/nextcloud/client-building/blob/master/README.md

**Comment by misch7** [comment]
For Windows these are the current and correct build instructions:
https://github.com/nextcloud/client-building/blob/master/README.md

The instructions in the Wiki are outdated and get updated once we've the time.
