### ISSUE TITLE
preventing Automatic Updates in macOS

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1547]
Existing methods doesn't work for you?
https://docs.nextcloud.com/desktop/2.5/autoupdate.html#preventing-automatic-updates

_Originally posted by @michaelstingl in https://github.com/nextcloud/desktop/issues/1512#issuecomment-544815472_

**Comment by TP75** [comment]
At least for the 2.6.1 RC1 the default plist is missing from Mac OS X / macOS installation.

> **Preventing Automatic Updates in macOS Environments**
> You can disable the automatic update mechanism, in the macOS operating system, by copying the file `nextcloud.app/Contents/Resources/deny_autoupdate_com.nextcloud.desktopclient.plist` to `/Library/Preferences/com.nextcloud.desktopclient.plist`.

```
$ ls -1 /Applications/nextcloud.app/Contents/Resources
Nextcloud.icns
Translations
qt.conf
sync-exclude.lst
```
Obviously no `deny_autoupdate_com.nextcloud.desktopclient.plist` provided.

**Comment by TP75** [comment]
I hope the NC desktop devs would in due time please:
1. provide means & code for _preventing Automatic Updates in macOS_ as appropriate
1. make available https://docs.nextcloud.com/desktop/2.6/ with an updated content

**Comment by TP75** [comment]
still **open** for _2.6.1stable_ unfortunately

**Comment by tobiasKaminsky** [comment]
Why do you want to prevent auto-install?
On iOS/Android/Linux this is common.

**Comment by TP75** [comment]
Hi @tobiasKaminsky 
CC @michaelstingl 

> Why do you want to prevent auto-install?
> On iOS/Android/Linux this is common.

1. A more elaborate request in the beginning was copied to the top of this issue.

1. There is a word like "free" which includes the freedom of choice.

1. Opt-in is EU accepted procedure to protect privacy, not the opt-out.

1. Your claim seems quite debatable. The usual Linux package system has a regular update with user controlled upgrade, I presume.

1. The Nextcloud FOSS project should always seek to implement code according to the self-proclaimed core values of Nextcloud GmbH, if I may.

There may be more...

**Comment by misch7** [comment]
There is no auto-update functionality in the current macOS builds. You only get notified for new updates and 2.6.1 now provides a download link within the update notification.

Closing this here for now since re-enabling auto-update is still work in progress and there will be no automatic installation without user's consent.

**Comment by TP75** [comment]
@misch7 -- Why confused?

> 5\. The Nextcloud FOSS project should always seek to implement code according to the self-proclaimed core values of Nextcloud GmbH, if I may.
>
> 6\. It was documented as a feature of the NC desktop App/Client, obviously.

AFAI this is a NC self documented feature.

@camilasan Thank for adding this to the 2.6.2 milestone.

**Comment by tobiasKaminsky** [comment]
@misch7 can you re-check documentation and then adjust it: https://docs.nextcloud.com/desktop/2.6/autoupdate.html

**Comment by claucambra** [comment]
With the new auto-updater, updates can be dismissed and future reminders prevented so will close, thanks for opening this issue
