### ISSUE TITLE
GUI response and text shall be more appropriate to macOS

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1548]
### Expected behaviour

The NC desktop client should:

- show GUI items and resp. informative text applicable to the OS platform it is installed on
- should provide a functionality in accordance to the setup and by transparent GUI response

### Actual behaviour

The current intermediate Version **2.6.1rc1** of the NC desktop client in a Mac OS X / macOS environment:
- shows misleading text or text not appropriate to Mac OS X / macOS
- after first setup establishes a Nextcloud folder icon in the sidebar of the Apple Finder although the applicable GUI checkbox remains unchecked

### Steps to reproduce

1. Make a fresh install of the NC desktop client on OS (1.) and/or (2.)
1. Choose the 'Einstellungen' i.e. 'Settings' view of the NC desktop client
1. Select the 'Allgemein' i.e. 'General' view
1. view the 'Erweitert' i.e. 'Advanced' settings and compare this to a Finder window

see the screenshot below

### Client configuration

Client version: 

- _Version **2.6.1rc1** (build 20191018)_

Operating system: 

1. _Mac OS X / macOS Sierra 10.12.6_
1. _Mac OS X / macOS Mojave 10.14.6_

OS language: _German (Deutsch / DE)_

Qt version used by client package: 

- _Qt 5.12.5_

### Server configuration

Nextcloud version: _16.0.5.1_

### Brief description:

View is similar between OS (1.) and (2.) and deviations are marked red:
![screenshot_client_2019-10-19d02_general](https://user-images.githubusercontent.com/31193257/67282335-d2978b80-f4d1-11e9-9168-d60055d76156.png)

You may find a Nextcloud folder icon sitting in the sidebar of the Apple Finder although the applicable GUI checkbox of the NC desktop client remains unchecked.

Proposed improvements to the informative text:
- There is the 'Finder' and no 'Explorer' on the Mac.
- The 'sidebar' of the Finder is named 'Seitenleiste' in the German de-DE locale but it is not called 'Navigationsbereich'.

Please refer to:
- [Get to know the Finder on your Mac](https://support.apple.com/en-us/HT201732)
- [Kennenlernen des Finders auf dem Mac](https://support.apple.com/de-de/HT201732)
- In addition to the apparent Apple Design & [Human Interface Guidelines](https://developer.apple.com/design/) there should be an applicable official translation list for OS & App terms which could be downloaded via the official Apple Developer project page, if I recall correctly.

**Comment by TP75** [comment]
still **open** for _2.6.1stable_ unfortunately

**Comment by misch7** [comment]
Fixed in 2.6.2 and option removed in 2.6.4 due to missing implementation of the option.
