### ISSUE TITLE
MacOS desktop client is constantly scanning files

### ISSUE THREAD

**Issue by lencell** [nextcloud/desktop#1550]
### Expected behaviour
Client finish scanning and only process new files that are to sync without starting a full scan again

### Actual behaviour
The client seems to start a full scan after syncing any file and is scanning the sync folder 100% of the time greatly slowing down the syncing process (when not halting it totally)

### Steps to reproduce
1. Start nextcloud client
2. wait for scan to finish (a long time)
3. modify a file
4. watch the scan going on again

### Client configuration
Client version: 2.5, 2.6.0stable build 20190927

Operating system: macOS Catalina 10.15

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications/nextcloud.app

It is noteworthy to say that there is quite a lot of file that are synced (100k+) so that non stop scans are really a problem

### Server configuration

Nextcloud version: 16.0.4.1

Storage backend (external storage):

### Logs
https://gist.github.com/lencell/750731eeca10f2583fb346e424c58849

I've put only the first lines there as the scan goes on for a long time as I said earlier there is more than 100k files.

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by andrimont** [comment]
Thank you @lencell to report this important issue that I experience as well.
I use the same operating system: macOS Catalina 10.15

**Comment by joshtrichards** [comment]
Hi @lencell - This is a very old issue. Are you still experiencing this in newer versions of the client?

**Comment by claucambra** [comment]
Closing due to lack of info
