### ISSUE TITLE
keep logo in tray icon

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/desktop#1552]
# Expected behaviour
Nextcloud logo, or similarly distinguishing visual effect, should remain in tray icon at all times, with any status information represented as an overlay.

# Actual behaviour
After the initialization phase of the application, the tray icon appears either as a check mark or *X* mark.  Thus, the icon indicates that there is an application with some positive or negative status, but not which application.

# Client configuration
Client version: 2.6.1-rc1

Operating system:  Linux Mint 19.2, Cinnamon Desktop

OS language: English

Qt version used by client package: 5.12.5

Client package: `Nextcloud-2.6.1.20191018-rc1-x86_64.AppImage`

**Comment by jancborchardt** [comment]
There has been a ton of discussion which went into the tray icons, including **New sync state icons  https://github.com/nextcloud/client_theming/issues/196** and **Add new sync state icons #416**.

It has been working well and it’s distinct from other apps since we are one of the only ones (or the only one) not using a logo. It just doesn’t work having the logo _and_ the sync state there at the same time in this tiny space.

**Comment by brainchild0** [comment]
Thank you for indicating the references, which I had missed from my earlier keyword searches of past issues.

I read the two issues, and now have a better understanding of the considerations and history leading to the current choice for icons.

I notice a prominent issue during these discussions was how to represent a large number of distinct states in addition to the branding logo.  Ultimately, the logo was dropped because it was seen as unnecessary and interring with the representation of rich state information.

Looking briefly at my Mint Cinnamon tray icons, I see a variety of different indicators but only very simple state information.  The system update tool has two states, for updates being available and no updates being available.  The Bluetooth controller has two states, for enabled and disabled, as does the nightlight tool.  The network manager has three states, for connected, not connected, or trying to connected.  The music player is very simple, being a static icon, the same whether music is playing, paused, or not loaded.  The battery indicator is the most intricate, having separate overlays for charge level and for connection to the charger.  In all cases, the outline of a battery is the most plain and recognizable feature.

All of these icons clearly and centrally indicate the purpose of the icon, with state information being auxiliary.

I think the recent focus on detailed information about current state might be reconsidered. I hardly think that the reason for other services not similarly forgoing representation of the application in the tray icon in favor  of only status information is  because Nextcloud does so currently and those services wish to avoid confusion, even though they wish they had had the idea first.  I rather think  simply that the solution  is not an optimal use of a tray icon.  My suggestion would be to use a logo, and in cases of error or needing user attention, to overlay  a smaller icon from a selection of one or two possibilities.  It is unnecessary to try to communicate a large number of possible states in the width and height of 16 pixels.  It is also unnecessary to try to fit the state information in the central circle of the logo, as state information ought to  be absent much of the time, and when present, ought to be easily noticed.

**Comment by derhagen** [comment]
I second @brainchild0's opinion. Most of my tray icons clearly communicate which service they belong to. Nextcloud stands out, in that 95% of the time it shows a nondescript checkmark, which only tells me "Something is okay".
When I'm looking for the nextcloud icon to adjust settings, I always have to look twice. At the same time, if anything requires my attention, I get a notification anyway. While it might make sense to clearly show sync or error states as clear as possible and omit the nextcloud logo, I disagree that a checkmark as a default state gives me a good feeling of what's going on on my PC. If more application developers would make similar decisions, I would have a lot of checkmarks in my tray bar.

2 more cents to the design debate I read up on: Most of your alternatives involved a large nextcloud logo and a small status symbol next to or embedded into it. What about taking the current icons and adding a small nextcloud logo to the side, when the resolution is high enough?

**Comment by brainchild0** [comment]
A common idiom appears to utilize a circle, to convey status information, placed as an overlay in the lower right portion of the icon, occupying about one half of the width and height. The circle is often solid and given a hue even when the icon theme is monochrome, with the particular color indicating the status. For Nextcloud, a red circle might indicate an error. Normal status might be given as a green circle, or indeed none at all. Active synchronization might be shown as a circular pair of arrows. Such a proposal maintains a largely uniform appearance of the main icon as it expresses the application to which it belongs, while adding simple status information that is agreeable to representation in a compressed space.
