### ISSUE TITLE
support Mac OS X 10.11 El Capitain or earlier

### ISSUE THREAD

**Issue by TP75** [nextcloud/desktop#1556]
### Expected behaviour
Nextcloud desktop 2.6+ for Mac OS X / macOS shall support Mac OS X 10.11 El Capitain to enable legacy Mac equipment in continuity of the NC desktop 2.6.0 version.

See the [contribution in the forum](https://help.nextcloud.com/t/help-testing-the-desktop-2-6-1-client-alpha/62584/4) by [forum user LaurentR2D](https://help.nextcloud.com/u/LaurentR2D2) for a more elaborate rationale.

### Actual behaviour
Version 2.6.1rc1 requires at least macOS 10.12 Sierra, unfortunately.

### Client configuration
Client version: _Version 2.6.1rc1 (build 20191018)_

**Comment by misch7** [comment]
Hey,

version 2.6.1 RC1 is built with Qt 5.12.5 to support OpenSSL 1.1.1d (with TLS 1.3). We're currently upgrading the client to support Qt 5.12 on all platforms for security and (framework) bug fixes. Sadly Qt 5.12 requires at least macOS 10.12

Previous builds were linked against Qt 5.9.2 and OpenSSL 1.0.2 which is only supported till the end of this year and will become a major security risk from then on.

Most recent devices running Mac OS X 10.11 El Capitain should support the upgrade to macOS 10.12 High Sierra, and for general security one should consider upgrading the system, see:
https://support.apple.com/kb/SP765

We may consider providing parallel builds with the old Qt and OpenSSL 1.0 till the end of this year, to go with OpenSSL's lifecycle but sadly cannot release security-outdated clients from then anymore.

For more info about Qt's requirements see:
https://doc.qt.io/qt-5.12/supported-platforms.html
https://doc.qt.io/qt-5.12/macos.html

And of course here too, regarding OpenSSL:
> Version 1.1.1 will be supported until 2023-09-11 (LTS).
> [...]
> Version 1.0.2 will be supported until 2019-12-31 (LTS).

https://www.openssl.org/policies/releasestrat.html

Legacy support is one of the things I really in open-source development, but when security needs to be sacrificed for that, an OS upgrade should be the better way ;-/

**Comment by LaurentBechir** [comment]
Does it means that after the end of the year only version 2.6.1 and later will work ? My Mac Pro is too old to support Mac Os 10.12.

**Comment by TP75** [comment]
IMHO one should not camouflage design decisions and human resource plans for development efforts with a term like 'security' as a killer argument.

There is a way OpenSSL 1.1.x is supporting Mac OS X / macOS 10.5 PPC up to 10.14 Intel and beyond, I presume:
- https://ports.macports.org/port/openssl/
- https://www.openssl.org/policies/releasestrat.html

Furthermore, there is LibreSSL with TLS 1.3 support for Mac OS X / macOS available:
- https://www.libressl.org/releases.html
- https://ports.macports.org/port/libressl-devel/summary

The Qt Tool Kit is just another cross-platform framework (headers, data, and libraries) for writing cross-platform GUI-based applications.

**Comment by misch7** [comment]
So then I guess you have just found an opportunity to contribute code to open-source and are welcome to do so. Dig in the Qt documentation and make a modern-SSL capable port for the Mac legacy platforms. I'm curious for results and here to help.

**Comment by TP75** [comment]
In the meantime the kind devs provide a **legacy** PKG for 10.10.+ Macs apparently.

https://github.com/nextcloud/desktop/releases

Hail to the devs of a sustainable code basis and listening to user requests !!
