### ISSUE TITLE
WIN10/NC Client 2.6.0 Share link via context menu takes forever

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/desktop#1558]
### Expected behaviour
File should be shared/Link should be crated

### Actual behaviour
Clicking on the + is spinning the 'busy circle icon' forever

### Steps to reproduce
1. Right click on file in Nextcloud folder
2. Share via Nextcloud > Share options
3. Click the + symbol to create a link

![Bildschirmfoto vom 2019-10-24 11-36-07](https://user-images.githubusercontent.com/25605570/67473762-d0a10a00-f642-11e9-94c0-f8a0ca1b5388.png)

### Client configuration

Operating system: WIN 10 1809

OS language: german

Installation path of client: default

Nextcloud version: 2.6.0stable-Win64

### Server configuration

Nextcloud version: 15.0.11

**Comment by marcosms** [comment]
I notice that this happend only when a password is mandatory to share a file. If you disable the check in the server for this feature, this doesn't happend, but if you want to put a password in a file, the desktop app don't let you do it. It seems that there is a bug in the nextcloud destkop app when you want share files.

**Comment by ericschdt** [comment]
I can confirm this issue on Windows 7 and NC Desktop 2.6.1 + NC17. It's impossible to share a public link within the app or at the website.

**Comment by ericschdt** [comment]
Maybe a duplicate of https://github.com/nextcloud/desktop/issues/1511

**Comment by supremesyntax** [comment]
I think you are right. I am closing this issue to set the focus on #1505
