### ISSUE TITLE
Nextcloud-virtualdrive-techpreview-v2 cannot accept Let's Encrypt SSL cert

### ISSUE THREAD

**Issue by PelleHanses** [nextcloud/desktop#1559]
The preview version 2 of Windows client app virtual drive cannot accept SSL cert from Let's Encrypt.

### Expected behaviour
When I'm connecting to my Nextcloud server via https it should work.

### Actual behaviour
The preview version 2 of Windows client app virtual drive cannot accept SSL cert from Let's Encrypt.

### Steps to reproduce
Start the Windows client virtual drive app v2.
Click on "Log in"
Add an https address  using Letäs Encrypt
You will get a window with the following alternatives (translated from Swedish):
"Choose another URL"
Try unencrypted over HTTP
Configure TLS client cert

### Client configuration
Client version:
Nextcloud-virtualdrive-techpreview-v2

Operating system:
Windows 10

OS language:
Swedish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration
Nextcloud version: 17.0.0

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
`[OCC::Application::setupLogging 	"################## Nextcloud locale:[sv_SE] ui_lang:[] version:[2.5.0techpreview-v2 (build 20190914)] os:[Windows 10 (10.0)]"
[OCC::Application::setupTranslations 	Using "sv_SE" translation
[OCC::SocketApi::SocketApi 	server started, listening at  "\\\\.\\pipe\\ownCloud-xxxxxx"
[OCC::FolderMan::FolderMan 	setting remote poll timer interval to 30000 msec
[OCC::FolderMan::setupFoldersMigration 	Setup folders from  "C:/Users/xxxxx/AppData/Roaming/Nextcloud/folders" (migration)
[OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use system configuration
[unknown 	QObject::connect: Cannot connect (null)::clicked() to OCC::SettingsDialog::accept()
[OCC::ownCloudGui::slotOpenSettingsDialog 	No configured folders yet, starting setup wizard
[unknown 	Could not parse stylesheet of object OCC::OwncloudSetupPage(0x22a68e3fe40, name = "OwncloudSetupPage")
[OCC::WebViewPage::WebViewPage 	Time for a webview!
[unknown 	Please register the custom scheme 'nc' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
[unknown 	Could not parse stylesheet of object OCC::OwncloudSetupPage(0x22a68e3fe40, name = "OwncloudSetupPage")
[unknown 	Could not parse stylesheet of object OCC::OwncloudSetupPage(0x22a68e3fe40, name = "OwncloudSetupPage")
[OCC::SocketApi::slotNewConnection 	New connection QLocalSocket(0x22a690df4a0)
[OCC::OCUpdater::backgroundCheckForUpdate 	Checking for available update
[OCC::AccessManager::createRequest 	2 "" "https://updates.nextcloud.org/client/?version=2.5.0.20190914&platform=win32&oem=Nextcloud&versionsuffix=techpreview-v2" has X-Request-ID "1fdad5bc-18db-4f52-9bce-dab065162aa2"
[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed
[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed
[OCC::OCUpdater::slotVersionInfoArrived 	Failed to reach version check url:  "TLS initialization failed"
[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed
[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed
[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed`

And it is going on writing "[unknown 	QSslSocket::connectToHostEncrypted: TLS initialization failed". The log file are growing to 500MB in a couple of minutes.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by warnerbryce** [comment]
Does your WebServer (Apache or Nginx) have TLS 1.3 enabled ? 
If no, it's normal to have this issue. Virtual Drive Tech Preview V2 works only with a TLS 1.3 connection.

**Comment by duesseldorferjung** [comment]
Facing the same issue and tested my provider on https://www.ssllabs.com and they support TLS 1.3.
Any ideas?

**Comment by fracarvic** [comment]
Same here with nextcloud server 17 behind traefik with TLS1.2 and TLS1.3 enabled, with let's encrypt cert.

Same "TLS initialization error".

**Comment by Dennis360ict** [comment]
same issue. Confirmed TLS1.3 with ssllabs and WS16 als client OS.

**Comment by PelleHanses** [comment]
I can also confirm same problem with TLS 1.3. I have confirmed with ssllabs.com and I get A+ rating.

**Comment by D34DC3N73R** [comment]
Running nextcloud v18 and have the same behavior with tech preview v2. TLS 1.3 is enabled on the server. 

# TLS 1.3 (suites in server-preferred order)
--
TLS_AES_256_GCM_SHA384 (0x1302)   ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_AES_128_GCM_SHA256 (0x1301)   ECDH x25519 (eq. 3072 bits RSA)   FS | 128

**Comment by misch7** [comment]
The old Tech Preview is built using a Qt version without support for OpenSSL 1.1.1 and thus without support for TLS 1.3 as well.

A new Tech Preview is currently in development and the build system already has been updated to support OpenSSL 1.1.1 and our recent regular releases include this (and so are TLS 1.3 capable).

Please stay tuned until a new Virtual Drive build becomes available.

**Comment by D34DC3N73R** [comment]
Are there any updates here? Really looking forward to the new tech preview and I'm not sure if I missed it being released.

**Comment by caesarcxiv** [comment]
https://owncloud.org/news/desktop-client-2-6-release-native-virtual-file-system-on-windows-10/

**Comment by caesarcxiv** [comment]
> https://owncloud.org/news/desktop-client-2-6-release-native-virtual-file-system-on-windows-10/
> 
> looks like owncloud supports it - testing against my nextcloud instance now

It works amazingly! nextcloud - just fork it - skip 2.7 and the UI upgrade and just solve the sync issue - I'll take function over pretty everday .... plus release the msi already

**Comment by er-vin** [comment]
Doesn't apply anymore with the new code base. Please open a new issue if that shows up with latest dailies.
