### ISSUE TITLE
Systray popup text should use primary/secondary text to be more readable in KDE

### ISSUE THREAD

**Issue by mcorteel** [nextcloud/desktop#1562]
### Expected behaviour
On KDE, the systray popup should only show "Nextcloud" as its primary text and the rest (state of each sync) as secondary text.

Here is the KDE Connect systray popup which shows correct secondary text use:
![KDE Connect systray popup](https://user-images.githubusercontent.com/6164603/67621735-13194100-f813-11e9-8f48-6ce4c1f6763a.png)

### Actual behaviour
Everything is displayed as primary, making it very hard to read.
![Nextcloud client systray popup](https://user-images.githubusercontent.com/6164603/67621736-157b9b00-f813-11e9-85b9-1a3e1658e9b0.png)

Note: This issue has always been there, it's nothing new (and I mean since the old days of the first version of the ownCloud desktop client).

### Steps to reproduce
Hover over the nextcloud systray icon in KDE (with several sync folders)

### Client configuration
Client version: 2.6.0
Operating system: Linux
OS language: French
Qt version used by client package: 5.13.1
Client package: OpenSUSE RPM
Installation path of client: /usr/bin/nextcloud

**Comment by mgallien** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
To be even more complete, that would require us to have specific code just to support Linux desktops that provides extended system tray features that are not found anywhere else. We would also need to have a proper detection routine working flawlessly.
