### ISSUE TITLE
Notification popups should be less obnoxious

### ISSUE THREAD

**Issue by Dagefoerde** [nextcloud/desktop#1569]
### Expected behaviour
Please be gentle about displaying notifications and give us a simple way to dismiss them. Right now, if there is a notification at the server, the desktop client (very) frequently displays a notification popup with the headline. It does not tell me what the notification is about, i.e., it does not display anything but the headline. I can only see the text if I log on to the web interface and look at the notification there. Moreover, the notification keeps reappearing unless I log on to the web interface and dismiss it there.

This, in combination with the recent frequency of (official) notifications (namely, nginx configuration, help improve Nextcloud, app recommendation 1, app recommendation 2, etc. all within one week. really?), is very distracting and disrupts my work as I need to perform a number of steps in order to make the notifications go away.

Thanks for any improvements in this regard.

### Actual behaviour

1. Provide a means to read the entire notification on the desktop.
2. Provide the means to dismiss a notification from the desktop.
3. Display the notification less frequently.

### Steps to reproduce
1. Have a notification on the server
2. Use the desktop application for a number of hours

### Client configuration
Client version: 2.6.0git.

Operating system: Ubuntu, with Mate + XMonad

Client package (From Nextcloud or distro) (Linux only): PPA nextcloud-client

### Server configuration

Nextcloud version: 17.0.0

**Comment by bjoernv** [comment]
I use the KDE Plasma desktop. Notifications from most other programs are configurable, so for instance I can hide frequent notification popups. It's unclear, why Nextcloud client notifications are not configurable in KDE Plasma desktop.

**Comment by plutocrat** [comment]
I've had 20 messages today telling me to install Nextcloud Mail, and another 20 to install Nextcloud Talk. Its way too much! Once a week would be sufficient. Or even better if I could acknowledge that I've seen them and I've made a decision not to install them, and don't notify me again.

**Comment by markusdd** [comment]
I also would like to know how to completely switch off all notifications except ones related to file updates.
I do not want ANY app recommendations etc.

**Comment by plutocrat** [comment]
Seems to have calmed down again now. No notifications for a couple of weeks. Maybe it was just a one-off

**Comment by adamrgolf** [comment]
> 
> 
> I also would like to know how to completely switch off all notifications except ones related to file updates.
> I do not want ANY app recommendations etc.

any updates on this? I've disabled the "recommendations" app from the nextcloud admin console, but still get "App Recommendation: " balloon tip popups from the system tray icon for nextcloud on Windows.... It's very annoying and unsolicited.

**Comment by ShamimIslam** [comment]
What version of the nextcloud app are you running? Nextcloud 2.6.2 here and I get the notifaction each time the app starts, once for each account, if the application is not enabled.

**Comment by muramasatheninja** [comment]
Is there a way I can disable all notifications coming from Nextcloud desktop client on KDE. It has way too many notifications. I don't need to see every sync notification when I update a file.

**Comment by ShamimIslam** [comment]
"Show server notifications" in General Setttings?

**Comment by muramasatheninja** [comment]
I have "Show server notifications" unchecked but still get a great deal of bubble notifications from the client in KDE.

**Comment by nicolasfella** [comment]
> I use the KDE Plasma desktop. Notifications from most other programs are configurable, so for instance I can hide frequent notification popups. It's unclear, why Nextcloud client notifications are not configurable in KDE Plasma desktop.
Notifications not being configurable in Plasma has been fixed with !1879

**Comment by DuvelCorp** [comment]
I had to disable the Notifications app because it is out of control. Nextcloud 19.0.2 / Windows10. It's like 5 times a day "A new app is available: calendar" and alike. But I just don't care about it. Telling it one time is enough. Its looks like there's no sense of "Acknowledged" within NextCloud notifications. But when you really see that it is bugged as hell, is when suddenly it display 5 times in a row the same 3 notifications. Extremely annoying !
