### ISSUE TITLE
Feature request: simple interactive resolution of conficts

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#1570]
I think the current handling of conflicts leaves much to be desired from the end user point of view. 
Most users don't know what to do about the Nextcloud icon suddendly switching to yellow, and in the activities list, the conflict is buried far down after a barrage of notifications saying that file xyz is in the ignore list. Further, the UI does not clearly instruct what to do about the conflict. 

If you are lucky and you find the notice, as to which file caused the conflict, you still don't know what to do with it. 

In most cases, the solution is either of the two, either remove the local conflict file, or replace the server file with the local conflict file. It would be great if the desktop client would offer you the choice to do either of the two when it detects a conflict, because else, in my experience, most users never get around to manually solving it, because they simply don't know how. In my experience, even a seemingly trivial task such as delete the first file and rename the second to the name of the first is asking too much of many non-technical users.

**Comment by fhennig** [comment]
I support this idea!

Conflict resolution has become an issue for me recently and so far it is really a pain.  I often don't even notice the conflicts and then find a random conflicted file in a project directory or similar.  Having to think about conflict resolution then is very annoying, I'd much rather have a popup for that.

**Comment by veddox** [comment]
See the discussion at #1195
