### ISSUE TITLE
macOS menu bar icon does not stick to dragged position

### ISSUE THREAD

**Issue by NanoSector** [nextcloud/desktop#1572]
When dragging the menu bar icon to change its position with cmd+drag, the menu bar icon does switch places and stays there.

Restart the nextcloud app however and the menu bar icon moves back to the far left of the menu bar. This is especially annoying with apps like Dozer which hide menu bar icons to the left of their icon, thus the nextcloud icon always becomes hidden after a restart.

### Expected behaviour
The menu bar icon should stick to the place it was dragged to after restarts.

### Actual behaviour
The menu bar icon resets to the leftmost position on the menu bar.

### Steps to reproduce
1. Move the menu bar icon with cmd+drag
2. Restart the desktop client

### Client configuration
Client version: 2.6.0stable

Operating system: macOS Catalina 10.15.1 (19B88)

OS language: English (United Kingdom)

Installation path of client: `/Applications/nextcloud.app`

### Logs
N/A?

**Comment by janprzy** [comment]
That is not a problem with Nextcloud. MacOS simply positions the icons of third-party apps in the order they were started.

If you want to position third-party menu bar apps persistently, look into apps like [Bartender](http://www.macbartender.com) or [Dozer](https://github.com/Mortennn/Dozer)

**Comment by Yoshi2889** [comment]
Please re-read my issue as I specifically mention apps like Dozer always hiding the icon due to this behaviour. Other apps allow their icons to be dragged to a specific position and they will stick there, Nextcloud does not.

**Comment by er-vin** [comment]
> That is not a problem with Nextcloud. MacOS simply positions the icons of third-party apps in the order they were started.

And that's the default Mac behavior we're going to officially support. We're not going to actively support such third party apps as Dozer. Now if someone produces a patch for it: great. Just don't expect this to be solved by the team anytime soon.

**Comment by claucambra** [comment]
The latest versions of macOS no longer impose this restriction and so the issue can be considered resolved. Thanks for reporting!
