### ISSUE TITLE
Windows client crash

### ISSUE THREAD

**Issue by BurningTheSky** [nextcloud/desktop#1575]
### Expected behaviour
Client to sync and stay running

### Actual behaviour
Client crashes randomly

### Steps to reproduce
Have reinstalled client a number of times but it is still crashing

### Client configuration
Client version:
2.6.0.5839

Operating system:
Windows 10

OS language:
English

Installation path of client:
C:\Program Files\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
[OCC::Application::setupLogging 	"################## Nextcloud locale:[en_GB] ui_lang:[en_US] version:[2.6.0stable-Win64 (build 20190927)] os:[Windows 10 (10.0)]"
[OCC::Application::slotParseMessage 	Running for 371.332 sec

Faulting application name: nextcloud.exe, version: 2.6.0.5839, time stamp: 0x5d8e286f
Faulting module name: ntdll.dll, version: 10.0.18362.418, time stamp: 0x99ca0526
Exception code: 0xc0000374
Fault offset: 0x00000000000f9269
Faulting process id: 0x51c4
Faulting application start time: 0x01d590960056a137
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: f5109eb3-1821-4e88-bf98-5f9ebf37cbb1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by gudbergsen** [comment]
Same here!

Version: 2.6.1stable-Win64 (build 20191105)
Windows 10, DA
C:\Program Files (x86)\Nextcloud
