### ISSUE TITLE
Nextcloud Windows desktop client can't stop checking for updates

### ISSUE THREAD

**Issue by sshockley** [nextcloud/desktop#1577]
To cut down on data leakage, I have the outbound Windows Firewall set to block connections unless whitelisted.  The Nextcloud client is only allowed to connect to my Nextcloud server.

On startup, Nextcloud tries to contact download.nextcloud.com and it's blocked.  Unfortunately, it does this more than 70 times per second.  Coupled with logging, this brings my machine to its knees on bootup.

I don't recall exactly when the behavior started, but it's probably within the past six months.

I've worked around this using the suggestion in #1480 but I think this is still a bug.

### Expected behaviour
The Nextcloud client should check the return code to see if the connection is blocked, rather than just blindly retrying.  It should at least have a timer between retries.

### Actual behaviour
Nextcloud client appears to just try to reconnect.

### Steps to reproduce
1. Configure Windows Defender Firewall with Advanced Security to Block on outbound connections 
2. Create a rule for nextcloud.exe to allow it to connect to your server
3. Enable auditing (I believe Auditpol /set /category:"Object Access" /success:enable /failure:enable)
4. Check your Security event logs for event 5157

### Client configuration
Client version: 2.6.0

Operating system:
Windows 10 1709 Enterprise
OS language:
US-English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

**Comment by telephon** [comment]
I can reproduce the same behaviour for the macOS Version (2.6.2stable (build 20191224)). So it is not a Windows-related problem.

Temporarily blocking the client from accessing the server address results in a lot of cpu usage, which also is very irritating. It may cause some users to distrust nextcloud.
