### ISSUE TITLE
Transifex (for all languages): key instead of string

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/desktop#1578]
Please remove the translation request for string "TextLabel", see discussion here:
https://www.transifex.com/nextcloud/nextcloud/translate/#fr/client/184142877

**Comment by rakekniven** [comment]
Source: 

https://github.com/nextcloud/desktop/blob/9d8b8be8d234151667f47e58cd0097a11920c3f8/src/gui/sharelinkwidget.ui#L318

We had similar issues in the past. Cannot find issue at the moment ...

**Comment by rakekniven** [comment]
Found it https://github.com/nextcloud/desktop/pull/1441/

**Comment by joshtrichards** [comment]
Fixed in #1604
