### ISSUE TITLE
share dialog in new client badly designed

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#158]
Hi,

Just looking at the new client, 2.4.x or so, and its new share dialog:
![screenshot_20180131_151448](https://user-images.githubusercontent.com/551757/35627544-7b573dde-0699-11e8-93ce-0dfdb47bfa48.png)
![screenshot_20180131_151503](https://user-images.githubusercontent.com/551757/35627555-8430fe22-0699-11e8-8ed7-368aa48d9ca5.png)
![screenshot_20180131_151613](https://user-images.githubusercontent.com/551757/35627600-ad9ac1c6-0699-11e8-8054-9499df83fe95.png)

This really needs input from @nextcloud/designers ... Perhaps we can sit at FOSDEM and mockup something that looks designed for normal users, not system administrators?

**Comment by tobiasKaminsky** [comment]
Indeed, this is really awful :/

**Comment by jancborchardt** [comment]
Folks, when and why was this changed? :\ Where’s the spec discussion where designers were involved?

Once we introduce a change like this, it is an absolute mess to clean up and roll back. Splitting this into two tabs is exactly the same mistake we did with splitting the Activity view in settings into 3 separate lists. It’s confusing and a mess of an interface – even the amount of options on the link alone.

Please follow the server design on aspects where that exists (like Sharing and Activity), and if there are additions to be made, please always involve @nextcloud/designers in the planning process already.

**Comment by MorrisJobke** [comment]
> Folks, when and why was this changed? :\ Where’s the spec discussion where designers were involved?

It was downstreamed ;)

**Comment by jancborchardt** [comment]
> It was downstreamed ;)

Ugh, ok. Then sorry for the assumption! :) 

Then for clarification @nextcloud/client are we still trying to change as little as possible to make downstreams possible? Cause that share dialog (and the mentioned Activity list in 3 separate tabs) are really some things we could and should improve the design of on our end. :)

**Comment by rullzer** [comment]
@jancborchardt well I haven't look at the code that is moved around. But it is more a question of time (and all the trouble it gives with more downstreamed changes). But in general yes we should be able to fix this. The question is when.

**Comment by camilasan** [comment]
"Perhaps we can sit at FOSDEM and mockup something that looks designed for normal users, not system administrators?" +1

**Comment by jancborchardt** [comment]
@camilasan great idea! :) Let's do that.

**Comment by jancborchardt** [comment]
Here's the mockup for sharing, to combine users and links :)
![](https://cloud.nextcloud.com/s/rg3M3m7SYrW6gXg/preview)
https://cloud.nextcloud.com/s/rg3M3m7SYrW6gXg

**Comment by camilasan** [comment]
From talking to @jancborchardt: the "New share link" will be displayed once the user click in the input "Share".

**Comment by tobiasKaminsky** [comment]
For android and iOS @jancborchardt came up with https://github.com/nextcloud/android/issues/2485, which should be roughly the same as web UI.

**Comment by jospoortvliet** [comment]
Please remember to make sure that file-drop works! In the screenshots above and in the current client, this is not available. It shows the third description under 'download/view' and 'download/view/upload' as "receive files from others without revealing the contents of the folder" but you can't actually choose it.

I suppose the dialog should look as close as possible to the web UI and at least have all the functions:
* copy direct link
* share to user/group/federated/email
* share link
 access options: 
  ( ) read only
  ( ) allow upload and editing
  ( ) file drop (upload only)
 [ ] Password protect
 [ ] Set expiration date

Just like:
 ![screenshot_20180718_132308](https://user-images.githubusercontent.com/551757/42878530-b74b4074-8a8d-11e8-923d-aee896761deb.png)

Some day, tags, comments and activities should be integrated, I suppose...

**Comment by jancborchardt** [comment]
Yes, those options are in what in the mockup above is called "Menu building block", that is the 3-dot popover menu.

And as @pixelipo said in https://github.com/nextcloud/server/issues/6620#issuecomment-337874318

> What about simply having 3 independent (checkbox) items:
> 
> - View (read)
> - Upload
> - Edit

Because we have a lot of people asking for the ability to share a folder with viewing and upload permissions, but not edit (meaning delete). For example if you share a vacation pictures folder with others where you want them to add stuff but not accidentally delete.

**Comment by jospoortvliet** [comment]
The new share dialog is merged, so let's close this.
