### ISSUE TITLE
Broken link in About section [minor bug]

### ISSUE THREAD

**Issue by selivan** [nextcloud/desktop#1588]
### Expected behaviour
Settings - General - About - For more information please click **here**

"here" link should lead to online documentation

### Actual behaviour

"here" link leads to 404 document: https://docs.nextcloud.com/desktop/2.6/

### Steps to reproduce

1. Open Settings from tray icon
2. Open General tab
3. Click on "here" link in "About" section

### Client configuration
Client version: 2.6.1git

Operating system: Ubuntu 18.04 Bionic

OS language: English

Client package (From Nextcloud or distro) (Linux only): nextcloud ppa: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu

**Comment by maltehi** [comment]
This also occurs in the Windows versions 2.6.0stable-Win64 and 2.6.1stable-Win64 on Windows 10 (German).

**Comment by mgallien** [comment]
Sorry for the delay but this is fixed and the link is now working (including the later versions of the client).
