### ISSUE TITLE
Client crash on sharing

### ISSUE THREAD

**Issue by squalo80** [nextcloud/desktop#1589]
### Expected behaviour
When you Right click on a folder inside Windows explorer you could share it

### Actual behaviour
the client crash

### Steps to reproduce
1.open nextcloud folder
2.right click on a file
3.choose share with nextcloud and BOOM it crach

### Client configuration
Client version:  2.6.0stable-Win64 (build 20190927)

Operating system: Windows 10 Pro 64 bit version 1903

OS language: ITA

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 16.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by syzop** [comment]
We have this same issue. I was hoping the new client release from 4 days ago would help, but it still crashes with version 2.6.1stable-Win64 (build 20191105). Nextcloud server is on 16.0.5 (Linux).

Simply right click on a folder in nextcloud, choose Share with nextcloud and then Share options. It crashes with an 0xc0000005 access violation in nextcloud.exe. The client language is Dutch.
We have the same problem on all networks (different images, slightly different Windows 10 versions), about 200+ computers.

Problem did not appear with client 2.3.3, but that version is rather old. We migrated from that version to 2.6.0 a few months ago and then we first encountered the crash bug. As said, 2.6.1 has the same issue.

**Comment by syzop** [comment]
Could this be the same as in owncloud https://github.com/owncloud/client/issues/7044 and thus https://github.com/owncloud/client/commit/3f429da050e4eb3831d347fb8e42c74eed956477 for a fix?
I see the nextcloud code does not have this if !socket check etc.

**Comment by squalo80** [comment]
Could be, but until someone have already tested the solution confirm that, i wait :)

**Comment by syzop** [comment]
My co-worker solved the issue by turning on the following option in the admin webinterface:
[x] Permit users to share using a link
and then the sub-options are all turned off by us.

This fixed the crash issue on the client.

**Comment by squalo80** [comment]
Sorry for my late reply.
I checked this morning on my setup. It looks like that the "turnaround" suggested by @syzop works.
I hope that someone from the development checks it and confirms.

Ciao
