### ISSUE TITLE
What is the Virtual Drive for macOS's status and plan?

### ISSUE THREAD

**Issue by wxiaoguang** [nextcloud/desktop#1591]
https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration/

This blog was posted on January 28, 2019 and said "The Mac version is functional and a build will be available in the coming weeks."

Can we try the macOS desktop client with virtual drive support now? Or what is the plan about?

**Comment by hawai-i** [comment]
Agreed, there were no updates/annoucments for Mac users since then.
A general update on the state of VFS in nextcloud would be nice. Can't wait to use this feature. It would solve a lot of problems for me (using windows).

**Comment by jospoortvliet** [comment]
Hi team,

It's a work-in-progress, as before, I'm afraid. At the last hack weekend the client team got together I believe they agreed to create a pull request with a TODO, so that'll help tracking progress for you all...

**Comment by BRadHoc** [comment]
Can't wait for this, nextcloud desktop in it's current form is quite unusable for me due to the amount of data I have stored on the server and lack of local disk space.

**Comment by InfamousUser** [comment]
Quite unusable, yes.

**Comment by fdzaebel** [comment]
I also Sound love to see this. Of there is a Beta version for testing please let me know.

**Comment by ratnaweera** [comment]
I am thrilled about everything I have seen in the nextcloud universe so far. But I am absolutely puzzled by how a core feature like the "virtual drive" concept is still missing. I would move everything I have on pCloud, Dropbox, google Drive and OneDrive to nextcloud in an instant.... but for this vital missing feature.

What is the timeline on this?

**Comment by derfritz1** [comment]
Is there any new information about this?

**Comment by InfamousUser** [comment]
How nice of somebody to take a notice of this. I should open one for Windows...

**Comment by Adiyogue** [comment]
yes this feature would definitely be key for me! Any updates on this are greatly appreciated...

**Comment by tomalbers** [comment]
Hey Jos! It's me :)
Any plans for this?

**Comment by F3000** [comment]
Any new updates for 2021 ?

**Comment by User-042** [comment]
They seem like they left macOS in the dust. :(

**Comment by pete1019** [comment]
+1

This is essential! Such a cool feature!

**Comment by voarsh2** [comment]
This needs sorting out.

**Comment by FlexW** [comment]
For the current status of the virtual file system on OSX have a look at this [forum post](https://help.nextcloud.com/t/help-test-our-desktop-client/107344).

**Comment by camilasan** [comment]
I will close this ticket since our plan for mac OS is quite concrete and is already in motion.

**Comment by F3000** [comment]
@camilasan what did you mean with “in motion “ ?

**Comment by pete1019** [comment]
@F3000 how about clicking the link from FlexW? You will get all the information there. Then you know why this is closed.

....
"For the current status of the virtual file system on OSX have a look at this forum post."
....

**Comment by F3000** [comment]
> @F3000 how about clicking the link from FlexW? You will get all the information there. Then you know why this is closed.
> 
> ....
> "For the current status of the virtual file system on OSX have a look at this forum post."
> ....

Yesterday I can’t open the link . It works now 👌

**Comment by djoesch** [comment]
Hello, this funcion was essential  for us on changing from Dropbox to Nextcloud. This is not a "nice to have". The expectiation is that Nexcloud is supporting virtual files, even on MacOs.
So maybe you could ask "Dropbox" themselves how they realized it. ;-)

https://help.dropbox.com/de-de/installs-integrations/sync-uploads/smart-sync

What is the special skill a developer must have? Or is it a Apple security certificate stuff thing?
It would be even nice, if ther would be some nerdy information, before we uninstall Nextcloud on our server and go back to Dropbox...

**Comment by pete1019** [comment]
> 

Try this to get Virtual Files (this is how it is called now) for MacOS:

"For people looking to test and play with this on Linux and Mac OS X:
You can set the configuration option in **nextcloud.cfg: showExperimentalOptions=true**"

**Comment by pete1019** [comment]
> 

Where did you try to find it?

Google: mac os "nextcloud.cfg"
Result: https://help.nextcloud.com/t/osx-config-path/26947

$HOME/Library/Preferences/Nextcloud
or
$HOME/Library/Application Support/Nextcloud

If you can not find it then M1 might be special but that would be strange.

**Comment by pete1019** [comment]
> > 
> 
> Where did you try to find it?
> 
> Google: mac os "nextcloud.cfg" Result: https://help.nextcloud.com/t/osx-config-path/26947
> 
> $HOME/Library/Preferences/Nextcloud or $HOME/Library/Application Support/Nextcloud
> 
> If you can not find it then M1 might be special but that would be strange.

@djoesch found it?

**Comment by djoesch** [comment]
Both folders do not exist. I already knew all threads about this issue.

**Comment by r2evans** [comment]
Thanks @pete1019, your cues helped me. *However*, the folders are not apparent in Finder. Odd. (I'm not a macos junkie, using my wife's computer to fix a few things.)

- in Finder, navigated to `Library / Application Support`, and there is no `Nextcloud` subdir
- still in Finder, went to the "MacBook Pro" location (root of the hdd?), navigated to `Users / username`, and there is no `Library` subdir (*really* odd)
- I'm a command-line junkie, so I opened the **Terminal** app; it defaults to the `$HOME` directory, so I just typed `cd "Library/Application\ Support/Nextcloud/` and it worked
- `ls -l` showed the `nextcloud.cfg`; to verify the option had not already been set, `grep -i showExperimental nextcloud.cfg` returned nothing
- used `vim` (more about me being a command-line junkie) and added a line at the end of the `[General]` section that read `showExperimentalOptions=true`, saved and exited the file
- went to the **Nextcloud** desktop app selected `Exit`, then went to **Launchpad** to restart it
- for the account in question (I have only one on this macbook), I opened the three dots on the right and in addition to the typical *"Open folder; Edit Ignored Files; Create new folder; Force sync now; ..."* options, I now see at the bottom *"Enable virtual file support (experimental) ..."*; this presents a modal dialog warning of raining cats and dogs, heck-on-earth, and all sorts of potential disruptions (I'm exaggerating a little, but it is clearly not minor) before allowing me to press a button titled `Enable experimental placeholder mode`
- now, just as in the windows desktop client, each of the folders allows me to control "Availability"

I hope this literal walk-through can help others. (Frankly, if somebody could explain to me why `/Users/username/Library/Application Support/Nextcloud/` *exists* but was not visible in **Finder** ... I would appreciate it a bit, and I'm sure many who believe that the folder does not exist might also appreciate an explanation of how to get to a "not-apparent" folder.

(FYI: macOS Big Sur 11.4, running nextcloud desktop client 3.3.6, connecting to a nextcloud-23.0.0 instance on my home NAS.)

@djoesch I'm not affiliated with NC and am not in a support role, but I hope this offers some context, perhaps an assurance that it is working *somewhere*, and it was not as obvious as one could hope.

**Comment by pete1019** [comment]
@r2evans thanks for the effort.

This might help as well if somebody is more into Finder:
google: macos show invisible files

**Comment by jlfranklin** [comment]
> However, the folders are not apparent in Finder. Odd. (I'm not a macos junkie, using my wife's computer to fix a few things.)

In macOS, the Library folder is where applications store their own data, including everything from preferences to databases to all your emails to browser caches to your downloaded Steam library to the locally stored contents of your Google drive.  It's a lot of data, often one of the three largest folders in your home directory, 100% managed by applications, and generally not for (non-technical) users to go mucking about in.  So, by default macOS hides it from users to keep them from deleting or corrupting their app data because that always ends in tears.

If you're brave, you can expose it in Finder by opening your home directory, pressing Cmd-J to "Show View Options" , and checking "Show Library Folder" at the bottom of the view options window.  ("Show View Options" is also available under the View menu.)
