### ISSUE TITLE
Allow to disable built-in update notification

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/desktop#1594]
I hope this isn't a duplicate, because probably more people encountered that issue already.

### Expected/Actual behaviour
If the desktop client gets updated/a new version is released, I get a notification telling me to update my client. Since the client is installed through my system's package manager, the notification should not appear, as I have to wait until the new version is released by the maintainers of my distribution. A buildflag that disables the built-in update mechanism should solve this problem.

### Steps to reproduce
1. Use a Linux distribution like Archlinux
2. Install the package nextcloud-client
3. Wait for a client update
4. Get a notification to update the client even though I have to wait until the maintainers update it

### Client configuration
- Client version: 2.6.1
- Operating system: Archlinux
- OS language: de_DE
- Qt version used by client package (Linux only, see also Settings dialog): 5.13.2
- Client package (From Nextcloud or distro) (Linux only): nextcloud-client from the Archlinux community repository
- Installation path of client: ?

### Server configuration
Nextcloud version: 17.0.0 (but also happened with previous versions)

**Comment by jaller94** [comment]
Are there any distros setting `skipUpdateCheck=true` system-wide? If there are already distros doing this, it would be on the Arch maintainers to follow along, along with a note for distro maintainers in the Nextcloud Client documentation.

https://docs.nextcloud.com/desktop/2.6/autoupdate.html#preventing-automatic-updates-in-linux-environments

**Comment by KopfKrieg** [comment]
I've hoped for a compile time or system wide option. Sure, a user could set `skipUpdateCheck=true`, but you'd have to do this for every user account on the system. This doesn't feel right (and as far as I know the Archlinux maintainers are usually against the idea of changing user's configuration files through system-wide installed packages). A system wide flag or something similar would probably be better.

**Comment by PureTryOut** [comment]
Just to prevent people from trying it in the future, creating `/etc/Nextcloud/nextcloud.cfg` with the contents

```
[General]
skipUpdateCheck=true
```

does **not** work. After a restart of the client, the notification still appeared for me.

**Comment by pkartsev** [comment]
Thanks for keyword 'nextcloud.cfg'!
(found in the source: 
------------------------
The Nextcloud Client reads a configuration file.  You can locate this configuration file as follows:

On Linux distributions:
        ``$HOME/.config/Nextcloud/nextcloud.cfg``
----------------
So, adding the option in this file worked for me: ~/.config/Nextcloud/nextcloud.cfg

P.S. actually this checkbox should be accessible from GUI configuration page...

**Comment by PureTryOut** [comment]
The problem is that it can't be set system-wide by the package managers. `$HOME/.config/Nextcloud/nextcloud.cfg` will disable the update notification yes, but only for that user and the user will have to make that file themselves. However, distros will want to disable it for them and system-wide, not per user.

**Comment by yan12125** [comment]
The correct path for system-wide configurations is `/etc/Nextcloud/Nextcloud.conf`. It should be properly documented, though.

**Comment by KopfKrieg** [comment]
> The correct path for system-wide configurations is `/etc/Nextcloud/Nextcloud.conf`. It should be properly documented, though.

Oh, good to know. And I see there's already an update for Archlinux available. Awesome!

**Comment by DJCrashdummy** [comment]
...well, but even if you installed the windows-client via a "package manager" like [chocolatey](https://chocolatey.org/packages/nextcloud-client) the notification is just annoying (and for noobs also confusing). :frowning_face:

**Comment by KopfKrieg** [comment]
> ...well, but even if you installed the windows-client via a "package manager" like [chocolatey](https://chocolatey.org/packages/nextcloud-client) the notification is just annoying (and for noobs also confusing). frowning_face

Can't chocolatey also just ship a global configuration file which disables the update notification/check? If it's possible under Linux, why not under Windows too?

Unfortunately I couldn't figure out where this configuration file needs to be. I wanted to update the documentation on it, but the source code is rather hard to read.

**Comment by DJCrashdummy** [comment]
@KopfKrieg thank you for the heads-up and the link!

before posting my first comment i also had a quick look for an existing `nextcloud.cfg` under windows, but no luck... :unamused: 

i can't tell you if it is possible that the "package manager" disables the update notification, i hardly use windows and therefore chocolatey (just supporting a few noobs), but i opened an issue (https://github.com/aronovgj/choco-auto/issues/37) to ping the package maintainer.
all i can tell about chocolatey is, that they they are just scripting the installation of existing packages and not building them from source, which should not necessary in this case.

**Comment by TheCakeIsNaOH** [comment]
Hi,

I'm the maintainer of the `nextcloud-client` Chocolatey package.

The package is currently using the `.msi` installers, and by default passes `SKIPAUTOUPDATE="1"`, which should disable the update notification. So the update check should be disabled for versions 3.0.3 and newer.

**Comment by FlexW** [comment]
Does the issue still apply? If yes, please reopen it.

**Comment by xucian** [comment]
is there any config for windows too? I installed it manually, not via choco
