### ISSUE TITLE
AppImage: Have to log on to nextcloud accounts on each programme start

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#1595]
# Expected behaviour

The appimage should behave just like a native nextcloud client and automatically log on on restart.

### Actual behaviour

On each programme start, the client is logged out and wants me to log in again.

### Steps to reproduce
1. set up nextcloud accounts with the regular nextcloud client
2. Download the Appimage
3. Launch the Nextcloud AppImage

### Client configuration
Client version: Version 2.6.0stable (build 20190927). 
Gebaut von der GIT-Revision e0b32c auf Sep 27 2019, 15:13:34 verwendet Qt 5.12.1, OpenSSL 1.0.2g 1 Mar 2016

Operating system: Debian GNU Linux Buster (AppImage)

OS language: de_DE

Qt version used by client package (Linux only, see also Settings dialog):  5.12.1

Client package (From Nextcloud or distro) (Linux only): Appimage

Installation path of client: /usr/local/bin/Nextcloud-2.6.0-x86_64.AppImage

### Server c

Four differnent accounts, three of them Nextcloud 17.1. Issue occurs with all of them. 

Nextcloud version:

17.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

Gist at: https://gist.github.com/vasyugan/481e298e0bf31152c07f153050b9d258

**Comment by misch7** [comment]
Did you also try the newer 2.6.1 release?
https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.6.1-x86_64.AppImage

I just installed a fresh Debian 10 VM with GNOME and it works, we integrated libsecret support into the 2.6.1 AppImage.

**Comment by misch7** [comment]
Closing this here to keep everything in one issue, please see: https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811

**Comment by RastaTaz** [comment]
Same here, using the appimage client on Ubuntu 24.04 and Enlighentment as desktop (configured to load gnome services on login - it is asking my user password to keyring when session starts): I still have to go through the browser login/grant to allow the client to connect to the server.
=> That's quite annoying and not very user-friendly...
![Image](https://github.com/user-attachments/assets/62ee437b-82dd-48b5-bc39-a94f8a948360)
