### ISSUE TITLE
Please add Flatpak Support

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [nextcloud/desktop#1598]
### Expected behaviour
The development team provides an official Flatpak version of the client, which is automatically updated and maintained. This can be provided via flathub.org, for example.
Or as a direct link on the following page: https://nextcloud.com/install/#install-clients
An official version is important to me, because the security of my system is also very important to me.

### Actual behaviour
The current problem for me is that there is no official Flatpak version of the Nextcloud client. Since my Linux distribution is more than seriously considering building its package base on Flatpak, I'm afraid that I'm going to be disconnected with my Nextcloud solution soon because the packages are not available. Security and up-to-date status of libraries used in unofficial packages is also not guaranteed.

**Comment by Derkades** [comment]
While not ideal, you'll still be able to use the AppImage

**Comment by e-alfred** [comment]
Why do you think the Nextcloud Flatpak is not maintained by official Nextcloud people?

The version you can find here is maintained by @juliushaertl:

https://flathub.org/apps/details/org.nextcloud.Nextcloud
https://github.com/flathub/org.nextcloud.Nextcloud/graphs/contributors/

**Comment by freechelmi** [comment]
Really nice to have a first community maintained flatpak version of the nextcloud client, can we report bugs here about it ?

**Comment by juliushaertl** [comment]
Please report flatpak related bugs to https://github.com/flathub/org.nextcloud.Nextcloud if they seem related to the client code they should to here of course.

Let's close this since a flatpak build is available

**Comment by 4jNsY6fCVqZv** [comment]
@juliushaertl The inquiry was not about the availability of a flatpack in general, but about an official package, which is offered and maintained by Nextcloud itself.
I assume that there is no official package, because none is offered for download https://nextcloud.com/install/#install-clients
In addition, there is nothing written about Nextcloud at https://flathub.org/apps/details/org.nextcloud in the "Developers" section.
On flathub.org anyone can post any package. Even without asking the projects why I prefer an official package. Of course this can be distributed on flathub as well.

**Comment by 4jNsY6fCVqZv** [comment]
There is another problem with publishing via Flathub. Flathub is a platform that also offers proprietary packages. Since I switched to Linux to only find free software in my Software Center, installing the Nextcloud Flatpak unfortunately takes me away from this goal. When I install an app via Flathub, the proprietary apps I don't want are suddenly displayed in my Software Center. I don't want that. Therefore I ask you to offer an official version for download via your website as an alternative for people who are looking for 100% Free Software.

**Comment by tilosp** [comment]
@4jNsY6fCVqZv https://github.com/flathub/flathub/issues/691 would solve this

**Comment by 4jNsY6fCVqZv** [comment]
@tilosp Thanks for the link and your feedback! I came across it during my research.  In fact, that would be a solution to my concerns. However, since there hasn't been any activity in this direction for over a year and no milestone or developer or label has been assigned to this good idea, I'd rather ask you directly. For something to happen. Could you imagine realizing that as Nextcloud?@camilasan

**Comment by mgallien** [comment]
> There is another problem with publishing via Flathub. Flathub is a platform that also offers proprietary packages. Since I switched to Linux to only find free software in my Software Center, installing the Nextcloud Flatpak unfortunately takes me away from this goal. When I install an app via Flathub, the proprietary apps I don't want are suddenly displayed in my Software Center. I don't want that. Therefore I ask you to offer an official version for download via your website as an alternative for people who are looking for 100% Free Software.

Please ask to the person maintaining your Software Center an option to hide the software depending on their license.
I am already very happy that someone is maintaining this flathub package for the community. Let's be grateful !
