### ISSUE TITLE
tray icon to large

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#16]
See the screenshot:

![tray](https://user-images.githubusercontent.com/1589737/31675962-7096533e-b366-11e7-8a97-ad890beeb5e4.png)

The icon is to big compared to all the other icons.

cc @jancborchardt we discussed this in Berlin as well.

**Comment by jancborchardt** [comment]
Ref https://github.com/nextcloud/client_theming/issues/201 – @rullzer when I fix it, should it go here or the theming repo?

**Comment by MegaV0lt** [comment]
Why not using the lying "8" instead the checkmark?

**Comment by rullzer** [comment]
@jancborchardt I'm moving over the theme. So here will be fine then.

**Comment by rullzer** [comment]
@jancborchardt work your magic!

**Comment by camilasan** [comment]
is it done @rullzer @jancborchardt ?

**Comment by skjnldsv** [comment]
Agreed. We need a small border :)
![capture d ecran_2018-05-23_12-46-42](https://user-images.githubusercontent.com/14975046/40420092-8210832e-5e87-11e8-8043-ce0d4d3b744c.png)

**Comment by juliushaertl** [comment]
@alexanderdd might prepare a PR with the icons discussed in  https://github.com/nextcloud/client_theming/issues/196#issuecomment-368575575
