### ISSUE TITLE
2.6.1 Client broke images in explorer sync folder

### ISSUE THREAD

**Issue by koschei293** [nextcloud/desktop#1600]
![image (5)](https://user-images.githubusercontent.com/31357239/68672750-50940300-0563-11ea-919b-9340b039a95d.png)
Nexcloud client 2.6.1 stable
Windows 10 1809-1903
Nexcloud server 16.0.3

Update was from client 2.5
delete old -> install new

**Comment by mgallien** [comment]
As I only understanding English, could you please try to explain more what is the problem.
I am not sure but I will try to sum up your bug:
 * you have upgraded from 2.5 to 2.6.1
 * there are some files that have become unreadable

In any case please consider the following:
Make sure you are running the latest recommended version of the desktop client and of the server. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
