### ISSUE TITLE
Continuous high CPU usage (~15%) in all versions

### ISSUE THREAD

**Issue by tobizviz** [nextcloud/desktop#1601]
The NextCloud desktop client will consume 15% CPU continuously on start until you open a webview (e.g., Account -> Add new -> Register with provider) and then close it.
I have experienced this bug since initially installing at version 2.5 (now 2.6.1). It really doesn't seem like it should be hard to fix.

My OS: Window 7. My Qt Version: 5.12.5.

**Comment by dkohtes** [comment]
On Mac it is depending on an active sync. If all sync are inactive CPU usage is low again.

**Comment by dkohtes** [comment]
BTW, opening a webview didn't change anything on CPU usage on Mac OS 10.15.1

**Comment by nursoda** [comment]
https://github.com/nextcloud/desktop/issues/1513

**Comment by misch7** [comment]
Indeed, duplicate of #1513.
