### ISSUE TITLE
Re-enable translation for installer & add traditional chinese

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#1603]
Currently we do not upgrade our installer translation files:
https://github.com/nextcloud/desktop/tree/master/admin/win/nsi/l10n

We should add this again to transifex and add traditional chinese, as we only support simplified chinese.

**Comment by misch7** [comment]
Let's talk about this next week.

**Comment by FlexW** [comment]
@tobiasKaminsky Does this still apply?

**Comment by tobiasKaminsky** [comment]
NSI is the old installer ".exe", right?
As we do not do this any longer, we do not need this.
(we do might need this for certain customers, so we cannot get rid of nsi currently)
