### ISSUE TITLE
Enforce password protection

### ISSUE THREAD

**Issue by Xman2o** [nextcloud/desktop#1616]
With active Enforce password protection share over Windows client not possible

Release loop in the client

**Comment by kesselb** [comment]
Moved this over to the desktop repository. Would you mind to add https://github.com/nextcloud/desktop/blob/master/.github/issue_template.md to your post? Without it's a bit hard to reproduce / fix. Thanks :+1:

**Comment by supremesyntax** [comment]
Possible duplicate of #1505
