### ISSUE TITLE
Create visible feedback about stopped synchronization after copying large folders

### ISSUE THREAD

**Issue by RREE** [nextcloud/desktop#1618]
### Expected behaviour
A moved big folder in Windows explorer should be visible after the moving operation.

I propose two changes to Nextcloud:

1. Nextcloud must not interfere in the correct working of Windows (or any other OS). Especially it must not stop any file or folder copying or display.
2. If the synchonization is stopped for any reason (e.g. because a folder is too big), not only show it in the Nextcloud window, but also create an OS notification that the user will see.

### Actual behaviour
I support a hosted nextcloud installation for a small architecture office. We have different synchronization folders for active projects (Documents/Akquise_Kunde) and for closed projects (Documents/Archive). One of the architects moved a project folder from the active folder to the archive folder by Windows mouse drag&drop today. The size of the folder was about 1GB which exceeds the configured limit for synchronization of 500MB.

The architect called me for support as the project folder was removed from the origin folder but was not yet visible in the target folder of the Windows explorer. He was worried that he had completely lost all project data. Windows search did not find any of the project files (his claim, I did not verify).

When I opend the Nextcloud window it stated in the bottom line that one of the folders was too big for synchonization (the lost project folder). I clicked on the button to confirm that everything should be synchonized. After that click Windows showed the project folder in the target location with the blue overlay icon indicating that a sychronization was going on.

The architect lost at least one hour of his valuable working time and he lost faith in the correct working of Nextcloud and Windows. 

### Steps to reproduce
1. Have at least two synchronized folders configured in the client
2. Move a big subfolder between the two configured synchonized folders (big means bigger than the configured synchonization limit)
3. Do not look at the Nextcloud client window, i.e. minimize it to the tray
4. Monitor the target location of the big move in Windows explorer. The moved folder does not show up if the user does not confirm the synchonization in the NExtcloud client window. 

### Client configuration
2.5.1

Operating system:
Windows 10

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version:
17.0

Storage backend (external storage):

### Logs
Not available

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

There has been significant changes in the sync engine since this issue was opened.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
