### ISSUE TITLE
File conflict resolved still showed until log file is deleted manually

### ISSUE THREAD

**Issue by Fantu** [nextcloud/desktop#1628]
Server Nextcloud 17.0.1 on debian 10
Client Nextcloud 2.6.1 in windows 7 64 bit

Hi, when there are file conflicts still show warning even if resolved and the only way I found to "solve" it was close the client, delete "<folder sync name>_sync.log" file, restart the client.
From a fast look and test seems that actually the client for windows (I not tried linux client for now) parsing and listing full "<folder sync name>_sync.log" file entries without option to limit view to warning and error only, empty/rotate log files option (or at least I not found it)
Even if developer side that I think is considered as features request for normal users to which we will give Nextcloud to use syncing big folders with many files scrolling hundreds of thousands or millions of entries for view warning/errors and show warning/error still solved is an issue.

Is there a way to do easy/fast at least the add of option to rotate/clean the log and another option to show only warning/error entries?

Thanks for any reply and sorry for my bad english.

**Comment by lemmy04** [comment]
hm, for me it is usually enough to quit the client, manually resolve the conflict, and start the client - which of course is not what I want to be doing.
If I wanted that kind of manual intervention, I could just sync my stuff to my local fileserver with unison.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?

**Comment by Fantu** [comment]
Retried now on client version 3.2.1 and the issue is not reproducible, so should be solved, thanks
