### ISSUE TITLE
macOS: When moving a folder into a Nextcloud directory, files within subfolders will not sync

### ISSUE THREAD

**Issue by briankendall** [nextcloud/desktop#1630]
This is quite a serious bug, especially since macOS bundles will not sync correctly when they're moved into the Nextcloud directory.

### Expected behaviour
When moving a folder into my Nextcloud directory, all files contained with subfolders should be synced.

### Actual behaviour
Any files contained within a subdirectory are not synced

### Steps to reproduce
1. Setup Nextcloud desktop in macOS (has been reproduced in 10.14.6)
2. Execute the following terminal commands to create a folder with a subdirectory and some files and move it into the Nextcloud directory, replacing `/path/to/Nextcloud` with the path of the Nextcloud directory:

        mkdir test
        echo data > test/file.txt
        mkdir test/subdir
        echo moredata > test/subdir/missing_file1.txt
        echo stillmoredata > test/subdir/missing_file2.txt
        mv test /path/to/Nextcloud

3. Wait for Nextcloud Desktop to sync
4. Use the Nextcloud web interface to see what files were actually synced
5. Note that `missing_file1.txt` and `missing_file2.txt` are not synced!

### Some more noteworthy info:

This appears to be a macOS only bug. I cannot reproduce it in Windows. (I have not tried in Linux.)

Moving `test` into the Nextcloud directory using the Finder also triggers the bug.

I can work around the bug by copying a folder into my Nextcloud directory instead of moving it.

I can also force Nextcloud to sync the missing files by using `touch` to change their modification dates, e.g.: `find /path/to/Nextcloud/test -exec touch {} \;`

### Client configuration
Client version: Version 2.6.1stable (build 20191105).

Operating system: macOS 10.14.6

OS language: English

Installation path of client: /Applications/nextcloud.app

### Server configuration
**Nextcloud version:** NextcloudPi docker v1.17.1

### Logs

1. Client logfile:

https://gist.github.com/briankendall/f0b926010333211d1166fea48abd58dd
Contents of log directly after moving `test` into the root of my Nextcloud directory. (Server URL has been redacted. Path to my Nextcloud directory has been replaced with `/path/to/Nextcloud`.)

2. Web server error log: 

`/var/log/apache2/error.log` contains no recent entries, including for today

`/var/log/apache2/nc-error.log` contains no recent entries, and nothing is logged when I trigger the bug

Here are the lines that appear in `nc-access.log` when I trigger the bug by moving `test` into the root of my Nextcloud directory: https://gist.github.com/briankendall/199aed9e42b9bafc934e0c81677818f5

3. Server logfile: nextcloud log (data/nextcloud.log):

The following gets added to `nextcloud.log` when I move `test` into the root of my Nextcloud directory: https://gist.github.com/briankendall/da6347d9cb1da16f72e014ca99b17087

**Comment by manuelstuder** [comment]
Can confirm that the issue also exists on my mac:
macOS 10.15.2
Nextcloud client: 2.6.2stable (build 20191224)

**Comment by jbrrrr** [comment]
Can confirm this issue! I think it's quite a severe bug and needs some attention!

I found this problem when analysing issues with deleted files in nextcloud (files deleted in storage, but still shown in browser -> files do exist in filecache table, but do not exist in storage). All macOS environment.
This bug may be one reason for these often seen and very annoying problem, which cause broken syncs.

More Info:
If nested folders are moved in finder into the synced nextcloud folder:
'nested_folder/nested_folder1/nested_folder2/nested_folder3/files' -> synced is only 'nested_folder/nested_folder1/' (only first subfolder without content)
When the folder containing subfolders and data is copied (instead of moved) everything works as it should.

APFS?

Client: macOS 10.14.6 (same problem macOS 10.13)
Nextcloud Client: Version 2.6.2stable (build 20191224)
Nextcloud Server: Nextcloud 17.0.2 (Same problem Nextcloud 16.0.7)

**Comment by briankendall** [comment]
For what it's worth, I've also reproduced this issue in macOS 10.12.6 with an HFS+ formatted drive, so it's not specifically an issue with APFS.

I don't mean to be pushy, but I really hope we get some response from the devs about this soon. This is a really, really critical bug that makes Nextcloud downright _dangerous_ to use in macOS. Just moving any file that's a bundle, be it an application, framework, a project file from something like Xcode or Logic Pro X, or just a simple folder will cause syncing to fail with no clear way to fix it. If someone doesn't realize what's going on and god forbid deletes the complete version of an improperly synced folder or bundle they may experience significant data loss.

**Comment by tschuele** [comment]
I've had the same issue. Could any of the developers please give an update?

**Comment by jbrrrr** [comment]
By the way: A simple restart of the sync client solves the problem. [quit and start]
This is probably the reason why this bug does not lead to large data losses. After a restart of the client(-computer), the incomplete synchronization will be performed correctly again.

Additional info:
SyncClient Version 2.3.3 (build 4) (macOS 10.13.6) works without errors.
