### ISSUE TITLE
German initial config screen layout problems

### ISSUE THREAD

**Issue by cbxnet-ali** [nextcloud/desktop#1631]
### Expected behaviour
User opens config screen and everythings works and looks right

### Actual behaviour
one options has no effect, another is not shown due to broken layout

### Steps to reproduce
1. create first nextcloud account in client
2. goto later config page (see screenshots)

### Client configuration
Client version:

Operating system: Win10

OS language: German
Installation path of client: Default

![image](https://user-images.githubusercontent.com/45972057/69235115-f7465800-0b90-11ea-8e96-6fcb45c0cf6d.png)

- The first 500 mb value is not stored in the config.
- The second line misses a configurable value, but looks like there has to be one.

**Comment by FlexW** [comment]
@cbxnet-ali Could you please test with a more recent version (3.2.2)? If the issue is resolved, please close it.

**Comment by cbxnet-ali** [comment]
It is fixed now. Thanks for the heads-up.
