### ISSUE TITLE
Incorrect syntax in Content-Type header charset

### ISSUE THREAD

**Issue by pmetras** [nextcloud/desktop#1632]
### Expected behaviour
The nextcloud client software on Linux should use a correct charset syntax (without quotes) in the `Content-Type` header. This would not raise ModSecurity alerts on the web server...

### Actual behaviour
On linux, the client sends the header `Content-Type: application/xml; charset="utf-8"` in `PROPFIND` requests.

It should be `Content-Type: application/xml; charset=utf-8` (see. https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17)

This behaviour raises alarms in ModSecurity + OWASP CRS 3.1 rules.

### Steps to reproduce
1. Use the client on Linux and check the web server logs showing content type data.

### Client configuration
Client version: Not available for the moment. Will complete later.

Operating system: Linux Debian buster 10.2 on server; Ubuntu 18.04 on client

OS language: en_CA.UTF-8

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client:

### Server configuration

Nextcloud version: 16

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

Not available for the moment; will complete later.

2. Web server error log:

Apache access log
```
192.168.1.189 - - [2019-11-20 07:37:50.633454] "PROPFIND /cloud/remote.php/dav/ HTTP/1.1" 207 647 "-" "Evolution/3.28.5" "application/xml; charset=\"utf-8\"" 59368 www.example.com 192.168.1.6 443 proxy:unix:/run/php/php7.3-fpm.sock|fcgi://localhost - - "-" XdUznilwWLAdC8h3WDT@kwAAAFM TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 878 2325 -% 4831787 - - - - - - -
```

Apache error log with ModSecurity error
```
[2019-11-20 07:37:50.635830] [-:error] 192.168.1.189:59368 XdUznilwWLAdC8h3WDT@kwAAAFM [client 192.168.1.189] ModSecurity: Warning. Match of "rx ^%{tx.allowed_request_content_type_charset}$" against "TX:1" required. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1044"] [id "920480"] [msg "Request content type charset is not allowed by policy"] [data "\\x22utf-8\\x22"] [severity "CRITICAL"] [ver "OWASP_CRS/3.1.0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/CONTENT_TYPE_CHARSET"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"] [hostname "www.example.com"] [uri "/cloud/remote.php/dav/"] [unique_id "XdUznilwWLAdC8h3WDT@kwAAAFM"]
```

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by jlfranklin** [comment]
This looks like a bug in Evolution, not Nextcloud.  While this bug report is useful for other NC users running into the same thing, it should be reported to either the [Debian bug tracker](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=evolution-data-server) or the main [Gnome Evolution project](https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues).

**Comment by mgallien** [comment]
indeed @jlfranklin , I am closing it
