### ISSUE TITLE
Problem with IPv6: no connection

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#1633]
- have a setup to our internal cloud
- log out
- enable IPv6
- log in -> works
- then I see "time out"

If I do the same, but disable IPv6 with:
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6

then I can connect & sync files.

Using:
2.6.1 from Arch repo: Gebaut von der git-Revision 5adbc0 auf Nov 6 2019, 01:47:23 verwendet Qt 5.13.2, OpenSSL 1.1.1d 10 Sep 2019

**Comment by Peac** [comment]
I have a Nextcloud server with IPv6 and no connection issues. I also double-checked, that the client (version 2.6.1) uses IPv6.
