### ISSUE TITLE
Per-folder-sync-connection .sync-exclude.lst not respected?

### ISSUE THREAD

**Issue by rpasing** [nextcloud/desktop#1635]
### Expected behaviour
If an entry like '*.key' is present in a folder sync connections .sync-exclude.lst, all files matching that pattern should not be synchronised.

### Actual behaviour
Those files are being synchronised!

### Steps to reproduce
1. Add a new (i.e. empty on both remote and local) folder sync connection to Nextcloud desktop client. View the folder in your Nextcloud Web UI and on your local filesystem. Folder should be empty on both sides (expect the sync-statusfiles locally).
2. Right click in the desktop client on that sync connection -> Edit Ignored Files -> Add an entry '*.key'
3. Locally create 'foo.key' file in the synchronized folder, e.g. `echo bar > foo.key`
4. Take a look at the Nextcloud desktop client tab 'Activity' -> foo.key is being synchronised!
5. Take a look at your Nextcloud Web UI -> foo.key is there!

### Client configuration
Client version:
2.6.1

Operating system:
Arch Linux

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.13.2

Client package (From Nextcloud or distro) (Linux only):
Arch Linux package nextcloud-client https://www.archlinux.org/packages/community/x86_64/nextcloud-client/

### Server configuration
Nextcloud version: 
17.0.1

### Logs

Client logfile:
https://gist.github.com/rpasing/ab111ce141ef65537b6531cec3e6f0fe

$ cat .sync-exclude.lst
> *.key

**Comment by PhrozenByte** [comment]
Same issue here.

Nextcloud 16.0.6
Nextcloud Desktop Client 2.6.1git on Ubuntu 18.04 using `ppa:nextcloud-devs/client`

**Comment by doits** [comment]
:+1: Same for me, Nextcloud Server 17.0.2 and Nextcloud Desktop Mac 2.6.2rc1

**Comment by doits** [comment]
I just found out that you need to restart the client in order to catch up changes. Then it seems to respect them.

**Comment by ianp1** [comment]
I don't know if this is related, but for me the .sync-exclude.lst files are ignored after restarting Nextcloud desktop client. If i quickly restart the synchronization after the application starts, the excludes work just fine (at least for me).
Can you confirm that?

I'm using 2.6.2stable on Linux Mint 19

**Comment by actonDev** [comment]
@ianp1 2.6.2stable on Windows 10 and that worked
I had the problem that the `.sync-exclude.lst` it wasn't being respected but after restarting the application it works

**Comment by iaian7** [comment]
I'm having similar issues with the per-account file ignore list too (the one created through the Nextcloud client interface for a specific account, and saved as a .sync-exclude.lst file to the root of the synced folder).

Sounds like it's potentially the same issue, but I've submitted the bug here just in case: https://github.com/nextcloud/desktop/issues/1875

**Comment by 360path** [comment]
> I just found out that you need to restart the client in order to catch up changes. Then it seems to respect them.

Same for me. I had to restart the client for it to respect the ignore list.

**Comment by iaian7** [comment]
Restarting the client refreshes the list, and it'll work for a bit, eventually stops referencing the list. Somewhere between 20 minutes and 20 hours after restarting, the client starts uploading all of the files it was supposed to ignore.

**Comment by 360path** [comment]
> Restarting the client refreshes the list, and it'll work for a bit, but eventually stops referencing the list. Somewhere between 20 minutes and 20 hours after restarting, the client starts uploading all of the files it was supposed to ignore.

I'll wait another 12 hours to see if the behaviour described by you comes up. So far the ignore list is working.

**Comment by doits** [comment]
FYI I have similar problems to @iaian7: It *seems* to work after restarting the client but after some time all files get uploaded anyways.

**Comment by 360path** [comment]
After 7 days the ignore list is still working for me after restart of the client and meanwhile also after restart of the system.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?
