### ISSUE TITLE
.sync-exclude.lst in subfolder overrides the one from parent folder?

### ISSUE THREAD

**Issue by jsaraiva** [nextcloud/desktop#1636]
### Expected behaviour
The .sync-exclude.lst from a subfolder should _add_ to the excludes from parent folder(s). If a parent folder excludes "node_modules/", for example, it should be excluded from subfolders too, even if they define their own exclude rules.

### Actual behaviour
The subfolder's excludes completely override/ignore the excludes from parent folder(s).

### Steps to reproduce
1. Create a folder (e.g., "source"). In that folder, add an exclude for "node_modules/".
2. Within "source", create a subfolder (e.g., "MyProject"). In that subfolder, add another exclude (e.g., "log/"). 
3. Create a "node_modules" folder within "MyProject", and fill it with some content (an empty text file, or something like that).
4. The node_modules folder _and_ its contents are not ignored from synchronization.

### Client configuration
Client version: 2.6.1stable (build 20191105)

Operating system: macOS 10.14.6

OS language: English

### Server configuration

Nextcloud version: 17.0.1

**Comment by jsaraiva** [comment]
Another easy way to verify this is that .DS_Store files located in folders with .sync-excludes.lst are synchronized (completely disregarding the global excludes).

**Comment by rpasing** [comment]
Are you sure your excludes are working at all?
I got problems with them not working at all, see #1637 - can you maybe help me out there?

**Comment by jsaraiva** [comment]
Yes, the excludes are working. My "node_modules" global exclusion rule, for example, works in all folders that do not have a .sync-excludes.lst file, which are then "overwriting" that global exclusion rule.
The problem is simple: excludes in a specific folder discard all excludes from parent folders, _and_ even from the exclusion list that comes out-of-the-box for the sync client.

As for your problem, I offered a suggestion in your issue.

**Comment by rpasing** [comment]
Yeah, I linked the wrong issue, my issue is #1635 and not #1637 :D 

What I meant was: Are you sure that the per-folder exclusion list is working? The global one is working, I know, but is the per-folder one working at all?

**Comment by jsaraiva** [comment]
Some rules apparently work, others don't:

tmp/
log/
^- These seem to work

public/packs/
^- This one apparently doesn't work

**Comment by iaian7** [comment]
I've tested "folder/" format exclusion, and it only works temporarily. Eventually, be it 10 minutes or 20 hours, the Nextcloud client will sync the "ignored" files to the server. Bug submitted here: https://github.com/nextcloud/desktop/issues/1875
