### ISSUE TITLE
sync issues

### ISSUE THREAD

**Issue by jookk** [nextcloud/desktop#1637]
Nextcloud v17.0.1
Debian buster
PHP 7.3.11
Apache 2.4.38
max upload size is set to 10gb

error log from nc:

[webdav] Fatal: Sabre\DAV\Exception\BadRequest: Expected filesize of 9549302 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 49152 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side. at <<closure>>

0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1130
   OCA\DAV\Connector\Sabre\File->put("*** sensitive parameter replaced ***")
1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 513
   Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
2. <<closure>>
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
3. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
6. /var/www/nextcloud/apps/dav/lib/Server.php line 317
   Sabre\DAV\Server->exec()
7. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
8. /var/www/nextcloud/remote.php line 163
   undefinedundefinedrequire_once("/var/www/nextcloud ... p")

PUT /remote.php/dav/files/user/dir/subdir/file.epub
from 192.168.1.1 by user at 2019-11-22T16:00:34+01:00

file is not synced. Nextcloud desktop is red with notice, that connection is expired. Later it is trying to sync again, and again with no success.

**Comment by jsaraiva** [comment]
Maybe try disabling Apache's mod_reqtimeout module?

[https://github.com/nextcloud/server/issues/9471](https://github.com/nextcloud/server/issues/9471)

**Comment by jookk** [comment]
unformately, didnt fixed issue. I disabled mod_reqtimeout, but still the same.

**Comment by stemy2** [comment]
I have a similar problem, i have totally random "connection expired" problems with no other message. And it's not related to the file size, the problematic file can be smaller than other files that passed like a charm.

**Comment by stemy2** [comment]
The bug is still there.

**Comment by stemy2** [comment]
Sorry, but the problem is still there.

**Comment by FlexW** [comment]
@stemy2 Please provide us with instructions on how to reproduce the issue. Otherwise, it won't get fixed.
