### ISSUE TITLE
Nextcloud MacOSX client accesses the keychain continuously

### ISSUE THREAD

**Issue by IMEIICCID** [nextcloud/desktop#1639]
By coincidence I noticed that **the client accesses the keychain continuously**. This is very unpleasant and causes unnecessary traffic in the operating system.
With the program FSmonitor this can be observed very well. 
It would be good if this bug could be fixed.
Many thanks in advance.

### Client configuration

Client 2.6.1stable (build 20191105)

Please try to only report a bug if it happens with the latest version
The latest version can be seen by checking https://download.nextcloud.com/desktop/
For support try our forums: https://help.nextcloud.com
--->

Operating system:
MacOSX Sierra 10.12.6.
OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
/Applications/nextcloud.app

### Logs
MacOSX Log:
https://gist.github.com/IMEIICCID/f0668fff9e53d4055d0f7dcd15e0652b

**Comment by doits** [comment]
Looks like this is the root cause for #1638, see https://github.com/nextcloud/desktop/issues/1638#issuecomment-559463721 for a trace of some syscalls.

**Comment by misch7** [comment]
Duplicate, please see: #1638
