### ISSUE TITLE
Closing notifications in the settings dialog should immediately close them

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#164]
Currently when you close a notification, it shows in super small text on the left »Closing in a few seconds«. It’s very confusing that it even takes time to close it.

Regardless if there needs to be a request sent to the server and verified etc, the notification should immediately vanish from the interface. Even if it’s not instantly gone per se, we need to lie here, otherwise the system seems slow.

**Comment by tobiasKaminsky** [comment]
If the "dismiss call" fails for any reason, just show this particular notification again.

**Comment by nickvergessen** [comment]
#117 and #133 should solve the issue in most cases....

**Comment by aslmx** [comment]
Shall i open a new issue, or is this issue here also taking action on the fact that the Notification constantly re-appears and really bothers a lot...

**Comment by nickvergessen** [comment]
It's already being dealt with.

**Comment by camilasan** [comment]
The dismiss button has been fixed.

**Comment by jancborchardt** [comment]
This is not about it not working – it did work. It’s about the amount of time it takes to actually vanish the notification, which was 1–2 seconds. Instead it should vanish immediately (can re-appear on error).

**Comment by er-vin** [comment]
This looks like it doesn't apply anymore with the new GUI.
