### ISSUE TITLE
End-to-End Encryption Missing Documentation

### ISSUE THREAD

**Issue by frake65** [nextcloud/desktop#1643]
### Expected behaviour
Documentation should at least give minimal configuration information about end-to-end encryption. We are not talking about security by obusfacation here, are we?

### Actual behaviour
I could not find out, which files to restore from TimeMachine after breakdown of my system - so I lost my End-To-End 12-word. There is a subfolder "<user>/Library/Application Support/nextcloud", but none of the files there gave me information about end-to-end encryption.
There is also $HOME/Library/Preferences/Nextcloud/nextcloud.cfg - but no clue, if the certificate information has anything to do with end-to-end-encryption.
[Nextcloud desktop client documentation](https://docs.nextcloud.com/desktop/2.6/) does not even mention end-to-end encryption.

### Steps to reproduce
nothing specific. - Just install nextcloud client from scratch.

### Client configuration
Client version:
2.6.1

Operating system:
Mac OS 10.15.1

Nextcloud version:
17.0.1

**Comment by mgallien** [comment]
End-to-End encryption needs your passphrase to decode the encrypted keys that are stored by the server. It is usually stored in Mac OS keychain.

Indeed, documentation needs improvement. Let's focus this issue on that and just that.

Note that Github isn't a support portal. We provide support to customers only. Github is our developer platform. If you're not a customer you can ask the community for help on [help.nextcloud.com](help.nextcloud.com).We of course try to deal with bugs as quick as we can, but it can take time as we have lots of other things on our plate. You are welcome to contribute to this free and open source product, to submit patches that fix bugs for example. We try to respond quickly to pull request from contributors.

**Comment by joshtrichards** [comment]
Fixed in #3136 

Also the `end_to_end_encryption` app recently gained a greatly expanded README: https://github.com/nextcloud/end_to_end_encryption/blob/master/README.md
