### ISSUE TITLE
Allow Client SSL certificate Authentication against the web server.

### ISSUE THREAD

**Issue by daniel-ferradal-marquez** [nextcloud/desktop#1648]
Suggestion: It would be great to be able to choose a personal certificate or that the desktop client asks for a client SSL certificate when the http server asks for one for added security.

### Expected behaviour
At configuration, when specifying the server, client should prompt to choose personal certificate if server demands one.

### Actual behaviour
Client just seem to be connecting to the server until it times out.

### Steps to reproduce
1. Install desktop client
2. Specify server to connect
3. Wait for client timeout

### Client configuration
Client version:
Nextcloud-2.6.1-x86_64.AppImage

Operating system:
Linux (Kubuntu 19.10).

OS language:

Qt version used by client package (Linux only, see also Settings dialog):
Linux distro has 5.12.4.

Client package (From Nextcloud or distro) (Linux only):
Nextcloud-2.6.1-x86_64.AppImage

Installation path of client:
~/.local/bin/Nextcloud-2.6.1-x86_64.AppImage

### Server configuration
Without SSL client auth connection works, so nextcloud server configuration does not apply.

Regarding the http server (apache) in the SSL virtualhost:
SSLCACertificateFile /path/to/allowed-cas.pem
SSLVerifyClient require

### Logs
Nextcloud-desktop output:
[OCC::FolderMan::setupFoldersMigration  Setup folders from  "/home/nextcloud-user/.config/Nextcloud/folders" (migration)
[OCC::ClientProxy::setupQtProxyFromConfig       Set proxy configuration to use the prefered system proxy for http tcp connections
[OCC::ownCloudGui::slotOpenSettingsDialog       No configured folders yet, starting setup wizard
[OCC::WebViewPage::WebViewPage  Time for a webview!
[unknown        Please register the custom scheme 'nc' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
[OCC::OCUpdater::backgroundCheckForUpdate       Checking for available update
[OCC::AccessManager::createRequest      2 "" "https://updates.nextcloud.org/client/?client=RGlzdHJpYnV0b3IgSUQ6CVVidW50dQpEZXNjcmlwdGlvbjoJVWJ1bnR1IDE5LjEwClJlbGVhc2U6CTE5LjEwCkNvZGVuYW1lOgllb2FuCg%3D%3D&version=2.6.1.20191104&platform=linux&oem=Nextcloud&versionsuffix=stable" has X-Request-ID "c0796c94-6ec8-4fda-b157-cdb9a92e26fe"
[OCC::PassiveUpdateNotifier::versionInfoArrived         Client is on latest version!
[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone    No system proxy set by OS
[OCC::AccessManager::createRequest      2 "" "https://nextcloud.example.com:4443/status.php" has X-Request-ID "5b375b0e-de05-4eb0-9838-194cfa52aee7"
[OCC::AbstractNetworkJob::start         OCC::CheckServerJob created for "https://nextcloud.example.com" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::AbstractNetworkJob::slotTimeout   Network job timeout QUrl("https://nextcloud.example.com:4443/status.php")
[OCC::CheckServerJob::onTimedOut        TIMEOUT
[unknown        QIODevice::write (QSslSocket): device not open
[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone    No system proxy set by OS
[OCC::AccessManager::createRequest      2 "" "https://nextcloud.example.com:4443/status.php" has X-Request-ID "69934ff9-3091-4d3e-bebf-79a41c46682c"
[OCC::AbstractNetworkJob::start         OCC::CheckServerJob created for "https://nextcloud.example.com" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished  status.php returns:  QJsonDocument({"edition":"","extendedSupport":false,"installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Daniel Cloud","version":"17.0.0.9","versionstring":"17.0.0"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x5579afb69300)
[OCC::DetermineAuthTypeJob::start       Determining auth type for QUrl("https://nextcloud.example.com:4443/remote.php/webdav/")
[OCC::AccessManager::createRequest      2 "" "https://nextcloud.example.com:4443/remote.php/webdav/" has X-Request-ID "ee31e75a-66a4-47d9-ac91-446b7ea07bb7"
[OCC::AbstractNetworkJob::start         OCC::SimpleNetworkJob created for "https://nextcloud.example.com" + "" "OCC::Account"
[OCC::AccessManager::createRequest      6 "PROPFIND" "https://nextcloud.example.com:4443/remote.php/webdav/" has X-Request-ID "7deb0839-bdb0-46d3-a82c-3f2de9a4bf6f"
[OCC::AbstractNetworkJob::start         OCC::SimpleNetworkJob created for "https://nextcloud.example.com" + "" "OCC::Account"
[OCC::AbstractNetworkJob::slotFinished  QNetworkReply::ProtocolFailure "Server requires that HTTP/1.1 be used instead of HTTP/2." QVariant(Invalid)
[unknown        stream 3 finished with error: "Server requires that HTTP/1.1 be used instead of HTTP/2."
[OCC::AbstractNetworkJob::slotFinished  QNetworkReply::ProtocolFailure "Server requires that HTTP/1.1 be used instead of HTTP/2." QVariant(Invalid)
[OCC::DetermineAuthTypeJob::start()::<lambda    Did not receive WWW-Authenticate reply to auth-test PROPFIND
[OCC::DetermineAuthTypeJob::checkBothDone       Auth type for QUrl("https://nextcloud.example.com:4443/remote.php/webdav/") is 4
[OCC::AccessManager::createRequest      4 "" "https://nextcloud.example.com:4443/index.php/login/v2" has X-Request-ID "c8949e9c-bca2-4315-9982-2375135a8a2c"
[OCC::AbstractNetworkJob::start         OCC::SimpleNetworkJob created for "https://nextcloud.example.com" + "" "OCC::Account"
[unknown        stream 5 finished with error: "Server requires that HTTP/1.1 be used instead of HTTP/2."
[OCC::AbstractNetworkJob::slotFinished  QNetworkReply::ProtocolFailure "Server requires that HTTP/1.1 be used instead of HTTP/2." QVariant(Invalid)
[OCC::Flow2Auth::openBrowser()::<lambda         Error when getting the loginUrl QJsonObject({"error":null,"login":null}) "There was an error accessing the 'token' endpoint: <br><em>Server requires that HTTP/1.1 be used instead of HTTP/2.</em>"
[unknown        stream 1 finished with error: "Server requires that HTTP/1.1 be used instead of HTTP/2."

**Comment by wdehoog** [comment]
For our server (uses client certificates) it already works this way. The client asks for the certificate when we create the account.
Unfortunately there is a bug related to the size of the certificate keys so we cannot use this feature yet.

Your logs suggest the client already gets access without a certificate:
``` 
QJsonDocument({"edition":"","extendedSupport":false,"installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Daniel Cloud","version":"17.0.0.9","versionstring":"17.0.0"}) 
``` 
I think you will have to take a look at the configuration of your site.
