### ISSUE TITLE
l10n: Combine strings using plural handling

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#1649]
https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L457

https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L459

Please combine this two strings to one and use plural handling.
Currently we have two strings at Transifex. Both have singular/plural form which does not make any sense.

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/156989422?q=issue%3Aopen

**Comment by rakekniven** [comment]
Same for more strings regarding hour and minutes.

**Comment by rakekniven** [comment]
Hello, Any update on this?

**Comment by rakekniven** [comment]
Second occurence:

https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L469

https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L471

Third occurence:

https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L484

https://github.com/nextcloud/desktop/blob/6a9f155856d421adf2b2aae3c638bac5de34fcc8/src/common/utility.cpp#L486

Please have a look.

**Comment by rakekniven** [comment]
Hello @misch7 @camilasan 
can someone please have a look? We have 6 issues for that at Transifex.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
