### ISSUE TITLE
Desktop notification about new notifications is not actionable

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#165]
![screen shot 2018-02-02 at 18 44 10](https://user-images.githubusercontent.com/925062/35747441-9828aff8-084a-11e8-875e-b15c65043196.png)

Several problems here:
- It seems clickable but it’s not. Clicking the notification should open the settings dialog, focused on the activity tab.
- It’s absolutely unclear what this is about. Should ideally show the most recent notification and »and 8 more«
- We use »notification(s)« even though we totally know how many there are. We can do better. ;)

Better wording would be:
> **Update to Nextcloud 13 available**
> And 8 other notifications from cloud.nextcloud.com

(No need to say »from servername« when there is only one account configured.)

**Comment by juliushaertl** [comment]
I think we really should just push one notification for each one from the server with the actual message in it. Summarizing the notifications only leads to an additional step, where the user needs to open Nextcloud in the browser. At least the freedesktop notification spec also allows to add actions to them, so there should be an option to dismiss, open or any other action specified in the server notification. No idea how that works on Windows/macOS but I guess there are similar APIs for that as well. 

https://developer.gnome.org/notification-spec/ for reference.

**Comment by jancborchardt** [comment]
Sounds good too @juliushaertl. The OS should do grouping.

**Comment by shtrom** [comment]
Same for Windows: a single notification with “You received x notifications” is pretty useless.

**Comment by jospoortvliet** [comment]
long fixed ;-)
