### ISSUE TITLE
nextcloud: relocation error: nextcloud: symbol malloc version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference

### ISSUE THREAD

**Issue by Victor-Morel** [nextcloud/desktop#1653]
### Expected behaviour
Nextcloud launches

### Actual behaviour
Nextcloud doesn't launch, and I got the following message: 

`nextcloud: relocation error: nextcloud: symbol malloc version Qt_5 not defined in file libQt5WebEngineCore.so.5 with link time reference`

### Steps to reproduce
1. Launch Nextcloud
2.
3.

### Client configuration
Client version: 2.7, and 2.6 before that

Operating system:
Debian Sid

**Comment by Q-Storm** [comment]
I have the same issue. Do you need any more package or system information?

**Comment by er-vin** [comment]
Yes indeed more information would be needed. At a glance it looks like a packaging issue could well be gone.

@ivaradi ? Does it ring any bell to you?

**Comment by Q-Storm** [comment]
I cannot reproduce the problem anymore.

**Comment by Victor-Morel** [comment]
Ditto for me

**Comment by er-vin** [comment]
OK, let's close it then. Thanks for reporting.
