### ISSUE TITLE
No menu bar icon in Gnome 3.34 (with extension to show these)

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/desktop#1656]
### Expected behaviour
Using the TopIcons Plus extension for gnome-shell, I expected to see a nextcloud-client icon in the gnome top panel (like the other icons, which are shown by the extension in the top panel, like Rambox). 

### Actual behaviour
There is no icon in the top panel. The issue started by updating from Fedora 30 to 31 and thus updating from client version 2.5.x to 2.6. I reinstalled the nextcloud-client package already.

### Client configuration

Operating system: Fedora 31, 64 bit

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.12.5

Client package (From Nextcloud or distro) (Linux only): 2.6.1

Installation path of client: default distro path

### Logs

Logs produced by nextcloud-client in journalctl:
```
... nextcloud[2706]: QSocketNotifier: Can only be used with threads started with QThread
```
I see this line several times.

**Comment by pomarec** [comment]
FYI I have the same behaviour as you but the same log as https://github.com/nextcloud/desktop/issues/1818

**Comment by rmeissn** [comment]
Update: Meanwhile I upgraded to Fedora 32, Nextcloud-Client v2.6.4 (using QT v5.13.2) and also tried several other gnome-shell extensions to show tray icons in the top bar. There is no change in behaviour and the Nextcloud-Client icon is still missing.

**Comment by rmader** [comment]
FTR: on Fedora, QT apps use the Wayland backend by default now. TopIcons Plus only shows legacy X11 tray icon - the now-universally-agreed-on-but-somewhat-standard successor is KStatusNotifierItem/AppIndicator and the extension for that is https://extensions.gnome.org/extension/615/appindicator-support/ - which is installed by default on Ubuntu. That *should* work (although in my case I see a wrong icon, which is the reason I stumbled over this bug).

**Comment by rmeissn** [comment]
The mentioned extension by @rmader works after a system reboot. Thus it seems to be a gnome-shell extension bug.
