### ISSUE TITLE
Help me ? build window not work? 

### ISSUE THREAD

**Issue by phamducthinhdev** [nextcloud/desktop#1658]
Hi IT community nextcloud, I am having 1 problem of building nextcloud desktop window 10. OpenSSL is not getting the library
![2](https://user-images.githubusercontent.com/27260441/70017824-c6194f00-15b6-11ea-87f0-47477557f863.PNG)
![3](https://user-images.githubusercontent.com/27260441/70017825-c6b1e580-15b6-11ea-8f79-13248c0488d5.PNG)

I had set path

set PATH="C:\Program Files\CMake\bin\";%PATH%
set PATH="C:\Program Files\OpenSSL-Win64\bin\";%PATH%
set PATH="C:\qtkeychain";%PATH%
set PATH="C:\zlib";%PATH%

**Comment by misch7** [comment]
Hey @phamducthinhdev Have you seen our build repo for the Windows client?

https://github.com/nextcloud/client-building/

This is how we create the daily builds and releases, maybe the script there can help you to get a clue if you compare them with your build instructions :)

Here is also another recent issue which could be helpful for you: #1652

**Comment by phamducthinhdev** [comment]
Thanks you

Vào 12:44, Th 3, 3 thg 12, 2019 Michael Schuster <notifications@github.com>
đã viết:
