### ISSUE TITLE
Error: DATA on invalid stream

### ISSUE THREAD

**Issue by acsfer** [nextcloud/desktop#1659]
### Client configuration
Client version:
2.6.1

Operating system:
Windows 10 x64

OS language:
French

Qt version used by client package (Linux only, see also Settings dialog):
5.12.5

### Server configuration

Nextcloud version:
17.0.1

Storage backend (external storage):
Object Storage (S3 compatible)

### Logs
1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
![image](https://user-images.githubusercontent.com/12234510/70041617-c9640900-15bd-11ea-8dc4-985595e80d06.png)

2. Web server error log:
Empty

3. Server logfile: nextcloud log (data/nextcloud.log):
Empty

See also, for reference: https://help.nextcloud.com/t/data-on-invalid-stream-huh/57082

**Comment by samotar** [comment]
I'm encountering the same issue running server 17.0.1 (no access to web server logs here sadly) and Windows-client 2.6.1. Tested 2.7.0.6114-daily-20191202 as well. Using the same client versions and syncing the same files from another Nextcloud instance running server 15.0.13 there are no problems whatsoever. I fail to recognize a pattern between the affected files as well. Just one example from the client logfile:

`||backup/Internal-Storage/Download/01_uebungsblatt_textverstaendnis_m6.pdf|INST_NEW|Down|1530955429|b971847121aa05a04c52be2cde4598ec|31014|00015372oc441rj4ycyv|2|DATA on invalid stream|0|0|0||||`

**Comment by andreapx** [comment]
I have this problem too.

**Comment by wiwie** [comment]
I encounter this problem also with Nextcloud 18.0.1; with the linux as well as the Windows client.

**Comment by st0ne** [comment]
Same here in windows, linux and mac.
But with webinterface it is working...

Also running with S3 object storage.
