### ISSUE TITLE
Linux client constantly re-adds folders to file manager

### ISSUE THREAD

**Issue by toxpal** [nextcloud/desktop#1661]
```
Version 2.6.1git. For more information please click here.
This release was supplied by Nextcloud GmbH
Built from Git revision 5adbc0 on Nov 6 2019, 01:47:23 using Qt 5.13.2, OpenSSL 1.1.1d 10 Sep 2019
```
Manjaro KDE with default file explorer (Dolphin). in NC client, I set option "_Show sync folders in Explorer's Navigation Pane_" to **disabled**. Despite that, NC adds synced folders every time. Even if I manually remove them from file manager, NC client re-adds them within next launch of NC client.

Even worse - I have only one folder synced, but NC adds the same folder to file explorer multiple times. See example here - https://i.postimg.cc/9QhwV70N/files.png

Also, I found another bug while posting this bug :) If I check/uncheck "_Show sync folders in Explorer's Navigation Pane_" box several times (like chec/uncheck every second or so), NC client crashes between 5th-10th (un)check. No error messages, it just quits.

**Comment by ml-** [comment]
I stumbled upon the crash a while ago:
https://bugs.archlinux.org/task/64630#comment183980

The maintainer of the packages fixed it with this commit:
https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/nextcloud-client&id=9de94fc7083d0c5b327ea01e09a89d953f8b5569

Commit message
> The option "Show sync folders in Explorer's Navigation Pane" is supposed to
> be hidden on non-Windows platforms, but there is a bug.

His quick and dirty patch, which is **NOT** suitable for upstream.
```diff
diff --git a/src/gui/generalsettings.cpp b/src/gui/generalsettings.cpp
index 62381d36d..c69592c82 100644
--- a/src/gui/generalsettings.cpp
+++ b/src/gui/generalsettings.cpp
@@ -91,6 +91,7 @@ GeneralSettings::GeneralSettings(QWidget *parent)
     #else
         if (QOperatingSystemVersion::current() < QOperatingSystemVersion::Windows10)
     #endif
+#else
             _ui->showInExplorerNavigationPaneCheckBox->setVisible(false);
 #endif
```
Would be nice if a contributor could have a look at this and eventually disable the checkbox for all non-Windows machines.

**Comment by toxpal** [comment]
> Would be nice if a contributor could have a look at this and eventually disable the checkbox for all non-Windows machines.

Yes, that would be nice to have. In other hand, it would also be nice if this option works with Linux because I clearly see that NC can add folders to Linux file explorer without any problems, so it should be possible to disable this feature for non-Windows machines too.

**Comment by mgallien** [comment]
We already have a fix that does the same thing in the latest release. Closing the bug.
If you test and there is still an issue, please open a new one.
