### ISSUE TITLE
Possible directory name escaping issue with owncloud server

### ISSUE THREAD

**Issue by btittelbach** [nextcloud/desktop#1663]
Operating system: Linux / Ubuntu

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 2.5.3git

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop 2.5.3-1      amd64

Installation path of client: default dpkg install path

### Server configuration
Nextcloud version: none / Owncloud 10.3.1.1

Storage backend (external storage): None

## Disclaimer

- This is just something I noticed and wanted to mention. Sorry for not investigating this in more depth at the moment
- I only noticed it when syncing with an additional owncloud instance with the nextcloud-desktop and could not reproduce it quickly when syncing with a nextcloud-server, so feel free to ignore and close this issue if you feel it does not apply

## Issue

If a sync-connection from an owncloud instance contains a folder that contains a "&" (and possibly also ',' ) character in it's name, nextcloud-desktop fails to correctly check the checksum of the files in this folder and will always try to update them again and again, even though the file-contents are completely identical.

It seems to be a bug, since it works perfectly fine with all other folders.

**Comment by mgallien** [comment]
We do not support running the Nextcloud desktop client with anything except Nextcloud server. Sorry
