### ISSUE TITLE
Linux client cannot connect to a site with a Certificate having a non-matching name - Problem for split hosting model

### ISSUE THREAD

**Issue by user23498723452** [nextcloud/desktop#1665]
Please go read my previous issue (almost a year old) which describes this.    As well as the snippet below from #758 

https://github.com/nextcloud/desktop/issues/997

> This commit only appears to be addressing CA related issues,  but there are often hostname issues for clients such as those using self-signed certs, or accessing the legi certificate via private IP address - which is not supported in any certificate.
> 
> Please expand the errors that are supported to include hostname issues!  See my issue at https://github.com/nextcloud/desktop/issues/997 
> 
> Please add in the CertificateCommonNameInvalid error!
> 
> _Originally posted by @user23498723452 in https://github.com/nextcloud/desktop/pull/758#issuecomment-453787413_

**Comment by user23498723452** [comment]
It appears that the current nextcloud-devs PPA fixes this issue.
**BUT** I'm waiting for some clarity at https://github.com/nextcloud/desktop/issues/997#issuecomment-562964364_

**Comment by mgallien** [comment]
Is this still reproducible ?
