### ISSUE TITLE
Nextcloud-client-nautilus causing nautilus to hang on start

### ISSUE THREAD

**Issue by Chadsr** [nextcloud/desktop#1667]
### Expected behaviour
Nautilus opens with Nextcloud-client-nautilus running.

### Actual behaviour
nautilus hangs with output:
```
Initializing Nextcloud-client-nautilus extension
Using python version sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

Issuing a keyboard interrupt during this hang results in nautilus starting up and call  stack as follows:
```
  File "/usr/lib/python3.7/site-packages/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 143, in _handle_notify
    self._remainder += self._sock.recv(1024)
```

After which nautilus proceeds to work as expected...

### Steps to reproduce
1. Open nautilus file manager with `nextcloud-client` installed
2. Witness the above behaviour
3. Issue a ctl-c keyboard interrupt
4. Get the above mentioned output, followed by nautilus functioning again

This doesn't seem to cause a hang every time and I haven't figure out why that is the case, yet.

### Client configuration
Client version: `2.6.1git`

Operating system: Manjaro (`5.4.0-1-MANJARO`)

OS language: `en_US.UTF-8`

Qt version used by client package (Linux only, see also Settings dialog): `Using Qt 5.13.2, built against Qt 5.13.2`

Client package (From Nextcloud or distro) (Linux only): `nextcloud-client`

Installation path of client:
```
whereis nextcloud

nextcloud: /usr/bin/nextcloud /usr/lib/nextcloud /usr/share/nextcloud /usr/share/man/man1/nextcloud.1.gz
```
### Logs

After restarting nextcloud client with `nextcloud --logwindow`, the behaviour seems to have stopped. So now I am slightly confused and will update this section if/when it happens again.

**Comment by Chadsr** [comment]
I'm still constantly encountering this issue. It's definitely caused by the nextcloud client, as when I quit it, Nautilus will un-hang itself.

**Comment by FlexW** [comment]
I'm not able to reproduce the issue. Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.

**Comment by evdcush** [comment]
I encounter this issue every time I invoke `nautilus` from the terminal.

```
$ nextcloud --version
qt5ct: using qt5ct plugin
Nextcloud version 2.6.2-1build1
Using Qt 5.12.8, built against Qt 5.12.5
Using 'OpenSSL 1.1.1f  31 Mar 2020'
```

Example:

```
$ nautilus .
Initializing Nextcloud-client-nautilus extension
Using python version sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
^C^C^C^C^C^C
```

At which point I just kill the terminal tab.

---

System info:

```
# OS: 
Ubuntu 20.04.4

# Kernel: 
x86_64 Linux 5.13.0-51-generic

# DE: 
GNOME 3.36.5
```
