### ISSUE TITLE
Client crashes when removing external HDD

### ISSUE THREAD

**Issue by pgrm** [nextcloud/desktop#167]
I couldn't find any existing issue describing this behavior:

1. Add a folder from an external HDD or USB stick to be synchronized.
2. While it's syncing, unplug said device (no safe removal in windows, just unplug)
3. You'll see an error saying that the nextcloud client crashed
4. Restart nextcloud it works without problems (It shows error, that it's unable to find local sync folder, that's fine)
5. Plug external HDD or USB back into the computer, syncing starts again without problems

Everything in this chain seems to work correctly, except that nextcloud crashes when the external device is removed. I could reproduce it quite reliably. I understand that it might be quite tough to handle, since a lot of read and write operations might fail suddenly, but still, the whole application shouldn't crash or?

This is the dialog I see:

![image](https://user-images.githubusercontent.com/713456/35941673-58a425f8-0c53-11e8-8664-7fd1778f2f9c.png)

I already sent the report once or twice, just wanted to explain exactly how I got to the error here as well

**Comment by camilasan** [comment]
Hi! "Send this report" is not working atm. Sorry.
So, please, could you check for the client logs? Also which version are you running? Which OS? 
Thanks!
