### ISSUE TITLE
Client interfers with storing data in kwallet

### ISSUE THREAD

**Issue by bussec** [nextcloud/desktop#1670]
### Expected behaviour
Nextcloud-client should not influence data entries in the kwallet outside of the "Nextcloud" folder.

### Actual behaviour
As long as nextcloud-client is running, all changes to "Maps" entries in kwallet non-Nextcloud folders are written into "Nextcloud/Maps". The original entries remain unchanged.

### Steps to reproduce
1. Start kwalletmanager
2. Create a new folder "foo"
2. Create a new entry "bar" in "foo/Maps"
3. Create a new key:value pair in "bar" ("password","123456")
4. Save the entry
5. Go to "Nextcloud/Maps", you should find an entry "bar" there.
6. Go back to "foo/Maps", the entry "bar" exists, but it does not contain any data

### Client configuration
Client version:
2.6.1 (Issue does not occur with 2.5.2)

Operating system:
GNU/Linux (Fedora 30)

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.12.5

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client-2.6.1-1.fc30.x86_64 

Installation path of client: 
/usr/bin

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

**Comment by bussec** [comment]
The issue does not occur with version 3.1.3 (Git revision 3842d306f950f631482d29466b52667eb2073f1f) from nextcloud-client-3.1.3-1.fc33.x86_64 (Fedora 33).
