### ISSUE TITLE
Unable to use Windows' ShellExecute on Nextcloud folders

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [nextcloud/desktop#1671]
### Expected behaviour
Emacs has a wrapper around Win32' ShellExecute function, which can be used to open
files using the default file associations (among other tasks). The code is here
http://git.savannah.gnu.org/cgit/emacs.git/plain/src/w32fns.c I cut the code below

When I use this function on a standard file, such as a PDF or a Word file, Windows
will look for the file type and launch the program that handles that type. Except if
the file resides in a Nextcloud folder, in which case nothing happens.

An excerpt of the code used to call ShellExecuteW (using unicode strings).

      shexinfo_w.cbSize = sizeof (shexinfo_w);
      shexinfo_w.fMask =
	SEE_MASK_INVOKEIDLIST | SEE_MASK_FLAG_DDEWAIT | SEE_MASK_FLAG_NO_UI;
      shexinfo_w.hwnd = NULL;
      shexinfo_w.lpVerb = ops_w;
      shexinfo_w.lpFile = doc_w;
      shexinfo_w.lpParameters = params_w;
      shexinfo_w.lpDirectory = current_dir_w;
      shexinfo_w.nShow =
	(FIXNUMP (show_flag) ? XFIXNUM (show_flag) : SW_SHOWDEFAULT);
      success = ShellExecuteExW (&shexinfo_w);

### Actual behaviour

Nothing happens. However, if I switch off Nextcloud, the file is opened with the default
file associated to it.

### Steps to reproduce
1. Place a pdf file inside a Nextcloud folder. Say it is c:\Nextcloud\document.pdf
2. Install Emacs
3. Launch Emacs as "emacs -q -eval '(w32-shell-execute "open" "c:\\Nextcloud\\document.pdf")'
4. Nothing happens
5. Disable Nextcloud (quit it) and repeat step 3.
6. The PDF file is opened with Adobe, Edge or any other PDF browser that is the default one

### Client configuration
Client version: Version 2.6 1stable-Win64 (build 20191105)

Operating system: Windows 10

OS language: Spanish

### Logs

    [OCC::SocketApi::slotReadSocket 	Received SocketAPI message <-- "open:C:\\Users\\juanj\\Nextcloud\\1906 R4.pdf" from QLocalSocket(0x1a41cab8cb0)
    [OCC::SocketApi::slotReadSocket 	The command is not supported by this version of the client: "open" with argument: "C:\\Users\\juanj\\Nextcloud\\1906 R4.pdf"

**Comment by misch7** [comment]
Related to #1599 -> same cause, let's discuss it there.
