### ISSUE TITLE
Very Very small interface

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/desktop#1672]
Hello, 

I have an Hidpi problem : 

![image](https://user-images.githubusercontent.com/1949622/70450978-e6f50f00-1aa4-11ea-8ef5-a0759920c040.png)

### Expected behaviour
look more huge

### Actual behaviour
very small

Version 2.6.1

**Comment by FlexW** [comment]
Does the issue still persist with the newest version (3.1.1)?

**Comment by ad1rie1** [comment]
not dear
