### ISSUE TITLE
user manual is difficult to read

### ISSUE THREAD

**Issue by axd1967** [nextcloud/desktop#1673]
The color choice of the web user manual is wrong: contrast is too low between soft blue and white.

https://docs.nextcloud.com/desktop/2.6/index.html :

![image](https://user-images.githubusercontent.com/3529789/70461741-a18f0c80-1ab9-11ea-8cee-026d0234c929.png)

Please make the font a bit thicker, don't force me to override my fonts in my browser. 

Compare this with the rtd docs:

https://docs.nextcloud.com/server/17/user_manual/
![image](https://user-images.githubusercontent.com/3529789/70461876-f3379700-1ab9-11ea-8a9e-9515cdadb4f5.png)

Much better!

**Comment by cieska** [comment]
I guess that you are viewing this on Firefox? There on the web many articles about this that web uses Google Fonts that not nicely rendering on Firefox. At least I guess so.

**Comment by sirtoobii** [comment]
Can confirm on Firefox 68.3 (ESR, Linux). @cieska As far I can see there are no google fonts on the docs page.

**Comment by Rello** [comment]
closing as tracked here
https://github.com/nextcloud/desktop/pull/6854
