### ISSUE TITLE
Files are automatically overwritten eliminating recent changes

### ISSUE THREAD

**Issue by tschuele** [nextcloud/desktop#1676]
### Expected behaviour
No changes to files if they are not modified.

### Actual behaviour
From time to time, files are "automatically" reverted to a previous version, thus eliminating recent changes. Background: It happened at least twice to me that the activity log showed changes of some files by other users. However, when I looked at the files, it turned out they were in an old state and my additions were lost. In both cases, the users assured me that they didn't touch the files.

### Steps to reproduce
Hard to reproduce, general behavior:
1. File x is in version 1
2. File x is modified by user a, resuling in version 2
3. Activity log shows that user b has modified file x
4. File x has the same content as version 1, user b is not aware of any changes

### Client configuration
Client version:

Operating system: Windows / Mac

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 17.0.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?
