### ISSUE TITLE
Suppress ignored file warnings in log and per-account ignored file settings

### ISSUE THREAD

**Issue by jmsmdy** [nextcloud/desktop#1680]
**Background:** I use Nextcloud to sync a lot of LaTeX documents. When *.tex files are compiled, they can generate a lot of auxiliary files like *.aux, *.log, *.blg, which are used to speed up compilation, debugging, and other purposes. Because of the way they are generated, if Nextcloud happens to sync when a LaTeX document is being compiled, it often throws a conflict error with these files. I assume this is because they are written to multiple times during the compilation process which messes up the synchronization. I expect this issue would be very difficult to solve in a general way by changing the Nextcloud sync procedure, so I haven't submitted a bug report about this. Instead, I just added *.aux, *.log, and *.blg to the ignored files list. Since they are only useful as local files anyway, this isn't a problem for me.

**Issue:** My Nextcloud log is now filled with hundreds of "This file is listed on the ignore list" warnings. If there ever is a genuine conflict, the Nextcloud client makes it very difficult to actually find it. There is no way in the client interface to search the log, and no way to display only conflicts / serious errors. Even scrolling through to find a conflict is difficult, because the icon for "This file is on the ignore list" and "This file has a conflict" are the same.

**Suggested feature:** Give an option in the client settings to suppress warnings about ignored files, or else categorize/sort the warnings by severity. It would also be nice if ignored files settings could be made per-account, rather than system-wide, since people who have multiple Nextcloud accounts might want some files ignored for some accounts but not others. I can imagine one person might want to be able to read some log files remotely, but wouldn't care about LaTeX log files.

**Comment by kesselb** [comment]
Guess you're talking about the activity log within the nextcloud desktop client hence I moved it.

**Comment by andis-spr** [comment]
![Clipboard03](https://user-images.githubusercontent.com/52537705/71557387-051fb080-2a4e-11ea-9894-78e50bf14160.png)

These notifications seem to pop up one after another right after OneNote stops writing changes to a document while previous file version is being uploaded. I'd like to have an option to suppress these errors.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
