### ISSUE TITLE
Files not being synced when locally moving folders to the "Nextcloud synced folder"

### ISSUE THREAD

**Issue by Golffies** [nextcloud/desktop#1681]
### Expected behaviour
When moving at once from the desktop filesystem a group of folders and their subfolders into the local "Nextcloud folder" on the desktop, i.e. the folder which is synced with the Nextcloud server, it is expected for all these moved folders, subfolders and enclosed files to be synced with Nextcloud too.

### Actual behaviour
When moving at once a group of folders and their subfolders into the local "Nextcloud folder" on the desktop, all the folders and sub-folders are actually synced with the Nextcloud server, but none of the enclosed files are synced with the Nextcloud server. All newly synced folders and sub-folders have a size of zero on the Nextcloud server and have no files inside.

### Steps to reproduce
1. On your desktop, open your local "Nextcloud folder";
2. Drag and drop a bunch of other folders including sub-folders and files from your desktop file system to your local "Nextcloud folder" (both being located on the same partition/volume);
3. Observe the synced process to be completed by the Nextcloud client; it is done very fast, even when having to copy-paste folders and subfolders with dozens of MB inside;
4. Log into your account on the Nextcloud webserver and go to the "files" application;
5. Open the newly moved folders and subfolders; all of them have a size of zero and all of them are empty;
6. Observe that there are no files in none of the newly moved folders and subfolders;
7. Go back to the Nextcloud client and click on its "Settings" tab;
8. In the bottom part of the client's window, pull-down the list of the newly synced folders and subfolders;
9. Observe that all the folders and subfolders are reported with a size of zero;
10. Click on the "Force sync now" option in the Nextcloud client;
11. Observe that the newly synced but empty folders and subfolders remain empty.

### Workaround
It is enough to quit the Nextcloud client and launch it again, for it to sync once again all the folders with the Nextcloud server; this time, all the recently moved folders and subfolders and all the files contained in them are correctly synced with the Nextcloud server, i.e. they now appear in the web UI of the Nextcloud server.

### Client configuration
Client version: 2.6.1stable (build 20191105)

Operating system: OS.X 10.13.6

OS language: French

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications/nextcloud.app

### Server configuration

Nextcloud version: 17.0.1

Storage backend (external storage): LVM logical volume EXT4 formatted

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files
Client logs cannot be easily sanitized; they will be delivered by private mail on request, if needed.

2. Web server error log:
Not sure that web server logs are relevant in the present case.

3. Server logfile: nextcloud log (data/nextcloud.log):
nextcloud.log is not populated with additional lines when triggering the problem reported here above.

**Comment by Golffies** [comment]
Looks like my trouble report is a duplicate of #1000 and #1351.

**Comment by K-MeLeOn** [comment]
Any news on that? There's still a problem on Mac.
I can't offer your solution to my client...

**Comment by arandax** [comment]
Am waiting solution too. As workaround I create a folder and then delete it to force the sync, but this is not a solution and/or applicable with customers.

**Comment by bh11** [comment]
Same with Version 2.6.4stable (build 20200303), Server version 17.0.3 on macos 10.15.4.

Quitting and restarting the nextcloud client app can be used as a workaround for the problem.

**Comment by camilasan** [comment]
Please upgrade the server and the desktop client and then if the problem persists reopen the issue.

**Comment by camilasan** [comment]
The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by bh11** [comment]
The issue is still present with the latest versions: server version 19.02, macOS client 2.6.5, macOS 10.15.6

**Comment by camilasan** [comment]
> The issue is still present with the latest versions: server version 19.02, macOS client 2.6.5, macOS 10.15.6

Ok then please update the issue with logs. You can replace sensitive data with a random string.
