### ISSUE TITLE
nextcloud 2.6.1 very slow on Windows 8.1, works on Linux and Windows 10.  (nextcloud Version 2.5.3 works on Windows 8.1 , Version 2.6.2 solved Problem)

### ISSUE THREAD

**Issue by ifrh** [nextcloud/desktop#1686]
### Expected behaviour
The nextcloud client (nextcloud.exe) on the host system (Windows 8.1 (64bit)) 
should be as fast as nextcloud client inside the Linux VM running on the same computer
or nextcloud.exe with Windows 10.

### Actual behaviour
If I want to synchonise 19 MB than I had to wait multiple hours on Windows 8.1 (without running a linux VM in parallel time). There is no network problem, there is no server problem.
If I run nextcloud client inside a linux VM in virtualbox on that Windows 8.1 computer,
than I can synchronise 3GB in 30 minutes.

If I use nextcloud.exe (same version) but on an other PC with Windows 10 at the same wired network connection, than nextcloud.exe  is as fast as the linux version inside the VM.

### Steps to reproduce
1. Install nextcloud client v2.6.1 on Windows 8.1 (64bit)
2. wait long time for finishing synchronisation ....
3. run ` perfmon /res ` and see how often nextcloud.exe is not responding, but generates very low network traffic.

### Client configuration
Client version on Host:  2.6.1stable-Win64 (build 20191105)
Client version in VM: Version 2.6.1git. 
No Bandwidth limit is configurated 

Operating system: Windows 8.1 (64 bit)

OS language: german

Installation path of client:
C:\Program Files (x86)\Nextcloud

**Comment by ifrh** [comment]
downgrading nextcloud client to 
```
Version 2.5.3daily-Win64 (build 20190725). For more information please click here.
Diese Version wird von Nextcloud GmbH bereitgestellt
Gebaut von der git-Revision b216e3 auf Jul 25 2019, 11:08:01 verwendet Qt 5.12.3, OpenSSL 1.0.2s 28 May 2019
```
solved the speed problem while synchronising on Windows 8.1 (64 bit).

**Comment by ifrh** [comment]
Update to Version 2.6.2 solved the problem for Windows 8.1 .

```
Version 2.6.2stable-Win64 (build 20191224). Für weitere Informationen klicken Sie bitte hier.
Diese Version wird von Nextcloud GmbH bereitgestellt
Gebaut von der git-Revision 1d7455 auf Dec 24 2019, 13:21:28 verwendet Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019
```

**Comment by AaronADev** [comment]
Shouldn't this issue be closed? It appears there are a lot of issues that aren't closed that were remedied by the user or an update and it's hard to tell which ones are actually affecting current releases....

**Comment by ifrh** [comment]
@AaronADev : good point. I am closing that report.
