### ISSUE TITLE
Unable to Grant Access to Desktop client (macOS)

### ISSUE THREAD

**Issue by MarkErik** [nextcloud/desktop#1690]
### Expected behaviour
Able to grant access after logging in on the web browser

### Actual behaviour
Pressing the 'Grant Access' button on the web browser does nothing.

If I open the web browser console I see this error:

Refused to send form data to 'http://xyz.xyz.com/login/v2/grant' because it violates the following Content Security Policy directive: "form-action 'self'".

### Steps to reproduce
1. Install client
2. Follow the install steps, enter in my next cloud server information (on https)
3. On next step, the client opens up Safari and asks me to sign in, I do, and then nothing happens.
4. Have also tried copying the URL from the client to Chrome, same issue
5. Have also tried the above steps after removing cookies etc. for the browsers
5. Have also made sure that I did not have a signed-in session in the browser

### Client configuration
Client version: Version 2.6.1stable (build 20191105)

Operating system: macOS Mojave

OS language: English

### Logs

From Chrome Console:

Warning: 
Mixed Content: The page at 'https://xyz.xyz.com/login/v2/grant?stateToken=xyz' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://xyz.xyz.com/login/v2/grant'. This endpoint should be made available over a secure connection.

Error:
Refused to send form data to 'http://xyz.xyz.com/login/v2/grant' because it violates the following Content Security Policy directive: "form-action 'self'".

**Comment by dagobertdebug** [comment]
Same issue here. 

Latest nextcloud docker image.
Version 2.6.1stable (build 20191105)

**Comment by misch7** [comment]
This looks very similar to #1038.

Please try this fix: https://github.com/nextcloud/desktop/issues/1038#issuecomment-460804408

**Comment by Dantist-77** [comment]
I've added 'overwriteprotocol' => 'https', to my config.php on server and this fixed an issue.

**Comment by MarkErik** [comment]
Thank you @Dantist-77 for the suggestion, adding 'overwriteprotocol' => 'https' in config.php on the server did the trick.
