### ISSUE TITLE
including hidden files with UTF8 seems to break the synchronization process

### ISSUE THREAD

**Issue by efx** [nextcloud/desktop#170]
## Details
When synchronizing hidden folders that contained a file named `🐹`, the sync process seemed to hang and not move on from the error. For reference, the hamster imogee was created for fun as part of https://github.com/ember-cli/ember-cli/, but subsequently removed in later versions.
* client: desktop  2.2.3 build 84 (Built from Git revision 57bc79 on Dec 6 2017, 06:08:13 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017) 
* platform: macOS Sierra 10.12.6 (16G1212)

## Steps to reproduce
I am not sure if this is the exact cause, but you could try reproducing with the following:
1. Install the backup client, enable sync hidden files:
<img width="724" alt="screen shot 2018-02-07 at 9 23 06 am" src="https://user-images.githubusercontent.com/472721/35921425-8dc67ec2-0be8-11e8-8b27-2a47aed33c4d.png">

2. Create a mock hidden directory structure:
```
mkdir -p ~/.aaa-secret && touch ~/.aaa-secret/🐹
```
3. Enable sync and possibly see error cause the rest of the synchronization to hang

**Comment by efx** [comment]
The target server was not configured for UTF8 per https://docs.nextcloud.com/server/11/admin_manual/installation/system_requirements.html#database-requirements-for-mysql-mariadb. I will test later to see.

**Comment by camilasan** [comment]
Hi! Why are you using an older version of try the desktop client? Did you try the latest and it didn't work for you?

**Comment by efx** [comment]
@camilasan howdy! I was using the version of the client at the time I reported the issue. I am unable to test this currently, so feel free to close it.
