### ISSUE TITLE
Version 2.6.2stable-Win64 doesn't sync .db, .db-wal and .db-shm files.

### ISSUE THREAD

**Issue by KerimG** [nextcloud/desktop#1702]
### Expected behaviour
Files should be synced and then be removable. 

### Actual behaviour
Files are stuck in syncing process and cannot be removed either. I tried turning off the client and then removing the files but then the files are recreated and resynced.

![image](https://user-images.githubusercontent.com/9061713/71560582-75d5c580-2a6c-11ea-94e7-860b186c1ddb.png)

### Steps to reproduce
1. No idea. I just realized I have such files in both of my accounts and cannot get rid of them.

### Client configuration
Client version: 2.6.2stable-Win64 

Operating system: Windows 10

OS language: English (USA)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files

### Server configuration

Nextcloud version: 17.0.2

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Contains nothing

2. Web server error log: n/a

3. Server logfile: nextcloud log (data/nextcloud.log): n/a

**Comment by DrCarsonBeckett** [comment]
That files belong to the sync client. Its there since since I start to use the desktop client (2.2).
They are hidden, so "normal" users dont see them.

**Comment by KerimG** [comment]
Thank you for the explanations. Strangely enough, they occasionally seem to cause conflicts themselves. So I end up with various copies of those strange files.

**Comment by Rykimaruh** [comment]
Hi, I see this as well. So what was the explanation? I'm still confused as to what I am looking at
