### ISSUE TITLE
Webinterface open online file with desktop software and save back online

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/desktop#1705]
The online interface has a great ui with favorites and labels. As the different desktop didn't support all this (and it need lot of coding work).

When I open an Excel file via the web interface make changes and go to save, would it be possible that Excel will open the webdav or sync folder file instead of download the file to downloads where the changes didn't sync back to NC.

**Comment by DarkknightAK** [comment]
Than I can do all the work with the web interface and the file edit stuff with my desktop apps I use.

**Comment by DarkknightAK** [comment]
https://mein-dms.agorum.com/blog/agorum-core-im-alltag-dokumente-ohne-umwege-bearbeiten

That's how an dms did it.

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
