### ISSUE TITLE
nextcloud client fails to fall back to english if translation is missing

### ISSUE THREAD

**Issue by polrus** [nextcloud/desktop#1708]
The activity tab in the desktop client show an error with no translation and no english translation either so server reply is not shown at all - instead user is presented with %1-%4

my dir/my_file.mov: Server odpowiedział "% 1 % 2" na "%3 % 4" 

which stands for :server replied "% 1 % 2" on "%3 % 4"

### Expected behaviour
If translation for certain language is missing like in this case - the english translation should be provided to %1-%4 as fall back so we can at least try to understand what the error is

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. use nextcloud client 2.6.2
2. have your locale set to Polish
3. start a client that has some issue to be shown and see the activity tab

### Client configuration
Client version:

2.6.2
Operating system:
Linux OpenSuse Leap 15.1
OS language:
Polishy
Qt version used by client package (Linux only, see also Settings dialog):
5.9.7
Client package (From Nextcloud or distro) (Linux only):
distro
Installation path of client:

### Server configuration

Nextcloud version:
Nextcloud 17.0.2
Storage backend (external storage):
NFS
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?

**Comment by polrus** [comment]
not able to reproduce in current version - closing
