### ISSUE TITLE
Nextcloud 2.6.2 AppImage and PPA won't start

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/desktop#1709]
### Expected behaviour
Nextcloud should start.

### Actual behaviour
I get these errors:
```
qt.qpa.xcb: failed to initialize XRandr
qt.qpa.xcb: XKeyboard extension not present on the X server
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
XIO:  fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server ":10.0"
      after 237 requests (237 known processed) with 0 events remaining.
```

### Steps to reproduce
1. Download AppImage in version 2.6.2 for 64 Bit Linux.
2. `chmod +x` it
3. Run it.

### Client configuration
Client version:
Nextcloud version 2.6.2stable (build 20191224) from here: https://download.nextcloud.com/desktop/releases/Linux/latest

Operating system:
Ubuntu 16.04.6 LTS

OS language:
```locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

Qt version used by client package (Linux only, see also Settings dialog):
I can not open settings dialog.

Client package (From Nextcloud or distro) (Linux only):
From Nextcloud.

Installation path of client:
There was no installation but an AppImage although I would prefer a proper DEB package.

**Comment by NicolasGoeddel** [comment]
Same issue with the PPA version:

### Expected behaviour
Nextcloud should start.

### Actual behaviour
I get these errors:
```
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
XIO:  fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server ":10.0"
      after 223 requests (223 known processed) with 0 events remaining.
```

### Steps to reproduce
1. `sudo add-apt-repository ppa:nextcloud-devs/client`
2. `sudo apt update`
3. `nextcloud`

### Client configuration
Client version:
Nextcloud version 2.6.2git

Installation path of client:
`/usr/bin/nextcloud`

**Comment by pgassmann** [comment]
Duplicate of #1704

**Comment by NicolasGoeddel** [comment]
No. It is not a duplicate. It starts normally and works great on a normal Desktop, but it will not start if I am on a different display, like when using xrdp.

**Comment by NicolasGoeddel** [comment]
Well, what details do you need?
