### ISSUE TITLE
Desktop sync client deleted local data instead of uploading them to the server (after server rollback using a snapshot)

### ISSUE THREAD

**Issue by telien** [nextcloud/desktop#171]
Dear all,

yesterday, I made a strange observation which caused a loss of some data. Due to various issues, I had to rollback my server using the full server snapshot created end of january. I did not believe that this could cause any issues, therefore I did not make a backup of my local data. 
After my server was ready again, the windows sync client of nextcloud has overwritten my local data which were newer than end of january. In addition, new data from february were fully deleted by the sync client instead of uploading them. As I was not able to recover them, I unfortunately lost them. Luckily not a big deal as these data were not extremly important.
For me personally, this behaviour of the sync client is a kind of strange. I assumed that the client would realize that the local data are newer than data on the server and would upload the newer data to the server. This unfortunately didn't happen... 

Do you now about this behaviour of the sync client? I guess it is a bug...

Thanks and best regards
telien

**Comment by DominiqueFuchs** [comment]
I'm afraid that the client behaved as expected (and as it should do). 

My guess what happened is that your rollback caused the server etags (header information for all objects on the remote tree, used by the sync engine when comparing local tree, remote tree and journal) to date to the exact time of recreation for all objects. This is also an issue when restoring computer backups when software and/or filesystem do not care about this (then we are talking about file timestamps, atimes/mtimes etc.). 
If this is the case, your client saw that everything on the server is newer (including folders with current timestamps and **not** containing files that are present on the local tree - which then leads to the assumption that those got deleted meanwhile on the remote side. And (again: if this is the case) one had to either look into the chosen method for restoration or on the server development to handle this case with regard to the etags.

Do you agree/disagree, @telien ?

**Comment by michaelstingl** [comment]
Docs mention an `occ` command for restore:
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/occ_command.html#maintenance-commands
