### ISSUE TITLE
nextcloud desktop client instantly crashes on start for all versions since 2.5.0

### ISSUE THREAD

**Issue by OvoiDs** [nextcloud/desktop#1711]
Hello,

I'm trying to install nextcloud desktop client on my Windows 10 computer but it crashes each time I try to start it for all versions since 2.5.0.

2.3.3.1 starts fine.

### Expected behaviour
Click on the shortcut
bam it's open

### Actual behaviour
Click on the shortcut
"Program has ceased to function"

### Client configuration
Latest version is impaired

Operating system: W10

OS language: FR

Thanks guy for your work, i'm really stuck.

**Comment by lightzhan** [comment]
Oh, I am meeting the same problem, My OS is WIN7. When I start the program and open its window, a moment later, it freeze and I find the app eat 25% CPU source.

**Comment by lightzhan** [comment]
If I do not open the window, It won't freeze. So strangle.

**Comment by bestmagister** [comment]
Hello!
Maybe I have the same problem. The nextcloud client crashes onMacOS Mojave with an Abort 6 messages few seconds after lauching it.
I have produced logs launching with the command line. Is there a way I could contribute by sending them to developers?
