### ISSUE TITLE
can't get rid of old folder symbol (link) in explorer navigation

### ISSUE THREAD

**Issue by olli0815** [nextcloud/desktop#1712]
Hi,

I can't get rid of an non existing Link, of an older sync.
Even after deleting all nextcloud registry entries and re-installation of the client the (dead) link appears again. How to get rid of?

![win explorer](https://user-images.githubusercontent.com/17963080/71819803-6a4a5600-308d-11ea-9656-553b9335637f.PNG)

**Comment by billyjacoby** [comment]
I'm having this exact same issue and it's driving me mad. Does anyone have a fix for this?

**Comment by olli0815** [comment]
okay,

got it.
regedit for "IsPinnedToNameSpaceTree"
set to 0
Thats it.
As mentioned here..
https://www.schieb.de/758114/onedrive-icon-aus-explorer-entfernen
