### ISSUE TITLE
Wrong file size in sync client 2.6.2 for Windows

### ISSUE THREAD

**Issue by schousda** [nextcloud/desktop#1719]
### Expected behaviour
When a file changes, it gets synched by the Windows client.

### Actual behaviour
The file gets synched, but the client shows a wrong size.
Even if the file(s) are only small, the client always shows a size 4 GB.
![grafik](https://user-images.githubusercontent.com/21222928/72235934-17b0f280-35d5-11ea-91f5-b76067af2c89.png)

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:

Operating system:
Windows 10 x64 1909

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:
Cloud 17.0.2

Storage backend (external storage):
Webhoster

**Comment by Ark74** [comment]
This is still a thing on v2.6.4stable
Related: https://github.com/nextcloud/server/issues/15833
