### ISSUE TITLE
Windows Sync Client 2.6.2 and app password

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/desktop#1722]
Nextcloud version: 17.0.2
Operating system and version: Ubuntu 18.04
Apache or nginx version : NGINX 1.16.1
PHP version : 7.3.13

The issue you are facing:

Is this the first time you’ve seen this error? : always

Steps to replicate it:

Enable 2FA on Nextcloud
Create App password
Try to login to Windows 10 sync client 2.6.2
Getting response “Wrong username or password.”

However I can use the App password for WebDAV connection and is working fine.

Could you help me to use App password for the client please? I know I can use 2FA but because we are using LDAP and company policy is to change user password every 90 days I wold like to use APP password to make sure Nextcloud client app is not prompting about new when user change it.

**Comment by mgallien** [comment]
Can you still reproduce the connection error ?
I have tested with a Nextcloud instance connected to an LDAP server with 2FA enabled and the desktop client uses browser to authenticate successfully without any issue nor needing an app password.
