### ISSUE TITLE
Wrong size report of client 2.6.2

### ISSUE THREAD

**Issue by angledezma** [nextcloud/desktop#1724]
Hello friends. I have noticed that the nextcloud client does not correctly inform the sizes of the folders, almost all places them in GB. I send the images.

I'm using Nexcloud client 2.6.2stable (Build 20191224)
Windows 10 (1909) operating system in Latin American Spanish

![real_size](https://user-images.githubusercontent.com/59850765/72299503-0b598380-362f-11ea-81e0-53371cc4b48a.jpg)
![reported_size](https://user-images.githubusercontent.com/59850765/72299504-0b598380-362f-11ea-9816-f967e25fe302.jpg)

**Comment by mgallien** [comment]
Can you still reproduce this issue with latest version ?
To me it looks like this is fixed.
