### ISSUE TITLE
Nextcloud Desktop cannot authenticate on HTTPS server

### ISSUE THREAD

**Issue by batbast** [nextcloud/desktop#1728]
### Expected behaviour
Authentication Nextcloud Desktop

### Actual behaviour
Autentication pending

### Steps to reproduce
1. Clean .config/Nextcloud folder
2. Launch Nextcloud Desktop
3. Login > Server address with https://mydomain
4. Launch Browser webflow authentication
5. Nextcloud Desktop authentication pending because it tray to join http://mydoamin/index.php/login/v2/poll not https://mydomain/index.php/login/v2/poll

### Client configuration
Client version:
2.6.1-2

Operating system:
Linux Debian Testing

OS language:
EN_US

Qt version used by client package (Linux only, see also Settings dialog):
5.12

Client package (From Nextcloud or distro) (Linux only):
Package: nextcloud-desktop
Version: 2.6.1-2
Status: install ok installed
Priority: optional
Section: net
Maintainer: ownCloud for Debian maintainers <pkg-owncloud-maintainers@lists.alioth.debian.org>
Installed-Size: 3 229 k

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Nextcloud version:
16.0.6.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
[OCC::Application::setupLogging 	"################## Nextcloud locale:[en_US] ui_lang:[] version:[2.6.1-2] os:[Debian GNU/Linux bullseye/sid]"
[OCC::Application::setupTranslations 	Using "en_US" translation
[OCC::SocketApi::SocketApi 	server started, listening at  "/run/user/1000/Nextcloud/socket"
[OCC::FolderMan::FolderMan 	setting remote poll timer interval to 5000 msec
[OCC::AccountManager::restoreFromLegacySettings 	Migrate: restoreFromLegacySettings, checking settings group "Nextcloud"
[OCC::AccountManager::restoreFromLegacySettings 	Migrate: checking old config  "/home/bast/.config/ownCloud/owncloud.cfg"
[OCC::ownCloudGui::setupContextMenu 	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
[OCC::FolderMan::setupFoldersMigration 	Setup folders from  "/home/bast/.config/Nextcloud/folders" (migration)
[OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use the prefered system proxy for http tcp connections
[OCC::ownCloudGui::slotOpenSettingsDialog 	No configured folders yet, starting setup wizard
[OCC::WebViewPage::WebViewPage 	Time for a webview!
[unknown 	Please register the custom scheme 'nc' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
[OCC::UpdaterScheduler::slotTimerFired 	Skipping update check because of config file
[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://mydomain/status.php" has X-Request-ID "33ce53bb-188e-47ed-8e9f-d1ee4f530cc1"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://mydomain" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"BatCloud","version":"16.0.6.1","versionstring":"16.0.6"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x558cb82d1f60)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://mydomain/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://mydomain/remote.php/webdav/" has X-Request-ID "9c2a90f5-0b66-44e3-8658-b3631f49a5c8"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://mydomain" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://mydomain/remote.php/webdav/" has X-Request-ID "c05e04ac-940f-4dee-bf6a-7fc87dd8fd81"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://mydomain" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://mydomain/remote.php/webdav/") is 4
[OCC::AccessManager::createRequest 	4 "" "https://mydomain/index.php/login/v2" has X-Request-ID "627f89e2-4772-45ba-8c86-19e43900f203"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://mydomain" + "" "OCC::Account"
[OCC::Flow2Auth::openBrowser()::<lambda 	setting remote poll timer interval to 5000 msec
[OCC::AccessManager::createRequest 	4 "" "http://mydomain/index.php/login/v2/poll" has X-Request-ID "e143b3e2-1d58-4be5-b964-0db6dd3bf66b"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://mydomain" + "" "OCC::Account"
[OCC::AbstractNetworkJob::slotTimeout 	Network job timeout QUrl("http://mydomain/index.php/login/v2/poll")
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::OperationCanceledError "Connection timed out" QVariant(Invalid)
[unknown 	QIODevice::read (QNetworkReplyHttpImpl): device not open
[OCC::AccessManager::createRequest 	4 "" "http://mydomain/index.php/login/v2/poll" has X-Request-ID "3deb72ad-edc3-444b-aa0b-bb81e2e55f23"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://mydomain" + "" "OCC::Account"

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by signupforacomment** [comment]
Same problem here, client is version 2.6.2, server version 18.0.

From taking a look in the webserver logs it seems the problem is that you put in an URL, the client access the status.php for whatever reason, generates the URL, opens the browser and then awaits the authorization code.
Though instead of keeping the access the URL, the client switches to directly trying to access the IP address which, in case of virtual hosting, will break SNI requests.

Steps to reproduce:

1. (might be another cause) Setup a reverse proxy doing SSL offload
2. Setup a webserver with 2 vHosts
3. Let 1 vHost take all requests directed to unknown names or directed towards the IP
4. Let the other vHost serve Nextcloud

Let both log into different logfiles and while the client initially requests the correct vHost, the "Awaiting authorization" seems to try to access the IP directly:

234.567.890.123 - - [31/Feb/2039:00:00:00 +0000] "POST /nextcloud/index.php/login/v2/poll HTTP/1.1" 502 598 "-" "Mozilla/5.0 (Linux) mirall/2.6.2git (Nextcloud)"

Should be shown in the access.log of vHost 1. The "502" above is the reply the default vHost (at least mine) sends out for every uninteresting request.

**Comment by g-work** [comment]
I had the same problem. Look at https://[Your Domain]/index.php/settings/user/sync-clients. When it says the adress of the server was http instead of https, you have to edit two lines in config.php:

> 'overwrite.cli.url' => '[httpS://your-domain]',
> Use this configuration parameter to specify the base URL for any URLs which are generated within Nextcloud using any kind of command line tools (cron or occ). The value should contain the full base URL: https://www.example.com/nextcloud
> 
> 
> 'overwriteprotocol' => 'https',
> When generating URLs, Nextcloud attempts to detect whether the server is accessed via https or http. However, if Nextcloud is behind a proxy and the proxy handles the https calls, Nextcloud would not know that ssl is in use, which would result in incorrect URLs being generated.
> Valid values are http and https.

In my case, the loginprocess forwarded to http which isn't reachable on my server and so the authentication process failed.

**Comment by LucaBernstein** [comment]
Same problem here.

So basically what I would question is why a connection over a TLS connection generates an authentication link with http://

**Comment by LucaBernstein** [comment]
Please note that I opened a related issue here: https://github.com/containous/traefik/issues/6315

I just tried your suggestion @g-work you described in that comment: https://github.com/nextcloud/desktop/issues/1728#issuecomment-583757990

Current procedure: Serve nextcloud both on HTTP and HTTPS and simply add the `'overwriteprotocol' => 'https',` in the config.php

Just tried it: Now login seems to work again.

Though I do not see this as the final solution (as it feels rather dirty to normally have my traefik handle http -> https rewrite and now nextcloud handles this internally - and: how to make sure that the reverse proxied https requests which nextcloud receives as http requests don't get rewritten over and over again?) it works for now (fine as mitigation)

Thanks! If you need any more information please don't hesitate to ask me :)

Luca

**Comment by kermit-frog** [comment]
> 
> 
> I had the same problem. Look at https://[Your Domain]/index.php/settings/user/sync-clients. When it says the adress of the server was http instead of https, you have to edit two lines in config.php:
> 
> > 'overwrite.cli.url' => '[httpS://your-domain]',
> > Use this configuration parameter to specify the base URL for any URLs which are generated within Nextcloud using any kind of command line tools (cron or occ). The value should contain the full base URL: https://www.example.com/nextcloud
> > 'overwriteprotocol' => 'https',
> > When generating URLs, Nextcloud attempts to detect whether the server is accessed via https or http. However, if Nextcloud is behind a proxy and the proxy handles the https calls, Nextcloud would not know that ssl is in use, which would result in incorrect URLs being generated.
> > Valid values are http and https.
> 
> In my case, the loginprocess forwarded to http which isn't reachable on my server and so the authentication process failed.
> 
> @signupforacomment You could also try
> 
> > 'overwritehost' => '',
> > The automatic hostname detection of Nextcloud can fail in certain reverse proxy and CLI/cron situations. This option allows you to manually override the automatic detection; for example [www.example.com](http://www.example.com), or specify the port [www.example.com:8080](http://www.example.com:8080).

That solved my problem @g-work! I have contacted my provider and asked him to look at the solution from this thread. From there the settings (overwriteprotocol und overwritehost) were set and after that the authentication could be done without any problems. 

Thank your very much!

**Comment by g-work** [comment]
@LucaBernstein 

> So basically what I would question is why a connection over a TLS connection generates an authentication link with http://

It depends on your configuration. In my case, nextcloud is behind a proxy that handles encryption. So nextcloud itself doesn't "know" there is a https connection. Therefore you have to set it manually in config file.

**Comment by rullzer** [comment]
> @LucaBernstein
> 
> > So basically what I would question is why a connection over a TLS connection generates an authentication link with http://
> 
> It depends on your configuration. In my case, nextcloud is behind a proxy that handles encryption. So nextcloud itself doesn't "know" there is a https connection. Therefore you have to set it manually in config file.

Exatly. Since Nextcloud doesn't know it you need to tell it.

We are looking into adding this as a check on the setup page. As it seems to be a somewhat common setup bug.

**Comment by batbast** [comment]
Into config.php, the parameter overwrite.cli.url' => '[httpS://your-domain]' is necessary but not enough.
We had to add 'overwriteprotocol' => 'https'.

Maybe these parameters could be merged?


Le 28 février 2020 17:30:21 GMT+01:00, Roeland Jago Douma <notifications@github.com> a écrit :
>> @LucaBernstein
>> 
>> > So basically what I would question is why a connection over a TLS connection generates an authentication link with http://
>> 
>> It depends on your configuration. In my case, nextcloud is behind a proxy that handles encryption. So nextcloud itself doesn't "know" there is a https connection. Therefore you have to set it manually in config file.
>
>Exatly. Since Nextcloud doesn't know it you need to tell it.
>
>We are looking into adding this as a check on the setup page. As it seems to be a somewhat common setup bug.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/desktop/issues/1728#issuecomment-592590936
-- 
Bat Bast

**Comment by FlexW** [comment]
Is there still anything to address in this issue? I have no trouble connecting to an SSL server.

**Comment by mattdale77** [comment]
I have this issue and have the recommended settings configured and for me it doesn't resolve it. It also affects the Android app

**Comment by szaimen** [comment]
Hi @mattdale77 please refer to https://help.nextcloud.com for this. Thanks!

**Comment by mattdale77** [comment]
I haven't found a solution on there for this that works for me
