### ISSUE TITLE
Client crashes when adding new folder sync (when an existing folder snyc isn't found)

### ISSUE THREAD

**Issue by Maroko** [nextcloud/desktop#1733]
### Expected behaviour
Click on the button "Add folder synchronization", should open the menu to add a new folder.

### Actual behaviour
If there is an existing folder synchronization, but the folder is not found (e. g. a USB that isn't plugged in), nextcloud will crash when trying to add a new folder synchronization.

### Steps to reproduce
1. Create a folder snyc with an folder on an USB stick.
2. Remove the USB stick.
3. Try to create a new folder synchronization.

### Client configuration
Client version: 2.6.2

Operating system: Windows 10 Home 64bit

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs
Client crashes without printing new lines to logfile.
`[OCC::JsonApiJob::finished      Nothing changed so nothing to retrieve - status code:  304
[OCC::ServerNotificationHandler::slotNotificationsReceived      Status code  304  Not Modified - No new notifications.
[OCC::WebFlowCredentials::slotFinished  request finished
[OCC::PropfindJob::finished     PROPFIND of QUrl("my nextcloud url") FINISHED WITH STATUS "OK"`

After the above line I clicked on the "create new folder sync" button, then nextcloud crashed, without logging the error.

**Comment by Aldaris1985** [comment]
Can confirm this error when using a network drive that is not connected.

**Comment by FinduschkaLi** [comment]
Same behaviour observed on my drive. I tried the new beta (2.7.0beta1-Win64) where I could add a new sync although a network folder sync (not connected) was present. 
The client now just randomly crashes though. (I am not sure that the error is linked, will conduct some testing)

**Comment by cmiltiadis** [comment]
I can confirm too. 
I sync data from an external drive, that I only want to connect and sync occasionally. I have to keep the sync folder paused, otherwise the NC app complains too much that it doesn't find the drive. The app now crashes a few seconds after I press 'Add new folder to sync'.
