### ISSUE TITLE
"open in browser" does not highlight file

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#1734]
- select file
- "open in browser" in conext menu
- opens corresponding folder in browser, but not highlight files (I guess it is scrollTo=123)

@misch7 :heart:

**Comment by Zegorax** [comment]
Same issue with V2.7.0 Beta 1. It opens the file instead of the folder containing the file.

**Comment by FlexW** [comment]
I can not reproduce the problem with the latest version. Seems to be resolved.
