### ISSUE TITLE
High memory usage of Flatpak version

### ISSUE THREAD

**Issue by MarekPikula** [nextcloud/desktop#1740]
### Expected behaviour
Smaller memory footprint of Nextcloud Desktop client.

### Actual behaviour
I have two accounts to two separate servers configured in my Nextcloud Desktop client.
One of them is under 50GB and the other about 250GB of synced data.
Right now it sits on a little above 4GB of RAM usage.

After launch when fully initialised it uses about 210MB of RAM.

### Client configuration
Client version: 

Installed from Flathub.
Version 2.6.2git.  
Built from Git revision 1d7455 on Jan 4 2020, 10:18:57 using Qt 5.12.6, OpenSSL 1.1.1d 10 Sep 2019

Operating system: Fedora 31 KDE Plasma

OS language: Polish

Qt version used by client package (Linux only, see also Settings dialog): 5.12.6

Client package (From Nextcloud or distro) (Linux only): Flatpak from Flathub

Installation path of client: `/var/lib/flatpak/app/org.nextcloud.Nextcloud/x86_64/stable/active/files/bin/nextcloud`

### Server configuration

Nextcloud version: first one 17.0.1, second 17.0.2

Storage backend (external storage): local storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Will be attached once it'll get to this point again. Didn't launch it with `--logwindow` before.

**Comment by MarekPikula** [comment]
From the brief observation it seems to go up in RAM usage when updating files.
As mentioned before it started at 210MB and now it's sitting at 300MB.

I'll try to stress test it next week to see what is causing this horrendous RAM usage from before.

**Comment by mgallien** [comment]
Thanks for your report.
I am sorry but this is maintained by a third party and you should probably start by reporting this problem on the Flathub packaging repository.
https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues
If some fixes are needed on our side, we will be happy to help.
