### ISSUE TITLE
Username on NextCloud Client for Windows is case sensitive

### ISSUE THREAD

**Issue by proteusoz** [nextcloud/desktop#1741]
### Expected behaviour
When user changes AD windows password the web 'grant access' page should just work.

### Actual behaviour
When using 2.6.X and up, we are seeing our users struggling with the Web site to grant access to system when the user has changed their windows password.  We have found that if you initially sign in as JJO.BLOGS and then when prompted to log into the 'grant access' page again (after password change) and use jjo.blogs (or anything that doesn't match the first nextcloud login) it will look like it works, but never gets past the nextcloud dialogue screen Open In Browser/Copy Link to validate user.

Once you are in this 'loop' of validation, open web page, users are stuck, until you get them to log into the Web interface and Log out and then use the user name as shown on the 'open in browser/copy link' screen.  Once you get the case right on the username it works as it should.

I don't believe that the login username should be case sensitive.

### Client configuration
Client version:
2.6.2

Operating system:
Windows 10
OS language:
English (Australian)

Installation path of client:
c:\program files\nextcloud

**Comment by marcohald** [comment]
Hi,

we have the same Problem and created a Ticket with the ID Ticket#9610875

**Comment by misch7** [comment]
Fixed by #1827 and will get into the 2.6.4 release.
