### ISSUE TITLE
Ask for permission before a large number of files are removed

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#1743]
The sync client already ask the user when a large folder shows up whether it should be synced or not. The same should happen the other way around. Imagine that because of a bug all shares (temporarily) disappears or a user deletes a shared folder or large parts of a group folder by accident. This shouldn't delete all the local copies directly but give the users the chance to keep the offline copies and verify if the delete operation was triggered by intention or not.

**Comment by wiswedel** [comment]
Since for actual unsharing it may be intended by the share owner that the so-far-sharee doesn't have access to the files (or copies) anymore, I guess an unshare action should still trigger local deletion.

**Comment by isdnfan** [comment]
the logic should always follow the idea: server is master and all clients are only copies.. such security mechanisms should be applied on the server side, like versions, trashbin and so on.. if the user wants to keep local storage he still can implement some kind of local backup..

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
