### ISSUE TITLE
Building within docker

### ISSUE THREAD

**Issue by jgonyea** [nextcloud/desktop#1754]
This is just an informational gathering ticket, and not a true bug issue.

Is it possible to build the linux client within a docker container and then copy the result to another machine?  If so, what dependencies need to be installed on the second machine for the resultant build to function properly?

**Comment by FlexW** [comment]
Please go to https://help.nextcloud.com if you have questions. It might be tricky to get the graphical interface working with docker, espacially if you plan to deploy to Windows. Keep in mind that you will not have any explorer/nautilus/finder integration with a docker image.
