### ISSUE TITLE
Timestamps for logs

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/desktop#1756]
### Expected behaviour
Nextcloud writes a LOG with F12. To debug problems a log should have a timestamp for each line. Similar to NGINX, PHP and almost every other log.

### Actual behaviour
The log contains no date and time information.

### Steps to reproduce
1. Open the Nextcloud Client
2. Press F12
3. Wait a bit until log entries appears

### Client configuration
Client version: v2.7.0 (but is not version dependent)

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Logs

Do not think this feature request/issue require logs. But if necessary, I can provide an example.

**Comment by tomasz-lasko** [comment]
+1  

I was also surprised that logs / debug logs did not contain timestamps (Windows 10, 64bit, 2.6.4) - this is really bad because I could not trace back the problem :(
