### ISSUE TITLE
Client crashes on Linux after entering server URL.

### ISSUE THREAD

**Issue by fancycode** [nextcloud/desktop#1758]
I commented this on closed issue #1036 but the issue still happens, so I'm adding as a new issue.

### Expected behaviour
1. Start app on Ubuntu Linux.
2. Enter server URL.
3. Application should ask for login credentials.

### Actual behaviour
The application crashes with a segmentation fault between steps 2 and 3.

### Steps to reproduce
1. Checkout 04a08bfb23a4de73996a3790e84c3b8c290996d9
2. Build
3. Start application

### Client configuration
Client version:
commit 04a08bfb23a4de73996a3790e84c3b8c290996d9

Operating system:
Ubuntu Linux 18.04 LTS

Qt version used by client:
5.9.5 from the official repository.

Installation path of client:
`/home/domain/jojo/devel/nextcloud/desktop`

### Logs
gdb stacktrace:
https://gist.github.com/fancycode/a56bb4253fa15ddc716ac6a865e61ec7

The official app on Windows (2.6.2stable-Win64 (build 20191224)) works fine with the same server, so I assume it's a client-side issue that only happens on Linux.

**Comment by claell** [comment]
@fancycode I reopened #1036, so I guess this can be closed?

**Comment by claell** [comment]
Also, as side note, there also is #1378 that was also opened as duplicate.

**Comment by fancycode** [comment]
> I reopened #1036, so I guess this can be closed?

Sure, if it gets fixed from #1036 I'm happy to close this one.
