### ISSUE TITLE
Desktop Client Uploading Fails

### ISSUE THREAD

**Issue by MonkeyGovernor** [nextcloud/desktop#176]
Can't get the Desktop Client to sync files and folders. It’ll start creating the folders, but I get an error stating Server Replied - Not Acceptable on almost every file it tries to upload.

The Web Interface and Android Phone client have no issues uploading these files to the same server.

Here are screenshots of it attempting to upload files through the client.  Logs don't turn up anything regarding the files failing to upload.

https://ibb.co/mY3YrH

https://ibb.co/fyvDrH

https://ibb.co/gZga5c

https://ibb.co/fehRBH

https://ibb.co/gLYYrH

https://ibb.co/nGG8Qc

https://ibb.co/htyzWH

https://ibb.co/fyFeWH

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
