### ISSUE TITLE
Linux client crashes with GLib-ERROR **: Creating pipes for GWakeup: Too many open files

### ISSUE THREAD

**Issue by Vogelchevalier** [nextcloud/desktop#1769]
### Expected behaviour
The client doesn't crash

### Actual behaviour
The client crashes after a few hours or a few days

### Steps to reproduce
1. Run the client
2. Wait for a day or so, maybe longer, who knows. Took ~16 hours last time it happened (today).

### Client configuration
Client version:
2.6.2git. Built from Git revision 1d7455 on Dec 24 2019.

Operating system:
Manjaro Linux 64bit

OS language:
English (en_GB)

Qt version used by client package (Linux only, see also Settings dialog):
5.14.0-1

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client 2.6.2-1 from the Arch community repo

### Logs

Nothing related to the issue in the logfile. Error from terminal output.

`(process:93519): GLib-ERROR **: 23:08:28.546: Creating pipes for GWakeup: Too many open files`

**Comment by rain0r** [comment]
Can confirm this error. Happens every night on my desktop.

- glib-2.60.7-r1
- glibc-2.30-r3
- nextcloud-client-2.6.2

```
(process:4358): GLib-ERROR **: 04:14:30.687: Creating pipes for GWakeup: Too many open files
Trace/breakpoint trap
```

**Comment by subdee** [comment]
I also confirm, it happens often and the client dies. I am continuously out of sync.

nextcloud-client-2.6.3git from AUR

**Comment by danjpgriffin** [comment]
I also have this issue. I have a PR that provides a fix. 

https://github.com/nextcloud/desktop/pull/1899

**Comment by sputnick-dev** [comment]
Same issue, happens when my backup script run.

`(nextcloud_20200330:15992): GLib-ERROR **: 00:17:17.968: Creating pipes for GWakeup: Too many open files`

Nextcloud version 2.5.1git
Using Qt 5.11.3, built against Qt 5.11.3
Using 'OpenSSL 1.1.1d  10 Sep 2019'

**Comment by claell** [comment]
@danjpgriffin Thanks for providing a fix, let's hope, it gets merged soon!

Also do you think this is related or even the same issue as #1035?

**Comment by danjpgriffin** [comment]
@claell Not sure if the same issue. I will try and figure out a test-case to see if I can reproduce this on my own machine when I get time.

**Comment by jZ7He56RkPTYABUjfww4** [comment]
me too

**Comment by ibschreiber** [comment]
Same here. 
Ubuntu 16.04 LTS
current client version from ppa

(nextcloud:1787): GLib-ERROR **: Creating pipes for GWakeup: Zu viele offene Dateien
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

**Comment by ibschreiber** [comment]
Workaround script:

Put this into executable file and run every Minute by crontab.

```
#!/bin/bash

NCC="/usr/bin/nextcloud"

if pgrep -x "nextcloud" > /dev/null
then
    #echo "Already Running"
else
    #echo "Stopped - restarting"
    $NCC &
fi
```

**Comment by fndmossmann** [comment]
I'm having the same issue.
> nextcloud[2171]: Creating pipes for GWakeup: Too many open files

I was using version 2.6.4 from flathub on Fedora 32.
The native version, from Fedora's repo, which was the same version, also had the same problem.

Just grabbed the latest daily AppImage build (https://download.nextcloud.com/desktop/daily/Linux/Nextcloud-2.7.0.20200515-daily-x86_64.AppImage), which should have @danjpgriffin's PR included, and will test it for a couple of days.
Hope if works.

**Comment by fndmossmann** [comment]
Yup, 6 days running the 2.7.0 client without crashes.

**Comment by claell** [comment]
Thanks for testing @fndmossmann. I will leave this open until it lands in a stable release.

**Comment by RampantPanda** [comment]
I get the error "Too many open files" when syncing a bunch of jpgs. I am using the appimage version 2.7.0. Not sure if this is a separate issue? The client doesnt crash, just doesn't sync.

I had the same issue in the stable version as well and tried the daily to see if that would fix the issue.

**Comment by RampantPanda** [comment]
...actually, 

This still happens, just took a while with a new sync. I'm using the 2.7.0 daily appimages, and the sync never completes. I get a lot of "too many files open" errors and the client sometimes crashes. I'm using Fedora 32 with Gnome and wayland.

**Comment by simonszu** [comment]
Similar issue on Mac OS: 

```
2020-10-21 19:23:05:142 [ critical  ]:  QNetworkInterface: could not create IPv6 socket (Too many open files)
QThreadPipe: Unable to create pipe: Too many open files
2020-10-21 19:25:56:268 [ fatal default ]:      QEventDispatcherUNIXPrivate(): Can not continue without a thread pipe
``` 

Client is simply crashing after hours or few days after starting.

**Comment by michield** [comment]
Yes, this is definitely an issue. Using Ubuntu 20.04.1 LTS

`Creating pipes for GWakeup: Too many open files`

I think it's been happening to me for quite some time, but I didn't notice. Very awkward when restarting it, causes document conflicts in the team.

lsof |wc -l
returns 2751132

but further investigation with 

`lsof | cut -d ' ' -f 1 | sort | uniq -c`

finds that 

`2164468 zoom`

so, even if it's nice if nextcloud can handle this exceptional situation, the culprit (in my case) is zoom

**Comment by achimrothe** [comment]
The big still exists even with client 3.2.01
GLib-ERROR **: 10:45:37.701: Creating pipes for GWakeup: Too many open files
