### ISSUE TITLE
HTTP2 & "Server stopped accepting new streams before this stream was established"

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#1771]
### Actual behaviour
As @papjul suggested, seperating the discuss from original issue: https://github.com/nextcloud/desktop/issues/1182#issuecomment-582291749

owncloud reported bug in Qt again causing "Server stopped accepting new streams before this stream was established" when server enables HTTP2.0: https://github.com/owncloud/client/issues/7610

### Steps to reproduce
1. Enables http2 in server conf
2. Sync files larger than 20MB containing umlauts/ non-ascii character

**Comment by DrCarsonBeckett** [comment]
Dublicate of #1503 : 
https://github.com/nextcloud/desktop/issues/1503
