### ISSUE TITLE
Osx 2.6.2 - .App files are broken after sync

### ISSUE THREAD

**Issue by NeutroGe** [nextcloud/desktop#1775]
### Expected behaviour
When application files (.app) are uploaded through the nextcloud client to the server then downloaded back from the server still through the nextcloud client, these apps should keep working properly.

### Actual behaviour
When the .app files are downloaded back and executed they do not work anymore and a message saying that the app is corrupted is displayed on OSX.

### Steps to reproduce
1. Download any osx standalone application like Platypus
2. Put the file in the nextcloud folder for syncing with the nextcloud client
3. Download the file back using the client somewhere else and try to execute it.

### Client configuration
Client version: Version 2.6.2stable (build 20191224)

Operating system: osx Mojave 10.14.6

OS language: any

Qt version used by client package (Linux only, see also Settings dialog): 5.12.5

Client package (From Nextcloud or distro) (Linux only): from Nextcloud

Installation path of client: default

Nextcloud server version: 18.0

Thanks for your help!

**Comment by matis-schotte** [comment]
+1
Same problem here, but with .pkg files.
Looks like the file type recognized by the system is changed by nextcloud?

**Comment by mgallien** [comment]
Can you still reproduce this issue with latest release ?

**Comment by NeutroGe** [comment]
Sorry but this issue is over a year old and i've stopped using nextcloud since then so i can't. I think it could have been linked to this issue:

https://github.com/nextcloud/desktop/issues/206

If you want to try to reproduce it you can download a mac os big sur VM and use it to test. 

You can download a standalone mac osx app here: https://sveinbjorn.org/platypus

But you should be able to reproduce it with any standalone .app mac osx file.
