### ISSUE TITLE
Unicode characters not preserved when syncing

### ISSUE THREAD

**Issue by Iambecomeroot** [nextcloud/desktop#179]
I have folders and files with french accents on my server. When I sync them using the nextcloud client, these accents get replaced with question marks. This change then gets propagated to the server when I change files under these folder. Is there any way to keep the unicode characters?

`nextcloud --version`:
```
Nextcloud version 2.3.3
Git revision 57bc7918d7b0650c116f3512787f7677d4e5ab17
Using Qt 5.10.0, built against Qt 5.10.0
Using 'OpenSSL 1.1.0g  2 Nov 2017'
```

`uname -a` (client):
```
Linux Zeus 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux
```

Server version: 13.0.0

`uname -a` (server):
```
Linux nas 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux
```

**Comment by DominiqueFuchs** [comment]
@Iambecomeroot The latest stable client should be fully compatible with these unicode characters and I am not able to reproduce this issue nowadays (latest stable 2.5.3 and fresh NC 15 instance). Do you still experience issues with this?

**Comment by Iambecomeroot** [comment]
I have not noticed it for a while. Maybe you are right and it is fixed.
