### ISSUE TITLE
Context Menu in taskbar - German language gone after update to 2.6.3, only English available

### ISSUE THREAD

**Issue by mjunghanns** [nextcloud/desktop#1791]
### Expected behaviour
The context menu appearing after having clicked the Nextcloud Desktop's taskbar icon should display it's menu items in German (or local) language, as it has been prior to v2.6.3.
The screenshot below represents v2.6.2
![grafik](https://user-images.githubusercontent.com/22636982/74636182-c661c900-5167-11ea-9020-93e3e8e85243.png)

### Actual behaviour
The context menu items and the submenu items are now in English. The rest of the application is still in German and is thus operating as expected. 
![grafik](https://user-images.githubusercontent.com/22636982/74638566-6c173700-516c-11ea-826d-48928b5789e4.png)

### Steps to reproduce
1. Perform fresh install OR update existing installation
2. Right-click on Nextcloud Desktop's taskbar icon
3. Optionally, hover on any menu item that is capable of expanding sub-menuitems

### Client configuration
Client version:

Operating system: MS Windows 7 Professional SP 1

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): -

Client package (From Nextcloud or distro) (Linux only): -

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 17.0.3

Storage backend (external storage): Local

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

`[OCC::FolderMan::setupFolders 	Setup folders from settings file
[OCC::defaultJournalMode 	Detected filesystem "NTFS" for "C:/Users/<username>.<WINDOWS-DOMAIN>/Nextcloud/._sync_210288218b9e.db"
[OCC::ConfigFile::setupDefaultExcludeFilePaths 	Adding user defined ignore list to csync: "C:/Users/<username>.<WINDOWS-DOMAIN>/AppData/Roaming/Nextcloud/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal 	Adding folder to Folder Map  OCC::Folder(0x5858500) "1"
[OCC::FolderMan::scheduleFolder 	Schedule folder  "1"  to sync!
[OCC::FolderMan::scheduleFolder 	Folder is not ready to sync, not scheduled!
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://<nextcloud-srv-fqdn>/remote.php/webdav/" :  "Not yet Started"
[OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.24.0"
[OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
[OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use the prefered system proxy for http tcp connections
[OCC::WebFlowCredentials::fetchFromKeychain 	Fetch from keychain!
[OCC::SocketApi::slotNewConnection 	New connection QLocalSocket(0x58ea810)
[OCC::KeychainChunk::ReadJob::slotReadJobDone 	Unable to read "Nextcloud_<username>_clientCertificatePEM:https://<nextcloud-srv-fqdn>/:0" chunk "0" "Password entry not found"
[OCC::KeychainChunk::ReadJob::slotReadJobDone 	Unable to read "Nextcloud_<username>_clientKeyPEM:https://<nextcloud-srv-fqdn>/:0" chunk "0" "Password entry not found"
[OCC::WebFlowCredentials::slotReadClientKeyPEMJobDone 	Unable to read client key "Password entry not found"
[OCC::KeychainChunk::ReadJob::slotReadJobDone 	Unable to read "Nextcloud_<username>_clientCaCertificatePEM0:https://<nextcloud-srv-fqdn>/:0" chunk "0" "Password entry not found"
[OCC::WebFlowCredentials::slotReadClientCaCertsPEMJobDone 	Unable to read client CA cert slot "0" "Password entry not found"
[OCC::AccountState::slotCredentialsFetched 	Fetched credentials for "https://<nextcloud-srv-fqdn>" attempting to connect
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/status.php" has X-Request-ID "a9383189-4934-421c-a285-6011b1ee8998"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://<nextcloud-srv-fqdn>" + "status.php" "OCC::ConnectionValidator"
[OCC::Utility::registryWalkSubKeys 	ASSERT: "result == 0L" in file c:\nextcloud\desktop\src\common\utility_win.cpp, line 230
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","extendedSupport":false,"installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Nextcloud","version":"17.0.3.1","versionstring":"17.0.3"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x6caa320)
[OCC::ConnectionValidator::slotStatusFound 	** Application: ownCloud found:  QUrl("https://<nextcloud-srv-fqdn>")  with version  "17.0.3" ( "17.0.3.1" )
[OCC::ConnectionValidator::setAndCheckServerVersion 	QUrl("https://<nextcloud-srv-fqdn>") has server version "17.0.3.1"
[OCC::Account::writeAppPasswordOnce::::operator() 	appPassword stored in keychain
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://<nextcloud-srv-fqdn>/remote.php/webdav/" has X-Request-ID "052cd64c-d5ae-4e32-ba93-34f66d501a09"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://<nextcloud-srv-fqdn>" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://<nextcloud-srv-fqdn>/remote.php/webdav/") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "75c04dbd-1ac3-43e0-8b4f-c7da4583fbf5"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://<nextcloud-srv-fqdn>" + "ocs/v1.php/cloud/capabilities" "OCC::ConnectionValidator"
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/ocs/v1.php/config?format=json" has X-Request-ID "51cad916-051a-424c-bd13-8c503e9dccff"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://<nextcloud-srv-fqdn>" + "ocs/v1.php/config" ""
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://<nextcloud-srv-fqdn>/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
[OCC::ConnectionValidator::slotCapabilitiesRecieved 	Server capabilities QJsonObject({"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"bruteforce":{"delay":0},"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0"},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"default_permissions":31,"federation":{"expire_date":{"enabled":true},"incoming":true,"outgoing":false},"group":{"enabled":true,"expire_date":{"enabled":true}},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple_links":true,"password":{"askForOptionalPassword":false,"enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":false,"sharebymail":{"enabled":true,"expire_date":{"enabled":true},"password":{"enabled":true},"upload_files_drop":{"enabled":true}},"sharee":{"query_lookup_default":false},"user":{"expire_date":{"enabled":true},"send_mail":false}},"notifications":{"admin-notifications":["ocs","cli"],"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web"],"push":["devices","object-data","delete"]},"ocm":{"apiVersion":"1.0-proposal1","enabled":true,"endPoint":"https://<nextcloud-srv-fqdn>/ocm","resourceTypes":[{"name":"file","protocols":{"webdav":"/public.php/webdav/"},"shareTypes":["user","group"]}]},"password_policy":{"api":{"generate":"https://<nextcloud-srv-fqdn>/ocs/v2.php/apps/password_policy/api/v1/generate","validate":"https://<nextcloud-srv-fqdn>/ocs/v2.php/apps/password_policy/api/v1/validate"},"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"minLength":8},"spreed":{"config":{"chat":{"max-length":32000}},"features":["audio","video","chat-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","chat-read-marker","webinary-lobby","start-call-flag"]},"theming":{"background":"https://<nextcloud-srv-fqdn>/core/img/background.png?v=2","background-default":true,"background-plain":false,"color":"#0082c9","color-element":"#0082c9","color-text":"#ffffff","logo":"https://<nextcloud-srv-fqdn>/core/img/logo/logo.svg?v=2","name":"Nextcloud","slogan":"","url":"https://nextcloud.com"}})
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/ocs/v1.php/cloud/user?format=json" has X-Request-ID "e912263f-968b-4376-9d8a-95f054020474"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://<nextcloud-srv-fqdn>" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://<nextcloud-srv-fqdn>/ocs/v1.php/config?format=json") FINISHED WITH STATUS "OK"
[OCC::ConnectionValidator::ocsConfigReceived 	Determined user-visible host to be "<nextcloud-srv-fqdn>"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://<nextcloud-srv-fqdn>/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/remote.php/dav/avatars/<user-HASH-UUID>/128.png" has X-Request-ID "7ec26497-78df-4b66-b523-e51c1466c064"
[OCC::AbstractNetworkJob::start 	OCC::AvatarJob created for "https://<nextcloud-srv-fqdn>" + "" "OCC::UserInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::ClientSideEncryption::initialize 	Initializing
[OCC::ClientSideEncryption::initialize 	No Client side encryption avaliable on server.
[OCC::AccountState::slotConnectionValidatorResult 	AccountState connection status change:  OCC::ConnectionValidator::Undefined -> OCC::ConnectionValidator::Connected
[OCC::AccountState::setState 	AccountState state change:  "Getrennt" -> "Verbunden"
[OCC::ActivityListModel::startFetchJob 	Start fetching activities for  "<username>@<nextcloud-srv-fqdn>"
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/ocs/v2.php/cloud/activity?start=0&count=100&format=json" has X-Request-ID "3a74cf4e-a458-4977-a8b5-821fecce0a79"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://<nextcloud-srv-fqdn>" + "ocs/v2.php/cloud/activity" "OCC::ActivityListModel"
[OCC::AccessManager::createRequest 	2 "" "https://<nextcloud-srv-fqdn>/ocs/v2.php/apps/notifications/api/v2/notifications?format=json" has X-Request-ID "eb868b4c-b876-449a-8bed-b113e5f9f2ec"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://<nextcloud-srv-fqdn>" + "ocs/v2.php/apps/notifications/api/v2/notifications" "OCC::ServerNotificationHandler"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "REGISTER_PATH:C:\\Users\\<username>.<WINDOWS-DOMAIN>\\Nextcloud" to QLocalSocket(0x58ea810)
[OCC::AccountSettings::slotAccountStateChanged 	Accout "<username>@<nextcloud-srv-fqdn>" Client Side Encryption false
[OCC::FolderMan::slotAccountStateChanged 	Account "<username>@<nextcloud-srv-fqdn>" connected, scheduling its folders
[OCC::FolderMan::scheduleFolder 	Schedule folder  "1"  to sync!
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/" :  "Not yet Started"
[OCC::FolderMan::startScheduledSyncSoon 	Starting the next scheduled sync in 0 seconds
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://<nextcloud-srv-fqdn>/ocs/v2.php/apps/notifications/api/v2/notifications?format=json") FINISHED WITH STATUS "OK"
[OCC::ServerNotificationHandler::slotEtagResponseHeaderReceived 	New Notification ETag Response Header received  "d751713988987e9331980363e24189ce"
[OCC::ActivityListModel::clearNotifications 	Clear the notifications
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\<username>.<WINDOWS-DOMAIN>\\Nextcloud" to QLocalSocket(0x58ea810)
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/" :  "SyncPrepare"
[OCC::Folder::startSync 	*** Start syncing  "https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/"  - client version 2.6.3stable-Win64 (build 20200217)
[OCC::Folder::startSync 	Forbidding local discovery to read from the database
[OCC::FolderMan::slotFolderSyncStarted 	>========== Sync started for folder [Nextcloud] of account [<username>@<nextcloud-srv-fqdn>] with remote [https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/]
[OCC::SyncEngine::startSync 	There are 8047398912 bytes available at "C:/Users/<username>.<WINDOWS-DOMAIN>/Nextcloud/"
[OCC::SyncEngine::startSync 	Sync with existing sync journal
[OCC::SyncEngine::startSync 	"Using Qt 5.12.5 SSL library OpenSSL 1.1.1d  10 Sep 2019 on Windows 7 SP 1 (6.1)"
[OCC::SyncEngine::startSync 	Using Selective Sync
[OCC::SyncEngine::startSync 	#### Discovery start ####################################################
[OCC::SyncEngine::startSync 	Server "17.0.3.1" 
[csync_update 	## Starting local discovery ##
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://<nextcloud-srv-fqdn>/ocs/v2.php/cloud/activity?start=0&count=100&format=json") FINISHED WITH STATUS "OK"
[_csync_detect_update 	._sync_210288218b9e.db excluded  (1)
[_csync_detect_update 	._sync_210288218b9e.db-shm excluded  (1)
[_csync_detect_update 	._sync_210288218b9e.db-wal excluded  (1)
[_csync_detect_update 	Desktop.ini excluded  (1)
[_csync_detect_update 	Database entry found for HowTo, compare: 1581930005 <-> 1578466604, etag:  <-> 5e157d2e7c967, inode: 109915 <-> 109915, size: 0 <-> 0, perms: 0 <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	file: HowTo, instruction: INSTRUCTION_EVAL <<=
[_csync_detect_update 	Database entry found for HowTo/BIOS123.img, compare: 1578466604 <-> 1578466604, etag:  <-> 03bef5518ee762291e9d89dbd1ee2d1d, inode: 109916 <-> 109916, size: 29 <-> 29, perms: 0 <-> 19f, checksum:  <-> SHA1:3eefeeeac22ce09ea22f7516a0cd549d14603247 , ignore: 0,  e2e: 
[_csync_detect_update 	file: HowTo/BIOS123.img, instruction: INSTRUCTION_NONE <<=
[csync_ftw 	 <= Closing walk for C:/Users/<username>.<WINDOWS-DOMAIN>/Nextcloud/HowTo with read_from_db 0
[_csync_detect_update 	Database entry found for Neues Textdokument.txt, compare: 1578404696 <-> 1578404696, etag:  <-> 0f8be0a7fa84ea62d0dda41aded14afd, inode: 109919 <-> 109919, size: 15 <-> 15, perms: 0 <-> 9f, checksum:  <-> SHA1:fcb9d38ef649ea386643398e1561b1c85b28d9ed , ignore: 0,  e2e: 
[_csync_detect_update 	file: Neues Textdokument.txt, instruction: INSTRUCTION_NONE <<=
[csync_ftw 	 <= Closing walk for C:/Users/<username>.<WINDOWS-DOMAIN>/Nextcloud with read_from_db 0
[csync_update 	Update detection for local replica took 0.024 seconds walking 3 files
[csync_update 	## Starting remote discovery ##
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/" has X-Request-ID "b3cdd0e8-e513-4e9c-a3c9-d78d67f5565e"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://<nextcloud-srv-fqdn>" + "" "OCC::DiscoverySingleDirectoryJob"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::LsColJob::finished 	LSCOL of QUrl("https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/") FINISHED WITH STATUS "OK"
[OCC::Folder::etagRetreivedFromSyncEngine 	Root etag from during sync: "\"5e299990e9f22\""
[_csync_detect_update 	Database entry found for HowTo, compare: 1578466604 <-> 1578466604, etag: 5e157d2e7c967 <-> 5e157d2e7c967, inode: 0 <-> 109915, size: 0 <-> 0, perms: fd <-> fd, checksum:  <->  , ignore: 0,  e2e: 
[_csync_detect_update 	Reading from database: HowTo
[_csync_detect_update 	file: HowTo, instruction: INSTRUCTION_NONE <<=
[fill_tree_from_db 	1 entries read below path HowTo from db.
[_csync_detect_update 	Database entry found for Neues Textdokument.txt, compare: 1578404696 <-> 1578404696, etag: 0f8be0a7fa84ea62d0dda41aded14afd <-> 0f8be0a7fa84ea62d0dda41aded14afd, inode: 0 <-> 109919, size: 15 <-> 15, perms: 9f <-> 9f, checksum:  <-> SHA1:fcb9d38ef649ea386643398e1561b1c85b28d9ed , ignore: 0,  e2e: 
[_csync_detect_update 	file: Neues Textdokument.txt, instruction: INSTRUCTION_NONE <<=
[csync_ftw 	 <= Closing walk for  with read_from_db 0
[csync_update 	Update detection for remote replica took 0.085 seconds walking 3 files
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Discovery end ####################################################  115 ms
[csync_reconcile 	Reconciliation for local replica took  0 seconds visiting  3  files.
[csync_reconcile 	Reconciliation for remote replica took  0 seconds visiting  3  files.
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Reconcile end ####################################################  116 ms
[OCC::SyncEngine::slotDiscoveryJobFinished 	Permissions of the root folder:  "DNVCKR"
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Post-Reconcile end ####################################################  117 ms
[OCC::SyncJournalDb::close 	Closing DB "C:/Users/<username>.<WINDOWS-DOMAIN>/Nextcloud/._sync_210288218b9e.db"
[OCC::SyncEngine::finalize 	CSync run took  126 ms
[OCC::Folder::slotSyncFinished 	Client version 2.6.3stable-Win64 (build 20200217)  Qt 5.12.5  SSL  OpenSSL 1.1.1d  10 Sep 2019
[OCC::Folder::slotSyncFinished 	SyncEngine finished without problem.
[OCC::Folder::showSyncResultPopup 	Folder sync result:  2
[OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.24.0"
[OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\<username>.<WINDOWS-DOMAIN>\\Nextcloud" to QLocalSocket(0x58ea810)
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/" :  "Success"
[OCC::FolderMan::slotFolderSyncFinished 	<========== Sync finished for folder [Nextcloud] of account [<username>@<nextcloud-srv-fqdn>] with remote [https://<nextcloud-srv-fqdn>/remote.php/dav/files/<user-HASH-UUID>/]
[OCC::OCUpdater::backgroundCheckForUpdate 	Checking for available update
[OCC::AccessManager::createRequest 	2 "" "https://updates.nextcloud.org/client/?version=2.6.3.20200217&platform=win32&oem=Nextcloud&versionsuffix=stable-Win64" has X-Request-ID "08f776c3-3a23-4e1c-9f10-ac20a2ff357f"`

2. Web server error log: -

3. Server logfile: nextcloud log (data/nextcloud.log): -

**Comment by misch7** [comment]
Thanks for reporting!

Seems like some translation keys have been changed or removed and so the previous values got missing. Will be addressed in the next release then.

**Comment by rakekniven** [comment]
Related report at helpf forums:

https://help.nextcloud.com/t/desktop-client-2-6-3-sprache-ist-englisch-statt-deutsch/71410

**Comment by CarlosCastaneda** [comment]
> 
> 
> Related report at helpf forums:
> 
> https://help.nextcloud.com/t/desktop-client-2-6-3-sprache-ist-englisch-statt-deutsch/71410

Thanks for reporting my confirmation of the issue.

**Comment by Valdnet** [comment]
No translations here:

![obraz](https://user-images.githubusercontent.com/47037905/74772778-eccf5380-5290-11ea-8185-31d9f54d3388.png)

**Comment by DrCarsonBeckett** [comment]
Noticed that too and can confirm that too. If log files or specs are needed, simply tell me to.

**Comment by misch7** [comment]
Fixed in 2.6.4 by merging and auto-backporting translations: https://github.com/nextcloud/docker-ci/pull/203
