### ISSUE TITLE
Request - NextCloud client download mirrors

### ISSUE THREAD

**Issue by zingmars** [nextcloud/desktop#1795]
Hello,

This is not an issue with nextcloud desktop itself, but I'm wasn't sure where else to file this. Would it be possible to have mirrors for client downloads (i.e. why not store them using github releases). 
It's just that nextcloud.com is insanely slow for me - 
![image](https://user-images.githubusercontent.com/917126/74720356-55411500-523e-11ea-8e42-3db87a0c6c63.png)
And this is on a 100Mbit connection - 
![image](https://user-images.githubusercontent.com/917126/74720450-80c3ff80-523e-11ea-812b-6cd43775a636.png)

And it's not just this machine/connection. I've tried various machines (both desktop and laptops) and connections (coffee shops, university wi-fi, mobile networks), and I've never seen the download go above 150KB/s on any of them. Needless to say, it's very frustrating because the Windows client is 120MiB, and each update (even if they are fairly rare) takes more than 20 minutes because of this.

Thank you.

**Comment by cmasterdelphi** [comment]
I subscribe to that. It feels like, the servers are horrible slow. I only get 50kbit/s too.

**Comment by fl4co** [comment]
I've been trying to download the Mac desktop app since yesterday but it's painfully slow. If anyone managed to download it, it'd be awesome if he/she uploaded it somewhere else. I came to GitHub hoping to find alternative download links but unfortunately the binaries are only uploaded to the barely working download.nextcloud.com. I don't know how a situation like this can last for more than 24 hours when you have users complaining here and on the community boards.

**Comment by ElucGeek** [comment]
Would it be possible to have it on torrent? I'm sure many will be very happy to seed this.

**Comment by jospoortvliet** [comment]
Yeah, mirrors - or we should space out the updates. We just updated our servers to new hardware and then the updater for the desktop client attracted hundreds of thousands of users to flood the server...

I'll create a new issue for the spacing out of updates, I think it is a better solution than all the work that it takes to set up a mirror network - but the admins will have to decide.

**Comment by zingmars** [comment]
At the very least, can you please also upload the installers to github releases? Github's CDN is fairly fast pretty much everywhere and it shouldn't be that much additional work to add.

**Comment by mgallien** [comment]
The release are now distributed through github releases. So I am closing this issue now. Keep in mind that currently an update may need a few day before it is made available to all clients to download it.
