### ISSUE TITLE
Linux Client notifies of update and demands download although updates come automatically

### ISSUE THREAD

**Issue by rschr** [nextcloud/desktop#1799]
### Expected behaviour
No update notifications when updates come automatically

### Actual behaviour
Linux Client notifies of update and demands download although the update comes automatically via system updates (here: Ubuntu based system, official PPA).

### Steps to reproduce
1. Install Nextcloud client with apt packager from [official Nextcloud repository](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) 
2. Wait until an update is ready
3. Start Nextcloud client

### Client configuration
Client version: 2.6.2git
Operating system: Linux Mint 19.3

**Comment by Kieltux** [comment]
You can disable the notification in the nextcloud config file:
`~/.config/Nextcloud`
```
[General]
skipUpdateCheck=true
```

**Comment by rschr** [comment]
Excellent, thanks!

Would be nice, of course, to have it as an option in the GUI.

**Comment by JoshStrobl** [comment]
Package maintainer for nextcloud-client on Solus here. Personally I'd like a configure + compile-time CMake flag to disable this entirely, as Solus users get their package updates reliably every Friday, including for the Nextcloud client, and an update notification for something they really can't do anything about, nor need to be concerned about, isn't desired. If there are security related issues, they're already informed and we cherry-pick those onto our stable repository outside our weekly sync cycle.

**Comment by misch7** [comment]
Hey @JoshStrobl,

thanks for taking care of the package :)

I've created a PR to ease controlling the updater with a CMake flag, see #1847 

Since most likely everyone else (maintainers, contributors) will want to compile without the updater, I decided to disable the updater build by default.

So you won't have to change anything to skip the updater for future master and release builds ;)

**Comment by claell** [comment]
@JoshStrobl #1512 seems to be requesting exactly what you want.

**Comment by claell** [comment]
@rschr look at #1480 for having a GUI option.

**Comment by claucambra** [comment]
We now have a GUI option + compile time parameters to disable the updater component
