### ISSUE TITLE
space out update notifications

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#1800]
As mentioned in #1795 - our servers got flooded with hundreds of thousands of users who wanted a new version of our client. That doesn't really work - so we have to space out the updates a bit. How-what-I dunno, I leave that to you, team ;-)

**Comment by Volker-K** [comment]
How do the users install the desktop client? Any software distribution you can control or du they download it themselves?
If you can control the distribution, add
```
[UPDATER]
seenVersion=99
```
to ~/AppData/Roaming/Nextcloud/Nextcloud.cfg and no one will be asked to install a new version anymore.

**Comment by andyg2** [comment]
The download is painfully slow at all times, spacing out the update notifications isn't going to help with that.
Creating a release on GitHub is both simple and a guaranteed fix for the problem. It's also free and unlimited.

We don't limit the total size of the binary files in the release or the bandwidth used to deliver them. However, each individual file must be smaller than 2 GB.

https://docs.github.com/en/github/managing-large-files/distributing-large-binaries

https://docs.github.com/en/github/administering-a-repository/about-releases

**Comment by jospoortvliet** [comment]
fixed by using github for downloads.
