### ISSUE TITLE
[v2.7.0-beta1] Closing Google Chrome exits Nextcloud Client

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#1804]
### Expected behaviour
The Client should be indipendet from other applications exiting.

### Actual behaviour
The Nextcloud client silently exits after closing a Google Chrome Incognito Tab. I think there are more cases but this is one i could reconstruct.

### Steps to reproduce
1. Start Nextcloud Client
2. Start Google Chrome Incognito Tab
3. Close Google Chrome

### Client configuration
Client version: v2.7.0-beta1

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

I think this is the relevant part:
```
[OCC::SocketApi::slotNewConnection 	New connection QLocalSocket(0x13e929a1120)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "REGISTER_PATH:C:\\Users\\******\\Nextcloud" to QLocalSocket(0x13e929a1120)
[OCC::SocketApi::slotReadSocket 	Received SocketAPI message <-- "GET_STRINGS:CONTEXT_MENU_TITLE" from QLocalSocket(0x13e929a1120)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "GET_STRINGS:BEGIN" to QLocalSocket(0x13e929a1120)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:Nextcloud" to QLocalSocket(0x13e929a1120)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "GET_STRINGS:END" to QLocalSocket(0x13e929a1120)
[OCC::SocketApi::slotReadSocket 	Received SocketAPI message <-- "GET_MENU_ITEMS:C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" from QLocalSocket(0x13e929a1120)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x13e929a1120)
```

**Comment by splitt3r** [comment]
@DominiqueFuchs this seems to be related to the new tray menu. Could you have a look at it?

**Comment by splitt3r** [comment]
Downgrading to 2.6.4 fixed the issue for me. The issue also appeared with normal Chrome Tabs + the new Chromium based Edge browser.

**Comment by er-vin** [comment]
I can't seem to reproduce it at all. I opened and closed plenty of tabs without the application quitting (neither on latest daily nor on the beta1).

**Comment by er-vin** [comment]
Alright, from the log and the fix I have (PR to come in a minute) I think this is unrelated to chrome and more related to the shell integration since indeed there was a mistake when the menu items were requested.
