### ISSUE TITLE
Add sha sum and/or gpg signing to distributed binaries

### ISSUE THREAD

**Issue by xgqt** [nextcloud/desktop#1805]
Operating system:
all

Client package (From Nextcloud or distro) (Linux only):
any/all

Comment:
It would be nice to add sha sum and/or gpg signing to distributed EXEs, PKGs and AppImages.
Please consider this for users' safety and trust towards your project.

**Comment by er-vin** [comment]
Starting with 3.0.2 those binaries are signed

**Comment by xgqt** [comment]
> Starting with 3.0.2 those binaries are signed

nice
thanks a lot :D

**Comment by resoli** [comment]
Hello, i came here after searching to validate latest Appimage `Nextcloud-3.16.0-x86_64.AppImage` , but it doesn't appear to be signed:

`./validate-x86_64.AppImage Nextcloud-3.16.0-x86_64.AppImage 
Error: AppImage not signed
`
