### ISSUE TITLE
Windows Client doesn't remove sync folder from explorer permanetly after deactivating the option to show them

### ISSUE THREAD

**Issue by OdinsAuge** [nextcloud/desktop#1807]
### Expected behaviour
When I deactivate the Option "Show Sync-Folders in explorers navigation area" (Synchronisierungsordner im NAvigationsbereich des Explorers anzeigen), I don't want to see the Sync Folders there.

### Actual behaviour
After each restart, the sync folderes are there again.
Activating and deactivating the optin, removes them again, but after the next restart hey are there again.

### Steps to reproduce
1. Deaktivate the Option
2. Restart the PC

### Client configuration
Client version: 2.6.3

Operating system: Windows 10

### Server configuration

Nextcloud version: 17.0.3

**Comment by misch7** [comment]
Thanks for reporting! :)

Fixed by PR #1820 and will get into the 2.6.4 release.
