### ISSUE TITLE
NC Windows Client 2.6.3 crashes while adding new account

### ISSUE THREAD

**Issue by thoka** [nextcloud/desktop#1815]
Short time aftger adding and validating a new account, the windows client (win10) crashed without any notice. 
After restart there was no new account added.
I enabled logging but there were no hints to problems in the logs.

As a next step I renamed the nextcloud config directory in %AppData/Roaming to start with a fresh configuration. 
After restarting the client, some account information still survived and adding an other account gave a new crash.

The problem was solved by deleting some old configuration found in %AppData/Local.

**Comment by misch7** [comment]
Thanks for reporting. I guess you refer to the 2.6.3 release?

Since you examined the configuration files: Did you see any special difference between the old (now deleted) config and the new files?

**Comment by thoka** [comment]
Hm. The content inside $AppData/Local/Nectcloud.cfg was only some remains of login information:
```
[General]
optionalDesktopNotifications=true

[Accounts]
version=2
0\url=https://some.domain.de
0\serverVersion=14.0.3.0
0\http_user=user
0\authType=http
0\user=user

[ActivityListHeader]
geometry=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\x93\0\0\0\x5\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0W\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x5\0\0\0k\0\0\0\x1\0\0\0\0\0\0\0\xb4\0\0\0\x1\0\0\0\0\0\0\0W\0\0\0\x1\0\0\0\0\0\0\0W\0\0\0\x1\0\0\0\0\0\0\0\xc6\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0)

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x2]\0\0\0\xec\0\0\x5\x1d\0\0\x3\\\0\0\x2\x63\0\0\x1\x6\0\0\x5\x17\0\0\x3V\0\0\0\0\0\0\0\0\a\x80)
```

The old $AppData/Roaming/Nectcloud.cfg included a large `0\General\CaCertificates="@ByteArray(-----BEGIN` entry and `[Proxy]` and `[ActivityListeHeader]` sections , which all are not part of the new config files.
