### ISSUE TITLE
Nextcloud sync is slow when you folder to sync is on cifs/smb mount

### ISSUE THREAD

**Issue by yodatak** [nextcloud/desktop#1816]
### Expected behaviour 
The sync of a folder take like 20s to download every file even when the folder is on a smb share

### Actual behaviour
Nextcloud-client crash and it take like 5 hours to download every file 

### Steps to reproduce
1. On a fedora 31
2. You have a cifs mounted folder or disk 
3. You decided to sync a folder on you nextcloud into /mnt/server/Nextcloud
4. The ui become unresponsive and even crash 

### Client configuration
Client version:

//192.168.1.XXXX/share on /mnt/server type cifs (rw,relatime,vers=3.1.1,cache=strict,username=XXXX,domain=SAMBA,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.1.XXX,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1)

Operating system: Fedora 31 64bit

OS language: Francais

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Nextcloud version 2.6.2git on fedora rpm

Installation path of client:

### Server configuration

Nextcloud version: 18

Storage backend (external storage): no external storage 
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
https://gist.github.com/yodatak/3cddfcaacd71476ff83c761d661a5c67

**Comment by heeplr** [comment]
can confirm this (nextcloud 20.0.5)

I *suspect* sqlite sync db/journal is the cause of this, although i'm not sure. Is there a way to move the db/journal to another location outside of the actual sync folder to test this?

i'm using various nextcloud accounts to sync ~1 TB of data. Locally I use a smallish SSD + CIFS NAS, so syncing to a non-network path wouldn't be an option. Tests show, that it works flawlessly, when syncing on the SSD.

**Comment by CombeeMike** [comment]
You could try symlinks. Move the files to the SSD, create symlinks from CIFS (Nextcloud sync target location) -> files on SSD.
I can't tell if this makes the SQLite driver actually use the file SSD location or if it still has to "go through" the CIFS. It could even break the client but it could be worth a shot 🤷‍♂️

**Comment by CombeeMike** [comment]
BTW I'm experiencing the same issues. Sync client is running on Ubuntu 18.04 and I'd like to sync data to a Synology NAS DS216j...

**Comment by mgallien** [comment]
Could you please check if that can be reproduced using the latest 3.2.1 version ? There has been many fixes in 3.2.0 around file syncing.

**Comment by CombeeMike** [comment]
@mgallien I'll have a look but I don't know when I'll get to it...
I'll let you know here once I explicitly tested with the new version.

**Comment by CombeeMike** [comment]
@mgallien

I updated to `v3.2.1` yesterday and added a sync connection to my `NAS DS216j` which is mounted via cifs.

The situation is pretty much the same as with the old version. The sync of 38 GB of data is still running after ~ 24 hours even though the NAS is on the same 100 GB network as the sync client.

Also the client shows me some errors (`... webserver returning empty content length for non-empty file on resume`) and is pretty much unresponsive all the time. E.g. I have the "settings view" open with the new sync connection selected and when I click on the "General" tab, it takes some minutes before the view actually changes. Sometimes the OS (`Ubuntu 20.04.2 LTS`) grays out the app and tells me that it's unresponsive with the option to wait or terminate etc.

Please let me know if I can give you any more useful information like debug logs etc.

**Comment by ice-92** [comment]
I have the exact same issue using a samba share. Very annoying. 

Nextcloud version 3.2.0git
