### ISSUE TITLE
Respect protocol querying the token endpoint

### ISSUE THREAD

**Issue by devlux** [nextcloud/desktop#1817]
### Expected behaviour
Connection a new client to a server with HTTPS should call the token endpoint respecting the requested protocol (HTTPS).

### Actual behaviour
Trying to connect a new client for server that uses HTTPS fails as the wrong protocol (HTTP) is used to query the token endpoint.

### Steps to reproduce
1. Try to connect a new client 
2. Log in
3. Server Address to a HTTPS-only server
4. Grant access
5. Keep waiting until error appears

### Client configuration
Client version: 2.6.3

Operating system: win10

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 18.0.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by rullzer** [comment]
We query the endpoint the server gives us back.

My guess is you are behind some reverse proxy and you didn't set: overwriteprotocol

**Comment by devlux** [comment]
ah thank you for the information, will check that! :-)

**Comment by devlux** [comment]
overwriteprotocol did the trick, thanks @rullzer

**Comment by RuofengX** [comment]
I got same problem, also open the setting `'overwriteprotocol' => 'https'` in config.php.
I think it may be the nextcloud server's bug.
