### ISSUE TITLE
After update to nc13 client tries to delete local folders

### ISSUE THREAD

**Issue by KB7777** [nextcloud/desktop#182]
Hello.

I had just right now situation as described here -- https://help.nextcloud.com/t/after-update-to-nc-13-client-tries-to-delete-folders/27284, but I don't sync over SMB. Every files are at my local Windows10 client.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by camilasan** [comment]
if you still have this problem, please re-open the issue.

Thanks!
