### ISSUE TITLE
Windows Client cannot upload more than 1 encrypted (E2E) file otherwise stucks forever

### ISSUE THREAD

**Issue by banane4711** [nextcloud/desktop#1822]
### Expected behaviour
When copying files in a folder marked as encrypted the client should upload all files and be ready for next topic afterwards

### Actual behaviour
Single uploads do work if files are copied one by one (and the user is waiting for the sync of each file before copying the next one
If more than one file is copied or a file is renamed the client stucks. Even after restarting the client or the server the encrypted directory is no longer usable and all uploads to this directory stuck
(unencrypted files can be copied without problems, even whole folders are synchronized)

### Steps to reproduce
1. Create a new encrypted directory
2. Sync the directory to Your local Windows installation
3. Copy several files to that directory
4. The first file gets copied, afterwards the client stucks forever

### Client configuration
Version 2.6.3stable-Win64 (build 20200217)

Operating system:
Windows 10 V1909

OS language:
German

Installation path of client:
C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 18.0.1

Storage backend (external storage):
Only internal storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
https://gist.github.com/banane4711/6e59458f789b209e7fbc2269b2f1a94e

2. Web server error log:
No Webserver Errors

3. Server logfile: nextcloud log (data/nextcloud.log):
https://gist.github.com/banane4711/d91eb448c68295b3534bb6a5f6103159

**Comment by banane4711** [comment]
I tried a bit more. Unencrypted files are running without any issues. 
If I try to access files from Android I get the message "File locked".I tried to unlock files by cleaning up the database manually using SQL, I flushed the redis cache and restarted redis but anyway it does not solve the problem.

**Comment by allexzander** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/2853 and will be released in 3.2.
