### ISSUE TITLE
Client sync icon shown as white square with faint sync status icon within it

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/desktop#1831]
### Expected behaviour
The icon should show in the manner it has been designed.

### Actual behaviour
The icon is showing as a white square, with a faint sync status icon within it.
![image](https://user-images.githubusercontent.com/9272078/75864316-1ac0a600-5e02-11ea-88b9-d1dbf4cad34f.png)

### Client configuration
Client version: 
2.6.3git

Operating system: 
Manjaro Gnome Stable

OS language: 
English

Qt version used by client package (Linux only, see also Settings dialog): 
QT5, 0.41

Client package (From Nextcloud or distro) (Linux only): 
Community repository

Installation path of client:
```
[arnom@AMJ ~]$ which nextcloud-client
which: no nextcloud-client in (/home/arnom/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin)
```

**Comment by ohrie** [comment]
Does it still have this behavior on Gnome 3.36 with the latest Manjaro release?

**Comment by ohrie** [comment]
Also try with newer Nextcloud Client 2.6.4 which is also available via Manjaro package managers.

**Comment by edalongeville** [comment]
On an up to date Manjaro using Gnome 3.36.1 and Nextcloud desktop client 2.6.4-1, the icon is 3 dots, no matter what the status is (syncing, up to date,...).

Icon at the extreme right:
![Screenshot from 2020-04-30 12-54-53](https://user-images.githubusercontent.com/22616866/80702857-03d8c000-8ae2-11ea-85bd-e568e69ae071.png)

**Comment by armaccloud** [comment]
Manjaro is updated for me too.
Nextcloud is on version 2.4.6.
Since the latest Manjaro updates of a week ago, the icon changed, showing much better (but still not full) transparency. See second icon.

![image](https://user-images.githubusercontent.com/9272078/80704263-92e6d780-8ae4-11ea-8d89-7d2e93f271cc.png)


@edalongeville That is strange, for me the icons do show the different states. What package and version are you using? I've got this one

![image](https://user-images.githubusercontent.com/9272078/80704385-c295df80-8ae4-11ea-94b5-e8aa6756cff2.png)

**Comment by edalongeville** [comment]
@armaccloud This is odd, I'm using the exact same package. My system was freshly installed yesterday.

Do you think the Nvidia proprietary driver could be causing this?
Most of the issues I've had over the last year were caused by Nvidia, so it's now my suspect number one every time something goes wrong.

**Comment by armaccloud** [comment]
It could be something to try out, I am using the video-modesetting package instead of the proprietary driver, which actually works better for me (less lag when scrolling webpages).

**Comment by veddox** [comment]
@edalongeville The 3-dot icon is an upstream issue, see the discussion at #1977
