### ISSUE TITLE
Empty lines and lines starting with unesacaped # in sync-exclude.lst are undesirably shown in interface

### ISSUE THREAD

**Issue by kroko** [nextcloud/desktop#1833]
### Expected behaviour

The behaviour should be as for few last years where empty lines and those starting with unesacped  `#` (comment lines) in `sync-exclude.lst`  are not shown in Nextcloud desktop client interface, *Ignored Files Editor* window.  
I have been "using" custom sync exclusions for long time (see [this](https://github.com/WARP-LAB/nextcloud-settings-for-programmers)) and this behaviour is a regression.

### Actual behaviour

All empty lines in  `sync-exclude.lst` file show up as empty entries in GUI.  
All lines starting with unescaped `#` in  `sync-exclude.lst` file show up as empty entries in GUI.  
I believe that it is a bug based on fact that even your own *default* `sync-exclude.lst` file which can be obtained by clicking *Restore Defaults* has empty lines... and that results in redundant empty lines in GUI.

See screenshot.

![Annotation 2020-03-04 231158](https://user-images.githubusercontent.com/720976/75924094-02d33b80-5e6f-11ea-9453-f76636dc7fce.jpg)

### Steps to reproduce

1. Within Nextcloud _Settings_ under _General_ tab click _Edit Ignored files_ to bring up _Ignored Files Editor_ window. Click _Restore Defaults_, it should create file (if not exists) and fill it Built in patterns.
2. Check GUI modal *Ignored Files Editor* (see screenshot) and observe empty lines.
3. Edit `sync-exclude.lst` by adding _comment lines_ - lines starting with unescaped `#`.
2. Check GUI modal *Ignored Files Editor* (see screenshot) and observe even more empty lines.

### Client configuration
Client version:  
2.6.4stable-Win64 (build 20200303)

Operating system:  
MSW 10 64bit

OS language:  
English

Installation path of client:  
C:\Program Files\Nextcloud

### Server configuration

DNA

### Logs

DNA

**Comment by FlexW** [comment]
I think this problem is resolved.
