### ISSUE TITLE
100% when trying to sync certain folders on both Windows and Manjaro Linux

### ISSUE THREAD

**Issue by TobiasDev** [nextcloud/desktop#1837]
### Expected behaviour
The client to not crash while syncing files.

### Actual behaviour
The Windows and Linux app crashes when trying to "clean" sync certain folders, 100%

### Steps to reproduce
This is pretty difficult to say, because it seems to only affect certain folders. I can't figure out why they are crashing. The weirdest part is that it also changes which folder causes the 100% crash depending on if I'm using Windows or Linux.

### Client configuration
Version 2.6.4stable-Win64 (build 20200303)

Operating system:
Windows 10, and Manjaro Linux

OS language:
English and Swedish

**Comment by TobiasDev** [comment]
It's getting worse. I have been trying to sync a 900KB folder, and it crashes every single time. I have even done a selective sync with only this folder, and it has a 100 crash rate no matter if I do this folder or another one.

**Comment by TobiasDev** [comment]
Not sure if this helps: 

```
(process:5501): GLib-GIO-CRITICAL **: 21:23:51.134: g_menu_insert_item: assertion 'G_IS_MENU (menu)' failed
Segmentation fault (core dumped)
```

But this is what it says in the log when running the client through the console on Linux.

**Comment by misch7** [comment]
Could you provide the output of the client logs from both machines?

`nextcloud --logdebug --logflush --logfile <FILENAME>`

You may replace sensitive information like username and server URL using an editor. For more options see `nextcloud --help`.

**Comment by TobiasDev** [comment]
> Could you provide the output of the client logs from both machines?
> 
> `nextcloud --logdebug --logflush --logfile <FILENAME>`
> 
> You may replace sensitive information like username and server URL using an editor. For more options see `nextcloud --help`.

Will do, on my way to work, but I'll post it later today.

**Comment by TobiasDev** [comment]
Here is the log file from my Manjaro installation, I got Windows to work by downloading, folder, by folder, by folder. So I prefer not removing that and starting over. :( Unless you really have to have the log file from that one as well? Because on my Manjaro KDE it doesn't even work to do the folder by folder sync. :( 

[ManjaroKDE_NextCloud_Log.txt](https://github.com/nextcloud/desktop/files/4306658/ManjaroKDE_NextCloud_Log.txt)

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is fixed, can you close the issue ?
