### ISSUE TITLE
No write access to external micro SD card

### ISSUE THREAD

**Issue by caco3** [nextcloud/desktop#1840]
I have a x86 tablet where I installed [Android x86](https://www.android-x86.org/). I know this is a rater unusual setup, but I don't think the issue is related to this since other apps on the same system do not have this issues to write to the external micro SD card.

**Issue**
The Android nextcloud client `3.10.1` has no write access to the external micro SD card. The easiest way to prove this is by trying to upload a file to nextcloud. The app then shows a warning that the file system is read only:
![resized_DSC_0030](https://user-images.githubusercontent.com/1783586/76033043-878b8b80-5f3b-11ea-9748-da762e281816.JPG)

Notes:
* The app has all permissions!
* The app never asked me for write permissions on the external micro SD card!

**Comment by misch7** [comment]
This repository is for the Desktop Client only (Linux, macOS, Windows).

Please create Android issues at this repository:
https://github.com/nextcloud/android
