### ISSUE TITLE
macOS notification with broken link

### ISSUE THREAD

**Issue by botic** [nextcloud/desktop#1844]
![grafik](https://user-images.githubusercontent.com/193023/76143285-8c088f00-6076-11ea-808b-d2bfdd1a3fee.png)

### Expected behaviour

No HTML should be visible in the notification text. Clicking the OS notification should open the download page.

### Actual behaviour

Nothing happens if I click the notification and I need to manually go to the download page in my browser.

### Steps to reproduce

1. Receive the notification on macOS
2. Click on it
3. The notification drawer just disappears

### Client configuration

Client version: 2.6.3 (but also noticed before in earlier releases)
Operating system: 10.15.3 (also noticed on earlier 10.5.x releases)
OS language: German

### Server configuration

Nextcloud version: 17 and 18

### Logs

Not applicable.

**Comment by dems54** [comment]
Same bug for me on 2.6.5

**Comment by MorrisJobke** [comment]
@er-vin I can reproduce this here as well if you need help debugging or testing a fix.

**Comment by er-vin** [comment]
@MorrisJobke this would need someone like @camilasan @misch7 or @DominiqueFuchs who have a Mac to look into it.

**Comment by misch7** [comment]
This is related to the upcoming auto-update function, like mentioned in #1798. Once we have that working, no link will remain within the notification.

**Comment by botic** [comment]
This issue is still present in the current client. I still send out mails to our users to force them to update. Very bad UX if you want to keep all clients on the latest release.

**Comment by FlexW** [comment]
Should be fixed by https://github.com/nextcloud/desktop/pull/3052

**Comment by botic** [comment]
Thanks! If it opens the correct download page on click, most problems would be gone :) This would be wonderful, since small distributed teams don't have the central enterprise update infra.

**Comment by FlexW** [comment]
@botic On MacOS the link is still not clickable. Unfortunate MacOS does not support embedding links in the notification. Please read my comment in the corresponding pull request.
