### ISSUE TITLE
Deselection of Deskop Icon under Windows doesn't work

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/desktop#1846]
With latest Windows Desktop Client 2.6.4 in installation procedure
a deselection of desktop symbol doesn't work.

In every setup option a desktop symbol will be created.

**Comment by misch7** [comment]
Thanks for reporting! 👍 

I guess the setup script is missing an instruction to save the option in the config file, so the client adheres to its default (true) for the option.

**Comment by Siggi0904** [comment]
Hi,

still not fixed in 2.6.5

Please check.

**Comment by er-vin** [comment]
Will be solved by the upcoming MSI installer.
