### ISSUE TITLE
Add an integrated updater

### ISSUE THREAD

**Issue by Ich5003** [nextcloud/desktop#1849]
### Expected behaviour
When there is a new update a message should appear, that a new update is available.
Accepting the update should start an integrated updater, which will then download the real updater from the website and immediately start the downloaded updater.
From this point on the following steps equal those from manually updating.
_This is just one possible solution for an integrated updater. Downloading the update in background and notify the users to start it would be another._

### Actual behaviour
Clicking the `Update now` button opens the webbrowser which is then downloading the file.
User needs to manually start the downloaded file to update.

### Reasons for this feature-request
1. Non-techie users may find the update process complicated and confusing. In the worst case they stop updating their client software and it may get incompatible to the server version some time.
2. When downloading the file users often forget to then start the update, so after the next restart the `Update available` dialog will pop up again reminding the user to download the update. Some users may recognize they already downloaded the file some time ago and may simply start the update. Other users might start the procedure from the beginning with downloading the update and may again forget to start the update after downloading the file.

In my opinion the current update process is more complicated than it need's to be and should be simplified to improve UX.

**Comment by splitt3r** [comment]
They are working on it 😀 have a look at https://github.com/nextcloud/desktop/pull/1847.

**Comment by Ich5003** [comment]
Thank you @splitt3r 
I searched if there is already an issue for this, but I didn't find any.

**Comment by claell** [comment]
@Ich5003 I think I found an issue regarding this: #1798. So I guess this can be closed as a duplicate.
