### ISSUE TITLE
[i18n] Cannot find the Occitan translation

### ISSUE THREAD

**Issue by ensag-dev** [nextcloud/desktop#1852]
Hello,
whereas the client is being translated on Transifex, I cannot find theses translations on the GitHub and thus on the desktop client.
How to import the translation form Transifex so the Occitan language is available?
Best regards

**Comment by ensag-dev** [comment]
Anyone?

**Comment by enboig** [comment]
I was missin Catalan some years ago on server, and they told me that languages under ~80% were not included in releases. If Occitan is in transifex you should ensure at least 80% is translated for server and/or client.

I cannot assure this is your case, but is worth a try.

**Comment by rakekniven** [comment]
Currently the client has 53,25% completeness.
See https://www.transifex.com/nextcloud/nextcloud/language/oc/

@misch7 Can you confirm the 80% threshold?

**Comment by enboig** [comment]
I cannot, I just found my mail and it was nextcloud server related:

> It is automatically added if core and settings are above 75 % translated :)
> https://github.com/nextcloud/docker-ci/blob/master/translations/handleTranslations.sh#L45
> Thanks for your help

**Comment by Mejans** [comment]
Hello!
Seems like now it's imported https://github.com/nextcloud/desktop/commits/master/translations/client_oc.ts
En Boig, quin nom ^^ Nos tornem totes bauges/boijos amb la situacion actuala :P

**Comment by rullzer** [comment]
Yes we have a threshold for translations.
Please check if in tomorrows daily build the translation is present.

**Comment by rakekniven** [comment]
So it is 50% for nearly all resources, or?

**Comment by ensag-dev** [comment]
I have my client in Occitan for some months now :)
