### ISSUE TITLE
time of last sync not localized

### ISSUE THREAD

**Issue by adymitruk** [nextcloud/desktop#1856]
### Expected behaviour
The client shows the time since last sync wrt the same timezone.

### Actual behaviour
The time is shown in probably UTC.

![Screenshot_20200310_190959](https://user-images.githubusercontent.com/159030/76376042-87f1a100-6304-11ea-9fb7-1d7356f885c3.png)

### Steps to reproduce
sync a file from the pacific time zone in the evening
observe the sync client's "last saved" blurb

### Client configuration
Client version:
2.6.4-20200303.193231~bionic1

Operating system:
Ubuntu 18.04 w/ Kubuntu desktop

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
ppa

Installation path of client:
/usr/bin

### Server configuration

Nextcloud version:
Nextcloud 17.0.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by adymitruk** [comment]
this should be easy to fix. I don't mind doing it myself if someone points me to the code that's sending the unadjusted timezone.

**Comment by FlexW** [comment]
I think this does not apply anymore. Please reopen the issue if the problem still exist.

**Comment by emichael** [comment]
I'm currently seeing this same behavior with Version 3.3.1 (Ubuntu) of the desktop app and a server running Nextcloud 21.0.4.
