### ISSUE TITLE
Nextcloud desktop constantly querying DNS

### ISSUE THREAD

**Issue by pagaille** [nextcloud/desktop#1860]
Hi,

I recently added [pihole](https://pi-hole.net) to my network (basically a DNS server for Network-wide Ad Blocking) and noticed that the nextcloud client was making a LOT of DNS requests. The usual rate is one request per 30 second. That's odd and not really efficient 😊

Oddly enough, that happens also when the computer is supposed to be sleeping. 

<img width="799" alt="image" src="https://user-images.githubusercontent.com/1886799/76452029-b472ef00-63d0-11ea-9575-f9c2640d7653.png">

Version 2.6.4stable (build 20200303) - OSX Catalina 10.15.3 (19D76)

Thanks for having a look into this.

Matthieu

**Comment by jlHertel** [comment]
I also recently setup pihole and noticed the same behavior.
Maybe something is not properly caching the DNS entry.

**Comment by pagaille** [comment]
Please note that it is the case on Windows and OSX. Any comment on this ?

**Comment by FlexW** [comment]
When not using the push notifications backend the client polls the server every 30 seconds for file, notifications and activity changes. I also noticed that the client makes a lot unnecessary avatar requests (every 30 seconds).

**Comment by pagaille** [comment]
Not sure I understand what you mean by "push notification backend". My setup is quite standard and the notification app (if relevant) is installed and enabled. Is there anything I can do ?

**Comment by FlexW** [comment]
No, it has nothing to do with the notification app. With Nextcloud 21 there was a high performance backend for files introduced https://github.com/nextcloud/desktop/issues/1860#issuecomment-806452946. With that enabled, the client does not need to poll the server every 30 seconds for file/notification changes.

**Comment by pagaille** [comment]
Well, I just checked again, and as far as I can tell the number of DNS requests issued by the desktop client as dropped to a much more acceptable rate : 350 requests during the last 24h on my home network.
