### ISSUE TITLE
300 files - each 80K - do not synch

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/desktop#1862]
* NC 14.0.4
* End-to-End Encryption 1.0.5
* Windows Desktop Client 2.5.1final (build 20181204)

To reproduce:
* Enabled E2E for folder "TestE2E"
* Copied 300 files with ~80K each to that folder
* Synch does not happen
* Synch with the same files in unencrypted folder "Test" works

Nothing in the NC logs.

![grafik](https://user-images.githubusercontent.com/3857906/49689288-775de400-fb1f-11e8-8f50-b5280219b307.png)

300 files:
[TestE2E.zip](https://github.com/nextcloud/end_to_end_encryption/files/2659936/TestE2E.zip)

**Comment by georgehrke** [comment]
cc @misch7

**Comment by er-vin** [comment]
This is confirmed, both on Windows and Linux actually. Doesn't look platform specific.
