### ISSUE TITLE
Client deletes folders locally and shows folders as new folders

### ISSUE THREAD

**Issue by digi772** [nextcloud/desktop#1863]
### Expected behaviour
Client should not delete folders locally

### Actual behaviour
Client deletes folders locally and shows the folders as new folders, see screenshot.

### Steps to reproduce
It is hard to reproduce the error, but the error occured now on the 4th notebook with different client versions (1x Client 2.5.2  2x Client 2.6.2, 1x Client 2.6.3)

### Client configuration
Client version: 2.5.2/2.6.2/2.6.3

Operating system: Windows 10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 17.0.1
![Nextcloud 2020-03-12_github](https://user-images.githubusercontent.com/62095205/76522928-c5227400-6467-11ea-8f93-98d89c7dd77f.jpg)

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by jurgenhaas** [comment]
I'm seeing a similar issue and I reported it in the groupfolders module: https://github.com/nextcloud/groupfolders/issues/828

My impression is that this happens if the external storage (i.e. also group folders) are temporarily not available as it always happens during update.

**Comment by theroch** [comment]
The beavior exists also with [this bug](https://github.com/nextcloud/server/issues/20622)!
I think the client should mark the folders locally as deleted and after a configurable timeout the folders can be realy removed from disk.
It's not very funny to always reload several GBs from the server while the connections was broken for some seconds or minutes.
Maby it is also possible to ask the user to delete the folders finally?
