### ISSUE TITLE
Files become not encryped in folders with german umlauts 

### ISSUE THREAD

**Issue by larslehners** [nextcloud/desktop#1864]
Looks like encryption does not apply to files in folders with german umlauts in foldername like "verschlüsselt". 

To reproduce:
When I create such a folder on my mac (OSX 10.14.13) and encrypt it with the mac nextcloud client (2.5.1final 2.5.1final build 20181204) the lock icon is set. After sync I can see the folder with the lock icon in webapp too and I'm not able to access it. After uploading a file to the folder via mac nextcloud client, it is not safed encrypted on the nextcloud servers filesystem. 

I'm using nextcloud 15.0.4.0. Ther're not third party apps installed.

**Comment by georgehrke** [comment]
cc @misch7

**Comment by er-vin** [comment]
I confirm this is still the case on current master, will need to be fixed before 2.7.0.
