### ISSUE TITLE
Desktop client not recognizing subfolder as encrypted

### ISSUE THREAD

**Issue by StefanAbl** [nextcloud/desktop#1867]
I enabled e2e for a folder using the desktop client on Windows (Version 2.5.3daily.win64)
Added a subfolder on my phone using the Nextcloud-dev app from F-Droid and uploaded a picture to it.
The folder did not show the padlock symbol in the Desktop Client and the picture was not readable additionally a file created in said subfolder on the Desktop client was not encrypted on the server but rather it was readable to the root user of the server. 
On the other hand a test file created on the Desktop not in the subfolder was properly encrypted on the server but readable by both clients.
![grafik](https://user-images.githubusercontent.com/48151667/63179115-b992da00-c04b-11e9-8832-65761dc2019c.png)
you can clearly see the unencrypted file on the server

**Comment by georgehrke** [comment]
cc @misch7

**Comment by georgehrke** [comment]
Most likely a duplicate of #816

**Comment by claell** [comment]
@StefanAbl can you please confirm?

**Comment by SonRiab** [comment]
That's the exact behavior described in #774.

**Comment by claell** [comment]
I was a bit unsure about

> On the other hand a test file created on the Desktop not in the subfolder was properly encrypted on the server but readable by both clients.

whether this was also a described bug, but probably with "readable" @StefanAbl means that they get decrypted properly by the clients and not that they appear not encrypted in the clients. Since @StefanAbl did not react for a longer time, I will close as duplicate of #774 and ask to reopen if this should not be the case.

**Comment by claell** [comment]
Duplicate of #774

**Comment by SonRiab** [comment]
> I was a bit unsure about
> 
> > On the other hand a test file created on the Desktop not in the subfolder was properly encrypted on the server but readable by both clients.
> 
> whether this was also a described bug, but probably with "readable" @StefanAbl means that they get decrypted properly by the clients and not that they appear not encrypted in the clients. Since @StefanAbl did not react for a longer time, I will close as duplicate of #774 and ask to reopen if this should not be the case.

Files located in the encrypted folder directly are handled correctly - they are encrypted on the server side and decrypted on the client side(s). It's all about files in subfolders of encrypted folders. :)

**Comment by claell** [comment]
That is only what #774 is about. This might indeed be just another issue and I was trying to make sure it was not. Probably it is not another issue and @StefanAbl just meant that everything worked properly outside of subfolders.

**Comment by StefanAbl** [comment]
Sorry for not reacting for such a long time.
Yes it should basically be a duplicate of #774 or #816. I opened the issue in the wrong repo, that was probably why i did not see those issues.

**Comment by claell** [comment]
@StefanAbl no problem. Thanks for your clarification!
