### ISSUE TITLE
Not all selected files are synchronized

### ISSUE THREAD

**Issue by Id3aFly** [nextcloud/desktop#1868]
### Expected behaviour
I have several files and folders uploaded at my server. I selected them in the Windows Nextcloud Desktop client to be synchronized. Therefore I expect those folders to be downloaded to my local Windows 10 in the nextcloud folder.

### Actual behaviour
The Nextcloud client shows that synchronization was successful and that the folder was synchronized.
![1](https://user-images.githubusercontent.com/5712180/76571520-a1831c00-64af-11ea-860e-2d3e59ca8fbc.jpg)

But when I look into the explorer, some folders are not downloaded. For example "Auszug", "CampusCruise" and "DiLabWettbewerb" are missing in my explorer. My explorer shows system and hidden files, that means, they are not downloaded to my filesystem. 
![2](https://user-images.githubusercontent.com/5712180/76571513-9def9500-64af-11ea-9c4d-20e1e6fbd284.jpg)

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303

Operating system: Latest Win10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 18.0.1

Storage backend (external storage): Yes, 4TB single external HDD

### Fix
I was able to fix this:
1. I was deactivating the synchronization for one of the folders e.g. "Auszug".
2. In the subsequent synchronization process the other 2 prior missing folders "CampusCruise" and "DiLabWettbewerb" were suddenly downloaded.
3. Finally I selected "Auszug" to be synchronized again, and it was downloaded as well.

Do you have any idea how this could happen?
Are there logs for the past available as well?

**Comment by claell** [comment]
Regarding the logs I found https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#obtaining-the-client-log-file not sure whether they contain relevant informaiton.

Are you able to reproduce this behaviour?

**Comment by Id3aFly** [comment]
The link you provided didn't work for me.
And no, unfortunately I'm not able to reproduce this behaviour. If the behaviour appears again, I'm going to report it before I'm going to fix it, so I can maybe work with the developers to find more out out about this.

**Comment by claell** [comment]
> The link you provided didn't work for me.

You mean you could not open the logs with F12? Or were the logs empty? Or did the link lead to nowhere?

**Comment by Id3aFly** [comment]
The URL (https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#obtaining-the-client-log-file) at first didn't work.
Now it did and I was able to export the logfiles, but nothing regarding the above mentioned, problematic files was contained (maybe because it was too long ago?)
I could still upload the logfiles, if you want me to.

**Comment by claell** [comment]
Ah, ok.

Do you think the files contain the time when this happened? Unfortunately currently they don't seem to come with a timestamp (#1756).

If you think that the time is contained in the logs they might be helpful.

**Comment by Id3aFly** [comment]
Yeah, that's quite annoying that timestamps are missing.
I investigated if the logs include the time ~24 days ago and that#s sadly not the case.
Shall I close this issue?

**Comment by claell** [comment]
Alright.

I'd suggest to leave this open, since the issue still has happened regardless of the availability of logs.

If you want, you could try to reproduce this for example in a VM where you setup the client again. However that of course requires time and might not even be successful with reproduction.
