### ISSUE TITLE
Sync is broken when using two devices

### ISSUE THREAD

**Issue by Irillit** [nextcloud/desktop#1869]
Steps to reproduce:
1. Create an encripted folder and place a file there on first laptop.
2. Log in on second laptop. All files are viewable.
3. Add new file from a second laptop.
=> you'll see message "File deleted from server" and some problems with the sync.

Reproduced on Windows-Windows and Windows-Linux clients.

Is anything wrong with my usage?

**Comment by georgehrke** [comment]
cc @misch7
