### ISSUE TITLE
Client creating endless huge .part files and never finishing job

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/desktop#187]
I'm using NC 13 and the latest desktop client on Windows 10 Pro. It's probably easiest to see this issue in screenshot but, in a nutshell, the Desktop client is filling up my drive with enormous .part files and never actually assembling any of them into an actual final file. The images below show it best. I'm not really sure how to help debug this, so let me know thanks.

It seems as if the NC client is trying to copy a file that's still in the process of being created instead of waiting until all file locks are released or until there are not more changes to the file before starting the sync process.

Also, the job never finishes. The only way to sync is to manually copy using Windows copy/paste to the NC 13 data drive at which point the Desktop client properly copies it back to my desktop and then allows me to delete all those .part files. Obviously, this isn't the way syncing is supposed to work, but I note it because the Desktop client has no problem copying FROM the data directory but rather the issue is with copying TO the data directory. Thanks.

This first screenshot is the directory of my NC Desktop Client - you can see the 11.8gb that should be synced to the server:

![image](https://user-images.githubusercontent.com/11135869/36304967-a5a18a66-12df-11e8-8712-d9014d81c2b6.png)

This second screenshot is from my NC 13 data drive. As you can see, it's 5 hours later and the 11.8gb file is actually never copied, just a bunch of huge .part files with timestamps hours after the original file was created:

![image](https://user-images.githubusercontent.com/11135869/36305031-e574ec96-12df-11e8-9060-f467bc839ee7.png)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by camilasan** [comment]
if you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
