### ISSUE TITLE
White page when trying to register new account to custom server.

### ISSUE THREAD

**Issue by jviereck** [nextcloud/desktop#1871]
### Expected behaviour

In the NextCloud Connection Wizard, after providing the server address a login window should show up.

### Actual behaviour

The page to login in is a white, blank page.

### Steps to reproduce

1. Install nextcloud client 2.6.4 on macOs 10.14.
2. Open the NextCloud Connection Wizard
3. Enter server address (in my case `https://nextcloud.psioc.net`)
4. Press `Next >`

### Client configuration
Client version: 2.6.4

Operating system: macOs 10.14

OS language: English / USA

Installation path of client: /Applications/

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://gist.github.com/jviereck/e8d0127dac3af5b19c2e3b31fb500bc8

2. Web server error log: Not accessible

3. Server logfile: nextcloud log (data/nextcloud.log): Not accessible

**Comment by rds13** [comment]
I do have the same behaviour.
On server-side I have an http error 499 although a curl command with HTTP/2 configured give a 200 return code.

> XXX.XXX.XXX.XXX - - [15/Mar/2020:17:40:13 +0100] "GET /nextcloud/index.php/core/js/oc.js?v=b828f331 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.4stable (build 20200303) (Nextcloud)"

**Comment by jviereck** [comment]
Was able to resolve the issue. The server admin updated to nextcloud 16. Afterwards, I was able to login.
