### ISSUE TITLE
Malformed mail address causes notification mail loop

### ISSUE THREAD

**Issue by bluikko** [nextcloud/desktop#1873]
### Expected behaviour
If user in LDAP has malformed "mail" attribute, the user should just be skipped and deleted from `activity_mq` table when sending activity notifications.

Or in other words:
1. If activity notification mail sending fails for one user with SMTP permanent error, it should be skipped permanently.
2. If activity notification mail sending to a group has error(s) on some user(s), only users with errors should be retried - not sending the same mail again to all those users, including those who already got the activity notification.

### Actual behaviour
If user has malformed "mail" attribute in LDAP it causes an activity notification loop. Pending activity notification mails are not removed from `activity_mq` table for any user, causing every user keep getting the same activity notification on every processing.

User in LDAP had malformed "mail" attribute: it was missing @ character and domain. Example mail address:
```
john.doe
```
A share was added by another user to a company-wide group in LDAP so everyone in the company got an "activity notification" mail.

The malformed mail address caused even those mails that were already sent out to not be deleted from `activity_mq` table. Notifications were sent out again to all users. This repeats on every activity notification processing until `activity_mq` table is cleaned up manually.

**It seems that the `activity_mq` table entries are not deleted at all if even one entry in a batch of activity notifications fail.**

### Steps to reproduce
1. Add a user "A" with malformed e-mail, for example `john.doe` (missing @domain).
2. Add a share using another user "B" that allows user A with malformed mail address and normal users C, D, E, causing users A, C, D, E to get activity notification.
3. All users A, C, D, E keep getting activity notifications on every notification processing.

### Client configuration
Client version: irrelevant

Operating system: EL7

OS language: EN_US

Qt version used by client package (Linux only, see also Settings dialog): irrelevant

Client package (From Nextcloud or distro) (Linux only): RPM

Installation path of client: irrelevant

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log: irrelevant

3. Server logfile: nextcloud log (data/nextcloud.log):
```
{"reqId":"evVUI0YR8mu44QiDs2eI","level":3,"time":"2020-03-15T21:30:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"idn_to_ascii() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"\/opt\/www\/nextcloud\/lib\/private\/Mail\/Message.php","line":78,"function":"idn_to_ascii","args":[null,0,1]},{"file":"\/opt\/www\/nextcloud\/lib\/private\/Mail\/Message.php","line":143,"function":"convertAddresses","class":"OC\\Mail\\Message","type":"->","args":[{"john.doe":"John Doe"}]},{"file":"\/opt\/www\/nextcloud\/apps\/activity\/lib\/MailQueueHandler.php","line":394,"function":"setTo","class":"OC\\Mail\\Message","type":"->","args":[{"john.doe":"John Doe"}]},{"file":"\/opt\/www\/nextcloud\/apps\/activity\/lib\/MailQueueHandler.php","line":163,"function":"sendEmailToUser","class":"OCA\\Activity\\MailQueueHandler","type":"->","args":["john.doe@domain.corp","john.doe","en","Asia\/Bangkok",1584307801]},{"file":"\/opt\/www\/nextcloud\/apps\/activity\/lib\/BackgroundJob\/EmailNotification.php","line":65,"function":"sendEmails","class":"OCA\\Activity\\MailQueueHandler","type":"->","args":[500,1584307801]},{"file":"\/opt\/www\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\Activity\\BackgroundJob\\EmailNotification","type":"->","args":[null]},{"file":"\/opt\/www\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/opt\/www\/nextcloud\/cron.php","line":124,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/opt\/www\/nextcloud\/lib\/private\/Mail\/Message.php","Line":78,"CustomMessage":"--"},"userAgent":"--","version":"17.0.2.1"}

```

**Comment by claell** [comment]
I think this is related to nextcloud server. This is the wrong repo for your issue. Please open at the nextcloud/server repo.

**Comment by bluikko** [comment]
I was indeed meaning to open it for nextcloud/server and not for nextcloud/desktop. Thanks.
