### ISSUE TITLE
Installing Nextcloud client, wrong screen after a back operation

### ISSUE THREAD

**Issue by crickxson** [nextcloud/desktop#1874]
### Expected behaviour
In the sequence after installing Nextcloud client, the url of an Nextcloud instance is asked. And there is two buttons : 'Find a provider' and 'Forward' (maybe not precisely the wording, i was using the french version). If by mistake the user click on the first, a webpage is show as an embed in the installer windows which is normal, the back button brings him to the previous window and the 'Forward' button should initiate the connection to the url provided.

### Actual behaviour
After the mistake, the 'Forward' button bring back wrongly the webpage about providers.

### Steps to reproduce
Described above

### Client configuration
Client version: 2.6.4

Operating system: Windows 10 family, version 1909

OS language: French

**Comment by erixoltan** [comment]
This also happens in Linux (Kubuntu, KDE desktop).
