### ISSUE TITLE
Local file ignore list, .sync-exclude.lst, periodically ignored

### ISSUE THREAD

**Issue by iaian7** [nextcloud/desktop#1875]
### Expected behaviour

Files that match patterns in .sync-exclude.lst should not be uploaded to the Nextcloud server when created, copied, pasted, duplicated, modified, or otherwise exist.

### Actual behaviour

Files that match patterns in the .sync-exclude.lst file are periodically, seemingly randomly, uploaded to the server. Sometimes while working with the files, sometimes 12 or more hours later. This appears to happen to both "*.extension" and "folder/" file matching patterns, but it's the ignored folders that are of particular concern in my current Nextcloud environment.

### Steps to reproduce

This has been tested for several weeks now across multiple systems using a series of different ignore lists, every scenario has had this issue.

1. Create file ignore list either through the Nextcloud client UI or by editing .sync-exclude.lst directly (note that both "*.extension" and "folder/" formats are used in my tests, none of them appear to work long term).
2. Restart the Nextcloud client.
3. Either immediately or sometime within the next day or two, the Nextcloud client will attempt to sync all of the ignored files, often successfully the first time, then unsuccessfully on subsequent attempts as other users face the same error and thousands of not-ignored files are suddenly in conflict.

I thought perhaps the formatting of the ignore list was at fault, but after trying multiple variations (folder/, *folder/, *folder/*, Folder/, etcetera), none of them worked.

I thought perhaps the ignore list was too complicated, but after simplifying it to the bare bones (only using basic "*.extension" and "folder/" formatting), it still only works temporarily. Eventually the Nextcloud client will stop ignoring the files and try to upload everything that was supposed to be ignored.

I suspected it could be an issue with the first time a folder is synced - perhaps new files were the culprit, and once the client erroneously uploaded everything once, I could delete the incorrect files on the server and it would then continue to sync as expected. This is not the case. Even after working as expected for a short period of time (successfully ignoring the files in .sync-exclude.lst), the Nextcloud client eventually tries syncing them again.

I suspected it could be an issue with the ignored files not already existing on the server (perhaps the client was looking for a matching server file before it ignored the local one?), so I left empty folders on the server that should have been ignored by the desktop client. However, eventually, the client starts to fill the empty folders with content from the desktop client, even though they should have all been ignored.

Note that this is being tested with a Unity project where large numbers of files within the library folder must be ignored. In theory this shouldn't make a difference (they're just files and folders), but since Unity constantly autogenerates large numbers of files, is it possible this has an impact on how the bug manifests?

### Client configuration

Client version: Version 2.6.4stable (build 20200303)

Operating system: MacOS High Sierra 10.13.6 and MacOS Mojave 10.14.6
NOTE: this has been tested on multiple computers, including a Windows 10 machine that seems to display the same issue, but I haven't entirely confirmed. The MacOS clients are confirmed to be buggy.

OS language: English

Installation path of client: /Applications/

### Server configuration

Nextcloud version: 18.0.2

Storage backend (external storage): internal storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[ClientLog1.txt](https://github.com/nextcloud/desktop/files/4344991/ClientLog1.txt)
[ClientLog2.txt](https://github.com/nextcloud/desktop/files/4344993/ClientLog2.txt)
(two partial logs during an error where thousands of ignored files were being uploaded to the server and/or conflicting)

2. Web server error log: Inaccessible to me, hopefully it's not relevant.

3. Server logfile: nextcloud log (data/nextcloud.log): 
[nextcloud.log](https://github.com/nextcloud/desktop/files/4344995/nextcloud.log)

**Comment by powerpaul17** [comment]
I have the same problem, but I'm not sure if it started when I created a local .sync-exclude.lst file in a certain folder. Do you happen to have one too?

**Comment by iaian7** [comment]
Yes, this was tested with a local .sync-exclude.lst file. It was originally set up through the GUI, but later edited using Sublime Text, and saved to a sub-folder so that other users of the shared folder could use the same ignore file list. This is critical for things like Unity projects, which is why this bug can be so serious - Nextcloud quickly corrupts everything as it tries to sync everyone's temp and cache files, even though they're supposedly excluded!

**Comment by powerpaul17** [comment]
In my case it's starting to sync a node_modules folder with 60k files which is excluded both in the settings and in a local .sync-exclude.lst file. But it seems to starting to ignore both after some time, but only in the folder with the local file.

**Comment by powerpaul17** [comment]
I'll try and remove the local file again and see if it works as before.

**Comment by powerpaul17** [comment]
Just for information, I removed the local `sync-exclude.lst` file and the problem did not happen again. At least for a few days now..

**Comment by ajay10000** [comment]
With Nextcloud set to start with Windows, every time I restart the computer, Nextcloud ignores the exclude list.  I have to close Nextcloud, re-open and it is fine.  Simple list:
temp
.tmp
outlook2013.pst

Nextcloud Version 2.6.4stable-Win64 (build 20200303)
Feature update to Windows 10, version 1909

**Comment by qualiaa** [comment]
I believe this issue is a duplicate of https://github.com/nextcloud/desktop/issues/1534

**Comment by er-vin** [comment]
Yes, I understand it as duplicate of #1534 indeed.

**Comment by powerpaul17** [comment]
No, this issue is about a "local" `sync-exclude.lst` file, i.e. a file in a folder which should override the global ignore settings.

**Comment by er-vin** [comment]
Ah gotcha. My bad.

**Comment by kcpr** [comment]
I think this bug, or the similar one, also appears in Ubuntu client. I added some entries to the list (`backup/` and `home/` to be specific) and it worked correctly at the first time, but when the folder was to be synced again the client started uploading files it was not supposed to.

**Comment by RainerW** [comment]
I have a fresh 3.1.1 windows install.
 - only the global ignore list is honored 
 - edit on via the UI for one syncronisation is not honored ( but written to .sync-exclude.lst )
 - editing the .sync-exclude.lst file directly is "picked up" but still not honored on sync.

I found feature #1374 ... so, a copy of the same file into an subfolder did work. wtf!

/timeline is my synced folder:
  /timeline/.sync-exclude.lst  -> will be completely ignored
  /timeline/2019/.sync-exclude.lst  -> will be honored

I added "*.exe" as ignore pattern an just pasted a exe i had lying around.
 /timeline/Testfiles.exe  -> file will be uploaded
 /timeline/2019/folder/Testfiles.exe -> file is correctly not uploaded

**Comment by er-vin** [comment]
@camilasan I guess this latest comment sheds some more light on the couple of exclude list issues we got reported lately.

**Comment by jobec** [comment]
I bumped into the same issue.
Global works, local is totally ignored.

And I'm stuck now... A logs folder with the same name should be synced in connection A but not in connection B. So now I can choose between ignoring them both, or uploading them both.

**Comment by hashashin1191** [comment]
Confirmed with 3.1.2 from official zypper repo on openSUSE 15.2 and 3.1.2 AppImage and 3.1.2 on Windows 8.1.
Using 3.1.3 AppImage solves the issue.

**Comment by dasaweb** [comment]
Is this related to [that issue](https://github.com/nextcloud/desktop/issues/2728)?  [Client 3.2.0-rc2 is out now](https://github.com/nextcloud/desktop/releases/tag/v3.2.0-rc2), and I'm still stuck with 3.0.3 because of this problem.

**Comment by jsaraiva** [comment]
This has happened ever since the feature's introduction (in v2.6, I believe). I gave up on this feature months ago, and used only the global ignore list, which works. However, it is not difficult to imagine cases in which the global ignore list is not a viable option.

**Comment by rbi** [comment]
I just stumbled across this yesterday. It prevents me from just syncing my /home folder instead of artificially putting stuff into a special Nextcloud folder just for the sake of syncing. I want to do `echo '.*' > ~/.sync-exclude.lst`, sync my /home with my Nextcloud home and then never spend another thought about whether files are being synced between all my computers or not. It's a pity that doesn't work. :-(
