### ISSUE TITLE
Nextcloud Talk shortcut broken (nextcloud-2.7.0.15230-daily-20200318) : quick fix ?

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/desktop#1877]
Just tried a new daily build, 1st time in ages

nextcloud-2.7.0.15230-daily-20200318-Release

The Talk shortcut seems to be going to wrong url

/apps/spreed/

when it 'should be'

/index.php/apps/spreed/

hopefully a quick fix

Also it would be nice to have a mouse-over to say what each of the 3 icons does:

- Folder > Local Files
- Talk > Talk
- 4 app icon > Other Apps

**Comment by claell** [comment]
> Also it would be nice to have a mouse-over to say what each of the 3 icons does:

Please create a new issue for that to keep things separated.
