### ISSUE TITLE
Nextcloud client does not show login prompt (macOS, 2.6.3, 2.6.4stable (build 20200303), and 2.7.0beta)

### ISSUE THREAD

**Issue by jokuha** [nextcloud/desktop#1888]
### Expected behaviour
When the login credentials of the server has changed the client needs to ask the user for login credentials in a corresponding dialog. The dialog shows "user" and "password" fields.

### Actual behaviour
The dialog opens, but no input fields are available. Instead, a narrow blue line shows at the top, see attached screenshot.
(The "blue" might be due to our facilities customized theme of the nextcloud login screen, which is moistly light blue)

### Steps to reproduce
1. log out of server in client
2. try to log in 

### Client configuration
Client version:
* not working (described buggy behavior): 2.6.3, 2.6.4, 2.7.0-beta1
* working: 2.6.1, 2.6.2

Operating system: macOS

OS language: English

Installation path of client: /Applications/nextcloud.app/Contents/MacOS/

### Logs

1. Client logfile: see attachment
[nextcloud.log](https://github.com/nextcloud/desktop/files/4364970/nextcloud.log)

### Screenshot
![b5330d4d58f2166503054b83c6d13ba7e06e2c30](https://user-images.githubusercontent.com/13561679/77246558-f994ed80-6c28-11ea-8b32-a6b8c95971ad.jpeg)

**Comment by Yann-Hou** [comment]
Hi,

It's same for me.

Version 2.6.4stable 
MacOS 10.15.3

See you soon !

**Comment by jsjohann** [comment]
Same for me as well.

Version 2.6.4stable
MacOS 10.15.3

**Comment by aturetta** [comment]
Same for me. Installing on a new MacPro (Catalina), the latest version did not allow me to login, had to reinstall using 3.6.1

**Comment by jokuha** [comment]
> Once the login is saved, I was able to upgrade to 2.6.4 and everything keeps working

That's indeed true – guess this indicates that some change to the login dialog seems to be the issue.

**Comment by claell** [comment]
So apart from not showing the dialog when logging out, it also doesn't show the dialog after first installation or whenever opening the client without being logged in? So it is basically preventing the user to login?

**Comment by jokuha** [comment]
> So it is basically preventing the user to login?

correct

**Comment by mokkun** [comment]
Are there any updates on this? Currently stuck with version 2.3.3.

**Comment by jokuha** [comment]
This (my) report seems to be a duplicate of #1793 (which is only for 2.6.3., but seems to report the same issue).

**Comment by claell** [comment]
@jokuha thanks for pointing that out! I will mark this as a duplicate then. Could you move relevant information from this issue like the screenshot to #1793? Afterwards this can be closed.

**Comment by claell** [comment]
Duplicate of #1793

**Comment by jokuha** [comment]
Moved most relevant info to #1793 and linked from there to here.
