### ISSUE TITLE
Slow upload due to high cpu usage? on single large file

### ISSUE THREAD

**Issue by f-s** [nextcloud/desktop#1894]
### Expected behaviour
Upload speed is similar to 2 large files: >>900Mbit/s (~960) no problem

### Actual behaviour
Upload speed of large files (eg. 4-20Gbyte) range looks CPU limited, 2 loaded cores during upload and is slow <700Mbit (constant)

### Steps to reproduce
1. Put a single, large file in upload folder
2. Wait for upload to commence
3. Slow upload <700Mbit/s in my case

### Client configuration
Client version:
Version 2.6.4stable-Win64 (build 20200303).

Operating system:
Win64
OS language:
German

The server has a very low load during upload. Maybe its a client problem.

Thanks for any help to reduce Upload CPU burden.

**Comment by f-s** [comment]
I checked upload function with 

curl 7.68.0 (x86_64-generic-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1e zlib/1.2.11.1-motley nghttp2/1.39.2

and I can easily get the ~960Mbit/s for a single file on that same server.

=> a SSL implementation issue with the desktop client?

**Comment by claell** [comment]
Could you maybe add some more details to your description above? I don't entirely understand some sentences.

Also, when uploading smaller files of the same size in total like the large file, do they upload faster and with less CPU load?

**Comment by f-s** [comment]
> Also, when uploading smaller files of the same size in total like the large file, do they upload faster and with less CPU load?

Correct, they upload faster with even higher CPU load and saturate the link. (see first post)

I tested the curl upload from shell - see  above for curl version - and that uploads single large files fine too. BTW: This is all done on a LAN. (see second post)

I still suspect a SSL implementation issue (old version, missing HW accel. etc. ?). I force this cipher on the server side: ECDHE-RSA-AES128-GCM-SHA256

**Comment by f-s** [comment]
@claell 
btw, upload without transport encryption (i.e. http) is fine (>>900Mbit) on a single, large file with this nc client.

**Comment by claell** [comment]
Thanks for adding the additional information! I did not understand the description entirely when I read it.

I guess the test with http suggests that you might be right with your suspicion about what causes the issue.

Unfortunately the desktop client seems to be lacking manpower to fix all the outstanding issue in the near future. Do you by any chance have the skills and would be willing to contribute a fix for this?

**Comment by f-s** [comment]
@claell 
Of course I am willing, but I do not have access to a test infrastructure to further investigate the issue. Does nextcloud sponsor dev. infrastructure, that would be perfect.

**Comment by claell** [comment]
@f-s alright, nice to hear.

I am not sure how nextcloud handles this. There is at least a [demo instance](https://try.nextcloud.com/) of Nextcloud Server that you could use. Also there are some hosters where you get a Nextcloud instance with limited space for free. A not complete list is [here](https://nextcloud.com/signup/). Google will probably give some more results. I guess this is what you meant with dev. infrastructure, correct? Let me know, if you need more details. You can also [contact](https://nextcloud.com/contact/) nextcloud directly.

**Comment by f-s** [comment]
@claell 
Sorry, I contacted "Vanessa Steeg" at nexcloud.com and she declined that they sponsor infrastructure to dig further into this issue. So the issue will remain.

**Comment by f-s** [comment]
Oh, btw. this is not a bug: I call it a rate limiting feature 🥇

**Comment by claell** [comment]
@f-s I don't really understand. Is something wrong with the options I linked above (demo instance or free nextcloud accounts)? You did not mention them.

Also, please don't close not fixed issues. I reopened, since this is not fixed. I can understand your frustration, although I don't know the conversation with nextcloud and what you requested there.

So, I hope you can address the options I mentioned. Let me know why they don't work for you to fix this issue. Then I can see whether there are other options, maybe some nextcloud hoster is willing to create a test instance for this issue. But please first try the other options.

**Comment by f-s** [comment]
Starting with server 19.0.1 and client 2.6.5 the server has also issues https://github.com/nextcloud/server/issues/21428 
In this combination the speed dropped to <600Mbit.
