### ISSUE TITLE
Cannot get public share link after initial file sync [macOS client]

### ISSUE THREAD

**Issue by jaronaz** [nextcloud/desktop#1897]
### Expected behaviour
After adding file to Nextcloud folder on MacOS, and after it has synced with nextcloud server, the synced file gets a green check.
Then you can right-click the file and choose "Share via Nextcloud" > copy public link (among other options)

### Actual behaviour
After adding file to Nextcloud folder on MacOS, and after it has synced with nextcloud server, the synced file gets a green check.
Then you can right-click the file and choose "Share via Nextcloud" > copy internal link (only other option is "open in browser", and greyed out "further sharing not allowed") There is no "copy public link" option.

If I restart the nextcloud desktop app (or force sync) then I do get the option to "copy public link"
I rather not do that everytime I want to share a file.

So it appears that two syncs are needed, 1 to upload the file and 1 to be able to retrieve a public share link.

Besides this issue I really like everything about this application, thank you for making it!

### Steps to reproduce
1. sync file with server using nextcloud desktop app
2. right-click the file and choose "Share via Nextcloud" > 
3. see that you don't get the option "copy public link"
4. restart the nextcloud app, or force sync
5. now see that you DO have the option to "copy public link"

### Client configuration
Client version: 2.6.4 stable

Operating system: macOS Mojave 

OS language: dutch

Qt version used by client package (Linux only, see also Settings dialog): 5.12.5

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:  /Applications/nextcloud.app/

### Server configuration
Nextcloud version: 18.0.3
Storage backend (external storage): filesystem

### Logs
Nothing strange in logs. I see the same, only after the second sync the option for public link appears.

**Comment by briankendall** [comment]
I just came here to report this bug. Given that I need public links for newly copied files in my synced directory all the time, It's very annoying and by far the worst aspect of using Nextcloud. I hope it gets fixed soon!

**Comment by cskollar** [comment]
Same problem here, very annoying. But as I see it depends on the time. If you wait 30-50 sec the share option will appear.

**Comment by sharcslife** [comment]
I just wanted to chime in and report that this issue (wheter it is considered one or not) still extists with 20.0.8 and 3.1.3 (Windows).

**Comment by jaronaz** [comment]
Has this been fixed?

**Comment by sharcslife** [comment]
> Has this been fixed?

In my case, running 20.0.9 and 3.2.0 for Windows, it seems to have been fixed.
Didn't spot it in the release notes though.

**Comment by briankendall** [comment]
It does appear to be fixed in 3.2.0 for macOS.
