### ISSUE TITLE
Desktop Client deletes non-synced folders on server

### ISSUE THREAD

**Issue by OliverW87** [nextcloud/desktop#1898]
I have synced only Folder Job1 under Sub1 to my Mac. My directory tree for this example is:
```
- Base
   - Sub1
      - Job1
      - Job2
      - more than 100 Jobs...
   - Sub2
```
### Expected behaviour
When i was delete folder Sub1 due to incorrect operation locally on my Mac.
I would expect he will only delete subfolders i have synced on my client.

### Actual behaviour
When i was delete folder Sub1 due to incorrect operation locally on my Mac.
The client has synced this action and has delete **ALL** folders on server-side under Sub2 and himself. 

### Steps to reproduce
1. Create this directory tree
2. Sync with your Client (in my case macOS) only the Folder Job1
3. Now Delete Sub1 or for more data lost Base on your Client locally

### Client configuration
Client version: 2.6.4stable

Operating system: macOS may also happens with Windows

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019

Installation path of client: /Applications/nextcloud.app/

Nextcloud version: 18.0.3

Storage backend (external storage): Tested local Datadir for NC and also on SMB Share

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
`[csync_update 	Update detection for remote replica took 0.894 seconds walking 13 files
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Discovery end ####################################################  896 ms
[OCC::ActivityListModel::removeActivityFromActivityList 	Activity/Notification/Error successfully dismissed:  "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet (übersprungen aufgrund des früheren Fehlers, erneuter Versuch in 15 Sekunden)"
[OCC::ActivityListModel::removeActivityFromActivityList 	Trying to remove Activity/Notification/Error from view...
[OCC::ActivityListModel::removeActivityFromActivityList 	Activity/Notification/Error successfully removed from the list.
[OCC::ActivityListModel::removeActivityFromActivityList 	Updating Activity/Notification/Error view.
[csync_reconcile 	Reconciliation for local replica took  0 seconds visiting  12  files.
[_csync_merge_algorithm_visitor 	INSTRUCTION_UPDATE_METADATA    server dir:  Test/Mainfolder
[_csync_merge_algorithm_visitor 	INSTRUCTION_UPDATE_METADATA    server dir:  Test
[_csync_merge_algorithm_visitor 	INSTRUCTION_REMOVE             server dir:  Test/Mainfolder/Sub1
[csync_reconcile 	Reconciliation for remote replica took  0 seconds visiting  13  files.
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Reconcile end ####################################################  897 ms
[OCC::SyncEngine::checkErrorBlacklisting 	"Test/Mainfolder/Sub1"  is blacklisted, but has changed mtime!
[OCC::SyncEngine::slotDiscoveryJobFinished 	Permissions of the root folder:  "DNVCKR"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:OK:/Users/macos_user/Nextcloud/Test" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:OK:/Users/macos_user/Nextcloud/Test/Mainfolder" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:/Users/macos_user/Nextcloud/Test" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:/Users/macos_user/Nextcloud/Test/Mainfolder" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:/Users/macos_user/Nextcloud/Test/Mainfolder/Sub1" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:/Users/macos_user/Nextcloud/Test/Mainfolder" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:/Users/macos_user/Nextcloud/Test" to SocketApiSocket(0x7fd653e42720)
[OCC::SyncEngine::slotDiscoveryJobFinished 	#### Post-Reconcile end ####################################################  903 ms
[OCC::Folder::slotSyncStarted 	#### Propagation start ####################################################
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/" :  "Sync Running"
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_REMOVE propagation of "Test/Mainfolder/Sub1" by OCC::PropagateRemoteDelete(0x7fd65717e2b0)
[OCC::PropagateRemoteDelete::createDeleteJob 	Deleting file, local "Test/Mainfolder/Sub1" remote "Test/Mainfolder/Sub1"
[OCC::AccessManager::createRequest 	5 "" "https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1" has X-Request-ID "9aade143-3b3c-4316-8ab8-1209b119aa60"
[OCC::AbstractNetworkJob::start 	OCC::DeleteJob created for "https://secret" + "/Test/Mainfolder/Sub1" "OCC::PropagateRemoteDelete"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::ContentAccessDenied "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet" QVariant(int, 403)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::ContentAccessDenied
[OCC::WebFlowCredentials::stillValid 	"Error transferring https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1 - server replied: Forbidden"
[OCC::DeleteJob::finished 	DELETE of QUrl("https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1") FINISHED WITH STATUS "ContentAccessDenied Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet"
[OCC::createBlacklistEntry 	Probably firewall error:  403 , blacklisting up to 1h only
[OCC::SyncJournalDb::setErrorBlacklistEntry 	Setting blacklist entry for  "Test/Mainfolder/Sub1" 2 "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet" 1585227200 125 1585227182 "5e7ca5b88ca3f" "" 0
[OCC::blacklistUpdate 	blacklisting  "Test/Mainfolder/Sub1"  for  125 , retry count  2
[OCC::PropagateItemJob::done 	Could not complete propagation of "Test/Mainfolder/Sub1" by OCC::PropagateRemoteDelete(0x7fd65717e2b0) with status 10 and error: "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet"
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:/Users/macos_user/Nextcloud/Test" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:SYNC:/Users/macos_user/Nextcloud/Test/Mainfolder" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:ERROR:/Users/macos_user/Nextcloud/Test/Mainfolder/Sub1" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:/Users/macos_user/Nextcloud/Test/Mainfolder" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "STATUS:IGNORE:/Users/macos_user/Nextcloud/Test" to SocketApiSocket(0x7fd653e42720)
[OCC::ActivityWidget::slotItemCompleted 	Item  "Test/Mainfolder/Sub1"  retrieved resulted in  "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Test/Mainfolder/Sub1"  retrieved resulted in error  "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Server hat \"403 Forbidden\" auf \"DELETE https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/Mainfolder/Sub1\" geantwortet"
[OCC::SyncJournalDb::close 	Closing DB "/Users/macos_user/Nextcloud/._sync_86855ca17610.db"
[OCC::SyncEngine::finalize 	CSync run took  1165 ms
[OCC::Folder::slotSyncFinished 	Client version 2.6.4stable (build 20200303)  Qt 5.12.5  SSL  OpenSSL 1.1.1d  10 Sep 2019
[OCC::Folder::slotSyncFinished 	SyncEngine finished without problem.
[OCC::Folder::showSyncResultPopup 	Folder sync result:  3
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:/Users/macos_user/Nextcloud" to SocketApiSocket(0x7fd653e42720)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "UPDATE_VIEW:/Users/macos_user/Nextcloud" to SocketApiSocket(0x7fd65610f2b0)
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/" :  "Success, some files were ignored."
[OCC::FolderMan::slotFolderSyncFinished 	<========== Sync finished for folder [Nextcloud] of account [user_name@secret] with remote [https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/]
[OCC::AccessManager::createRequest 	6 "GET" "https://secret/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "0e88e5e7-d786-4b26-a9eb-a44b76aa15c6"
[OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://secret" + "ocs/v2.php/core/navigation/apps" ""
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/" has X-Request-ID "e561c2a6-b361-4428-be19-0b7c12f39892"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://secret" + "/" "OCC::FolderStatusModel"
[OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.24.0"
[OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::LsColJob::finished 	LSCOL of QUrl("https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/" has X-Request-ID "03f18273-0787-4180-8710-23af15931d6c"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://secret" + "/Test/" "OCC::FolderStatusModel"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::LsColJob::finished 	LSCOL of QUrl("https://secret/remote.php/dav/files/5A107460-5997-42EF-9DAB-334A52FFD447_3512/Test/") FINISHED WITH STATUS "OK"`

2. Web server error log: no logs due this time

3. Server logfile: nextcloud log (data/nextcloud.log): no logs due this time

**Comment by Escubaer** [comment]
I think this is a wrong expectation. When you delete "sub2", that command is send to the server and it does exactly that: "delete sub2". With all subfolders, itself and all files in there ... at least with all where you have delete rights to. If done by mistake you can revise the action via server trashbin.

**Comment by OliverW87** [comment]
really?
Please look at it from the user's perspective.
they will see the directory tree on his client locally.
```
Base
   -sub2
      - job1
```
on the server looks (not locally)
```
Base
   - sub1
   - sub2
      - job1
      - job2
      - job3
```
so your user means "i can will delete job1" and "oh now i have the empty folder sub2 this can also deleted"

**Comment by claell** [comment]
Sounds reasonable to me. I will mark this as feature request, maybe some might even consider it a bug, as no warning or notification is displayed to the user imposing the risk of losing files.

**Comment by Escubaer** [comment]
IMHO the proper way for that is a virtual file system, so the user will see everything - but it doesn't take space at his local disc.
Keep in mind that the user must have actively removed the subfolder in the selective sync dialog ... 

Of course you can wait till somebody programs something, I doubt its worth the time ... but I am sure PRs are welcome ... but it is complex here ... VFS is way easier.

**Comment by ilippert** [comment]
> Sounds reasonable to me. I will mark this as feature request, maybe some might even consider it a bug, as no warning or notification is displayed to the user imposing the risk of losing files.
 a user warning would be great.
