### ISSUE TITLE
Talks in the Desktop App?

### ISSUE THREAD

**Issue by EpeR1** [nextcloud/desktop#1900]
Dear Developers,

Is there anybody, who is working on integrating Nextcloud Talk to Nextcloud Desktop App?
It would be a nice and useful open source alternative to Microsoft Teams.
What do you think?

**Comment by splitt3r** [comment]
There are some discussions about it at https://github.com/nextcloud/spreed/issues/1100.

**Comment by nathanael-h** [comment]
Just found this repo today, but didn't try: https://github.com/indev29/nextcloud-talk-desktop 
There's also: https://github.com/fds2610/NCT-Desktop

**Comment by claucambra** [comment]
Hi folks, we will continue improving our existing Talk integration in the desktop client but will not be featuring a full Talk application within this desktop client
