### ISSUE TITLE
Window nextcloud-client does not open correctly.

### ISSUE THREAD

**Issue by noname-3** [nextcloud/desktop#1905]
### Expected behaviour.
The window should open correctly, just above the nextcloud-client tray icon.

### Actual behaviour.
The window does not open correctly, the window opens higher than necessary.

### Steps to reproduce.
1. Open nextcloud-client.
2. Right click nextcloud-client icon in tray.

### Client configuration
Client version:

2.6.4

Operating system:
Arch Linux ( KDE ).

OS language:
ru_ru

Client package (From Nextcloud or distro) (Linux only):
distro Arch linux

Installation path of client:
From the official repository distro Arch linux.
sudo pacman -S nextcloud-client

![nextcloud-client](https://user-images.githubusercontent.com/62765820/78068675-79e1ee00-73a1-11ea-9a5e-7ec871925573.png)

**Comment by claell** [comment]
Did you do some tests to isolate the problem? Is this also happening on a different OS or desktop environment? Is this happening with other languages? The more information you can provide the better.

**Comment by noname-3** [comment]
> Did you do some tests to isolate the problem?

> 
If you mean to test whether the window behaves this way several times, then yes, no matter how many times I test, the window is higher than necessary.

>  Is this also happening on a different OS or desktop environment?

> 

In Manjaro Linux xfce, window open correctly.

![nextcloud](https://user-images.githubusercontent.com/62765820/78478158-938e8700-774d-11ea-8131-ee733a95b720.png)

In Windows 8.1, window open correctly.

![test](https://user-images.githubusercontent.com/62765820/78480576-3cd57d00-774e-11ea-84e4-c4f2cb586567.png)

It may be the case in kde, but in kde there are applications that, by right-clicking on the tray icon, the window opens correctly.

**Comment by claell** [comment]
> If you mean to test whether the window behaves this way several times

No, that would be reproducibility. However it is also good to know that, so thanks for mentioning.

With isolation I meant to try to isolate the source of this with checking whether this also happens on other desktop environments or OSs for example. So thanks for adding that information, seems this is KDE specific (with that I mean not an issue of KDE, but that the client does not work correctly with KDE).

Also it might be interesting to check it on KDE with a different language to see, whether the language being set to russian causes this issue.

**Comment by noname-3** [comment]
Manjaro Kde, language : en_us
![en_us](https://user-images.githubusercontent.com/62765820/79069998-3fe6e500-7cdb-11ea-9413-b2cc0023505e.png)

Manjaro Kde, language : uk_ua
![uk_ua](https://user-images.githubusercontent.com/62765820/79070009-52f9b500-7cdb-11ea-9c25-f3491a239de0.png)
