### ISSUE TITLE
Error message integration in client ui (main window) need to be improved

### ISSUE THREAD

**Issue by anolting** [nextcloud/desktop#191]
Error message displayed by the client seems to hover over the main windows and overlaying the  displaying (indicated by the tool tip showing the actual uploading file) of folders which are configured to be synced.

You are not able to close the message.
Additionally it would a good idea to store them separately to be able to fix the issues later.

![nextcloud client error message overlays syncing folder view which still has the focus](https://user-images.githubusercontent.com/12763750/36378474-3918a5fc-157b-11e8-9701-65dacfc00920.png)

**Comment by camilasan** [comment]
@jancborchardt @nimishavijay how do you think we could improve?

**Comment by Rello** [comment]
This can be closed. Error messages are shown over multiple lines now
