### ISSUE TITLE
Package for Ubuntu 20.04

### ISSUE THREAD

**Issue by darkdragon-001** [nextcloud/desktop#1911]
Please package nextcloud for Ubuntu 20.04 and publish via http://ppa.launchpad.net/nextcloud-devs/client/ubuntu.

**Comment by ivaradi** [comment]
The beta repository (http://ppa.launchpad.net/nextcloud-devs/client-beta/ubuntu/) contains packages for Focal, although the ones built from the master branch. 

The next stable release in the main repo will have a Focal package.

**Comment by mmartinortiz** [comment]
Is there an estimated time for the next stable release?

**Comment by iGadget** [comment]
Until the next stable release, what is the workaround for now? Install 18.04 package? 19.10 package? Beta 20.04 package? Something else?

**Comment by Novaal** [comment]
A workaround could be to install [v2.6.2](https://packages.ubuntu.com/focal/nextcloud-desktop) from universe:
```bash
sudo add-apt-repository universe
sudo apt-get install nextcloud-desktop
```

**Comment by iGadget** [comment]
> A workaround could be to install [v2.6.2](https://packages.ubuntu.com/focal/nextcloud-desktop) from universe:
> 
> ```shell
> sudo add-apt-repository universe
> sudo apt-get install nextcloud-desktop
> ```

I get unmet dependencies when I try that:
```
The following packages have unmet dependencies:
 nextcloud-desktop : Depends: libnextcloudsync0 (= 2.6.2-1build1) but 2.6.4-20200303.193231~focal1 is to be installed
```

**Comment by Thorsten42** [comment]
the ppa was updated yesterday and now contains focal! However, auto start was broken for me since there was a strange path included inside ~/.config/autostart/Nextcloud.desktop. After changing it to Exec=/usr/bin/nextcloud it was working fine

**Comment by JohnWalkerx** [comment]
After uninstalling all old packages, everything is working for me with the normal PPA.
Thanks a lot!

**Comment by iGadget** [comment]
After an 'apt update' I could install nextcloud-client today. Awesome, thanks team!

**Comment by darkdragon-001** [comment]
Thanks!
