### ISSUE TITLE
Update dialog shows wrong installed version and wants to update to already installed version

### ISSUE THREAD

**Issue by inok16** [nextcloud/desktop#1912]
### Expected behaviour
The Nextcloud Client dialog does not pop-up during start, if the latest Nextcloud Client is already installed.

### Actual behaviour
The Nextcloud Client dialog pops up everytime the Nextcloud Client starts and asks me to update to version 2.6.4. The Nextcloud Client dialog detects the version 2.6.0.20190927 as the currently installed version, although the latest Nextcloud Client version 2.6.4 is installed.

### Steps to reproduce
1. Just start the Nextcloud Client (in my environment)

### Client configuration
Nextcloud 2.6.4.15215 as per Windows Apps & Features Window

Operating system:
Windows 10 Pro (1909)

OS language:
German

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version:
17.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Its quite private (files & folders) and I have no guess which part of the log file you could be interested in? Maybe someone could tell me. Then I dont have to strip all the private stuff out of the log window.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by claell** [comment]
@inok16 thanks for opening this.

Regarding the log: Since the dialog pops up during start of the client, the logs from starting the client until the dialog appears might be relevant.

**Comment by inok16** [comment]
Maybe another hint: I just wanted to change the way nextcloud is being auto-started (by adding the -logwindow command line switch). The properties window looks like this:
![Autostart_Properties](https://user-images.githubusercontent.com/39257043/78859473-b364ca00-7a2f-11ea-8aaa-945a1eb94f0f.JPG)

**Comment by inok16** [comment]
Here it is:
[small_log.txt](https://github.com/nextcloud/desktop/files/4454163/small_log.txt)

If you need more logs, just let me know.

**Comment by inok16** [comment]
Hmm. I restarted the client several times and it seems that - sometimes - the correct version seems to be detected. Look at this:

One of the early tries 
(with --logwindow, but not the first start since boot):
![General_Option_Menu_Faulty](https://user-images.githubusercontent.com/39257043/78860669-0c822d00-7a33-11ea-9bb5-464bbc3f0f7b.JPG)

Another try (without the --logwindow switch):
![General_Option_Menu_Correct](https://user-images.githubusercontent.com/39257043/78860734-350a2700-7a33-11ea-949f-f1c5c5c1ab4d.JPG)

Same installation, no reboot. I just restarted the client.

**Comment by claell** [comment]
@inok16 thanks for adding that info. From the logs I also saw that a possibly wrong version is displayed:
`[OCC::Folder::slotSyncFinished 	Client version 2.6.0stable-Win64 (build 20190927)  Qt 5.12.5  SSL  OpenSSL 1.1.1d  10 Sep 2019`

Regarding the language I saw that also the screenshot of the properties window you provided above showed English as language. Did you notice a correlation of the wrong version and English language?

Also is there a correlation between the start option and the English language?

The behaviour looks like there are two different versions of Nextcloud installed on your PC and sometimes version 2.6.4 gets launched and sometimes version 2.6.0 gets launched. Could you check whether there are differences between those "versions" that would sugegst that? Maybe there have been some things modified in the GUI (changelog might give a hint) in between those versions, so you would notice a difference.

Regarding logs, you can also display them with F12: https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by inok16** [comment]
> Did you notice a correlation of the wrong version and English language?

No, not yet. I would have to perform some more tests.

> Also is there a correlation between the start option and the English language?

With start option I assume you mean the command line switch --logwindow? What do you mean with start option?

> The behaviour looks like there are two different versions of Nextcloud installed on your PC

Is that even possible? I have no clue how to verify that.

**Comment by inok16** [comment]
> The behaviour looks like there are two different versions of Nextcloud installed on your PC
You are absolutely right. There are two different Nextcloud installations:
First: C:\Program Files (x86)\Nextcloud (this is what windows auto-starts)
![x86](https://user-images.githubusercontent.com/39257043/78890088-479d5400-7a65-11ea-92e5-206af978c35c.JPG)
Second: C:\Program Files\Nextcloud (this is what I start manually)
![x64](https://user-images.githubusercontent.com/39257043/78890121-5552d980-7a65-11ea-9281-54c9734c27a2.JPG)

**Comment by claell** [comment]
> With start option I assume you mean the command line switch --logwindow?

Correct.

**Comment by claell** [comment]
Seems like we got more closely to the root of the problem. I find it interestingly that one version is installed in Program Files (x86) although it claims to be for Windows 64 bit (but that does not necessarily mean it also is a 64 bit program).

Since you only found one installation when searchin in Apps and Features and it might also shed some light onto the issue:
What is the history of your system - meaning:
What was the first Nextcloud desktop version that you installed? Did you perform updates of that version until you reached 2.6.4? If yes, then how? I think the auto updater does not work currently, so you probably downloaded them manually and installed them? All that might be important details.

**Comment by inok16** [comment]
Sorry, I cant remember which version I installed first. I bought my Synology NAS in 08.2018. Some weeks later I setted up the Nextcloud server. Maybe a client version that was recent at the end of 2018? As far as I can remember, I updated manually. But I cant remember how many times. Usually I update soon after a new software has been released. Probably I updated consequently from one release to another until I reached 2.6.4.

**Comment by claell** [comment]
Alright. Just wanted to make sure that this happened during an update. There would have been the possibility that you installed nextcloud 2.6.0 once then decided to no longer use it and came back installing 2.6.4 after a while. But that does not seem to be the case.

So probably the installation changed its location by itself to from Program Files (x86) to Program Files during the update to 2.6.1 maybe? I assume that you did not modify the paths during updates.

**Comment by inok16** [comment]
> There would have been the possibility that you installed nextcloud 2.6.0 once then decided to no longer use it and came back installing 2.6.4 after a while.

No, never.

> So probably the installation changed its location by itself to from Program Files (x86) to Program Files during the update to 2.6.1 maybe?

No, I dont change that. I dont know the exact criteria how installers determine to correct installation folder. So I let the installier choose the correct one. Thats it.

**Comment by claell** [comment]
Alright. I did some search:

https://github.com/nextcloud/desktop/blob/1a73d3323adbe166550aa4e2f77f0970774da68d/NextcloudCPack.cmake#L51
But this is probably outdated.

There seem to be issues with both Program Files and Program Files (x86): https://github.com/nextcloud/desktop/search?p=3&q=%22Program+Files%22&type=Issues

Also I found this, suggesting that support for 32 bit has been added:
https://github.com/nextcloud/desktop/issues/840#issuecomment-519095559

**Comment by claell** [comment]
Building seems to be managed in https://github.com/nextcloud/client-building.

A short search revealed: https://github.com/nextcloud/client-building/search?q=%22Program+Files%22&unscoped_q=%22Program+Files%22

**Comment by claell** [comment]
@misch7 since you introduced builds for 32bit, can you think of a reason for this issue? Maybe the Program Files folder detection did not work properly in earlier versions, then got fixed an left an old version behind?

**Comment by inok16** [comment]
At the end of this week, I will somehow remove the 32 bit version of nextcloud. A backtrace will then probably no longer be possible.

**Comment by claell** [comment]
Alright. I fear that no developer will respond until then, unfortunately. But this issue contains pretty much information including logs, so I guess this won't be a problem.
