### ISSUE TITLE
Feature request: Dark mode for windows client

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/desktop#1914]
Hi all,
I´m really enjoying NC itself and also the client. Keep up the great work. You guys are awesome. As the title says, I´d like a dark mode for the windows sync client. Maybe you could make this feature dependent on the Windows Settings of the app mode (dark/light).

**Comment by claell** [comment]
@CountOmega There has already been an issue for macOS that I now edited to cover nextcloud in general: #1287
There is a PR that will implement the requested functionality: #1439. So I guess we can close this as duplicate. Feel free to reopen if you think otherwise.

**Comment by claell** [comment]
Duplicate of #1287
