### ISSUE TITLE
l10n: Need context regarding string "Stat failed"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#1916]
See here:

https://github.com/nextcloud/desktop/blob/49e1338087420ddf645885ee409e78e27fda550d/src/libsync/syncengine.cpp#L539

Does stat mean status -> Getting status failed ?

**Comment by rakekniven** [comment]
@misch7 Can you provide some words here?

**Comment by mikelgs1** [comment]
Hello! I´m sorry. This is my first time here. Maybe I should have said that I was translating Nextcloud in Transifex (English > Basque) and I saw that here: client, line 597.

Three lines below (600) I can see "Only %1 are available, need at least %2 to start". That´s the reason I thought it a mistake.

So, what should it be? Stat or start? I need to do the translation into Basque properly :-)

**Comment by rakekniven** [comment]
Hello @mikelgs1 ,

nice you made your way over here to GitHub.
Your line numbers are not source code line numbers. They are string id numbers at Transifex, right?

**Comment by mikelgs1** [comment]
Yes, they are! 😄

**Comment by rakekniven** [comment]
Ping

**Comment by rakekniven** [comment]
Hello @camilasan @misch7 Please spend a minute to enlighten us with some context.

Thank you.

**Comment by allexzander** [comment]
Hi. The message is indeed vague. Instead, we could use this:
**Item is skipped due to exclusion or an error.**
Kindly, refer to it as a more precise context.

**Comment by rakekniven** [comment]
Hello @er-vin,

would you mind to add comment from previos post as comment to code?
We hat a discussion last week in the community chat and I filed an issue here:
https://github.com/nextcloud/documentation/issues/5422

**Comment by er-vin** [comment]
> Hello @er-vin,
> 
> would you mind to add comment from previos post as comment to code?
> We hat a discussion last week in the community chat and I filed an issue here:
> [nextcloud/documentation#5422](https://github.com/nextcloud/documentation/issues/5422)

Well, @allexzander proposal was to change the whole string, which in that case is likely a better fix. Even "Stat failed" sucks as a message to the user, I think that something more verbose like proposed will be better for the user and reduce the need for a translator comment on that particular message. What do you think?

**Comment by rakekniven** [comment]
I want to achieve two goals. First use the string of @allexzander as comment to help all translators, second is to test the commenting thing for c++. 
A better source string which makes an comment superfluous is the best.

@er-vin But please help my with this comment stuff, then I can add comments myself to the source for example given short words like "Line" where you need some context.

**Comment by er-vin** [comment]
> I want to achieve two goals. First use the string of @allexzander as comment to help all translators, second is to test the commenting thing for c++.
> A better source string which makes an comment superfluous is the best.

Sure but @allexzander needs to know how to move on. Do you agree that his proposal is best and would make a comment superfluous? This way he can make a PR and put that issue to rest.

> @er-vin But please help my with this comment stuff, then I can add comments myself to the source for example given short words like "Line" where you need some context.

Not sure what more you'd need from me there. The recommendation is to do what's in the Qt doc linked in your issue:
```
//: translator comment
label->setText(tr("text to translate");
```

There's really nothing more to it.

**Comment by rakekniven** [comment]
Ok, so let's separate it, maybe my english is not accurate enough.

@allexzander Please create a PR with your text proposal. Thanks for that.

@er-vin I know the docs of Qt, but are there actually comment in given format somewhere in desktop source?
If so, please point me to them and I will check if comments are visible at Transifex UI to help translators.
If no, then please add a commit with given syntax and I will check Transifex as well.
Does that makes sense to you?

**Comment by er-vin** [comment]
> @er-vin I know the docs of Qt. Are there actually comments in given format somewhere in desktop source code?
> If so, please point me to them and I will check if comments are visible at Transifex UI to help translators.
> If no, then please add a commit with given syntax and I will check Transifex as well.
> Does that makes sense to you?

Gotcha! Yes we got a few already, for instance:
 * https://github.com/nextcloud/desktop/blob/master/src/libsync/syncresult.cpp#L138
 * https://github.com/nextcloud/desktop/blob/master/src/gui/folderstatusmodel.cpp#L150
 * https://github.com/nextcloud/desktop/blob/master/src/gui/folderstatusmodel.cpp#L976
 * https://github.com/nextcloud/desktop/blob/master/src/gui/folderstatusmodel.cpp#L982

There are obviously more.

**Comment by rakekniven** [comment]
Thank you @er-vin . C++ is now done.

**Comment by FlexW** [comment]
Is there still anything to address in this issue? If yes, feel free to open it again.
