### ISSUE TITLE
the right mouse button displays: "Share via %1"

### ISSUE THREAD

**Issue by mrcore** [nextcloud/desktop#1917]
Windows10, Chinese, in the synchronized folder, the right mouse button displays: "Share via %1".
![bug](https://user-images.githubusercontent.com/29938346/78877575-a2de3f00-7a83-11ea-991b-045e3e0494dd.PNG)

**Comment by claell** [comment]
@rakekniven this looks like a problem with the trainslations, correct? Could you or some of the translation team have a look?

**Comment by rakekniven** [comment]
> Windows10, Chinese, in the synchronized folder, the right mouse button displays: "Share via %1".
> ![bug](https://user-images.githubusercontent.com/29938346/78877575-a2de3f00-7a83-11ea-991b-045e3e0494dd.PNG)

What is the correct translation?

**Comment by mrcore** [comment]
> > Windows10, Chinese, in the synchronized folder, the right mouse button displays: "Share via %1".
> > ![bug](https://user-images.githubusercontent.com/29938346/78877575-a2de3f00-7a83-11ea-991b-045e3e0494dd.PNG)
> 
> What is the correct translation?

Chinese : 通过NextCloud共享

**Comment by rakekniven** [comment]
Looks like the placeholder "%1" isn't replaced like designed.
Will check on a windows machine tomorrow

**Comment by rakekniven** [comment]
Just checked it on a Win7 VM and it works with german.

On Transifex the encoding of the character "%" in chinese looked a little strange and I changed it.
See https://www.transifex.com/nextcloud/nextcloud/translate/#zh_CN/client/194472501?q=text%3A'Share+via+%251' and it's history.
Maybe that will fix it.

**Comment by mrcore** [comment]
@rakekniven      I guess Google Translator directly copied by the translator.
Google Translate will translate the half-width characters% (Unicode: \ u0025) into Chinese full-width characters% (Unicode: \ uff05). 
It is difficult for the eyes to find the difference.

**Comment by rakekniven** [comment]
Are you able to try this changing it localy on your machine?

**Comment by mrcore** [comment]
@rakekniven I don't know where to modify it.

**Comment by mrcore** [comment]
@rakekniven I need the client_zh_CN.qm file.

**Comment by mrcore** [comment]
@rakekniven I need a new client_zh_cn.qm file.

**Comment by rakekniven** [comment]
Hello @camilasan , can you provide a qm file with that tiny character change to get this tested?

**Comment by claell** [comment]
Is this fixed @mrcore @rakekniven?

**Comment by mrcore** [comment]
@claell  yes
