### ISSUE TITLE
Unable to sync certain PDF files: differences expected vs. read filesize

### ISSUE THREAD

**Issue by alex9434** [nextcloud/desktop#1918]
### Expected behaviour
PDF file gets synced.

### Actual behaviour
Error message for some (not all) PDF files:
Server replied: "400 Bad Request" to "PUT https:// *** deleted ***" (Expected filesize of 51076122 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 10944512 bytes.

### Steps to reproduce
1. Put PDF affected file in synced directory
2. Above error message

### Client configuration
Client version:

Operating system:
Windows 10
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
N/A
Client package (From Nextcloud or distro) (Linux only):
2.6.4stable-Win64
Installation path of client:
default

### Server configuration

Nextcloud version:
18.0.0.3
Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
[OCC::Application::setupLogging 	"################## Nextcloud locale:[en_SG] ui_lang:[en_US] version:[2.6.4stable-Win64 (build 20200303)] os:[Windows 10 (10.0)]"
[OCC::Application::slotParseMessage 	Running for 12754.5 sec
[OCC::AccessManager::createRequest 	2 "" "https://xxx/ocs/v1.php/cloud/user?format=json" has X-Request-ID "ffcc2028-d901-43f4-a50e-5c6c8f942ddb"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://xxx" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://xxx/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK"
[OCC::AccessManager::createRequest 	2 "" "https://xxx/remote.php/dav/avatars/alex/128.png" has X-Request-ID "f8efa9bd-342c-4ee3-ba2b-5f31ee96ac03"
[OCC::AbstractNetworkJob::start 	OCC::AvatarJob created for "https://xxx" + "" "OCC::UserInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished

2. Web server error log:
no error message

3. Server logfile: nextcloud log (data/nextcloud.log):
empty

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases

Please reopen the issue if the problem still exists.

**Comment by alex9434** [comment]
Hi @FlexW apologies for the delay. The problem does not seem to exist anymore on version 21.
