### ISSUE TITLE
Word Change

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#192]
This is a very minor change request but I found it odd that to start sync again the term is "unpause" it should be either "resume synchronization" or "start synchronization". "unpause" sounds clunky. Just a minor quibble.

**Comment by camilasan** [comment]
@jancborchardt maybe you have an opinion about it?

**Comment by jancborchardt** [comment]
Yep, it should be »Resume« in all cases where »Unpause« is used. :)
