### ISSUE TITLE
Blank page after login with server

### ISSUE THREAD

**Issue by numeropi** [nextcloud/desktop#1924]
Hi, trying the version 2.6.4 pkg desktop in imace

I receive a blank page after Next button once introduced our Nextcloud instance address: https://nubo.komun.org

![image](https://user-images.githubusercontent.com/56868560/79080402-d7b4f500-7d14-11ea-84b9-3becd20eda19.png)

Using the version 
https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-2.3.3.84.pkg
as suggested here:
https://help.nextcloud.com/t/problem-with-imac-and-nextcloud-desktop-app/74264

it solved the problem but not sure what happens with the most recent version.

**Comment by jonatansteller** [comment]
There is a previous bug report on the same issue that is already triaged: https://github.com/nextcloud/desktop/issues/1888

**Comment by claell** [comment]
Thanks for mentioning the duplicates @jonatansteller! Closing this one.

@numeropi please use #1793 for further tracking this issue.

**Comment by claell** [comment]
Duplicate of #1793
