### ISSUE TITLE
Conflict: Server version downloaded, local copy renamed and not uploaded

### ISSUE THREAD

**Issue by FDVCZ** [nextcloud/desktop#1928]
Hello everyone,

### Actual behaviour
we use NextCloud for our projects and we keep getting this notice:
"**Conflict: Server version downloaded, local copy renamed and not uploaded**"

This notice shows up when someone save a file which has been edited in the meanwhile.
It is correct behaviour that NextCloud detect this situation.

What is not correct is how NextCloud currently solves this situation.
Conflicted copy is not uploaded to the server.

I already searched out a statement that this is currently intended behaviour, but I am affraid **this is wrong!**

The very principle of cloud is to keep all things in cloud.
It means to keep all files accessible not only for other users, but also for myself in case I want to use a different device.   

**However, this basic principle is completely ruined by current NextCloud behaviour.** 

### Steps to reproduce
Example: My task is to update some document. I will do it and save the updated document (correct one). In the meanwhile someone else has accidentaly opened the same document and saves it (=wrong file is created) after me. My file (correct) is therefore not uploaded to the server. I leave my computer and somebody needs the correct file. But at this moment it is immpossible to get the correct file. No other user can reach the correct file, not even me although I have NextCloud mobile app, although I can access via web browser from other computer. 

This is unacceptable behaviour for a cloud storage!!!

### Expected behaviour
It is logical that on the cloud storage all files have to be uploaded on the server. It is not possible to monitor all files, all synchronisations, this would be a huge waste of time and also it is a big risk that file will be not accesibble when needed or will be lost completely.  

Remember: For a cloud storage priority number one is to safely store all files - in other words have a possibility to find a correct file. Categorizing which file is correct and which is wrong (what is trying to do current NextCloud logic at first) comes as the second, but (!!!) it can not be done when the correct file is missing!!!  

Note: Also compare this issue with other cloud solutions. Usually conflicted copies are uploaded to the server. I guess this has a good reason.

I also searched out there is an experimental feature - OWNCLOUD_UPLOAD_CONFLICT_FILES=1.
This is promissing, but it is not acceptable to have this only as local setting, this has to be a centralized switch (we can not watch all users whether they have this setting on value 0 or 1).

**Comment by progserega** [comment]
May be issue such?
https://github.com/nextcloud/desktop/issues/943

**Comment by FDVCZ** [comment]
> May be issue such?
> #943

Partially yes, but in #943 it is described as a general issue with no reason, which in my case is not. In my case I am aware this issue occurs only in a specific situation and it is not an issue but (for some weird reason) an intentional behaviour of NextCloud. Therefore result is the same in both cases, but maybe in #943 the reason is some unkown bug. In my case the reason is intention of NextCloud developers.

**Comment by kescherCode** [comment]
I suppose the sync client would need a feature where, per folder-sync connection, the behavior on conflicts can be adjusted.
Some people want to upload conflicts, some users want to always prefer the local file, and yet others may want to always prefer the remote file.

**Comment by FDVCZ** [comment]
> I suppose the sync client would need a feature where, per folder-sync connection, the behavior on conflicts can be adjusted.
> Some people want to upload conflicts, some users want to always prefer the local file, and yet others may want to always prefer the remote file.

Yes, you are totally right. 
(Only in my point of view this feature doesn't have to be "per folder", this could be a general switch for whole storage, basically a button using existing function "OWNCLOUD_UPLOAD_CONFLICT_FILES").
Regarding user preferences - I am sure there is also 3rd type of users - which doesn't want to share conflicted copies, but want to back up all files to cloud (considering local copy can be lost easily vs. files stored on cloud which have guaranteed availability and daily back-up). 

**From "_syncing perspective_" is for us always more important _to have a file_, than to protect a file (against unwanted sharing with others). This has a simple and logical reason - syncing is not intended for protection, for protection there are user groups (sharing only to authorized users). _Syncing should ensure all files are always synced_ on the cloud (even conflicted copies).**
This argument is valid even more because you can not ensure conflicted copy is the "wrong copy", on the contrary the conflicted copy can be the "correct copy" and the copy on cloud can be easily the wrong/obsolete one.

**Comment by kescherCode** [comment]
@FDVCZ In my use case, this would only be useful if it was a per "folder sync" setting. I have folders where having conflicted copies uploaded would cause havoc. I like to resolve conflicts manually. However, with other folders (often shared with other people), this would be fine.

> From "_syncing perspective_" is for us always more important _to have a file_
Not in my case.

**Comment by memen45** [comment]
Would it be possible to combine this with the current existing feature 'File versioning'? This would allow a conflicted copy to be accessible from the server by checking the file details and then 'Versions' tab. Additionally, conflicted versions could be marked as such with an exclamation mark?
