### ISSUE TITLE
Client is downloading files multiple times

### ISSUE THREAD

**Issue by sysoppl** [nextcloud/desktop#193]
I have mounted external storage (ostack), and every time I upload something to it, my desktop client is downloading files every time it sync to the server. That is generating a lot of bandwith. It downloaded my folder about 6 times now, and right now every time I start the app it download whole folder again, and again, and again..

### Steps to reproduce:
1. Open nextcloud and wait until it sync (download files)
2. Exit nextcloud
3. Open nextcloud again
4. It is downloading the same files
5. Exit nextcloud
6. repeat

**Comment by michaelstingl** [comment]
@sysoppl Thanks for reporting this issue. Could you post the "steps to reproduce"?

**Comment by camilasan** [comment]
You mean, there were no changes in the folder and yet it is trying to sync it every time?

**Comment by sysoppl** [comment]
Yes, every time I start app it was syncing the same files even if there was no changes. I tried scanning whole cloud via occ, but it doesnt help. Currently I dont use external storage anymore, just because of this bug. 
My external storage was Object Storage
