### ISSUE TITLE
Cancelled Sync When No Cancellation Was Given

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#194]
I am using Nextcloud Windows client on Windows 10 Professional and I have a few files that refuse to sync that throw out an error saying that the sync was cancelled even if there was no one using the computer. Why?

https://i.imgur.com/oDs9IPk.png

**Comment by camilasan** [comment]
You could check the logs for more specific errors. Did you bring this question to the forums help.nextcloud.com?

**Comment by camilasan** [comment]
needs info was never fulfilled :)
