### ISSUE TITLE
nautilus-nextcloud not working on debian Bullseye

### ISSUE THREAD

**Issue by parrenin** [nextcloud/desktop#1944]
### Expected behaviour
Tell us what should happen
I recently updated debian from buster to bullseye.
Nautilus-nextcloud was working correctly before, but now it does not work.
When I go to the Nextcloud folder, I don't see any stamp on the file and folders icons.
Moreover, NextCloud does not autostart, although it is in the autostart list in gnome-tweaks.
### Actual behaviour
Tell us what happens instead
There is no stamp on icons.
### Steps to reproduce
1. Install debian bullseye
2. Install nextcloud-desktop and nautilus-nextcloud packages
3. Go to the NextCloud folder.

### Client configuration
Client version:
2.6.2

Operating system:
Debian bullseye
OS language:
French
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
From distro
Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by 2EricBrunet** [comment]
Hi,
Same behavior in Nautilus interface at the installation on Bullseye, but today I can see it in my share folder :little stamp of color at the down right of the icons and a menu contextual (with a right click of the mouse). Maybe it must be reboot to work?

Technical détails:
```
# lsb_release -a
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
# aptitude -v show nautilus-nextcloud
Paquet : nautilus-nextcloud                             
Version : 2.6.4-1
```
Have a good day

**Comment by Dr-Willy** [comment]
I had the same issue on Debian Buster. 
@parrenin I had to manually install the package 'nextcloud-desktop-cmd' and it fixed the problem.

**Comment by er-vin** [comment]
@ivaradi I guess this one is for you?

**Comment by ivaradi** [comment]
I don't think `nextcloud-desktop-cmd` is really needed for `nautilus-nextcloud`. The Nautilus integration plugin communicates with the desktop client via a Unix socket (provided by the client), and does not call `nextcloudcmd` at all. It also works for me without having `nextcloud-desktop-cmd` installed, at least on Ubuntu, but I don't think it should work differently on Debian.

Since the desktop client did not start automatically for @parrenin, it may be the real cause. 

BTW, the versions mentioned are very old ones. My Debian repos already have the 3.1.1 version for testing.

**Comment by 2EricBrunet** [comment]
> Hi,
> Same behavior in Nautilus interface at the installation on Bullseye, but today I can see it in my share folder :little stamp of color at the down right of the icons and a menu contextual (with a right click of the mouse). Maybe it must be reboot to work?
> 
> Technical détails:
> 
> ```
> # lsb_release -a
> Description:	Debian GNU/Linux bullseye/sid
> Release:	testing
> # aptitude -v show nautilus-nextcloud
> Paquet : nautilus-nextcloud                             
> Version : 2.6.4-1
> ```
> 
> Have a good day

I confirm since my last distrib upgrade, my problem is solved!

$ aptitude -v show nautilus-nextcloud
Paquet : nautilus-nextcloud                             
Version : 3.0.1-3
