### ISSUE TITLE
Nextcloud restarts upload process constantly and fails (connection closed)

### ISSUE THREAD

**Issue by fdeitelhoff** [nextcloud/desktop#1945]
### Expected behaviour
Files should be uploaded when the size exceeds approximately 16 mb.

### Actual behaviour
The client restarts the upload process constantly at around 16/20 MB. See the gif.

![nextcloud-upload](https://user-images.githubusercontent.com/1618135/80624487-07216c80-8a4c-11ea-99b3-fd883d0249fc.gif)

### Steps to reproduce
1. Put a larger file (> 20 MB) in a synced folder on the desktop.
2. The client tries to sync/upload the file.
3. The error happens after some seconds.

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303)

Operating system: Windows 10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 17.0.0 - 18.0.3

Storage backend (external storage):

### Logs

https://gist.github.com/fdeitelhoff/4472e1583fe748353a223d30008e0155

You can see the connection reset/error in line 473.

2. Web server error log: not available

3. Server logfile: nextcloud log (data/nextcloud.log): The log file is empty

The error is weird and I cannot track it down. I can upload larger files from the web interface. This error appears on different systems with the same user name. Others do not have the problem and can upload files with more than 1 GB.

I reinstalled the client many times with no effect.

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases
