### ISSUE TITLE
Allow the application window to be smaller

### ISSUE THREAD

**Issue by merge** [nextcloud/desktop#1950]
### Expected behaviour
When I resize / shrink the client application window by dragging, it should at least become way thinner than it currently does.

### Actual behaviour
The windows has a quite large "minimum size" where it stops getting smaller.

### Steps to reproduce
1. Open the desktop client application window
2. Drag it smaller
3.

### Client configuration
Client version: 2.6.4

Operating system: Linux

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 5.12.5

Client package (From Nextcloud or distro) (Linux only): AppImage

Installation path of client: home dir

**Comment by claucambra** [comment]
I believe the settings window should now be resizeable to be fairly compact :)
