### ISSUE TITLE
Update ChangeLog file or delete it

### ISSUE THREAD

**Issue by hefee** [nextcloud/desktop#1952]
The ChangeLog  file in the top dir was not updated since v2.5.3, so please update it or delete it, if you do not care about this file anymore.

Me personally would love to have a ChangeLog file still beeing mantained, as it helps me to to scan through the released page. And it is a less scattered output than scanning over git log myself, as I do not want to read all those translation updates.

**Comment by camilasan** [comment]
Fix with #1956
