### ISSUE TITLE
sync client crashes while fetching folder list from a remote nextcould storage

### ISSUE THREAD

**Issue by dhrunia** [nextcloud/desktop#1959]
### Expected behaviour
Sync client to fetch the folder list and not crash

### Actual behaviour
Sync client says `fetching folder list from server` and then crashes

### Steps to reproduce
1. Configure a remote storage(also a nextcloud instance in my case)
2. In the nextcloud client, expand a folder on remote storage with many subfolders

### Client configuration
Client version:2.6.4

Operating system:Debian testing

OS language:English(India)

Qt version used by client package (Linux only, see also Settings dialog):5.12.5

Client package (From Nextcloud or distro) (Linux only):Appimage from Nextcloud

Installation path of client:/home/anirudh/Software

### Server configuration

Nextcloud version:18.0.4

Storage backend (external storage): Local and Nextcloud external storage

### Logs

1. Client logfile: https://gist.githubusercontent.com/dhrunia/2ad3167b72460f53213eab05644e2df6/raw/36f7a3c5d6a96212916ba401fc2c2b0b55a0cade/nextcloud_client.log

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases
