### ISSUE TITLE
nextcloud-client-caja from PPA depends on nonexistent python-caja

### ISSUE THREAD

**Issue by kc9jud** [nextcloud/desktop#1960]
This was apparently previously reported and fixed in Fedora/Redhat: https://bugzilla.redhat.com/show_bug.cgi?id=1746560

### Expected behaviour
Install from Nextcloud PPA on Ubuntu:
```
$ sudo add-apt-repository ppa:nextcloud-devs/client
$ sudo apt update
$ sudo apt install nextcloud-client-caja
```

### Actual behaviour
Unable to install with missing dependency:
```
$ sudo apt install nextcloud-client-caja 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nextcloud-client-caja : Depends: python-caja but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Steps to reproduce
1. Add PPA to `dpkg`.
2. Try to install `nextcloud-client-caja`.

### Client configuration
Client version: 
```
nextcloud-client-caja/focal,focal 2.6.4-20200303.193231~focal1 all
  Caja plugin for Nextcloud
```

Operating system: Ubuntu 20.04

OS language: en-us

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): Ubuntu PPA

Installation path of client: N/A

**Comment by ivaradi** [comment]
I have rebuilt the package so that it depends on `python3-caja`. Could you install the new version and try it?

**Comment by kc9jud** [comment]
That fixed it. Thanks!

**Comment by aliparsai** [comment]
This is breaking dependency on Linux Mint 19.3 Mate: 
```

$ sudo aptitude install nextcloud-client-caja 
The following NEW packages will be installed:
  caja-nextcloud{b} 
The following packages will be REMOVED:
  nextcloud-client{u} 
The following packages will be upgraded:
  nextcloud-client-caja 
1 packages upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 46.1 kB of archives. After unpacking 69.6 kB will be freed.
The following packages have unmet dependencies:
 caja-nextcloud : Depends: python3-caja which is a virtual package and is not provided by any available package

```


```
The following packages have unmet dependencies:
 caja-nextcloud : Depends: python3-caja but it is not installable
E: Unable to correct problems, you have held broken packages.

```

Maybe the dependency should be python-caja OR python3-caja

**Comment by ivaradi** [comment]
I have replace python3-caja with python-caja in distributions earlier than Focal and rebuilt the stable packages, which now have version 2.6.5.

@aliparsai, please, give it a try and let me know your results.

**Comment by aliparsai** [comment]
> I have replace python3-caja with python-caja in distributions earlier than Focal and rebuilt the stable packages, which now have version 2.6.5.
> 
> @aliparsai, please, give it a try and let me know your results.

Everything seems to work now. I got  an error message when upgrading from version 2.6.4, but when I removed nextcloud-client-caja first and installed it again the problem went away.

```
dpkg: error processing archive /tmp/apt-dpkg-install-ubFKyy/5-caja-nextcloud_2.6.5-20200711.134057.adada8b2e-1.0~bionic1_all.deb (--unpack):
 trying to overwrite '/usr/share/caja-python/extensions/syncstate-Nextcloud.py', which is also in package nextcloud-client-caja 2.6.4-20200303.193231~bionic1
Preparing to unpack .../6-nextcloud-client-caja_2.6.5-20200711.134057.adada8b2e-1.0~bionic1_all.deb ...
Unpacking nextcloud-client-caja (2.6.5-20200711.134057.adada8b2e-1.0~bionic1) over (2.6.4-20200303.193231~bionic1) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-ubFKyy/5-caja-nextcloud_2.6.5-20200711.134057.adada8b2e-1.0~bionic1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by ivaradi** [comment]
Thanks for the error report, it seems that some "Replaces:" directives were missing, which I have added now.
