### ISSUE TITLE
High process consumption in Windows Explorer

### ISSUE THREAD

**Issue by alex-dacosta** [nextcloud/desktop#1970]
### Expected behaviour
The Windows Explorer process consumption should remain low.

### Actual behaviour
Often (not always) while Nextcloud is checking for modifications, the Windows Explorer ends in consuming a lot of process %. This impedes the use of the Explorer itself for current operations (file copy, renaming, etc.).
When we put Nextcloud in pause, then the process consumption returns to normal.

### Steps to reproduce
1. 
2.
3.

### Client configuration
Client version: 2.6.4 

Operating system: Windows 10 18363

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.12.5, OpenSSL 1.1.1d

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: "C:\Program Files (x86)\Nextcloud\nextcloud.exe"

### Server configuration

Nextcloud version: 16

Storage backend (external storage):

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases
