### ISSUE TITLE
Nextcloud Sync client on MacOS delete files without permission on local drive...

### ISSUE THREAD

**Issue by emichaux3172** [nextcloud/desktop#1971]
Hello everyone.

I have a big issue on my Mac.
I was on macOS Mojave until end of March 2020 and I’m on macOS Catalina (10.15.4) now.
I’m using Nextcloud Desktop Sync. (V2.6.4stable) - build 20200303

Since january 2020, i have trouble with the sync. between my server and my Mac.
After connecting all my files from my local drive folder (Nextcloud), each of my files were sent to my distant web server. Which was good and all my files were accounted for.

However, i discovered the first time in January (i was under macOS Mojave) that a big part of my files where gone from my local drive.
I checked on my distant drive, and all of them where still on my distant one.

So i disconnected Nextcloud Sync on my Mac and reconnected it, to load again all my files to my local drive.

It took times, but after some weeks, once again, my files where gone from my local drive. (still available on my distant drive - fortunately)

I re-did a sync between my distant and local drive and my files stayed on my local drive for a long time until end of march. (Before my upgrade to macOS Catalina.)

After discussing with a friend of mine, i decided to upgrade my OS with the hope to solve this issue (loss of my local files).

Unfortunately, it did not work at all and i had to disconnect definitively Nextcloud Sync to keep my local files on my local drive.

Did anyone has the same issue ?
Did anyone has a solution ?

Thanks for your reply.

Eric

**Comment by axsdenied** [comment]
Probably the same issue here but on Debian Buster with the same version of the Desktop Sync client.

Everything worked for a while and then lots of local files got deleted. They were still on the server. Force sync did not get them back, the log files reported that everything was synced even though the files were not there.
After reconnecting the desktop client all the files got synced back.

A few days later the local files were gone again. This time I found a workaround, I simply created a file on the server (using the browser interface) and then suddenly the Desktop Sync Client decided to get about 2GB of the deleted files. It did not get everything though, lots of the local files were still missing. Creating another file in a different subfolder (using the browser interface again) triggered another large sync session by the client.

**Comment by felixbinder** [comment]
I'm experiencing the same issue on macOS and nextcloud 3.0.2. The files are present on the server, but whole local folders are empty/non existing.

**Comment by emichaux3172** [comment]
I'm glad that some people has the same issue... now i'd like that Nextcloud client would work now ?!
Anyone got news from them on this BIG ISSUE ?

**Comment by er-vin** [comment]
Is it me or that sounds like a duplicate of #260 ?

**Comment by njm2112** [comment]
(x-posted to [#260](https://github.com/nextcloud/desktop/issues/260))

client: v3.1.1 installed on macOS Big Sur (11.1)
server: v17.0.2 via Docker (using mariadb, in case that matters)

i am having this problem as well but it seems to have been triggered by my running out of disk space on my local hard drive. suddenly I noticed a huge volume of files had been deleted locally and once the client realized that it could write to the local hard drive again, it began to sync data from a folder on the server that i had previously excluded from syncing...

really hoping that nextcloud addresses this bug promptly.
