### ISSUE TITLE
Desktop client fails after power saving mode

### ISSUE THREAD

**Issue by sanchobear** [nextcloud/desktop#1978]
### Expected behaviour
After starting computer from power saving mode, nextcloud desktop client should be in the same state as before and ready to synchronize files.

### Actual behaviour
Starting from power saving made renders naxtcloud desktop client unresposible with error message  "An error occurred while opening a folder" and "Der Zugriff auf das Netzwerk ist nicht gestattet"

### Steps to reproduce
1. Start Nextcloud clinet
2. Check that sync is working
3. Set computer to power saving mode
4. Start computer
5. Inspect Nextcloud desktop client
6. Sync not working, client app crashed

### Client configuration
Client version: 2.6.4stable-Win64 (build 20200303). 
Operating system: Win 10 64 bit Version 1909
OS language: German
Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 18.0.4
Storage backend (external storage): local disk

### Logs
![image](https://user-images.githubusercontent.com/15321726/81941981-35817900-9602-11ea-8d54-53a0e4c74a90.png)

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
### before power saving mode
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://serveraddress/nextcloud/remote.php/dav/files/name/" :  "Success"
[OCC::FolderMan::slotFolderSyncFinished 	<========== Sync finished for folder [D:\Nextcloud] of account [name@serveraddress] with remote [https://serveraddress/nextcloud/remote.php/dav/files/name/]

### start from power saving mode
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://serveraddress/nextcloud/remote.php/dav/files/name/" has X-Request-ID "262b93c6-0e26-46bc-b1b4-0d414b67c007"
[OCC::AbstractNetworkJob::start 	OCC::PropfindJob created for "https://serveraddress/nextcloud" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropfindJob::finished 	PROPFIND of QUrl("https://serveraddress/nextcloud/remote.php/dav/files/name/") FINISHED WITH STATUS "OK"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://serveraddress/nextcloud/remote.php/dav/files/name/" for changes via ETag check. (time since last sync: 54 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://serveraddress/nextcloud/remote.php/dav/files/name/" has X-Request-ID "d4655439-162c-451a-bf08-0c5c0b86fb16"
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://serveraddress/nextcloud" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://serveraddress/nextcloud/remote.php/dav/files/name/") FINISHED WITH STATUS "OK"
[OCC::Folder::slotRunEtagJob 	Trying to check "https://serveraddress/nextcloud/remote.php/dav/files/name/" for changes via ETag check. (time since last sync: 134 s)
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://serveraddress/nextcloud/remote.php/dav/files/name/" has X-Request-ID "c44d46fd-5065-447b-8d8f-90cc3dd39d9d"
[OCC::RequestEtagJob::start 	request network error:  "Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::AbstractNetworkJob::start 	OCC::RequestEtagJob created for "https://serveraddress/nextcloud" + "/" "OCC::Folder"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::UnknownNetworkError "Der Zugriff auf das Netzwerk ist nicht gestattet." QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownNetworkError
[OCC::WebFlowCredentials::stillValid 	"Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::RequestEtagJob::finished 	Request Etag of QUrl("https://serveraddress/nextcloud/remote.php/dav/files/name/") FINISHED WITH STATUS "UnknownNetworkError Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::AccessManager::createRequest 	2 "" "https://serveraddress/nextcloud/ocs/v1.php/cloud/user?format=json" has X-Request-ID "637aa43f-2554-4f41-b192-9bd6aed30251"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://serveraddress/nextcloud" + "ocs/v1.php/cloud/user" "OCC::UserInfo"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://serveraddress/nextcloud/remote.php/dav/files/name/" has X-Request-ID "e209b605-7175-447a-ac9c-9e70d747d53a"
[OCC::AbstractNetworkJob::start 	OCC::LsColJob created for "https://serveraddress/nextcloud" + "/" "OCC::FolderStatusModel"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::UnknownNetworkError "Der Zugriff auf das Netzwerk ist nicht gestattet." QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownNetworkError
[OCC::WebFlowCredentials::stillValid 	"Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::JsonApiJob::finished 	JsonApiJob of QUrl("https://serveraddress/nextcloud/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "UnknownNetworkError Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::JsonApiJob::finished 	Network error:  "ocs/v1.php/cloud/user" "Der Zugriff auf das Netzwerk ist nicht gestattet." QVariant(Invalid)
[OCC::AccessManager::createRequest 	2 "" "https://serveraddress/nextcloud/remote.php/dav/avatars/name/128.png" has X-Request-ID "5eebbec0-d424-45a6-88bd-0315102a4af6"
[OCC::AbstractNetworkJob::start 	OCC::AvatarJob created for "https://serveraddress/nextcloud" + "" "OCC::UserInfo"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::UnknownNetworkError "Der Zugriff auf das Netzwerk ist nicht gestattet." QVariant(Invalid)
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::UnknownNetworkError
[OCC::WebFlowCredentials::stillValid 	"Der Zugriff auf das Netzwerk ist nicht gestattet."
[OCC::LsColJob::finished 	LSCOL of QUrl("https://serveraddress/nextcloud/remote.php/dav/files/name/") FINISHED WITH STATUS "UnknownNetworkError Der Zugriff auf das Netzwerk ist nicht gestattet."

2. Web server error log:
No relevant errors

3. Server logfile: nextcloud log (data/nextcloud.log):
No relevant errors

**Comment by killermouse0** [comment]
Same issue. My current workaround is to quit and restart the client. Annoying since my laptop goes to sleep very frequently during the day. If anyone has a better one, please chime in!

**Comment by er-vin** [comment]
Is it me or it is a duplicate of #482 ?
