### ISSUE TITLE
crashed with SIGSEGV in QAbstractEventDispatcherPrivate::allocateTimerId()

### ISSUE THREAD

**Issue by Thorsten42** [nextcloud/desktop#1980]
### Expected behaviour
no crash :)

### Actual behaviour
nextcloud crashed 

### Steps to reproduce
1. it came out of nowhere

### Client configuration
Client version: nextcloud 2.6.4 from the nextcloud ubuntu 20.04 ppa 

Operating system: ubuntu 20.04

OS language: en-us

Qt version used by client package (Linux only, see also Settings dialog):
Nextcloud version 2.6.4git
Using Qt 5.12.8, built against Qt 5.12.8
Using 'OpenSSL 1.1.1f  31 Mar 2020'

Client package (From Nextcloud or distro) (Linux only): nextcloud ppa

Installation path of client:
default (/usr/bin/nextcloud)

### Stacktrace from ubuntu apport
`
SegvAnalysis:
 Segfault happened at: 0x7eff8a35360a <_ZN31QAbstractEventDispatcherPrivate15allocateTimerIdEv+58>:	mov    (%r15),%ebp
 PC (0x7eff8a35360a) ok
 source "(%r15)" (0x00000030) not located in a known VMA region (needed readable region)!
 destination "%ebp" ok
 Stack memory exhausted (SP below stack segment)
SegvReason: reading NULL VMA
SourcePackage: nextcloud-client
Stacktrace:
 #0  0x00007eff8a35360a in QAbstractEventDispatcherPrivate::allocateTimerId() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #1  0x00007eff8a353bfd in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #2  0x00007eff8a3543a1 in QBasicTimer::start(int, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #3  0x00007eff8b2edd85 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #4  0x00007eff8b2ee49b in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #5  0x00007eff8b34b494 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #6  0x00007eff8b34b60d in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #7  0x00007eff8a382b74 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #8  0x00007eff8ad6ea66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
 No symbol table info available.
 #9  0x00007eff8ad780f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
 No symbol table info available.
 #10 0x00007eff8a35693a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #11 0x00007eff8a3595b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #12 0x00007eff8a3aef67 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #13 0x00007eff956bdfbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #14 0x00007eff956be240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #15 0x00007eff956be2e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #16 0x00007eff8a3ae565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #17 0x00007eff8a3554db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #18 0x00007eff8a18d785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #19 0x00007eff8a18e9d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #20 0x00007eff89b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139635446826752, -5446800765864405344, 140734489144670, 140734489144671, 140734489144864, 139635446822912, 5302920282973116064, 5302426639369606816}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #21 0x00007eff89cb3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
StacktraceAddressSignature: /usr/bin/nextcloud:11:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+20060a:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+200bfd:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+2013a1:/usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12.8+14d85:/usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12.8+1549b:/usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12.8+72494:/usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12.8+7260d:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+22fb74:/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.12.8+1da66:/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.12.8+270f0:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+20393a:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+2065b8:/usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8+25bf67:/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.2+35fbd:/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6400.2+36240
StacktraceTop:
 QAbstractEventDispatcherPrivate::allocateTimerId() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 QBasicTimer::start(int, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
Tags: third-party-packages focal
ThreadStacktrace:
 .
 Thread 5 (Thread 0x7eff637fe700 (LWP 2559)):
 #0  0x00007eff89ca696f in __GI___poll (fds=0x7eff380018f0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimized out>
 #1  0x00007eff956be1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007eff956be2e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007eff8a3ae565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #4  0x00007eff8a3554db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #5  0x00007eff8a18d785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #6  0x00007eff8a18e9d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #7  0x00007eff89b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139635351086848, -5446800765864405344, 140734489144926, 140734489144927, 140734489145120, 139635351083008, 5302941765325788832, 5302426639369606816}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #8  0x00007eff89cb3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 4 (Thread 0x7eff69b4d700 (LWP 2542)):
 #0  0x00007eff89ca696f in __GI___poll (fds=0x7eff4400e450, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimized out>
 #1  0x00007eff956be1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007eff956be533 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007eff955a9e9a in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
 No symbol table info available.
 #4  0x00007eff956e7931 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007eff89b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139635455219456, -5446800765864405344, 139635463607502, 139635463607503, 139635463607648, 139635455215616, 5302919181850875552, 5302426639369606816}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #6  0x00007eff89cb3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 3 (Thread 0x7eff7efc5f00 (LWP 2447)):
 #0  0x00007eff957ca3f8 in ?? () from /lib64/ld-linux-x86-64.so.2
 No symbol table info available.
 #1  0x00007eff957c2eca in ?? () from /lib64/ld-linux-x86-64.so.2
 No symbol table info available.
 #2  0x00007eff89bdaa27 in __run_exit_handlers (status=1, listp=0x7eff89d7c718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
         atfct = <optimized out>
         onfct = <optimized out>
         cxafct = <optimized out>
         f = <optimized out>
         new_exitfn_called = 2223
         cur = 0x559d77164b30
 #3  0x00007eff89bdabe0 in __GI_exit (status=<optimized out>) at exit.c:139
 No locals.
 #4  0x00007eff7ce14c0c in ?? () from /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
 No symbol table info available.
 #5  0x00007eff87dc41a2 in _XIOError () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #6  0x00007eff87dc12e8 in ?? () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #7  0x00007eff87dc1afd in _XFlush () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #8  0x00007eff87dc482d in _XGetRequest () from /lib/x86_64-linux-gnu/libX11.so.6
 No symbol table info available.
 #9  0x00007eff7c3e9c92 in ?? () from /lib/x86_64-linux-gnu/libGLX_mesa.so.0
 No symbol table info available.
 #10 0x00007eff7e1d2b0d in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
 No symbol table info available.
 #11 0x00007eff7e1d2b1d in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
 No symbol table info available.
 #12 0x00007eff8a77ed2f in QOpenGLContext::destroy() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
 No symbol table info available.
 #13 0x00007eff8a77efdb in QOpenGLContext::~QOpenGLContext() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
 No symbol table info available.
 #14 0x00007eff8a77effd in QOpenGLContext::~QOpenGLContext() () from /lib/x86_64-linux-gnu/libQt5Gui.so.5
 No symbol table info available.
 #15 0x00007eff93ac0254 in ?? () from /lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5
 No symbol table info available.
 #16 0x00007eff8a358852 in qt_call_post_routines() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #17 0x00007eff8ad6f12a in QApplication::~QApplication() () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
 No symbol table info available.
 #18 0x0000559d754e78bf in SharedTools::QtSingleApplication::~QtSingleApplication() ()
 No symbol table info available.
 #19 0x0000559d753d8ba0 in OCC::Application::~Application() ()
 No symbol table info available.
 #20 0x0000559d753a39f3 in main ()
 No symbol table info available.
 .
 Thread 2 (Thread 0x7eff6ab4f700 (LWP 2540)):
 #0  0x00007eff89ca696f in __GI___poll (fds=0x559d7790fd40, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
         sc_ret = <optimized out>
 #1  0x00007eff956be1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #2  0x00007eff956be2e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #3  0x00007eff956be331 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #4  0x00007eff956e7931 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #5  0x00007eff89b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139635472004864, -5446800765864405344, 140734489141630, 140734489141631, 140734489141776, 139635472001024, 5302925777846900384, 5302426639369606816}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #6  0x00007eff89cb3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 No locals.
 .
 Thread 1 (Thread 0x7eff6934c700 (LWP 27072)):
 #0  0x00007eff8a35360a in QAbstractEventDispatcherPrivate::allocateTimerId() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #1  0x00007eff8a353bfd in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #2  0x00007eff8a3543a1 in QBasicTimer::start(int, QObject*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #3  0x00007eff8b2edd85 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #4  0x00007eff8b2ee49b in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #5  0x00007eff8b34b494 in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #6  0x00007eff8b34b60d in ?? () from /lib/x86_64-linux-gnu/libQt5Network.so.5
 No symbol table info available.
 #7  0x00007eff8a382b74 in QObject::event(QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #8  0x00007eff8ad6ea66 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
 No symbol table info available.
 #9  0x00007eff8ad780f0 in QApplication::notify(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
 No symbol table info available.
 #10 0x00007eff8a35693a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #11 0x00007eff8a3595b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #12 0x00007eff8a3aef67 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #13 0x00007eff956bdfbd in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #14 0x00007eff956be240 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #15 0x00007eff956be2e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
 No symbol table info available.
 #16 0x00007eff8a3ae565 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #17 0x00007eff8a3554db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #18 0x00007eff8a18d785 in QThread::exec() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #19 0x00007eff8a18e9d2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
 No symbol table info available.
 #20 0x00007eff89b04609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139635446826752, -5446800765864405344, 140734489144670, 140734489144671, 140734489144864, 139635446822912, 5302920282973116064, 5302426639369606816}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #21 0x00007eff89cb3103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

`

**Comment by FlexW** [comment]
Could you please try a more recent version and tell us if the problem still exists?

The newest version can be found on: https://github.com/nextcloud/desktop/releases
