### ISSUE TITLE
High CPU load with .sync-exclude.lst

### ISSUE THREAD

**Issue by HorstBort** [nextcloud/desktop#1983]
### Expected behaviour
Nextcloud should not use 100% CPU

### Actual behaviour
100% CPU usage (1 core) during sync

### Steps to reproduce
1. Add `.sync-exclude.lst` to folder
2. Wait
3. Observe 100 % CPU usage (1 core during sync)

### Client configuration
Client version: 2.6.4-20200303.193231~focal2

Operating system:
`LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
`
Note: Happened under Ubuntu 19.10 Eoan as well.

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.12.8

Client package (From Nextcloud or distro) (Linux only): 2.6.4-20200303.193231~focal2

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

Not provided due to privacy. Also, timestamps in the log file would make it way easier to provide relevant lines only.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

4. strace: Following lines flood strace output. Removing `.sync-exclude.lst` fixes this.

`openat(AT_FDCWD, "/home/hauke/Nextcloud/Software/Spotify/.sync-exclude.lst", O_RDONLY|O_CLOEXEC) = 35
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
read(35, ".idea/workspace.xml\n.idea/Spotif"..., 16384) = 49
read(35, "", 16335)                     = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
munmap(0x7f18918ec000, 1376256)         = 0
munmap(0x7f1891a3c000, 1179648)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1891b1c000
mprotect(0x7f1891b1c000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1892cce000, 1114112)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18919ec000
mprotect(0x7f18919ec000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892cce000
mprotect(0x7f1892cce000, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1891c4c000, 1376256)         = 0
munmap(0x7f1892b9e000, 1245184)         = 0
mmap(NULL, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1891c4c000
mprotect(0x7f1891c4c000, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892b9e000
mprotect(0x7f1892b9e000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f18a849a000, 1376256)         = 0
munmap(0x7f18928be000, 1245184)         = 0
mmap(NULL, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18a849a000
mprotect(0x7f18a849a000, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18928be000
mprotect(0x7f18928be000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
close(35)                               = 0
openat(AT_FDCWD, "/home/hauke/Nextcloud/Software/Spotify/.sync-exclude.lst", O_RDONLY|O_CLOEXEC) = 35
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
read(35, ".idea/workspace.xml\n.idea/Spotif"..., 16384) = 49
read(35, "", 16335)                     = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
munmap(0x7f1892efe000, 1048576)         = 0
munmap(0x7f1891d9c000, 1179648)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1891d9c000
mprotect(0x7f1891d9c000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1892cce000, 1114112)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f189168c000
mprotect(0x7f189168c000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892cce000
mprotect(0x7f1892cce000, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1891c4c000, 1376256)         = 0
munmap(0x7f1892b9e000, 1245184)         = 0
mmap(NULL, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1891c4c000
mprotect(0x7f1891c4c000, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892b9e000
mprotect(0x7f1892b9e000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f18a849a000, 1376256)         = 0
munmap(0x7f18928be000, 1245184)         = 0
mmap(NULL, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18a849a000
mprotect(0x7f18a849a000, 1376256, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18928be000
mprotect(0x7f18928be000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
close(35)                               = 0
openat(AT_FDCWD, "/home/hauke/Nextcloud/Software/Spotify/.sync-exclude.lst", O_RDONLY|O_CLOEXEC) = 35
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
read(35, ".idea/workspace.xml\n.idea/Spotif"..., 16384) = 49
read(35, "", 16335)                     = 0
statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=49, ...}) = 0
munmap(0x7f18a811a000, 1179648)         = 0
munmap(0x7f1892dde000, 1179648)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f18a810a000
mprotect(0x7f18a810a000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1892cce000, 1114112)         = 0
mmap(NULL, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892ece000
mprotect(0x7f1892ece000, 1245184, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
mmap(NULL, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1892dbe000
mprotect(0x7f1892dbe000, 1114112, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
munmap(0x7f1891c4c000, 1376256)         = 0
munmap(0x7f1892b9e000, 1245184)         = 0
^Cstrace: Process 205693 detached`

**Comment by laurenzroth** [comment]
One of my users is experiencing this as well on his Mac. See the specs below. Removing `.sync-exclude.lst` did not resolve the problem for him.

<img width="584" alt="Schermafbeelding 2020-06-29 om 22 01 31" src="https://user-images.githubusercontent.com/47368888/86473462-394b9500-bd41-11ea-8517-d2e6abf37cb0.png">
