### ISSUE TITLE
Sync issue with files

### ISSUE THREAD

**Issue by Kastello1** [nextcloud/desktop#1985]
### Expected behaviour
Nextcloud Windows App should sync folder and files

### Actual behaviour
No files are transfered/synced

### Steps to reproduce
1. Add Nextcloud account to client
2. Add folder for sync

### Client configuration
Client version: Version 2.6.4stable-Win64 (build 20200303).

Operating system: 
Windows 10

OS language: 
German

Installation path of client:
Default

### Server configuration

Nextcloud version:
18.0.4
Server:
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
https://gist.github.com/Kastello1/d620db73f0f3b0e049514ec0203775ae

**Comment by FlexW** [comment]
Version 2.6.4 is pretty old. Could you try a more recent version and tell us if you still have the problems?
