### ISSUE TITLE
Endless sync error on Windows: Readme.md empty while 5 byte on server (+ workaround fix)

### ISSUE THREAD

**Issue by jpeg2600** [nextcloud/desktop#1993]
### Expected behaviour
Every files should sync correctly

### Actual behaviour
Windows 10 was popping up a sync error notification every other minute while I was working on some files. My message was in french but the Nextcloud's error could be loosely translated as "the file received is empty but the server indicates it's 5 bytes". 

### FIX: 
Disabling rich workspaces or adding text to the header fixed it. Clicking on the header creates an empty readme.md file but in my case, that was causing a problem with the synchronisation. 

### Steps to reproduce
I'm unable to reproduce the problem by simply activating the rich workspace again. 

### Client configuration
Client version: 2.6.4 (latest as of today) 

Operating system: Windows 10
OS language: French

### Server configuration

Nextcloud version: 18.0.4 (latest as of today) 

1. Client logfile: 
`[OCC::AccessManager::createRequest 	2 "" "https://data.lan/remote.php/dav/files/admin/Readme.md" has X-Request-ID "a240285f-c530-4ce5-bc9c-b69efb92d8c5"
[OCC::AbstractNetworkJob::start 	OCC::GETFileJob created for "https://data.lan" + "/Readme.md" "OCC::PropagateDownloadFile"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::PropagateItemJob::done 	Could not complete propagation of "Readme.md" by OCC::PropagateDownloadFile(0x1a96e384af0) with status 2 and error: "Le fichier reçu est vide bien que le serveur indique que sa taille devrait être de 5 octets."`

**Comment by 71GA** [comment]
@jpeg2600  You say: 

> Disabling rich workspaces or adding text to the header fixed it.

Can you be a bit more speciffic / descriptive. How did you dissable rich workspaces?
