### ISSUE TITLE
In activity verb is not shown in German translation

### ISSUE THREAD

**Issue by smatthie** [nextcloud/desktop#2002]
### Expected behaviour
The activity entries should be some kind of full sentences.

### Actual behaviour
In German, the verb comes at the end and is usually cut off as the line is too long, so what should be "you have uploaded file1 file2 ..." becomes "Du hast Datei1, Datei2..." without the verb at the end that says what I actually have done with the files.

### Steps to reproduce
1. Open the activity pane in the German version of the client.
2. You see it. 
3.

### Client configuration
Client version: 2.6.4stable-Win64 (build 20200303).

Operating system: Windows 10 (64)

OS language: German

![nextcloud](https://user-images.githubusercontent.com/4404285/82557644-fef8b080-9b63-11ea-94fb-f4e93d0d0ddf.png)

**Comment by veddox** [comment]
The translations have already been revamped in the newest version. Instead of "Du hast <filename> erstellt" it now says "Sie haben erstellt <filename>". This should have fixed the issue.

You can download a daily build here: https://download.nextcloud.com/desktop/daily/Windows/
