### ISSUE TITLE
macOS client 2.6.4 shows wxWidgetsDebugAlert upon user login [intermittent]

### ISSUE THREAD

**Issue by mackonsti** [nextcloud/desktop#2004]
### Expected behaviour
From time to time, when I reboot MacOS Mojave and go onto the desktop after login, I get this window popping up. This is not a constant problem but intermittent, and I noticed it only after I installed Nextcloud Client 2.6.3 some time ago (was the first time, ever). My login user has administrator privileges.
![wxWidgetsDebugAlert](https://user-images.githubusercontent.com/1313613/82650993-d7651f00-9c1b-11ea-83d6-d757d600bedb.png)
### Actual behaviour
This **wxWidgets Debug Alert** window should not appear.

### Steps to reproduce
The issue is **intermittent** and I have not understood under what conditions it happens, yet.
1. Install Nextcloud Client on macOS
2. Login and connect as a fresh user (on macOS)
3. Reboot and login the same user.

### Client configuration
Client version:  **2.6.4stable** (build 20200303)
Operating system: MacOS **Mojave 10.14.6** with latest updates
OS language: **English**
Qt version used by client package (Linux only, see also Settings dialog): **N/A**
Client package (From Nextcloud or distro) (Linux only): **N/A**
Installation path of client: **Default** at:
`/Applications/NextCloud.app/Contents/MacOS/nextcloud`

### Server configuration
Type: OpenMediaVault **4.1.3x Arrakis** (Debian)
Using Docker Engine (19.03.9) with image from **linuxserver/nextcloud**
Nextcloud version: **Nextcloud 18.0.4** version
Storage backend (external storage): **None** (all internal drives)

### Logs
1. Client logfile: **Not available yet**
There is no log that I could capture early on in the reboot/login process, will be retrying to reproduce and will advise.
2. Web server error log: **N/A**
3. Server logfile: nextcloud log (data/nextcloud.log): **N/A**

Thank you for considering checking this issue, please do let me know what more information you would require that I can get you when it happens again, from my macOS client.

**Comment by mackonsti** [comment]
Hello again, I wanted to report that the client showed again this dialog window. Still using the MacOS client **2.6.4 stable** and I realised this is shown when the NextCloud server is not running on the NAS or the URL cannot be reached. Just happened earlier when I had to shut down the OpenMediaVault running NextCloud insider Docker.

![wxWidgets Debug Alert NextCloud Offline](https://user-images.githubusercontent.com/1313613/83569323-9545b280-a524-11ea-944b-51226170a868.png)

Thank you again for your attention. Best regards

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by mackonsti** [comment]
Hello @camilasan thank you for your message. I had installed already on 2 macOS computers your latest (per these days) client version 3.1.2 (macOS) and did **not** encounter this issue. Thanks again.
