### ISSUE TITLE
nextcloude directory containing . cannot be synced

### ISSUE THREAD

**Issue by fschaupp** [nextcloud/desktop#2008]
### Expected behaviour
nextcloud should be able to open the nextcloud folder in order to sync it's content

### Actual behaviour
An error occurred, sayin' the nextcloud folder couldn't be opened and the "Open Browser" Button appeard, but after clicking it, it redirected me to a wrong url
actual: Ccloud.something.tld wrong one: C%5Ccloud.something.tld
My nextcloud folder ist at C:\cloud.something.tld

### Steps to reproduce
- install windows client v2.6.4
- name your nextcloudfolder like the domain
- sync stuff (at least try)
the check for differences will work, but then it crashes

### Client configuration
Client version:
2.6.4 Windows client

Operating system:
Windows 10 EE
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
Default (Program x86)

### Server configuration
linux one
Nextcloud version:
2.6.3
Storage backend (external storage):
ftp
### Logs
https://pasteboard.co/J9Lyn3r.png

**Comment by mbenecke** [comment]
I can replay this with my setup:

### Windows Client
Version 2.6.4stable-Win64 (build 20200303). 
Built from Git revision b45f5f on Mar 3 2020, 20:59:52 using Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019

### Server
Debian GNU/Linux 8.5.0 - Docker  version 17.05.0-ce, build 89658be
Nextcloud Container: [nextcloud:stable](https://hub.docker.com/_/nextcloud)
Loadbalancer: [linuxserver/letsencrypt](https://docs.linuxserver.io/images/docker-letsencrypt)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
