### ISSUE TITLE
can't sync or create folders with name "core" (case-sensitive)

### ISSUE THREAD

**Issue by riidom** [nextcloud/desktop#2009]
### Expected behaviour
When syncing, it should not ignore folders with name "core"; when creating it should not give an error message

### Actual behaviour
On syncing, it would tell me in the desktop client that "sync ok, but some files ignored"
On creation it will give an error message "could not create folder core". If I create a folder e.g. name "test" and rename it to "core" this will work, but NC acts weird, it jumps back to root folder and I am not able to delete the "core" (formerly test) folder anymore. Deleting the parent folder seems to work though.

### Steps to reproduce
1. Have a folder structure on your local HDD with a subfolder called "core" (and some files in it maybe?)
2. try to sync, see the core folder gets ignored
3. add the core folder in appropiate place yourself, to give NC a gentle aid
4. try to add a folder named core somewhere else 

### Client configuration
Client version:
Version 2.6.4stable (build 20200303)

Operating system:
Kubuntu 18.04

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.12.5

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
~/Anwendungen/Nextcloud-2.6.4-x86_64.AppImage

### Server configuration

Nextcloud version:
 18.0.4

Storage backend (external storage):

### Logs

Invalid argument supplied for foreach() at /mnt/$XXXX/htdocs/nc/apps/serverinfo/lib/Os.php#155		2020-05-24T09:47:09+0200
Undefined variable: result at /mnt/$XXXX/htdocs/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173		2020-05-24T09:47:09+0200
Invalid argument supplied for foreach() at /mnt/$XXXX/htdocs/nc/apps/serverinfo/templates/settings-admin.php#101		2020-05-24T09:47:07+0200
Undefined variable: result at /mnt/$XXXX/htdocs/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173		2020-05-24T09:47:07+0200
A non-numeric value encountered at /mnt/$XXXX/htdocs/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#52		2020-05-24T09:47:07+0200

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file. 

Thanks!

**Comment by riidom** [comment]
I don't have it installed anymore, closing it, thank you.
