### ISSUE TITLE
Can't use public link created by another user

### ISSUE THREAD

**Issue by biva** [nextcloud/desktop#2011]
### Expected behaviour
When User A has created a public link for a file, this link should be available for User B as well. This should be available:
- A. When User B accesses the "Share Options" feature (right-click on a file, Share via Nextcloud, share options), User B should be able to copy the link created by User A (instead, we just see the message "User A shared via link", but the link is not accessible)
- B. When User B copies a public link (right-click on a file, Share via Nextcloud, Copy public link), the link created by User A should be copied (instead, a new link is copied)

On the user interface in the browser, User B can see the link created by User A (and even copy it, modify the permissions and remove it)

### Potential related issues
- https://github.com/nextcloud/desktop/issues/858
- https://github.com/nextcloud/desktop/issues/1179
- https://github.com/nextcloud/desktop/issues/1304
- https://github.com/nextcloud/desktop/issues/1903

**Comment by warnerbryce** [comment]
I don’t think it’s a good idea
User A create share link for a file for a specific customer with a password and expiration date. 
If user b could use the same link he will have to deal with this, and can’t know what the password is. 

If user B could use the same link, so he can delete the share while user A still wanted to use it.

**Comment by kescherCode** [comment]
Each user has his own link. This is how Nextcloud (and ownCloud too, btw!) work internally. This would cause quite a few incompatibilities.

**Comment by er-vin** [comment]
I agree with the other commenters here, this is not going to fly AFAICT and will lead to interoperability issues.

**Comment by biva** [comment]
Hello @er-vin I understand your doubt, but I continue to think that it's a good idea. I think Nextcloud aims to be a collaborative platform, right? Within an organisation, we share public links with others. The advantages are that:
1. We avoid sending large pieces on email
2. We can keep the same link with different versions: even if I edit a document, my partner can always have the updated version by clicking on the link

When you work with partners, it's confusing for them if we share different links. It's much better if I can see the public link created by my colleague.

In addition, if we create multiple public links, one user can remember to remove his link, and another user can forget it: one link will remain active, while the organisation wants to remove all the public links for this file. In my experience, you can't trust users to manage old links correctly.

Finally, I understand your doubt @warnerbryce about deleting a link that userB would want to keep. But we would avoid that by showing the name of the user who created the link, don't you think?

Technically, I don't understand the problem: NC server knows the list of whole public links. The only thing to do would be to display the public link if it already exists. If modifying the properties of a link leads to a technical issue, then displaying the link (with the name of the user who created the link) would be enough.

Do you understand my use-case, and do you think it makes sense?

**Comment by kescherCode** [comment]
@biva That use-case collides with users keeping individual sharing links private.

It would have to be a new feature, which the original sharing user needs to enable per share (be it a file or folder share). In the web interface, you also can't just copy the share link of another user.

**Comment by biva** [comment]
@kescherCode This is wrong: on the web interface, I can definitely share the link of another user!

**Comment by kescherCode** [comment]
> @kescherCode This is wrong: on the web interface, I can definitely share the link of another user!

I guess I didn't phrase it clear enough: You can't share it as your own link. The link of another user is shown to you seperately in the interface. They are not shown as your link, and thus the Nextcloud sync client can't currently know about them.

What if a file is shared via link by multiple people? If you were to click "copy link", Nextcloud shouldn't just take one of the existing ones without asking you beforehand. It should still be a seperate option, maybe a "share another user's link" option in the context menu.

**Comment by biva** [comment]
What do you mean they are not shown as your link? From the user perspective, it doesn't make ny difference: I can copy the link and modify its properties.

Nextcloud should be consistent: the rule on the UI should be the same as on the desktop client. Either I can copy a public link created by another both on the UI and on desktop. Or I can't. The current situation doesn't make sense. Or I misunderstood something?

**Comment by jancborchardt** [comment]
First off this is nothing specific to the desktop client, so it doesn’t really belong in the desktop repository.

Ref @rullzer for commenting on the reasoning for the architecture.

**Comment by biva** [comment]
Thanks @jancborchardt to step in. I just noted as well that the desktop app already shows if another user shared a link. I see this message: "Tom shared via link".  This is quite good for our use-case: I can go on the UI in the browser, and see the link of Tom.

It would just be easier for me to see this link in the dialog box of the destkop app.

Thanks for your support and your understanding :)

**Comment by rullzer** [comment]
So @jancborchardt is right. We can't use one link by default. There are several issues with it.

1. The original owner might not know you also send out the link
2. It might be password protected etc.

So if you really want this you'll have to coordinate with your colleagues which link to share.
Using the same link is undesireable.

**Comment by biva** [comment]
Thanks @rullzer for your feedback. But then, I don't understand your logic: why is this link available on the UI in the browser?

To answer your issues:
1. Why is it a problem if the original owner (UserA) doesn't know if I (UserB) also send out the link? UserB knows that UserA might delete the link at any time, that's it. And anyway, UserB can also delete the link at any time today 
2. How is it a problem? Either UserB knows the password, and that's OK. Or UserB doesn't know the password, and he creates a new link. But I don't understand the problem.

Also, I understand that using the same link is undesirable in your point of view. In our use-case, where we use public links extensively with a lot of partners, and these links are managed by several people in our organisation, I can assure you that it is definitely desirable: we already do it for several years and this is what we desire.

To conclude on that, I think the way the UI works today makes sense:
1. Public links should be manageable by anybody having the write access on the file itself. Indeed, if I have the write access on a file, I can delete the file itself: why wouldn't have the right to delete the link (which is a lower power than deleting the file)? So I think we shouldn't change anything on the way the UI works today.
2. In a dream world, the desktop app should offer the same possibilities than the UI. I understand that it's technically hard, and it requires time. So the desktop app has technical limitations. But I think the desktop app should not have a different logic than the UI. Or am I wrong with that?
3. That said, I would understand if you don't have the time to develop this feature. But I don't understand why this feature would not make sense.

**Comment by biva** [comment]
Hello, am I misunderstanding something about this issue? What do you think about the logic above?

**Comment by biva** [comment]
Hello @rullzer , Is there something I misunderstood? Shouldn't this issue be open again?

**Comment by biva** [comment]
Hello @rullzer , Is there something I misunderstood? Shouldn't this issue be open again?
