### ISSUE TITLE
Confusing user agent during desktop app authentication flow

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2016]
When you log in to your server, you are at some point faced with this page:
![auth user agent](https://user-images.githubusercontent.com/925062/82755978-7b46fa00-9dd7-11ea-9d01-21db8db204b7.png)

That’s downright scary. ;) Instead the regular client should simply say "Nextcloud desktop client" and the nightly one "Nextcloud desktop client nightly".

cc @rullzer @er-vin @misch7 as I’m not sure if this is so easy, or requires server adjustments as well.

**Comment by misch7** [comment]
> The "trick" is to use a custom user agent only for login flow, in desktop case it could be something like "PC-Name ($platform)", which should be specific enough to find it in the list, if needed.

Hmm, feels like kind of a "cheat" in regard what the server admins may like to see in their auth logs.
But I guess it might be okay since they still can see the related logging around the auth requests.

**Comment by jancborchardt** [comment]
> in regard what the server admins may like to see in their auth logs

This is mostly about what end users see, and that should be clean and understandable. :) If we need additional stuff for server logs that could be separate and not visible in the interface?

**Comment by misch7** [comment]
> > in regard what the server admins may like to see in their auth logs
> 
> This is mostly about what end users see, and that should be clean and understandable. :)

I know ;-)

> If we need additional stuff for server logs that could be separate and not visible in the interface?

When we modify the user-agent then this is what the server gets (logs) and is visible for the user.

**Comment by jancborchardt** [comment]
Since the Android app already does this for some time: Did we have any server admin reports about this being off? Because if not we can just go for the same approach anyway?
