### ISSUE TITLE
Client occasionally starts to sync ignored files

### ISSUE THREAD

**Issue by Temtaime** [nextcloud/desktop#202]
Seems that bug related only to ignored folders.
For example in my ignored list there are records "aa/bb/" and "aa/cc/" - it works ok and doesn't trigger sync.
But if i create many files in "aa/bb/" or delete them from this folder, it can start to upload files from "aa/cc/".
It is very annoying.

[nextcloud.zip](https://github.com/nextcloud/client/files/1772558/nextcloud.zip)
Log file and ignore list.
I paused it when saw that it started to upload tools/graphics.
The bug comes totally occasionally and can happen to any folder and can upload to my server tons of unused files.

Sure i run latest client(2.3.3 build 1) and NC 13.

**Comment by Temtaime** [comment]
> #=#=#=# Syncrun started 2018-03-04T12:21:50
> #=#=#=#=# Propagation starts 2018-03-04T12:21:54 (last step: 4265 msec, total: 4265 msec)
> ||perfontain_site|INST_REMOVE|Down|1502708056||0||4||0|0|0|||INST_NONE|
> ||misc|INST_REMOVE|Down|1519470957||0||4||0|0|0|||INST_NONE|
> ||firmware|INST_REMOVE|Down|1495916078||0||4||0|0|0|||INST_NONE|
> ||backups|INST_REMOVE|Down|1519634185||0||4||0|0|0|||INST_NONE|
> #=#=#=# Syncrun finished 2018-03-04T12:21:55 (last step: 1090 msec, total: 5356 msec)

Found that client sometimes also deletes local files when nobody touches them.
It is very frustrating.

**Comment by kprkpr** [comment]
Me too. I have a pattern "build/generated/" and nextcloud client is uploading and downloading thousands of files that I have check to be ignored..

**Comment by camilasan** [comment]
I tried it and it worked when I didn't add any slash to the pattern, so instead of "aa/bb" I added "aa", "bb" and "cc". Then even after add and deleting files from the folders they were not synced. Could you try that too?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively. Besides... there were changes made in recent releases related to ignored files.
