### ISSUE TITLE
Client freezes most of the time and takes half an hour for small files

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/desktop#2041]
### Expected behaviour
After a file change the client should start the synchronization and it should not last longer than a minute for small files like a Word document.

### Actual behaviour
After one or more files have changed the client waits a long time until it does anything. You can watch this by using `strace -p $(pidof nextcloud)`. After a while it seems to discover a lot more directories than those that have changed which takes a few minutes. Then the synchronisation of 12 files with 2.6 MB in total lasts just a few seconds. But then the client needs several minutes to write to its SQLite database which also can be watched using `strace`. You will see lots of lines like this:
```
pread64(31, "\r\0\1\0\2\1\273\0\2\336\1\274\1'\0\226\0\0\0\0\0\1\0\0\0\0\0\0\0\0\0\0"..., 1024, 96151552) = 1024
...
```
While `31` refers to
```
lrwx------ 1 user user 64 Mai 28 05:10 /proc/10564/fd/31 -> /mnt/raid5_1/Data/Cloud/._sync_f723f2b2ef65.db
```
While the process reads from that file for minutes the whole frontend remains unresponsive. The last thing it shows is the progress bar of the latest synchronisation process with "0 seconds remaining, 2.6 MB of 2.6 MB, File 12 of 12". You see it for minutes, sometimes up to half an hour.

From changing a file until it is synchronized with the server can take half an hour or more in total.

What you also can see in the output of `strace` is this line which stands there for minutes. I don't know what it means but while it stands there the application is frozen and does nothing.
```
futex(0x558ab1fc66e8, FUTEX_WAIT_PRIVATE, 3, NULL
```

### Steps to reproduce
1. Synchronize a folder with over 50000 inotify watchers.
2. Change a file, create a new one or delete one.
3. Wait.

### Extra information
On the same machine also runs an Owncloud Desktop client which synchronizes more than double the amount of directories and files. It is very fast compared to the Nextcloud Client. Here are the stats of inotify watchers
```
   INOTIFY
   WATCHER
    COUNT     PID     CMD
----------------------------------------
  106506    31111  owncloud
   51554    10564  nextcloud
     243    31022  /usr/sbin/smbd --foreground --no-process-group
     105        1  /lib/systemd/systemd --system --deserialize 21
...
```

### Client configuration
Client version:
2.6.4git

Operating system:
Ubuntu 18.04

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
There is no version number of Qt mentioned in the settings dialog.

Client package (From Nextcloud or distro) (Linux only):
http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic/main amd64 Packages

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Nextcloud version:
18.0.3

Storage backend (external storage):
Nothing

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
There is no log file because when I start nextcloud with a logfile it takes so much space that the drive is full in under 24 hours. And every restart also takes up to an hour until it starts the synchronization.

2. Web server error log:
There are no errors.

3. Server logfile: nextcloud log (data/nextcloud.log):
This file is several Megabytes in total and I don't think it has any relevance here because the server runs great.

**Comment by camilasan** [comment]
We have made a lot of changes to the sync engine in master. Could you try it:? https://download.nextcloud.com/desktop/daily/ 
(we highly recommend to set up from scratch a new test folder to run this new version)

**Comment by NicolasGoeddel** [comment]
I need to wait for the weekend because it is a production system. I don't want to switch to a daily build in the middle of the week.
