### ISSUE TITLE
Fontsize in GUI very small on UHD display and not scaling with Gnome Tweak Tool

### ISSUE THREAD

**Issue by jwich71** [nextcloud/desktop#205]
I’m using the latest Nextloud Client 2.3.3 with Fedora 27 on a HP Spectre X360 with UHD display. The fontsize of Nextcloud GUI is very small and it can’t scaled with the Gnome Tweak Tool.
Can you please implement compatibility with GNOME Tweak Tool, so the fonts of Nextcloud are scaling like all the other apps?

**Comment by StrangeNoises** [comment]
This is actually more about scaling support of the app in a GNOME desktop, where it shares issues with other QT apps, such as Dropbox and Enpass. As of current versions of the app (2.3.3) and of GNOME (3.28.1), if the app is started in an already-running desktop session, it correctly scales the UI according to the scaling factor in force at that time.

But:

If you set nextcloud-client to autostart at login, it will start up at scaling factor 100%, which makes everything look far too small where the scaling factor is eg: 200% or 300%. You can workaround this by putting an autostart delay in `~/.config/autostart/Nextcloud.desktop`, eg: `X-GNOME-Autostart-Delay=5`, so it only starts once the desktop session is established. So making that a default could be useful.

Also, if the scaling factor is then changed during the session (this happens, eg: when plugging a laptop into a monitor and wanting to switch from 300% on the 4K laptop screen to 200% on the 4K monitor), these QT apps don't react to the new scaling factor, and thus look wrong until they're restarted.

**Comment by jwich71** [comment]
This workaround doesn't work for me. Also disabling autostart of Nextcloud client and just starting it manually after login doesn't change anything. The fontsize is still very small. Is there a debugging mode for the Nextcloud client, to see more output?

**Comment by camilasan** [comment]
You can run the client with the option --logdebug.

**Comment by jwich71** [comment]
Unfortunately there's no option --logdebug
> nextcloud --logdebug
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Unrecognized option '--logdebug'
Try 'nextcloud --help' for more information

**Comment by camilasan** [comment]
Do you have any logs in ~/.config/Nextcloud?

**Comment by jwich71** [comment]
After playing around with the new scaling feature (100%/200%/300%) in Gnome 3.28 the font in Nextcloud Client was also scaled. But this is not persistent. After rebooting and autostart of Nextcloud Client, the font size is small again.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
