### ISSUE TITLE
Change Default Sync Folder on Installation or via Registry

### ISSUE THREAD

**Issue by Eimerlein** [nextcloud/desktop#2053]
Windows Client drops his files to c:\users\username\nextloud . This folder is synct to the profile server. so all netxcloud files landing on profile server for nothing.

Please move the windows sync folder to c:\users\username\appdata\local or make an install or registry option available to set the default path.

Thanks

**Comment by camilasan** [comment]
I don't understand the problem: when you add your account, you can add sync folders and pick where your files will be synced to in your computer.  See https://docs.nextcloud.com/desktop/3.0/_images/client-3.png.

If you have problems on how to use the desktop client, you can also try asking the community for help on [help.nextcloud.com](help.nextcloud.com).

I am closing this issue for now. If you don't agree with it then please re-open it and *use the issue template*.

**Comment by Eimerlein** [comment]
Hi

 

We are a company. I would like to define the directory for all users using the client in our domain. So nobody has to move it manually.

 

Thanks

 

Sebastian Eimer

 

Von: Camila <notifications@github.com> 
Gesendet: Dienstag, 9. Februar 2021 12:49
An: nextcloud/desktop <desktop@noreply.github.com>
Cc: Eimer, Sebastian <eimer@cit.fra-uas.de>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/desktop] Change Default Sync Folder on Installation or via Registry (#2053)

 

I don't understand the problem: when you add your account, you can add sync folders and pick where your files will be synced to in your computer. See https://docs.nextcloud.com/desktop/3.0/_images/client-3.png <http://sea-02.cit.frankfurt-university.de:32224/?dmVyPTEuMDAxJiY0NGVhZDA3YjQ3YzI3NjA0NT02MDIyNzZDOF8xNjEzN18xNDA1OF8xJiY5NzM2OTUxNGY3YjVkMDc9MTIzMyYmdXJsPWh0dHBzJTNBJTJGJTJGZG9jcyUyRW5leHRjbG91ZCUyRWNvbSUyRmRlc2t0b3AlMkYzJTJFMCUyRiU1RmltYWdlcyUyRmNsaWVudC0zJTJFcG5n> .

If you have problems on how to use the desktop client, you can also try asking the community for help on help.nextcloud.com.

I am closing this issue for now. If you don't agree with it then please re-open it and use the issue template.

**Comment by camilasan** [comment]
We already offer a msi installer for everyone and I believe you can achieve that by using a specific tool to roll out the installer in multiple machines at once.

And in this case consider asking help/questions on the forum at [help.nextcloud.com](help.nextcloud.com) (or, if this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/)).
