### ISSUE TITLE
Nextcloud client closes without reason (win 10)

### ISSUE THREAD

**Issue by kermit-frog** [nextcloud/desktop#2054]
### Expected behaviour
Nextcloud client should remain active

### Actual behaviour
Nextcloud client is started with system start. I can see in the task view box that nextcloud is running. Open nextcloud settings. Close nextcloud settings. 
After a while when opening the task view box i at first can see the nextcloud icon. As soon as i hover over the icon it will disappear. the task manager confirms that nextcloud is no longer running.

### Steps to reproduce
1. let nextcloud client start with system
2. open task view box (nextcloud icon is there)
3. Open nextcloud settings window
4. Close nextcloud settings window
5. open task view box again (nextcloud icon is still there)
6. hover over icon (nextcloud icon will disappear)
7. check that nextcloud task is not active in task manager

### Client configuration
Client version: 2.7.0 Windows
Operating system: Windows 10 Pro V 10.0.18363 built 18363
OS language: German
Installation path of client: C:\Program Files\Nextcloud
Nextcloud version: nextcloud-2.7.0.15515-daily-20200603-Release

**Comment by kermit-frog** [comment]
additional information: 
issue no longer occurs after moving back to stable 2.6.4.15215

**Comment by er-vin** [comment]
This could be a duplicate, @kermit-frog what did you do in the session during that "after a while"? Any Chromium based browser used?

**Comment by er-vin** [comment]
While looking at #1804 it occurred to me, could it be related to you doing things in the file manager or on the desktop? (for instance right clicking on a file or such outside of a sync'ed folder)
