### ISSUE TITLE
Does not build with QT 5.15

### ISSUE THREAD

**Issue by ecsgh** [nextcloud/desktop#2066]
### Expected behaviour
Want to build nextcloud-desktop

### Actual behaviour
Can not build nextcloud-desktop with QT 5.15
With other QT versions nextcloud-desktop does build (5.9.x and 5.12.x)

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:
2.6.4

Operating system:
openSUSE Tumbleweed

OS language:

Qt version used by client package (Linux only, see also Settings dialog):
5.15.0

Client package (From Nextcloud or distro) (Linux only):
Source from nextcloud github to build a package.

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

One of the errors in build log is:
[   95s] /home/abuild/rpmbuild/BUILD/desktop-2.6.4/src/libsync/propagateuploadv1.cpp: In member function 'virtual void OCC::PropagateUploadFileV1::doStartUpload()':
[   95s] /home/abuild/rpmbuild/BUILD/desktop-2.6.4/src/libsync/propagateuploadv1.cpp:42:25: warning: 'int qrand()' is deprecated: use QRandomGenerator instead [-Wdeprecated-declarations]
[   95s]    42 |     _transferId = qrand() ^ _item->_modtime ^ (_fileToUpload._size << 16);
[   95s]       |                         ^
[   95s] In file included from /usr/include/qt5/QtCore/qchar.h:43,
[   95s]                  from /usr/include/qt5/QtCore/qhash.h:44,
[   95s]                  from /usr/include/qt5/QtCore/QHash:1,
[   95s]                  from /home/abuild/rpmbuild/BUILD/desktop-2.6.4/src/libsync/owncloudpropagator.h:18,
[   95s]                  from /home/abuild/rpmbuild/BUILD/desktop-2.6.4/src/libsync/propagateupload.h:16,
[   95s]                  from /home/abuild/rpmbuild/BUILD/desktop-2.6.4/src/libsync/propagateuploadv1.cpp:16:
[   95s] /usr/include/qt5/QtCore/qglobal.h:1277:80: note: declared here
[   95s]  1277 | Q_CORE_EXPORT QT_DEPRECATED_VERSION_X_5_15("use QRandomGenerator instead") int qrand();

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by misch7** [comment]
Have you also tried to build the `stable-2.6` branch?

It includes fixes for Qt 5.15 that were not available with the last tagged `v2.6.4` release, however the next release (2.6.5) will include these fixes (2.6.x releases will always be tagged from the stable-2.6 branch).

Trying to compile the v2.6.4 tag failed for me too on macOS but stable-2.6 worked fine :)

**Comment by nicolasfella** [comment]
master works fine with Qt 5.15 for me

**Comment by er-vin** [comment]
Yes, master and stable-2.6 should build. I build them against 5.15 anyway. :-)
