### ISSUE TITLE
Segmentation fault when shell integration requests menu on empty file path

### ISSUE THREAD

**Issue by veddox** [nextcloud/desktop#2079]
### Description

Client crashes soon after start with a segfault. The log indicates that the shell integration (in this case the Nautilus plugin) requested menu items for an empty string file path:

```
[OCC::SocketApi::slotReadSocket 	Received SocketAPI message <-- "GET_MENU_ITEMS:" from QLocalSocket(0x7eff58018840)
[OCC::SocketListener::sendMessage 	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x7eff58018840)
```

GDB shows the segfault to originate from `socketapi.cpp`, line [802](https://github.com/nextcloud/desktop/blob/3f685fd93303d5e0338c49acd7eddb1a7bdd6963/src/gui/socketapi.cpp#L802):

```
Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
0x00005555556d500a in QExplicitlySharedDataPointer<OCC::AccountState>::data (this=0x10) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:160
160	    inline T *data() const { return d; }
(gdb) bt
#0  0x00005555556d500a in QExplicitlySharedDataPointer<OCC::AccountState>::data (this=0x10)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qshareddata.h:160
#1  0x00005555556e498e in OCC::Folder::accountState (this=0x0) at /<path>/src/gui/folder.h:104
#2  0x00005555557b77c0 in OCC::SocketApi::command_GET_MENU_ITEMS (this=0x555556259210, argument=..., listener=0x5555564041f0)
    at /<path>/src/gui/socketapi.cpp:802
```

### To Fix:

1. `SocketApi::command_GET_MENU_ITEMS()` should check for an empty string/null pointer.

2. Nautilus shell integration should make sure it doesn't send an empty string request. (I don't yet quite understand how that happens.)

### Client configuration

Nextcloud version 2.7.0git
Git revision 7cde49cb631ac8855e56bef385f6aa0235f89db9
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04 LTS, x86_64

**Comment by veddox** [comment]
Fixed with pull request #2081

**Comment by er-vin** [comment]
Isn't it fixed with #2096? I was hunting one on Windows but the backtrace here looks very similar.

**Comment by veddox** [comment]
Well, you merged a lot of commits in the last two days! :smile: 

The segfault appears to be fixed indeed. Although I now get *two* "Nextcloud" menu entries in my file browser. Not sure yet what causes that.

**Comment by er-vin** [comment]
This is odd... maybe the python part of your patch was still worth it? Looks like it pre-filters in some cases...

**Comment by veddox** [comment]
And none of the NC menu items ("Open in Browser", "Share", etc.) is clickable - in either of the two NC menus.

**Comment by veddox** [comment]
The python patch doesn't affect the double-menu thing. I'll open a new issue and close this one.

**Comment by veddox** [comment]
See #2100
