### ISSUE TITLE
Generating Nextcloud.ico error

### ISSUE THREAD

**Issue by Kaitookidoo** [nextcloud/desktop#2082]
I have problem in ./build-desktop.bat
The error is as shown below

Generating client_tr.qm
Updating 'C:/Nextcloud/client-building/desktop/build/src/gui/client_tr.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Generated 769 translation(s) (769 finished and 0 unfinished)
Generating client_uk.qm
Updating 'C:/Nextcloud/client-building/desktop/build/src/gui/client_uk.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
Generated 748 translation(s) (748 finished and 0 unfinished)
Ignored 21 untranslated source text(s)
Generating client_zh_CN.qm
Updating 'C:/Nextcloud/client-building/desktop/build/src/gui/client_zh_CN.qm'...
Generated 769 translation(s) (769 finished and 0 unfinished)
Generating client_zh_TW.qm
Updating 'C:/Nextcloud/client-building/desktop/build/src/gui/client_zh_TW.qm'...
Generated 769 translation(s) (769 finished and 0 unfinished)
Generating Nextcloud.ico
'C:\Nextcloud\client-building\desktop\src\gui\convert.exe' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]
Automatic MOC for target nextcloudcmd
Building Custom Rule C:/Nextcloud/client-building/desktop/src/cmd/CMakeLists.txt
mocs_compilation.cpp
cmd.cpp
simplesslerrorhandler.cpp
netrcparser.cpp
Generating Code...
nextcloudcmd.vcxproj -> C:\Nextcloud\client-building\desktop\build\bin\Release\nextcloudcmd.exe
"*** Build FAILED: desktop Release Win64 (single-build-desktop.bat)"

**Comment by misch7** [comment]
Since you already opened the same issue in the `client-building` repo, let's handle it there: https://github.com/nextcloud/client-building/issues/25
