### ISSUE TITLE
Wish: Retry wallet buttom on login page

### ISSUE THREAD

**Issue by MrManor** [nextcloud/desktop#2088]
### Expected behaviour
Auto login at startup - after wallet is opened

### Actual behaviour
To repeat my statement from #1292: I manage/support several system for less techsavy family and friends. I see they never manage to use the desktop syncclient - "Ohh that thing - it never works so got tired of it and just press close". When I observe them login, they often start login and leave to fetch coffie or whatever. When they return kdewallet is waiting for password - and NCSync apparently timed out waiting for keyring to be opened, and now also asking for password.
All system are KDE based and gnome-keyring is removed to avoid more than one password manager popping up and confusing users. All running (at the time of writing)

    OpenSUSE 15.1
    KDE Framework 5.55.0
    Qt 5.9.7
    nextcloud-client-2.5.3
    kwalletd5-5.55.0

I have observed that when I login myself - and I am fast enough to answer the kdewallet password prompt right after login, everything works as expected. But one typing error - another password popup stealing focus while typing - or a long passphrase - and you are doomed.

Edit: Well not completely doomed. I just tried to kill the instance prompting for password, and start a new after opening kdewallet. That worked to.

### Steps to reproduce
1. login
2. fetch coffie before opening KDEwallet

### 
I suggest that if NCSync times out waiting for the user to open his wallet, the login page should have a "Retry Wallet" buttom.

**Comment by brainchild0** [comment]
I confirm the  same issue in a GNOME environment with Keyring. If the keyring is not unlocked at the time of application initialization, which it never is due to the application starting automatically before I am able to provide the unlock password, then the application sits in a disconnected state until the process is terminated. In some but not all cases, the application presents a prompt for manual login, which is undesirable if credentials are stored in a wallet.

**Comment by camilasan** [comment]
I have noticed it myself with 3.1.2 on OpenSUUSE :/

**Comment by zokushou** [comment]
Related OpenSUSE issue: https://bugzilla.opensuse.org/show_bug.cgi?id=1182225 . I do not remember ever authorizing the desktop client to create a keyring entry anyway, deleting the keyring entry solves the issue temporarily.

**Comment by T-bond** [comment]
I proposed an alternative workaround/solution in here: https://github.com/nextcloud/desktop/issues/2573#issuecomment-779361514

**Comment by MrManor** [comment]
@T-bond thanks for reminding me on this. Actually I have not seen the mentioned behavior lately, so I assuming that the underlying problem is fixed by now. Today running 
```
OpenSUSE 15.2
KDE Frameworks 5.71.0
Qt 5.12.7
Nextcloud Desktop Klient Version 3.1.3
kwalletd5-5.71.0
```
I see that Nexcloud sits quietly in the Disconnected state, even after the wallet prompt times out. And if the user after that press retry, in the wallet app. and enters the passphrase, then everything work as expected. 

So whatever has been done - that works for me (and my users) so as the OP I'll close this issue.
