### ISSUE TITLE
new line in dir/filename raises an error

### ISSUE THREAD

**Issue by mihailstoynov** [nextcloud/desktop#2098]
### Expected behaviour
Either sync the dir/file or a more descriptive error

### Actual behaviour
a more generic (non descriptive) error

### Steps to reproduce
1. Create a dir/file with a new line. This in KDE Dolphin is easy when you paste a multiline string
2. Wait for the Nextcloud app to try to sync
3. Error

### Client configuration
Client version:

Nextcloud version 2.6.4git

Operating system:
KDE Plasma on top of Arch

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
https://www.archlinux.org/packages/community/x86_64/nextcloud-client/

Installation path of client:
/usr/bin/nextcloud

### Server configuration
Installed via the most popular ansible galaxy module. A very small server with little data.

Nextcloud version:
18.0.2

Storage backend (external storage):
filesystem

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

[_csync_merge_algorithm_visitor 	INSTRUCTION_NEW                client dir:  folder with
 new line
[OCC::SyncEngine::checkErrorBlacklisting 	Item is on blacklist:  "folder with\n new line" retries: 4 for another 2843 s
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "folder with\n new line" by OCC::PropagateIgnoreJob(0x560a9cbf4a80)
[OCC::ActivityWidget::slotItemCompleted 	Item  "folder with\n new line"  retrieved resulted in error  "Server replied \"404 Not Found\" to \"MKCOL https://x.com/remote.php/dav/files/xx/folder with%0A new line\" (skipped due to earlier error, trying again in 47 minute(s))"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Server replied \"404 Not Found\" to \"MKCOL https://x.com/remote.php/dav/files/xx/folder with%0A new line\" (skipped due to earlier error, trying again in 47 minute(s))"

2. Web server error log:
there is nothing in there

3. Server logfile: nextcloud log (data/nextcloud.log):
nothing in there

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
