### ISSUE TITLE
Digikam DB files: Error Transfering https: //*** server replied: Precondition failed  (An If-Mach header was speciefied and the ressource did not exist)

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/desktop#21]
`Digikam DB files: Error Transfering https: //{PATH} server replied: Precondition failed  (An If-Mach header was speciefied and the ressource did not exist)`

I wish to share the Digicam Database across PC's and I got this warning all the time. Because I do not understand the Error message I thoght that the Problem is an Open File. but that is not the case. Even Digicam is closed this Messages appear.

Please...
- ...Made the Error more clear
- ...add a hint for a solution
- ...If this is an Error on Nextcloud please repair it

**Comment by esprit-libre** [comment]
I have the same problem with Thunderbird archive. Any workaround ?

**Comment by AlviseNicoletti** [comment]
It happened to us with a normal zip (not an open file).

**Comment by camilasan** [comment]
@Mannshoch @AlviseNicoletti did you try the 2.3.3 version?

**Comment by Mannshoch** [comment]
For me not possible to test it now. I'm using Ubuntu 16.04 LTS and wish not to risk something with a PPA at moment. I will try before upgrade to 18.04 LTS.

**Comment by AlviseNicoletti** [comment]
@camilasan I'm sorry I don't know... but be aware that both our server and client software are up to date.

**Comment by cwittstock** [comment]
Same Problem here. I've created a large PDF-file with InDesign. After starting the export, InDesign created my pdf-file with a size of 0KB. While InDesign is exporting, the file get synced with the nextcloud server. Now the pdf-export ist ready, my pdf file is round about 30MB large, and I'm stuck in getting the error message.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
