### ISSUE TITLE
Binding loop in Window.qml

### ISSUE THREAD

**Issue by veddox** [nextcloud/desktop#2104]
### Error message

The following line shows up in the logfile:

```
[unknown        qrc:/qml/src/gui/tray/Window.qml:396:21: QML Menu: Binding loop detected for property "width"
```

### Problem diagnosis

The problem is with the use of `contentItem.childrenRect` for the width of the apps menu button, line 399:

https://github.com/nextcloud/desktop/blob/9b9504c8606d3a33a8a7970a827a0e6ec1f1a968/src/gui/tray/Window.qml#L399

When this reference is removed, the error message disappears.

However, there are various design considerations to be kept in mind when attempting a fix, see the discussion here: https://github.com/nextcloud/desktop/pull/2089

### Version

Nextcloud version 2.7.0git
Git revision afac668d9c877ff4e60df484f1d5752e22450e23
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04 LTS, x86_64

**Comment by er-vin** [comment]
I'd say this is now superseded by #2159. I'm thus closing this one.
