### ISSUE TITLE
Linux client doesn't respect GNOME font selection

### ISSUE THREAD

**Issue by eh8** [nextcloud/desktop#2115]
### Expected behaviour
The Nextcloud client uses the same font seen throughout the rest of the GNOME desktop environment.

![image](https://user-images.githubusercontent.com/22990581/85247934-6c2a8a80-b41d-11ea-94c8-24c7938e962b.png)

### Actual behaviour
Nextcloud client instead uses the default GNOME font 'Cantarell.'

![image](https://user-images.githubusercontent.com/22990581/85247916-603ec880-b41d-11ea-9945-ae9f9130ce41.png)

### Steps to reproduce
1. Install Nextcloud desktop client
2. Double click tray icon

### Client configuration
Client version: 2.6.4.git

Operating system: Arch Linux 

Qt version used by client package (Linux only, see also Settings dialog): 5.15

Client package (From Nextcloud or distro) (Linux only): distro

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

```
[OCC::Application::setupLogging         "################## Nextcloud locale:[en_US] ui_lang:[en_US] version:[2.6.4git] os:[Arch Linux]"
[OCC::Application::slotParseMessage     Running for 116957 sec
[OCC::AccessManager::createRequest      6 "PROPFIND" "https://us.cloudamo.com/remote.php/dav/files/ericcheng986@gmail.com/" has X-Request-ID "b49d4bb7-199c-4b36-80eb-0ffc155ec6d0"
[OCC::AbstractNetworkJob::start         OCC::PropfindJob created for "https://us.cloudamo.com" + "/" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished  request finished
```
Additional information omitted for privacy

**Comment by jancborchardt** [comment]
@er-vin if you point out which file this likely needs to be changed in, it could possibly be a "good first issue", what do you think? :)

**Comment by eh8** [comment]
Let me know if I can provide any additional context or debugging info!

**Comment by er-vin** [comment]
> @er-vin if you point out which file this likely needs to be changed in, it could possibly be a "good first issue", what do you think? :)

I wish I knew. ;-)

Actually this could even be something upstream, apart if we somehow overridden fonts it should be picked up for us by the Qt platform theme plugin...

**Comment by eh8** [comment]
When I first installed the client it used the correct font. After a few days it switched to Cantarell and has remained since. Disabling Cantarell via `font-manager` results in Vera Sans being used.

**Comment by vtronko** [comment]
What happens if you run it like this
`QT_QPA_PLATFORMTHEME=qt5ct nextcloud`
?

**Comment by eh8** [comment]
@vtronko solved!
