### ISSUE TITLE
Easier Customization of Desktop Client

### ISSUE THREAD

**Issue by AHeimberger** [nextcloud/desktop#2117]
### Expected behaviour
I guess there are often requests to make customization of the Nextcloud desktop client easier, additionaly to the Theme containing the Logo of the Application. This can be done, but it is realy cumbersome, because you need to modify the `NEXTCLOUD.cmake` File.

- Custom Application Name:  [Link 1](https://help.nextcloud.com/t/slight-customization/5000),  [Link 2](https://help.nextcloud.com/t/how-to-replace-the-name-nextcloud-with-my-name-in-the-desktop-client/21960)
- Custom Theme: [Link 1](https://help.nextcloud.com/t/branding-desktop-clients/5876/3), [Link 2](https://github.com/nextcloud/client_theming)

I guess it would be nice if you could make the .cmake-variables for the application modifiable as well.

```
    cmake "-G${VERSION_VSSTUDIO}" \
        "../build" \
        -Wno-dev \
        -D CMAKE_PREFIX_PATH=${DIR_QT_MSVC} \
        -D QTKEYCHAIN_LIBRARY="${DIR_QTKEYCHAIN}/lib/qt5keychain.lib" \
        -D QTKEYCHAIN_INCLUDE_DIR="${DIR_QTKEYCHAIN}/include/qt5keychain" \
        -D ZLIB_LIBRARY="${DIR_ZLIB}/lib/zlib.lib" \
        -D ZLIB_INCLUDE_DIR="${DIR_ZLIB}/include" \
        -D OPENSSL_ROOT_DIR="${DIR_OPENSSL}" \
        -D OPENSSL_INCLUDE_DIR="${DIR_OPENSSL}/include/" \
        -D OPENSSL_LIBRARIES="${DIR_OPENSSL}/lib/" \
        -D NO_SHIBBOLETH=1 \
        \
        -D APPLICATION_NAME="My Application" \
        -D APPLICATION_SHORTNAME="myapp" \
        \
        .
```

**As well as all other variables:** APPLICATION_EXECUTABLE, APPLICATION_DOMAIN, APPLICATION_VENDOR, APPLICATION_ICON_NAME, LINUX_PACKAGE_SHORTNAME, THEME_CLASS, APPLICATION_REV_DOMAIN, WIN_SETUP_BITMAP_PATH, MAC_INSTALLER_BACKGROUND_FILE, THEME_INCLUDE, APPLICATION_LICENSE, ...

With this approach it would be easier to change the application name, without patching your cmake file like approached in the links mentioned.

**Comment by rwese** [comment]
Valid points, are you aware of this Repo [client-building](https://github.com/nextcloud/client-building).

There you have a [defaults file](https://github.com/nextcloud/client-building/blob/master/defaults.inc.bat) which allows the use of environment variables.

It isn't complete and support for branding clients requires some tinkering, and updates see [PR#30](https://github.com/nextcloud/client-building/pull/30). I will also provide a PR later.

**Comment by AHeimberger** [comment]
Yes, I am aware of this repository and I feel sorry, because I really don`t like it. There are so many instructions about how to build/modify the nextcloud client. In my oppinion it does not require an additional repository with those .bat-files. People should work on a single of truth. 

- https://github.com/nextcloud/client-building
- https://github.com/nextcloud/desktop#hammer_and_wrench-how-to-compile-the-desktop-client
- https://docs.nextcloud.com/desktop/2.6/building.html 
- https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client
- https://github.com/nextcloud/client_theming

**Comment by rwese** [comment]
You are absolutely right, working with the client-building repo to build a branded client I understand where you are coming from. Yet getting from source to executable to installer, in the case of windows, is not something everybody knows, so having the NSIS-Installer somewhat ready for branding was nice.

It took quite a lot of tinkering and fixing to get it to work and still it is not a good solution, but more than ownc...d gives you. 

You still have to customize the `/oem/<branded_name>/OEM.cmake` file and also run the batch files with the proper parameters.

**Comment by AHeimberger** [comment]
> You still have to customize the `/oem/<branded_name>/OEM.cmake` file and also run the batch files with the proper parameters.

I was looking for `/oem/<branded_name>/OEM.cmake` where am I supposed to find this cmake-file?

**Comment by rwese** [comment]
You can use the `Nextcloud.cmake` file from the root directory.

The process is not so clear but what I had to do, while using the client-building repo, was:

* Create a 'oem' directory like `/oem/<brand>`
* Copy&Modify the Nextcloud.cmake > `/oem/<brand>/OEM.cmake` (filename must be this way)
* Copy&Modify `theme.qrc`
* Copy&Modify all theme files you desire, the filenames of the `*Nextcloud*` must match the ApplicationName
* Create a proper `application_name/anexia_cloudstore.VisualElementsManifest.xml`

Run a build command with the `-DOEM_THEME_DIR=$(pwd)/desktop/oem/<brand>`

yeah... all but simple, and this is not all, I am certain I forgot a bunch.
