### ISSUE TITLE
[Error] Desktop Client won't sync

### ISSUE THREAD

**Issue by rusty-genius** [nextcloud/desktop#212]
Hey guys,

i am experiencing some trouble with my nextcloud client on linux. each time when i boot up my pc and nexcloud autostarts, it can’t connect with my server. it always shows me “can’t connect to … operation cancelled”. after i delete my account and set up the same account again, it works flawlessly.

the same goes for my wifes account and for my arch laptop (i use mint on my main machine by the way)
this is the logfile:
03-11 10:52:13:699 5343 unknown: custom style sheet is disabled
03-11 10:52:13:743 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:13:744 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:13:744 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:13:778 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:13:779 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:15:199 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560ccc6b6830)
03-11 10:52:15:201 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:15:201 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version “13.0.0.14"
03-11 10:52:15:202 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Undefined” -> “Credentials Wrong"
03-11 10:52:15:203 5343 OCC::HttpCredentials::fetchFromKeychain: -------- -----> QSslCertificate(””, “”, “1B2M2Y8AsgTpgAmY7PhCfg==”, (), (), QMap(), QDateTime(Invalid), QDateTime(Invalid)) QSslKey(PrivateKey, OPAQUE, -1)
03-11 10:52:15:204 5343 OCC::AccountState::setState: AccountState state change: “Getrennt” -> "Konfigurationsfehler"
03-11 10:52:15:205 5343 OCC::FolderMan::slotAccountStateChanged: Account “tim@www.spacepirate.de” disconnected or paused, terminating or descheduling sync folders
03-11 10:52:15:273 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:15:274 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:15:274 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:15:276 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:15:277 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:16:495 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560cccb68150)
03-11 10:52:16:496 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:16:497 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version "13.0.0.14"
03-11 10:52:16:498 5343 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-11 10:52:16:499 5343 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for “https://www.spacepirate.de” + “/” "OCC::ConnectionValidator"
03-11 10:52:17:323 5343 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
03-11 10:52:17:324 5343 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
03-11 10:52:18:641 5343 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!
03-11 10:52:43:716 5343 OCC::AbstractNetworkJob::slotTimeout: virtual void OCC::AbstractNetworkJob::slotTimeout() OCC::PropfindJob(0x7f283c00cfa0) Timeout QUrl(“https://www.spacepirate.de/remote.php/webdav/”)
03-11 10:52:43:716 5343 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) “Operation canceled” QVariant(Invalid)
03-11 10:52:43:717 5343 OCC::PropfindJob::finished: PROPFIND request not successful, http result code is 0 ""
03-11 10:52:43:717 5343 unknown: QIODevice::read (QNetworkReplyHttpImpl): device not open
03-11 10:52:43:717 5343 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change: “Credentials Wrong” -> "Timeout"
03-11 10:52:43:718 5343 OCC::AccountState::setState: AccountState state change: “Konfigurationsfehler” -> "Netzwerkfehler"
03-11 10:52:43:718 5343 OCC::AccountSettings::showConnectionLabel: “Keine Verbindung zu Nextcloud auf <a href=“https://www.spacepirate.de”>https://www.spacepirate.de\nOperation canceled"
03-11 10:52:43:719 5343 OCC::FolderMan::slotAccountStateChanged: Account "tim@www.spacepirate.de” disconnected or paused, terminating or descheduling sync folders
03-11 10:52:45:714 5343 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-11 10:52:45:715 5343 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-11 10:52:45:716 5343 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-11 10:52:45:718 5343 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-11 10:52:45:719 5343 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for “https://www.spacepirate.de” + “status.php” "OCC::ConnectionValidator"
03-11 10:52:46:916 5343 OCC::CheckServerJob::finished: status.php returns: QMap((“edition”, QVariant(QString, “”))(“installed”, QVariant(bool, true))(“maintenance”, QVariant(bool, false))(“needsDbUpgrade”, QVariant(bool, false))(“productname”, QVariant(QString, “SpacePirate”))(“version”, QVariant(QString, “13.0.0.14”))(“versionstring”, QVariant(QString, “13.0.0”))) QNetworkReply::NetworkError(NoError) Reply: QNetworkReplyHttpImpl(0x560cccb2c160)
03-11 10:52:46:916 5343 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found: QUrl(“https://www.spacepirate.de/status.php”) with version “13.0.0” ( “13.0.0.14” )
03-11 10:52:46:917 5343 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl(“https://www.spacepirate.de”) has server version "13.0.0.14"
03-11 10:52:46:917 5343 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-11 10:52:46:918 5343 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for “https://www.spacepirate.de” + “/” “OCC::ConnectionValidator”

**Comment by chefschaffner** [comment]
Same here since update.
Two Server installations: Version 13.0.0 works fine, Version 13.0.1 fails.
Two Clients: Linux and Windows, both cannot log in.

**Comment by stormlord58** [comment]
Same problem overhere.
Clients on iPhone. Galaxy Tab, Ubuntu and (sorry) Windows won't connect either.

**Comment by paskalito** [comment]
I also got this just now, without actually changing anything..

just checked my logs, last nextcloud client update was last month.
the only thing i made is changin my password also already some time ago, and the chaniging on the nextlcoud desktop client was actually working well.
with davdroid it was more annoying, and finally yesterday the android nextcloud client just promted me to authenticate till eternety when i tried to activate the autoupload option. - i restarted the server and funny enough now its working. - but nexctloud client stopped... - oh maybe thats possible before i did that i apt update && apt upgraded my debian server, may that be the cause? (also have automatic sec updates anyway but in the manual update i think the server installed a new kernel)

**Comment by chefschaffner** [comment]
Just tried it again: problem seems to be solved, at least under windows and Linux. Didn't try Android until now. I didn't recognize any update, so I'm a little confused...
Thanks for your inquiry

**Comment by paskalito** [comment]
@camilasan 
i think i meanwhile also upgraded to nc13 ( dont know exactly if i did that before or after my post) - anyway its still working but i still get pretty slow login times, i just reconfigured my calendar, tried it first from gnome-calendar, then from evolution - gnome-calendat did not work at all, evolution gave me errors about requests taking too long, and since i finally did it on the website itself i experienced the slow login by myself..

@chefschaffner @rusty-genius @stormlord58  do you also use caldav/carddav ?

**Comment by camilasan** [comment]
@paskalito maybe you could post the errors here? Do you see a connection to what was described in this issue? Otherwise, please feel free to open another issue. Thanks!

**Comment by chefschaffner** [comment]
After updating to 13.0.2 same happens again. The client cannot login, not with the nextcloud-password and also not with the generated application password. Again, happens with Window- and Linux-client.

**Comment by camilasan** [comment]
These are your server logs, correct?

**Comment by paskalito** [comment]
yes

**Comment by jeremiah-s-putnam** [comment]
I have noticed that if I access it from an external IP (with a connection from my phone via hotspot) I can connect just fine and it is fast.  However, connecting to it from the LAN I do not get a connection, only though the web.  NAT problems?  I did not have this problem with 13.0.

This is the same for the phone apps: Nextcloud, Talk, and Notes.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
