### ISSUE TITLE
Nextcloud Client with Files On-Demand 

### ISSUE THREAD

**Issue by axheli** [nextcloud/desktop#2121]
Could we develop an option to allow you to save space on your device by making files online only. However, for key files, turn on Files On-Demand to keep files on your hard drive and use offline (it will sync when you are back online).

**Comment by er-vin** [comment]
I think what you're requesting is the virtual drive which is under development, thus I'm closing this one. If you think what you're requesting is very different or not covered by the virtual drive we can discuss it further of course.

**Comment by axheli** [comment]
@er-vin Hello, no im not requesting for a virtual drive im asking for the client to handle that and not have a virtual drive. Just like the onedrive application dose

**Comment by er-vin** [comment]
Still, this looks like its covering the exact same use case (limit the amount of disk space used locally, only make sure a few selected ones are always there). Maybe different name and usability but clearly very similar need.

**Comment by axheli** [comment]
Yes, it is the same consept. Hopefully the virtual drive is not the only solution for this

**Comment by HammyHavoc** [comment]
Yes, looking for something similar to OneDrive in this regard.

**Comment by axheli** [comment]
@er-vin is there a way we can try to do a similar thing to what dropbox, onedrive, google drive are doing?

**Comment by stylefieber** [comment]
Basically this would be like the WebDAV intergartion from Windows but without limitations. That would be enough for many people, I think.
