### ISSUE TITLE
Error while reading 140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac

### ISSUE THREAD

**Issue by jt196** [nextcloud/desktop#2123]
### Expected behaviour
Desktop sync behaviour

### Actual behaviour
Error while syncing up to server:

### Steps to reproduce
This is happening when I sync the desktop

### Client configuration
Client version:
2.6.4

Operating system:

OS language: Mac OS Catalina

### Server configuration
Running in Docker behind an Nginx reverse proxy on a NAS. Can post the config.php here if necessary

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: `Error while reading: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac|0|0|0||||`

2. Web server error log: nothing shows up that looks related

3. Server logfile: no errors related to this

**Comment by andreasdueren** [comment]
For anyone with a similar problem and not being able to resolve it, try switching your ethernet cable. That seems to have done the trick for me.
