### ISSUE TITLE
Any Update on the Virtual Drive Feature?

### ISSUE THREAD

**Issue by ryperx** [nextcloud/desktop#2142]
Now it is 1 1/2 years later and nothing happened.
Is there any update on this feature?

https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration/

**Comment by er-vin** [comment]
Work has been resumed on it only recently. Hopefully it'll make some progress again in the coming months. We will of course communicate about this.

Thanks for your interest.
