### ISSUE TITLE
[2.7.0-beta1] unable to open database file 

### ISSUE THREAD

**Issue by wernerflamme** [nextcloud/desktop#2154]
### Expected behaviour
I want to sync via commandline and I expect that to happen. The very same commandline works with 2.6.4, but not with 2.7.0-beta1

### Actual behaviour
The software starts by showing the X-Request-ID. OK
Several values in JSON format are displayed. OK
Output: There are x bytes available at "syncdir" (per command line). OK
Output: New sync (no sync journal exists). Hm, I sync for a long time...
Output: "Using Qt 5.9.7 SSL library OpenSSL 1.1.1g  21 Apr 2020 on openSUSE Leap 15.1". OK
Output: Error: "unable to open database file" for "/home/wflamme/Nextcloud//home/wflamme/.local/share/nextcloudcmd/._sync_df32f796e800.db"

Meh. The syncdir is /home/wflamme/Nextcloud/, the directory /home/wflamme/.local/share/nextcloudcmd has just been created by nextcloudcmd and is empty. Why does the client tell me about "/home/wflamme/Nextcloud//home/wflamme/.local/share/nextcloudcmd"? Those paths don't belong together.

### Steps to reproduce
1. Download 2.7.0-beta1
2. install about a bazillion devel-packages needed for compilation
3. cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1
4. make install
5. invoke /usr/local/bin/nextcloudcmd -u wflamme -p 'T0p-S3kr3t' ~/Nextcloud https://my.nc.host

### Client configuration
Client version:
2.7.0-beta1

Operating system:
Linux, openSUSE Leap 15.1 x86_64

OS language:
echo $LANG -> POSIX

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.9.7

Client package (From Nextcloud or distro) (Linux only):
From Nextcloud, self built 2.7.0-beta1

Installation path of client:
/usr/local

### Server configuration

Nextcloud version:
15

Storage backend (external storage):
?

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
07-03 17:16:10:697 [ info nextcloud.sync.accessmanager ]:       2 "" "https://nc.ufz.de/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "5aed9500-d37e-4186-9a92-3372e070a8f2"
07-03 17:16:10:697 [ info nextcloud.sync.networkjob ]:  OCC::JsonApiJob created for "https://nc.ufz.de" + "ocs/v1.php/cloud/capabilities" ""
07-03 17:16:12:012 [ info nextcloud.sync.networkjob.jsonapi ]:  JsonApiJob of QUrl("https://nc.ufz.de/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
07-03 17:16:12:013 [ debug default ]    [ main(int, char**)::<lambda ]: Server capabilities [...long JSON output...]
07-03 17:16:12:018 [ info nextcloud.sync.engine ]:      There are 101431689216 bytes available at "/home/wflamme/Nextcloud/"
07-03 17:16:12:018 [ info nextcloud.sync.engine ]:      New sync (no sync journal exists)
07-03 17:16:12:018 [ info nextcloud.sync.engine ]:      "Using Qt 5.9.7 SSL library OpenSSL 1.1.1g  21 Apr 2020 on openSUSE Leap 15.1"
07-03 17:16:12:019 [ warning nextcloud.sync.database.sql ]:     Error: "unable to open database file" for "/home/wflamme/Nextcloud//home/wflamme/.local/share/nextcloudcmd/._sync_df32f796e800.db"
07-03 17:16:12:019 [ warning nextcloud.sync.database.sql ]:     CANTOPEN extended errcode:  14
07-03 17:16:12:019 [ warning nextcloud.sync.database.sql ]:     CANTOPEN system errno:  2
07-03 17:16:12:019 [ warning nextcloud.sync.database ]: Error opening the db:  "unable to open database file"
07-03 17:16:12:019 [ warning nextcloud.sync.engine ]:   No way to create a sync journal!

2. Web server error log:
?

3. Server logfile: nextcloud log (data/nextcloud.log):
?

**Comment by er-vin** [comment]
We will issue a beta2 soon. Could you please test again with it? or any of the latest daily builds and report? There's been work in that area could be fixed already.

**Comment by wernerflamme** [comment]
Well, the error seems to occur on the commandline version only. When starting the GUI version, the sync is running fine.
I'm missing the "Activities" button a bit, though ;)

And when I get "There are unresolved conflicts. Click for details." I do not see any details, nothing happens. On 2.6.4, the "Activities" windows opened.

I'll try to clone via git and build the current version.

**Comment by wernerflamme** [comment]
I can't build the current version. cmake stops with
```
-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
CMake Error at src/CMakeLists.txt:7 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.12".

  The following configuration files were considered but not accepted:

    /usr/lib64/cmake/Qt5/Qt5Config.cmake, version: 5.9.7
```

I have to set up a separate host for this, which will take a while.

**Comment by wernerflamme** [comment]
Qt5 5.12 is available in openSUSE Leap 15.2, so I have to do a system upgrade before I can test the newest version. Maybe next week.

**Comment by er-vin** [comment]
Thanks for your efforts in any case, appreciated.

**Comment by wernerflamme** [comment]
Well, I did the upgrade already. After a "git pull" to be up-to-date, I did the cmake and make steps, and the command line tool works as a charm :)

So I expect beta2 to have a working path finder too.

**Comment by er-vin** [comment]
Actually I realize only now that I should have linke #2172 to this issue here. :-)

Let's close it then.
