### ISSUE TITLE
Add an option to show the Nextcloud Sync window when starting Nextcloud

### ISSUE THREAD

**Issue by vimpostor** [nextcloud/desktop#2156]
Right now I have to click on the systray icon to show the window. It would be cool if there was an option to show the window automatically when I launch Nextcloud.

**Comment by er-vin** [comment]
The current approach is "launch a second time" to show the dialog.

**Comment by magnus-gross** [comment]
If you don't want to clutter the settings window, a command line option to show the window immediately would be sufficient for me

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/desktop/issues/1977#issuecomment-892113790
