### ISSUE TITLE
AccountManager changes from http auth to webflow authentication

### ISSUE THREAD

**Issue by AHeimberger** [nextcloud/desktop#2171]
Hey Guys, I am not sure whether the implementation was thought to be like that or if it was an introduced bug. I am currently trying to use oauth with your nextcloud client. The oauth mechanism stores its credentials as `http credentials`. When the application is restarted `accountmanager.cpp` changes the mechanism from `http` to `webflow`. This was introduced with commit 045bba0.

- I know this is not the forum, but what are your intentions for authentication?
- Why are you intenting to work on your own WebFlow when there is [Qt Network Authorization](https://doc.qt.io/qt-5/qtnetworkauth-index.html)? Is there any official documentation of WebFlow?
- What kinds of authentication methods are known to work (Basic, OAuth, Shibboleth, LoginFlowV2) except WebViewFlow?

**Comment by er-vin** [comment]
I'm not sure what to do with that one apart from closing it, it's not really an issue is it?

Besides those are mostly questions for the server people, in some way we merely implement what's supported there. I'd say you should try asking on the forums.

Of course if I misunderstood and there's a more precise issue I'll gladly tag as such and reopen. :-)

**Comment by AHeimberger** [comment]
Well I am not sure if it is an issue or not, because I do not know your future plans. Provide multiple authentication methods or not. Eventually all those different authentication methods are for you just some old artifacts from OwnCloud. However, I try to explain it in more detail. The client contains code to check which authentication method should be taken. 

First the client will send a PROPFIND request to the server. If the response contains BEARER the client will try to connect via oAuth `libsync/networkjobs.cpp -> authChallenge.contains("bearer ")`. If BEARER is not within the response it will take something different, which depends upon the version of the server software - method `checkAllDone()`. Depending upon some Logic in order of `LoginFlowV2 > WebViewFlow > OAuth > Shib > Basic` it will select another authentication method. That`s all okay for me.

**What's the point now. oAuth credentials are stored as http-credentials. So if those credentials are stored, they will be suppressed when the application is restarted. `accountmanager.cpp` kills http credentials in favour of webflow, due to the migration process.**

What I just have seen after inspecting this is that the code for `httpcredentials.cpp` does not work at the moment. Some threading issues with job and parent.

**Comment by er-vin** [comment]
I admittedly don't know that area very well. I'll reopen because indeed I find fishy that we kill some credentials... maybe the oauth one should be stored differently to not be confused with http ones?

Maybe @misch7 got an opinion about this as well?

**Comment by jospoortvliet** [comment]
My understanding is that loginflow is our only supported auth mechanism as it supports everything the server supports, including complex 2FA methods and so on - maintaining everything double on the client is nearly impossible and a waste of time... But how it's technically done is something @rullzer knows most about, I think.
