### ISSUE TITLE
Created a subfolder in Fedora client but not showing up in Windows 10 client

### ISSUE THREAD

**Issue by Bobo-amg** [nextcloud/desktop#2180]
Running latest server/clients. Noticed there have been others complaining of similar issues. Not sure if this is the same, but it is very annoying.

**Comment by er-vin** [comment]
Did the folder created from the Fedora client end up on the server? (do you see it from the web gui)

If not, logs from the Fedora client will need to be provided to figure out what's going on.
If they are on the server, then logs from the Windows client will need to be provided to get a better idea of the problem.

**Comment by Bobo-amg** [comment]
Yes, the folder ended up on the server. Can also be seen in the Android client.

Where can I find the Windows client logs?

Thanks

**Comment by er-vin** [comment]
A good start would be those: https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files
