### ISSUE TITLE
Cannot verify signatures of tagged commits for v.2.6.5 and v2.7.0-beta2

### ISSUE THREAD

**Issue by yan12125** [nextcloud/desktop#2185]
### Expected behaviour

There is a way to verify authenticity of nextcloud desktop sources, so that distribution packagers can create reliable packages.

### Actual behaviour

There are no gpg-signed source tarballs (#1510), so I check signatures of git commits to verify authenticity. It worked well for all recent releases. However, in version 2.6.5, the tagged commit (adada8b2eecd65d7a587b6abe0ae2aabca9a0b75) is signed by nextcloud-bot, and its gpg public key is not available. From https://github.com/nextcloud-bot.gpg,

> Note: The keys with the following IDs couldn't be exported and need to be reuploaded 130DAB86D3FB356C

And the public key is not available on Ubuntu keyserver, either (https://keyserver.ubuntu.com/pks/lookup?search=0x8B5274AEE6EC9C06B0DDAA96130DAB86D3FB356C&fingerprint=on&op=index).

Note that for Arch Linux packages, verifying commits is preferred as tags can be force-updated, and thus resultant packages are not reproducible.

### Steps to reproduce
1. Clone this repo
2. Try to verify the commit for v2.6.5
```
$ git verify-commit adada8b2eecd65d7a587b6abe0ae2aabca9a0b75
gpg: Signature made 西元2020年07月10日 (週五) 07時50分49秒
gpg:                using RSA key 8B5274AEE6EC9C06B0DDAA96130DAB86D3FB356C
gpg: Can't check signature: No public key
```
3. Try to fetch the public key
```
$ gpg --recv-keys 8B5274AEE6EC9C06B0DDAA96130DAB86D3FB356C
gpg: keyserver receive failed: No data
```

The results are similar for the tagged commit for 2.7.0-beta2 (501380a0047f3a5bc29b3a2ce5b3c07db5760a8a).

### Client configuration
Client version: 2.6.5

Operating system: Arch Linux

OS language: en_US.UTF-8

Qt version used by client package (Linux only, see also Settings dialog): N/A build issue

Client package (From Nextcloud or distro) (Linux only): distro. I'm updating the nextcloud-client package for Arch Linux and get blocked.

Installation path of client: N/A build issue

### Server configuration
N/A client issue

### Logs

N/A build issue

**Comment by J0WI** [comment]
The same key id showed up in https://github.com/docker-library/official-images/pull/8592#issuecomment-678399957 @nextcloud/security

**Comment by rullzer** [comment]
Mmmm I think the issue here is slightly different. You should not check the signature of the commit but the signature of the tag.
However. I'll see if we can also sign the tarballs.

**Comment by er-vin** [comment]
Note that we fixed the procedure we use so the tags v2.7.0-beta3 and following should use a publicly available key from the developer who tagged.

**Comment by yan12125** [comment]
Thank you both. I will switch to verfying tags in the next update for Arch Linux. Signed tarballs will be an even better option, of course.

**Comment by yan12125** [comment]
> I will switch to verfying tags in the next update for Arch Linux.

Oops forgot this. It has been done some time ago in https://github.com/archlinux/svntogit-community/commit/55c65ce592c91cbb90e1829ffee08a7b35ac5e67. Closing as there seems nothing to do at the Nextcloud side.
