### ISSUE TITLE
desktop 2.7beta2 "oversize folders"

### ISSUE THREAD

**Issue by r2evans** [nextcloud/desktop#2186]
### Expected behaviour

1. Preserve previously identified large folders overrides (folders over 500MB configured limit), don't "re-discover" them.

2. ~~While I am actively changing synced folders (due to number 1 above), keep the list "stable" without flashing and (more importantly) losing my changes while I'm making changes.~~ (migrated to #2193)

### Actual behaviour

1. After I upgraded, all of my previously identified overrides were unchecked. And because of number 2, I had to re-check multiple folders repeatedly; I finally selected a few and then hit "accept", which was **wrong** for me to do, because (1) I lost indication of the folders it thought were too big; and (2) every folder that I had not yet selected was then **purged** locally. Granted, nothing was lost except my time having to figure out what was set where.

    And for some reason, all of the folders I re-selected are being completely re-synced (it was fine just 5 minutes prior on version 2.6.5). Not fun for a 14GB folder. (That was stupid.)

2. ~~Flashes while it repeatedly updated its state. I don't know if it was partial discovery updating through multiple calls or whatever. The flashing was mildly annoying, the loss of my changes was significant. I don't care if this "shouldn't happen once it gets its state" ... but if that's the case, then you need to warn people "don't touch the app for at least 10 minutes while it rediscovers its place in the world".~~ (migrated to #2193)

### Client configuration
Client version: 2.7.0 beta 2

Operating system: win10_64

OS language: english

Installation path of client: `c:\Program Files\Nextcloud`

### Logs

1. Client logfile: **UNABLE**. Tried `--logwindow`, it did nothing, no window appeared. Tried `--logfile somefile.txt`, it kept failing, saying couldn't create file (I did it as administrator, too). I try `--logwindow` again and it complained that it couldn't create `somefile.txt` (but I did not say somefile ... so it carried the error from `--logfile` forward). Completely restarted nextcloud, and the logwindow came up but the log started from "now", so useless.

**Comment by er-vin** [comment]
This smells like a problem with the change of path of the journal db which contains those overrides. @DominiqueFuchs @misch7 you both worked on this I think, any ideas?

**Comment by DominiqueFuchs** [comment]
Firstly: Thanks @r2evans for testing the beta software and reporting in with this issue! 

@er-vin Good point, I remember that part.. I'll look into that shortly. Without having investigated yet, I think I didn't realize that kind of persistent settings is stored there at that time. Upgrading that should be relatively simple.

However this would only account for issue nr. 1, no clue about the flickering rn, has to be investigated too.

**Comment by r2evans** [comment]
It sounds like downgrading from the beta back to 2.6 would be similarly problematic, if the path of the journal db has changed. Is the old journal db hanging around unused now?

**Comment by er-vin** [comment]
> no clue about the flickering rn, has to be investigated too.

Well, that one likely should be reported as a different issue anyway. It shows up in other situations it's kind of unrelated. It's "just" that the model we currently use is rather dumb and reloads on every change. Would need a fairly comprehensive rework.

**Comment by r2evans** [comment]
@er-vin second-half of the issue migrated to #2193, thanks.
