### ISSUE TITLE
Desktop client with segementation fault in Fedora

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/desktop#219]
I installed the current Fedora 27 for an 32-bit machine with PAE support and installed the nextcloud desktop client from the repositories. I am unable to start the client. When launching the nextcloud client from the command line, I only obtain a segementation fault ("Speicherschutzfehler"). However, if I append the `--help` option the correct help message is shown.

Yours, 
Peter

**Comment by camilasan** [comment]
Could you provide the full error stack? You can get it by running the client from the terminal.

**Comment by DominiqueFuchs** [comment]
Due to lack of information but existing relation to more recent segfault issues (continue [on #441](https://github.com/nextcloud/desktop/issues/441) instead if you're experiencing the same) I'll close this.
