### ISSUE TITLE
Win Client 2.6.5: vcruntime140_1.dll not installed, when explorer integration not chosen

### ISSUE THREAD

**Issue by Sponkdamonk** [nextcloud/desktop#2190]
### Expected behaviour
Client should start 

### Actual behaviour
 error message appears, when client is startet "vcruntime140_1.dll is missing"

### Steps to reproduce
1. install client 2.6.5 without option "explorer integration"
2. start client

Client works as expected, when explorer integration is installed.

### Client configuration
Client version: 2.6.5
Operating system: Win 10

**Comment by Patta** [comment]
i can confirm this issue.

**Comment by marconetzlande** [comment]
Workaround: Install with "explorer integration" and uninstall it afterwards. NC still remains functional.
"vcruntime140_1.dll" ist part of  "VCredist_x64.exe". You can see that it installs VCredist_x64.exe when "explorer integration" is checked. VCredist_x64 is not removed when you remove "explorer integration".

**Comment by tjlanza** [comment]
I can confirm this issue as well.

Alternative workaround is to install the VC redistributables directly: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Meth0d007** [comment]
I have installed VC redist 2015 and am still getting the vcruntime140 Error. 
So that workaround does not work around anything for me.

Only thing that works for me is to enable explorer integration.

**Comment by DominiqueFuchs** [comment]
@misch7 Any ideas about this? Is the client-building repo used without further mods for the official builds?

**Comment by marconetzlande** [comment]
This is just a missed dependency new on the main application. If you had the vcredist installed once, you will never notice.

Maybe this three lines have to be moved to the installer main section so vcredist is installed every time.
https://github.com/nextcloud/desktop/blob/84b7ed04e6b95de6050f5d6757b0d4385b297abb/cmake/modules/NSIS.template.in#L479-L481

Maybe to line 383.
https://github.com/nextcloud/desktop/blob/84b7ed04e6b95de6050f5d6757b0d4385b297abb/cmake/modules/NSIS.template.in#L382-L384
