### ISSUE TITLE
2.6.5 client shows incorrect version

### ISSUE THREAD

**Issue by FuturePilot** [nextcloud/desktop#2192]
I have the latest desktop client 2.6.5 installed via the Ubuntu PPA. However in the "About" section it says it is 2.6.4. I'm not sure if this is actually 2.6.4 or 2.6.5. The version in the package name is 2.6.5. And the link under About directs to the documentation for 2.6.5.

![Screenshot_20200712_135449-1](https://user-images.githubusercontent.com/4391536/87253470-83bbc880-c449-11ea-9c6f-ea9c77414a1c.png)

```
❯ apt-cache policy nextcloud-desktop
nextcloud-desktop:
  Installed: 2.6.5-20200712.091457.adada8b2e-1.0~focal1
  Candidate: 2.6.5-20200712.091457.adada8b2e-1.0~focal1
  Version table:
 *** 2.6.5-20200712.091457.adada8b2e-1.0~focal1 500
        500 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.2-1build1 500
        500 http://mirror.us.leaseweb.net/ubuntu focal/universe amd64 Packages
```

### Expected behaviour
Version under "About" should be the correct version

### Actual behaviour
Version under "About" does not match package version

### Steps to reproduce
1. Install the latest package from the Ubuntu PPA
2. Start the client
3. Navigate to Settings > About

### Client configuration
Client version: 2.6.5?

Operating system: Kubuntu 20.04

OS language: en_US

Qt version used by client package (Linux only, see also Settings dialog): 5.12.8? Settings doesn't show this information

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by thepatcher** [comment]
I have the same issue - Ubuntu 20.04.

**Comment by er-vin** [comment]
@ivaradi any idea what happened?

**Comment by thepatcher** [comment]
And was it on purpose that different packages are installed now? e.g. nextcloud-client is not installed anymore, instead some nextcould-desktop-* packages are installed.

**Comment by PriceChild** [comment]
Looks like it might be the packaging of the library, not the client itself:
```
$ apt-cache policy libnextcloudsync0
libnextcloudsync0:
  Installed: 2.6.5-20200712.091457.adada8b2e-1.0~focal1
  Candidate: 2.6.5-20200712.091457.adada8b2e-1.0~focal1
  Version table:
 *** 2.6.5-20200712.091457.adada8b2e-1.0~focal1 500
        400 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.2-1build1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
$ dpkg -L libnextcloudsync0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnextcloudsync.so.2.6.4
/usr/lib/x86_64-linux-gnu/nextcloud
/usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.2.6.4
/usr/share
/usr/share/doc
/usr/share/doc/libnextcloudsync0
/usr/share/doc/libnextcloudsync0/changelog.Debian.gz
/usr/share/doc/libnextcloudsync0/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libnextcloudsync0
/usr/lib/x86_64-linux-gnu/libnextcloudsync.so.0
/usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.0
```

**Comment by ivaradi** [comment]
There is a patch which "sanitizes" the CMake files, which I took from the official Debian packaging setup. This sanitization involves removing the `VERSION.cmake` file and adding its contents to `CMakeLists.txt`. The patch obviously contains the version number and thus it clashes with `VERSION.cmake` if the version differs. 

I first "solved" this problem by removing the removal of this file from the patch, but in the "adding" part the old version, 2.6.4 remained, which caused these issues with the library and displayed versions. I have fixed this and rebuilt the packages, so an update should solve these problems.

The package naming was also changed to be the same as the official Debian package names, because people had problems updating from that version to the PPA. The old package names remained as transitional packages that can safely be removed.

**Comment by FuturePilot** [comment]
Yep. The latest updated fixed it. About is now showing 2.6.5.

```
Nextcloud version 2.6.5-20200713.144448.adada8b2e-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04 LTS, x86_64
```

```
dpkg -L libnextcloudsync0
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnextcloudsync.so.2.6.5
/usr/lib/x86_64-linux-gnu/nextcloud
/usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.2.6.5
/usr/share
/usr/share/doc
/usr/share/doc/libnextcloudsync0
/usr/share/doc/libnextcloudsync0/changelog.Debian.gz
/usr/share/doc/libnextcloudsync0/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libnextcloudsync0
/usr/lib/x86_64-linux-gnu/libnextcloudsync.so.0
/usr/lib/x86_64-linux-gnu/nextcloud/libocsync.so.0
```
