### ISSUE TITLE
Unresolved symbol when building on Ubuntu 19.10

### ISSUE THREAD

**Issue by muisit** [nextcloud/desktop#2194]
I'm trying to implement a feature through a PR (masking the WebDAV command using an HTTP header, so that only GET/POST requests are used and no DELETE/PUT/MOVE, etc.). 
I thought I'd start with building the nextcloud-desktop client on Ubuntu, but it balks right there already. I followed the README and the system requirements and that was almost fine. I think I had to further explicitely install qt5quick-5-dev or something. Sadly, the build bailed on me due to missing libraries anyway.

I then installed the build-dependencies for Ubuntu for Nextcloud-Desktop (apt build-dep nextcloud-desktop) and that resulted in a succesful build. Unfortunately the binary crashes with a 'undefined symbol: _ZN3OCC16EncryptFolderJob8finishedEi' error

Some quick searching revealed this symbol to reside in libocsync.so, to which the binary is properly linked as far as ldd is concerned. So although I know a fair bit of compiler/linker stuff, I am stuck here. It seems like some other library prevents libocsync.so from loading, causing the unresolved symbol. That could be because the nextcloud desktop client is also installed system-wide and running actively. That I cannot combine that with a basic development build is worrying.

I tried building the latest version on a fresh Ubuntu 18.10 virtual machine with no nextcloud-client installed. However, that bails on a Qt5 version mismatch. I was. however, able to actually build the original debian package from source on that machine, so I have some success, but not on the origin/master branch unfortunately.

So, before I venture on a complicated path that does not fit well with the actual back-end development, I was wondering if you might have some suggestions on how to properly set-up a development environment for nextcloud-desktop that go slightly further than the minimalist (and incomplete) suggestions from the readme. As I mentioned: if you follow those, your build fails early on due to missing libraries.

**Comment by er-vin** [comment]
Well that missing symbol tells me your executable is somehow picking the wrong lib. I see our README propose the install step, it is interesting mainly if you want to develop on the shell integration bits, if not you could run straight from the build directory (it's what I do most of the time) and then it should pick the libraries from the build directory as well.

**Comment by camilasan** [comment]
Correctly setting $LD_LIBRARY_PATH fixed this issue for me. You could do that only in the terminal where you are running the client or in your IDE.
