### ISSUE TITLE
Client fails to detect a creation date change

### ISSUE THREAD

**Issue by Limezy** [nextcloud/desktop#2196]
### Expected behaviour
When a file's creation date is changed, client should detect it and sync the change to the server

### Actual behaviour
Client doesn't detect anything and says everything is synced

### Steps to reproduce
1. Randomly chose a synced file
2. Change its creation date (I'm using A Better Finder Attributes 6)
3. Force sync the client
4. Check if anything happens

### Client configuration
Client version: 2.6.4

Operating system: OSX 10.14.4 (also checked with OSX 10.11.6)

OS language: English

### Logs
Didn't find anything special

### Why that issue matters ?
That issue seems important to me because Nexctloud heavily relies on creation date for sorting files / pictures, especially in the mobile app. My pictures are completely messed up because I use a RAW converter. I loose the "real" creation date when I export my pics to JPEG for instance.

**Comment by camilasan** [comment]
I wonder if this could have anything to do with #2176.

**Comment by camilasan** [comment]
> ### Logs
> 
> Didn't find anything special

Still, it might help.
