### ISSUE TITLE
Selective sync: Client does not sync newly selected folders

### ISSUE THREAD

**Issue by phiL0co** [nextcloud/desktop#220]
I'm using version 2.3.3-1 of the client on Arch Linux and I use selective sync.
The client synced the inital folder I activated.
When I later marked another folder to sync (in the selective sync view), the synchronization didn't start. When I closed the client window and reopened it, the selection of the new folder was gone again.

Adding a new folder in the file system in the Nextcloud-folder added the folder in the client and started the sync process. Here the function is as intended.

But I'm at the moment unable to sync an existing folder onto my hard disk. Nothing happens when I select a folder in the selective sync view.

Please tell me if you need additional information.

Thx a lot in advance.

Best regards

Philipp

**Comment by camilasan** [comment]
Sorry for the late reply. Do you get any errors? Is there anything in the logs (~/.config/Nextcloud)?

**Comment by phiL0co** [comment]
Hallo!
The folder or file ~/.config/Nextcloud doesn't exist.
In the Client UI all the recent changes on the server show up in the "Server activity" tab, but in the "sync protocol" tab nothing is synced when I add a new folder.
In the tab "not synced" nothing shows up either.

I'm running the client in Arch Linux. If you need further specific information, let me know!

**Comment by phiL0co** [comment]
I've succeeded to save the log.

During logging I tried to add the folder "Backgroundstories". Again nothing changed.
Perhaps the output is useful for you:

[180416_nextcloud.log](https://github.com/nextcloud/client/files/1916990/180416_nextcloud.log)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
