### ISSUE TITLE
Nautilus Nextcloud syncstate error

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/desktop#2203]
### Expected behaviour
No errors in syslog

### Actual behaviour
syslog shows errors related to the nautilus syncstate extension syncstate-Nextcloud.py.
Throws UnicodeDecodeErrors

### Client configuration
Client version: Version 2.6.5 (Ubuntu)

Operating system: Ubuntu 20.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 
```
>>> qmake -v
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```

Client package (From Nextcloud or distro) (Linux only): Installed from PPA ppa:nextcloud-devs/client

Installation path of client:

### Logs
```
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]: Traceback (most recent call last):
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 230, in get_file_items
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]:     return self.ask_for_menu_items(files)
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 237, in ask_for_menu_items
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]:     socketConnect.sendCommand(u'GET_MENU_ITEMS:{}\n'.format(filesstring))
Jul 15 00:08:21 hoth org.gnome.Nautilus[100096]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 103: ordinal not in range(128)
Jul 15 00:08:24 hoth gnome-shell[2446]: JS ERROR: TypeError: windowActor is null#012_addWindowEffect@resource:///org/gnome/shell/ui/closeDialog.js:90:28#012vfunc_s>
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]: Traceback (most recent call last):
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 230, in get_file_items
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]:     return self.ask_for_menu_items(files)
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 237, in ask_for_menu_items
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]:     socketConnect.sendCommand(u'GET_MENU_ITEMS:{}\n'.format(filesstring))
Jul 15 00:08:24 hoth org.gnome.Nautilus[100096]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 103: ordinal not in range(128)
```

**Comment by q-wertz** [comment]
I switched from nextcloud-client-nautilus to nautilus-nextcloud as `apt show nextcloud-client-nautilus` returns
```
Package: nextcloud-client-nautilus
Version: 2.6.5-20200713.144448.adada8b2e-1.0~focal1
Priority: optional
Section: oldlibs
Source: nextcloud-desktop
Maintainer: ownCloud for Debian maintainers <pkg-owncloud-maintainers@lists.alioth.debian.org>
Installed-Size: 36,9 kB
Depends: nautilus-nextcloud (= 2.6.5-20200713.144448.adada8b2e-1.0~focal1)
Download-Size: 20,7 kB
APT-Sources: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal/main amd64 Packages
Description: Nextcloud integration for Nautilus (transitional package)
 This is a transitional package for compatibility with the old Nextcloud
 client PPA packages names. It can be safely deleted.
```
Now the logged errors have vanished.

But in the manual on https://docs.nextcloud.com/desktop/2.6/navigating.html it still says one should install `Nextcloud-client-nautilus` which should be changed if the package is obsolete...

**Comment by er-vin** [comment]
@ivaradi opinions there?

**Comment by ivaradi** [comment]
As to the errors, I don't think it has anything to do with the package names. `nextcloud-client-nautilus` simply depends on on `nautilus-nextcloud`, i.e. the files of the extension are in the latter package anyway. I think this error can occur with file names containing accented characters, so @q-wertz, could you double check with such file names? 

Regarding the documentation, I would think that the `Nextcloud-client-nautilus` "plugin" text refers to some general concept since it talks about Linux not Ubuntu or Debian. Other distributions might have a different name and in case of Ubuntu/Debian the name starts with a lowercase `n` anyway. So I think the documentation should be reworded somehow, such as "(For example, Ubuntu and Debian users must install the `nautilus-nextcloud` package. Other distributions may vary.)" But, of course, other distributions could be listed as well.

**Comment by q-wertz** [comment]
Thanks for the help.

***

> As to the errors, I don't think it has anything to do with the package names. `nextcloud-client-nautilus` simply depends on on `nautilus-nextcloud`, i.e. the files of the extension are in the latter package anyway. I think this error can occur with file names containing accented characters, so @q-wertz, could you double check with such file names?

Ok. I was wrong. Errors are still there but slightly different and occurs only rarely. Problem occurs still in the ask_for_menu_items` function but this time it is a timeout.
```
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]: Traceback (most recent call last):
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 232, in get_file_items
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:     return self.ask_for_menu_items(files)
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 249, in ask_for_menu_items
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:     if not socketConnect.read_socket_data_with_timeout(timeout - dt):
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:   File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 120, in read_socket_data_with_timeout
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]:     self._sock.settimeout(timeout)
Jul 20 15:03:32 hoth org.gnome.Nautilus[54311]: OSError: [Errno 9] Bad file descriptor
```
I can try to check the file names. Is there an easy command to find violating ones, as I have two instances connected and there are quite a lot of files? (The client activity does not show any errors)
On the other hand side I can live with 8 error lines in 12 hours (may not even be a problem of the client but of nautilus).

***

> Regarding the documentation, I would think that the `Nextcloud-client-nautilus` "plugin" text refers to some general concept since it talks about Linux not Ubuntu or Debian. Other distributions might have a different name and in case of Ubuntu/Debian the name starts with a lowercase `n` anyway. So I think the documentation should be reworded somehow, such as "(For example, Ubuntu and Debian users must install the `nautilus-nextcloud` package. Other distributions may vary.)" But, of course, other distributions could be listed as well.

Might be a good idea to clarify the documentation (as far as I understand it, the `nextcloud-client-nautilus` is depreciated in general and not only Ubuntu).

**Comment by q-wertz** [comment]
1. No more `UnicodeDecodeError`s in my log
2. In https://docs.nextcloud.com/desktop/3.1/navigating.html#sharing-from-your-desktop it still says one should install the `nextcloud-client-nautilus` package instead of `nautilus-nextcloud`. This should still be fixed in the documentation (in my opinion)

**Comment by q-wertz** [comment]
Made an Issue in the documentation repo.

**Comment by q-wertz** [comment]
Ok documentation of the desktop client lives in this repo

**Comment by q-wertz** [comment]
no more details needed
