### ISSUE TITLE
tray icon doesn't show "paused"

### ISSUE THREAD

**Issue by r2evans** [nextcloud/desktop#2206]
### Expected behaviour

When I select "Pause sync for all", the icons used to (and should still) show "pause".

### Actual behaviour

Icons show green-check, as if all or any of the account are still syncing.

![image](https://user-images.githubusercontent.com/5815808/87703903-612ef580-c750-11ea-865f-565a1d9a927a.png)

### Client configuration
Client version: 2.7beta3

Operating system: win10

OS language: english

Installation path of client: `c:\Program Files\Nextcloud`

**Comment by DominiqueFuchs** [comment]
Thanks for testing and opening this issue!

You are right, for now the dropdown account indicator only implements the connected/disconnected state (it's a TODO). The systray icon however should change. I'll try to look into that shortly.

**Comment by DominiqueFuchs** [comment]
I created a PR that fixes both of your issue reports. "Fixing" b/c I separated the part corresponding the account dropdown indicator icons into #2210
