### ISSUE TITLE
Put log files somewhere else

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [nextcloud/desktop#221]
The client currently saves log files in the root directory, which clutters it up.

I propose that the log files should be stored in an alternative location (such as an AppData folder) to keep the synced folder clean.

**Comment by k1l1** [comment]
I am working on it ;)

**Comment by camilasan** [comment]
@k1l1 If you need any help, we now have the irc channel #nextcloud-client.

**Comment by juliushaertl** [comment]
Fixed with #253
