### ISSUE TITLE
New main dialog does not show in 2.7.0 installed via Ubuntu beta PPA

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2212]
I’m testing 2.7.0 via the beta PPA at https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client-beta (on Ubuntu 20.04 with GNOME) and the new main dialog doesn’t show at all, on click of the tray icon nothing happens. Neither on clicking "Open main dialog" of the right-click menu.

I did do a `sudo apt install nextcloud-desktop` instead of nextcloud-client as that was the one with 2.7.0 versions available.

Can confirm that when using the AppImage, everything works.

@misch7 advised that this is very likely caused by missing QML dependencies in the package. @ivaradi any idea?

Everything else seems to work fine, syncing and all. (The biggest issue is that without the main dialog it is not possible to add a second account)
Let me know if I can help debug somehow. When running nextcloud via the terminal there were no relevant messages – only the first one which I am not sure is related (as it is also shown for the AppImage)?
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by misch7** [comment]
Thanks for filing the report :)

> 
> @misch7 advised that this is very likely caused by missing QML dependencies in the package. @ivaradi any idea?
> 

Correct, I suspect this likely to be the cause. For the AppImage build we addressed it by supplying the `-qmldir` option to the Qt Deployment Tool, providing the `src/gui` folder as an absolute path:
https://github.com/nextcloud/desktop/blob/7f7dd6bc766d01247afca44b29d8a9552559e4b5/admin/linux/build-appimage.sh#L95

I don't know enough about the PPA packing process and where the source scripts for it could be found. How would we do this / could help you to fix it @ivaradi ? :)

**Comment by ivaradi** [comment]
@jancborchardt, @misch7 one of the issues was that some QML module packages were indeed missing from the dependencies. I have rebuilt the packages with the dependencies added, so now this issue should be resolved.

When I first select "Open main dialog", it appears and has the right content seemingly. However, if the window disappears and I select the "Open main dialog" menu item again, it does not appear. Sometimes something appears for a moment, but then goes away. I am not sure if this could be a packaging problem or a bug in the software.

**Comment by jancborchardt** [comment]
Ah thanks a lot @ivaradi, the issue is indeed resolved! :)

> When I first select "Open main dialog", it appears and has the right content seemingly. However, if the window disappears and I select the "Open main dialog" menu item again, it does not appear.

I can’t reproduce that issue though. @misch7 can you?


----

@ivaradi I just opened another issue I found also with the Ubuntu PPA: https://github.com/nextcloud/desktop/issues/2217 :) otherwise seems all super nice!

**Comment by jancborchardt** [comment]
Also btw @ivaradi on our Nextcloud instance we have a "Desktop team" Talk channel we use to coordinate. I can add you there with a guest account if you like, using the email address from your commits?

**Comment by ivaradi** [comment]
@jancborchardt , ok, why not?
