### ISSUE TITLE
Nextcloud desktop client under linux does shows empty dialog on second opening of folder dialog

### ISSUE THREAD

**Issue by ShamimIslam** [nextcloud/desktop#2216]
### Expected behaviour
Opening NextCloud on linux after start a second time shows the NextCloud folder dialog window

### Actual behaviour
Opening NextCloud on linux after start a second time shows a blank Nextcloud window with no folder dialog contents

### Steps to reproduce
1. Start NextCloud under linux
2. Close main dialog (or set to open minimized in systray)
3. Double click icon in systray or start desktop app from command line or menu
4. Dialog opens
5. Close dialog
6. Double click icon in systray or start desktop app from command line or menu
7. Blank window shows showing NextCloud frame but no content - window is empty

Quitting nextcloud and starting again, restores the window the first time the dialog is seen and again, fails the second time.

### Client configuration
Client version:
Has been occurring for the last 2 years
Currently tested version: 2.6.4
nextcloud-client-2.6.4-4.fc31.x86_64

Operating system:
Fedora 31

OS language:
Engligh

Qt version used by client package (Linux only, see also Settings dialog):
qt-4.8.7-50.fc31.x86_64

Client package (From Nextcloud or distro) (Linux only):
nextcloud-client-2.6.4-4.fc31.x86_64

Installation path of client:
/usr

### Server configuration

Nextcloud version:
17 - has been occurring since long before 17

Storage backend (external storage):
simple file based storage

### Logs
I'm not sure what errors I should be seeing here. The interaction between are not at odds. The rendering of the window is failing.

**Comment by er-vin** [comment]
Not sure we can do much about that one, it looks like some platform integration issue downstream. There's something which strikes me as odd though, are you sure about the Qt version reported? I mean "qt-4.8.7" is ancient, I'd expect lots of things to not work properly on a recent distro with such a Qt (including gui stuff).
