### ISSUE TITLE
Merge notification, activities, uploads & errors

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#222]
Here’s the mockup of the activity stream merged with notifications as we talked about for the Android app as well, and @camilasan as we discussed too.

Spec (copied from https://github.com/nextcloud/android/issues/1271#issuecomment-322036536)
> **Activity**: Merged Activity & notifications etc, much like the unified timeline in the sidebar of files https://github.com/nextcloud/server/issues/658. Most of these entries will at some point be interactive, like accepting a share, reverting to a version, or commenting etc. Actionable items like failed uploads or shares to be accepted will be shown up top. They will be separated by intermittent headers:
> 	- **Failed uploads** is first cause it’s local and most important cause it can lead to data loss. Will have a »Retry« and »Clear« in the header with text+icons. Then icons for each individual item.
> 	- **Requires attention** (working title) are the notifications and activities with interactivity which come from the server. For example incoming shares you need to accept. (Or in the future comments where you were mentioned with an action to reply.)
> 	- **Activities / History** where all the activites go in the end, and where also the things you act upon from **Failed uploads** and **Requires attention** go to → which is a big reason why this is a single view instead of separate ones. It’s the same things.

(Yes it’s an old and dirty mockup :)
![img_20170124_113357](https://cloud.githubusercontent.com/assets/925062/22245246/47e67ea4-e22f-11e6-99ba-a2d21fc4ae3b.jpg)

**Comment by jancborchardt** [comment]
@DominiqueFuchs @misch7 I think you mentioned you talked about how to prioritize the activity list → this is the issue you might be looking for? :)

**Comment by er-vin** [comment]
@jancborchardt isn't it what we got already in the new GUI? I see the errors, conflicts and such are already on top. And the most important notifications (like app updates available for admins) just after, then the history stuff.

**Comment by jancborchardt** [comment]
Yeqh, possibly it's best to now branch out to separate issues for the polishing, like grouping, showing upload feedback, etc etc.

**Comment by er-vin** [comment]
OK, closing this one then.
