### ISSUE TITLE
Folders called with double quotes are not syncing in windowsclients 

### ISSUE THREAD

**Issue by chillriver** [nextcloud/desktop#2222]
### Expected behaviour
The windows client should syncing folders with double quotes

### Actual behaviour
Folders called with double quotes are not syncing in windows clients, but Linux client can do

### Steps to reproduce
1. Online in Nextcloud create folder with double quotes
2. Syncing with desktop-client on windows
3. No folders are showing

Client version: Client 2.6.5
Operating system: Windows 10
Nextcloud version: 18.0.7

**Comment by Escubaer** [comment]
double quote is a forbidden character in Windows, what do you expect?
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

**Comment by chillriver** [comment]
Thanks for that information and this make sense, but maybe it should be intercepted, because some users don't know this issue by create folders online. They are surprised of lost folders.

**Comment by er-vin** [comment]
I guess it's captured in the logs, maybe a warning could be shown, might be something for the activity list in upcoming 2.7. If someone is willing to cook a patch for it I can help review.

**Comment by sberegszaszi** [comment]
Hi,
@chillriver Just asking to clarify, what do you mean by "folders called with double quotes". Do you mean, that they have double quotes in the name, like [This"folder"] for example?

**Comment by sberegszaszi** [comment]
@er-vin  There is a notification in the activity list if files are not synced. Although it does not specify the reason.
![Screenshot_2020-08-07_14-37-04](https://user-images.githubusercontent.com/51827363/89646154-85977100-d8bb-11ea-88b3-78ac50393729.png)
Client version: 2.6.5
OS: Windows 10
Server version: 19.0.1

Do you think there should be something more obvious, like a warning, maybe detailing the specific reason?

**Comment by er-vin** [comment]
Might be a bit hard to be really specific, but at least the current message seems misleading since it's not symlinks or the ignore list in that case...

**Comment by sberegszaszi** [comment]
I also found several issues addressing the same broader question:
#2014 
#1901 
#1723 
#464

**Comment by chillriver** [comment]
> Hi,
> @chillriver Just asking to clarify, what do you mean by "folders called with double quotes". Do you mean, that they have double quotes in the name, like [This"folder"] for example?

Yes you are right.

**Comment by er-vin** [comment]
> I also found several issues addressing the same broader question:
> #2014
> #1901
> #1723
> #464

Thanks, good catch, I'll keep #464 only and close the other ones (including this one)
