### ISSUE TITLE
Missing button icon on Mac with 2.6.5

### ISSUE THREAD

**Issue by er-vin** [nextcloud/desktop#2225]
<img width="745" alt="Capture d’écran 2020-07-22 à 13 36 25" src="https://user-images.githubusercontent.com/26774148/88171939-7dcf9f80-cc20-11ea-815b-76d962f3cc8e.png">
New graphical problem on version 2.6.5 the button icon has disappeared.

_Originally posted by @tib-kpl in https://github.com/nextcloud/desktop/issues/2138#issuecomment-662404364_

**Comment by MoloSeb** [comment]
I confirm the issue
https://help.nextcloud.com/t/buttons-bug-in-new-client/89380

**Comment by jospoortvliet** [comment]
@MoloSeb is this fixed in 3.0?

**Comment by tib-kpl** [comment]
> @MoloSeb is this fixed in 3.0?

yes

**Comment by er-vin** [comment]
Closing it then.
