### ISSUE TITLE
Nextcloud - Could not parse the JSON returned from the server: illegal value

### ISSUE THREAD

**Issue by jhenin** [nextcloud/desktop#2226]
I am faced regularly with issue #1915 , which I argue should be reopened. The workaround mentioned there is deleting and recreating the account. That requires a lengthy re-scan of the synced data, and is not what I'd call a fix.
I would have just commented there, but I am not allowed to reopen a closed issue.

**Comment by misch7** [comment]
Reopened #1915, let's discuss it there and close this one.
