### ISSUE TITLE
Deleting Files with the Desktop-Client fails sometime.

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/desktop#2229]
### Expected behaviour
Tell us what should happen

Deleting files properly with the Windows 
Client

### Actual behaviour
Tell us what happens instead

With an Android mobile device, files (images) are downloaded and sent to the cloud with the instant upload function.

With the Windows client the files are then downloaded to a Windows computer, viewed and moved or partially deleted.

Most of the time this works well. But about 10-20% of the files have problems deleting the files from the server.

The client then says "Directory/Filename.jpg: Deletion not allowed, Recovery; Recovery failed; The file was deleted from the server".

I will receive the message in German and translated accordingly.

I have to delete these files manually, which requires a certain effort.

### Client configuration
Client version: 2.6.5 (Windows)

Operating system:  Windows, German

### Server configuration

Nextcloud version: 18.07

**Comment by er-vin** [comment]
Any chance of providing us with debug logs covering the time when such failed deletions happen?

**Comment by Schneehexe** [comment]
I'd love to. But where do I find these logs?

**Comment by er-vin** [comment]
You can control this using the --logfile and --logdebug options on the command line. Alternatively you can add logDebug and logDir in the nextcloud.cfg (just don't forget to remove them later if you do this, it will fill up fairly quickly).

**Comment by Schneehexe** [comment]
After the last Version update, the problem was gone.
