### ISSUE TITLE
Provide option for 'direct download' after choosing 'copy public link' from context menu in desktop client

### ISSUE THREAD

**Issue by bbceg** [nextcloud/desktop#2230]
**Is your feature request related to a problem? Please describe.**
In order to have a direct download link I have to first copy the link and then append '/download'. This is fine as a one-off but not ideal if used regularly.

**Describe the solution you'd like**
It would be great to have the option to copy a link with the '/download' already appended. It probably makes most sense to include it in the additional options dropdown:

![image](https://user-images.githubusercontent.com/7188545/88380892-4a664f80-cd9d-11ea-9673-c452710d23c8.png)

Taking this one step further it could optionally be set as the default when sharing public links.

Hope that makes sense but do let me know if any further information is required.

**Comment by veddox** [comment]
Looks useful, and implementing it is pretty straightforward. I'm just not sure whether the dev team wants this from a UX perspective, but they'll have to decide that on the PR...

**Comment by er-vin** [comment]
@jancborchardt any opinion on this? It's kind of straightforward, my only concern would be about this menu getting crowded.

**Comment by jospoortvliet** [comment]
I would suggest to try and have this menu the same as the menu on the server. Just like we do with the other (mobile) clients, by the way. If we decide to add this feature to the server then we can have it in the client - but it should not be added to the client until it is in the server. That will keep the discussion in one place.

My suggestion thus is for @bbceg to open this issue in the server and close this here.

(I am skeptical of the feature itself, too, but that is a separate conversation to be had with the ux design team anyhow).

**Comment by bbceg** [comment]
I'm more than happy to open this issue in the server repo (I inadvertently created it there in the first place and it was moved, presumably because of the mention of 'desktop client') but it would be many more steps to login to the server to get hold of a 'direct download' link than it would be to use my desktop client so it wouldn't help me if it only made it to the server. Of course if everything has to go via the server then so be it.

**Comment by jancborchardt** [comment]
Yeah sorry, but adding this as well to the menu really will make it too much. We need to keep stuff simple to keep the important things obvious, and that unfortunately also means leaving some things out. Sorry about that. :)

**Comment by er-vin** [comment]
I'll thus close this one, we can always reopen if the opinion changes on the server side. Sounds unlikely though.
