### ISSUE TITLE
Client crashes after a couple of minutes if no internet connection is available (2.6.5 on Ubuntu 18.04)

### ISSUE THREAD

**Issue by k00ni** [nextcloud/desktop#2231]
### Expected behaviour
If client has no connection after it started it should wait/do nothing until some is available.

### Actual behaviour
After some time (~2 min.) the client crashes with 

> SIGSEGV in g_dbus_object_get_object_path()

### Steps to reproduce
1. Start Ubuntu with no internet connection.
2. (Client in autostart)
3. After a couple of minutes the client crashes.

### Client configuration
Client version: 2.6.5

Operating system: Ubuntu 18.04.4

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.9.5

Client package (From Nextcloud or distro) (Linux only): http://ppa.launchpad.net/nextcloud-devs/client/ubuntu

Installation path of client:

### Server configuration

Nextcloud version: 18

Storage backend (external storage):

### Logs

Output of `nextcloud --version`

```
Nextcloud version 2.6.5-20200713.144448.adada8b2e-1.0~bionic1
Using Qt 5.9.5, built against Qt 5.9.5
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1  11 Sep 2018'
Running on Ubuntu 18.04.4 LTS, x86_64
```

Because the content of the crash dialog was not exportable as text, I made a couple of screenshots.

![crash-1](https://user-images.githubusercontent.com/381727/88459571-b1b3fa80-ce96-11ea-87c8-aea1d93bdbd0.png)
![crash-2](https://user-images.githubusercontent.com/381727/88459572-b2e52780-ce96-11ea-886a-c36d7a18ffb1.png)
![crash-3](https://user-images.githubusercontent.com/381727/88459573-b4165480-ce96-11ea-8154-7aafd1ec7fd3.png)
![crash-4](https://user-images.githubusercontent.com/381727/88459575-b5478180-ce96-11ea-8165-9804ec82adf7.png)
![crash-5](https://user-images.githubusercontent.com/381727/88459577-b678ae80-ce96-11ea-852f-6d12f013bb0d.png)

**Comment by veddox** [comment]
Unfortunately, I could not reproduce this on my setup (client development version on Ubuntu 20.04). Just to make sure this is still an issue, could you test the [latest build](https://download.nextcloud.com/desktop/daily/) on your system and see if the problem persists?

Also, to give us some more information, the output of `nextcloud --version` would be helpful, as would a logfile produced by starting the client using `nextcloud --logfile <filename>`.

**Comment by veddox** [comment]
Actually, I'm fairly sure the segfault itself has been fixed - #2097 has an identical stacktrace and appears to be resolved.

However, I am still a little surprised, because this particular segfault comes during the client shutdown routine - and the client should *not* shutdown when there's no Internet. (It doesn't on my setup.) So I'm wondering why it does that? @misch7, do you have any ideas?

**Comment by k00ni** [comment]
I updated my initial post with the output of `nextcloud --version` in the Logs section.

`nextcloud --logfile <filename>` contains many personal information like file and folder names. Do you search for anything special there?

**Comment by veddox** [comment]
Great, thank you :+1:

At the moment, I'm mostly interested in whether there are any indicators as to why the client initiates shutdown?
