### ISSUE TITLE
Login from desktop app not possible because of access to token endpoint, "connection refused"

### ISSUE THREAD

**Issue by steven-omaha** [nextcloud/desktop#2232]
### Expected behaviour
Login on the NC desktop app on my server works.

### Actual behaviour
Login fails, `error access to token endpoint, "connection refused"` (translated from German)

### Steps to reproduce
1. In the nextcloud app, click "add account"
2. sign in
3. enter https://domain
4. App shows "Login Flow v2", request to alt-tab to browser
5. App shows the mentioned error 
6. In the web browser, I press "login", then "grant access". Webpage shows the spinning wheel animation forever.

### Client configuration
Client version: 2.6.5

Operating system: Windows 10 Pro

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 18.0.7.1

Storage backend (external storage): mariadb

### Logs
https://gist.github.com/steven-omaha/1cce6b510745df58aef5260fa0a99b13

**Comment by MarkErik** [comment]
Is your server by chance behind a reverse proxy?

I was setting up a server today, and I came across the same issue, and I had forgotten that there is a workaround adding `'overwriteprotocol' => 'https'` to config.php. https://github.com/nextcloud/desktop/issues/1690

Nextcloud should be able to detect (or at least ask during initial server configuration) that it is behind a reverse proxy and set the HTTPS address correctly.

**Comment by steven-omaha** [comment]
Yes, mine is behind a traefik. Thanks for the hint, will check

**Comment by steven-omaha** [comment]
That fixed it.
