### ISSUE TITLE
Removed Syncing Folder (On SD card on MS Surface), server deleted everything.

### ISSUE THREAD

**Issue by PStewardYUL** [nextcloud/desktop#2233]
### Expected behaviour
Upon removal of Nextcloud folder - Pause and confirm removal of entire server content was intended. If not, stay paused until user starts sync again.

### Actual behaviour
Automatically deleted all server content when SD card removed and when SD card restored, deleted local content.

### Steps to reproduce
1. Have a Microsoft Surface
2. Use SD card in base as storage medium for Nextcloud
3. Separate screen from base when Nextcloud is not-paused

### Client configuration
Client version: 2.6.5

Operating system: Windows 10 PRO

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: D:/Nextcloud

### Server configuration

Nextcloud version: 18.0.7

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by audunmg** [comment]
Happened to me as well, everything got deleted because a filesystem failed to mount on resume.

Would be great to have a check in the sync client to not delete absolutely everything.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support

**Comment by gusarg81** [comment]
Hi, this is happening to me too on Mac. Nextcloud sync folder is setup in a external disk. Is that disk is unmounted for some reason (or the user, of whatever the computer is turn on without that disk), Nextcloud client "threat it" as all file were deleted. Is there a way to fix this? Nextcloud should stop syncing if the entire Nextcloud folder is not there, and not delete it from the DB like is doing it.

I have a lot of files here (around 450GB) and the resync again when the disk is mounted, takes a lot of time.
