### ISSUE TITLE
compat_ifmu_ulist: error 14 in Console logs on macOS Catalina

### ISSUE THREAD

**Issue by mbentley** [nextcloud/desktop#2237]
### Expected behaviour
When running Nextcloud Desktop Client 2.6.5 on macOS Catalina 10.15.6, I am seeing error events being reported in Console.  I wouldn't expect this to be happening.

### Actual behaviour
![screenshot 2020-07-29 at 11 45 57 AM](https://user-images.githubusercontent.com/414445/88825879-153f7000-d196-11ea-8b63-2f37df3b73df.png)

The error repeats every 10 seconds for all of the interfaces on my Mac:
```
compat_ifmu_ulist: <interface> copyin() error 14
```

This only happens when Nextcloud is open so I believe it is something related to the Nextcloud client.

### Steps to reproduce
1. Run Nextcloud client on macOS
2. Look at the Console app
3. See errors.  Stop the Nextcloud client and the errors cease.

### Client configuration
Client version: 2.6.5

Operating system: macOS Catalina 10.15.6

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:`/Applications`

### Server configuration
Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

I didn't see anything relevant in the logfiles but here is a sample from when the errors were repeated multiple times in Console: https://gist.github.com/mbentley/3029da9882e9184aafa3d0e5ad51a1cf.  I also didn't see any specific correlation between when the Console errors were reported and when logs were output from the client.

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by kapfenho** [comment]
The same problem (or perhaps worse) happens with version 3.1.0 on macOS 10.15.7 and macOS 11.1

There are additional problems in app launch.

The OS error messages are quite firm what's the problem and what has to be done:

https://gist.github.com/kapfenho/f9e1e6ae31e19c7f039b1598a21ad112

**Comment by FlxVctr** [comment]
Here's a workaround: https://github.com/nextcloud/desktop/issues/2944

**Comment by FlexW** [comment]
I think this should be closed by #3040
