### ISSUE TITLE
URL of default Talk button is wrong. 

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/desktop#2243]
### Expected behaviour
Clicking on the Talk button in the main window should open the browser and the Talk app.

### Actual behaviour
The link that is openend is .../apps/spreed/ instead of .../index.php/apps/spreed/

### Steps to reproduce
1. clicking on the Talk button
2. Check url

### Client configuration
Client version:
Default 2.7RC1

Operating system:
MacOS

OS language:
english

Qt version used by client package (Linux only, see also Settings dialog):
default

Client package (From Nextcloud or distro) (Linux only):
official build

Installation path of client:
default

**Comment by karlitschek** [comment]
@camilasan @er-vin @misch7

**Comment by er-vin** [comment]
I see... the others apps are correct though? It opens the right URL?

**Comment by camilasan** [comment]
On my local instance https://localhost:8443/apps/spreed opens Talk, and https://localhost:8443/apps/mail opens the mail app. These urls are returned by the server.

**Comment by er-vin** [comment]
Yes, they are returned by the server... except for the Talk app, somehow this URL is built within `UserModel` unlike the others. Here I tested on two instances:
 * my local docker setup which uses .../apps/foo everywhere
 * my personal production instance which uses ../index.php/apps/foo everywhere

And in the second case the Talk button still goes to ../apps/spreed. It ends up working fine, but it probably shouldn't do that.

**Comment by camilasan** [comment]
I see. Talk is skipped so it doesn't show up in the menu.

https://github.com/nextcloud/desktop/blob/e02be629bbdd80c84ebf5c21f0b4d2d24504980a/src/gui/tray/UserModel.cpp#L868

**Comment by camilasan** [comment]
I am fixing it.

**Comment by karlitschek** [comment]
Thanks :-)
