### ISSUE TITLE
[on MacOS, v2.6.5] I have to relaunch NextCloud Desktop for sync

### ISSUE THREAD

**Issue by dleurs** [nextcloud/desktop#2253]
### Expected behaviour
On my computer, moving folders from my computer (like ~/Desktop) to the sync NextCloud folder, like ~/NextCloud, should  immediatly start the sync process for the folder and files insides the folder, e.g. upload file from computer to NextCloud. 

### Actual behaviour
Just the folder is sync immediatly, without starting syncing (upload, from computer to NextCloud) files inside that folder.

### Temp solution
Once folder with file inside NextCloud folder, close and open again NextCloud Desktop

### Client configuration
Client version: MacOS 2.6.5

Operating system: MacOS Catalina 10.15.5

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): what?

Installation path of client: what?no need?

### Server configuration

Nextcloud version: Nextcloud 19.0.1.1
Using CloudAmo, servers in Germany

Storage backend (external storage): what?

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log: no need?

3. Server logfile: nextcloud log (data/nextcloud.log): no need?

**Comment by ShadowHawk07** [comment]
I'm receiving the same issue, macOS Catalina 10.15.6, Client version 2.6.5.

**Comment by jospoortvliet** [comment]
Please, try v3.0 - if it is fixed, then please close this issue!
