### ISSUE TITLE
Make it easier to figure out you can sync multiple folders from one account

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#226]
You can sync files with Nextcloud in two major ways:
* sync everything in one directory, say /Nextcloud
* sync specific Nextcloud folders to your local system, like /Documents /work /private and /projects

The default is the first, and often users don't manage to find out about the 2nd. We should consider to overhaul the initial installation dialog to fix this, maybe look at how Google Drive does it (I understand it is more clear about it) or others.

**Comment by jancborchardt** [comment]
@jospoortvliet does Google Drive provide this? Honestly I’d say we should really focus on the dead-simple single /Nextcloud sync (what people are also used to from Dropbox), otherwise it complicates the setup.

**Comment by michaelstingl** [comment]
Wanna join the discussion in https://github.com/owncloud/client/pull/6470 ?

**Comment by er-vin** [comment]
@jancborchardt did you look a the PR @michaelstingl referred to? Do you think that'd do it? I guess it's more or less a power user thing in the end. By changing the wizard like this it's likely easier to create those complex setup without putting too much burden on less seasoned users.

**Comment by jancborchardt** [comment]
Maybe, if it's combined with the suggestions at https://github.com/owncloud/client/pull/6534
- Add "(recommended)" after the first option
- Also bold the first option

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
