### ISSUE TITLE
NC 18.0.7, Groupfolders 6.0.6 - different content on Browser and Sync-Clients

### ISSUE THREAD

**Issue by JarlMorgennebel** [nextcloud/desktop#2261]
### Expected behaviour
Groupfolder "Eltern - Mosaike" configured and shared with group parents (rw), two members.
Member A uploaded data using Mac OS X and Sync-Client to groupfolder and can see that data.
Member B uploaded data using Win 10 and Sync-Client to groupfolder and can see that data.

Expected: Member A and B can see all data.

### Actual behaviour
Member A only sees his data using the Sync-Client.
Member B sees all data using a Browser.
Member B sees only his data using the Sync-Client.

### Client configuration
Client version: Desktop Client 2.6.5
Operating system: Win 10
OS language: EN

### Server configuration
Nextcloud version: 18.0.7 + Postgresql 11.0 on Devuan 3.0

Storage backend (external storage):
Local USB disk

### Logs
![Browser](https://user-images.githubusercontent.com/59556758/89981030-6447d380-dc73-11ea-8608-717737be8926.PNG)
![Desktop-Client](https://user-images.githubusercontent.com/59556758/89981098-8ccfcd80-dc73-11ea-9076-6e5b17a8b593.PNG)

Logfiles are each 6 MB. However a "grep MOSAIK Client-Logfile.txt" returned empty. Also used occ to rescan files and groupfolders before opening this issue without resolving the issue.

Server worked fine before update to 18.0.7, but 18.0.6 showed same issue.

**Comment by er-vin** [comment]
I'm slightly confused about that report, so do you mean that the Windows client uploaded all its data on the server but then doesn't see it locally or in the web gui? (this comes from the fact that you did the distinction sync-client / browser for "member B" but not for "member A")

**Comment by JarlMorgennebel** [comment]
Apologies for being unclear.

The browser screenshot is from Machine B (Windows), User B showing data which has been uploaded from Machine A (Mac OS X) from User A using the Sync-Client.

The folder screenshot is from Machine B (Windows), User B showing data which has been uploaded from Machine B from User B using the Sync-Client.

The browser screenshot indicates more files and folders which are not displayed. The folder screenshot shows the other files but not the one seen in the browser file.

**Comment by er-vin** [comment]
You don't need to apologies, it's admittedly a slightly complex scenario... also we can't exclude it's just me being slow to understand. ;-)

What trips me up is that apparently something is wrong with the web gui as well... so I wonder if it's really a problem with the client or with the server.

Anyway, I'll try to rephrase in my own way to see if I got it right and you tell me where I'm wrong.

 * User A uploaded files through the Mac OS client;
 * User B uploaded files  through the Windows client;
 * User A sees her files both locally and using the web gui;
 * User A doesn't see any file from user B locally or using the web gui (although the web gui indicates more files not being displayed)
 * User B sees her files and user A files locally;
 * User B doesn't see her files using the web gui but sees user A files there (although the web gui also indicates more files not being displayed)

Did I get it all correct?

You seem to have access to the place where the files are supposed to be stored, if you look straight in the storage filesystem (using the command line, so not going through the web gui) do you see any of user B files?

**Comment by JarlMorgennebel** [comment]
Hi er-vin,

indeed, this is the summary. However I think there are two issues, one for the sync-client and one for the web-gui.

The good news - the web-gui one disappeared once I flushed the redis-cache (found this as hint within the forums).
The issue with the sync client remains - the folder 'MOSAIK' is still missing on the Windows box.

"ls -lah" on the storage filesystem:

```
root@wolke7:/mnt/usb-cloud/data/__groupfolders/15# ls -lah
total 16M
drwxr-sr-x  6 www-data www-data 4.0K Aug 11 10:08  .
drwxr-sr-x 13 www-data www-data 4.0K Jul 29 15:06  ..
-rw-r--r--  1 www-data www-data 7.8M Aug  3 08:55 'KUNSTGRIFF_2020 Birgit und Nina 20200803.pdf'
-rw-r--r--  1 www-data www-data 7.8M Aug  2 16:53 'KUNSTGRIFF_2020 Birgit und Nina in der....pdf'
drwxr-sr-x 19 www-data www-data 4.0K Aug  2 15:34 'MOSAIK '
drwxr-sr-x  2 www-data www-data 4.0K Aug 11 10:08  Test
drwxr-sr-x  2 www-data www-data 4.0K Aug  8 11:02 'Von Oliver unsortiert'
drwxr-sr-x  2 www-data www-data 4.0K Aug 10 21:09 'Von Oliver unsortiert - Kopie'
```

The missing folder (in terms of the sync-client on Windows box) is the one called 'MOSAIK'. However I do noticed a trailing whitespace in the folder name. I renamed the folder using the command line and initiated a filescan using occ for all users.

After the file scan the 'MOSAIK' folder synced fine on the Windows box as well. So the problem itself is solved.

However there is a bug in the Mac sync Desktop tool which allows to create/sync folders with trailing whitespace to Nextcloud.

May I recommend to not allow folder names with white space in the beginning/end at both the web-gui and the sync-client?

Thanks

**Comment by er-vin** [comment]
Thanks that was useful information. It's indeed not the first time we have such an issue regarding space at the end of names, we need to do better to catch name interoperability issues like this.

We got another issue covering that somewhere, I thus won't reopen this one.
