### ISSUE TITLE
Desktop client fails to sync

### ISSUE THREAD

**Issue by monochromec** [nextcloud/desktop#2273]
Exact same behaviour as with issue #1101 (https://github.com/nextcloud/desktop/issues/1101). Changing the reqtimeout parameters as suggested by patgrosse did not solve the problem. File size is 14 kB. More than happy to supply more details - just let me know.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version: 2.6.2-1build1

Operating system:
Focal Fossa, FC32

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
Not visible in Settings

Client package (From Nextcloud or distro) (Linux only):

nextcloud-desktop (from Focal repos)

Installation path of client:
/usr/bin

### Server configuration

Nextcloud version:
19.0.0
Storage backend (external storage):
Files

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

https://gist.github.com/monochromec/ab64f5cdc13a25bdaad5002d698c7aeb

2. Web server error log:

https://gist.github.com/monochromec/ab64f5cdc13a25bdaad5002d698c7aeb

3. Server logfile: nextcloud log (data/nextcloud.log):
n/a

**Comment by er-vin** [comment]
Please provide us with a client log file using --logfile and --logdebug on the command line. Make sure you're using the client 2.6.5 when doing so (there's been fixes since 2.6.2 and we improved the logging for 2.6.5). Get it to run just during a single failing sync so that we don't have too much noise.

Thanks in advance.

**Comment by monochromec** [comment]
Works with version 3.0 of the desktop client (AppImage). Closing the issue.

**Comment by er-vin** [comment]
Thanks for letting us know. Glad it solved your issue.
