### ISSUE TITLE
3.0 - Pause button and other features are now located in a submenu

### ISSUE THREAD

**Issue by helmut72** [nextcloud/desktop#2290]
### Expected behaviour
features are reachable without to many clicks

### Actual behaviour
Version 3.0 of Desktop client moved all features into a submenu

### Client configuration
Client version: 3.0

**Comment by er-vin** [comment]
@jancborchardt what do you think about that?

**Comment by jancborchardt** [comment]
"Pause sync" (or "Pause sync all") for multiple accounts will be brought back to the right-click menu as per https://github.com/nextcloud/desktop/issues/2391

The individual "Pause sync" should indeed be in the 3-dot menu like "Log out" and "Remove account", as first entry.


> sync progress bar

@sureloc We should fix that as well indeed by showing uploading feedback directly in the new main dialog as well. But it is a different discussion – mind opening a separate issue for it?

**Comment by unclev** [comment]
I vote for sync progress bar in the main window.

Regarding _Force sync_ it is event worse: it is in folder _Settings_. I'm aware that is it is per folder, - so what about _Force sync all_? Or get folder switcher available in the Main window?
