### ISSUE TITLE
Linux Client 3.0.0 HiDPI issue

### ISSUE THREAD

**Issue by xen0m0rph2020** [nextcloud/desktop#2295]
Hi all

On the latest version of the Desktop Linux client there is a new UI added when you click on the icon in taskbar. However this is not scaled on HiDPI everything is too small. Cannot screenshot as it dissapears as soon as you take screenshot.
When you go to settings and open the older dialogue then that works fine as usual and scales fine. 

This is on Ubuntu 20 and using the latest appimage of NextCloud client.

**Comment by er-vin** [comment]
@DominiqueFuchs you might be interested into that one, this is because it's all pixel based currently. I guess we'll have to come up with a multiplication factor to apply everywhere made out of Screen.pixelDensity and Screen.devicePixelRatio.

**Comment by Bubu** [comment]
For me the hiDPI scaling doesn't work, even in the main window.

But I got a screenshot of the tray activity, it's tiny... :-(

![image](https://user-images.githubusercontent.com/105185/92333110-36dc2300-f083-11ea-9905-009b79f18543.png)

**Comment by seanfarley** [comment]
For me, on Budgie, the icons are not scaled nicely (e.g. they appear blurry) but mostly are the correct final size.

**Comment by Steven--** [comment]
The problem still persists on Debian testing, using the nextcloud-desktop package (version 3.1.1-1).

~~~
$ nextcloud --version
Nextcloud version 3.1.1-1
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1j  16 Feb 2021'
Running on Debian GNU/Linux bullseye/sid, x86_64
~~~

Both the icons and the text are very tiny (compare, e.g., with the text on Nextcloud's home page as rendered by Firefox). 

![image](https://user-images.githubusercontent.com/5714076/111870330-71087480-8984-11eb-9bc8-b54e353729c3.png)

**Comment by recurved** [comment]
I finally fixed this for my 4k laptop display. I added this line to the end of my ~/.profile as suggested in a thread on stackexchange:

> `export QT_AUTO_SCREEN_SCALE_FACTOR=1`

Here's a link to the original post:
https://unix.stackexchange.com/a/443531

And here's what it looks like after the change:
![Nextcloud Desktop Screenshot](https://user-images.githubusercontent.com/39954171/111874470-cd12cf00-896b-11eb-8379-8668dd3d9349.png)

**Comment by Steven--** [comment]
I can confirm that the workaround suggested by @recurved works.
