### ISSUE TITLE
Nextcloud Desktop Client start minimized option?

### ISSUE THREAD

**Issue by tromlet** [nextcloud/desktop#2296]
### Expected behaviour
The Nextcloud desktop client window should not pop up every time I log in to my desktop.

### Actual behaviour
The Nextcloud desktop client window _does_ pop up every time I log in to my desktop.

### Steps to reproduce
1. Start computer
2. Log into user account

### Client configuration
Client version: 2.6.5 (Fedora)

Operating system: Fedora 32

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): ??

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: ??

**Comment by jospoortvliet** [comment]
This must be a fedora issue, it has never done this here. Can you try 3.0 once it is available in Fedora?

**Comment by er-vin** [comment]
Yes it feels like it is started twice for some reason, looks like a deployment issue to me.

**Comment by er-vin** [comment]
Now that I think of it: note that it could be a left over autostart file doing this, in which case upgrade won't help. You should perhaps check `~/.config/autostart*` or any other such autostart folder your desktop environment might look at.

**Comment by FlexW** [comment]
Does the issue still persist?

**Comment by tromlet** [comment]
This issue is perhaps better explained as a Windows user familiarizing himself with Fedora and Dash-to-Panel for GNOME. There's no obvious place for background applications to live (like the Windows system tray), so upon reboot, the Nextcloud window opens before disappearing - but System Monitor shows quite clearly that it's still running in the background, so. Everything's working fine, and whenever I need to get to the actual interface of the desktop app, I can just go to the Application Drawer and select it.

I would say that this issue is closed.

**Comment by FlexW** [comment]
@tromlet If you using Fedora or more precisely GNOME then you should install the [app indicator extension](https://extensions.gnome.org/extension/615/appindicator-support/). With that extension you get system trays in GNOME.
