### ISSUE TITLE
Client 3.0.0 crashes after e2ee has been enabled

### ISSUE THREAD

**Issue by Castiontone** [nextcloud/desktop#2298]
### Expected behaviour
Desktop client finishes sync successful

### Actual behaviour

- After installing new client 3 on Windows 10 (replacing 2.6.5) sync remains at 'preparing to sync'
- After a while the client either times out, or crashes.
- At the server apache2 uses high CPU. 
- On the server both default encryption module and e2ee app are enabled. (Not the server-side-encryption)
- Android app works fine with encryption.
- after using android to succesfuly create encrypted folder, also client 2.6.5 times out
- disabling e2ee app on server AND removing the encrypted file (and restarting server) solves issue for 2.6.5, but NOT 3.0.0

Happy to investigate this further if someone knows where to look next.

### Steps to reproduce
1. enable e2ee endpoint and default encryption app on NC 19.0.1
2. start desktop client 3.0.0
3. (restart apache2 on server because the whole instance becomes unresponsive)

### Client configuration
Client version: 3.0.0

Operating system:
Windows 10

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files\Nextcloud

### Server configuration
NC 19.0.1, Ubuntu 18.04, php7.4, apache  2.4.29

Nextcloud version: 19.0.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
2020-08-20 22:51:17:568 [ warning nextcloud.gui.sharing.ocs ]:	Could not parse reply to "GET" QUrl("https://SERVER/ocs/v2.php/core/navigation/apps") (QPair("absolute","true")) "illegal value" : ""

2. Web server error log:
Apache2 error log  "AH01797: client denied by server configuration: /var/www/nextcloud/data/.ocdata" and "AH01797: client denied by server configuration: /var/www/nextcloud/config"

3. Server logfile: nextcloud log (data/nextcloud.log):
(Nextcloud log gives "[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209", but does so regardless of whether encryption is enabled or not, so I did not investigate this further)

**Comment by bcutter** [comment]
I can confirm that using desktop client version 3.0.0 causes syncs to take like forever when server encryption (and E2E encryption) is activated:
Before enabling encryption: 2 seconds. server load minimal.
After enabling encryption: 290 seconds (almost 5 minutes). server load 100 % on one core for php-fpm, approx. 30 % for mysqld.

Also saw some crashes of the desktop client. Hope these bugs will be sorted out quickly in next desktop client version!

**Comment by basvandenbrink** [comment]
Same here with Postgres 9 as DB backend. I had to turn off E2E because of the major performance issues.

**Comment by camilasan** [comment]
If you ever tried end-to-end encryption before version 3.0, please follow the instructions from this post:
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590

to clean up the keys as that can break the functioning of >3.0 if you had a malformed key.

If that doesn't help then we will need the logs. Please run the client with --logdebug
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by er-vin** [comment]
In case of a crash a backtrace would be very welcome as well, it'd be useful to do it from a build with debug symbols (otherwise we'll likely miss quite some information).

**Comment by Castiontone** [comment]
interesting new finding: I always have port 80 closed on the server for security reasons, I only use ssl anyway. When re-enabeling port 80, encryption and client 3.0.x work well together, so this report can be closed

(Although I still have the high CPU of MySQL and lost folder sync connections as reported in other bugs)
