### ISSUE TITLE
NextCloud snap client in Ubuntu not saving credentials due to AppArmor policy.

### ISSUE THREAD

**Issue by ByteSizeOtter** [nextcloud/desktop#230]
Installing the Snap version of nextcloud-client works and the application syncs fine, however reboot or even restart of the application itself results in it asking for a password. It does not save the password to the gnome keyring, displaying a message in the password dialog, "No keychain service available." I have verified that gnome-keyring is installed and the daemon is running.

Installing and using the apt version of nextcloud-client works perfectly fine and in fact stores and uses the credentials in the keyring without fail.

Running the nexcloud-client snap from the command line results in the following:

> Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
> QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.125\" (uid=1000 pid=6412 comm=\"nextcloud \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=811 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
> QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.125\" (uid=1000 pid=6412 comm=\"nextcloud \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=811 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
> "Object path cannot be empty"
> Gkr-Message: secret service operation failed: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.151" (uid=1000 pid=6412 comm="nextcloud ") interface="org.freedesktop.DBus.Peer" member="Ping" error name="(unset)" requested_reply="0" destination="org.freedesktop.secrets" (uid=1000 pid=1902 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")

The very last line indicates why it's not saving the password (or reading them) as it's not able to communicate with the keyring daemon.

**Comment by elcolumbio** [comment]
i run in this, too.
do you have a workaround?

**Comment by norbekaiser** [comment]
Hi
I also Encountered this problem under ubuntu 18.04 with the snap version,
However i could solve it by adding the permission to add/store/modify passwords in the software center
![bildschirmfoto vom 2018-05-02 08-31-13](https://user-images.githubusercontent.com/9151455/39508894-6ace2080-4de4-11e8-8fae-c7af0272a3ce.png)

**Comment by brzd** [comment]
I have the same issue with apparmor policy preventing storing and fetching the password. I am not able to set permissions through the above suggested way.

**Comment by stooj** [comment]
There is an ongoing discussion here: [Nextcloud-client snap doesn’t remember password](https://forum.snapcraft.io/t/nextcloud-client-snap-doesnt-remember-password/4270)

**Comment by gerhardbeck** [comment]
Got same problem, but can't change the permissions , too

**Comment by misch7** [comment]
Closing this here becaue it seems to be solved.

For another `libgnome-keyring` issue please see: https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811
