### ISSUE TITLE
MacOS client logged out regularly

### ISSUE THREAD

**Issue by thanhtam4692** [nextcloud/desktop#2306]
### Expected behaviour
After installing the MacOS desktop client and successfully logged in with a Nextcloud server and doing syncing as expected, the client should stay logged in for at least several days (or months) depend on the setting in config.php

### Actual behaviour
Instead, it's logged out on daily basic. If the client is already running, it log the account out. If it is closed and then started, the whole login flow v2 is running again and I have to grant its access to the account again (even though my browser is still logged in with that Nextcloud account)

### Steps to reproduce
1. Install Nextcloud server 19.0.1 (it happened with current version as well, then I tried to update to the beta version to see if it was server error of some sort)
2. Install MacOS desktop client latest version: 2.6.5
3. Login with your credentials. Wait a day and the client will automatically logged your account out

### Client configuration
Client version: 2.6.5

Operating system: MacOS Catalina

OS language: English (UK)

Installation path of client:

### Server configuration
Nextcloud version: 19.0.1

**Comment by camilasan** [comment]
We need logs to be able to help you :)
Also do you have the same issue with the actual latest version 3.0?

**Comment by thanhtam4692** [comment]
Thank for your reply. I have my logs here: 

[20200825_1545_owncloud.log](https://github.com/nextcloud/desktop/files/5122779/20200825_1545_owncloud.log)

It seems like the client request password from my keychain but it could not be found, which is weird since I use v2 flow to authenticate the client so it should be other type of cert I guess?. Since I have my server without SSL, would it be the problem here?

**Comment by thanhtam4692** [comment]
I didn't realise there is a 3.0 version since my current client haven't report any update. I'm trying it right now.

**Comment by camilasan** [comment]
> would it be the problem here?

It should work without SSL.

**Comment by thanhtam4692** [comment]
Ok sao I gave client 3.0 a try, and the problem still persists. I have my log here:

[20200826_0240_owncloud.log](https://github.com/nextcloud/desktop/files/5127582/20200826_0240_owncloud.log)

2020-08-26 04:14:36:095 [ info nextcloud.gui.account.state ]:	AccountState state change:  "Connected" -> "Signed out"

Cookies is still valid (I guess): QNetworkCookie("nc_sameSiteCookielax=true; HttpOnly; expires=Fri, 31-Dec-2100 23:59:59 GMT; domain=cloud.tamthanhtran.xyz; path=/")

Could it be any problem with the backend? The Nextcloud apps on both IOS and Android are still working well for me.

**Comment by er-vin** [comment]
From the logs it looks like either the server rejects the token for some reason or that the token isn't stored/read from the Mac keyring by the client. Can you find said token in the keyring properly at least?

**Comment by thanhtam4692** [comment]
> From the logs it looks like either the server rejects the token for some reason or that the token isn't stored/read from the Mac keyring by the client. Can you find said token in the keyring properly at least?

I assume you meant Nextcloud will store its credential in keychain since this is MacOs client? I checked MacOS keychain and find nothing Nextcloud related. The client use v2/flow which is handled by the browser, I guess the cert should be in the browser itself? If not, can you show me how to get Nextcloud client to connect to MacOS keychain? I had thought about this already but I can not find anything online. Thank a lot!

**Comment by er-vin** [comment]
> > From the logs it looks like either the server rejects the token for some reason or that the token isn't stored/read from the Mac keyring by the client. Can you find said token in the keyring properly at least?
> 
> I assume you meant Nextcloud will store its credential in keychain since this is MacOs client?

Yes, this is what I meant.

> I checked MacOS keychain and find nothing Nextcloud related. The client use v2/flow which is handled by the browser, I guess the cert should be in the browser itself?

The client then get a token, this token is supposed to be stored in the MacOS keychain.

> If not, can you show me how to get Nextcloud client to connect to MacOS keychain? I had thought about this already but I can not find anything online. Thank a lot!

Well, you shouldn't need to AFAIK. There's something off somewhere... but I'm unsure what at the moment.

@camilasan @DominiqueFuchs @misch7 any idea?

**Comment by thanhtam4692** [comment]
I'm in version 3.2.1 right now and the problem persists

**Comment by mgallien** [comment]
> I'm in version 3.2.1 right now and the problem persists

Could you please send us the log when you reproduce with the latest version ?
That would help a lot

See following information:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)
Thanks!

**Comment by thanhtam4692** [comment]
Sorry I' a little late. I have tried to get the log from the client, but it seems like I can only get the log the old way. Anyway, here is the logs:

[Archive.zip](https://github.com/nextcloud/desktop/files/6693789/Archive.zip)

**Comment by tvlc** [comment]
Same issue on multiple mac machines. Please reopen.

**Comment by mjeshurun** [comment]
I'm also getting repeated "you have been logged out..." messages when using Nextcloud 3.3.1 desktop client on MacOS.

**Comment by alexander-potemkin** [comment]
same issue
