### ISSUE TITLE
Silent local file corruption on windows

### ISSUE THREAD

**Issue by metorm** [nextcloud/desktop#2307]
### Expected behaviour
When the sync ends, the local file shall be exactly the same as the remote (server) side.

### Actual behaviour
One local file, among other thousands of ones, is corrupted. The content is:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>System in maintenance mode.</s:message>
</d:error>
4e3069000360{A VERY LONG LINE OF TEXT MASKED FOR SECURITY}
encryption_applied: 1
encryption_blob_encrypted: 
size: 
is_shared: 
type_: 4
```

Note the `A VERY LONG LINE OF TEXT MASKED FOR SECURITY` part, I replaced some private data. It's a long line of text of about 850 chars.

While it's remote version remains correct:

```
id: 865d4cfd2638441bbf83fdfe23929d28
mime: 
filename: 
created_time: 
updated_time: 2020-01-05T13:52:48.369Z
user_created_time: 
user_updated_time: 
file_extension: 
encryption_cipher_text: JED010000220579f965259d3a4016a3ecaa2fb54e3069000360{A VERY LONG LINE OF TEXT MASKED FOR SECURITY}
encryption_applied: 1
encryption_blob_encrypted: 
size: 
is_shared: 
type_: 4
```

### Steps to reproduce
I don't know.
File modify time data shows this happened 2 months ago. That's why this is scary. I don't know if there are other files corrupted silently.

### Client configuration
Client version: 2.6.5

Operating system: Windows 10 x64

OS language: Chinese Simplified

Installation path of client: Default

### Server configuration

Nextcloud version: 18.0.6

### Logs

Since the exact date is unavailable, I cannot local relevant log data.

**Comment by camilasan** [comment]
First of  all I would consider upgrading the server and the client.
Second we need logs.
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by Electrenator** [comment]
I also have this issue but with a different message (seen below). This has been slowly corrupting files by writing an error message over file beginnings. The one I see is the following from the same file the sync log is from. Have had others but this is the only one I hadn't recovered yet.
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception</s:exception>
<s:message>An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` &gt;= 0' with params [1606732783, "files\/b47c7b4ec8b50220dd322fc5cee3ab3b"]:

		SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction</s:message>
</d:error>
``` 
Gladly it only updates these files on the server if these files update themselves, so have been able to restore most of the files this happened to. It doesn't seem to view those insertions as new file updates.  
Havn't catched this in the log yet, it doesn't hapen often. Did see that the sync log doesn't see an issue with the last fille that got corrupted. Part of that log with unrelated file entries stripped out:
```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=#=# Propagation starts 2020-11-30T09:35:31Z (last step: 1846 msec, total: 1846 msec)
09:41:07||Code/HvA Projects/FYS_year1_block1&2/team-5/src/www/administrator.html|INST_SYNC|Down|1606700832|31356c2e4f101f1294a580c4b49fb722|13233|00080962ocxvm7qykges|4||0|13233|1606599607||||
09:41:07||Code/HvA Projects/FYS_year1_block1&2/team-5/src/www/.administrator.html.~4ac175bb|INST_NEW|Up|1606728853|7b0cba252d066044f947297a9025d9c4|497|00081080ocxvm7qykges|4||201|0|0||||
#=#=#=# Syncrun finished 2020-11-30T09:35:44Z (last step: 12857 msec, total: 14704 msec)
#=#=#=# Syncrun started 2020-11-30T09:35:50Z
#=#=#=#=# Propagation starts 2020-11-30T09:35:53Z (last step: 2326 msec, total: 2326 msec)
09:41:29||Code/HvA Projects/FYS_year1_block1&2/team-5/src/www/.administrator.html.~4ac175bb|INST_REMOVE|Up|1606728853|7b0cba252d066044f947297a9025d9c4|497|00081080ocxvm7qykges|4||204|0|0||||
#=#=#=# Syncrun finished 2020-11-30T09:35:59Z (last step: 6069 msec, total: 8396 msec)
```
Now that I'm writing this, I do notice a `html result code` of 0, could have something to do with this. Furthermore, I hope that this comment on this will help move towards a solution.

## Further information
### Client configuration
Client version: 3.0.2
Operating system: Ubuntu Desktop 20.04.1 LTS x86_64
OS language: English (US)
Qt version used by client package (Linux only, see also Settings dialog): Not installed
Client package (From Nextcloud or distro) (Linux only): [from Nextcloud - Nextcloud-3.0.2-x86_64.AppImage](https://github.com/nextcloud/desktop/releases/download/v3.0.2/Nextcloud-3.0.2-x86_64.AppImage)
Installation path of client: ~/Nextcloud-x86_64.AppImage (/home/user/Nextcloud-x86_64.AppImage)

### Server configuration
Probably not necessary but will still include version.

Nextcloud version: 18.0.4

**Comment by metorm** [comment]
I think, if the issue is not fixed yet, it should still exist.
