### ISSUE TITLE
Windows Desktop Client 3.0.0: Display mnemonic is empty and also can't be filled in

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/desktop#2308]
### Expected behaviour

When clicking on "Display mnemonic" my configured mnemonic should be shown.

### Actual behaviour

I also tried to insert the mnemonic phrase, but when clicking "OK" and "Display mnemonic" again, the field is empty again.
The field mnemonic stays empty.

### Steps to reproduce
1. Start Nextcloud client
2. Clicking on "Display mnemonic"
3. Insert mnemonic passphrase
4. Click "OK" and "Display mnemonic" again.

### Client configuration
Client version: 3.0.0 (Windows)

Operating system: Windows 10 (64-bit)

OS language: DE

**Comment by bcutter** [comment]
You´re sure the E2EE app is installed and activated?

**Comment by blu-IT** [comment]
Yes, because I use it on Android mobile and syncing of encrypted folders/data works.

**Comment by bcutter** [comment]
Experienced the same on another client (Windows endpoint). After restarting the client Nextcloud desktop asked for the passphrase when starting up. After entering it the "display mnemonic" button shows the passphrase and E2E sync is working.

**Comment by lemmy04** [comment]
same on linux. by the way what is the "E2EE app"? Do you mean the 3.0 client?

**Comment by blu-IT** [comment]
@bcutter Strange, I already ended and restartet the nc client serveral time and noch change. Now I tried again and now it shows my mnemonic when clicking and the encrypted folder (via Android app) is recognized correctly!

Should this issue stay open to fix that behavior by the devs?

**Comment by camilasan** [comment]
What is the version of the end to end encryption app in the server?

**Comment by blu-IT** [comment]
V.1.5.2 on nc 19.0.0

**Comment by camilasan** [comment]
Also If you ever tried end-to-end encryption before version 3.0, please follow the instructions from this post:
https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590

to clean up the keys as that can break the functioning of >3.0 if you had a malformed key.

**Comment by camilasan** [comment]
And if that doesn't work we need the logs :) - please run the client with --logdebug
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by blu-IT** [comment]
@camilasan 

> Also If you ever tried end-to-end encryption before version 3.0, please follow the instructions from this post:
> https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590
> 
> to clean up the keys as that can break the functioning of >3.0 if you had a malformed key.

Yes, I tried e2e encryption before, so this might have been the problem. Did not know about the cleanup.
But now it is working, like I wrote before.

Thanks again!

**Comment by lemmy04** [comment]
please monitor your database for a bit: i noticed that on my system the database load inflated by roughly 1000% when I enabled e2ee.

**Comment by bcutter** [comment]
> please monitor your database for a bit: i noticed that on my system the database load inflated by roughly 1000% when I enabled e2ee.

I also noticed enabling E2EE increased cpu usage (php-fpm and MySQL) when desktop clients are syncing - and one sync progress takes like forever (2 seconds without E2EE versus 290 seconds with E2EE enabled).

Couldn't find an issue for this yet, but it's off-topic here.
