### ISSUE TITLE
Dockerfile url expired

### ISSUE THREAD

**Issue by kjjam** [nextcloud/desktop#2310]
Hello,
I am trying [Windows Installer Build](https://docs.nextcloud.com/desktop/2.6/building.html#windows-installer-build-cross-compile) to make windows installer .
Link below In the **Dockerfile**, is expired :
`http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Leap_42.1/windows:mingw.repo`

Operating system:
openSUSE Leap 42.3

**Comment by edvinkuric** [comment]
you can change the URL to http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Leap_42.3/windows:mingw.repo , which should work

maybe this can help you: 
https://github.com/nextcloud/desktop/issues/909
