### ISSUE TITLE
Client 3.0 shows E2E is available even if it is not

### ISSUE THREAD

**Issue by csware** [nextcloud/desktop#2312]
After starting the Nextcloud desktop application it shows that E2E encryption is available on the server, even if the server is not reachable (host not found) and the E2E app is not availableon the server (e.g., not enabled or very old owncloud server).

### Expected behaviour
The client should show that E2E is available only when it really is.

### Actual behaviour
The client shows that E2E is available even if it is not.

### Steps to reproduce
1. Optionally: Configure old owncloud server
2.  Close Nextcloud client
3. Disable networking resp. configure high packet loss.
4. Start Nextcloud client
5. See that E2E is available and can be configured

### Client configuration
Client version: 3.0.0

Operating system: Win10 1909 and 2004

OS language: de

**Comment by camilasan** [comment]
3.0.1 will fix this: #2280
