### ISSUE TITLE
Status feature in the desktop client

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2318]
We had a quick call discussing the integration of the Status feature in the different mobile apps and desktop client.

cc @georgehrke @camilasan from the call

Notes sorted from MVP to most advanced.

1. **Basic implementation, view-only:** Show the status in the subline of the currently selected account in the header (instead of the cloud domain). The status indicator icon could just show as first element of the subline instead of messing with the sync overlay icon.
2. **Ability to change the status:** In the 3-dot menu of the account, show a list of the statuses to pick (with the current one highlighted), just like in the web interface – see screenshot of statuses menu below:
    - Online
    - Away
    - Do not disturb
    - Invisible
    - (Divider line)
    - Log out
    - Remove account
3. **Set custom status:** We add a "Set custom status" after "Invisible" and clicking on it opens a separate window with the custom statuses just like in the web interface. See screenshot of "Set custom status" modal below.
4. **Icon placement:** In the desktop client we already place the sync state icon over the avatar – unfortunately this conflicts with the status icon now. The end goal should be to have this consistent and have the icon overlaying the avatar being the status icon – so we need to change it in desktop. We could move the sync icon onto the folder icon in the header of the currently active account?
5. **Do not disturb:** If the status is set to "Do not disturb", do not send operating system notifications
6. Last step: show status of the user you are sharing files with in the share dialog.

Also cc @er-vin @DominiqueFuchs for reference.

Screenshot of the statuses menu:
![image](https://user-images.githubusercontent.com/925062/91193205-1f05b600-e6f7-11ea-8764-aac8df2a4a3f.png)

Screenshot of the "Set custom status" modal:
![image](https://user-images.githubusercontent.com/925062/91193255-2e84ff00-e6f7-11ea-9945-57b3a87d6d26.png)

**Comment by camilasan** [comment]
https://gist.github.com/georgehrke/55a0412007f13be1551d1f9436a39675

**Comment by nickvergessen** [comment]
> Do not disturb: If the status is set to "Do not disturb", do not send operating system notifications

The notification endpoint has a header with the status: `X-Nextcloud-User-Status`. If that is set to `dnd`, you shouldn't trigger operating system notifications
https://github.com/nextcloud/notifications/pull/724/files?short_path=be2c9ef#diff-be2c9ef579bbe4a1f1b0009530d415fa

**Comment by jancborchardt** [comment]
> Documentation: https://gist.github.com/georgehrke/55a0412007f13be1551d1f9436a39675

Btw @georgehrke is this also somewhere in the Nextcloud docs? Otherwise we should move it over cc @rullzer @MorrisJobke?
