### ISSUE TITLE
Subfolder created in E2EE folder is not recognized as folder

### ISSUE THREAD

**Issue by basti1982** [nextcloud/desktop#2319]
### Steps to reproduce
1. Setup E2EE
2. Create folder in encrypted folder using desktop app (v3.0.0, AppImage on Debian 10)
3. Open encrypted folder in Android App
4. Created subfolder is not recognized as folder but as file

### Expected behaviour
A subfolder created in the encrypted folder with the desktop app should be recognized as folder by the Android app.

### Actual behaviour
Folders that are created within the encrypted folder using the desktop app are not properly recognized by the Android app. The Android app shows them as files. When creating a folder within the encrypted folder using the Android app, this folder is properly recognized by the desktop app.

## Server configuration detail

**Operating system:** Linux 4.15.0 nextcloud/android#1 SMP Mon Dec 9 19:36:21 MSK 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.44

**PHP version:** 

7.3.21
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 19.0.1 - 19.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, from 18

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - end_to_end_encryption: 1.5.2
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - issuetemplate: 0.6.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - richdocuments: 3.7.3
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.3
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - tasks: 0.13.3
 - text: 3.0.1
 - theming: 1.10.0
 - theming_customcss: 1.6.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - documentserver_community
 - encryption
 - files_external
 - onlyoffice
 - richdocumentscode
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.1.1",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable",
    "htaccess.RewriteBase": "\/",
    "preview_max_x": "2048",
    "preview_max_y": "2048",
    "jpeg_quality": "60",
    "preview_max_scale_factor": "10",
    "preview_filesize_image": "50",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Image",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\SVG",
        "OC\\Preview\\Font",
        "OC\\Preview\\MP3",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI"
    ],
    "loglevel": 2,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** e2ee

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** 

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

Screenshots:
![nc_android](https://user-images.githubusercontent.com/38282605/90872982-b25c8580-e39d-11ea-9c05-42a9df4229c2.jpg)

**Comment by tobiasKaminsky** [comment]
I therefore moved it to desktop repo.

**Comment by camilasan** [comment]
Still I would like to check the desktop client logs. Please run the client with --logdebug:
https://docs.nextcloud.com/desktop/2.6/troubleshooting.html#log-files

**Comment by basti1982** [comment]
Here's the log for creating a subfolder in an encrypted folder.

[nextcloud_client_log.txt](https://github.com/nextcloud/desktop/files/5134649/nextcloud_client_log.txt)

**Comment by er-vin** [comment]
The mimetype is set in propagateuploadencrypted.cpp line 177 (at time of writing this comment). This is in `PropagateUploadEncrypted::slotFolderEncryptedMetadataReceived()`.

@tobiasKaminsky to be honest, I find sad that we'd have to catch when the mimedatabase correctly gives us inode/directory (we don't determine that mimetype ourselves in fact) we'd have to "lie" and special case it to say httpd/unix-directory instead.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky to be honest, I find sad that we'd have to catch when the mimedatabase correctly gives us inode/directory (we don't determine that mimetype ourselves in fact) we'd have to "lie" and special case it to say httpd/unix-directory instead.

Yeas, this is really strange and I have no idea why we use something different on server…

**Comment by er-vin** [comment]
#2345 should fix it, that being said some extra testing would be welcome. If someone could try with the appimage which will be produced by the CI once it's done building and report how it went, it would be very welcome.
