### ISSUE TITLE
Using the e2ee feature inflates the database load

### ISSUE THREAD

**Issue by lemmy04** [nextcloud/desktop#2320]
### Expected behaviour
I'd expect the load on the database to stay more or less the same, or increase only a little bit, when there is **one** desktop client running.

### Actual behaviour
As soon as there is **one** desktop client running, the database load increases by **1000%** if the E2EE app is enabled

### Steps to reproduce
1. install the e2ee app on a server
2. start the 3.0 desktop client on linux
3. monitor your database
4. observe the number of sql queries go through the roof

Interesting side note: it is way worse when the client is running on linux, and almost nonexistent with the client running on windows.
See the attached image, which is from munin watching my database server:

at 08:05 I started the client on windows - had not been synced using 3.0 before. Stopped the client there at 08:10
at 08:20 I started the client on the same windows host again, had been synced once (see above), quit it after the statues reached "synchronistion successful"
at 08:30 I started the windows client on another windows host that had already been synced, quit it there after the statues reached "synchronistion successful", too
at 08:45 I started the linux client on a linux host that had already been completely synced before. Note the huge spike in sql queries. note: 15 minutes later the synchronisation still is not finished, several folders are still in "Waiting for other folders", and the database is still under heavy stress. Once this was finished, I restarted the client at 09:10
Note that unlike the windows client, the second run shows the same high database load - not half of it.

![mysql_queries-pinpoint=1598421600,1598427000](https://user-images.githubusercontent.com/664127/91274462-03de8900-e77f-11ea-88fb-2b2aa186f5a5.png)

### Client configuration
Client version:
3.0.0

Operating system:
openSUSE Leap 15.2

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
5.15.0

Client package (From Nextcloud or distro) (Linux only):
client package from openSUSE build service

Installation path of client:
/usr

### Server configuration
e2ee app enabled

Nextcloud version:
19.0.1 packaged for openSUSE

Storage backend (external storage):
no external storage

### Logs
1. Client logfile: 
`nextcloud --logdebug --logflush --logfile log.txt`
produces **no** output in that file at all...

2. Web server error log:
nothing in error_log except some apparmor warnings about running uncnfined

3. Server logfile: nextcloud log (data/nextcloud.log):
https://susepaste.org/77070357

**Comment by lemmy04** [comment]
turned the e2ee app off on the server and database load during syncs is back to normal. Also, syncs finish in the sort of timeframe that I'm used to.

**Comment by jospoortvliet** [comment]
Hi, can you please file this issue in the server E2EE app: https://github.com/nextcloud/end_to_end_encryption

This issue must be happening there, the desktop client can't do much about it.
You won't need it for this server issue, but wrt logging for the client - try  `nextcloud --logdebug --logfile log.tx` -> this creates a 100mb file in just a few minutes here, though I have 3 accounts and a lot of data ;-)
