### ISSUE TITLE
Desktop client does not synk videos and photos

### ISSUE THREAD

**Issue by Adriorjalesvidal** [nextcloud/desktop#2321]
Hi, 
There is a bug in the desktop nextcloud client related to synking. I will first explain the problem and next I will fill the template.

This is my setup:
Raspberry pi 3 b + with external storage HDD 1tb with nextcloud 19.0.1.1 downloaded from zip file at nextcloud official page.
iOS device with nextcloud app installed and connected to my nextcloud server.
Windows desktop with nextcloud client v3.0.0 

The nextcloud server uses /media/externo/data as nextcloud's data directory, which is a mounted /dev/sda drive, (the external usb hdd).
The nextcloud server is clean, no additional plugins are installed.

What I've done is:
I've used the iOS app to update videos and photos to the server using automatic gallery synk. The result folder was Photos (3.3 GB), with a tree of folders that references date of the pictures and videos. 
Photos
    2019
        08
        09
        10
        11
        12
    2020
        ...

As a result, in my server changes are properly displayed and if I use web interface the files are in place, but if I synk the windows client, the only thing it does is create the directories tree but none of pictures and videos are downloaded, and folders are empty.

What I've tried
I tried to force synk, to remove all limits on download, removed synk filters, reinstalled all clients, but nothing worked.
I've updated a md file from my iOS client into /photos/2019/08, and the changes were properly synchroniced and file was downloaded to my windows client in a few seconds, but videos and photos was not downloaded. 
I've copied manually from iOS client one of the videos located at photos/2019/08 and pasted it in the same folder, with no changes result. Windows client does not synchroniced the file, but web client shows the new file.
I've disabled power saving mode of the external hdd, and problem persists. 

### Expected behaviour
The expected behaviour is that windows client synk all the files without problems

### Actual behaviour
The windows client doesn't synk the files, only the tree structure is mirrored.

### Steps to reproduce
1. Update iOS gallery from iOS app to nextcloud server.
2. Check that nextcloud server have the files into it
3. Check that in a windows client, synk is not valid.

### Client configuration
Client version: Windows client 3.0.0, iOS client 3.0.5.8 

Operating system: Server: Raspberry Pi OS Buster lite, (previously known as raspbian 10 buster lite) updated

OS language: ?

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): N/A

Installation path of client: Default windows installation directory program files/nextcloud

### Server configuration

Nextcloud version: 19.0.1.1

Storage backend (external storage): local /dev/sda mounted at /media/externo and properly referenced on /etc/fstab. This data directory was properly stablished at installation time.

### Logs

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`:
2020-08-26 13:56:29:318 [ info nextcloud.gui.application ]:	"################## Nextcloud locale:[es_ES] ui_lang:[es_ES] version:[3.0.0stable-Win64 (build 20200811)] os:[Windows 10 (10.0)]"
2020-08-26 13:56:29:318 [ info nextcloud.gui.application ]:	Running for 4404.19 sec

2. Web server error log:
[Wed Aug 26 00:00:05.455129 2020] [mpm_prefork:notice] [pid 697] AH00163: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Aug 26 00:00:05.455208 2020] [core:notice] [pid 697] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 26 06:59:47.283044 2020] [php7:error] [pid 5797] [client 151.80.41.7:56500] script '/var/www/html/wp-login.php' not found or unable to stat, referer: http://www.adrins.es/wp-login.php
[Wed Aug 26 11:41:56.622819 2020] [mpm_prefork:notice] [pid 699] AH00163: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Aug 26 11:41:56.627340 2020] [core:notice] [pid 699] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 26 11:57:41.208765 2020] [mpm_prefork:notice] [pid 699] AH00169: caught SIGTERM, shutting down
[Wed Aug 26 11:58:02.981885 2020] [mpm_prefork:notice] [pid 701] AH00163: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Aug 26 11:58:02.983034 2020] [core:notice] [pid 701] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 26 12:07:27.677496 2020] [mpm_prefork:notice] [pid 701] AH00169: caught SIGTERM, shutting down
[Wed Aug 26 12:07:47.441079 2020] [mpm_prefork:notice] [pid 682] AH00163: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Wed Aug 26 12:07:47.444319 2020] [core:notice] [pid 682] AH00094: Command line: '/usr/sbin/apache2'

3. Server logfile: nextcloud log (data/nextcloud.log):
Empty

Thanks

**Comment by jospoortvliet** [comment]
Hi,
the client log should really be a LOT more - if I run with `nextcloud --logdebug --logfile log.txt` the log file is 60 mb in a few seconds!!! You will have to host that somewhere and link to it ;-)
There's no way it is just 3 lines long.

The nextcloud server log also should be VERY long - hundreds of lines at the absolute least. If it is empty, you disabled logging - which means we can't find out what is wrong. See https://docs.nextcloud.com/server/19/admin_manual/configuration_server/logging_configuration.html to configure the logging so we get helpful information.
