### ISSUE TITLE
Is it possible to compile the client without the GUI?

### ISSUE THREAD

**Issue by Hund** [nextcloud/desktop#2328]
Is it possible to compile the client without the GUI? I couldn't find anything amongst the emojis.. err, documentation.

**Comment by camilasan** [comment]
We have a command line tool:
https://docs.nextcloud.com/desktop/2.6/advancedusage.html#nextcloud-command-line-client

Otherwise when you have questions, you can ask the community for help on [help.nextcloud.com](help.nextcloud.com).

**Comment by Hund** [comment]
I know of that tool, but I don't want tons of dependencies when I don't use the GUI to begin with.

You haven't answered my question.

And thanks, but no thanks. I don't want to register another account.

**Comment by camilasan** [comment]
> You haven't answered my question. Why did you close my issue?

when you have questions, you can ask the community for help on help.nextcloud.com.

> I know of that tool, but I don't want tons of dependencies when I don't use the GUI to begin with.

The command line tool is shipped with the AppImage. I don't see why you would need to compile it (unless you would like to contribute :) or worry about dependencies. 

In any case, I never tried anything like it and I don't think it is possible to compile without the GUI. Even without the GUI you would have to deal with dependencies.

**Comment by Hund** [comment]
I see. It looks like Nextcloud went the same path as ownCloud, which is ironic considering the reason the creator forked his own project to begin with.

I guess this is non issue now then as I have to look into replacing Nextcloud with something where the developers cares about their users.

Thank you for your time!

**Comment by er-vin** [comment]
For the record, this is a duplicate of  #1339.
