### ISSUE TITLE
Nextcloud Client depends on nemo-python, which conflicts with python-nemo

### ISSUE THREAD

**Issue by JoeJoeTV** [nextcloud/desktop#2329]
### Problem
I can't install nemo-nextcloud, while having python-nemo and other nemo extensions which depend on it installed

### Steps to reproduce
1. Install python-nemo or any plugin that depends on it
2. Try to install nemo-nextcloud from the official PPA

### Client configuration
Client version: 3.0.0

Operating system: Linux Mint 20 Cinnamon 64bit

OS language: German

Client package (From Nextcloud or distro) (Linux only): nemo-nextcloud, nextcloud-desktop

Installation path of client: default

### Notes
I think nemo-python is from the ubuntu repository and python-nemo is from the linux mint repository.

**Comment by ivaradi** [comment]
I have modified to dependency to be on nemo-python or python-nemo, so hopefully it works now. The new packages for 3.0.1 are built this way. Please, test, and let me know your results.

**Comment by JoeJoeTV** [comment]
Yes, everything works now, I can install it besides all the other nemo extensions.

**Comment by JoeJoeTV** [comment]
I have the same issue again and it again wants to remove python-nemo.

**Comment by ivaradi** [comment]
I have implemented the change on the stable-3.0 branch only, and did not map it to master or stable-3.1. I have fixed this and rebuilt the 3.1.1 release version. Please, try it and let me know your results.

**Comment by JoeJoeTV** [comment]
It works again now, thanks!
