### ISSUE TITLE
Buttons Bug Client 2.6.5

### ISSUE THREAD

**Issue by meisterleise** [nextcloud/desktop#2330]
```
If you have the same issue or agree with somebody's comment, please do not add "me too" style comments. This is not helpful and makes it harder for our developers to follow the conversation. Just use the Github reactions emojis to like, agree with or disagree with comments.
```

### Actual behaviour
Since I’ve updated the the client from 2.5.3 to 2.6.5, the buttons are simple squares now. Feature or Bug?
The button for clipboard is gone. Well – it’s still there and you can click it, but it’s invisible.
Tested on 3 machines.

For better understanding a small screencast: [LINK](https://www.screencast.com/users/meisterleise/folders/Default/media/dc942b3e-cc66-4b52-876a-a4d49b9471be)

### Client configuration
Client: 2.6.5

Operating system:
System: macOS X.14.6

OS language:
de

**Comment by MoloSeb** [comment]
I can confirm the issue. The buttons are invisible. 
but they are still "there" if you know where to click.
You can for example click on the place where the copy to clipboard button would be and it will copy the link to clipboard...
So it seem to be a graphical issue.

**Comment by jospoortvliet** [comment]
Please, try version 3.0 of the client - I don't believe there will be new releases in the 2.6 series and if this problem does not exist in 3.0.1 (which will be released in an hour or so) then, well, it is solved...

**Comment by meisterleise** [comment]
Version 3.0.1 is fine. Thank you.
(I didn't realize, that there is a newer version, because the app hasn't informed for updates.)
