### ISSUE TITLE
Integrity Check Download

### ISSUE THREAD

**Issue by criwe** [nextcloud/desktop#2331]
Hi!

It would be nice to get some integrity check for the download like on https://nextcloud.com/install/#instructions-server on the download page https://nextcloud.com/install/#install-clients.

Best,
Christoph

**Comment by michaelstingl** [comment]
duplicate for https://github.com/nextcloud/desktop/issues/1510 ?

**Comment by criwe** [comment]
Yes, you are right. I close this ticket, hoping the other one won´t be ignored.
Best,
Christoph
