### ISSUE TITLE
Client 3.0 on the Mac causes desktop/space switch

### ISSUE THREAD

**Issue by TheRealTripleB** [nextcloud/desktop#2332]
### Expected behaviour
When I click on the Nextcloud icon in the toolbar on a Mac with multiple desktops/spaces, the Nextcloud window should open on the current desktop.

### Actual behaviour
On a Mac with multiple desktops, when clicking the Nextcloud icon in the toolbar the mac will always switch to the desktop where the Nextcloud.app was launched.

I already checked the com.apple.spaces.plist to see if the app is assigned to a specific desktop and I couldn't find an assignment.

### Steps to reproduce
1. launch the Nextcloud 3.0 app on the first desktop
2. change to desktop/space 2
3. click on the nextcloud symbol in the menu bar

### Client configuration
Client version: 3.0.0

Operating system:
MacOS Catalina 10.15.6

OS language:
German

Installation path of client:
/Applications/

**Comment by er-vin** [comment]
@DominiqueFuchs @misch7 @camilasan we'll need someone with a mac to test this I guess. :-)
