### ISSUE TITLE
Can't open main dialog

### ISSUE THREAD

**Issue by uusijani** [nextcloud/desktop#2333]
### Expected behaviour
Selecting "open main dialog" from the client menu brings up the main dialog.

### Actual behaviour
Selecting "open main dialog" from the client menu either does not bring up the main dialog, or brings it up only to have it disappear almost immediately. The location of the main dialog, when it does pop up, also seems random: sometimes it pops up in the top left corner of the scereen, sometimes at the center of the screen, sometimes right where the tray menu is.

If I'm quick enough to bring the mouse cursor over the main dialog when it pops up, the window seems to stay, until I take the cursor out of it, at which point the window disappears.

The settings window does still open as normal when selected, and works without issues.

### Steps to reproduce
1. Select "open main dialog" from the client ("tray") menu

### Client configuration
**Client version:** 3.0.0-20200821.171045.ff175088a-1.0~focal1

**Operating system:** Ubuntu 20.04 (using Wayland)

**OS language:** Finnish

**Qt version used by client package (Linux only, see also Settings dialog):** Don't know where to find that. The settings dialog only says "Version 3.0.0 (Ubuntu)" AFAICT.

**Client package (From Nextcloud or distro) (Linux only):** Don't understand the question.

**Installation path of client:** /usr/bin/nextcloud

### Logs

The client debug log from the time of trying to open the main dialog shows this:

    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowReferencePoint ]:  screenRect: QRect(0,0 2560x1440)
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowReferencePoint ]:  taskbarRect: QRect(0,0 2560x32)
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowReferencePoint ]:  taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowReferencePoint ]:  trayIconCenter: QPoint(73,507)
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowPosition ]:        taskbarScreenEdge: OCC::Systray::TaskBarPosition::Top
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowPosition ]:        screenRect: QRect(0,0 2560x1440)
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowPosition ]:        windowRect (reference) QRect(-127,36 401x511)
    2020-08-28 19:50:04:856 [ debug nextcloud.gui.systray ] [ OCC::Systray::computeWindowPosition ]:        windowRect (adjusted ) QRect(4,36 401x511)
    2020-08-28 19:50:04:859 [ warning default ]:    qrc:/qml/src/gui/tray/UserLine.qml:46: TypeError: Type error
    2020-08-28 19:50:04:861 [ warning default ]:    qrc:/qml/src/gui/tray/UserLine.qml:46: TypeError: Type error
    2020-08-28 19:50:04:863 [ warning default ]:    qrc:/qml/src/gui/tray/UserLine.qml:46: TypeError: Type error
    2020-08-28 19:50:04:865 [ warning default ]:    qrc:/qml/src/gui/tray/UserLine.qml:46: TypeError: Type error
    2020-08-28 19:50:04:868 [ info nextcloud.sync.accessmanager ]:  2 "" "https://(MY SERVER URL)/ocs/v2.php/apps/notifications/api/v2/notifications?format=json" has X-Request-ID "b0e242bb-588d-455f-a53d-066d8d0b9f42"
    2020-08-28 19:50:04:868 [ debug nextcloud.sync.cookiejar ]      [ OCC::CookieJar::cookiesForUrl ]:      (REDACTED)
    2020-08-28 19:50:04:869 [ info nextcloud.sync.networkjob ]:     OCC::JsonApiJob created for "https://(MY SERVER URL)" + "ocs/v2.php/apps/notifications/api/v2/notifications" "OCC::ServerNotificationHandler"
    2020-08-28 19:50:04:886 [ warning default ]:    qrc:/qml/src/gui/tray/Window.qml:473:17: QML MouseArea: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
    2020-08-28 19:50:04:886 [ warning default ]:    qrc:/qml/src/gui/tray/Window.qml:496:17: QML Image: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
    2020-08-28 19:50:04:886 [ warning default ]:    qrc:/qml/src/gui/tray/Window.qml:510:17: QML Column: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
    2020-08-28 19:50:04:886 [ warning default ]:    qrc:/qml/src/gui/tray/Window.qml:547:17: QML Button: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
    2020-08-28 19:50:04:886 [ warning default ]:    qrc:/qml/src/gui/tray/Window.qml:487: ReferenceError: hovered is not defined

Meanwhile, in syslog from the time:

    Aug 28 19:50:04 saegusa gnome-shell[4105]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x4200016 specified for 0x4200014.
    Aug 28 19:50:31 saegusa gnome-shell[4105]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x4200016 specified for 0x4200014.
    Aug 28 19:50:35 saegusa gnome-shell[4105]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x4200016 specified for 0x4200014.
    Aug 28 19:50:47 saegusa kernel: [17841.949249] nextcloud[55212]: segfault at ffffffffffffffff ip 00007f2b3b765671 sp 00007ffe18796c78 error 5 in libgobject-2.0.so.0.6400.3[7f2b3b737000+36000]
    Aug 28 19:50:47 saegusa kernel: [17841.949258] Code: b5 2c 02 00 48 8b 34 d8 eb b6 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 f3 0f 1e fa 48 85 ff 74 4f 48 8b 07 48 85 c0 74 47 <48> 8b 00 48 3d fc 03 00 00 76 1c 48 83 e0 fc 0f b6 50 14 45 31 c0

**Comment by uusijani** [comment]
Updated client to 3.0.1 and the issue persists.

**Comment by er-vin** [comment]
Hm, looks like a wayland specific issue to me. Looks like the client is segfaulting somehow if you could get us a clean backtrace with debug symbols installed this would help.

**Comment by uusijani** [comment]
I tried [enabling the main/debug component for the PPA](https://wiki.ubuntu.com/DebuggingProgramCrash#Installing_dbgsym_packages_from_a_PPA), but it just results in a bunch of "repository […] doesn't have the component 'main/debug'" errors when I run `apt update`. Should I open a separate issue about it?

**Comment by er-vin** [comment]
@ivaradi any idea about the debug syms in the PPA?

**Comment by ivaradi** [comment]
The building of the debug symbol packages was not enabled in the PPA, and actually I didn't even know that there is a simple checkbox for it. (One usually has to explicitly define the exta packages with debug symbols and then strip the binaries only in the non-debug packages.)

Nevertheless, I have enabled it for the alpha repo for the time being, to see whether it really works and what it does.

**Comment by ivaradi** [comment]
It has worked for the alpha repo, so I enabled it on the other two, and have rebuilt version 3.0.1 for the main repo. 

@uusijani could you, please, try it and let me know if the debug symbol packages work.

**Comment by uusijani** [comment]
Yup, it's working now, thanks @ivaradi! Installed the -dbgsym packages and reproduced the segfault, [here's the gist](https://gist.github.com/uusijani/3c4dc07fe1fa7effef107f245fd0c66f).

(TBH, I'm just cargo culting [from the wiki](https://wiki.ubuntu.com/Backtrace#Generation) here, so I have no idea if this result is useful, but I do have a fairly solid way of triggering the issue, so just let me know if I should do something differently.)

**Comment by er-vin** [comment]
I have an idea, but that's a bit a shot in the dark... @ivaradi if I make a PR to try to address this, do you have a way to roll a package with the content of that PR on top so that @uusijani can test?

AFAIK we don't build our AppImage with cloudproviders support so my change wouldn't be in the AppImage produced by the CI (and also it's unlikely to exhibit the crash which is really in the cloudproviders specific code).

**Comment by ivaradi** [comment]
@er-vin I can build a normal package (i.e. without debug symbols) quite easily, though I am not sure how I can get it to @uusijani . Or I can probably build a package in the alpha PPA repository, but then it should be installed relatively quickly, before it gets overwritten by the automatic build on master.

**Comment by er-vin** [comment]
Sounds like some trouble indeed... unsure how best to proceed...

**Comment by uusijani** [comment]
I'm up for testing those packages. Would Github allow you to attach a deb to a comment here (perhaps wrapped in [a Zip file](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests))?

**Comment by ivaradi** [comment]
I cannot see a way to attach files to a comment.

However, I could set an "experimental" repo on Launchpad and run the build in a way that the packages are uploaded there. This way you could configure that repo temporarily and install the package from there. Could this work for you?

**Comment by uusijani** [comment]
Sure, that sounds doable. 👍

**Comment by Buri** [comment]
I'm also suffering from this problem, running OpenSUSE Tumbleweed (20200915) (Gnome/Wayland)

**Comment by olaulau** [comment]
same problem for me.
debian testing, using ppa repository.
the appimage is ok.

**Comment by tux93** [comment]
I'm facing a similar issue on openSUSE Tumbleweed with Xfce, being unable to open the main dialogue is especially annoying since the Activity feed and Details for sync conflicts are no longer viewable through the Settings window

Client version is 3.0.2

**Comment by er-vin** [comment]
> I'm facing a similar issue on openSUSE Tumbleweed with Xfce, being unable to open the main dialogue is especially annoying since the Activity feed and Details for sync conflicts are no longer viewable through the Settings window
> 
> Client version is 3.0.2

You get the crash in gobject as well?

**Comment by tux93** [comment]
I do not see any `gui.systray` messages with `nextcloud --logdebug -l`

I do get the gobject crash in `journalctl`, but only when exiting the client with right click on the tray icon, not when trying to open the main dialog
```
Oct 19 11:27:30 Home kernel: nextcloud[11746]: segfault at ffffffffffffffff ip 00007f4d204d0bad sp 00007fff94148438 error 5 in libgobject-2.0.so.0.6400.6[7f4d204aa000+2f000]
Oct 19 11:27:30 Home kernel: Code: 02 48 8d 05 15 3b 02 00 48 8b 34 d8 eb b6 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 85 ff 74 4b 48 8b 07 48 85 c0 74 43 <48> 8b 00 48 3d fc 03 00 00 76 18 48 83 e0 fc 0f b6 50 14 45 31 c0
```

**Comment by manfredu** [comment]
I had a similiar issue on Void Linux, where I could not open the main window. I had to install the package qt5-graphicaleffects to solve the issue.

(S.a. https://github.com/nextcloud/desktop/issues/2390)

**Comment by tux93** [comment]
> I had a similiar issue on Void Linux, where I could not open the main window. I had to install the package qt5-graphicaleffects to solve the issue.
> 
> (S.a. #2390)

Thank you, searching for missing modules in the log revealed that I was missing `QtGraphicalEffects` and `QtQuick.Controls`.
Opened a downstream issue for the openSUSE here: https://bugzilla.opensuse.org/show_bug.cgi?id=1178209

**Comment by robeke** [comment]
I have a possibly related/same issue on Manjaro/Xfce with Nextcloud 3.0.3-1.  Although I am able to reliably open the main dialog, it causes `systemd-coredump[38612]: [🡕] Process 30559 (nextcloud) of user 1000 dumped core`.  This is followed by a lengthy stack trace of thread 30559 that starts with libgobject-2.0.so.0 and continues with remaining entries referencing libQt5Core.so.5.  If you think it could help, I could work on providing the full stack trace.

**Comment by weierophinney** [comment]
I'm observing this on Ubuntu 20.10, using Gnome Shell 3.38 on X.org. I have qml-module-qtgraphicaleffects and qml-module-qtquick-controls2 both installed. When I run the client with the `--logdebug` switch from a terminal, I don't see any additional information.

**Comment by curbengh** [comment]
Same issue on Ubuntu 20.10, MATE 1.24.1 with client 3.1.1-20201225.075704.75c329f4f-1.0~groovy1 (installed from [official PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client)). `nextcloud-desktop` has a missing dependency `qml-module-qtqml`. Installing it resolves the issue (also mentioned in https://github.com/nextcloud/desktop/issues/2390#issuecomment-702004776).

**Comment by nilsfr** [comment]
I can not install nextcloud-desktop on Ubuntu 20.04 using PPA: ppa.launchpad.net/nextcloud-devs/client/ubuntu
It requires a dependency called `qml-module-qtqml` that do not exits. However, there is a package called `qml-module-qtqml-models2`. Is it possible that qml-module-qtqml is the wrong dependency? I cannot find it for Debian either.

**Comment by ivaradi** [comment]
I have added the dependency on `qml-module-qtqml` for all distributions including Focal (20.04). However, it seems that this package was introduced only in Groovy, and does not exist in Focal. So I have just removed the dependency from Focal and the builds are underway. 

However, 20.10 should be OK now.

**Comment by er-vin** [comment]
@ivaradi can this be closed then now?

**Comment by ivaradi** [comment]
I think, yes. So closing it.
