### ISSUE TITLE
3.0.1 missing accounts button on ubuntu focal

### ISSUE THREAD

**Issue by mbogner** [nextcloud/desktop#2334]
On Ubuntu Focal with latest updates and latest version of the PPA desktop client (3.0.1) the gui refuses to add or edit clients. Maybe I missed some integration but I only managed to add my second nextcloud account via editing ./config/Nextcloud/nextcloud.cfg. I am used to have a accounts button above the folder sync section but its just missing.

```
manuel@fury:~$ sudo apt update && sudo apt dist-upgrade -y
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Hit:2 http://at.archive.ubuntu.com/ubuntu focal InRelease                                                                                  
Hit:3 https://download.docker.com/linux/ubuntu focal InRelease                                                                             
Hit:4 http://at.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                          
Hit:5 https://apt.releases.hashicorp.com focal InRelease                                             
Hit:6 http://at.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:7 http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal InRelease    
Fetched 107 kB in 1s (80,8 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
```
manuel@fury:~$ dpkg -l nextcloud-*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                     Version                                    Architecture Description
+++-========================-==========================================-============-================================================
un  nextcloud-client         <none>                                     <none>       (no description available)
un  nextcloud-client-l10n    <none>                                     <none>       (no description available)
ii  nextcloud-desktop        3.0.1-20200828.171413.0a62628f8-1.0~focal1 amd64        Nextcloud folder synchronization tool
ii  nextcloud-desktop-common 3.0.1-20200828.171413.0a62628f8-1.0~focal1 all          Nextcloud folder synchronization - common data
ii  nextcloud-desktop-doc    3.0.1-20200828.171413.0a62628f8-1.0~focal1 all          Nextcloud folder synchronization - documentation
ii  nextcloud-desktop-l10n   3.0.1-20200828.171413.0a62628f8-1.0~focal1 all          Nextcloud folder synchronization - localization
```
I consider it to be a bug but maybe I just missed an integration somewhere and I am supposed to configure it in another way on Linux?
![Screenshot from 2020-08-28 21-07-47](https://user-images.githubusercontent.com/53990/91606768-fa1d7700-e972-11ea-882f-67bc57bf5dba.png)

**Comment by er-vin** [comment]
This is now on the main dialog this is why you don't find that button here anymore. Closing it.

**Comment by mbogner** [comment]
@er-vin Thx. Found it.

My 2 cents: Not really intuitive on ubuntu 20.04. Need to click the tray icon and chose open main dialogue. Normally I consider being able to configure an application in its settings menu where this is was removed from.

**Comment by nightsparc** [comment]
@er-vin 
Sorry, but full ack to @mbogner

Its totally counter-intuitive, especially resolving conflicts is really, really hard.

I'm on Ubuntu 18.04 btw.

I mean, this silly main window vanishes whenever I'm leaving focus on it. Even taking a simple screen is basically impossible, since a key or mouse press leaves the focus of this thing.

How the hell should I get _any_ information on the conflict? The shown path is much too short to see the filename. I mean, 4 levels of directories (with _short_ names! About 20 chars each!) are not really that much...

**Comment by thomasboehm** [comment]
"Open main dialog" doesn't do anything here. No window, nothing. Xubuntu 20.04, upgraded to 20.10, Nextcloud client 3.0.2 from the PPA.

**Comment by sylvaticus** [comment]
Same as @thomasboehm : maybe we should open a separate bug report. On ubuntu 20.04 20.04, client 3.4.0 (ubuntu) the "Open main dialog" action does nothing.

**Comment by wujastyk** [comment]
+1 for "Open main dialog" action does nothing.
