### ISSUE TITLE
memory usage of 3.0 client grows in time

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#2335]
**If you have the same issue or agree with somebody's comment, please do not add "me too" style comments. This is not helpful and makes it harder for our developers to follow the conversation. Just use the Github reactions emojis to like, agree with or disagree with comments.**

### Expected behaviour
Memory usage should remain relatively stable

### Actual behaviour
after starting, the client very quickly grows to about 120 mb. After half a day it is 500 mb, and in a day, about 1700. Memory leak?

### Steps to reproduce
1. start the client
2. wait ;-)
3.

### Client configuration
Version 3.0

Operating system:
openSUSE

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
Built from Git revision ff1750 using Qt 5.15.0, OpenSSL 1.1.1g 21 Apr 2020

### Server configuration
I have 3 accounts configured.
* cloud.nextcloud.com (nc 19 latest, no E2EE)
* cloud.josandcamila.com:444 (nc 19 latest, no E2EE)
* techpreview.nextcloud.com  (nc 19 beta, no E2EE)

Storage backend (external storage):
Variety of storages...

### Logs

1. Client logfile: 
So... I ran the client with `nextcloud --logdebug --logfile log.txt` and in a few hours, it generated a 4.5gb file. I compressed it with zip and with LRZip - pick which one you want ;-)
https://cloud.nextcloud.com/s/pnjWTHCeLK3HGRa

2. Web server error log:
If you need it I can look in my private server, or we ask the Nc sysadmins.

3. Server logfile: nextcloud log (data/nextcloud.log):
If you need it I can look in my private server, or we ask the Nc sysadmins. But I'm hoping my massive client log will give some hints...

**Comment by er-vin** [comment]
Yes this is leaking, as far as I know it's not new (2.6 had similar issues). Can't seem to remember where the other report is...

Can't exclude 3.0 introduced new leaks of course, for sure it got a few fixed. ;-)

We hopefully get more fixed in the coming cycles.

**Comment by TheNomad11** [comment]
same issue with 3.0.1. , now it was using 950 MB (on Linux Mint 20)
2.6.5 is fine, ram usage stays the same, below 200 MB, will continue using that version therefore

**Comment by er-vin** [comment]
Note that one of those leak fixes will make it to 3.0.3. Please let us know how it improves the situation for you.

**Comment by simonspa** [comment]
I will check 3.0.3 out as soon as it is released because for me the situation is a lot worse than the reports above:

![image](https://user-images.githubusercontent.com/1677436/94572894-cedbbf80-0271-11eb-99a8-85fb39a5a6bd.png)

8G ram reserved after just 6h of running

**Comment by er-vin** [comment]
If you don't want to wait and report early you might want to try the appimage linked from #2479. This is pretty much 3.0.2 + the patch I had in mind.

**Comment by kescherCode** [comment]
After initially consuming ~200 MiB of RAM, this RAM usage rises to ~1.8 GiB in a matter of hours. This is a severe memory leak indeed. 2 accounts configured on each machine observed to be affected.

**Comment by er-vin** [comment]
> After initially consuming ~200 MiB of RAM, this RAM usage rises to ~1.8 GiB in a matter of hours. This is a severe memory leak indeed. 2 accounts configured on each machine observed to be affected.

Please don't tell me it's not with master or the appimage I was mentioning earlier... Which version is this?

**Comment by kescherCode** [comment]
@er-vin No, that's just the latest release obtainable via normal ways. I don't feel like using AppImages, to be honest.

**Comment by er-vin** [comment]
> @er-vin No, that's just the latest release obtainable via normal ways. I don't feel like using AppImages, to be honest.

That's OK. Please test again with 3.0.3 when it's out.

**Comment by newHeiko** [comment]
> If you don't want to wait and report early you might want to try the appimage linked from #2479. This is pretty much 3.0.2 + the patch I had in mind.

Feedback: I patched my 3.0.2 client with the patch from #2479. Instead of growing to ~12GB memory usage within three days before I killed it, it now fluctuates between ~2GB and ~3GB for the last three days - much better :-)

This is on Slackware Linux current, 5.4.72 kernel, qt 5.15.1 with one server, about 1200GB / 750.000 files in two folders.

Thanks,
Heiko

**Comment by er-vin** [comment]
Thanks for letting us know.
