### ISSUE TITLE
[3.0.1] Dialog at start asks for a pass...

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/desktop#2337]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
No dialog box

### Actual behaviour
Tell us what happens instead

![20200828-153526](https://user-images.githubusercontent.com/2804301/91635131-19a9b380-e9f6-11ea-83c5-1cd7b1c8dfd0.png)

### Steps to reproduce
1. Start nextcloud desktop sync client (Linux Mint 20 Cinnamon)
2. Sometimes after start or resume a dialog asking for a mey opens

### Client configuration
Client version: 3.0.1

Operating system: Linux Mint 20 Cinnamon

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): darkwing@darkwing-Lenovo-V110-15ISK ~ $ cat /etc/apt/sources.list.d/nextcloud-devs-client-focal.list 
deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main
# deb-src http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main

Installation path of client:

### Server configuration

Nextcloud version: 19

Storage backend (external storage): -

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
https://www.dropbox.com/s/qa0atx29r82jjet/nc.log?dl=0

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by criwe** [comment]
Same here.
I've got more accounts to sync (one nextcloud installation with e2ee enabled).
Linux client ask for the mnemonic for every account even when there's no e2ee folder.

The one with an e2ee folder doesn't accept my mnemonic...  
In the e2ee folder some files like "._abc.~2e1230d5" with 0 kb occur. I think with every try to enter the mnemonic a new one show up?!

Best,
Christoph
(Debian in my case)
