### ISSUE TITLE
Cannot react to notification in windows client app

### ISSUE THREAD

**Issue by wojcik13** [nextcloud/desktop#2339]
Hi,
in my Nextcloud configuration I’m using notification in order to confirm login attempt, so that login can be authenticated only from single device. Everything is working perfectly, but I’m moving from one device to another and have installed the newest version of Nextcloud Win client (3.0). In this app (on my admin device) while logging in (on other device), I see notification about login attempt, but I cannot respond to that. In the previous version (2.6.5) it was possible, but in the newest I can’t see this button to accept or decline login attempt.

Windows 10, Nextcloud client 2.6.5
![nextl](https://user-images.githubusercontent.com/17380779/91659500-492cee80-ead0-11ea-8584-a9c01539bb23.png)

Windows 10, Nextcloud client 3.0
![nextm](https://user-images.githubusercontent.com/17380779/91659509-5649dd80-ead0-11ea-8d16-4bab3bf34701.png)

Is it normal? :thinking:
Best regards

**Comment by codesmaker** [comment]
Same thing here. I can't find a way to react with the Nextcloud notification.

Nextcloud v3.0 on Ubuntu 20.04

**Comment by er-vin** [comment]
@DominiqueFuchs @jancborchardt opinions on that?

**Comment by codesmaker** [comment]
Any news on this issue?

**Comment by wojcik13** [comment]
Not, that I'm aware of. Maybe @er-vin @DominiqueFuchs @jancborchardt have some developments on that?

**Comment by DominiqueFuchs** [comment]
> @DominiqueFuchs @jancborchardt opinions on that?


@er-vin Not sure what opinion is needed from me here.. To make this work, someone would have to implement it - adding a corresponding action to this type of activity, just like for the different type of activities already differentiated by now.

**Comment by er-vin** [comment]
> > @DominiqueFuchs @jancborchardt opinions on that?
> 
> @er-vin Not sure what opinion is needed from me here.. To make this work, someone would have to implement it - adding a corresponding action to this type of activity, just like for the different type of activities already differentiated by now.

Well, you moved over that code into QML land, so I assumed you had insights on how it was done before and what's missing now. But also how it should be presented.

Will need to be investigate further I guess.

**Comment by jancborchardt** [comment]
> how it should be presented.

Basically just like it is in the settings dialog, except accounting for the limited space in the main dialog. The actions on the right would be:
- icon-info for "More information" (make sure to set alt text there) to link to the server for more information on that.
- 3-dot menu with "Accept login" and "Decline login".

**Comment by er-vin** [comment]
Should be solved by @allexzander work in 3.1.
