### ISSUE TITLE
"Host your own server" not translatable (in Transifex)

### ISSUE THREAD

**Issue by keunes** [nextcloud/desktop#2340]
"Host your own server" is not translated in Dutch in the latest desktop client. Checking Transifex, I couldn't find the string for the desktop client - only for the iOS and Android clients.

**Comment by bene64** [comment]
So it seems this [string](https://github.com/nextcloud/desktop/blob/master/src/gui/wizard/owncloudsetupnocredspage.ui#L433) was set to not translatable with https://github.com/nextcloud/desktop/commit/cd89efc24b9dc699c889d2a5a89710a8d9ad3d67.

**Comment by keunes** [comment]
Thanks for identifying that! I guess this was set to not-translatable given the HTML code in the string(?)

If someone gets at it, I guess the link to the docs should be updated also, so that it uses `latest` rather than an actual version number: `https://docs.nextcloud.com/server/latest/admin_manual/installation/index.html`

**Comment by keunes** [comment]
I'll tell you what bit: it's still an issue, even without new details.

**Comment by FlexW** [comment]
@keunes The code in that area has much changed. The string is not anymore in rich text format and is marked translatable. The actual string can be found [here](https://github.com/nextcloud/desktop/issues/2340#issuecomment-799194943) in code. That should solve the issue or do I miss something?

**Comment by bene64** [comment]
Yup, seems like the string got translated yesterday: https://github.com/nextcloud/desktop/blob/master/translations/client_nl.ts#L4557. Seems this should be included in the next release.

@FlexW your link to the actual string points to your comment instead of the source code.

**Comment by FlexW** [comment]
@bene Sorry my mistake. I corrected it. Then I will close this issue.

**Comment by keunes** [comment]
Great, thanks both!
