### ISSUE TITLE
Windows Shell Extensions not showing Next Cloud menu in some folders in sync folder

### ISSUE THREAD

**Issue by kevin-glendenning0** [nextcloud/desktop#2341]
### Expected behaviour
Windows Shell Extensions shows Next Cloud menu in right click in ALL sync folders and sub-folders

### Actual behaviour
Windows Shell Extensions only shows Next Cloud Menu in the sync folder only and none of the sub-folders

### Steps to reproduce
1) right click in ANY Next Cloud sync sub-folder

### Client configuration
Client version: 2.6.5

Operating system: Windows 10 Home Edition

OS language: English(US)

Installation path of client:
 Default

**Comment by misch7** [comment]
Starting with the 3.0.1 release, we have made significant changes to the Windows shell extensions:

- They now have their own GUIDs (CLSIDs), to not conflict with ownCloud and custom builds
- MSVC Redist runtime DLLs are no longer required (static linking)
- Names have been changed, e.g. from `OCOverlays` to `NCOverlays`

Please upgrade to 3.0.1 and note that you will have to reboot after installation to make the extensions work:
https://github.com/nextcloud/desktop/releases/tag/v3.0.1

**Comment by er-vin** [comment]
Please let us know if the situation improved on that one after upgrading to 3.0.1.
