### ISSUE TITLE
Deleting e2ee folder failed?

### ISSUE THREAD

**Issue by criwe** [nextcloud/desktop#2342]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Create folder on computer
2. Encrypt it via App (Win, 3.0.1)
3. Delete encrypted folder an pc

### Expected behaviour

Folder should be removed online too

### Actual behaviour
Folder is not removed.
Errormessage in log: "OCA\DAV\Connector\Sabre\Exception\Forbidden: Write access to end-to-end encrypted folder requires token - no token sent" (see details below)

### Server configuration

**Operating system:**

Linux 4.4.0-187-generic x86_64 (shared hosting)

**Web server:**
?

**Database:**
mysql 5.7.28 

**PHP version:**
7.2.30

**Nextcloud version:** (see Nextcloud admin page)
19.0.2

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Nextcloud log (data/nextcloud.log)

```
[webdav] Fatal: OCA\DAV\Connector\Sabre\Exception\Forbidden: Write access to end-to-end encrypted folder requires token - no token sent at <<closure>>

0. nextcloud/apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php line 153
   OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->verifyTokenOnWriteAccess(OCA\DAV\Connector\Sabre\Directory {}, null)
1. nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
2. nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 458
   Sabre\DAV\Server->emit("beforeMethod:DELETE", [Sabre\HTTP\Requ ... }])
3. nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
5. nextcloud/apps/dav/lib/Server.php line 320
   Sabre\DAV\Server->exec()
6. nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. nextcloud/remote.php line 167
   require_once("/www/htdocs/w01 ... p")

DELETE /remote.php/dav/files/xxxxxxxxx/e2ee-ordner
from 12.123.12.12 by xxxxxxxxx at 2020-08-29T14:36:16+00:00
```

Best,
Christoph

**Comment by er-vin** [comment]
Looks like desktop specific indeed so transferred the issue.

Would it also be possible to get desktop client debug logs during the removal? Would be done using --logfile and --logdebug on the command line. Thanks in advance.

**Comment by criwe** [comment]
Hi @er-vin,
could you please provide additional info how to get the logfiles. Maybe stupid questions: commandline on the pc (maybe possible) or server (no possible there). Or do I need to start the client with the command (--logfile / --logdebug)?
Thanks!
Best,
Christoph

**Comment by er-vin** [comment]
You would need to quit your client and then from the command line locally start the client, e.g. with something like `nextcloud --logdebug --logfile C:\nextcloud_client.log` in a terminal (assumed Windows and that nextcloud was in your path, if not you might want to cd in the installation directory of the client first).

**Comment by er-vin** [comment]
Thanks, that's definitely useful data. Unsure when we'll get to it (rather swamped at the moment) but your efforts will definitely help nailing it down.

Just to be sure I read that correctly "encrypted_folder" is the most top-level encrypted folder right? It is not a subfolder of another encrypted folder?

Because I see that `PropagateRemoteDelete` should handle the encrypted subfolder case just fine, but at a glance the check looks wrong for the top most encrypted folder...

**Comment by jkahrs** [comment]
> Just to be sure I read that correctly "encrypted_folder" is the most top-level encrypted folder right? It is not a subfolder of another encrypted folder?

That's correct "encrypted_folder" was created within the topmost sync directory ("$HOME/Nextcloud4") with no other (encrypted or non-encrypted) folders above. In other words its absolute path was "$HOME/Nextcloud4/encrypted_folder"

**Comment by er-vin** [comment]
OK, so could you please confirm that removing a subfolder in there is fine and just "encrypted_folder" is affected? At least that'd be very much aligned with what I suspect.

**Comment by jkahrs** [comment]
> OK, so could you please confirm that removing a subfolder in there is fine and just "encrypted_folder" is affected? At least that'd be very much aligned with what I suspect.

Can confirm.
Creating and deleting "$HOME/Nextcloud4/unencrypted_folder" works
Creating and deleting "$HOME/Nextcloud4/encrypted_folder/subfolder" works

**Comment by er-vin** [comment]
You meant "doesn't work" for the first one, right? Otherwise I'm very confused. :-)

**Comment by jkahrs** [comment]
No, creating and deleting "normal" folders alongside the encrypted folder seems working

```bash
~/Nextcloud4 ❯❯❯ tree -L 1                                                                                                                                                                                                                                                          
.
├── Documents
├── encrypted_folder
├── Nextcloud intro.mp4
├── Nextcloud Manual.pdf
├── Nextcloud.png
├── Photos
└── unencrypted_folder
```

**Comment by er-vin** [comment]
Ah yes... I misread "unencrypted" as "encrypted"... my bad...
