### ISSUE TITLE
Client 3.0.1 (macOS): Settings no accessible with a couple of accounts

### ISSUE THREAD

**Issue by AlexanderWillner** [nextcloud/desktop#2343]
### Expected behaviour
As a users, I want to be able to open the setting of the desktop client (3.0.1.) on macOS (10.14.6).

### Actual behaviour
As a couple of accounts have been setup, the "settings" field is not visible (it's cropped after "pause sync for all"). It is also not possible to scroll with the mouse to the settings. Workaround: navigate to settings via keyboard arrows (figured this out after a while).

### Steps to reproduce
1. Open the desktop client
2. Click on the menu bar icon
3. Try to click on settings

### Client configuration
Client version: 3.0.1
Operating system: macOS 10.14.6
OS language: English
Installation path of client: default (/Applications)

### Server configuration
n/a

### Logs

n/a

### Other information

Screenshot:

![Untitled-2](https://user-images.githubusercontent.com/307605/91693136-dae93a00-eb6a-11ea-8d9a-0c35610f2f7e.jpg)

**Comment by jancborchardt** [comment]
Much like the app list in the right of the header, this menu should also simply be scrollable. :)
