### ISSUE TITLE
Linux Desktop Client - Sync deletes all content if folder is unmounted

### ISSUE THREAD

**Issue by Doc-Saintly** [nextcloud/desktop#2350]
The use case is syncing your Nextcloud to an external drive so you have a local copy. The default sync behavior is different between Windows and Linux. Using the same steps can result in all files being deleted when using the Linux client.

### Expected behaviour
If I have a folder sync connection to a mounted drive, it should not do anything if that drive is unmounted.

### Actual behaviour
If you start Nextcloud on Linux with an unmounted folder sync connection, it will assume all files have been deleted and delete all the files on the Nextcloud side.

On the Windows client, it detects that the drive is unavailable and does not sync anything. This is the desired result.

### Steps to reproduce
1. Mount a drive to a path, e.g. `/media/nextcloud`
2. Create a folder sync pair from `/media/nextcloud` to your Nextcloud root
3. Unmount the drive (by restarting, removing the USB device, or any other method)
4. Start Nextcloud
5. Watch all of your files get wiped from Nextcloud

### Client configuration
Client version: 3.0.1

Operating system: Linux Mint 20

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): nextcloud Appimage

Installation path of client: Desktop

**Comment by er-vin** [comment]
Pretty much look like a duplicate of #2233

Different OS but in the same way based on the sync folder availability. I'll close as duplicate.

**Comment by Doc-Saintly** [comment]
I would say this is not a duplicate; that task requires a user to actively do something (disconnect a device while it's syncing). In this task, if you have an external drive that requires a password and you have Nextcloud set to auto start, the next time you boot your computer it will wipe out all of the files because the drive will not be mounted. This requires no special action or unsafe behavior (removing drives while in use is bad, Mmkay?)

Also, the same exact steps in this task will work just fine on Windows, but will fail in Linux. Task 2233 would have the same result on both Windows and Linux.

They are very closely related (how does Nextcloud deal with a missing folder), and if they are both resolved at the same time then that's great - but can the other task be updated to handle this specific case?

**Comment by er-vin** [comment]
Right, I see what you mean, let's reopen here then.

**Comment by audunmg** [comment]
The client seems to already be able to ask for confirmation when something happens, perhaps add an option there?

- [ ] Ask for confirmation when deleting root folder

**Comment by ballerhu** [comment]
Got the same issue with an encrypted volume which shall not be mounted automatically after rebooting the server.
After some trying I found that it seems to work as expected by making the mountpoint unreadable for the webserver 
(apache in my case):
- umount <mountpoint>
- chown root:root <mountpoint>
- chmod 700 <mountpoint>
- mount <mountpoint>

**Comment by Doc-Saintly** [comment]
What action needs to happen to help get this added as a bug that needs to be fixed?

**Comment by FlexW** [comment]
@Doc-Saintly You can become a paying customer of Nextcloud then this bug will become top priority. If you don't want that, you can fix that issue yourself and provide a pull request :)

**Comment by FlexW** [comment]
No, unfortunately there is no other way.
