### ISSUE TITLE
[3.0.1] Unclear Message without any information

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/desktop#2352]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Should at least tell somezhing useful

### Actual behaviour
Message without any sense
![image](https://user-images.githubusercontent.com/2804301/91991484-3a924180-ed33-11ea-8203-3f7686cc3d9d.png)

### Steps to reproduce
1. ? Apeared after resume of laptop
2.
3.

### Client configuration
Client version: 3.0.1

Operating system: Linux Mint 20 Cinnamin

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 19

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by MegaV0lt** [comment]
Still the same  with 3.0.2
![2020-11-04_08-31](https://user-images.githubusercontent.com/2804301/98088613-f251e580-1e81-11eb-9410-725ce0e66750.png)

**Comment by er-vin** [comment]
We would likely need client logs to figure out what that is, we don't have enough information to qualify it so far.
