### ISSUE TITLE
3.0.1: does not use standard KDE Plasma desktop font size for main window

### ISSUE THREAD

**Issue by martin21** [nextcloud/desktop#2354]
### Expected behaviour
New Nextcloud client main window uses standard font size of KDE Plasma Desktop.

### Actual behaviour
New Nextcloud client main window uses a font size that is difficult to read on ~143 dpi display.

If I select "Settings" I get back the usual window with has the correct font size.

### Steps to reproduce
1. Install Nextcloud Client 3.0.1
2. Open it from the system tray

### Client configuration
Client version: 3.0.1

Operating system: Debian Unstable

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.14.2

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: /usr/bin/nextcloud

### Logs

1. Client logfile: 

Nope! Contains sensitive data like which Nextcloud instances I use and which local folders they are synced to and whatever else. If you need something from the log, please say which part do you need. I tried to skim through the log, but with debug log level it is very much.

I am not sure whether the log would even matter for this kind of bug. Please reconsider this hard requirement, cause it requiring sharing potentially sensitive data does not match the kind of privacy approach I know and expect from Nextcloud. Thanks.

**Comment by martin21** [comment]
Needed to unblock some user asset URL with uMatrix to be able to upload this:

<img width="169" alt="nextcloud-client-3 0 1-anonymized" src="https://user-images.githubusercontent.com/114577/92095206-e2a41b00-edc4-11ea-8af2-ae24f648cb88.png">

**Comment by er-vin** [comment]
For now we're purposefully forcing out the platform theme because of bugs in qq2-desktop-style. Once this resolves there we can reevaluate the possibility to let the platform theme which will inherit the font properly.

**Comment by sunjam** [comment]
Same issue on XFCE Ubuntu 20.04 with 3.0.1 desktop client.  System theme and font are not adopted by desktop client main dialog.

**Comment by claucambra** [comment]
Hi, this was addressed with https://github.com/nextcloud/desktop/pull/3907 and the main tray dialog now uses system font sizing. Thanks for reporting!
