### ISSUE TITLE
3.0.1: Main window uses client side decorations, window not movable under KDE Plasma with KWin

### ISSUE THREAD

**Issue by martin21** [nextcloud/desktop#2355]
### Expected behaviour
Main window uses server side decorations or there is at least an option to tell it to use those.

### Actual behaviour
I have a window that looks like a smartphone app on the desktop. I am not able to move that window and it automatically closes whenever I click somewhere else.

<img width="169" alt="nextcloud-client-3 0 1-anonymized" src="https://user-images.githubusercontent.com/114577/92095767-9a392d00-edc5-11ea-87cf-a6b8371ecd30.png">

(small font size reported in a different issue)

When I tell it to open the settings window I get back the usual desktop window which has server side decorations.

Actually I do not get what functionality I would need the new main window for. Cause the link to the other apps just link into the web app. So I do not get the point, I can open the web browser myself. So for me easiest would be just to be able to disable the new window and go with the old window I am used to. I really do not get the point of it. This is a desktop, not a smartphone.

### Steps to reproduce
1. Install Nextcloud client 3.0.1
2. Open main window from system tray

### Client configuration
Client version: 3.0.1

Operating system: Debian Unstable

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.14.2

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: /usr/bin/nextcloud

### Logs

1. Client logfile: 

Nope! Contains sensitive data like which Nextcloud instances I use and which local folders they are synced to. If you need something from the log, please say which part do you need. I tried to skim through the log, but with debug log level it is very much.

I am not sure whether the log would even matter for this kind of bug. Please reconsider this as hard requirement, cause it requiring sharing sensitive data does not match the kind of privacy approach I know and expect from Nextcloud. Thanks.

**Comment by martin21** [comment]
Thank you very much for the answer and also for developing Nextcloud.

I like to object: Is it really *intended* behavior that I *cannot* move the window around?

*Sigh* seems I have to set up a KWin window rule to force that window into being usable as a window again.

**Comment by jancborchardt** [comment]
> I like to object: Is it really intended behavior that I cannot move the window around?

Yes, as it’s a tray menu, not an application menu. I assume we’re a bit limited by what the operating systems and also Qt can do, but this is also what is commonly done by other solutions such as Dropbox and Google Drive.

**Comment by martin21** [comment]
Well. It might be supposed to be a tray window. But telling from the behavior on this KDE Plasma desktop it clearly is not.

I use the auto hiding feature of the systray of the Plasma desktop. And what happens is that the Nextclient client supposed to be tray window appears *under* the systray, not beneath it:

<img width="203" alt="nextcloud-client-systray-anonymized" src="https://user-images.githubusercontent.com/114577/93205883-0f065280-f748-11ea-99db-73c442ff3e9f.png">

It also clearly does not look like any regular systray window under KDE Plasma, messing up the lock and feel of the desktop.

For me that is a major usability regression. I see the intention that you tried to make things better, the the result, at least here, clearly is worse.

**Comment by martin21** [comment]
Reported as new issue #2425.
