### ISSUE TITLE
Client 3.0.1 flatpak crash on ubuntu/fedora

### ISSUE THREAD

**Issue by lapor-kris** [nextcloud/desktop#2358]
### Expected behaviour
When run the desktop client, it should open.

### Actual behaviour
System freezes, screen starts to flicker a bit (part where the window of the client should be).

### Steps to reproduce
1. Install Nextcloud desktop client 3.0.1 from Flathub (Flatpak)
2. Open the client
3. Observe

### Client configuration
Client version: 3.01

Operating system: Ubuntu 20.04 and Fedora 32

OS language: Slovenian

Qt version used by client package (Linux only, see also Settings dialog): ?

Client package (From Nextcloud or distro) (Linux only): Flatpak

Installation path of client:?

### Server configuration

Nextcloud version: 19.0.1

**Comment by er-vin** [comment]
Note we don't produce the Flatpak packages, so we got no idea what's in there. You might want to get in touch with whoever creates them.

**Comment by lapor-kris** [comment]
Thanks for the info. I just found out who is orking on it and will report it there. This can be closed :)
