### ISSUE TITLE
Provide checksum & GPG .sig for (Windows) binary

### ISSUE THREAD

**Issue by beerisgood** [nextcloud/desktop#236]
Please provide SHA2-512 checksum and GPG .sig for the .exe binary so we can check if the binarys arent corrupted nor modified

**Comment by camilasan** [comment]
I agree we should do this. How can we do it @rullzer ?

**Comment by rullzer** [comment]
We already sign the windows installers. (the exe itself is signed). So when opening the installer windows already checks this.

**Comment by yan12125** [comment]
Hi could you consider doing the same (checksum & GPG .sig) for sources and binaries on platforms other than Windows?

**Comment by polymeer** [comment]
Hello folks,

some news here?
It would be nice to have the checkums at minimum. nc-client ist relevant for infrastructure and a risk

**Comment by misch7** [comment]
As @rullzer already said, the Windows installer is signed with our Windows code signing key and so are the binaries inside the program folder since 2.5.3, so that Windows can verify the software.

But I agree, we should provide checksums & GPG .sig's for the other platforms and can do this for Windows too, doesn't hurt ;-)

I'll implement this once I find the time. 😼

**Comment by misch7** [comment]
@yan12125 Ah, yes thanks, I've seen it :-)

**Comment by polymeer** [comment]
I may have not described pecisely. What I mean is that checksums are visible for the downloadable file as an asset. Not that the nc-client check the sum.

bytheway thank you for activity

**Comment by misch7** [comment]
@polymeer You're welcome :)

Thanks for clarifying 👍  This was already clear (to me at least), checkums like we know them for ISO downloads from distros and so on ;-)

**Comment by yan12125** [comment]
Great to see 3.0 is coming. Could this and related issues (#1490, #1510) be revisited for the 3.0 release?

/cc @er-vin - I noticed most recent tags are created by you. Thanks a lot for the efforts! I assume you may be interested in this and related issues.

**Comment by er-vin** [comment]
Definitely, unfortunately I don't think it will happen this time around, hopefully for the next cycle.

**Comment by yan12125** [comment]
I notice that in version 3.0.2, Windows .exe, Linux .appimage and macOS .pkg are all signed. Thanks a lot for the efforts! I think #1490 (for .pkg) and #1805 (for .appimage) can be closed? For tracking the status of signed source tarballs, one of this ticket or #1510 can be used.

**Comment by er-vin** [comment]
Good point, I'll close the relevant ones.
