### ISSUE TITLE
Consider replacing QtSingleApplication with something else

### ISSUE THREAD

**Issue by tilosp** [nextcloud/desktop#2364]
QtSingleApplication relies heavily on pids, this breaks if two client processes get the same pid.
This is for example the case in the flatpak sandbox. See: https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues/12

This is why I propose to replace QtSingleApplication with something else.
One alternative would be for example: https://github.com/itay-grudev/SingleApplication

I have opened this issue to get feedback on this idea.

**Comment by er-vin** [comment]
Yes, I'm totally for replacing QtSingleApplication which is a very old piece of a forked code we're carrying. How would you envision the transition though? I see they recommend git submodule but I'm not too hot on that, that said if it's unpackaged territory we might have no choice...

**Comment by fkrull** [comment]
But a Git submodule is not any worse than the status quo, right? QtSingleApplication is fully vendored so a submodule would arguably an improvement. And having a vendored-but-working implementation would still be preferable to having a vendored-and-subtly-not-working implementation.
