### ISSUE TITLE
Unicode horizontal ellipsis character U+2026 in source code

### ISSUE THREAD

**Issue by rwlin** [nextcloud/desktop#2365]
Hello,

It seems that all strings containing 3 period ". . ." in the source code are written in unicode character "…" (U+2026). That confused my visual studio compiler. Is that expected or you will fix this problem?

Thanks.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The string containing horizontal ellipsis in source code, for example, socketapi.cpp, should be ". . ." in ansi characters.

### Actual behaviour
The string containing horizontal ellipsis in source code uses unicode character "…" U+2026.

### Steps to reproduce
1. On windows 10, install git windows.
2. git clone --depth 1 https://github.com/nextcloud/desktop.git
3. check desktop\src\gui\socketapi.cpp

### Client configuration
Client version: 3.0.1

Operating system: Windows 10

OS language: Traditional Chinese

Qt version used by client package (Linux only, see also Settings dialog): 5.12.9

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Nextcloud

### Server configuration

Nextcloud version: N/A

Storage backend (external storage): N/A

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

C:\Nextcloud\client-building\desktop\src\gui\socketapi.cpp : warning C4819: 檔案含有無法在目前字碼頁 (950) 中表示的字元。請以 Unicode 格式儲存檔案以防止資料遺失 [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]
C:\Nextcloud\client-building\desktop\src\gui\socketapi.cpp(720): error C2001: 常數中包含新行字元 [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]
C:\Nextcloud\client-building\desktop\src\gui\socketapi.cpp(721): error C2064: 詞彙不等於使用 1 引數的函式 [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]
C:\Nextcloud\client-building\desktop\src\gui\socketapi.cpp(722): error C2059: 語法錯誤: '}' [C:\Nextcloud\client-building\desktop\build\src\gui\nextcloud.vcxproj]

2. Web server error log: N/A

3. Server logfile: nextcloud log (data/nextcloud.log): N/A

**Comment by er-vin** [comment]
Interestingly it doesn't fail the build for me. The compiler is assumed to interpret as UTF-8 though. Are you sure it didn't pick another encoding for some reason? (I'm unclear why it would though)
