### ISSUE TITLE
3.0.1 - LoadLibrary Error 87 over RDP (with ATI video)

### ISSUE THREAD

**Issue by klou** [nextcloud/desktop#2367]
### Expected behaviour

Launch the 3.0.1 Nextcloud Desktop Client (Windows)

### Actual behaviour

```
LoadLibrary failed with error 87: The parameter is incorrect.
```
The Client then exits.

### Steps to reproduce
1. Connect to an RDP session
2. Install 3.0.1 Client via `Nextcloud-3.0.1-setup.exe /S` on the RDP Host
3. Launch the Nextcloud client on the RDP Host

### Client configuration
Client version: 3.0.1.20200828
File version: 3.0.1.15740

Operating system: Windows 10 Pro, 1909

OS language: en-US

Installation path of client: %ProgramFiles%\Nextcloud  (64-bit location)

1. Client logfile: 
`nextcloud --logdebug --logfile log.txt` produces no output, no log file.

----------

#1116 discusses this error a little bit, and it's lack of verbosity.  

However, the comments point to many people having the same problems where the client fails to launch (with error 87) over RDP, especially with ATI cards.

This apparently isn't a problem when at the console.  However, with COVID19 and more people working remotely via RDP, this is obviously an issue.

**Comment by er-vin** [comment]
Isn't it a duplicate of #1116 then?

**Comment by klou** [comment]
This might be related to OpenGL 2.0+, and MS RDP not playing nicely with it.

**Comment by artaiprog** [comment]
I fixed it , reference below link 

https://support.esri.com/en/technical-article/000013717

**Comment by er-vin** [comment]
> This might be related to OpenGL 2.0+, and MS RDP not playing nicely with it.

Clearly and that's not much we can do about. Could you please look if @artaiprog workaround works for you?

**Comment by klou** [comment]
@er-vin 

That's not possible for everybody in my organization.

Do you know if QT5 is using ANGLE on Windows?  If not, is it possible to test this?  It is supposed to be easier on RDP.

https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL

**Comment by er-vin** [comment]
Yes, it's using ANGLE in the version we depend on. I know they dropped it later on but I'd have to check if 5.15 already made the switch or not.

**Comment by Mebus** [comment]
Hey folsk!

I can confirm this. I am using an ATI Radeon HD5450 and a Remote Desktop connection. I am interested in workarounds.

**Comment by klou** [comment]
https://www.amd.com/en/support/kb/release-notes/rn-rad-win-non-gcn-16-2-1-beta

Non-WHQL, but that's what we get for older hardware and older drivers that aren't going to see any attention.
