### ISSUE TITLE
Nextcloud v2.6.5 reports up-to-date.

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/desktop#2368]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
New version is detected. New version exists.

### Actual behaviour
No new version is detected. New version exists.

### Steps to reproduce
1. Have Nextcloud client v2.6.5
2. Check updates in the app
3.

### Client configuration
Client version: 2.6.5

Operating system: Windows 8.1 Update

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: default

### Server configuration

Nextcloud version: 19.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Following the instructions here the Nextcloud app opens instead of any logs. Linked instructions for MacOS work on Windows.
`2020-09-05 03:43:46:045 [ info nextcloud.sync.accessmanager ]:	2 "" "https://updates.nextcloud.org/client/?version=2.6.5.20200710&platform=win32&oem=Nextcloud&versionsuffix=stable-Win64&updatesegment=60" has X-Request-ID "e1b8ca8e-a97e-479d-bcbc-da83c545e71b"
2020-09-05 03:43:46:046 [ debug nextcloud.sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://updates.nextcloud.org/client/?version=2.6.5.20200710&platform=win32&oem=Nextcloud&versionsuffix=stable-Win64&updatesegment=60") requests: ()
2020-09-05 03:43:46:269 [ info nextcloud.gui.updater ]:	Client is on latest version!`

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by misch7** [comment]
The update rollout happens in staged phases, depending on a randomly generated one-time segment number. This is to stop flooding the server with too many download requests. It can take a few days until the update server returns the update information for your update segment.

If you can't wait for the update you may of course fetch it from our download page ;-)

Direct download link for latest Windows release:
https://download.nextcloud.com/desktop/releases/Windows/latest

Closing this because I already know some people got the update info from the server.

**Comment by InfamousUser** [comment]
That's what I thought, but 18 days seemed kind of excessive and I had problem with this before, I'll wait more then, thanks!

**Comment by misch7** [comment]
> That's what I thought, but 18 days seemed kind of excessive and I had problem with this before, I'll wait more then, thanks!

Ah okay, yeah that's quite a while ^^

We began rolling out the update just two days ago. I must admit I was a little extra cautious to not break anything for the broad user base, like 3.0.1 has some important fixes over 3.0.0 (and changed a lot from 2.6.5 anyway).

If you're curious, here is the update magic: nextcloud/client_updater_server#41

Thanks for keeping an eye on the slow update! ;-)

**Comment by InfamousUser** [comment]
Got the update to 3.0.1 now, so 2.6.5 skipped 3.0.0, yeah. Thanks for the response!
