### ISSUE TITLE
Ask for password at start

### ISSUE THREAD

**Issue by ignacioinnovo** [nextcloud/desktop#237]
Dear NextCloud Team,

Let me congratulate you all for the job done! I´ve switched to NextCloud some months ago and I´m very happy with it ;-)

I had the same request with the "previous" Windows client... Let me explain my situation...

What I need is that the client asks for password in every start.

What I want to do is to store the NextCloud contents in an encrypted volume (by BitLocker) and when the user restarts the PC she has to enter the password of the encrypted container and then the password for the NextCloud client in order to synchronize. In that way I keep the data safe in each computer if an unauthorized user try to use that PC.

I´m a C# developer, do you think I can help in any way? I saw that the client is developed in C++...

Thank you very much in advanced,
Ignacio.

**Comment by camilasan** [comment]
Glad to hear you are happy with it :)

I would suggest to simply use full disk encryption for this. It would of course be possible to create an encrypted volume, let the client sync there, and decrypt and mount on starting the client. But that would probably be a HUGE make-over of how the client works and it would be far from easy to do on every platform (Mac/Linux/Win).

Coming from C#... afaik I don't think you would have a hard time to get into C++. If you use irc, we are at #nextcloud-client channel.

**Comment by ignacioinnovo** [comment]
Hi Camila! How are you today?

Perhaps I haven´t expressed my self clearly!

I already have a BitLocker volume and the Nextcloud client syncronize a folder in it without any problem.

The problem is that if anyone sits on the PC, although the BitLocker volume could be inaccesible he/she can open the Nextcloud client and select another folder to syncronize without the client asking for password.

For example, now I´m working with my Nextcloud files in my BitLocker volume. Few hours later I will shut down my PC. Then another person can turn on my PC and, without knowing the password of the encrypted volume, can select another folder in the Nextcloud client to syncronize because the client would´t access the BitLocker volume. But, once the user select another folder it will start syncronizing without asking my Nextcloud account password.

Thank you in advanced!

**Comment by camilasan** [comment]
Hi Ignacio,  I am fine, thanks :)

If I understand you correctly, then your solution is to protect your user in the PC with a password (you are talking about Windows right? You should be able to configure to ask for password if your user is inactive for x minutes) and then create another user (maybe a guest user) to avoid to have someone else using your session.

These things really are better done by protecting the entire user session, not in an individual application.

I hope it helps! (You can also check our forums help.nextcloud.com if you need further help)

**Comment by ignacioinnovo** [comment]
Hi Camila! Thank you for the time you are spending on this topic!

What you say is right! It will be an alternative to protect the entire Windows session!

Although, I think it will be a good practice for the Nextcloud client not to save the password in the Registry nor in a file (I´m not really sure where it saves the user session information) just to has it in memory while the user enters it. Then, when the Nextcloud client closes, there will be no way to recover that information.

I was thinking about just a checkbox with a text like "Remember password" in the login dialog. With that checkbox the user will be able to choose between give the possibility to the software to persist the login information or not. In this scenario the probability to vulnerate the user credentials in the Nextcloud client will be zero and all the security robustness will reside on the BitLocker volume (or whatever software he/she uses to encrypt the volume).

Thank you very much again!

**Comment by camilasan** [comment]
After discussing with colleagues and our security specialist, we think that any change on the desktop client regarding this will at best give a false sense of security to people. As I mentioned before, the recommended is to use full disk encryption - if someone can access your computer and it's not encrypted they can regardless do a ton of nasty stuff. Therefore I am closing this issue :)

**Comment by ignacioinnovo** [comment]
Hi Camila! Thank you again for your attention on this topic!

I think I´m missing something: if I encrypt the disk but someone turn on my PC and change the sync folder to an unencrypted destination (let´s say a pendrive) of the desktop client, would it download all the files again?

**Comment by LukasReschke** [comment]
> if I encrypt the disk but someone turn on my PC and change the sync folder to an unencrypted destination (let´s say a pendrive) 

Our advice here would be to use full-disk-encryption (FDE) on the operating system partition as well. That would prevent a malicious actor to start up your operating system and change things in the Nextcloud client settings.

On Windows, you could use [Bitlocker Device Encryption](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/bitlocker-device-encryption-overview-windows-10) for that purpose.

Whilst we could add a password verification also to the Nextcloud client, this would add an additional maintenance burden for our team and we'd like to avoid this. In addition, without FDE, a malicious actor with access to your device could do a lot of things to get this information regardless. (install a keylogger, modify the Nextcloud binary, ...)

**Comment by ignacioinnovo** [comment]
Thanks for your answer @LukasReschke ! I was trying to avoid encrypting the full disk because of the perfomance impact, but I get your point on not to overload the Dev Team.
