### ISSUE TITLE
[question] Translation in the installer

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#2372]
I noticed a lot of incorrect translations into Polish in the installer of the windows application. Installer translations do not exist in Transifex.
If Nextcloud desktop application uses a ready-made application for installation, which one?
If not, where can these translations be improved?

**Comment by er-vin** [comment]
Currently this is not plugged to transifex. The strings are in admin/win/nsi/l10n/Polish.nsh though, less convenient I know.

**Comment by Valdnet** [comment]
@er-vin Thanks for the answer :wink:. Must add to Transifex.
While browsing the file, I noticed a different character encoding:
```
zostaæ
zatrzyma³
```
This makes it difficult to correct the translation of the file.

**Comment by Valdnet** [comment]
@nextcloud/desktop Translation corrected in Polish. I am asking you to merge PR: #2380.
