### ISSUE TITLE
Windows Client 3.0.1 HIDPI issue

### ISSUE THREAD

**Issue by m0nhawk** [nextcloud/desktop#2374]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Scaled Notification window.

### Actual behaviour
The Notification window is huge (see screenshot below).

### Steps to reproduce
1. Open new Notification window from system tray.
2. See the huge window.
<details>
<summary>Notification window</summary>
<img width="960" alt="Annotation 2020-09-08 120537" src="https://user-images.githubusercontent.com/8220926/92507312-62b6f000-f1cc-11ea-920c-10dc2271e6f1.png">
</details>

### Client configuration
Client version: 3.0.1

Operating system: Windows 10

Display resolution: 1920x1080

Display size: 13 inch (Dell XPS 13)

Display scaling: 150%

---
I believe it's related to #2295, but in Windows it's huge, instead of minuscule. And so far, it's only usable (and have adequate size in macOS).

**Comment by er-vin** [comment]
It's not really HiDPI isn't it? I mean it's 1920x1080 only from what you say. But you have scaling on top, so I expect everything to be 50% bigger not only our client.

I couldn't find the screenshot by the way. It be interesting to see how this goes indeed.

**Comment by m0nhawk** [comment]
@er-vin There is a screenshot under the "Notification window" spoiler.

And I forget, it's 13 inch screen (Dell XPS 13).

**Comment by er-vin** [comment]
So I guess the screenshot is showing the whole height of the screen but not the whole width, right?

**Comment by m0nhawk** [comment]
I've updated the screenshot. It roughly takes 1/3 to 1/2 of the screen estate.
