### ISSUE TITLE
Windows Client Crashes syncing large folders (40k files / 34k directories) after using up to 16 GB RAM

### ISSUE THREAD

**Issue by fpehla** [nextcloud/desktop#2375]
### How to use GitHub

NextCloud Client on Windows crashes when syncing large folders (40.000 files, 34.000 directories). 

Backstory: After upgrade from Client 2.6.5 to Client 3.0.1 my client started crashing. The Client 2.6.5 did not crash syncing the same folders, the folders grew in size while using 2.x clients. After upgrading to Client 3.0.1 the folders were no longer synced but the cliend crashed. Downgrading back to to Client 2.6.5 did not solve the issue, the older Client 2.6.5 also can no longer sync the folders. 

### Expected behaviour
Sync Client should be able to sync the same folders as before.

### Actual behaviour
Sync Client tries to sync the folders scanning locally and then remote. After scanning the sync client's RAM usage slowly grows to about 13 Gigabytes of RAM, then quickly grows to more than 15 Gigabytes of RAM, then quickly shrinks to about 500 Kilobytes of RAM, then the client exits / crashes. The system running the client has 32 Gigabytes of physical RAM with more than 10 Gigabytes of RAM free when the client exits / crashes.

On the next start of the sync client the same happens, the affected folders are no longer synced from client to server

I am not using e2ee.

### Steps to reproduce
1. Create a large directory structure containing a large number of files (the number of directories seems to be important)
2. Start Syncing to a nextcloud server that already has the same directory structure synced
3. Client uses a lot of RAM then exits / crashes

### Client configuration
Client version: 3.01, also when downgrading to 2.6.5

Operating system: Windows 10

OS language: German

Installation path of client: default

### Server configuration
Nextcloud version: 18.0.7

Storage backend (external storage): local filesystem

**Comment by schdief06** [comment]
I'm have the same issue with:
Windows 10
Client Version 3.0.1
Server Version: 18.0.8

(I have not tried to downgrade yet)

**Comment by fpehla** [comment]
Testing with Client 3.0.1:
- Delete Files / Directories on Nextcloud Server
- Re-Sync from Client to Server (seems to push all files to server without issue)
- Client starts a Re-Sync (scanning local, scanning remote)
- Same behavior as described in initial issue: memory consumption rises to about 16 Gigabytes of RAM, then Client exits / crashes

So even though the files are synchronized the client crashes.

**Comment by er-vin** [comment]
Is it still happening with 3.1 ?

**Comment by andresgunn** [comment]
One of my users experiences the same issue.

OS is Windows 10
Client is 3.1.3
Server is version 20.0.5

They managed to sync up their stuff (~200GB and ~1e5 files), but after that the troubles began.
Every time they start the client now, it will start scanning for changes then immediately after that completes the RAM usage starts growing until it reaces all the available RAM at which point the usage drops for a few seconds and then the client crashes.
