### ISSUE TITLE
[3.0.1] defect grafic in traypopup and no sync/wating forever

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/desktop#2383]
### Expected behaviour
Clean grafics in display

### Actual behaviour
Propably has to do with suspend/resume. After clicking on the trayicon the grafics is kind of destroyed
![grafik](https://user-images.githubusercontent.com/2804301/92442405-1f4e8880-f1b0-11ea-8103-0df5eadfeaca.png)

### Steps to reproduce
1. suspend pd
2. resume pc
3. click tray icon

### Client configuration
Client version: 3.0.1

Operating system: Linux Mint 20 Cinnamon

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by h4knet** [comment]
Similar issue on Windows 10 : https://github.com/nextcloud/desktop/issues/2386

**Comment by er-vin** [comment]
This looks like an issue with your graphics drivers or how Qt interfaces with it, can't do much about this.
