### ISSUE TITLE
3.0.1 No GUI at all on debian due to missing dependencies

### ISSUE THREAD

**Issue by jonascant** [nextcloud/desktop#2390]
### Expected behaviour
Nextcloud Client should display a Window.

### Actual behaviour
The process nextcloud-desktop --background is running, but no GUI ist shown.
No way to open in manually by restarting.

### Steps to reproduce
1. Install nextcloud-desktop on debian testing aarch64 (default debian desktop envirement)
2. start the client
3.

### Client configuration
Client version: 3.0.1

Operating system: Debian testing aarch64 default debian desktop envirement

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 5

Client package (From Nextcloud or distro) (Linux only):nextcloud-desktop

Installation path of client: /usr/bin/nextcloud

### Server configuration
Nextcloud version: 19.0.2

**Comment by er-vin** [comment]
If you stop the process and start nextcloud-desktop with the --logdebug and --logfile parameters, do you see anything in the logs or as output of the process?

**Comment by leArthurDent** [comment]
installing the missing dependencies libqt5-qtgraphicaleffects and libqt5-quickcontrols2 solved the issue for me. Still, any window is merely available installing a tray icon extension.

**Comment by m1435** [comment]
On Debian Sid, installing the following packages solved the issue for me:
`apt install qml-module-qtquick-controls2 qml-module-qtgraphicaleffects qml-module-qtqml qml-module-qtquick-layouts qml-module-qtqml-models2`.

**Comment by er-vin** [comment]
@jonascant is it a dependency issue for you as well?

If that's it then it's not arch specific like the title indicates and that would be a packaging issue. In the case of openSUSE it would need to be reported there. In the case of Debian, @ivaradi could you fix this in our ppa please?

**Comment by jonascant** [comment]
I can't test on that machine ATM. But i did install on a x86_64 machine (also debian testing) with the same problem. So i think it is not an arch thing. I got it working with a flatpak. However the new blue window that links to the cloud website does not seem to respect the GNOME design-guidelines. It is not movable and without a tray icon, i can't open it after i closed it.. Would it be possible to create two separate packages? The settings window as a standalone package for people who just want to synchronize and create another package with the widget window, where the settings app is a dependency? For now i am forced to pin the app down to 2.5 which works nicely.

**Comment by er-vin** [comment]
> I can't test on that machine ATM. But i did install on a x86_64 machine (also debian testing) with the same problem. So i think it is not an arch thing. I got it working with a flatpak.

OK, so that kind of confirm the missing dependency issue on debian packages. @ivaradi could you look into this please?

> However the new blue window that links to the cloud website does not seem to respect the GNOME design-guidelines. It is not movable and without a tray icon, i can't open it after i closed it.. Would it be possible to create two separate packages? The settings window as a standalone package for people who just want to synchronize and create another package with the widget window, where the settings app is a dependency? For now i am forced to pin the app down to 2.5 which works nicely.

This is a separate issue, we got that design decision discussed in another ticket.

**Comment by ivaradi** [comment]
I have added the `qml-module-qtqml` package as a dependency to the Debian Testing package (the other ones listed here: https://github.com/nextcloud/desktop/issues/2390#issuecomment-691625475 were already there). The 3.0.1 package has been rebuilt with it, so please, test it and let me know your results.

**Comment by m1435** [comment]
The issue appears to be resolved with latest `nextcloud-desktop=3.0.1-3` on Debian Unstable.

**Comment by Tachi107** [comment]
The issue still persists for me on Debian Testing, probably because `nextcloud-desktop` 3.0.1-3 from the Debian repos (and the version available in the official PPA) is packaged with all the packages mentioned by @m1435 except `qml-module-qtqml`. Installing it solves the issue.
