### ISSUE TITLE
Please expand file status text so that it can be read or copied

### ISSUE THREAD

**Issue by ajay10000** [nextcloud/desktop#2392]
### Expected behaviour
Expand the file status text in the desktop client when mouse over or (better) enable copy to clipboard function.

### Actual behaviour
When the file status text in the Windows desktop client is reporting multiple failures, it is impossible to view the file names and folder structures to investigate.

### Steps to reproduce
1. As above

### Client configuration
Client version: 3.0.1

Operating system: Windows 10 2004

OS language: English (AU)

**Comment by toxpal** [comment]
Using Linux, and I ask the same. Not only for failures, but for ALL text. Now, when I click NC client icon, I see a bunch of reports and all of them are useless because they look like "Shared file /root/folder_name/sub..." Doesn't help at all and very annoying.

Thank you.

**Comment by er-vin** [comment]
Duplicate #2349
