### ISSUE TITLE
Very often dialog with browser login popping up

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/desktop#2394]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I want the 3.x client to act like the older one - without that poping up of the browser and login / connecting there.
It's really annoying and it comes at nearly every start / login at my Windows 10 Pro German (Build 2004) PC.
I also can't tell my "John Doe"-users that they always have to additionally login with their browser and 
confirm that the desktop client may use their Nextcloud data.

I know it has been added for end2end encryption - but that's an absolutely _NOT_ user-friendly implementation!
If it keeps like that I (and all my Nextcloud users) don't care about the security and just want the old behaviour back!

At least it should be possible to switch that behaviour off (or better: at default it's switched off and you have to swicht it on if you want end2end encryption).

### Actual behaviour
At nearly every PC start (after Windows login of course) my web browser opens and shows that annyoing login / enable the share dialog - I searched through the settings and could not find an option to switch it off.

### Steps to reproduce
1. Install or update to desktop client >= 3.0
2. Start it

### Client configuration
Client version: 3.0.1

Operating system:
Windows 10 Pro, Build 2004

OS language:
German

### Server configuration
Shared hoster with Debian 9

Nextcloud version:
Nextcloud 17.0.8

**Comment by ieg999** [comment]
On manjaro linux the same. It's annoying
Nextcloud 19.0.2, Nextcloud client 3.1.0

**Comment by er-vin** [comment]
OK, I need more info here like a more precise description and screenshot or screencast because I'm not quite sure which dialog you're talking about.

At least for the record: popping up a web browser is not part of the e2ee code path.

**Comment by ieg999** [comment]
I need some time to make screenshots. Step by step.

**Comment by Bodenseematze** [comment]
> At least for the record: popping up a web browser is not part of the e2ee code path.
If it's not part of the e2ee code path - why is this dialog and opening the browser for "connecting" an account to the client now necessary?
In 2.x versions of the client it was not necessary and the big new feature of the 3.x versions was the end to end encryption - so I thought this must be part of it?!

@ieg999: thanks for making the screenshots - that's exactly the annoying thing which I talked about. In windows the dialog and the browser messages are exactly the same - although I see them in German and not in Russian ;-)

**Comment by ieg999** [comment]
But on my windows 10 nextcloud-client (3.0.1) works normally. It's strange..

**Comment by er-vin** [comment]
> > At least for the record: popping up a web browser is not part of the e2ee code path.
> 
> If it's not part of the e2ee code path - why is this dialog and opening the browser for "connecting" an account to the client now necessary?
> In 2.x versions of the client it was not necessary and the big new feature of the 3.x versions was the end to end encryption - so I thought this must be part of it?!

Well, could be something server side which changed or for some reason your client not being able to talk to the keyring anymore. Could you please check in the Windows Credentials that entries for Nextcloud are properly stored? This is located in the Credentials Manager in the Control Panel.

> @ieg999: thanks for making the screenshots - that's exactly the annoying thing which I talked about. In windows the dialog and the browser messages are exactly the same - although I see them in German and not in Russian ;-)

I think we got a report regarding that issue on Arch. You're on Manjaro I'd expect it'd be the same. Seems to be an issue between secret service and qtkeychain version on Arch. We can't do anything about this, will have to be solved by packagers. Same symptom but different issue.

**Comment by Bodenseematze** [comment]
> Well, could be something server side which changed or for some reason your client not being able to talk to the keyring anymore. Could you please check in the Windows Credentials that entries for Nextcloud are properly stored? This is located in the Credentials Manager in the Control Panel.
![Nextcloud_Credentials](https://user-images.githubusercontent.com/13251886/92722436-25329e00-f357-11ea-9225-af3ab3191b95.jpg)
there are two entries - which both look a bit strange.
The user and the web URL are both part of the title and also of the "Internet- or network address".
The first entry is "Nextcloud_<Username>:https://<URL>/:0"
The second entry is "Nextcloud_<Username>_app-password:https://<URL>..."
In both entries the username field is empty and they both say "changed today".

The following dialog ist popping up most of the time, when I start my PC or sometimes just "for fun" :-)
![Nextcloud_AuthorizeDialog](https://user-images.githubusercontent.com/13251886/92722884-c588c280-f357-11ea-9bea-3716247ae36c.jpg)
It says "You have been logged out from <Username>@<Url> as user <Username>. Please login again.
Please change to your Web browser to continue."

I will uninstall the 3.0.1 desktop client version and reinstall an old one (of the 2.x series) and see, if the issue is still present or if it's gone (and also see how the credentials manager entries look like)

**Comment by Bodenseematze** [comment]
I now uninstalled the desktop client 3.0.1 and reinstalled 2.6.5
Before the first start of the client I deleted the two entries from the Certificates Manager.

After the first start the popup and the browser opens (as expected) and the two entries in the Certifiactes Manager reappiered (same entries as with 3.0.1 client).
I then restarted my PC and logged in again with my Windows user - the Nextcloud client didn't start automatically (although the autostart option is set) but after starting it manually, no dialog pops up and the client works.
Later I restarted my PC again and after that re-login and starting the Nextcloud client (it did again not start automatically) the annoying dialog pops up again.

So the issue has nothing to do with the 3.0.x client version - although it appears the first time here when I installed the 3.0.0. client.
What could be the reason? Any Windows update?

**Comment by er-vin** [comment]
This is unclear why it'd suddenly start doing this. I got to admit it's slightly reassuring to me that you excluded 3.0 as having the issue since 2.6 exhibits it as well. Indeed we didn't make many changes in that area it would have been puzzling.

Since you've been kind enough to try with a downgrade, could you try as well with 2.6.3 please? (just in case and temporarily)

**Comment by bobpaul** [comment]
Related to this issue, is it no longer possible to log into the client using an app password? I'm only given the option to log in via browser. I prefer to use app passwords so that I can easily name my sessions in case I need to revoke credentials. 

Due to this issue, my `Security -> Devices & sessions` section is full of "Sync Client - Linux" sessions and other then guessing based on recency, it's not easy to tell which are the active sessions and which are stale. Creating an app password is extra steps, but it removes all ambiguity, and as such that's my preference.

**Comment by er-vin** [comment]
> Due to this issue, my `Security -> Devices & sessions` section is full of "Sync Client - Linux" sessions and other then guessing based on recency, it's not easy to tell which are the active sessions and which are stale. Creating an app password is extra steps, but it removes all ambiguity, and as such that's my preference.

Understood, we don't quite plan to change this but we plan to make the device string more telling than what it is currently.

**Comment by Bodenseematze** [comment]
> Since you've been kind enough to try with a downgrade, could you try as well with 2.6.3 please? (just in case and temporarily)
Sorry to be a bit late in my reaction - I had no time for experiments...

I tried a downgrade to 2.6.3 (I deleted the entries in the Certicate Manager before) - after the first start the browser window popped up (as expected).
After that I did several restarts and switched off my PC completely - I did not get the dialog.

That doesn't mean the problem isn't present in 2.6.3 - maybe it'll come back later, but currently it vanishes by downgrading to 2.6.3!
I'll keep that version now and report if it reaccurs...

**Comment by Bodenseematze** [comment]
Update: after a week at 2.6.3 (which BTW works a lot smooter as the newer versions) the dialog came back two times after a restart of the PC - but not more...
So the problem did already exist in 2.6.3 but was not as annoying as it is in newer versions...

**Comment by Bodenseematze** [comment]
Again an update: I have to revert my previous post.
In the last week (after doing the above post) I got the annoying dialog nearly every restart of my PC - so the problem is independent of the version!

Don't know, why it's sometimes coming more often...
...maybe it has something to do with my posts here ;-)

**Comment by Bodenseematze** [comment]
Is any developer working at this issue?
It's really annoying and I'd like it to be fixed - I can provide my help if someone produces a special version with extra logging or similar things...

**Comment by jansenm** [comment]
I am having the same problem on opensuse. It actually comes and goes. After login the client says i got logged out and need to authorise, opens a dialog and a brower.

My theory is that this is network related. I now have a command line of 

`pkill nextcloud && kshell5 nextcloud`

Which kills the client and just restarts it. After this the login works as expected. My guess is that the nextcloud client starts before my wlan connection is ready, doesnt reach the server, misinterprets the error and concludes that it got logged out. Can anyone check this code path?

**Comment by er-vin** [comment]
More likely that somehow it started before your keychain provider (kwallet, gnome keyring or such) was itself started. It's supposed to retry at least once but if that really takes too much time at some point it gives up.

**Comment by Bodenseematze** [comment]
Is any developer looking into that issue?
It's absolutely annoying here (as said: Win10 Pro) and I really want it to be fixed - and offer my help for finding and fixing the problem...

**Comment by Bodenseematze** [comment]
I got an automatic message from github-bot that the issue will be closed if no new details can be posted.
Is that the "solution" for issues to which nobody has a look - autoclose?

**Comment by FlexW** [comment]
@Bodenseematze If you just post a message then the stale bot will not close the issue. Regarding your problem: That dialog should not popup every time you reboot. Most likely something is off with your keychain but if you can drop me your logs here https://cloud.nextcloud.com/s/onzDjSexsxRq3pj I will take a look at them. Please make sure that you sent me the logs after that dialog misbehaved :)

**Comment by T-bond** [comment]
Maybe related to #2573 
I made a small investigation and a possible solution at that issue.

**Comment by T-bond** [comment]
Keep it open. Still relevant.

**Comment by Chad90b** [comment]
Seeing the exact same issue. Client v 3.14.3stable on win 10 pro. Desktop client never remembers the credentials and therefore constantly needs to log back in. Simply rebooting reproduces this.
