### ISSUE TITLE
Notification of Nextcloud message

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/desktop#24]
The nextcloud-client issues a notification that a message is awaiting in Nextcloud. This is fairly useful to get a notification when there is an update awaiting. 

But the notification is a big cliff-hanger, as it wont tell you what the message is and/or gives a link to the nextcloud to actually check and act upon the messge.

**Comment by Blackgen** [comment]
+1
The notification doesn't contain any info at all.
Also it appears seemingly random since when it pops up no file changes happend in the cloud.

**Comment by a-schild** [comment]
Same here,
when you have multiple accounts/servers configured in the desktop client, you don't see which notification is from which server.

![2018-01-24 14_54_03-nextcloud](https://user-images.githubusercontent.com/1441009/35335674-7e3371c2-0116-11e8-9e44-38b64a9a3fc5.png)

**Comment by camilasan** [comment]
We are atm working on improving the notifications. It should be included in the next release.

**Comment by camilasan** [comment]
We have completely re-done how notifications are displayed 2x since this issue was opened :) I would recommend trying the latest release. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).
