### ISSUE TITLE
Release new client updates on GitHub instead of (extremely slow) download.nextcloud.com

### ISSUE THREAD

**Issue by EmberHeartshine** [nextcloud/desktop#2401]
This issue is the same as [#22764](/nextcloud/server/issues/22764) I have reported on the server GitHub.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When downloading the update installer, the download (approx. 100 MB) should take less time than it takes me to download 7 copies of the My Little Pony movie (each ~1 GB)

### Actual behaviour
Downloading the update installer takes around 20-25 minutes.

### Steps to reproduce
1. Navigate to https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.0.1-setup.exe
2. Time the download
3. Download something else that's oddly specific and time that download to make sure you're not going crazy

### Client configuration
Client version: 3.0.1 (installer)

Operating system: Windows 10

OS language: English

Installation path of client: n/a

**Comment by Id3aFly** [comment]
I just tried this and the download took <20s for me.
Europe/Germany/Nürnberg

**Comment by mritzmann** [comment]
> I just tried this and the download took <20s for me.

The download speed varies depending on the day, time of day and whether new Nextcloud releases are announced or not. We should therefore not discuss whether the problem exists or not. Because I think that the problem exists is undisputed. See: https://help.nextcloud.com/t/nextcloud-com-slow-download-speed/71461/48?u=mritzmann

But Nextcloud is already working on it, Quote: 

> We’ll look into a CDN solution, but that will take a bit of time…

**Comment by EmberHeartshine** [comment]
GitHub offers a service expressly for this purpose. You can include binaries with releases.

**Comment by er-vin** [comment]
Well, actually this should be all switched to GH release pages now.
