### ISSUE TITLE
Client Version 3.0.1 (Windows) - Status Icons in taskbar shows last sync succesfull, but sync is running.

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/desktop#2402]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Status icon in taks bar should show the actual state of the sync client:
paused, running, fully synced, error.

### Actual behaviour
Statusbar shows client fully synced while sync is actually running.

### Steps to reproduce
1. Upgrade to 3.0.1 (better not, see other reported issues)
2. Repair config by repeatedly restaring and review subscribed folders etc.
3. See it resync the lot.

### Client configuration
Client version: 3.0.1

Operating system: Windows 10

OS language: Dutcj

Installation path of client: standard

**Comment by er-vin** [comment]
Duplicate of #2293

**Comment by er-vin** [comment]
Actually not, this one is the other way around in fact. Similar but not 100% the same. Reopening.
