### ISSUE TITLE
[wayland] Segmentation fault when clicking on tray-icon

### ISSUE THREAD

**Issue by Stunkymonkey** [nextcloud/desktop#2405]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
main windows shown and no crash

### Actual behaviour
when left-clicking the tray icon it exits with "Segmentation fault".
When using right-click nothing happens, but sway does not support tray-context menus.

### Steps to reproduce
1. start client
2. left click on tray icon
3. crash

### Client configuration
Client version: 3.0.1 (via pacman)

Operating system: Arch Linux

OS language: en_US.utf8

Qt version used by client package (Linux only, see also Settings dialog): 5.15.0

Client package (From Nextcloud or distro) (Linux only): 3.0.1

Installation path of client: `/usr/bin/nextcloud`

Window Manager: sway

### Logs

1. Client core dump: https://pastebin.com/Rb0aiEpA

**Comment by er-vin** [comment]
I can't reproduce. Do you see this with our AppImage as well? If yes I can make a tentative patch in a PR, which will produce another AppImage containing the possible fix which you could test and let me know if that fixes it for you.

Is that possible for you? Since I don't see it on my end I'm unsure how to approach this otherwise.

**Comment by Stunkymonkey** [comment]
I downloaded the AppImage and noticed, that it required `x11`. 
starting it with `QT_QPA_PLATFORM=xcb ./Nextcloud-3.0.1-x86_64.AppImage` works perfectly.
same as `QT_QPA_PLATFORM=xcb nextcloud`. So it might be related to wayland.

**Comment by Stunkymonkey** [comment]
so from my side i can assist in providing logs, but otherwise the issue is bypassed. feel free to close it. But expect others to open it again.

**Comment by er-vin** [comment]
Ah somehow didn't realize this was a wayland setup... might be sway specific as well I guess.

I'd be interested in debug log and a stacktrace on crash if you could provide us with that, could help at least figuring out where it's crashing and how far it went with trying to popup the window.

**Comment by Stunkymonkey** [comment]
the debug log is not interesting at all, because it crashed with a segfault. If you still need it i can recreate it.

the stacktrace is provided at https://pastebin.com/Rb0aiEpA

**Comment by er-vin** [comment]
> the debug log is not interesting at all, because it crashed with a segfault. If you still need it i can recreate it.

Still, I'd be interested to see how far along it went. I suspect it didn't go very far...

> the stacktrace is provided at https://pastebin.com/Rb0aiEpA

Any chance to have it with debug symbols and debug sources provided? I think I somewhat have an idea of where that is but getting source files with lines would be a great help.

**Comment by Stunkymonkey** [comment]
application log:
```
2020-09-14 15:00:55:522 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
2020-09-14 15:00:55:729 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
2020-09-14 15:00:55:739 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
2020-09-14 15:00:55:745 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
2020-09-14 15:00:55:750 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
2020-09-14 15:00:56:250 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::writePassword(const QString&, const QString&, const QString&, QKeychain::JobPrivate::Mode, const QByteArray&, QKeychain::JobPrivate*)
2020-09-14 15:00:59:614 [ fatal default ]:	ASSERT: "screen" in file /home/felix/todo/desktop/src/gui/systray.cpp, line 294
Aborted (core dumped)
```
coredump: https://pastebin.com/P28DrBik

**Comment by er-vin** [comment]
Yep, it's the one I suspected... so either `QGuiApplication::screens()` gives us an empty list in `Systray::currentScreen()` or their geometry is somehow bogus.

Since you built anyway, any chance you could add some debug output in `Systray::currentScreen()`?

**Comment by Stunkymonkey** [comment]
there are two screens (I expect my laptop and my monitor)
```
QGuiApplication::screens().length() = 2
QGuiApplication::screens()[0] = 0x55999e595590
QGuiApplication::screens()[1] = 0x55999e5950f0
```
and
```
Systray::currentScreen() = 0
```

**Comment by Stunkymonkey** [comment]
the `QCursor::pos()` is always at `(0, 0)`, which is false

**Comment by Stunkymonkey** [comment]
reading this:
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Drop_Menus

> On Wayland there is no global cursor position and QCursor::pos() only works by tracking the mouse move events.

...

> Similarly to Drop Menus, on wayland QCursor::pos() does not work as expected, and should be avoided to position context menus.

not sure how to continue

**Comment by Stunkymonkey** [comment]
Maybe tracing the mouse is not the best idea.

I also think it is more common to consider the active window.
It could be easier to get the `active_window.parent_screen`.

**Comment by er-vin** [comment]
> Maybe tracing the mouse is not the best idea.

Never was to be honest, but the conundrum is that we don't get the position on the activated signal on the systray...

> I also think it is more common to consider the active window.
> It could be easier to get the `active_window.parent_screen`.
> 
> choosing an arbitrary screen would prevent the crash, but not be the best solution.

Yes, I think we will have to go for such a fallback unfortunately. I'll try to get a PR rolling, would be nice if you could check out the branch and try it when the PR appears.

**Comment by Stunkymonkey** [comment]
I am happy to help fixing this. Ping me if there is anything I can do.

Thanks for your work. :+1:

**Comment by er-vin** [comment]
Alright, we got a first shoot at it on #2418. Please checkout the corresponding branch and let me know how it behaves for you.

**Comment by Stunkymonkey** [comment]
the window shows up perfectly fine. The geometry is a bit weird, but that is an sway issue.

If the PR gets merged, the issue can be closed.

**Comment by Stunkymonkey** [comment]
thanks for your fast response and the quick fix.
