### ISSUE TITLE
MacOS Big Sur: Nextcloud sync always crashes after some time

### ISSUE THREAD

**Issue by HLFH** [nextcloud/desktop#2416]
Hi,

I am using a recent version of MacOS and I had crash issues with Nextcloud Sync since the start.
I am using Nextcloud Sync version 3.0.1.
With MacOS, Nextcloud sync always crashes after some time...

Do you plan to fix it?

Thanks,
HLFH

**Comment by er-vin** [comment]
Hello,

Please provide us more information, the issue template is here for a reason. As such "things crash" won't get us anywhere. We need a more precise description of when it crashes, what it's been doing at that point. Logs and a stack trace would be welcome too.

Regards.

**Comment by HLFH** [comment]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.  

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead


### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:


Operating system: macOS Big Sur, version 11.0 Beta (20A5364e) ; it crashed with macOS Catalina as well

OS language: English

Installation path of client: /Applications/nextcloud


### Server configuration

Nextcloud version: Nextcloud 20.0.0 Beta 4

Storage backend (external storage): no external storage, only local

### Logs

**Client logfile:** 
I am now doing `nextcloud --logdebug --logwindow` and will provide the log as soon as it crashes again.

I am currently monitoring and will provide the web server error log and the *data/nextcloud.log* as soon as it crashed during the day.

**Comment by HLFH** [comment]
Might be a duplicate of https://github.com/nextcloud/desktop/issues/2067.

**Comment by HLFH** [comment]
In the last Nextcloud crash file:

```
Crashed Thread:        1272

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
```

and

```
Thread 1272 Crashed:
0   libsystem_kernel.dylib        	0x00007fff252878e2 sigprocmask + 10
1   libsystem_c.dylib             	0x00007fff2544d71c abort + 84
2   org.qt-project.QtCore         	0x000000011406e259 0x114056000 + 98905
3   org.qt-project.QtCore         	0x000000011406f9a4 QMessageLogger::fatal(char const*, ...) const + 202
4   org.qt-project.QtCore         	0x0000000114296a27 QEventDispatcherUNIXPrivate::QEventDispatcherUNIXPrivate() + 215
5   org.qt-project.QtCore         	0x0000000114297475 QEventDispatcherUNIX::QEventDispatcherUNIX(QObject*) + 37
6   org.qt-project.QtCore         	0x0000000114077f4a 0x114056000 + 139082
7   org.qt-project.QtCore         	0x000000011407695f 0x114056000 + 133471
8   org.qt-project.QtCore         	0x00000001140780d9 0x114056000 + 139481
9   libsystem_pthread.dylib       	0x00007fff2538b9b4 _pthread_start + 224
10  libsystem_pthread.dylib       	0x00007fff253874d7 thread_start + 15

Thread 1272 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000003  rcx: 0x00007000370c6d38  rdx: 0x0000000000000000
  rdi: 0x0000000000000003  rsi: 0x00007000370c6d5c  rbp: 0x00007000370c6d70  rsp: 0x00007000370c6d38
   r8: 0x0000000000000000   r9: 0x00000000000007fb  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000600000061b70  r13: 0x0000000000000000  r14: 0x00007000370c6d50  r15: 0x0000600000061b48
  rip: 0x00007fff252878e2  rfl: 0x0000000000000246  cr2: 0x00007fff87515930
```

**Comment by er-vin** [comment]
Yes, might be a duplicate of #2067 indeed. I suspect a memory leak behind this. Indeed in both case it doesn't crash right away but after quite some time. 3.0.3 might fix it, we just got a fix for a memory leak yesterday.

**Comment by HLFH** [comment]
@er-vin Happy to try 3.0.3 once it gets released.
