### ISSUE TITLE
Can't see full path

### ISSUE THREAD

**Issue by merkleID** [nextcloud/desktop#2420]
### Expected behaviour
Change of outlook 

### Actual behaviour
Weird outlook

### Steps to reproduce
1. you have to have conflicting documents

### Client configuration
Client version: 3.0.1

Operating system:
Windows 2019

OS language:
English

Installation path of client:
c:\program files\nextcloud

### Server configuration
linux
Optional section. It depends on the issue.

Nextcloud version:
19.0.2

Hi,
the new tray windows is really weird.
I can't see the full path and name of conflicting documents and if I click on them, the link opens a browser that doesn't point to the selected documents so that I can't understand what is wrong.
Please see attached .png 
Besides, I read about end-to-end encryption starting from ver3, but I didn't see it anywhere in any client of mine.

![Schermata 2020-09-14 alle 22 18 23](https://user-images.githubusercontent.com/30238962/93134906-be581080-f6d9-11ea-8636-45ca3d27c0d7.png)

**Comment by er-vin** [comment]
This got reported already and fixed. Fix is integrated and will be shipped with 3.0.2.

**Comment by merkleID** [comment]
> This got reported already and fixed. Fix is integrated and will be shipped with 3.0.2.

Thank-you very much!
