### ISSUE TITLE
3.0.1 on MacOS: Files/Folders are opened in browser instead of opening finder/file

### ISSUE THREAD

**Issue by travisbotello** [nextcloud/desktop#2427]
### Expected behaviour
When using the last updated/history list via the status bar icon to view/click on last edited files and folders it should actually open the corresponding file/folder in finder or file browser.

### Actual behaviour
It opens my nextcloud instance in browser with this url 'index.php/apps/files/?dir=/&fileid=2'

### Steps to reproduce
1. Click on nextcloud status bar icon
2. Select an entry from the last updated list
3. Click on this entry
4. Opens the browser instead of file/finder

### Client configuration
Client version:
3.0.1

Operating system:
MacOS Catalina 10.15.6

OS language:
DE

### Server configuration
Nextcloud version: 19.0.3

**Comment by er-vin** [comment]
This has been fixed in 3.0.2
