### ISSUE TITLE
3.0.1 [Feature request] Main window design suggestion: separate message types

### ISSUE THREAD

**Issue by unclev** [nextcloud/desktop#2438]
Main **issue**: with all the messages in the main window on the same list - file changes often "get lost".

In addition to #2290 design suggestions, I suggest

1. Separating messages by source and/or type:

   - files: creating, updating, deleting. Those activities affect the file sync process.
     (It would also be great having synchronization result on the list next to each content change record).

   - logging: info, warning, error messages.

   - sharing.

   - bookmarks.

   - other activities if reflected in the main window. (For now I see only one exception: file opening, and there should not be records like this).

   Possible UI implementation of such separation: in tabs.

2. Separate main list messages by date similarly to the _Activity_ page. (I suggest greyed caption item on the list).

**Comment by jancborchardt** [comment]
Rather than separating this again (we had this in the past which ended up in always needing to hunt which tab the relevant info is in) we should properly do the list entries.

That mainly means grouping for example. Conflicts should be grouped in 1 entry and then taken care of in a dialog. Similar to ignored files for example.

**Comment by joho1968** [comment]
How about a clickable filter for the view? Allow filtering on message type and free text (simultaneously). If you're looking for conflicts, you select only that message type. If you're looking for the file "wherediditgo.txt", you can enter that in the free text field.

**Comment by FlexW** [comment]
I will close that in favour of https://github.com/nextcloud/desktop/issues/3644 Grouping will happen through time and related entries will be grouped. We don't want to do it with tabs right now because they will complicate the interface and will hide information.
