### ISSUE TITLE
Clarifying e2e mnemonic description

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2442]
edit: It seems people can recover the mnemonic.  I hope this changes via #2443. :heart: 

Related to #2433 for e2e documentation on Nextcloud desktop client. [Revoke Keys](https://github.com/nextcloud/end_to_end_encryption/issues/32) discussion and [issue for better overall documentation](https://github.com/nextcloud/documentation/issues/11274).

Please clarify in the app that a mnemonic will only be shown that singular time, and will disappear forever once you select _Enable encryption_.

![a5f57688e6e91b1ec7573180b5943cfdc8778f06](https://user-images.githubusercontent.com/1787238/93411222-81ae2580-f84f-11ea-80bf-15c1b3814dbd.png)

I appreciate the wording you have on 3.0.1, but it is not clear enough.  Thanks for considering.
![e8d76bb78f7d03e9995b0f16b1d56ccdaecba588](https://user-images.githubusercontent.com/1787238/93411299-b1f5c400-f84f-11ea-8232-f78ddd32daed.png)

To protect your Cryptographic Identity, we encrypt it with a mnemonic of 12 dictionary words.  You must record and never lose these 12 words.  These will never be shown again once enabled and are required in case you ever lose access to your data or wish to add other devices to your account (like your mobile phone or laptop).  Have you recorded these words?  Record them carefully then Enable encryption.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
