### ISSUE TITLE
Never display mnemonic again once enabled.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2443]
Once enabled, please never show the mnemonic again within the desktop client application.  Otherwise, anyone can recover the key by accessing the desktop client on a computer logged into a Nextcloud account.

**Comment by er-vin** [comment]
I'll let you discuss that one with @jospoortvliet :-)

**Comment by sunjam** [comment]
I'm thinking of the typical bitcoin wallet where the user sees the mnemonic once during activation.  If by design you are still able to see or recover the mnemonic for the desktop or mobile client, it is always guarded behind some sort of password ala #684.  In this scenario, the key is normally forgotten by the client entirely after _X_ incorrect passwords to avoid brute force attacks.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
