### ISSUE TITLE
Too Many Shortcuts In Windows File Explorer!

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/desktop#2449]
While I appreciate this feature to show Nextcloud folder syncs like Dropbox or OneDrive in the left pane of Windows File Explorer, on one of my machines I'm logged into multiple accounts each with multiple folder sync connections (not just the entire folder). For each sync connection, I have another drive shortcut in Windows Explorer. I would prefer to disable these or at least have the option to turn them off, since they take up a majority of the "quick access" area. I'm happy to completely disable it, but if there's a way to enable/disable per sync connection that's even better.

![image](https://user-images.githubusercontent.com/5169868/93629112-c05df000-f9b5-11ea-8738-3e0c46c0f3df.png)

**Comment by Id3aFly** [comment]
To disable the explorer integration completely you can go to the settings, and disable the marked option:

![Image](https://i.imgur.com/EsuwCbd.jpeg)

**Comment by linucksrox** [comment]
Thanks! I didn't see that option was added, but that's exactly what I need.

**Comment by Id3aFly** [comment]
Glad I could help!
