### ISSUE TITLE
[ENHANCEMENT] Share Context Link

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#245]
I would like to suggest a feature if this is possible at all but to give the ability for a user using the Desktop client to create a share link directly from the context menu section so to eliminate the need to login into the website and create a share link from there.

**Comment by michaelstingl** [comment]
Related discussion in upstream project: https://github.com/owncloud/client/issues/6356

**Comment by DominiqueFuchs** [comment]
Meanwhile implemented (also in latest stable)
