### ISSUE TITLE
3.0.1 Sync pauses when screen locked

### ISSUE THREAD

**Issue by Frizou** [nextcloud/desktop#2453]
### Expected behaviour
. I expect desktop client to upload huge files during night, while my desktop screen is locked

### Actual behaviour
. file upload pauses during screen is locked

### Steps to reproduce
1. add huge files to local directory to be synced
2. check upload starts with command line "date;ifconfig enp0s25 | grep bytes", and compute upload bandwidth
3. lock screen clicking to "switch user"
4. wait a while
5. unlock screen
6. launch again command line "date;ifconfig enp0s25 | grep bytes", and compute upload bandwidth during screen locked --> upload near zero
7. wait a little bit, compute again upload bandwidth --> good

### Client configuration
Client version/package: Nextcloud-3.0.1-x86_64.AppImage
Operating system: GNU Linux Ubuntu Studio 20.04 (Xfce 4.14)
OS language: French
Qt version used by client package (Linux only, see also Settings dialog):
. Version 3.0.1git (build 3356). For more information please click here.
. This release was supplied by Nextcloud GmbH
. Built from Git revision 0a6262 on Aug 28 2020, 09:50:30 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020
Installation path of client: $HOME/Téléchargements

**Comment by iliuili** [comment]
The same bug.

**Client configuration**
Ubuntu 20.04.3 LTS
Xfce 4.14
`nextcloud --version`
Nextcloud version 2.6.2-1build1
Using Qt 5.12.8, built against Qt 5.12.5
Using 'OpenSSL 1.1.1f  31 Mar 2020'

**Comment by mgallien** [comment]
> The same bug.
> 
> **Client configuration**
> Ubuntu 20.04.3 LTS
> Xfce 4.14
> `nextcloud --version`
> Nextcloud version 2.6.2-1build1
> Using Qt 5.12.8, built against Qt 5.12.5
> Using 'OpenSSL 1.1.1f 31 Mar 2020'

Unfortunately, the version of desktop client that you are using is very old.
Are you able to test again with the last release ([Files client download](https://nextcloud.com/install/#install-clients) choose the Appimage version that is known to work everywhere and easy to install, the PPA is outdated) ?

**Comment by utzer** [comment]
Same for Nextcloud Desktop Client 3.7.3
Debian 12.1
Linux 6.1.0-12-amd64 x86_64
