### ISSUE TITLE
Client deleting local copy of files when external volume is not available

### ISSUE THREAD

**Issue by bjarneeins** [nextcloud/desktop#2454]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client should hold on to the local copy of the files and sync them as soon as the external storage is available again. 

### Actual behaviour
I set up a LUKS container and mounted it to some point in the filesystem.

I then added the mountpoint of the container as external storage in my nextcloud, assigned it to my user and synced my files. So far everything seemed fine but i am facing one problem.

When the LUKS container is not mounted and can therefore not be accessed by the nextcloud, my client (Fedora 32) does delete all local files which are stored on the externel storage and acts as if nothing is stored on the nextcloud.

When I then remount the Container all the files will get synced.

### Client configuration
Client version: 2.6.5 (Fedora)

Operating system: Fedora 32

### Server configuration

Nextcloud version: 19.0.3

Storage backend (external storage): Local storage

**Comment by er-vin** [comment]
To be sure I understood, the LUKS container is on the server side, right?

**Comment by bjarneeins** [comment]
Yes, it is on the server side.

**Comment by er-vin** [comment]
Not sure we can do much about this... the server tells us the content of the folder is gone in that case so we're supposed to abide by information.

**Comment by mburnicki** [comment]
Might the server be able to distinguish the case where a volume is (temporarily?) not accessible from the case where a volume/folder has been explicitly deleted/removed, and send an appropriate reply to the clients?

So a client could delete the folder if the folder has been deleted on the server, but it could still keep the folder if the server is  (temporarily) unable to access the volume, and wouldn't have to download the whole folder once more when the volume becomes accessible again.

**Comment by er-vin** [comment]
I guess those questions would need to be brought up with the people more active on the server, I don't master that part well enough.

**Comment by bjarneeins** [comment]
> Might the server be able to distinguish the case where a volume is (temporarily?) not accessible from the case where a volume/folder has been explicitly deleted/removed, and send an appropriate reply to the clients?
> 
> So a client could delete the folder if the folder has been deleted on the server, but it could still keep the folder if the server is (temporarily) unable to access the volume, and wouldn't have to download the whole folder once more when the volume becomes accessible again.

This is exactly what i was thinking about. :)

**Comment by bjarneeins** [comment]
Where would i have to adress this to get something like this implemented?
