### ISSUE TITLE
Black & White icons: Dark version for a light panel

### ISSUE THREAD

**Issue by jkufner** [nextcloud/desktop#2459]
I really like the subtl black&white icons. Unfortunately, my panel is light grey. The white icon on light grey panel is barely visible.

Please add dark grey icons that fit neatly with default KDE Plasma color scheme.

The dark grey color of other icons is `#4d4d4d` — see https://hig.kde.org/style/color/default.html.

Nextcloud client: nextcloud-desktop 2.6.4-1 from Debian.

**Comment by casasfernando** [comment]
I have the same problem in elementary OS 6. I love the monochrome icons as they blend a lot better with the panel.
Unfortunately in elementary OS  the panel transparency and background color can change automatically based on the desktop background. In some scenarios, where the background is very light, the white icon is almost impossible to see. This is not an issue with darker backgrounds as you can see in the screenshots below.

Darker background (ok):
![image](https://user-images.githubusercontent.com/15861819/137395854-73922b92-83f9-42bd-ad56-75a3ccb07e53.png)

Lighter background (not ok):
![image](https://user-images.githubusercontent.com/15861819/137396085-63bee4d8-5b06-4604-89db-dede294148d9.png)

As you can see in the screenshots other panel icons will automatically change to a dark variant when the panel background is light and to a lighter variant when the panel background is dark.
I'm not sure how this is achieve, but I think is CSS related, and SVG icons are required.
Do you think it would be possible to provide achieve something similar with Nextcloud Desktop client panel icons?

Thanks.

**Comment by claucambra** [comment]
Unfortunately there isn't much we can do about this on elementary. We do support black and white versions of the sync icon which work on most platforms with standard implementations of the system tray, so I will close this
