### ISSUE TITLE
Roll back to previous version please. 

### ISSUE THREAD

**Issue by fishscene** [nextcloud/desktop#2462]
Multiple issues submitted in one. Sorry, the amount of 

1) The GUI interface is confusing and counter-intuitive. 
2) Give option or remove explorer.exe links to Nextcloud folders in left-panel. In most cases, this is redundant and it is space-hogging. There's no way to minimize these as a category like in "Quick Access" or "This PC". 
3) Default the GUI in the tray to the Sync folders, which shows the sync status for multiple folders. I *REALLY* don't care to see a log file. If you think I'm wrong on this, name one other software that defaults the end-user experience to a log file.

**Comment by Id3aFly** [comment]
For your second question please see: #2449 

Regarding your first question it would be quite helpful for the developers if you could address your problems and wishes in more detail. If you want to improve your constructive criticism even more, you cold create several issues for it. That makes it way more easier to handle. Each one regarding one bug or problem you experience or see.

**Comment by er-vin** [comment]
What @Id3aFly says, I'll thus close this one.

Also please check first if the issues don't exist first before filing a new one. People tend to underestimate the effort spent on just chasing duplicates to not drown (and that time is taken away from actually fixing things).

**Comment by fishscene** [comment]
This issue was given the same respect for the issue process as the 3.0.1 Windows release had for end-users. Although the development team has the authority to close the issue (as they should), I have the authority to completely move away from the platform based on the next release (as I should based on the best interest of my users). 

I'll be watching how the next release handles the end-user experience.
