### ISSUE TITLE
"There are unresolved conflicts. Click for details." doesn't work very well

### ISSUE THREAD

**Issue by cyclops1982** [nextcloud/desktop#2464]
### Expected behaviour
I have a few connections setup, and some have conflicts.
I'd like to resolve these conflicts but i'm not able to find out easily how to do that. The settings dialog shows a yellow/amber line that states `There are unresolved conflicts. Click for details.` but clicking on this does nothing.

### Actual behaviour
I'm unable to resolve my conflicts.

### Steps to reproduce
1. Setup a sync
2. Create a conflict

### Client configuration
Client version: 3.0.1

Operating system: Windows 10 (LTSB)

OS language: en-us

Installation path of client: Default :c\program files\nextcloud\

### Server configuration

Nextcloud version: Nextcloud 18.0.7

Storage backend (external storage): N/A

**Comment by cyclops1982** [comment]
I'd like to update this ticket.

I was able to resolve my issue by finding the conflict file. I guess this item needs to be turned into a feature request because it's just not practical how this works.

The dialog that you get when you click on the nextcloud icon doesn't show the full paths. When you double click on the item, you go to the websites' files, not to the specific file or to the folder on the local disk where the conflict actually is. It would help if it did that so one can resolve teh conflict.

My paths are too long to fit into the dialog.

**Comment by stevleibelt** [comment]
Looks like your ticket is a duplication of [this](https://github.com/nextcloud/desktop/issues/1195) one.

**Comment by cyclops1982** [comment]
I agree, that's the same issue.
