### ISSUE TITLE
Nextcloud desktop core dumps in the background

### ISSUE THREAD

**Issue by PopeRigby** [nextcloud/desktop#2476]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud desktop shouldn't crash

### Actual behaviour
Nextcloud crashed in the background

### Steps to reproduce
Not sure. I was checking my systemd journal and saw that Nextcloud crashed 2 days ago. I don't remember it crashing.

### Client configuration
Client version: 3.0.2-1

Operating system: Arch Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.1

Client package (From Nextcloud or distro) (Linux only): Distro

Installation path of client: `/usr/bin/nextcloud`

### Server configuration

Nextcloud version: 19.0.3

Storage backend (external storage): N/A

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client core dump:
[nextcloud_core_dump.txt](https://github.com/nextcloud/desktop/files/5289308/nextcloud_core_dump.txt)

2. Web server error log: N/A

3. Server logfile: nextcloud log (data/nextcloud.log): 
[nextcloud.zip](https://github.com/nextcloud/desktop/files/5289329/nextcloud.zip)
(Sorry about using a zip file. It's so big that Gist crashed when I tried to paste it in)

**Comment by er-vin** [comment]
Hm... that backtrace looks very much like the one provided in #2333

Clearly something fishy in CloudProviderWrapper. I'd need a more precise backtrace with debug symbols and debug sources to pin point the line where it goes haywire. Please move the discussion there, if we can get more precise information I'm definitely taking.
