### ISSUE TITLE
[Feature] Activity feed missing in frontend

### ISSUE THREAD

**Issue by NicolasGoeddel** [nextcloud/desktop#2480]
### Activity Feed
It seems that the activity feed was removed in favour to the tiny popup window which you can get when you click on the notification icon. This is really inconvenient. If I got lots of conflicting files I can not get a proper view over all of them. Also when I click on one of the files the popup windows closes, and a new file manager window opens every time which is also annoying.

What I need is what the owncloud client offers:
![image](https://user-images.githubusercontent.com/1520064/94470321-d050ad80-01c7-11eb-9da1-3d2fa61baae5.png)

But the nextcloud client only shows this:
![image](https://user-images.githubusercontent.com/1520064/94470428-f7a77a80-01c7-11eb-9609-e53b4c1892c5.png)

### Client configuration
Client version: 3.0.2

Operating system: Ubuntu 20.04

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): There is no version in the settings dialog.

Client package (From Nextcloud or distro) (Linux only):
3.0.2-20200924.150911.068ad89d8-1.0~focal1
http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal/main amd64 Packages

Installation path of client:
/usr/bin/nextcloud

**Comment by er-vin** [comment]
@jancborchardt opinion? I don't think we want to go back in time like this but let's see.

**Comment by NicolasGoeddel** [comment]
I also like the fresh design in the popup menu although my nvidia drivers decide to destroy the graphics cache after each suspend (which I can not show here because the window closes every time I want to make a screenshot). But I guess this has nothing to do with the client. It's just nvidia gibberish.
Nevertheless I liked the main window with all its possibilities it had before. I liked the big window with the list of all recently synchronized files, all conflicts, and all ignored files. If you have file paths with more than 200 characters it helps a lot to have a big window.

Also unfortunately the tray icon is missing on a LXDE desktop which I connect to over XRDP. But I guess this should be a separate ticket then.

**Comment by cmasterdelphi** [comment]
I personally dislike the "new" Client very much and rolled back to 2.6.5 on all my devices. The "new" Client is not usable such as:
- shows conflicts but you cannot even jump to the issue / file
- the diaglog box from the systray icon is black/unreadable half the time
- I am not able to add more accounts anymore from the main window (why was this killed?)

**Comment by daladim** [comment]
I really miss that "activity" tab too.
Is this a bug or has it been removed on purpose?

I used it a lot to check that a transfer is going on as expected, or to monitor what is happening (which is very important when using scripts that may automatically move files, software that may automatically sort pictures or songs...or just to check Nextcloud is working correctly in case of a new user having installed it for the first time).

Thanks

**Comment by camilasan** [comment]
> Is this a bug or has it been removed on purpose?

On purpose.

>     * shows conflicts but you cannot even jump to the issue / file

We are working on improving things in the new UI. See #2527.

**Comment by K0HAX** [comment]
I am for improving things, but not at the expense of user experience. I find the new UI harder to read, and not being able to have it up while I'm doing other things on the machine (because clicking anywhere else makes it go away) make it less useful than the old UI.

**Comment by RedKage** [comment]
Same here, the new UI is a big step backward.
I share all of the above.

And, I am adding this:
![Untitled](https://user-images.githubusercontent.com/11867168/97801190-4028dc80-1c3b-11eb-9c45-f96c1f5ee0f1.png)

Windows OS, I have my tray bar at the top of the screen.
- When I click on the nextcloud tray icon I have a nvidia popup which tells me I can access the ALT+Z hotkey just like in video games. But it goes right on top of the menu
- The tray menu doesn't disapear when I click on the nextcloud tray icon and it stays on top of the nextcloud floating UI

The previous UI was poor, but the new one is even poorer.

**Comment by jancborchardt** [comment]
Hi, thanks a lot for the feedback everyone! We improved a lot of things with the new dialog in the meantime. Of course there’s always more things to fix, but this issue discussion has so many different points in it, unfortunately it’s not easy to get an overview.

For any issues you still encounter, please use the search to see if it already exists, and:
- If there is an issue already, please use the reaction feature to give the main post a :+1:
- If it doesn’t exist yet, please open _one_ separate issue for each problem

That helps us a lot to prioritize and fix the issues. Thanks a lot! :)
