### ISSUE TITLE
the ".sync-exclude.lst" does not work after restart the client

### ISSUE THREAD

**Issue by cntangt** [nextcloud/desktop#2482]
Version: 3.0.1 & 3.0.2
OS: windows 10 x64
STEP:
1. Edit the ".sync-exclude.lst", for example:
_temp
transfer_log.json_
2. run my program, the directory "temp" and file "transfer_log.json" are created
now, they are not synced
3. exit the nextcloud client
4. run the nextcloud client
now, both the "temp" and "transfer_log.json" are synced

**Comment by J4cker14** [comment]
last working client version 3.0.3

I can confirm, that the new client is not respecting that ignore files

**Comment by cntangt** [comment]
thanks, it was fixed.
