### ISSUE TITLE
Linux/Wayland Settings  "Click for details" does nothing

### ISSUE THREAD

**Issue by ohthehugemanatee** [nextcloud/desktop#2484]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

I should see extra details when I click on "Click for details".

### Actual behaviour

Nothing.

### Steps to reproduce
1. Install Nextcloud client with https://www.archlinux.org/packages/community/x86_64/nextcloud-client/
2. Trigger a status warning with eg a sync conflict.
3. Click the "click for details" link in the status warning.

### Client configuration

Operating system: Manjaro Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 
Qt 5.15.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 10.2.0) on "xcb"

Client package (From Nextcloud or distro) (Linux only):
v3.0.1 installed from https://www.archlinux.org/packages/community/x86_64/nextcloud-client/ .

Installation path of client:
`/usr/bin/nextcloud`

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[nextcloud.log](https://github.com/nextcloud/desktop/files/5298460/nextcloud.log)

2. Web server error log: not relevant

3. Server logfile: n/a

**Comment by er-vin** [comment]
This is not wayland specific and we got a couple of other reports for that one like #1195. Thus closing this one.

**Comment by ohthehugemanatee** [comment]
thank you, I didn't see that report in my searching. Will continue there.
