### ISSUE TITLE
F12 is already an assigned global hotkey on Mac.

### ISSUE THREAD

**Issue by AstraQuinn** [nextcloud/desktop#2488]
Expected behavior: The documentation specifies that pressing F12 on the client on any operating system will show the log window

Actual behavior: On Mac OS X F12 is already mapped to show the Dashboard by default. The hotkey doesn't work and I have to make Luddite users open the Terminal and run a command, which they might not do out of sheer fear of the unknown.\

Steps to reproduce: Open the Nextcloud window. Press F12 per the documentation.

Client configuration: Mac OS X, some recent version,  client 2.5.6.

This can be worked around by disabling the Dashboard hotkey feature, but this doesn't seem right. I don't need to change default system settings on Windows or Linux to make the client do what it's supposed to.

I fully understand the appeal of maintaining consistency between operating systems but from my perspective as a lowly sysadmin, this is just a bug. I would much rather simply have my Mac users use another key combo to bring up the log window than ask them to change system settings or run terminal commands.

**Comment by elsiehupp** [comment]
I have to press Fn-F12 in order to get the logs to open. That said, it would be nice if there was a more easily discoverable way to open the logs via the GUI.

**Comment by er-vin** [comment]
3.1 will change the way we deal with this. We'll start logging by default and the settings dialog will have a button allowing to create a zip containing all the debug information.

**Comment by AstraQuinn** [comment]
That would resolve this issue for me and my clients, at least! Thank you!

**Comment by er-vin** [comment]
OK, then I'll close it now. Since #2514 has been merged the solution I described above will be in 3.1.
