### ISSUE TITLE
Nextcloud-client multiple synchronizations interfere

### ISSUE THREAD

**Issue by ingoaltair** [nextcloud/desktop#2489]
### Expected behaviour
When adding a "Folder-Synchronization" in the client, even with the same base folder on the server, it should not interfere with any existing synchronization.

### Actual behaviour
After using the button "Ordner-Synchronisierung hinzufügen" (Add Folder-Sync), and choosing the root-folder on the server, all folders are unchecked in both the new sync and the original root sync, that I had. 

### Steps to reproduce
1. Create Account and add synchronization of the servers root https:/myserver/nextcloud/ to a local directory /data/a/nc. In my case, some folders below the root were checked, others weren't. 
2. let it do its work and sync the data
3. Create a second sync in the same account. Again, the same root on the server https://myserver/nextcloud, but a different local directory /data/b/nc
4. Check a different (in my case disjoint) set of folders below the root.
5. let it run
6. Go back and look into both configurations. In my case, all folders were unchecked.

additional info:
My intent is to have some of the data synchronized to the ssd in my desktop and others synched to the hdd. 
In a previous setup, I added two accounts to the client, because I didn't see the button below, which allows me to add an additional synchronization to the same account. That failed. It worked in the beginning, but with a more recent version of the client, it started to use the same folder selection for both accounts. Some of the folders beeing not synced and thus empty on one of the accounts (which had those folders unchecked before), these we considered deleted. After realizing the mistake, I wiped all local data and config files and started from scratch.
This time, using one account in the client, but adding synchronizations. The precise way I set this up was:
1. Created account and selected toplevel/root on the server. I started checking only one folder first, and when I observed things are going right, I continued to check all but a few large folders. 
2. I created a second sync in the same account. On the server I selected a subfolder of toplevel/root. This also worked well, but was not what I wanted. I needed the root on the server, so I could check a set of folders inside.
3. I left the sync of step #2 intact, but added a third one, this time selecting root on the server again. I checked a few folders inside a subfolder of root. They were basically the same folders as in #2. 
There was indeed a warning, that I have the same sync already, but it didn't make sense to me, because I need to sync to a different local directory. 
4. I started the sync, and immediately entered back into the configuration of both sync at root. Both of them had all folders unchecked. 
5. Despite all folders unchecked, no local data has been removed so far. But, my bet goes, if I do any change to the settings and ask to apply them, all folders that I failed to check will be removed. 

I appreciate, there is a warning, but:
* The warning does not explain, what the issue really is
* This use case should be supported
* even in the earlier setup, that I had with two accounts. This use case should be either supported or an explicit warning, that states that data can be lost should appear. 

### Client configuration
Client version: 3.0.1

Operating system: majaro 20.1
kernel: 5.8.6-1-MANJARO

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 5.15.0

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version: 15.0

Storage backend (external storage): no external

### Logs
for now, this one is a configuration issue, so I don't expect logs to matter

**Comment by er-vin** [comment]
@DominiqueFuchs I guess this didn't happen before because the journal db was in the sync folder itself, now that they are in a shared space we can indeed end up with collisions like this... we need a way to reduce such collisions I guess?

**Comment by ingoaltair** [comment]
Just looked at nextcloud.cfg
Again, the two interfering instances are pointing at the same db file. 
My understanding of the situation might be limited, but I don't see, why this is related to having the config in the synced folder or not. 
To me it seems, the name of the db file (this apparently random hex number) is generated from the server path. Hence, if I choose the same path again, it will generate the same filename, overwriting one with the other. Since I can't use the name for anything, why not creating a UUID and use it as the name? That would probably be, what you're saying as "reducing such collision"? 
If I'd be brave, I could hand edit the file and force it to use a separate db for the other instance. But I am not sure, what can happen down the road, when the client is upgraded or I generate more syncs. 
Any idea?

**Comment by ingoaltair** [comment]
I went ahead and changed the line in the config from _sync_34ab345ba.db to _sync_handcrafter.db 
It nicely generated a new db file automatically at next start of the client. All folders were checked and I undselected all, but those I wand. 
I am curious to how it goes and open to any warnings from anybody here.

**Comment by er-vin** [comment]
That looks like a good way to overcome it indeed.
