### ISSUE TITLE
AppImage should provide a .desktop file

### ISSUE THREAD

**Issue by oxivanisher** [nextcloud/desktop#249]
Since the Nextcloud client ideally runs after login automatically ("autorun", "startup") it would make much sense to let the AppImage deploy a .desktop file, so that the AppImage can be handled like any normal app. At the moment, the user has no possibility to let the client start at login without creating a .desktop file himself. As an example, the https://github.com/prusa3d/PrusaControl/ AppImage asks the user if a `.desktop` file should be created at the first launch of the application.

Sadly, I was not able to quickly find out how this is done exactly. Only that it has to do with `appimaged`. But I am sure, that @probonopd might help with this.

Probably useful links:

- http://discourse.appimage.org/
- https://github.com/AppImage/AppImageKit#appimaged-usage
- https://askubuntu.com/questions/902672/registering-appimage-files-as-a-desktop-app
- https://github.com/AppImage/AppImageKit/releases/

**Comment by probonopd** [comment]
If you want AppImages to be automatically integrated into the system (e.g., menus, MIME types, etc.) then all you need to do is install the optional `appimaged` daemon, e.g., from https://github.com/AppImage/AppImageKit/releases. Once you have done that, it will happen automatically.

**Comment by oxivanisher** [comment]
This happens with other apps, but not with the Nextcloud client. I also did a little digging and found no other nextcloud*.desktop file on my system. Just to make sure its not a residue from the previous installation.

**Comment by camilasan** [comment]
Any more information on this @rullzer?

**Comment by probonopd** [comment]
Inside the AppImage there needs to be a `usr/share/applications/nextcloud.desktop` file for `appimaged` to be able to do its work.

**Comment by jancborchardt** [comment]
@camilasan @rullzer it seems the info is there, we just need to add the desktop file inside the AppImage as @probonopd said? :)

**Comment by jancborchardt** [comment]
@probonopd maybe you want to open a pull request to fix that?

**Comment by probonopd** [comment]
So, is the question that this does not work when tools like the optional [`appimaged`](https://github.com/AppImage/appimaged) daemon or [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher/) are used, or is the question what to do when neither are used?

**Comment by jancborchardt** [comment]
@probonopd I would say ideally it should work in any of those situations. Making it work with appimaged etc. seems like a good first step?

**Comment by probonopd** [comment]
Yes. Users who want desktop integration are advised to use one of those tools.

**Comment by mind-overflow** [comment]
Wow, still no update on this?

**Comment by FlexW** [comment]
This works fine. We provide a .desktop file. You need to use one of the tools @probonopd advised. For example I used [https://github.com/probonopd/go-appimage/releases](https://github.com/probonopd/go-appimage/releases).
