### ISSUE TITLE
Updating to 3.0.2 selects all folders to sync

### ISSUE THREAD

**Issue by thejulian** [nextcloud/desktop#2492]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Updating from 2.6.x to 3.0.2 should keep the folders which are selected to sync configured as them

### Actual behaviour
ALL folders are selected to sync.

### Steps to reproduce
1. Remember selected folders
2. Update to 3.0.2
3. Check which folders are selected

### Client configuration
Client version: 3.0.2

Operating system: Windows 10

OS language: German

Installation path of client: default

### Server configuration

Nextcloud version: 19.0.3

### More Information
Actually happened to three different employees. But the first two updated to 3.0.1 more then one week ago. Today I've updated to 3.0.2 on another machine. Same behavior. Then i tried it on MacOS - everything worked as expected, so it seems to be an Windows related topic?

**Comment by er-vin** [comment]
Hm... I was pretty sure we had a duplicate for that one but can't find it now, let's tag.

**Comment by thejulian** [comment]
> Hm... I was pretty sure we had a duplicate for that one but can't find it now, let's tag.

you closed them two days ago --> #2279 and #1750 .

**Comment by er-vin** [comment]
Ah right thanks. Juggling too many balls at the same time. :-)

**Comment by szarpaj** [comment]
Also affected, I think the client was updated from 2.6.5 as 3.0.1 had some other issues (on this machine it was like 2.6.5->3.0.1->2.6.5->3.0.2). It seems that also the default 500MB limit isn't honored - I've added few gigabytes on other machine and 3.0.2 stared syncing those without asking (server @19.0.3).

**Comment by ThomGr** [comment]
Not sure if this is connected, but it seems to me: I had the same issue of all folders selected for syncing flooding my internal HD with all the photos from the past. So I deselected all but the previous year folders and everything was fine
Now the additional issue: when connecting the large external HD, the syncing for that instance of NC had the same folders deselected. I cannot have two "synchronizations" (not sure how this is called in the English UI) of the same folder with different sub-folders selected for each of them.
