### ISSUE TITLE
Client sync changes detection issue

### ISSUE THREAD

**Issue by iskullboxdotdev** [nextcloud/desktop#2494]
Hi,
I've been using NextCloud GUI sync client from the official repository on Ubuntu desktop.
After a file push to the folder, periodically it does not detect all the files in a newly updated folder.
The folder with all files is 80MB.
3rd build got synced 72MB of files, while the one after that was about 60MB, with half of the files missing.
Changes get noticed and synced only after the client restart.
NextCloud 19.0.1, dockerized with MariaDB and FPM for web.
NextCloud client v. 2.6.5. ( from ppa:nextcloud-devs/client)
Ubuntu 16.04. Kernel 4.4
I've also tried latest (3.0.2.) AppImage, still have the same issue.

**Comment by er-vin** [comment]
@camilasan could that be related to your work on #2322 ?
