### ISSUE TITLE
Client not reliably syncing new folders, tray icon does not actually reflect sync status

### ISSUE THREAD

**Issue by FloMiLe** [nextcloud/desktop#2495]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The client should reliably sync files and folders.

### Actual behaviour
Upon adding a folder tree with subfolders and files into a synced directory, only the parent and direct daughter folders are created on the server, but those remain empty. The sync client seems happy, falsely showing the checkmark in the tray icon indicating all should be done and well.

Only after restarting the client does it actually copy all files and folders to the server.

### Steps to reproduce
1. Have a sync client (with multiple accounts connected?).
2. Copy a folder structure with many levels of subfolders and files into a synced folder.
3. Hope for syncing to happen.

### Client configuration
Client version: 3.0.1 (macOS)

Operating system: macOS 10.15.6

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications/nextcloud.app

### Server configuration
Nextcloud version: 19.0.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by er-vin** [comment]
Should be fixed with #2439
