### ISSUE TITLE
Nextcloud-client warns to check the log files

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/desktop#25]
Over the past months I have had some sync issues occasionally. The client then issues a warning to check the log files for information about the issue.

I'm used to it now, but initially this message created some head scratching. 
First of all it wasn't clear if this was pointing at a log of the client or a log on the server. (I figured this out now:-) 
Secondly, it would be nice if there was a link to the log, as it is available in the admin backend, or at least describe in one of two sentences how to get to the log files.

**Comment by michaelstingl** [comment]
@brjhaverkamp [Nextcloud Administration Manual](https://docs.nextcloud.com/server/12/admin_manual/) points to the [ownCloud client docs](https://doc.owncloud.org/desktop/latest/) where you can find detailed instructions how to get client and server logs: https://doc.owncloud.org/desktop/latest/troubleshooting.html#log-files

**Comment by brjhaverkamp** [comment]
Indeed. My request is merely a userfriendliness improvement. To add a bit of reference text or a link to where the relevant logs can be found. So the user has an immmediate starting point if there is a problem.

**Comment by camilasan** [comment]
what do you think @jancborchardt?

**Comment by jancborchardt** [comment]
@camilasan where is this warning displayed? As a notification or in the settings window?

Either way, it would be great if the client could simply show a window with the logs so people can inspect it. Or if the error persists, a quick link to open an issue here with the logs as issue content (of course with personal info removed).

**Comment by markshep** [comment]
I keep getting this error and have no idea where the logs are.  I really don't want to go trawling through loads of documentation to work out where to find them, I just want to know what went wrong.  Please make this more use friendly.

**Comment by jancborchardt** [comment]
@brjhaverkamp @markshep would what I suggest at https://github.com/nextcloud/desktop/issues/25#issuecomment-389175911 solve the issue for you?

**Comment by er-vin** [comment]
Could someone give us the exact text of that warning? This would help narrowing it down, currently I'm not quite sure what to search for.

**Comment by brjhaverkamp** [comment]
Sorry, I haven't had this error for a longtime. So I am not able to provide a screenshot, I'm afraind

**Comment by camilasan** [comment]
This all sounds too vague. Since this issue was opened we had quite a few changes in how we display notifications.
Please check the latest client 3.2.4. If you still have issues with how notifications/errors are displayed, please open a new issue with screenshots :)
