### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by FlorentCoppint** [nextcloud/desktop#2501]
Hi,
I'm running Nextcloud client 3.0.2 on Ubuntu 20.04.
I have multiple server sync configured, including one with millions of files.
After few hours of normal behaviour, kernel kills Nextcloud process with "Out of memory" error.

> [899491.102134] Out of memory: Killed process 2064210 (nextcloud) total-vm:8186652kB, anon-rss:3419052kB, file-rss:0kB, shmem-rss:4kB, UID:1000 pgtables:10812kB oom_score_adj:0
> [899491.257237] oom_reaper: reaped process 2064210 (nextcloud), now anon-rss:32kB, file-rss:4344kB, shmem-rss:4kB

Laptop is running with 16GB of RAM, and Nextcloud client uses sometimes multiple GB of RAM...

What can I do ? To solve problem, or to debug it and help ?

**Comment by er-vin** [comment]
There are probably more memory leaks but one which was one of the main offenders was fixed last week with #2477. It's been backported and will be available in 3.0.3 in a couple of weeks. I will thus close this issue, please open a new one if that shows up again with 3.0.3. If you don't want to wait for 3.0.3 you can always test with the appimage posted on #2477 (assuming it is still available) and see how that fares.
