### ISSUE TITLE
You should be able to change language in the client

### ISSUE THREAD

**Issue by wahboh** [nextcloud/desktop#2517]
I see nowhere an option to change display language in the client. As of now it is a terrible mix of English and local (Swedish) text. The translations are OK when they appear, but there are still many (fixed) items left in English. 

If not all texts are translated, most of us prefers to switch to English entirely. But I see no such option?

**Comment by ftoledo** [comment]
also App Image v3.1.1 dont honor the locale settings:

```ragnarok@hp:~/AppImage$ locale
LANG=es_AR.UTF-8
LANGUAGE=es_AR:es
LC_CTYPE="es_AR.UTF-8"
LC_NUMERIC="es_AR.UTF-8"
LC_TIME="es_AR.UTF-8"
LC_COLLATE="es_AR.UTF-8"
LC_MONETARY="es_AR.UTF-8"
LC_MESSAGES="es_AR.UTF-8"
LC_PAPER="es_AR.UTF-8"
LC_NAME="es_AR.UTF-8"
LC_ADDRESS="es_AR.UTF-8"
LC_TELEPHONE="es_AR.UTF-8"
LC_MEASUREMENT="es_AR.UTF-8"
LC_IDENTIFICATION="es_AR.UTF-8"
LC_ALL=
```
![Captura de pantalla_2021-01-27_16-01-27](https://user-images.githubusercontent.com/95441/106040429-36d3d280-60b9-11eb-9236-09a7bc97d065.png)

**Comment by er-vin** [comment]
Duplicate of #111
