### ISSUE TITLE
NextCloud Popover not pop outs

### ISSUE THREAD

**Issue by hectorskypl** [nextcloud/desktop#2537]
### Expected behaviour
It should open the  popover

### Actual behaviour
Open just blank windows

### Steps to reproduce
1. click on notification area

### Client configuration
Client version: 3.0.2

Operating system: Windows 10 Enterprise 1607 2016 LTSB

OS language: Polish

Installation path of client: C:\Program Files\NextCloud

### Server configuration
Nextcloud version: 19

### Logs

1. Client logfile:  https://gist.github.com/hectorskypl/4f728d9f6761174a40d92cf3a03944f9

**Comment by pureche** [comment]
Having the same issue here. Clicked the notification icon, nothing shows up. Invisible menu above the notification icon that hangs.

**Comment by hectorskypl** [comment]
> 
> 
> Having the same issue here. Clicked the notification icon, nothing shows up. Invisible menu above the notification icon that hangs.

If you have radeon GPU you might install latest beta drivers cause seems its driver issue.

**Comment by pureche** [comment]
> > Having the same issue here. Clicked the notification icon, nothing shows up. Invisible menu above the notification icon that hangs.
> 
> If you have radeon GPU you might install latest beta drivers cause seems its driver issue.

Thanks for the reply. Unfortunately I have an Nvidia RTX 2080 Ti. And I just updated the driver. Doesn't fix it.

I also tried to install an earlier version of 3.0.1 since I updated it yesterday to 3.0.2. Still hangs with nothing functional.
