### ISSUE TITLE
Recent updates are unreliable - Desktop client windows

### ISSUE THREAD

**Issue by lucker999** [nextcloud/desktop#2545]
Hi there,

two recent updates (starting with 3.0) caused a lot of problems resulting in disruption of the work and missing deadlines in order to do the work over again. See details in [issues 2507](https://github.com/nextcloud/desktop/issues/2507), [issues 2492](https://github.com/nextcloud/desktop/issues/2492)
**First**, after an update the client unselects / selects all / selects randomly the list of folder to sync. It was not the case with previous version (before 3.0). I noticed it after a couple of days after the updates and, since the files were edited on three different machines, it resulted in 70 sync conflicts. Now I need to open three versions of each files and manually compare them in order to compile recent version. Thanks for a lot of additional work.

**Second**, it is impossible to get list of conflicted files (thanks so much for the useless new floating window as an interface). The files listed in this new window, but only a beginning of the path is visible. So, I see a lot of paths without file list and it is impossible to locate conflicting files. I can't evel scroll this list!

**Third**, the highlighted text "There are unresolved conflict. Click for details"  simply do nothing. Just symbolizes there.

**Fourth**, there is no option to disable this shiny new floating interface, which is brought nothing in terms of usability and only confusing, popping up instead of usual interface we all are familiar with.

### Expected behaviour
- *urgent* - please advise ASAP how I can list conflicting files! I can't proceed with the work!
- no changes in folder sync (three update in a row!)
- list of conflicted files, which I can at least browse comprehensibly, or better - export
- option to disable the new interface or switch back to old one if you are substantially changing it

Guys, I will not vent my feeling in the regard of this updates. I'm sure, you are proud of yourself with new design efforts. The only fact I would very much like to stress out is that recent updates are unreliable. It's a pity to learn that a hard way after long time being a very satisfied, loyal user who recommended your soft wholeheartedly.

**Comment by er-vin** [comment]
I understand your frustration. This is a bit of four tickets in one here though. Let me address the points separately:
 - (First): This one is still under investigation (but as you mentioned this is a duplicate from another issue ticket)
 - (Second) and (Third): There's a non trivial fix which will be integrated in 3.1 to address both (PR #2527)
 - (Fourth): This is not something we plan to change for the time being, there will be further iterations to improve that window of course and other facilities around like mentioned above (also has been discussed in other tickets)

Things being mentioned in this ticket being either addressed already and/or tracked in other existing tickets, I'll close this one.
