### ISSUE TITLE
Unable to start Nextcloud with SSH remote connection on batch mode

### ISSUE THREAD

**Issue by ferdymercury** [nextcloud/desktop#2548]
### Actual behaviour
When I execute Nextcloud-3.0.1-x86_64.AppImage on a remote machine that I connect to via ssh, it does not work if I am not using ssh -X. If use the -X flag, it asks for the password every time, it takes a very long time to start it, and finally it 'closes' if the ssh terminal is closed.

When I connect physically to the machine and login, Nextcloud always starts automatically. (launch on startup is running).

### Expected behaviour
It would be quite helpful to have a command-line version that does not require ssh -X. That would allow running things in batch mode and making the workflow much faster. This command could be executed in a Linux 'screen' that keeps running in the background even if you close the ssh connection later on.

When I used dropbox before, this could be easily achieved doing in the terminal:
```
screen
dropbox start
CTRL+A, D
```

### Steps to reproduce
1. Try to start Nextcloud AppImage on a remote machine via SSH
2. It asks for password and opens web browser
3. It stops if ssh connection is broken

### Client configuration
Client version: Nextcloud-3.0.1-x86_64.AppImage
Operating system: Ubuntu 18.04

OS language: Linux

Qt version used by client package (Linux only, see also Settings dialog): As in the appimage Ubuntu 3.0.1

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: /opt/

**Comment by er-vin** [comment]
Wouldn't it be what nextcloudcmd is for? We don't provide it as appimage though.

**Comment by ferdymercury** [comment]
Yes, that would probably solve it, and providing it as appImage would be great. Thanks!

**Comment by er-vin** [comment]
Well, there's no plan for that unfortunately. But there are debian packages for Ubuntu 18.04 AFAIK.

Closing this one then, the "cmd in appimage" demand is already in another ticket IIRC.
