### ISSUE TITLE
Further account connection flow improvement

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2554]
One of the main confusing things is this step when connecting to a server:
![](https://user-images.githubusercontent.com/1411800/95481762-a51b4a80-098d-11eb-84f9-5b16542f359e.png)

The "Sign up with a provider" and "Host your own server" buttons/links should not be visible in this step anymore. They only belong in the very first screen where one chooses.

In this second step, instead there should be a "Back" button on the bottom left. And the "Next" button ideally should be called "Log in" because that’s what will happen next.

cc @er-vin @nicolasfella @misch7 as a follow-up to https://github.com/nextcloud/desktop/pull/2534

**Comment by er-vin** [comment]
Superseded by #2720
