### ISSUE TITLE
MB reported as GB on the spanish translation

### ISSUE THREAD

**Issue by dara0s** [nextcloud/desktop#2557]
SPANISH TRANSLATION
On the main window of the client, when files are syncing, the speed and the progress is shown in GB/s and GB instead of MB/s and MB.

Images showing this behavior:

![Captura de pantalla 2020-10-15 160310](https://user-images.githubusercontent.com/52132330/96175033-a7872280-0f00-11eb-8ade-9362f0480404.png)
![Captura de pantalla 2020-10-15 160236](https://user-images.githubusercontent.com/52132330/96175035-a81fb900-0f00-11eb-9cdd-e3fd4829f78c.png)

**Comment by kesselb** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
Hmmh, seen such client issues in the past. Not 💯 sure if this is related to translation. Will check tomorrow.

**Comment by rakekniven** [comment]
As already thought yesterday I cannot find any wrong translated strings.

See https://www.transifex.com/nextcloud/search/?q=target_language%3Aes+project%3Anextcloud+source_text%3A%22MB%22

@camilasan Can you please check. We had such reports in the past.

**Comment by rakekniven** [comment]
Hello @dara0s,

there multiple spanish based translations available.
Which locale are you using? es_CO?

**Comment by dara0s** [comment]
@rakekniven 
This is what I got from the log:

2020-10-16 10:28:20:981 [ info nextcloud.gui.application ]:	"################## Nextcloud locale:[es_CL] ui_lang:[es_MX] version:[3.0.2stable-Win64 (build 20200924)] os:[Windows 10 (10.0)]"

(On my linux machine, locale:[en_US], ui_lang:[], ver:[2.6.2-1build1], the MB is shown OK)

**Comment by rakekniven** [comment]
Found it!
