### ISSUE TITLE
3.X UI event list actions (or lack of thereof)

### ISSUE THREAD

**Issue by the-vindicar** [nextcloud/desktop#2560]
### UI element in question
Event list that appears in main popup window.

### Expected behaviour
On click, system file explorer should open, focused on file/folder in question.
On right-click, context menu should be provided with the following options:
* "Open containing folder" - see above
* "Open on server" - opens browser with the URL corresponding to that specific file.
* "Resync now" - pushes this file to the start of sync queue, attempt to sync immediately.
Optionally, on double click, file/folder in question should be opened using associated program.

Scenarios in which these changes will be useful:
1. In case of successful sync, user might've been waiting for this specific file to download, and intends to use it immediately.
2. In case of a sync conflict, user will likely want to manually compare both files to resolve the conflict
3. In case of syncing error, user might want to transfer the file manually, or attempt sync again once internet connection is fixed.

In all cases, being able to immediately see the file in question within its folder would improve the workflow.

### Actual behaviour
On click, base URL of the associated Nextcloud server is opened, without focusing on associated file or folder.

### Steps to reproduce
1. Left-click on the tray icon.
2. Left-click on one of the events in the event list.

### Client configuration
Client version: 3.0.2

Operating system: Windows 10 ver 1607 Build 14393.3986

OS language: Russian

Installation path of client: C:\Program Files (x86)\Nextcloud

**Comment by er-vin** [comment]
@jancborchardt any opinion?

**Comment by jancborchardt** [comment]
> On click, system file explorer should open, focused on file/folder in question.

Right now on click the file itself opens, which is the expected action. Merely opening the file manager would be an annoying extra step.

> On right-click, context menu should be provided with the following options

All these options are quite technical and introduce additional complexity. All of that would have to be tested as well. Not sure about the value of adding those – do you have an example of e.g. Google Drive or Dropbox providing these actions?

**Comment by the-vindicar** [comment]
Odd, for me a single left click on event list of 3.0.2 client opened the web-browser, not the file in question.
