### ISSUE TITLE
Resolve Conflicted Copies from Desktop app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2563]
Related to #1928 

We really need the ability to resolve conflicted copies directly from the Desktop (and mobile) app.  Right now the user receives notifications, but no clear way to resolve these conflicts.  This would be a really helpful step for users!

Thank you for considering.

NextcloudPi 20.0.0 with Desktop app 3.0.2

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/desktop/issues/1195
