### ISSUE TITLE
Client login failed

### ISSUE THREAD

**Issue by misu99** [nextcloud/desktop#2565]
client:
![图片](https://user-images.githubusercontent.com/17765320/96392623-4062ba00-11ef-11eb-873b-a6ec44df6834.png)

server:
nextcloud    | 172.19.0.3 - - [19/Oct/2020:09:41:38 +0800] "POST /login/v2/poll HTTP/1.1" 400 0 "-" "Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)"

environment:
Run in docker, and use caddy to reverse proxy.
I tested not using caddy, that's no problem. so, how should I configure caddy ?

**Comment by er-vin** [comment]
Sorry but this is the repository about the desktop client. We don't have experience with caddy so can't really help. This question would be better addressed on help.nextcloud.com I think.
