### ISSUE TITLE
The new version 3.0.1 / 3.0.2 does not start on the desktop version of windows 10

### ISSUE THREAD

**Issue by GabrielMoldovanGiovanni** [nextcloud/desktop#2574]
The new version 3.0.1 / 3.0.2 does not start on the desktop version of windows 10

it is not minimally displayed in the system activity management

what should be done?

**Comment by er-vin** [comment]
I wonder if that's one of those faulty GPU driver cases. Could you please check if it's crashing on start? And if that's the case and somewhere in ntdll.dll then you should probably think about upgrading your GPU drivers.

We had reports from people using nvidia and intel drivers recently and upgrading fixed it for them.

**Comment by GabrielMoldovanGiovanni** [comment]
o updated the whole pc even with another techinic of the cup gpu of the motherboard but it should not be or also tried to remove the folders of the Roming and Local section and restore the program but it should not be non-soil because but on laptops it goes smoothly

**Comment by er-vin** [comment]
Could we please get more information about the crash then? (I assume it is one, I might be wrong of course)

**Comment by GabrielMoldovanGiovanni** [comment]
In total, 21 PCs are wrong and they are all desktops
