### ISSUE TITLE
Taskbar logo not showing sometimes

### ISSUE THREAD

**Issue by David-Lor** [nextcloud/desktop#259]
Under Ubuntu & Unity, randomly, the Nextcloud logo at the top taskbar is not showing properly:

![image](https://user-images.githubusercontent.com/17401854/39087011-221c1100-459a-11e8-9114-3cf2aa1e8eb5.png)
(Nextcloud logo should be the first one with the cross)

OS: Ubuntu Mate 16.04 LTS w/ Unity
Nextcloud 2.3.3

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

**Comment by camilasan** [comment]
if you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
