### ISSUE TITLE
Install on Pop!_OS 20.10 - Depends: libnextcloudsync0 (= 2.6.4-1) but 3.0.2-20200924.150911.068ad89d8-1.0~focal1 is to be installed

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/desktop#2590]
### Expected behaviour
When apt installing the nextcloud client, the package installs properly. a dependency version error occurs which prevents the install.

### Actual behaviour
When apt installing the nextcloud client, a dependency version error occurs which prevents the install.

The following packages have unmet dependencies:
nextcloud-desktop : Depends: libnextcloudsync0 (= 2.6.4-1) but 3.0.2-20200924.150911.068ad89d8-1.0~focal1 is to be installed
E: Unable to correct problems, you have held broken packages.

### Steps to reproduce
1. Perform `sudo apt install nextcloud-desktop`
2. Verify the error occurs

![image](https://user-images.githubusercontent.com/9272078/97093702-93ed6180-164e-11eb-960d-c5c82b4ad065.png)

### Client configuration
Nextcloud Desktop 3.0.2

Operating system: Pop!_OS 20.10

OS language: English

### What I've tried
sudo apt-get update --fix-missing
sudo apt-get install -f

**Comment by ivaradi** [comment]
The version 3.0.2-20200924.150911.068ad89d8-1.0~focal1 looks like it comes from the Ubuntu PPA. Is the PPA configured? Though if so, it should take nextcloud-desktop from there as well... 

Could you issue the command 

apt-cache show nextcloud-desktop

?

**Comment by armaccloud** [comment]
For sure, here it is

Package: nextcloud-desktop
Architecture: amd64
Version: 2.6.4-1
Priority: optional
Section: universe/net
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: ownCloud for Debian maintainers <pkg-owncloud-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3271
Depends: libnextcloudsync0 (= 2.6.4-1), libqt5sql5-sqlite, nextcloud-desktop-common, nextcloud-desktop-l10n, libc6 (>= 2.14), libcloudproviders0 (>= 0.2.5), libgcc-s1 (>= 3.0), libglib2.0-0 (>= 2.37.0), libqt5core5a (>= 5.12.2), libqt5dbus5 (>= 5.6~), libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1), libqt5keychain1 (>= 0.7.0), libqt5network5 (>= 5.6~), libqt5webenginecore5 (>= 5.7.1), libqt5webenginewidgets5 (>= 5.7.1), libqt5webkit5 (>= 5.212.0~alpha3), libqt5widgets5 (>= 5.11.0~rc1), libqt5xml5 (>= 5.6~), libstdc++6 (>= 5.2)
Recommends: nextcloud-desktop-doc
Filename: pool/universe/n/nextcloud-desktop/nextcloud-desktop_2.6.4-1_amd64.deb
Size: 1267028
MD5sum: f2029178961c35a7df505aceff00f43d
SHA1: bbbf10162c69abfbdc992f062306d154e54ae711
SHA256: c657a60c8f407b9689a6a1dab5addc9573f2523d32e5615694a83511eb46b6af
SHA512: 2695ee602c756a5741f15024a1e5de8fde1c2732ad435d140c781446e604abb114e19a18277b3eae135246d35ee4eb6dbbacdcd3cdde4546e67b747fdaf85118
Homepage: https://nextcloud.com/install/#install-clients
Description-en: Nextcloud folder synchronization tool
 The Nextcloud desktop app lets you always have your latest files wherever
 you are. Just specify one or more folders on the local machine to and a server
 to synchronize to. You can configure more computers to synchronize to the same
 server and any change to the files on one computer will silently and reliably
 flow across to every other.
 .
 nextcloud-desktop provides the graphical client specialising in
 synchronizing with cloud storage provided by Nextcloud.
Description-md5: a2bf7c3db498a3e87f05105e73c38541

**Comment by ivaradi** [comment]
Do you have the Ubuntu PPA configured?

**Comment by armaccloud** [comment]
Yes, I think that should be this one. Is that not correct?

![image](https://user-images.githubusercontent.com/9272078/97108298-e79e9000-16cc-11eb-830e-69c8192dbe7a.png)

**Comment by ivaradi** [comment]
It is strange then, because apt-cache show...  should then display version 3.0.2-20200924.150911.068ad89d8-1.0~focal1 of the nextcloud-desktop package as well, not just 2.6.4...

Anyway, could you try installing nextcloud-desktop with specifying the version explicitly, like:

sudo apt-get install nextcloud-desktop=3.0.2-20200924.150911.068ad89d8-1.0~focal1

**Comment by armaccloud** [comment]
Hmm, it doesn't find the package this way.

![image](https://user-images.githubusercontent.com/9272078/97109367-29323980-16d3-11eb-9191-91794ad1fa03.png)

**Comment by ivaradi** [comment]
It is really strange that your system sees the PPA version of the library, but not the nextcloud-desktop package itself. Maybe you could try removing the PPA from your configuration, do an apt-get update, and then add the PPA again.

**Comment by armaccloud** [comment]
That did the trick, thank you @ivaradi!
