### ISSUE TITLE
File exclusion per directory

### ISSUE THREAD

**Issue by DBLouis** [nextcloud/desktop#26]
I would like to be able to exclude files to be sync by directory. I know it can be done globally but a per directory exclusion list (like a .gitignore) would be great.

The context is that I am using cmake and I would like to exclude build files but keep sources being synced.

**Comment by qw3ry** [comment]
I would really like this, mostly because I wouldn't have to manage separate exlusion lists on every client I use

**Comment by Temtaime** [comment]
Try to create .sync-exclude.lst in any directory and then after the sync remove this file.
Client will state "Could not read system exclude file" and will never sync again. Client restart helps.

**Comment by camilasan** [comment]
> @mgallien @camilasan Do we not provide this feature already with `.sync-exclude.lst` files? They can be created for sub directories as well.

We do have this feature including bug fixes.
