### ISSUE TITLE
Linux PPA really outdated

### ISSUE THREAD

**Issue by NdK73** [nextcloud/desktop#2604]
### Expected behaviour
"sudo apt update && sudo apt full-upgrade" should upgrade nextcloud-client to the latest stable (3.0.2, at least according to appimage file).

### Actual behaviour
client 2.6.5 remains installed

Operating system:
Ubuntu 18.04LTS

OS language:
It

Qt version used by client package (Linux only, see also Settings dialog):
N/A

Client package (From Nextcloud or distro) (Linux only):
2.6.5/3.0.2

Installation path of client:
2.6.5: /usr/bin
3.0.2: ~/bin

### Server configuration
N/A (E2E encryption seems to work on 3.0.2 and the old client worked OK for the last year).

### Logs
N/A: packaging issue. Updated files are not present in PPA repo.

PS: since updates stopped mid-pandemic-outbreak, I hope the maintainer is OK!

**Comment by er-vin** [comment]
@ivaradi ? I seem to remember we had to drop support for 18.04 due to dependencies right?

**Comment by NdK73** [comment]
> @ivaradi ? I seem to remember we had to drop support for 18.04 due to dependencies right?

The ppa only refers to Xenial (16.04LTS) as best-effort because of dependencies.
The most recent version in "stable" is 2.6.4 for disco (19.04, non LTS). In "alpha" it's up to 2.7.0 for various releases. But files are dated 2020-05-01. That's why I hope @ivaradi is well!

**Comment by er-vin** [comment]
I remember messages from him more recently than this. So I'm not too worried (yet).

**Comment by ivaradi** [comment]
I'm fine, thanks :)

Indeed, support had to be dropped for 18.04 because it conains  Qt 5.9, which is too old a version for the client that requires 5.12. I have updated the description of PPA accordingly.

**Comment by er-vin** [comment]
OK, let me close it then.
