### ISSUE TITLE
v3.0.3 : Microsoft Defender shows warning after launching install

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#2605]
### Expected behaviour
Installer should run without errors and warnings

### Actual behaviour
Started installer and immediately got this warning:

![2020-10-30_15h02_56](https://user-images.githubusercontent.com/2069590/97714873-fcf72e00-1ac1-11eb-86b4-d823bed279b0.png)

### Steps to reproduce
1. Download installer from https://nextcloud.com/install/#install-clients (https://github.com/nextcloud/desktop/releases/download/v3.0.3/Nextcloud-3.0.3-setup.exe)
2. Launch installer 
3.

### Client configuration
Client version: 3.0.3

Operating system: Windows 10 Enterprise

OS language: german

Installation path of client: C:\Program Files\Nextcloud

**Comment by rakekniven** [comment]
After click at "more information" I got this:

![2020-10-30_15h03_05](https://user-images.githubusercontent.com/2069590/97715393-9d4d5280-1ac2-11eb-92cb-bcc34e617132.png)

Pressed "Continue anyway" (Trotzdem ausführen) and installer started.

But it hanged.
So I uninstalled old v3.0.2 version and started installation again and it worked.

**Comment by tonyskilton** [comment]
I m seeing the same behaviour as rakekniven.
Defender is flagging the installer for version 3.0.3 as potentially harmful.
AVG is also flagging the file as harmful, triggering a CyberCapture scan.
(Sending the file to their servers for deeper analysis)

After clicking through all the AV dialogs and proceeding with the installation, It hangs almost immediately with the error shown on the attached image.

![Screenshot 2020-10-30 123844](https://user-images.githubusercontent.com/21333776/97731910-a7c11980-1acd-11eb-99fd-3256dfed2b9a.png)

I downloaded the x64.msi from github, the file prompted the same harmful file dialogs, but installation proceeded successfully.

**Comment by rainerzufall** [comment]
same for me. Any more information we can add, that would be helpful?

**Comment by er-vin** [comment]
So that's really two issues here: the upgrade itself failing on that file it can't write in and defender flagging the installer. We got another separate ticket for the failing upgrade so I'll ignore this here and deal only with defender.

So we had to change the key we were using to sign the binaries (simply the old keys were getting expired really soon now). But the new keys are not in the defender whitelist yet. We've been told this should happen when we reach some critical mass of installs (of course we're not in control of that threshold).

That's why I'm just closing it, we can't do much about it and it's supposed to clear itself after enough installs are done.

**Comment by rakekniven** [comment]
> We've been told this should happen when we reach some critical mass of installs

Wow, very transparent logic from MS.

**Comment by rakekniven** [comment]
> We got another separate ticket for the failing upgrade

@er-vin Is this #2606 ?

**Comment by er-vin** [comment]
Yes, that'd be the one.

**Comment by sunchezz89** [comment]
I have similar issues with upgrading.
When i choose to uninstall previous version, i get the error with `install script already running` which has been mentioned before.

If i choose "add components", the installer starts the process until approx. 25%. Then showing the error `could not overwrite ../shellext/NCContextMenu.dll`. No way to finish the installation properly.
I repeated the same process after shutting down NC-Client with the same result.

Info: 
Explorer.exe has not been opened in the PC-Sesssion to this point.
Manually deleting the file shows the same effect, win10 says it's still in use by the explorer.

**Comment by xames81** [comment]
What then??? no resolving?

**Comment by michauk** [comment]
> 
> 
> What then??? no resolving?

Hi, I got this issue this morning too.
Killing nextcloud.exe before upgrading just makes you go a bit further then stops for NCContextMenu.dll file.
Solution as mentionned in @rakekniven 's previous message : uninstall first (or uninstall now if half installed). Install then. You won't loose any config nor sync'ed files.
Regards,
