### ISSUE TITLE
Update routine issue started with 3.0.2 (present in 3.0.3 as well)

### ISSUE THREAD

**Issue by DrCarsonBeckett** [nextcloud/desktop#2606]
### Expected behaviour
I wanted to install 3.0.3 client and ran it like everytime. Just started the 3.0.3 installer and it should offer to remove the previous function and actually uninstall the previous version before installing the latest one.

### Actual behaviour
A message pops up that "The uninstaller is already running." (original message from my german installation: "Das Deinstallationsprogramm wird bereits ausgeführt.").

### Steps to reproduce
1. Install 3.0.2 .
2. Try to install 3.0.3 with selecting to remove the previous installation.
3. See the message. That never happened before version 3.0.1

### Client configuration
Client version:
3.0.3 (now, previous version was 3.0.2).

Operating system:
Windows 10 Pro x64

OS language:
German

Installation path of client:
Original one: "C:\Program Files\Nextcloud\"

I could narrow it down to 3.0.2 client release. With that version that behaviour started. I can install 3.0.3 if I manually remove 3.0.2 first. When I want to install 3.0.2 over 3.0.3 then the same issue appears. If I use the 3.0.1 installer, then the uninstallation works as intended. So that bug was introduced with 3.0.2 .

**Comment by Id3aFly** [comment]
Had the same problem; with the identical client configuration as @DrCarsonBeckett .
Workaround was to deinstall the 3.0.2 version manually first. Luckily all my settings were kept, so it was no effort at all!

**Comment by devdracon** [comment]
...the same behaviour with me with the same environment.

**Comment by cyril23** [comment]
same here, it's super annoying that you have to go to Control Panel to uninstall the old version instead of using the new installer

**Comment by pstimpel** [comment]
Just to make it clear: uninstalling the 3.0.2, rebooting the machine, and then run the install did solve the "uninstaller already running", but still causes lots of trouble since some QT files are still blocked by the system.

**Comment by devdracon** [comment]
> Just to make it clear: uninstalling the 3.0.2, rebooting the machine, and then run the install did solve the "uninstaller already running", but still causes lots of trouble since some QT files are still blocked by the system.

you can get rid of this by removing the 3.0.2 as described, the reboot in protected mode, delete the nextcloud folder, reboot & install the new version.

annoying - but as camilsan stated, they're working on this problem

**Comment by pstimpel** [comment]
"annoying"? No, wrong word.  Glad they are working on a fix already.

**Comment by devdracon** [comment]
> "annoying"? No, wrong word. Glad they are working on a fix already.

...this was related to the cumbersome update routine  ;)
