### ISSUE TITLE
Nextcloud Pop-Up Window partly hidden under Windows taskbar

### ISSUE THREAD

**Issue by matzl** [nextcloud/desktop#2607]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

When clicking the icon in the Windows taskbar, the Nextcloud Window shall apear above or outisde the area of the taskbar.

### Actual behaviour
The Nextcloud Window/Overlay opens, but it hides partly under my taskbar.
![image](https://user-images.githubusercontent.com/9556620/97754903-980afa80-1af8-11eb-980c-7094e558eb68.png)

### Steps to reproduce
1. Move Windows taskbar to top of the screen
2. Click on Nextcloud icon
3. Nextcloud window hides under taskbar

### Client configuration
Client version: 3.0.2

Operating system: Windows 7 Home Premium SP1 64 bit

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud\nextcloud.exe

**Comment by er-vin** [comment]
We had a fix committed for Windows 7 a few days ago. It missed the boat for 3.0.3 though, if you feel like trying with one of the dailies and letting us know how it goes. Otherwise test again with 3.1.0 end of November. The issue should hopefully gone.

**Comment by splitt3r** [comment]
Btw. this looks quite like Windows 7 which is not supported anymore. Have a look at https://docs.nextcloud.com/desktop/3.0/installing.html#system-requirements.
