### ISSUE TITLE
Offer alternate login / OAuth method (like mobile apps)

### ISSUE THREAD

**Issue by Flore-mozfr** [nextcloud/desktop#261]
Hello,

I have a small nextcloud 13 instance (around 30 users) and I just recently installed [Social login](https://apps.nextcloud.com/apps/sociallogin) to offer the users an alternative login solution. It works and the issues I might have with it are reported on their github.

My only problem is with the nextcloud client app (on desktop) where there are no alternative to the classic login / password. The mobile apps are offering this alternative by displaying the login screen.

Usecase:

1. User A creates an account on nextcloud using social login
2. User A logs in Nextcloud on the browser using their google account (thanks to social login)
3. User A logs in on mobile app using their google account
4. User A installs the desktop app to sync their files on their computer
5. The desktop app asks for login/password but does not offer social login (unlike mobile apps): FAIL

I also [created the issue on social login github](https://github.com/zorn-v/nextcloud-social-login/issues/5), but it's certainly better here.

**Comment by rullzer** [comment]
Fixed in #75
