### ISSUE TITLE
Unresolved conflicts

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/desktop#2611]
Hello,

since Version 3.0.2 i have a message that contains "you have unresolved conflicts, press for details" but when i clickt on the text, nothing happend. I can nowhere see, where is the conflict!

Windows 10 1909
Nextcloud 20.0.1
Nextcloud Desktop APP 3.0.3

**Comment by er-vin** [comment]
Closing it, this is a duplicate of #1195 it got fixed with #2527 to be delivered with 3.1.0
