### ISSUE TITLE
Nextcloud Client 3.0.3 Nextcloud undefined status no sync

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/desktop#2612]
on 2 client installations v.3.0.3 I am getting synchronization problems with the status: Nextcloud undefined status and does not download or synchronize folders. I tried to delete folders in% appdata% and reinstall nextcloud from 0 but I have to go back to release 3.0.2 to get everything working again. nextcloud server instances are updated to latest release 20.0.0.1

**Comment by tigernero79** [comment]
in practice it always gives me 2 folders to synchronize and never synchronizes them and remains in an "undefined state" I attach screenshots

![Immagine](https://user-images.githubusercontent.com/35575744/98025342-d6126200-1e09-11eb-82b6-985b1f6fa0f8.png)

**Comment by kruthoff** [comment]
Please check if it works if you _disable_ end-2-end encryption on the server.

I'm experiencing the same issue. Sync does not work if E2E is enabled. My client runs into timeouts, the connection breaks (red warning in client), and the client doesn't recover and looks like in your screenshot.

Another check would be to see if your problem is related to #2593

**Comment by er-vin** [comment]
As @kruthoff says, this would be useful if you could check a bit further which case you're in. It looks a lot like a duplicate.

**Comment by kruthoff** [comment]
[nx-client-3.0.3.log](https://github.com/nextcloud/desktop/files/5486894/nx-client-3.0.3.log)

I'm adding my client log, maybe it helps to analyze further. (Not sure where to put it, as there are at least 2 tickets with sync problems already?)

A lot of checks seem to work fine, until timeout problems arise. Can I do something to avoid these? They don't appear if E2E is disabled, even if I sync large amounts of data.

**Comment by er-vin** [comment]
@kruthoff this is clear your case is #2593 

Now wondering if that's the case for @tigernero79 as well or if he's in a different case.

**Comment by tigernero79** [comment]
today I try to put back the 3.0.3 disabling e2e and I try, with v3.0.2 all is fine

**Comment by tigernero79** [comment]
@er-vin  @kruthoff 

I confirm that by deactivating the pugin end to end nextloud version 3.0.3 the synchronization has resumed. so something blocks the synchronization with the end to end module

**Comment by jktoiuhito** [comment]
As you seem to have access to the server, [please see my comment on how I (temporarily) resolved the issue](https://github.com/nextcloud/desktop/issues/2593#issuecomment-721565119) and see if it helps.

**Comment by tigernero79** [comment]
@jktoiuhito very good The procedure you indicated to eliminate the e2e blocks works.

tested.

**Comment by andreasschmitz** [comment]
Does anyone have an update on this? Is this resolved? I haven't tried E2EE out since I ran into this bug last year.

**Comment by carlfriedrich** [comment]
This issue is probably fixed with upcoming client 3.2. I tried with 3.2.0rc3 on Windows:

- enabled e2e on server
- add new folder on android device
- set as encrypted
- add file to folder
- encrypted in NC web ui
- syncs correctly to win client
- add file to folder from win client
- syncs correctly to android app

**Comment by mr-manuel** [comment]
Hello, can you please reopen this issue? I have the same problem with client version 3.4.1 on Windows. The clients stops syncing after some time. After I close and reopen the EXE it works again for some hours.
Which logs do you need?

**Comment by bmhj2** [comment]
> Hello, can you please reopen this issue? I have the same problem with client version 3.4.1 on Windows. The clients stops syncing after some time. After I close and reopen the EXE it works again for some hours. Which logs do you need?

+1 from me. Same client version, same issue.

**Comment by mr-manuel** [comment]
Could you please reopen this issue?

**Comment by alex-dacosta** [comment]
same issue here
and not related at all to E2E encryption

**Comment by dbdonb** [comment]
Same issue here please.

**Comment by dbdonb** [comment]
> > Same issue here please.
> 
> is it with VFS system enabled?

Yes. I'm on windows 10. Here's the last log
https://i.imgur.com/16XAtcW.png
