### ISSUE TITLE
NC Client 3.0.3 frequently stuck with 100% CPU usage on MAC

### ISSUE THREAD

**Issue by solick** [nextcloud/desktop#2614]
Since updating to 3.0.3 on MacOS Catalina I face the problem of stuck client (seeing wheel of death) and CPU Usage at 100%.

From the log files I am not sure but maybe the sync has been finished but still the client continue to work on something.

Restarting cause a long time 100% usage and after > 15 minutes the client continue to sync.

Testest in on 1 iMAC.

**Comment by er-vin** [comment]
I think we'd need debug logs and eventually some more information about where the consumption is (I don't know if for instance on mac there's a way to know which threads are consuming).

**Comment by solick** [comment]
please find enclosed an analysis of the current process with 100% cpu consuming. 
[201105-nextcloud-analysis.txt](https://github.com/nextcloud/desktop/files/5497555/201105-nextcloud-analysis.txt)

**Comment by solick** [comment]
just an update: currently 100% CPU usage, not responding in activity:

Physical Memory: 1,31 GB
Virtual Memory: 10,11 GB
12 ports
472979 errors

This was a clean installation on a new iMAC this week.

**Comment by mspeculatrix** [comment]
I'm having exactly the same problem. Updated from 3.0.2 to 3.0.3 on a MacBook Pro. Syncing works fine for a while - maybe 15 mins - then hangs with 100% CPU usage. I have to use Activity Monitor to kill the process. I tried removing the Folder Sync Connection and starting from scratch, but same thing happens.

3.0.2 is working fine on my Win10 machine, an iMac and two Linux boxes.

Where do I find debug information on the Mac? I'm running Mojave.

Also, I've looked in vain for a version of 3.0.2 so I can roll back to that. Any pointers where I can find it?

**Comment by er-vin** [comment]
> please find enclosed an analysis of the current process with 100% cpu consuming.
> [201105-nextcloud-analysis.txt](https://github.com/nextcloud/desktop/files/5497555/201105-nextcloud-analysis.txt)

Didn't spot anything obvious there (or I can't read that file properly), I'm still wondering where it's spending the time.

Could we have client debug logs as well?
