### ISSUE TITLE
Client deletes also files ignored by sync when removing local folder

### ISSUE THREAD

**Issue by peeter-t2** [nextcloud/desktop#2617]
There are some files that the nextcloud sync can be set to ignore. E.g. I ignore .git folders since nextcloud can't really handle them well. 

When removing the files temporarily locally - connected to this issue https://github.com/nextcloud/desktop/issues/260#issuecomment-723573114 - nextcloud also deletes the files that it has never synced. So they will be/are now gone forever. :)

Perhaps this could be fixed. At least ask what to do with files on the ignore list?

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
