### ISSUE TITLE
Sync deletes files it shouldn't delete during resync

### ISSUE THREAD

**Issue by kelvinhammond** [nextcloud/desktop#2618]
### Expected behaviour
Nextcloud should sync files and not arbitrarily delete and/or resync files locally and remotely.

### Actual behaviour
During issue: https://github.com/nextcloud/desktop/issues/1433 nextcloud was resyncing, yet again, and deleted a folder it was supposed to keep. I'm not sure of the scenario that caused it to happen, maybe I rebooted during its resync, either way it deleted my keepass folder which I've recovered from the trashbin manually.

I will note that during https://github.com/nextcloud/desktop/issues/1433 nextcloud-client deletes the files from the remote server and reuploads them. This is rather wasteful because its 130GB+ being uploaded each time.

### Steps to reproduce
Not sure how to do this, see https://github.com/nextcloud/desktop/issues/1433

### Client configuration
Client version: 3.0.3-1

Operating system:
ArchLinux

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
Not shown

Client package (From Nextcloud or distro) (Linux only):
Distro

Installation path of client:
```
nextcloud-client /etc/
nextcloud-client /etc/Nextcloud/
nextcloud-client /etc/Nextcloud/sync-exclude.lst
nextcloud-client /usr/
nextcloud-client /usr/bin/
nextcloud-client /usr/bin/nextcloud
nextcloud-client /usr/bin/nextcloudcmd
nextcloud-client /usr/include/
nextcloud-client /usr/include/nextcloudsync/
nextcloud-client /usr/include/nextcloudsync/creds/
nextcloud-client /usr/include/nextcloudsync/creds/abstractcredentials.h
nextcloud-client /usr/include/nextcloudsync/creds/httpcredentials.h
nextcloud-client /usr/include/nextcloudsync/mirall/
nextcloud-client /usr/include/nextcloudsync/mirall/account.h
nextcloud-client /usr/include/nextcloudsync/mirall/configfile.h
nextcloud-client /usr/include/nextcloudsync/mirall/networkjobs.h
...
```

### Server configuration
Nextcloud version: nextcloud:19.0.3-apache

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
I've notices the issue too late, no longer in the logs. Why does nextcloud only keep about 3 days of logs?

**Comment by kelvinhammond** [comment]
This issue may be related to https://github.com/nextcloud/desktop/issues/2617 also which is rather annoying. Somehow my Apps folder was deleted by the sync client even though this is excluded.

**Comment by jarbus** [comment]
This just happened to me. I had my .config directory synced to Nextcloud, and it instead deleted it on my machine and remotely.

**Comment by er-vin** [comment]
Yes, this looks like a combination of #1433 and #2617 so I'll just close this one as a duplicate.
