### ISSUE TITLE
Mac OS: "Add account" opens new account wizard only if the settings dialog is already open.

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#2623]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Click on "Add account" opens new account wizard.

### Actual behaviour
"Add account" opens new account wizard _ONLY_ if the settings dialog is already open.

### Steps to reproduce
1. Close settings dialog
2. Click on "Add account" in the systray menu
3. New account wizard doesn't show up

### Client configuration
Client version:

Operating system: Mac OS Catalina

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.12.9 compiled with OpenSSL

Client package (From Nextcloud or distro) (Linux only): compiled from master

### Server configuration
Not relevant in this case.

### Logs
I don't think it will help either.

**Comment by CoreTechnologyAG** [comment]
Same behaviour on windows 10 desktop and linux ubuntu 20.04

**Comment by er-vin** [comment]
This is fixed in 3.1.1.
