### ISSUE TITLE
Nextcloud Desktop client continually notifies the same app update

### ISSUE THREAD

**Issue by rca** [nextcloud/desktop#2624]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I am running Nextcloud Desktop v 3.0.3 on a Mac.  When there is an update for a server component (Collabora Online, in this case), notifications will continually come in.  I expect to get one notification per released version.

### Actual behaviour
Notifications continually come in, approximately once an hour

![Screen Shot 2020-11-11 at 7 58 08 AM](https://user-images.githubusercontent.com/53537/98814952-6e08e080-23f4-11eb-9980-bcb94b1773c0.png)

For the time being I have disabled server notifications in the client settings.

### Steps to reproduce
1.  Run a local nextcloud server
2.  Install and run Nextcloud Desktop on a Mac
3. When there is an update, expect a notification once an hour

### Client configuration
Client version: 3.0.3

Operating system: Mac

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): N/A

Installation path of client: Wherever the Mac installer puts it ... ?

### Server configuration
Nextcloud version:20.0.1

Storage backend (external storage): This is running in the lsio docker container

**Comment by allexzander** [comment]
@rca
Is the desktop app running continuously for a couple of hours? Or does it get restarted between repeating notifications you've mentioned?

**Comment by wrickout** [comment]
I have issue like you but i get like this "ncadmin added you to group..." and more. I got it every windows start.
