### ISSUE TITLE
CSync-Access failed

### ISSUE THREAD

**Issue by pointhi** [nextcloud/desktop#263]
Sometimes when I copy a directory and delete stuff inside it before nextcloud is able to sync, I get the error: ```CSync-Access failed path/to/deleted/directory```. And it is not able to recover by itself and I need to delete the directories which were already added to the server.

I think I get similar problems when build files are synchronized which are deleted shortly afterward.

**Comment by camilasan** [comment]
@pointhi Could you give more details on how to reproduce it - step by step? You copied this directory from where? Was a directory being synced? Thanks for the report.

**Comment by pointhi** [comment]
I had this problem again. Seems like it's a server problem because the web interfaces shows a file, but the file actually does not exist on harddisk ```data/user/files/...```. Doing ```occ files:scan --all``` also does not fix the issue.
```
Sabre\DAV\Exception\NotFound: File with name /path/to/file/file.md could not be located

    /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 76: OCA\DAV\Connector\Sabre\Directory->getChild('Short_Acitivity...')
    /var/www/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 81: Sabre\DAV\Tree->getNodeForPath('files/user/p...')
    [internal function] Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
    /var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/cloud/apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
    /var/www/cloud/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
    /var/www/cloud/remote.php - line 164: require_once('/var/www/cloud....')
    {main}
```

**Comment by camilasan** [comment]
Did you look for similar errors at nextcloud/server or at the forums help.nextcloud.com?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
