### ISSUE TITLE
Static washed out display on Linux Desktop client

### ISSUE THREAD

**Issue by smac89** [nextcloud/desktop#2631]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The desktop client shows a readable looking display

### Actual behaviour
The client looks washed out and unreadable

### Steps to reproduce
1. Not sure. It only happens after either sleep or a few hours of being on

### Client configuration
Client version:
```
➜ nextcloudcmd --version
Nextcloud version 3.0.3git
Git revision 78da725ac38e1508e5800d02fd1700a4e43b1088
Using Qt 5.15.1, built against Qt 5.15.1
Using 'OpenSSL 1.1.1h  22 Sep 2020'
Running on Linux 5.9.6-arch1-1, x86_64
```

Installation path of client: `/usr/bin/nextcloud`

### Before sleep:
![ArcoLinux_2020-11-12_17-08-42](https://user-images.githubusercontent.com/8305511/99007620-7cfaaa80-253c-11eb-845a-2ccfe615fc39.png)

### After sleep:
![ArcoLinux_2020-11-12_17-11-21](https://user-images.githubusercontent.com/8305511/99007608-74a26f80-253c-11eb-9e68-1965e6ba36b0.png)

It actually gets worse than this, but this image is what I was able to reproduce after a simple sleep-wake cycle.

**Comment by er-vin** [comment]
This is unfortunately likely a driver issue. This window uses QtQuick which in turns uses OpenGL so there's likely some broken state when the machine is resumed from sleep, we got no chance to reach out that deep in the stack.

**Comment by smac89** [comment]
Indeed you're right. I followed the instructions [here](https://wiki.archlinux.org/index.php/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend), and I no longer experience this.
