### ISSUE TITLE
"Could not read system exclude file" on Windows 10

### ISSUE THREAD

**Issue by AstraQuinn** [nextcloud/desktop#2632]
Expected Behavior: The sync client does not lose the system exclude file, or has a fallback mechanism so the client can keep syncing if the exclude file is lost.

Actual behavior: About a week after an update to Nextcloud 3.0.3 a Windows 10 machine spontaneously can no longer access the system exclude file and therefore can no longer sync.

Steps to reproduce: User has no idea what they did to trigger this bug. They definitely aren't mucking around in the Nextcloud system folders, so at least we can rule out "user accidentally trashed it"

Logs: I am waiting for the user to forward the logs, but thought I would open a bug now.

I found that this issue has cropped up before, in [issues #172](https://github.com/nextcloud/desktop/issues/172) and before in the owncloud client at [issue #2683](https://github.com/owncloud/client/issues/2683)

Thank you for reading, I'm aware this isn't a great amount of information, if in addition to the client logs there's any additional info I can attach please let me know. Thanks for everything you all do!

**Comment by er-vin** [comment]
@camilasan you looked in that area not so long ago IIRC. Does that ring any bell to you?

**Comment by AstraQuinn** [comment]
Y'all, I'm having some issues stripping out identifying information from the log files. We're dealing with thousands of files and manually ctrl f'ing and replacing will take a lot longer than is reasonable. Do you all have any handy hints, tips, sed commands, whatever that can expedite this process? I am continuing to try and figure it out myself but I can't promise I will have time.

**Comment by AstraQuinn** [comment]
I can, however, report that every single computer in our network running Nextcloud 3.0.3 on either Windows or Mac developed this issue. The only ones that didn't were personal laptops running 3.0.2. Apologies for the delays in submitting the log files I am moving as fast as I can

**Comment by er-vin** [comment]
> Y'all, I'm having some issues stripping out identifying information from the log files. We're dealing with thousands of files and manually ctrl f'ing and replacing will take a lot longer than is reasonable. Do you all have any handy hints, tips, sed commands, whatever that can expedite this process? I am continuing to try and figure it out myself but I can't promise I will have time.\
> 
> EDIT quick question do you need the log files to consistently reference the same names? IE can I just strip filenames out or does it need to be replaced with some kind of hashed identifier?

Yes, it's a manual process and admittedly not something easy with production data. An alternative would be to provide us the file using a private file drop. I got one setup there: https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

If you use it, please make sure to give a name to the file which allows us to map back to your exact case.

**Comment by AstraQuinn** [comment]
Thanks! I uploaded the first client's logs and named it "ClientLogFromAstraQuinn" will upload more later.

**Comment by camilasan** [comment]
Hey, I am checking your logs @AstraQuinn, could be related to a PR I have been working #2590...

**Comment by er-vin** [comment]
> Hey, I am checking your logs @AstraQuinn, could be related to a PR I have been working #2590...

For the record I think you meant #2540

**Comment by camilasan** [comment]
> > Hey, I am checking your logs @AstraQuinn, could be related to a PR I have been working #2590...
> 
> For the record I think you meant #2540

Yes.

**Comment by camilasan** [comment]
I was able to reproduce this issue by unchecking folders that had an exclude list from being synced (see #2692)
When the folder is unchecked and removed from the disk the exclude file list doesn't get updated accordingly so when it tries to read the exclude file again and it doesn't exist anymore... it shows you the error. 
The logs from @AstraQuinn don't give any information about it.

**Comment by AstraQuinn** [comment]
Accepting this issue as resolved, thanks everyone! Sorry I couldn't provide more useful information. Things came up.

**Comment by BeenEncoded** [comment]
On NextCloud Windows Desktop Client version 3.4.2, the issue still persists.  I deleted a sync connection with excluded files and am now recieving the error described in the op of this issue.  I've attatched my logs.  Let me know if any other information is needed.
[logs.zip](https://github.com/nextcloud/desktop/files/8102322/logs.zip)
.
