### ISSUE TITLE
Nextcloud-3.1.0-rc1-x64.msi can not be installed

### ISSUE THREAD

**Issue by goldengel** [nextcloud/desktop#2633]
### Expected behaviour
Update from 3.0.3 to 3.1.0

### Actual behaviour
After Update, no error, just computer restart was forced on msi installer.
After restart, the app does not start.
On manually start, it crashed. Nextcloud client is unusable.

### Steps to reproduce
1. Update https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-3.1.0-rc1-x64.msi
2. Start NextCloud Client

### Client configuration
3.1.0 RC

Operating system: 
Windows 10

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Windows Eventlog
 (No usable error response named)
```

Name der fehlerhaften Anwendung: nextcloud.exe, Version: 3.0.81.16024, Zeitstempel: 0x5fad76f4
Name des fehlerhaften Moduls: nextcloud.exe, Version: 3.0.81.16024, Zeitstempel: 0x5fad76f4
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000000997d0
ID des fehlerhaften Prozesses: 0x548
Startzeit der fehlerhaften Anwendung: 0x01d6b9b0e46e70a8
Pfad der fehlerhaften Anwendung: C:\Program Files\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\Program Files\Nextcloud\nextcloud.exe
Berichtskennung: 6d5a8650-74ac-4d2f-8b53-33d9e57c8029
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

Entry 2
```
Fehlerbucket , Typ 0
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: nextcloud.exe
P2: 3.0.81.16024
P3: 5fad76f4
P4: nextcloud.exe
P5: 3.0.81.16024
P6: 5fad76f4
P7: c0000005
P8: 00000000000997d0
P9: 
P10: 

```
Angefügte Dateien:

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_nextcloud.exe_8448a86f3b7f26d7f786ecd054c9ed2ba16b55a1_31010ed2_b9e868e1-b7ee-40e9-809b-843a3c2cf4f7

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 6d5a8650-74ac-4d2f-8b53-33d9e57c8029
Berichtstatus: 4
Bucket mit Hash: 
CAB-Datei-Guid: 0

Not possible to attach files in this issue. 

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by allexzander** [comment]
@goldengel  Which installer was used when installing 3.0.3? Was this Nextcloud-3.0.3-x64.msi?

**Comment by goldengel** [comment]
as I linked in my issue, yes https://download.nextcloud.com/desktop/prereleases/Windows/Nextcloud-3.1.0-rc1-x64.msi

**Comment by allexzander** [comment]
@goldengel Yes, I've seen that. My question is about the old version 3.0.3. You've mentioned that you've updated from 3.0.3 to 3.1.3. So I was wondering if the old version was installed using the MSI or it was installed with .exe NSIS installer? Of course, if you still can remember that.

**Comment by goldengel** [comment]
it was the exe installed on 3.0.3.

**Comment by camilasan** [comment]
Is this still an issue with https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.1.2-x86.msi?
