### ISSUE TITLE
Use cloud files API for virtual drive on Windows

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/desktop#2637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Whats this all about?
The idea is simple. Ditch dokan and other fuse-emulating libraries and use the [windows cloud files API](https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine). Those tools solve a problem which has been finally recognized by Microsoft. 

### Background
Cloud files API is used by several cloud syncing services already, e.g. OneCloud, OneDrive, Synology Drive and Seafile. I've tested all of them (except OneCloud) and can tell you that this is working very nicely. It is integrated deeply into the system and solves a lot of problems which otherwise would be much effort to cover.

### Related issues
#1104
#1073
#184

**Comment by axheli** [comment]
This would be awesome! I hope we can see this soon :)

**Comment by axheli** [comment]
@er-vin What do you think about this?

**Comment by er-vin** [comment]
What can I say, of course I think it's the way it should be. ;-)

**Comment by axheli** [comment]
@er-vin would this also be for the MacOS Desktop client?

**Comment by michaelstingl** [comment]
> @er-vin would this also be for the MacOS Desktop client?

Related macOS API is FileProvider (https://github.com/nextcloud/desktop/issues/1337)

**Comment by SlavDimov** [comment]
Is there a similar API for Linux?

**Comment by er-vin** [comment]
> Is there a similar API for Linux?

Not that I know of. I think that longer term it'd be nice to see libcloudproviders extended to provide this. It seems to be used by most file managers on Linux so that could do the trick.

**Comment by dverzolla** [comment]
I was searching "dokan" and dropped here. It's really nice to have the integration with https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine. Right now I'm looking more information regarding Nextcloud and Dokan, to achieve Virtual File System. However this 'feature' isn't well docummented. Any idea where to find more informations about NextCloud + Dokan implementation?
