### ISSUE TITLE
Sync files problem 

### ISSUE THREAD

**Issue by anjichiban** [nextcloud/desktop#264]
Hi everybody, 

I use the version 13.0.1 of Nextcloud server & Nextcloud client for MacOSX 10.13.3 and I have a slight issue : this morning, a wonderful popup message appears to me 
![capture d ecran 2018-04-24 a 10 19 19](https://user-images.githubusercontent.com/38652001/39176109-41dba6d6-47ac-11e8-949a-7dc4735cd17c.png)

I think in English, it would says something like this :

![](https://help.nextcloud.com/uploads/default/original/2X/c/c28a31a2bfebb502becc4af4a334998a0d3686e9.png)

I have deleted no folders on Nextcloud, so I don't get the message clearly. I am understanding it as in "All the files contained in Nextcloud folder (which is the root folder) will be deleted" but as I said before, I didn't do any big actions on the server.

Thanks

**Comment by tabp0le** [comment]
I actually had this happen the other day on Linux client. It ended up being because my mounted OpenStack bucket was temporarily unavailable. Not sure if this is the same thing, but that pop-up was the same one I got.

**Comment by camilasan** [comment]
@anjichiban do you still have the problem? Did you check what @tabp0le mentioned?

**Comment by anjichiban** [comment]
@camilasan  I clicked on "delete all files" after being 100% sure that I made a backup. Seems like nothing changed… I don't use OpenStack !

**Comment by camilasan** [comment]
what is your client version? Could you post your logs?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
(I think this issue is similar to #182)

**Comment by camilasan** [comment]
if you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
