### ISSUE TITLE
Automatically update is not working and new version not detected with 'Check for update now'.

### ISSUE THREAD

**Issue by Steve-Z** [nextcloud/desktop#2640]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client should automatically update to newer version when one is available.

### Actual behaviour
A couple of days ago I got a notification to update to 3.0.3. I skipped it at that time, but now when I view settings, it says that I am using the latest version.

### Steps to reproduce
1. Nextcloud >Settings > General
2. General tab shows current version=3.0.2 and says "No updates are available. Your installation is at the latest version."
![image](https://user-images.githubusercontent.com/31359112/99190795-310f5780-272e-11eb-9aa8-bb6d138d31f6.png)

### Client configuration
Client version: 3.0.2

Operating system: Pop_OS 20.04

OS language: Linux

Qt version used by client package (Linux only, see also Settings dialog): ? (Can't figure out how to check this with AppImage.)

Client package (From Nextcloud or distro) (Linux only): Nextcloud-3.0.2-x86_64.AppImage

Installation path of client: Two iterations of `/tmp/Nextcl*` (Which seems odd.)
**UPDATE**: Reboot fixed the 2-iterations problem.

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
Those commands do not work with AppImage

**UPDATE**
I was able to generate log file by running the AppImage from the command line as follows:
```~/path/to/Nextcloud-3.0.2-x86_64.AppImage --logdebug --logfile log.txt```

**Most importantly**, running that command from the command line (as opposed to double-clicking the AppImage in Files/Nautilus) fixed my problem. Not sure if the option arguments were important to fix this. The client then identified that there was a newer version available. It provided a link to the[ Install Clients page](https://nextcloud.com/install/#install-clients) rather than updating itself.

I can upload/attach the log.txt (6MB) or a smaller file with lines specific to my file/directory names filtered out (3.3MB) if that is important for you to know. Or should I use Gist?

**Comment by er-vin** [comment]
I think this is due to the skipping you did initially. Once you do that it refrains from proposing updates again at least for a while.

**Comment by Steve-Z** [comment]
@er-vin Skipping should not break the functionality of automatic update checking or manual update checking as it does in this case. I could understand not getting notifications for a while, but when one opens Settings > General it should not say, "No updates available...", which is clearly not true. Same when one manually checks for updates.
