### ISSUE TITLE
Nextcloud desktop client shows different files compared to Web client

### ISSUE THREAD

**Issue by VSZM** [nextcloud/desktop#2644]
### Expected behaviour

Files stored in the cloud should display all the same regardless of which client is used for a single user.

### Actual behaviour

I have created a new folder on my iOS device using Nextcloud Coherence for iOS 3.0.13.1. After creating the directory I have moved some files to it from the parent directory, then shared the parent directory with a link that expires over time.
On my desktop client (Windows 3.0.2) the files that were moved to the subdirectory are no longer visible in the parent directory (as expected). However the newly created subdirectory is not visible either. If I open the Web Client in my browser the newly created subdirectory is visible with the files moved in it as well (as expected). Server version used is 18.0.3. I have double checked and on the windows client all directories are checked for synchronization.

**Example for the structure**:

_Original state_
- directoryA
    - file1.txt
    - file2.txt

_New state (as created on iOS client, and visible on Web interface after sync)_
- directoryA
    - new_subdir
        - file1.txt
    - file2.txt

_Erroneous new state (as seen on Windows desktop client and in File Explorer)_
- directoryA
    - file2.txt

### Steps to reproduce
1. Create the above folder structure as in Original state on a desktop client. Make sure the server is synced and the state is the same in Web Client.
2. Create a new subdirectory on an iOS client and move a file to it.
3. Observe the divergence on desktop client.

### Client configuration
Client version: 3.0.2

Operating system: Windows 10, latest stable updates

OS language: English

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 18.0.3

Storage backend (external storage): Yes

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://pastebin.com/8bKZ8kE5

2. Web server error log: 

3. Server logfile: nextcloud log (data/nextcloud.log): https://paste.ubuntu.com/p/WTfV4Stmj3/plain/

**Comment by er-vin** [comment]
From the log, it looks like the server didn't change the etag on the root folder. Is it still the same if you force a full sync in the settings dialog? Or after a restart of the client?

**Comment by VSZM** [comment]
Hi,

Yes, It is still the same. I have restarted my PC many times since, did the force full sync as well. I also restarted the server. The folder still won't synchronize on desktop. I could of course work around by downloading the folder from the web ui and just recreate the folder on desktop, but I think this could be a major bug in the synchronization engine and I want to contribute in fixing it. 

Let me know if there are any more information I can provide. I am the owner of the server as well, so I have full access.

Regards, VSZM

**Comment by er-vin** [comment]
So could you try to reproduce the issue, but do a force sync just after doing the changes with your iOS client? And sending the logs of that?

So far on non-forced sync I don't see anything "wrong" as in the client seems to get information from the server that nothing changed. So I wonder what would show in the logs during a forced sync.

Knowing which files moved were will help to explore those logs obviously.

**Comment by VSZM** [comment]
Hm... I could not reproduce the issue with a new folder.

However I do still have the previous folder that will not sync. Proof here: https://imgur.com/a/OhEDp7m

**Comment by er-vin** [comment]
Ah this is a bummer... because I suspect the root cause appeared on logs "in the past" and we missed them... That's why I proposed to recreate the situation again. :-/
