### ISSUE TITLE
Alert Notification buttons not working on Mac Client

### ISSUE THREAD

**Issue by Steve8291** [nextcloud/desktop#2650]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Alerts that show up on Mac OS in the Notifications Center should be clickable to open Finder windows, etc.

### Actual behaviour
Tell us what happens instead

When Nextcloud Client provides an Alert on the Mac OS, the alert shows up in the notifications pane like it should. However, when there are buttons to chose for instance "Show" or "Close" on a new file having been added. Clicking on the "Show" button merely closes the alert dialog and does not open a Finder window with the file in it as I would expect that it should. The same is true when given the alert about a Nextcloud update being available. I'm wondering if maybe there is some Security & Privacy setting that needs to be changed to allow this but I can find nothing about it in the Nextcloud documentation.
NOTE: This feature has never worked for me in any version of Nextcloud or Nextcloud Mac Client.

### Steps to reproduce
1. Install Nextcloud Mac OS Client (current version)
2. Wait for a notification like a shared file or an update
3. When the notification comes through try to click on "Show"
4. Notification closes and nothing happens. No files are shown.

### Client configuration
Client version:

Latest Version, no end to end encryption : 2.3.3 (build 84)
Operating system:
Mac OS 10.15.7 Catalina
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
/Applications/nextcloud.app

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
> Latest Version, no end to end encryption : 2.3.3 (build 84)

2.3.3 is not the latest version :)

Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by Steve8291** [comment]
Thanks @camilasan
That fixed it. I guess I just assumed that the old client was updating itself. That was not the case. Looks like the new one does autoupdates though.
