### ISSUE TITLE
Can't close (exit) NC client on Linux

### ISSUE THREAD

**Issue by toxpal** [nextcloud/desktop#2657]
Manjaro KDE + NC client 3.0.3.

Every time I right-click NC icon and select "Exit Nextcloud", it re-adds itself 1 second later. I even tried to "kill" it using task manager built into OS, and somehow NC re-adds itself second later. It never happened in the past, and I'm not sure if the issue is related to NC or OS itself.

Could anyone try to exit NC client via right-click to see how it works?

**Comment by er-vin** [comment]
This is odd, for sure exits fine for me... and we don't really have an restart code anywhere... Feels like something outside the client code.

**Comment by toxpal** [comment]
Alright, after 2 reboots it started functioning properly again. Probably had something to do with OS.

**Comment by theoo** [comment]
I have the same issue. As soon as it exists (using the "Exit Nexcloud" option from the applet), the app spawns again.

```
Nextcloud version 3.15.3daily
Git revision a595d5bcb6f13f4ea4080b694682a5ae43e2f769
Using Qt 6.8.2, built against Qt 6.8.1
Using Qt platform plugin 'wayland'
Using 'OpenSSL 3.4.1 11 Feb 2025'
Running on CachyOS, x86_64
```

I tried to kill it (kill -9), and it spawns again too! It's almost creepy. 👻 
In my case, rebooting didn't change a thing. The only thing to do was to remove the package before killing the app.

**Comment by nilsding** [comment]
@theoo fwiw, I investigated that in https://github.com/nextcloud/desktop/issues/7653#issuecomment-2675126703

**Comment by mohamadali-halwani** [comment]
> [@theoo](https://github.com/theoo) fwiw, I investigated that in [#7653 (comment)](https://github.com/nextcloud/desktop/issues/7653#issuecomment-2675126703)

I noticed that the option "run on startup" in nextcloud's settings was turned on. I turned it off, tried to kill it a few times, and it respawned indeed. I followed your top on deleting the service from the `dbus-1` directory, then tried to kill it again, and it vanished. Did not need to do a `systemctl --user daemon-reload`.

Thank you so much.
