### ISSUE TITLE
feature: drop files on client icon and get shared link back

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#266]
It'd be nice to be able to 'just' drop stuff on the Nextcloud client icon and get a shared link back in the clipboard.

It would, of course, involve moving/copying files somewhere - either the users' root or a 'shared' or 'dropped' folder, not sure. In either case it'd make interaction with the client a bit nicer :drum:

**Comment by rullzer** [comment]
And what to do if you have multiple accounts ;)
Or don't even sync the root etc ;)

**Comment by comradekingu** [comment]
@rullzer Then you get a dropdown menu and can select it?

**Comment by er-vin** [comment]
Overall not a great idea with the settings we got as @rullzer. I'd also add that it's a tiny target to hit in a crowded space for drag and drop so not so great usability wise.
