### ISSUE TITLE
Unable to disable hidden file syncing

### ISSUE THREAD

**Issue by Baptistou** [nextcloud/desktop#2664]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I want to NOT sync hidden files.

### Actual behaviour
I cannot disable hidden file syncing in Nextcloud Settings.
When I uncheck the checkbox Sync hidden files, the checkbox still remain checked.
Then if I sync a folder, hidden files (for example desktop.ini) are still uploaded to the server.
Tested on Windows 7 and Windows 10.

### Steps to reproduce
1. Open Nextcloud Desktop
2. Go to General Settings
3. Go to Edit Ignored Files
4. Uncheck the checkbox Sync hidden files
5. Click on button OK
6. Go to Edit Ignored Files
7. The checkbox is still checked

### Client configuration
Client version:
3.0.2

Operating system:
Windows 7 Service Pack 1 64 bits
Windows 10 1909 64 bits

OS language:
French

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
C:\Program Files\Nextcloud

### Server configuration

Nextcloud version:
20.0.2

Storage backend (external storage):
None

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
I don't have any log when I uncheck the checkbox nor when I click on button OK

2. Web server error log:
None

3. Server logfile: nextcloud log (data/nextcloud.log):
None

**Comment by Baptistou** [comment]
Same behaviour after update to Nextcloud Desktop 3.0.3

**Comment by joshtrichards** [comment]
Duplicate of #1346

Let's track there.
