### ISSUE TITLE
Use favicon in explorer context menu

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/desktop#2668]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Favicon in context menu

I recomment using the favicon of the server, alternatively we could use the standard icon that is also used for the folder in the left folder tree in windows explorer (NC logo on blue circe).

### Actual behaviour
No favicon, see
![favicon](https://user-images.githubusercontent.com/42836313/100396697-59f4ee00-3046-11eb-8743-19dc5bc554f3.png)
You can also download the one that is used on cloud.example.or (fake url)

### Steps to reproduce
1. Right-click on a file in your nextcloud folder
2. Spend time to find "Nextcloud" in the context menu

### Client configuration
Client version: 3.0.3

Operating system: Win 10 Pro current updates

OS language: de

Qt version used by client package (Linux only, see also Settings dialog): ?

Client package (From Nextcloud or distro) (Linux only): windows

**Comment by elsiehupp** [comment]
Just IMHO, this should be a Windows-only behavior. It is not the norm to show icons in menus on macOS. (I don't know what the norm is on Linux. GNOME probable skews Mac-like, and KDE probably skews Windows-like, just like they do with everything else.)

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
