### ISSUE TITLE
Add "Hide download" option to Share dialog

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/desktop#2672]
The share feature currently supports a *Hide download* option for each share, but this option is not available through Nemo shell integration.

~~Similarly, the web interface but not the shell extensions allows the user to give a short title to each share.~~ (Moved to #3483.)

**Comment by brainchild0** [comment]
What information is needed?

**Comment by brainchild0** [comment]
It would be nice if this issue could be evaluated by a human, even though it has been closed by a robot.

**Comment by FlexW** [comment]
@brainchild0 You are talking about two different features. Let's concentrate this issue on the first one which I think is valid. Please open another issue for the second feature request.

**Comment by brainchild0** [comment]
@FlexW: Sure. Of course the ideal is that the dialog in shell integration shows all the same features as the web interface. I understand that from a development standpoint, it is unavoidable that features of one component may lag behind those of another component. I am only hoping to give a reminder of the gap for those developers who would try to maintain equality between the features of each component.

I opened another issue, as requested.

**Comment by jospoortvliet** [comment]
> @FlexW: Sure. Of course the ideal is that the dialog in shell integration shows all the same features as the web interface. I understand that from a development standpoint, it is unavoidable that features of one component may lag behind those of another component. I am only hoping to give a reminder of the gap for those developers who would try to maintain equality between the features of each component.

That is our goal, but it's also a fair bit of work to keep up. But you'll find that 3.4.1 introduced a bunch of improvements in this area and more are coming!

**Comment by joshtrichards** [comment]
Fixed in #5622
