### ISSUE TITLE
Client crashes on start on windows 10

### ISSUE THREAD

**Issue by lkempf** [nextcloud/desktop#2673]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The client should start.

### Actual behaviour
The client crashes with an access violation.

WinDBG output:
```
(904.4198): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
ocsync!OCC::Utility::crash:
00007ffc`32407900 c704250000000001000000 mov dword ptr [0],1 ds:00000000`00000000=????????
0:000> g
(904.4198): Access violation - code c0000005 (!!! second chance !!!)
ocsync!OCC::Utility::crash:
00007ffc`32407900 c704250000000001000000 mov dword ptr [0],1 ds:00000000`00000000=????????
```

Stack:
```
[0x0]   ocsync!OCC::Utility::crash   
[0x1]   nextcloudsync!OCC::Logger::mirallLog + 0x228   
[0x2]   Qt5Core!qt_message_output + 0x198   
[0x3]   Qt5Core!QCoreApplicationPrivate::qmljsDebugArgumentsString + 0x7f   
[0x4]   Qt5Core!QMessageLogger::fatal + 0x3f   
[0x5]   ocsync!OCC::SqlQuery::prepare + 0x1f8   
[0x6]   ocsync!OCC::SyncJournalDb::checkConnect + 0x69e   
[0x7]   ocsync!OCC::SyncJournalDb::getSelectiveSyncList + 0x96   
[0x8]   nextcloud + 0x1883a   
[0x9]   Qt5Core!QMetaObject::activate + 0x4c3   
[0xa]   nextcloud + 0x3eff7   
[0xb]   Qt5Core!QMetaObject::activate + 0x4c3   
[0xc]   nextcloud + 0x375a   
[0xd]   nextcloud + 0x34625   
[0xe]   nextcloud + 0x1ff45   
[0xf]   nextcloud + 0xfa5f   
[0x10]   nextcloud + 0xd6e87   
[0x11]   nextcloud + 0xd63f2   
```

Deleting `%appdata%\Nextcloud` fixed the issue.

### Client configuration
Client version: 3.0.3

Operating system: Win 10 20H2

OS language: en

Installation path of client: C:\Program Files\Nextcloud 

### Server configuration

Nextcloud version: 20.2

### Logs

1. Client logfile: 
No logfile is created when using `.\nextcloud.exe --logdebug --logfile log.txt`

**Comment by er-vin** [comment]
Unfortunately without logs we won't be able to do much about it and you removed the folder before producing said logs. Closing it for now, if you can get logs of the issue we'll reopen.

**Comment by lkempf** [comment]
I have a backup of the old config and can reintroduce the crash. Also no logs are created, so it is impossible to provide logs.

**Comment by er-vin** [comment]
Ah good then. Yes you can produce logs! ;-)

Just start it from the command line using --logdebug and --logfile C:\nextcloud-desktop.log

This should at least put the fatal error in there, we shall then know more.

**Comment by lkempf** [comment]
I have also found out why I could not create log files. The command line has to be elevated. Otherwise creating the log file fails without error. I have put a censored log here: https://gist.github.com/lkempf/de3c6230030d033ddc07c1f78ea296ed

If you need the blocks at the beginning I removed I'll try to censor it properly (removing server url, synced folder names, etc).

**Comment by er-vin** [comment]
Hm... not sure we'll be able to do much about it. It looks like something ended up creating corrupted database files in the past... but that's too late to know why. Did you have a system crash or similar?

**Comment by lkempf** [comment]
No I don't think so. It just stopped working which I only noticed yesterday because it crashed without an error. It has been going on for at least a week according to the sync conflicts I had to fix. I think providing an error message when a database is corrupted would help.

**Comment by timotheebesse** [comment]
There is issue with Intel integrated graphics. Try updating the drivers. See here https://github.com/nextcloud/desktop/issues/896

**Comment by WelliSolutions** [comment]
The log file contains personal information. How am I supposed to remove that information when I attach the log?
The problem occurs when downgrading from 3.2.0 to 3.1.3 and when some of the hidden .sync files are in the nextcloud folder.

```
2021-04-25 23:10:41:168 [ warning nextcloud.sync.database.sql ]:	Sqlite prepare statement error: "unknown function: parent_hash()" in "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId, e2eMangledName, isE2eEncrypted) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18);"
```

**Comment by er-vin** [comment]
Indeed, if 3.2.0 picked up the sync folder, it adds an index (metadata_parent) to the sync db file which makes it incompatible with earlier releases. You can workaround this either by killing said db file (and waiting for a full resync) or by killing the index by hand using sqlite command line tool.
