### ISSUE TITLE
Client crashes when exiting or shutting down on Windows 7

### ISSUE THREAD

**Issue by bryanscottwalker** [nextcloud/desktop#2674]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Application should close gracefully with no error messages about crashing, and no holding up Windows shutdown procedures.

### Actual behaviour
Exit: Windows crash reporter indicates the application crashed.

Shutdown: The "Windows is waiting..." dialog shows. The machine in question is set to close these as quickly as possible.

### Steps to reproduce
1. Exit: Right click tray icon, select "Exit Nextcloud"
2. Shutdown: Shut down Windows using normal shutdown dialogs from the Start menu.

### Client configuration
Client version: 3.0.3

Operating system: Windows 7, patched to last available updates

OS language: en

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud\nextcloud.exe

### Server configuration

Nextcloud version: 20.0.2

Operating System:	Linux 4.14.204-odroidxu4 armv7l (Armbian)
CPU:			ARMv7 Processor rev 3 (v7l) (8 cores)
Memory:			1.95 GB
Device:			Odroid HC2 w/onboard HDD

Server and Client are on same LAN

Storage backend (external storage): 3TB WD Red HDD

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	nextcloud.exe
  Application Version:	3.0.3.15941
  Application Timestamp:	5f9ab08a
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb67f
  Exception Code:	c0000005
  Exception Offset:	000000000002a1e1
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	d4e1
  Additional Information 2:	d4e153ff5d31fe8b8e6745409ff8e9bd
  Additional Information 3:	092e
  Additional Information 4:	092eecb1bc45f9211753288bad339127

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

No errors indicated

3. Server logfile: nextcloud log (data/nextcloud.log):

No errors indicated

Other observations: This is not the first version where this has happened. We tried to update to a version about a year ago (I believe, I do not remember exactly) and had the same issue. We were able to downgrade to a very old version of Owncloud to solve the problem. At the time, the server was an Open Products device.

**Comment by splitt3r** [comment]
Version 3 of the Nextcloud client does not support Windows 7 anymore (have a look at https://docs.nextcloud.com/desktop/3.0/installing.html#system-requirements). You should upgrade to a more modern and secure version of Windows.

**Comment by bryanscottwalker** [comment]
Thank you for the information.

When a "More Secure" (with indication that we think you are joking) version of Windows becomes available, one that does not constantly update itself and randomly break applications, we will update.

**Comment by er-vin** [comment]
BTW, note that it's likely a GPU driver issue. At least try to update this (we've seen it on Windows 10 as well, got a bunch of duplicates I'm trying to kill them off as I go).

**Comment by bryanscottwalker** [comment]
Interesting, thank you. The machines we're using are the last generation, as far as I know, that supported Windows 7.

I don't believe there are any new GPU - or for that matter any at all - driver updates. I will investigate and report back if I find something of interest. Due to the aforementioned problem with Win10 updates breaking software, we can't "upgrade" right now.
