### ISSUE TITLE
"Your storage is almost full" message spam

### ISSUE THREAD

**Issue by VincentBotte** [nextcloud/desktop#2676]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The pop-up should not pop anymore after being closed. Or it should pop only once while being displayed to avoid getting spammed.

### Actual behaviour
Everytime I browse a folder in an almost full disk, a pop-up appears on the top right side of the screen. It eventually covers the entirety of the right side of the screen.
![alt text](https://i.imgur.com/jYbMnE2.png "Pop-up spam")

### Steps to reproduce
1. Have a disk almost full (90%+)
![alt text](https://i.imgur.com/CIKeM3H.png "Disk full")
2. Browse folders on Nextcloud in this disk with a non admin user
3. Pop-up appears again and again

### Client configuration
Client version: 3.0.3
Client package (From Nextcloud or distro) (Linux only): Ubuntu

### Server configuration
Nextcloud version: 19.0.2.2

**Comment by er-vin** [comment]
Are you sure this is coming from the desktop client? I can't seem to find that message on our end.

**Comment by VincentBotte** [comment]
Oh I'm sorry this is the web client. Wrong section?

**Comment by er-vin** [comment]
Yes definitely, needs to be on the server. Please reopen there. ;-)
