### ISSUE TITLE
Enhancement: Sharing-indicator in Desktop-Client?

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/desktop#2683]
(should be a feature-request)

Hi,

I'm not aware, if I'm right here, but I'm missing an indicator in Windows / macOS, that shows, if a file / folder is shared. Isn't it available?? In a browser you see an icon, if it's shared. Would be very nice, if it's possible for system (Explorer / Finder).

**Comment by Zeik0s** [comment]
Would be great if this is possible, like Onedrive does it. As a separate Column:

![image](https://user-images.githubusercontent.com/35345686/101089014-d6db1700-35b4-11eb-8997-f2329f66f27e.png)

Not sure if Windows-API for this is documented.

**Comment by er-vin** [comment]
You should already have an indicator for this. The sync state icon in the file manager is different for shared files and folders. You have those right? If not there might be a problem with your install, like the file manager extensions being unchecked during install or similar.

**Comment by kangaroo72** [comment]
Are you meaning this??
![image](https://user-images.githubusercontent.com/6906390/101348626-3a529680-388c-11eb-92b9-1828c9dca874.png)

Okay, it's there - but I think for the most users (including me), it's bad to recognize...

**Comment by er-vin** [comment]
Yep, the thing is AFAIK the windows API allows us only one icon. On Linux for instance you actually can have four so we have to separate icons.

**Comment by kangaroo72** [comment]
to bad, but true - thx anyway
