### ISSUE TITLE
Add an option to use a simple menu like in version 2.x?

### ISSUE THREAD

**Issue by briankendall** [nextcloud/desktop#2687]
After having used Nextcloud 3.x for a while, I find that the new menu is a bit of a UX downgrade for me. I don't care about any of the notifications it's displaying, and now some menu items that were easy to get at in the old menu (like app settings) are harder to access.

What do you think of the idea of having a setting to switch back to a simpler menu? If that's okay I could potentially whip up a PR for it.

**Comment by er-vin** [comment]
Sorry but it's not going to happen. Now of course we'll keep iterating on it so it's value will grow (for instance in 3.1.0 it will actually make conflict handling much easier than before). There are other such changes which will come over time.
