### ISSUE TITLE
Desktop App dont allow 2FA any more.....

### ISSUE THREAD

**Issue by ThomasCr** [nextcloud/desktop#2688]
Hi, I use the Nextcloud Desktop Client 3.0.3 from [PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) on Kubuntu 20.04.

With the old Client, I could use the 2FA on logged on clients ([from here](https://apps.nextcloud.com/apps/twofactor_nextcloud_notification))

![grafik](https://user-images.githubusercontent.com/226670/101276451-39970300-37ad-11eb-95a1-79ed166af8ba.png)
(the first option there)

But on the new Client I only can read the request, but have to option to allow/disallow the request!

![grafik](https://user-images.githubusercontent.com/226670/101276594-508a2500-37ae-11eb-994a-83f505f63d02.png)

Any idea when this will be possible again?

**Comment by allexzander** [comment]
@ThomasCr 

Fixed already https://github.com/nextcloud/desktop/pull/2666.

Will become available end of December (IIRC).
