### ISSUE TITLE
Linking/copying configuration to new computer deletes almost all files from all servers without notification

### ISSUE THREAD

**Issue by AlexanderWillner** [nextcloud/desktop#2689]
### Expected behaviour
- No data loss, ideally seamless transition
- Or a strong warning, better an error message

### Actual behaviour
Almost all data on all servers from all linked accounts have been deleted.

### Steps to reproduce
Execute the bad idea to link or copy the configuration from one machine to a new machine to make the transition easier:
1. ```ln -s "$HOME/path/to/e.g./iCloud/configurations/Nextcloud" "$HOME/Library/Application Support/Nextcloud"```
2. Start the client
3. Authenticate within the browser for the different servers
4. See the files vanish (sometimes all files, sometimes a few files are left)

### Client configuration
Client version: 3.0.3git

Operating system: macOS 11.0.1 (20B50)

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client: /Application/nextcloud.app

### Server configuration

Nextcloud version: unknown (most probably various)

Storage backend (external storage): unknown (most probably various)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: I'm only executing the client again when I know how to resolve the issue

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log: unknown

3. Server logfile: nextcloud log (data/nextcloud.log): unknown

**Comment by er-vin** [comment]
Yes, this is most likely due to the fact that the journal dbs in 3.0 got moved in the settings folder. It's better if you link only the nextcloud.cfg.

That said, we reverted that move with 3.1 due end of this week. That's why I'm closing this one I think it won't be possible to hit it like this anymore.
