### ISSUE TITLE
Whitelist of wifi networks

### ISSUE THREAD

**Issue by joel-porquet** [nextcloud/desktop#27]
It'd be great to be able to define a list of wifi networks for which the client is authorized to perform synchronization. It happens sometimes that I tether my phone to my laptop through wifi and I'd prefer not to have big data transfer from nextcloud during that time. From now, I manually pause the synchronization but ideally it'd be very convenient to just define which wifi networks are OK for sync (this way, all other wifi networks - such as in airports, coffee shops, etc.- would be deactivated by default).
Thanks!

**Comment by michaelstingl** [comment]
There is very affordable existing software out there that blocks traffic on tethered connections: https://www.tripmode.ch/

Related upstream issue: https://github.com/owncloud/client/issues/4808

**Comment by HammyHavoc** [comment]
Would be interesting for file sync with local servers if it was dictated by network.

**Comment by Rello** [comment]
Hello,
I am closing this because it is not on the roadmap due to prioritization.
