### ISSUE TITLE
3.03 Sync of readme.md - Sync Error because of 3x same file.

### ISSUE THREAD

**Issue by Numrollen** [nextcloud/desktop#2704]
Hey,
i dont know how my NC instance made this but it created 3x readme.md files in the same folder while i edited it several times. I took a screenshot.

![image](https://user-images.githubusercontent.com/7830015/102075113-0e905d00-3e06-11eb-8f3e-89d2cea508e5.png)

Now the client CANT sync this to windows, 3x the same filename wont work in windows, even with different case sensitive names.

**Comment by camilasan** [comment]
Hi, could you check if you still have this issue with the latest desktop client? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).
If you still have it, could you share the logs?

**Comment by camilasan** [comment]
To provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file. 

Thanks!

**Comment by Numrollen** [comment]
[log_ncsync_error.zip](https://github.com/nextcloud/desktop/files/5950001/log_ncsync_error.zip)

Sorry, still error exists. Another guy here have the same problem.
