### ISSUE TITLE
Talk / appointment updates, perhaps more

### ISSUE THREAD

**Issue by Numrollen** [nextcloud/desktop#2705]
Would be nice for all systems where the users should get informed the windows client would popUp a Message. Not all users let NC open and would be even better when informed when they come back to their PCs. Yes, a Mail with all happened since last active would also be nice but also with the windows client would help be a more "on time" notification when browser and NC is not open. Or even open, i cant look there all the time.

With NC Talk:
- @ User wrote: Let us talk, now! Click here to reply xxx (after 10 sec it disapears)
- You are notified by @ User (after 5sec it disapears)
- Team XYZ startet a call and invited you. Click here to join (will stay and count minutes up)

With calender: 
- in 15min your meeting starts "Lunch with pete" (after 10 sec it disapears)
- 5min to meeting in Talk. Click here to join (will stay and count down)

With NC:
- Video verification for directory was opened. Would you like to verify? Click here.

And so on. _Just an idea to get a better use of activitys that are time critical where the client could help a lot._

(personal opinion: sync, sync errors and events listed is good. all other icons on the top right i dont use)

**Comment by claucambra** [comment]
These have now been implemented -- mainly on the server side, we just forward these on the client :)
