### ISSUE TITLE
Problems with Umlauts when syncing heterogeneously between windows and unix

### ISSUE THREAD

**Issue by rmx-it** [nextcloud/desktop#271]
Hi,
having the following environment:
- nextcloud 13.0 server running FreeBSD-11 with postgres as DB, ZFS as FS.
- One nextcloud-client (2.3.3.1) under Windows 8.1
- One nextcloud-client (compiled from latest sources) running on FreeBSD 11.
  (I'm the maintainer of the nextcloud-client of the FreeBSD port btw.)

Now I'm having the following issue:
- Creating Files/Dirs with Umlauts (öäü...) on the Windows client side works
- The Files/Dirs get created on the nextcloud-server side.
- I see the Files/Dirs in the Android-client too.
but:
- The Files/Dirs do not get seen/synced to the nextcloud-client on FreeBSD.
  (The client user has a de_DE.UTF8 locale btw.)
- I don't see the Files/Dirs in the Logfile either...

How can this be debugged further?

Thanks in advance
---
mike

**Comment by camilasan** [comment]
Could you share the client logs?

**Comment by rmx-it** [comment]
Hi,
I'd like to avoid posting the logs publically.
Could I send them privately per Email?

**Comment by rmx-it** [comment]
Ups. Was not ment to be closed...

**Comment by rmx-it** [comment]
Hi,
BTW:
Another experiment. This time from the FreeBSD side.
- Create a directory 'ÜÄÖ' in the NextCloud folder.
  https://ibb.co/kFOaW7
- Watch the NextCloud client.
  https://ibb.co/hMUqW7
- Look into the sqliteDB's dump:
`
....
INSERT INTO metadata VALUES(-8406747461494501041,18,'������',366886,0,0,0,1525366238,2,'','00048596ocv08xysupak','',2,0,'',0,'');
....
`
- Take a look onto the NextCloud Server:
https://ibb.co/dNPw4S

So, as it seems, the FreeBSD client side doesn't handle the umlauts correctly...

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).
