### ISSUE TITLE
Memory access error (Linux)

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/desktop#2710]
The Nextcloud Client crashes on startup 
### Expected behaviour
Nextcloud Client Starts

### Actual behaviour
Nextcloud crashes on startup (error: memory access error)
-->

### Client configuration
Client version:
3.1.0

Operating system:
Ubuntu Budgie 20.04.1 LTS
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):
qt5ct: 0.39-1build3
Client package (From Nextcloud or distro) (Linux only):
http://ppa.launchpad.net/nextcloud-devs/client/ubuntu

### Server configuration
Nextcloud version:
20.0.2

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
```
qt5ct: using qt5ct plugin
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by er-vin** [comment]
Could we get debug logs and a backtrace of the crash please? Otherwise we won't be able to locate it.

**Comment by chli1** [comment]
I have the same problem since I updated to 3.1.0-20201214.180315.7f4ffd0f7-1.0~focal1 from Ubuntu PPA yesterday. Here is the relevant portion regarding the segmentation fault from the crash report.
[nextcloud-3.1.0-20201214.180315.7f4ffd0f7-1.0~focal1.sigsegv.txt](https://github.com/nextcloud/desktop/files/5694268/nextcloud-3.1.0-20201214.180315.7f4ffd0f7-1.0.focal1.sigsegv.txt)

**Comment by er-vin** [comment]
Thanks, I'm preparing a PR. It will produce an AppImage it'd be appreciated if you could test it and report here when it shows up.

**Comment by er-vin** [comment]
AppImage available on #2713 please let us know how this goes. Thanks in advance.

**Comment by chli1** [comment]
Yes, this version works without problems! Thank you very much for your quick solution!

**Comment by er-vin** [comment]
Thanks for the confirmation. We'll land it after review then.

**Comment by sercxanto** [comment]
> Thanks for the confirmation. We'll land it after review then. It will be released in 3.1.1 in a couple of weeks.

Thanks for the quick feedback on #2750 .

However a couple of weeks until a fixed version is available is a long time for such a major issue. :-/

Currently I am not unable to use nextcloud-desktop. The currently available AppImage shows the same issue and in the PPA the last working version 3.0.3 (which is still installed on another machine I didn't update yet) is not longer available.

Is there any workaround to avoid triggering the bug, like deleting the avatar?

**Comment by er-vin** [comment]
FYI 3.1.1 release preps are going on right now, I've been fast tracking it seeing the amount of affected user. Should be published right in time for xmas.

I'm still baffled this didn't show on *any* of our test systems and that the bug in the code was present since 3.0.0 but somehow didn't trigger before...

**Comment by chli1** [comment]
@sercxanto I'm facing the same issue. The fix is already backported to 3.1 so I'm currently using the AppImage built by the corresponding pull request. See AppImage linked here: #2715

**Comment by rsudev** [comment]
I am facing this issue as well:
```nextcloud --version
Nextcloud version 3.1.0git
Git revision 7f4ffd0f72482b6cf42e74335f3a360c3058f023
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1h  22 Sep 2020'
Running on openSUSE Tumbleweed, x86_64
```
ANY workaround I can apply on the data/settings side? Or do I have to switch to AppImage?

**Comment by er-vin** [comment]
Unfortunately not, it's either AppImage or wait for 3.1.1.

If everything goes well 3.1.1 will be published tomorrow.

**Comment by rsudev** [comment]
Thank you very much for the speedy reply!
I assume the distro-packages will take even a bit more time, so I'll checkout AppImage.

**Comment by rsudev** [comment]
FYI: The AppImage works for me. Thanks again!

**Comment by Korsani** [comment]
FYI: v3.1.1 works on macos 11.1
Many thanks !
