### ISSUE TITLE
PPA 3.1.0 update broken dependencies on Ubuntu 20.10

### ISSUE THREAD

**Issue by Derkades** [nextcloud/desktop#2711]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

```
The following packages have been kept back:
  dolphin-nextcloud libnextcloudsync0 nextcloud-desktop-cmd
```
When manually upgrading (`sudo apt install dolphin-nextcloud libnextcloudsync0 nextcloud-desktop`), the following happens:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nextcloud-desktop : Depends: qtbase-abi-5-12-8 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by er-vin** [comment]
@ivaradi any idea?

**Comment by ivaradi** [comment]
@Derkades are you sure you  are trying to install the package from the repository for Groovy? I still have 20.04 (Focal) and the package `nextcloud-desktop` indeed depends on `qtbase-abi-5-12-8`. However, if I check the package for Groovy, it contains a dependency on `qtbase-abi-5-14-2`.

**Comment by qrest** [comment]
I'm on ubuntu 20.04 using the PPA ``http://ppa.launchpad.net/nextcloud-devs/client/ubuntu/``and getting the same error:

```The following packages have unmet dependencies:
 nextcloud-desktop : Depends: qtbase-abi-5-12-8 but it is not installable
```

**Comment by Derkades** [comment]
Sorry, my bad. Still used `focal` instead of `groovy` in the apt list entry

**Comment by ivaradi** [comment]
@Derkades since @qrest is on 20.04, `focal` should work.
@qrest could you copy here the output of the `dpkg -s libqt5core5a` command? `libqt5core5a` is the package that should provide `qtbase-abi-5-12-8`.

**Comment by Derkades** [comment]
```
Package: libqt5core5a
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 5860
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: qtbase-opensource-src
Version: 5.14.2+dfsg-6
Replaces: libqtcore4 (<< 4:4.8.7+dfsg-20~)
Provides: qtbase-abi-5-14-2
Depends: shared-mime-info, libc6 (>= 2.29), libdouble-conversion3 (>= 2.0.0), libgcc-s1 (>= 3.4), libglib2.0-0 (>= 2.22.0), libicu67 (>= 67.1-1~), libpcre2-16-0 (>= 10.22), libstdc++6 (>= 5), libzstd1 (>= 1.3.2), zlib1g (>= 1:1.1.4)
Recommends: qttranslations5-l10n
Suggests: libthai0
Breaks: libqt5scintilla2-12v5 (<< 2.9.2+dfsg-2~), libqtcore4 (<< 4:4.8.7+dfsg-20~)
Description: Qt 5 core module
 Qt is a cross-platform C++ application framework. Qt's primary feature
 is its rich set of widgets that provide standard GUI functionality.
 .
 The QtCore module contains core non-GUI functionality.
Original-Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
Homepage: https://www.qt.io/developers/
```

**Comment by qrest** [comment]
As you can see I am on KDE neon (which has a ubuntu 20.40 base), which has a more up to date Qt version, maybe that is the problem.
```
Package: libqt5core5a
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 5625
Maintainer: Neon CI <neon@kde.org>
Architecture: amd64
Multi-Arch: same
Source: qtbase-opensource-src
Version: 5.15.2+dfsg-0xneon+20.04+focal+build23
Depends: shared-mime-info, libc6 (>= 2.29), libdouble-conversion3 (>= 2.0.0), libgcc-s1 (>= 3.4), libglib2.0-0 (>= 2.22.0), libicu66 (>= 66.1-1~), libpcre2-16-0 (>= 10.22), libstdc++6 (>= 10), libzstd1 (>= 1.3.2), zlib1g (>= 1:1.1.4)
Recommends: qttranslations5-l10n
Suggests: libthai0
Breaks: libqt5scintilla2-12v5 (<< 2.9.2+dfsg-2~)
Description: Qt 5 core module
 Qt is a cross-platform C++ application framework. Qt's primary feature
 is its rich set of widgets that provide standard GUI functionality.
 .
 The QtCore module contains core non-GUI functionality.
Homepage: https://www.qt.io/developers/
```

**Comment by ivaradi** [comment]
@qrest  yes, the newer version is indeed the problem. 

The Debian build control file does not refer to `qtbase-abi-5-12-8` directly, this dependency (as all shared library dependencies)  is generated automatically by the Debian package build infrastructure. So what I could do is perhaps to explicitly specify libqt5core5a, but I don't know if it worked at all, and even if it did, it would circumvent the automatism and maybe produce invalid packages after a while. 

So this means that the PPA does not support KDE Neon, only standard Ubuntu and those derivates that do not perform such incompatible alterations. That said, maybe there is some compatibility package that does provide `qtbase-abi-5-12-8`. Could you execute  `aptitude search '~Pqtbase-abi-5-12-8'` to see if it is so?

**Comment by qrest** [comment]
This is the output I get:
```
> aptitude search '~Pqtbase-abi-5-12-8'
i A libqt5core5a                        - Qt 5 core module                              
p   libqt5core5a:i386                   - Qt 5 core module 
```
I now reverted back to the non-PPA version, this works for me too.

**Comment by pbek** [comment]
> I'm on ubuntu 20.04 using the PPA `http://ppa.launchpad.net/nextcloud-devs/client/ubuntu/`and getting the same error:
> 
> ```
>  nextcloud-desktop : Depends: qtbase-abi-5-12-8 but it is not installable
> ```

Same issue here on KDE Neon (Ubuntu 20.04) with the same `aptitude search '~Pqtbase-abi-5-12-8'` output like @qrest.

```
i   libqt5core5a                                                                                             - Qt 5 core module                                                                                                  
p   libqt5core5a:i386                                                                                        - Qt 5 core module  
```

My (sad) workaround was using https://github.com/nextcloud/desktop/releases/download/v3.1.0/Nextcloud-3.1.0-x86_64.AppImage.

**Comment by LightTemplar** [comment]
I have the very same problem on KDE Neon. Why is this issue still closed after so many another reports here?

**Comment by Derkades** [comment]
Other issues are being closed as duplicates of this one, but this issue is about me accidentally trying to use the focal repo on groovy.

I think a separate issue should be (re-)opened for discussion about KDE neon 20.04 compatibility.

**Comment by TimJay** [comment]
@er-vin could you re-open one of the KDE neon 20.04 focused issues, thanks 👌

**Comment by ivaradi** [comment]
The original report was about the client on standard Ubuntu 20.10, and it turned out that the wrong distribution from the PPA repo was used. 

The issues about KDE neon are not something I can do much about as I have explained here: https://github.com/nextcloud/desktop/issues/2711#issuecomment-745169022 .

**Comment by rueckix** [comment]
This workaround does it for Neon: https://github.com/nextcloud/desktop/issues/2722#issuecomment-782813875
