### ISSUE TITLE
Not able to move window to 4K screen

### ISSUE THREAD

**Issue by derritter88** [nextcloud/desktop#2712]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud client on Windows should able to moved around on different screen.

### Actual behaviour
Tell us what happens instead
If I would like to move a the client windows from a ultrawidescreen HD (2560 x 1080) screen to a 4K screen the client bounces back and just the mouse pointer moves over.

### Steps to reproduce
1. Open client on ultrawidscreen HD screen.
2. Try to move client to a 4K monitor.

### Client configuration
Client version: 3.1.0

Operating system: Win 10 Pro for WS

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client: `C:\Program Files\Nextcloud`

### Server configuration
Nextcloud version: 20.0.3

Storage backend (external storage): n/a

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by er-vin** [comment]
Which window are we talking about the main dialog or the settings dialog? What do you mean by "bounce back"? Do you mean you literally see it bounce or you mean it's back to its original place when you open it again?

**Comment by derritter88** [comment]
I am talking about the syncronisation configuration - it looks like this:

![IMG_20201215_080827](https://user-images.githubusercontent.com/8606313/102183052-82d20b80-3ead-11eb-8d36-4cf0cf742347.jpg)

And this is the most possible direction where I can move the window - as soon as I would like to move it to the 4K screen it bounces back.
Bounces back would mean that the window goes back a few pixel to the opposite direction; 4K monitor would be right, so the syncronisation windows goes to the left side.
It does not go back to the position where I opened it.

**Comment by er-vin** [comment]
OK, settings dialog. Thanks for the clarifications.

**Comment by axheli** [comment]
Are both of your screens the same specs? i see one of your screens is not?

**Comment by derritter88** [comment]
No, both screens are different.
The left one has 2560x1080 & the right one has 3840x2160

**Comment by axheli** [comment]
that may be because of your two different monitors and they both have different resolutions. I'm running 4k monitors and they're both the same and i dont get that. @er-vin i dont think this is a Nextcloud Client issue. Please see below. 

![image](https://user-images.githubusercontent.com/59488153/103359905-62de4280-4a7e-11eb-977f-0acf49e14d63.png)

**Comment by derritter88** [comment]
Just a suggestion: Maybe it's due to 4K monitor (right) has 175 % scaling while main monitor has 100 %?!
