### ISSUE TITLE
License: proprietary?

### ISSUE THREAD

**Issue by heipa0** [nextcloud/desktop#272]
Hello, the nextcloud-client snap says that it is proprietary. Shouldn't it be open source? 

Is this a mistake or is the snap really proprietary?

![license](https://user-images.githubusercontent.com/35292661/39396494-c3143632-4b21-11e8-9aa8-16a3e30d762a.png)

**Comment by camilasan** [comment]
@heipa0 Definitely not proprietary. Will check it. (https://github.com/nextcloud/nextcloud-snap/issues/68#issuecomment-386130712)

**Comment by camilasan** [comment]
Solved in https://github.com/nextcloud/nextcloud-snap/issues/68

**Comment by szaimen** [comment]
I guess it was this one:
https://github.com/nextcloud/client_theming/blob/master/linux/snap/snapcraft.yaml
