### ISSUE TITLE
UI improvements: New account wizard

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#2720]
### Add account option
- [ ] On the system tray menu, change text from "Add account" to "Add Nextcloud account"

### First step of the wizard (login or sign up)
- [ ] Change wizard window title to "Add Nextcloud account"
- [ ] Align titles: "Connect to Nextcloud" and "Setup Nextcloud server"
- [ ] Change background to Nextcloud blue + white font (see Android client)
- [ ] Stop automatic carousel animation: allow the user to navigate through it only
- [ ] Make login button the primary action 
- [ ] Change text "Sign up with Provider" to "Create account with Provider"
    - [ ]  If user clicked on "Sign up with Provider"... on the next step: make webview window smaller and remove white border
- [ ] Add text "or" between buttons
    
### Second step of the wizard (server url)
- [ ] Remove button to sign up with providers from this step
- [ ] Remove :lock: icon displayed by default: it should only show up after if user enters an url
- [ ] Change hint text color to grey (the texts that explains how to fill up the url)
- [ ] Change text "Next" in button to something like "Pick syncing folders" (or what describes "next" step)

### Third step (syncing folders)
- [ ] Replace the Nextcloud (application icon) logo with  the user avatar
- [ ] Replace text "Server" by username and server name

### New fourth step
- [ ] Add a 4th step where it says new account is connect and syncing
- [ ] After it should show the main dialog

cc @jancborchardt

**Comment by elsiehupp** [comment]
Hi there! I added a [pull request](https://github.com/nextcloud/desktop/pull/2974) that fixes [the issue of not being able to quit from the first-launch wizard](https://github.com/nextcloud/desktop/issues/2969), and I figured I should mention it here just so we can avoid any potential conflicts.
