### ISSUE TITLE
Visual bug: Windows client shows deleted folders in sync list until restart

### ISSUE THREAD

**Issue by woodcarver76** [nextcloud/desktop#273]
When I delete a directory locally on my Windows 10 machine, the folder correctly disappears from the server. But the folder is still visible in the desktop client as one of the folders to sync, until I restart the client. Then, the folder correctly disappears from the list. Triggering manual sync does not help.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

**Comment by camilasan** [comment]
if you still have this problem, please re-open the issue.

Thanks!
