### ISSUE TITLE
Encryption of a non-empty folder fails

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/desktop#274]
The client (64cbc884740f20bc08d188675bce3b4b82070863) allows to encrypt non-empty folders and the server does not prevent it from doing so.
This leads to folders that have some unencrypted files and some encrypted ones. The folder is marked as encrypted on the server (and Web-UI) and therefore cannot be modified (not even deleted) in the Web-UI.

When another client tries to sync this folder it reports files that it cannot decrypt (the unencrypted files).
This is basically a dead end situation as you cannot delete the folder in the Web-UI nor with the client.

**Comment by tcanabrava** [comment]
Fixed locally, pushing.

**Comment by camilasan** [comment]
Pushed to where @tcanabrava? :)

**Comment by camilasan** [comment]
@tcanabrava Was your fix included in #251?

**Comment by tcanabrava** [comment]
Fix is in review.

**Comment by camilasan** [comment]
PR https://github.com/nextcloud/client/pull/291

**Comment by camilasan** [comment]
This is fixed. It is in master.
