### ISSUE TITLE
Linux client opens the main menu on start - can't be closed normally

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/desktop#2740]
### Expected behaviour
When using autostart, the main menu should not appear on my desktop without explicitly requesting it. 

### Actual behaviour
Tell us what happens instead:

When I log into my desktop (Ubuntu 20.04 w/ Unity 7) the main menu dialog appears in the middle of my desktop and does not go away unless I go to the taskbar and select "open main dialog". At this point it reopens the menu which I can navigate away from so it closes

### Steps to reproduce
1. Make sure you have autostart for NC configured
2. Log into desktop (Unity 7 on Ubuntu 20.04)
3. See the menu in the middle of the screen which cannot be closed UNLESS,
4. Click on the taskbar NC menu and select "Open Main dialog" - this will reopen the menu
5. navigate away from the menu (click someplace on your desktop) and the menu closes 

### Client configuration
Client version:

Operating system: Ubuntu 20.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Unclear where to get this info. 
I hope this is enough: 
qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu

Client package (From Nextcloud or distro) (Linux only):
Nextcloud v3.1.0 from PPA (https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client)
Installation path of client: /usr/bin/nextcloud 

### Server configuration
N/A

**Comment by evilSwanson** [comment]
I use Kubuntu (Ubuntu 20.4 + KDE Plasma) and don't have that problem. So this might be related to Unity.

**Comment by er-vin** [comment]
Yes, sounds like something being off in the way the session startup happens. Like it starts the client several times for some reason.

**Comment by childeofentropy** [comment]
i have the same issue in debian bullseye and nextcloud-desktop 3.1.1
