### ISSUE TITLE
Nextcloud Desktop Linux 3.1 -  "For more information please click here." -> 404

### ISSUE THREAD

**Issue by aslmx** [nextcloud/desktop#2745]
### Expected behaviour
When i click the "here" Link, on the Settings -> General tab, it opens "more information" (what ever that might be)

### Actual behaviour
When i click the "here" Link, on the Settings -> General tab, it opens

https://docs.nextcloud.com/desktop/3.1/

That link shows "File not found"

### Steps to reproduce
1. Right click on Nextcloud Desktop Tray icon, click settings
2. Open General Tab
3. Click on "here" link

### Client configuration
Client version: 3.1 

Operating system: Linux Mint 20, XFCE edition

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): apparently not shown on settings dialog :(

Client package (From Nextcloud or distro) (Linux only):  from nextcloud-devs PPA

Installation path of client: /usr/bin/nextcloud

### Server configuration
I would guess irrelevant here. If necessary I will share it upon request.

**Comment by camilasan** [comment]
Thanks for the report. I opened an issue with our sysadmins. It will be fixed soon.

**Comment by camilasan** [comment]
Also https://github.com/nextcloud/documentation/pull/5932.
