### ISSUE TITLE
Crashes x64 under Windows 10

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/desktop#2746]
After upgrade from 3.0.3 to 3.1 via msi (64bit) or exe (34bit) packages the application crashes. If manually starting it also crashes in 3 s.

**Comment by er-vin** [comment]
Could we have a backtrace of the crash? or the debug logs?

I suspect this is a duplicate of #2710 but I'd like to be sure.

**Comment by ostasevych** [comment]
> Could we have a backtrace of the crash? or the debug logs?
> 
> I suspect this is a duplicate of #2710 but I'd like to be sure.

I am sorry, please, guide me, how to get debug logs?..

**Comment by er-vin** [comment]
For the backtrace I'd advise using procdump: https://docs.microsoft.com/en-us/sysinternals/downloads/procdump

For the logs: https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#saving-files-directly
In your case I'd advise going for the alternative proposed when you specify parameters on the command line.

**Comment by vantino** [comment]
still the same issue we experienced with nc 3.1.0 desktop version
after wake up of sleep mode, it needs to be restarted to work again

**Comment by ostasevych** [comment]
> still the same issue we experienced with nc 3.1.0 desktop version
> after wake up of sleep mode, it needs to be restarted to work again

Yes, I confirm. Win10, x64.

**Comment by vantino** [comment]
Meeto

Von: Oleksa <notifications@github.com>
Gesendet: Dienstag, 12. Januar 2021 08:32
An: nextcloud/desktop <desktop@noreply.github.com>
Cc: Marc Vantino <vantino@outlook.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nextcloud/desktop] Crashes x64 under Windows 10 (#2746)


still the same issue we experienced with nc 3.1.0 desktop version
after wake up of sleep mode, it needs to be restarted to work again

Yes, I confirm. Win10, x64.
