### ISSUE TITLE
Nexcloud Desktop Windows 10 update issues causing desktop app to crash.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/desktop#2747]
I have noticed the following behavior (in the past few month (several releases)) when updating  my versions of Nextcloud client on my Windows 10 PC.
It seems, as long as I make use of the "Add Folder Sync Connection"option, the new update just can't cope with it and simply crashes .

This needs to be looked at, and a fix provided ASAP.
Usually, removing the new install and reverting back to former version of Nextcloud usually restore the issue.

Thanks

**Comment by er-vin** [comment]
I'm not 100% sure I understand the steps to get the crash and what you meant to workaround it. Could you please modify the issue description to respect the issues template while giving as many details as you can?

Also we would likely need the following: debug logs when the crash happens and a backtrace of the crash.

Thanks in advance.
