### ISSUE TITLE
Sync progress bar in tray menu similar to Settings

### ISSUE THREAD

**Issue by JohannesStroebel** [nextcloud/desktop#2755]
### Idea
Add something similar like the sync progress bar from the nextcloud client settings ![image](https://user-images.githubusercontent.com/47080541/102817628-6b74b000-43d0-11eb-8fbc-28df56d17e5e.png)
to the windowsbar informations page (e.g. in the red area)
![image](https://user-images.githubusercontent.com/47080541/102817813-babae080-43d0-11eb-90f1-2eeec377f5fa.png)

### Client configuration
Client version: 3.0.3

Operating system: Windows 10

OS language: German

**Comment by er-vin** [comment]
Any opinion @jancborchardt ?

**Comment by jancborchardt** [comment]
You’re right @JohannesStroebel, great suggestion! We had this in an original spec but didn’t get around to it yet. :)

If a sync is in progress, the first entry of the list could always be feedback on that – a bar, and as the subline the same text "22 minutes left …" etc as we also do in the settings dialog.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
