### ISSUE TITLE
NC 3.1.0 crashes every time under Ubuntu 20.04

### ISSUE THREAD

**Issue by elpraga** [nextcloud/desktop#2756]
After the last update, NC desktop client crashes under every DE (Gnome Shell, Fluxbox) I have tried. It does not sync even in the background.

What kind of additional information can I provide? 

versions:

```
qt5ct: using qt5ct plugin
Nextcloud version 3.1.0-20201214.180315.7f4ffd0f7-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.1 LTS, x86_64
```

**Comment by er-vin** [comment]
I suspect this is a duplicate of #2710 

Could we have a backtrace of the crash to confirm?

**Comment by elpraga** [comment]
I'm sorry, my skills are somewhat limited.

Could you, please, tell me how to obtain the backtrace @er-vin ?

**Comment by er-vin** [comment]
Alternatively please try the appimage posted on #2713 and let me know if it solves the crash for you. If yes this would be indeed due to #2710.

**Comment by elpraga** [comment]
Fixed with the latest update
