### ISSUE TITLE
"/latest" URL is not pointing to the latest release

### ISSUE THREAD

**Issue by andredb90** [nextcloud/desktop#2757]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
https://download.nextcloud.com/desktop/releases/Mac/Installer/latest should be pointing to the latest stable release (3.1.0)

(we are relying on this URL to automatically pull the latest release. 

### Actual behaviour

https://download.nextcloud.com/desktop/releases/Mac/Installer/latest downloads Nextcloud installer package version 3.0.2.

### Steps to reproduce
1. open https://download.nextcloud.com/desktop/releases/Mac/Installer/latest in browser
2. Checked version number of the downloaded installer. 

### Client configuration
Client version: 3.1.0

Operating system:
macOS 11.1

OS language:
English

**Comment by er-vin** [comment]
Any chance you could do something using https://github.com/nextcloud/desktop/releases/latest as starting point?

We'd like to get bots off download.nextcloud.com for load reasons.

**Comment by andredb90** [comment]
Thanks for your swift response. - That works!
