### ISSUE TITLE
MacOS Client 3.1 Can't add more than 6 users

### ISSUE THREAD

**Issue by TheRealDidi** [nextcloud/desktop#2758]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Clicking first on the username and then on "Add Account" should open the window with the URL request relating to the server to be connected and so on the other information.

### Actual behaviour
The procedure for creating a new account works up to the sixth account on the identical server. When you try to create the seventh, clicking on "add account" nothing happens. The last menu items have also disappeared and it is no longer possible to close the client (I have to kill it)!

### Steps to reproduce
1. Add an account as usual by clicking on "add account" and complete the configuration by following the instructions
2. Repeat the process for 6 different users on the exact same server
3. By clicking on "add account" when you reach the seventh user, nothing happens (the window does not even open) and the last menu items have disappeared: it is no longer possible to close the client (I have to kill it)!

### Client configuration
Client version: 3.10

Operating system: Mac OS 11.1

OS language: italian

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications/nextcloud

### Server configuration

Nextcloud version: 20.0.4

Storage backend (external storage): n/a

**Comment by TheRealDidi** [comment]
![addaccount](https://user-images.githubusercontent.com/17416303/102867320-e40f5700-4438-11eb-8314-1b397578dbaa.png)

Since the last two menu items have also disappeared, in addition to not being able to add other accounts, I can no longer even open the list of files to be synchronized locally of the accounts already present in case I want to remove some folders .. There is by chance a string that open that window using terminal?

**Comment by er-vin** [comment]
Oh OK, that's because you can't reach the menu entry to add an account that you can't add anymore? In that sense it's purely a GUI problem right? Or am I misunderstanding something?

**Comment by TheRealDidi** [comment]
Thanks for the reply :)
Both things.
If I click on add account ("Aggiungi account") nothing happens; I can also neither close nor enter the settings because the two items below are no longer there, which disappeared right at the end of the configuration of the sixth account, they were there before.

**Comment by er-vin** [comment]
OK, thanks for the info.
