### ISSUE TITLE
main view not opening on xubuntu 20.10

### ISSUE THREAD

**Issue by yalsicor** [nextcloud/desktop#2764]
### Expected behaviour
After clicking the Open Main Window Option from System tray icon the Main window opens

### Actual behaviour
The main window does not open. There is nothing happening at all.

### Steps to reproduce
1. Click Icon in System tray
2. Click Option Open Main Window

### Client configuration
Client version: 3.1.0, also tried alpha channel: 3.1.50

Operating system: Xubuntu 20.10 (XFCE desktop)

OS language: German

Client package (From Nextcloud or distro) (Linux only):  from nextcloud-devs PPA

Installation path of client: /usr/bin/nextcloud

I can open the Settings window with no problem, but adding a new account is not possible due to missing main window view.

I can give more information if needed.

Best,
yal

**Comment by er-vin** [comment]
That feels like one of the ppa issues that @ivaradi processed recently. What do you think @ivaradi ?

**Comment by yalsicor** [comment]
Could that be some dependencies missing?

I just checked out the AppImage (v.3.1.0) and there it is working.

**Comment by er-vin** [comment]
> Well, at least the main window opens, trying to add a new account fails, the menu option just doesnt do anything.

Different issue, been fixed already. The fix is shipped with 3.1.1.

**Comment by dom134** [comment]
Hello, this affects me as well.
v.3.1.1
Ubuntu 20.10 (Gnome + Wayland)
Clicking on 'Open main dialog' does nothing
