### ISSUE TITLE
add an option to hide explorer pane's entries

### ISSUE THREAD

**Issue by Albirew** [nextcloud/desktop#2766]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
either explorer pane not show any share or all are shown under a "Nextclood" subfolder

### Actual behaviour
explorer pane is flooded with NxC shares

### Steps to reproduce
1. install client
2. create 5+ folder sync
3. open explorer with navigation pane
4. try to access the “computer” or “network” group (see screenshot)

### Client configuration
Client version: 3.0.3

Operating system: windows 7 (should be same with 10)

OS language: fr_FR

Installation path of client: "C:\Program Files\Nextcloud"

Any usefull info:
![Sans titre](https://user-images.githubusercontent.com/2805161/102993676-e4355280-451d-11eb-80ea-4a6724552c31.png)

**Comment by er-vin** [comment]
@jancborchardt any opinion on this? It is indeed all or nothing right now.

**Comment by Nyaran** [comment]
You have an option for that

![Sin título](https://user-images.githubusercontent.com/1042532/103133426-a31e7900-46aa-11eb-9008-3e8896221006.png)
 (sorry, mi interface is in spanish, but the option is in that possition)

**Comment by Albirew** [comment]
ah, i see. 3.1.0 was out but it still only show as "up to date" in 3.0.3.
Issue still good for my second idea: a Nextcloud folder entrie with shares in explorer pane woth shares inside instead of an entrie per share

**Comment by Albirew** [comment]
@Nyaran updated to 3.1.1 but looks like this option doesn't exist on win7 or so
![Sans titre](https://user-images.githubusercontent.com/2805161/103151833-ee578b00-4781-11eb-8bea-3e9faafd24d4.png)

**Comment by er-vin** [comment]
> @Nyaran updated to 3.1.1 but looks like this option doesn't exist on win7 or so

Yes, this is unsupported on Win7 AFAIK. This is an OS which reached end of life as well, so don't expect changes there.

**Comment by Baptistou** [comment]
As a workaround on Windows 7 :
1. Edit the file ```C:\Users\USERNAME\AppData\Roaming\Nextcloud\nextcloud.cfg```
2. Change the value ```showInExplorerNavigationPane=true``` to ```showInExplorerNavigationPane=false```
3. Close and restart Nextcloud, the icons should disappear from explorer pane.

**Comment by Derkades** [comment]
see #2766 if you find this issue through google
