### ISSUE TITLE
[macOS] 3.1.1 quits on Big Sur after a few seconds, checksum errors with a daily build

### ISSUE THREAD

**Issue by vitobotta** [nextcloud/desktop#2767]
### Expected behaviour
Hi.
I would expect the latest release to be stable on macOS Big Sur 11.1 and sync files without any issues.

### Actual behaviour
I tried the latest release 3.1.1 on Big Sur 11.1 but it quits after a few seconds without any helpful errors or anything. The same happened with the recent previous releases, and the only way I got the Nextcloud client working for me is to use the latest daily build (Dec 18 first, now Dec 23).

The daily build doesn't quit and seems to work for the most part, but it's happened a couple of times already that it gets stuck in a sort of syncing loop for some random files (already present on disk) with the message "The downloaded file does not match the checksum, it will be resumed" for the files affected. But these don't get fixed apparently. I am not sure if it's a problem with the server (I use Hetzner's managed Nextcloud service) or with the client. I use the same client on an older mac with High Sierra and this checksum issue hasn't happened there yet.

### Steps to reproduce
With 3.1.1
1. The app quits after a few seconds
2. 
3. 

With daily build Dec 23
1. Configure a connection
2. The sync sometimes gets stuck in a loop while trying to sync some random files due to issues with mismatching checksums. A couple of times I fixed it by deleting and reuploading the files, but at the moment the files are quite many so I am looking for a proper fix.
3. 

### Client configuration
Client version:
3.1.1 and daily build Dec 23

Operating system:
macOS Big Sur 11.1 - I have also tried upgrading to 11.2 beta just in case, with no difference

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration
Nextcloud version: 20.0.4

Storage backend (external storage):
Not sure (it's a managed/hosted Nextcloud instance). 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Is there any specific info I can provide rather than full logs? I am a bit uncomfortable sharing files with full lists of my files etc.

2. Web server error log:
I don't have access to these.

3. Server logfile: nextcloud log (data/nextcloud.log):
I don't have access to these.

Thanks in advance for any input!

**Comment by er-vin** [comment]
Clearly something is off if there's a checksum error on download. Could we get logs for this error case? (use the new button in the settings dialog for it)

Then please upload the zip file in our secure file drop, make sure it contains a descriptive name more people are uploading there, a companion text file saying which file is affected would be welcome as well: https://cloud.nextcloud.com/s/7ZSqepBdwCgwnkA

**Comment by vitobotta** [comment]
Hi @er-vin 

Just to be sure before I upload, is there any sensitive information in the logs? 

The affected files are kinda random, every time I restart the app I see new ones. I tried removing and readding the folder connection with no difference.

**Comment by vitobotta** [comment]
@er-vin 

It doesn't seem like the file contains any sensitive data so I uploaded it. The file name is vito_botta.zip.

Thanks a lot in advance for looking into it!

**Comment by er-vin** [comment]
Can't promise we'll look into the logs soon but at least we got them stashed somewhere. Thanks.

**Comment by vitobotta** [comment]
@er-vin is my data safe in the meantime or can something get corrupted/lost?

**Comment by er-vin** [comment]
Should be safe

**Comment by vitobotta** [comment]
Cool. Hopefully you'll have a chance to check this soon. Thanks! :)
