### ISSUE TITLE
Add automatic retry after file transfer fail and login fail

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#2769]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
There are some times when the network hiccups, causing transfer to fail or login fail. The program should be able to recover from such error.

### Actual behaviour
The program just sits there and do nothing after gateway timed out.

### Steps to reproduce
1. disable the backend server of a load balancer, the balancer would report "gateway timed out"
2. 
3.

### Client configuration
Client version: 3.0.3

**Comment by camilasan** [comment]
Hi, 

1. Could you provide logs? Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
See https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files.
2. On which platform you are running the desktop client? 
3. Could you provide screenshots of the error?
4. What is the Nextcloud server version?

Thanks!
