### ISSUE TITLE
Missing action icons

### ISSUE THREAD

**Issue by Tachi107** [nextcloud/desktop#2775]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Actions in the client's feed should have different icons.
![image](https://user-images.githubusercontent.com/34214253/103170407-41921200-4844-11eb-89ab-bf3ecd864230.png)

### Actual behaviour
All actions have the same icon (thunder). 
This only happens with one of my two Nextcloud servers.
![image](https://user-images.githubusercontent.com/34214253/103170369-fb3cb300-4843-11eb-9231-6499d141f869.png)

### Steps to reproduce
1. Install client
2. Add account
3. Look at actions not having icons

### Client configuration
Client version: 3.0.1 (Debian)

Operating system: Debian Testing

OS language: Italian

Qt version used by client package: 5.15.2

Client package: from Debian Testing

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version: 20.0.4

Storage backend (external storage): No

### Logs

1. Client logfile: [del.dog/tachi_nextcloud-desktop_missing-action-icons](https://del.dog/tachi_nextcloud-desktop_missing-action-icons)

2. Web server error log: Nothing related to Nextcloud

3. Server logfile: nextcloud log (data/nextcloud.log): [del.dog/tachi_nextcloud-desktop_missing-action-icons_server](https://del.dog/tachi_nextcloud-desktop_missing-action-icons_server) (Spoiler: nothing relevant, only `/appinfo/app.php is deprecated` stuff)

**Comment by Tachi107** [comment]
Strangely enough, after adding and then removing a few hundreds of files the bug disappeared...
![image](https://user-images.githubusercontent.com/34214253/103366143-1ae10f00-4ac2-11eb-8f16-49118d774229.png)

I feel like this should remain open until someone figures out why/what happened

**Comment by joshtrichards** [comment]
The "thunder" icon is the default `activity.svg` icon. Not sure why this would have occurred at the time, but given we haven't seen further reports in 4 years I'll close this out for now. We can always re-open if it pops up again.
