### ISSUE TITLE
Desktop client shows "There are unresolved conflicts. Click for details" but not clickable

### ISSUE THREAD

**Issue by jvhoffbauer** [nextcloud/desktop#2779]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

<img width="697" alt="image" src="https://user-images.githubusercontent.com/9884254/103343814-34b42f00-4a8d-11eb-949b-2adb90293d1d.png">

### Expected behaviour
Something should happen, when I click on the "Click for details" text or I should be able to access the details somehow

### Actual behaviour
Nothing happens

### Steps to reproduce
1. Probably create some _unresolved conflicts_ during syncing
2. Open the desktop client settings

### Client configuration
Client version: 3.0.3
Operating system: Mac OS
OS language: English
Installation path of client: /Applications/nextcloud

### Logs

Client logfile: I see log entries like these ones:

`./extracted//20201229_0048_owncloud.log.0:390133:2020-12-29 00:49:07:691 [ info nextcloud.sync.csync.updater ]:	file: x/y/z/myfile (conflicted copy 2020-01-28 112343).pdf, instruction: INSTRUCTION_NONE <<=`

`./extracted//20201229_0048_owncloud.log.0:404387:2020-12-29 00:49:14:148 [ warning nextcloud.gui.activity ]:	Item  "x/y/z/myfile (conflicted copy 2020-01-28 112343).pdf"  retrieved resulted in error  "Conflict: Server version downloaded, local copy renamed and not uploaded."`

If you need any more information, feel free to reach out. I actually think, this is a gui bug in the client.

**Comment by er-vin** [comment]
Thanks for reaching out. This has been fixed in 3.1

**Comment by jvhoffbauer** [comment]
Oh great, sorry then!
