### ISSUE TITLE
Nextcloud client db file gets weird group id

### ISSUE THREAD

**Issue by Iolaum** [nextcloud/desktop#2785]
### Expected behaviour

Files created by the latest version of the nextcloud client have group ownership appropriate for the folder they are created. Ideally this should be the primary group of the user running the nextcloud client.

### Actual behaviour
The `._sync_69b16fd30061.db` folder of a synced directory has a groupid of `101001`. Note that such an entry does not exist in the `/etc/group` file. This issue has appeared on both folder's that I am syncing to my nextcloud instance. The issue appears to have taken place after I updated my nextcloud client from 3.0.x to 3.1.1.

You can see an example here:

```
# I move to a sync'ed directory first
$ ls -la
... various synced subfolders here
-rw-r--r--. 1 user1 user1        0 Jan  1 10:25  .owncloudsync.log
-rw-r--r--. 1 user1 101001 11067392 Jan  2 22:33  ._sync_60689335bd02.db

```

### Steps to reproduce

1. Have some files syncinf with a 3.0.x version of nextcloud client. If I recall correctly my previous version was `nextcloud-client-3.0.3-1.fc33.x86_64`
2. Update to the current latest available version, `nextcloud-client-3.1.1-1.fc33.x86_64`
3. Check the group ownership of  `._sync_69b16fd30061.db` files.

### Client configuration
Client version:

```
$ nextcloud --version
Nextcloud version 3.1.1git
Git revision 75c329f4ff3472774b00537e096ba8c987a6bb3c
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1i FIPS  8 Dec 2020'
Running on Fedora 33.20210102.0 (Silverblue), x86_64

```

Operating system:

```
$ cat /etc/os-release 
NAME=Fedora
VERSION="33.20210102.0 (Silverblue)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33.20210102.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='33.20210102.0'
```
OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): `nextcloud-client-3.0.3-1.fc33.x86_64`

Installation path of client:

```
$ which nextcloud
/usr/bin/nextcloud
```

### Server configuration

Nextcloud version: 20.0.3.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by er-vin** [comment]
OK, this is odd. I definitely don't have this here...

**Comment by Iolaum** [comment]
Yes the client was installed from the official fedora repositories. I 'll give it a shot at trying to replicate it.
