### ISSUE TITLE
Nextcloud Sync Client logout after PC boot

### ISSUE THREAD

**Issue by xXPerditorXx** [nextcloud/desktop#2798]
I have the problem, that every time I boot my PC the sync Client needs the permission of my user. If I click grand access and reboot later, the Sync Client Pops Up and it wants again the permission of my user.
After I Grand Access to the Client, Nextcloud stopped working and I have to stop nextcloud.exe via Task Manager and start it again.
![1](https://user-images.githubusercontent.com/60017046/103767594-32b81600-5021-11eb-84f7-dbc83d39c35e.png)

**Comment by er-vin** [comment]
Please fill in the issue template. Which windows version is that? Also probably worth trying with a more recent version.

**Comment by xXPerditorXx** [comment]
MS WIndows 10 Home 10.0.19042 
Nextcloud Sync 3.1.1 (Windows)

**Comment by er-vin** [comment]
You screenshot claims 3.0.2 for the desktop client version though. We'd need logs I guess. But one thing you could check is that the credentials end up properly in Windows Credentials Manager.

**Comment by xXPerditorXx** [comment]
How do I get the log file.

**Comment by xXPerditorXx** [comment]
![Uploading Screenshot 2021-01-06 134253.png…]()

**Comment by xXPerditorXx** [comment]
Ok I get it but there is now another error

![Screenshot 2021-01-06 134701](https://user-images.githubusercontent.com/60017046/103770062-ae1bc680-5025-11eb-9ab5-a54bbd844d0b.png)

**Comment by er-vin** [comment]
With 3.1.1 you can simply click on the "Create Debug Archive" button in the settings dialog. In you case it's better done just after boot I'd say this way it should capture whatever goes wrong.

**Comment by xXPerditorXx** [comment]
Ok i can give it to you but now it don't asked me again, but I hope you will find something.

[bug.zip](https://github.com/nextcloud/desktop/files/5781479/bug.zip)

**Comment by er-vin** [comment]
> Ok i can give it to you but now it don't asked me again, but I hope you will find something.

Then don't bother, it really need to be done within the 24 hours of the problem showing up. Let's see if it does it again and then create the archive quickly.

**Comment by xXPerditorXx** [comment]
At the moment it is not showing up again and I don't know why

**Comment by xXPerditorXx** [comment]
Is it normal, that on startup i get Nextcloud recommendations and every time it says Genarate Backup Codes?

**Comment by er-vin** [comment]
> ![Capture](https://user-images.githubusercontent.com/60017046/104010255-8145eb80-51ac-11eb-8ac2-a6df4f04744a.PNG)
> Is it normally, that on startup I get Nextcloud recommendations and every time it says Generate Backup Codes?

I'd say yes, it shows you the server notifications that you didn't dismiss. Can be done from the activity stream.
