### ISSUE TITLE
Nextcloud version 3.1.1git crashes when solving conflicts files with style Fusion or Chameleon on ArchLinux

### ISSUE THREAD

**Issue by AkechiShiro** [nextcloud/desktop#2804]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Resolving conflicts should never crash Nextcloud.

### Actual behaviour
Here is the backtrace I got in [`gef` (an enhanced GDB)](https://gist.github.com/AkechiShiro/0d132831c9d3a3d55bdac22605bf7adf)

### Steps to reproduce
1. Have a lot of conflicts
2. Try to resolve them and then at some point
3. Notice the crash

### Client configuration
Client version: 
```
Nextcloud version 3.1.1git
Git revision 75c329f4ff3472774b00537e096ba8c987a6bb3c
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1i  8 Dec 2020'
Running on Arch Linux, x86_64
```

Operating system: ArchLinux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
```
Using Qt 5.15.2, built against Qt 5.15.2
```

Client package (From Nextcloud or distro) (Linux only): coming from distro, the community repo of the ArchLinux official repo

Installation path of client:`/bin/nextcloud`

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: the log file is huge about 58MB I can't really upload it anywhere at the moment.

I will upload the client log file later when reproducing the bug again.

**Comment by AkechiShiro** [comment]
Here is some more info, I'm adding the client logfile to the initial message of this issue.
```
Opening in existing browser session.
2021-01-07 18:02:51:376 [ fatal default ]:	Object 0x559f37ab7190 destroyed while one of its QML signal handlers is in progress.
Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
This behavior is NOT supported!
qrc:/qml/src/gui/tray/Window.qml:550: function() { [native code] }
[1]    1282603 abort (core dumped)  nextcloud --logdebug --logfile log.txt
```

**Comment by er-vin** [comment]
Logs might not be necessary but the backtrace of the crash is definitely necessary.

**Comment by Freeedim** [comment]
(Very sorry for the off-topic but I am trying to start a crusade the earliest I can against an error that seems quite new and quickly spreading across Internet, before it goes wild and viral:
"per say" does not exist and means nothing. "per se" does exist and is Latin for "by it(self)", or "in it(self)".
Sorry, I mean no offense.)

**Comment by er-vin** [comment]
> (Very sorry for the off-topic but I am trying to start a crusade the earliest I can against an error that seems quite new and quickly spreading across Internet, before it goes wild and viral:
> "per say" does not exist and means nothing. "per se" does exist and is Latin for "by it(self)", or "in it(self)".
> Sorry, I mean no offense.)

Actually I'm more offended of the fact I did it... I'm very much aware of "per se"... I really wonder why I typed "say" this time. :-)
