### ISSUE TITLE
3.1.1. linux appimage indicator icon broken

### ISSUE THREAD

**Issue by dtto** [nextcloud/desktop#2806]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On startup, the indicator icon should be visible on the top nav bar as it always has been in the past. When synced, should display green check mark, when syncing a blue sync icon.

### Actual behaviour
Tell us what happens instead
Icon is white-on-white at all times and thus almost impossible to see. When fully synced, it is white-on-white. When syncing, it is also white-on-white.
### Steps to reproduce
1. Upgrade to 3.1.1.
2. Restart nextcloud desktop client

### Client configuration
Client version: 3.1.1

Operating system: Debian Buster

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): I can't seem to find this.

Client package (From Nextcloud or distro) (Linux only): Appimage downloaded from nextcloud.com

Installation path of client: /usr/local/bin/

**Comment by er-vin** [comment]
Could we have a screenshot plase? Also which desktop environment is this? We got reports of issues which really are in the GNOME Shell applets for instance. Could be linked to the switch to monochrome icons of course.

**Comment by xen0m0rph2020** [comment]
Hi
My issue is slightly different but it was closed.
I don't have any icons in status bar. While this bug is about it being white on white.

**Comment by er-vin** [comment]
Yes, we got the icon missing reported in some other issue. It's mostly a timing issue AFAICT.

**Comment by dtto** [comment]
Here you go.

![nextcloud_icon](https://user-images.githubusercontent.com/6629106/104223220-37514580-53f8-11eb-9338-54d8c5ee3cbc.png)

The nextcloud icon is right next to the audio icon.

**Comment by er-vin** [comment]
Right so it'd need to use the black ones. @camilasan any idea on what we could base that switch to be black instead of white? Since for light colored bars it'll obviously create such issues...

Worst case scenario we move back to colored for Linux.

**Comment by camilasan** [comment]
> Right so it'd need to use the black ones. @camilasan any idea on what we could base that switch to be black instead of white? Since for light colored bars it'll obviously create such issues...
> 
> Worst case scenario we move back to colored for Linux.

We change the default for monochrome icons on Linux but any user can still uncheck it in the settings "Use monochrome icons". Wouldn't that solve your problem @dtto?

**Comment by er-vin** [comment]
> > Right so it'd need to use the black ones. @camilasan any idea on what we could base that switch to be black instead of white? Since for light colored bars it'll obviously create such issues...
> > Worst case scenario we move back to colored for Linux.
> 
> We change the default for monochrome icons on Linux but any user can still uncheck it in the settings "Use monochrome icons".

Good point. People are not stuck with that... still for a first impression on launch and having to go there manually it's not great. I wondered if we had a way to know which monochrome icons to pick... maybe not...

> Wouldn't that solve your problem @dtto?

Could you indeed check and report please?

**Comment by dtto** [comment]
> We change the default for monochrome icons on Linux but any user can still uncheck it in the settings "Use monochrome icons". Wouldn't that solve your problem @dtto?

Indeed, that does fix it. Honestly, I had never seen that setting before so it still might be a good idea to roll out another fix. Thanks for the work.

**Comment by camilasan** [comment]
> I wondered if we had a way to know which monochrome icons to pick... maybe not...

I would have to look into this.
