### ISSUE TITLE
Reinstalling an instance and logging back in can result in data loss

### ISSUE THREAD

**Issue by panos** [nextcloud/desktop#2808]
### Expected behaviour

When the end user/administrator deletes their instance and then brings it back up (with similar information, e.g. usernames, URLs or even passwords), it's natural for some folders not to exist at first.

The Desktop sync client should figure out that the instance is pragmatically different than the other one, then recreate and reupload the files.

### Actual behaviour

Instead of doing that, however, the sync client immediately opts for synchronising itself with the server, thus deleting any files that may exist in the folders.

I briefly got scared that something like that was about to happen, so I took a timely backup, but then I had to go through the installation process again, which actually did result in data loss this time. It may be important to note that I didn't have a few files sync at first because of encoding-related issues, although I'm not sure if that's relevant.

### Steps to reproduce
1. Create Nextcloud instance
2. Reauthenticate and synchronise files
3. Delete the Nextcloud instance, repeat steps 1 and 2
4. Congratulations, you lost your synchronised folder.

(Make sure to use a file with German/Greek-specific characters under an ext4 partition on a server and a btrfs partition on the client, just in case my initial presumption as to what the issue is was incorrect.)

### Client configuration

Client version: `3.1.0`

Operating system: `Gentoo/Linux` (`17.1`, running on top of a customized Linux kernel)

OS language: English (`en-US`)

Client package (From Nextcloud or distro) (Linux only): See https://packages.gentoo.org/packages/net-misc/nextcloud-client

### Server configuration

Nextcloud version:

Storage backend (external storage): No

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: I'm not particularly sure how to include relevant logs without including personal information at the same time, so I tried my best to describe the issues and potential causes that I detected myself. I'd be more than glad to update this document accordingly, though.

**Comment by panos** [comment]
I stood very lucky because I abuse software a lot and I end up using them in unexpected ways very often, so I tried to report this issue as fast as I could in order to prevent something [like this](https://github.com/microsoft/vscode/issues/32405) from happening to anyone again.

**Comment by er-vin** [comment]
Honestly I'm not sure that's fixable or that it's even desirable to fix this. I mean in the situation you describe the server got redone with no migration of data. The client has no way to know it should be treated as a new server. Said server exposes an empty directory with a new etag value... so yes the client is going to sync with that. It's effectively like removing all files from the server.

**Comment by panos** [comment]
Yeah, I got that part, which is why I was careful enough to back up my data just in case. The folder on the server may be empty and there were no efforts at migrating the data (which oftentimes is not possible- an issue with my database/encryption modules promtped me to do this), but I'm not sure why an empty folder of a new server is supposed to bear heavier weight than the contents of the folder that already exists.

I mean, that does sound like a very complicated way to get a clean slate when you could just delete the folder, doesn't it? That's why I think that what I described should be dealt with as "expected".

Also, why does the client default towards destruction in this case?

**Comment by panos** [comment]
It's kind of difficult for me to wrap my head around this problem, particularly because any other solution would require some other identifier for the server on top of existing credentials. But hey, you could also see some other security benefits that would probably fall under the case of edge cases. (e.g. individual hijacks the DNS records of a Nextcloud instance, accepts the token of its users [I'm not sure if this is possible since I haven't read up on the design] regardless of its value and redirects them to a fake Nextcloud instance, files get stolen).

If you possessed some sort of unique identifier strictly between the client and the server that's not just the URL, just like OpenSSH, is there a chance that this could do the trick, maybe? Perhaps I'm excessively opinionated on this, but I just want to help.

**Comment by er-vin** [comment]
Because the decision tree roughly speaking is checking if the remote folder changed or not (yes in that case) and if it's more recent than the local one (yes again in that case). So it will pick the remote version.

Changing that decision tree would quickly lead to situations like "I removed stuff from the server and it's still here locally, why do I have to remove it by hand?"

As for the token yes we got one, that's what is used for the auth in fact. But you can decide to logout and login later, it's not gonna help.

**Comment by panos** [comment]
I knew I was being a bit unclear in what I was saying, but how about some sort of 'internal certificate'-thingie (I really have no better way to describe this) that says 'Hey, I'm **YOUR server**. This is *my identity*, which it's completely irrelevant to the domain and my other characteristics. If you're trying to log back in and cannot verify it's me, do all the sync-ing stuff from scratch!")

**Comment by er-vin** [comment]
OK, I see what you mean. This would require support from the server first though, I don't think we have that... @rullzer do you know more?

**Comment by panos** [comment]
Does this really have to be closed considering that it's still outstanding?
