### ISSUE TITLE
Feature: network filesystem mounting (windows drive letters)

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/desktop#2810]
This feature request is tied to a deficiency in the mswindows webdav client implementation.

In many cases, especially many-user systems with shared access to group folders, a full sync is impractical, and needs are better handled by mounting a network filesystem.

The deficiency in question is the fact that their (ms) webdav client intentionally disposes of login credentials upon reboot, making it impossible to automatically remount a webdav on login unless you write a script that stores the login credentials in plain text that is executed as a scheduled task on login, i.e. ```net use X: https://nextcloud.mydomain.xyz/remote.php/webdav /user:USER PASSWORD /persistent:no```

This approach is both poor for security, and overly challenging to implement for a large number of non-technically competent users.

So the feature request is for the nextcloud client, at least for Windows, to be able to handle the filesystem mounting when the sync client starts on login. Other platforms don't need this feature since they don't suffer from this defect, which is apparently intentional;

https://docs.microsoft.com/en-us/troubleshoot/windows-client/networking/cannot-automatically-reconnect-dav-share

There are 3rd party programs able to perform this function, but none free of security concerns.

**Comment by er-vin** [comment]
Probably better solved with #2444

**Comment by lbdroid** [comment]
Isn't that the same thing, but implemented by reinventing the wheel?

**Comment by er-vin** [comment]
Not really, it also brings offline availability of some files as you see fit. More control overall.

**Comment by lbdroid** [comment]
If the intention is to go with something similar to the "owncloud" implementation, it doesn't fit needs, since it still uses an unwanted synchronization approach, just that it synchronizes files on demand rather than in bulk.

**Comment by er-vin** [comment]
Well, apart from "I don't want it to sync" I don't see how it doesn't fit the need: you get the files on demand like with a webdav mount. It also does more obviously.

In any case there's almost no chance of making an alternative to the windows webdav client.

**Comment by lbdroid** [comment]
It doesn't fit needs because it will eventually fill the disk on the local machine needlessly. This is OK for technically minded people who can clear it out as needed, but not so good for normals. When you have a lot of users each accessing files all over the share, then it will eventually synchronize everything, storing many copies of all data needlessly.

And I'm not actually suggesting making an *alternative* to the windows webdav client, rather this could be implemented simply by *controlling* the windows webdav client. Because windows is too stupid to remember credentials after signing out, the nextcloud client can just trigger a "net use" as appropriate upon login.

**Comment by er-vin** [comment]
> It doesn't fit needs because it will eventually fill the disk on the local machine needlessly. This is OK for technically minded people who can clear it out as needed, but not so good for normals. When you have a lot of users each accessing files all over the share, then it will eventually synchronize everything, storing many copies of all data needlessly.

That's assuming files are never pruned. It will be the case at some point.

> And I'm not actually suggesting making an _alternative_ to the windows webdav client, rather this could be implemented simply by _controlling_ the windows webdav client. Because windows is too stupid to remember credentials after signing out, the nextcloud client can just trigger a "net use" as appropriate upon login.

OK. I get what you mean now. Still that's an extra workflow for something similar to the virtual file system in the end.
