### ISSUE TITLE
Apply name and icon from custom theme to Windows explorer link

### ISSUE THREAD

**Issue by iUltimateLP** [nextcloud/desktop#2812]
### Expected behaviour
It would be cool if the link to the Nextcloud folder on the left side of the Windows explorer would be themed to the admin theming settings of Nextcloud. I've manually changed it via the Windows Registry so here's an image of how it could look like:

![image](https://user-images.githubusercontent.com/8491339/104205838-2839ba00-542f-11eb-9985-e7c9523f9b56.png)

### Actual behaviour
It just shows the standard Nextcloud logo and name.

### Client configuration
Client version: 3.0.3

Operating system: Windows

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

**Comment by er-vin** [comment]
Sorry slightly unclear to me from the screenshot, which one did you hack in the registry?

Note that this works through branding already, but I guess you're not running a branded client.

**Comment by iUltimateLP** [comment]
The NEXUScloud is what I hacked in registry, it used to be the standard blue Nextcloud icon and "Nextcloud" name. So the branded client does indeed set up the link in the explorer with the custom branded name and logo?

**Comment by er-vin** [comment]
Yes. Because the branded client usually has a different application logo and it uses that one for the explorer sidebar.

**Comment by camilasan** [comment]
I am not sure this is an "enhancement" we would want to implement.

**Comment by iUltimateLP** [comment]
> Yes. Because the branded client usually has a different application logo and it uses that one for the explorer sidebar.

Ah I see that the branded client works a little bit towards OEMing a nextcloud installation.

> I am not sure this is an "enhancement" we would want to implement.

Well, if Nextcloud already gives you the opportunity to theme (and brand) the web interface, why not also the explorer link. Sure, having a blue "Nextcloud" there is enough, but you could also add a checkbox in the settings for that.

**Comment by er-vin** [comment]
> > Yes. Because the branded client usually has a different application logo and it uses that one for the explorer sidebar.
> 
> Ah I see that the branded client works a little bit towards OEMing a nextcloud installation.

This is exactly about that yes.

> > I am not sure this is an "enhancement" we would want to implement.
> 
> Well, if Nextcloud already gives you the opportunity to theme (and brand) the web interface, why not also the explorer link. Sure, having a blue "Nextcloud" there is enough, but you could also add a checkbox in the settings for that.

Honestly shouldn't be in the settings GUI. Eventually as settings in the config but shouldn't get exposed in my opinion.

In any case since that's doable via the branding mechanism I'm leaning toward closing that one.

**Comment by iUltimateLP** [comment]
Alright, then I'll have a look at creating branded clients!

**Comment by camilasan** [comment]
> Alright, then I'll have a look at creating branded clients!

I think you can start by checking the scripts we use for the daily builds at https://github.com/nextcloud/client-building.

**Comment by MatDepInfo** [comment]
@iUltimateLP what change do you made to achieve that ?
