### ISSUE TITLE
Cannot access settings on macOS

### ISSUE THREAD

**Issue by dirkhusemann** [nextcloud/desktop#2813]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

Clicking on the nextcloud menu bar icon I expect to find a way to access the nextcloud settings.

### Actual behaviour

Settings menu is not shown, only accounts are listed and menu items to access local files or remote dashboard, activities, etc.

### Steps to reproduce
1. Click on nextcloud icon in menu bar.
2.
3.

### Client configuration
Client version: 3.1.1

Operating system: macOS 11.1

OS language: English

**Comment by er-vin** [comment]
In the account menu there is a settings entry.
