### ISSUE TITLE
NC Desktop App on 10.11

### ISSUE THREAD

**Issue by tilllt** [nextcloud/desktop#2818]
### Expected behaviour
Apple has a different support and update strategy than i.e. Microsoft. You cannot install anything newer than El Capitan on certain older Macbooks, which are still very usable for most people, and very frequently found "in the wild". OTOH, the recent Nextcloud Desktop client is not available for MacOS <11.11, so "El Capitan" is not supported anymore, which is for millions of Mac users the end of the line in terms of MacOS. When installing the "Legacy" NC App on one of those older Macs, it reminds you to update to the new Version, which you cannot install on your OS.

I am not a programmer, but frankly i dont understand why a comparatively "simple" app like the NC desktop App wouldnt be able to run on El Capitan. We are not talking about Photoshop here.

In terms of sustainability and being able to continue your "dated" Macs, i would appreciate if recent Versions of the Desktop App for OSX would be released for El Capitan as well. 

### Actual behaviour
When you just click download on the NC Desktop App page, you will discover on older Macs, that the default suggested Mac App does not work on El Capitan. So you need to go there again, download the legacy app. After installing the Legacy APP, it will suggest you to Upate to the newer Version, which is not available for El Capitan.

**Comment by er-vin** [comment]
Well, El Capitan is end of life since August 2018. We're thus not supporting it anymore. I understand that might be frustrating but we're going along with the ecosystem there and it's getting impossible to do anymore. For instance we depend on Qt which dropped support for El Capitan a while ago as well.

**Comment by tilllt** [comment]
On Top of that, i am researching now for like 15min on HOW i can enter my own server into the MacOS Legacy Client. I can just just click "Register with a Provider" or "Host your own Server" Link, which leads me to the instructions to install a server (which i have already) and not to the "Manually enter account" Dialog that i would expect.

**Comment by tilllt** [comment]
> Well, El Capitan is end of life since August 2018. We're thus not supporting it anymore. I understand that might be frustrating but we're going along with the ecosystem there and it's getting impossible to do anymore. For instance we depend on Qt which dropped support for El Capitan a while ago as well.

Like i mentioned before, given the different nature of how Hardware and Software is tied together with Apple, i think this not a very user friendly decision. I can install Windows 10 on my old Windows PC if i accept that it will be slow, but i cannot install anything newer than El Capitan on my old Macbook. If you look at the Market Share of El Capitan or below, its still at 5 Percent, which is quite significant in numbers.

**Comment by tilllt** [comment]
Also, I really don't care of the Legacy client doesn't get updates anymore on the GUI side, but in my understanding there will also be no Bugfixes and enhancements for the underlying sync mechanisms, right? And thats something that probably does not rely on Qt.

**Comment by er-vin** [comment]
> Also, I really don't care of the Legacy client doesn't get updates anymore on the GUI side, but in my understanding there will also be no Bugfixes and enhancements for the underlying sync mechanisms, right? And thats something that probably does not rely on Qt.

Sure, but that'd mean maintaining 2.6 on old Qt builds which won't get security fixes even longer (and it's been stretched quite a bit already). Add to that the manpower necessary for such maintenance jobs on two quickly diverging code base. It's not affordable for us.

**Comment by tilllt** [comment]
I am not a software engineer, but wouldnt a seperation of GUI and sync backend make sense? not only for this use case, but in general? i am frankly surprised that its put together into a monolithic software.

**Comment by er-vin** [comment]
I think you're wrongly assuming Qt is only for GUI. It is not. It's in particular providing quite a bit of the features related to network access and secret management. It's rather important to have security updates on those for instance.

**Comment by tilllt** [comment]
I see your points, it's just sad that the software ecosystem is (involuntarily) supporting Apples strategy of planned obsolescence. With the release of macOS Sierra, they dropped support for a huge range of popular mac's without any actual technical reason for this, there are a lot of complaints and articles about that. You will find that somebody even wrote a Patcher that enables Sierra to run on a lot of models without problems. In my case, they dropped the support for the wireless chipset so it's not that easy to get beyond "El Capitán" unfortunately.

In any case, I don't see the option to enter a self hosted nextcloud server on the mac legacy client... Is it hidden somewhere or does the legacy mac client only connect to paid services?

**Comment by er-vin** [comment]
> I see your points, it's just sad that the software ecosystem is (involuntarily) supporting Apples strategy of planned obsolescence. With the release of macOS Sierra, they dropped support for a huge range of popular mac's without any actual technical reason for this, there are a lot of complaints and articles about that. You will find that somebody even wrote a Patcher that enables Sierra to run on a lot of models without problems. In my case, they dropped the support for the wireless chipset so it's not that easy to get beyond "El Capitán" unfortunately.

Well, this is why on a personal level I stay away from that particular ecosystem. You have to abandon too much freedom.

> In any case, I don't see the option to enter a self hosted nextcloud server on the mac legacy client... Is it hidden somewhere or does the legacy mac client only connect to paid services?

No, the feature is supposed to be there. The wizard didn't change much since 2.6.

**Comment by tilllt** [comment]
![Bildschirmfoto 2021-01-14 um 09 45 59](https://user-images.githubusercontent.com/1854364/104566877-74167a00-564e-11eb-91ff-de29c811fe1e.png)
![Bildschirmfoto 2021-01-14 um 09 45 34](https://user-images.githubusercontent.com/1854364/104566881-74af1080-564e-11eb-9f38-382eb2a03f83.png)

Thats what i get. Where is the "Manual Configuration" hidden?
