### ISSUE TITLE
Default user the client is started with

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/desktop#2820]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I think the nextcloud client does not need root privileges to run and it is sufficient when the nextcloud client is started with user privileges.

### Actual behaviour
It is started with root privileges.

I think in Ubuntus Startup Applications Preferences there should be `/usr/bin/nextcloud --background %u` instead of `/usr/bin/nextcloud --background`

### Steps to reproduce
1. Install nextcloud
2. Reboot 
3. Look at user that is running nextcloud

### Client configuration
Client version: 3.1.1

Operating system: Ubuntu 20.10

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):
```
Using Qt 5.14.2, built against Qt 5.14.2
Using Qt platform plugin 'xcb'
```

Client package (From Nextcloud or distro) (Linux only): nextcloud ppa

Installation path of client:
```shell
$ which nextcloud
/usr/bin/nextcloud
```

### Logs

I think not necessary in this case.

**Comment by er-vin** [comment]
I suspect something in the packaging or some stale startup entry created I don't know how. In our code we do nothing to try to execute as root, I'd even advise against using the client from the root user to be honest.

@ivaradi does it ring any bell? Think that can be a thing from the packaging? because clearly I don't see how the code could produce such behavior.

**Comment by ivaradi** [comment]
I cannot see how it could be started as root unless the X session runs as root. The autostart mechanism starts all applications as the user logged in to the session. The client certainly runs as my user on my machine.

Or perhaps the executable is setuid root, but it is not so in the package.

**Comment by q-wertz** [comment]
You are correct. When I start the laptop without the attached docking station nextcloud is started as user.
But with attached USB Docking station the DisplayLinkManager is running and this one is running with root privileges.
DisplayLinkManager is quite messy. I think it has to run as root.

Does it harm to make `/usr/bin/nextcloud --background %u` the default startup command?

**Comment by er-vin** [comment]
No I don't think it harms to use that command.

In any case, looks like it's really outside of our realm, so I'll close this one.

**Comment by q-wertz** [comment]
So it's not the installer that sets this startup command? :thinking:
