### ISSUE TITLE
Nextcloud Desktop Client from master silently corrupts files 

### ISSUE THREAD

**Issue by trassl** [nextcloud/desktop#2822]
Nextcloud Desktop Client silently uploads corrupt files and you won't notice (Problem 1), because the filesize is correct but checksums are not transmitted (Problem 2) and if checksums would be transmitted, they are not checked on the server side (Problem 3). I guess, file chunking is very broken on master.

Nextcloud Desktop Client from master is affected, tested with f7be923b7347556ca4d57e42b74024a5b38701f2.

Nextcloud Desktop Client from stable-3.1 is NOT affected.

(Yes, I know, this is in-development code, which should not be used in production)

This bug report is about Problem 1.

Problem 2 affects all client versions with the current stable server (tested with Nextcloud 20): the server does accounce the `checksums` capability and therefore the client does not set the `OC-Checksum` header. Feel free to open an appropriate issue for that one.

Problem 3 affects the current stable server (tested with Nextcloud 20): even if the checksums are sent by the client, the checksums are not used on the server side to verify the uploaded temporary file before moving it to the permanent storage. Feel free to open an appropriate issue for that one.

### Expected behaviour
Local file and remote file on the server have the same checksum.

### Actual behaviour
Local file and remote file on the server differ, but the client thinks all is ok.

### Steps to reproduce
**ATTENTION: DO NOT USE YOUR NORMAL ACCOUNT!**

1. BACKUP your current nextcloud client configuration directory (here: ~/.config/Nextcloud)
2. REMOVE your current nextcloud client configuration directory (here: ~/.config/Nextcloud)
3. CREATE a FRESH account on the server for testing purposes
4. Build, install and run client from master
5. Connect the client to the newly created account from 3.
6. Create a new test folder and create a reasonable sized test file (see below for a Python script)
7. Copy test file to the configured Nextcloud folder
8. Wait for the synchronization to happen
9. Compare local and remote file

### Details
This is the script I used to create the test file:
```python
# This will create and OVERWRITE a 200MB file called A.txt in the current folder
with open("A.txt", "w") as fp:
    for n in range(0, 200 // 50 * 1024 * 1024):
        fp.write("A" * 50 + "\n")
```
The test file created with my script consists of >4m lines of `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`. Each line ends with an newline (`\n`). The line length is limited to 50 chars to make it easier to diff, no other reason for that. This does not change the actual bug behaviour.

The client uploads four chunks:
```
-rw-r----- 1 1000 1000  10000000 Jan 12 00:00 0000000000000000
-rw-r----- 1 1000 1000 100000000 Jan 12 00:00 0000000000000001
-rw-r----- 1 1000 1000 100000000 Jan 12 00:00 0000000000000002
-rw-r----- 1 1000 1000   3909504 Jan 12 00:00 0000000000000003
```
Local test file sha1 is `aafefeee5203e6520aa0bf7b59e8e7129ea5353b`.

Remote test file sha1 is `f55b36a861a9f62a50e69f616f6e056ef50cda6a` (because of dynamic file chunking this may be different on another system).

This is the diff:
```
--- A.txt
+++ A.txt.server
@@ -196076,6 +196076,7 @@
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
@@ -2156859,6 +2156860,7 @@
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
@@ -4117642,10 +4117644,7 @@
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

### Cleanup
Be sure to remove the test account afterwards and restore your stable client configuration.

### Client configuration
Client version: master
Operating system: Linux

**Comment by er-vin** [comment]
Thanks a lot for testing this, QA on master is always most welcome especially with such a precise report and the necessary to easily reproduce. Makes things much easier for us.
