### ISSUE TITLE
[Question]: Crash upon launch

### ISSUE THREAD

**Issue by raghavgururajan** [nextcloud/desktop#2828]
Hello Folks!

I have built nextcloud-desktop (v3.1.1) from source. While launching the application, it crashed with the following:
```
2021-01-15 05:34:10:775 [ fatal default ]:	Could not find QtWebEngineProcess
Aborted
```

Any ideas please?

Thank you!

Regards,
RG.

**Comment by er-vin** [comment]
It looks like you got some environment issue or such. It doesn't find one of the Qt components at runtime.
