### ISSUE TITLE
Repository for Ubuntu is not keeping up-to-date

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2836]
[Suggested repository](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) for Ubuntu that is listed on your [main Client Download page](https://nextcloud.com/install/#install-clients) is notably behind on their releases, still offering 2.6.* or even 2.5.*

Wondering if it would be possible the update these repositories to ease update process for Ubuntu & Debian users waiting for proper packaging.  I see there is an appimage release, but that is not a good options for some Linux users #2564.  Thanks for considering!

**Comment by ivaradi** [comment]
The repository does provide version 3.1.1 of the client for Focal and Groovy. Unfortunately, the client cannot be compiled for older versions of Ubuntu since sometime during the 2.7 series. That is why 2.6.5 is supplied for Bionic or Xenial.
