### ISSUE TITLE
Enter E2E passphrase not accepted on Linux desktop appimage 3.1.1

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#2838]
Running version 20.0.4 with Linux Desktop appimage 3.1.1 on Ubuntu with kernel 5.4.0-62-lowlatency

E2E was enabled on a Windows desktop.  Now attempting to add same recovery words to a Linux desktop and the same recovery words simply aren't accepted.  When attempting to submit the words nothing happens.  I can keep submitting indefinitely or close the window.

**Comment by er-vin** [comment]
Could you look at the debug logs and let us know what gets in there during when you validate the dialog with the passphrase?

**Comment by sunjam** [comment]
Apologies, I simply ran into multiple issues with e2e and removed the app entirely.  If someone else encounters this, or I encounter this again in the future, I'll re-open.
