### ISSUE TITLE
Use Monochrome Icons ignored on Gnome Desktop

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/desktop#2841]
Desktop client v3.1.1 no longer shows a monochrome icon in the [Gnome AppIndicator](https://extensions.gnome.org/extension/615/appindicator-support/), even though it is turned on in the settings:

<img src="https://user-images.githubusercontent.com/476060/105055095-fd74e480-5a72-11eb-9efa-22a0d30dd69f.png" width="290" height="294"/>

**Comment by FlexW** [comment]
I couldn't reproduce this on Version 3.1.1 (Arch) in Gnome Shell 3.38.2 with AppIndicator Version 34. Do you use a custom icon theme? Because the icon in the screenshot does not look like the default one.

**Comment by mcnesium** [comment]
I do use [papirus-maia-icon-theme](https://github.com/Ste74/papirus-maia-icon-theme) (comes with Manjaro I guess), but it is no different when switching to `Adwaita (default)`, except that the icon is smaller:

<img src="https://user-images.githubusercontent.com/476060/105061607-fef5db00-5a79-11eb-981e-22500bf17ded.png" width="50%" height="50%"/>

**Comment by mcnesium** [comment]
Sorry, this is on GNOME Shell 3.38.3 and AppIndicator Version 34 as well.

**Comment by mcnesium** [comment]
I just saw that the tripple-dot icon is still white: <img src="https://user-images.githubusercontent.com/476060/105063556-251c7a80-5a7c-11eb-95bf-61f9404e98c1.png" width="50%" height="50%"/>

or is white its non-monochrome color anyway?

By the way: I do remember that the blue Info-icon has been blue in my monochrome-setting since I started using Gnome on the desktop years ago, but I ignored it because it did not distract too much because it rarely shows up.

**Comment by FlexW** [comment]
This still does not look like the default one. I did a quick test on my machine with the papirus icon theme (Papirus-Dark) and if I have it enabled the client does indeed not change the icon but I guess that has nothing to do with the client but with the icon theme not providing a different icon but I may be wrong. I'm sure @er-vin or @camilasan do know more about it.

**Comment by er-vin** [comment]
Yes indeed. On Linux the systray system can catch the icon name and override it with a themed icon. We got no control over that mechanism it's in the platform.

For instance on Plasma I got a totally different icon because there are the necessary overrides in place on that platform.

**Comment by mcnesium** [comment]
> On Linux the systray system can catch the icon name and override it with a themed icon

Thanks for clarifying. As you might have realized by now, I have no idea of how icons work in Gnome. I have scrolled through `/usr/share/icons/Papirus/` and `/usr/share/icons/Papirus-Maia` and searched for files named `*check*` but I could not find this one. Could you point me to the correct icon name, so I can fix it?

**Comment by er-vin** [comment]
I'd look for something with nextcloud in the name and/or state- in the name. This one is named "state-ok" internally.

**Comment by mcnesium** [comment]
Thanks! There has indeed been a change in the Papirus theme, which I referenced. Let's wait and see what this is about over there.

Here is quick workaround, in case other people (mostly Manjaro users, I guess) find this:

    sudo find /usr/share/icons/Papirus/ -iname '*state-ok*' -exec sed -i 's/class="ColorScheme-PositiveText"/class="ColorScheme-Text"/g' {} \;

then restart Gnome shell, e.g. by typing `Alt+F2` -> `r`
