### ISSUE TITLE
Have to enter e2e password without encryption enabled

### ISSUE THREAD

**Issue by PunkIslamist** [nextcloud/desktop#2842]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client should start, log in, and start syncing.

### Actual behaviour
A dialog pops up, asking me for an E2E passphrase. Syncing seems to work for the most part if I click 'cancel' a bunch of times, but some files do not get synced. This happens even though I never enabled E2E encryption, and do not have the E2E encryption app activated.
The status of client remains in "Waiting to start syncing."

![image](https://user-images.githubusercontent.com/26367652/105071875-70875680-5a85-11eb-9002-110c808a0a7c.png)

![image](https://user-images.githubusercontent.com/26367652/105071890-754c0a80-5a85-11eb-868c-ff456998f495.png)

![image](https://user-images.githubusercontent.com/26367652/105071900-7846fb00-5a85-11eb-915c-69e961576ad2.png)

### Steps to reproduce
Unsure. It works fine on one PC, but does not work on another. Both are using the same version of the client, connecting to the same server, using the same account. It does happen on every start of the client on the affected PC, though.

### Client configuration
Client version: 3.1.1, installed via scoop

Operating system: Windows 10 19042

OS language: English

Installation path of client: scoop folder

### Server configuration

Nextcloud version: I do not know. Using hosted version by Webo.hosting

Storage backend (external storage): I do not know

### Logs

1. Client logfile: https://gist.github.com/PunkIslamist/eccd6b03cba4653597f4bb39505f32e1
(I replaced the actual username with `username`.

2. Web server error log: Not sure how to get it, I am using a hosted instance.

3. Server logfile: nextcloud log (data/nextcloud.log): Not sure how to get it, I am using a hosted instance.

**Comment by er-vin** [comment]
I think there's a slight confusion, the dialog you're seeing is about the end to end encryption but what you're looking at in the settings on the server is the server side encryption.

End to end encryption is enabled for all accounts on the server as soon as the end to end encryption app is installed. So I think webo.hosting installed it on their servers and the first client you got connected to the account did the key generation. You can retrieve the mnemonic from that device and enter it in the second one.
