### ISSUE TITLE
Translation cut off while installaing the custom build app

### ISSUE THREAD

**Issue by mmarif4u** [nextcloud/desktop#2843]
While installing the custom build app(build with client-building) on windows, translation is cut off in this screen.

Is there some settings/ui file to edit and adjust the width of the screen OR this is built by Windows OS?

![installation-window](https://user-images.githubusercontent.com/1280585/105150362-a557e400-5b3f-11eb-89d7-11996e8f9409.png)

**Comment by er-vin** [comment]
We indeed don't have much control over this... also we're in the process of phasing out the NSIS installer in favor of the MSI one so it's not going to be fixed. Hence why I'm closing this one.
