### ISSUE TITLE
CONTRIBUTING.md links to the appstore template for reporting issues which asks for irrelevant information and doesn't ask for actual needed information

### ISSUE THREAD

**Issue by Ackis** [nextcloud/desktop#285]
When I made my first issue today I noticed that [CONTRIBUTING.md](https://github.com/nextcloud/client/blob/master/CONTRIBUTING.md) links to a [nextcloud/appstore file](https://raw.githubusercontent.com/nextcloud/appstore/master/.github/issue_template.md).

That template asks for information such as browser version, javascript errors, etc. when I don't think it's what you want for issues posted here.

**Comment by curiousDTU** [comment]
this bug is already solved please close this bug. 
Thanks..
