### ISSUE TITLE
Excessive "Remote wipe started" notifications

### ISSUE THREAD

**Issue by matrixes** [nextcloud/desktop#2852]
### Expected behaviour
If everything is ok with the subsequent sync checks after initial first sync, stop throwing up a toast/pop up notification. Make it a setting to disable specifically these types of notifications (because I _want to see_ error notification popups, not disable _all_ notifications _completely_) or at least don't show these sync pop ups per default if everything is alright.

### Actual behaviour
Excessive "Remote wipe started" notifications on Windows

### Steps to reproduce
This is drawing from memory, and that I had issues with my sign in. This is the abbreviated version:

1. Disconnect/Disassociate the client from Nextcloud
2. Sign in to Nextcloud
3. Choose an already existing local folder to sync files to
4. Choose to wipe local folder/sync from server (so you get to keep your local files)
5. A notification pops up stating "Remote wipe started"
6. Every now and then (probably when the client has done subsequent sync checks with the server and successfully performs a sync/no changes were made) the same notification pop up "Remote wipe started" show up throughout the day. This is more than a little annoying, and the message text make no sense.

### Client configuration
Client version: 3.1.1

Operating system: Windows 10

### Logs

https://gist.github.com/matrixes/e50fcb24c2c4a8b66a96cb6a77aa653f

**Comment by er-vin** [comment]
Do you have it on the server side as well? Did you try dismissing the notification in the activity list of the main window?

**Comment by camilasan** [comment]
> How do I check?

On the bell icon, next to your avatar on your Nextcloud instance:
![notifications](https://user-images.githubusercontent.com/241266/105723471-1c69ef80-5f27-11eb-9a39-026e8554d30e.png)
