### ISSUE TITLE
Build instructions inadequate for Mac (missing dependencies)

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#2856]
### Expected behaviour
Following the build instructions [README.md](https://github.com/nextcloud/desktop/blob/master/README.md), the [system requirements in the wiki](https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client), the [compilation instructions in the wiki](https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client), and [the build instructions in the manual](https://docs.nextcloud.com/desktop/3.1/building.html) should create a system environment where running `cmake ..` in `desktop/build` results in a successful Nextcloud Desktop build on Mac.

### Actual behaviour
Even after manually adding dependencies to the `PATH` and manually setting variables in the shell profile, `cmake` complains of missing dependencies. Additionally, [there is no immediately obvious way to install `inotify` on Mac](https://github.com/inotify-tools/inotify-tools/issues/11), and there is no immediately obvious way to specify `fsevents` ([the Mac equivalent of `inotify`](https://stackoverflow.com/questions/1515730/is-there-a-command-like-watch-or-inotifywait-on-the-mac)) as an alternative for building. Finally, `cmake` complains of missing package confirguration files. My output is below:
```
% cmake ..
-- Build of crashreporter disabled.
-- GIT_SHA1 6bded34856bcd59e77677b42976b56d9fe7470d3
Compiling without updater
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (INOTIFY)
  does not match the name of the calling package (INotify).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindINotify.cmake:24 (find_package_handle_standard_args)
  CMakeLists.txt:191 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
================> LIBCLOUDPROVIDERS_LIBRARY-NOTFOUND
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args`
  (LIBCLOUDPROVIDERS) does not match the name of the calling package
  (Libcloudproviders).  This can lead to problems in calling code that
  expects `find_package` result variables (e.g., `_FOUND`) to follow a
  certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindLibcloudproviders.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:202 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
CMake Error at src/CMakeLists.txt:7 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.12) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/elsiehupp/Repositories/desktop/build/CMakeFiles/CMakeOutput.log".
See also "/Users/elsiehupp/Repositories/desktop/build/CMakeFiles/CMakeError.log".
```

### Steps to reproduce
1. Install OpenSSL, QtKeychain, and Qt 5.x.x via Homebrew. (Xcode and Xcode Command Line Utilities are already installed.) Run `brew install $(brew deps owncloud-client)`.
2. Create `build` subfolder and run `cmake`.
3. Install additional dependencies that are reported missing by the `make` script (Glib, PdfLatex, and Sphinx), and link the appropriate executables in the `/usr/local/bin` and/or define system variables in the shell user profile.
4. Try running `cmake` again.
5. `cmake` reports being unable to find `INOTIFY` (there is no obvious way to correct this), `SPHINX_EXECUTABLE` (despite `sphinx/bin/searchd` being manually linked... I think this is correct?), LIBCLOUDPROVIDERS (the exact error output suggests that the letter case is mismatched in the script), and the package configuration `Qt5Config.cmake` (or similar, which does not exist on the system despite Qt5 being installed via Homebrew).
6. `make install` does not work, either. This is unsurprising, but I figured I check regardless.

### Client configuration
* Nextcloud Desktop as cloned in `git` is the latest from the default branch
* System is macOS Big Sur Version 11.1, running on Intel
* NOTE: macOS defaults to `zsh` rather than `bash`, though it can be set to use `bash`. I have left it using `zsh`.

### Logs
* [CMakeOutput.log](https://gist.github.com/elsiehupp/1ff81204715b75875500f1658db7ea69)
* [CMakeError.log](https://gist.github.com/elsiehupp/8dfa874f908451dd90a8598b95a81d24)

### Additional Notes
* Build instructions are spread over a large number of pages, and many of them are missing crucial information. For example, while some (but not all) environmental variables are listed in the [client manual](https://docs.nextcloud.com/desktop/3.1/building.html), the missing dependencies are neither present nor explained. As a more specific example, which Sphinx executable should `SPHINX_EXECUTABLE` point to? There are multiple executables in `sphinx/x.y.z/bin` to choose from, and none of them are named `sphinx`!
* In general there isn't a full list of dependencies; I had to make educated guesses on what to install via Homebrew. `brew install $(brew deps owncloud-client)` seems like it ought to install the relevant dependencies, but it doesn't.
* The manual's formatting is terrible, and the instructions are vague. What is the difference between inset monospace text and red monospace text? When there are variables mentioned in red, where do they go? It took some digging for me to find how to add things to the `PATH` and how to define variables in `~/.zshenv`. Even then, I'm not sure if I did things correctly. Some of the variables in the manual I haven't used, while other variables I've taken from the `cmake` output.
* The build instructions come across like they haven't actually been used by their authors in quite some time. Rather, they seem to have evolved over the course of years without the new versions actually being tested. Documentation should be validated just like the software itself should be validated.
* https://github.com/nextcloud/desktop/issues/1254 is about build problems on Mac, but it does not seem relevant or helpful in my situation. https://github.com/nextcloud/desktop/issues/1652 is about `LIBCLOUDPROVIDERS` but is also unhelpful.
* [This](https://cmake.org/pipermail/cmake-developers/2015-September/026567.html) is one of the few results for `SPHINX_EXECUTABLE` on the open internet, and it is not helpful, either. (There is no file named `sphinx-build` on my computer.) There are also two completely unrelated projects named `sphinx`, and it's unclear which one the `cmake` script wants.
* My purpose for building Nextcloud Desktop is to see if using the latest version of Qt 5 can help with Issue https://github.com/nextcloud/desktop/issues/2829 or Issue https://github.com/nextcloud/desktop/issues/2584.

**Comment by FlexW** [comment]
I have no Mac so I can't test but your problem is not sphinx, libcloudprovides or inotify, these are all optional and the output is just for your information. The problem is that qt5 can not be found. You may have a wrong version installed. That's the only error that is thrown (indicated by the line`CMake Error at src/CMakeLists.txt:7 (find_package):`).

**Comment by elsiehupp** [comment]
I did a quick search, and [this result](https://stackoverflow.com/questions/40081327/macos-sierra-cmake-failed-with-qt5) suggested the following:
```
build % cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
```
Which moved me past the initial error and onto another:
```
CMake Warning at src/gui/CMakeLists.txt:203 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
```
The full output:
```
% cmake .. -DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5

-- Build of crashreporter disabled.
-- GIT_SHA1 6bded34856bcd59e77677b42976b56d9fe7470d3
Compiling without updater
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (INOTIFY)
  does not match the name of the calling package (INotify).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindINotify.cmake:24 (find_package_handle_standard_args)
  CMakeLists.txt:191 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
================> LIBCLOUDPROVIDERS_LIBRARY-NOTFOUND
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args`
  (LIBCLOUDPROVIDERS) does not match the name of the calling package
  (Libcloudproviders).  This can lead to problems in calling code that
  expects `find_package` result variables (e.g., `_FOUND`) to follow a
  certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindLibcloudproviders.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:202 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
-- Using Qt 5.15.2 (/usr/local/opt/qt/bin/qmake)
-- Performing Test WITH_FPIC
-- Performing Test WITH_FPIC - Success
-- Performing Test WITH_STACK_PROTECTOR
-- Performing Test WITH_STACK_PROTECTOR - Success
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.32.3
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- Looking for argp.h
-- Looking for argp.h - not found
-- Looking for nanosleep in rt
-- Looking for nanosleep in rt - not found
-- Looking for utimes
-- Looking for utimes - found
-- Looking for lstat
-- Looking for lstat - found
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Warning at src/gui/CMakeLists.txt:203 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- OWNCLOUD_SIDEBAR_ICONS: Nextcloud: /Users/elsiehupp/Repositories/desktop/theme/colored/128-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/16-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/256-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/32-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/64-Nextcloud-sidebar.png
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- Could NOT find CMocka (missing: CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/elsiehupp/Repositories/desktop/build
```
After this I ran `make install`, and the build worked? I would still like to be able to build without errors.

This is my `.zshenv` so far:
```
export GLib2_INCLUDE_DIR=$(brew --prefix glib)/include
export GLib2_LIBRARY=$(brew --prefix glib)/lib

# export INOTIFY_INCLUDE_DIR=
# export INOTIFY_LIBRARY_DIR=

export OPENSSL_ROOT_DIR=$(brew --prefix openssl)

export PDFLATEX_EXECUTABLE=/usr/local/texlive/2020basic/bin/x86_64-darwin/pdflatex

export QT_PATH=$(brew --prefix qt5)/bin
export DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5

export SPHINX_EXECUTABLE=$(brew --prefix sphinx)/bin/indextool
```
My thought is I could add this (and the installation instructions for the various dependencies) to the Wiki and/or any other Mac build instructions in this repository once I've gotten it fully working.

Any idea about the remaining missing dependencies? The resulting application after I ran `make install` launched and created an icon in my Menu Bar, but it didn't seem to actually work...

**Comment by FlexW** [comment]
I also think it would be good to have the compile instructions just in one central place with the correct instructions.

Regarding your problem: As I said I don't own a Mac so I can't test what's going one here but a lot of things look odd to me. You're setting `brew=/usr/local/bin/brew` but then in the lower statements you don't use this variable but instead wrote out the whole path to brew. You shouldn't specify `GLib2_INCLUDE_DIR` and `Glib2_LIBRARY` on the command line. These variables should be figured out by CMake. I think the statement `export DQt5_DIR=...` is also useless you shoud specify that directly on the `cmake` command like `cmake -DQt5_Dir=...`.

You could also have a look if the file `Qt5LinguistToolsConfig.cmake` or ` qt5linguisttools-config.cmake` are located on your computer. If yes, then point CMake to the right directory with setting `CMAKE_PREFIX_PATH=/path/to/the/directory/of/these/files:$CMAKE_PREFIX_PATH`. You can set this environment variable either in your `.zshenv` or as I described above (but it's generally not a good idea to set this in `.zshenv`). If you miss these files then the library might not be installed on your computer and you need to install it first.

Regarding your slow `.zshenv` you can always write a separate script where you put all these instructions including the cmake statement. Another possibility is to specify these environment variables direct on the command line, like `QT_PATH=... cmake ...`.

Maybe someone with a Mac can help you better.

**Comment by elsiehupp** [comment]
> You're setting `brew=/usr/local/bin/brew` but then in the lower statements you don't use this variable but instead wrote out the whole path to `brew`.

I see. I removed the full path in the calls to `brew`.

> You shouldn't specify GLib2_INCLUDE_DIR and Glib2_LIBRARY on the command line. These variables should be figured out by CMake.

CMake specifically complained about not being able to find GLib2, which is why I manually defined the variables it gave me.

> I think the statement export `DQt5_DIR=...` is also useless you should specify that directly on the `cmake` command like `cmake -DQt5_Dir=....`

Again, I don't really know what I'm doing, but this apparently worked, since I've been able to run `cmake ..` with no extra options since I added that.

> You could also have a look if the file `Qt5LinguistToolsConfig.cmake` or `qt5linguisttools-config.cmake` are located on your computer.

It was hiding in the Qt folder. I added it and some other variables to my `~/.zshenv`:
```
brew=/usr/local/bin/brew

export CMOCKA_LIBRARIES=$(brew --prefix cmocka)/lib
export CMOCKA_INCLUDE_DIR=$(brew --prefix cmocka)/include

export DOXYGEN_EXECUTABLE=$(brew --prefix doxygen)/bin/doxygen

export GLib2_INCLUDE_DIR=$(brew --prefix glib)/include
export GLib2_LIBRARY=$(brew --prefix glib)/lib

# export INOTIFY_INCLUDE_DIR=
# export INOTIFY_LIBRARY_DIR=

# export LIBCLOUDPROVIDERS_INCLUDE_DIR=
# export LIBCLOUDPROVIDERS_LIBRARY=

export OPENSSL_ROOT_DIR=$(brew --prefix openssl)

export PDFLATEX_EXECUTABLE=/usr/local/texlive/2020basic/bin/x86_64-darwin/pdflatex

export QT_PATH=$(brew --prefix qt5)/bin
export Qt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
export Qt5LinguistTools_DIR=$(brew --prefix qt5)/lib/cmake/Qt5LinguistTools/

export SPHINX_EXECUTABLE=$(brew --prefix sphinx)/bin/indextool
```
(I got `CMocka` and `doxygen` from `brew`.)

Now the output from `cmake ..` looks like this:
```
build % cmake ..        
-- Build of crashreporter disabled.
-- GIT_SHA1 b8a56e0b4b8dab9353c262e7206f46570fe0a62f
Compiling without updater
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (INOTIFY)
  does not match the name of the calling package (INotify).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindINotify.cmake:24 (find_package_handle_standard_args)
  CMakeLists.txt:191 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
================> LIBCLOUDPROVIDERS_LIBRARY-NOTFOUND
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args`
  (LIBCLOUDPROVIDERS) does not match the name of the calling package
  (Libcloudproviders).  This can lead to problems in calling code that
  expects `find_package` result variables (e.g., `_FOUND`) to follow a
  certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindLibcloudproviders.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:202 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find LIBCLOUDPROVIDERS (missing: LIBCLOUDPROVIDERS_INCLUDE_DIR LIBCLOUDPROVIDERS_LIBRARY) 
-- Using Qt 5.15.2 (/usr/local/opt/qt/bin/qmake)
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- OWNCLOUD_SIDEBAR_ICONS: Nextcloud: /Users/elsiehupp/Repositories/desktop/theme/colored/128-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/16-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/256-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/32-Nextcloud-sidebar.png;/Users/elsiehupp/Repositories/desktop/theme/colored/64-Nextcloud-sidebar.png
-- Using own sqlite3 from /Users/elsiehupp/Repositories/desktop/src/3rdparty/sqlite3
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/elsiehupp/Repositories/desktop/build
```
I still don't know what the story is with `INotify` or `sphinx`, but `libcloudproviders` is apparently [downloadable from GitHub](https://github.com/juliushaertl/libcloudproviders). I don't know how to compile it after cloning the repository, though, and just pointing to the `src` and `data` folders doesn't seem to work.

> Regarding your slow `.zshenv` you can always write a separate script where you put all these instructions including the `cmake` statement. Another possibility is to specify these environment variables direct on the command line, like `QT_PATH=... cmake ....`

I realized that I can go `source <profile_file>` with pretty much any text file, so I could move the relevant bits of `.zshenv` into a new file for building. But writing a shell script that does everything all at once seems ideal, especially if it can be integrated with the repository and the Mac build instructions.

**Comment by FlexW** [comment]
`libcloudproviders` can just be used on Linux and especially GNOME it's not important for you. Sphinx is just for generating documentation. INotify is also not important for you.

> I realized that I can go source <profile_file> with pretty much any text file, so I could move the relevant bits of .zshenv into a new file for building. But writing a shell script that does everything all at once seems ideal, especially if it can be integrated with the repository and the Mac build instructions.

The whole point of CMake is that you don't need to set these variables by hand. This should be figured out by CMake if it's configured properly.

**Comment by elsiehupp** [comment]
> EDIT:
Maybe the CMake scripts must be improved for Mac.

💁‍♀️

**Comment by elsiehupp** [comment]
I'm closing this because it's essentially a messier duplicate of #2893 now.
