### ISSUE TITLE
Desktop Client status feedback to server 

### ISSUE THREAD

**Issue by hanscomps** [nextcloud/desktop#286]
Add selectable option to supply client sync status and errors per user to the server back-end. 
This will help administrators audit what are being synced and what system wide sync issues are that users are experiencing.
This will require Client feature and Server application.

The status variables can include (all selectable):
    Client version
    Last successful full sync (date-time)
    Sync errors experienced (with simple filter)
    ...more?

**Comment by camilasan** [comment]
Wouldn't the admin_audit app solve this?
https://docs.nextcloud.com/server/20/admin_manual/configuration_server/logging_configuration.html

**Comment by joshtrichards** [comment]
nextcloud/server#40160
