### ISSUE TITLE
Client ask for Update again and again, even though it is already updated

### ISSUE THREAD

**Issue by lwt-pressy** [nextcloud/desktop#2861]
### Expected behaviour

The update request comes once when a new version is published.

### Actual behaviour

Each first start after reboot the nc client shows "A new update for Nextcloud ..." and wants to open the installer. 

![nc1](https://user-images.githubusercontent.com/13365281/105627875-aa67ac80-5e39-11eb-8da9-361805b40e71.PNG)

Even though the new Version is already installed.
![nc2](https://user-images.githubusercontent.com/13365281/105627889-b94e5f00-5e39-11eb-92ab-675dad3198bd.PNG)

I also verified it with checking the version through the "prüfen" button.

### Steps to reproduce
1. activate "Automatisch auf Aktualisierungen prüfen"

### Client configuration
Client version: 3.1.1.

Operating system:
Windows 10 Pro - 20H2 (all updates applied)

OS language:

German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

Default

### Workaround

a) Abort the Installation and start  the client a second time, then it will not ask for an update.
b) Disable automatic checks for update

**Comment by er-vin** [comment]
Could you provide us with debug logs? This can be done with the "Create Debug Archive" button.
