### ISSUE TITLE
The program is constantly crashing

### ISSUE THREAD

**Issue by Fastereus** [nextcloud/desktop#2862]
Client application version 3.1.1 Win Crashes constantly, while other computers have no problem.
the previous version worked without problems.
last lines from LOG:
[20210123_1106_owncloud.log.0.txt](https://github.com/nextcloud/server/files/5859339/20210123_1106_owncloud.log.0.txt)

**Comment by er-vin** [comment]
This journal database is somehow incompatible with 3.1.1. Did you use the owncloud client with that folder by any chance?

You can workaround this by removing the corresponding index from your db file using the sqlite command line tool (or similar). Nothing we can do about it from the code.
