### ISSUE TITLE
Error while accessing token-endpoint on latest Client Versions [Windows/Ubuntu]

### ISSUE THREAD

**Issue by malbreitenbach** [nextcloud/desktop#2883]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When using Desktop Client for Windows or Ubuntu the login and connection to the working Nextcloud Server should work with the latest Desktop Client Version and latest Nextcloud Server Version.

### Actual behaviour
After typing servers URL the following Error Message occurs:
German: 
Fehler beim Zugriff auf den 'Token'-Endpunkt:
Error transferring _https://MyURL.com/index.php/login/v2_ - server replied: Forbidden

English (translated):
Error while accessing token-endpoint:
Error transferring _https://MyURL.com/index.php/login/v2_ - server replied: Forbidden

The Error just occurs while using Nextcloud Client V3.x.x (Windows), V3.x.x (Ubuntu). 
The login is working properly on Nextcloud Client V2.6.x (Windows) using the exact same procedure and same nextcloud server.
The login is also working using the Android Client.

### Steps to reproduce
1. Open Nextcloud Client V3.x.x on Windows10 / Ubuntu
2. Add User/Account (translated)
3. Login to nextcloud (translated)
4. Typing valid server URL (https://myURL.com)
5. Continue
6. Error occurs

### Client configuration
Client version:
Not Working: 3.1.1 (Ubuntu) [3.1.1-20210122.180059.75c329f4f-1.0~focal1], 3.1.1 (Windows)
Working: 2.6.5 (Windows)

Operating system:
Windows 10, Ubuntu 20.04.1 LTS (both testet, same error)

OS language:
German

Client package (From Nextcloud or distro) (Linux only):
`ppa:nextcloud-devs/client`

Installation path of client:
Default installation by `apt install caja-nextcloud`

### Server configuration
PHP 7.3

Nextcloud version:
20.0.6

Storage backend (external storage):
Default

### Logs

1. Client logfile: 
https://gist.github.com/malbreitenbach/092d1de68b18c3d06ee16a39c295b2e6

2. Web server error log:
Empty PHP Log

3. Server logfile: nextcloud log (data/nextcloud.log):
https://gist.github.com/malbreitenbach/7e2fa2599046be1d5a5c0f6fdff10df8

### Workaround
1. Install Client Version 2.6.5
2. Perfom the login (works for me without any problem)
3. After logging in successfully, update the client to the latest version
4. The client should now work properly

**Comment by FlexW** [comment]
Can you reproduce this error with an example account from try.nextcloud.com

**Comment by malbreitenbach** [comment]
Hallo @FlexW,
Connecting to "https://demo1.nextcloud.com" seems to work properly using the latest Client 3.1.1 (Ubuntu). 
In addition to that I tried manually to pull the authentication by
`curl -X POST https://myURL.com/index.php/login/v2`, which returns
`{"poll":
{"token":"tCyB_[...]_Rtg","endpoint":"https:\/\/myURL.com\/index.php\/login\/v2\/poll"},
"login":"https:\/\/myURL.com\/index.php\/login\/v2\/flow\/60r_[...]_c9Y"}`
which seems to be as expected.

Thanks for the good work btw!

**Comment by malbreitenbach** [comment]
Is any more information I can provide? Meanwhile I also tested on Version 3.1.2 (Ubuntu). Error is persisting.

**Comment by salzamt** [comment]
still broken

**Comment by FlexW** [comment]
@salzamt @malbreitenbach I'm not sure that is really a bug. If it works with the demo server, than it's probably a server configuration issue.

**Comment by digitalfreak85** [comment]
Same issue here.
Ubuntu 20.04. Default installation nothing special.
Works with iOS and Android App. Also Webfrontend works. But with the Desktop Client it is the same Problem.

**Comment by gabrix73** [comment]
Same issue here:
LMDE 6 Faye
#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

**Comment by 7HE-W0R1D** [comment]
In the latest windows desktop  3.15.3 I'm getting this error as well but if I go back and retype the url, it brings up the login page even though the error displays. I'm using centos10 in a Fedora server VM.
