### ISSUE TITLE
desktop client sometimes skips torproxy

### ISSUE THREAD

**Issue by merkleID** [nextcloud/desktop#2887]
Operating system: BigSur
OS language: English
DesktopClient: latest
torproxy: docker dperson/torproxy:latest
method: http
nextcloud server: Ubuntu snap:latest

Hi,
tailing the logs on my nextcloud server, I found this:

tail -f /var/snap/nextcloud/current/logs/apache_access.log

162.247.74.204 - - [31/Jan/2021:23:31:54 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:31:57 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 1027 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:32:15 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:32:26 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:32:26 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:32:27 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 1027 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:32:34 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:32:47 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:32:58 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:33:27 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:33:30 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 1039 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:33:30 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 293 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:33:57 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:33:58 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 291 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:02 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 1039 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:02 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 293 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:27 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:34 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:34 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:34:58 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:35:06 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
162.247.74.204 - - [31/Jan/2021:23:35:06 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:35:28 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:35:38 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:35:38 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:35:58 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:10 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:10 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:27 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:42 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:42 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:36:57 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:14 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:14 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:28 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:46 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:46 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:37:57 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:38:01 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:38:16 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:38:18 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:38:18 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:38:27 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
[MyREDACTEDip] - - [31/Jan/2021:23:38:31 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4193 "-" "Mozilla/5.0 (Macintosh) mirall/3.1.1git (build 4316) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:38:50 +0100] "PROPFIND /remote.php/dav/files/luca/ HTTP/1.1" 207 4205 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"
107.189.10.251 - - [31/Jan/2021:23:38:50 +0100] "GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 3459 "-" "Mozilla/5.0 (Macintosh) mirall/3.0.3git (build 3799) (Nextcloud)"

107.189.10.251 and 162.247.74.204 are Tor Exit Relay, [MyREDACTEDip] is my static ip address.

I don't why, but even if I did set a proxy in my desktop client, and it works, sometimes it skips the proxy and goes directly to the server (it's when the log says [MyREDACTEDip]).

EDIT: it happens also using SOCKS5 as method.

Thank you,
Luca

**Comment by er-vin** [comment]
How is the proxy set in your config file? Do you force the torproxy in there? Or is it set as system proxy?

I'm asking because if it is set as system proxy we might not be able to do much about it, it could be some policy inside macOS which decides the system proxy is available or not and changes it on the fly.

**Comment by merkleID** [comment]
> How is the proxy set in your config file? Do you force the torproxy in there? Or is it set as system proxy?
> 
> I'm asking because if it is set as system proxy we might not be able to do much about it, it could be some policy inside macOS which decides the system proxy is available or not and changes it on the fly.

manual setting of proxy

**Comment by er-vin** [comment]
OK, thanks for the information. Not quite sure why it'd do this. Could you provide us with client debug logs to see what it says about the proxy? On 3.1 or later it is about clicking the "Create Debug Archive" button in the settings dialog.
