### ISSUE TITLE
Nextcloud client creating new sync folder

### ISSUE THREAD

**Issue by TerryHewitt** [nextcloud/desktop#2896]
### Steps to reproduce
1. Start nextcloud client
2. bring up settings page
3. ANOTHER sync of  J:\SPS  is created

It appears to work correctly even with the multiple copies of sync

### Expected behaviour
Nextcloud doesn't create additional Folder Sync Connections

### Actual behaviour
Each time I start Nextcloud client (3.1.2) on Windows 10 it creates another copy of the folder I have requested to sync
I delete the redundant syncs, but next time I start the client again they re-appear.
This is also happening with the Photography account.
![image_2021-01-31_164738](https://user-images.githubusercontent.com/15708659/106391189-06a37100-63e4-11eb-9625-fd3079e26400.png)

### Server configuration

**Operating system:**
Ubuntu 20.04.1
**Web server:**
nginx 1.18.0

**Database:**
mariadb
**PHP version:**
7.4 
**Nextcloud version:** (see Nextcloud admin page)
20.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.3 
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - analytics: 3.2.0
  - appointments: 1.7.15
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.3
  - external: 3.7.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - gpxedit: 0.0.13
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.4
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - phonetrack: 0.6.5
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_facebook: 2.1.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - cms_pico
  - encryption
  - issuetemplate
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.wthassociates.com",
           "***removed sensitive values**********",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "maintenance": false,
        "debug": false,
        "loglevel": 1,
        "data-fingerprint": "d37bd8a6753bffcfd9fb1077ec46df42",
        "updatechecker": true,
        "updater.release.channel": "stable",
        "rewrite_url": true,
        "overwrite.cli.url": "https:\/\/nextcloud.wthassociates.com",
        "app_install_overwrite": [
            "files_markdown",
            "announcementcenter",
            "audioplayer",
            "calendar",
            "deck",
            "external",
            "gpxedit",
            "gpxmotion",
            "gpxpod",
            "files_mindmap",
            "phonetrack",
            "cms_pico",
            "spreed",
            "camerarawpreviews",
            "user_external"
        ],
        "mysql.utf8mb4": true
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
**Browser:**
Opera
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing obviously related to the error
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing obviously related to the error
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No browser log available
```
</details>

**Comment by er-vin** [comment]
How odd... This only happens with two accounts but not the other ones?

**Comment by TerryHewitt** [comment]
Kevin

Correct. Only two of the accounts.

Best wishes
Terry

**Comment by er-vin** [comment]
Could you try to run a setup with only one of the affected accounts? See if that reproduces the issue and if yes provide us with logs? (using the Create Debug Archive button in the settings dialog)

Right now without logs I have no good idea about what could cause this...

**Comment by TerryHewitt** [comment]
Kevin

Yes. Will try that later today.
I will make a copy of nextcloud. Cfg
And edit out the accounts to leave only one.

I will let you have the results later today.

I might add I did try and edit out the repeated folders in the nextcloud. Cfg but they still reappeared when starting nextcloud client.

Best wishes
Terry

Best wishes
Terry

________________________________

**Comment by TerryHewitt** [comment]
Kevin,

 

Not sure I’m able to do exactly what you need…

 

Can I remind you that along the way I have tried editing the nextcloud.cfg to take out the replicated folders!

 

So Nexctloud client is running and  I have removed the replicated folder sync connections.

Then I have clicked  create debug archive to produce Nextcloud-One.zip

 

Then I exit Nextcloud.

I restart Nextcloud and I get two extra copies of SPS J:\SPS

And one extra copy of Photography  I:\Photography

Then I have clicked create debug archive again to produce Nextcloud-Two.zip

 

Does that give you anything to go on?

I’m a bit nervous of editing nextcloud.cfg to get rid of all the other accounts properly and in such a way so that when  I put them all back in it doesn’t go and copy 3TB of data!

 

If you wanted to edit the nextcloud.cfg I would be happy to use that one if it would help.

 

Of course anything else needed I will try and do.

 

Links to the two zip files.

 

https://nextcloud.wthassociates.com/s/5ox9P36tfGH82Br

 

password is 123Nextcloud

 

Best wishes

 

Terry

 

Professor W T Hewitt

WTH Associates Ltd

 

Telephone: +44 7905 759 003

 

Company registration number:7336226

HMRC VAT Registration number: 998 8457 23

 

Company Registered Address

St George's House  | 215 - 219 Chester Road | Manchester | M15 4JE

**Comment by er-vin** [comment]
The plot thickens... Couldn't find anything in the logs, but the accounts with the issue have something in common, they all have a folder for which the journal database has not been migrated. Honestly I fail to see how that could happen especially in that way.

I'll give you a possible workaround though so that you can at least try to get things to behave properly:
 * Quit the desktop client
 * Open your nextcloud.cfg and find the journalPath entries which have an absolute path in them (starting with C:/), in what you provided I found two of them (which seems to match your description)
 * For those two, move the corresponding db file out of where they are and put them in the corresponding sync folder instead (so one will go in I:\Photography the other one in J:\SPS), be very careful at that step, don't mix them up!!!
 * Then edit the journalPath entries to keep only the "._sync_xxxx.db" part, drop the rest of the path
 * Start the desktop client again

I would expect this would get you back on track.

I wonder what the root cause is but I don't think we'll be able to find it, clearly happen too long in the past and we won't have the information to replay it.

**Comment by TerryHewitt** [comment]
Kevin,

 

First of all thanks for your help on this strange bug. It is much appreciated.

 

Well,

 

I stopped Nextcloud client

 

Went to do the edits you suggested and

The .db  files were already in the correct place (I:\Photography and J:\SPS).

 

There was what was obviously an old one in  C:/Users/hewitt/AppData/Roaming/Nextcloud/ - which I renamed. (old date and small compared to other).

 

I edited out the  C:/Users/hewitt/AppData/Roaming/Nextcloud/from  the JournalPath

 

I edited out the replicated folders

 

e.g., 1/Folders/311/*

and 1/Folders/3111/*

and similarly for 4/Folders/*

saved the file

 

Started Nextcloud and no change, still replicating the folders, and when I look at nextcloud.cfg It’s put back the C:/Users/hewitt/AppData/Roaming/Nextcloud/ in the journal path, even though the .db files aren’t there.

Did it again, and it looks like I’ve fixed SPS J:\SPS

 

But photography still  replicating itself.

And a few seconds after startup it modifies the nextcloud.cfg!

 

The one  I edited and the one that nextcloud reads at start up attached as “nextcloud – Edited.cfg”

The one Nextcloud creates After  startup is attached as nextcloud.cfg

 

I deleted these lines from nextcloud.cfg – which I think are the 2nd copy of I;\Photography that is being included

Restarted nextcloud.cfg and within a few seconds they are added to the nextcloud.cfg file!

And of course  giving m two copies of the folder.

 

1\Folders\31\localPath=I:/Photography/

1\Folders\31\journalPath=._sync_df3887dece75.db

1\Folders\31\targetPath=/Photography

1\Folders\31\paused=false

1\Folders\31\ignoreHiddenFiles=true

1\Folders\31\navigationPaneClsid=@Variant(\0\0\0\x1e\xe\x8a\x91\x13\x3\xb2OZ\x8b\xc3\x38\xe0\xd8\xec!W)

 

 

Anything else I can try/do?

 

Best wishes

 

Terry

 

Professor W T Hewitt

WTH Associates Ltd

 

Telephone: +44 7905 759 003

 

Company registration number:7336226

HMRC VAT Registration number: 998 8457 23

 

Company Registered Address

St George's House  | 215 - 219 Chester Road | Manchester | M15 4JE

**Comment by er-vin** [comment]
I'm sorry I'm out of ideas... I'm even more surprised it'd fix it for one but not the other. You sure you didn't miss one of the duplicates or something like that?

Worst case scenario you could remove the photography account completely and recreate it from scratch... I understand this isn't very satisfying though.

**Comment by TerryHewitt** [comment]
Kevin

Thanks for the help.  As it working OK with both copies I think I'll leave it as it is until I have time to delete/add photography or it starts happening again.

Again your support is much appreciated.

If I fix it I'll let you know what I did!

Best wishes
Terry

Best wishes
Terry

________________________________
