### ISSUE TITLE
Nothing happens after app installation on macOS

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#2899]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After installation, it would be nice to automatically start the app so that:
- When you don’t have any accounts/folders configured from before, the "Add Nextcloud account" dialog is shown
- When you do have accounts/folders configured, the tray app starts, and could even show the open tray menu if possible?

### Actual behaviour
After the app is installed, nothing happens and you need to manually open it via spotlight or applications.

### Client configuration
Client version: 3.1.1

Operating system: macOS Big Sur (11.2.1)

OS language: German

**Comment by camilasan** [comment]
> macOS

Which macOS? :)

**Comment by camilasan** [comment]
*sigh* 
I could reproduce it on mac OS Catalina.

**Comment by jancborchardt** [comment]
Sorry @camilasan – it was the latest at time of the comment, Big Sur. :) Added it to the issue text.
