### ISSUE TITLE
Add in-line reply functionality to notifications from Nextcloud Talk

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/desktop#2908]
Other communication apps support this, and it's amazingly useful because it saves you from having to open Talk in a browser tab from the notification. Might only save a few seconds, but it makes all the difference.

**Comment by jancborchardt** [comment]
@HammyHavoc yes, great point! :) Do you have some screenshots on how this looks like for other apps on Windows in your case (and maybe also macOS if this exists)? Thanks!

**Comment by HammyHavoc** [comment]
Here's an example of it on Windows: https://www.thurrott.com/windows/windows-10/210903/your-phones-android-notification-syncing-now-supports-inline-replies

Here's a macOS example: https://github.com/sindresorhus/caprine/issues/298#issuecomment-354345143

Stay well! :- )

**Comment by camilasan** [comment]
What I actually have in mind is much more simple, it is without integration with the OS - that makes it much more complex to maintain it for the 3 platforms. I would do a widget for the reply. What do you think @jancborchardt @tobiasKaminsky?

**Comment by jancborchardt** [comment]
@camilasan by widget you mean that it could show directly in the tray modal? Maybe sort of like this mockup: https://github.com/nextcloud/notifications/issues/637 – that would definitely be nice. :)

**Comment by camilasan** [comment]
> by widget you mean that it could show directly in the tray modal?

yes, in head that is how it would work :) I need to check if I can do exactly like it.

**Comment by HammyHavoc** [comment]
> 
> 
> What I actually have in mind is much more simple, it is without integration with the OS - that makes it much more complex to maintain it for the 3 platforms. I would do a widget for the reply. What do you think @jancborchardt @tobiasKaminsky?

Native integration is obviously preferred; having notifications appear on an OS where notifications are expected to appear makes more sense than hiding them in a tray icon where users aren't likely to look if they're not expecting to find them there.

**Comment by nickvergessen** [comment]
As discussed the missing message id will be added to the `objectId` field of the notification.
Currently it is `conversationToken` and in the future it will be `conversationToken/messageId` with messageId being a bigint and conversationToken being a string like before.
