### ISSUE TITLE
[Feature Request] Add similar file sync option as OneDrive and iCloud - "Always available offline"

### ISSUE THREAD

**Issue by swartzlib7** [nextcloud/desktop#2910]
I am in the process of completely migrating away from Google, Apple and Microsoft in both a personal and business capacity. I use Nextcloud and I really enjoy and love it. Thank you for this awesome product!

I have checked all issues here for what I am requesting and hopefully this is something new and valuable. I am a software engineer and am planning to get involved with NextCloud in the mid term future.

**OS**
I use Clear Linux, Ubuntu and Windows 10 daily.

**Feature**
There is one feature that will make the sync feature a rock solid experience in contrast to the mentioned companies above.
To have a similar file context menu sync option such as "Always available offline" (or similar wording). This can be used to set a file property to control whether the sync app creates a "ghost" file or pulls over the actual file from the server.

**Benefits**
This will enable better management of local file storage and allow a full view of the files using the local file system without taking up actual disk space.

**Current work-around**
Right now I have to jockey the sync settings to get the desired files synced to my computer as I manage my file server from multiple devices. I also have to use the web or WebDav interface just to get a complete view of the entire file system structure.

I'm not sure if there are any Microsoft Windows licencing issues with something like this, but I doubt it and this will be absolutely fantastic to have!

Thank you
Stephen

**Comment by Derkades** [comment]
Doesn't this exactly describe the new virtual filesystem feature? Are you aware of this feature? Are you proposing any changes or additions to it?

![image](https://user-images.githubusercontent.com/15892014/108129687-cd8b2200-70ae-11eb-92e9-ac9c22bcbd4c.png)
