### ISSUE TITLE
The client has deleted data on the server instead of synchronizing it. 

### ISSUE THREAD

**Issue by IMEIICCID** [nextcloud/desktop#2913]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Due to a mistake I destroyed my MacOSX System :-(
Luckily I had a Time Machine Backup :-)

This backup was a couple of weeks old and with it I could restore my system to 100%.
Bad News!  The Nextcloud Client did delete files on the server, which where not in the client directory (MacOSX) ,
instead of sync this files.

### Expected behaviour
The client should syncronize all existing data on the server to the client.

### Actual behaviour

The client has deleted data on the server instead of synchronizing it. 

### Steps to reproduce
1. Restore a MacOS System from a Time Machine Backup than you will see the mess
2. The sync folder in the Time Machine backup should have fewer folders than the current one on the server.

### Client configuration
Client version: Nextcloud Desktop-Client Version 3.1.0

Operating system:

OS language: MacOSX 10.12.6 Sierra

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: Standard

### Server configuration

Nextcloud version: Synology Server Nextcloud 20.0.4.

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

https://www.dropbox.com/s/bdlrwg5j5au0jhg/client.zip?dl=0

Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log): https://www.dropbox.com/s/d0x0ak3ccsiapnd/server-nextcloud.log?dl=0

**Comment by camilasan** [comment]
I am sorry that this has happened. 
I will check the logs.
