### ISSUE TITLE
nextcloudcmd --exclude does not support a hierarchy of directories

### ISSUE THREAD

**Issue by molok** [nextcloud/desktop#2916]
If the server has these directories

    /root/2021/0101/
    /root/2021/0102/
    /root/2020/0101/
    /root/2020/0102/

there is no way to exclude syncing the directory /root/2021/0101/ using nextcloudcmd

**Comment by camilasan** [comment]
Please, follow the **issue template**.
We can't help you without more information: which desktop client version are you running? do you get an error when running nextcloudcmd? steps to reproduce the error?

After checking if there isn't another similar issue open, re-open the issue once you can provide the full report.

**Comment by molok** [comment]
### Expected behaviour
I expect to be able to choose which folders to sync using nextcloudcmd

### Actual behaviour
The --exclude option takes a file containing the files/folders to exclude from the sync, there is exactly ZERO documentation on its format, by trial and error I found out that I can only exclude folders by their own name but I can not exclude a subdirectory unless it has a unique name in the whole repository.


### Steps to reproduce
1. have a repository with the following folders
    a/foo
    b/foo
2. create an exclude.lst containing
    /a/foo
    /a/foo/
    a/foo
    a/foo/
3. `nextcloudcmd -u user -p pass --exclude exclude.lst https://myrepo.com/remote.php/webdav`
4. watch nextcloudcmd sync the `a/foo` folder

### Client configuration
Client version:
Nextcloud version 2.6.2-1build1
Using 'OpenSSL 1.1.1f  31 Mar 2020'

Operating system: Ubuntu 20.04.2 LTS

OS language: US/English

Qt version used by client package (Linux only, see also Settings dialog): Using Qt 5.12.8, built against Qt 5.12.5

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop-cmd/focal,now 2.6.2-1build1 amd64 [installed]

Installation path of client: /usr/bin/nextcloudcmd

**Comment by Bravehartk2** [comment]
Ist there any chance someone has answer to this question or a link to a details doc about filtering the synchronisation on cli as it is possible via GUI?

**Comment by recolic** [comment]
Same issue. I have the following directory on Nextcloud server:

```
/InstantUpload/**
```

And I tried `nextcloudcmd --exclude /InstantUpload`,  `nextcloudcmd --exclude /InstantUpload`. Neither works.

**Comment by archont00** [comment]
Although this issue got closed, the `--exclude filename` option still does not work as expected.

My objective is to exclude any path, which contains `.dtrash` folder name (used by digiKam as local Wastebin for each photo collection; I have multiple collections located like `Photos/Camera/.dtrash`, or `Sync/Central/.dtrash`). I use systemd user timer, which calls a script in `$HOME/.config/nextcloudcmd/cloud-sync.sh`. The binary called by script is `/usr/bin/nextcloudcmd`.

My findings:
- Adding the line with `].dtrash` to `/etc/Nextcloud/sync-exclude.lst` always works (installed by package).
- Adding the line with `].dtrash` to `$HOME/.config/Nextcloud/sync-exclude.lst` always works (created by GUI client).
- Adding the line with `].dtrash` to  `$HOME/.config/nextcloudcmd/sync-exclude-files.lst` and using the option **`--exclude $HOME/.config/nextcloudcmd/sync-exclude-files.lst`** never works.
- However, adding the line with `].dtrash` to `$HOME/.config/nextcloudcmd/sync-exclude.lst` and using the option **`--exclude $HOME/.config/nextcloudcmd/sync-exclude.lst` works**

It seems that the `--exclude` option requires the file name to be `sync-exclude.lst` and nothing else... Hope it helps other users!
