### ISSUE TITLE
Feature : add a password validation when changing config on the client

### ISSUE THREAD

**Issue by GLLM** [nextcloud/desktop#292]
Hi all !

I have a feature request : I'd like to be able to add a password/PIN so that the user is only able to change the sync'ed folder & settings once he entered it.

Usecase :
I hae a NC server with different clients running (Android a PCs).
One of those PC is my work computer, on which I only sync 1 (one) specific folder.
I'd like to be able to prevent the setup modification (i.e. the sync'ed folders) so that one person using my PC with another login (admin, for instance, who could gain access to my files) cannot play and setup another folder to sync and find out about my personal files.

Maybe inputting the user NC password before validating any changes in the client setup could be fine !

Thanks
G_LL_M

**Comment by torrbox** [comment]
You can always create a new user and share the folder with your regular user, which is what I have been doing.  I mean.. wouldn't an admin be able to read the stored password anyway? Or does Nextcloud not store passwords, but does token/hash magic or whatever?

**Comment by GLLM** [comment]
Hi @torrbox  
I think you misunderstood me ... I want the sysadmin of my company computer to be prevented from adding another sync folder in NC wwindows client .... or anyone here who would sneak, in case I've not locked my PC.

Its has nothing to do with NC users/accounts :-)

**Comment by juliushaertl** [comment]
This won't stop your sysadmin from changing stuff by accessing the config manually. If someone has control over your system, there is not much the Nextcloud client could do about, to protect from that.

**Comment by GLLM** [comment]
Fair enough :)
