### ISSUE TITLE
Invisible main dialogue on Windows 10 Home w. 3.1.2stable-Win64

### ISSUE THREAD

**Issue by rokkitlawnchair** [nextcloud/desktop#2923]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The main dialogue gets displayed after clicking the "nextcloud desktop client" **tray icon**.

### Actual behaviour
The main dialogue and its sub menus are not visible but still reacting to input by mouse clicks and showing tool tips on mouse hoover. The **task list icon** appears and indicates that the main dialogue is displayed and has the focus.

I am experiencing this issue on three Windows Clients (all with identical hardware, OS and patches, installed software packages).

[screenshot](https://ignion.net/s/omyNG5ifyGYzT9n)

### Steps to reproduce
1. leftclick the tray icon

### Client configuration
Client version: 

Version 3.1.2stable-Win64 (build 20210128) git-Revision [939826](https://github.com/nextcloud/desktop/commit/9398260fb3742212fb98ee4c2b35c20b45dd9b6d), Qt 5.12.9, OpenSSL 1.1.1g  21 Apr 2020

Operating system:
Windows 10 Home
20H2
Windows Feature Experience Pack: 120.2212.551.0

OS language:
German

Installation path of client:
C:\Program Files (x86)\Nextcloud

### Logs
I haven't found any log entries related to GUI interaction between the nextcloud desktop client and Windows. Logging is activated - I can provide the logs if necessary.

**Comment by rokkitlawnchair** [comment]
might be the same issue as [# 2795](https://github.com/nextcloud/desktop/issues/2795)

**Comment by PCCV** [comment]
I get exactly the same behavior on Linux with Nextcloud 3.1.6 and 3.3.6 on Opensuse 15.3 (XFCE 4.16 - kernel 5.3.18 - Nvidia 470.86) but only after resuming from standby or hibernate. 
- On a reboot, Nextcloud works as expected, if I hibernate and resume, this behavior appear. 
- After resuming, if I close Nextcloud and re-open it, the window is displayed correctly but if I hibernate and resume, this behavior come back. 
- On the workspace switcher, we can see the window opened, but it is invisible on the desktop.
- On the space shown by the workspace switcher, we can get tooltips from mouse hoover and I can click to obtain the good reaction.

I found the same description in #2795 on windows 8.1
May be the same that #2764 on Ubuntu 20.10, but he didn't describe mouse behavior.
