### ISSUE TITLE
[QUESTION]: How to use packaged versions of 3rdpary?

### ISSUE THREAD

**Issue by raghavgururajan** [nextcloud/desktop#2929]
Hello Folks!

I am in an unique situation. I am currently packaging nextcloud-client (desktop) for [GNU Guix](https://guix.gnu.org).

While building this client, is it possible to use packaged version of 3rdparty dependencies, instead of using files under `src/3rdparty`? By packaged version, I mean package available in the distribution.

Thank you!

Regards,
RG.

**Comment by FlexW** [comment]
As far as I'm concerned the build system uses automatically the system provided sqlite package if you compile on a Linux system, but you can not use the system dependencies for the the other packages. 

Is there any reason why you want to use the system packages for that? Maybe you can prove me wrong but most of the libraries in 3rdparty are not available as packages from distributions I think.

**Comment by raghavgururajan** [comment]
> As far as I'm concerned the build system uses automatically the system provided sqlite package if you compile on a Linux system, but you can not use the system dependencies for the the other packages.

I see.

> Is there any reason why you want to use the system packages for that? Maybe you can prove me wrong but most of the libraries in 3rdparty are not available as packages from distributions I think.

Yes, I currently do not have those dependencies as system packages. But I am planning to package them as well, if possible. It appears kmessagewidget is part of KDE-Core. Some others are found to be part of [qt-solutions](https://github.com/qtproject/qt-solutions).

**Comment by FlexW** [comment]
@er-vin @camilasan Do you know why we are not using the system dependencies if they are there? Do these packages need to stay at a pinned version?

**Comment by nicolasfella** [comment]
kmessagewidget is part of https://invent.kde.org/frameworks/kwidgetsaddons, but I don't know how nextcloud's copy compares to the current upstream one. I guess the intention behind the local copy is to avoid depending on the whole kwidgetsaddons module for just one class

**Comment by er-vin** [comment]
> kmessagewidget is part of https://invent.kde.org/frameworks/kwidgetsaddons, but I don't know how nextcloud's copy compares to the current upstream one. I guess the intention behind the local copy is to avoid depending on the whole kwidgetsaddons module for just one class

Yep, that's the explanation behind that copy.

**Comment by raghavgururajan** [comment]
> > kmessagewidget is part of https://invent.kde.org/frameworks/kwidgetsaddons, but I don't know how nextcloud's copy compares to the current upstream one. I guess the intention behind the local copy is to avoid depending on the whole kwidgetsaddons module for just one class
@er-vin 

> Yep, that's the explanation behind that copy.

I see. How about for QtLockedFile and QtSingleApplication?

**Comment by er-vin** [comment]
> @er-vin
> 
> > Yep, that's the explanation behind that copy.
> 
> I see. How about for QtLockedFile and QtSingleApplication?

Those are never packaged in distros AFAIK, not only they're feeble dependencies on other platforms like windows or mac.

**Comment by raghavgururajan** [comment]
@FlexW @nicolasfella @er-vin @elsiehupp 

I finally managed to do the following:
1. Package QtSolutions (https://guix.gnu.org/en/packages/qtsolutions-0-53.9568abd/).
2. Package Nextcloud Desktop (https://guix.gnu.org/en/packages/nextcloud-client-3.1.3/), with patching source to use KMessageWidget from KWidgetAddons and to use QtLockedFile+QtSingleApplication from QtSolutions.
