### ISSUE TITLE
Improve translations in German

### ISSUE THREAD

**Issue by andreas-aeschlimann** [nextcloud/desktop#2930]
The desktop client has several phrases containing `remote`. It created a lot of confusion with our clients using the client because of the German translation.

**Example:**

`Checking for changes in remote directory` is translated as `nach Änderungen in entfernten Ordnern suchen`.

The problem is that `remote` is translated as `entfernt`. Without having a good context, this may be understood as `deleted` (delete = entfernen, deleted = entfernt).

**Suggestion to prevent ambiguousness:**

I suggest to change the phrasing or use another word for `remote`.

`Checking for changes in remote directory` is translated as `nach Änderungen in Ordnern auf dem Server suchen`.

**Comment by Id3aFly** [comment]
I haven't noticed this phrase so far but I support the propose of @andreas-aeschlimann.

I don't know if this is the correct place to discuss translations (are they crowdsourced anywhere, or should it be done via PR?), but depending in which context this sentence arises there might be a better translation like "Suche auf dem Server nach Veränderungen in Ordnern".
As remote directory also could mean the (remote) server in general,  depending on the context other translations might be fitting as well.

**Comment by andreas-aeschlimann** [comment]
> I haven't noticed this phrase so far but I support the propose of @andreas-aeschlimann.
> 
> I don't know if this is the correct place to discuss translations (are they crowdsourced anywhere, or should it be done via PR?), but depending in which context this sentence arises there might be a better translation like "Suche auf dem Server nach Veränderungen in Ordnern".
> As remote directory also could mean the (remote) server in general, depending on the context other translations might be fitting as well.

Thanks for supporting it.

See here, there are several appearances of `entfernt`:
https://github.com/nextcloud/desktop/blob/master/translations/client_de.ts

**Comment by Id3aFly** [comment]
Thank, I looked it up. Some translations with "remote->entfernt" are really bad.

I would depend the translation to German on the context:
- If it is the description of a button like: "If you click this, the client looks for remote folders" I would go opt for your recommendation: "nach Änderungen in entfernten Ordnern suchen".
- If it is describing a current executed task I would suggest to use: "Suche auf dem Server nach veränderten Ordnern"

**Comment by camilasan** [comment]
We use transifex for the translations: https://www.transifex.com/nextcloud/nextcloud/client/
I think you need to create an account and ask to join the organization.

**Comment by Id3aFly** [comment]
I think this issue can be closed, to continue the translation improvement on transifex. @andreas-aeschlimann do you agree?

**Comment by andreas-aeschlimann** [comment]
> I think this issue can be closed, to continue the translation improvement on transifex. @andreas-aeschlimann do you agree?

Sure thing, thanks a lot for taking over.

**Comment by Id3aFly** [comment]
@FlexW Please close this issue.
