### ISSUE TITLE
Desktop client fails to connect to server

### ISSUE THREAD

**Issue by sundowndev** [nextcloud/desktop#2933]
My server is properly configured, it only works with HTTPS, not HTTP. But when connecting Linux client with the server, the browser redirects to `http://example.com/login/v2/grant`. Which is not accepted by the Content Security Policy. So I change manually the URL to `httpS://example.com/login/v2/grant` then click on "Authorize". The client receive the response but fails to connect.

### Expected behaviour

Client to connect with the server

### Actual behaviour

Client rejects the response, as the server is misconfigured. Because the redirection was supposed to happen with HTTP scheme, not HTTPS.

![image](https://user-images.githubusercontent.com/16480203/108043802-d396e980-7041-11eb-896c-659e9248585a.png)

### Steps to reproduce

1. Type the server URL, click on next
2. Authorize the request in the browser

### Server configuration

Operating system: Ubuntu LTS
Web server: NC v20.0.7

### Client configuration

Nextcloud version 3.1.2-20210128.185328.9398260fb-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.2 LTS, x86_64

**Comment by FlexW** [comment]
Have you tried to connect to an account at [try.nextcloud.com](https://try.nextcloud.com)? If yes, does it give you also an error?

**Comment by sundowndev** [comment]
> Have you tried to connect to an account at [try.nextcloud.com](https://try.nextcloud.com)? If yes, does it give you also an error?

Just tried and it does give me an error. Guess this comes from my server configuration. Do I have to set a specific param to use HTTPS ?

Note: this is working fine on another computer with the same server, but the client keeps disconnecting and ask to reconnect at each boot. Am I missing something with the configuration ? I also noticed I'm not using the official NC Client since it's a snap package.

**Comment by FlexW** [comment]
You get also an error if you try to connect to try.nextcloud.com?

In general, you should not need to do any special configuration for SSL on the client-side. This should all work out of the box. 

I don't know which guide you used to configure your server but you may have a look at the configuration examples [here](https://github.com/nextcloud/docker). Since to get the server working with SSL some extra tweaking is required.

**Comment by sundowndev** [comment]
> You get also an error if you try to connect to try.nextcloud.com?
> 
> In general, you should not need to do any special configuration for SSL on the client-side. This should all work out of the box.
> 
> I don't know which guide you used to configure your server but you may have a look at the configuration examples [here](https://github.com/nextcloud/docker). Since to get the server working with SSL some extra tweaking is required.

Sorry for the typo, I dot not receive error from try.nextcloud.com.

I'm deploying on Kubernetes, and just used the official Helm chart.

**Comment by sundowndev** [comment]
For those wondering, here are the env vars that were missing in my configuration : 

```yaml
extraEnv:
    - name: TRUSTED_PROXIES
      value: 10.106.0.0/20
    - name: FORWARDED_FOR_HEADERS
      value: HTTP_X_FORWARDED_FOR
    - name: APACHE_DISABLE_REWRITE_IP
      value: '0'
    - name: OVERWRITEPROTOCOL
      value: https
    - name: OVERWRITEWEBROOT
      value: /
```
