### ISSUE TITLE
Documentation on conflicts does not contain dialog introduced in 3.1

### ISSUE THREAD

**Issue by dirks** [nextcloud/desktop#2940]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The documentation should contain the sync conflict handling dialog [introduced in 3.1](https://nextcloud.com/blog/nextcloud-desktop-client-3-1-is-here-with-new-conflict-dialog-notification-handling-and-sharing-options/).

### Actual behaviour
Except for the `Change ownCloud reference to Nextcloud` the documentation on sync conflicts has not changed since its creation.

### Steps to reproduce
1. Read through https://docs.nextcloud.com/desktop/3.1/conflicts.html

### Client configuration
Client version: 3.1.2

Operating system: KDE neon User Edition 5.20

OS language: en_US.UTF-8

Qt version used by client package (Linux only, see also Settings dialog): Appimage (see below)

Client package (From Nextcloud or distro) (Linux only): Version 3.1.2. (KDE) from appimage

Installation path of client: not installed

### Server configuration

Not relevant, documentation bug.

### Logs

Not relevant, documentation bug.

**Comment by mgallien** [comment]
@dirks Thanks for your report. Would you like to try writing the missing documentation ?
The format is super easy and does not require sophisticated tools on your side.
That would be really helpful !

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
