### ISSUE TITLE
Theming Variables Overlap More Than They Should

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#2946]
The [pull request I just submitted](https://github.com/nextcloud/desktop/pull/2945) fixes the titular issue in https://github.com/nextcloud/desktop/issues/2898, but some of the underlying issues—namely that the various theming variables overlap with each other when they probably shouldn't—remains.

I did an initial test with deliberately mismatched variables (copied over from #2898), and here are the results:

> I decided to do a quick test with alternate theme values to see what ended up where. These are the OEM values:
> 
> ```
> set( APPLICATION_NAME       "Nextcloud" )
> set( APPLICATION_SHORTNAME  "Nextcloud" )
> set( APPLICATION_EXECUTABLE "nextcloud" )
> ```
> 
> I replaced them with these values:
> 
> ```
> set( APPLICATION_NAME       "Whiskey" )
> set( APPLICATION_SHORTNAME  "Tango" )
> set( APPLICATION_EXECUTABLE "Foxtrot" )
> ```
> 
> And the values appeared in the following places:
> 
> ```
> Foxtrot.app (no icon)
> Foxtrot.app/Contents/Frameworks/libFoxtrot_csync.0.dylib
> Foxtrot.app/Contents/Frameworks/libFoxtrotsync.0.dylib
> Foxtrot.app/Contents/MacOS/Foxtrot
> Foxtrot.app/Contents/MacOS/Foxtrotcmd
> Foxtrot.app/Contents/MacOS/libFoxtrot_csync.3.1.50.dylib
> Foxtrot.app/Contents/MacOS/libFoxtrot_csync.dylib
> Foxtrot.app/Contents/MacOS/libFoxtrotsync.3.1.50.dylib
> Foxtrot.app/Contents/MacOS/libFoxtrotsync.dylib
> 
> CFBundleExecutable Foxtrot
> CFBundleIconFile Nextcloud.icns
> CFBundleIdentifier com.nextcloud.desktopclient
> CFBundleLongVersionString Whiskey 3.1.50git
> 
> UTTypeIdentifier com.nextcloud.desktopclient.VIRTUALFILE
> public.filename-extension nextcloud
> CFBundleTypeName Foxtrot Download Virtual File
> LSItemContentTypes com.nextcloud.desktopclient.VIRTUALFILE
> 
> CFBundleDisplayName: Whiskey Extensions
> 
> /Users/elsiehupp/Library/Preferences/Whiskey 
> /Users/elsiehupp/Library/Preferences/Whiskey/Foxtrot.cfg
> 2021-02-21 10:46:36:508 [ info nextcloud.gui.application ]:	"################## Tango locale:[en_US] ui_lang:[] version:[3.1.50git] os:[macOS 11.2]"
> ```
> 
> And in the GUI:
> <img alt="Screen Shot 2021-02-21 at 10 46 44 AM" width="862" src="https://user-images.githubusercontent.com/9206310/108630599-9bbde680-7433-11eb-9ee4-c606bf618799.png">
> I backed up my settings and tried running `Foxtrot.app`; because the name was different, it didn't seem to read my existing preferences, but neither did it crash on startup. I didn't test to see if there were any other errors, though.

In order to make sure that the build variables don't have any potentially breaking conflicts, my recommendation is that there be a "Test" theme that uses deliberately mismatched variable values (such as the variable names as string literals, albeit with any illegal characters removed where necessary), just to make sure that superficially similar variable values aren't silently dependent on each other, at least in a way that could cause breaking errors.

**Comment by elsiehupp** [comment]
Here's a potential version of `TESTTHEME.cmake`:
```
set( APPLICATION_NAME       "ApplicationName" )
set( APPLICATION_SHORTNAME  "ApplicationShortName" )
# APPLICATION_EXECUTABLE is APPLICATION_SHORTNAME,
# with spaces removed, and (if not macOS) all lowercase
set( APPLICATION_DOMAIN     "ApplicationDomain" )
set( APPLICATION_VENDOR     "ApplicationVendor" )
set( APPLICATION_UPDATE_URL "ApplicationUpdateUrl" CACHE STRING "URL for updater" )
set( APPLICATION_HELP_URL   "ApplicationHelpUrl" CACHE STRING "URL for the help menu" )
set( APPLICATION_ICON_NAME  "ApplicationIconName" )
set( APPLICATION_ICON_SET   "SVG" )
set( APPLICATION_SERVER_URL "ApplicationServerUrl" CACHE STRING "URL for the server to use. If entered, the UI field will be pre-filled with it" )
set( APPLICATION_SERVER_URL_ENFORCE ON ) # If set and APPLICATION_SERVER_URL is defined, the server can only connect to the pre-defined URL
set( APPLICATION_REV_DOMAIN "ApplicationRevDomain" )
set( APPLICATION_VIRTUALFILE_SUFFIX "ApplicationVirtualFileSuffix" CACHE STRING "Virtual file suffix (not including the .)")

# The following code is necessary for the macOS .app to have title case
if (APPLE)
    string(REPLACE " " "" APPLICATION_EXECUTABLE "${APPLICATION_SHORTNAME}")
else ()
    string(REPLACE " " "" temp "${APPLICATION_SHORTNAME}")
    string(TOLOWER "${temp}" APPLICATION_EXECUTABLE)
endif()
# message(STATUS "Debug: APPLICATION_EXECUTABLE is ${APPLICATION_EXECUTABLE}")

set( LINUX_PACKAGE_SHORTNAME "LinuxPackageShortName" )
set( LINUX_APPLICATION_ID "${APPLICATION_REV_DOMAIN}.${LINUX_PACKAGE_SHORTNAME}")

set( THEME_CLASS            "ThemeClass" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )

set( MAC_INSTALLER_BACKGROUND_FILE "${CMAKE_SOURCE_DIR}/admin/osx/installer-background.png" CACHE STRING "The MacOSX installer background image")

# set( THEME_INCLUDE          "${OEM_THEME_DIR}/mytheme.h" )
# set( APPLICATION_LICENSE    "${OEM_THEME_DIR}/license.txt )

option( WITH_CRASHREPORTER "Build crashreporter" OFF )
#set( CRASHREPORTER_SUBMIT_URL "https://crash-reports.owncloud.com/submit" CACHE STRING "URL for crash reporter" )
#set( CRASHREPORTER_ICON ":/owncloud-icon.png" )

## Updater options
option( BUILD_UPDATER "Build updater" OFF )

option( WITH_PROVIDERS "Build with providers list" ON )


## Theming options
set( APPLICATION_WIZARD_HEADER_BACKGROUND_COLOR "#0082c9" CACHE STRING "Hex color of the wizard header background")
set( APPLICATION_WIZARD_HEADER_TITLE_COLOR "#ffffff" CACHE STRING "Hex color of the text in the wizard header")
option( APPLICATION_WIZARD_USE_CUSTOM_LOGO "Use the logo from ':/client/theme/colored/wizard_logo.(png|svg)' else the default application icon is used" ON )


#
## Windows Shell Extensions & MSI - IMPORTANT: Generate new GUIDs for custom builds with "guidgen" or "uuidgen"
#
if(WIN32)
    # Context Menu
    set( WIN_SHELLEXT_CONTEXT_MENU_GUID      "{BC6988AB-ACE2-4B81-84DC-DC34F9B24401}" )

    # Overlays
    set( WIN_SHELLEXT_OVERLAY_GUID_ERROR     "{E0342B74-7593-4C70-9D61-22F294AAFE05}" )
    set( WIN_SHELLEXT_OVERLAY_GUID_OK        "{E1094E94-BE93-4EA2-9639-8475C68F3886}" )
    set( WIN_SHELLEXT_OVERLAY_GUID_OK_SHARED "{E243AD85-F71B-496B-B17E-B8091CBE93D2}" )
    set( WIN_SHELLEXT_OVERLAY_GUID_SYNC      "{E3D6DB20-1D83-4829-B5C9-941B31C0C35A}" )
    set( WIN_SHELLEXT_OVERLAY_GUID_WARNING   "{E4977F33-F93A-4A0A-9D3C-83DEA0EE8483}" )

    # MSI Upgrade Code (without brackets)
    set( WIN_MSI_UPGRADE_CODE                "FD2FCCA9-BB8F-4485-8F70-A0621B84A7F4" )

    # Windows build options
    option( BUILD_WIN_MSI "Build MSI scripts and helper DLL" OFF )
    option( BUILD_WIN_TOOLS "Build Win32 migration tools" OFF )
endif()
```
Basically, the goal with test values like this is that the build should succeed, even if the dummy values don't necessary make sense.

**Comment by er-vin** [comment]
As I hinted on #2945 it should be kept in mind that it ties in to branding so any change there should be very carefully considered and coordinated with the brander app. Otherwise expect interesting surprises.

**Comment by elsiehupp** [comment]
Yes, my thought with this issue is that there could be a "dummy" branding-variable list as part of testing, so that it can be confirmed that the variables are actually being processed as intended, specifically in order to avoid these interesting surprises for your OEM customers.

With #2945 what I did was put the fix in the branding-variable list for Nextcloud, which specifically keeps the change from causing any unexpected issues with your OEM customers (while also keeping the fix from them until it can be confirmed to work on a case-by-case basis).

**Comment by elsiehupp** [comment]
The approach I took with #2945 had the advantage of actually reducing the number of theme variables (by making `APPLICATION_EXECUTABLE` derived rather than user-assigned), and in the long run reducing the number of redundant variables seems like a good way to eliminate the issue of different variables being invisibly interchanged due to the fact that they *usually* (but not always) have the same value.

Here are some variables that could be simplified:

* With regard to reducing the number of variables, in particular, `APPLICATION_EXECUTABLE`, `APPLICATION_VIRTUALFILE_SUFFIX`, and `LINUX_PACKAGE_SHORTNAME` all seem like they could be derived from `APPLICATION_SHORTNAME` (which could be clearly labeled as not allowing spaces or punctuation).
* With some additional cleverness, `APPLICATION_REV_DOMAIN` could be derived from `APPLICATION_DOMAIN`, though there seems to be some confusion between `APPLICATION_REV_DOMAIN` and `LINUX_APPLICATION_ID`, with the latter being somewhat awkwardly "com.nextcloud.desktopclient.nextcloud".
* Further, `APPLICATION_ID` (a replacement for `LINUX_APPLICATION_ID` to be shared between Linux and macOS) could just be derived from `APPLICATION_DOMAIN` and `APPLICATION_NAME`, as follows.

In my earlier process of digging through the instances of the word "nextcloud" in the code, one thought I had was that `APPLICATION_NAME` should be "Nextcloud Desktop", to distinguish it from "Nextcloud Server" and "Nextcloud Mobile". Consequently the three applications would have the following reverse-domain IDs:
* Nextcloud Desktop: com.Nextcloud.NextcloudDesktop
* Nextcloud Mobile: com.Nextcloud.NextcloudMobile
* Nextcloud Server: com.Nextcloud.NextcloudServer

While it may initially seem somewhat silly to have the word "Nextcloud" twice in each application ID, it's important because that way the application name (the right-most portion) actually matches the name of the application (which contains the word "Nextcloud"). And the application names (well, the long names, not necessarily shown in every setting) would have to include "Desktop", etc., in order that the three application IDs (which would be derived from `APPLICATION_NAME`) actually be distinct strings.

(It's not clear to me whether all-lowercase or CamelCase is more the norm for reverse-domain IDs, but the latter seems useful for when an application name consists of more than one word.)

While I recognize that, for example, application IDs used for third-party distribution (App Store, Snapcraft, etc.) may be non-trivial or impossible to change, in other instances it would be perfectly feasible to create aliases along the lines of how the installation code already checks for existing Owncloud installs.

FWIW there are other instances where tweaking the themed variables and themable strings would be useful—for example, "Nextcloud Extensions" could be more clearly named "Nextcloud Finder Integration"—and I recognize that changing these variables (especially the application ID) is a delicate task. In general, though, in the long run it seems like consolidating the number of user-assignable theme variables would make the related code more stable and easier to maintain.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
