### ISSUE TITLE
Nice Name for the Installer

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/desktop#2947]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I think it would be nice to have a descriptive naming for the installer.

### Actual Behaviour
When automatically updating the Desktop Client, the admin-request prominently shows the Installer name, which is something like `4ceb.msi`. As i'm a small perfectionist, i'm always confused for a short moment, that i don't allow to install `Nextcloud_Update_v123.msi` or something similar. 

### Steps to reproduce
1. Update NC-Desktop on Windows
2. Have your perfectionism feel strange - Feel free to just close this issue, if you don't find this step. 😉 

### Client configuration
Client version: 3.1.3 (Windows)
Operating system: Win10

**Comment by splitt3r** [comment]
It also misses the Nextcloud icon which would make it a bit more recognizable.

**Comment by mgallien** [comment]
done by https://github.com/nextcloud/client-building/pull/131
I had missed the gihtub issue when merging the PR
sorry
new UAC prompt
![Image](https://github.com/user-attachments/assets/e79b8b27-9368-4f9b-be3a-1ecf3f9d6165)
