### ISSUE TITLE
Daily Build 3.1.50.20210225 - Virtual Folders unable to load images in the Photo Folder

### ISSUE THREAD

**Issue by gurrman22** [nextcloud/desktop#2952]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen
Image Loads in program and previews download

### Actual behaviour
Tell us what happens instead
When attempting to open the image or movie file in photos it says an unexpected error has occured. then asks to try again or skip. 
Error : 0x8007017C: The Cloud Operation is invalid

### Steps to reproduce
1. Virtual file the Syncs
2. Attempt to load photo from photos folder
3.error happens no issue with documents

### Client configuration
Client version: Daily Build 3.1.50.20210225

Operating system: Windows 10 20H2

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):na

Client package (From Nextcloud or distro) (Linux only):na

Installation path of client:C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 20.0.8.1 

Storage backend (external storage): Hyper V VHDX thin Provisioned

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since
[Nextcloud logs.zip](https://github.com/nextcloud/desktop/files/6053914/Nextcloud.logs.zip)
 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:na
![image](https://user-images.githubusercontent.com/79734934/109381220-cd581580-793d-11eb-8248-28890b3f320d.png)

3. Server logfile: nextcloud log (data/nextcloud.log):na

**Comment by er-vin** [comment]
@FlexW @allexzander It's the one you're presently chasing right?

**Comment by FlexW** [comment]
@er-vin Yes correct.
