### ISSUE TITLE
Pushnotifications - Allow approvedCerts

### ISSUE THREAD

**Issue by leaty** [nextcloud/desktop#2953]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Pushnotifications should adhere to the same ssl configuration as the account connection, or if the push server has a different certificate- prompt the user for trust.

### Actual behaviour
The connection is denied and thus, no push support.

### Steps to reproduce
1. Set notify_push server to point to somewhere with a self-signed certificate.
2. Start nextcloud client.

### Client configuration
Client version 3.1.3

Operating system:
Arch Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15

Client package (From Nextcloud or distro) (Linux only): https://archlinux.org/packages/community/x86_64/nextcloud-client/

Installation path of client: na

### Logs
```
2021-02-27 22:33:47:310 [ warning nextcloud.sync.pushnotifications ]:	Received websocket ssl errors: ("The certificate is self-signed, and untrusted")
2021-02-27 22:33:47:310 [ warning nextcloud.sync.pushnotifications ]:	Websocket error QAbstractSocket::SocketError(13)
2021-02-27 22:33:47:310 [ info nextcloud.sync.pushnotifications ]:	Disconnected from websocket
2021-02-27 22:33:47:310 [ info nextcloud.sync.pushnotifications ]:	Close websocket
```

**Comment by leaty** [comment]
I want to mention that I attempted.. and successfully half-patched this by doing the following:
```cpp
_websocket->setSslConfiguration(_account->sslConfiguration());
```

However, in some amazingly weird way I can't make it fail again. If I do `git checkout master -f` and rebuild completely fresh, newly named directories and all, it still works. I don't know if Qt stores this information or something, but i just can't make my own builds stop working anymore in regards to this issue. However, the official package still fails, only my own builds work after I made this change once.

**Comment by FlexW** [comment]
@LukasReschke I ping you because we had a discussion about client certificates and if we want to support them at all in the client. What do you think?

@leaty In the meantime as a workaround, you can submit your self-signed certificate to the operating system. Qt should then pick up this certificate and you should get no errors.

**Comment by leaty** [comment]
> In the meantime as a workaround, you can submit your self-signed certificate to the operating system. Qt should then pick up this certificate and you should get no errors.

I've done that, but thanks anyway. :+1:
It's just not an easy thing to do for my non-techy clients.

> if we want to support them at all in the client.

My 2 cents: Not everyone wants run with a domain name- security through obscurity I guess you could call it, so let's encrypt won't work in those cases. The trust dialog was easy enough to explain, as it's just another step in the client setup, but to install certs OS-wide is another story. An alternative to supporting specific certificates, you could have a button to allow *any* self-signed certificate, and simply ignore that error.

**Comment by LukasReschke** [comment]
> @LukasReschke I ping you because we had a discussion about client certificates and if we want to support them at all in the client. What do you think?

My personal opinion here is that certificates should be installed in the Operating System Trust Store. I am not a fan of us having a custom "Invalid certificate press here to import" button as that leads to users blindly accepting them as shown in countless studies :) 

So I'd be fine with us deferring this for now until we decided on what the path forward for self-signed certificates is. (including for WebViews etc)

**Comment by FlexW** [comment]
I will close that issue for now.
