### ISSUE TITLE
[ARM -M1] Garbled graphics on Activity Screen 

### ISSUE THREAD

**Issue by freumichCH** [nextcloud/desktop#2962]
### Expected behaviour

Activity Screen shows correct rendered graphics

### Actual behaviour

Activity Screen shows garbled graphics

### Steps to reproduce

1. Building desktop client based on instructions from [This Manual](https://raw.githubusercontent.com/nextcloud/desktop/master/doc/building.rst)
2. Installed on a macOS 11.2.2 with M1 - ARM main processor
3. Logged in with test account and setup client
4. Open activity Screen 
![Bildschirmfoto 2021-03-02 um 18 08 41](https://user-images.githubusercontent.com/22443781/109686256-65ded780-7b82-11eb-8311-09992f6cfa5a.png)

Doing the same procedure with a intel mac shows correct rendered graphics in the activity screen

### Client configuration
Client version: 3.1.3

Operating system: macOS 11.2.2

OS language: German / Swiss-German

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.15.2

Installation path of client: /Volumes/Applications/

**This only happening on self build clients. Clients downloaded from nextcloud.com does show correct rendered graphics***

Does someone have an idea what could be wrong? I'm pretty sure it's my build environment. But have no clue where to start.

Thanks in advance ✌🏻🤙🏻

**Comment by freumichCH** [comment]
This has been reproducible on several computers with ARM - M1 processors

**Comment by michaelstingl** [comment]
Does it run native on M1 or in Rosetta 2 emulation?

**Comment by freumichCH** [comment]
It does say for both, nextcloud and my own branded Client that it use "Intel" as architecture

**Comment by Syntax3rror404** [comment]
Yes, if the task is shown as intel, Rosetta is in the game.

**Comment by freumichCH** [comment]
Problem ist still present with V3.3.3 desktop client. 

Is this coming from the QR environment? 
Can someone reproduce this issue?

**Comment by mgallien** [comment]
> Problem ist still present with V3.3.3 desktop client.
> 
> Is this coming from the QR environment?
> Can someone reproduce this issue?

sure but you already opened #3801let's continue there
