### ISSUE TITLE
"Show chat" does not do anything

### ISSUE THREAD

**Issue by hul51u** [nextcloud/desktop#2968]
### Expected behaviour
Browser with link to the chat should open.

### Actual behaviour
No function

### Steps to reproduce
1. Receive a private message.
2. Desktop client shows on "Activity": xxx sent you a private message (German: xxx hat Dir eine private Nachricht gesendet)
3. Click on the three dots on the right
4. Click on show chat (German: Chat anzeigen)

### Client configuration
Client version: 2.6.4-1

Operating system: Ubuntu 20.10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): sudo apt install nextcloud-desktop

Installation path of client:

### Server configuration

Nextcloud version: 20.0.8.1

**Comment by FlexW** [comment]
Could you please try with the newest version if the issue still exists? At the moment the newest version is 3.1.3.
