### ISSUE TITLE
Default CMAKE_INSTALL_PREFIX is a protected/hidden folder on macOS

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#2970]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On macOS, the default `CMAKE_INSTALL_PREFIX` value should work without `sudo` before `make install`, and the directory should be easily navigable in the Finder.

### Actual behaviour
On macOS he default `CMAKE_INSTALL_PREFIX` value, `usr/local`, throws a compiler error without `sudo`, and the directory is hidden in the Finder.

### Steps to reproduce
1. Follow [the existing build instructions](https://github.com/nextcloud/desktop/blob/b33ea052711e84118851ff5e92dd95847c144937/doc/building.rst).
2. Don't set `CMAKE_INSTALL_PREFIX`.
3. Run `make install` without `sudo`.
4. After getting a build error, try again with `sudo make install`.
5. Try to navigate to the new build using only the Finder and without using Cmd-Shift-G.

### Client configuration

* Client version: 3.1.50git
* Operating system: macOS Big Sur 11.2.1
* OS language: English
* Installation path of client: `/usr/local`

**Comment by FlexW** [comment]
I don't think this should be the case and I think `/usr/local` is a sensible default install location. Installation in a non system directory is just advised if you want to do development. I will close that for now.

**Comment by elsiehupp** [comment]
I would rather get at least one other person's opinion on this.

**Comment by er-vin** [comment]
Yes, I would agree with @FlexW here. This is normal and expected behavior on Unix family OSes. And indeed for developers that might not fit, that's why they would change CMAKE_INSTALL_PREFIX at cmake time *if* they want to install (but in most cases for a single application like this you don't need to, it's a more advanced use).

**Comment by elsiehupp** [comment]
> This is normal and expected behavior on Unix family OSes.

I was going to say, I know macOS is weird, but if it isn't quite *that* weird, yet...
