### ISSUE TITLE
Apple cleanup wizard deleted files from NextCloud, so it deleted many shared files

### ISSUE THREAD

**Issue by JochenHWezel** [nextcloud/desktop#2973]
## Problem description

Today, a user reported that she found many files from her NextCloud instance in her trash bin. A few hours ago, she said yes to Apples MacOS cleanup wizard which seems to remove old/unused files.

I'm not an Apple MacOS user, so I can't tell much about the cleanup wizard. But I know that I don't want to repeat this situation for a 2nd time. But there are high chances to face this problem again:
* The cleanup wizard seems to be a "feature" of Apple's MacOS
* When the Mac gets slow over time, the MacOS wizard seems to pop up and recommend cleaning up old files (as I understood from my user)
* The cleanup wizard uses a logic to cleanup old/unused files, but the logic is unknown to me or the user
* The cleanup wizard also cleans up files from NextCloud sync folder !!
* After NextCloud client synced the many file deletions 
  * for sure, the file deletions replication to the server and all the other users who access the same shared folders
  * in my case, in many folders were 1 or 2 files deleted
* The PROBLEM is: 
  * find the many places where files are missing (while you're not knowing that or which files are missing)
  * try to identify which files are deleted accidently and which files are deleted regulary/correctly/by-user-with-sense
  * have all the other users accessing the same shared folders on NextCloud who wonder why they don't find their files any more

## It doesn't seem to be a one-time problem
I faced a similar situation months ago in my company with another MacOS user. We also missed several files, but we hadn't got a idea why the files were missing and for how long. We were only able to identify the many file deletions to that MacOS user. He didn't had an explanation why "he" deleted these files, and he assured that he wasn't aware to deleting any files from our nextcloud sync folders. But now I see that it might be the very same reason: Apple's MacOS cleanup wizard...

Since this accident occurred with a different NextCloud server instance on different IT environment with different users, the problem is not related to a technical issue of a server. The only same thing of both described problem stories is the admin: that's me. :-/

## Intention of this ticket / possible solutions
* Maybe this issue is more an issue related to MacOS and not to NextCloud, but I don't expect that Apple will change the behaviour of the cleanup wizard. So the problem for all Nextcloud users with at least 1 MacOS user in the team will have this problem one day. 
* Or maybe this issue can be fixed by moving or recommend moving the sync folder to another location on disk which is not scanned by Apple's cleanup wizard or maybe there is a possibility to tell to the cleanup wizard to NOT scan the sync directory.
* Maybe other people in the community experienced similar situations and can share from their knowledge.
* Maybe it's worthy to provide at least some notes on a documentation page at nextcloud.com with a guide to warn MacOS users from this cleanup wizard action or to provide helpful guides to admins to prevent such accidents or how to handle the situation if the accident already occured.

**Comment by FlexW** [comment]
Thank you for taking the time to write that issue:) Indeed we had other people with similar symptoms but I'm unsure if their problems were caused by the cleanup wizard.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
