### ISSUE TITLE
Nextcloud macOS client catches focus every 10 seconds

### ISSUE THREAD

**Issue by Kater--S** [nextcloud/desktop#2978]
When my Mac has booted up and I have logged in, the NC desktop client is started automatically. However, for at least one hour it is constantly presenting the menu bar menu every 10 seconds, even if the NC Settings dialog is open. What is most annoying, I must say, is that it also catches focus, interrupting any work like typing text etc.

The NC processes (nextcloud and Nextcloud Extensions) are _not_ restarting, their pids are not changing.

Syncing is done without errors, all connections show the green checkmark.

Pausing any or even all of my five NC server connections does not stop the behaviour.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
NC client should work in background, at least unless some error occurs. Even then, changing the menu bar icon is sufficient.

### Actual behaviour
Every 10 seconds the menu bar menu is popping up, catching the keyboard focus. I have to click in my current application window (or hit cmd-tab twice, esc has no effect) to return to my work.

### Steps to reproduce
1. start the system
2. start working

### Client configuration
Client version:
3.1.1 (latest)
Operating system:
macOS 10.14.6 (latest 10.14 subversion)
OS language:
EN+DE

Installation path of client:
/Applications/nextcloud.app

### Logs
Console log showing two episodes of the ever-repeating sequence:
```
default	16:13:35.458104 +0100	launchservicesd	CHECKIN:0x0-0x1e21e2 4211 com.nextcloud.desktopclient
default	16:13:35.459479 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : nextcloud
default	16:13:35.472495 +0100	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.nextcloud.desktopclient, type: 0: 0x7f8bde0062e0 at /Applications/nextcloud.app
default	16:13:35.487986 +0100	nextcloud	Current system appearance, (HLTB: 1), (SLS: 0)
default	16:13:35.492138 +0100	nextcloud	Post-registration system appearance: (HLTB: 1)
default	16:13:35.496914 +0100	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: com.nextcloud.desktopclient token: f4267 pid: 4211
default	16:13:35.509912 +0100	nextcloud	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x7fc44ed18190
 (
    "<NSAquaAppearance: 0x7fc44ed17420>",
    "<NSSystemAppearance: 0x7fc44ed17ac0>"
)>
default	16:13:35.632034 +0100	nextcloud	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,quit handler=0x7fff4793e4d7 isSys=NO) err=0/noErr
default	16:13:35.638337 +0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:nextcloud, _appTrackingState = 2
default	16:13:45.696742 +0100	launchservicesd	CHECKIN:0x0-0x1e31e3 4212 com.nextcloud.desktopclient
default	16:13:45.698075 +0100	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : nextcloud
default	16:13:45.711638 +0100	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.nextcloud.desktopclient, type: 0: 0x7f8bddf09fc0 at /Applications/nextcloud.app
default	16:13:45.730217 +0100	nextcloud	Current system appearance, (HLTB: 1), (SLS: 0)
default	16:13:45.734212 +0100	nextcloud	Post-registration system appearance: (HLTB: 1)
default	16:13:45.742823 +0100	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: com.nextcloud.desktopclient token: f4267 pid: 4212
default	16:13:45.752932 +0100	nextcloud	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x7ff2ee60a5d0
 (
    "<NSAquaAppearance: 0x7ff2ee607770>",
    "<NSSystemAppearance: 0x7ff2ee608d10>"
)>
default	16:13:45.869376 +0100	nextcloud	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,quit handler=0x7fff4793e4d7 isSys=NO) err=0/noErr
default	16:13:45.876729 +0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:nextcloud, _appTrackingState = 2
```

### Workaround
1. stop Nextcloud client
2. restart Nextcloud client

Console log now only shows these entries:
```
default	16:36:34.396419 +0100	nextcloud	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 1300, 512, <private>
default	16:36:52.420760 +0100	nextcloud	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 1312, 512, <private>
default	16:36:55.652817 +0100	nextcloud	UNIX error exception: 17
default	16:36:55.655095 +0100	nextcloud	UNIX error exception: 17
```
All accounts synced, no log entries for several minutes.

**Comment by Kater--S** [comment]
Addition:
Exiting the client in its own menu seems not to work. Instead I have to "Quit" (not "Force Quit") the process in Activity Monitor.

**Comment by FlexW** [comment]
WIth menu bar you mean the main dialog that opens up if you click on the tray icon?

**Comment by Kater--S** [comment]
correct. “menu bar menu” = Nextcloud’s main dialog opened from macos tray (system menu bar, top of screen). sorry for unclear denomination.

**Comment by sudoer** [comment]
I left a little script running to monitor focus changes.  See https://apple.stackexchange.com/a/170699

Using that script, I noticed that nextcloud seems to grab focus at the top of every hour.  It appears only to happen when my mac is "in use" and not when idle.  So maybe that means nextcloud only grabs focus when it is syncing changed files.

This kind of switch showed up every hour:

2021-03-30 15:58:21: iTerm2 [/Applications/iTerm.app]
2021-03-30 15:58:33: Slack [/Applications/Slack.app]
2021-03-30 16:00:02: nextcloud [/Applications/nextcloud.app]
2021-03-30 16:00:04: Slack [/Applications/Slack.app]
2021-03-30 16:01:35: iTerm2 [/Applications/iTerm.app]
2021-03-30 16:02:46: Slack [/Applications/Slack.app]

Version 3.1.3 (macOS).

**Comment by Kater--S** [comment]
Unfortunately, the bug is still a bug. Each time I reboot, the behaviour is the same.

I am using the latest version 3.1.3 (macOS) in the _stable_ channel.

**Comment by sudoer** [comment]
The top-of-the-hour focus-grab is still an issue in Nexcloud 3.3.5 on MacOS (Big Sur).

**Comment by claucambra** [comment]
Hi @Kater--S is this issue still happening for you on 3.5.1? Thanks!
