### ISSUE TITLE
"Fluent Design" Style Updates?

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#2987]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

In #2954, @szaimen included the following screenshot to illustrate how icon norms have changed on Windows 10 under Microsoft's ["Fluent Design"](https://www.microsoft.com/design/fluent/) style, which is in the process of supplanting the ["Metro"](https://en.wikipedia.org/wiki/Metro_(design_language)) style from Windows 8:

!["Fluent Design" icons](https://user-images.githubusercontent.com/42591237/110682332-1b410900-81db-11eb-8d7c-35d4c6e389f1.png)

These new icons are part of a broader redesign by Microsoft that includes a two new symbol libraries—[Segoe UI](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font) and [Fluent UI](https://github.com/microsoft/fluentui-system-icons)—but particularly salient to #2954 is the question of how the application icon should appear: "Fluent Design" tends to feature full-color symbols within a larger frame.

### Actual behaviour

The existing Nextcloud Desktop icon, while well-suited to the current design language of macOS and iOS, more closely matches with the older "Metro" style of Windows icons, that is, a monochrome symbol in front of a colored background. The monochrome symbol is useful for the Finder sidebar and the Nautilus sidebar but doesn't seem to fit with the context of the File Explorer, as shown in #2903. To borrow @pkrolkgp's screenshots again:

![106886965-cba38500-66e4-11eb-84c5-25d3408dc569](https://user-images.githubusercontent.com/9206310/110712073-951ec580-81ce-11eb-8954-3ec2f99d3d1d.png)
![106887169-11f8e400-66e5-11eb-835f-44e18c5c6855](https://user-images.githubusercontent.com/9206310/110712079-994ae300-81ce-11eb-8e58-b42038332e13.png)

Less salient to #2954, Nextcloud Desktop uses custom UI icons, which could look increasingly out of place on Windows 10 if Microsoft's Segoe UI or Fluent UI icons become popular. (The question of platform-standard UI icons on other platforms may be better addressed elsewhere, but it's worth noting that most platforms do, in fact, offer them.)

### Steps to reproduce
1. Pin the Nextcloud app and the Nextcloud folder next to one or more of the redesigned Microsoft icons in the Start Menu for a visual comparison.

### Client configuration
Operating system: Windows 10

### What to do?
Note that this issue is delicately intertwined with the question of branding, so any modifications to the core design concept of the application icon are a bit beyond what I'm comfortable dealing with personally. The existing icon does work well in certain contexts, though as is apparent in the linked issues, it works less well in others. It seems like someone with more prerogative—@jancborchardt \*cough, cough\*—could potentially work on a supplementary variant of the icon where the logo uses a color and/or the blue circle is adapted to a more symbolically meaningful shape.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/desktop/issues/2987#issuecomment-2464316897

@Rello, I believe that *this* still applies.
