### ISSUE TITLE
Document release signature verfiication with gpg

### ISSUE THREAD

**Issue by maltfield** [nextcloud/desktop#2991]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

When I go to download the nextcloud desktop client, I should also see instructions on how to verify the authenticity of the file after download and before install. Or, at least, a link to the document that describes this.

### Actual behaviour

I see no mention about cryptographic authenticity verification on the download page

 * https://nextcloud.com/install/#install-clients

### Steps to reproduce
1. Go to https://nextcloud.com/install/#install-clients
2. ???
3. Get confused and open ticket

### Client configuration
Client version: n/a

Operating system: Windows

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: n/a

### Server configuration

Nextcloud version: n/a

Storage backend (external storage): n/a

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by maltfield** [comment]
I initially assumed that the packages just weren't signed at all, and I wanted to open a ticket asking to please sign releases.

But a quick search for 'gpg' in the issues for this github repo show that this has been apparently already been implemented in #1805

Yet I have no idea where to find:

1. The official NextCloud release signing public key and
2. The checksum file for your releases
3. The signature of the checksum file for your releases

Hence this ticket to address this with documentation

**Comment by FlexW** [comment]
You can find them for each release [here](https://github.com/nextcloud/desktop/releases). We should a link to them on nextcloud.com I guess.

**Comment by affinityv** [comment]
> You can find them for each release [here](https://github.com/nextcloud/desktop/releases). We should a link to them on nextcloud.com I guess.

What are you talking about?  You can find files and their signatures, but you cannot find the public signing key anywhere, nor instructions to check for those that need them.

**Comment by affinityv** [comment]
>$ gpg --verify Nextcloud-3.2.4.pkg.asc Nextcloud-3.2.4.pkg
gpg: Signature made Thu 08 Jul 2021 20:54:36 AEST
gpg:                using RSA key A438DC095967A1F11601CC42B69CB7F1069B3399
gpg: Can't check signature: No public key

**Comment by affinityv** [comment]
There are also no check sums either.

**Comment by mgallien** [comment]
I fail to see what would be the added value to document how one is supposed to be using an external tool to check the signature of a release.
I guess we will have to spend quite some time documenting how to do it on all platforms and I would prefer to focus on something else for the documentation.
My advice follow the results liked here [gpg verify signature](https://duckduckgo.com/?t=ffab&q=gpg+verify+signature&ia=web)

**Comment by affinityv** [comment]
I think we all know HOW to check the signature and verify it, the problem is that the public key isn't published and/or able to be found.  Has this changed?
