### ISSUE TITLE
Large files (~20 GB) fail to sync

### ISSUE THREAD

**Issue by dakontiva** [nextcloud/desktop#2992]
### Expected behaviour
Files should be synced irrespective of the file size

### Actual behaviour
Large files of approximate 20 GB size cause sync to fail.

### Steps to reproduce
1. Create a a new folder
2. Copy some small (< 5MB) and large files (approx. 20GB) to this folder
3. Wait for the sync to start
4. Sync succesfully copies small files but fails to copy large files

### Client configuration
Client version: 3.1.3 (appimage for linux)

Operating system: Ubuntu 20.10

OS language: English (US)

Qt version used by client package (Linux only, see also Settings dialog): Can't find it in settings dialog

Client package (From Nextcloud or distro) (Linux only): Linux appimage from Nextcloud

Installation path of client:
$HOME/Software/Nextcloud.appimage

### Server configuration

Nextcloud version: 20.0.7

Storage backend (external storage): No external storage

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://anirudh.owncube.com/index.php/s/D4LLdFtEop3go3K

2. Web server error log: Unfortunately, I couldn't get this as I am using a shared hosting system from a nextcloud provider and the provider doesn't give access to the web server.

3. Server logfile: nextcloud log (data/nextcloud.log): https://anirudh.owncube.com/index.php/s/5oYnfqrtw9so4Ke

**Comment by FlexW** [comment]
@dakontiva Could you tell me how the files were named that failed? Would it make a lot easier to inspect the logs.

**Comment by dakontiva** [comment]
the file that failed is a vm disk image, the path from the nextcloud root folder is `Software/Gnome Boxes/win10`.
