### ISSUE TITLE
Theming broken on KDE in 3.2 RC(?)

### ISSUE THREAD

**Issue by Derkades** [nextcloud/desktop#2993]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Desktop client no longer themed properly with Breeze Dark theme on KDE.
![image](https://user-images.githubusercontent.com/15892014/110808520-5a776480-8284-11eb-8c4e-13f9876c7186.png)

### Client configuration
Client version: It's complicated.

I removed the old package and stable repository from my system, removed all nextcloud desktop packages, added the rc repository and installed `dolphin-nextcloud`.

New packages are installed:
![image](https://user-images.githubusercontent.com/15892014/110809750-7c251b80-8285-11eb-8e6b-bbb91b8430fb.png)

It says I'm using 3.1.81 but it mentions virtual files which are a 3.2 feature as far as I know.
![image](https://user-images.githubusercontent.com/15892014/110809447-2d778180-8285-11eb-8d58-b8380c6003a8.png)

Operating system: Ubuntu 20.10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): I can't find it in the settings dialog?

Client package (From Nextcloud or distro) (Linux only): https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client-beta

**Comment by FlexW** [comment]
The general settings dialog looks fine on my side. However, I see some problems when open the sync and network settings. I have attached some screenshots:

![breeze-dark](https://user-images.githubusercontent.com/19961516/110813097-7977f580-8288-11eb-8e91-022a75af92b8.png)
![breeze-dark3](https://user-images.githubusercontent.com/19961516/110813115-7e3ca980-8288-11eb-95a5-ad1f0af8a501.png)
![breeze-dark-2](https://user-images.githubusercontent.com/19961516/110813134-81379a00-8288-11eb-89a1-d2baddc7e790.png)

@camilasan or @tobiasKaminsky as I'm not a regular KDE user and I think you are? Could you confirm that this looked correct in the past (not sure if you used the dark theme :))? 

@Derkades 3.1.81 is a pre release. It will become 3.2.0 one day.

**Comment by Derkades** [comment]
Thanks!
