### ISSUE TITLE
Main dialog should respect system theme

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#2994]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The main dialog should respect the system theme. Like for example if a dark color theme is chosen, the main dialogs background should not be white. Since the rest of the client respects the system theme, this looks off in my opinion.

### Actual behaviour
The main dialogs background has always the same color, regardless which theme was chosen.

### Steps to reproduce
1. Set a dark theme
2. Open the main dialog

### Client configuration
Client version: 3.1.81

As this involves design questions, a comment from @jancborchardt you would be valuable:)

**Comment by elsiehupp** [comment]
I've tried digging in the code to see where exactly the popover "lives", but unlike the settings dialogue, it isn't particularly obvious.

**Comment by FlexW** [comment]
@elsiehupp Related code lives in `src/gui/tray`.

**Comment by splitt3r** [comment]
Awesome idea 👍🏻 also https://github.com/nextcloud/desktop/pull/1439 was a pretty promising start. Maybe you can build upon it.

**Comment by elsiehupp** [comment]
Copying from #3310:

I also came across [a potentially relevant tip](https://forum.qt.io/post/542991) on the Qt forums:

> [**khrykin**](https://forum.qt.io/user/khrykin) [Jul 25, 2019, 10:40 PM](https://forum.qt.io/post/542991)
>
> You can't reliably detect macOS appearance change in Qt, but nevertheless full dark mode support is achievable, though may require a bit of extra work. Key point is to do all your styling, i.e. backgrounds, borders, etc. in `paintEvent()` and relate all relevant colors to `QApplication::palette()`. Hence you can't really use `setStyleSheet()` for anything color-related. One particular gotcha is `QLabel`, for which I ended up writing my own `ColoredLabel` alternative which would receive its current color via callback.

I haven't looked particularly closely at the issue recently, but it seems like there are still some quirks in how Qt supports macOS Dark Mode.

**Comment by jancborchardt** [comment]
This will be fixed by https://github.com/nextcloud/desktop/pull/4251, testers are very welcome! :)

**Comment by splitt3r** [comment]
Looking forward to test it once the windows build is ready 👀
