### ISSUE TITLE
Sharing link in windows client do nothing

### ISSUE THREAD

**Issue by lucker999** [nextcloud/desktop#2996]
### Expected behaviour
Get a sharing link to a file from Windows Desktop Client 

### Actual behaviour
Nothing. A click in context menu "Nextcloud -> Copy public link"

![screenshot1](https://nc.shershidsky.eu/s/A9wtRtxX473yoqM/preview)

opens a dialog 

![screenshot2](https://nc.shershidsky.eu/s/i3QZtW9kZMzZcbY/preview)

which is identical to dialog "Share options", but it does nothing in order to provide a public link:
- If no user\group entered the arrow is not active (I want a public link, not for a user)
- the button "share link" is not active

So, I have to open web access, log in to installation, find the file, click menu, open sidebar, click to create a link, then do not forget to open context menu to uncheck password protection, and only then use the link. This is ridiculous. I do not mention that the help pages do not reflect actual behaviour of windows client.

### Steps to reproduce
1. Right click on a file in Windows Explored
2. Chose Nextcloud -> Copy bublic link 
3. Stumble upon "Nothing happens"

### Client configuration
Client version: 3.1.3

Operating system: Win 8.1

OS language: En

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
default

### Server configuration
Nextcloud version: 21.0

Storage backend (external storage): none

**Comment by FlexW** [comment]
I'm not sure I understand your issue correctly but when I right-click on a file on a file and go to Nextcloud -> Copy Public Link. I get a link to the file that I can share with everyone and which everyone can access. Nextcloud -> Copy Public Link does not open any dialog for me.

**Comment by lucker999** [comment]
You may be right, I am not sure of it myself right now.

I tested this on another PC (windows 8.1 as well) and it works as expected. I went back to the laptop and switch off "High Contrast Theme" - and the public link dialog appears to be with additional clickable items previously being absent. I switched back to high contrast theme and the public link dialog just keeps working as expected. 

As for the comments to your reply. I was not confused, the public link dialog (please see the screenshot) was simply lacking buttons for the second line (Share link):
- a button to copy the link to clipboard
- a button to manage options for public link
Now they are here as they should be.

Have no idea what was the problem about. May be switching off/on the high contrast theme bring this back to life. Anyway, I guess this should be closed. If I encounter the problem later I will reopen the issue with possibly more details.

Once again, thank you for the reply.
