### ISSUE TITLE
The server version 21.0.0.18-Nextcloud is unsupported! Proceed at your own risk.

### ISSUE THREAD

**Issue by cscholz** [nextcloud/desktop#3001]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
No error about an unsuportes server version should be shown as these version is the official stable one.

### Actual behaviour
Client shows an error message:
_The server version 21.0.0.18-Nextcloud is unsupported! Proceed at your own risk._

### Steps to reproduce
I'm running two instances of nextcloud. Error message is shown on borth. So the steps should be
1. install nextcloud server (stable) 21.0.0.18
2. install client version 3.2 RC1
https://help.nextcloud.com/t/desktop-client-3-2rc1-ready-help-test/110579
3. Connect to server and use virtual file system

### Client configuration
Client version:
- 3.2 RC1
- using virtual file system

Operating system:
- Windows 10, Version 21H1 (Build 19043.867)

OS language:
- German

Installation path of client:
- default location

### Server configuration

Nextcloud version:
- 21.0.0.18

Storage backend (external storage):
- local file system

**Comment by trvrcr** [comment]
Same Issue

NC-server: 21.0.0-8

**Comment by Lars1963** [comment]
Also the same issue.

**Comment by FlexW** [comment]
@cscholz @trvrcr @Lars1963 could one of you provide me your logs? Since I'm unable to reproduce it.

**Comment by Lars1963** [comment]
@FlexW Which logs do you need? Those in C:\Users\User\AppData\Roaming\Nextcloud\logs?

**Comment by FlexW** [comment]
Yes. Just go to Settings -> General -> Create Debug Archive .... Thank you :)

**Comment by art-ist** [comment]
Same with Server 20.0.5, 
btw. how to find out what server releases are or should be supported.

**Comment by brtptrs** [comment]
Same error for NC 20.0.7 and it seems to corrupt the local synchronisation when trying to back out and revert back to 3.1.3

**Comment by FlexW** [comment]
@Lars1963 Did you send it to felix.weilbach@nextcloud.com? Because I didn't received anything. Maybe the spam filter removed it.
You can drop me the logs private here https://cloud.nextcloud.com/s/onzDjSexsxRq3pj. Sorry for the extra work.

> btw. how to find out what server releases are or should be supported.

As far as the code goes everything newer than Nextcloud server version 18.0.0 should be supported automatically.

> it seems to corrupt the local synchronisation when trying to back out and revert back to 3.1.3

That was to be expected because there are huge changes between 3.2.0-rc1 and 3.1.3. Mainly that crash happens because the sync db has a different format in both releases. In general it's not supported to go back to an older version. If you want to go back to a older version, you should remove the sync db.

**Comment by Lars1963** [comment]
> @Lars1963 Did you send it to [felix.weilbach@nextcloud.com](mailto:felix.weilbach@nextcloud.com)? Because I didn't received anything. Maybe the spam filter removed it.
> You can drop me the logs private here https://cloud.nextcloud.com/s/onzDjSexsxRq3pj. Sorry for the extra work.
> 

Well I did sent it to your mailadress. Nevertheless, I'm uploading just now to the link you provided.

**Comment by cscholz** [comment]
I've uploaded my log (3_2_RC1_cscholz.zip)
