### ISSUE TITLE
Appling Theming Settings on Desktop Client

### ISSUE THREAD

**Issue by ghost** [nextcloud/desktop#3002]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I can see my instance theming is set to use custom theme.
The Android client uses it, but it's not applied on the desktop client.

**Describe the solution you'd like**
- Apply theming settings on the desktop client

<details>
<summary>Screenshots</summary>

![Screenshot from 2021-03-14 01-11-05](https://user-images.githubusercontent.com/75371007/111038521-78032480-8464-11eb-871b-0094520653e6.png)
![Screenshot_20210314-011130_Nextcloud](https://user-images.githubusercontent.com/75371007/111038580-c44e6480-8464-11eb-8874-73e021b16be9.png)
![Screenshot from 2021-03-14 01-16-21](https://user-images.githubusercontent.com/75371007/111038522-789bbb00-8464-11eb-9eb1-cd32a877b814.png)

</details>

**Comment by jancborchardt** [comment]
This was fixed by @claucambra with https://github.com/nextcloud/desktop/pull/4237 :)
