### ISSUE TITLE
. (dot) at the end of folder name prevents sync to windows client, Example "Folder e. V."

### ISSUE THREAD

**Issue by sutidor** [nextcloud/desktop#3013]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Name a folder "Some Folder e. V."
2. See it online
3. Dont find it synced without a trace or error in Nextcloud Desktop

### Expected behaviour
Folder sync normally

### Actual behaviour
Folder unsynced without a trace

### Server configuration

**Operating system:**
Windows 10

**Web server:**
nginx

**Database:**
postgresql

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
20

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
linuxserver/nextcloud:latest

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by FlexW** [comment]
Windows does not allow to create filenames that end with a dot. If I try to sync such files, I get a notification in my activity log. However, the notification is not 100 % clear here. It says that the file is on the ignore list and therefore gets not synced.  @sutidor can you confirm that you have this message too?

@camilasan @allexzander Maybe we should make the message clearer and fire an additional operating system notification?

**Comment by allexzander** [comment]
> Maybe we should make the message clearer and fire an additional operating system notification?

@FlexW I had that idea ~4 months ago. We didn't set high priority for that as we always had other, more annoying bugs to fix, so, it's your call if you want to show an alternative message. 
Then again, if there is an error in the Tray window already, maybe, it is not that bad. It depends. 
Just make sure, if you implement a custom message, you still keep the old message for the cases when the file is indeed in the ignore list. Currently, it seems, the "File is in the ignore list"(or something) is a generic message that gets displayed in many cases.
