### ISSUE TITLE
Correctness of text string

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#3027]
While browsing and accepting translations in Transifex, I found a text string like this:
https://github.com/nextcloud/desktop/blob/8c66b9f89e214c7c88d3239cf517881638e589a1/src/gui/folderman.cpp#L1480

Is it correctly constructed. In my opinion, the second part of the sentence excludes the first. If the synchronization was successful, why is there a conflict?
Shouldn't there be: `Sync was successful, resolved conflicts.`

**Comment by FlexW** [comment]
I think it's correct. The sync was successful relates to that there were not network errors and the sync procedure could finish successfully. However, during the sync the sync engine discovered conflict which it could not resolve (after all the sync engine can not resolve conflicts on it's own). Maybe the wording could be adjusted to something like: "Sync finished with unresolved conflicts".

**Comment by Valdnet** [comment]
@FlexW Thanks for the clarification 👍.

> Maybe the wording could be adjusted to something like: "Sync finished with unresolved conflicts".

Most correctly. I am asking for PR 😉.
