### ISSUE TITLE
Icon overlay vs. status column in Windows Explorer

### ISSUE THREAD

**Issue by tobwoerk** [nextcloud/desktop#3030]
### Expected behaviour
Windows Explorer shows Nextcloud icon overlays for files and folders that are synchronized to a NAS.

### Actual behaviour
Two Nextcloud accounts are configured in the Windows client.
Sync folder 1 is Nextcloud only -> overlay icons are working fine.
Sync folder 2 – besides being a Nextcloud folder – is synchronized with a NAS using QSync -> Windows Explorer shows the status column depicting the QSync status but no overlay icons for files and folders.

### Steps to reproduce
1. Install Nextcloud.
2. Install QSync.
3. Set up two Nextcloud accounts and choose base folders next to each other.
4. Choose folder 2 to sync using Qsync.
5. => folder 1 is showing Nextcloud sync icons, folder 2 is not

### Client configuration
Client version: 3.1.3 (Windows)
QSync version: 5.0.0.1409

Operating system:
Windows 10 Pro 19042.867, 64bit

OS language:
German

Installation path of client:
C:\Program Files\Nextcloud

**Comment by FlexW** [comment]
It's not supported Nextcloud with any other sync provider in parallel on the same folder.
