### ISSUE TITLE
Application icon missing on Mac OS

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#3033]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
There should be a Nextcloud icon on nextcloud.app when the user access Applications on Mac OS.

### Actual behaviour
There isn't an icon.

![iconmissing](https://user-images.githubusercontent.com/241266/112361471-b7870780-8cd3-11eb-9be2-5a0201a60d79.png)

### Steps to reproduce
1. Install desktop client 3.2.0-rc2.
2. Got to Applications.

### Client configuration
Client version: 3.2.0-rc1 and 3.2.0-rc2.
Operating system: Mac OS Catalina 10.15.7
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 
Installation path of client: /Applications/nextcloud.app/

### Server configuration
Nextcloud version: 20

### Logs
There is no need for the logs in this case :)

**Comment by splitt3r** [comment]
This could be related:

![image](https://user-images.githubusercontent.com/1869584/112480993-d9859600-8d76-11eb-808a-0ac35564fca6.png)

On Windows 10 (Nc client 3.2.0-rc2) the Nextcloud icon is missing in the Explorer + Task Manager Startup View.

**Comment by camilasan** [comment]
Fixed in 3.2.1.
