### ISSUE TITLE
Client won't launch automatically

### ISSUE THREAD

**Issue by StCyr** [nextcloud/desktop#3036]
### Expected behaviour
Desktop client should launch automatically at login

### Actual behaviour
Desktop client doesn't launch automatically

### Client configuration
Client version: 3.13

Operating system: Windows 10

OS language: EN

### Logs

Please find my debug archive here: https://nextcloud.bollu.be/index.php/s/sKFGSz9LKBxq85b

**Comment by FlexW** [comment]
Have you enabled "Launch on System Startup" in Settings -> General?

**Comment by StCyr** [comment]
yes

![image](https://user-images.githubusercontent.com/8179031/112621067-9d5f3d80-8e29-11eb-892c-0b3978ec9d86.png)

**Comment by FlexW** [comment]
Okay, and I guess if you open the task manager and go to the tab "Startup", nextcloud.exe is enabled for startup?

**Comment by StCyr** [comment]
> Okay, and I guess if you open the task manager and go to the tab "Startup", nextcloud.exe is enabled for startup?

No, it isn't

PS: I forgot to add that it stopped starting automaticaly at boot after an update

**Comment by FlexW** [comment]
Okay. Have you enabled it and does it start automatically again? Was that a Nextcloud update or something else?

**Comment by StCyr** [comment]
It's not even there:

![image](https://user-images.githubusercontent.com/8179031/112685048-4763b780-8e74-11eb-802b-e5b5a993d480.png)


Yes, yes, after an update of the nextcloud client

**Comment by allexzander** [comment]
@StCyr What happens if you add Nextcloud.exe to a startup manually? Like described here https://docs.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys?

**Comment by StCyr** [comment]
@allexzander 

Ah! That was it: For some reason my HKCU\Software\Microsoft\Windows\CurrentVersion\Run\Nextcloud key was set to C:\Program Files(x86)\Nextcloud\Nextcloud.exe while Nextcloud.exe is really in C:\Program Files\Nextcloud. Probably some update issue....

I've changed it and will tell you how things go at next reboot.

**Comment by allexzander** [comment]
> @allexzander
> 
> Ah! That was it: For some reason my HKCU\Software\Microsoft\Windows\CurrentVersion\Run\Nextcloud key was set to C:\Program Files(x86)\Nextcloud\Nextcloud.exe while Nextcloud.exe is really in C:\Program Files\Nextcloud. Probably some update issue....
> 
> I've changed it and will tell you how things go at next reboot.

@StCyr Probably because of using X86 MSI installer. Things can get messy when mixing X64 and X86 installers. So, best way is to remove the app and install a proper (in most cases X64) version.

**Comment by StCyr** [comment]
Ok, I confirm it works now. 

Thanks for the help @allexzander and @FlexW
