### ISSUE TITLE
Nextcloud folder icon missing/wrong after fresh install (RC2)

### ISSUE THREAD

**Issue by bavarialogy** [nextcloud/desktop#3037]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The nextcloud folder should be created with an icon that looks like something cloudy (e.g. nextcloud.ico from bin folder).

### Actual behaviour
The folder icon is set to something non-existing, resulting in an icon that looks like a .exe file without an embedded icon.

### Steps to reproduce
1. Fresh install on windows 10, create new folder during setup wizard (I think I typed in "Nextcloud" manually)

### Client configuration
Client version:
Nextcloud-3.2.0-rc2-x64

Operating system: MS Windows 10.0.19042.870

OS language: English (US)

Qt version used by client package (Linux only, see also Settings dialog): -none-

Client package (From Nextcloud or distro) (Linux only): -none-

Installation path of client: default (C:\program files\nextcloud)

### Server configuration
Nextcloud version: NC 21.0.0 (fpm, nginx)

**Comment by splitt3r** [comment]
This could be a duplicate of https://github.com/nextcloud/desktop/issues/3033 or https://github.com/nextcloud/desktop/issues/3035

**Comment by tob123** [comment]
I encountered this during upgrading the client (removal old client, install new client), i did no reboots in between.

**Comment by camilasan** [comment]
Could you try rebooting? 

#3033 is the application icon missing, this is the status icon. Perhaps related but not the same.

**Comment by bavarialogy** [comment]
I have now manually set the icon to Nextcloud.ico (via folder properties). This works for me as a workaround, so I'll only leave this open for tracking the bug itself.

**Comment by johkoenig** [comment]
Is there a change this is connected to vfs? I converted my only synced folder to vfs (with the known issues), the icon was gone. Then, I converted back, some time later the icon was there again.

**Comment by bavarialogy** [comment]
Unfortunately I can't verify if this happens when enabling VFS because I can't disable it anymore (My Nextcloud desktop client freezes everytime I open the settings). Think my installation might be too big for a technical preview (got 2.348.206 files, most of those within the sync scope)..

**Comment by dbolton** [comment]
Where can I find Nextcloud.ico to manually fix this on my computer? 

I lost the icon after wiping my client computer and restoring from backup. (Windows 10).

**Comment by FlexW** [comment]
I recommend you to just reinstall the client, the .ico files gets generated during the build process. You can not just download it.
