### ISSUE TITLE
Client 3.2 RC2 - Client freeze during sync (? vfs link creation)

### ISSUE THREAD

**Issue by cscholz** [nextcloud/desktop#3041]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client 3.2 RC2 freeze during the creation of vfs file links. Client get unresponsive.
It seems that the client did not died. If you I long enough (15- minutes) the client will eventually respond again. But then usually aborts with a timeout error. Unsure if the timeout comes from the server or the client due to the unresponsiveness.

This behaviour occured with two different backend server.

### Actual behaviour
Don't freeze and finish sync or throw an exception earlier to inform the user about a delay

### Steps to reproduce
unknown

### Client configuration
Client version: 3.2 RC2

Operating system: Windows 10 (Build 19043.867)

OS language: German

Installation path of client: Standard Path

### Server configuration
Nextcloud version: 20.0.0.18

### Logs
I've created a debug log after the client get responsive again. I don't want to post it here in its entirety though. I'd like to put it in a Nextcloud Drop Zone for the developers.

![image](https://user-images.githubusercontent.com/3398846/112628364-18792180-8e33-11eb-86dc-1579a5dc21cd.png)

![image](https://user-images.githubusercontent.com/3398846/112628244-ea93dd00-8e32-11eb-8a3e-d6a99029489f.png)

**Comment by camilasan** [comment]
You can upload the logs here: https://cloud.nextcloud.com/s/K7rNAFfPYdkbydM

**Comment by cscholz** [comment]
I've uploaded the log files (20210326.zip).

**Comment by bavarialogy** [comment]
Experienced the same but only on initial sync with lots of items.

**Comment by allexzander** [comment]
This was fixed in https://github.com/nextcloud/desktop/pull/3057
