### ISSUE TITLE
Nextcloud Desktop Client login trouble

### ISSUE THREAD

**Issue by Eutectico** [nextcloud/desktop#3047]
### Actual behaviour

When adding a new account in the Nextloud Desktop-client, some Nextcloud servers open the credentials in the desktop app and others open a browser where the client can log in.

```
Is there any way to control this? which is used only the application and not the browser?
```
### Client configuration
Client version: 3.1.3
Operating system: Windows Server 2019 Standard
OS language: DE

### Server configuration

Nextcloud-1 version: 14.0.1 
Nextcloud-2 version: 20.0.8

Thanks

**Comment by FlexW** [comment]
I'm not sure I understand what you mean because there is only one way to login in at the moment and that way goes through the browser. If you really use a server with version 14 then there might be not the login flow 2 implemented and therefore the client falls back to the old login flow. Server version 14 is not anymore supported and you should upgrade that server.

**Comment by Eutectico** [comment]
Yes I know that version 14 is not supported and we have to update it. The problem we have is that in the new version the users have to check in the Browser, while in version 14 the client checks in a desktop client window.

The problem we have is that the users have only Internet Explorer installed and the link generated by the Nextcloud Desktop Client is blocked by our proxy. 

This problem does not arise when using version 14 of the server.

**Comment by FlexW** [comment]
Why is this link blocked? Is there something in it that the proxy does not like? Because if the host is blocked by proxy you won't be able to sync anything. There is currently no other way then going through the browser to login to your account.

**Comment by Eutectico** [comment]
Ok, thanks anyway. 
We will have to find another solution to our problem.
