### ISSUE TITLE
sync-exclude.lst Does not work

### ISSUE THREAD

**Issue by talesam** [nextcloud/desktop#3055]
I performed a simple test, put it in the "**.sync-exclude.lst**" `.ssh` file, which is where the ssh keys are, then I copied this directory (.ssh) to a folder that is in sync with the server. The .ssh directory was automatically synchronized, ignoring what is inside the **.sync-exclude.lst** file that was not to be synchronized.

**Comment by patagonaa** [comment]
seems to be duplicate of #2728

**Comment by FlexW** [comment]
Thanks @patagonaa. Closing because duplicate of #2728
