### ISSUE TITLE
Full Re-sync..... why !

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/desktop#3062]
Hi,

This has always been a recurring issue over the years

Im running a recent 'daily build', 3.1.81

For reasons i have never understood, the client decides to do a complete re-sync.  The 2 bummers are:

- it takes an age
- it invariably overwrites some files, loosing me data

Anything i get provide log wise and from where ?

Regards

ZT

**Comment by allexzander** [comment]
Hello @zippytiff. When does full-resync happen? After installing a new build? Or, does it happen on every launch? Also,  which build exactly you are using? You've mentioned **3.1.81** as a **recent daily build**, but, recent dailies are **3.1.83**.

Also, could you attach your logs archive here? You can generate it by going into `Tray->Settings->Create Debug Archive`.
Please, also, try creating the debug logs archive right after the complete resync happens again.
Thx.

**Comment by zippytiff** [comment]
hi,

Version 3.1.81daily-Win64 (build 20210322)

When i checked the debug archive, i could see it didnt go back to Thursday (when it last happened)

Where are those log files locations ?

I will update to latest 'daily' in mean time

Regards
ZT
