### ISSUE TITLE
CLDAPI error

### ISSUE THREAD

**Issue by sergeevabc** [nextcloud/desktop#3063]
Windows 7 x64, Nextcloud [3.1.83.20210405][1].

![](https://i4.imageban.ru/out/2021/04/05/2951f61d3e9587fe519cead1f592aae0.png)

[1]: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-3.1.83.20210405-daily-Win64-x64.msi

**Comment by allexzander** [comment]
@sergeevabc Cloud Filter API is not supported on Windows 7 according to Microsoft. https://docs.microsoft.com/en-us/windows/win32/cfapi/cloud-files-api-portal Windows 10 build 1709 is required at least.

You can still use the latest stable 3.1.3 build if you are not going to use the VFS.

I am going to discuss Windows 7 issues internally tomorrow and come back with more details.

**Comment by sergeevabc** [comment]
@allexzander, I tried (fresh) 3.1.83, because (stable) 3.1.3 displays a black rectangle instead of recent activity when I click a tray icon. So for now I stick to ownCloud 2.7.6 which has no such errors.

**Comment by allexzander** [comment]
> @allexzander, 3.1.3 displays a black rectangle instead of recent activity when I click a tray icon

This is unfortunate. You may as well want to attach logs from 3.1.3 here if possible.

**Comment by allexzander** [comment]
> > @allexzander, 3.1.3 displays a black rectangle instead of recent activity when I click a tray icon
> 
> This is unfortunate. You may as well want to attach logs from 3.1.3 here if possible.

Or, even batter @sergeevabc Create a separate issue for "black rectangle" with logs attached.
Thx.

**Comment by allexzander** [comment]
@sergeevabc Alright. I've discussed it with more people. Unfortunately, we do not support Windows < 10 anymore. Some pages are not updated yet and claim Windows 7+ support, but, we are going to change that. On the download page, I've mentioned earlier, we only provide a version for Windows 10.

**Comment by CacheMinimal** [comment]
As suggested in #3081, would it be a good idea to add a launch condition in the MSI installer to prevent it installing on unsupported platforms? There is a good example, including detecting Windows versions, here:

http://etutorials.org/Programming/Mastering+visual+studio+.net/Chapter+6.+Setup+and+Deployment/6.11+Launch+Conditions/

**Comment by allexzander** [comment]
> As suggested in #3081, would it be a good idea to add a launch condition in the MSI installer to prevent it installing on unsupported platforms? There is a good example, including detecting Windows versions, here:
> 
> http://etutorials.org/Programming/Mastering+visual+studio+.net/Chapter+6.+Setup+and+Deployment/6.11+Launch+Conditions/

Yes, this will get implemented soon.

**Comment by pm-pm** [comment]
> 
> 
> @allexzander, I tried (fresh) 3.1.83, because (stable) 3.1.3 displays a black rectangle instead of recent activity when I click a tray icon. So for now I stick to ownCloud 2.7.6 which has no such errors.

Just for notification:
I have the same problem since Nextcloud 3.x Client. The black rectangle "only" appears on 1 of 4 Win7 Computers.
Maybe a "dll" Missing? I have no idea or clue. Re-Installation does not help.

**Comment by pm-pm** [comment]
> @sergeevabc Alright. I've discussed it with more people. Unfortunately, we do not support Windows < 10 anymore. Some pages are not updated yet and claim Windows 7+ support, but, we are going to change that. On the download page, I've mentioned earlier, we only provide a version for Windows 10.

Windows 7 OS is heavily used by non-mainly-internet-access-computers.
For writing a letter and watching webmail with latest FF a W7 computer is enought. ;-)

**Comment by TheMatzy** [comment]
The same error occurs under Windows Server 2016 Build 1609.

**Comment by OutbackMatt** [comment]
Same error occurs under Server 2012 R2
This is still a Microsoft supported OS for another 2.5 years
https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2

**Comment by allexzander** [comment]
@OutbackMatt 
Apparently, you're going to need Windows Server 2019 to use the latest desktop client with Cloud Filter API. Though, the Server is not exactly intended for using it as a normal Windows (Home or Enterprise).

We'll add a condition into the 3.2.1 installer to not allow installation if no CFAPI is available.

**Comment by allexzander** [comment]
@mgallien What do you think about this discussion?

**Comment by tromlet** [comment]
> @OutbackMatt
> Apparently, you're going to need Windows Server 2019 to use the latest desktop client with Cloud Filter API. Though, the Server is not exactly intended for using it as a normal Windows (Home or Enterprise).

I mean, if nextcloud/nextcloud is advertising itself as a solution for businesses (which it *does*)... then support for a Windows Server version through its lifecycle should be the *minimum* target. These can be (and are - often) used as terminal servers, and people are going to want to have the desktop client to interact with their Nextcloud files in their day-to-day workflow, without the interruption of having to go fetch a file through a browser and then re-sync it - because that would obviously be a... dramatic and silly interruption in a user's workflow.

At the very least, some kind of official guidance (like, in the docs) as to what version work with which OSes, and a pledge to support base functionality for these versions through the supported lifecycle of the OS would be appreciated... though it'd probably just be easier to offer good, backwards compatibility. Seems like that'd be easy to do on a Microsoft platform.

**Comment by wedeen** [comment]
Hello, I have the same error:
Windows 8.1
try to install nextcloud-client 3.2.0, downloaded from the german nextcloud website.
How can I fix it, I have to use nextcloud.

**Comment by FlexW** [comment]
@wedeen For now pick a older release. This will work on Windows 8.1. For example https://github.com/nextcloud/desktop/releases/tag/v3.1.3

**Comment by Amr0d** [comment]
I have this problem on Windows 10 20H2 v2. How can I install the missing files?
