### ISSUE TITLE
Talk icon

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/desktop#3067]
Hi

Just updated to the lastest overnight build (Nextcloud-3.1.83.20210406-daily-Win64-x64) , last update i did was march

Why has the link to 'online nextcloud' which took me to the home page, now been replaced with just a link to the 'Talk' feature ?

Where can i change this ? as before i deploy i will have to change this to the home page for all users

Thanks

ZT

**Comment by FlexW** [comment]
Could please be a little bit more specific what you mean. Maybe provide a screenshot. There is still a Talk icon that takes you to Talk if you click on it.

**Comment by zippytiff** [comment]
Hi

See attached.

I did just notice that if i restart the nextcloud client, for a moment i saw/see the old 4 icon icon

Hope this helps

ZT[](url)
![talk_icon](https://user-images.githubusercontent.com/31544391/113724191-04160e00-96ea-11eb-896e-42fa91cf7d5a.jpg)

**Comment by FlexW** [comment]
Okay I understand. That issue is known and should be resolved in the final version. Should than be as it was before. @camilasan I think you wanted to provide a pr for that? Maybe you can close that issue here if your pr is merged :)

**Comment by camilasan** [comment]
>  @camilasan I think you wanted to provide a pr for that? Maybe you can close that issue here if your pr is merged :)

Yes.

**Comment by camilasan** [comment]
Fixed with #3069
