### ISSUE TITLE
Suggestion for Files conflict between server and local

### ISSUE THREAD

**Issue by 614User** [nextcloud/desktop#3074]
Hi, 

I am using the current Nextcloud-version and am happy with it excepting when there is conflicts between files on the computer and on the server. I am using EndNote and it has a lot of sub-files. When Endnote is opened and Nextcloud tries to connect with the server, there is file conflicts. Because Endnote (or other programs as well) is using a file(s), and Nextcloud cannot overwrite an opened file(s), it keep both server and local versions. Unlucky there is more than 1 file are opening (in my case working with Endnote). Therefore, Nextcloud offers me two options (both of them have in my opinion some drawbacks)

- open each folder and delete conflicts file, which I do not know if it is the right one to delete (because its name is renamed to \"conflicted copy ...\", but not explicit written \"server\" or \"local\" 

- click on the error showing in the Nextcloud popup window and choose \"server\" or \"local\" for EACH file. So I need to click 5 times for each file, which is very very time consumed because there is more than 5 of them. 

I would do the second option and it would be very nice if Nextcloud opens for me only one list of all files to choose \"server\" or \"local\" and at the end I can click on \"Ok\". It would save a lot of my working time. 

Thanks you for reading this suggestion and hope that this option will be soon realized. 

Best regards!

**Comment by TuzelKO** [comment]
Faced a similar problem. After copying a directory with more than 5000 small files during synchronization, the laptop periodically fell asleep. Now the application requires to resolve conflicts... Through the window with the resolution of the conflict of one file. How do I resolve 4000 conflicts?

I really need this feature...

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
