### ISSUE TITLE
Request for option to disable Windows Explorer Integration

### ISSUE THREAD

**Issue by Pingger** [nextcloud/desktop#3078]
Hi,

because I very often stumble upon #1393. I hereby request the feature to disable the File and Folder Icon Overlays.

![image](https://user-images.githubusercontent.com/4761298/114217547-9b889480-9968-11eb-94e0-b830d11b3c55.png)
with File and Folder Icon Overlays I mean those green thingies in the this screenshot.

Greetings
  
  
  

### PS: Workaround
Delete/move to a different Folder:
\<Nextcloud\>/shellext/NCOverlays.dll
When this DLL can't be loaded, the Performance issues are gone(, but so are the overlay icons). (A Reboot might be required, to purge the DLL from memory)

**Comment by mgallien** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by endurance1968** [comment]
Windows explorer becomes unusable slow for bigger? installations. A simple rename of a file or folder takes 10s (SSD and AMD R9 with 128GB RAM so on a fast machine). You start editing then the systems hangs wait then continue to type.. wait again until synced.
As consequence I alway pause sync and only manually trigger a sync - but this is not the idea of nextcloud. Frequently I have also all desktop icons with an overlay checkbox (which should not be there as desktop is not part of nc path). But this is a different annoying bug with the overlay.
I now also remove the DLL let see if this temporarily helps.

**Comment by Pingger** [comment]
@mgallien As you can see: NO IT IS NOT LOW! #1393

**Comment by FernandoMarques-Santos** [comment]
Not because you guys commented soon, but I was searching for a way to minimize the visual impact of the overlays without vanishing the context menu feature. The green circle is too overwhelming ([see this post I found for the same thing](https://help.nextcloud.com/t/change-overlay-icon-with-alternative/97017). I'm patient. I will wait until this gets traction.

**Comment by Sieboldianus** [comment]
A workaround is to create ntfs Junctions for folders and work from there. 

e.g.:

- 1: c/nextcloud/myfiles/folder1
- 2: d/myfiles/folder1
Add `1` to your Nextcloud sync, but work in `2`. Only `1` will show the Nextcloud icons.

```cmd
mklink /J link_name target_dir
mklink /J "D:\myfiles\folder1" "C:\nextcloud\myfiles\folder1"
```
