### ISSUE TITLE
CLDAPI Error At Startup

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/desktop#3079]
Windows 10 Enterprise LTSB 2016, fresh install of Nextcloud 3.2.0-rc3 I'm seeing this error message after every reboot. I believe this is a similar issue to #3063 but I'm running Windows 10, not Windows 7. So apparently this is not isolated to Windows 7.

Regardless, could someone please explain what CLDAPI.dll is? I assume it's related to the new VFS but more explanation would be appreciated.

**Comment by FlexW** [comment]
What is the exact version of your Windows 10? DLDAPI.dll is a part of the file cloud files api from Windows. Without this library the new virtual drive feature does not work. I think support for this was added during Windows 10 version 1709. You can read more about it [here](https://docs.microsoft.com/en-us/windows/win32/cfapi/cloud-files-api-portal). Maybe your Windows 10 version is to old?

**Comment by linucksrox** [comment]
Thank you! That explains it, LTSB 2016 is older than 1709 and doesn't receive feature updates. Time for me to upgrade.

I would just suggest mentioning this minimum version in the release notes.

**Comment by linucksrox** [comment]
Thinking more about this, I sill consider this a bug. In my opinion it should either check the Windows version during installation and fail to install because Windows is too old and unsupported, or disable the cloud sync/virtual file system features in that case. Allowing it to install and leaving it in a broken state doesn't make a lot of sense to me.

**Comment by FlexW** [comment]
@linucksrox Sorry, I forgot to remove the label. I opened a issue about checking the Windows version while installing yesterday https://github.com/nextcloud/desktop/issues/3083.
