### ISSUE TITLE
AppImage not starting

### ISSUE THREAD

**Issue by lukrop** [nextcloud/desktop#308]
After making the AppImage executable using `chmod a+x` I'm not able to start it.

```bash
lukrop ~/downloads % ./Nextcloud-2.3.3-x86_64.AppImage     
dup2 error: Bad file descriptor
```

Thats happening on voidlinux.

Maybe also related to #235? I'm running i3 though.

**Comment by camilasan** [comment]
Did you try what was suggested at #235?

**Comment by lukrop** [comment]
```
LD_LIBRARY_PATH=/usr/lib QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins/platforms ./Nextcloud-2.3.3-x86_64.AppImage
```

Does *not* yield a different result. Doesn't look like it's a Qt issue like in #235 but something else. Hence the new ticket.

**Comment by esbeeb** [comment]
Indeed, when I add those variables at the start of the command line, then I can execute Nextcloud Desktop client 2.3.3 in my Manjaro Linux 17.1.10.

Thanks, @lukrop!  :)

**Comment by mgallien** [comment]
Is this still an issue ?
I would like to know what we can do here but will need information from you.
