### ISSUE TITLE
CLDAPI.dll is missing, Nextcloud Desktop 3.2.0 on Windows 7 32-bit

### ISSUE THREAD

**Issue by CacheMinimal** [nextcloud/desktop#3081]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud Desktop installs and allows the user to interact with the product.

### Actual behaviour
Installation completes successfully but any attempt run it produces an error about CLDAPI.dll, which is missing.

### Steps to reproduce
1.  Download Nextcloud Desktop from https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.2.0-x86.msi
2.  Run the installer and allow a restart when prompted
3.  Double-click the Desktop Nextcloud icon and the following error is produced:

![Error](https://user-images.githubusercontent.com/27230720/114308527-3b1a6400-9adc-11eb-9bef-153ca77b1411.png)

4. Clicking OK closes Nextcloud, leaving no functionality available

### Client configuration
Client version: 3.2.0

Operating system: Windows 7 Professional SP1 32-bit (Version 6.1.7601)

OS language: English (United Kingdom)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Logs
Unavailable as no MSI installer log in %temp% and the client will not start.

**Comment by Id3aFly** [comment]
Hi, 
have a look at #3063 especially to the answer in https://github.com/nextcloud/desktop/issues/3063#issuecomment-813860515.
It is stated that:  `we do not support Windows < 10 anymore`

**Comment by CacheMinimal** [comment]
That certainly explains the behaviour once installed.  Would it be a good idea to add a launch condition in the MSI installer to prevent it installing on unsupported platforms?  There is a good example, including detecting Windows versions, here:

http://etutorials.org/Programming/Mastering+visual+studio+.net/Chapter+6.+Setup+and+Deployment/6.11+Launch+Conditions/

**Comment by FlexW** [comment]
I will close this in favour of https://github.com/nextcloud/desktop/issues/3083
