### ISSUE TITLE
Add check to installer to prevent installation on too old Windows versions

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3083]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud Desktop client should not be allowed to installed on Windows versions that don't provide the CLDAPI.dll.

### Actual behaviour
Nextcloud Desktop client is allowed to be installed on Windows versions that provide CLDAPI.dll.

### Client configuration
Client version: 3.2.0-rc3

Operating system: Windows

**Comment by rakekniven** [comment]
We had first report in the forum and myself ran in the same issue at an old VM with WIN7.
Tested with v3.2.0 final.

**Comment by GGD159** [comment]
my Windows version is Windows 10 Enterprise 2016 LTSB version 1607 (build 14939.4350). This version is a supported by Microsoft for 10 years. So I have a valid and fully supported Windows version, but I still get the above error message.
I think the license check must be done in another better way to exclude not valid Windows versions from the desktop client.
cu

**Comment by FlexW** [comment]
@GGD159 If your Windows version does not ship the CLDAPI.dll then you will get this error. For example Windows 8.1 is still supported by Microsoft but does not contain CLDAPI.dll. Also not all versions of Windows 10 ship CLDAPI.dll.
