### ISSUE TITLE
Show note on receiving share

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#3102]
See https://github.com/nextcloud/server/issues/21557

**Comment by tobiasKaminsky** [comment]
@camilasan I post it here to not flood overview issue with Desktop-only info.

You can see here that the incoming note is missing:
![image](https://user-images.githubusercontent.com/5836855/132461278-86e78ee0-4522-442a-a962-33a96240f524.png)


A second/related problem is if the the other using disallowed resharing, then there is no way to show this at all.
(On Android we then still show the same view, but have the search replaced by "resharing not allowed"
![image](https://user-images.githubusercontent.com/5836855/132461099-1494fa5b-0e6c-4570-831b-0e16a368574e.png)
