### ISSUE TITLE
Nextcloud 3.2 client <for more information click here> leads to nonexisting page.

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/desktop#3118]
Downloading nextcloud client 3.2 from site, installing, client works as expected.

Right clicking icon in taskbar and selecting settings, then general en clicking on About: For more information click <here> leads to a none existing page on nextcloud.com:

https:
![image](https://user-images.githubusercontent.com/3179748/114660994-84460000-9cf6-11eb-9f99-15c2243ad457.png)
//docs.nextcloud.com/desktop/3.2/

**Comment by mgallien** [comment]
Thanks for the report.

Sorry for the missing link, we are working on fixing it.

**Comment by mgallien** [comment]
Sorry, I forgot to test again and it is now fixed.
