### ISSUE TITLE
Minimum CMake version

### ISSUE THREAD

**Issue by nicolasfella** [nextcloud/desktop#3134]
@FlexW and I have been doing some cleanup on the CMake code. Being able to rely on a recent-ish CMake version and their features would be helpful there. The currently stated minimum version is 3.6, which was released in 2016.

In KDE we recently made a push for 3.16 as minimum required version. I propose we do the same here.

On Windows and macOS it's rather easy, there is no reason not to use the latest available version. On Linux we need to take into account what distros provide. CMake 3.16 is shipped by Ubuntu Focal, but not by e.g. Ubuntu Bionic or Debian Stable. This matches our support for Qt where we support Focal but not Bionic or Debian Stable.

There might be the case of someone wanting to build Nextcloud on a distro with an older CMake, but fortunately CMake is easy to backport, for example there is an official PPA for older Ubuntu.

Thoughts?

**Comment by mgallien** [comment]
I am currently trying to get a summary of the different stuff we are doing in CI, automated tests and build environments. Looks like updating stuff has not always been easy in the past.
That said, I would like to do it.

**Comment by claucambra** [comment]
CMakeLists.txt currently marks minimum required as 3.16 so I will close
