### ISSUE TITLE
Right align folder icon in main dialog

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#3137]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behavior

The folder icon in the main dialog should be right aligned (if you don't have Talk installed).

![image](https://user-images.githubusercontent.com/1869584/114841960-af088500-9dd8-11eb-8a81-dca06d845a36.png)

### Client configuration
Client version: 3.2.0

Operating system: Windows 10

OS language: English

**Comment by FlexW** [comment]
Resolved in 3.3.0
