### ISSUE TITLE
Sync with virtual file error.

### ISSUE THREAD

**Issue by Chuanbin-Wang** [nextcloud/desktop#3139]
### Expected behaviour
Sync with virtual file succeed. such as the OneDrive.

### Actual behaviour
sync error.
![image](https://user-images.githubusercontent.com/76732400/114873240-a9895a00-9e2d-11eb-8b8d-269e97364353.png)
![image](https://user-images.githubusercontent.com/76732400/114870682-0b949000-9e2b-11eb-825e-20cc67951032.png)

__When I disable the virtual file support, the sync is succeed.__
![image](https://user-images.githubusercontent.com/76732400/114871984-71cde280-9e2c-11eb-86d0-91c40b7a9cc7.png)

### Steps to reproduce
1. Add sync folder 
2. Enable virtual file support.

### Client configuration
Client version: 3.2

Operating system: Win10 20H2 

OS language: CN

Installation path of client: default for C:\Program files\Nextcloud.

### Server configuration
Nextcloud version: docker with latest

Storage backend (external storage): linux with xfs format.

### Logs
1. Client logfile: 
[20210415_2031_owncloud.log.0.gz](https://github.com/nextcloud/desktop/files/6317970/20210415_2031_owncloud.log.0.gz)

I can find the error message:
![image](https://user-images.githubusercontent.com/76732400/114871357-cb81dd00-9e2b-11eb-86aa-1e8670efce17.png)

**Comment by uberiain** [comment]
I have the same problem with this configuration:

Client configuration
Client version: 3.2

Operating system: Windows 10.0.17763.1879

OS language: ES

Installation path of client: default for C:\Program files\Nextcloud.

Server configuration:
Ubuntu 20.04

Nextcloud version: 21.0.1


Logs:
![Nextcloud 3 2 0](https://user-images.githubusercontent.com/29492430/114997053-5fd55980-9e97-11eb-88e4-772b220e5bce.PNG)
[Nextcloud 3.2.0.zip](https://github.com/nextcloud/desktop/files/6323666/Nextcloud.3.2.0.zip)

Same machine with Nextcloud desktop 3.2.0-rc3 is working without any problem.

**Comment by wagnbeu0** [comment]
I have the same problem:
I have setup a new computer to test the virtual file system because migrating my existing NC installation on my desktop was causing other problems so I wanted to test it from scratch.
On my server I have an folder “Photos” which has about 300 GB and almost 60.000 Files sorted by Year.
When I now connect the new computer to my NC server, it starts scanning all the folders. The Photos folder cannot be scanned completey, everytime it pops up with a new error message, sometimes with an “error” with a file in 2011, sometimes with an file in 2017, never the same file.

Then it starts scanning again from scratch so I am in a loop.

I use NC21.0.1 and Win10 Pre x64 with Desktop Client 3.2.0

**Comment by uberiain** [comment]
I have found that if I install the X86 version the system works fine. Can it be a problem of the msi X64?
Can someone with the same problem check this out?

**Comment by wagnbeu0** [comment]
I installed the 32bit 3.2.0 Client on two Win10 computers, but the error is still there. So for me no difference.

**Comment by mgallien** [comment]
Thanks for your report.
This issue is already fixed by #3187 .

**Comment by JustACasual** [comment]
sorry to ask, but I just downloaded and started syncing (local folder D: empty) and get this error for each virtual file it tries to create.
Should this already be fixed or is this not yet in the current release? I am on Win10 and Client Version 3.2.1 
![grafik](https://user-images.githubusercontent.com/55889353/120098843-78908a80-c138-11eb-99e9-8aec16a2a46f.png)
![grafik](https://user-images.githubusercontent.com/55889353/120098850-85ad7980-c138-11eb-87bf-26034a89bb95.png)

**Comment by FlexW** [comment]
@JustACasual Syncing a root directory like D: will never work on Windows. That is because of a limitation with the Windows API. OneDrive does also not allow it. The next release will include a warning when users try to do that.
