### ISSUE TITLE
[3.2.0] New RightClickText not translated

### ISSUE THREAD

**Issue by Numrollen** [nextcloud/desktop#3140]
Im not sure if its a bug but on german windows 10 the 2 phrases

Keep this on this device
Free up space.

are not translated in the short menu.

![image](https://user-images.githubusercontent.com/7830015/114897131-3d98f880-9e11-11eb-9da4-9d551abb198b.png)

**Comment by allexzander** [comment]
@Numrollen These 2 entries are not inside "Nextcloud", so, I assume it's a bug of Windows. Do you mind checking how these look with OneDrive?

**Comment by johkoenig** [comment]
@allexzander They are translated correctly when using OneDrive. Also, OneDrive places the commands "Sharing" and "Show online" directly next to these, and not into a seperate submenu, as nextcloud does. (For information only, I dont want this to be changed for nextcloud. Submenu is fine).

**Comment by johkoenig** [comment]
Problem still exists in 3.2.1

**Comment by johkoenig** [comment]
Problem still exists in 3.2.1

**Comment by johkoenig** [comment]
Problem still exists in 3.2.2

**Comment by johkoenig** [comment]
This bug report did not receive an update in the last 4 weeks, so it must be assumed that this bug is still present. Please take a look again and update the issue with new details, otherwise the users will have to live with this issue much more than 2 weeks. Thank you!

**Comment by DegrangeM** [comment]
Problem still exist in 3.4

**Comment by hartsberger** [comment]
Problem still exists in 3.5.0

**Comment by hartsberger** [comment]
Problem solved with 3.6.0

![2022-09-07 12_07_56-A-RDS-TEST01](https://user-images.githubusercontent.com/60740965/188852589-ff4eac01-110f-4f8e-96b8-984a8adda0a0.png)

**Comment by allexzander** [comment]
> Problem solved with 3.6.0
> 
> ![2022-09-07 12_07_56-A-RDS-TEST01](https://user-images.githubusercontent.com/60740965/188852589-ff4eac01-110f-4f8e-96b8-984a8adda0a0.png)

Interesting... We did not fix it.
