### ISSUE TITLE
Environment variables in local paths aren't resolved

### ISSUE THREAD

**Issue by manuth** [nextcloud/desktop#3141]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce
1. Install the client
2. Add a folder sync with a path containing an environment-variable (using windows- or unix-style) such as `%USERPROFILE%`/`$USERPROFILE` or `%LOCALAPPDATA%`/`$LOCALAPPDATA%`

### Expected behaviour
The client should accept the provided path.

### Actual behaviour
The client states that the path could not be found (as it doesn't resolve the environment-variables).

### Client configuration
Client version: 3.1.3

Operating system: Windows 10

OS language: German (Switzerland)

Installation path of client: `C:\Program Files\Nextcloud\`

### Server configuration
Nextcloud version: 21.0.1

Storage backend (external storage): Issue is the same for all backends

### Logs
1. Client logfile: _Will be provided if necessary_

2. Web server error log: _Will be provided if necessary_

3. Server logfile: nextcloud log (data/nextcloud.log): _Will be provided if necessary_

**Comment by FlexW** [comment]
Where is the place in the GUI where you want to add a folder with environment variables in the path?

**Comment by manuth** [comment]
I'd like to type the environment variables in the `Add folder-sync` dialog and have them included in the `nextcloud.cfg`-file.
Under this circumstance one could, for example, sync to `${LOCALAPPDATA}` even if the username changes.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
