### ISSUE TITLE
Provide a feature for exporting and importing settings (such as folder-sync preferences)

### ISSUE THREAD

**Issue by manuth** [nextcloud/desktop#3142]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Provide a feature for exporting and importing settings
Currently you have to add each folder sync by yourself which might be quite a pain (especially if you have a lot of folder syncs for instance when using Nextcloud for syncing savegames).

I'd love to see a feature for exporting and importing folder sync preferences using nextcloud

**Comment by FlexW** [comment]
Is it enough for you to copy your `nextcloud.cfg` file around? This file should contain all your folder configuration settings.

**Comment by manuth** [comment]
Yes, as far as I can see, the `nextcloud.cfg` (and maybe also `sync-exclude.lst`) should be enough.

**Comment by FlexW** [comment]
Okay. I will close that request then.
