### ISSUE TITLE
[3.2.3] Clicking on the 3 dots button next to filesync status is really slow

### ISSUE THREAD

**Issue by eibex** [nextcloud/desktop#3143]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When clicking the button (highlighted in red below) the menu comes up immediately
![image](https://user-images.githubusercontent.com/40539455/114947686-dea5a480-9e4d-11eb-841a-224ceeb19276.png)

### Actual behaviour
The menu comes up after 5 seconds or more, making you wonder if you actually pressed the button or if it does anything.
The CPU usage doesn't even spike that much (from 2% to 10% at most).

### Steps to reproduce
1. Click the button highlighted in the picture above

### Client configuration
Client version: 3.2.0

Operating system: Win10

OS language: English

Installation path of client: Default

### Logs
```
[...]
2021-04-16 00:58:27:863 [ warning nextcloud.sync.vfs.cfapi ]:	Couldn't find pin state for regular non-placeholder file "C:\\Users\\***USERNAME***\\Nextcloud\\Folder1\\Folder2\\file1.ext"
2021-04-16 00:58:27:863 [ warning nextcloud.sync.vfs.cfapi ]:	Couldn't find pin state for regular non-placeholder file "C:\\Users\\***USERNAME***\\Nextcloud\\Folder3\\Folder4\\file2.ext"
2021-04-16 00:58:27:863 [ warning nextcloud.sync.vfs.cfapi ]:	Couldn't find pin state for regular non-placeholder file "C:\\Users\\***USERNAME***\\Nextcloud\\Folder5\\Folder6\\file3.ext"
2021-04-16 00:58:27:863 [ warning nextcloud.sync.vfs.cfapi ]:	Couldn't find pin state for regular non-placeholder file "C:\\Users\\***USERNAME***\\Nextcloud\\Folder7\\Folder8\\file4.ext"
[...]
```
There is a line for this for basically every file in the Nextcloud directory. I actually think this is the reason the button is slow: it's writing a lot of lines to the logfile.

All those lines are generated whenever I press the button.

**Comment by Githopp192** [comment]
same to be .. did the NC **Upgrade to 21.0.1** some days ago .. 
I did also notice that with three points - but only after i enabled the "**Virtual Agent" ..** 
When you then try to click on three points .. it takes more than 15-30 Sec., that the GUI will show the **right-click context.**

**Comment by MitchellHicks** [comment]
The Pause went away for me when i upgraded to 3.2.1 along with a number of other issues...

**Comment by eibex** [comment]
> The Pause went away for me when i upgraded to 3.2.1 along with a number of other issues...
I can still replicate in 3.2.1

**Comment by johkoenig** [comment]
still present on 3.2.2 if vfs is enabled

**Comment by MitchellHicks** [comment]
yes it is... i'm not sure how i got it working on one computer.. tried a
new install and enable on a new computer...same issues had to use the old
method...

**Comment by johkoenig** [comment]
still present on 3.2.3 if vfs is enabled

it actually got worse. Now, the client freezes fo a couple seconds.

**Comment by rockpham** [comment]
This issue is also present on my set up on 3.2.3 with vfs enabled

**Comment by MitchellHicks** [comment]
Still having this issue with 3.2.4 and 22 I think of nextcloud...

after some digging i think it's related to not syncable files on the cloud
side... somehow i had a number of windows shortcuts saved on the cloud..
when i removed them from the cloud and the local folders that instance
completed it's sync...

but i am still having client computers i can't activate the VFS on or it
just hangs explorer/nextcloud requiring a forced end task then removal of
the hidden .sync files and restart.. but still locks up... after random
keyboard mashing with forehead have been able to switch off VFS and
continue with life...

Mitch

**Comment by mgallien** [comment]
This is fixed with the 3.3.0 release.
Please @eibex can you test with the latest one (3.3.1) and close the report if it is working for you or send us the logs with 3.3.1 ?

**Comment by eibex** [comment]
Tested on 3.3.2 and it seems fixed

**Comment by Githopp192** [comment]
Tested it, too .. it's fast now like "Speedy Gonzales" - well done :-)
