### ISSUE TITLE
Etag change of notifications

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3145]
As of https://github.com/nextcloud/notifications/pull/930/files#diff-cd0e03c7a922d1f7204c225b439145f4c8eb207434cc062b20c71a1856021660R122

all eTags are now surrounded with " ".
This affects those endpoints:
GET /ocs/v1.php/apps/notifications/api/v1/notifications
GET /ocs/v1.php/apps/notifications/api/v2/notifications
GET /ocs/v2.php/apps/notifications/api/v1/notifications
GET /ocs/v2.php/apps/notifications/api/v2/notifications

Please check if you use them in combination with eTag and make sure that it then still works.

**Comment by FlexW** [comment]
For me it seems like we are using the **ocs/v2.php/apps/notifications/api/v2/notifications** endpoint. The corresponding code that deals with fetching new notifications, can be found in `src/gui/tray/NotificationHandler.cpp`. However, we seem not to use the etag values directly. We receive them in `ServerNotificationHandler::slotEtagResponseHeaderReceived()`, but then just save the raw response in a `QByteArray`. We then just pass this raw etag response to a notification job on line 54 in `src/gui/tray/NotificationHandler.cpp`. I therefore would conclude that we don't need to take any action on the issue. I will close it for now.
