### ISSUE TITLE
[3.2.0] Status in main window is always Offline even if I am online and sync works

### ISSUE THREAD

**Issue by jkehrel** [nextcloud/desktop#3147]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Status in main window represents real status

### Actual behaviour
is always Offline even when I am connected

### Steps to reproduce
always

### Client configuration
Client version: 3.2.0

Operating system: Windows 10 Pro

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 20.8

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Lars1963** [comment]
In my case, one of two NC-Instances is always showing offline, the other one shows online.
If I start the webbrowser and login, then the will show online for a while; then change to online again.
Worth mentioning? On both instances is the Client Push-App active.

**Comment by allexzander** [comment]
@camilasan You may want to take a look ^^

**Comment by jkehrel** [comment]
Today I upgraded the server to NC Version 20.0.9 (was 20.0.8 before) and the wrong status display in the client is gone. So it seems to be a problem between 20.0.8 and client 3.2 and not a general problem.
Yours jkehrel

**Comment by Lars1963** [comment]
> Today I upgraded the server to NC Version 20.0.9 (was 20.0.8 before) and the wrong status display in the client is gone. So it seems to be a problem between 20.0.8 and client 3.2 and not a general problem.
> Yours jkehrel

Can't confirm this, I'm on NC 21.01 with this issue.

**Comment by jkehrel** [comment]
Lars1963 you are right. On a different laptop with client 3.2 there is the wrong status display in main window even with 20.0.9 server. Hope that an developer looks after it.

**Comment by Lars1963** [comment]
@jkehrel Please reopen. Is you also stated, the problem is not solved.

**Comment by jkehrel** [comment]
Problem still there

**Comment by camilasan** [comment]
Could you share a screenshot of what you are describing? 
The status icon on the folder shows if you are connected to the server and your folders are syncing.
The status icon on the user avatar shows your user status e.g. green for online etc with a message.

**Comment by jkehrel** [comment]
![grafik](https://user-images.githubusercontent.com/1656808/115610613-66c1f900-a2e9-11eb-9683-d957ff8a2142.png)
It shows "Offline" even if I am connected and in sync

**Comment by camilasan** [comment]
> ![grafik](https://user-images.githubusercontent.com/1656808/115610613-66c1f900-a2e9-11eb-9683-d957ff8a2142.png)
> It shows "Offline" even if I am connected and in sync
> Was OK up to version 3.13

This is correct. 
- The folder icon shows the **syncing/server connection status**.
- The avatar icons shows your **user status**. Offline is the default status if you didn't set anything.

Please check  #3182.

**Comment by Lars1963** [comment]
Okay, I can confirm this now. On my private server I had the `user-status`-app deactivated. There the user-status shows allways online. On the firm-server the app was active but not actively used, so no status was set.

@camilasan Maybe implement a check if the `user-status`-app is active at all? If not so, then don't show the status in the client.

**Comment by jkehrel** [comment]
Thanks for your explanation. I misunderstood the status.
I will close it now.
Bye
