### ISSUE TITLE
VFS: Currently downloading

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3159]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

***

![image](https://user-images.githubusercontent.com/38327267/115149035-b4243900-a051-11eb-96ad-c17a9596904c.png)

Can't cancel file downloads initiated by a program (open file). 'Free up space' on the file/folder being currently downloaded does not work. Blocker for users with lover connection speeds.

Using the notification of 'stuff is being downloaded' to cancel downloads seems to work.  
If it's an older initiator, ex if the download was requested, and the machine was restarted afterwards, there seems to be no way to cancel downloads through the GUI.

OneDrive has this integrated in to the app itself.  
I'd suggest to add 'currently downloading' to the activity log. Alternatively, a button there to manage downloads could work, but that button might be reserved for only #3160
![image](https://user-images.githubusercontent.com/38327267/115149212-9905f900-a052-11eb-97c6-33ab5bf77167.png)

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
