### ISSUE TITLE
VFS: Manage offline files.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3160]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

***

Looking for something similar to the W7 Sync Centre, what's still used by samba shares on w10. OneDrive has this integrated in to the app itself.

A place to view all (filter: only) 'Always keep on this device'.

Also show disk usage in local and cloud.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
