### ISSUE TITLE
VFS: Cancelling file explorer transaction moving files to VFS crashes nextcloud desktop.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3161]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Steps might be different, but this is how it happened. `~` = `C:\Users\foo`
1. Move `~\Desktop\bar` to `~\Nextcloud\Desktop\bar`, both folders already exist.
2. Press ✕ on the explorer file transfer transaction.
3. A while later, when the file transfer progress/status window closes, Nextcloud has crashed.

### Client configuration
Client version: 3.2.0

Operating system: w10

OS language: EN

Installation path of client: default

Pardon, I can't provide logs for this, haven't and don't have the time to replicate right now.

**Comment by jtagcat** [comment]
unstale

**Comment by joshtrichards** [comment]
#3420
