### ISSUE TITLE
win app crash ( latest )

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/desktop#3166]
Win10 app crash at first install, no files created in appdata, .
Event viewer error code:

`Nom de l’application défaillante nextcloud.exe, version : 3.2.0.25321, horodatage : 0x60706bba
Nom du module défaillant : ntdll.dll, version : 10.0.19041.928, horodatage : 0x9bed63d6
Code d’exception : 0xc0000409
Décalage d’erreur : 0x00000000000a2020
ID du processus défaillant : 0x3030
Heure de début de l’application défaillante : 0x01d73484a79550ff
Chemin d’accès de l’application défaillante : C:\Program Files\Nextcloud\nextcloud.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\ntdll.dll
ID de rapport : 871add6c-1e0a-48f0-ba9d-6f3707697966
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : `

**Comment by stratege1401** [comment]
after cleaning the system, ALL major install from 2.6.5 to 3.2.0 are failing with the same message. Surely link to latest winupdate

**Comment by allexzander** [comment]
Hello @stratege1401 

Could you run the app again, and then, share the logs that it generates during the crash? Since you can't probably access the UI to create a debug logs archive, you can as well copy the logs folder manually and attach it here. The logs folder is located in "C:/Users/<your_user_name>/AppData/Roaming/Nextcloud"

**Comment by wagnbeu0** [comment]
I had the same problem yesterday. Please rename the following folders 
C:\Users\<USERNAME>\AppData\Roaming\Nextcloud
C:\Users\<USERNAME>\AppData\Local\Nextcloud

to something like Nextcloud_old

Then start Nextcloud again and configure the client again. It should work now.

**Comment by stratege1401** [comment]
Hello,


**_STEP1_**

so, i had a working win10 pro desktop nextcloud 2.6.5 set-up.
It was used for a few days to my unRAID nextcloud 21xx server.

Under ./appdata/roaming/Nextcloud/ i found no "logs" except:
nextcloud.cfg
```
[General]
confirmExternalStorage=false
newBigFolderSizeLimit=500
optionalServerNotifications=true
updateSegment=18
useNewBigFolderSizeLimit=false
showInExplorerNavigationPane=true
crashReporter=true
monoIcons=false

[Accounts]
version=2
0\url=https://xxxxxxxx
0\serverVersion=21.0.1.1
0\webflow_user=xxxxxxx@gmail.com
0\authType=webflow
0\user=@Invalid()
0\Folders\1\localPath=C:/.../Documents/nextcloud/
0\Folders\1\journalPath=._sync_9ed53b229f51.db
0\Folders\1\targetPath=/
0\Folders\1\paused=false
0\Folders\1\ignoreHiddenFiles=false

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\x88\0\0\0\x38\0\0\aa\0\0\x3 \0\0\x4\x89\0\0\0^\0\0\a`\0\0\x3\x1f\0\0\0\0\0\0\0\0\a\x80\0\0\x4\x89\0\0\0^\0\0\a`\0\0\x3\x1f)

[Updater]
autoUpdateFailedVersion=3.1.3
seenVersion=3.1.3
updateTargetVersion=3.1.3
updateAvailable=C:/.../AppData/Roaming/Nextcloud//Nextcloud-3.1.3-setup.exe

[Nextcloud]
autoUpdateCheck=false
```



nextcloud_sync ( just some lines ... )
```
19:15:46||Automatique/2019/09/19-09-18 15-09-27 0158.jpg|INST_NEW|Down|1596374402|ae6e100788e5df3b1094e3d52ed1842b|3159553|00143002ocfk1xgqcrko|4||0|0|0||||
19:15:45||Automatique/2019/09/19-09-18 13-43-34 0150.jpg|INST_NEW|Down|1591791798|ca8539e199f0541fdf16eaaf76b99d01|1908718|00143000ocfk1xgqcrko|4||0|0|0||||
#=#=#=# Syncrun finished 2021-04-24T19:15:54Z (last step: 8043 msec, total: 10692 msec)
#=#=#=# Syncrun started 2021-04-25T10:12:33Z
#=#=#=#=# Propagation starts 2021-04-25T10:12:33Z (last step: 334 msec, total: 334 msec)
#=#=#=# Syncrun finished 2021-04-25T10:12:34Z (last step: 12 msec, total: 346 msec)
#=#=#=# Syncrun started 2021-04-25T10:28:44Z
#=#=#=#=# Propagation starts 2021-04-25T10:28:45Z (last step: 441 msec, total: 441 msec)
#=#=#=# Syncrun finished 2021-04-25T10:28:45Z (last step: 11 msec, total: 452 msec)
```


sync-eclud.lst
```
# This file contains fixed global exclude patterns

*~
~$*
.~lock.*
~*.tmp
]*.~*
]Icon\r*
].DS_Store
].ds_store
._*
]Thumbs.db
]photothumb.db
System Volume Information

.*.sw?
.*.*sw?

].TemporaryItems
].Trashes
].DocumentRevisions-V100
].Trash-*
.fseventd
.apdisk

.directory

*.part
*.filepart
*.crdownload

*.kate-swp
*.gnucash.tmp-*

.synkron.*
.sync.ffs_db
.symform
.symform-store
.fuse_hidden*
*.unison
.nfs*

My Saved Places.

\#*#
```


**_STEP 2_**

2.6.5 complain ( showing ) about an update being available pour version 3.1.x ( from my memory, so i might mix numbering version here, but definitly 3.x.x ). 
I choose to update. Seem the process went well.
First glitch was missing nextcloud notification icon.
Tried to restart it manually. Nothing.
Here is win eventvw link : https://n2.rkn.ovh/s/LQWLKp9k4kwoMTF
crash1.jpg is this event.


**_STEP3_**
full uninstall, cleaning, reboot.
fresh 3.1.x install.
eventvw is crash3.jpg and crash4.jpg

**_STEP4_**
full uninstall, cleaning, reboot.
fresh 3.2.x install.
eventvw is crash2.jpg



I will now try to do:

> I had the same problem yesterday. Please rename the following folders
> C:\Users<USERNAME>\AppData\Roaming\Nextcloud
> C:\Users<USERNAME>\AppData\Local\Nextcloud 

coming back in a few ....

**Comment by stratege1401** [comment]
well,

C:\Users\AppData\Local\Nextcloud is non-existant.
C:\Users\AppData\Roaming\Nextcloud renamed.

app updated, started, then silently crash with same error code as crash2.jpg  ...
C:\Users\AppData\Local\Nextcloud was not recreated.
C:\Users\AppData\Local\Nextcloud still non-existant.

rolled back to 2.6.5...
working again.

**Comment by wagnbeu0** [comment]
To be honest: if the old 2.6.5 is working for you then stay at it. I upgraded three installations from 2.6 to 3.1 and 3.2 and the sync is either not working, VfL not working with huge folders or everything is terrible slow

**Comment by stratege1401** [comment]
Yep... I have no urgency to update to latest 3.x.x
But, I am concern about deprecation at one time and security...
I have 2 kind of users, family and pro.
It's easier with pro as the hardware is more homogeneous.

... And if course, it is on my own daughter laptop that I encountered this
annoying bug.

Digging a bit, and planning a full reset for her w10

Le dim. 25 avr. 2021 à 15:50, Ben Wagner ***@***.***> a
écrit :

**Comment by allexzander** [comment]
@stratege1401 
I am a bit confused, but, looks like the crash happens due to some leftovers in the **Roaming** folder, or, other garbage that may be present in the system that's in use for quite a while.

When you have time, could you please get a VM of exactly the same Windows version and build, and, try to install 3.2.0 there? Just for the sake of checking how it goes with a clean OS installation.

@wagnbeu0 
We're going to include a few fixes for VFS and other things in 3.2.1. Slow sync with VFS is not going to be fixed in 3.2.1 but, we'll roll out a fix in one of the upcoming bugfix releases.

**Comment by allexzander** [comment]
Also, @stratege1401 kindly add some translations to your screenshots that are in French. We are all from different countries, and not many of us speak French :(

**Comment by stratege1401** [comment]
> Also, @stratege1401 kindly add some translations to your screenshots that are in French. We are all from different countries, and not many of us speak French :(

Yep, but cannot do. those screenshots are regular w10 eventwiever shots. Witch are link to w10 initial language settings ( core system ) and cannot be change on the fly, unless changing the core w10 components and having your whole computer in a foreign language.

The only important informations on those screenshoot are the error code. With are the same in every country... 🤣except every country doesnt speak microsft error codes ...

Anyway some string translation from screenshot.

here:

```
nom de l'application défaillante = Faulting application name
Horodatage = time stamp
Nom du module défaillant = Faulting module name
Code d'exception = Exception code
Décalage d'erreur = Fault offset
ID du processus défaillant = Faulting process ID
Heure de début de l'application défaillante = Faulting application start time
Chemin d'accès de l'application défaillante = Faulting application path
ID de rapport = Report ID
Nom complet du package défaillant = Faulting full name application
ID de l'application relative au package défaillant = Faulting Package-relative application ID
```

**Comment by stratege1401** [comment]
> I am a bit confused, but, looks like the crash happens due to some leftovers in the **Roaming** folder, or, other garbage that may be present in the system that's in use for quite a while.

Well, i manually clean every known location for every nextcloud files or data. I also clean the windows register manualy.
This did not change the outcome, or the error code for any of the 3.x options ( fresh install or update from 2.6.5 )

> When you have time, could you please get a VM of exactly the same Windows version and build, and, try to install 3.2.0 there? Just for the sake of checking how it goes with a clean OS installation.

About VM, i will save time and skip it as this laptop is a MSI PC Portable Gamer GL62 7QF-1665XFR.
My two kids have the exact same laptop, with the exact same windows 10 pro eom, with the exact same drivers, with the exact same windows update level.
The only difference is software related, as they dont have the same apps. 
My son laptop works perfectly with latest 3.x and my daughter is failling.
Weird.

As only one of them is failling, I am guessing it is a one time bug.
I am planning to do a full wipeout/Fresh-install in the coming month ( my daughter computer, waiting the end of schools year as she will move to medical university ).

The main difference between the two laptops are the "protecting" software on it. The failling one is using Kasperky Total protection. The other one ESET Smart Security Premium.
I dig into the logs but found nothing....

Thank for your help. I hope a clean fresh out of the box re-install will fix it.

**Comment by Ivar418** [comment]
i also have a issue with the same error about the dll in event viewer. however it does work on my other pc, but not my laptop. i tried to replace the dll with the one from my pc but (as expected) it didnt even boot. ive done multiple reinstalls, the folders in appdata dont exist.

heres a ss of the error in eventviewer 
![image](https://user-images.githubusercontent.com/14140952/118178399-30812080-b434-11eb-9282-ac5bcdd7e538.png)

**Comment by Ivar418** [comment]
> > I am a bit confused, but, looks like the crash happens due to some leftovers in the **Roaming** folder, or, other garbage that may be present in the system that's in use for quite a while.
> 
> Well, i manually clean every known location for every nextcloud files or data. I also clean the windows register manualy.
> This did not change the outcome, or the error code for any of the 3.x options ( fresh install or update from 2.6.5 )
> 
> > When you have time, could you please get a VM of exactly the same Windows version and build, and, try to install 3.2.0 there? Just for the sake of checking how it goes with a clean OS installation.
> 
> About VM, i will save time and skip it as this laptop is a MSI PC Portable Gamer GL62 7QF-1665XFR.
> My two kids have the exact same laptop, with the exact same windows 10 pro eom, with the exact same drivers, with the exact same windows update level.
> The only difference is software related, as they dont have the same apps.
> My son laptop works perfectly with latest 3.x and my daughter is failling.
> Weird.
> 
> As only one of them is failling, I am guessing it is a one time bug.
> I am planning to do a full wipeout/Fresh-install in the coming month ( my daughter computer, waiting the end of schools year as she will move to medical university ).
> 
> The main difference between the two laptops are the "protecting" software on it. The failling one is using Kasperky Total protection. The other one ESET Smart Security Premium.
> I dig into the logs but found nothing....
> 
> Thank for your help. I hope a clean fresh out of the box re-install will fix it.

i also have kaspersky on my desktop, so that cant be it since it runs fine on it.my laptop doesnt have kaspersky and doesnt run and it has norton

**Comment by Ivar418** [comment]
i might have found a workaround. i installed nextcloud x86 but it still wouldnt run. so next thing ive tried is to switch in geforce control panel to run nextcloud via my gtx1060. and voila, it started working. im gonna perform a reinstall with x64 and try a reinstall of my igpu drivers

**Comment by allexzander** [comment]
> Update:
> I used DDU to remove the igpu driver. after a reboot nextcloud worked till the igpu driver got installed. so im certain that theres a incompatibility there

That's an interesting finding. Thank you. Does this mean the Nextcloud sync client now works normally? Or, do you still have to run it on a GPU?

**Comment by Ivar418** [comment]
> > Update:
> > I used DDU to remove the igpu driver. after a reboot nextcloud worked till the igpu driver got installed. so im certain that theres a incompatibility there
> 
> That's an interesting finding. Thank you. Does this mean the Nextcloud sync client now works normally? Or, do you still have to run it on a GPU?

No it only works on the gtx1060. If started on my igpu it wont start

**Comment by allexzander** [comment]
@Ivar418 So, did I get it right? You are using a GPU to run a Nextcloud client on it? Or is it, you are switching between integrated and discrete (gtx1060) GPU to run the entire OS on it? It's actually the first time I encounter this interesting scenario.

**Comment by Ivar418** [comment]
> @Ivar418 So, did I get it right? You are using a GPU to run a Nextcloud client on it? Or is it, you are switching between integrated and discrete (gtx1060) GPU to run the entire OS on it? It's actually the first time I encounter this interesting scenario.

Im using my gpu to run nextcloud on (not the entire OS). im on a laptop and i use nvidea control pannel to switch between intergrated and discrete gpu
