### ISSUE TITLE
Windows installer: Start after installing and rebooting

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3169]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

***

Quite a paper cut bug.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. ![image](https://user-images.githubusercontent.com/38327267/115221363-197f3500-a0f9-11eb-8b53-96ffe19086e6.png)
2. The client is started in the taskbar, yet the sign in window does not appear (as I'd expect) 
![image](https://user-images.githubusercontent.com/38327267/115221503-459ab600-a0f9-11eb-8c23-71bd6ea265e3.png)
2. ![image](https://user-images.githubusercontent.com/38327267/115221406-2865e780-a0f9-11eb-84e9-5117e4b2e289.png)
3. (expected, not currently happening) After reboot, Nextcloud is started one-time.  
This could be implemented as 'did user click X or not in the sign-in' (and when X is pressed, don't prompt to sign in / autostart again).

### Client configuration
Client version: 3.2.0  
Operating system: win

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
