### ISSUE TITLE
Sync is messed up after having deleted all files in the shared folder

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#3172]
Hello !

I have the following problem with version 3.2.0.

Note : 
1. same problem with DEB installation (PPA) and AppImage
2. software used under GNU/Linux OS (Xubuntu 20.04)

Prerequisite : 
1. Connect the client software to the instance of your choice
2. Set up a synchronized directory

Reproduction of the problem : 
1. from the web interface, put files, folders, etc ...
2. the files are uploaded without any problem via the client software
3. from the web interface, delete all these files and folders.
4. the synchronisation crashes and fails to delete the files and folders on the computer

NB: the problem does not seem to occur if you do not delete all the files from the web interface (partial deletion of data)

I did the same thing with version 3.1.3. Everything goes well (no bug)

Thank you in advance !

Jerome

**Comment by FlexW** [comment]
I tried to reproduce the problem, but for me the client was even unable to remove all files. It would hang forever if I tried to do that. I referenced a pull request that resolves the problem for me. However, I'm unable to reproduce the crash. Could you share your logs with me? You can drop them here: https://cloud.nextcloud.com/s/gF7E326o5fPiXFi

**Comment by Jerome-Herbinet** [comment]
Hello FlexW,
Thank you for your reply. 
I realize that i my explanation wasn't really easy to understand (English is not my mother language). 
In fact, you have perfectly reproduced my issue ;-)
So forget about crash, it wasn't a good description. 
The client is effectively unable to remove the files and hands forever ...
Thanks again a lot for your reply and for your bug fix, hoping that your pull request will be validated.
Jérôme
