### ISSUE TITLE
Nextcloud install WIndows2016

### ISSUE THREAD

**Issue by hnagasawa** [nextcloud/desktop#3177]
I installed NextCloud under Windows2016.
Installation finish. I click Nextcloud icon.
Error messages "not found CLDAPI.dll"
Is there a solution? Or please tell me where to request the creation for Windows Server.

**Comment by Id3aFly** [comment]
I guess this is related to #3083 #3081 #3079 
See also #3138

**Comment by andyxheli** [comment]
You might need to add the feature of the desktop experience on please see below link and let me know.


https://docs.vmware.com/en/VMware-Horizon/2012/published-desktops-applications/GUID-13F25FDB-654C-467F-9BC9-F2F9C4E4EAD7.html

**Comment by FlexW** [comment]
@hnagasawa You need to upgrade your Windows. Please have a look at the issues that @Id3aFly has linked.

**Comment by hnagasawa** [comment]
I installed nextcloud client Windows2016 standard. So, this error occured Version 3.2.0 and later.
This error does not Nextcloud Client Ver3.1.3 under Windows2016

**Comment by andyxheli** [comment]
@hnagasawa thats because 3.2.0 has the virtual file support and when you're installing the app it's looking for that file that file is normally on your system by Microsoft. What I would do it make sure you have the server up to date and turn on Windows Desktop Experience because by default the server dose not have those features enabled. Please see my link

**Comment by github-tomster** [comment]
@hnagasawa 
https://github.com/nextcloud/desktop/pull/3138 🙄 

@world 
the 'responses' created here are an excellent example of nonsense 🤦‍♂️

**Comment by andyxheli** [comment]
@github-tomster what so nonsense id love to know ?

**Comment by github-tomster** [comment]
@andyxheli 
#3138 has all the infos ❕ 
it is neither an out of date operating system nor a missing feature or even an desktop experience ... 🗑️ 
the error is in the [code published](https://github.com/nextcloud/desktop) and [documents provided](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#desktop-client)
[@Id3aFly's ](https://github.com/nextcloud/desktop/issues/3177#issuecomment-823821810) answer was all needed!
