### ISSUE TITLE
Inform users, that 'Create debug archive' contains personal data.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3189]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

***

People end up posting tons of personal information, including filenames/paths, and depending on what you consider personal, server details.

**Comment by isdnfan** [comment]
the debug archives introduced with 3.2 contains huge amount of personal identifiable information (PII) - which prevents me from uploading them to help.nextcloud.org and github. additionally this logs can not be easily modified by the user - there must be an improvement to debug archive format.

**Comment by joshtrichards** [comment]
Doc update pending in #6237 

In-app reminder pending in #6238
