### ISSUE TITLE
"Account" button missing in 3.1.3

### ISSUE THREAD

**Issue by tflidd** [nextcloud/desktop#3194]
From the documentation:
![image](https://user-images.githubusercontent.com/8111200/115864747-9848da80-a437-11eb-8a0d-e06ca70cb2bd.png)

There should be a button to manage different accounts. However, on my 3.1.3 client (Win 10 Pro), I don't see this button:
![image](https://user-images.githubusercontent.com/8111200/115865045-10af9b80-a438-11eb-87cd-7c8122725011.png)

I tried to change the size of the window, but the button is not there. I found no way on this interface to add an account (right click on existing account, three dots menu, right click on existing sync point), was this removed on purpose? For me this is not very intuitive and the documentation refers to something that isn't there!!!!

**Comment by FlexW** [comment]
I think the documentation should be updated. You should create accounts through the main dialog.

**Comment by tflidd** [comment]
I found in the mean time that you can do it on the context menu of the status icon. It's a bit strange that this feature is not available in the "main window" where you manage all the accounts, sync points etc.

**Comment by Tie-fighter** [comment]
How does one **REMOVE an account**. 

Without the account button I have found no way to do so in the GUI.

**Comment by FlexW** [comment]
Documentation was updated.
