### ISSUE TITLE
Required CLDAPI.DLL at Windows 8.1

### ISSUE THREAD

**Issue by hectorskypl** [nextcloud/desktop#3202]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen
App should work

### Actual behaviour
Tell us what happens instead
App even not run

### Steps to reproduce
1. Install nextcloud client
2. try run it

### Client configuration
Client version: 3.2.0

Operating system: Windows 8.1

OS language: Polish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Id3aFly** [comment]
I guess this is related to #3083  #3081 #3079
See also #3138

**Comment by FlexW** [comment]
Please have look at the linked issues.

**Comment by hectorskypl** [comment]
Seems it's time to drop Nextcloud if basic functionality stops work and pushes to upgrade to latest and most bugged software in name of what? Crappy VFS? 

Any other suggestions?

**Comment by sryze** [comment]
@FlexW What is CLDAPI for? is it required? Can you hide it behind a flag?

**Comment by FlexW** [comment]
@sryze It's required for the virtual files on Windows. It would be possible to compile without virtual files on old systems. However, we decided to not go this route as this means a lot of extra work for us.

**Comment by wedeen** [comment]
It means if I want to use nextcloud I must upgrade from Windows 8.1 to Windows 10?? Why? Win 8.1 is not that old. This is not ok, there should be a way to use it without upgrading my Windows.
I hope client 3.1.3 works a long time...

**Comment by hectorskypl** [comment]
> It means if I want to use nextcloud I must upgrade from Windows 8.1 to Windows 10?? Why? Win 8.1 is not that old. This is not ok, there should be a way to use it without upgrading my Windows.
> I hope client 3.1.3 works a long time...

I simply recommend you to ownCloud. I did and everything works fine, even on Windows 7.

**Comment by mgallien** [comment]
> It means if I want to use nextcloud I must upgrade from Windows 8.1 to Windows 10?? Why? Win 8.1 is not that old. This is not ok, there should be a way to use it without upgrading my Windows.
> I hope client 3.1.3 works a long time...

We are organizing to be able to provide extended support for Windows 8.1 until the end of its support by Microsoft.
Do not expect new features but critical bugs will be fixed with more point releases. The updater will be modified to handle that case.

**Comment by wedeen** [comment]
This would be great

**Comment by github-tomster** [comment]
@world
this is an excellent example how not to do it! 🤦‍♂️ 
win8.1 server2016 even server 2019 💩 
this shows clearly: not a BiT sustainable! 💢
