### ISSUE TITLE
appimage 3.2.0 gives X11 connection error

### ISSUE THREAD

**Issue by 0xBYTESHIFT** [nextcloud/desktop#3203]
### Expected behaviour
Appimage should run after executing this command:
```sh
chmod +x nextcloud-3.2.0.AppImage
./nextcloud-3.2.0.AppImage
```

### Actual behaviour
I got this error:
```sh
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 22 (Invalid argument) on X server ":1"
      after 426 requests (426 known processed) with 0 events remaining.
```

### Steps to reproduce
1. chmod +x nextcloud-3.2.0.AppImage
2. ./nextcloud-3.2.0.AppImage

### Client configuration
Client version: 3.2.0, AppImage

Operating system: ubuntu 21.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): AppImage

Installation path of client: ~/Downloads

**Comment by mgallien** [comment]
So looks like your x11 server closed the connection.
Could you please confirm that you are using Wayland and XWayland ?
Could you please provide us the full logs ?

**Comment by 0xBYTESHIFT** [comment]
It was on pure X11. Reboot resolved it
