### ISSUE TITLE
How to set up NextCloud Desktop to open my cloud not in a default browser?

### ISSUE THREAD

**Issue by ilsawa** [nextcloud/desktop#3204]
I use Firefox browser as default.
For work  with my cloud I use /opt/ungoogled-chromium (it is compiled with support for H.265 / HEVC and allows for me to view MP4 with such compression).
And I would be really happy If I could assign it as default for NextCloud Desktop.

**Comment by FlexW** [comment]
This is not possible at the moment. It just picks up your default application that you have assigned. You would need to change that.

**Comment by ilsawa** [comment]
> This is not possible at the moment. It just picks up your default application that you have assigned. You would need to change that.

It is possible not for the moment, but for the future. Add the ability to specify the path to the browser binary file with one of the nextcloud.cfg parameters

**Comment by FlexW** [comment]
I checked with the team and we can understand your issue but we are not going to implement this feature. Every feature adds extra work for us implementing and maintaining it. We think too less people will have a benefit from this feature, to make it worth the effort.

**Comment by ilsawa** [comment]
I see that a lot https://www.google.com/search?ie=utf-8&q=%22nextCloud%22%20%22HEVC%22
- People are looking for solving a problem with the playback of the H.265 / HEVC video format, although it is very simple.
The only solution for users Linux, which I saw is to make recompression with another codec.
It is stupid if you can perform several command in console:

```
sudo su

cd /opt

wget https://github.com/macchrome/linchrome/releases/download/v90.0.4430.85-r857950-portable-ungoogled-Lin64/ungoogled-chromium_90.0.4430.85_3.vaapi_linux.tar.xz

tar -xvf ungoogled-chromium_90.0.4430.85_3.vaapi_linux.tar.xz

# User:User Change to your
chown -R user:user /opt/ungoogled-chromium_90.0.4430.85_3.vaapi_linux/

ln -s /opt/ungoogled-chromium_90.0.4430.85_3.vaapi_linux/chrome-wrapper /opt/ungoogled-chromium

exit

# Running:
/opt/ungoogled-chromium

```
I don't think anyone who needs it will make this browser default. More "no" than " yes"

Of course, I can make a shortcut for ungoogled-chromium and not to use nextcloud desktop to open a browser. But I would like more integration from this program.
By the way, nextcloud desktop does not perceive the environment variables, the command "env DEFAULT_BROWSER=/opt/ungoogled-chromium /usr/bin/nextcloud" does not work.

**Comment by FlexW** [comment]
We use this function to open the browser https://doc.qt.io/qt-5/qdesktopservices.html#openUrl . We have not that much influence of the Qt framework. Of course we could roll out our own function for that... Maybe you can report that problem to Qt upstream, when they fix it, we get it in the client for free.
