### ISSUE TITLE
Missing text string

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#3207]
@FlexW @er-vin Is on this line:
https://github.com/nextcloud/desktop/blob/cfb02644e06bad10541c8a48d8d6a3950fe1f583/src/gui/wizard/owncloudadvancedsetuppage.ui#L566
a text string is not missing?

**Comment by FlexW** [comment]
That's fine. It's supposed to be empty. Does is cause any issues?

**Comment by Valdnet** [comment]
> Does is cause any issues?

For me, it won't cause any problems. I just encountered this empty string while browsing text strings. I will also close the issue 😉.
