### ISSUE TITLE
Nextcloud desktop Client for Windows, can not synchronize, how I can do to fix it, thanks.

### ISSUE THREAD

**Issue by yockrain** [nextcloud/desktop#3208]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
**I install a new Ubuntu 20.04, and install NextCloud by this command:
sudo bash -c "$(wget -q -O - https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh)"
and I use External storages to connect my Windows Server share folder
I install desktop client into my desktop(Win10), login my account, I can view the share folder with brower, but a lot files can not be synchronized by desktop client.
I have change another laptop, but the error is reamin.
I even reinstall whole Ubuntu and Nextcloud, but the problem remain.
could you give me some advice to fix this problem, I am very very confuse about that.
Thanks.**

### Steps to reproduce
1.
2.
3.

### Client configuration
**Client version: 3.1.3**

Operating system:
**Windows 10**

OS language:
**US**

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:
**Nextcloud 21.0.1**

Storage backend (external storage):
**Windows Server 2019**

### Logs
**https://gist.github.com/yockrain/49ce741ec97db33d45a9e20f36a4b091**

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Nextcloud.log
https://gist.github.com/yockrain/3b5f593119a228dbbe3ccfa41489f007**

**Comment by FlexW** [comment]
This sounds a lot like a support request and not a actual bug. If you need help with setting up the software, you can go to the forum and ask for help there.
https://help.nextcloud.com

If this is really a bug, please tell me and I will reopen the issue.
