### ISSUE TITLE
[v3.2] Sync DB is exclusively locked (indefinitely)

### ISSUE THREAD

**Issue by detoxhby** [nextcloud/desktop#3222]
### Expected behaviour

Sync database (`._sync_[hash].db` - SQLite 3) is readable for acquiring information about the local files.

### Actual behaviour

Sync database is exclusively locked and cannot be opened for ReadOnly mode to read information necessary for local extensions.

### Steps to reproduce

1. Start nextcloud desktop client
2. Try read from SQLite sync database in ReadOnly mode
3. Failure with error: `database is locked`

### Client configuration

Client version: 3.2.0
Operating system: Windows 10
Installation path of client: default (by msi installer)

---

NOTE: it was working perfectly in PRE-v3.2 versions (actually been using this method for years, dating back to the origins of nextcloud); can't see any logical/technical reason to hold an exclusive lock indefinitely by the client.

Ref: https://sqlite.org/lockingv3.html

**Comment by mgallien** [comment]
Sorry but I am not sure I understand the steps you are doing.
Let me try to say it with my words:

1. Start desktop client;
2. Open the sync database with an SQLite client (like DB Browser for SQLite);
3. See an error reported by the SQLite client

**Comment by detoxhby** [comment]
> Sorry but I am not sure I understand the steps you are doing.
> Let me try to say it with my words:
> 
> 1. Start desktop client;
> 2. Open the sync database with an SQLite client (like DB Browser for SQLite);
> 3. See an error reported by the SQLite client

Correct.
(opening the database with standard library will report this error - either in DB Browser or in any custom client)

**Comment by detoxhby** [comment]
while nextcloud desktop client (v3.2.0) is running without performing any task (no sync, no update, idle process):
![image](https://user-images.githubusercontent.com/1679462/116379016-eb91a300-a812-11eb-9d46-3826d13af40c.png)

**Comment by detoxhby** [comment]
@mgallien can I provide any extra information necessary? (did recheck with v3.2.1, same result)

**Comment by FlexW** [comment]
@detoxhby I think all information is there. As there are other more important bugs, don't expect someone to work on it in the near future.

**Comment by detoxhby** [comment]
ℹ️ UPDATE: I've found an alternative way to interact with the database. The main problem was that nextcloud client has changed to use WAL with Journaling and thus it is not enough to specify read only mode.

Details here: https://sqlite.org/wal.html (section _5. Read-Only Databases_)

The solution persist of using the `immutable=1` URI param to open the database...which seems obvious but almost no utility or connector specify this. For example, using .NET (System.Data.SQLite) connector, the only way to manage this type of connection is to drop generic connection string format and use _fullURI_ based initialization.

I'm not sure yet if this can be lowered to allow generic read only access to the database outside of main process. Will evalutate the usage patter and will close this issue if no other way possible as this most like will never change in the future as destop client needs full exclusive locking + WAL/Journaling in current implementation (which is an overkill in my opinion, but can't override the development directions, so it's not something we need change if there's workaround).

**Comment by mgallien** [comment]
> information_source UPDATE: I've found an alternative way to interact with the database. The main problem was that nextcloud client has changed to use WAL with Journaling and thus it is not enough to specify read only mode.
> 
> Details here: https://sqlite.org/wal.html (section _5. Read-Only Databases_)
> 
> The solution persist of using the `immutable=1` URI param to open the database...which seems obvious but almost no utility or connector specify this. For example, using .NET (System.Data.SQLite) connector, the only way to manage this type of connection is to drop generic connection string format and use _fullURI_ based initialization.
> 
> I'm not sure yet if this can be lowered to allow generic read only access to the database outside of main process. Will evalutate the usage patter and will close this issue if no other way possible as this most likely will never change in the future as destop client needs full exclusive locking + WAL/Journaling in current implementation (which is an overkill in my opinion, but can't override the development directions, so it's not something we need change if there's workaround).

Thanks for the update.
As the switch to using wal with journaling is deliberate I do not think we can do anything on our side.

Is it too much to ask you to put that information in the [Nextcloud forum](https://help.nextcloud.com) for other people that may try to find a solution in that case ?

**Comment by mgallien** [comment]
I am considering we should close this issue
@detoxhby can you do it ?

**Comment by detoxhby** [comment]
@mgallien we are having a pretty busy period atm but will post the information on the forum laster (at least end of 21Q4) to help people 👍🏻
