### ISSUE TITLE
"All Synced" Tray Icon Redesign

### ISSUE THREAD

**Issue by DarXas** [nextcloud/desktop#3223]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

**Icon should be clearly distinguishable from other applications to avoid confusion and enable quick access.**

### Actual behaviour

![icon tray](https://user-images.githubusercontent.com/83289920/116287578-dd9b3e00-a790-11eb-9a4e-e63a611b9549.jpg)

### Steps to reproduce

1. Look at the Icon.

### Suggestion

![allsynced](https://user-images.githubusercontent.com/83289920/116287780-16d3ae00-a791-11eb-9716-bdb029e8cfc1.jpg)
(new all synced - recognizable logo)

![nosync](https://user-images.githubusercontent.com/83289920/116288265-9f524e80-a791-11eb-84ab-4a9b5c5a4bc6.jpg)
(possible use of current "no account" icon as "not syncing" to keep visual consistency)

### Relevant issues

Windows tray icon looks like the Skype one #2915

New sync state icons #196

Add new sync state icons #416

FEATURE REQUEST: Please change tray icon to NextCloud logo #2131

### Client configuration

Operating system: Windows 10

**Comment by mgallien** [comment]
maybe I am biased by the icons found in mainly monochrome icon themes like Breeze but isn't the Nextcloud tray icons too colorful ?

**Comment by DarXas** [comment]
Sorry, I tried thinking about how to improve the current "all synced" tray icon to make it more obvious when you take a quick look at it, because I initially cofused it with the verry similar "Skype" icon. I didn't want to start a discussion about the whole color sceme that is currently used. (I thought the Nextcloud Logo would be fitting as an "all synced" icon, because it has the same color as the "syncing" icon)

**Comment by DarXas** [comment]
With that, I mean that I think the visual difference would still be enough, although you could also invert the syncing colors to make it even more differentiatable 

![allsynced](https://user-images.githubusercontent.com/83289920/116405634-26ee9a80-a830-11eb-9b0f-5151956f63b3.jpg) ![sync](https://user-images.githubusercontent.com/83289920/116405520-0de5e980-a830-11eb-8e5e-54521a4bf264.jpg)

**Comment by mgallien** [comment]
> @mgallien Sorry, I tried thinking about how to improve the current "all synced" tray icon to make it more obvious when you take a quick look at it, because I initially cofused it with the verry similar "Skype" icon. I didn't want to start a discussion about the whole color sceme that is currently used. (I thought the Nextcloud Logo would be fitting as an "all synced" icon, because it has the same color as the "syncing" icon)

Sorry for my confusion. I agree that what you propose is an improvement. if @jancborchardt agree, I would be happy to improve that. What are the people we should involve when modifying this kind of things ?

**Comment by mgallien** [comment]
We should probably go with the Nextcloud icon to accommodate also branded clients where they would get the branded icon and would be easy differentiate also?

**Comment by DarXas** [comment]
> We should probably go with the Nextcloud icon to accommodate also branded clients where they would get the branded icon and would be easy differentiate also?

That sounds like it would be a good thing to do.

**Comment by jesusdeveloper** [comment]
I am a mac user and it is true that this sometimes confuses with other icons.

But the proposal that the OP comments on does not seem correct to me.

A better idea seems to me an icon like Dropbox uses that would be dropbox icon + small icon (nextcloud logo (all synchronized), nextcloud logo with update symbol (in progress)) ...

More details in the following image or in the following url: https://help.dropbox.com/es-es/installs-integrations/sync-uploads/sync-icons 

(In my case for Macintosh)

https://i.ibb.co/vx17BTm/Captura-de-pantalla-2021-12-02-a-las-20-15-06.png

**Comment by Andreas-Kainz** [comment]
I think you can use the tree circles NextCloud icon for the system tray and have the status overlay at the big central circle.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
