### ISSUE TITLE
windows10 cmake -G“ MinGW Makefiles” ../ client  mingw32-make or cmake -G "Visual Studio 16 2019" ../Client ?

### ISSUE THREAD

**Issue by Jxzcode** [nextcloud/desktop#3225]
-- Build of crashreporter disabled.
-- GIT_SHA1 314ab62804d45c8b4cb4209c0daca29f09dac477
Compiling without updater
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
CMake Error at C:/Qt/Qt5.12.9/5.12.9/mingw73_32/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by
  "Qt5WebEngineWidgets" with any of the following names:

    Qt5WebEngineWidgetsConfig.cmake
    qt5webenginewidgets-config.cmake

  Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
  or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebEngineWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "D:/C++/nextcloud/client-build/CMakeFiles/CMakeOutput.log".

**Comment by FlexW** [comment]
You probably need to install Qt web engine or make CMake aware of it.

**Comment by Jxzcode** [comment]
Thank you for answering my question，use cmake -G "Visual Studio 16 2019" .. compile nextcloud-desktop，The error is gone 。webengine There is，But new problems arose,  qtkeychain Compiled through and add System environment variables have been added

**Comment by FlexW** [comment]
@Jxzcode I'm not sure what you did, but I must admit that compiling the client on Windows is not that straightforward. I have a file here https://cloud.nextcloud.com/s/ezLpDDHx24fHrKN where you can find rough instructions that you need to follow to compile the client on Linux, Windows 10 and macOS. Maybe it helps you to build the client.

I will close that issue for now, as there is no bug, but feel free to ask me if you have any further trouble with compiling. You can also go to the forum help.nextcloud.com and ask for help there.

**Comment by anver** [comment]
> @Jxzcode I'm not sure what you did, but I must admit that compiling the client on Windows is not that straightforward. I have a file here https://cloud.nextcloud.com/s/ezLpDDHx24fHrKN where you can find rough instructions that you need to follow to compile the client on Linux, Windows 10 and macOS. Maybe it helps you to build the client.
> 
> I will close that issue for now, as there is no bug, but feel free to ask me if you have any further trouble with compiling. You can also go to the forum help.nextcloud.com and ask for help there.

The link is not found, pls share the link for the instructions, thx
