### ISSUE TITLE
desktop windows client main dialog invisible/washed out

### ISSUE THREAD

**Issue by TibiTaebi** [nextcloud/desktop#3237]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Main dialog should be visible regardless of what's behind.

### Actual behaviour
Main dialog invisible/washed out especially when there's something bright in the back. See here:
![NC Client Main Dialog washed out](https://user-images.githubusercontent.com/18166734/116663873-f9bcfc00-a997-11eb-8dda-f48b9971d1b7.jpg)

### Steps to reproduce
open main dialog

### Client configuration
Client version: 3.2.0
Operating system: windows 10 pro 20h2
OS language: en
Installation path of client: "C:\Program Files\Nextcloud\nextcloud.exe"

**Comment by splitt3r** [comment]
Are you connected via RDP to the VM running the Nextcloud client?

**Comment by TibiTaebi** [comment]
RDP: no
VM: yes, VMware Workstation 16 Player, 16.1.0 build-17198959
Host and Guest OS: Windows 10 Pro, 20H2
The Nextcloud client runs in the VM on my working PC and I'm directly connected to it (not via RDP).

**Comment by mgallien** [comment]
> Are you connected via RDP to the VM running the Nextcloud client?

This is indeed a good idea. I never had problems with VirtualBox.
@TibiTaebi could you try with another hypervisor like VirtualBox ?

If the problem comes from the graphical stack (OpenGL drivers, VM, ...) I fear we will not be able to fix the stack beneath us.

**Comment by TibiTaebi** [comment]
Yes, I will, but I need some time.

**Comment by allexzander** [comment]
Not sure if we can fix it from our side. Looks like some VGA driver configuration issue indeed. Also, I never experienced this issue in Virtual Box before and not experiencing it in Hyper-V too.

**Comment by TibiTaebi** [comment]
> 
> 
> Not sure if we can fix it from our side. Looks like some VGA driver configuration issue indeed. Also, I never experienced this issue in Virtual Box before and not experiencing it in Hyper-V too.

You can probably reproduce the error with a VM from VMware:
- I use the latest free player: 'VMware® Workstation 16 Player, 16.1.1 build-17801498'.
- Install Windows 10 x64 Pro EN (no need to activate)
- update windows to the latest version (probably not necessary but I did it)
- install VMware tools,
- install NC client,
- update the display driver (optional update from Windows Update) to _VMware SVGA 3D 8.17.2.14_ and see what happens --> the NC client main window at this point is probably washed out like mine
- roll back the display driver to version 8.17.1.1 --> it should be good.
- and then yes, somehow debug the client

**Comment by allexzander** [comment]
@TibiTaebi  Is it the same when using Nextcloud 3.1.3?

**Comment by TibiTaebi** [comment]
> 
> 
> @TibiTaebi Is it the same when using Nextcloud 3.1.3?

Yes, it's the same.
Both screen shots are with client 3.1.3. First with display driver _VMware SVGA 3D 8.17.1.1_ and second with version 8.17.2.14.
When rolling back the driver NC client is good again.
![NC_Client_ok](https://user-images.githubusercontent.com/18166734/117454736-c0136480-af46-11eb-960a-5266b74343a8.jpg)
![NC_Client_error](https://user-images.githubusercontent.com/18166734/117454739-c0abfb00-af46-11eb-80d6-c2a7bed9e467.jpg)

**Comment by CCRDude** [comment]
Still happens for me (within VMWare Workstation, 16.2.5).

Know the problem from Chrome (and all Chrome based browsers) - there, disabling hardware acceleration (in Chrome settings) helps.

To please the Nextcloud client, I need to disable hardware acceleration for the "Display" in VMWare.

It feels kind of weird that such a small window needs to use hardware acceleration.
