### ISSUE TITLE
Rename and replace file leads to deletion and creation of new file

### ISSUE THREAD

**Issue by biva** [nextcloud/desktop#3240]
### What happens
1. Sync the file **docu.doc** (possibly, **docu.doc** has a shared public link, but it)
2. Edit this file and close it
3. Rename the file **docu2.doc**
4. Sometimes (not always) **docu2.doc** is considered as newly created document (without any previous version and without any shared link) and **docu.doc** is deleted.

### What should happen
**docu2.doc** should be the renamed version of **docu.doc** and keep the old versions and the shared links.

### Similar issues
I have looked for existing issues:
- https://github.com/nextcloud/desktop/issues/2132 is interesting and looks the same as the one I'm reporting  @Weak-Chicken (it was closed for inactivity but marked as bug by @er-vin)
- @katrinleinweber shares in https://github.com/nextcloud/desktop/issues/1142 that the same problem might happen with folders
- this might be related to the general wrong "conflict generation" https://github.com/nextcloud/desktop/issues/943
- @twatzl reported that it can delete files in a folder https://github.com/nextcloud/desktop/issues/1296
- some users reported the existence of 2 files when renaming. I don't see that clearly but it might help to understand (https://github.com/nextcloud/desktop/issues/347 or 

#### Config
NC21 (Debian, Apache)
Desktop 3.1.3 on Windows 10

**Comment by joholm2** [comment]
Hi, sorry I missed this one when I created my issue recently.
On the other hand mine may be more useful because I have found the error which is causing it.
 Please see https://github.com/nextcloud/desktop/issues/3270 - especially my second post there.

**Comment by allexzander** [comment]
@biva Can you share logs that got created right after you experience this issue?

**Comment by joholm2** [comment]
@allexzander - please the the bug report I created and linked to above. It has not only logs but pinpoints the fault.

Please see #3270 - especially my second post there.

**Comment by allexzander** [comment]
@joholm2 Thx I've noticed that issue too. However, when dealing with such cases, I prefer having logs from all users that encountered seemingly same issue to exclude the chance that we're dealing with different issues having identical symptoms.

**Comment by joholm2** [comment]
@allexzander Ok, thanks - understood.

**Comment by biva** [comment]
I have created a file test.txt and renamed it several times in a row. I see the following files deleted in the Web UI:
![image](https://user-images.githubusercontent.com/9964305/117789628-d1ab8380-b248-11eb-9f35-1f57f07fa98e.png)
The last name is fez.txt:
![image](https://user-images.githubusercontent.com/9964305/117790001-35ce4780-b249-11eb-9f66-06c5fe06ab90.png)

@allexzander @joholm2 I would like to share the log with you but I'd be more comfortable to share per email, not in a public place: would that be possible?

**Comment by biva** [comment]
For information, this is not on 3.2 only, it happened on previous versions as well.

**Comment by allexzander** [comment]
@biva Sure. Please send logs to my inbox alex@nextcloud.com

**Comment by biva** [comment]
Thanks! I sent you the email with the logs @allexzander Do you think it's the same issue as https://github.com/nextcloud/desktop/issues/3270?

**Comment by allexzander** [comment]
@biva Received. Thanks. Yes. Looks like we have 3 similar issues on Github. Anyways, I've got the PR with a fix https://github.com/nextcloud/desktop/pull/3311

And, here you can get an early test build before I release the fix, if interested https://cloud.nextcloud.com/s/g6acjp9HGNPweL5

**Comment by biva** [comment]
Congrats :) I'm just wondering if your PR fixes a bug that happens on 3.2 only? Because in our situation, this bug is present for a long time with previous versions.

**Comment by allexzander** [comment]
> Congrats :) I'm just wondering if your PR fixes a bug that happens on 3.2 only? Because in our situation, this bug is present for a long time with previous versions.

@biva You will have to update to 3.2.2 when it's out. We won't be rebuilding 3.2.

**Comment by biva** [comment]
Sorry for the misunderstanding. What I meant is: "is this bug [the one solved in the PI] related to 3.2 only? Or was this bug present in previous versions?"

Indeed, we see this bug for a long time: the bug mentioned in this issue #3240 is not specific to 3.2 and virtual folders.

**Comment by biva** [comment]
Hello @allexzander I just installed 3.2.3 on Windows 10 and the problem is not solved: I still have the same issue. Does this version include the fix?

**Comment by biva** [comment]
For information in order to reproduce the issue:
1. Create a file test.txt
2. Keep renaming it very fast, edit it, change the content, save it, rename it... Do this several times, very fast, without leaving time to the desktop client to finalise the sync.
3. Check the web UI: you should find one or several deleted files corresponding to this file (while no file should be created/deleted)

It might look a weird scenario to do this, but that's to reproduce the issue easily. For large files, it's really possible that this happens without making these weird fast changes and savings.

**Comment by biva** [comment]
Hello @allexzander I tested it with 3.2.4, still the same issue :( Could you please provide any update?

Thanks!

**Comment by biva** [comment]
Could you also please reopen this issue as it's still there?
