### ISSUE TITLE
Nextcloud-3.2.1-x64.msi will not install on Windows 8.1 x64

### ISSUE THREAD

**Issue by WST1811** [nextcloud/desktop#3245]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Actual behaviour
MSI-Installer from Version 3.2.1 will not install, error message appear.

### Steps to reproduce
1. Download and run Nextcloud-3.2.1-x64.msi
2. Error Message: This application only runs on Windows 10, Version 1709 or higher!
3.

### Client configuration
Client version: 3.13

Operating system: Windows 8.1 x64

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): From Nextcloud

Installation path of client: "C:\Program Files\Nextcloud\nextcloud.exe"

### Server configuration

Nextcloud version: 21.01

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

EDIT: MSI-Client Nextcloud-3.2.0-x64.msi is running without errors.

**Comment by mgallien** [comment]
We only support Windows 10 version 1709 and later versions since the 3.2.0 release of desktop client.
It is not possible to use newer features and still support old Windows versions.
We still support Windows 8.1 with the 3.1 minor release (current version is 3.1.3).

**Comment by WST1811** [comment]
Thanks for reply.
The Nextcloud Client (3.1.3) offer me this version, why the client offer a version it is not supported on my device? And Microsoft support Windows 8.1 until january 2023! https://docs.microsoft.com/de-de/lifecycle/faq/windows#windows-8.1

**Comment by WST1811** [comment]
OK, i think i'm not the last user with W8.1 or older. ;) Thanks for clearing this issue.

**Comment by ronbass** [comment]
3.1.3 offering automatically the update is confusing when it is not supported under win.7 or win.8, there should have been a notice before updating it and having errors then losing the application.
There should be at least a link to get the previous version, if I did not keep it on my folders I would have lost access to my NC files.
It is ok not to support older OS but at least you need to keep the previous version somewhere on your portal, this is standard practice for all apps that are not supported even after 10 years.
thank you

**Comment by WST1811** [comment]
@ronbass 
You can download from here old versions: [https://download.nextcloud.com/desktop/releases/Windows/](https://download.nextcloud.com/desktop/releases/Windows/)
Of course you are right with your comment.

**Comment by ronbass** [comment]
Thank you very much, that's helpful and I suggest this link should be added on the download page for people like me who were not able to find it. ;-)

**Comment by muchahagrande** [comment]
Well, Windows 8.1 is still supported by MS.

**Comment by WST1811** [comment]
https://github.com/nextcloud/desktop/issues/3245#issuecomment-830190027

I have more than one W8.1 Client, now i get the notification to update on each Client, it is possible to get a update for 3.1.3 that the client not notify me to update to a not working version?

**Comment by mgallien** [comment]
I am working on that. Users with 3.1.3 may soon get a 3.1.4 to fix the upgrade.

**Comment by WST1811** [comment]
> 
> 
> I am working on that. Users with 3.1.3 may soon get a 3.1.4 to fix the upgrade.

OK, thanks. I will wait for the fix. :)

**Comment by FlexW** [comment]
@pzzszk At the moment it's because of the virtual files feature on Windows. This feature does not work on older versions.

**Comment by l1m3r** [comment]
> @pzzszk At the moment it's because of the virtual files feature on Windows. This feature does not work on older versions.

That is not much of an explanation at all. I can't find anything useful with "virtual files feature Windows 10" unless you count the age old command "subst".
Nor do you explain why this new feature is required for new NC clients.

Is there a blog post somewhere explaining this?
Please post some more resources/links so we can actually try to understand this odd decision to suddenly (seems to me) drop support for windows 8.1

Thanks.

**Comment by FlexW** [comment]
@l1m3r Blog post https://nextcloud.com/blog/nextcloud-desktop-client-3-2-with-status-feature-and-virtual-files-available-now/.
Windows 8.1 support is not really dropped, because Nextcloud stated on their website for a long time that only Windows 10 is officially supported. Also there are currently ongoing discussion internally how other Windows versions can be supported. For now the solution is to keep using 3.1.3 if you use Windows 8.

**Comment by WST1811** [comment]
Desktop Client 3.1.3 offer me Desktop Client 3.2.2. Why? I can't install like 3.2.1. It is so hard to build a new Desktop Client how will run on each OS? You can ask for some features the OS-Build before you offer this features.

**Comment by Piotr-Fr** [comment]
Same here.
I do not understand why Nextcloud download page tells the users it works on Win 8.1. It is highly misleading.
Despite the fact, I do not understand why Win 8.1 is not supported in newer versions.
As someone already asked the question, let me repeat that: what are features and reqs of Win 10 that you guys can't make Nc work on Win 8.1?

I use that system for the very basic reason: it is stable.

**Comment by FlexW** [comment]
@Piotr-Fr I can not see that on the official download page it is stated that Win 8.1 is supported. See here https://nextcloud.com/install/#install-clients

Having that said, Win 10 1709 and higher is required because the Nextcloud client needs the CFApi for the virtual files feature that is only available in this newer version. 3.3.0 will contain an update so that the client will be able to run on older Windows versions, but then without the virtual files feature.

**Comment by WST1811** [comment]
> 
> Having that said, Win 10 1709 and higher is required because the Nextcloud client needs the CFApi for the virtual files feature that is only available in this newer version. 3.3.0 will contain an update so that the client will be able to run on older Windows versions, but then without the virtual files feature.

Windows 10 1709 is out of Support from Microsoft. For Home, Pro, Enterprise and Eduction. https://docs.microsoft.com/de-de/lifecycle/products/windows-10-home-and-pro

Did you have a timeline for coming out Version 3.3.0? On May, 9 you wrote you bring a Fix in 3.1.4 for older Windows Versions soon. https://github.com/nextcloud/desktop/issues/3245#issuecomment-835787114  Whats goin on?

**Comment by FlexW** [comment]
3.1.4 will not come. 3.3.0 will contain a fix for older platforms and there is no exact schedule. Pre-release 1 of 3.3.0 was released today, and the final release will come out in a few weeks.

**Comment by WST1811** [comment]
@FlexW 
Today i installed NC Desktop Version 3.3.0, thanks to all who helped to develop this version, for me it works. :)

**Comment by pzzszk** [comment]
Great news - thanks.  It installs properly on W7 & seems to be OK.  Thanks for doing this.

**Comment by Piotr-Fr** [comment]
> 
> 
> @Piotr-Fr I can not see that on the official download page it is stated that Win 8.1 is supported. See here https://nextcloud.com/install/#install-clients
> 
> Having that said, Win 10 1709 and higher is required because the Nextcloud client needs the CFApi for the virtual files feature that is only available in this newer version. 3.3.0 will contain an update so that the client will be able to run on older Windows versions, but then without the virtual files feature.

@FlexW First of all, fixed, thanks! Secondly, you are right, my lack of precision: download site informed, but on a similar page, 3.2.1 v.
https://docs.nextcloud.com/desktop/3.3/installing.html
there was an info it was installable on Win 8.1 for sure. Cannot find it now.
Also, please note, now on the above site no info about older versions, however, it works now on Win 8.1. So there is a bit of inconsistency here.
Anyway, thanks for solving that out!
