### ISSUE TITLE
Update fails on Windows 7 x64 for version 3.2.1

### ISSUE THREAD

**Issue by Infogeekx** [nextcloud/desktop#3249]
### Expected behaviour
Update should work on Windows 7.

### Actual behaviour
Update doesn't work.

![Image of issue](https://i.imgur.com/WNBudjq.png)

### Steps to reproduce
Attempt install on Windows 7.

**Comment by Id3aFly** [comment]
I guess this is related to #3083 #3081 #3079
See also #3138

**Comment by Id3aFly** [comment]
What is the error message you are getting?
Just "Update Failed"?

**Comment by Infogeekx** [comment]
> What is the error message you are getting?
> Just "Update Failed"?

Yes, the installation/update fails as shown in the image.

**Comment by WST1811** [comment]
No chance for W7 anymore: https://github.com/nextcloud/desktop/issues/3245

**Comment by Infogeekx** [comment]
You would think NextCloud of all would be more considerate about privacy and security issues as widely claimed, instead of being just yet another one forcing towards the issue riddled Windows 10 platform.

**Comment by FlexW** [comment]
Please see the issue https://github.com/nextcloud/desktop/issues/3249 and the linked ones why we prevent installation on old Windows version. Just a thought from me: If you want privacy switch to Linux:)

**Comment by Id3aFly** [comment]
@FlexW I don't know if it is possible, but there are many issues here regarding this update problem to 3.2.x. is there any way you add some "information" or more details why the update is not possible instead of just raising "Update failed"?

**Comment by FlexW** [comment]
@Id3aFly Good idea. I'm not sure if MSI is able to display a reason for the failure. @allexzander Do you know this?

**Comment by allexzander** [comment]
> @Id3aFly Good idea. I'm not sure if MSI is able to display a reason for the failure. @allexzander Do you know this?

@FlexW Actually, there is a message that is getting displayed by MSI when the update is failing. But, apparently, it only appears when running the updater with a UI. Looks like the updater is running the MSI silently. This is something that needs to be double-checked.

**Comment by c89williams** [comment]
This is really disheartening to see. Windows 7 may be officially EOL by Microsoft but Windows 8 has 2 years left, however you guys chose to only support Windows 10? I'd put money on there still being a good percentage of Nextcloud users using older versions of Windows but now you've snubbed them. If you have analytics data pertaining to desktop client OS, have you bothered to check it?

It seems ridiculous in my mind to force the latest version of an OS just to support a few silly optional features when 99% of the code is perfectly capable running on an older OS. Perhaps you should disable those features instead of the entire program? Just a thought.

This is the first software I've had that actually makes running Windows 7 a problem which says something. smh

**Comment by FlexW** [comment]
@c89williams You can still use the desktop client. Just stay on an older release. By the way, there are other reasons too, to go for Windows 10. For example we want to migrate to Qt6, to support the latest hardware and get all bugfixes from Qt. Qt6 will only be available for Windows 10.

**Comment by c89williams** [comment]
Staying on an older version works at the moment, but what about in a year? At some point there may be a breaking change rendering all older clients useless, and what will you tell us then? Sorry for your luck? At the heart of it this is a **file syncing program**, why on earth do you need to complicate it with certain technologies requiring the latest version of Windows?

Oh wait, this just in: older Windows versions suddenly no longer support file syncing, must upgrade to Win10 for continued support. Hmm that's weird, Dropbox, Box, Google Drive, OneDrive, iCloud Drive, IDrive, SugarSync, BackBlaze, and a dozen other providers still have functioning client apps for Windows 7. Huh that's funny, I wonder how they managed that?

The kicker is that OwnCloud still supports Windows 7.

What are you guys doing.

**Comment by Id3aFly** [comment]
You could have a look at tools like MountainDuck, Cyberduck or GoodSync. I know they are able to connect with Nextcloud as well.
