### ISSUE TITLE
Client 3.2.1 and Windows Server 2016

### ISSUE THREAD

**Issue by fastleo63** [nextcloud/desktop#3253]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Update the client to 3.2.1

### Actual behaviour
Install interrupted with error of Windows 10 version < 1709
But I have Windows Server 2016 (that isn't freely upgradeable to a newer version, such as with Windows 10)

### Steps to reproduce
1. Launch 3.2.1 MSI installer
2.
3.

### Client configuration
Client version:

Operating system: Windows Server 2016

OS language: Italian

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
You need to stay at an older client version then. Please see this issue and the linked ones: https://github.com/nextcloud/desktop/issues/3083
