### ISSUE TITLE
No Download Button for Updates on macOS (again)

### ISSUE THREAD

**Issue by jonasgarstick** [nextcloud/desktop#3254]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After checking for updates manually or get the notification from the client there is an update I would expect to get a clickable button (link) to download the update.

### Actual behaviour
The message contains the link in plain text "https://nextcloud.com/install/?pk_campaign=clientupdate#install-clients". You cannot copy or click the link directly.

### Steps to reproduce
1. Manually install client 3.2.0 
2. Open Nextcloud Preferences
3. Check for updates and check the message

### Client configuration
Client version:
3.2.0 (macOS)

Operating system:
macOS Catalina 10.15.7

OS language:
german
![nc-update-download](https://user-images.githubusercontent.com/17829368/116896385-7bc95100-ac34-11eb-9b7f-3cf5cc83af0f.png)
![notification](https://user-images.githubusercontent.com/17829368/116896402-81269b80-ac34-11eb-8b38-f05368147cac.png)

**Comment by claucambra** [comment]
Hi all, the client now ships with an autoupdater which provides a popup with several options when an update is available. The autoupdater handles downloading and installing the relevant update, delaying the update or dismissing it entirely. https://github.com/nextcloud/desktop/pull/4466

In situations where this autoupdater has been disabled the standard update notification is now clickable and will take you to the client download page. https://github.com/nextcloud/desktop/issues/3732

Thanks for reporting!

**Comment by claucambra** [comment]
Yes, this is a separate issue -- seems like at the moment Sparkle is taking "no update available" from our servers as "no valid update information". When there is a valid update the update popup appears and the update is correctly downloaded and installed. Looking into this

**Comment by foss-** [comment]
Where is this separate issue tracked?

**Comment by claucambra** [comment]
Sorry, by "issue" I meant problem 😅 It was mentioned here https://github.com/nextcloud/desktop/issues/3974#issuecomment-1130153218 but no issue was opened, feel free to open an issue

**Comment by foss-** [comment]
Followup: https://github.com/nextcloud/desktop/issues/4627
