### ISSUE TITLE
Use KDE's Qt patch collection

### ISSUE THREAD

**Issue by nicolasfella** [nextcloud/desktop#3256]
Qt 5.15 does not have an open source LTS release (technically it does, but with 1 year delay).

KDE is maintaining a community LTS of sorts where important commit from Qt6 are backported to Qt 5.15: https://dot.kde.org/2021/04/06/announcing-kdes-qt-5-patch-collection

However there are no binary releases, only the source code in git: https://invent.kde.org/qt/qt

I would suggest we use it for our binary releases. This would for example solve https://github.com/nextcloud/desktop/issues/2584

**Comment by mgallien** [comment]
Thanks for opening this issue.

This is on my todo list.

I am still trying to start by upgrading the Qt version we are using with Qt 5.12.10 as the first step, 5.15.2 as the seond one and then more.

**Comment by mgallien** [comment]
The plan is also to start using a build tooling where it is easy to build dependencies and desktop client from sources.

**Comment by elsiehupp** [comment]
Hi @mgallien—regarding dependencies, I opened [an issue](https://github.com/nextcloud/desktop/issues/3024) a while back asking about using project-based package management for dependencies (in order simplify setup, reduce version conflicts, improve reproducibility, etc.). Is that within the scope of what you’re working on? Thanks!

**Comment by mgallien** [comment]
This is indeed on my to do list. Thanks for asking. I have tested KDE's Craft and plan to test another one.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
