### ISSUE TITLE
Year specified in Copyright should be 2021 instead of 2020

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#3258]
Just seen legal notice dialog.

https://github.com/nextcloud/desktop/blob/4efe00fecaf88b587c6bcb75f1af17ba1fa12747/src/gui/legalnotice.cpp#L55

Year is not up-to-date.

If I am right, I can provide PR as well. 
Need some feedback.

**Comment by mgallien** [comment]
Please yes, you can create a PR for that.
