### ISSUE TITLE
add tablet mode support win10 for the nextcloud desktop app

### ISSUE THREAD

**Issue by bruhdev1290** [nextcloud/desktop#3266]
add support for windows 10 tablet mode for the nextcloud desktop client

**Comment by FlexW** [comment]
@bruhdev1290 Could you describe what is missing, or which problems you face when you use the tablet mode?

**Comment by bruhdev1290** [comment]
@FlexW what i mean is that say if you where going to the nextcloud settings general page
its not optimized for tablet mode it displays in a regular window it should display in a full screen as a windows user in tablet mode would find it uncomfortable to use it in interface not optimized for tablet mode
