### ISSUE TITLE
Nextcloud Reuploads Files unnessesarily

### ISSUE THREAD

**Issue by openminded42** [nextcloud/desktop#3284]
### Expected behaviour
Nextcloud Client syncs only changed files

### Actual behaviour
Nextcloud reuploads unchnaged files every sync interval. This caused above 200GB unnecessary traffic in May 2021!

### Steps to reproduce
1. Fresh installation of Nextcloud client.
2. Setup for Sync with htts;//occucloud.de user "markus"
2. New sync with the nextcloud server into an empty folder.
3. Observe the Nextcloud syncs files again and again without any changes.

### Client configuration
Client version: Version 3.2.1 (Ubuntu)
Operating system: Ubuntu 21.04
OS language: German
Qt version used by client package (Linux only, see also Settings dialog): Cannot find this!
Client package (From Nextcloud or distro) (Linux only): Distro

Installation path of client:
- /usr/bin/nextcloud
- /usr/share/nextcloud
- /usr/share/man/man1/nextcloud.1.gz

### Server configuration
Nextcloud version: 20.0.9,
Storage backend (external storage): does not apply

### Logs
1. Client logfile: 
https://gist.github.com/openminded42/86c2a4aa56f8347f91d2b034b30f6a9b

[__nextcloud_client_parameters.txt](https://github.com/nextcloud/desktop/files/6440618/__nextcloud_client_parameters.txt)
[__nextcloud_client_buildinfo.txt](https://github.com/nextcloud/desktop/files/6440620/__nextcloud_client_buildinfo.txt)
[20210507_1131_owncloud.log](https://github.com/nextcloud/desktop/files/6440624/20210507_1131_owncloud.log)

2. Web server error log:
This file is confidential. Please ask if you need it.

3. Server logfile: nextcloud log (data/nextcloud.log):
This file is confidential. Please ask if you need it.

**Comment by openminded42** [comment]
![screenshot](https://user-images.githubusercontent.com/62114032/117431507-9b5cc400-af29-11eb-9c27-36adf6fc08c3.png)

**Comment by allexzander** [comment]
@openminded42 

Does this happen with every file or specific files/folders only?

**Comment by openminded42** [comment]
@allexzander This happens only to some ducouments. The documents are all either PDF or JPG. Nothing has changed. The files have not been touched in any way.
