### ISSUE TITLE
Compilation of nextcloud/desktop on Windows

### ISSUE THREAD

**Issue by TechSolution99** [nextcloud/desktop#3288]
Hello, nextcloud community.
I tried to compile nextcloud/desktop using CMake.
I installed VS2017 and CMake.
Could you please give me detailed steps of compilation nextcloud/desktop to executable?
Looking forward to your help soon.
Regards.

**Comment by mgallien** [comment]
Please read https://docs.nextcloud.com/desktop/3.2/building.html

Please notice that issues are for bug or feature requests and not support so next time go to [https://help.nextcloud.com](https://help.nextcloud.com).

**Comment by FlexW** [comment]
@mgallien @TechSolution99 the docuemntation about building the client on Windows are really outdated. This document may help you https://cloud.nextcloud.com/s/ezLpDDHx24fHrKN
