### ISSUE TITLE
Big Sur Style Icon

### ISSUE THREAD

**Issue by elsiehupp** [nextcloud/desktop#3294]
## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Expected Behavior
Nextcloud Desktop should have an icon that conforms with Apple's [icon design guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) for macOS Big Sur:
* Generally follow the supellipse outline from the icon template.
* Use the predefined drop shadow.
* Use more definition and shadow on macOS than on iOS.
* [Implied] Use generally vivid colors, with a vertical gradient that may or may not create the illusion of depth.
* Prefer using a Big-Sur-style icon on older versions of macOS to using an older-style icon on Big Sur.

### Example Icons
<img width="128" alt="apple-mail-256@2x" src="https://user-images.githubusercontent.com/9206310/117553294-c4ab4c00-b01e-11eb-90df-b6878dc745b8.png"><img width="128" alt="apple-messages-256@2x" src="https://user-images.githubusercontent.com/9206310/117553306-cd038700-b01e-11eb-85d3-b5e60acc77c4.png"><img width="128" alt="apple-music-256@2x" src="https://user-images.githubusercontent.com/9206310/117553310-d4c32b80-b01e-11eb-97a9-75a521e5e3c0.png">

## Actual Behavior
Nextcloud Desktop’s icon on macOS is identical to its icons on Windows and Linux. In particular:
* The icon uses a circular outline.
* The icon does not use the predefined drop shadow.
* The glyph is flat, solid white and has no definition or shadow.
* The background gradient is on a diagonal and, while high-saturation, is not particularly vivid.
* The icon design style passingly resembles the guidelines from macOS Mojave, rather than using the current guidelines across all versions of macOS.

### Existing Icon
<img width="128" alt="nextcloud-existing" src="https://user-images.githubusercontent.com/9206310/117553365-3a171c80-b01f-11eb-8090-3075e630ef67.png">

## Commentary
I’ve put together a set of variations on the icon. (On complication is that there doesn’t seem to be a canonical definition for the exact proportions of the glyph.)

### Potential Tweaked Designs
<img width="128" alt="nextcloud-diagonal-3d" src="https://user-images.githubusercontent.com/9206310/117553545-49e33080-b020-11eb-8a81-487d244e49ee.png"><img width="128" alt="nextcloud-diagonal-floating" src="https://user-images.githubusercontent.com/9206310/117553546-4a7bc700-b020-11eb-862c-7261332886e5.png"><img width="128" alt="nextcloud-diagonal-inset" src="https://user-images.githubusercontent.com/9206310/117553547-4b145d80-b020-11eb-8928-bc5ded388902.png"><img width="128" alt="nextcloud-diagonal-rounded" src="https://user-images.githubusercontent.com/9206310/117553614-9cbce800-b020-11eb-950c-286e15b5aa47.png">
<img width="128" alt="nextcloud-vertical-3d" src="https://user-images.githubusercontent.com/9206310/117553631-afcfb800-b020-11eb-8424-57049317ac5d.png"><img width="128" alt="nextcloud-vertical-floating" src="https://user-images.githubusercontent.com/9206310/117553632-afcfb800-b020-11eb-8ec9-daf72e43fef0.png"><img width="128" alt="nextcloud-vertical-inset" src="https://user-images.githubusercontent.com/9206310/117553634-b0684e80-b020-11eb-9ed1-1adbb8cf2bdf.png"><img width="128" alt="nextcloud-vertical-rounded" src="https://user-images.githubusercontent.com/9206310/117553558-4e0f4e00-b020-11eb-8bd7-76de29f7affb.png">
<img width="128" alt="nextcloud-hue-shift-3d" src="https://user-images.githubusercontent.com/9206310/117553735-308eb400-b021-11eb-81f3-cd1981f4ff37.png"><img width="128" alt="nextcloud-hue-shift-floating" src="https://user-images.githubusercontent.com/9206310/117553658-ce35b380-b020-11eb-8bf4-e62e33aa94e0.png"><img width="128" alt="nextcloud-hue-shift-inset" src="https://user-images.githubusercontent.com/9206310/117553648-beb66a80-b020-11eb-98ea-e02b9cdb835f.png"><img width="128" alt="nextcloud-hue-shift-rounded" src="https://user-images.githubusercontent.com/9206310/117553724-24a2f200-b021-11eb-8414-9403a5c15ce5.png">

I put this in an Issue rather than a Pull Request because it’s fairly open-ended at this point, and I don’t want to prematurely demonstrate a preference for one specific design.

**Comment by elsiehupp** [comment]
It’s worth mentioning that the Linux icon could also stand to undergo some tweaks in order to better match the [GNOME](https://developer.gnome.org/hig/stable/icon-design.html.en) and [KDE](https://develop.kde.org/hig/style/icons/colorful/application/) icon design guidelines. Some of the tweaks for one platform could carry over to the others, but in general each platform seems like a separate issue.

**Comment by elsiehupp** [comment]
One other thing to note is that the leftmost column features a glyph that’s rendered from a 3D model. It would be possible to make changes to the render; the material that’s there is just the absolutely most basic option. The rendering effects in the other three columns are entirely programmatic within the illustration program.

**Comment by Id3aFly** [comment]
Even I am no Mac user, I have to admit, I like the icons from the second and thrid line very much!

**Comment by FlexW** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
So while we’re not going to go overboard with shadows and plasticity – also simply because of recognizability and logo trademark – we can certainly adjust the border-radius and drop-shadow of the whole element. :)

Unfortunately the guidelines are only available in Photoshop, XD and Sketch, neither of which I can use. If someone can convert them to SVG that would be great: https://developer.apple.com/design/resources/#macos-apps @elsiehupp since you created the mockups which I assume was on that basis? :)

For reference, the source file we would use is https://github.com/nextcloud/promo/blob/master/nextcloud-icon.svg

**Comment by elsiehupp** [comment]
The template/guidelines use layer-effect shadows, which SVG apparently does not support. I’m not sure what other formats support both vector and layer effects. (To be clear, I’m not actually using Photoshop myself; I’m using [Affinity Designer](https://affinity.serif.com/designer/) and exporting.)

**Comment by dpschen** [comment]
👋  Hello,
maybe I misunderstood but if not:
I simply put the SVG @jancborchardt mentioned (https://github.com/nextcloud/promo/blob/master/nextcloud-icon.svg) inside the "App Icon" Sketch file and exported them all.
Hope that helps 😄 

### This is how the sketch file looks with the Nextcloud icon added
![Screenshot 2021-06-26 at 21 13 51](https://user-images.githubusercontent.com/6173598/123523733-d7a8d700-d6c5-11eb-8d79-912eb0702d74.png)

### All icons as directory
[Icon-App-Name.iconset.zip](https://github.com/nextcloud/desktop/files/6720589/Icon-App-Name.iconset.zip)

### Individual icons (same as the zip above)

**2X**
![icon_16x16@2x@2x](https://user-images.githubusercontent.com/6173598/123523602-ee026300-d6c4-11eb-97a9-d513b83591fb.png) ![icon_32x32@2x@2x](https://user-images.githubusercontent.com/6173598/123523603-ee9af980-d6c4-11eb-9007-798022cf26af.png) ![icon_128x128@2x@2x](https://user-images.githubusercontent.com/6173598/123523604-ef339000-d6c4-11eb-9845-b904c9176152.png) ![icon_256x256@2x@2x](https://user-images.githubusercontent.com/6173598/123523606-efcc2680-d6c4-11eb-9000-4813d57eb373.png) ![icon_512x512@2x@2x](https://user-images.githubusercontent.com/6173598/123523609-f0fd5380-d6c4-11eb-8152-e55e54fbff58.png)

**1X**
![icon_16x16](https://user-images.githubusercontent.com/6173598/123523611-f3f84400-d6c4-11eb-88d7-f2b69e24e6bb.png) ![icon_32x32](https://user-images.githubusercontent.com/6173598/123523612-f490da80-d6c4-11eb-838a-52249448e4e2.png) ![icon_128x128](https://user-images.githubusercontent.com/6173598/123523613-f5297100-d6c4-11eb-9a7b-024fb361fb7d.png) ![icon_256x256](https://user-images.githubusercontent.com/6173598/123523614-f5c20780-d6c4-11eb-892b-77fe482e91fe.png) ![icon_512x512](https://user-images.githubusercontent.com/6173598/123523615-f65a9e00-d6c4-11eb-8859-8e87aa122ded.png)

### Edited Sketch file with the SVG added. 
[Template - Icon - App.sketch.zip](https://github.com/nextcloud/desktop/files/6720594/Template.-.Icon.-.App.sketch.zip)

**Comment by elsiehupp** [comment]
That is indeed the baseline for making a Big Sur icon (and more or less where I started). The various subtly different versions I posted above mostly differed in terms of how to show depth with the logo, as well as potential changes to the gradient.

I started with the template from [macosicons.com](https://macosicons.com/resources) rather than the official one from Apple, though. Obviously the Apple template includes multiple sizes (as is the norm for Linux icons), but IIRC I didn’t use it because I don’t have Sketch.

There are Python scripts floating around that generate sized PNG files from SVG files for Linux (I’ve worked on a version of the script myself), and the same script could probably be used for generating sized images for macOS, though packing them into an icon set would be an additional step.

**Comment by dpschen** [comment]
Yes I saw the changes :)
I forgot about  macosicons.com. Their template seems really better than the apple one 👍 .

Regarding the gradients:
Personally I would also be happy with something like your second column / second row:
![](https://user-images.githubusercontent.com/9206310/117553632-afcfb800-b020-11eb-8ec9-daf72e43fef0.png)
Seems like a good compromise!

> So while we’re not going to go overboard with shadows and plasticity – also simply because of recognisability and logo trademark – we can certainly adjust the border-radius and drop-shadow of the whole element. :)

I understood @jancborchardt here this way that he doesn't think a change of the logo itself makes sense, but a change of the outer stuff is no problem – so that's what I did.

**Comment by elsiehupp** [comment]
Here are the editable PSD files for the second column, second and third row:

* [nextcloud-macos-floating-icon-vertical-gradient.psd.zip](https://github.com/nextcloud/desktop/files/6720661/nextcloud-macos-floating-icon-vertical-gradient.psd.zip)
* [nextcloud-macos-floating-icon-hue-shift-gradient.psd.zip](https://github.com/nextcloud/desktop/files/6720662/nextcloud-macos-floating-icon-hue-shift-gradient.psd.zip)

I also included the third-column logos as hidden layers in each file, since I personally think it’s more a e s t h e t i c. (My personal preference is probably third column, third row.)

(I’m not actually using Photoshop, but PSD is the main quasi-interchangeable format that supports layer effects, i.e. inner and outer drop shadows. SVG drop shadows end up rasterized.)

**Comment by dpschen** [comment]
@elsiehupp I love the
> a e s t h e t i c`

😄 

---

@jancborchardt: Any thoughts on @elioqoshi and my icons?

**Comment by jancborchardt** [comment]
Sorry for the missing reply! @dpschen your icon proposal looks great, this is exactly what I meant! Keeping the Nextcloud style and adjusting it slightly to the icon guidelines. :+1: 

cc @claucambra @mgallien if it’s possible to update the icon only for macOS?

**Comment by claucambra** [comment]
> Sorry for the missing reply! @dpschen your icon proposal looks great, this is exactly what I meant! Keeping the Nextcloud style and adjusting it slightly to the icon guidelines. +1
> 
> cc @claucambra @mgallien if it’s possible to update the icon only for macOS?

Yup, totally doable :)

**Comment by elsiehupp** [comment]
Hi @jancborchardt @claucambra @mgallien—

The icon @dpschen mentions here:

> Regarding the gradients: Personally I would also be happy with something like your second column / second row: ![](https://user-images.githubusercontent.com/9206310/117553632-afcfb800-b020-11eb-8ec9-daf72e43fef0.png) Seems like a good compromise!

Is from this set I included when I opened the issue:

> ### Potential Tweaked Designs
> <img width="128" alt="nextcloud-diagonal-3d" src="https://user-images.githubusercontent.com/9206310/117553545-49e33080-b020-11eb-8a81-487d244e49ee.png"><img width="128" alt="nextcloud-diagonal-floating" src="https://user-images.githubusercontent.com/9206310/117553546-4a7bc700-b020-11eb-862c-7261332886e5.png"><img width="128" alt="nextcloud-diagonal-inset" src="https://user-images.githubusercontent.com/9206310/117553547-4b145d80-b020-11eb-8928-bc5ded388902.png"><img width="128" alt="nextcloud-diagonal-rounded" src="https://user-images.githubusercontent.com/9206310/117553614-9cbce800-b020-11eb-950c-286e15b5aa47.png">
> <img width="128" alt="nextcloud-vertical-3d" src="https://user-images.githubusercontent.com/9206310/117553631-afcfb800-b020-11eb-8424-57049317ac5d.png"><img width="128" alt="nextcloud-vertical-floating" src="https://user-images.githubusercontent.com/9206310/117553632-afcfb800-b020-11eb-8ec9-daf72e43fef0.png"><img width="128" alt="nextcloud-vertical-inset" src="https://user-images.githubusercontent.com/9206310/117553634-b0684e80-b020-11eb-9ed1-1adbb8cf2bdf.png"><img width="128" alt="nextcloud-vertical-rounded" src="https://user-images.githubusercontent.com/9206310/117553558-4e0f4e00-b020-11eb-8bd7-76de29f7affb.png">
> <img width="128" alt="nextcloud-hue-shift-3d" src="https://user-images.githubusercontent.com/9206310/117553735-308eb400-b021-11eb-81f3-cd1981f4ff37.png"><img width="128" alt="nextcloud-hue-shift-floating" src="https://user-images.githubusercontent.com/9206310/117553658-ce35b380-b020-11eb-8bf4-e62e33aa94e0.png"><img width="128" alt="nextcloud-hue-shift-inset" src="https://user-images.githubusercontent.com/9206310/117553648-beb66a80-b020-11eb-98ea-e02b9cdb835f.png"><img width="128" alt="nextcloud-hue-shift-rounded" src="https://user-images.githubusercontent.com/9206310/117553724-24a2f200-b021-11eb-8414-9403a5c15ce5.png">

I can easily put an SVG of any of these into a pull request, though only the second or third column would be straightforward to make 100% vector (since they just have basic drop shadows).

Just let me know what you'd like!

**Comment by claucambra** [comment]
Hi @elsiehupp second row / second column would be fantastic, could you post the SVG? Thanks!
