### ISSUE TITLE
Virtual files deleted after moving to its parent virtual folder

### ISSUE THREAD

**Issue by Athorus** [nextcloud/desktop#3296]
Hello,

On Windows with file explorer, when I try to move a virtual file from a virtual folder to its parent one, the file is moved, then few seconds later, when the sync is finished, the file is deleted (I can restore it to its original folder thank to the web page). If I move a virtual file to a virtual child folder, the file is moved properly.

If I move files available locally, all works as expected.

I’m using Nextcloud 21.0.1 on Debian Buster for the server part and Windows client 3.2.1.

Regards,
David.

**Comment by allexzander** [comment]
@Athorus

Is there anything special about that file? I tried locally with a random file, but, couldn't get to reproduce it. Could you do a short screen recording of how this happens for you? (no worries about personal files, you can just use a random non-sensitive file to demonstrate it). Thank you in advance.

**Comment by Athorus** [comment]
A little wmv that shows the bug


[VirtualFileBug.zip](https://github.com/nextcloud/desktop/files/6466081/VirtualFileBug.zip)

**Comment by Athorus** [comment]
@allexzander 

Here a little video showing the issue.

[VirtualFileBug.zip](https://github.com/nextcloud/desktop/files/6466141/VirtualFileBug.zip)

**Comment by allexzander** [comment]
@Athorus 
Is external storage used on the server-side by any chance?

**Comment by Athorus** [comment]
What do you mean by "external storage" ? It is a lvm logical volume.

**Comment by Athorus** [comment]
```
root@serveur:/media# mount |grep next
/dev/mapper/vg-nextcloud on /media/nextcloud type ext4 (rw,relatime,commit=60)
```
```
root@serveur:/media# ll /media/nextcloud/
total 68
drwxr-xr-x 11 www-data www-data  4096 avril 24 14:59 appdata_ocvnwxpjzciu
-rw-r--r--  1 www-data www-data     0 avril 24 14:17 index.html
drwx------  2 root     root     16384 avril 24 14:06 lost+found
-rw-r-----  1 www-data www-data 40392 mai   12 15:47 nextcloud.log
drwxr-xr-x  5 www-data www-data  4096 avril 28 22:08 orus
drwxr-xr-x  5 www-data www-data  4096 avril 24 14:35 root
```

**Comment by Athorus** [comment]
```
root@serveur:/media# cat /var/www/html/nextcloud/config/config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocvnwxpjzciu',
  'passwordsalt' => 'fN4197qjz72W9F+xeyh66ALmlbieVV',
  'secret' => 'IdFZv2JgAKkIIB0DcmZzirRbRIhrQqBQ8FcUDlgYif57cU/c',
  'trusted_domains' =>
  array (
    0 => '192.168.0.1',
    1 => 'serveur',
    2 => 'xxxx.xxxx.xxx',
    3 => 'xxxx.xxxxr.xxxx',
  ),
  'loglevel' => 2,
  'filesystem_check_changes' => 0,
  'datadirectory' => '/media/nextcloud',
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'overwrite.cli.url' => 'http://192.168.0.1/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'nextcloud',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'default_phone_region' => 'FR',
  'owerwriteprotocol' => 'https',
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
  'maintenance' => false,
);
```

**Comment by Athorus** [comment]
One more comment, if I move the file with the webpage, everything is fine.

**Comment by andyxheli** [comment]
I can confirm this. Same thing happens to me. First i created a folder then i moved a folder with in that i took all the file and moved them out of the folder and the client was showing syncing but the status never chnaged to show the cloud icon so then i moved them back to the original folder and all files are deleted.

**Comment by andyxheli** [comment]
Also once i moved the files out of the test folder i cant even delete the folder looks like it locked it.

**Comment by allexzander** [comment]
> @Athorus
> Is external storage used on the server-side by any chance?

I mean external storage set via plug-in with the same name. But, looks like you're not using it.

**Comment by allexzander** [comment]
Weird, the same scenario doesn't bring any issues in my case.

Could you also share the logs archive created right after you've reproduced the issue? @Athorus

**Comment by andyxheli** [comment]
where are the client logs located and id be happy to share them

**Comment by Athorus** [comment]
@allexzander 
What are the logs archive ? Do you mean the nextcloud.file or something else ?

I’ve seen logs can be activated on the client side, I’m working on it.

**Comment by Athorus** [comment]
@andyxheli press F12 to activate clients logs after opening the nextcloud window.

**Comment by Athorus** [comment]
@andyxheli restart your NextCloud client if you don’t see logs.

**Comment by Athorus** [comment]
Here the log from the client 

[20210512_1747_owncloud.log.0.gz](https://github.com/nextcloud/desktop/files/6467389/20210512_1747_owncloud.log.0.gz)
[20210512_1747_owncloud.log.1.gz](https://github.com/nextcloud/desktop/files/6467390/20210512_1747_owncloud.log.1.gz)
[20210512_1747_owncloud.log.2.gz](https://github.com/nextcloud/desktop/files/6467391/20210512_1747_owncloud.log.2.gz)
[20210512_1747_owncloud.log.3.gz](https://github.com/nextcloud/desktop/files/6467392/20210512_1747_owncloud.log.3.gz)

**Comment by andyxheli** [comment]
Here are my logs 

[Logs.zip](https://github.com/nextcloud/desktop/files/6467553/Logs.zip)

**Comment by allexzander** [comment]
Thx. Looks like I see what went wrong:
`Line 630: 2021-05-12 17:47:53:346 [ info sync.discovery ]:	Can't rename because the etag has changed or the directory is gone "Bug/folder/file.md"
	Line 631: 2021-05-12 17:47:53:346 [ warning sync.discovery ]:	Wiping virtual file without db entry for "Bug/file.md"
	Line 632: 2021-05-12 17:47:53:346 [ info sync.discovery ]:	Discovered "Bug/file.md" CSyncEnums::CSYNC_INSTRUCTION_REMOVE OCC::SyncFileItem::Down CSyncEnums::ItemTypeVirtualFile`
	
Probably related to https://github.com/nextcloud/desktop/issues/3270

**Comment by allexzander** [comment]
@andyxheli Your logs seem very recent to me. I couldn't find lines similar to ones in my previous comment. Also, there is no CSYNC_INSTRUCTION_REMOVE in your logs. I guess, it's because they are just created and stored into a temporary folder, since you've used F12 and set that checkbox. Kindly uncheck it, and then, create a debug archive with your logs from the default location. You can do it via UI after unchecking the temporary folder checkbox and then restarting the app. Note: If the issue happened more than 24 hours ago, those logs are wiped already. In any case, I'd suggest you reproduce an issue again and then, create debug logs archive right away. Just to make sure we don't lose important lines and then I'll be able to check if your case is the same as the one that @Athorus encountered.
![image](https://user-images.githubusercontent.com/12224014/118013510-de200100-b35a-11eb-91d7-04bcab425c7c.png)

**Comment by allexzander** [comment]
I'll be working on fix later this week. Thank you for reporting.

**Comment by andyxheli** [comment]
@allexzander  here you go let me know if you need anything else. 

[NC Logs.zip](https://github.com/nextcloud/desktop/files/6467830/NC.Logs.zip)

**Comment by andyxheli** [comment]
Also the sync status never change back to offline when moving files from folder to another. Just stays at syncing. 

![image](https://user-images.githubusercontent.com/59488153/118016913-9928aa00-b31b-11eb-979d-b16b4cb2f453.png)

**Comment by claell** [comment]
@andyxheli see #3440
