### ISSUE TITLE
Make client default to sync none

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/desktop#33]
Based on experience during rollouts - people don't notice (nor RTFM) that the client defaults to sync all. This causes negative experiences of using the sync client which could be avoided if the user was required to select the files they want to sync.

**Comment by DominiqueFuchs** [comment]
Hey @putt1ck , thanks for the input! It's been a long time - but are you still there? 

If yes: I think that the majority of users still expects the client to sync everything that is already present for the particular user (locally or in the remote tree). Talking about "rollout", I understand that this may be different when deploying NC in standardized and/or enterprise environments - what about an additional config setting that disables every folder per default for the initial configuration if present? Then one could deploy this config file with the installation.

**Comment by putt1ck** [comment]
I'm still here :)

Anything that helps stop users from synchronising (trying to synchronise!) 100Gs of data is a good thing.

**Comment by Rello** [comment]
Hello,
the user is getting an information even including a size estimation in the current client versions. So I regard this as solved
![Image](https://github.com/user-attachments/assets/224f08be-bd1a-4d08-b8e9-94e7e2c5512d)

**Comment by putt1ck** [comment]
Defaulting to sync nothing is still an RFE. It makes for a better, safer experience in deployments with large numbers of non-technical users, while causing at worst no pain for technical users; arguably it makes for a better experience for those users also because only in small (home) deployments are you likely to want to synchronise everything. It is also easy to implement.

**Comment by Rello** [comment]
Hello,
This feature is neither available in the brander (enterprise), installer or client config. 
It is also not on our roadmap. As a Enterprise customer, this could be requested for evaluation via the account management.

Regards,
Marcel
