### ISSUE TITLE
Server Replies "409 Conflict" and won't sync some files.

### ISSUE THREAD

**Issue by TooManyHobbies** [nextcloud/desktop#3303]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Files in E2EE folder should sync to server.

### Actual behaviour
Changed files attempt to sync, but fail with the message:
Server replied "409 Conflict" to "PUT.... for each affected file.

### Steps to reproduce
1.Save one of the affected files or create a new file in the same directory.  Wait for NC to sync and notice the 409 error in the GUI.

### More information
I had three files open on my computer for 8 or more hours.  I wasn't using the computer.  No other sync clients were running.  I noticed they weren't syncing.  Also, I could not create a file in the same folder and have it sync.  Any new activity in the folder would not sync.  I could however create a new folder above the the folder that wouldn't sync, and that new folder would work fine.  It seems that the entire  folder containing the file that won't sync is affected.  All of this is happening inside of an E2EE folder.

Also, if you look at the logs, note that the client log is in local time, and that is -4 hours UTC.  One of the events can be seen in the attached nextcloud_client.log at line 5760 and the corresponding server log event is around line 1430.  Hope this helps!  Thank you.

### Client configuration
Client version: 3.2.1

Operating system: 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): qmake / qmake-qt5 aren't found.  dpkg-query -l shows a lot of qt files at 5.15.2

Client package (From Nextcloud or distro) (Linux only): Appimage from Nextcloud

Installation path of client: /home/john/bin/Nextcloud-3.2.1-x86_64.AppImage

Nextcloud version: 20.0.9

Storage backend (external storage):

### Logs

1. Client logfile AND server logfile:   https://gist.github.com/TooManyHobbies/d91a7c9999eb9adfa1bc5b3facd181d1

**Comment by TooManyHobbies** [comment]
One more note.  After a few days of trying to understand this, today I noticed a message about php memory.  I'm sorry I don't recall exactly what it said, but I know it had something to do with not enough memory.  When I searched for a solution it was this:
sudo snap set nextcloud php.memory-limit=512M

Maybe the database is corrupted?

**Comment by TooManyHobbies** [comment]
Closing this issue for now.  I will try to reproduce this on a fresh install of both client and server.  I did clear up the issue by deleting all of the files on the server, and the client, then moving a copy of the data back to the client and setting up a new shared folder on the server.

**Comment by neostorm** [comment]
Had this issue with a setup on a FreeNAS server after a reboot following a power outage. I hadn't opened the app in months so it was behind about 400+ files. It was able to sync some files for the month of 09 but got stuck when trying to create a folder for the last month 10. I ended up manually creating the folder and this solved the 409 error and allowed it to start transferring files from the ios app for images created in the month of 10. I had hoped once it finished with the folder month of 10 it would create 11 and continue without issue. It then fell into the same issue where it would try to upload all the files fail and repeat.
