### ISSUE TITLE
Invalid query (syntax error?) when asking for user_status/api/v1/user_status

### ISSUE THREAD

**Issue by fs1** [nextcloud/desktop#3306]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
no errors in server log

### Actual behaviour
I see a lot of 404 errors in my webserver log like this one:
`0.0.0.0 - - [11/May/2021:23:25:42 +0200] "GET /nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json HTTP/1.1" 404 228 "-" "Mozilla/5.0 (Windows) mirall/3.2.1stable-Win64 (build 20210428) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)" 80101`

### Steps to reproduce
1. install nextcloud windows app
2. regularly the app tries to sync and produces an error in the webserver log

### Client configuration
Client version: 3.2.1

Operating system: Windows 10

OS language: German

### Server configuration

Nextcloud version: 21.0.1
user_status version: 1.1.1

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.

Please tell me if you really need it, as it seems to me, that the Server logs say it all ("Please check the syntax") and it is just a GET query.

2. Web server error log:
`0.0.0.0 - - [11/May/2021:23:25:42 +0200] "GET /nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json HTTP/1.1" 404 228 "-" "Mozilla/5.0 (Windows) mirall/3.2.1stable-Win64 (build 20210428) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)" 80101`

If I try to call this URL on a command line (using curl), I get the same result:
`192.168.2.2 - - [11/May/2021:23:26:08 +0200] "GET /nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status?format=json HTTP/2.0" 404 228 "-" "curl/7.64.0" 90694`

But this way I see a reason for this error:
`{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services.\n"},"data":[]}}`

3. Server logfile: nextcloud log (data/nextcloud.log):
empty

**Comment by fs1** [comment]
Please also have a look at https://github.com/nextcloud/android/issues/8382, as it's pretty the same.

**Comment by gtmadev** [comment]
It's definitely broken. Tried installing with both native and linuxserver.io docker versions. All result in the same error. Disabled all browser plugins, Brave shields, etc. No joy.

I am surprised more people are not reporting this. I have been running Seafile for a long time and decided to take another look at Nextcloud. But it's just not stable.
