### ISSUE TITLE
Windows client wont sync folder with trailing space on name created by GNU/Linux one on Group Folder.

### ISSUE THREAD

**Issue by Ark74** [nextcloud/desktop#3319]
### Expected behaviour
All folders should be synced while using Group Folders  on Windows sync client.

### Actual behaviour
When creating folders with a trailing space inside a Group Folder using a GNU/Linux Sync client, the Windows client won't sync those folders, it's necessary to remove the trailing space on the name for the Windows client to be able to "see" them.

GNU/Linux Appimage is not affected, folders with trailing space on the name sync correctly among GNU/Linux users.
 

### Steps to reproduce
1. Create a group folder.
2. Using GNU/Linux appimage create a folder inside the Group Folder with a trailing space,  'My folder ' and 'Other folder'.
3. Open sync client on a machine with Windows, only 'Other folder' gets synced.
4. Rename 'My folder ' from web interface or GNU/Linux client to 'My folder'
5. 'My folder' now gets synced on Windows client, as before it was completely blind.

### Client configuration
Client version:
Microsoft Windows - 3.2.1
GNU/Linux Appimage - 3.2.1

Operating system:
Windows 10
Ubuntu 20.04

OS language:
es-MX

Qt version used by client package (Linux only, see also Settings dialog):
AppImage

Client package (From Nextcloud or distro) (Linux only):
AppImage

Installation path of client:
N/A

### Server configuration

Nextcloud version: 21.0.1

Group Folder: 9.0.1

### Logs
No error shown, recorded.

**Comment by allexzander** [comment]
@Ark74 Windows is limited indeed when it comes to special characters. I wonder, what would be the use case when you require trailing space in the name?

**Comment by Ark74** [comment]
Not an actual use case.

But group folders are mean to be used by groups, some times large and active groups, so the fact that people might have 'non-standard' typing behaviour, that it could fall on the required naming patter for some kind of document or an actual mistype while naming a folder can break the synergy among teams, lead to uncertainty.

Which is not the right feeling on collaborative software. :laughing: 

Anyway, hopefully this can be looked at or documented, so we can check for restrictions in case this is a won't fix issue.
Thanks.

**Comment by FlexW** [comment]
Just for the record: I think we already provide the user with a warning when files can not be created.

**Comment by Ark74** [comment]
This was a weird case, since there was no error on the logs at all, no sign of something missing.
Just by the time we figure the trailing space in the naming, then we started testing.

Or do you mean a warning on documentation?

**Comment by FlexW** [comment]
@Ark74 There was this pr https://github.com/nextcloud/desktop/pull/3022 that was merged. It displays an operating system notification when a file could not be created because of naming issues. Additionally it creates an entry in the activity log of the main dialog. It was not backported to the 3.2 branch, but it should appear in 3.3.0. Is such a warning/notification enough for you?

**Comment by Ark74** [comment]
Yeah, that would be super useful.
I guess will wait for v3.3, you might close this at will.

Thanks
