### ISSUE TITLE
The option to exclude folders/ files from Syncing, custom sources like in the android version too

### ISSUE THREAD

**Issue by secretmango** [nextcloud/desktop#3325]
Hi, I use the desktopp and android app.

Its really good that the android app can handle various locations,
but the desktop client (afaik) cant. This is pretty annoying.
I also miss the feature to eclude files or folders in the context menu,
because when having everything I want to sync in the folder, everything gets synced, without exception.

But overall great working program! The feature to upload from phone and download to PC is great too!

Best regards!

**Comment by FlexW** [comment]
Is selective sync solving your problem https://docs.nextcloud.com/desktop/2.6/navigating.html#using-the-ignored-files-editor ?

**Comment by firefoxlover** [comment]
Hi,

 

I have a few problems. One is that I often get a sync error with some hidden file called C91DEC5B.

It shows no file ending so I cant put it in the list to ignore.

The feature I would be happy about is a way to ignore Folders or Files by name (specific ones), not their file type.

 

Best regards,

Henning

 

Von: Felix Weilbach ***@***.***> 
Gesendet: Montag, 17. Mai 05 2021 17:07
An: nextcloud/desktop ***@***.***>
Cc: firefoxlover ***@***.***>; Author ***@***.***>
Betreff: Re: [nextcloud/desktop] The option to exclude folders/ files from Syncing, custom sources like in the android version too (#3325)

 

Is selective sync solving your problem https://docs.nextcloud.com/desktop/2.6/navigating.html#using-the-ignored-files-editor ?

**Comment by FlexW** [comment]
You can also put whole file names in the ignore list.

**Comment by firefoxlover** [comment]
Thanks, I will try it !

 

Von: Felix Weilbach ***@***.***> 
Gesendet: Montag, 17. Mai 05 2021 18:25
An: nextcloud/desktop ***@***.***>
Cc: firefoxlover ***@***.***>; Author ***@***.***>
Betreff: Re: [nextcloud/desktop] The option to exclude folders/ files from Syncing, custom sources like in the android version too (#3325)

 

You can also put whole file names in the ignore list.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
