### ISSUE TITLE
NC-Client leads fail2ban to ban my IP adresse 

### ISSUE THREAD

**Issue by DrAxelbauer** [nextcloud/desktop#3340]
I have a strange problem with the NC-Client

Since about 3 weeks my Client in combination with my user is leading my IP address to be baned by fail2ban on the server.

How to reproduce:
1. Connect my Client with my account
2. As soon as the syncing starts a network timeout occurs and my IP is baned by the servers fail2ban.

This happens only with my personal account. I have tried it with a testuser account and with this user the client works as expected. 
I have also tried a fresh full-sync deleting all my data in my local NC folder and connecting my account anew.

Any ideas why this happens?

I am on Ubuntu 20.0.4 having the latest Version 3.2.1-20210429.171749.5901a0f98-1.0~focal1 installed.
Nextcloud version: 20.0.9

[debug.tar.gz](https://github.com/nextcloud/desktop/files/6510523/debug.tar.gz)

Fail2ban log:

2021-05-17 11:31:32,843 fail2ban.actions        [456610]: NOTICE  [haproxy-handshake] Ban myip
2021-05-17 11:46:32,975 fail2ban.actions        [456610]: NOTICE  [haproxy-handshake] Unban myip
2021-05-17 11:47:03,152 fail2ban.actions        [456610]: NOTICE  [haproxy-handshake] Ban myip
2021-05-17 12:02:03,275 fail2ban.actions        [456610]: NOTICE  [haproxy-handshake] Unban myip

May 17 10:36:46 localhost haproxy[301680]: myip:50582 [17/May/2021:10:36:31.033] public/4: Timeout during SSL handshake
May 17 10:36:46 localhost haproxy[301680]: myip:54229 [17/May/2021:10:36:31.162] public/4: Timeout during SSL handshake
May 17 10:36:46 localhost haproxy[301680]: myip:40461 [17/May/2021:10:36:31.258] public/4: Timeout during SSL handshake

**Comment by FlexW** [comment]
I tried to extract your debug archive, but it fails with:
```
gzip: stdin has more than one entry--rest ignored
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
Could you try to create the debug archive with the gui? Go to Settings -> General -> Create Debug Archive...

**Comment by DrAxelbauer** [comment]
... here we go...
[debug.zip](https://github.com/nextcloud/desktop/files/6511265/debug.zip)

**Comment by diditopher** [comment]
This looks like a duplicate of [https://github.com/nextcloud/server/issues/15688](url)
