### ISSUE TITLE
compare 2 files with size 0

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/desktop#3343]
I do not know why these are 0 but it should be possible to delete both files not get rid of the error message
![image](https://user-images.githubusercontent.com/6248560/119031330-4732f480-b9ab-11eb-99ba-70477b69a61e.png)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Tell us how the feature should work

**Comment by FlexW** [comment]
Sorry, but could you please explain more clearly what the problem is, and what you want to be solved?

**Comment by ferdiga** [comment]
as I said, I want to delete 0 Byte files both locally and on the server, which currently is not possible

**Comment by FlexW** [comment]
Are these files on your hard drive? Can they be deleted without the Nextcloud client?

**Comment by ferdiga** [comment]
well one file is on the server one on the local hard drive

**Comment by FlexW** [comment]
If this dialog pops up both of these files are on your computer. They client does not delete files on the server. Are you able to delete them without the client?

**Comment by ferdiga** [comment]
yes I deleted both files manually - cumbersome activity as the error message does not point in which directory the files are

**Comment by FlexW** [comment]
Okay so I think the only thing we can do here is to make the dialog a little bit clearer with adding the path to the file?

**Comment by ferdiga** [comment]
This would definitely help
Nevertheless 2 files with size 0 should be probably be deleted

**Comment by FlexW** [comment]
I don't agree with the second statement. There might be cases where you want to have files that are empty.

**Comment by ferdiga** [comment]
But not 2 of themOn Wed 14. Jul 2021 at 13:40, Felix Weilbach ***@***.***> wrote:
I don't agree with the second statement. There might be cases where you want to have files that are empty.

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
