### ISSUE TITLE
Many popups asking whether to trust a server certificate

### ISSUE THREAD

**Issue by mburnicki** [nextcloud/desktop#3347]
I'm running a NC server at home for a couple of years now. The server is also reachable from the outside world and has a valid https cert issued by "Let's Encrypt", for the hostname/domain seen from the outside.

Of course the cert is not valid for the internal local domain, e.g. if I access to the server locally, inside my intranet. Usually (for Web browsers, Thunderbird, etc.) it is sufficient when i simply acknowledge ONCE that these programs should accept the cert anyway, and I have to do this only once when the cert has been renewed.

Yet, the NC desktop client has not complained very much that the cert was untrusted, but just today it starts to send popup Windows asking if I would trust the cert anyway. Those Windows start to pop up whenever the desktop client is started, and it looks like it asks over and over again, probably for each folder that is checked.

Wouldn't it be sufficient to ask this ONCE, and remember whether the user has selected to accept the cert, or not?

The strange thing is that this has happened the first time today, but neither the server nor the clients have recently been updated, and the https cert is still valid. The Nextcloud App for Android, as well as DavX5 instances connecting from outside don't complain about the cert.

Server version: 20.0.9 on Ubuntu
Client version: nextcloud-desktop 3.1.3 (installed 2021-04-19)
Client OS: openSUSE Leap 15.2 with current patch level

**Comment by WulftheNordicRanger** [comment]
I am also having this issue with my client. I recently migrated my server and the desktop client keeps trying to connect to the old one even though I have signed out and removed the old sync connections. I am running the client on arch linux

**Comment by HWiese1980** [comment]
I'm seeing the same issue. Any idea how to solve it? I am running Nextcloud on a bare metal K8s cluster behind a Traefik IC, which serves a self-signed certificate.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
