### ISSUE TITLE
Message when removing link sharing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#3356]
### Steps to reproduce

1. Share the file via a public link.
2. Delete the shared link.

The words "Public link" are repeated in the message to remove the sharing of a public link. Shouldn't the text string be as follows: `Do you really want to delete the share <i>%1</i>?.`

https://github.com/nextcloud/desktop/blob/755d6724767f54f645b45302004866b0878c53c8/src/gui/sharelinkwidget.cpp#L509

![obraz](https://user-images.githubusercontent.com/47037905/119394373-62b33d80-bcd2-11eb-850c-f818b6aab2b5.png)
_Sorry for the screenshot in Polish 😉._

### Client configuration
Client version: 3.2.1

**Comment by FlexW** [comment]
I think we could check if _namesSupported is false, and if it is false we just display: "Do you really want to delete the public link share".

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
