### ISSUE TITLE
Computer restarts unexpectedly after automatic update

### ISSUE THREAD

**Issue by Mon3yb** [nextcloud/desktop#3360]
### Expected behaviour
User notification for a pending reboot after an update is done

### Actual behaviour
The system just rebooted without any user interaction or notification. There was no clue that Nextcloud was responsible. I had to search the Event Viewer to get to the message why it rebooted.

Nextcloud is installed as the "SYSTEM" user. This might be the culprit but I'm not sure. As we deploy Nextcloud to over 500 computers we can not change it to a "normal" user.

### Steps to reproduce
1. Deploy Nextcloud to a computer using the "SYSTEM" user
2. Wait for the automatic Nextcloud update
3. System reboots automatically without notification or user interaction

### Client configuration
Client version: 3.1.2.20210128

Operating system: Windows 10 20H2

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: "C:\Program Files (x86)\Nextcloud"

### Logs
Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
- Eventviewer Report -> https://gist.github.com/Mon3yb/2b07ecc918a38c19424b7a71516c09a2

There was no debug or other logfile in the described location

**Comment by FlexW** [comment]
Are you a paying customer of Nextcloud? If yes, please use the support channel. You will get faster help there.

**Comment by Mon3yb** [comment]
Thank you for the response. I guess the issue was not with Nextcloud directly. It was an issue of Windows Autopilot and how it handles Software Deployment. Unfortunately it checks the MSI version on every sync and then overwrites the installation if a different MSI-Code was found on the system. 
I still did not expect it to force reboot after an install. I have not noticed similar behavior on other software but this does not have to mean the issue lies with the Nextcloud installer.

Anyway I'm sorry for the inconvenience caused. I closed the issue with this comment. If you want to further investigate it I can help in gathering more information.
