### ISSUE TITLE
Linux nextcloud clutters my Nautilus sidebar with shortcuts

### ISSUE THREAD

**Issue by ilippert** [nextcloud/desktop#3361]
As indicated in other issues, the client offers helpful links in the Linux file explorer (here Fedora, Gnome) to the synchronised folders.
https://github.com/nextcloud/desktop/issues/3307#issuecomment-839944971 indicates this sidebar, for instance.

The problem is when I use Nextcloud extensively, and all the sync connections show up in the sidebar. In my case, I have 4 synced connections - and now nextcloud takes far too much space in the sidebar - and I do not seem to be able to collapse this or configure it to not be shown.

### Feature description
Tell us how the feature should work
Specify in the nextcloud client's global settings, or for each connection, whether the connection should be shown in the sidebar.

**Comment by joshtrichards** [comment]
Duplicate of #1982
