### ISSUE TITLE
No documentation for --background

### ISSUE THREAD

**Issue by uusijani** [nextcloud/desktop#3374]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Preface

Ticking the "Launch on System Startup" box in the desktop client's General settings tab (correctly) adds a `.desktop` file under `~/.config/autostart/`, with the following `Exec` line:

        Exec="/usr/bin/nextcloud" --background

### Expected behaviour
The effect of `--background` should be mentioned in [options.rst](https://github.com/nextcloud/desktop/blob/master/doc/options.rst) (and the resulting [online documentation](https://docs.nextcloud.com/desktop/3.2/advancedusage.html)).

### Actual behaviour
The `--background` parameter is undocumented.

### Client configuration
Client version: 3.2.1
Operating system: Ubuntu 20.04
OS language: English
Client package: 3.2.1-20210429.171749.5901a0f98-1.0~focal1

**Comment by FlexW** [comment]
Are you feeling confident enough to do it yourself?

**Comment by uusijani** [comment]
@FlexW Not really, as I don't know what the parameter does... due to it being undocumented :) Editing options.rst shouldn't be an issue, I'd just need to know what it should say about `--background`.

**Comment by uusijani** [comment]
I can add that to options.rst, but the terse explanation still seems pretty meaningless; at least for me there's no visible difference when I run nextcloud with `--background` compared to running without.

This could be due to [#2333](https://github.com/nextcloud/desktop/issues/2333) though, if running without `--background` is supposed to open the main dialog (which has never worked on Focal). If so, I'd mention this too, something like: "Launch the application in the background (without opening the main dialog)."

**Comment by FlexW** [comment]
@uusijani I admit the explanation is not good. When launching with `--background` the main dialog shows not up on start. Without `--background` the main dialog does show up. You can notice that difference when you have no tray implementation.
