### ISSUE TITLE
Inconsistent trailing text </checksum> in checksums causes move and renames to be rejected

### ISSUE THREAD

**Issue by joholm2** [nextcloud/desktop#3381]
### Expected behaviour
Checksums are compared when assessing potential renames or moves. 
In a real move or rename the "two" files (before and after move or rename) should have the same checksum

### Actual behaviour
In some cases the checksums differ so the rename or move is rejected and a delete and upload is used instead, which can lead to large amounts of unnecessary uploading & downloading. 

The reason for the difference in checksums is due to the presence or absence of trailing text "<\/checksum>" in the stored checksums.

**Note**: this is **not** the same bug as https://github.com/nextcloud/desktop/issues/3270
 
### Steps to reproduce
(Note: We use "non-root" Sync folders")
**A - Specific to move or rename**
1. Carry out several move and or renames of files within the same Sync folder 
2. Find the Nextcloud logs in .../users/<user>/AppData/Roaming/Nextcloud
3. Search for lines containing "checking checksum of potential rename"
4. These lines show the two checksums being compared
5. In all cases the checksum text starts with "SHA1"
6. In some cases the checksum text ends at the end of the 40 character checksum
7. In some cases the text includes a trailing "<\/checksum>"
8. Here an example from a move...

> "SHA1:38ecaef7c28294a7a3bed04efbed7e4c990d2ee3<\/checksum>"
> "SHA1:38ecaef7c28294a7a3bed04efbed7e4c990d2ee3"

9. Since the comparison is a simple text matching, the difference can result in "checksums don't match" even when the actual checskum sequences are identical
10. See attached log for more examples.

**B - General scan of logs**

1. Find the Nextcloud logs in .../users/<user>/AppData/Roaming/Nextcloud
2. Unpack them (eg "gzip -d *.gz")
3. Scan the logs for lines which include checksums, and look for presence or absence of "<\/checksum>"

> grep "SHA" * | grep "<\/checksum>"
> grep "SHA" * | grep -v "<\/checksum>"

4. Result...

> there are numerous log entries showing checksums **with** trailing text "\/checksum text
> there are numerous log entries showing checksums **without** trailing text "\/checksum text

### Client configuration
Client version: Version 3.2.50 (Windows) = Version 3.2.1 with bug fix for https://github.com/nextcloud/desktop/issues/3270
Update: logs from earlier use of version 3.2.1 have now been checked and show same differences in checksum text.
Update: logs from latest version 3.2.3 have now been checked and show same issue.

Operating system: Windows 10 Pro

Installation path of client: Default

###Server configuration
Nextcloud version: 21.0.2, Ubuntu 20.04.2

Storage backend (external storage): SMB, Raid, Western Digital

### Logs

[checking_checksum_trimmed.txt](https://github.com/nextcloud/desktop/files/6564327/checking_checksum_trimmed.txt)

**Comment by joholm2** [comment]
@allexzander 
Hi, you were very helpful with the previous bug I found #3270.
But now we are back, stuck with an equally serious problem but seemingly a different bug caused by mismatched checksum formats.
I'm just puzzled that 9 days have gone by and there is still no response on this post.
Do you know whether anyone will look at this?
Thanks!

**Comment by allexzander** [comment]
@joholm2 We are all very busy solving different issues at the moment. Someone will definitely going to look into this issue when we have more time. Thank you for reporting it.

**Comment by joholm2** [comment]
@allexzander 
Ok; thank you very much for your quick response!

**Comment by joholm2** [comment]
Hi @allexzander,

What does "0. Needs triage" actual entail? How will that happen? Who does it? Is there anything more I can do? 

I haven't been able to find where this strange text "</checksum>" is coming from. I've searched all the code I can find.

But it is still there in Destop client 3.2.3

**Comment by joholm2** [comment]
I have just installed Nextcloud client 3.2.4 and confirmed the error is still present there.

Extract from a log where a simple move was handled as a new file (create) and old file remove (delete)

2021-08-01 15:15:07:353 [ info sync.discovery ]:	checking checksum of potential rename  "Data/7 - Scans/A999_Bg850-4201_Insättningsuppgifter_Detaljer_20210714.pdf" "SHA1:957b348c0f54aa4b7d28cd356f0f467956d568a8" "SHA1:957b348c0f54aa4b7d28cd356f0f467956d568a8\</checksum>"
2021-08-01 15:15:07:353 [ info sync.discovery ]:	Not a move, checksums differ

**Comment by mgallien** [comment]
This will be solved once we release 3.3.2 release at end of the month.
Please open a new issue if you ended up having troubles once you have tested that version.
