### ISSUE TITLE
Access direct link instead of randomized public link via client

### ISSUE THREAD

**Issue by jonvog** [nextcloud/desktop#3382]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I very often need to embed video files in a 3rd party app (CueDB). This app needs public direct links to work and I'd like to access these direct links directly via the context menu in the Nextcloud folder in my local file explorer. At the moment I have to create a public link, paste it to a browser, open it, right click the download button and copy the link address. It is possible, but very inconvenient, if I have to do this a lot.

**Describe the solution you'd like**
I would like to have another entry in the file explorer context menu that lets me copy the direct link instead of the default public link.

**Describe alternatives you've considered**
A setting that lets me choose whether "copy public link" copies the randomized public link or the direct link into the clipboard.

**Additional context**
Dropbox does this exactly as I want it to (but I'd like to use Nextcloud instead)

**Comment by FlexW** [comment]
@kesselb is there already an API on the server that allows us to get that link?

**Comment by kesselb** [comment]
Hey @FlexW,

sorry for my late reply. I don't think we include the url to download a file directly somewhere. It should be possible to generate the url to download a url if you know the token. filename is optional.

Show share: `/s/{token}`
Download share: `/s/{token}/download/{filename}`

https://github.com/nextcloud/desktop/blob/4992977167b8cfc2319a6f642d1c08c02cf4f670/src/gui/sharemanager.cpp#L176-L181

This approach looks correct to me. getDirectDownloadLink is not used in desktop. 

https://github.com/nextcloud/desktop/pull/2234 and https://github.com/nextcloud/desktop/issues/2230 look related.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by jonvog** [comment]
Hi,
the client has improved a lot since, but as far as I can tell this is still not possible (and it still would be a feature my workflow could benefit from). In the file context menu it's possible to choose from the options *internal link* and *public link*.
What I need is a direct public link. At the moment I still have to paste the public link into a browser in order to access the direct link from there.

**Comment by Rello** [comment]
Hello,

yes. sorry for the incorrect wording here. The use case is a little limited in order to enhance the share menu for every user out there.

thank you

**Comment by jonvog** [comment]
yeah got it. and I see the context now, since in the last client version it got a lot worse for users that need a direct link.
It's now 8 clicks/actions instead of a single one and quite a tedious process if you have to get direct links for a lot of files (which is the case in my daily workflow for a lot of tasks) and clearly for us it's not a UX improvement at all, but I can see that the same doesn't apply to every other user out there. maybe at some point we can get a smooth option for this task that doesn't clutter the menu for others (like the option to reveal the direct link entry through a setting for instance).
