### ISSUE TITLE
Main Dialog Display Missing in 3.2+ Windows Desktop Client

### ISSUE THREAD

**Issue by azon2111** [nextcloud/desktop#3389]
The main dialog wants to show but the window is never drawn on the screen so cannot resolve sync issues or anything of that nature.  Wondering if an app cache issue from upgrading from earlier versions.

![Main-Dialog-Screen-Missing](https://user-images.githubusercontent.com/5655647/120317493-b0204380-c2ac-11eb-8d35-f27d39919e51.JPG)

**Comment by FlexW** [comment]
What happens if you click on the tray icon on the right hand side (The one with the green checkmark)? Does it open a dialog?

**Comment by eckhardtj** [comment]
Hi,

same problem here. I installed Nextcloud Client 3.2.2 on Windows 10 20H2 (64-bit). The main dialogue does not show up. Right click on the tray icon behaves normally. The settings dialog opens as usual.
