### ISSUE TITLE
Rename repository to "desktop"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/desktop#339]
Is this possible without breaking everything? Client is iOS, Android - nearly everything. Desktop would be more descriptive 🤔 What do you think?

@rullzer @camilasan

**Comment by camilasan** [comment]
It makes sense to me. Just not sure how much work is to update everything - where else we would have to change it?

**Comment by juliushaertl** [comment]
Probably better to do it now, as we don't have a released a version out of this repo yet, but as @camilasan I cannot say what might break then. 

Is github redirecting renamed repos?

**Comment by rullzer** [comment]
I don't have a preference here. I can move it.

**Comment by rullzer** [comment]
Done
