### ISSUE TITLE
crash of explorer at update 3.2.2 ... 3.3 -> reboot needed it because complete loop crash of explorer.exe

### ISSUE THREAD

**Issue by boistordu** [nextcloud/desktop#3399]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
the upgrade does not crash completely explorer and make it enter in a endless crashs loop and simply give me a window to ask me to reboot.

### Actual behaviour
endless crash loop of explorer.exe
had to ctrl-alt-delete

### Steps to reproduce
1. simply upgrade 3.1.2 to 3.2.2 on windows 20H2 or 21H1
2. highly reproduceable on every windows client I had. 
3.

### Client configuration
Client version: 3.2.2

Operating system: windows 10 pro

OS language: FR or ENG following the hosts

Installation path of client: C:\Program Files\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

https://1drv.ms/u/s!AqgwRql30Mi5tJ9e8aHnGoHlSBlP0g?e=zbQMSf

28MB of logs

this happened in the event viewer
20 of them. You can see the start time difference. followed by 8 windows error reports each

Since it happened on different hosts. The only thing in common besides OS is the presence of boxcryptor and veracrypt. You might look into that

```
Faulting application name: explorer.exe, version: 10.0.19041.1023, time stamp: 0xc438eef0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0000602
Fault offset: 0x000000000010b39c
Faulting process id: 0xc868
Faulting application start time: 0x01d7572c9d0b239b
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 44ecfbcd-7d2b-4ca3-bc70-ff4c5a9cb7d2
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Faulting application name: explorer.exe, version: 10.0.19041.1023, time stamp: 0xc438eef0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xc0000602
Fault offset: 0x000000000010b39c
Faulting process id: 0xcc70
Faulting application start time: 0x01d7572c9acf1d38
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 282dd660-9978-4abe-b4ba-d6e8cd343937
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by splitt3r** [comment]
I had no problems upgrading the client to the latest version on latest Windows 10 with ENG lang. It worked like a charm 👍🏻. Maybe sth. special about your setup?

**Comment by boistordu** [comment]
I've specified everything that could influence it in the description.
Nothing special besides that. 
This is no security software involved. The only 2 software that could have influenced has been cited.

And as I said, it happened on all my hosts, which are 5 at the moment.... So....

**Comment by StarSmasher44** [comment]
Ever since updating and enabling virtual file system, after a short while nextcloud completely froze up, and explorer.exe failed to respond in any way possible.
Closing Nextcloud process cleared the block and everything worked again.

2nd time around I couldn't kill the process any more (even as admin) and had to reboot... Then Nextcloud froze again, and so did Explorer.

So kind of have the same issue, but slightly worse. Already deleted the whole config folder, reinstalled nextcloud with 0 effect.

**Comment by boistordu** [comment]
> Ever since updating and enabling virtual file system, after a short while nextcloud completely froze up, and explorer.exe failed to respond in any way possible.
> 
> Closing Nextcloud process cleared the block and everything worked again.
> 
> 
> 
> 2nd time around I couldn't kill the process any more (even as admin) and had to reboot... Then Nextcloud froze again, and so did Explorer.
> 
> 
> 
> So kind of have the same issue, but slightly worse. Already deleted the whole config folder, reinstalled nextcloud with 0 effect.

Do you have any other soft ? I mean by that any other cloud soft sync ? Any encrypting capability software ? Any security software ?

**Comment by nssatlantis** [comment]
> > Ever since updating and enabling virtual file system, after a short while nextcloud completely froze up, and explorer.exe failed to respond in any way possible.
> > Closing Nextcloud process cleared the block and everything worked again.
> > 2nd time around I couldn't kill the process any more (even as admin) and had to reboot... Then Nextcloud froze again, and so did Explorer.
> > So kind of have the same issue, but slightly worse. Already deleted the whole config folder, reinstalled nextcloud with 0 effect.
> 
> Do you have any other soft ? I mean by that any other cloud soft sync ? Any encrypting capability software ? Any security software ?

Nothing runs in the background, I have no encryption anywhere, not even nextcloud, I have default windows AV and it is not the issue either, no other sync clients.

It does connect to nextcloud and starts first sync, but shortly thereafter freezes nextcloud app & explorer.exe and that's just the end of it..

**Comment by boistordu** [comment]
Yeah so definitely it's a bad call to explorer.exe something like that then. 
For me other variables could have been taken into account like Dokan library and such

**Comment by nssatlantis** [comment]
2 weeks, 0 comments.. Guess I won't be using the nextcloud windows app for a while

**Comment by FlexW** [comment]
@nssatlantis Did you try to uninstall the client and install it again?

**Comment by simonrich** [comment]
Same problem here. Replicates exactly like mentioned by nssatlantis. Installed windows client 3.2.2. After a couple of reboots, the explorer did even open until I killed nextcould through the task manager. NC client not working obvisously.

Win 10 Pro (2004 Edition)

**Comment by Meth0d007** [comment]
Did you try not using the "explorer integration" ?
I don't have this issue as NC is not crashing on my w10, it's just not syncing. (See other issues)  
3.2.2 seems totally bugged on Windows, only way to 'work' with NC for me was to revert all clients to 3.1.3 by hand.

**Comment by boistordu** [comment]
I'm going to reinstall completely windows on one of the client and if I see this problem again, seriously you have to listen to feedback a little bit guys. You can't just develop your app and then based on the fact that it s running in a windows vm with nothing installed, you would assume that it's working. 
We all know it's not the case for so many reasons.

**Comment by boistordu** [comment]
Yay same problem with 3.2.3.... seems that it is difficult to make hear our voices around here...

**Comment by boistordu** [comment]
So same thing happened with 3.2.4. 
There has been also an interesting thing on fedora, nextcloud crashes when being updated.
It might be something or not, didn't dig into it yet. But the only common thing that could exist between fedora and windows, it's that the files are stored in a Veracrypt container, open at the time of the upgrade. And actually on fedora veracrypt crashed when nextcloud have been upgraded.

**Comment by boistordu** [comment]
Still happening in 3.3

How difficult is it to put a reboot popup in the installer

**Comment by nssatlantis** [comment]
> Still happening in 3.3
> 
> How difficult is it to put a reboot popup in the installer

Not sure why you had to change the title, a reboot has never fixed the issue for me nor many others, it isn't the prime issue.

**Comment by Tha14** [comment]
![image](https://user-images.githubusercontent.com/5931740/128541506-4099ee2f-54e1-44b2-9fd7-cd2a26931a48.png)
Is this the same problem? This should not be happening guys...

**Comment by bossanovaorca** [comment]
just ran into this while updating to 3.3.2

**Comment by philippgs** [comment]
Happened to me for several updates of the client, including the latest 3.3.3. `explorer.exe` gets shutdown but not re-started and when started manually via the task manager, it crash-loops until reboot. Explorer integration is enabled.

**Comment by loufidelity** [comment]
I had a similar problem for two of the latest updates now. For example today when updating to 3.3.3. 

After update, Windows taskbar is gone and explorer doesn't restart. I can still alt-tab to some of the open apps. When starting explorer manually from Task Manager, windows task bar appears but is flashing about every second. Seems that explorer is in a crash loop. Rebooting the computer works.

**Comment by mgallien** [comment]
> I had a similar problem for two of the latest updates now. For example today when updating to 3.3.3.
> 
> After update, Windows taskbar is gone and explorer doesn't restart. I can still alt-tab to some of the open apps. When starting explorer manually from Task Manager, windows task bar appears but is flashing about every second. Seems that explorer is in a crash loop. Rebooting the computer fixes the problem.

what did you do when the installer is asking for a reboot at end of install ?
it happen that I have just done an upgrade from 3.3.2 to 3.3.3 without any troubles (but selected manually the process to kill when the installer asked me to do it)
I even skipped the popup asking for a reboot at the end

**Comment by matthiastummers** [comment]
Now the same happens with OwnCloud: https://github.com/owncloud/client/issues/8995

**Comment by boistordu** [comment]
For what I've experienced there is some kind of incompatibility with Veracrypt or Dokan filesystem. Veracrypt is crashing when updating nextcloud client and that's under fedora. 
So in my case a reboot has always fixed the situation but this also means for those where a reboot doesn't fix the problem, that nextcloud encrypted container is giving some problems to general filesystem. 

So to others where reboot doesn't fix the problem, which kind of third party software are running at the same time of an upgrade ?
