### ISSUE TITLE
Sync client doesn't "see" overly long file paths as an error

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/desktop#34]
So, this one's an edge case, but...

a customer using NC for a massive government funded project had to use a clunky Java plugin based portal, which managed to create files with paths longer than Windows (8.1) supports;
where Windows applications in general error on attempted access with a message about file path being too long, NC fails silently and doesn't notify the user.

For a typical end user this just seems like their files didn't sync and they don't know why.

**Comment by camilasan** [comment]
@putt1ck  Do you still have this problem with 2.3.3?

**Comment by putt1ck** [comment]
Good question! Because of being such a weird edge case (you need an application that can write file paths longer than Windows support, which is quite a few bugs all on their own) and indeed be using Windows (ditto...) it's not easy for me to reproduce this. The client with the issue had to shorten the file paths so they could access them with other software, so we can't even test there.

**Comment by camilasan** [comment]
ok @putt1ck let us know when you can test with the latest client. Thanks for the report.

**Comment by putt1ck** [comment]
I think the client has fixed the paths, so testing will require someone to work out how to force overly long paths (apparently it can be done with Java...).

**Comment by camilasan** [comment]
We are not supporting Windows 8.1 anymore (neither is Microsoft...).

If you still have this problem with the latest desktop client (running on a supported platform), please re-open the issue.

Thanks!
