### ISSUE TITLE
macOS deskop client icon pressed flat on inactive monitors

### ISSUE THREAD

**Issue by JoCord** [nextcloud/desktop#3408]
### Expected behaviour

The icon

<img width="47" alt="image" src="https://user-images.githubusercontent.com/20401703/120962564-44ccea80-c760-11eb-9dde-9cd2211e0a1e.png">

### Actual behaviour
On the main/active monitor this is correct - on all other it looks like this:
<img width="43" alt="image" src="https://user-images.githubusercontent.com/20401703/120962616-5d3d0500-c760-11eb-8f62-6acb412c7ef0.png">

**Operating system:**
macOS 11.4, 11.6
Desktop Client 3.2.2, 3.2.4, 3.3.6 (but this issue also exists on older versions)

**Where did you install Nextcloud from:**
I downloaded the desktop client from the homepage for nextcloud desktop clients

**HW:**
I checked this on different monitor (notebook display or external monitor) and resolutions. My setting on the monitor configuration is: "Resolution: Scaled"

**Misc:**
I think you do not need any log files or server config date - do you?

**Comment by FlexW** [comment]
Are you have this issue on both computers? As I'm not able to reproduce it with macOS BigSur 11.4 and Client 3.2.2. I tried with Resolution scaled and resolution set to default for display.

**Comment by JoCord** [comment]
> Are you have this issue on both computers? As I'm not able to reproduce it with macOS BigSur 11.4 and Client 3.2.2. I tried with Resolution scaled and resolution set to default for display.

I have tested it on a Macbook Pro 16 (2 * 5k LG Displays + Notebook Display) and on a MacMini (2 * 5k LG)

**Comment by FlexW** [comment]
@JoCord Please see my edited comment.

**Comment by uidproberlin** [comment]
I can confirm this bug. You can see it in at least two monitor hardware environments.

**Comment by matt-horwood-mayden** [comment]
I too get this (MacBook Pro (15-inch, 2017)), with both displaylink and displayport screens

main screen (external monitor) ![image](https://user-images.githubusercontent.com/17851531/132333834-77678c36-94b3-47ac-b3b2-805d80e92979.png)
Second screen (external monitor) ![image](https://user-images.githubusercontent.com/17851531/132333870-44d5ed3f-fedc-40c3-bfa8-9d49f27d8d08.png)

**Comment by akufuncture** [comment]
+1 and it’s been hella bugging me. Not sure why the fix is so hard 😭

**Comment by JoCord** [comment]
I installed version 3.4.2 (Nextcloud Desktop Client) and it is fixed.

Main monitor: 
<img width="38" alt="image" src="https://user-images.githubusercontent.com/20401703/151919296-1dc81a98-f0ce-4b33-adf5-e3993a81be55.png">

Second monitor:
<img width="33" alt="image" src="https://user-images.githubusercontent.com/20401703/151919326-23d6fd15-f510-481f-9e02-3caeabadf0e6.png">

Thank you very much for your support!

If nobody else has problems with it, i would close the issue.

**Comment by matt-horwood-mayden** [comment]
ThYes have just installed 3.4.2 and it is fixed, I think 3.4.1 also fixed it
