### ISSUE TITLE
Make it lean !

### ISSUE THREAD

**Issue by gfalquet** [nextcloud/desktop#3413]
The desktop application takes 399MB on disk (MacOS.)  That's half the size of a Linux distribution.  This certainly means that the binary contains huge pieces of software that are not used and must be removed.

**Comment by FlexW** [comment]
Fo me it is only 226.9 MB on macOS. The application bundle on macOS contains the complete Qt framework and this alone is 186 MB. Qt is known to be big and there is no way to make it smaller.
