### ISSUE TITLE
[VFS] Windows client hangs when you "make available offline" the `.sync_*` files

### ISSUE THREAD

**Issue by stavros-k** [nextcloud/desktop#3417]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client don't hang

### Actual behaviour
When using VFS, and "Make available offline" the files _.sync_*dc.db* the client will hang, even after windows reboot, or app restart.
In order to fix. 
* Shudown nextcloud server
* reboot windows (or kill app)
* restart app
* disable vfs
* start nextcloud server

### Steps to reproduce
1. Right click .sync*db* files and "make available offline"
2. Wait a sec 
3. Client hang

### Client configuration
Client version: 3.2.2

Operating system:

OS language: Eng

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 21.0.2

Storage backend (external storage): Local file system

### Logs

https://gist.github.com/stavros-k/11517a54ab9b592e5dda9f30862ecd50

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log): No errors logged

**Comment by FlexW** [comment]
This should be fixed by https://github.com/nextcloud/desktop/pull/3390 and will be available in the next release.
