### ISSUE TITLE
Client won't open / no icon Xubuntu 18.04

### ISSUE THREAD

**Issue by leighss** [nextcloud/desktop#342]
Now I am on 18.04 Xubuntu, but I had similar probs on 16.04
I installed the client via `ppa:nextcloud-devs/client` - its version 2.3.3

If I have no sync folders then the client starts manually normally (I have start at system startup disabled)

Also, it starts manually with only the sync folder of the partition on my laptop:
(‘mnt/DATA’, LABEL=DATA’ ‘mount at system startup’)

However, The client will not open if I manually start it from the menu (At least there is no icon, although `ps -ef | grep nextcloud` shows a nextcloud process) when I have my external disk sync folders added
(‘mnt/Red 1TB’, LABEL=Red 1TB’ ‘mount at system startup’)

I can, however, still open the client with the external sync folders, but have to do this:

1. start from menu, no icon but nextcloud process running
2. wait approx 3 minutes, until the process is ended / no longer running (no idea what stops it)
3. start from menu again and icon appears and client runs as expected

Start at system startup also doesn't work, but I guess this is due to the same problems causing the difficulty in manual starting? Or this will be the next problem to solve if it a separate one (I have tried sleep delay)

**Comment by leighss** [comment]
The problem is with the external NTFS Red 1TB disk - if I remove that the client opens at startup or manually, giving the red cross (source missing) icon. Then, when I plug in the external disk the client starts functioning normally.

**Comment by sakuraiyuta** [comment]
I got same problem.

Env:
* Linux Mint XFCE Edition 19.1
* Nextcloud client ver 2.5.2git
* NC sync folder is external SMB/CIFS network storage (written on `/etc/fstab`)


---

After system booted, executing nextcloud-client from terminal, wait a few minutes, and got error:

```
$ nextcloud --logdir /home/user/.config/Nextcloud/ --logdebug
ICE default IO error handler doing an exit(), pid = 20990, errno = 32
```

Then I tried to unmount external storage, start NC client, mount storage again, and got to works well...same as @leighss .
(Notice: `mount -o remount` doesn't make no effects)

```
$ umount {$SYNC_DIR}
$ nextcloud # shows desktop icon(red cross)
$ mount {$SYNC_DIR} # NC client starts to sync...maybe no problems there
```

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

**Comment by exaveal** [comment]
lol what a fuck. closed automaticallyy. Error still exists.
