### ISSUE TITLE
bug translation in french linux

### ISSUE THREAD

**Issue by x0rld** [nextcloud/desktop#3423]
### Expected behaviour
Have all the text in French

### Actual behaviour
There is some sentence in English

![image](https://user-images.githubusercontent.com/45242856/121417671-744f4300-c96a-11eb-9829-cb4fd1fc1b63.png)
It looks like it's not a missing translation because I found it in the client_fr.ts 
https://github.com/nextcloud/desktop/blob/470a89dfaed26ce8f7a911d9b4870be4bbe842e6/translations/client_fr.ts#L4976
https://github.com/nextcloud/desktop/blob/470a89dfaed26ce8f7a911d9b4870be4bbe842e6/translations/client_fr.ts#L5021
https://github.com/nextcloud/desktop/blob/470a89dfaed26ce8f7a911d9b4870be4bbe842e6/translations/client_fr.ts#L5032

### Steps to reproduce
1.Connect to a new nextcloud 
2. allow it in the browser
3. the text for synchronize is not only in french
### Client configuration
Client version: 3.2.1
Operating system:
fedora 34
OS language:
French
Qt version used by client package (Linux only, see also Settings dialog):
5.15.2
Client package (From Nextcloud or distro) (Linux only):
nextcloud-client on fedora repos
Installation path of client:
/usr/bin/nextcloud

### Logs
https://pastebin.com/9tGyqzS3

**Comment by FlexW** [comment]
These new translations are only in master. They are not yet in the 3.2 branch. There were some recent changes. You can verify this if you look at the branch that was tagged with 3.2.2.
