### ISSUE TITLE
TXT-Files Federated-Cloud-Sharing The downloaded file is empty

### ISSUE THREAD

**Issue by KGremmer** [nextcloud/desktop#3428]
### Expected behaviour
There should be no errors

### Actual behaviour
TXT-Files shared from another Nextcloud-System are empty, when you download it from the browser or from the nextcloud-Client
Error-Message from the Nextcloud-Client:
The downloaded file is empty, although the server has transmitted 5 B as size
The preview in the Browser is working.

### Steps to reproduce
1. Share a folder from Nextcloud-System-A to Nextcloud-System-B
2. Upload a txt-File
3. Download the file with a Browser from Nextcloud-System-B or with the Nextcloud-Client

### Client configuration
Client version: 3.2.2.20210527

Operating system: Windows 10 Enterprise 20H2

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): /

Client package (From Nextcloud or distro) (Linux only): /

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 21.0.2

Storage backend (external storage): /

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[Debug-Client.zip](https://github.com/nextcloud/desktop/files/6637253/Debug-Client.zip)

2. Web server error log: No errors

3. Server logfile: nextcloud log (data/nextcloud.log): No errors

**Comment by mhoffmann75** [comment]
Exact same behavior here. Files with extension .txt cannot be synced with desktop client from federated share.
- Renaming file to .md making it sync. Reverting back to .txt gives same error.
- Same file in Nextcloud Web works fine.
- local files (not federated) work ok
- Some older .txt files (created in ealier nextcloud versions) work on federated share

Reproducible with 2 nextcloud 20.0.10 instances (from official docker image; each one behind Nginx proxy as TLS proxy - see Nginx config for reference https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/proxy/uploadsize.conf)
Syncing with nextcloud desktop for macOS 3.2.2 or on windows with latest nextcloud desktop client.

**Comment by mgallien** [comment]
@KGremmer @mhoffmann75 
sorry that nobody humans really looked at this ticket when you commented here
can you still reproduce that bug ?
in case you can, may I ask you to try with the latest release (3.3.2 now) and share your logs ?

**Comment by mhoffmann75** [comment]
Thanks for the reopening. With desktop client 3.3.2 (macOS) against nextcloud server 21.0.4 and federated remote side being nextcloud 20.x the bug is still present. I will report back after updating remote side.

**Comment by KGremmer** [comment]
I think there is no Bug in the Client, because you cant even download the txt-files correctly from the browser.
For me its a bug in the Nextcloud-Core or in the Federation-Plugin.
I uploaded the Debug Logs to nextcloud/server#24026

**Comment by mgallien** [comment]
thanks @KGremmer

**Comment by KGremmer** [comment]
Still in 21.0.5.
Update to 22 not available for me yet.

**Comment by KGremmer** [comment]
Fixed or me in 22.2.0
