### ISSUE TITLE
client 2.5.1 delete local files

### ISSUE THREAD

**Issue by mroldao** [nextcloud/desktop#3430]
strange thing happens in a user using 2.5.1 nextcloud client.
he has a folder with sync problems, when the errors were fixes and starts to sync, the nextcloud client delete the local files inside that folder. 
why? there is anything we can do to recover those delete files? 
sync db file?
this is a tremendous loss, because are important files. 
any help?

**Comment by FlexW** [comment]
@mroldao Do you still have the issue with the recent version of client (3.2.2)?
