### ISSUE TITLE
Win10-Desktop - Possible SYN flooding on port 443 and broken pipe's

### ISSUE THREAD

**Issue by UN-pi** [nextcloud/desktop#3431]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Windows-Client 3.2.2 should sync without syn-flooding messages and broken pipes

### Actual behaviour
I am using a v-server to access my home-server with nextcloud, because I only have a DS-lite-connection.
So all the traffic is going over the v-server with socat-services.
Running the android-app or access over the browser works normal. No error or synflood-warnings are shown.

When starting the Win-Desktop-client the v-server log this message 2 times:
TCP: request_sock_TCPv6: Possible SYN flooding on port 443. Sending cookies.  Check SNMP counters. 
TCP: request_sock_TCPv6: Possible SYN flooding on port 443. Sending cookies.  Check SNMP counters. 

and the socat-service:
443_socat6[6400]: 2021/06/09 12:43:22 socat[6455] E write(6, 0x56216edfe2e0, 2856): Broken pipe

Tell us what happens instead
please see above notice

### Steps to reproduce
Maybe the client is connecting so quickly with so many https-connection-requests, that the server shows the
syn-flood-message.
The broken-pipe also maybe be a result because the server is sending syn-cookies and the home-server has closed the connection.

As a workaround I startet socat with -t0 -Parameter so there is no langer the default 0,5 Sec. delay for the connection.

Increasing the sysctl.conf-Parameter doesn't help
# net.ipv4.tcp_max_syn_backlog - How many half-open connections.
# for which the client has not yet sent an ACK response can be kept in the queue
# default 128
net.ipv4.tcp_max_syn_backlog = 65535

# Increase number of incoming connections
# Default: 128
# the maximum value that .tcp_max_syn_backlog can take.
# Hgiher values are silently truncated to the value of .somaxconn
# In older Kernels this value can not be higher than 65535
net.core.somaxconn = 65535

### Client configuration
Client version: 3.2.2

Operating system: win10

OS language: de

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 20.0.10.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Please provide the desktop client logs:
- Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
- On previous releases: Via the command line: nextcloud --logdebug --logwindow or nextcloud --logdebug --logfile log.txt (See also https://docs.nextcloud.com/desktop/3.1/troubleshooting.html#log-files)
Thanks!
