### ISSUE TITLE
Compleate freeze after first setup nad reboot (VFS)

### ISSUE THREAD

**Issue by fenpaws** [nextcloud/desktop#3447]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
After the initial setup and a reboot it should sync normally, or in my case generate placeholders (VFS).

### Actual behaviour
The initial setup it works fine, it generates everything and is up and running. 
After a reboot everything freezes, Nexcloud Desktop and the Explorer at times, i can't open the App or close it. Task manager is the only option.

After killing the app that Explorer reacts normally again. 

### Steps to reproduce
1. Install nextcloud Desktop 3.2.2
2. Set it up
3. Reboot

### Client configuration
Client version: 3.2.2

Operating system: Windows 10 21H1

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 20.0.8

### Logs

1. Client logfile: 
Well, we have a problem here, I can't get ANY logfile. 
I tried multiple things, `.\nextcloud.exe --logdebug --logwindow` and `.\nextcloud.exe --logdebug --logfile log.txt` but NOTHING works.
With the `--logwindow` i get this:
![dwm_u6wZy2x76e](https://user-images.githubusercontent.com/29946173/122091329-f9be7180-ce08-11eb-9def-4b6acfa9cb4c.png)

**Comment by FlexW** [comment]
How many files do you sync and how big are they?

**Comment by claell** [comment]
Possibly #3451 is related?

**Comment by fenpaws** [comment]
> 
> 
> How many files do you sync and how big are they?

If my Windows Explorer tells the truth it would be around 44069 files. (237GB)
Most of them are projekt files from Unity, around 38524 files (3.29GB)

**Comment by nssatlantis** [comment]
In my case it was a aingle 500mb folder.. hardly anything large

**Comment by claell** [comment]
Reopening, since this bug is probably still existing.

**Comment by claell** [comment]
Reopening again, since I don't think relevant code for this has changed in the meantime.

**Comment by mgallien** [comment]
I am afraid that without logs we cannot really understand what is happening and fix it
so could affected people post their logs ? that would be nice

**Comment by fenpaws** [comment]
Well as I stated in my initial post it's impossible to get any logs when the whole program just locks up, and the explorer. If you could give any hints on how we can provide logs then please do.
