### ISSUE TITLE
Crash when trying to create folder from settings menu

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Create a new folder from the settings when using virtual files on Windows.

### Actual behaviour
Client crashes when creating a new folder from the settings menu.

### Steps to reproduce
1. Setup a folder with Virtual files enabled on Windows
2. Go to the settings
3. Right-click on the folder and create a new folder
4. Observe the crash (in debug mode, in release it probably won't crash because the assert is then not compiled in)

### Client configuration
Client version: 3.2.2

Operating system: Windows 10

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
