### ISSUE TITLE
Synchronization issue with NextCloud for Windows

### ISSUE THREAD

**Issue by sebsimappus** [nextcloud/desktop#3459]
Hello,

I am coming to you following a big synchronization problem between the NextCloud server and the software for Windows.

The files are present on the server and the NextCloud software for Windows downloads 3/4 of the files.

Each folder is created in the same way by the same member.

In addition, the latest version of the software crashes at each syncronization, we are obliged to download an old version 3.1.1.

thank you in advance
![1](https://user-images.githubusercontent.com/37553261/122547999-1806b600-d031-11eb-948e-2d71752e0671.jpg)

**Comment by sebsimappus** [comment]
Hello,

I come back to you following my last post, I found the problem, the files which are not download by Nextcloud on Windows comes following a space at the end of the name of the file, a colleague who uses a mac. see Attachment.

cordially
![Capture d’écran 2021-06-18 125133](https://user-images.githubusercontent.com/37553261/122563785-e992d600-d044-11eb-94f0-0da15ba91560.png)

**Comment by FlexW** [comment]
Windows do not support spaces in file names. That's why they are not downloaded. In the next feature release, there will be a better warning when files could not be created.
