### ISSUE TITLE
Some files not syncing:  server reply: not acceptable

### ISSUE THREAD

**Issue by stearno** [nextcloud/desktop#346]
![nextcloud error](https://user-images.githubusercontent.com/24409475/40572488-dc155d34-60be-11e8-976f-62311048dfc3.png)
Some files are not uploading.  They are just powerpoints (some of them).  What do I need to do to fix this issue as I cannot have big chunks of files not uploading.  Thanks.

**Comment by plyaskin** [comment]
I have the same problem and don't know how it to solve :( Please let us know or to solve in the app.

**Comment by camilasan** [comment]
Hi @stearno @plyaskin, thanks for the report.
This looks like a server issue, probably a configuration... 
What is the server version? Could you provide the server logs and client logs?

**Comment by camilasan** [comment]
For more details: https://help.nextcloud.com/t/dont-sync-some-files-via-desktop-client/30363

**Comment by plyaskin** [comment]
Hi @camilasan, 
I have the last version of NextCloud (13.0.4 now). What should be the configuration of server?
At the moment I have the following issues:
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the Tips & Tricks section and the documentation for more information.

Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)
The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips.
No memory cache has been configured. To enhance performance, please configure a memcache, if available. Further information can be found in the documentation.
The PHP OPcache is not properly configured. For better performance it is recommended to use the following settings in the php.ini:
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

About last PHP OPcache my provider said to me that I need VPS, but I'm really needed?

**Comment by camilasan** [comment]
@MorrisJobke Could you quickly look at the issue description? I don't think it is a problem in the client.
Thanks.

**Comment by plyaskin** [comment]
Hi @MorrisJobke, not necessary for big files.
For example I have the file DTP.zip (3.4 MB) and try to sync via desktop client and I have the error: “Server replied: request entity too large” (upload_max_filesize 14.6G, post_max_size 14.6G), but if I rename an extension of file to another (DTP.1), I can upload file to my folder on the server.

**Comment by MorrisJobke** [comment]
Maybe @rullzer or @icewind1991 knew more.

**Comment by stearno** [comment]
Dear support,
Most of my files upload/sync just fine.  It is only a few files that 
show they are not syncing.

I have succesfully uploaded just find by my desktop, mobile, and using 
the online web UI.

These are the ones that have sync errors on the desktop:
6/19/2018 8:01:47 AM,Biz-PEAK United/Clients/Al Baraka/Skill assessment 
- Completion status/Competence Assessor.pdf,                     
Nextcloud,Continue blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3401125306/00000000 
- server replied: Not Acceptable
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/CSL/Old Versions/Investor 
Pitch Deck for presentation v1.pptx,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/4079412397/00000000 
- server replied: Not Acceptable
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/CSL/CSL Investment Teaser, 
June 2017.pptx,                     Nextcloud,The item is not synced 
because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1047421500/00000000 
- server replied: Not Acceptable
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/CSL/CSL Business Plan 
Presentation, June 2017.pptx,                     Nextcloud,The item is 
not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2269049638/00000000 
- server replied: Not Acceptable
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/Al Shasky Group/~$Proposal 
- draft 1.xlsx,                     Nextcloud,File is listed on the 
ignore list.
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/Al 
Baraka/Training/~$Competence Assurance Program Training.pptx,            
          Nextcloud,File is listed on the ignore list.
6/19/2018 8:01:13 AM,Biz-PEAK United/Clients/Al Baraka/KSA's/Total 
Competencies signed by two RMs.pdf,                     
Nextcloud,Continue blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2772809171/00000000 
- server replied: Not Acceptable
6/19/2018 8:00:38 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol II/Advanced PPC Tips 
with Alex Goad.mp3,                     Nextcloud,Continue blacklisting: 
Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/4163674012/00000000 
- server replied: Not Acceptable
6/19/2018 8:00:29 AM,    Biz-PEAK United/Clients/Al Baraka/KSA's/~$GDP - 
Driller.xlsx,                     Nextcloud,File is listed on the ignore 
list.
6/19/2018 8:00:29 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol II/Insider 
Super-Affiliate PPC Strategies Stephen Clayton.mp3,                     
Nextcloud,Continue blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/170451874/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,         Biz-PEAK United/Clients/Al Baraka/CAA 
Docs/~WRL0005.tmp,                     Nextcloud,File is listed on the 
ignore list.
6/19/2018 7:59:57 AM,      Biz-PEAK United/Clients/Al Baraka/CAA 
Docs/~$A Program.doc,                     Nextcloud,File is listed on 
the ignore list.
6/19/2018 7:59:57 AM,  Biz-PEAK United/Clients/Al Baraka/CAA Docs/~$A 
Program v1.docx,                     Nextcloud,File is listed on the 
ignore list.
6/19/2018 7:59:57 AM,             Biz-Achieve Success/Website 
Images/Post-it note.psd,                     Nextcloud,The item is not 
synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2303022879/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,                Biz-Achieve 
Success/Facebook/FacebookCover-3.psd,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2689698416/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,                Biz-Achieve 
Success/Facebook/FacebookCover-2.psd,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/709511732/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/5-Squeeze page setup.mp4,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/949007550/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/4-Newsletter setup.mp4,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1800659328/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/3-eBook setup.mp4,                     Nextcloud,The item is 
not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1661999884/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/2-Affiliate redirects setup.mp4,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3544237460/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/1-Uploading AffiloTheme for self hosting.mp4,                   
   Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2517568211/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Videos 
Training/0-AffiloJetpack 2.0 _ Affilorama.mp4,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3752283984/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Millionaire Mindset Upgrade/Millionaire Mindset 
Upgrade.mp4,                     Nextcloud,The item is not synced 
because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1114083929/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Millionaire Mindset Upgrade/Millionaire Mindset 
Upgrade Audio.mp3,                     Nextcloud,The item is not synced 
because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2184586618/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Live Traffic Strategies 
Workshop/trafficstrategies3.mp4,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3130871838/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Live Traffic Strategies 
Workshop/trafficstrategies2.mp4,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3074835995/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Live Traffic Strategies 
Workshop/trafficstrategies1.mp4,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2950666870/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Resources/Capturing leads through Mobile Marketing.mov,    
                  Nextcloud,The item is not synced because of previous 
errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1383338701/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:57 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol II/How to Ambush 
Google Adwords with Andrew X.mp3,                     Nextcloud,Continue 
blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/734898196/00000000 
- server replied: Not Acceptable
6/19/2018 7:59:06 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol I/Direct linking PPC 
Secrets with .mp3,                     Nextcloud,Continue blacklisting: 
Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2428158995/00000000 
- server replied: Not Acceptable
6/19/2018 7:58:49 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol I/Renegade PPC 
Tactics with Ryan Moran.mp3,                     Nextcloud,Continue 
blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1614602078/00000000 
- server replied: Not Acceptable
6/19/2018 7:58:45 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/PPC Millionaire Confessions Vol I/Advanced PPC 
Strategies with Gauher Chaudhry.mp3,                     
Nextcloud,Continue blacklisting: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/324825196/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Mark Ling & Daniel Turner - Outsourcing 
101/outsourcing.mp4,                     Nextcloud,The item is not 
synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3491133396/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/ProductCreationSecrets.zip,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3900953855/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantWebsiteSecurity.zip,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1601210255/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantSqueezePageMastery.zip,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3741968008/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantSoftwareProducts.zip,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/708999173/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantBlogTraffic.zip,                     Nextcloud,The item is 
not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3189537954/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantAudioMastery.zip,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/4219315326/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/InstantAdsenseCash.zip,                     Nextcloud,The item is 
not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/4055471777/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/HowToGetALotMoreGoogleTrafficForFree.zip,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/3123624199/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/HowToCreateaMinisiteIn30MinutesOrLess.zip,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/981491496/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/HowToCreateProfitPullingToolbarsForFree.zip,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/644190860/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/HowToCreateFullyFeaturedAndProfessionalPDFsForFree.zip,           
           Nextcloud,The item is not synced because of previous errors: 
Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/63906583/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,Biz-Achieve Success/Affilojetpack/Mark Ling - 
AffiloJetPack/Bonus/Internet Marketing Mastermind/Step By Step 
Videos/HowToAddAutomaticallyUpdatingContentToYourWebsiteForFREE.zip,     
                 Nextcloud,The item is not synced because of previous 
errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/699591627/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,AmazonDriveDownload/Magic Briefcase/Wondershare 
PDFelement (Editor) 5.7.3.7 + Serial {B4tman}/Setup.exe,                 
     Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1159575264/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,AmazonDriveDownload/Magic Briefcase/Trading/T4 
Bktsts/MA as PT backtests - VariedSMA, varriedSL, no minPT, 
2013-2015/Portfolio.sqa,                     Nextcloud,The item is not 
synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1829769998/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,AmazonDriveDownload/Magic Briefcase/Trading/T4 
Bktsts/MA as PT backtests - 30sma, no sl, no minPT, 2013-2015/Portfolio 
listOfTrades_of all MAasPT nosl nominpt.csv,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1888831789/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,        AmazonDriveDownload/Magic 
Briefcase/CBTi/Program/cbt.mp3,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2914047794/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,   AmazonDriveDownload/Magic 
Briefcase/CBTi/Program/03Track3.mp3,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1815839129/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,AmazonDriveDownload/Magic Briefcase/CBTi/Conquering 
Insomnia program webinar on Vimeo.wmv,                     Nextcloud,The 
item is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/1835635408/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,        AmazonDriveDownload/Magic 
Briefcase/CBTi/CBT Webinar.wmv,                     Nextcloud,The item 
is not synced because of previous errors: Error transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/2357463712/00000000 
- server replied: Not Acceptable
6/19/2018 7:57:15 AM,   AmazonDriveDownload/Magic 
Briefcase/Badegoib/._Untitled-22.ai,                     Nextcloud,File 
is listed on the ignore list.
6/19/2018 7:57:15 AM,        AmazonDriveDownload/Magic 
Briefcase/Badegoib/._.DS_Store,                     Nextcloud,File is 
listed on the ignore list.
6/19/2018 7:57:15 AM,AmazonDriveDownload/Magic 
Briefcase/Back/VID_20150516_180717.mp4,                     
Nextcloud,The item is not synced because of previous errors: Error 
transferring 
http://www.findatradingcoach.com/nextcloud/remote.php/dav/uploads/admin/685914826/00000000 
- server replied: Not Acceptable

------ Original Message ------

**Comment by plyaskin** [comment]
Hi @rullzer and @icewind1991, can you help us?

**Comment by plyaskin** [comment]
Found a solution
https://github.com/nextcloud/docker/issues/32

**Comment by MorrisJobke** [comment]
> Found a solution
> nextcloud/docker#32

Thanks for the hint. Then it was a setup issue and I will close this one.

**Comment by plyaskin** [comment]
@MorrisJobke this is not my subject just a similar issue.
