### ISSUE TITLE
Nextcloud desktop crashes after upgrade to Ubuntu 21.04

### ISSUE THREAD

**Issue by kklemon** [nextcloud/desktop#3462]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud desktop client should start.

### Actual behaviour
Nextcloud desktop client crashes with the following error:

```
2021-06-18 20:39:52:829 [ fatal default ]:      ENFORCE: "allow_failure" in file ./src/common/ownsql.cpp, line 265 with message: SQLITE Prepare error
fish: “nextcloud” terminated by signal SIGABRT (Abort)
```

### Steps to reproduce
1. Install Ubuntu 21.04
2. Install `nextcloud-desktop` from the `ppa:nextcloud-devs/client` repository
3. Start Nextcloud using the `nextcloud` command

### Client configuration
Client version: 3.1.1-1ubuntu1.1

Operating system: Ubuntu 21.04, Linux 5.11.0-18-generic #19-Ubuntu SMP Fri May 7 14:22:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

OS language: en_US.UTF-8

Qt version used by client package: Qt 5.15.2, built against Qt 5.15.2

Client package (From Nextcloud or distro) (Linux only): `nextcloud-desktop` from `ppa:nextcloud-devs/client`, version 3.1.1-1ubuntu1.1

Installation path of client: `/usr/bin/nextcloud`

### Logs

1. Client logfile: [https://gist.github.com/kklemon/f098f8c30e4476c93b22d1a4d3b40ab4](https://gist.github.com/kklemon/f098f8c30e4476c93b22d1a4d3b40ab4)

**Comment by FlexW** [comment]
Did you downgrade the client? That looks like the sync journal is not compatible with the client. Please stop the client and try to delete the `._sync` files in the folder you want to sync.

**Comment by kklemon** [comment]
> Did you downgrade the client? 
No, I would suspect to have made an implicit upgrade together with my distro.

> Please stop the client and try to delete the ._sync files in the folder you want to sync.
That did the trick. Thanks for the help!
