### ISSUE TITLE
Windows explorer rename refresh needed

### ISSUE THREAD

**Issue by Pillaknuff** [nextcloud/desktop#347]
Hi together,

i just noticed certain problems my windows file explorer has in connection with renames/deletions in connection with the nextcloud client. Renamina a file will result in the temporary existence of two files, one with the old name, one with the new, both shown in the windows explorer. 
Trying to open the old one will result in a "file not found" error message, refreshing the windows explorer manually will make the issue dissappear, thus i think the error is due to a missing refresh behavior of the windows explorer in connection with the nextcloud client plugin.
The problem appears both under windows 10 and windows 7. No big issue, just a little irritating inconvenience. I first noticed the problems about 2 months ago.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
