### ISSUE TITLE
Cannot Update WINDOWS CLIENT

### ISSUE THREAD

**Issue by Jojo-Burger** [nextcloud/desktop#3474]
Hello,
I can’t update the NextCloud client, I have this error on them “Unable to check for updates”
NextCloud version 21.0.2
PHP Version: 7.4.20
MYSQL Version: 10.3.27

**Comment by FlexW** [comment]
On which platform is the client running? Which is the current version of your client. Can you upload the logs of your client?

**Comment by Jojo-Burger** [comment]
> On which platform is the client running? Which is the current version of your client. Can you upload the logs of your client?

I am using the Windows client, the current version is 3.2.2 and how do I download the client logs?

**Comment by Meth0d007** [comment]
`2021-06-23 20:51:20:140 [ info nextcloud.sync.accessmanager ]:	2 "" "https://updates.nextcloud.org/client/?version=3.2.2.20210527&platform=win32&osRelease=windows&osVersion=10&kernelVersion=10.0.19043&oem=Nextcloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=stable-Win64&updatesegment=67&msi=true" has X-Request-ID "4de8e965-25f1-45eb-a1d4-0bd55951932b"

2021-06-23 20:51:20:140 [ debug nextcloud.sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://updates.nextcloud.org/client/?version=3.2.2.20210527&platform=win32&osRelease=windows&osVersion=10&kernelVersion=10.0.19043&oem=Nextcloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=stable-Win64&updatesegment=67&msi=true") requests: ()

2021-06-23 20:51:20:284 [ warning nextcloud.gui.updater ]:	Failed to reach version check url:  "Error transferring https://updates.nextcloud.org/client/?version=3.2.2.20210527&platform=win32&osRelease=windows&osVersion=10&kernelVersion=10.0.19043&oem=Nextcloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=stable-Win64&updatesegment=67&msi=true - server replied: Internal Server Error"
`

![image](https://user-images.githubusercontent.com/17513721/123152717-27d52e80-d465-11eb-8785-4fd07e42510e.png)

**Comment by FlexW** [comment]
What is the current version of the client? You can create the logs when you go to Settings -> General and then press the button "Create debug archive...". As a quick workaround, you can just uninstall your current client and download the newest version from https://nextcloud.com/install/#install-clients . The uninstallation will not remove the configured accounts and sync directories.

**Comment by Meth0d007** [comment]
3.2.2. Just reporting the bug.
I don't like sharing NCs debug logs as they are not anonymized. Everyone can see from that Log what is going on and reproduce the problem by opening the link in any browser.

**Comment by mgallien** [comment]
> 3.2.2. Just reporting the bug.
> I don't like sharing NCs debug logs as they are not anonymized. Everyone can see from that Log what is going on and reproduce the problem by opening the link in any browser.

Thanks for your report, I am reproducing the problem.
I will fix the update server and close the issue once a fixed version is deployed.

**Comment by mgallien** [comment]
Please test but the server is now working for me
