### ISSUE TITLE
Windows desktop client stuck on reconciling changes

### ISSUE THREAD

**Issue by pnwwebworks** [nextcloud/desktop#3487]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud client should complete the sync when there are no notes in the notes folder on server.

### Actual behaviour
Desktop client gets stuck at reconciling changes when no notes are in the folder. Sync completes properly when notes are available in the folder.

### Steps to reproduce
1. Create new note on server, or through android app.
2. Wait for sync (or force sync) on desktop app
3. Note appears fine on windows system
4. Delete note off server
5. Force sync or wait for sync
6. Desktop client gets stuck if there are no notes left when the last note is deleted

### Client configuration
Client version: Windows Desktop Client 3.2.2

Android Notes App Version: 3.2.5

Operating system: Windows 10 Pro 21H1; Server on Apache & PHP 7.4; Android 11

OS language: English

Installation path of client: Default x64

### Server configuration

Server Version: 21.0.2
Notes App Version: 4.0.4

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Available upon request securely

2. Web server error log: None Given

3. Server logfile: nextcloud log (data/nextcloud.log): Available upon request securely

**Comment by FlexW** [comment]
This could be solved by https://github.com/nextcloud/desktop/pull/3192 . But the fix was not backported to the stable 3.2 branch.

**Comment by thejungletiger** [comment]
Is there a current beta release that you would like me to test for you?

**Comment by FlexW** [comment]
@thejungletiger You can try a daily https://download.nextcloud.com/desktop/daily/

**Comment by thejungletiger** [comment]
The daily seems to have the correct resolution. All works fine when deleting all notes, syncing empty folders, and re-adding files.

When is the current version of daily scheduled to be dropped to the stable channel?

**Comment by FlexW** [comment]
The first pre-release was released today. You can expect the final release within the next few weeks.

**Comment by patricksebastien** [comment]
My users are experiencing this bug too. Fixed in:
https://github.com/nextcloud/desktop/releases/tag/v3.3.0-rc1

Hopefully an update will be available soon...

**Comment by pnwwebworks** [comment]
All appears to be fine in 3.3.1.
