### ISSUE TITLE
Rename "owncloudsync.log" files in sync directories

### ISSUE THREAD

**Issue by LostInCompilation** [nextcloud/desktop#3491]
The Client (Windows 10, no virtual file system) is creating multiple hidden files in the sync directory, for example:
-".owncloudsync.log"
-".sync_c6217acc34d7.db"
-".sync_c6217acc34d7.db-shm"
-....

It looks like ".owncloudsync.log" is still an old leftover from the OwnCloud fork.
How about renaming them to ".nextcloudsync.log"?

**Comment by Jiaocz** [comment]
If you install serverside nextcloud, the default database prefix is "nc_". LOL.

**Comment by LostInCompilation** [comment]
> If you install serverside nextcloud, the default database prefix is "nc_". LOL.
What do you mean? I'm not talking about the server instance.

**Comment by Jiaocz** [comment]
> > If you install serverside nextcloud, the default database prefix is "nc_". LOL.
> 
> What do you mean? I'm not talking about the server instance.

Yes I know. I just mean that there are lots of things still named oc or own cloud like https://github.com/nextcloud/desktop/search?q=owncloud and https://github.com/nextcloud/desktop/search?q=oc

**Comment by LostInCompilation** [comment]
Maybe someday this will get cleaned up :D
As long as it is pure backend, it's not a big deal. But having path names in the server code with "oc" in the name gave me some headaches once. Everything crashed because I assumed the path would have "nc" instead of "oc" as prefix...

**Comment by mgallien** [comment]
this file is needed by the internal mechanism that is monitoring files change and cannot be removed
I am not sure we really need to rename it and the priority for this would be very low in any case.
I prefer to close now rather than pretending we would do it.

**Comment by LostInCompilation** [comment]
I can understand that this is low priority, but not doing those little things will lead to more and more fragmentation and hard to find bugs. It's not the first time that I crashed a Nextcloud-Server because of this exact issue. 1000 files named nc_ and then there is one named oc_...
And I think your answer somehow confirmed this. If renaming this file is not an easy thing in the codebase, the problem with file fragmentation is already huge.

**Comment by joshtrichards** [comment]
Cleaned up some in #5271
