### ISSUE TITLE
File deleted when a file is displaced

### ISSUE THREAD

**Issue by jroussay** [nextcloud/desktop#3493]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
A file is moved (drag and drop, cut/paste) from a folder A to a Folder B

### Actual behaviour
File is deleted on client and server, and it isn't in the trash

### Steps to reproduce
1. Set up a virtual filesystem
2. Cut and paste a file that is not already sync

### Client configuration
Client version: 3.2

Operating system: Windows 10

OS language: FR

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
https://gist.github.com/jroussay/a2110e54dd74176e230c089fbaf70639

2. Web server error log:
Nothing relevant

3. Server logfile: nextcloud log (data/nextcloud.log):
Nothing relevant

Thanks

**Comment by andyxheli** [comment]
Same issue while having virtual files enabled

**Comment by mgallien** [comment]
This will be fixed by the next stable version 3.3.2.
Once it is released at the end of the month, can you please test again and if the bug is fixed close that issue ?

**Comment by andyxheli** [comment]
@mgallien yes will do. Thank you for the update

**Comment by jroussay** [comment]
It's working now.
Thanks
