### ISSUE TITLE
Virtual Files stopped working Client 3.2.3

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3495]
As soon as i upgrade to 3.2.3 from 3.2.2 the virtual files stopped downloading get a windows error can download file then the files deletes automatically very very unstable

**Comment by claell** [comment]
Fortunately, this does not seem to happen for me.

I assume that a log file will be helpful

Ping @FlexW @allexzander as this might be urgent

**Comment by andyxheli** [comment]
I do have server side encryption on maybe with that feature there's issues? I will also try it in a different computer and see the results keep you posted

**Comment by allexzander** [comment]
> I do have server side encryption on maybe with that feature there's issues? I will also try it in a different computer and see the results keep you posted

VFS does not work with E2EE at the moment. We are aiming to add support in 3.3.0 or 3.4.0. Work in progress. Which error you are getting? Is it a popup? You can download E2EE files/folders now if you right-click and choose "Always available locally", as a workaround.

**Comment by andyxheli** [comment]
Thank you for letting me know @allexzander Just wanted to let you know that on version 3.2.2 I didn't have an issue.


Now if I clicked on a Individual￼ file it would show the windows transfer window and download and then say error downloading and when I mark it as always available offline it would download and get stuck right by the end and program would stop responding.

**Comment by allexzander** [comment]
@andyxheli You may want to try adding a new local sync folder. Similar to how you did that when connecting an account to the sync client but now, without adding an account, just a folder via the button "Add Folder Sync Connection". This should solve your problem if you do not try to double-click non-hydrated files in encrypted folders until they are hydrated with "Always available locally". Clumsy workaround, but, should help until we have implemented full VFS + E2EE support.

**Comment by andyxheli** [comment]
Heres the error i get 

![image](https://user-images.githubusercontent.com/59488153/123857401-da831200-d8e7-11eb-98c2-b5d6bfd7ee59.png)

**Comment by LucaOverflow** [comment]
It stopped workig for me as well. As soon as the Client wants to sync it just crashes without any error message. It stays visible with the sync icon in the task bar until i hover my mouse over it. Then it disappears. Downgrading to 3.2.2 didnt do the trick for me.

The log File doesnt seem to say something useful. At the end at least. It's very big so i didnt check the whole file.
Is there a separate error log file?

I dont use the server side encryption module.

**Comment by alex6480** [comment]
I have the same issue as @LucaOverflow 

It happened back in 3.2.2 as well where it would occasionally crash when syncing. After I updated to 3.2.3 Nextcloud the crashes became so frequent that it cannot sync at all. I had to turn off virtual files for it to become usable again. I can't tell if the issue is due to the update, or if it's just that after updating I was syncing a lot of files, which made it more likely that a crash would occur before completion.

The log had no useful information, but the windows event viewer had logged af CldAPI crash.
Perhaps your problem is the same as this issue: #3349

**Comment by claell** [comment]
@LucaOverflow @alex6480 I doubt that you experience the same problem as @andyxheli at least your symptoms and setup is rather different. I am not even confident that you both have the same issue. So probably your problem can be better treated in an issue dedicated to your specific problems.

**Comment by Githopp192** [comment]
just some days ago, i did the upgrade from Nextcloud Desktop-Client 3.2.2 to 3.2.3.
Running Windows 10 with the newest Build (21H1); NC Version: 21.0.1

Getting x80070185 - Error when trying to download/open some (but not all !) documents -->

![ScreenShot026](https://user-images.githubusercontent.com/32612067/124348112-66e34c80-dbe8-11eb-894b-edb66665ca90.jpg).

Choosing "make always available locally" make the PDF availabe again on the client.

Tested more files on the Windows Client with the Cloud symbol -->

![ScreenShot027](https://user-images.githubusercontent.com/32612067/124348589-030e5300-dbeb-11eb-9cf3-293b688dfabe.jpg)

The strange thing is, that some jpg files with the cloud symbol can be successfully downloaded/opened, others on the same folder and the same permissions not - like this one (IMG_1623088...jpg).

![ScreenShot028](https://user-images.githubusercontent.com/32612067/124348651-69937100-dbeb-11eb-972f-8ad81372734e.jpg)

Restarting Nextcloud Desktop-Client did not solve the issue.

**Comment by andyxheli** [comment]
@Githopp192 just wanted go see do you also have encryption enabled ?

**Comment by stardust342** [comment]
I have the same issue, it only affects random files, others work fine. But it's about 50/50 so it's unusable for me.
I believe E2E encryption is disabled (I don't recall enabling it), however it is secured behind a reverse proxy with SSL.

**Comment by Githopp192** [comment]
> @Githopp192 just wanted go see do you also have encryption enabled ? 

Oh, sorry forgot to mention - no, no encryption enabled at all

**Comment by andyxheli** [comment]
@claell i don't think this is relaxed too encryption.

**Comment by lorenzo-w** [comment]
Exact same issue here. Random files, but consistently always the same files, return an error when trying to open them and are thus unusable. 

Here is an excerpt of my logs from when I tried to open one of these files:

`2021-07-04 15:16:35:364 [ debug nextcloud.sync.vfs.cfapi.wrapper ]	[ `anonymous-namespace'::cfApiFetchDataCallback ]:	Fetch data callback called. File size: 176172
2021-07-04 15:16:35:365 [ info nextcloud.sync.vfs.cfapi ]:	Received request to hydrate "D:\\NC\\NONE_OF_YOUR_BUSINESS.pdf" "1d770d39a0e0101"
2021-07-04 15:16:35:365 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -143314219672656488
2021-07-04 15:16:35:365 [ debug nextcloud.sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum, e2eMangledName, isE2eEncrypted  FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
2021-07-04 15:16:35:365 [ info nextcloud.sync.vfs.cfapi ]:	Couldn't hydrate, the file is not virtual
2021-07-04 15:16:35:366 [ info nextcloud.sync.vfs.cfapi.wrapper ]:	VFS replied for hydration of "D:\\NC\\NONE_OF_YOUR_BUSINESS.pdf" "1d770d39a0e0101" status was: false`

**Sync Client Version** 3.2.3
**OS:** Windows 10 Home, Build 19041.1081
**Nextcloud Version: ** 21.0.0

I also have E2E in use but none of the affected file are encrypted.

I hope with these infos you are able to track the bug down.

**Comment by Githopp192** [comment]
> @claell i don't think this is related too encryption.

yes, @claell ... i think you're right ... there are many similar issues, where encryption is NOT enabled (like in my case).

**Comment by vithusel** [comment]
I can confirm the above also happens to me. 

I've got 3 different instances on different physical servers. Only one of them are giving me this issue. I though it may be due to the push notify feature that was implements but removing that made no change.

**Comment by Githopp192** [comment]
tried to completely re-install Nextcloud Desktop-Client 3.2.3 (de-install/restart windows/install/restart windows).

Did not help - same situation.

**Comment by allexzander** [comment]
@Githopp192 Does it work if you just right-click a file in the Explorer and choose "Make always available locally"? Will the file get downloaded successfully?

**Comment by andyxheli** [comment]
@allexzander for me it dose not work.

**Comment by vithusel** [comment]
> @Githopp192 Does it work if you just right-click a file in the Explorer and choose "Make always available locally"? Will the file get downloaded successfully?

This works for me. Would you like me to send any logs?

**Comment by Githopp192** [comment]
@vithusel - yes .. as i wrote before "Choosing "make always available locally" make the PDF availabe again on the client." - this is working.

Which logs would you like to see ?

**Comment by claell** [comment]
@andyxheli Seems to really be unrelated to encryption. Still, I think @LucaOverflow and @alex6480 have a different problem, they describe crashes. This issue seems to be more about not working file retrieval where the client does not crash.

**Comment by allexzander** [comment]
This should be fixed with https://github.com/nextcloud/desktop/pull/3501 and will be available in 3.2.4

**Comment by andyxheli** [comment]
@allexzander  Thank you sir.

**Comment by Githopp192** [comment]
> This should be fixed with #3501 and will be available in 3.2.4

Great !

**Comment by andyxheli** [comment]
Should i close this ?

**Comment by lorenzo-w** [comment]
> 
> 
> Should i close this ?

I'd say let's wait until it is in the release and confirmed working there...

**Comment by andyxheli** [comment]
Copy that. Thanks

**Comment by allexzander** [comment]
Haven't released it yet, but, will do it soon. You can check if the issue is still happening with this build https://cloud.nextcloud.com/s/MHMYFcCxLjgAJa9

**Comment by vithusel** [comment]
> Haven't released it yet, but, will do it soon. You can check if the issue is still happening with this build https://cloud.nextcloud.com/s/MHMYFcCxLjgAJa9

Im still having the same issue with this new build.

**Comment by vithusel** [comment]
[20210707_1019_owncloud.log.1.gz](https://github.com/nextcloud/desktop/files/6775986/20210707_1019_owncloud.log.1.gz)
[20210707_1019_owncloud.log.2.gz](https://github.com/nextcloud/desktop/files/6775987/20210707_1019_owncloud.log.2.gz)
[20210707_1019_owncloud.log.0.gz](https://github.com/nextcloud/desktop/files/6775988/20210707_1019_owncloud.log.0.gz)

Please find the logs attached

**Comment by vithusel** [comment]
One last thing to add. 

As a last ditch effort i downgraded to 3.2.1 as a test and the issue still happens. Perhaps this is somehow linked to a recent update on server side?

**Comment by allexzander** [comment]
@vithusel This may be due to 3.2.3 has corrupted local files (not server ones), so, you have to add a new local sync folder, or, sync all broken files with "Make always available locally", and then, try downloading with a double-click.

**Comment by brtptrs** [comment]
The upcoming 3.2.4 version solves the problem for me. Thank you!

**Comment by feutl** [comment]
Ok, I jump onto this too now after following the issue. I am not sure if I have the same issue or the reason is the same, but my client stopped working with upgrading to 3.2.3 and downgrading does not fix it again.
What mainly happens is that the client connects to the server, and starts processing the changes. After a certain amount of time the applications hangs and shows (not responding in the "settings" window - not the main window popping up next to the taskbar icon)
If this happens, the hanging, the client disconnects from my instance and reconnects again, starting all over. This happens over and over again and actually the changes on the server or the client do not get pushed to the other side.
I use the notify app, and I do have lots of files on the server.

Anyhow, if I opene a file while the taskbar icon shows the green check icon, the file can be downloaded via VFS and the explorer, but the files added to the server or the client to not get synced.

What is interesting, I have another PC running windows 10 and this one syncs perfectly with the same instance and files.

First, could my problem be related to this one? If not what could it be and how could it be fixed, and what should I provide or look into?

Thanks

**Comment by vithusel** [comment]
> @vithusel This may be due to 3.2.3 has corrupted local files (not server ones), so, you have to add a new local sync folder, or, sync all broken files with "Make always available locally", and then, try downloading with a double-click.

Awesome! 

I have tested it after deleting and recreating the folder sync and all working as expected. Is there anyway of forcing this remotely? I've got a fair few users i will need to do this for.

**Comment by grandgeorg** [comment]
We have the same issue. 
Desktop Client Verion 3.2.3
Windows 10 Version: 21H1

Even the option "make always available locally" for a file only works after forcing synchronisation for the whole share in the desktop client settings.

For us this is a major issue as our complete workflow is havilly disrupted.

Here an error message (in german):

![001](https://user-images.githubusercontent.com/811894/124918864-d183f600-dff5-11eb-890d-121e9781e9fd.png)

**Comment by feutl** [comment]
> 
> 
> > @vithusel This may be due to 3.2.3 has corrupted local files (not server ones), so, you have to add a new local sync folder, or, sync all broken files with "Make always available locally", and then, try downloading with a double-click.
> 
> Awesome!
> 
> I have tested it after deleting and recreating the folder sync and all working as expected. Is there anyway of forcing this remotely? I've got a fair few users i will need to do this for.

I did the same within the NC app, without losing any data, it is working now again.
Took some time to rescan the files and sync what was necessary and missed.

**Comment by congoelmex** [comment]
downgrading to 3.2.2 and deleting the .sync.db file in the local nextcloud directory seems to have helped at one installation I maintain. On my personal computer I had the same problem and updated the Client to 3.2.4 - still the same problem. After deleting the sync.db it worked again. Of course the client had to resync everything...

**Comment by andyxheli** [comment]
Client 3.2.4 seems to fix this issue.

**Comment by congoelmex** [comment]
No it doesnt.

At least not by just installing.
If you just install 3.2.4 over 3.2.3 the Problem is still there.
You have to proactively delete the .sync.db on the client (of course with following resync) to make it work again.

**Comment by andyxheli** [comment]
@congoelmex I updated to 3.2.4 then i removed the sync folder added a new sync folder and everything looks good. Where's the issue?

**Comment by congoelmex** [comment]
Exactly that's the way (though you don't have to delete the whole sync folder - the .sync<numbers>.db file seems to be enough).
I just stumbled over the short "Client 3.2.4 seems to fix this issue." If you just perform the Update of the client, the problem won't go away...

so. no offense - rather an addendum. ;)

**Comment by andyxheli** [comment]
Ahhhh gotcha. Okay we reopen then.

**Comment by allexzander** [comment]
FYI, at the moment, we can only offer a workaround by manually deleting .sync.db. The fix is not something that's happening soon, so, anyone who is blocked by this regression will have to apply this workaround for now.

**Comment by congoelmex** [comment]
I can live with this solution, but your statement is...interesting... ;) I can imagine that this is kind of a deal breaker for a lot of people.

**Comment by isdnfan** [comment]
manually deleting the file might be a problem for lot of inexperienced users. would you mind to add menu option "perform full sync" running this steps automatically (delete/clean .sync.db and start fresh sync cycle)?

**Comment by allexzander** [comment]
@isdnfan Thank you for the suggestion. This could indeed be useful.

**Comment by kenvix** [comment]
Same problem. This seems to happen very often on unstable networks

**Comment by andyxheli** [comment]
No longer an issue running 3.3.1

**Comment by hjenkel** [comment]
Running 3.4.1 and still an issue. @andyxheli

**Comment by Josefpi92** [comment]
I am an unexperienced user and have this issue still with Nextcloud 3.14.2. I'm afraid and don't know how to manually delete .sync.db. Is this still the solution or is there, meanwhile, another workaround/fix
