### ISSUE TITLE
*.lnk files is not syncing

### ISSUE THREAD

**Issue by vgdh** [nextcloud/desktop#3499]
### Expected behavior
My blabla**.lnk** files is syncing

### Actual behaviour
It is not

### Steps to reproduce
1. Create link
2. Put it in sync folder
3. It will not go to nextcloud server

### Client configuration
Client version: 3.2.3
Operating system: Win 10
OS language: Rus
Installation path of client: default

**Comment by Discostu36** [comment]
This is intended behaviour, see #3057

**Comment by wlnx** [comment]
> This is intended behaviour, see #3057

This "intended behavior" is a Qt issue, lnk-files are not symlinks, you can try to

cd shortcut-to-folder.lnk

and see that Windows doesn't treat it as a symlink. And I am also missing lnk-files. :'(

**Comment by Taomyn** [comment]
Not sync'ing .lnk files is a huge mistake, users with shortcuts on their desktops would completely lose them if they were to recover their local profile for any reason and not everyone can remember exactly what they were to simply "put them back manually".

**Comment by zlydk** [comment]
See also https://github.com/nextcloud/desktop/issues/3244 for further discussion and requests on syncing .lnk files again.
