### ISSUE TITLE
Linux appimage -> wrong version?

### ISSUE THREAD

**Issue by criwe** [nextcloud/desktop#3504]
Hi!

I´ve downloaded the linux appimage (3.2.3) right now.
When entering the settings and the "general" tab, it says its Version 3.0.1?!

Can anyone confirm?

Thanks!
Best,
Christoph

**Comment by camilasan** [comment]
Is it from https://download.nextcloud.com/? I just downloaded https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-3.2.3-x86_64.AppImage and it says 3.2.3:
![3 2 3](https://user-images.githubusercontent.com/241266/124714186-be8ff980-df01-11eb-94d4-3e190c91fd60.png)
