### ISSUE TITLE
VFS: allow downloading directories once.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3506]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
The result of what happens when you check 'Always keep on this device', let it download, and uncheck it.  
This allows setting up (new) devices in a high-connectivity environment (1Gbps vs 40Mbps), before passing it to the user.

For users, this also allows downloading a project folder beforehand, without having to wait for it to load dynamically when needed.

For now, in addition, it's also a bad workaround for #3407

**Comment by mgallien** [comment]
> ### How to use GitHub
> 
>     * Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
> 
>     * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> 
>     * Subscribe to receive notifications on status change and new comments.
> 
> 
> ### Feature description
> 
> The result of what happens when you check 'Always keep on this device', let it download, and uncheck it.
> This allows setting up (new) devices in a high-connectivity environment (1Gbps vs 40Mbps), before passing it to the user.
> 
> For users, this also allows downloading a project folder beforehand, without having to wait for it to load dynamically when needed.
> 
> For now, in addition, it's also a bad workaround for #3407

I am not sure I understand what you want.
In any case, if you uncheck `'Always keep on this device'` the files can be removed at any time by Windows.

Could try to explain again what you would like ?

**Comment by jtagcat** [comment]
Setting up a new device, or starting a new project, building an **initial** cache.

Users have a 256G disk, and they tend to mark 'Always keep on device' for 1 TiB of data.

If you know you (or the user) is going to need files. Problem is, there is not enough local storage to keep everything 'Always keep on this device'.

***

Simplified example. You _plan_ to view 300 images from a folder. You select 'Download once' (equivalent to selecting 'Always keep on this device', and then unchecking it, the files stay on the device, but aren't mandated on the device).  
This way, there is no wasted time in waiting for them to download on the fly, yet there is no buildup over time either.

Users are not concerned, nor should they be, to go through their files and unchecking the 'Always keep on this device'.

The point is to empower users in building a cache (avoiding frustration in waiting for remote storage), yet at the same time giving Windows free hands in cleaning up files that haven't been accessed in 2 years.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
