### ISSUE TITLE
Win: Contingency service OR start/ping NCD without opening any windows via Task Scheduer

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/desktop#3507]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Nextcloud Desktop crashes frequently (especially with VFS). Not really here to whine about it.

Especially VFS users. When Nextcloud Desktop crashes, they are left in a (often) panicking state of their files being gone, corrupted, et al.

I've made a task scheduler task to start Nextcloud every minute. This likes to sometimes open the nextcloud's window unneeded. Is there a 'start Nextcloud in the background opening nothing if already open' CLI flag?

Alternatively, a separate service, that monitored Nextcloud, and restarted it, would be a better user experience.

**Comment by claell** [comment]
Is there a bug report for the crashes that can be linked here?

**Comment by jtagcat** [comment]
Why would there need to be a link? /g

It's a feature request. All bugs will never be crushed, having this on devices you don't use, it'd be nice if the plug wasn't permentally pulled on users.

**Comment by claell** [comment]
I was just asking out of curiosity, since you mentioned the crashes and that seems to be a rather serious / annoying bug to me. So ideally it can be fixed as well :)

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
