### ISSUE TITLE
Sync error (error 400) on file with name containing a CR or LF

### ISSUE THREAD

**Issue by ccomb** [nextcloud/desktop#3512]
Witth Nextcloud 20 and the desktop sync app version 3.1.1 on Linux.

I have a file whose name contains a "$\n".
It can be created for example with `touch 'Foo'$'\n''Bar'`

During sync, I get an error 400 caused by this file. (error 400 on MOVE ....)

Once I just rename the file and remove the `'$'\n''` it then syncs correctly.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
