### ISSUE TITLE
windows-desktop-client add "Force Synchronization now" to main context menu in systray

### ISSUE THREAD

**Issue by kongomongo** [nextcloud/desktop#3520]
Hi there,

Often I want to move files from my iOS device to my desktop or vice versa. I find that often I end up having synced the files and waiting on the other end for things to start going.

For example: Taking pictures on iOS, using Photos app to Share->Nextcloud->Upload stuff and then waiting on desktop to be able to use the pictures/movies.

Sometimes this takes looong.

What I find myself doing then is going systray->context->settings->context menu on nextcloud (with green checkmark)->force sync now.

What I would propose is adding this to the main context menu in systray (along with the "pause sync for all").

What I understand is that this would be a force sync for all accounts, which might not be desirable. It would have to be named "force sync for all". I would be OK with it, since there are no relevant performance hits in my use case.

As another method one could do another approach:

left click systray to open ui -> add a force sync to the ui here. 

Either here
[https://i.imgur.com/mecfnNh.png](https://i.imgur.com/mecfnNh.png)
or here
[https://i.imgur.com/D4BGbpO.png](https://i.imgur.com/D4BGbpO.png)

What do you guys think?

Many thanks for this cool project.

**Comment by mgallien** [comment]
Thanks,
to me that sounds a great idea
I will check with our design team

**Comment by FlexW** [comment]
By the way with the push notifications backend, you would not have this problem. As the desktop client would be notified immediately if there are changes to the files on the server.

**Comment by kongomongo** [comment]
FlexW, I did a quick google search but I couldn't find a good hit. Can you point to a direction where this is explained?

That said, even if notifications are push, a feature like this can still be usable?

**Comment by FlexW** [comment]
@kongomongo That is the repo https://github.com/nextcloud/notify_push and here a blog post about it https://nextcloud.com/blog/nextcloud-faster-than-ever-introducing-files-high-performance-back-end/ 

I mean not everyone can setup push notifications and for those, that button might be useful :) I think if you have the push notifications backend you will rarely use the button.

**Comment by kongomongo** [comment]
Thanks @FlexW. That seems a little more involved, not sure if it works on webspace-only hosting where you can't run a daemon.

Nevertheless thank you for the tip!

**Comment by kongomongo** [comment]
any traction on this?

**Comment by FlexW** [comment]
@kongomongo Currently there are more urgent tasks. If you need that feature feel free to implement it yourself and open a pull request :)

**Comment by kongomongo** [comment]
OK, can you help out here?

https://github.com/nextcloud/desktop/pull/3696

**Comment by PhilippSchlesinger** [comment]
This seems implemented by now (in 3.7.3)
![grafik](https://user-images.githubusercontent.com/2735628/220903565-58ff0f16-a1e1-4600-aa2e-fd56ff09e875.png)

**Comment by kongomongo** [comment]
yes can confirm 3.7.3 has the sync now feature! Awesome. Thanks everyone! And thanks @PhilippSchlesinger for bringing it up!
