### ISSUE TITLE
Mac system does not switch the translation place

### ISSUE THREAD

**Issue by yinglian-litao** [nextcloud/desktop#3522]
Mac system does not switch the translation place

**Comment by claell** [comment]
Please specify, I don't understand what you mean

**Comment by yinglian-litao** [comment]
Apple client, where can I set the language?

**Comment by yinglian-litao** [comment]
> Please specify, I don't understand what you mean

Apple client, where can I set the language?

**Comment by claell** [comment]
I still am not sure whether I understand what you mean. I assume, you want to change the language of the application? I guess the app language follows the system language (or can be set while installing, not sure).

**Comment by FlexW** [comment]
The client follows the language of the system. There is no possibility to change it in the client.
