### ISSUE TITLE
Windows Client: Nextcloud Desktop Client Extension doesn't pass hostname for 'Open in browser'

### ISSUE THREAD

**Issue by tanzhenchao** [nextcloud/desktop#3525]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The link passed should include the full path to the file/folder. (Google Chrome https://nextcloud.mydomain.com/index.php/f/193049)

### Actual behaviour
The actual link is missing the hostname (https:///index.php/f/193049)

### Steps to reproduce
1. Select a file in the synced Nextcloud folder
2. Right click and select the 【Nextcloud】-> 【Open in browser】option
3. Browser shows https:///index.php/f/193049

### Client configuration
Client version:Nextcloud Desktop Client Version 3.2.0(Windows)

Operating system:Microsoft Windows [Version 10.0.19042.572]

OS language:English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version:Nextcloud version: 21.0.2.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:None generated

3. Server logfile: nextcloud log (data/nextcloud.log):None generated

**Comment by mgallien** [comment]
Hello sorry for missing this bug report in time but can you:

- upgrade to the latest version and test to see if you still reproduce ?
- Provide us the logs. See the procedure in the issue template in your first message ?
