### ISSUE TITLE
"VFS" Renaming a file issue deleted and recreates 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3527]
I notice when renaming a file while having VFS on it will delete the old file and create a new file with the renamed. Should it just rename the file and not delete and create a new one ? 

![image](https://user-images.githubusercontent.com/59488153/125091596-2aa36680-e096-11eb-814b-198838acc49d.png)

**Comment by allexzander** [comment]
@andyxheli Should be fixed in 3.2.4. Can you still reproduce it?

**Comment by andyxheli** [comment]
@allexzander Yes I can reproduce it on 3.2.4 sorry I should of stated I'm having the issue on 3.2.4 in the original post. I did a clean install still the same issue.

**Comment by andyxheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/126542613-9cd528b9-b760-4920-a69b-7dc395063fa4.png)

**Comment by andyxheli** [comment]
Still an issue

**Comment by andyxheli** [comment]
Still an issue

**Comment by mgallien** [comment]
> Still an issue

hello,
can you @andyxheli share your logs when testing with the latest release (3.3.3 at the moment) ?

**Comment by andyxheli** [comment]
Sorry look for on 3.3.3. I did changed a lot of files and did see an issue. If this changes in the future ill be sure to reopen this ticket or open a new one. @mgallien Thank you for your time.
