### ISSUE TITLE
Could not read system exclude file

### ISSUE THREAD

**Issue by DC7IA** [nextcloud/desktop#3530]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud Client should sync.

### Actual behaviour
Nextcloud Client does not.

### Steps to reproduce
1. try to sync
2. does not work ("Could not read system exclude file", which has no meaning to me)

### Client configuration
Client version: 3.2.2

Operating system:

```
$ uname -sr
FreeBSD 13.0-RELEASE-p3
```

OS language: C

Qt version used by client package (Linux only, see also Settings dialog): not a Linux, does not apply

Client package (From Nextcloud or distro) (Linux only): not a Linux, does not apply

Installation path of client: /usr/local/bin/nextcloud

### Server configuration

I don't think this is needed since clients on Linux and Android just work.

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
You probably don't have the system exclude file where the client expects it. Is there a sync-exclude.lst file in /etc/Nextcloud and ~/.config/Nextcloud ?

**Comment by DC7IA** [comment]
No, there is none in `/etc/`, because that is an operating system path on FreeBSD. Programs can place files in `/usr/local/etc/`, but not in `/etc`, that is just for FreeBSD itself.

Also, what does such a file look like anyway?

**Comment by FlexW** [comment]
@DC7IA Sorry, I do not know much about FreeBSD. Look at the sync-exclude.lst file in the repository root directory. Just copy it to /usr/local/etc/Nextcloud and see if that solves the problem.

**Comment by DC7IA** [comment]
Thanks, that folder contains a `sync-exclude.lst.sample`, I just copied that to `sync-exclude.lst` and now the client syncs.

It's just strange that I need to do that manually. :thinking:

**Comment by FlexW** [comment]
@DC7IA Did you hit `make install` with superuser privileges? Which folder contained the `sync-exclude.lst.sample` file? I'm going to close that issue now.

**Comment by DC7IA** [comment]
`/usr/local/etc/Nextcloud/sync-exclude.lst.sample`, used `pkg install nextcloudclient` instead of compiling.

**Comment by mgallien** [comment]
> `/usr/local/etc/Nextcloud/sync-exclude.lst.sample`, used `pkg install nextcloudclient` instead of compiling.

if you used pkg install that means it is in the port hierarchy (basic knowledge only about *BSD) ?
if yes, can you reach to the FreeBSD maintainer ?
we can always help but we do not maintain it ourselves
