### ISSUE TITLE
Missing asc signature files for release 3.2.4

### ISSUE THREAD

**Issue by dave-kennedy** [nextcloud/desktop#3533]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
asc signature files should be listed alongside binaries in latest release.

### Actual behaviour
No asc signature files are available for the latest release.

### Steps to reproduce
1. Go to https://github.com/nextcloud/desktop/releases/tag/v3.2.4.

(None of the other client/server stuff is relevant.)

**Comment by FlexW** [comment]
Thanks for noting. We will add them. FYI macOS and Windows don't need these files, as the installers are signed anyway.

**Comment by allexzander** [comment]
@dave-kennedy Added.

**Comment by dave-kennedy** [comment]
@FlexW do you mean when you install a package on macOS it automatically does a `gpg --verify`? Is the asc file built into the package?

**Comment by FlexW** [comment]
@dave-kennedy I'm not sure if it does exactly that, but the package is signed and I assume that the OS does the necessary checks, like Windows does for example.

**Comment by allexzander** [comment]
Files are just signed with our key. Asc is not built in AFAIK.

**Comment by dave-kennedy** [comment]
Okay, thanks for explaining. I've never really understood the whole signing business. I still don't, actually. I mean, the AppImage is also "signed", but you still recommend to verify the signature matches the one in your keyring, right? How is that different on Mac or Windows?

**Comment by FlexW** [comment]
@dave-kennedy It's not necessary to verify the Windows or macOS installer after download, because a signature is built into the installer. You should be safe without doing it. The app image COULD be signed too, but it IS NOT at the moment. Therefore you need to check it yourself with the asc file. This will probably change in the future, and we will remove the asc files altogether then.
