### ISSUE TITLE
Allow setting to start client to old view

### ISSUE THREAD

**Issue by hr87** [nextcloud/desktop#3534]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

Add a setting to start directly into the old GUI (currently called settings). On Fedora with Gnome, the new GUI is almost unusable. The GUI will show up when started, but normally is not responsive. However, when I click anywhere else on the desktop, or switch programs, it disappears immediately. This, together with it being unresponsive, forces me to not use my computer until the new client decides to finally do something. This makes the client pretty much unusable, and the only thing I normally try to do is to get into the old GUI, which normally only works on the 3rd try. Therefore, I propose a setting to circumvent the new client and allow to directly start the old GUI.

I noticed on a Mac, that it is supposed to have a status icon, with which the disappearing GUI makes more sense. But with Gnome not allowing status icons, the disappearing pretty much makes the whole client unusable.

**Comment by FlexW** [comment]
We working on a pull request that fixes the situation on GNOME. https://github.com/nextcloud/desktop/pull/3468
