### ISSUE TITLE
Two nextcloud accounts on one windows machine: one of the two visual state is always displayed as "offline"

### ISSUE THREAD

**Issue by netsrotr** [nextcloud/desktop#3535]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Using now newest version 3.2.4. It worked with older version(s)... Problem: I use nextcloud to sync a private cloud and my company cloud at my work laptop.  It worked fine with older version(s).

### Actual behaviour
Now it happens, that one of the two accounts is stated "offline" randomly, like this:
![image](https://user-images.githubusercontent.com/5443937/125257605-e1555000-e2fd-11eb-9295-559693be474f.png)
If I restart nextcloud client, it might switch the "offline" state just to the other account, sometimes also both offline.
BUT: it seems, the sync. is still working. I have read the hints at [https://docs.nextcloud.com/desktop/3.2/troubleshooting.html](https://docs.nextcloud.com/desktop/3.2/troubleshooting.html), both servers are working well, also in webDAV mode. Nothing is in the local log file(s).

### Steps to reproduce
1.  Try the client with two accounts the same time
2. I don't know, if this will be reproducable...

### Client configuration
Client version: 3.2.4

Operating system: Edition	Windows 10 Pro
Version	21H1
Installiert am	‎27.‎08.‎2020
Betriebssystembuild	19043.1083
Leistung	Windows Feature Experience Pack 120.2212.3530.0

OS language: de

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
[nextcloud.debug.zip](https://github.com/nextcloud/desktop/files/6799957/nextcloud.debug.zip)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
The "Offline" is related to your user status in Nextcloud. Not the sync status. In the next feature release, the "Offline" or "Online" Status will be removed to avoid confusion.
