### ISSUE TITLE
Windows Client in idle high CPU usage since 3.2.2

### ISSUE THREAD

**Issue by FireEmerald** [nextcloud/desktop#3538]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The Windows Desktop client should consume less than 5% CPU usage in idle mode.

### Actual behaviour
The client consumes about 20-30% CPU usage in idle mode.

The issue was already reported earlier in 2020 but then it got closed and it seems no dev noticed the recent new comments: #2379 

### Steps to reproduce
1. Install latest Windows client
2. Connect to any server
3. See high CPU usage in idle mode

Downgrading to 3.2.1 solved the issue on my particular system. So it's definitely a bug in the recent versions.

### Client configuration
Client version: >= 3.2.2, 3.2.3

Operating system: Windows 10

OS language: German

Installation path of client: n/a

**Comment by J-Spark1** [comment]
I am having exactly the same issue of 40% cpu ussage by the nextcloud client. There are two cores completly pinned at 100% and one at around 90%.

My configuration:

client version: 3.2.4 
OS: Windows 10:
language: German
CPU:  AMD Ryzen 7 4700U

**Comment by Zaphod81** [comment]
Had this with the last two client updates.
Killing all instances via task manager solves the problem.
Since the update starts automatically, I only found out when my Laptop battery was drained in a short time.

Win10 - 21H1
Intel i7-3920XM

**Comment by claell** [comment]
Not sure how to treat this. I have reopened #2379 for now, but am not entirely sure, whether both issues are identical. If yes, this one can be closed as a duplicate.

**Comment by nicogerber** [comment]
Same problem here. I solved it by killing all instances of Nextcloud and restarting the client.

Client version: 3.2.4
OS: Windows 10

**Comment by q-wertz** [comment]
I had yesterday the same problem (after the installation) and killed NC. After shutting down the PC yesterday and looking back into the issue today I saw that the CPU load now is back to normal again.

**Comment by allexzander** [comment]
> I had the same problem yesterday (after the installation) and killed NC. After shutting down the PC yesterday and looking back into the issue today I saw that the CPU load now is back to normal again.

@q-wertz Was it a clean installation, or was it an update from an old version to a recent one? If so, which version was previously installed?

**Comment by q-wertz** [comment]
It was an update. Not sure which was the one before but usually I stay with the most recent one, so I assume it was 3.2.3

3.2.4 is working like a charm since the reboot :tada:

**Comment by allexzander** [comment]
@q-wertz Did the update request a reboot? Or, did you have to reboot manually to make things work?

**Comment by q-wertz** [comment]
It didn't request one as far as I remember. I did a manually one (shutdown not reboot If that's of importance for you)

**Comment by allexzander** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/3566

Keep in mind, the fix will start to work in 3.3.1. The bug is in the client's updater code, so, for it to start working properly, you must first install 3.3.0 (which is going to be released soon), then, update to 3.3.1 and subsequent releases should work properly, without the old process sitting there and eating your CPU cycles. After updating to 3.3.0, please restart, to avoid the issue. 3.3.1 should then work fine without the need to restart.
