### ISSUE TITLE
Windows 10 client crashes ENFORCE(FAILING) - nextcloud_csync.dll

### ISSUE THREAD

**Issue by freprec** [nextcloud/desktop#3539]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud client should not crash shortly after connecting to the server.

### Actual behaviour
A short while (not much more than a minute) after the client connects to the server it crashes. This did not occur a few versions back, but I do not remember which.
Visual Studio Debug Message: Unhandled exception at 0x00007FFD11539800 (nextcloud_csync.dll) in nextcloud.exe: 0xC0000005: Access violation writing location 0x0000000000000000.
My older forum topic: https://help.nextcloud.com/t/windows-10-client-crashes-enforce-failing/117519

### Steps to reproduce
1. Let the client connect to the server.
2. Wait for it.
3. The client crashes!

### Client configuration
Client version: Windows Client 3.2.4 (and a few before)

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Nextcloud version: 21.0.2, running on Synology NAS

Storage backend (external storage): Synology NAS

### Logs

1. Client logfile (from client v3.2.2): 
https://gist.github.com/freprec/7e76f79ff0d7f807e32c715cf42aa69b

2. Web server error log: n/a

3. Server logfile: nextcloud log (data/nextcloud.log): Content does not seem relevant. Could be made available privately.

**Comment by FlexW** [comment]
@freprec Did you downgrade? That error appears if the sync database is incompatible with the client version. Please delete the files starting with `._sync` in your sync folders. That should solve the problem.

**Comment by freprec** [comment]
I did not downgrade, but deleting the ._sync files on Windows fixed it. Thanks a lot!
