### ISSUE TITLE
Provide Complete System Requirements for Windows Desktop CLiENT Compatibility

### ISSUE THREAD

**Issue by github-tomster** [nextcloud/desktop#3543]
@world 
the official system requirements list's a vague and incomplete info about the compatibility for the windows desktop client:
[OFFiCiAL LATEST ADMiN DOCUMENTATiON](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#desktop-client)
```
Desktop client
We strongly recommend using the latest version of your operating system 
to get the full and most stable experience out of our clients.

Windows 7+
```
or

[Nextcloud Client Manual](https://docs.nextcloud.com/desktop/3.2/installing.html#system-requirements)
```
System Requirements
Windows 10+
```

~~Windows 10+/Windows 7+~~ can be fixed to  ```Windows 10 1709 and later```
maybe an extra info like ``` [SAC ONLY]``` and ```No Windows Server``` can save lifes...
if one can do a statement on LTSC/LTSB/iOT can make this complete.

@thosewondering
indeed, [nextcloud desktop client is not supported on WiNSERVER ](https://github.com/nextcloud/desktop/issues/3416#issuecomment-857935244) never was❗ 

the support for win os ```< Windows 10 1709``` was dropped with client version 3.2.0 on 2021-04-13
[silly me was unable to find the changelogentry for that. any hints where to find it❓]

is there little or a strong probabillity that this official no-documentation and
the following issues are related:
#3416 
#3378 
#3392 
#3300 
#3253 
#3177 
and so on and on ... 🤦‍♂️ 

there is a chance that a more detailed documentation can prevent such issues 🤷‍♂️ 
if so one can call it an enhancement 🤷‍♂️ 

you're welcome to use my feedback, given in my leisure time, for free!

**Comment by FlexW** [comment]
Do you want to create a pull request on your own to fix the documentation? You can find the documentation for the desktop client here https://github.com/nextcloud/desktop/blob/master/doc/installing.rst . The admin documentation can be found here https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst .

**Comment by github-tomster** [comment]
https://github.com/nextcloud/desktop/pull/3546
https://github.com/nextcloud/documentation/pull/6962

lets see if this helps 🤷‍♂️

**Comment by Pimmetje** [comment]
I think there first should be a discussion if everything without Microsoft cloud sync api should be dropped in the first place.
Be aware that a lot of used systems supported & unsupported to not have this API. 

If there is a discussion somewhere please point me to it.

**Comment by mgallien** [comment]
closing since the 3.3 release series is working again on all Windows edition still supported by Microsoft (8.1+ and 10+).
