### ISSUE TITLE
Windows uninstall - VFS folder still registered

### ISSUE THREAD

**Issue by reduakt** [nextcloud/desktop#3562]
### Expected behaviour
When I uninstall Nextcloud sync client and delete my local Nextcloud folder, it should also unregister a used VirtualFileSystem VFS folder in Windows.

### Actual behaviour
If the folder is recreated after nextcloud uninstall, windows still assumes the folder is some sort of VFS. Right click content menu and status icons inside the folder are like within OneCloud folder. This messes up explorer sync icons, if the folder is reused with full sync feature again.

### Steps to reproduce
1. Install NC
2. Sync your folder with VFS feature
3. Delete NC application and delete your local NC-VFS folder
4. Recreate the folder
5. Right click context menu on folder or look inside the folder to verify that windows still thinks it needs VFS treatment

### Client configuration
Client version: 3.2.4

Operating system: Windows 10 20H2 19042.1110

OS language: DE

### How to quick-fix manually
1. regedit.exe
2. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SyncRootManager
3. Delete the subfolder which is associated to the VFS nextcloud folder

### Others
Same bug is found on Owncloud [(https://github.com/owncloud/client/issues/8282)]

**Comment by TheThief** [comment]
If anyone's stuck with a nextcloud folder full of VFS placeholders that they can't delete, you just need the following powershell:

```
$MethodDefinition = @'
[DllImport("CldApi.dll", CharSet = CharSet.Unicode)]
public static extern Int32 CfUnregisterSyncRoot(string SyncRootPath);
'@

$CldApi = Add-Type -MemberDefinition $MethodDefinition -Name 'CldApi' -Namespace 'Win32' -PassThru
$CldApi::CfUnregisterSyncRoot("C:\Users\%username%\Nextcloud")
```

(Replace the path with your nextcloud folder path)

**Comment by allexzander** [comment]
@reduakt @TheThief I am working on implementing this as a part of the MSI installation package. If you install this build https://cloud.nextcloud.com/s/pxWYn78S7MSLLYs, keys would get removed from the Registry upon uninstallation.
