### ISSUE TITLE
Settings Menu with the three dots hangs

### ISSUE THREAD

**Issue by albbino** [nextcloud/desktop#3567]
Version 3.2.4 on Windows 10

If the option virtual files is enabled its no longer possible to edit the menu with the three dots.
On every the dialog displaying "no response".

![image](https://user-images.githubusercontent.com/53584330/126236895-a080b4e1-7d3b-4443-b177-9b49840655d4.png)

**Comment by jbruck** [comment]
This happens to me, newly after upgrading to 3.2.4. It could be related to #3349 which also occurs on my system.

**Comment by FlexW** [comment]
This is because the client goes through every file to calculate the availability of virtual files. There is a pending pull request which will remove the availability entry from the context menu. A better solution might be delivered later. https://github.com/nextcloud/desktop/pull/3565

**Comment by allexzander** [comment]
The PR #3565 was merged and is available in this build https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.3.0-rc2-x64.msi. The issue should now be fixed. Thx.
