### ISSUE TITLE
Create a unified installer for 32-bit and 64-bit on Windows

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3570]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Only one installer for 32-bit and 64-bit on Windows. Maybe this can be achieved with https://wixtoolset.org/documentation/manual/v3/bundle/

**Comment by Rello** [comment]
32 is not supported anymore by QT
