### ISSUE TITLE
Nextcloud 3-2.4 failed install on fresh w10PRO 21H1 laptop MSI GL67-7QF

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/desktop#3575]
Laptop is a MSI GL62-7QF (https://www.msi.com/Laptop/GL62-7QF/Specification)

Just installed a fresh W10PRO 21H1 from the media tools creator.

fisrt boot, user created, connected to internet.

No other software added, no update, no nothing

Fresh download and install of Nextcloud-3.2.4-x64 

reboot as asked

launching nextcloud desktop 3.2.4

Application crash.

error as follow:

crash app nextcloud.exe, version : 3.2.4.25618, timestamp : 0x60e484a1
crash module : ntdll.dll, version : 10.0.19041.928, timestamp : 0x9bed63d6
Code exception : 0xc0000409
0x00000000000a2020
0x22d0
0x01d77d84833ffda5
C:\Program Files\Nextcloud\nextcloud.exe
C:\Windows\SYSTEM32\ntdll.dll
581be8f5-ef59-4fc0-853a-0ad9e00438d1

all nextcloud desktop 3.x version are crashing.

last 2.x is running.

i am lost ....

**Comment by stratege1401** [comment]
same crash for 3-3.0-rc1
Code exception : 0xc0000409
0x00000000000a2120
Nextcloud.exe version : 3.2.81.25627, horodatage : 0x60f00019
crash module ntdll.dll, version : 10.0.19041.1110, horodatage : 0xe7a22463

**Comment by FlexW** [comment]
Were any logs created? Unfortounley I think the crash dumps are not really helpful.
