### ISSUE TITLE
i18n: Need context for "%1 as %2"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#3578]
https://github.com/nextcloud/desktop/blob/15affdbfdaa6a32daba2f3ae0319c215d543b792/src/gui/accountsettings.cpp#L1108

Please provide some context.

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/326823769?q=issue%3Aopen

Even better add comments to source code.

**Comment by FlexW** [comment]
It's this string in the gui so the %1 is server name and %2 is the user name. Not sure who a good context would like there. The code is a bit weird there.

![Screenshot from 2021-07-22 17-58-34](https://user-images.githubusercontent.com/19961516/126670757-995aa773-b924-4482-b1bf-297cb50a8da6.png)

**Comment by mgallien** [comment]
no longer an issue since the code changed and this string has been removed/modified.
