### ISSUE TITLE
empty files synced to server due to disk full event

### ISSUE THREAD

**Issue by pascalBokBok** [nextcloud/desktop#359]
We had an accident in relation to a disk becoming full during sync.

The result was that 7 files of 0KB was synced back to the server.
Fortunately I was able to track them down through Activitity and manually restore from earlier revisions.

I'm guessing what happened was the sync client created the files before filling data and then crashing due to disk full and after restarting synced the empty files back due to newer timestamp.

I will post the full client version information when I get get back home.
it's a linux client.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
