### ISSUE TITLE
Last local file deletion stuck the client sync process

### ISSUE THREAD

**Issue by Vost3** [nextcloud/desktop#3590]
### Expected behaviour
Remove the file on the server

### Actual behaviour
The client stay in "rapprochement des modifications" and the last file of the local folder is not removed on server.
Every new event on local side not work after that

### Steps to reproduce
1. Remove the last file on local folder
2. To return on stable states, delete de sync*.db file but the reappear cause on server side it wasn't deleted

### Client configuration
Client version: **3.2.4 (Manjaro)**

Operating system: 
Manjaro : **5.11.4-1-rt11-MANJARO (64-bit)**
OS language: **French**
Qt version used by client package (Linux only, see also Settings dialog): **5.12.2**
Client package (From Nextcloud or distro) (Linux only): **Chih-Hsuan Yen (compiled in 09/07/2021) on Pamac**

Installation path of client: /etc/Nextcloud

### Server configuration
Nextcloud version: **22.0.0**
Storage backend (external storage): **No**

### Logs
1. Client logfile: https://gist.github.com/Vost3/1186b1560b6c6f1bda1efd77e38f055c.js

2. Web server error log: https://gist.github.com/Vost3/2fa6e7509a6c51e97d75b3f1180f60b6.js

3. Server logfile: nextcloud log (data/nextcloud.log): https://gist.github.com/Vost3/b89132fe40b69e22ade19170918b93f5.js

**Comment by FlexW** [comment]
This issue should be resolve in the latest master. Do you want to give the latest RC a try and see if the problem is gone? You can find it here https://github.com/nextcloud/desktop/releases/tag/v3.3.0-rc2
