### ISSUE TITLE
Desktop 3.2.4 stopped responding when syncing renamed video files

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#3605]
After renaming about 100 video files, the desktop client would trigger about 10 process under "System (PID 4)" to read through the video files, causing about 100MB/s of read. The client itself would then stopped responding and caused the explorer to malfunction as well.
### Expected behaviour
The client should be remain normal during the background activity
### Actual behaviour
The client stopped responding
### Steps to reproduce

1. sync a folder which has about 100 mp4 file with the server (size varying from 100MB to 700MB)
2. create several subfolders
3. rename all the mp4 files with a batch renamer
4. spread the renamed files into subfolders

**Comment by allexzander** [comment]
@Milokita Did the client come back to life at some point, or, did you have to terminate it?

**Comment by Milokita** [comment]
it would occasionally came back to life as if had read through all the file. Just few seconds later it would start reading the video files and freezes again. In the end, I have to terminate it

Sincerely
XINGZ

________________________________

**Comment by Milokita** [comment]
As shown in the screenshot, the problem is reproducible on SSD. 
![image](https://user-images.githubusercontent.com/8993036/129125575-7ea7c8f1-93b5-43e2-8ba5-1709903aa0da.png)
![image](https://user-images.githubusercontent.com/8993036/129125858-4e7ab3c6-511b-4319-b250-101bd75a55f0.png)

**Comment by mgallien** [comment]
@Milokita we have fixed a bug related to file renames in our latest release
can you test with 3.3.2 ?

**Comment by Milokita** [comment]
@mgallien Yes, the bug is resolved.
