### ISSUE TITLE
Rename logfiles in AppData from "Owncloud" to Nextcloud

### ISSUE THREAD

**Issue by LostInCompilation** [nextcloud/desktop#3606]
The current version of the Nexctloud client for Windows creates log files inside "%appdata%\Nextcloud\logs" which are named like "20210729_0830_owncloud.log" or "20210729_0830_owncloud.log.0.gz" (gz archive).

They should be renamed from Owncloud to Nextcloud.
Similar issue like #3491, but this issue refers to logfiles in AppData, not the sync folders.

**Comment by joshtrichards** [comment]
Fixed in #5271
