### ISSUE TITLE
Automatically send crash reports

### ISSUE THREAD

**Issue by c0fe** [nextcloud/desktop#361]
Once in a while my Nextcloud Windows client crashes, rather than prompt the user every time if they want to send a crash report, I would like to suggest a feature to disable this and automatically send the crash report and reboot the application. If the application immediately crashes within 5 minutes of starting up a few times then the user should be notified that there is a problem.

**Comment by joshtrichards** [comment]
Hi @c0fe - I think this is a "nice to have", but until we get the crash reporter working again (if/when) this is a non-starter: see #4165.

I'm going to close this out (for the time being) for that reason and also the following additional ones:

- automated *reporting* is an edge case that has privacy concerns (though behind an opt-in it might be okay) 
- insufficient interest in the past five years based on traffic to this issue 

If someone wishes to work on #4165 and then also implement a toggle for opt-in reporting behind it so be it (and now the two issues are linked by reference permanently).
