### ISSUE TITLE
Crash during synchronization due to ENFORCE: "false" in discoveryphase.cpp, line 188

### ISSUE THREAD

**Issue by pylorak** [nextcloud/desktop#3614]
Nextcloud client crashes after a couple of seconds being started and doesn't finish synchronizing.

Client log created using `--logdir` option is attached:
[20210730_1054_owncloud.log](https://github.com/nextcloud/desktop/files/6906502/20210730_1054_owncloud.log) (some info redacted using mass replace)

Client version: 3.2.4
Server version: 20.0.11
OS Version: Windows 20H1 (Build 19041.1110)

**Comment by FlexW** [comment]
This error happens when the sync journal is not compatible to the client. Probably because of a downgrade. Please delete the files starting with ._sync in the sync folder.

**Comment by pylorak** [comment]
Will try the workaround and see if it helps.

However, the analysis of the cause is clearly wrong. There was never a downgrade to trigger this, which is obvious, because as mentioned the client version is 3.2.4. That is the latest version available. Actually, the problem's been happening since the Nextcloud desktop client updated itself to the latest version (approximately) about a week ago.

**Comment by FlexW** [comment]
You could have run a daily or rc or build directly from master. Then it would be a downgrade. If you never installed any other version of the client, then it's odd.
