### ISSUE TITLE
If OS support is end of life, display a warning in client instead of updating

### ISSUE THREAD

**Issue by sunjam** [nextcloud/desktop#3622]
Request: If a desktop client update will no longer support the user's operating system (Windows 7) the update should not proceed and instead give a warning such as "Your operating system ia no longer supported as of version x.xx.x"

Thank you for considering.  See forum discussion at https://help.nextcloud.com/t/nextcloud-desktop-client-3-2-3-is-out/119190

**Comment by FlexW** [comment]
Just for the record: With 3.3.0 we made the part that caused issues on older operating systems like Win7 optional. That means it will run again on Win7 and you can safely update. Although we do not officially support that.

**Comment by mgallien** [comment]
@sunjam can you report if the latest version worked for you ?
I am closing this issue, please let us know if a reopen is needed.

**Comment by sunjam** [comment]
Latest version properly installed.
