### ISSUE TITLE
Can't install 3.3.0 on Windows 10 21H2 (19044.1151)

### ISSUE THREAD

**Issue by CryptoSiD** [nextcloud/desktop#3630]
I'm running Windows 10 21H2 (OS Build 19044.1151) and I can't install the latest Nextcloud Desktop.

I'm getting the following error:
![mjEa](https://user-images.githubusercontent.com/7094808/128340474-acc49469-7891-4692-bdae-771fa3456cb7.png)

Here's a screenshot of "winver":
![5dSF](https://user-images.githubusercontent.com/7094808/128340844-27648055-f377-4db8-821f-f80e2f88b571.png)

EDIT:
The issue is most likely the "1511" in the Windows version, the installer seems to check if the version is lower than 1709.
Since I'm on 21H2 and the version is lower than 1709 it refuses to install.

I verified the code and I can't find anything related to "version 1709" but I'm not a coder so I might be wrong.

It might be related to the way the installer is getting compiled?

**Comment by allexzander** [comment]
@CryptoSiD  Just tried on a clean VM (Windows Home version 10...something). Couldn't reproduce. You may be having a leftover of a previous version that is attempted to get uninstalled. I suggest you first remove the old version manually via "Remove Programs", and then, clean installation of 3.3.0 from here should work https://nextcloud.com/install/#install-clients

**Comment by CryptoSiD** [comment]
I can't uninstall 3.3.0-rc2 either, I'm getting the same error when trying to uninstall it.
![h7ZW](https://user-images.githubusercontent.com/7094808/128435805-0c568fa6-5f67-43b7-8cd1-4970a84ef412.png)

**Comment by CryptoSiD** [comment]
The issue is most likely the "1511" in the Windows version, the installer seems to check if the version is lower than 1709.
Since I'm on 21H2 and the version is lower than 1709 it refuses to install.

I verified the code and I can't find anything related to "version 1709" but I'm not a coder so I might be wrong.

It might be related to the way the installer is getting compiled?

**Comment by allexzander** [comment]
@CryptoSiD You should be able to remove the old version from your system. You need to use the "Add or remove programs" menu for that. You may also try to remove it without the UI via `msiexec` command-line tool https://docs.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options. Unfortunately, since the problematic version was installed, you need to find a way to uninstall it prior to installing the 3.3.0.

**Comment by CryptoSiD** [comment]
I already tried to remove it using "Add or remove programs" and I get what is shown in the screenshot.

The issue is also present with 3.3.0 since I can't install it.

**Comment by allexzander** [comment]
@CryptoSiD In 3.3.0 we don't have that condition and message box. It was removed. It is displayed for you by the MSI of the old version. You may need to use a program cleaner/registry cleaner tool and remove it manually. Please first try the `msiexec` way. There is no way for us to fix it in 3.3.1,

**Comment by CryptoSiD** [comment]
I'm not on Windows 11 and I've been able to update without issue.

You can close this issue!
