### ISSUE TITLE
client 3.3.0 can't connect with ldap user

### ISSUE THREAD

**Issue by vm03** [nextcloud/desktop#3631]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client connect and sync same as  previous versions. Ex 3.2.0 works good.

### Actual behaviour
Can't connect with error:
404 Not found (Principal with name username not found)

### Steps to reproduce
1. Install client 3.3.0 or upgrade
2. Login to server

### Client configuration
Client version: 3.3.0

Operating system: MacOS 11.2 and MacOS 10.15.7

OS language: English and Russian

### Server configuration

Nextcloud version: 22.0.0 LDAP users.

**Comment by splitt3r** [comment]
Maybe a duplicate of https://github.com/nextcloud/desktop/issues/3628?

**Comment by vm03** [comment]
Yes. could not find  #3628
