### ISSUE TITLE
Automatic check for updates - disable has no effect

### ISSUE THREAD

**Issue by Doev** [nextcloud/desktop#3633]
Yesterday I disabled the automatic check for updates in the client 3.2.4 and there was no effect. There was still a notification that there are updates.

**Comment by mgallien** [comment]
I cannot reproduce it from a master build.
Could you share logs of your desktop client ?
The best would be that you disable the automated checking of update from settings dialog than close and start again the application.

**Comment by joshtrichards** [comment]
Closing due to no follow-up after ~3 years and nothing actionable remaining at this point. :)

**Comment by marcolaux** [comment]
3.17.2 still checks for updates even if it is disabled in the settings

<img width="646" height="383" alt="Image" src="https://github.com/user-attachments/assets/08ec6d77-d55b-483c-9999-8fccd4119739" />
