### ISSUE TITLE
Client 3.2.4 often shows "offline"-state, but is online

### ISSUE THREAD

**Issue by Doev** [nextcloud/desktop#3634]
![grafik](https://user-images.githubusercontent.com/6341785/128493433-eafc31e7-4e52-4bb5-8724-cce65fbd2cd3.png)

**Comment by allexzander** [comment]
@Doev This is not a status of a desktop client. It's the status of your user. You must log in into a Web UI to see the Online status in the desktop client.

**Comment by Doev** [comment]
I tested it, it is correct. May fault.

**Comment by allexzander** [comment]
@Doev No worries. It is indeed may look confusing. @jancborchardt We may want to think about it.

**Comment by FlexW** [comment]
@Doev @allexzander The sign "Offline" should not appear even if you are offline to avoid confusion. From which version is that screenshot? That should be fixed in 3.3.0.

**Comment by Doev** [comment]
As said in the headline :-) 3.2.4

There is no "offline" in Version 3.3.50 (Windows).
