### ISSUE TITLE
Create a Nextcloud desktop client dev version

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Provide a "Nextcloud Dev" version of the desktop client which will allow users to test the latest changes in master. It should be possible for users to have the "Nextcloud Dev" client and the regular Nextcloud client installed and run in parallel.

- [ ] Create "Nextcloud Dev" builds. Probably via Brander.
- [ ] Add some sort of telemetry so we can see how many users are using it.

Related: https://github.com/nextcloud/desktop/issues/3636

**Comment by joshtrichards** [comment]
Part I: https://github.com/nextcloud/desktop/wiki/Daily-Builds
Part II: #2941

**Comment by claucambra** [comment]
We now have daily builds, so I will close
