### ISSUE TITLE
Add bug/crash reporter

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3638]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Add a bug reporter and crash reporter directly in the client which will make it easy for users to provide feedback/bug reports to us. 

Related: https://github.com/nextcloud/desktop/issues/3637 https://github.com/nextcloud/desktop/issues/3636

**Comment by joshtrichards** [comment]
There is one in the code base already (see `WITH_CRASHREPORTER`), but I'm not sure of it's state.

**Comment by joshtrichards** [comment]
Let's consolidate tracking for this into #4165
