### ISSUE TITLE
Local File is not readable (Windows Error 0x80070185) - Windows NC Client 3.3.0

### ISSUE THREAD

**Issue by uma201** [nextcloud/desktop#3641]
### Steps to reproduce
1. Nextcloud client synchronizes with Server
2. Out of 100.000 files, a handful (2 at the moment) cannot be open (0x80070185)

### Expected behaviour
File should be readable. 

### Actual behaviour
File is not readable. Shows cloud symbol in Windows explorer instead of green OK symbol.
When trying to open the file, strange messages appear (probably from the associated application, like LibreOffice or PDF Viewer).
Windows Error code: 0x80070185 Der Cloudvorgang war nicht erfolgreich.
Note: File is readable on Server and on other client systems, seems to be local to one PC

### Server configuration

**Operating system:**
Ubuntu LTS 18.04 

**Web server:**
??

**Database:**
MariaDB 10.4?

**PHP version:**
7.4??

**Nextcloud version:** (see Nextcloud admin page)
21.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
From nextcloud

### Client configuration

Nextcloud Client 3.3.0 / wincfapi

**Browser:**

**Operating system:**
Windows 10 Home
Windows 21H1
19043.1151

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by FlexW** [comment]
That error normally pops up if the placeholder file is corrupted. Not sure why it was corrupted, but I suggest you quit the client, delete the sync journal (files starting with ._sync in the sync folder) and restart the client. Please tell us if that helps.

**Comment by uma201** [comment]
Dear FlexW,
I stopped the Nextcloud client and then removed the .sync_blablabla.db file from the sync folder (this was the only file starting with .sync).  Then the following happened:
- After starting the client again, it downloaded the complete folder (3.9 GB, took some minutes), although it was all on disc already. 
- Some files (the same as before) still had the cloud symbol in the windows explorer. To me, it seems to be random which files have a cloud symbol and which not.
- However, when I click on a file with cloud symbol, Windows downloads the file and then (after some seconds, depending on the network speed), the file opens, e.g. in PDF viewer.
- Empty folders seem to have the cloud symbol (easy to spot since the cloud symbol propates up the directory hierarchy).
- I have checked this on my Surface PC (Windows 10 Education, 20H2, 19042.1151 with Nextcloud Client 3.3.0), and it also has files with cloud symbol that download when clicked on.

I am using Nextcloud for many years now and havent seen such behavior before. Seems to be correlated with the client upgrade (I migrated to NC21 a month ago and didnt observe problems afterwards).

Regards

**Comment by FlexW** [comment]
> After starting the client again, it downloaded the complete folder (3.9 GB, took some minutes), although it was all on disc already.

Mh it should not download anything if using virtual files.

> Some files (the same as before) still had the cloud symbol in the windows explorer. To me, it seems to be random which files have a cloud symbol and which not.

Maybe that is because they are still placeholder files. Maybe you could also try to delete your account from the desktop client, then remove the sync folder and configure the sync folder again. Maybe that will resolve the problem. I'm aware that is not a proper solution, I just wanted to provide you with a workaround.

> However, when I click on a file with cloud symbol, Windows downloads the file and then (after some seconds, depending on the network speed), the file opens, e.g. in PDF viewer.

Does it then get a green checkmark?

> Empty folders seem to have the cloud symbol (easy to spot since the cloud symbol propates up the directory hierarchy).

That is expected and conforms with OneDrive.

**Comment by uma201** [comment]
Hello,
I have switched back to version 3.2.4, and will wait for a while before I try the 3.3.x again. Stability is really important for me. (maybe I should have paid more attention to the release notes on 3.3.0?)

BTW, Nextcloud is a great software, and I really like it!
