### ISSUE TITLE
Enhance the main dialog

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3644]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The main dialog shows currently a lot of information but finding the right information is sometimes difficult. Therefore we like to improve the situation.

First a mockup of how the activity stream could look like in the main dialog:

![2021-08-10T16:39:01,908483836+02:00](https://user-images.githubusercontent.com/19961516/128887507-1684570c-d61c-4508-8a2b-305c72626a01.png) 

The mockup is not set in stone and buttons etc may look different depending on the platform.

Things to do:

- [ ] Remove impossible actions from entries in the main dialog. For example: Share button on deleted files.

- [ ] In the activity entries separate file names from file paths so both information is readable. 

- [ ] Add ellipses in between long file paths and file names. Example: some/sup.../path 

- [ ] Make the first entry an entry that displays the sync status. It should indicate if everything is okay or if there are errors. If there is currently ongoing sync activity it should show it with a progress bar.
![2021-08-10T16:39:26,546710566+02:00](https://user-images.githubusercontent.com/19961516/128887582-3a5b5893-fa24-4a4e-825e-f3a773fd2531.png)

Missing: Mockup for sync is okay, Mockup for sync error

- [ ] Give Talk mentions a bit more space, put buttons on a new row possibly. Make the whole message readable, or at least more of it, 2–3 rows.
![2021-08-10T16:40:04,357265715+02:00](https://user-images.githubusercontent.com/19961516/128887656-49309acb-b7d0-465a-927a-8029deb6b4b4.png)

- [ ] Reduce size of icons for Sharing and X, as they are too big visually. Maybe even stylize them with circular light blue background and icon in blue, as in the mockup.
![2021-08-10T16:40:42,522969395+02:00](https://user-images.githubusercontent.com/19961516/128887695-cab48cd3-92b5-4589-8d9f-705793248460.png)
Discuss: How to make sync errors more obvious?

- [ ] Similar for the "View chat" button style-wise

- [ ] Reduce the amount of "Synced …" entries, possibly by grouping if it’s the same file, or by just showing the activities from the server. → Needs to be discussed how to do that in detail.

- [ ] Move from a sentence for an activity to the splitting of name, action, etc → probably needs changes in the API and coordination with Joas
![2021-08-10T16:44:08,194870267+02:00](https://user-images.githubusercontent.com/19961516/128887859-2243c936-57ba-464a-add4-581704ce27a2.png)

- [ ] Show in the activity the avatar of the person that created a file/event/talk and for files show file type icons. Files that were created by other users should probably not show the filetype as icon but the avatar of the person who created the file.

**Comment by nimisha-vijay** [comment]
![image](https://user-images.githubusercontent.com/52440189/129032925-95db12fa-909a-427a-88f7-19ef8d58fb87.png)
![image](https://user-images.githubusercontent.com/52440189/129032856-4deb7311-6d4e-431a-98fc-f1a809fa0b59.png)

Here's how it can look like if it's syncing or has an error (icons are the state icons in the desktop repo).
Maybe we can also add sync options in a three dot menu on the side (Pause sync, etc) 
What do you think?

**Comment by tobiasKaminsky** [comment]
Closing in favor of sub-tickets.
