### ISSUE TITLE
Error: "The downloaded file is empty despite that the server announced it should have been x"

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/desktop#3652]
The following error message keeps ocurring with the Nextcloud client:
"The downloaded file is empty despite that the server announced it should have been X" or "Die heruntergeladene Datei ist leer, obwohl der erver X als Größe übermittelt hat."

The file is downloaded correctly and does have the stated size. In this case it's a *.xls file.

### Expected behaviour
Download the file correctly without encountering errors or stating error messages.

### Actual behaviour
The file is downloaded correctly, but the cited error message apperas.

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version: 3.3.0

Operating system: Windows

OS language: German

Installation path of client: Standard

### Server configuration

Nextcloud version: 20.0.11
PHP version: 7.2.34

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by mgallien** [comment]
Can you share your logs (desktop client and server) when that happen ?
Can you test again with latest release (3.3.3 at the moment) ?

**Comment by thrynir** [comment]
Hi,

It seems that either the last client update or Nextcloud 22 (I was in 21 previously) fix the issue.

Regards,
