### ISSUE TITLE
Bulk upload

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3657]
As discussed with @mgallien and @juliushaertl idea is 
- on the client: construct binary blob with multiple files and send it together with filename/path and byte offset
- on server: split the big file into the individual ones and write them to the filesystem

Split up:
- [x] #3761 
- [x] #3762

**Comment by claell** [comment]
Are this and #3658 already possible for downloading files? If not, that might also be useful in that direction.

**Comment by claell** [comment]
Are this and #3658 already possible for downloading files? If not, that might also be useful in that direction.

**Comment by claell** [comment]
Are this and #3658 already available for downloading files? If not, that might also be useful in that direction.

**Comment by mgallien** [comment]
download optimizations will come as a later step

**Comment by claell** [comment]
For my use case, download seems to be much more important. Usually, download network bandwidth is much higher than upload (thus the bottleneck often seems to be the file processing by Nextcloud) and when connecting new clients, the amount of files to download is also very high (while new files to upload mostly get added one by one / in less large batches).
