### ISSUE TITLE
Clean up activity entries in main dialog

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3660]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
- [x] Remove impossible actions from entries in the main dialog. For example: Share button on deleted files.
- [x] In the activity entries separate file names from file paths so both information is readable.
- [x] Add ellipses in between long file paths and file names. Example: some/sup.../path

Context: https://github.com/nextcloud/desktop/issues/3644

**Comment by claucambra** [comment]
First item can be considered done by #4090 

In terms of the second and third, #4102 is addressing this, though rather than display elided file locations it takes the approach of the web client's Activity app and shows file names and their location on hover in a tooltip.

**Comment by claucambra** [comment]
With #4102 merged, this issue can be considered completed :)
