### ISSUE TITLE
Desktop: better error handling

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3661]
While syncing our NC on mac/Windows Andy and Frank reports that they have issues that cannot be resolved

- do a full sync with our c.nc.c
- see if the same error happens  
  - error regarding case sensitive files
  - virtual files on Windows cannot be synced
- all those errors need to have a way so that user can resolve them via client *or* client/server needs to fix them on their own

Errors:
- [x] resolve naming conflicts https://github.com/nextcloud/desktop/issues/3751
- [x] trailing whitespace https://github.com/nextcloud/desktop/issues/3749
- [x] webdav folder error, check back with Frank, on Hackweek in Berlin

If you need more info, Andy and Frank offered to provide you more info and/or even test something

**Comment by FlexW** [comment]
Which version did they test? cloud.nextcloud.com should sync fine and without errors with virtual files.

**Comment by tobiasKaminsky** [comment]
As far as I know the latest version.
@AndyScherzinger ^

**Comment by FlexW** [comment]
For the record: The errors show up in the main dialog.

**Comment by AndyScherzinger** [comment]
My issues, as discussed, on Windows:

* Wildcard in filenames ('*')
* Space at the end of a folder name like 'Name '
* Dot at the end of a folder like 'Name.'

**Comment by FlexW** [comment]
Thanks. Points one to three should be covered by #3751.  For point four I'm not sure we can do anything. Renaming is done by Windows and not the client. We can not prevent users from renaming files on their hard drive, but that should give anyway an error on Windows as the filename to which the file should be renamed does already exist.

**Comment by AndyScherzinger** [comment]
By renaming I rather thought about the rename coming from the server while I am not sure if this is a problem.
