### ISSUE TITLE
Improve Talk mentions in main dialog

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3663]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Give Talk mentions in main dialog a bit more space, put buttons on a new row possibly. Make the whole message readable, or at least more of it, 2–3 rows.

Context and screenshots: https://github.com/nextcloud/desktop/issues/3644

**Comment by claucambra** [comment]
With avatar images and recent changes to the activity items and talk activity items specifically we can consider this to be done
