### ISSUE TITLE
Split name and descripton of activities in main dialog

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3665]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Move from a sentence for an activity to the splitting of name, action, etc → probably needs changes in the API and coordination with @nickvergessen 

Context and screenshots: https://github.com/nextcloud/desktop/issues/3644

**Comment by nickvergessen** [comment]
Let's have a call to discuss what you need and how we can achieve it. But string splitting is at least not a good idea (due to translations and other things)

**Comment by wonx** [comment]
I'm subscribing to this enhancement report because, as I commented in https://github.com/nextcloud/desktop/issues/3703, the text does not fit the main dialog and is not legible.

**Comment by tobiasKaminsky** [comment]
C&P:
Move from a sentence for an activity to the splitting of name, action, etc.

![image](https://user-images.githubusercontent.com/5836855/219308517-58340e3b-9cdc-44ac-bdc8-69fae219a843.png)

@jancborchardt still something we want to do?

**Comment by jancborchardt** [comment]
@tobiasKaminsky yes, absolutely! :) This will allow us to be more compact and concise in notifications rather than showing a whole unwieldy sentence.

(Also ref the mockups for the Talk notifications by @nimishavijay at https://github.com/nextcloud/desktop/issues/5275 )

**Comment by nickvergessen** [comment]
There is a bit of a technical difference. The talk notifications have a subject and message and basically the client can simply overwrite the subject with the username and show the message without touching.

The thing you suggest here is splitting a single string into multiple, which will not work due to translations. A translation neutral subject is not available on the client level so they would not know what kind of string to use:
* UserA xyzed FileA
is xyz changed, or shared, or created, or deleted, ... You can not know it because the translation does not give it away.

**Comment by nickvergessen** [comment]
Well that also requires breaking the PHP API for all apps that provide activities, so really not a fan.

But on that note, it seems like the message/subline (apart from broken casing, I think the screenshot should start with upper case?) is the "short subject" we use in the right sidebar:
https://github.com/nextcloud/server/blob/ccd08877e803be1281b6c9325219e862c1995f9c/apps/files_sharing/lib/Activity/Providers/Users.php#L53-L75

So a random idea would be to: When long/normal version is requested and the user agent is our desktop client, we return the short subject as message and the file as subject?
Sample PR which adjusted user shares available at https://github.com/nextcloud/server/pull/36804

**Comment by nimishavijay** [comment]
If there is a full list of all the types of activities + the primary and or secondary actions for them @jancborchardt and I can make mockups for it :)

**Comment by nickvergessen** [comment]
> If there is a full list of all the types of activities + the primary and or secondary actions

There is not, any app can invent a new activity at any time

**Comment by tobiasKaminsky** [comment]
> So a random idea would be to: When long/normal version is requested and the user agent is our desktop client, we return the short subject as message and the file as subject?

"hiding" this logic bound to UA is strange.
Then better have this as an explicit and optional parameter.

@jancborchardt I understood that you want to change this on all (web and all clients?)
