### ISSUE TITLE
Client connects to dual stack server through IPV4 even if IPV6 is available

### ISSUE THREAD

**Issue by Milokita** [nextcloud/desktop#3674]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The client should connect to server via IPV6 when it's available

### Actual behaviour
From the server, it's observed that the connection is made through IPV4 while the IPV6 address is available and functioning.
Access through the webpage, it can be seen that the connection is through IPV6 

### Steps to reproduce
1. setup a server which has both IPV4 & IPV6 address
2. Ping the server, by default it will show IPV6 address
3. Sync a folder with the server
4. start iftop on server or watch the log

### Client configuration
Client version: 3.3.0

Operating system: Win10

**Comment by FlexW** [comment]
Could you please explain why it would be better to connect through Ipv6?

I'm not sure that is even something we can or should handle ourselves. I think Qt should handle that for us, and according to https://www.qt.io/blog/2011/07/05/ipv6-changes-in-qt5 it does. Qt automatically uses the one that replies faster, which in your case might be Ipv4.

**Comment by Milokita** [comment]
The test is conducted in LAN with IPv6 and v4 resolved to the same server by host file, so there should be very little differences in respond time. The reason I think it is a sync engine issue rather than Qt is because on owncloud Ver2.8.2 which uses Qt 5.12.10 can correctly uses IPv6 while ours can't.
