### ISSUE TITLE
Main Dialog Missing Since Upgrade to any 3.X version

### ISSUE THREAD

**Issue by azon2111** [nextcloud/desktop#3687]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Should see the main dialog so conflicts and sync information can be seen and conflicts resolved.

### Actual behaviour
Never shows the window but shows in taskbar.  No way to move the window and changing the resolution did not result in seeing it.  Uninstalling and reinstalling 

### Steps to reproduce
1. Seems only to be issue for upgrade from 2.x to 3.x as this is only time we have seen this issue.

### Client configuration
Client version: 3.15 Windows 10

Operating system:

OS language: EN-US

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by FlexW** [comment]
Could you please provide your logs? Otherwise, it will be difficult to help you. You can drop them here https://cloud.nextcloud.com/s/6w5abTCtdHJQjrw .

**Comment by azon2111** [comment]
What log specifically do you need and default path to this log.

Thank you.

**Comment by azon2111** [comment]
Figured that out, sorry. ZIP uploaded

**Comment by azon2111** [comment]
Any ideas, thank you.

**Comment by azon2111** [comment]
> Could you please provide your logs? Otherwise, it will be difficult to help you. You can drop them here https://cloud.nextcloud.com/s/6w5abTCtdHJQjrw .

I uploaded this a little while back, was it any help in solving the mystery ?

**Comment by FlexW** [comment]
I don't see any errors related to the GUI inside the logs that could help me to track the issue down. Is the client running inside a VM. With which graphic card is the computer running? Did you try to uninstall the client and then reinstalling it? Because you seem to be the only person with this problem and a lot of people use the client I guess it's something specific to your system.
