### ISSUE TITLE
Rephrase login dialog as most users do not own/control the server

### ISSUE THREAD

**Issue by rasos** [nextcloud/desktop#3693]
The option `Login to your Nextcloud` should be rephrased to `Login to a Nextcloud`. 

Most users do not host the nextcloud by themselves, but rely on a service partner or their company / organisation they work for. So it is _not_ the user's nextcloud. We are having frequent confusions of customers and their partners / staff that want to sign up which option to choose, as none is really matching their use case: 

![Screenshot_2021-08-20_11-33-33](https://user-images.githubusercontent.com/485723/130213541-95b718c4-669e-46ed-a484-6eb395c11e7b.png)

 `Login to your Nextcloud`  is probably only clear for admins. 

#3011

Nextcloud Desktop Client Version 3.2.4 (Ubuntu)

**Comment by FlexW** [comment]
@jancborchardt @nimisha-vijay opinion please :)

**Comment by rasos** [comment]
Yesterday we probably lost a potential user of our nextcloud. He was already testing our nextcloud with the browser. When installing the App he erroneously clicked on "Create account with Provider" and found one who was slightly cheaper (but does not offer BBB integrated - so a lot to explain).

The second option in the login dialog should thus be probably rephrased to "Looking for a Nextcloud service provider?"

And the third option is also confusing to normal users (who don't really know what hosting means). Proposal for rephrasing: "How to install and run your own Nextcloud server". 

I am not against competition among providers. But let us guide users who just want to sign in pave a more clear way. I would suggest that the first option should be highlighted for the most common use case which is that a user already has signed in via a web interface at his company / organisation and now is trying to add sync capabilities.

**Comment by nimisha-vijay** [comment]
Pretty interesting!
For normal users, don't you think "your Nextcloud" would simply mean the one they use -- regardless of whether it is selfhosted or with a provider? My guess here is that the confusion arises because there is another option that explicitly states "Provider", so people are confused as to what the other one means now.

What if we kept the login option the same, and changed the second and third one? 
- Log in to your Nextcloud
- Sign up for an account
- Set up your own Nextcloud server

Agreed that the login option should be highlighted.
What do you think?

**Comment by jancborchardt** [comment]
Something that we can do wording-wise is to adjust it to be the same cross-platform. It’s quite nice how it’s done on Android, ref @tobiasKaminsky:
![Talk wording](https://user-images.githubusercontent.com/925062/130799629-3a977cc0-4cd4-4adc-bb30-00701a377f1a.jpeg)
What do you think @FlexW?


Also @rasos to have the least potential of confusion for your customers, we recommend getting branded Nextcloud clients: https://nextcloud.com/branding/
This way your provider domain will be hardcoded and people will just directly be able to log in with username and password.
