### ISSUE TITLE
Workaround for requiring inkscape just in order to generate some png

### ISSUE THREAD

**Issue by timtas** [nextcloud/desktop#3702]
Latest nextcloud-client (3.3.1) now has a hard dependency on inkscape. I found out that this is only needed to generate a couple of png files from an svg file.

To me, it is clearly way over the top to require the installation of a full-blown vector graphics application just for that, as rsvg-convert (and surely other command line tools) can achieve the same.

I now built a wrapper script "inkscape", with the following contents:
```
#!/bin/bash

# silly wrapper for nextcloud-desktop inkscape call


PNG_W="$2"
PNG_H="$4"
SVG_F="$5"
PNG_F="$7"


rsvg-convert -w $PNG_W -h $PNG_H -o $PNG_F $SVG_F 
```
which works around the problem, but I'm sure it would be easier if you could maybe add a check for rsvg-convert to nextcloud-client and then call this if inkscape is not present.

**Comment by mgallien** [comment]
we ended up using inkscape because we had troubles with other tools especially in the context of all the platforms we support (Linux desktops, Windows and Mac OS).
I am not sure I understand what the big deal is after all this is just an `apt-get install inkscape` away

**Comment by timtas** [comment]
Yes, if you're on debian/ubuntu, it's only that. plus ca 100 MB of binaries and libraries. If you however compile your system yourself and have otherwise no use for inkscape, things look a bit different. You first have to compile the otherwise never used gtkmm2 and then inkscape, all just for converting those few svg's to png's.

I'm not complaining all that much (I have my workaround in place), I just thought maybe you could make inkscape an optional dependency, with either:
- a fallback on rsvg-convert
- a fallback on pre-converted png's

Just for people like me that for some reason like to compile nextcloud-desktop themselves without then also having to build/install inkscape for a very minor part of the whole build process.

**Comment by BJKle** [comment]
I like @timtas solution. I deinstalled inkscape and installed "brew install librsvg" with the above mentioned workaround.

**Comment by MonkeysAreEvil** [comment]
Actually, this also has become a problem on Gentoo and derivatives. The build process is sandboxed and inkspace seems to want to write tempfiles during the svg->png process. These tempfiles are outside the sandbox so the `mkostemp` call is caught and the install process fails. Similarly, I just patch the CMakeLists to use rsvg-convert but that's pretty hacky.

```
diff --git a/src/gui/CMakeLists.txt b/src/gui/CMakeLists.txt
index 0368dd197..58c83afdf 100644
--- a/src/gui/CMakeLists.txt
+++ b/src/gui/CMakeLists.txt
@@ -239,7 +239,7 @@ endif()
 
 # Generate png icons from svg
 find_program(INKSCAPE
-  NAMES inkscape inkscape.exe
+  NAMES rsvg-convert
   REQUIRED
   HINTS "C:\\Program Files\\Inkscape\\bin" "/usr/bin" ENV INKSCAPE_DIR)
 # REQUIRED keyword is only supported on CMake 3.18 and above
```
