### ISSUE TITLE
Main dialog window is too narrow for line length

### ISSUE THREAD

**Issue by wonx** [nextcloud/desktop#3703]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Text in the main dialog window, the one that appears when you click the tray icon should be word wrapped so it can be read.
Alternatively, you should be able to resize that window. 

Currently, it's impossible to know which file has been synced or had a problem.

![Captura de 2021-08-22 09-45-05](https://user-images.githubusercontent.com/2736639/130347082-c101368b-d122-4bf3-8408-2cde2f7c75f7.png)

**Comment by mgallien** [comment]
We agree but improving that is already the scope of https://github.com/nextcloud/desktop/issues/3665.
Let's close this one. Thanks anyway for the suggestion.
