### ISSUE TITLE
Windows installer does not work properly

### ISSUE THREAD

**Issue by jimmyfi** [nextcloud/desktop#3721]
I've been trying upgrade my nextcould windows client to latest version but they seem to crash to errors 2503 and 2502.

`Product: Nextcloud -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , , `

`Product: Nextcloud -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , , `

Earlier setups have worked just fine but these latest ones causes issues. I've also noted that new versions require explorer.exe to be restarted ?

Server is also on latest version so there shouldn't be any mismatces of versions.

Windows is Version 21H1 (19043.1165)

**Comment by mgallien** [comment]
can you test again against the latest release (3.3.2) ?

**Comment by jimmyfi** [comment]
Yes. Same happens with 3.3.2

**Comment by mgallien** [comment]
@jimmyfi thanks for the test

**Comment by jimmyfi** [comment]
Just tested on windows version 2004 upgrade worked just fine :)

**Comment by mgallien** [comment]
@jimmyfi thanks for the test

**Comment by jimmyfi** [comment]
issue still is on on  21H1 (19043.1165) so its not closed yet

**Comment by jimmyfi** [comment]
and version 3.3.3 has same error codes..

**Comment by mgallien** [comment]
sorry opening again

**Comment by jimmyfi** [comment]
I did more testing and tried to uninstall the 3.3.0 and still got those two errors that are on the first topic.. not really sure how to fix this (reinstalling windows is not an option;D) :/

**Comment by jimmyfi** [comment]
I tried uninstalling the old version but it didnt work out either (same error codes).. So I gave up and installed win11 and new update installer works just fine ... could be that my old win10 installation was so corrupted already that it didnt work as it should.. or something :) Sorry for the trouble
