### ISSUE TITLE
Usage of private Qt class QZipWriter

### ISSUE THREAD

**Issue by cgzones** [nextcloud/desktop#3723]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The GUI uses the private Qt class [QZipWriter](https://github.com/nextcloud/desktop/blob/1d4f6ab19d31ea7bd8fd5b1f7e51c27ec6e24c93/src/gui/generalsettings.cpp#L49), which also has no stability guarantee.

On Debian the Qt5::GuiPrivate library has no CMake configure script and thus the affected code is [removed](https://salsa.debian.org/owncloud-team/nextcloud-desktop/-/blob/master/debian/patches/0004-Revert-8fb673457b42-Add-a-button-to-create-a-debug-a.patch).

Are there any plans to implement the functionality via public interfaces or is there [hope](https://bugreports.qt.io/browse/QTBUG-3897) to get these interfaces stable?

**Comment by mgallien** [comment]
On Debian Qt5Gui Private component is provided by package qtbase5-private-dev
you can see when adding `find_package(Qt5Gui REQUIRED COMPONENTS Private)` within a cmake project.

For simplicity the Debian packagers choose to build the desktop client with usage of private APIs to avoid the need to rebuild the desktop client when they update Qt. That is their choice.

Using another method to write zip would be nice but that is definitely a feature request and priority for it is low.

Would like to try maybe using KDE Frameworks 5 Archive library ?

**Comment by hefee** [comment]
> On Debian Qt5Gui Private component is provided by package qtbase5-private-dev
> you can see when adding `find_package(Qt5Gui REQUIRED COMPONENTS Private)` within a cmake project.
> 
> For simplicity the Debian packagers choose to build the desktop client with usage of private APIs to avoid the need to rebuild the desktop client when they update Qt. That is their choice.

With a not stable ABI the things in the Private part may change very rapidly. This is the reason, why Debian created this package. As for every minor update all packages, depending on that package needs to get recompiled. The other reason is to make sure, that project do not rely on something, that is not stable. There are only a few valid use cases, when this private API should be used. 

> Using another method to write zip would be nice but that is definitely a feature request and priority for it is low.
> 
> Would like to try maybe using KDE Frameworks 5 Archive library ?

That would be a great alternative.

**Comment by mgallien** [comment]
> > On Debian Qt5Gui Private component is provided by package qtbase5-private-dev
> > you can see when adding `find_package(Qt5Gui REQUIRED COMPONENTS Private)` within a cmake project.
> > For simplicity the Debian packagers choose to build the desktop client with usage of private APIs to avoid the need to rebuild the desktop client when they update Qt. That is their choice.
> 
> With a not stable ABI the things in the Private part may change very rapidly. This is the reason, why Debian created this package. As for every minor update all packages, depending on that package needs to get recompiled. The other reason is to make sure, that project do not rely on something, that is not stable. There are only a few valid use cases, when this private API should be used.

I am sorry for my usage of the word `simplicity`
I wanted to express that not using private APIs in the Debian package means that work is simpler because we are not tied to a specific Qt ABI (as you said no rebuild, ....)

I have no idea when we could switch to a proper public API for that. sorry
