### ISSUE TITLE
Latest update (to 3.3.2) crashed Windows Explorer for me

### ISSUE THREAD

**Issue by claell** [nextcloud/desktop#3726]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
No crash of Windows Explorer

### Actual behaviour
Windows task bar disappeared, took some time to reappear and then again some time (I think about a minute) to recover successfully. Further crashes in between iirc.

### Steps to reproduce
1. I had version 3.3.0 or 3.3.1 installed (not sure)
2. Wait for the update notice (I waited until the message window appeared that an update was available and clicked "Ok" to install it

### Client configuration
Client version: 3.3.0 or 3.3.1 (not sure)

Operating system: Windows 10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by claell** [comment]
I think the crash happened right after the installation window disappeared. Possibly when the client was started again.

Currently, my network connection is not stable, but not sure whether that is related.

**Comment by ostpol** [comment]
On my machines Windows Explorer is crashing during/right after uninstalling with

`msiexec /x $ProductCode /qn /norestart`

It doesn't happen, when it get's uninstalled manually via Apps and Features.

**Comment by zokradonh** [comment]
While my explorer bar on the bottom was missing I could see in the task manager that the explorer.exe process was running (still?). Maybe it was a new explorer.exe process with administrator privileges(incorrectly started by setup maybe) that will never behave as Windows-Shell and therefore no task bar? 

After this crashed explorer update I now have problems with windows UWP apps (calculator, snipping, etc). I can not really interact with them after start, they need 10-20 seconds to fully start.
I experienced the same also a year ago after a NextCloud update and I reinstalled my system due to this. Now after this update I experience the same again.
Anyone else with this strange behavior?

**Comment by claell** [comment]
@zokradonh Snipping tool works fine for me.

**Comment by danielpngr** [comment]
i got the same issue... after killing nextcloud in the taskmanager the freeze stops and everything works fine

**Comment by matthiastummers** [comment]
Now the same happens with OwnCloud: https://github.com/owncloud/client/issues/8995

**Comment by claell** [comment]
Let's hope, this was a one-time issue and doesn't occur again.
