### ISSUE TITLE
Login polling does not work with latest client

### ISSUE THREAD

**Issue by tb102122** [nextcloud/desktop#3730]
### Expected behaviour
Login should get the connection details correct but the Client Sync is not starting even the login vie the browser was successful.

### Actual behaviour
Client polling Windows stays open and does not get the successful login.

### Steps to reproduce
1. Install new client
2. stop client
3. logout/change user password
3. start client
4. login via browser window: "Account connected"
5. login polling window stays open and error is created

### Client configuration
Client version: https://github.com/nextcloud/desktop/releases/tag/v3.3.2
Operating system: Windows 10 with Chrome
OS language: English
Installation path of client: Default

```
2021-08-31 09:30:53:318 [ info nextcloud.sync.connectionvalidator ]:	No system proxy set by OS
2021-08-31 09:30:53:321 [ info nextcloud.sync.accessmanager ]:	2 "" "https://DOMIAN/status.php" has X-Request-ID "49071803-70b3-471a-9bc3-7799e504e539"
2021-08-31 09:30:53:325 [ debug nextcloud.sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://DOMAIN/status.php") requests: (QNetworkCookie("__Host-nc_sameSiteCookielax=true; secure; HttpOnly; expires=Fri, 31-Dec-2100 23:59:59 GMT; domain=DOMAIN; path=/"), QNetworkCookie("__Host-nc_sameSiteCookiestrict=true; secure; HttpOnly; expires=Fri, 31-Dec-2100 23:59:59 GMT; domain=DOMAIN; path=/"))
2021-08-31 09:30:53:327 [ info nextcloud.sync.networkjob ]:	OCC::CheckServerJob created for "https://DOMAIN" + "status.php" "OCC::ConnectionValidator"

**Comment by claell** [comment]
Can confirm the behavior. This makes using the connection impossible in this state if I am correct.

Ping @allexzander @FlexW @mgallien

**Comment by tb102122** [comment]
@claell Yes correct, the only work around of now is using the client with version 3.2.x

**Comment by claell** [comment]
@tb102122 Hm, I thought that I just got it to work with 3.3.1. Are you sure you need 3.2.x?

**Comment by tb102122** [comment]
@claell No it does not work in my case.

**Comment by tb102122** [comment]
@mgallien When do you expect that the version with the bug fix can be released?

**Comment by mgallien** [comment]
@tb102122 
current plan is to finish the review and then the release should happen at the end of the month

**Comment by claell** [comment]
@mgallien I hope this is not meant seriously. I am having a really hard time to understand how such an annoying and trust destroying problem affecting many users (look at the votes on the corresponding issues for the PR) will remain unfixed for users for another month.

Nextcloud always used to be prone to bugs and stuff like this, but as a user, I'd really like to have those issues handled better.

This really makes me wonder whether aiming for companies and government agencies as target for Nextcloud is a good thing.

cc @karlitschek

**Comment by davidbaumann** [comment]
I am running NextCloud 20.0.11, connecting with the Windows 10 Client, I was able to work around the problem following way:

Install Desktop Version 3.3.0
Reboot. NextClound will not start, as the main .exe is missing.
Install again (repair installation)

Now you can log in.

**Comment by FlexW** [comment]
@davidbaumann try to install client 3.3.3. There was a bug in 3.3.0-3.3.2
