### ISSUE TITLE
Nextcloud-Client always need access granted - Ubuntu Budgie 21.04

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/desktop#3738]
Hi team,

apologize for raising that issue, but I cannot find a solution...
My client (based on official ppa) always askes for granting access via Browser.

I'm on Ubuntu Budgie 21.04.

Can anyone help, please? Thanks - Tom-

**Comment by FlexW** [comment]
Which version are you using?

**Comment by kangaroo72** [comment]
It's Version 3.3.2 (Ubuntu)

**Comment by FlexW** [comment]
Did it work in the past? Is your keychain configure properly? We had some issues with login in the latest version. With version 3.3.3 everything should be resolved. Please try that version and see if everything works again.

**Comment by kangaroo72** [comment]
![image](https://user-images.githubusercontent.com/6906390/132208687-01ae19ee-9442-4dfd-b0f5-380a8c17093d.png)

now with 3.3.3 it looks fine :-)

The partially synchronization like in Windows isn't availlable in Linux?
![image](https://user-images.githubusercontent.com/6906390/132209118-ceb61265-3825-46fa-b205-a0cae86598f3.png)

**Comment by FlexW** [comment]
What do you mean with partially sync? Virtual files? That is only available on Linux as an experimental feature.

**Comment by kangaroo72** [comment]
yes, virtual files!!

**Comment by FlexW** [comment]
You need to install an extension for your file manager application. If you use budgie I guess you use nautilus. Then you need the nautilus extension. It seems like you are on a Ubuntu based distro so you can install it with:
`sudo apt install nautilus-nextcloud`

**Comment by kangaroo72** [comment]
Ah cooooool - thx
