### ISSUE TITLE
German translation for title of file conflict window has a typo

### ISSUE THREAD

**Issue by claell** [nextcloud/desktop#3745]
Just a quick issue so it is not forgotten.

**Comment by Valdnet** [comment]
@rakekniven Can you take a look at it?

**Comment by rakekniven** [comment]
Hallo @claell ,

kannst Du bitte den String angeben bzw. einen Screenshot anfügen?

Dann wird das sofort gefixt.

**Comment by rakekniven** [comment]
Und welche Client version Du benutzt wäre noch interessant.

**Comment by rakekniven** [comment]
Ist es "Syncronisations-Konflikt"?

Gerade gefixt

**Comment by claell** [comment]
@rakekniven Vielen Dank! Hatte das als Erinnerung für mich erstellt und wollte nochmal Details nachliefern, wenn es das nächste Mal auftritt. Aber der Fehler scheint auch so gefunden worden zu sein. Aktuell kann ich gerade nicht einfach einen Konflikt produzieren, um das Fenster wieder zu sehen. Aber ich gehe davon aus, dass es genau dieser Fehler war, den du erwähnst.

**Comment by claell** [comment]
So, endlich mal wieder diese Meldung bekommen, sodass ich jetzt einen Screenshot nachreichen kann.

War tatsächlich wie vermutet dieser String.
![grafik](https://user-images.githubusercontent.com/6171135/133933673-8334e6cb-d1bb-4083-b21b-464ebfa24a85.png)

**Comment by rakekniven** [comment]
Ok, dann sollte der nächste Release das beheben. Gruß
