### ISSUE TITLE
nextcloud does not delete files

### ISSUE THREAD

**Issue by holzfelix** [nextcloud/desktop#3748]
### Expected behaviour
An important function of Nextcloud no longer seems to work in version 3.3.3. Both in the Mac and in the Windows client.

If you exclude a folder from synchronisation, it is no longer deleted from the PC but remains. This means that no memory space is released. 

Is the problem known? What could be the cause?
### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. Open synchronisation settings
2. Deselect folder
3. Click Apply
4. Folder remains on PC 

### Client configuration
Client version:
3.3.3.

Operating system:

Windows & Mac

**Comment by mgallien** [comment]
I cannot reproduce.
Can you share your logs ?
without logs we have no way to work on this

**Comment by AqujZ1K9** [comment]
Dear @mgallien I'm uploading the logfiles for @holzfelix . There pretty big tho..

the client is producing Gigabytes on logfiles..

Here are the latest of them:

https://ifinfra.s3.eu-central-1.amazonaws.com/20210908_0955_owncloud.log.0
https://ifinfra.s3.eu-central-1.amazonaws.com/20210908_1004_owncloud.log.1
