### ISSUE TITLE
Open file on desktop, not in browser

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/desktop#3768]
Collaborators will send internal links to files to other people, who then open the link.
Files will then be opened in the browser.

BUT: If the user opening the link has a Nextcloud desktop client installed, the client should grab the Safari browser link and rather open the file on the PC if possible (eg a Word file will open Mac Word, and not Collabora Word).

Would be a killer feature for true and flexible way of collaborating on files - otherwise user have to search for the local synched file after looking in the browser.

**Comment by mgallien** [comment]
Duplicate of #1321
