### ISSUE TITLE
Additional features for custom configuration during the initial setup (URL, username, etc.)

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#3769]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Tell us how the feature should work

**Comment by Pimmetje** [comment]
It would be a big plus if some silent switches can be used to pre-populate the server url & username (maybe even the password). We can argu if it is safe but in some cases it could be useful. 
When SSO is used the SSO flow should be started after first launch.
