### ISSUE TITLE
macOS version 3.3.3 Settings: Plugin for virtual files shows "suffix"

### ISSUE THREAD

**Issue by jameskimmel** [nextcloud/desktop#3774]
### Expected behaviour
Show the activated plugin or in this case something like "Plugin not installed. Go to XY to download XY".

### Actual behaviour
It shows:
"Plugin for virtual files: suffix"

### Steps to reproduce
1. Install 3.3.3 on macos
2. Go to settings, general

### Client configuration
Client version: 3.3.3

Operating system: macOS 11.5.2

OS language: German

**Comment by FlexW** [comment]
suffix is the vfs plugin for macOS. Did you enable the experimental options? I think the plugin gets loaded internally in the client even if you don't enable the experimental options. That is why it shows up in the settings. Maybe we can hide that string in the gui if the experimental options are not enabled.

**Comment by jameskimmel** [comment]
> suffix is the vfs plugin for macOS.
Ahh, now I get it :)
 
No, did not enable it in the experimental options.

> Maybe we can hide that string in the gui if the experimental options are not enabled.
Good idea!

**Comment by andyxheli** [comment]
Is there any time frame when vfs will no longer be experimental on MacOS

**Comment by andyxheli** [comment]
Sounds good! Not a problem at all completely understand. If there’s any testing you need I’d be happy to help.

Sent from my iPhone

On Oct 14, 2021, at 7:42 AM, Felix Weilbach ***@***.***> wrote:

﻿

It's already a task, but the priority is low and it will be a lot of work to implement it. The suffix plugin will probably never become stable on macOS. We want to go with the native solution on macOS (FileProvider API).

**Comment by jameskimmel** [comment]
does not show up in red any more. Closed for me.
