### ISSUE TITLE
Text strings for 2, 3, and 4

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#3776]
Add text strings for the number of items for the numbers 3, 4, and 5 in the following text strings:

https://github.com/nextcloud/desktop/blob/06f37234dc0fc33b048842102435578caec01356/src/gui/userstatusselectormodel.cpp#L417
https://github.com/nextcloud/desktop/blob/06f37234dc0fc33b048842102435578caec01356/src/gui/userstatusselectormodel.cpp#L424
https://github.com/nextcloud/desktop/blob/06f37234dc0fc33b048842102435578caec01356/src/gui/userstatusselectormodel.cpp#L431

This change is significant for various languages, e.g. in Polish it is as follows:

> 1 minuta
> 2 minut**y**
> 3 minut**y**
> 4 minut**y**
> 5 minut

**Comment by mgallien** [comment]
is it not a limitation of using `tr` ?
I guess KI18n framework from KDE's community is working fine for this (at least I know that translators of French are then able to select the correct form).
could you have a look to see how well it is working for Polish ?

**Comment by Valdnet** [comment]
@mgallien For other text strings, it is possible to translate both singular and plural.
Sample text string:

![obraz](https://user-images.githubusercontent.com/47037905/132835228-94dbc32f-e643-4f83-bfc4-53a8bef04a7c.png)

https://github.com/nextcloud/desktop/blob/06f37234dc0fc33b048842102435578caec01356/src/common/utility.cpp#L503-L506

However, for the above-mentioned strings, this is not possible. This is probably due to the code.

![obraz](https://user-images.githubusercontent.com/47037905/132835300-5464dd8c-9862-4736-ad19-9213141a9b4b.png)
![obraz](https://user-images.githubusercontent.com/47037905/132835356-89849947-c814-4a87-9946-28904cced287.png)
![obraz](https://user-images.githubusercontent.com/47037905/132835439-09ffe194-2f8e-49a6-9491-76ef9663f425.png)

**Comment by mgallien** [comment]
@Valdnet do you want to work on a patch ?
I am a bit short on the time available to do it myself in a reasonable time frame

**Comment by Valdnet** [comment]
> do you want to work on a patch ?

I'd love to, but the change probably requires more coding.

**Comment by Valdnet** [comment]
@mgallien Sample of code change:

```
        if (minutesLeft == 1) {
            return tr("%1 minute", "", minutesLeft);
        } else {
            return tr("%1 minutes", "", minutesLeft);
        }
```

Is my logic right? Do I need to improve anything else?

**Comment by mgallien** [comment]
@Valdnet yes but in this case should you not also add context to help translators ?

**Comment by Valdnet** [comment]
@mgallien Well. I will take care of this and add context for the translators.

**Comment by Valdnet** [comment]
Changes made.

@mgallien Please check if it's okay. I did not add context for the translators because they are simple text strings that do not require detailed explanation for their meanings.

**Comment by Rello** [comment]
this can not be implemented for technical reasons
