### ISSUE TITLE
Bug: checkbox 'Sync hidden files' reselected after reopening window 'Ignored  Files Editor'

### ISSUE THREAD

**Issue by Verhoeckx** [nextcloud/desktop#3782]
**Operating system**
Fedora 34 Silverblue

**Nextcloud Desktop**
version 3.3.3

**Package format**
Flatpak
  
  
**Steps to reproduce**
1. Open Nextcloud Desktop
2. Click on icon in the system tray
3. Click on Settings
4. Click on **Edit Ignored Files**
5. **Deselect** the checkbox **Sync hidden files**
6. Click on OK
7. Click again on **Edit Ignored Files**

**Result**
The checkbox  **Sync hidden file**s is checked again.

**Comment by Verhoeckx** [comment]
**File**
`/var/home/verhoeckx/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud/sync-exclude.lst`

**Content**
```
*~
~$*
.~lock.*
~*.tmp
]*.~*
]Icon\r*
].DS_Store
].ds_store
._*
]Thumbs.db
]photothumb.db
System Volume Information
.*.sw?
.*.*sw?
].TemporaryItems
].Trashes
].DocumentRevisions-V100
].Trash-*
.fseventd
.apdisk
.directory
*.part
*.filepart
*.crdownload
*.kate-swp
*.gnucash.tmp-*
.synkron.*
.sync.ffs_db
.symform
.symform-store
.fuse_hidden*
*.unison
.nfs*
My Saved Places.
\#*#
```

**Note**
I miss the expression `.*`.

**Comment by Verhoeckx** [comment]
Adding hidden directories manually does works.

**Steps**
1. Open Ignored Files Editor
2. Click on Add
3. Enter `.*`
4. Click on OK.

**File**
 /var/home/verhoeckx/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud/sync-exclude.lst

**Content**
```
*~
~$*
.~lock.*
~*.tmp
]*.~*
]Icon\r*
].DS_Store
].ds_store
._*
]Thumbs.db
]photothumb.db
System Volume Information
.*.sw?
.*.*sw?
].TemporaryItems
].Trashes
].DocumentRevisions-V100
].Trash-*
.fseventd
.apdisk
.directory
*.part
*.filepart
*.crdownload
*.kate-swp
*.gnucash.tmp-*
.synkron.*
.sync.ffs_db
.symform
.symform-store
.fuse_hidden*
*.unison
.nfs*
My Saved Places.
\#*#
.*
```

**Comment by Verhoeckx** [comment]
It's still a bug.

**Comment by Verhoeckx** [comment]
This is still a valid bug report.

**Comment by joshtrichards** [comment]
Duplicate of #1346 

Let's track there.
