### ISSUE TITLE
Nextcloud Desktop can not connect to HTTP/2 server, and also the Android client.

### ISSUE THREAD

**Issue by OrvilleQ** [nextcloud/desktop#3787]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Desktop Client connect to Server.

### Actual behaviour
Nextcloud can't connect to my Nextcloud 22.1.1 installation (deploy with offical apache docker image)

### Steps to reproduce
1. Open Nextcloud
2. Type Nextcloud Server URL
3. Error occur.

![image](https://user-images.githubusercontent.com/21377465/133082376-49fa93ea-8725-4f4f-b524-15e513353843.png)

### Client configuration
Client version: 3.3.3

Operating system: Windows 11 Pro

OS language: zh-CN

Installation path of client: C:/Program Files/Nextcloud

### Server configuration

Nextcloud version: 22.1.1

Storage backend (external storage): S3

### Logs

1. Client logfile: 
[20210913_2011_owncloud.log](https://github.com/nextcloud/desktop/files/7154162/20210913_2011_owncloud.log)

2. Web server error log:
No error.

3. Server logfile: nextcloud log (data/nextcloud.log):

PS. Same thing happend to android client but with browser my Nextcloud installation works just fine.

**Comment by FlexW** [comment]
Please translate the dialog. I can't read that language. Having said that, I guess that is a dialog that complains about invalid certificates? You probably haven't configured your server correct.

**Comment by OrvilleQ** [comment]
> Please translate the dialog. I can't read that language. Having said that, I guess that is a dialog that complains about invalid certificates? You probably haven't configured your server correct.

It says:
```
Failed to connect to the secure server address specified. How do you wish to proceed?

Select a different URL

Retry unencrypted over HTTP (insecure)

Configure client-side TLS certificate
```
As I mentioned before, It work perfect with browser and certificates are fresh new also, and I install the server with offical docker image with nginx as reverse proxy.

Here's my nginx conf file:

```conf
server {
        listen 80 proxy_protocol;
        listen 82 http2 proxy_protocol;
        server_name [Mask];

        location / {
                proxy_redirect off;
                proxy_pass http://localhost:30755;
                proxy_set_header Host $http_host;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                client_max_body_size 512m;
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        }
}
```
I use another program for SSL but the same plan always worked so I don't think is it's problem.

And I fix the [log](https://github.com/nextcloud/desktop/files/7154162/20210913_2011_owncloud.log)'s link up there. Sorry for that.

**Comment by OrvilleQ** [comment]
As I can see from the log, it seems because client got nothing from `status.php`

```
2021-09-13 22:18:28:018 [ warning nextcloud.sync.networkjob.checkserver ]:	error: status.php replied  0 ""
```

But I can normally access `status.php` within my browser.

![image](https://user-images.githubusercontent.com/21377465/133100932-b56da693-a789-46e9-aa66-0b9a69fb333e.png)

And Client works just fine with demo1.nextcloud.com

I'm really confusing now :-(

**Comment by OrvilleQ** [comment]
Oh, I see.

#1823

It is because HTTP/2.

Everything works after I add OWNCLOUD_HTTP2_ENABLED=1 to environment variable.

https://github.com/nextcloud/desktop/blob/138323b79d288b899f9d029ff2c2b2934086a39c/src/libsync/accessmanager.cpp#L81-L89

It's an issue stay for almost two years now. Someone even mentioned this bug has been fixed in Qt version 5.9.4, and you guys are using Qt 5.12.9 now. I just can't believe it.

> http2 seems to cause issues, as with our recommended server setup we don't support http2, disable it by default for now

But `http2` is opend by default in your OFFICAL DOCUMENT FOR NGINX!!! See [here].(https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=http2)

![image](https://user-images.githubusercontent.com/21377465/133105922-274b4984-e599-4f00-912e-ca5bec378def.png)

Please, uncomment those code for checking qt's or at least, make connection fall back to http/1.1. We all know that HTTP/2 connection is basiclly 100% compatible with HTTP/1.1 thanks to ALPN. I could access my webserver using curl with HTTP/1.1 without any pain.

```
#: curl -v --http2 [Mask]
* Connected to [Mask] port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
```

```
#: curl -v --http1.1 [Mask]
* Connected to [Mask] port 443 (#0)
* ALPN, offering http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
```

And I'm guessing could this be the same issue on the Android side. I could add environment variable to my PC, but I can't add them to my phone.

**Comment by OrvilleQ** [comment]
Yes, it is the same issue.

https://github.com/nextcloud/android/issues/2681

HTTP/2 support for Android client has opened for three years now. Even though we could access HTTP/2 server with HTTP/1.1 painless.

**Comment by OrvilleQ** [comment]
And client for Apple device won't have this issue.

(ー_ー)

I speechless.

**Comment by acsfer** [comment]
All my nginx servers have `http2` and client connects fine,becaus it issues a HTTP/1.1 request.

```
server {
    listen       443 ssl http2;
    listen       [::]:443 ssl http2;
    server_name
        nextcloud.exampls.com
      ;

    ssl_certificate_key      ssl/nextcloud.key;
    ssl_certificate          ssl/nextcloud.combined_crt;

    root   /srv/users/nextcloud/apps/nextcloud/public;

    access_log  /srv/users/nextcloud/log/nextcloud/nextcloud_nginx.access_ssl.log  main;
    error_log  /srv/users/nextcloud/log/nextcloud/nextcloud_nginx.error_ssl.log;

    proxy_set_header    Host              $host;
    proxy_set_header    X-Real-IP         $remote_addr;
    proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-SSL   on;
    proxy_set_header    X-Forwarded-Proto $scheme;

    include /etc/nginx-sp/vhosts.d/nextcloud.d/*.ssl_conf;
    include /etc/nginx-sp/vhosts.d/nextcloud.d/*.conf;
}
```

And a log line from the client:

`xxx.xxx.xxx - [23/Sep/2021:09:04:52 +0200] "PROPFIND /remote.php/dav/files/user/ HTTP/1.1" 207 266 "-" "Mozilla/5.0 (Windows) mirall/3.0.3stable-Win64 (build 20201029) (Nextcloud)" "-" 952 0.238 "server=127.0.0.1:81" "255" "rt=0.212" "cloud.ceped.org" "-"`

Also, please note that **nginx is not officially supported**. Read the warning + note at the top of that page.
https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html

**Comment by OrvilleQ** [comment]
After a few days of exploration, I found out it was because of my misunderstanding of h2c, h2 and alpn which cause my SSL setup will fallback http/1.1 connection to nothing when no alpn was specified.

Everything works fine now.
