### ISSUE TITLE
Main dialog's "account" menu not scrollable if main dialog is shown as normal window and height is too big

### ISSUE THREAD

**Issue by nursoda** [nextcloud/desktop#3789]
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Actual and expected behaviour
As I have many accounts set up and find it cumbersome to try to deduct information on paths containing an error from that tiny notification area window. So I added `showMainDialogAsNormalWindow=true` to `.config/Nextcloud/nextcloud.cfg` and use the "real window" mode (thanks for that!).

The issue: When I maximize the main window (or set its height to something a bit greater that half of the windows height), I can no longer scroll the account list thus being unable to add new accounts or enter settings through that menu.

<details>
<summary>Screenshot: This is the height that still works. A bit more and the menu is no longer scrollable</summary>

![grafik](https://user-images.githubusercontent.com/8425483/133125798-8b728952-1810-4cd0-8f8e-c18de8aa7c77.png)

</details>

### Client configuration
Client version: 3.3.3-git
Operating system: Arch linux

### Server configuration
Nextcloud version: 21.x and 22.x

**Comment by FlexW** [comment]
That I understand correct: The account list is scrollable until the window reaches a certain height? If it is scrollable, is it hen possible to see all accounts?

**Comment by nursoda** [comment]
Yes. Yes.

**Comment by claucambra** [comment]
Fixed with #4216 thanks for reporting!
