### ISSUE TITLE
Main dialog should respect system font and font size

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3797]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The main dialog should use the default font of the system and not some tiny font for better readability. Caption font can be 2px smaller than the normal font.

Just for the record: That might be not too easy to fix because the main dialog does currently expect the font to be that small and we may encounter layout issues.

@tobiasKaminsky @jancborchardt Maybe we can put this on the task board.

EDIT: We can use the Qml type `FontMetrics` to get the default size and then multiply it by a given factor to determine smaller fonts for subheadings for example.

**Comment by claell** [comment]
Related to #914?

**Comment by FlexW** [comment]
@claell No sure, I think the first one is about a hidipi issue. The second one is maybe also hidipi issue or that problem may be gone if we don't use a fixed font size.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky @jancborchardt Maybe we can put this on the task board.

Added for discussion 👍
Having the Desktop app more native is good, I think.
