### ISSUE TITLE
Desktop client returns "invalid response to an authenticated webdav request" on account setup/login attempt

### ISSUE THREAD

**Issue by silentbreaksec** [nextcloud/desktop#38]
I've followed the NextCloud install manual (and several others on the internet), but can't seem to get the desktop client connected to the NextCloud server. It keeps returning "There was an invalid response to an authenticated webdav request" on the credentials page. If I click "Click here to request an app password from the web interface", it opens a browser that shows the text below. 

`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"12.0.3.3","versionstring":"12.0.3","edition":"","productname":"Nextcloud"}`

I've tried creating an app password manually, but that password doesn't work either. I KNOW my password is correct. I've also tried local users (e.g. admin account), and LDAP users. Here's a screenshot of the client error. I'm currently using ownCloud, but would like to migrate off of it. 

![2017-11-14_9-31-12](https://user-images.githubusercontent.com/7194249/32791741-ee1346be-c91e-11e7-866b-2257c705a50f.jpg)

For what it's worth, the web UI works fine.

**Comment by camilasan** [comment]
Are you still having this problem? If so, could please post your logs?

**Comment by camilasan** [comment]
Did you update the server to 13 and the client to 2.3.3?

**Comment by claell** [comment]
@silentbreaksec is this still relevant with current client versions?

**Comment by camilasan** [comment]
> @silentbreaksec is this still relevant with current client versions?

I really don't think so.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
