### ISSUE TITLE
Folder with 1,2 million files not possible to sync

### ISSUE THREAD

**Issue by sla-te** [nextcloud/desktop#3800]
Description already very clear.. 

### Steps to reproduce
1. Install Nextcloud 17.0.1.1 on ubuntu 18.04.3 LTS inside HyperV VM
2. Assign 20 GB memory and 4 CPU cores
3. Manually add 1,2 million files to any users files folder via scp
4. Run occ files:scan and wait 8 hours for it to finish
5. Login to the user using the Windows client, check the folder containing the 1,2 million files, wait.

### Expected behaviour
Client dowloads all the files, server does not become instable.

### Actual behaviour
Client says "waiting" until, after a very long time, it shows:
`An error occured while opening a folder Operation canceled`
In the server when I look at htop, I can see that php-fpm: pool Nextcloud is consuming all the 20GB memory of the server and after some time finally kills the processes, all cores at 100% load.

### Server configuration

**Operating system:**
Windows 10 

**Web server:**
Hyper V VM , 4 vCores, 20GB memory

**Database:**
Postgres 10.10

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
No

**Where did you install Nextcloud from:**
[https://shop.hanssonit.se/product/nextcloud-vm-microsoft-hyper-v-500gb/](https://shop.hanssonit.se/product/nextcloud-vm-microsoft-hyper-v-500gb/)

**Signing status:**
<details>
<summary>No errors have been found.</summary>
</details>

**List of activated apps:**
<details>
<summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
  - mail
  - user_ldap
</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "SENSITIVE VALUE",
            "SENSITIVE VALUE",
            "SENSITIVE VALUE"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "https:\/\/SENSITIVE VALUE\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "0",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "simpleSignUpLink.shown": "false",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logtimezone": "Europe\/Berlin",
        "htaccess.RewriteBase": "\/",
        "maintenance": false
    }
}
</summary>
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Client**
Windows 10 client 2.6.1sstable-Win64 (build 20191105)

**Browser:**
Not applicable

**Operating system:**
Windows 10

#### Web server error log
[apache error.log](https://gist.github.com/chwba/7e87bac8b094ff4bda643b37480b5373)

#### Nextcloud log (data/nextcloud.log)
[Log](https://gist.github.com/chwba/8c014769b23b7719712a37560cc06245)

#### Browser log
<details>
<summary>Not applicable, synced with Windows client</summary>
</details>

##### Tries to increase memory limit for nextcloud
Tried with:
/etc/php/7.2/apache/ : memory_limit = -1
/etc/php/7.2/fpm/ : memory_limit = -1
/etc/php/7.2/cli/ : memory_limit = -1

And with:
/etc/php/7.2/apache/ : memory_limit = 512M
/etc/php/7.2/fpm/ : memory_limit = 256M
/etc/php/7.2/cli/ : memory_limit = -1

Same result

**Comment by dimm0** [comment]
😔

**Comment by dimm0** [comment]
🥺

**Comment by jospoortvliet** [comment]
So I see that the original request is actually for the server - not the client, so this should be there. Moreover - I'm not sure if this is still relevant. We've dealt with many of the problems mentioned (like adding indexes), and we certainly have installations with many more than 1.2 million files so this is probably resolved.

I would propose we keep this closed and if this still exists with Nextcloud 23, it can be re-created in the server repo.

Note that if you want to put a million files in one folder, be prepared to give PHP more execution time and memory than normal. (I do agree it should be possible to do this, by the way, even though I'm not sure how urgent it is to fix as you can distribute the files over sub directories as work-around).
