### ISSUE TITLE
New folders marked as "ignored". Not getting synced since upgrading from Nextcloud 3.2.4 to 3.3.3 on macOS.

### ISSUE THREAD

**Issue by CaptainBalou** [nextcloud/desktop#3806]
### Expected behaviour

New directories are synced well as before in 3.2.4.

### Actual behaviour

All new folders are marked as "ignored" and are not getting synced since upgrading from Nextcloud 3.2.4 to 3.3.3 on macOS. This happens even the ignore list is completely empty.
Note: Virtual file extension (suffix) is enabled.

### Steps to reproduce

- Create a new directory inside the synced folder structure. The sync icon will occur next to the folder name
- Wait a few seconds
- The sync icon switches to a yellow icon. Hovering above this displays "ignored".

#### Client:
3.3.3 (also tested with 3.3.1 and 3.3.2).

Operating system:
macOS Big Sur 11.6

OS language:
German

#### Server:
Nextcloud version:
20.0.12

Regards
Marco

**Comment by ShawonAshraf** [comment]
3.3.5 the bug is still there. On both macOS and Linux.

**Comment by ShawonAshraf** [comment]
3.3.6 and bug still exists.

**Comment by CaptainBalou** [comment]
It wasn't fixed yet as far as I know.

**Comment by ShawonAshraf** [comment]
It's still not fixed. When people ask for enhancements on forums people come and gatekeep bugs and tell people to report on github. But once they're on github, something as user experience breaking as this one, nobody cares.

**Comment by CaptainBalou** [comment]
Issue still existing on my end.

**Comment by CaptainBalou** [comment]
@ShawonAshraf 
> It's still not fixed. When people ask for enhancements on forums people come and gatekeep bugs and tell people to report on github. But once they're on github, something as user experience breaking as this one, nobody cares.

The developers are focusing on the most wanted things which I totally understand. Very few are voting for this bug report so it seems to somehow fly under the radar.

**Comment by CaptainBalou** [comment]
I would love to have someone looking into this. Guys, we need more up-votes to get attention. 😉

**Comment by Sanic** [comment]
@CaptainBalou Does this problem still exists for you?
I just installed 3.4.2 yesterday and creating new folders in my sync folder worked for me. The folders (and also their content) are synced. Not sure though if there is a specific setting or anything else necessary to reproduce the problem.

**Comment by CaptainBalou** [comment]
> @CaptainBalou Does this problem still exists for you? I just installed 3.4.2 yesterday and creating new folders in my sync folder worked for me. The folders (and also their content) are synced. Not sure though if there is a specific setting or anything else necessary to reproduce the problem.

Hello @Sanic . Thanks for jumping into the discussion. Are the folders which have already been synced before also synced after the upgrade? That would be a good sign for me to test it again. No, you don't have to do anything special except that I use the "virtual file extension (suffix)". Are you using this as well?

**Comment by Sanic** [comment]
Yes, there were already synced ones, but my client version was a bit older than 3.2.4 (can't remember exactly).
Regarding the suffix, i've the following settings on my side: 'Using virtual files plugin: suffix'

**Comment by CaptainBalou** [comment]
That looks so promising at the moment. I updated and the errneous behaviour seems to be gone. I observe this a few more days and report back.

**Comment by CaptainBalou** [comment]
The issue seems to be gone. Thanks for your hint.

Unfortunately I couldn't stay on that version 3.4.2 because of another issue I've open (#3629). Unfortunately this issue doesn't seem to be fixed.
