### ISSUE TITLE
Sidebar Icon on macOS Monterey (12.0.1) looks different

### ISSUE THREAD

**Issue by BJKle** [nextcloud/desktop#3809]
### Expected behaviour
After connecting to the Nextcloud server, sidebar icon should change to the Nextcloud logo in blue.

### Actual behaviour
Sidebar icon changes to a black Nextcloud logo. (Regardless of "use monochrome icons" checkbox ticked or not).

### Steps to reproduce
1. Upgrade to macOS Monterey final
2. connect to Nextcloud server, using the latest desktop app.

### Client configuration
Client version:
3.3.6 (also tested with 3.3.0 and 3.3.3).

Operating system:
macOS Monterey (12.0.1) ~~beta~~
Intel and M1

OS language:
English

### Server:
Nextcloud version:
22.1.1 and 22.2.0

![NC_sidebar_light](https://user-images.githubusercontent.com/88108046/139423880-737584fb-a47b-48a9-9232-0d090b7be62d.png)

![NC_sidebar_dark](https://user-images.githubusercontent.com/88108046/139423904-88e71e6a-9a65-4ac3-91ea-22d2c513a78b.png)

**Comment by akufuncture** [comment]
It’s happening on all three of my Macs on Monterey. Didn’t notice that on Big Sur because I was always in Dark Mode and the icons used to be black. Now it’s grayish.

**Comment by BJKle** [comment]
In Big Sur, even dark mode, the sidebar icons had the same color as the rest. Maybe Apple has changed the conditions for creating sidebar icons in Monterey.

**Comment by BJKle** [comment]
It is still there

**Comment by c4539** [comment]
This issue still exists in 3.4.1:
![image](https://user-images.githubusercontent.com/7140045/147908749-67fcc634-cb95-4fef-9287-6262dc551969.png)

**Comment by dkocher** [comment]
Duplicate for #3695.

**Comment by BJKle** [comment]
Duplicate for #3695

**Comment by fasci** [comment]
The problem disappeared for me with an update to macOS 12.3.
