### ISSUE TITLE
status icon not displaying correctly on Linux

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/desktop#3814]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The status icon should appear as it does on Windows and mac

### Actual behaviour

Instead of the status icon, I see a three dots icon: 
![grafik](https://user-images.githubusercontent.com/3313208/133990210-5180d0fe-9c62-4fa2-a805-a97abe042cb4.png)

After killing and restarting the Nextcloud client a number of times (in my experience ranging from 2 to 7), the correct icon indicating the current sync status and activity appears.

### Steps to reproduce
1. Make sure your GNOME desktop supports status notifier icons through the appropriate extention
2. Launch  the desktop client appimage
3. Watch what happens.

### Client configuration
Client version:

Operating system: Debian GNU/Linux 11 (Bullseye)

OS language: de_DE.UTF-8

Qt version used by client package (Linux only, see also Settings dialog):

Actually, not shown in the settings dialogue. I use the AppImage, so it presumably does not use the system libqt install. 

Client package (From Nextcloud or distro) (Linux only):

(AppImage, currently 3.3.3, but the problem has been around for long.)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

[debug archive created. Where can I upload it to?]

**Comment by FlexW** [comment]
I can not confirm the bug. For me the latest version (3.3.4) works fine. Do other tray icons show up? Maybe you need to use a different extension for tray icons. I use this one https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by vasyugan** [comment]
> I can not confirm the bug. For me the latest version (3.3.4) works fine. Do other tray icons show up? Maybe you need to use a different extension for tray icons. I use this one https://extensions.gnome.org/extension/615/appindicator-support/

I'll check with the latest version today. I have seen this literally for years. Would be great if it were fixed now. I a m using the [KStatusNotifier](https://extensions.gnome.org/extension/615/appindicator-support/) extension, which works fine for all other applications. Again, the pattern is that I have to kill and restart the sync client several times. Finally I get a normal Nextcloud systray icon. So it isn't that the extension somehow is incapable of displaying such icons.

**Comment by emichael** [comment]
This has been happening for over a year for me. In my case, I typically only run into the problem the first time I start my system each day. Subsequent restarts seem to work fine.

In #1977, it was speculated that https://github.com/ubuntu/gnome-shell-extension-appindicator/pull/260 would fix the issue. This was not the case. I still saw errors being thrown by the appindicator extension, so I reported https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/296. But after this was fixed, instead of the three dots the icon doesn't show up at all. If you kill nextcloud and restart, the tray icon appears as normal. There are no longer any errors being reported for gnome-shell, so at this point I'm fairly convinced it's an issue with the nextcloud client. Other applications (e.g. Slack) don't have any issues and display tray icons just fine.

**Comment by emichael** [comment]
Just in case anyone else is frustrated waiting on a fix, here's an incredibly hacky workaround.

Put this file in `~/.config/autostart/`

```
[Desktop Entry]
Type=Application
Exec=gnome-extensions disable appindicatorsupport@rgcjonas.gmail.com && gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Fix Gnome Appindicator Extension
Name=Fix Gnome Appindicator Extension
Comment[en_US]=Reload the appindicator extension on startup to fix issues with the Nextcloud client
Comment=Reload the appindicator extension on startup to fix issues with the Nextcloud client
X-GNOME-Autostart-Delay=30
```

Replace the extension name with the right one from `gnome-extensions list` if you're not using the version from the gnome plugin repo.

**Comment by emichael** [comment]
@vasyugan As soon as I disable and re-enable the extension (after Nextcloud has already started, hence the delay), the tray icon appears and everything works as normal. No idea why that fixes it, but it does in my case. I'm using the latest version of the appindicatorsupport extension.

**Comment by vasyugan** [comment]
> @vasyugan As soon as I disable and re-enable the extension (after Nextcloud has already started, hence the delay), the tray icon appears and everything works as normal. No idea why that fixes it, but it does in my case. I'm using the latest version of the appindicatorsupport extension.

Can confirm that it works for me, too! Thank you very much! How did you stumble across this fix?

**Comment by emichael** [comment]
un-stale

This is still a problem.

**Comment by viggy96** [comment]
Reloading the appindicator extension doesn't work for me. I still see the issue.
![image](https://user-images.githubusercontent.com/9837626/142807783-665909f5-0f2d-4eef-be73-19beccd58201.png)

**Comment by vasyugan** [comment]
> Reloading the appindicator extension doesn't work for me. I still see the issue. ![image](https://user-images.githubusercontent.com/9837626/142807783-665909f5-0f2d-4eef-be73-19beccd58201.png)

There seem to be two different issues. Sometimes, nextcloud starts but somehow the status icon doesn't show up, sometimes, the whole application seems to hang while starting up.

**Comment by vasyugan** [comment]
still happening, tried with both the flatpak and appimage packages.

**Comment by viggy96** [comment]
Its been fixed for me for a bit now. One of the last Nextcloud client and/or GNOME updates in Manjaro fixed it.

**Comment by major-mayer** [comment]
This is still an issue on the latest Manjaro Gnome using Nextcloud 3.15.0 :
![Image](https://github.com/user-attachments/assets/8d4d3154-02d9-4e07-a16e-91a4c1342426)

Also, I cannot confirm that enabling and disabling the AppIndicator extension brings back the original icon instead of the three dots.

Can somebody please reopen this issue and maybe prevent the bot from staling this issue? @mgallien @claucambra (sorry, i don't know how to get attention to this issue otherwise)
