### ISSUE TITLE
Windows icons broken by nextcloud - cannot remove explorer integration

### ISSUE THREAD

**Issue by rclough** [nextcloud/desktop#3818]
Hey there, I'm experiencing a multifaceted issue where I tried installing Nextcloud to do backups, but Nextcloud crashes any time it syncs. In addition, it seems to have broken a number of my windows icons, causing them to turn into blank pages.

I gave up on trying to make it work, so I uninstalled it. However, all of the Explorer integration features do not get uninstalled, so all of my icons are still covered in the nextcloud sync icon, and my broken icons remain broken, which I suspect is related. **I'm opening this issue in hopes that I can get help removing the explorer integration only.**

This bug is severely impacting my ability to use my windows installation - I cannot see the icons of many of my applications on my task bar, for example.

Things I've tried:
* Moving the Appdata folder to try get the client to not crash so I can edit settings and uncheck the nabar option
* Uninstalling
* Reinstalling nextcloud, then uninstalling
* Reinstalling with explorer integration disabled

### Expected behaviour
When I uninstall nextcloud, the explorer integration - all the "sync" icons overlaid should be removed, and "status" column shouldn't exist anymore.

### Actual behaviour
They remain.

### Steps to reproduce
1. Install Nextcloud with explorer integration
2. Maybe set up a sync so large it crashes nextcloud? Not sure if this part is needed
3. Uninstall nextcloud

### Client configuration
Client version:
3.3.3 (and prior, since I've tried uninstalling and reinstalling over the past few months, but I don't know what the prior versions were)

Operating system: Windows

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): N/A

Installation path of client: C:/Program Files/Nextcloud

### Server configuration
N/A

### Logs
No logs provided since it has more to do with the uninstalltion process, but if you want I can try and collect a log from the crash, its just a bit hard because I literally cant start and access nextcloud settings with the crashing configuration

## Addendum 

\* *Please note that anywhere I talk about "my computer"/"my x" I'm actually talking about my girlfriends computer, so you can imagine the grief I'm experiencing in having messed up her windows explorer just for trying and failing to do backups* 😓

**Comment by FlexW** [comment]
- Did you restart after the installation and de-installation?
- Have you verified that the Nextcloud installation folder (that probably is in `C:\Program Files\Nextcloud`) is empty?
- Did you remove the files that start with `._sync` in the folder you tried to synchronise?

**Comment by rclough** [comment]
> Did you restart after the installation and de-installation?

Yes

> Have you verified that the Nextcloud installation folder (that probably is in C:\Program Files\Nextcloud) is empty?

I'll check this today

> Did you remove the files that start with ._sync in the folder you tried to synchronise?

I have not, did not realize I need to look for those files, however this will be pretty problematic because I was trying to index the entire user folder (ie all files, all documents, music, etc...) I suppose nows a good time to learn power shell...

**Comment by FlexW** [comment]
> I have not, did not realize I need to look for those files, however this will be pretty problematic because I was trying to index the entire user folder (ie all files, all documents, music, etc...) I suppose nows a good time to learn power shell...

These are just three files on the root sync folder. They should be easy to find :)
