### ISSUE TITLE
Make user status selector dialog modal

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3819]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
User status selector dialog should be modal as discussed with @jancborchardt.

### Actual behaviour
User status selector dialog is not modal.

**Comment by tobiasKaminsky** [comment]
How much effort is this? If <2 wd, do it, when time permits.
