### ISSUE TITLE
$RECYCLE.BIN Windows notification appears multiple times a day when syncing whole partition

### ISSUE THREAD

**Issue by GammelSami** [nextcloud/desktop#3826]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
No notification

### Actual behaviour
Multiple times a day I get this annoying notification:

"**ℹ $RECYCLE.BIN** The file name is a reserved name on this file system."

I already tried to add $RECYCLE.BIN to the ignored files but that didn't help.

### Steps to reproduce
1. Sync entire drive (F:\ is my NVME SSD)
2. Keep adding, deleting, editing some files on the drive, I guess

### Client configuration
Client version: 3.3.3

Operating system: Windows 10 Pro 20H2

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 21.0.0

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://gist.github.com/GammelSami/17b5b60652244d46514c9fddbc9cd2ff

2. Web server error log: https://gist.github.com/GammelSami/ddd642a076cd712292d4a1e037faea83

3. Server logfile: nextcloud log (data/nextcloud.log): https://gist.github.com/GammelSami/6d05a10deed9b9c3691ba02678da16b8

**Comment by EVOTk** [comment]
Hello,
I have the same concerns. https://www.forum-nas.fr/threads/nextcloud-desktop-recycle-bin.16811/

I disabled the recycle bin on this disk, without success.
I added an exclusion filter, but also failed.

![2021-09-17 10_55_11-Window](https://user-images.githubusercontent.com/45015615/134635275-b1cc7a2e-a8c9-4ddf-a583-ffaa5346c716.png)

I'm sync entire HDD drive (E:\)

**Client version:** 3.3.3 / Windows 10
**Nextcloud version:** 22.1.1

**Comment by GitPullNow** [comment]
I'm also affected by this and I sync entire D: drive.
Getting the same notifications as EVOTk's printscreen.

Adding to the ignore list does not help to resolve these messages.
If any additional information is required to resolve this issue please let me know.

Windows 10 x64 21H2 build 19044.1645
Nextcloud Desktop Client v3.4.4.20220318

**Comment by GitPullNow** [comment]
After the last desktop client update to version 3.5.1 the $RECYCLE.BIN causes a permanent warning (yellow exclamation mark tray-icon). I've added $RECYCLE.BIN to the ignore list but this does not resolve the issue.

Deleting my $RECYCLE.BIN temporarily fixes it until next boot when the $RECYCLE.BIN is created again.

Clicking on the warning opens a "rename" dialog with red text stating "Checking renaming permissions...." as it complains now about illegal characters which I think has to do with the $ in the name. 

I've also configured the ignore to the below mentioned "//$RECYCLE.BIN" and allowed both to be deleted but this does not help. The yellow exclamation mark makes it difficult to now see when there really is an issue. It requires me to check each time to make sure its not something new.

Desktop tray
![image](https://user-images.githubusercontent.com/94388268/169594745-b5b679ee-d69d-40ac-a8a1-c1c5ac0645c7.png)

When going to settings
![image](https://user-images.githubusercontent.com/94388268/169594965-2167d874-397e-4782-9f0a-e1074212c376.png)

When clicking the warning in the desktop tray
![image](https://user-images.githubusercontent.com/94388268/169594792-b14b1723-4e48-489e-b3d1-ea5b10b25cdf.png)

Current ignore list
![image](https://user-images.githubusercontent.com/94388268/169595004-2174df98-29d5-4cc8-85dd-4aad6bc0627e.png)

**Comment by werkkrew** [comment]
I am also having this issue.

**Comment by misterloz** [comment]
Glad other people have having this issue. Seems to have occurred from 3.5 onwards. I've tried all sorts of things, including adding it to the global sync-exclude.lst file, but it is still coming up.

**Comment by GitPullNow** [comment]
I see that this has been approved as a bug and was wondering if a fix can be expected. I don't want to sound inpatient but this bug is really annoying and masks real sync problems as the ICON stays yellow all the time. The annoying part is the excessive windows notifications.

**Comment by Jessiedog** [comment]
Same issue as above using v3.5.4.  Not present when eg 3.3.1 loaded.

**Comment by mrHalfer** [comment]
I confirm, it is not possible to add to exceptions. Maybe because it's not a file, but a directory.

**Comment by GilbertBigood** [comment]
Hi. I have the same issue.

**Comment by enoch85** [comment]
Are there any plan to fix this? :see_no_evil:

**Comment by robclay** [comment]
Add me to the list of hoping for a fix!

**Comment by avmarchenko** [comment]
For folks using removable media as their local Nextcloud storage, a workaround that may be acceptable is to disable the recycle bin on this device. This can be accomplished via the recycle bin properties dialog (right click on the recycle bin icon and select properties; check the radial dial that disables the recycle bin on the removable media in question).

**Comment by lgngmx** [comment]
Hi, same issue.

**Comment by thomasnorris** [comment]
Same issue here.

**Comment by enoch85** [comment]
Hi all, 

Please stop with the "+1, add me to the list comments". It notifies all the subscribers of this issue. Intead, please add your :+1: to the original issue. It also makes it eaiser to filter and search since you actually can filter for "most :+1: reactions".

Thanks!

**Comment by mgallien** [comment]
@GammelSami and others
can you still reproduce this issue with the latest release 3.9.0 ?

**Comment by Kernald** [comment]
@mgallien It's still a problem in 3.9.0. Both the notification, the "!" status icon and the unresolved conflict for the recycle bin.

**Comment by kissgyorgy** [comment]
I can confirm. It can basically makes impossible to use a full drive as a Nextcloud sync folder.

**Comment by Niccober** [comment]
The latest update v3.9.2 solved the problem on my machine. The warning about the recycle bin is gone!

**Comment by kissgyorgy** [comment]
I think this issue can be closed, I can confirm it's working properly since v3.9.2!
