### ISSUE TITLE
Nextcloud not syncing a folder "access denied"

### ISSUE THREAD

**Issue by exilschaengelsche** [nextcloud/desktop#3834]
Hi everyone,

The nextcloud Window 10-client should sync two main folders. One is synced whereas the other folder is not synced: "Access denied." /"Zugriff verweigert". Both the Windows client and the nextcloud server are fresh installations from yesterday/today / (24-09-2021). Both folders are synced with the Mega- cloud and the Synology Drive client. Shutting down both applications did not help. I have already logged off from the Windows- client and logged in again and I had also renamed the folder, but the error still occurs. Is there a log- file somewhere?
Also, when right- clicking the unsynced folder, the Nextcloud context- menue is greyed out and thus not clickable.
What are your thoughts?

Looking forward for your help.
Cheers!

**Comment by FlexW** [comment]
You can create a debug archive when you go to the Settings Dialog then to the General tab and then click on the button "Create Debug archive...". Keep in mind that it is not supported to use multiple sync clients in the same folder. That can cause issues.
