### ISSUE TITLE
Keyring failure on Artix Linux

### ISSUE THREAD

**Issue by tim-pearce** [nextcloud/desktop#3836]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client should connect and begin syncing

### Actual behaviour
It starts up disconnected from all servers. Eventually it asks me to login through the browser. It also takes a looooong time from the setting dialog to open.

### Steps to reproduce
1. Do an upgrade of Artix Linux!

### Client configuration
Client version: 3.3.3-2 (I have also tried 3.3.0 and the Appimage and I think I also tried 3.3.4)

Operating system: Artix with kernels 5.14.6 and 5.10.68

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version: 21.0.4 (2 servers but both on same version)

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: I couldn't get that before!
[log.txt](https://github.com/nextcloud/desktop/files/7230884/log.txt)

Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

I found this in /var/log/auth.log
Sep 26 14:38:46 carl gnome-keyring-daemon[5080]: couldn't connect to dbus session bus: Cannot spawn a message bus when setuid
Sep 26 14:38:46 carl gnome-keyring-daemon[5080]: couldn't connect to dbus session bus: Cannot spawn a message bus when setuid
Sep 26 14:38:47 carl polkitd[1983]: Registered Authentication Agent for unix-session:2 (system bus name :1.78 [/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1], object path /org/gnome/PolicyKit1/AuthenticationAgent, locale en_AU.UTF-8)
Sep 26 14:38:48 carl gnome-keyring-daemon[5080]: couldn't connect to dbus session bus: Cannot spawn a message bus when setuid
Sep 26 14:38:48 carl gnome-keyring-daemon[5403]: Couldn't connect to session bus: Cannot spawn a message bus when setuid

I came across a post somewhere saying that QT5 would not support setuid - didn't say they prevent it!

**Comment by mauzil** [comment]
I have the same problem with Xfce.
When I login from lightdm, a dbus-daemon process goes to zombie

**Comment by tim-pearce** [comment]
I found the problem. The upgrade from glib2.2.68.4 to 2.70.0 causes it.
On artix (and other Arch Linux based distros)
sudo pacman -U /var/cache/pacman/pkg/glib2-2.68.4-1-x86_64.pkg.tar.zst (assuming you still have it)
On one PC I then had to go through the login process for each account again.

**Comment by mauzil** [comment]
Well done. It's work
Good job

**Comment by alanibrus** [comment]
Any other solutions on this one? 
I'm on Arch and downgrading glib2.7 to 2.68 solution worked for a while, but now seems that some other applications is also depending on that library so if I now downgrade to 2.68, I cannot even start Xfce. With 2.7, everything else works normally but on every launch of nextcloud client, it asks to re-login from browser and opening browser window takes forever.
