### ISSUE TITLE
Support direct renaming of folders

### ISSUE THREAD

**Issue by wcb33** [nextcloud/desktop#3837]
Support direct renaming of folders, according to the current performance of the client, you need to rename the files inside the folder one by one. The speed is very slow. But the renaming operation in the web interface is very fast.

**Comment by Chuanbin-Wang** [comment]
And when rename by web interface, the client need sync all subdirectory and all files. it's understanding. why not just rename the folder?

**Comment by FlexW** [comment]
Do you mean if you rename a folder with files in it, all files get synced again instead of just performing a move of the folder on the server?

**Comment by Chuanbin-Wang** [comment]
Yes. And when sync done, in the web Activity page, just see the folder rename,

**Comment by FlexW** [comment]
Thank you. Then it is a bug :)

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
