### ISSUE TITLE
Tray icon does not show pause if only one account is paused

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3843]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The tray icon should show the pause icon if even only one account is paused.

### Actual behaviour
The tray icon does not show the pause icon in this case.

### Steps to reproduce
1. Have multiple accounts configured
2. Pause one account
3. Look at the tray icon

See also: https://github.com/nextcloud/desktop/issues/2210#issuecomment-929293420

NOTE: Check other states too.

**Comment by jancborchardt** [comment]
Just tested this with 2 accounts and it is fixed, the tray icon shows the pause icon if only 1 account is paused.

The tray menu itself could be a bit improved in that manner, but that is tracked in https://github.com/nextcloud/desktop/issues/6633
