### ISSUE TITLE
Combine sharing / activity as "file detail"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3845]
Would it be possible that we combine the window for Sharing and Activity into one, with tabs? Then it would be just like on web and Android/iOS.

Clicking the "Sharing" action anywhere would always open the window with the sharing tab open, and "View activity" would open the window with the "Activity" tab open.

cc @tobiasKaminsky since it’s regarding cross-platform experience.

_Originally posted by @jancborchardt in https://github.com/nextcloud/desktop/issues/3737#issuecomment-930147428_

**Comment by tobiasKaminsky** [comment]
New file activity: 
![image](https://user-images.githubusercontent.com/5836855/135391794-3f47d90e-2948-4130-b126-3f43301b5768.png)

Sharing dialog is well known :)

If something is not clear, please discuss it with designers (maybe even with mockup), before working on it :)

**Comment by claucambra** [comment]
This will not be possible unless we rewrite the share dialog in QML (which I think we should do, as we should with the Settings dialog). This does mean it will be a lot more work though 

@tobiasKaminsky I am happy to take this task

**Comment by claucambra** [comment]
Notes from design call:

- Mockup at https://github.com/nextcloud/server/issues/26691

- Combine into File details dialog (like sidebar on web)

- Is its own dialog first, like now, but QML

- Then afterwards we can also integrate it into the tray menu, cause then you could click on the menu of activity list entries and the details can slide in
