### ISSUE TITLE
Cleanup option menu

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3846]
With new activity (#3329) we have one entry more.
![image](https://user-images.githubusercontent.com/5836855/135392090-a5474196-52f1-4c24-bded-dd4139933354.png)

With https://github.com/nextcloud/desktop/issues/3845 we can combine things again.

I suggest to shrink it to
- open in browser / edit (if file can be edited directly, e.g. txt)
- share option (show share tab, with possibility to share public or copy internal link)
  - this must then also be shown if resharing is not allowed
- file detail (which then directly shows activity)

@jancborchardt

**Comment by jancborchardt** [comment]
So actually as far as I remember, the two "Copy link" options are actually the things I mostly used in the menu. This is why I’m not sure if it’s good to remove, also regarding regression.
Also there are 2 entries for Virtual Files

I see 2 possible options here:
- **Either we simplify completely**, and in that case it might be best if we just have the "Nextcloud" entry in the right-click menu which _directly_ opens the file details window. The details window would then include the tabs for Activity/Sharing, and we’d need to add the toggle for virtual files, as well as the "Open in browser".
- **Or we say it’s fine to have this menu for quick access**, and make sure it looks nice and use separators to logically group the entries.

If we go with continuing the menu, this is how it would possibly look like with all entries (and separators).
```
Online only
Available offline
---
Open in browser (or "Edit in Nextcloud" for editable documents)
File details (or split it into "Activity" and "Sharing options" which will decide what tab to open for the modal)
---
Copy public link
Copy internal link
```

**Comment by Rello** [comment]
@tobiasKaminsky to my understanding this is obsolete as outdated? let me know if its not. then we can reopen
