### ISSUE TITLE
Query lookup server

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3847]
Query lookup search needs to be opt-in as it is now, but we should enhance the way:

Desktop it is not clearly visible how to do it
![image](https://user-images.githubusercontent.com/5836855/128337116-68534a88-00e3-4ad5-a7c9-bc26e4ecf9bf.png)

Discussed with @jancborchardt @nimisha-vijay 
![image](https://user-images.githubusercontent.com/5836855/128337195-869b0d6e-2f05-47ff-b4b5-506860d43ead.png)

- show "search globally" as last search "result"
- after click on it
  -  change "search globally" to "global search results"
  - append search results from lookup server
    - if none are found, show "no results found"

**Comment by allexzander** [comment]
@tobiasKaminsky So, do we need to have "Search globally" with a magnifying glass inside a background as the last completer list entry on the desktop, according to the second picture?

**Comment by allexzander** [comment]
Likely, this needs inheriting the **QCompleter** and overriding some of its public methods (e.g. **setPopup()**).
