### ISSUE TITLE
Enhance dll loading on Windows

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#3849]
See https://github.com/nextcloud-gmbh/h1/issues/186

**Comment by mgallien** [comment]
@tobiasKaminsky  when attaching to the nextcloud.exe from official release binaries, I do not see the dll mentioned in this report.
I will comment back on the h1 issue directly

**Comment by mgallien** [comment]
![image](https://user-images.githubusercontent.com/168967/135411738-c7b018ac-6238-4ee6-8fb0-0844355a6ca7.png)
