### ISSUE TITLE
Segmentation fault when enabling virtual filesystem in 3.3.5 (Ubuntu)

### ISSUE THREAD

**Issue by wonx** [nextcloud/desktop#3864]
### Expected behaviour
Today I tried to enable the virtual filesystem in Nextcloud my Ubuntu 20.04 system. I added the showExperimentalOptions=true in nextcloud.cfg and restarted the client. Then I clicked on "Enable virtual file support (experimental)" in the client. At that point, it immediately closes.

I don't know at what version it started happening, but it used to work in the past, and now it just closes. When launching the client from a console, I just see a "Segmentation fault"

### Steps to reproduce
1. Add showExperimentalOptions=true  to ~/.config/Nextcloud/nextcloud.cfg
2. Restart client
3. Click on "Enable virtual file support (experimental)" 

### Client configuration
Client version: Nextcloud version 3.3.5-20210930.171550.0d9a6987e-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.3 LTS, x86_64

Operating system: Ubuntu 20.04 LTS

OS language: Catalan

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): 3.3.5-20210930.171550.0d9a6987e-1.0~focal1 from https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

Installation path of client:
/usr/bin/nextcloud

### Server configuration

Nextcloud version: 

Storage backend (external storage):

### Logs

1. Client logfile: 
[nextclouddebugfile.zip](https://github.com/nextcloud/desktop/files/7273083/nextclouddebugfile.zip)

**Comment by FlexW** [comment]
That crash probably happens because the vfs plugins are not packaged correctly. Could that be the case @ivaradi (See also how we copy explicitly the vfs plugins to the correct location in the AppImage packaging process https://github.com/nextcloud/desktop/blob/087b9084452793407a5cdc72bd772db66968efb5/admin/linux/build-appimage.sh#L53)

Having said that, AppImage is the only package we official support on Linux, so I'm going to close that ticket.

@mgallien we may think about fixing the root cause of this problem since I think that is now the third ticket that we got about this problem.

**Comment by mgallien** [comment]
> That crash probably happens because the vfs plugins are not packaged correctly. Could that be the case @ivaradi (See also how we copy explicitly the vfs plugins to the correct location in the AppImage packaging process
> 
> https://github.com/nextcloud/desktop/blob/087b9084452793407a5cdc72bd772db66968efb5/admin/linux/build-appimage.sh#L53
> )
> 
> Having said that, AppImage is the only package we official support on Linux, so I'm going to close that ticket.
> 
> @mgallien we may think about fixing the root cause of this problem since I think that is now the third ticket that we got about this problem.

I have started https://github.com/nextcloud/desktop/pull/3869 but more work is needed
