### ISSUE TITLE
Virtual Files (wincfapi) crashes nextcloud desktop upon sync.

### ISSUE THREAD

**Issue by mia-cx** [nextcloud/desktop#3866]
issue still relevant in latest release of nextcloud desktop (3.3.5 (Windows)).
i hadn't had the opportunity to try the potential fix but have time to try stuff again.

_Originally posted by @mia-cx in https://github.com/nextcloud/desktop/issues/3550#issuecomment-933091311_

**Comment by FlexW** [comment]
Duplicate of  #3550.
