### ISSUE TITLE
App main dialog not visible/behind other windows on Linux Xfwm4

### ISSUE THREAD

**Issue by haarp** [nextcloud/desktop#3867]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The app's main dialog (the one that appears when clicking on the tray icon) is often not visible when another window (e.g. Firefox) is at the same location and focused. The dialog spawns behind the other window. The window manager (Xfwm4 from the Xfce project) has a focus stealing prevention mechanism which is relevant here. I've never seen this happen with any other app, so Nextcloud seems to be at fault here.

The fix is easy,  the main dialog (and only the main dialog) should spawn with the "Always on top" setting.

Until then, as a workaround, I have added this rule to my [devilspie2](https://www.gusnan.se/scite/devilspie2/) config:
```
if ( get_application_name()=="Nextcloud" ) then
	set_window_above();
end
```

### Expected behaviour
Dialog always visible

### Actual behaviour
Dialog hidden by other windows

### Steps to reproduce
1. Use Xfwm4 as window manager (tested w/ v4.16.1)
2. In Window Manager Tweaks, activate "Acctivate focus stealing prevention"
3. Maximize **and focus** a Firefox window
4. Click the Nextcloud tray icon
5. -> Nextcloud dialog invisible, behind the Firefox window
6. Click tray icon two more times
7. Dialog disappears, reappears, is visible now

### Client configuration
Client version: 3.1.3

Operating system: Gentoo Linux, Xfce4

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): Distro

Thanks!

**Comment by brtptrs** [comment]
Testing 3.4 (3.3.81) from the Ubuntu alpha ppa:
The "main dialogue" does not show at all
Clicking on the system tray shows the options as expected and selecting the different options works, except when clicking on "Open main dialog", here nothing happens.

Ubuntu 20.04 
NC 3.4.0-20211124.120120.f575cc186-1.0~focal1

**Comment by haarp** [comment]
Yes, it seems even with the Devilspie always-on-top workaround, the dialog very often remains invisible. So something else must be bugged in addition.

Curiously, tooltips are shown on the invisible dialog.

**Comment by janvlug** [comment]
This issue seems to be related to the fact that the Main window is not a regular window. This causes several issues in Linux distributions (I am using Fedora 35 with GNOME on Wayland, and the Nextcloud client Main window has not been working properly for a long time). See also:
- https://github.com/nextcloud/desktop/pull/2649#issuecomment-752961069
- https://github.com/nextcloud/desktop/issues/1977#issuecomment-892113790

**Comment by haarp** [comment]
I'm closing this as a duplicate of #4017, which has many more upvotes, even though this issue was first.
