### ISSUE TITLE
General settings button unaccessible when using many (6) accounts

### ISSUE THREAD

**Issue by GuillaumeGirardot** [nextcloud/desktop#3872]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Being able to access the general settings button on my MacOS client when using many nextcloud accounts. It could be achieved by increasing the app window size or by being able to scroll down the content, etc. ?

### Actual behaviour
I have a total of 6 accounts synchronised on my Mac. When I open the list on the MacOS client, I can see all of then but the window is not long enough to show the general settings button, and it cannot be scrolled down. I used to have 5 accounts before : the windows was just long enough to access the general settings button. Please check the screenshot below.

<img width="841" alt="Screenshot 2021-10-06 at 08 07 00" src="https://user-images.githubusercontent.com/92011295/136150782-7a5624b6-bc79-4a4c-99fd-db7babb14903.png">

### Steps to reproduce
1. Get 6 accounts on your Mac.
2. Click on the nextcloud icon on the top bar.
3. Click on the name of the first account that appears to open the window with the accounts list. There won't be enough space for the general settings button to appear.

### Client configuration
Client version: 3.3.5git (build 7627)

Operating system: MacOS BigSur 11.6

OS language: English

Laptop : MacBook Pro (Retina, 15-inch, Mid 2014)

Display : 15.4", 2880 × 1800

Display  settings : scaled to "more space" which "looks like 1920x1200" (MacOS settings...)

Qt version used by client package (Linux only, see also Settings dialog): N/A

Client package (From Nextcloud or distro) (Linux only): N/A

Installation path of client: Application folder of MacOS (default)

### Server configuration

Nextcloud version: 22.2.0.2

Storage backend (external storage): Private server at home on an Intel NUC (nextcloud.baxir.fr)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: I cannot access the general settings (which is the bug I am reporting :) ) so I cannot generate this logfile.

2. Web server error log: N/A

3. Server logfile: nextcloud log (data/nextcloud.log): N/A

Thank you for your help!

Guillaume

**Comment by GuillaumeGirardot** [comment]
EDIT : scrolling with the up/down keyboard arrows is working, but not with the trackpad/mouse.

**Comment by FlexW** [comment]
Related https://github.com/nextcloud/desktop/issues/3789

**Comment by ethancedwards8** [comment]
I can reproduce, 2 accounts.

**Comment by claucambra** [comment]
Fixed with #4216 , thanks for reporting!
