### ISSUE TITLE
Automatically Generate Password when sharing a file via link or email

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#3873]
Hello it would be nice to have the client automatically generate a secure password when sharing a file via link or email

![image](https://user-images.githubusercontent.com/59488153/136249953-2c0685a1-4618-4d8b-8394-60e81b07b308.png)

**Comment by andyxheli** [comment]
Hello, any progress on this

**Comment by AndyXheli** [comment]
Hi @mgallien @claucambra Cn we pleae reopen this issue? 

The auto password generator is not working on client 3.7.4 tested on windows once i click on share via link i get an option to set password and dose not auto generate 

Please see attached video


https://user-images.githubusercontent.com/59488153/228358252-2dda0040-ba26-413c-959d-5d56407bdbfb.mp4
