### ISSUE TITLE
Sync app for shared link

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/desktop#3877]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Would it be possible to allow someone to install the sync client in order to sync a folder for which she/he received a link?
No username, no password, this user would just copy paste the link he/she received and till this shared link is valid, he/she can sync the folder to her/his computer.

In a working environment, we often share a folder with co-workers of a project. So far, they need to go online to get and receive files and we need to notify them when we added or modified a file because they don't get the update neither any notification.

If we could invite them to install a sync app (this one with a "shared link setup option" or even better a more basic one, very few options) at the same time we give them the shared link, and they could benefit the synchronisation, that would be nice.

**Comment by tobiasKaminsky** [comment]
I had this time a while ago. Cool to see that other/you also want to have it.

**Comment by Rello** [comment]
Hello,

the feature is currently not on the roadmap as the effort is significant here. We are focusing on the integrations and sync stability.

Thank you for your suggestion
