### ISSUE TITLE
[Windows 11] Client doesn't start at all

### ISSUE THREAD

**Issue by aviallon** [nextcloud/desktop#3879]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The client should start, and ask me to connect

### Actual behaviour
Nothing happens. When looking at the Task Manager's details, I can see that it briefly appears before disappearing very soon after.

I tried launching it with a terminal to see if there was any log, but there wasn't any (`nextcloud --logdebug --logfile log.txt`)

### Steps to reproduce
1. Install Windows 11 (Pro edition, in my case)
2. Install Nextcloud
3. Reboot when asked
4. Try to start Nextcloud

### Client configuration
Client version: 3.3.5  
The bug also occurs with 3.3.4 and 3.0.3 (I tried previous versions to see if the bug applied to older versions as well).

Operating system: Windows 11

OS language: fr_FR

Installation path of client: `C:\Program Files\Nextcloud`

### Server configuration

Nextcloud version: Not relevant

### Logs

1. Client logfile:  **None, couldn't get any log!!!**

**Comment by FlexW** [comment]
Duplicate of https://github.com/nextcloud/desktop/issues/3405

**Comment by FlexW** [comment]
> Is there a Windows 11 development branch I could try?

There exists no such branch right now.

**Comment by tobiasKaminsky** [comment]
@allexzander can you look into this?

**Comment by allexzander** [comment]
@aviallon Can you check if there is "logs" folder under "C:/Users/<your-user-name>/AppData/Roaming/Nextcloud"? If it is present, kindly zip it and attach it here (or let me know if there is sensitive data in your logs so I will create a private upload folder for you).

**Comment by aviallon** [comment]
> @aviallon Can you check if there is "logs" folder under "C:/Users//AppData/Roaming/Nextcloud"? If it is present, kindly zip it and attach it here (or let me know if there is sensitive data in your logs so I will create a private upload folder for you). Even better, zip the entire "Nextcloud" folder and share it with me.
> 
> It might also be the case that the local sync folder has corrupted db, etc. You may want to try to backup the "nextcloud.cfg" file from the folder in the above section, and remove it temporarily, then, when you start the desktop client, you will need to create a sync folder connection from scratch. See if that helps to resolve the crash.
> 
> Also, is Windows 11 you are using upgraded to the latest patch?

I finally gave up and reinstalled Windows 10, where I do not have any issue. I'll give Windows 11 another chance in a few years, when Windows 10 becomes obsolete.

**Comment by Leesteak** [comment]
I was having this issue, but I managed to resolve it by moving where the local sync folder was, and also disabling the VFS.
