### ISSUE TITLE
Provide a warning when no keychain is avaialbe

### ISSUE THREAD

**Issue by Equidamoid** [nextcloud/desktop#3881]
### Expected behaviour
When logging in with `gnome-keyring` not installed/running, one of these scenarios should happen:
 - (preferred) everythng works, credentials are stored
 - a warning is shown ("can't store the credentials")

### Actual behaviour
Credentials are silently lost. Starting the client again gives "you have been logged out" and forces a manual log-in.

### Steps to reproduce
1. Start nextcloud-desktop on a system without gnome-keyring available
2. log in
3. quit
4. start nextcloud-desktop again

### Client configuration
Client version: `3.1.3`

Operating system: gentoo

OS language: irrelevant

Qt version used by client package (Linux only, see also Settings dialog): `5.15.2-r10`

Client package (From Nextcloud or distro) (Linux only): normal ebuild

Installation path of client: default

**Comment by MacsKavana** [comment]
bringing this up after ~2 years.

what's going on? why isn't there at least any warning that no keyring service is available?

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
