### ISSUE TITLE
Client 3.3.5 macOS Desktop no UI appears after installation

### ISSUE THREAD

**Issue by dpudelko** [nextcloud/desktop#3896]
### Expected behaviour
Tray icon in menu bar appears and is usable to control nextcloud.

### Actual behaviour
Unfortunately, I can no longer start or open the ui of the macOS Desktop version.

After the installation, the normal dialog for setting up nextcloud still appeared. But afterwards I had no icon in the menubar. The process itself is running, but I can't control anything.

### Steps to reproduce
MacBook Pro M1, clean install --> Setup private nextcloud --> no icon appears

### Client configuration
Client version: 3.3.5

Operating system: macOS

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications

### Logs

1. Client logfile: 

**How to access the log file without having access to the UI?**

**Comment by tacticalpacket** [comment]
Having the exact issue.  One minor difference.  I can start the application and the UI appears in the toolbar (green circle with checkmark) and will stay there until I go to click on it.  Clicking triggers it to crash and disappear generating log file.

In logs I get: 
`CGSSetSurfaceColorSpace failed with 1000`
`*** Assertion failure in void set_surface_colorspace(CGSConnectionID, CGSWindowID, CGSSurfaceID, CGColorSpaceRef _Nonnull)(), NSCGLSurface.m:118`

**Comment by Nevarro** [comment]
@tacticalpacket: I have the same problem with 3.4.0 and macOS 12.0.1. The menu bar icon appears and syncing works. But if I click on the menubar icon, it disappears and crashes.

> Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process:   exc handler [56131]

Application Specific Information:
Crashing on exception: CGSSetSurfaceColorSpace failed with 1000

**Comment by hendriks73** [comment]
Other software packages seem to face the same issue:

- [Open Broadcaster Software](https://obsproject.com/forum/threads/obs-crashing-just-after-first-window-adding-e-g-a-video-capture-device-with-exception-cgssetsurfacecolorspace.149990/)
- [beaTunes](https://www.beatunes.com/) (private bug report)

Unless people are using Apple's library in the wrong way somehow, perhaps it's worth it filing a bug report with Apple.

**Comment by hendriks73** [comment]
The person reporting the private beaTunes bug report reports that he was able to "fix" the issue by by reverting the color profile for his LG 4K display to the default, instead of a downloaded one.

**Comment by claucambra** [comment]
Hi, does this issue still occur with the latest version of the desktop client? If so, could you provide which macOS version this issue is occurring on? Thanks!

**Comment by dpudelko** [comment]
Turns out it's not a nextcloud bug.

I use BetterTouchTool, and the tool makes menu bar icons disappear.

**Comment by vinioliveira** [comment]
> or his LG

I just wanted to thank you for saving me a few hours of debugging, I was facing this issue for a while, and I couldn't figure out what's going on!  

P.S.: I was having this issue with a completely different app ❤️

**Comment by emish89** [comment]
> > or his LG
> 
> I just wanted to thank you for saving me a few hours of debugging, I was facing this issue for a while, and I couldn't figure out what's going on!
> 
> P.S.: I was having this issue with a completely different app ❤️

Me too! On LG! Thanks a lot guys

**Comment by LETIshNick** [comment]
> Me too! On LG! Thanks a lot guys

Thanks a lot.

I stumbled upon the same error trying to play QuakeSpasm-Spiked. After reverting the colour profile to the default one the error disappeared. By the way, the screen is the Gigabyte one.

I don't have enough competence for issuing a bug to the place where it should belong, maybe someone manages to do that.
