### ISSUE TITLE
Syncing single folder syncs all higher-level single files

### ISSUE THREAD

**Issue by PhoenixIV** [nextcloud/desktop#3899]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Actual behaviour
I want to sync a single folder
`hello/there`
to my desktop.

I noticed this will also sync all higher-level files with it.

```
hello/there/*  (correct)
hello/file1.txt  (unwanted)
hello/file2.txt  (unwanted)
file1.txt        (unwanted)
file2.txt        (unwanted)
```

### Expected behaviour
Only files from the chosen folder should be synced.

### Additional observations
There is no option to select / exclude files from upper levels.

### Client configuration
Client version: 3.3.5

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 21.0.4

### Logs
Please inquire for logs only when necessary. I created a debug file and found personal information in there.

**Comment by FlexW** [comment]
@PhoenixIV Try to delete your sync connection and then try to add a sub folder again as sync connection. That should work. Indeed if you have already configured folder A and inside folder A there is folder B, you can't add folder B as a separate sync target.

**Comment by PhoenixIV** [comment]
The warning message I mentioned about / already being synchronized came up after I configured only folder B inside folder A to be synchronized with the wizzard upon installation.

I now tried it the way you described: I deleted all synchronization tasks, removed all files from my PC (just to confirm its working) and set it up again from within the settings menu. Now it works as intended. Will you keep this ticket open as a reminder to maybe improve the wizard?

**Comment by PhoenixIV** [comment]
Another idea: Maybe add the possibility to integrate the sync into Windows explorer on a per-sync basis, like as a last step when adding a new folder to sync.

**Comment by PhoenixIV** [comment]
Sure, I am fine with a more condense ticket.

In Windows explorer there shows a new entry for each separate folder / sync that is added. It might be sweet to enable or disable this entry not only in general, but maybe have the possibility to choose for every sync if it should be listed in the explorer.

The entry that is added to the navigation area of the explorer is named as the full path to the folder, including folder separators, so I also thought it might be sweet to rename this to something more eye candy.
