### ISSUE TITLE
Handling Files Locking in the Desktop Client

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/desktop#3900]
When editing a file, synchronized with the server, with the local editor (ex. Gedit for text files, LibreOffice Calc for spreadsheets ...), there is no way to know if someone else is also editing the file somewhere else.

While the implemented conflict resolution policy works fine in some cases, merging the different versions of the file can be a complex and error prone manual procedure. This situation can occur often in installations with a large number of Desktop clients and users preferring local over in-browser editors.

If the following two features were implemented, the user could in principle let everyone knows that he/she is working on the file:

- show an icon on the file entry in the File Manager, like the ones shown [here](https://docs.nextcloud.com/desktop/3.3/navigating.html?highlight=nautilus#using-the-synchronization-client), that indicates that the file is being edited.
- provide a new menu entry in the Nextcloud right-click menu to lock the file  

This would give the Desktop user the same experience as the Web user with the [Temporary files lock](https://apps.nextcloud.com/apps/files_lock) app. I think it is acceptable that the user remains responsible of locking /unlocking the file instead of having an automatic check in place.

**Comment by tobiasKaminsky** [comment]
This is currently discussed in https://github.com/nextcloud-gmbh/customers/issues/643 and then I will add it to our board.

**Comment by marcotrevisan** [comment]
It would also be nice to somehow remove write permissions on the locked file until the lock itself is removed.

**Comment by marcotrevisan** [comment]
For instance in Max OS Finder there's a "lock" feature for files. Assuming it can be used by the NC client, it may come in handy for the purpose of preventing the unwanted writes. Also, Finder will show the lock icon on files.

**Comment by vagner-dias** [comment]
Someone found a code snippet with an example on how to implement this lock feature. >>>> https://github.com/nextcloud/files_lock/issues/72

**Comment by claucambra** [comment]
This is now available
