### ISSUE TITLE
Desktop client can't sync some files, says WindowsError: 5 Access denied

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/desktop#3906]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Files should synchronize between cloud and desktop client.

### Actual behaviour
Some files are not being synchronized because of this error showing:

![Capture d’écran 2021-10-19 à 12 32 54](https://user-images.githubusercontent.com/764332/137893489-7ef0cc09-09ee-4ada-9550-280bf390bd11.png)

It may happen on all sorts of files, no matter the type. Majority of them is synchronized well but I'd say about 5~10% encounters this error. Files are well shared in the organization and the user has access to them through their browser without issues. It's the local synchronization through the desktop client that is not happening.

### Steps to reproduce
1. Start sync
2. See errors coming : WindowsError : 5 Access Denied

### Client configuration
Client version: 3.3.5

Operating system: Win 10

OS language: French

### Server configuration

Nextcloud version: 20.0.13.1

Storage backend (external storage): S3

### Logs

1. Client logfile: 

You can find the zip of logs at this link 👉 https://nuage.liiib.re/s/LgJ6DDH9Wnp4s3D

Thanks for your dear help and to all NC contributors! 🤗

**Comment by FlexW** [comment]
@mgallien That looks similar to the issues you once had with one customer where the client had trouble renaming files for no reason. The logs are full of errors because of renaming not only the tmp files.

**Comment by mgallien** [comment]
@ImaCrea can you please test again with 3.4.1 and sends us back log files ?
the current link as expired and I was not able to copy them locally before

**Comment by ImaCrea** [comment]
hey @mgallien I'm sorry but not comfortable anymore sharing it since I've seen into the archive that data are *not* anonymized. I don't want risking a breach of privacy here. Thanks for understanding.

**Comment by mgallien** [comment]
> hey @mgallien I'm sorry but not comfortable anymore sharing it since I've seen into the archive that data are _not_ anonymized. I don't want risking a breach of privacy here. Thanks for understanding.

there is always the option of sending it directly to us as we have in any case strong obligations regarding confidentiality
without the logs and because we do not reproduce the error, we cannot fix it

**Comment by danir-de** [comment]
We had the same issue on an instance where virtual files were disabled, just before I found this issue.
We solved it by completely deleting the user profile and enabling virtual files while logging back in.

**Comment by joshtrichards** [comment]
Possibly related: #4894

**Comment by joshtrichards** [comment]
Possibly similar to #5473 and was remedied via #6053.

@ImaCrea Are you still experiencing this / able to reproduce this behavior in newer versions of the client?

**Comment by ImaCrea** [comment]
> Possibly similar to #5473 and was remedied via #6053.
> 
> @ImaCrea Are you still experiencing this / able to reproduce this behavior in newer versions of the client?

Hi there, sorry this was a while and I'm afraid I can't reproduce it at the moment.

**Comment by claucambra** [comment]
Hello, since the issue seems to not be reproducible I will close this issue -- please feel free to reopen if the problem reappears

**Comment by Fred-DTV** [comment]
I'm having the same issue, but I found a workaround:
My setup is a folder on a Synology NAS synced via Syncthing to a VPS running Nextcloud and then externally mounted via Local Folder
This gave me the WindowsError: 5
now I mounted the same folder directly via SMB (also in NC via external files) and it syncs without problems.

I still haven't found the cause though

UPDATE: This didn't solve it. We are still getting this error on some of our about 50 machines and it is absolutely not reproducable and driving us insane tbh.

It is always different machines, and different files that throw this error, so it feels imposssible to track this down. Also there is nothing avaluable in the logs.  at least not for me.


I would much appreciate if this issue gets reopened @claucambra

**Comment by uncovery** [comment]
I am having the same issue here. Temporary files are being created, but never properly synced. The issue is on files that were shared with me from another person. Some are from TALK, others are normal folder shares. This can be only resolved by going into the web interface and clicking on "Leave this share". It affects multiple devices that share is being used on. In other words, this is not an issue of the destination machine (apart from the operating system) but rather how nextcloud is trying to share it on the machine.

**Comment by uhhbeku** [comment]
Hello, this is closed, I know, but just because I've experienced the issue (or better a client experienced the issue) today I would like to comment on this.
Several files did not synchronise to the windows client (newest version) with windows error 5.
Changing the synchronising mode to virtual on the client, wait for synchronisation, changed back again - every file is synchronised.
(5 webservers, 2 redis, S3 primary storage, 2FA)

**Comment by thalunil** [comment]
I can also reproduce this with a current Nextcloud client, annoying indeed

**Comment by hex-m** [comment]
> Hello, since the issue seems to not be reproducible I will close this issue -- please feel free to reopen if the problem reappears

@claucambra can you please reopen?

**Comment by uncovery** [comment]
I just installed on a new computer. 100% of my images from nextcloud talk are subject to that issue.

**Comment by svenb1234** [comment]
Same here with 33.0.4. Temporary files which are never finished due to "error 5" Clicking on the item in the client's file list opens the start-page of the nextcloud instance - not very helpful. If it would at least jump to the file or give some clue on how to solve the problem - e.g. remove the temporary file and start re-syncing it.

**Comment by uncovery** [comment]
> Same here with 33.0.4. Temporary files which are never finished due to "error 5" Clicking on the item in the client's file list opens the start-page of the nextcloud instance - not very helpful. If it would at least jump to the file or give some clue on how to solve the problem - e.g. remove the temporary file and start re-syncing it.

Check if this is the same as here: https://github.com/nextcloud/desktop/issues/9885
I provided a script to fix the issue temporarily there.

**Comment by mrtomatwo** [comment]
I posted a workaround that works for me at https://github.com/nextcloud/desktop/issues/9885#issuecomment-5494043807 - maybe it helps :')
