### ISSUE TITLE
macOS client does not sync folders created locally

### ISSUE THREAD

**Issue by Aephir** [nextcloud/desktop#3909]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On macOS, if moving a file to, or creating a new file/directory in sub-directories, the files and/or directories should sync with Nextcloud.

### Actual behaviour
I see a red `x` at those directories and/or files. The only ones that do sync are the ones created/moved to the base `Nextcloud` or the first sub-direcories (e.g. `Nextcloud/Documents`). It look s a bit like #1083, but restarting the client does not (temporarily) fix it. It might be specific for moving something into folders that were present before macOS Nextcloud Client was installed (which would be everything "deeper" than e.g. `Nextcloud/Documents`).

### Steps to reproduce
1. Make a `Nextcloud` directory in your user's home dir (I had one from previous Nextcloud install).
2. Set up Nextcloud and the macOS client.
3. Sync the local files/folders to Nextcloud [NOTE: A lot of the folders wouldn't sync or show up in Client settings under "Folders to sync" until right-clicking in Finder, and choosing the `Nextcloud`->`Open in Browser`, then they showed in Client settings and showed the green checkmark in Finder (meaning "synced")].
4. Create a new file/directory in a subfolder that was initially synced from macOS to Nextcloud e.g. move a file to `Nextcloud/Documents/Something/`, as long as `Something` was created before installing the Nextcloud client.
5. Watch it not sync.

### Client configuration
Client version: 3.3.5 (macOS)

Operating system: macOS 11.6

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): NA

Client package (From Nextcloud or distro) (Linux only): NA

Installation path of client: `/Applications`

### Server configuration

Nextcloud version: 22.2.0

Storage backend (external storage): TrueNAS RAIDZ2 array (Nextcloud installed in FreeBSD Jail on TrueNAS machine)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: When choosing `Create Debug Archive`, the `logs` when unzipping is empty. I've attached the *.zip file (though unzipped, redacted a few lines from `nextcloud.cfg` and re-zipped the folder). Opening client and pressing `F12` as stated in the guide this issue guideline links to (https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files) does nothing.
[nextcloud_client.zip](https://github.com/nextcloud/desktop/files/7376168/nextcloud_client.zip)

2. Web server error log: NA

3. Server logfile: nextcloud log (data/nextcloud.log): NA, I assume (and hope, since there's sooo much sensitive information just in file/folder names;  I wouldn't even know what to search for in those 8.1 MB to find it all)

**Comment by FlexW** [comment]
Would be weird if the client has changed the permission because it shouldn't be installed as a root and therefore it shouldn't even be possible that the client changes the permissions to root. Can you reproduce the problem reliably? Otherwise, I would suggest we close the ticket and reopen it again if you have problems again. Because until now it seems like you are the only person that experienced the issue.

**Comment by Aephir** [comment]
I'll close.

I can't guarantee that some of the directories on Nextcloud storage were not created via shell before installing the macOS client (I tried moving old data between RAIDZ2 datasets, and had an error, but perhaps it created directories before throwing the error; I didn't notice). But it does sound more logically plausible. I'll re-open if I find evidence for the contrary.
