### ISSUE TITLE
Failed to get password from kwallet under window manager

### ISSUE THREAD

**Issue by tramhao** [nextcloud/desktop#3915]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
 I've installed kwalletmanager and pam-kwallet. I've also searched the current issues about kwallet but none match my case. The problem I met: I don't use sddm. When I use startplasma-wayland to login, nextcloud client can read the password ok. When I use other window managers like leftwm, nextcloud cannot read the password.

### Actual behaviour
Here is what I found in log file: 
```
2021-10-21 12:19:44:776 [ warning nextcloud.sync.credentials.webflow ]:	Error while writing password "Error calling StartServiceByName for org.freedesktop.secrets: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)"
2021-10-21 12:19:44:776 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::writePassword(const QString&, const QString&, const QString&, QKeychain::JobPrivate::Mode, const QByteArray&, QKeychain::JobPrivate*)

```

### Steps to reproduce
1. I've configured /etc/pam.d/login as below:
```
auth optional pam_kwallet5.so
session optional pam_kwallet5.so auto_start force_run
```
2. When I'm in window manager, I can open kwalletmanager, and the wallet is opened all right, and I can see the item for nextcloud in it. 
3. nextcloud client can get password from kwallet under kde, but not from window managers. It must be some configuration problem. 

Another suggestion: is it ok for nextcloud to use other authentication method like pam_gnupg? It's simpler and lighter, and no need for kde desktop installed.

### Client configuration
Client version: 
```
Nextcloud version 3.3.5git
Git revision 0d9a6987ebb0040b34451e51f54121dbd339ddf8
Using Qt 5.15.2, built against Qt 5.15.2
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1l  24 Aug 2021'
Running on Arch Linux, x86_64
```

Operating system: Arch

OS language: en_US.UTF-i

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): arch aur

Installation path of client: /usr/bin/nextcloud

### Server configuration

Nextcloud version: 22.2

Storage backend (external storage):zfs

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)
[nextcloud.log](https://github.com/nextcloud/desktop/files/7386008/nextcloud.log)

2. Web server error log:
no related error about nextcloud client.
3. Server logfile: nextcloud log (data/nextcloud.log):
no related error about nextcloud client.

**Comment by tramhao** [comment]
any suggestions?

**Comment by mike-lloyd03** [comment]
@tramhao did you ever figure this out? I'm on a very similar setup (Arch, LeftWM, kwalletmanager, pam-kwallet) and am having the same problem. The wallet automatically opens on login but Nextcloud client doesn't seem to be able to communicate with it. With Nextcloud desktop running, Kwalletmanager does not appear in the "Applications" tab.

A non-KDE alternative would be very welcome.

**Comment by tramhao** [comment]
I haven't solve it. I have to click a website login confirmation every time I start system.

**Comment by mike-lloyd03** [comment]
Hey for what it's worth, I got this working by installing `gnome-keyring` and using that instead of `kwallet`. Nextcloud now authenticates by itself on login. I was having similar problems with Mailspring and it's working now too. 

I also have this added at the end of `~/.config/leftwm/up` to start the daemon on login.

```bash
if [ -n "$DESKTOP_SESSION" ]; then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi
```
