### ISSUE TITLE
When Autoupdate fails, but download succedded.

### ISSUE THREAD

**Issue by RubenFixit** [nextcloud/desktop#3918]
![image](https://user-images.githubusercontent.com/5217851/138377563-02ebb6de-e8cf-40d5-822b-1eea8a4c0ebc.png)

Auto update fails quite frequently for me. I noticed that just the installation fails. If the auto updated already downloaded the file then I would like the `Update manually` button to open the file explorer to the path of the downloaded file, instead of opening my browser to the nextcloud download page. Then I can run the installer manually without having to re-download the installer.

Preferably, the auto-updater should just be fixed.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
