### ISSUE TITLE
NextCloud Virtual File Support missing despite options and plugin enabled

### ISSUE THREAD

**Issue by cyberpower678** [nextcloud/desktop#3926]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When using NextCloud on macOS with experimental options enabled, and when the suffix plugin is loaded, the option to folder sync with VFS should be given.

### Actual behaviour
NextCloud presumes to sync the old fashioned way without this option.

### Steps to reproduce
1. On an M1 Mac, enable experimental options
2. Add a folder sync
3. Observe the lack of an option to enable vfs

### Client configuration
Client version: 3.3.5

Operating system: MacOS Montery 12.0

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: Applications

**Comment by hemdrup** [comment]
We need it now :D

**Comment by cyberpower678** [comment]
Still broken

**Comment by cyberpower678** [comment]
Still broken
