### ISSUE TITLE
Nextcloud desktop crashes the computer on ChromeOS via crostini when trying to add a folder to sync

### ISSUE THREAD

**Issue by vhaudiquet** [nextcloud/desktop#3941]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Issue

Nextcloud desktop crashes the computer on ChromeOS via crostini when trying to add a folder to sync.
Note that the whole computer crashes, so it is hard for me to get logs.
I know that you might not support ChromeOS, and that i'm using a weird configuration : a container inside of an unsupported system running Debian 11 only because of the development channel of ChromeOS as this is still beta.
Still, i'm having this problem and i would like to fix it.
Maybe it is due to something that could happen on Debian 11 as well, but just so happens to do more on ChromeOS.

### Expected behaviour
Nextcloud client works and open dialog

### Actual behaviour
The whole chromebook crashes : screen goes black, and after 2 seconds the device restarts
Note that this does not happen all the time, and i have no idea why... I run it the same way each time.
It also happened to me every time i clicked "Chose folder" button when the dialog did show.

### Steps to reproduce
1. Put chromebook in development mode to get latest Debian 11 container, install nextcloud-desktop and open it
2. Click on user, settings
3. Click on the button to add a folder sync

### Client configuration
Client version: 3.1.1-2+deb11u1

Operating system: ChromeOS with Crostini Debian 11 (bullseye) container, on arm64

Device : Lenovo Duet, architecture arm64 (Mediatek Helio P60)

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): nextcloud-desktop

Installation path of client:

### Logs
As i said, it is hard to get logs since the whole system crashes.
I joined the logfile obtained via `nextcloud --logdebug --logfile nlog1.txt` but i think it does not contain a trace of the crash.
If someone knows how i can run nextcloud in a way that i could keep the logs (debugger ? breakpoints ? as it crashes the system, i really have no idea...) or can point me to the location of the code handling this part so that i try on my machine adding exit(0) instructions to see how far i can go and thus where it crashes, i'll gladly do it.

1. Client logfile: 
 
[nlog1.txt](https://github.com/nextcloud/desktop/files/7444111/nlog1.txt)

**Comment by mgallien** [comment]
please can you try again with latest version ?
it is currently 3.4.0 at the moment
from a quick guess that could be related to the graphical driver for which we require OpenGL support

**Comment by vhaudiquet** [comment]
The link on the nextcloud website is
`https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x86_64.AppImage`
which is a dead link, it shoud be `https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x64.AppImage`

Anyway, this AppImage seems to be for x86_64 but i'm on ARMv8 (Aarch64)
As the debian repos did not update to 3.4.0, i guess i have no choice but to compile it myself ? I did not find precompiled Aarch64/arm32 binaries....

**Comment by mgallien** [comment]
> The link on the nextcloud website is `https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x86_64.AppImage` which is a dead link, it shoud be `https://github.com/nextcloud/desktop/releases/download/v3.4.0/Nextcloud-3.4.0-x64.AppImage`

thanks
I am in the process of fixing that broken link

> Anyway, this AppImage seems to be for x86_64 but i'm on ARMv8 (Aarch64) As the debian repos did not update to 3.4.0, i guess i have no choice but to compile it myself ? I did not find precompiled Aarch64/arm32 binaries....

we only build for x86_64
I gave a quick look at flathub and they provide Aarch64
the 3.4.0 release is in the process of being published
