### ISSUE TITLE
Checksum mismatch on each startup, not on forced sync

### ISSUE THREAD

**Issue by ysalmon** [nextcloud/desktop#3942]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
On system startup, or on resuming an internet connection, the client should sync the repository with no error.

### Actual behaviour
On my laptop, each time I resume from suspend or boot up the computer or just get an internet connection back, the sync gives a checksum mismatch error for two files (always the same). Going to the main interface and forcing a sync makes the error messages go away, only for them to reappear next time.

### Steps to reproduce
1. While nextcloud client is running, do a Force sync
2. Close nextcloud client
3. Run nextcloud client again

### Client configuration
Client version: 3.3.6 (ubuntu)

Operating system: KUbuntu 20.04

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): 5.12.8

Client package (From Nextcloud or distro) (Linux only): appimage from https://nextcloud.com/install/#install-clients 

Installation path of client: file:///opt/yann/Nextcloud-3.3.6-x86_64.AppImage

### Server configuration

Nextcloud version: see log ?

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

[nc.tar.gz](https://github.com/nextcloud/desktop/files/7446242/nc.tar.gz)

Some filenames had to be redacted. Gladly, those are not the files with sync errors.

**Comment by mgallien** [comment]
sorry for the delay
we will have a look

**Comment by ysalmon** [comment]
I have to point out that this problem still happens with client 3.3.6, and, more importantly, also happens when syncing to a fresh, empty folder.

So I suspect there is in fact a problem serverside.
