### ISSUE TITLE
Wrong usage of "sleep" in osx/postinstall.sh

### ISSUE THREAD

**Issue by BJKle** [nextcloud/desktop#3949]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When running postinstall.sh, it should sleep for 10 seconds

### Actual behaviour
Error message "usage: sleep seconds"

### Steps to reproduce
1. run postinstall.sh
2.
3.

### Client configuration
Client version:

Operating system:
MacOS / Monterey

OS language:
English

Installation path of client:
/Applications

### Solution:
in admin/osx/post_install.sh.cmake
delete the s after 10
run **sleep 10** instead of **sleep 10s**

**Comment by BJKle** [comment]
Still not fixed

**Comment by BJKle** [comment]
easy to fix but nobody cares

**Comment by szaimen** [comment]
Feel free to create a PR with your fix 👍

**Comment by BJKle** [comment]
I'm not a developer. Just can open/close issues.
