### ISSUE TITLE
Do not show the sync icon if a link is inside a folder. 

### ISSUE THREAD

**Issue by albbino** [nextcloud/desktop#3950]
Its ok if links are not synchronized. 
But why do a folder shows the sync icon instead of the green check icon if inside the folder is a link. 
So you never know is the folder actualy synchronising or is a link inside

**Comment by claell** [comment]
Please provide some more details. Which OS do you use and do you use virtual files? Also, what exactly do you mean with link? A symbolic link?

**Comment by albbino** [comment]
I use Windows 10.
I mean link to other folders on the same cloud.

**Comment by claell** [comment]
Ah so server side link.

**Comment by albbino** [comment]
![image](https://user-images.githubusercontent.com/53584330/141116472-99dd9aea-e2ab-4038-9b47-3ce21d7c45ce.png)

How is it called in english. ShortCut? In german we say "Verknüpfung"

**Comment by claell** [comment]
Yes, shortcut (or symbolic link on Linux for example). Thanks, got it now.

**Comment by albbino** [comment]
Why is this closed. Are there questions?
The bug is Not fixed
