### ISSUE TITLE
Black Main Window only on SOME Windows 7 PC since Version 3.x

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/desktop#3960]
### Steps to reproduce
1. Install Desktop Client on PC (Optiplex 780)
2. Using Desktop Client 3.3.6

Hello.
Yes, we are using some Windows 7 PC. Thats ok. ;-)

**Since** the Windows Desktop Client 3.x ONLY the Main Window is only Black (Left Mouse Button) on Optiplex 780.
The Settings Window is ok and the Programm is working.

Here we have 4 Windows 7 PC with nearly same setup:
2 Optiplex 7**8**0 SFF - The Main Window is black since Client 3.x (Only Main Window)
2 Optiplex 7**9**0 SFF - Everything works fine.

**I could image that this is a issue of the grafik card, but i have found no solution since maaany month.**
**Does anybody have a hint for me or is it fixable in the Nextcloud Desktop Client?**

Thanks for any good idea
![main_window_black](https://user-images.githubusercontent.com/47995430/140987247-4647deee-6fca-4ddd-b261-ab66ada4f256.png)
.

**Comment by FlexW** [comment]
That COULD indicate an issue with the OpenGL driver. The main dialog gets rendered with the help of OpenGL, and on Windows, OpenGL is sometimes a bit buggy and we had similar issues. The wizard and settings menu get drawn without OpenGL. Do older versions show the main dialog? Up to which version was the main dialog visible? Could you verify that these versions are still working today?

**Comment by pm-pm** [comment]
Hello,
thanks for your reply.
Yes, the old 2.x Version work without a screen problems. Only 3.x Versions have a black window.
This PC is using a common Intel Chipset with related Grafik Chip. A common combination.
Of course, Driver and OS are "up to date" :-)

[Just for information](https://www.harlander.com/dell-optiplex-780-usff-mini-pc-core-2-duo-2-93ghz-4gb-250gb-intel-gma-4500-win-7-ohne-lw-gebrauchte-a-ware.html):
Chipsatz Intel Q45 Express
Grafikkarte Intel GMA 4500 (Onboard Chipset, not changeable)

**Comment by FlexW** [comment]
> Hello, thanks for your reply. Yes, the old Nextcloud Desktop 2.x Version work without a screen problem. Only Nextcloud Desktop 3.x Versions have a black window. This PC is using a common Intel Chipset with related Grafik Chip. A common combination. Of course, Driver and OS are "up to date" :-) A workaround is also very welcome.
> 
> [Just for information](https://www.harlander.com/dell-optiplex-780-usff-mini-pc-core-2-duo-2-93ghz-4gb-250gb-intel-gma-4500-win-7-ohne-lw-gebrauchte-a-ware.html): Chipsatz **Intel Q45 Express** Grafikkarte **Intel GMA 4500** (Onboard Chipset, not changeable)

Can Windows 7 be up to date? I guess it gets not updated anymore. My idea was that we updated the Qt version somewhere between 2.x and 3.x, and that the newer Qt version causes troubles on Win7. That could be the case as the newer Qt version does not support Win7 anymore.

Having said that, I guess it's very unlikely that we will work on this issue because no one of us has Win7 and we can't reproduce it. And as far as I can tell Win7 is not supported anymore. However, that means not we would not accept a pull request from you that fixes that issue.
