### ISSUE TITLE
Remove dead OAuth code

### ISSUE THREAD

**Issue by FlexW** [nextcloud/desktop#3962]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Since OAuth is not used anymore and was replaced by Login Flow V1 and V2, it would be nice to have the code removed from the desktop client.

**Comment by tobiasKaminsky** [comment]
Totally fine by me.
This can be a nice evening task to slowly remove it. Nothing time critical 👍
