### ISSUE TITLE
Search Results not clickable

### ISSUE THREAD

**Issue by jonasgarstick** [nextcloud/desktop#3965]
### Expected behaviour
Search results are clickable and lead to location of file/folder.

### Actual behaviour
No interaction possible.

### Steps to reproduce
1. Search something in the new search box of the Desktop Client
2. Try to click / interact with results

### Client configuration
Client version: 3.3.81 (macOS) = 3.4.0-rc1
Operating system: macOS 11.6.1 (Big Sur)
OS language: German

![search-results-client](https://user-images.githubusercontent.com/17829368/141324874-25c34b82-1e1b-4e85-8b32-460da246d62a.png)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by FlexW** [comment]
Is the folder available locally? Does the web browser open?
On Linux, it works as expected. On the M1 Mac, when the folder is not available locally the web browser opens for me. I couldn't test the other scenario so far.

**Comment by jonasgarstick** [comment]
> Is the folder available locally? Does the web browser open? On Linux, it works as expected. On the M1 Mac, when the folder is not available locally the web browser opens for me. I couldn't test the other scenario so far.

Folder is available locally, web browser did not open. Unfortunately I had to uninstall the RC1 client today because I also had this issue: https://github.com/nextcloud/desktop/issues/3967 and the whole behaviour of the client was kinda broken (could not quit the client anymore, clicking on the symbol with no reactions, window did not show up in the right place)

**Comment by FlexW** [comment]
Okay, I was able to reproduce it on both Mac's (Intel and M1).
