### ISSUE TITLE
Multiple Nextcloud Extensions on MacOS

### ISSUE THREAD

**Issue by pszypowicz** [nextcloud/desktop#3967]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
There should be just one **Nextcloud Extensions** process along side the **Nextcloud** process on MacOS.

### Actual behaviour
Actually over time the **Nextcloud Extensions** will get multiplied. 

As a side note, this is a native apple silicone 3.4.0rc1 release but I'm sure this also happen before on intel version. 

### Steps to reproduce
1. Run Nextcloud on MacOS
2. After a while (sometime day/days and with sleep/hibernation in between) the **Nextcloud Extensions** process will get multiplied. 
3. Open "Activity Monitor" on mac, filter the "Nextcloud" keyword and see the result

<img width="1298" alt="Zrzut ekranu 2021-11-12 o 09 35 40" src="https://user-images.githubusercontent.com/2733699/141437442-a51e247f-a321-4f9c-822b-2663b34d4834.png">

### Client configuration
Client version:
3.4.0.rc1

Operating system:
MacOS

OS language:
Polish/English

**Comment by FlexW** [comment]
I can't reproduce it. I see after the installation for a short time (1 to 2 seconds) two Nextcloud Extension processes. But I now had the client running for the whole weekend, and I still have just one Nextcloud Extensions process. I've created a pr to also compile the finder extensions for arm and x86 and made them a universal binary too. Maybe that was causing problems. If you want, I can create a test build for you to test it.

**Comment by pszypowicz** [comment]
I'm not sure either what cause it. For example today, after a weekend I had just one process for extension (as it should be).

But on friday this is how it looked like:
<img width="1303" alt="Zrzut ekranu 2021-11-12 o 14 52 28" src="https://user-images.githubusercontent.com/2733699/141773822-0374867e-8f32-4dbf-9cb5-55fcf3283c58.png">

Interestingly enough, extensions look like it is already compiled for an AS. 

If you provide a new package RC, I'm happy to test it.

**Comment by gennaios** [comment]
On 3.3.6, I checked and also have more than one Extensions process. Two. Looks to be normal:

> The system may also launch additional copies of your extension whenever an Open or Save dialog is displayed. This means that the user may have multiple copies of your extension running at once, and some may be very short lived. Therefore, it’s generally best if the extension focuses on handling the badges, contextual menus, and toolbar buttons. Place in a separate service (a Login Item or Launch Agent) any code that performs the sync, updates state, or communicates with remote data sources. This approach ensures that there is only one syncing service running at a time.

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Finder.html

**Comment by FlexW** [comment]
@gennaios Thanks for the link. Here is the build: https://cloud.nextcloud.com/s/PykMNZ98bW4CMnH

**Comment by gennaios** [comment]
@FlexW thanks for the build. I can wait until release. Do you know if the upcoming update will be built as Universal?

**Comment by FlexW** [comment]
@gennaios Very likely, if we do not find a major issue.

**Comment by pszypowicz** [comment]
@FlexW Thanks. This build seems to behave better on my mac. I'm looking forward to 3.4.0 final release :)

**Comment by zfdang** [comment]
Is it because I'm also using path finder? There are more than 10 Nextcloud extensions running

**Comment by zfdang** [comment]
<img width="500" alt="Screen Shot 2022-06-20 at 20 41 31" src="https://user-images.githubusercontent.com/1241196/174603955-9dfc2543-0c26-4bb3-8a9d-e637dab67652.png">

**Comment by telephon** [comment]
same here. What are they for?

<img width="950" alt="Screenshot 2022-08-31 at 18 43 03" src="https://user-images.githubusercontent.com/1810559/187733404-c00fb425-40f3-4dc3-905c-9caf9870c8e5.png">

**Comment by telephon** [comment]
@mgallien this continues to be an issue. In terms of energy impact, this should be addressed.
I am on macOS 12.6.2, with a new nextcloud client installed.

Could it be caused by being offline? Some years ago, there was trouble in nextcloud client whenever one wasn't online.

**Comment by mgallien** [comment]
> @mgallien this continues to be an issue. In terms of energy impact, this should be addressed. I am on macOS 12.6.2, with a new nextcloud client installed.
> 
> Could it be caused by being offline? Some years ago, there was trouble in nextcloud client whenever one wasn't online.

my idea is that we revisit this once we have a release out based on the next Qt major version that is natively supporting the newest Apple platforms and has generally much improved code
that would mean either testing the dailies once https://github.com/nextcloud/desktop/pull/4584 is merged or the major release after `3.7.0`

**Comment by faxotherapy** [comment]
Hi, sorry to re-open the case, but I've got literally tons of “Nextcloud Extensions” in the Activity Monitor. Using MacOS Monterey. I've got 371 of them and it looks like it's “spamming” my server to the point [_psad_](https://github.com/mrash/psad) banned my IP address.
