### ISSUE TITLE
Use a QQC2 theme to implement custom styling in tray window

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/desktop#3973]
In my recent PRs, I saw that the QML part is duplicating a lot of code related to QQC2.Control styling. See https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#creating-a-custom-style

**Comment by claucambra** [comment]
Strongly agree that this is something we should so.

To explain: QtQuick Controls components have default styling that, while functional, is completely discordant with the UI design we are going for in the desktop client. A great example of this is #4624 where the difference is very clear.

Our solution thus far has been to add custom styling elements to each QML component we use in the client. Unfortunately that means styling *every single element we use in the client* that is written in QML. This creates a significant amount of duplicated code and duplicated work which needs to be repeated every time a new component is written in QML, especially when we are talking about additional views, pages or windows. This is also error-prone, as for instance, we need to ensure that system-level theme switching is correctly handled by all of these components. We also need to ensure that everything remains readable across system themes.

Fortunately, QtQuick supports [custom styles](https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#creating-a-custom-style) which completely eliminates the need for doing this by hand. Custom styles apply the type of customisation we want in the desktop client to all the components in the custom style. Using a custom style will *significantly* reduce our code footprint, make it much easier to create new QML components in the future, guarantee client-wide dark mode compatibility in QML components, allow us to much more easily change our design in the future, and so on.

@tobiasKaminsky @mgallien thoughts on putting this on the board? :)

**Comment by CarlSchwan** [comment]
There is probably some boilerplate code that can be copied from https://invent.kde.org/plasma/qqc2-breeze-style

**Comment by claucambra** [comment]
Now that we are directly deferring to the standard platform themes for styling I will close this issue :)
