### ISSUE TITLE
W10 client crashing

### ISSUE THREAD

**Issue by victoroos** [nextcloud/desktop#3976]
Hi all,

Before everyone asks, I'm unable to even get a log due to nextcloud client on windows 10 crashing in less than 10 seconds while setting up first time synch.
It got some meta data, but that is it.
How can I..get you more info?
vkr
victor

**Comment by FlexW** [comment]
You can obtain logs if you go to to C:/Users/USER/Roaming/AppData/Nextcloud/Logs. Could you send them?

**Comment by victoroos** [comment]
Ah, thanks. I needed that tip! Apparently it is too big for any paste site.
[20211116_1036_owncloud.log.zip](https://github.com/nextcloud/desktop/files/7545147/20211116_1036_owncloud.log.zip)

**Comment by victoroos** [comment]
> You can obtain logs if you go to to C:/Users/USER/Roaming/AppData/Nextcloud/Logs. Could you send them?

Could you help me with the log? because I don't find a real error in them.

**Comment by allexzander** [comment]
@victoroos The only thing I was able to discover in your log is that some files/folders end with `...` (e.g. `Relatie met...`).
You might want to fix those names first via Web UI. They are not supported on Windows. This gives the error `"File names ending with a period are not supported on this file system."`.
