### ISSUE TITLE
memory leak ?

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/desktop#398]
when launched on a w10 laptop, the sync desktop app started to use around 60 Mo of memory and between 18 to 34% of cpu power. A few hours laters ( 3H ) the CPU use is unchanged, but the memory usage rise up to 720 Mo ...

**Comment by camilasan** [comment]
Possibly related: #124

**Comment by stratege1401** [comment]
Might be related, but as I am on Windows and #124 is on Linux, memory management is different, so might be better to keep them separated. 

Actually able to "replicate" on win10 pro 1803 and home 1803 on two different hardware.

**Comment by jernst** [comment]
I observe similar behavior on the Mac. Freshly started: about 34M. Before the restart: about 500M.

**Comment by stratege1401** [comment]
On w10pro 1803/17134.345 nextcloud App version  2.5.0 build 20181112 the memory leak seems to be fixed !!!

Closing.

**Comment by abiusx** [comment]
I can confirm that it went up to 24GB of RAM for me in several weeks of uptime. There's definitely a leak somewhere.

**Comment by olissongs** [comment]
2.6.4 problems are the same, so not fixed?

**Comment by arrrlaska** [comment]
Getting 700+ MiB RAM usage after 1 hour uptime.
I have 71,140 files/folders in my nextcloud folder totalling 253GB.

```
$ find nextcloud |wc
  71140  324234 6403190
$ du -sh nextcloud
253G	nextcloud
```
