### ISSUE TITLE
Link to issue template is broken

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/desktop#3981]
When trying to create a proper issue:

<img width="275" alt="grafik" src="https://user-images.githubusercontent.com/195000/142174971-09dfef35-2286-4b4a-94fa-30eb248a0c2c.png">

and visiting the link: https://github.com/nextcloud/desktop/blob/2308c9da49cbda0f137c4ac1a35cf64de9ade188/CONTRIBUTING.md

The template to create a proper issue is gone / 404: Not Found
https://raw.githubusercontent.com/nextcloud/desktop/master/.github/issue_template.md

**Comment by FlexW** [comment]
Thanks for the notice. Just open a issue and choose bug or pull request. The information in CONTRIBUTING.md is outdated.
