### ISSUE TITLE
Nextcloud Desktop on macOS logout after every reboot

### ISSUE THREAD

**Issue by samirelassal** [nextcloud/desktop#3990]
### Expected behaviour
The Nextcloud client should remain logged in after a reboot.

### Actual behaviour
After every reboot of my laptop, a Nextcloud Desktop window pops up stating that I have been logged out of my account. The login window on my browser appears automatically.  

### Steps to reproduce
1. upgrade Nextcloud client to 3.3.6 on macOS
2. reboot the computer

### Client configuration
Client version: 3.3.6 for macOS
Operating system: macOS 12.0.1

### Server configuration

Nextcloud version:
12.0.4

**Comment by StefanGebhardt** [comment]
Same problem adressed here, but unfortunately still no solution https://github.com/nextcloud/desktop/issues/3820

**Comment by dafi87** [comment]
I can confirm the problem with 3.3.6 on MacOS 12.0.1
