### ISSUE TITLE
macOS Monterey title bar icon squished when not in-focus on secondary monitors

### ISSUE THREAD

**Issue by allywilson** [nextcloud/desktop#3998]
After upgrading to macOS Monterey, the title bar changes depending on which monitor your current window is active on, it dims/greys out the icons, date, etc. on the inactive monitors. When this happens the Nextcloud icon appears to become squished.

![image](https://user-images.githubusercontent.com/470127/143247275-44669bd1-4550-46b0-a11c-3a6b9ba81691.png)

it's fine on the active monitor:
![image](https://user-images.githubusercontent.com/470127/143247408-c17e51f2-6983-42bb-8c34-95c5083f7f78.png)

Small video showing it (2nd icon from left):
https://user-images.githubusercontent.com/470127/143247597-6a030ee0-db5f-4558-b81a-9189f48c2cee.mov

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Icon should change colour/dim, not resize.

### Actual behaviour
Icon appears to resize/shrink vertically as well as being dimmed/greyed.

### Steps to reproduce
1. Install Nextcloud Desktop (using v3.3.6)
2. Attach a secondary monitor
3. Click between the active and in-active monitors and watch the icon squish.

### Client configuration
Client version: 3.3.6

Operating system: macOS 12.0.1 21A559 x86_64 

OS language: en_GB

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): 

Installation path of client: /Applications/nextcloud.app/Contents/MacOS/Nextcloud

**Comment by BJKle** [comment]
@allywilson I assume you are running it on a Mac with a Silicon Processor.
This is a duplicate of #3549, #2584 and #3752.
It will disappear, with a native M1 build.
You can use the Release Candidate or just wait for the final 3.4.0 Release.

**Comment by allywilson** [comment]
Nope, Core i9

**Comment by BJKle** [comment]
I don't have Intel anymore. But why don't you give the RC a try?

**Comment by allywilson** [comment]
Yep, working now with the RC. Thank you!
