### ISSUE TITLE
l10n: Change real ugly string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#4004]
https://github.com/nextcloud/desktop/blob/e2f1854b1e08ec3d80287ac21171d0737a6783d4/src/libsync/bulkpropagatorjob.cpp#L627

Remove leading "; " from string.

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#pl/client/341486758

**Comment by claucambra** [comment]
Hi @rakekniven since your change was merged I will close this PR, thank you for your contribution!
