### ISSUE TITLE
Click action in status bar on GNOME

### ISSUE THREAD

**Issue by winkelnp** [nextcloud/desktop#4005]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Single click on status bar icon opens menu, fitting to style of GNOME top bar menus (used to work fine)

### Actual behaviour
Small main page window opens at random location on screen

### Steps to reproduce
1. enable "AppIndicator and KStatusNotifierItem Support" GNOME shell extension
2. Open nextcloud app and keep running in background
3. Click on sync icon in top bar

### Client configuration
Client version: 1:3.3.6-1

Operating system: Manjaro GNOME

OS language: English UK

Qt version used by client package (Linux only, see also Settings dialog): qt5

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: N/A

### Server configuration

Nextcloud version: using TAB.digital cloud provider

Storage backend (external storage): N/A

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: N/A (I think, I can upload if needed)
 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log: N/A

3. Server logfile: nextcloud log (data/nextcloud.log): N/A

**Comment by janvlug** [comment]
See also #3867.

**Comment by winkelnp** [comment]
The issue seems to have resolved itself upon upgrading to version `3.4.0`.
clicking on the status menu icon now shows a system-integrated menu, as it did before.

Thanks for your help and prompt action!

**Comment by RomeroVerde** [comment]
This issue is still there in Version 3.4
https://github.com/nextcloud/desktop/issues/4069
