### ISSUE TITLE
Debug dump: No obfuscation at all, users who submit a report here are required to divulge private information

### ISSUE THREAD

**Issue by Moini** [nextcloud/desktop#4018]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

* The Nextcloud desktop client should clean out all potentially sensitive data from the debug zip file contents
* The Nextcloud desktop client should warn about which data is contained in the dump
* (Additionally: file extension should be zip automatically, but there isn't any)

### Actual behaviour

* The debug log / databases contain sensitive data such as email addresses, nextcloud user names, private server addresses, local disk paths (which include local user names), something called oc_sessionPassphrase, file and folder names in the nextcloud, file checksums, a user's online times, file modification times, ... basically everything except the files themselves.
* No visible effort has been made to obscure any of the sensitive data
* Nextcloud team **requires** that such a dump is included in any reports about desktop client misbehavior in their issue template:
  > desktop client logs are a hard requirement for bug reports because we don't know how to do magic here :)

To be honest, I'm shocked. Nextcloud boasts itself of respecting and improving their users' privacy, and then this? 
As a temporary fix, the requirement should be removed from the issue template ASAP.  
As a near-term fix, the user data should be cleaned before saving as a debug dump that is supposed to be posted into a public place.

### Steps to reproduce

1. Right-click on desktop client icon
2. Select 'Settings'
3. Select 'General' in top right corner
4. Click on 'Create Debug Archive ...'
5. Inspect resulting file

### Client configuration
Any

### Server configuration
Any

**Comment by joshtrichards** [comment]
Duplicate of #3189 + #3190

Let's consolidate there.

**Comment by Moini** [comment]
2 years old, and this was the first verbal reaction. Let's hope it doesn't take another two.
