### ISSUE TITLE
[Bug]: Set user stauts dialog glitches

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#4021]
First and most importantly the version 3.4.0 works great and the global search + sync status are awesome!

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Dialog is placed correct everytime and not only the first time you open it.

### Actual behaviour
The Set user status dialog is places a bit strange on my Windows machine. Also the smilies are a bit small and pixelated.

![image](https://user-images.githubusercontent.com/1869584/144263323-861eb863-b0bd-46f8-a22a-6008ca35d561.png)

The smiley slector empty state should say sth. like 'Your most selected smileys will be shown here...'

![image](https://user-images.githubusercontent.com/1869584/144264298-7eff9057-4907-43b7-9b01-a1b49b9b80e5.png)

The border should stay here

![image](https://user-images.githubusercontent.com/1869584/144580438-800ee10c-69ff-4d5f-bdf0-b1bccdf6812f.png)

### Steps to reproduce
1. Set user status (dialog is placed center of screen)
2. Close the dialog
3. Open it again (dialog is placed center of its parent dialog)

### Client configuration
Client version: 3.4.0

Operating system: Windows 10

OS language: EN

### Server configuration

Nextcloud version: 22

Related #3819

**Comment by mgallien** [comment]
> The highlight squares and the empty "Recents" tab should be addressed by both #4628 and #4624
> 
> The smiley faces unfortunately are a result of Windows' native fonts having very... unique emojis. To me, the only sensible solution to this seems to be to ship a custom font with the client (should we @jancborchardt @mgallien ?)

I would prefer not to ship fonts but rely on the platform to get native integration

**Comment by claucambra** [comment]
Not much we can do about Windows 10's horrible emojis then :(

**Comment by claucambra** [comment]
I will close this issue, thanks @splitt3r for opening
