### ISSUE TITLE
Nextcloud 3.4.0 crash when click on the menu item on macOS

### ISSUE THREAD

**Issue by kpatzwald** [nextcloud/desktop#4024]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Click on the menu item should open the desktop app.

### Actual behaviour
The App crash.

### Steps to reproduce
1. Click on the app icon in the menu
2. The icon disappear from the menu.

### Client configuration
Client version:
3.4.0

Operating system:
macOS 10.15.7

OS language: Geman

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:  /Applications/Nextcloud.app/   

### Server configuration

Nextcloud version: 22.2.3

Storage backend (external storage): SSD

### Logs

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

[Nextcloud_2021-12-02-092956_MyBook.log](https://github.com/nextcloud/desktop/files/7640595/Nextcloud_2021-12-02-092956_MyBook.log)

**Comment by michi7801** [comment]
Same issue here. I have a fresh installed Nextcloud Server 23 and a fresh installed Client 3.4. It worked fine until I configured the first sync. A few seconds later it crashed and it is not working since then.

**Comment by ilpssun** [comment]
Same here.  Crashlog attached.  Upgrading from 3.3.6 → 3.4.0 the issue appeared, downgrading to 3.3.6 again solved it as a workaround.
[Nextcloud_3.4.0_crashlog.txt](https://github.com/nextcloud/desktop/files/7644578/Nextcloud_3.4.0_crashlog.txt)

**Comment by frake65** [comment]
For me the downgrade did not help. After re-installing 3.3.6 over 3.4.0 the  issue described here still appears.

**Comment by kpatzwald** [comment]
> For me the downgrade did not help. After re-installing 3.3.6 over 3.4.0 the issue described here still appears.

Try to uninstall the new version first and than install the old one.

**Comment by ilpssun** [comment]
That is what I did after the original 3.3.6 installer did not overwrite the newer 3.4.0 😀. Should have been more specific in my answer.

**Comment by ilpssun** [comment]
For me, this bug was fixed in 3.4.1.  The client is working fine now after the upgrade from 3.3.6 to 3.4.1.
