### ISSUE TITLE
Sync icons in mac folder (Virtual files)

### ISSUE THREAD

**Issue by jesusdeveloper** [nextcloud/desktop#4028]
## Feature description

I have used the search engine but I have not found this request.
Nextcloud mac client version: 3.4.0
I am using the experimental virtual files option for mac. With version 3.4 it seems to work quite well.
I see that an essential and very useful feature is necessary.
When we go to the Finder to any used nextcloud folder with virtual files, it is unknown if the folder:
- It is ALWAYS available locally.
- It is available locally.
- It is only in the cloud (in this case the files have the extension ".nextcloud".

CURRENTLY

Right now Finder (mac file explorer) only shows green badge icons / update / error / ignored.
Icons should be added for the cases described above:
- It is ALWAYS available locally.
- It is available locally.
- It is only in the cloud (in this case the files have the extension ".nextcloud".

Dropbox has them for example, These are the missing icons (but with dropbox):
![allsynced](
![](https://i.postimg.cc/904W3fr9/Captura-de-pantalla-2021-12-02-a-las-20-37-46.png)

All the best!

**Comment by jesusdeveloper** [comment]
Please can someone change this topic as "bug" tag for me?

Thanks

**Comment by xavi-b** [comment]
Facing the same issue

**Comment by claucambra** [comment]
Hi, going forward we will not be continuing work on the current experimental VFS for macOS. We are instead pursuing virtual files support through FileProvider. You can keep track of this in the following issue: #1337
