### ISSUE TITLE
Client no longer localised

### ISSUE THREAD

**Issue by Mejans** [nextcloud/desktop#4034]
Hello,
this is what I am experimenting where is used to work.

### Expected behaviour
The main menus and items are translated in Occitan

### Actual behaviour
All the software is in English

### Steps to reproduce
1.Install Nexcloud client in 3.4 in Ubuntu
2.Open it

### Client configuration
Version 3.4.0 (Ubuntu)

Operating system: Ubuntu Focal up to date

OS language: Occitan

Qt version used by client package (Linux only, see also Settings dialog): ubuntu-5.4.0-91-generic

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client:

**Comment by splitt3r** [comment]
Could be related to https://github.com/nextcloud/desktop/pull/4022

**Comment by igor-cali** [comment]
Same with Italian language

**Comment by MegaV0lt** [comment]
Same here with Linux Mint 20.2 German. NC is only shown in English

**Comment by Mejans** [comment]
How comes such a feature is not tested before release?

**Comment by ajoana** [comment]
Same with German on current Mint Mate 20.3. and main dialog doesn't open either - see #4069

**Comment by MegaV0lt** [comment]
Bug also with 3.4.1 on Linux Mint
Feels like alpha sotfware
