### ISSUE TITLE
Nextcloud desktop tray icon does not change when account offline

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/desktop#4036]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When the connection to the account is offline, the tray icon should indicate that

### Actual behaviour
The tray icons remains a green checkmark and files are no longer synced without telling the user

### Steps to reproduce
1. Make the account go offline (password change triggered it for me)
2. observe the icon

### Client configuration
Client version: 3.4.0 and earlier

Operating system:
Windows 10
MacOS mojave

OS language:
Nederlands (Dutch)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
Default

### Server configuration

Nextcloud version:
22.2.3

Storage backend (external storage):
None

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
None given that the client is offline

**Comment by gvansanden** [comment]
Just to be clear, the bug is not that the client needs to be reconnected after a password change on the server, the problem is that the tray icon does not change to notify the user to reconnect

**Comment by allexzander** [comment]
@gvansanden Changing the account password does not disconnect the desktop client from the server. There is an 'apppasword' that is still valid for the Desktop Client. Can you try revoking the 'apppasword' by going into `settings/user/security` on your server, and choosing "Revoke" on the corresponding device?

**Comment by gvansanden** [comment]
That is strange indeed.  There are about 50 users on this instance and when their AD passwords had to be changed, they all disconnected.

Both on Windows 10 and MacOS



-----Original message-----

**Comment by gvansanden** [comment]
Sorry for the delay.  I did test this further with both FreeIPA and AD.  When the user password expires and he has to change it, the Desktop client disconnects and stays that way unit the user explicitly logs in again AND goed through the web base flow...

**Comment by gvansanden** [comment]
The problem persists, regardless of LDAP or AD used but consists of two issues
- If your password is changed in LDAP/AD, your account is logged out despite the app password
- The client does not correctly indicate that issue

**Comment by gvansanden** [comment]
Still there
