### ISSUE TITLE
Can not find ocsynclib.h and OCSYNC_EXPORT 's define position

### ISSUE THREAD

**Issue by duqingnian** [nextcloud/desktop#4041]
I am sorry, but whereis the ocsynclib.h file? and where is the position define OCSYNC_EXPORT ?

**Comment by allexzander** [comment]
> I am sorry, but whereis the ocsynclib.h file? and where is the position define OCSYNC_EXPORT ?

@duqingnian Please check CMake documentation https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html. The header you are interested in, is generated by CMake and is put into build output folder.
