### ISSUE TITLE
Local network syncronisation to save server bandwidth

### ISSUE THREAD

**Issue by T0nio** [nextcloud/desktop#4042]
Hello,

I'm using Nextcloud client to sync my file between my Nextcloud account and all my devices (smartphone, desktop and laptop). I'm often on the same local network (my home LAN), and I feel it would be a good bandwidth optimization if it was possible to sync directly the files between my devices without downloading everything from server.

Concrete use case:
- I download a new video on my desktop computer (1GB)
- It's uploaded to my Nextcloud account
- It's sync on my laptop
- It's sync on my smartphone
Result: I have downloaded 2GB over the Internet, where it would be nice to have this sync done only on my LAN (faster, less carbon footprint, ...)

I feel it's not an easy feature, but it seems very interesting to me (and more powerful if it would work on shared files / folders: in an organization for instance.

Sorry if I'm not very clear, I can add more info if needed,

Thank you,

**Comment by maxxer** [comment]
#2010

**Comment by T0nio** [comment]
Oh I didn't find it, thanks !
