### ISSUE TITLE
First run design improvements

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/desktop#4052]
@jancborchardt and I did a review of the first run experience of the desktop clients on Linux and Windows 

* [x] Issue related to wording: <https://github.com/nextcloud/desktop/issues/3693>

# Sign up with provider: 
* [ ] When signing up, there isn't feedback when you click on "Log in" and hence you click it again, which results in an "Invalid token" error and you have to go to the web.Some feedback while clicking on "Log in" would be nice.

# While setting up folders:
* [x] "Skip folder config" can go to the right of "Back"
* [x] Local folder folder path ("Nextcloud") looks like an action button, maybe show the full file path (eg /home/nimisha/Nextcloud) or ellipsize if it is too long (eg /home/.../Nextcloud)

# After setting up 
* [x] As soon as you create your account and link folder the main dialogue opens at a seemingly random place on the screen, it should always open wherever it normally opens for each platform 

# Issues with AppImage
* [ ] When using the AppImage, indicator icons are not showing
* [ ] On Windows, indicator icons in the file manager only show up after restart – and not communicated?
* [ ] On Linux, they do not work at all using the AppImage, you need to
  * Use the PPA [https://launchpad.net/\\\~nextcloud-devs/+archive/ubuntu/client](https://launchpad.net/%5C\~nextcloud-devs/+archive/ubuntu/client)
  * Install the "nextcloud-desktop" package there (*not* nextcloud-client)
  * Additionally install "nextcloud-client-nautilus" (and "python-nautilus"?)
  * Then restart Nautilus

**Comment by claucambra** [comment]
A few comments from me:

> * [ ]  Issue related to wording: [Rephrase login dialog as most users do not own/control the server #3693](https://github.com/nextcloud/desktop/issues/3693)

There is now an open PR for this :)

> # Sign up with provider:
> * [ ]  When signing up, there isn't feedback when you click on "Log in" and hence you click it again, which results in an "Invalid token" error and you have to go to the web.Some feedback while clicking on "Log in" would be nice.

I'm not sure what you mean here, is the the normal log in button on the wizard? Or are we talking about some other button? A screenshot or video would be awesome

> # After setting up
> * [ ]  As soon as you create your account and link folder the main dialogue opens at a seemingly random place on the screen, it should always open wherever it normally opens for each platform

For technical reasons this is, at the moment, not fixable on Linux platforms (this should not be an issue on Windows or macOS). The only working way we have of positioning the main tray dialog on Linux is by positioning the dialog relative to where the cursor is. The only real workaround here is to hardcode the position of the dialog when showing it after configuring an account, or to just not show the main dialog at all.

> # Issues with AppImage
> * [ ]  When using the AppImage, indicator icons are not showing

Not sure if this used to be the case, at least now it works as long as the file browser extension is installed

> * [ ]  On Linux, they do not work at all using the AppImage, you need to
>   
>   * Use the PPA [https://launchpad.net/\~nextcloud-devs/+archive/ubuntu/client](https://launchpad.net/%5C~nextcloud-devs/+archive/ubuntu/client)
>   * Install the "nextcloud-desktop" package there (_not_ nextcloud-client)
>   * Additionally install "nextcloud-client-nautilus" (and "python-nautilus"?)
>   * Then restart Nautilus

What would a solution to this look like? Maybe a guide to setting up the client for new users?

**Comment by jancborchardt** [comment]
Regarding the ones I can comment on:

> There is no Back button here (at least not anymore)

We should keep a "Cancel" button on the bottom left though. Otherwise if you notice at this step you authed to the wrong server, it's unclear how to start the setup newly.
If "Cancel" is clicked, we can go back to the server address input field step.

> The only real workaround here is to hardcode the position of the dialog when showing it after configuring an account, or to just not show the main dialog at all.

I'd say we should definitely show it so people know and see what is happening. Is it possible to center it on the screen?

> Maybe a guide to setting up the client for new users?

Can't the package have recommended optional dependencies which are installed if available?

**Comment by claucambra** [comment]
> Regarding the ones I can comment on:
> 
> > There is no Back button here (at least not anymore)
> 
> We should keep a "Cancel" button on the bottom left though. Otherwise if you notice at this step you authed to the wrong server, it's unclear how to start the setup newly. If "Cancel" is clicked, we can go back to the server address input field step.
> 
> > The only real workaround here is to hardcode the position of the dialog when showing it after configuring an account, or to just not show the main dialog at all.

Okay, will add.

> I'd say we should definitely show it so people know and see what is happening. Is it possible to center it on the screen?

Yeah, that can be done :)

> > Maybe a guide to setting up the client for new users?
> 
> Can't the package have recommended optional dependencies which are installed if available?

This is something we can suggest to packagers, though we have no direct control over it. It will ultimately be up to distributions/package maintainers

**Comment by claucambra** [comment]
@jancborchardt @nimishavijay Are we ok with closing this now? :)

**Comment by jancborchardt** [comment]
Good for me, yes. :) @nimishavijay?

We should probably do a separate installation experience review as well, but focused on Windows and macOS as it's our biggest user base.

**Comment by claucambra** [comment]
Okay, I will close now then -- feel free to ping me when you do your review and I will start working on that :)
