### ISSUE TITLE
3.4: Ubuntu client doesn't show Account button to add new accounts

### ISSUE THREAD

**Issue by k00ni** [nextcloud/desktop#4056]
### Expected behaviour
To have a button which allows me to add new accounts. Wasn't there an "account" button on the [right side](https://docs.nextcloud.com/desktop/3.4/navigating.html#adding-new-accounts)?

### Actual behaviour
No Account button or anything. I can't find a way to add new accounts. 

![Bildschirmfoto von 2021-12-09 09-00-06](https://user-images.githubusercontent.com/381727/145357340-de5904f3-6aa7-45ac-b814-2759a4b443c3.png)

### Steps to reproduce
1. Use Nextcloud 3.4
2. Open main window

### Client configuration
Client version: 3.4
Operating system: Ubuntu 20.04.3

Client logfile: https://gist.github.com/k00ni/5797938a8943a6ce65639fd4de260f8a

*Debug archive contained other files, but I couldn't open them because invalid user rights?!*

**Comment by allexzander** [comment]
![image](https://user-images.githubusercontent.com/12224014/145396526-8d1ab471-7bd3-48d7-8dda-bfc26ffd8986.png)

**Comment by k00ni** [comment]
![Bildschirmfoto von 2021-12-09 14-18-30](https://user-images.githubusercontent.com/381727/145403786-ef82edd8-5256-4288-91e8-5218f8e130f5.png)

When clicking "Open main menu" nothing happens currently.

**Comment by allexzander** [comment]
@k00ni Please create a separate issue about it if there is not one already. As a workaround, you can add a new account into **nextcloud.cfg** file in the app data directory (should be under ~/.config/Nextcloud, but, if it is not there, just locate that .cfg file). In that file you can already find configuration options for one user, you can then duplicate lines, just change the account name, folder path, and, index of the account (from 0 to N). The temporary workaround, if the tray dialog can not be displayed.

Which version of Ubuntu? Is it GNOME or something else? Does it work fine with 3.6 Desktop Client?

**Comment by k00ni** [comment]
Thank you for getting back to me. I will try to reinstall NC first, but make a new issue if it doesn't work again.

> Which version of Ubuntu? Is it GNOME or something else? Does it work fine with 3.6 Desktop Client?

Ubuntu 20.04.3, Gnome 3.36.8. Didn't try it with 3.6, only 3.4 is provided through sources and PPA.

**Comment by k00ni** [comment]
Btw. since I posted my issue here, I get weird Github notifications, like https://github.com/nextcloud/desktop/actions/runs/1562495831

**Comment by allexzander** [comment]
> Thank you for getting back to me. I will try to reinstall NC first, but make a new issue if it doesn't work again.
> 
> > Which version of Ubuntu? Is it GNOME or something else? Does it work fine with 3.6 Desktop Client?
> 
> Ubuntu 20.04.3, Gnome 3.36.8. Didn't try it with 3.6, only 3.4 is provided through sources and PPA.

Ahh, sorry mean 3.3.6 - previous version.

**Comment by allexzander** [comment]
> Btw. since I posted my issue here, I get weird Github notifications, like https://github.com/nextcloud/desktop/actions/runs/1562495831

Try to unsubscribe from whatever is not related to you
