### ISSUE TITLE
Nextcloud displays itself as 'owncloud'

### ISSUE THREAD

**Issue by Polynomendivision** [nextcloud/desktop#406]
Not really an issue since it's still working fine - but I think you should know it.

## Problem:
Nextcloud calls itself "Owncloud" on the notification bars on the locked Ubuntu 18.04 screen.

## How to reproduce:
Lock your screen (via Strg+Alt+L)  and watch out for the notifications on this locked screen. Nextcloud notifications are entitled with "Owncloud".

## System:
Ubuntu 18.04 with the Nextcloudclient v2.3.3 (german language setting)

## Does it hurt?
No. Just something I would like you to know, cause I think this is a bit awkward.

**Comment by camilasan** [comment]
This is a duplicate of #28 and it is already solved ;)
