### ISSUE TITLE
Better integration with Files Lock app

### ISSUE THREAD

**Issue by solracsf** [nextcloud/desktop#4060]
Whole app/lock feature does NOT work correctly with desktop client (v3.4.0) and the files/lock app: https://github.com/nextcloud/files_lock

**Example:** if someone locks a file, file can be deleted on desktop without any notice/warning. The file will be deleted and, even after resynchronization, it remains deleted (you can only find a record in "Activity log" stating "423 Locked" error) and is not restored. And the worst thing is that, when this file is unlocked, desktop client even push this "deleting order" to the server and therefore delete file on the server (!!).

Considering the order for deletion was made in time when **the file should be protected by the lock feature** this is very strange / unwanted / confusing and at this moment practically useless feature.

More details at https://github.com/nextcloud/files_lock/issues/27

**Comment by Derkades** [comment]
See also https://github.com/nextcloud/desktop/issues/3900

**Comment by pmarini-nc** [comment]
This issue shouldn't be closed

**Comment by marcotrevisan** [comment]
Ping

**Comment by torefloo** [comment]
hello, is the file locking feature active?

**Comment by torefloo** [comment]
There is an excel file in the folder, how can I make it open as read-only in the second person who opens it when another person opens it.

but I want to be able to do it via nextcloud windows app using microsoft office.

**Comment by solracsf** [comment]
This is not possible ATM.

**Comment by torefloo** [comment]
so does nextcloud make an update about it?

**Comment by vagner-dias** [comment]
V 3.10 has this request fully implemented
