### ISSUE TITLE
Error transferring server replied: Not Acceptable

### ISSUE THREAD

**Issue by Tron74** [nextcloud/desktop#407]
Hello, 

I install Nexcloud on my Rasperry PI
In the web (only https port are open) every think are ok.

In windows and android clients I recieve this message:

Error: trasfering https://cloud.example.com:443/status.php - server replied: HTTP/1.1 400

I I try to open on broswser: https://cloud.example.com:443/status.php 

I recieve:
{"error": "Trusted domain error.", "code": 15}

**Comment by camilasan** [comment]
I believe you should create an issue on the server :-) or ask for help in the forums (help.nextcloud.com).

**Comment by rullzer** [comment]
Yes this is a server problem. You need to make sure your trusted domain array in config.php is filled properly. See config.sample.php on your server for more info.
