### ISSUE TITLE
MacOs Client freezing (Sabre\DAV\Exception)

### ISSUE THREAD

**Issue by bendschs** [nextcloud/desktop#4077]
Desktop Client Interface on Mac OS is freezing (spinning wheel) while trying to sync with the following error message on server side:

`Sabre\DAV\Exception: Unknown error while seeking content`

Expanding the log shows:

```
/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/apps/dav/lib/BulkUpload/MultipartRequestParser.php - line 129:

OCA\DAV\BulkUpload\MultipartRequestParser->isAt()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/apps/dav/lib/BulkUpload/BulkUploadPlugin.php - line 69:

OCA\DAV\BulkUpload\MultipartRequestParser->isAtLastBoundary()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

OCA\DAV\BulkUpload\BulkUploadPlugin->httpPost()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

Sabre\DAV\Server->emit()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

Sabre\DAV\Server->invokeMethod()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

Sabre\DAV\Server->start()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/apps/dav/lib/Server.php - line 339:

Sabre\DAV\Server->exec()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/share/CACHEDEV1_DATA/.qpkg/NextCloud80/nextcloud/remote.php - line 166:

require_once("/share/CACH ... p")
```
this happens on 3.3.6 and 3.40. I am on MacOS Catalina and Nextcloud 23.

**Comment by bendschs** [comment]
Update: unchecked "sync hidden files" in file ignore settings and now everything is working again.

**Comment by bendschs** [comment]
Update: Problem is back even after unchecking "sync hidden files"

**Comment by allexzander** [comment]
> Update: unchecked "sync hidden files" in file ignore settings and now everything is working again.

Where is that setting?

**Comment by timbrd** [comment]
@bendschs Is your Mac using an Apple Silicon or an Intel chip? The native M1 desktop client (3.4.0 and 3.4.1) is freezing on my machine after syncing for a few minutes, version 3.3.6 (last Intel only build) is working without problems.

I cannot find those error messages on my server though.

**Comment by bendschs** [comment]
intel
upgraded to 3.4.1 (from 3.3.6) and the problem is back.
for my it freezes almost immediately after startup, very annoying ....

**Comment by bendschs** [comment]
after deactivating the sync of hidden files once again (apparently that was reset during the latest update) 3.4.1 works just fine for me
.

**Comment by bendschs** [comment]
i was always very happy with nextcloud, but this  one really sucks!
