### ISSUE TITLE
Files automatically receive the Hidden attribute in Windows Explorer

### ISSUE THREAD

**Issue by vanDariu** [nextcloud/desktop#4085]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Open Windows Explorer where one should find the Nextcloud folder with all the (virtual) files on the server

### Actual behaviour
The files in the Nextcloud folder are automatically hidden (as in the file attribute in windows) except .owncloudsync.log which is visible. Everything can be seen only after checking the "see hidden files" option in the menu. Also, creating a new folder or file makes them automatically hidden.

### Steps to reproduce
1. I recently reinstalled my server and all my clients and this worked flawlessly until now. The files are normally visible on the server and on the android client. Hope I gave enough information.
2.
3.

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:
[__nextcloud_client_buildinfo.txt](https://github.com/nextcloud/desktop/files/7720735/__nextcloud_client_buildinfo.txt)

[__nextcloud_client_parameters.txt](https://github.com/nextcloud/desktop/files/7720736/__nextcloud_client_parameters.txt)

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by godario** [comment]
Hi! I just noticed that also my Nextcloud is affected by this problem. Since, at least for me, with this bug NC is unusable, I tried to update the client to the last daily build ([Nextcloud-3.3.81.20211116-daily-Win64-x64.msi](https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-3.3.81.20211116-daily-Win64-x64.msi)) and the issue seems fixed. Can you try it too? Thanks.

**Comment by vanDariu** [comment]
YES! It seems to work just fine! Thank you!
