### ISSUE TITLE
Year not correct when setting default expiration date

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4086]
- set default expiration date in admin/settings (to e.g.365, might happen also with lower values e.g. 100)
- share a file from Desktop
- see that date within sharing option on Desktop is not correct

**Comment by tobiasKaminsky** [comment]
Only reproducible in 3.3.6.

**Comment by allexzander** [comment]
@tobiasKaminsky Can we close this? Or, is backport needed first?

**Comment by tobiasKaminsky** [comment]
Closing, as it is in https://github.com/nextcloud/desktop/pull/4088
