### ISSUE TITLE
Cannot use Gnome system proxy setting with client 2.3.2

### ISSUE THREAD

**Issue by liamdennehy** [nextcloud/desktop#41]
Steps to reproduce:
1. Enable proxy in Gnome settings (e.g. my.proxy:8080)
2. Nextcloud client 2.3.2 complains "No connection to Nextcloud at https://my.server. Host my.server not found"
3. Click on the link "https://my.server" in the nextcloud client
4. Confirm host is easily reachable with default browser and Gnome proxy settings
5. Manually enter proxy details in "Network" page of client
6. Nextcloud client can now operate normally through the proxy

**Comment by camilasan** [comment]
@liamdennehy did you try 2.3.3?

**Comment by dtuecks** [comment]
@camilasan What info do you need? As you can see I'm using 2.3.3. So the problem seems to affect 2.3.3, too.

**Comment by Dennis14e** [comment]
I have the same problem (Ubuntu 18.04).
Maybe it has something to do with this:
https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1730672

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? There were fixes related to proxy settings in recent releases. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients). 

if you still have this problem, please re-open the issue.

Thanks!
