### ISSUE TITLE
Nextcloud desktop exited unexpectedly

### ISSUE THREAD

**Issue by book-s** [nextcloud/desktop#4104]
错误应用程序名称: nextcloud.exe，版本: 3.3.6.25940，时间戳: 0x617a888f
错误模块名称: nextcloud_csync.dll，版本: 0.0.0.0，时间戳: 0x617a8443
异常代码: 0xc0000005
错误偏移量: 0x000000000001a100
错误进程 ID: 0xa3c
错误应用程序启动时间: 0x01d7f6d2912cba41
错误应用程序路径: C:\Program Files\Nextcloud\nextcloud.exe
错误模块路径: C:\Program Files\Nextcloud\nextcloud_csync.dll
报告 ID: 1f40c1e4-89cb-4526-ad64-036496ef34e9
错误程序包全名: 

Bad application name: nextcloud Exe, version: 3.3 6.25940, timestamp: 0x617a888f

Error module name: nextcloud_ csync. DLL, version: 0.0.0 0.0, timestamp: 0x617a8443

Exception code: 0xc00000005

Error offset: 0x000000000001a100

Error process ID: 0xa3c

Error: application startup time: 0x01d7f6d2912cba41

Error application path: C: \ program files \ nextcloud \ nextcloud exe

Error module path: C: \ program files \ nextcloud \ nextcloud_ csync. dll

Report ID: 1f40c1e4-89cb-4526-ad64-036496ef34e9

Error package full name:

Bad application name: nextcloud Exe, version: 3.3 6.25940, timestamp: 0x617a888f

Error module name: nextcloud_ csync. DLL, version: 0.0.0 0.0, timestamp: 0x617a8443

Exception code: 0xc00000005

Error offset: 0x000000000001a100

Error process ID: 0xa3c

Error: application startup time: 0x01d7f6d2912cba41

Error application path: C: \ program files \ nextcloud \ nextcloud exe

Error module path: C: \ program files \ nextcloud \ nextcloud_ csync. dll

Report ID: 1f40c1e4-89cb-4526-ad64-036496ef34e9

Error package full name:

**Comment by allexzander** [comment]
@book-s There is no way for us to investigate the problem without more details (logs, repro steps, etc.). Have you tried removing the "Nextcloud" folder from "C/Users/<YOUR-USER-NAME>/AppData/Roaming/"? Also, be sure to try the latest 3.4.1 version https://nextcloud.com/install/#install-clients
