### ISSUE TITLE
Problem with avatars

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/desktop#4105]
Hello,
Since the update to version 22.2.3 of Nextcloud I have a problem with my account avatars.
That is, they appear when the user is logged in to their account but when another user clicks on the [icon](https://s.jordand.fr/cZ6msR569D.png) it just sees the default avatar and not the account avatar:

Example: The Administrator account
Once connected: [Screen](https://s.jordand.fr/RYLDrHSeEP.png)
On the contact icon from another administrator account: [Screen](https://s.jordand.fr/GAVBDioScC.png)

Information:
I use PHP 8.0 and NGINX in WEBSERVER

I specify that I only have this problem on 2 accounts and when creating a new one, there is no such problem.

**Comment by mgallien** [comment]
@JordanDIG thanks for the report
Can you confirm this is happening with the desktop client ?
I cannot tell from your screenshots if it is about the desktop client user interface or the web one.

**Comment by JordanDIG** [comment]
> thanks for the report
> Can you confirm this is happening with the desktop client ?
> I cannot tell from your screenshots if it is about the desktop client user interface or the web one.

This appears on the nextcloud instance, I don't have this problem on the client, the avatar is loaded correctly.

**Comment by JordanDIG** [comment]
The problem is still there :/
I am in version 23.0.0
