### ISSUE TITLE
exFAT and enforced VFS

### ISSUE THREAD

**Issue by Emporea** [nextcloud/desktop#4108]
I have not upgraded to 3.4.1 yet, nor have I enabled VFS, because I am not able to.
#4078 suggests as descripted in the changelog that it will enforce VFS.

My synced folder is on an exFAT filesystem which doesn't appear to be available for VFS in the Nextcloud Desktop client.

What would happen if I upgrade to 3.4.1?

**Comment by allexzander** [comment]
WNF
