### ISSUE TITLE
Selective Sync Does not Remove Folders

### ISSUE THREAD

**Issue by Id3aFly** [nextcloud/desktop#4109]
### Expected behaviour
Unchecking a folder from the items in the selective sync list should remove the folder also in the explorer.

### Actual behaviour
The folder remains available and also the green sync icon is shown.
![grafik](https://user-images.githubusercontent.com/5712180/147208219-9066eedf-649f-45eb-ad24-3fe9e2945f6f.png)
![grafik](https://user-images.githubusercontent.com/5712180/147208299-1854bcc9-3690-40c5-bd5b-d3ee3cdd68d6.png)

### Steps to reproduce
1. Sync some folders.
2. Uncheck a folder from selective sync. Wait for "changed file scan" has finished. 
3. -> The folder is still available.

### Client configuration
Client version: 3.4.1
Operating system: Win 11
OS language: German
Installation path of client: Default (C:\Program Files\Nextcloud)

### Server configuration
Nextcloud version:
NextcloudPi with:
![grafik](https://user-images.githubusercontent.com/5712180/147209251-deface06-86e0-4626-a71c-dc3c6843cca1.png)

I will provide logs, if required. Are logs anonymized? Or do they contain sensitive information?

**Comment by allexzander** [comment]
@Id3aFly I couldn't reproduce it on the latest 3.4.1. Have you clicked the "Apply" button after unchecking the folder? It does disappear for me when I do so.

**Comment by Id3aFly** [comment]
Yes, I did.

**Comment by andriusr** [comment]
Having the same problem also on MacOS (Mojave 10.14), client version 3.4.1. Selecting/unselecting file folder seems to do not have any effect. Unselected folders stays on local disk, while selected anew folders does not appear.

**Comment by Id3aFly** [comment]
Good to see I am not the only one having these problems.

**Comment by romixch** [comment]
I have the same issue on Manjaro Linux with Nextcloud Client 3.4.2 and latest Server version 23.0.0. Can I help by revealing some Logfiles?
I want to save some space on my notebook. Folders stay on my machine when I uncheck them to exclude it from syncing. When I delete them locally and enable sync again it gets even deleted on the server.

**Comment by romixch** [comment]
This helped me to fix it for my machine:
Uncheck the parent folder (like "Fotos" in the example above).
Apply settings and wait for sync.
Then check all the sub folders you want to sync.
Apply settings again.

**Comment by PaoloVIP** [comment]
The same for me. Unchecked folder on client, doesn't remove local dir/files. The romixch trick won't works for me.
Nextcloud Hub II (23.0.3) - Nextcloud client 3.2.3 (Ubuntu)
