### ISSUE TITLE
Synchronisation is unreliable, missing files, not retrying

### ISSUE THREAD

**Issue by ygoe** [nextcloud/desktop#411]
I resumed my computer this morning from sleep and after a while I got messages about some new files being downloaded but others not. I should check my log window. That window just said that some files were not downloaded. The "not synchronised" view is empty.

I tried forcing a sync. I tried pausing and resuming the synchronisation. I restarted the Nextcloud application. Those missing files will not be downloaded.

I have no more information about this other than it's some current version. I'm probably not using this anymore and look for something else. This happens too often. It's not of great use to me if I need to manually check and redo everything.

Windows 10, x64, Nextcloud Desktop app has no version info, Server 13 (no more details available).

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by ygoe** [comment]
I stopped using the file sharing of Nextcloud some time ago, and after upgrading from v13 to v20, I'll try to stop using the calendar as well. The whole product is getting uglier but no better. Still no push notifications for Talk chat messages, so we need something else for team communication.
