### ISSUE TITLE
No longer possible to disable sync icons

### ISSUE THREAD

**Issue by albgus** [nextcloud/desktop#4112]
### Expected behaviour
It used to be an option to decide whether or not to display the sync status icon in explorer for every file. This appears to have been removed recently (version 3.4?)

### Actual behaviour
All clients which get updated to the latest version get the setting reset and starts displaying status icons everywhere. There appear to be no options to control this behaviour.

... and all relatives having the nextcloud client installed asking questions about what these little green checkmarks everywhere is :)

### Client configuration
Operating system: Windows 10

OS language: Swedish

Client version: 3.4.2

**Comment by allexzander** [comment]
@albgus We did not remove this option. It is enabled by default and it's been like this for a while. One needs to manually disable it as on the screenshot 
![image](https://user-images.githubusercontent.com/12224014/147468939-d8da2486-f15e-4eba-8799-5d2bcb610f37.png)

**Comment by albgus** [comment]
@allexzander That option has not been available when updating the package for quite a long while. Don't get me wrong, I think that the old process was a terrible user experience, asking the user to click next 10 times as soon as there was an update.

It seems to me that the problem here is that the updater doesn't consider the previously selected install option and instead just sets the defaults as soon as a new update is installed.

**Comment by q2apro** [comment]
Actually posted here: https://github.com/nextcloud/desktop/issues/180

But this thread seems more recent, so again:

---

⚠️ Please reopen this. There should be an option to not display the checkmark.

Actually there is a problem with Nextcloud and Windows Explorer. 

When opening Explorer, Nextcloud goes over ALL folders in the left sidebar (folder pane) and sets green checkmarks on each of them. If you have more than 50 folders there and a normal PC, you notice how slow the Explorer gets.

There *must* be an option so Nextcloud does not touch the folder pane, in other words, does not put its green checkmark there.

Please reopen!

<br>

PS: I got a new highend PC, and still, I notice a lag when opening a certain folder in Windows Explorer.

**Comment by dwheeler** [comment]
After landing here from google and finding no solution I thought I would post one here:
For windows, the icons are controlled via registry entries under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers`
[Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) from microsoft is a quick way to edit these and other windows extensions.
Under the "Explorer" tab you should find individual entries for each of the icons, you can disable the ones you do not wish to see
![image](https://github.com/nextcloud/desktop/assets/295991/0ead3bff-17a0-49b4-92f2-3ed1487a0850)
Re0enabling them if you choose to later involves moving the registry entires back from the autoruns disabled folder
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers\AutorunsDisabled`

**Comment by gessel** [comment]
Just a note for anyone searching from Linux for a solution to managing the icons.  If you're using Nemo and the sync state icons have become oppressively large, there is an easy option for disabling them entirely: unselect the SyncStateExtension_Nextcloud+NemoPython Nemo extension.

<img width="797" height="422" alt="Image" src="https://github.com/user-attachments/assets/f56c1364-b6a8-4108-94d5-a98d3486c413" />
