### ISSUE TITLE
Desktop client v3.4.1 won't run on macOS 10.12

### ISSUE THREAD

**Issue by sryze** [nextcloud/desktop#4114]
On the Nextcloud download page it says "macOS 10.12+" but it doesn't seem to work on 10.12.6. When I launch the app I get this error:

You can’t use this version of the application “Nextcloud.app” with this version of macOS.

You have macOS 10.12.6. The application requires macOS 10.13 or later.

Please return support for macOS 10.12 or update the webpage to avoid confusion.

![Screen Shot 2021-12-27 at 13 21 08](https://user-images.githubusercontent.com/4525736/147446003-ca081dc5-e14e-4085-a3fe-42b4fc80ccae.png)

![Screen Shot 2021-12-27 at 13 21 36](https://user-images.githubusercontent.com/4525736/147446052-c173a344-e2be-4f77-a117-5c41c8f93bde.png)

**Comment by rakekniven** [comment]
Had this troube as well with the same version as the issue reporter.

Installed v3.3.6 again.

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/nextcloud.com/pull/1619
