### ISSUE TITLE
Nextcloud Desktop Client deletes downloaded files instead of syncing

### ISSUE THREAD

**Issue by Alex98234** [nextcloud/desktop#4126]
### Expected behaviour
Nextcloud Desktop Client syncs a folder where a game download is occuring (GOG.com). Client should detect when files are locked and sync them when they are not locked anymore.

### Actual behaviour
Client detects that files are locked (because they are still downloading, I assume). When they are not locked, client displays syncing a file ([415MB "setup_digital_deluxe_content_270b_(20256).exe" in this example](https://i.imgur.com/BQjv8e3.png)) and finishes.
When I try to execute/open the file, Windows explorers gives an error, stating that the item is not present. F5 reveals that the file is gone.
(In this instance, this only occurs to one .exe file out of 3, some .bin files with 4GB filesize get synced correctly.)

All I find in the logfile is the following, multiple times:

`2022-01-01 00:52:19:161 [ info nextcloud.gui.activity C:\Users\sysadmin\AppData\Local\Temp\2\windows-8634\client-building\desktop\src\gui\tray\activitylistmodel.cpp:423 ]:	Activity/Notification/Error successfully dismissed:  "Games/BattleTech - Digital Deluxe Edition v270b (20256)/setup_digital_deluxe_content_270b_(20256).exe"`

I had similar "mysterious" disappeared files and folders of various files a few months ago but wasn't able to reproduce them. In this specific case, I was able to reproduce it multiple times.
The disappeared .exe file is nowhere to be found, neither in Windows recycle bin or in Nextcloud's 'deleted files' section.
**So yes, this is a bug that made me lose data.**

### Steps to reproduce
1. Download the game "BATTLETECH - Digital Deluxe Edition" from GOG.com into a Nextcloud synced folder, I suppose?

### Client configuration
Client version: 3.4.1
Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 22.2.2.0

Storage backend (external storage): Nextcloudpi on a raspberry pi 4, storage is a btrfs RAID of three hard drives. (No errors or any warnings here)

### Logs

Client logfile: https://gist.github.com/Alex98234/38e13794718d415c515fe26c603fc8a6

**Comment by claell** [comment]
Just to clarify as it took me some time to understand: You are downloading files on your computer and the Client deletes the files on your Computer. So they don't seem to have ever actually gotten uploaded to the cloud, probably (which would explain why they don't show up there under deleted files).

**Comment by Alex98234** [comment]
Yes. While the files are downloading, they are locked by the GOG.com downloader. When they are finished downloading, the nextcloud client detects that the lock is gone and started the described behavior.

I don't know if the client application is actually uploading (it _does_ display a notification and a filesize, screenshot linked in my report), but the file gets deleted.

Eventually my workaround was to download this game to a Download folder that is not synced by the Nextcloud client application. After the download was finished, I copied it to the intended "Games" folder and the Nextcloud client decided to actually synchronize instead of deletion.

**Comment by claell** [comment]
Alright.

Another workaround would likely have been to disable the Nextcloud client until the download was finished. But that is also only a workaround.
