### ISSUE TITLE
Virtual filesystem causes file change after every single save+sync

### ISSUE THREAD

**Issue by detoxhby** [nextcloud/desktop#4139]
### Expected behaviour
Just like with normally synced folders, with virtual filesystem after saving+syncing a file it shouldn't change again immediatelly.

### Actual behaviour
After saving a file (for example a text in Notepad++ or an XLS in Excel), when the sync runs in the client the same file changes (in some way, cannot determine as it is a virtual file - size, date, didn't change seemingly) and the refereced softwares notifies the user that someone else modified the file and it should be reloaded after the window has been brought back to focus (for example: minimized or put in the background earlier).

This absolutely kills the productivity as you cannot work in even a text file but in az excel table it drops the in-progress data if reloaded.
Also, it confuses the avarage user who cannot react to this problem and generates infinite questions to IT.

We have investigated this problem on different systems and were able to reproduce it. Switching back to normal sync eliminates this problem but also invalidates the point of using virtual filesystem of not syncing multi-hundred GB data down just because of working on a few files.

### Steps to reproduce
1. Add virtual filesystem sync folder, sync out, green check
2. Modify a text file from that folder in Notepad++
3. Change the content, save the file and minimize the window
4. Wait for sync to run
5. Bring back focus on the editor program
6. "File has changed" notification appears to reload the content

### Client configuration
Client version: 3.4.1
Operating system: Windows 10 21H1
Installation path of client: default installation

### Server configuration
Nextcloud version: 22.2.3

**Comment by claell** [comment]
Might be related to #3456 (especially the observations made in the comments there)

**Comment by donaldsycamore** [comment]
QOwnNotes is affected by this too.  I see that Nextcloud is truncating file timestamps -- running this in msys on Windows 11 I see:

donald@GIGABYTE-AERO MSYS /c/users/donald/nextcloud/test
$ while [ 1 ] ; do date |tee testfile; cat testfile; for i in `seq 1 10` ; do ls -l --time-style=full-iso testfile;sleep 1;done; done
Wed, Jan 26, 2022 10:47:27 PM
Wed, Jan 26, 2022 10:47:27 PM
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.491779500 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.491779500 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.491779500 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.491779500 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.000000000 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.000000000 +1300 testfile
-rw-r--r-- 1 donald donald 30 2022-01-26 22:47:27.000000000 +1300 testfile

**Comment by detoxhby** [comment]
still present
