### ISSUE TITLE
Set expiration date on email shares

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4147]
- share a folder/file via email
- want to set expiration date
--> currently not possible, only in web

Is this >2 days, so we shall put it on board?

**Comment by inok16** [comment]
I have got the same problem. So if you have any further questions, dont hesitate to ask.

**Comment by mgallien** [comment]
@tobias after internal discussions we estimate the work to something between 2 to 4 days to get it merged

**Comment by claucambra** [comment]
This is now possible with #4929
