### ISSUE TITLE
macOS Mojave (10.14 DevBeta 1): UI bug

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/desktop#415]
They seem to have changed something regarding the UI ... See:

![bildschirmfoto 2018-06-12 um 14 04 27](https://user-images.githubusercontent.com/19711361/41289412-f19fcafc-6e49-11e8-87ea-dcd3950ab134.png)

Before:

![macsettings](https://user-images.githubusercontent.com/19711361/41289597-9e564b9a-6e4a-11e8-92d9-c07ab633edf0.png)

**Comment by juliushaertl** [comment]
I guess this is out of scope of the client and rather an issue with Qt: https://bugreports.qt.io/browse/QTBUG-68891
