### ISSUE TITLE
Connected S3 Bucket not showing up via local sync

### ISSUE THREAD

**Issue by Noxdor** [nextcloud/desktop#4155]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour

Connected S3 Bucket shows up as a folder locally on my machine via Sync with my Nextcloud instance.

### Actual behaviour

Everything but the S3 Bucket syncs. It does show in the web interface, just doesn't get synced to my local machine.

### Steps to reproduce
1. Setup an S3 Bucket (in my case with Linode) and connect it via the `external storage support` extension.
2. Add an example file to the bucket to test if it shows up (including the bucket folder) on your local fs, where you are syncing your Nextcloud instance.
3. See that it is not syncing the bucket.

### Client configuration
Client version: 3.4.1

Operating system: Garuda Linux (Arch derivative) garuda-5.15.12-zen1-1-zen

OS language: English/Deutsch, mix it up!

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From Nextcloud or distro) (Linux only): I am not sure what is meant here, I installed it via my systems package manager pacman.

### Server configuration

Nextcloud version: Nextcloud Hub II (23.0.0)

Storage backend (external storage): S3 Linode

I really just want to know if this is normal behaviour, I could imagine this might be a feature not implemented yet. If not, I would be curious what's going wrong.

**Comment by Noxdor** [comment]
Unfortunately I had to solve this issue now by the native integration of webdav folders in Dolphin. Here, the S3 Bucket shows up. It's a shame though because the quick links to Talk, Calendar etc. from the Nextcloud Client are great. Looking forward to a sync of the S3 bucket out of the Nextcloud Client.

**Comment by allexzander** [comment]
@Noxdor Nextcloud Desktop client doesn't deal directly with external storage. It works via the NC server. Whatever is configured in the NC server - will get taken as the only source of truth by the desktop client. The client itself doesn't care if the server set up with external storage or not. So, it's more of a support request to a server + external storage integration.
