### ISSUE TITLE
Enhance call notification

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4159]
- [ ] add "answer" / "decline" button to call notification, which opens browser and joins call
  - [ ] does this need talk help?
- [ ] can response time be quicker? Not wait 30s
- [ ] native integration *or* generic tray notification by us
  - later we want to add predefined replies, so we need more than "accept" / "decline" button, so please check if this would be possible with native integrations
  - [ ] mac os
![image](https://user-images.githubusercontent.com/5836855/148732201-98d8c736-80e1-462d-a35a-018aae56663a.png)
  - [ ] Windows
![image](https://user-images.githubusercontent.com/5836855/148732330-fd5180d2-3da5-410b-b230-f2e87c2ed737.png)
  - [ ] Linux?

**Comment by nickvergessen** [comment]
> can response time be quicker? Not wait 30s

Notify_push already should do it?

**Comment by tobiasKaminsky** [comment]
> * which opens browser and joins call

@nickvergessen is this possible to directly join?

**Comment by tobiasKaminsky** [comment]
For second step: add quick reply

**Comment by nickvergessen** [comment]
No, not at the moment

**Comment by tobiasKaminsky** [comment]
> > > * which opens browser and joins call
> > 
> > 
> > @nickvergessen is this possible to directly join?
> 
> No, not at the moment

Ok, then this is out of scope right now.
Once it is possible from Talk side, we will add it as a new issue to implement it.

**Comment by tobiasKaminsky** [comment]
@camilasan 
Can you check what is better (UX, but also time wise): native integration or generic tray notification by us?

Later we want to add predefined replies, so we need more than "accept" / "decline" button, so please check if this would be possible with native integrations.

**Comment by camilasan** [comment]
@jancborchardt @tobiasKaminsky I think it will be easier and quicker to do the generic tray notification.
I think we can make it look the same in the 3 platforms as the one for Windows (the screenshot in the issue description).

**Comment by jancborchardt** [comment]
Mockup here too, as talked about in the call :)
![Incoming call](https://user-images.githubusercontent.com/925062/162759269-5b9672e3-c9e3-4bae-9c75-0f9da63599cb.png)

Location:
- Top right in macOS and Linux
- Bottom right in Windows

With some whitespace from menu bar and right screen edge (same amount of space in both directions).
And rounded corners, just like the tray menu.

**Comment by claucambra** [comment]
We have existing code for positioning the tray near the OS task/menu bar, IMO we should just position in same place

**Comment by jancborchardt** [comment]
> We have existing code for positioning the tray near the OS task/menu bar, IMO we should just position in same place

Sure, that works. :) My info was that we can only position it near the mouse cursor. But positioning it near the menu bar (or where the icon is) is better.

-----

Also @claucambra, we were talking about possibly having a blurred version of the avatar in the background (like we do in the web, and like Teams does in the screenshot above, and others on mobile) – this could possibly look like this:
![image](https://user-images.githubusercontent.com/925062/164207810-025d6497-6bb7-4f03-ac5a-aaee7b16bbab.png)
(Gaussian blur size 50px, and brightness decrease so the text is legible.)
But if it’s easier to do native notifications e.g. on macOS, then that would be even better.

cc @karlitschek

**Comment by karlitschek** [comment]
looks awesome

**Comment by claucambra** [comment]
Current implementation in PR #4426 

<img src="https://user-images.githubusercontent.com/70155116/164344641-03774f9e-740f-4168-8b9f-e6e7bb5387d3.jpg" width=250>
