### ISSUE TITLE
Wrong position of popup on MacBooks with Notch

### ISSUE THREAD

**Issue by autoantwort** [nextcloud/desktop#4163]
### Expected behaviour
For example a native popup:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/41973254/148805327-ef426d1e-e9d6-41c4-9362-4229d08df25d.png">

### Actual behaviour
<img width="426" alt="image" src="https://user-images.githubusercontent.com/41973254/148805398-7c878486-e2d4-4581-8c4a-68e8d581bfd3.png">
Also the left edge is behind the notch. 

### Steps to reproduce
1. Buy a MacBook with Notch
2. Install Nextcloud client
3. See wrong position

### Client configuration
Client version: 3.4.1
Operating system: macOS 12.1

**Comment by allexzander** [comment]
A regression? Or, does it also happen with 3.3.6?
