### ISSUE TITLE
Color tray menu header according to theming of active account

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#4173]
Tray menu header could reflect theming color of the currently selected account (like in Android for the primary color).
This would help a lot in distinguishing which account is currently selected.

We need to make sure this uses the same algorithm as on web, like if the primary color is very bright, the icons need to be dark, and we need to double-check if it looks good for extremes like white and black as theming colors.

(Leftover part from https://github.com/nextcloud/desktop/issues/877 )

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/blob/57b2a8ef1a60fbfa8331b045ca49f0e60d34eb28/src/main/java/com/owncloud/android/utils/theme/ThemeColorUtils.java#L50

Is where we compute/get our color from.

@jancborchardt can you point us to the server side part, so we can check if the some algorithm is used?
