### ISSUE TITLE
Prevent Accidental Re-Sync / Re-Upload after accidentally Moving a Folder/File In and Out of Sync-Location

### ISSUE THREAD

**Issue by pdolinic** [nextcloud/desktop#4176]
Sometimes it is possible to accidentally move out a folder of a Sync-Location, Nextcloud then thinks the folder was deleted and when moving that folder back into the location seconds after - Nextcloud starts reuploading. 
-> This is problematic if the folder is big (or even even small) because not only will this use all bandwith - this will also have to happen across all devices again and again (and possibly hit a lof of dependent programs)

Brainstorming / Solution: 
Step 1) Keep a Sha256sum of all Folders and Files for at least 24 - 48 hours so you can keep track of accidental "moving folder out and inside". 
Step 2) Expect this in a way and create a Storage-Location for "Deleted/Moved" for 24-48 hours, so it is not necessary to Re-upload.

**Comment by billcarroll** [comment]
It might also make sense to confirm folder moves, especially for folders above a certain size.

**Comment by Rello** [comment]
Hello,

we are dependent on the file system events the OS is giving us. and a move is a move.
We can also not store an additional shadow copy of everything as this would create huge efforts for syncing change when being put back in place a day later.
I do not see a business case here, compared to the very high efforts and expected conflicts
