### ISSUE TITLE
Build failure on GCC 12 because standard attributes are present in the middle of decl-specifiers

### ISSUE THREAD

**Issue by michel-slm** [nextcloud/desktop#4180]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud 3.4.1 should build fine with GCC 12

### Actual behaviour
This fails due to GCC 12 "detecting using standard attributes in the middle of decl-specifiers, which is invalid.". [build.log](https://github.com/nextcloud/desktop/files/7876193/build.log) and [root.log](https://github.com/nextcloud/desktop/files/7876194/root.log) (the latter showing what packages are used for the build) attached.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99032#c3

### Steps to reproduce
1. install Fedora
2. sudo dnf install fedora-packager
3. fedpkg clone -a nextcloud-client
4. cd nextcloud-client
5. fedpkg srpm && mock ./*.src.rpm

### Client configuration
Client version: 3.4.1

Operating system: Fedora Linux (developing on 35, building against Rawhide which has GCC 12)

OS language: US English (but N/A)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): nextcloud-client-3.4.1-1.fc36

Installation path of client: N/A

### Server configuration
N/A

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Build log: https://gist.github.com/michel-slm/8b4d2f28b8edf0bd51e07625de854042

**Comment by michel-slm** [comment]
GCC documentation of the change: https://www.gnu.org/software/gcc/gcc-12/changes.html

**Comment by michel-slm** [comment]
Affects 3.4.2 too: https://kojipkgs.fedoraproject.org//work/tasks/2480/82252480/build.log

**Comment by Flowdalic** [comment]
This issue has been reproduced by Gentoo CI: https://bugs.gentoo.org/842159

Please re-open.
