### ISSUE TITLE
Nextcloud Desktop client on macOS sync slow, freezes and resumes

### ISSUE THREAD

**Issue by jcastro** [nextcloud/desktop#4181]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Files should be synced continuously 

### Actual behaviour
Files are being synced, then all activity is stoped for a few minutes and then it restarts again for a bit, the cycle repeats

### Steps to reproduce
1. Select a bunch of folders with many files to sync
2. Wait for the sync process to start

### Client configuration
Client version:

Operating system: macOS Monterrey 12.1 Macbook Pro 14 M1 Pro

OS language: English

Desktop client macOS osx-21.2.0 version 3.4.1

### Server configuration

Nextcloud version: Nextcloud Hub II (23.0.0) - TrueNAS plugin

Storage backend (external storage): TrueNAS

### Logs
1. Client logfile: 
Download logs: https://d.pr/f/QmTDy2

2. Web server error log:
Download logs: https://d.pr/f/VPhN5T

3. Server logfile: nextcloud log (data/nextcloud.log):
Download logs: https://d.pr/f/N0fiPu

There's also a video that shows the behaviour, you can fast forward it to see what's happening. The terminal window shows the resources and process used in the nextcloud server. There's also no IO wait, the server is barely used when the video was recorded and it's running on a NVME drive for the database. The network widget shows the activity in the macOS client, which as you can see aside from nextcloud barely has any activity

https://user-images.githubusercontent.com/190036/149770305-6c998034-d289-4042-bd25-7989b2406ba1.mp4

**Comment by jcastro** [comment]
Rolling back to Desktop client version 3.3.6 seems to solve the problem

**Comment by allexzander** [comment]
Probably related to https://github.com/nextcloud/desktop/issues/4106

**Comment by snowflakeas** [comment]
same problem new NC23.0 install
client 3.3.6 seems to solve this (slow, but at least moves forward)

**Comment by jcastro** [comment]
@allexzander should this be fixed on 3.4.2? thanks!

**Comment by jcastro** [comment]
Just a heads up that release 3.4.3 didn't fix this issue

**Comment by jcastro** [comment]
3.4.3 working very bad, had to go back to 3.3.6

**Comment by jcastro** [comment]
3.4.4 still has the issue

**Comment by nioakeim** [comment]
I noticed the same issue on a large sync operation. for 44Gb sync with the 3.4.4 I was waiting for hours, but with 3.3.6 it just finished under 20 minutes.  To bad that 3.4.4 is the intel version

**Comment by jcastro** [comment]
3.5 rc1 still with the issue, had to go back to 3.3.6

**Comment by jcastro** [comment]
3.5 rc3 still with the issue, had to go back to 3.3.6

**Comment by jcastro** [comment]
3.5 still wit hthe issue sadly

**Comment by jcastro** [comment]
3.5.1 seems to fix the issue, can't reproduce anymore. Thanks!
