### ISSUE TITLE
Nextcloud Sync Client Randomly Deletes Data After Adding Another Client Machine

### ISSUE THREAD

**Issue by GAPPSRefusenik** [nextcloud/desktop#4185]
Server - 21.0.2
Proxmox LXC Container (Turnkey Nextcloud ISO Image based on Debian 10 Buster)

1st Machine:
Desktop Client - 3.4.1.20211221
Windows 10 Enterprise 2016 LTSB

2nd Machine:
Desktop Client - 3.4.1.20211221
Windows 10 Enterprise 2019 LTSC

Expected behaviour
The 2 clients sync chosen folders with the server.

Actual behaviour
With no warning, the Windows 10 client deleted a bunch of seemingly random files. Folders were left intact, interestingly enough, more often than not being empty.

Background: The other day I registered a new domain for my nextcloud and had to reconfigure clients accordingly. I started with my desktop PC (hereafter PC1). I always skip the initial sync selection and then configure sync folders manually. So I went ahead and picked the three common Windows user data folders 'Documents', 'Pictures' and 'Videos'. It took a little time, and all went well. Since I run Windows version 1607 on my Desktop, I had to sync everything. For my Surface PC (hereafter PC2) running Windows version 1809, I enabled Virtual Files, and then added the same three user data folders.

Last night while using PC2, I noticed some notifications about recently deleted files in my video folder. In order to make sure that nothing undesirable happens, I immediately exited the sync client. Also, when I booted PC1 today, I immediately disabled the NIC and then also exited the sync client. Upon further inspection of my local file system, and also the files on the server, I noticed mostly empty folders in both the 'Pictures' and 'Videos' directories. Expectedly, the trash bin on the server was full of precious private user data.

I've done a quick inspection of the server log file, and noticed that the unauthorized and unprompted deletion of files started at around the same time I added the sync connections on PC2, or shortly thereafter. Further indication to my assumption is the fact that the logged IP address of the machine that initiated the deletion sync is the IP address of PC2.

I attached the server log file, stripped down to the events of relevance. The logs of the unprompted deletion events start on line 71.
[nextcloud.log](https://github.com/nextcloud/desktop/files/7899767/nextcloud.log)
.

**Comment by allexzander** [comment]
@GAPPSRefusenik 

Have you noticed any errors in the desktop client that initiated the deletion? Something similar to `Couldn't create placeholder info...`?

You may also want to attach desktop client logs here.

**Comment by GAPPSRefusenik** [comment]
I believe I have read that placeholder error before. Couple of months back I had a similar issue with one particular folder that got deleted several times. I restored it from the trash bin, and it stopped occurring after I disabled syncing of hidden files which I assume caused the issue.

I have only relatively brief logs in the %appdata%\local directory. Do you have to enable logging for the sync client manually?
