### ISSUE TITLE
Files delete by client not in server trash.

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/desktop#4190]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I think that if the client delete files, they should be kept in the server's trash.

### Actual behaviour
Files are not in the trash.

### Steps to reproduce
1. delete files locally
2. check the server, they are not in the trash

Maybe it is not relevant, but this happened after this comment:
https://github.com/nextcloud/desktop/issues/4016#issuecomment-1015294697

I had this issue, we were debugging with 2 users, and I think I got it back up.
One user managed to sync well, so that's why I think I managed to correct everything.
And the other user, his client deleted half of the server, so that now, I have to do half a recover :upside_down_face: 

### Client configuration
Client version: 3.4.1

Operating system: Mac os

OS language: French

Installation path of client:

### Server configuration

Nextcloud version: 20.0.12

Storage backend (external storage): s3

### Logs

Waiting the user to send it to me.

1. Client logfile: 

2. Web server error log:
78.x.x.x - user [19/Jan/2022:12:04:22 +0000] "DELETE /remote.php/dav/files/user/Tr%C3%A9so%20Gestion/Ressources%path... HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Macintosh) mirall/3.4.1git (build 8596) (Nextcloud, osx-20.3.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)" "78.x.x.x"

3. Server logfile: nextcloud log (data/nextcloud.log): didn't find relevant logs

**Comment by pierreozoux** [comment]
How do we keep that open?

**Comment by milux** [comment]
I also regard this a bug and would be happy if this was kept open...
