### ISSUE TITLE
Enable sharing-features for search results on desktop client

### ISSUE THREAD

**Issue by 4ree** [nextcloud/desktop#4193]
Hi,

I'm using the desktop client on Linux.
The file explorer Dolphin does not have context menu for sharing files using nextcloud client and the only option is sharing with the client itself. But, most of the time we need to use search for finding the file that will be shared.

It would be really convenient if we have the share function for search results.

Thanks

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a commend here.
Thank you for your support
