### ISSUE TITLE
Client always asks to login when it starts

### ISSUE THREAD

**Issue by gianmarcogg03** [nextcloud/desktop#4195]
I'm using the NC desktop client version 3.4.0-2 on Arch Linux. Every time the client starts, whether it's on session login or when I start it manually, it brings up a browser window asking me to login and authorize the client. Thanks in advance.

**Comment by allexzander** [comment]
@gianmarcogg03 Seems to be a duplicate of https://github.com/nextcloud/desktop/issues/3820?

**Comment by gianmarcogg03** [comment]
Solved by simply installing `gnome-keyring`. Thanks for your help anyway.
