### ISSUE TITLE
Editing notes created or modified by Desktop Sync Client elsewhere creates "File could not be synced" error

### ISSUE THREAD

**Issue by MillironX** [nextcloud/desktop#4196]
> _Previously reported as https://github.com/stefan-niedermann/nextcloud-notes/issues/1451_
> _Previously reported as https://github.com/nextcloud/notes/issues/806_

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Setup the Desktop sync client on one or more computers
2. Create a new note on the Desktop computer

    ```bash
     echo "# Note From Desktop\n\nThe quick brown fox..." >> ~/Nextcloud/Notes/"Note From Desktop.txt"
    ```

4. In the Server Notes app, select "Note From Desktop" in the sidebar, and add the text "Does this work?" to the note body

    ![Editing on server](https://user-images.githubusercontent.com/25492070/150351065-3c202ed8-8968-4f1a-91eb-095b07e20c77.png)
    
6. Wait for the change to be propagated to the Desktop sync client

### Expected behavior

The file `~/Nextcloud/Notes/Note From Desktop.txt` on the desktop computer should say

```markdown
# Note From Desktop

The quick brown fox...

Does this work?
```

Note that if the edit in step 4 is made from another synced Desktop computer, then the expected behavior is observed.

### Actual behavior

The Desktop sync client reports 

```plaintext
Note From Desktop.txt could not be synced due to an error
```

![Nextcloud Notification](https://user-images.githubusercontent.com/25492070/150223707-e7062d78-3fc8-425c-8a8c-b21928e95a6e.png)

Examining the error report in the settings dialog reveals

```plaintext
Note/Note From Desktop.txt: The downloaded file does not match the checksum, it will be resumed <CHECKSUM> != <CHECKSUM>
```

![Nextcloud Settings Dialog](https://user-images.githubusercontent.com/25492070/150224478-261cd00a-f7d1-417b-8ffe-fbb6830774d5.png)

The server app reflects the correct state of the files, however.

### Client configuration

- Client version: 3.3.6 (Fedora) (_Latest distro package_)
- Operating system: Fedora 35
- OS language: en-us
- Qt version used by client package (Linux only, see also Settings dialog): 5.15.2
- Client package (From Nextcloud or distro) (Linux only): distro
- Installation path of client: `/usr/bin/nextcloud`

### Server configuration

- Nextcloud version: 21.0.1
- Storage Backend: S3 (Linode)
- OS: Debian 10
- Web server: Apache2
- PHP version: 7.3.31-1
- Database: MySQL 10.3.31-MariaDB-0

**Nextcloud configuration:**

<details>

```json
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nextcloud.millironx.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.millironx.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "US",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "versions_retention_obligation": "auto",
        "app_install_overwrite": [
            "ocsms"
        ],
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud.millironx.com.storage",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "us-east-1.linodeobjects.com",
                "port": 443,
                "use_ssl": true,
                "region": "us-east-1"
            }
        },
        "maintenance": false
    }
}
```

</details>

### Logs

1. Client logfile: [client_logfile.zip](https://github.com/nextcloud/desktop/files/7926031/client_logfile.zip)
2. Web server error log: [error.log](https://github.com/nextcloud/desktop/files/7926089/error.log)
3. Server logfile: nextcloud log (data/nextcloud.log): [nextcloud.log](https://github.com/nextcloud/desktop/files/7926071/nextcloud.log)

**Comment by Lars1963** [comment]
Maybe related to #4141

**Comment by MillironX** [comment]
Cannot reproduce after upgrading server to Nextcloud v22
