### ISSUE TITLE
Strange behavior of W10 NextCloud desktop app

### ISSUE THREAD

**Issue by lkavale** [nextcloud/desktop#420]
We have NextCloud 13 server (At Docker container on Debian VM hosted on VMWare ESXi) in our office network. Server is acessible through office network address and via public internet address. We are using Windows 10 NextCloud desktop 2.3.3 (Build1) application. When the NextCloud server was down, the application was at discconected state (trying to reconnect the server), the PC was connected to office network through VPN connection, the application generate some trafic that disturbing that VPN connection. Pings to office network were very long (over 100ms at some times, with several outages) and VNC connections to office network are stucking and failing. When we kill the NextCloud app, everythig was working fine. We have tried that several times with the same results.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?
