### ISSUE TITLE
Files marked for sync never get sync'd

### ISSUE THREAD

**Issue by azukaar** [nextcloud/desktop#4201]
I am using Nextcloud client with VFS enabled. Everytime I try to paste a folder in the Nextcloud folder, half of the file won't upload, making the whole setup completely useless. I have attached logs for an example I did trying to copy paste a random folder from my desktop into the nextcloud folder.

![image](https://user-images.githubusercontent.com/7872597/151156761-34209678-18cd-4966-8cbd-686c66d1a25b.png)

For some reasons, 2 folders sync'd just fine, but one didn't

![image](https://user-images.githubusercontent.com/7872597/151156799-0d80f908-5fb5-4f9b-9871-4e84c55a230c.png)

The whole folder didn't sync, it is also empty on the remote, so it is not just the icon but the sync did indeed fail:

![image](https://user-images.githubusercontent.com/7872597/151156861-fcb8dd3c-cc60-42f8-b39e-ab396b6ca075.png)

I have attached the logs here for further information. Thanks for looking at it

[log.txt](https://github.com/nextcloud/desktop/files/7941435/log.txt)

Client version: 3.4.1

Operating system: Win 10

OS language: EN

Nextcloud version: 23.0.0

Storage backend (external storage): Local External Storage

**Comment by Lars1963** [comment]
Maybe related to #4141

**Comment by azukaar** [comment]
Not fixed
