### ISSUE TITLE
translation -> fr - "polling" is wrongly translated to "sondage"

### ISSUE THREAD

**Issue by feth** [nextcloud/desktop#4211]
Well, we could argue that's my feeling.
When polling refers to checking a remote URL, I'd rather translate "polling" to "connexion du client". Still imperfect.
Or maybe something even more explicit -a non technic user asked me for help on this one.

Two occurrences:

https://github.com/nextcloud/desktop/blob/fe799e983bf22f64d20ae4625ae0d77f7b5aa06e/translations/client_fr.ts#L1195
https://github.com/nextcloud/desktop/blob/fe799e983bf22f64d20ae4625ae0d77f7b5aa06e/translations/client_fr.ts#L3394

My 2c,
cheers

**Comment by joshtrichards** [comment]
Those translation files are pulled from outside this repository. We manage translations via [Transifex](https://www.transifex.com/nextcloud/nextcloud/dashboard/). You can add/update translations yourself by signing up and entering the group. So just request joining the translation team for Nextcloud on the site and start translating. All translations will then be automatically pushed to this repository.
