### ISSUE TITLE
Log file cannot be opened for writing. The log output cannot be saved.

### ISSUE THREAD

**Issue by k-bx** [nextcloud/desktop#4214]
Hi. I'm using https://sam.nl.tab.digital for a few days now. It's been working well so far. I'm using Ubuntu 20.04 and Nextcloud client installed via Snap (`sudo snap install nextcloud-desktop-client`).

The exact error is this:

```
File "/home/kb/snap/nextcloud-desktop-client/13/.config/Nextcloud//logs/20220128_1049_owncloud.log.0"
cannot be opened for writing.

The log output cannot be saved!
```

As shown on this screenshot:

![Screenshot from 2022-01-28 10-50-49](https://user-images.githubusercontent.com/107968/151516621-ea591a16-195e-4385-bea3-f2d32ddcf126.png)

Version info is this:

```
$ nextcloud-desktop-client.nextcloudcmd --version
Nextcloud version 3.4.2git
Git revision b0791e51ceebef3295b30dc596c391c077af1924
Using Qt 5.15.3, built against Qt 5.15.3
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu Core 20, x86_64
```

**Comment by k-bx** [comment]
Update: restart helped, it seems, and things were never really broken, so this is low priority. However, I think it'd be nice to fix this still.

**Comment by glasen** [comment]
This bug only occurs when using the snap package maintained by me. The bug is triggered when the snap package is updated in the background when the client is still running.

The only way to fix this, is changing the log directory from "~/snap/next-cloud-desktop-client/$snap_revision/.config/Nextcloud/logs" to "~/snap/next-cloud-desktop-client/common/Nextcloud/logs".

**Comment by pfagomez** [comment]
I have the same error
Built from Git revision [dacaf7](https://github.com/nextcloud/desktop/commit/dacaf72669b9e1ec119e23d6c2f7b8f8dd6dcfe6) on Feb 19 2022, 08:59:16 using Qt 5.15.3, OpenSSL 1.1.1f 31 Mar 2020
I could not find the option to change the log directory

**Comment by FabienZa** [comment]
Same to me, how can we modify the log directory folder please ?

**Comment by sylock** [comment]
Same here.

**Comment by pfagomez** [comment]
I still have this issue

**Comment by imakecodes** [comment]
I have the same issue, someone have some fix?

**Comment by naderjafari** [comment]
I have the same issue, someone have some fix?

**Comment by villasenor** [comment]
@glasen - can we change the default log directory to avoid this? It's not clear from your comment what the correct configuration should be. Thanks!

**Comment by FabienZa** [comment]
To me, the only solution was to don't use the snap version anymore...
The .deb one works. =/

**Comment by glasen** [comment]
I've made a patch to change to default log-dir in the snap-package. It now points to "~/snap/nextcloud-desktop-client/common/logs". This directory does not get touched when upgrading the snap.
