### ISSUE TITLE
Reproducible crash of Nextcloud Desktop-Client Version 3.4.2 (macOS)

### ISSUE THREAD

**Issue by d-3-s** [nextcloud/desktop#4215]
### Expected behaviour
I can sync folders and files independent of the structure. 

### Actual behaviour
There are multiple scenarios in which my Nextcloud Desktop-Client uses 100% CPU load if I move certain files / folder+file structures into a folder to be synced.

### Steps to reproduce
1. take a fresh 23.0.0 installation
2. install latest Nextcloud Desktop-Client (3.4.2; Definitely already happened since 3.4.0) and connected to your server
3. sync some working files on it (not sure if that step is really needed)#
4. **create a folder starting with a "." e.g. ".test"**
5. **add any file with content into that folder e.g. text.txt containing "foo bar"** --> an empty file works, as soon as you add content it consumes 100% CPU and will stay like that forever
6. one needs to kill the client with kill -9 processID
7. remove the file from the folder .text
8. start the client and it will stay again at low CPU consumption and files in other folders can be synced 

### Client configuration
Client version:
Nextcloud Desktop-Client 3.4.2 - installed via homebrew

Operating system: macOS Monterey 12.2

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog):

Installation path of client: not changed, used "default of homebrew"

### Server configuration
Nextcloud version: Nextcloud Hub II (23.0.0)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
I will add this if needed in a later step; I need to create it from a clean virtual machine, as the configuration.cfg inside it contains too much sensitive data

2. Web server error log:
There are no records in the error logs. The only thing I found was the following, that you get a 500 after some time (But that takes a few seconds, the client already went to 100% CPU load before that):
`172.29.4.6 - ds 28/Jan/2022:09:23:26 +0000 "PROPFIND /remote.php" 207
172.29.4.6 - ds 28/Jan/2022:09:23:27 +0000 "PROPFIND /remote.php" 207
 172.29.4.6 -  28/Jan/2022:09:23:47 +0000 "GET /ocs/v2.php" 304
172.29.4.6 -  28/Jan/2022:09:24:19 +0000 "GET /ocs/v2.php" 304
172.29.4.6 -  28/Jan/2022:09:24:19 +0000 "PUT /index.php" 200
172.29.4.6 -  28/Jan/2022:09:24:19 +0000 "PUT /index.php" 200
172.29.4.6 - ds 28/Jan/2022:09:23:27 +0000 "POST /remote.php" 500
172.29.4.6 -  28/Jan/2022:09:24:47 +0000 "GET /ocs/v2.php" 304`

3. Server logfile: nextcloud log (data/nextcloud.log):
At the time of the 500 log I get 
`{"reqId":"lGNFuIBV1lUSuIEMds0U","level":4,"time":"2022-01-28T09:24:27+00:00","remoteAddr":"172.29.8.2","user":"$user","app":"webdav","method":"POST","url":"/remote.php/dav/bulk","message":"Unknown error while seeking content","userAgent":"Mozilla/5.0 (Macintosh) mirall/3.4.2git (build 9042) (Nextcloud, osx-21.3.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"23.0.0.10","exception":{"Exception":"Sabre\\DAV\\Exception","Message":"Unknown error while seeking content","Code":500,"Trace":[{"file":"/var/www/html/apps/dav/lib/BulkUpload/MultipartRequestParser.php","line":129,"function":"isAt","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->","args":["--boundary_.oOo._kk2crXOPNUS+SVAuPc4mHuBoFd5oWjWm--\r\n"]},{"file":"/var/www/html/apps/dav/lib/BulkUpload/BulkUploadPlugin.php","line":69,"function":"isAtLastBoundary","class":"OCA\\DAV\\BulkUpload\\MultipartRequestParser","type":"->","args":[]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPost","class":"OCA\\DAV\\BulkUpload\\BulkUploadPlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:POST",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":166,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/BulkUpload/MultipartRequestParser.php","Line":111,"CustomMessage":"--"}}
`

**Comment by michi7801** [comment]
## Client configuration
Client version:
- Nextcloud Desktop-Client 3.4.2 - installed via homebrew
- Operating system: macOS Big Sur 11.6
- OS language: DE
- Installation path of client: not changed, used "default of homebrew"

## Server configuration
- Nextcloud version: Nextcloud Hub II (23.0.0)

## Problem
I also observed this behavior after syncing bigger folders. After 5 - 10 minutes the client crashes and I have to kill it through terminal. After waking up my Macbook from sleep the crash also happens. 
As long as nothing gets synced or all syncs have finished everything runs fine. I can confirm that this not only happens with hidden files and folders. Although the spike in CPU-usage only happens when syncing hidden files and folders.

**Comment by d-3-s** [comment]
I resolved the issue for me:

- the virtual machine I as initially using for the test was an image which I was upgraded to Big Sur. With a total clean image I could not reproduce it.
- Therefore I tried to uninstall in a clean way (including everything in Libary, Logs, ...) in each to be synced folder the *.db files of nextcloud
- After reinstalling nextcloud with brew the issue did not appear anymore and I could sync hidden folders
- After doing the same on my machine in use it worked as well.

Hint: one does not even need to wait till everything is synced again. I just selected the same folders (even with the existing .hidden/problematic.txt file inside) and it was finished with that approach in a few seconds.

--> If you have the issue reinstall nextcloud (use a tool which really detects all the Libaries as well; Not just the program in the programs folder)

**Comment by claucambra** [comment]
Hi, the client logfiles would be very appreciated as without them it is very difficult to tell exactly what is causing the crash on the desktop client side. Could you provide them? Thanks!

**Comment by d-3-s** [comment]
Hi!
folder logs which you get with "Debug-Archive erstellen" never contained any data. Also if I was manually checking the logfiles I did not see any logmessages. So it hang before doing any logfile interaction.

nextcloud.cfg (without sensitive data)
`[General]
clientVersion=3.4.2git (build 9042)
confirmExternalStorage=true
newBigFolderSizeLimit=500
optionalServerNotifications=true
updateSegment=63
useNewBigFolderSizeLimit=false

[Accounts]
0\Folders\1\ignoreHiddenFiles=false
0\Folders\1\journalPath=.sync_7e2b904955ad.db
0\Folders\1\localPath=/xxxxxxxxx
0\Folders\1\paused=false
0\Folders\1\targetPath=/
0\Folders\1\version=2
0\Folders\1\virtualFilesMode=off
0\authType=webflow
0\dav_user=xxxxxxxxxxxx
0\serverVersion=23.0.0.10
0\url=xxxxxxxxxxxxxxxxx
0\user=@Invalid()
0\version=1
0\webflow_user=xxxxxxxxxxxxx

[Settings]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\xb0\0\0\x4\xce\0\0\x3\t\0\0\a\x9c\0\0\0\xb0\0\0\x4\xea\0\0\x3\t\0\0\a\x9c\0\0\0\0\0\0\0\0\x5\xa0\0\0\0\xb0\0\0\x4\xea\0\0\x3\t\0\0\a\x9c)
`

I fully understand that it is very hard to analyse anything further, but I can't provide what I don't have ;-)
