### ISSUE TITLE
[Bug]: Windows max path length=260 symbols limitation

### ISSUE THREAD

**Issue by pmelikov** [nextcloud/desktop#4227]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the path length is >=260 characters in Microsoft Edge on Win 11, Nextcloud successfully transfers all files and folders with normal path lengths, but instead of files whose path exceeds 260 characters, it creates a NotFoundError file in the root directory with the content: "NotFoundError: A requested file or directory could not be found at the time an operation was processed.".
This is because on Windows the maximum allowed path length is 260 characters, as opposed to 4096 characters on Linux.

### Steps to reproduce

1. Create folder named "111..." with long path, for example, "C:\Users\XXXXX\Downloads\1111111111111111111111111111111111111111111111111111\22222222222222222222222222222222222222222222222222222222\3333333333333333333333333333333333333333333333333333333333333333333333333\my_file4444444444444444444444444444444444444444.yml"
2. Try to upload this folder with all its files
3. And instead file "my_file444" near root "111..." Nextcloud with create file "NotFoundError"

### Expected behavior

This is not an informative error message, and is there any point in uploading all other files from the download directory if some "inappropriate files" are skipped?
Perhaps it's better to add a warning "The file path is too long! Ignore the file and uploadi everything else?" instead of creating "NotFoundError" file in root folder.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
it is not necessary. Its just Windows client limitation
```

### List of activated Apps

```shell
it is not necessary. Its just Windows client limitation
```

### Nextcloud Signing status

```shell
it is not necessary. Its just Windows client limitation
```

### Nextcloud Logs

```shell
it is not necessary. Its just Windows client limitation
```

### Additional info

it is not necessary. Its just Windows client limitation

**Comment by pmelikov** [comment]
I don't know if the desktop client has this problem. I meant that the version in the browser has it.

**Comment by limatus** [comment]
**Please reopen the issue, as:**

We are struggling with this issue daily across our fleet, even though we have enabled LongPathsEnabled=1 in the Windows Registry (Windows 11, VFS enabled).

We specifically encounter the error: Vorübergehender Fehler beim Entfernen eines vom Server entfernten lokalen Objekts (English: Temporary error removing local object that has been removed from server)

The Specific Behaviour: 
We observe a distinct partial failure:

Data is deleted: When we delete a complex directory tree on the server, the client successfully deletes the files inside these folders locally.

Folders remain: The empty folders themselves fail to be removed. The client throws the “Temporary Error” and the empty folder structure remains on the disk as a “zombie” entry. But only for the folders that are too long, the others are deleted without an error. 

Manual Fix: We can manually delete these empty folders in Windows Explorer without issues, so the OS capability is there.

Anonymized Example from our logs: Path length: ~190 characters (folder structure only, excluding file names) C:\Users\User\Nextcloud\01_Department\01_Region\Country_Name\03_Projects\Category_A\03\06_Misc_Files\P\Infrastructure_Project_Alpha\Construction_Site_Water_Point_Installations\Construction_Site_Water_Point_Installations

Hypothesis: It seems that while the file deletion (likely DeleteFile) handles the path length or VFS correctly, the operation to remove the directory itself (RemoveDirectory or the recursive check if empty) hits the MAX_PATH wall or a VFS limitation.
