### ISSUE TITLE
Check any sync database operations for improper error management

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4229]
Desktop client is relying on a sync database to maintain proper state of a sync folder.
Some access to sync database can generate errors without them being properly handled. Check all such usage to ensure errors are not getting ignored silently.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by allexzander** [comment]
- check first that inside SyncJournalDb class we really check any error from low-level methods implementing the DB operations (SqlQuery::exec for example)
- make it impossible to ignore the return values of methods of the SyncJournalDb class
