### ISSUE TITLE
Checks every code path that can delete files

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4232]
Ensure that every lines of code that could delete files are legit and that no errors could lead to data loss.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by allexzander** [comment]
@mgallien @tobiasKaminsky Checked every occurrence of assigning the instruction **CSYNC_INSTRUCTION_REMOVE** to **SyncItem**. All conditions for checking **localEntry**, **serverEntry**, **dbEntry**, and VFS folders/files look legit. I could not find any obvious logic that might cause data loss.
