### ISSUE TITLE
Implement end to end tests with real server

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4234]
Implement end to end tests with real server.
~~Exact test perimeter to be determined.~~

This issue aims to provide a minimum test setup, so that upcoming features/bug fixes can implement further tests.
Currently Linux only, then port it to Windows (might be a bit more work due to docker) and Mac (no CI right now).

- [x] set up test server within CI
  - Android example https://github.com/nextcloud/android/blob/master/.drone.yml#L30 server service, available with http://server
- [x] connect client with server
- [ ] Tests
  - [x] create some files, upload them, check that they are on server
  - [x] create some files, upload them, delete them, check that they were deleted on server
  - [ ] create a file, upload it, check activity endpoint, that info is available

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by mgallien** [comment]
For example to test bulk upload a scenario could use some random files created that way `dd if=/dev/urandom of=8K bs=1024 count=8`
Apparently it is possible for bulk upload to also fail when just creating an empty file by doing `echo "ABC" > testFile`

**Comment by tobiasKaminsky** [comment]
Activity endpoint was wrong, this should be tested.

**Comment by tobiasKaminsky** [comment]
Android has some tests: 
https://github.com/nextcloud/android/blob/master/app/src/androidTest/java/com/nextcloud/client/EndToEndRandomIT.java

There are even "random" tests.
