### ISSUE TITLE
Mac OS and virtual folders (experimental), problematic first sync when the user has access to many files

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/desktop#4239]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The first scan takes minimal actions i.e. scans only the first / second level of folders, 
OR
The first scan, after it was interrupted (i.e. when the computer stands by) can benefit from the previous work performed to finish its work.

### Actual behaviour
The first synchronization keeps restarting especially on laptops and it's not easy to have it finish. During this phase, the Nextcloud directory stays empty, the user can't be productive.

### Steps to reproduce
1. The user has access to a large number of files and there is a deep folder hierarchy structure. The order of magniture is over 100.000 files, some thousands folders, nesting up to 5th-6th level.
2. Start up the Mac OS Client, enable virtual folders and let it work.
3. During the first scan (which can easily takes more than one hour), put the mac int standby or do any other intervention that stops the client.
4. The client restarts the scan from the beginning.

### Client configuration
Client version:

3.4.2

Operating system:
MacOS

OS language:
it

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
/Applications/Nextcloud

### Server configuration

Nextcloud version:
22.2.1 , 22.2.2, 22.2.3

Storage backend (external storage):
local

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by DimitriMeimaridis** [comment]
I have something like 20k+ files and I'm experiencing the same issue but a step further. Virtual files seem to also be not syncing correctly. After about a thousand files, it freezes up and can't sync. I have even tried to keep the client app open with nothing else running in the background. This occurred in both my Ubuntu VM and my Macbook.

**Comment by marcotrevisan** [comment]
In my case, when the first sync has finished it just works. My desktop version is 3.4.2. 
If I have to work on a folder I usually set it as locally availabale so I can also benefit from Spotlight searches. This might mitigate your problem @DimitriMeimaridis ...

**Comment by marcotrevisan** [comment]
In my current setup the new version 3.4.3 has further slowed down the initial sync. 
Moreover, on some error situations like folders with trailing spaces, it will now stop and restart forever.
The problem with these file names is that the average user has no clue of this being a problem as Finder allows for that.
