### ISSUE TITLE
Permanent Sync & high CPU load on Windows 10

### ISSUE THREAD

**Issue by prplecake** [nextcloud/desktop#4241]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud should not sit at ~20% CPU usage indefinitely. Sync should finish, and Nextcloud should not prevent File Explorer from opening!

### Actual behaviour
Nextcloud sits at ~20% CPU usage, system tray icon shows syncing icon, though I'm unable to right-click it, no menu shows. If I manage to get into settings before it gets into this state, the settings window will immediately show Not Responding. If I'm slow enough, but manage to open the system tray menu, that menu will basically become unresponsive as well, with Task Manager showing "Not responding"

When Nextcloud is in this state, File Explorer won't open, though once I end the process, File Explorer windows will open. Nextcloud would also prevent Event Viewer (and presumably other mmc.exe utilities) from opening when right-clicking the Start menu and selecting Event Viewer. Again, it'll open once I end the Nextcloud process.

This seems very similar to #1274.

### Steps to reproduce
1. Launch Nextcloud
2. Observe it hanging

### Client configuration
Client version: 3.4.2.20220127

Operating system: Windows 10 21H2

OS language: English

Installation path of client: `"C:\Program Files\Nextcloud\nextcloud.exe"`

### Server configuration

Nextcloud version: 23.0.1 RC1

Storage backend (external storage): S3-compatible

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://gist.github.com/prplecake/88d5e7b1dbf7aaac0aee529db712f28d (There two logs here, nc-log1.txt was taken after I restarted the php-fpm service on the server.)

2. Web server error log: https://gist.github.com/prplecake/77ffbb100af944946dc9340457e384b6

3. Server logfile: nextcloud log (data/nextcloud.log): https://gist.github.com/prplecake/f334301b6c539b71bf929a8120d67be2

I'll note that once I end the Nextcloud process, I see an error that reads "Sabre\DAV\Exception: Unknown error while seeking content" on the admin logging page.

**Comment by Prandur** [comment]
I experience the same behaviour. Server Version is 23.0.0 as docker setup.
I further tried uninstalling and reinstalling the client to no effect. Downgrading it to 3.4.1 or 3.3.6 also showed no effect.

**Comment by Prandur** [comment]
Same behaviour. Downgrading the client showed no effect.
Server configruation is different for me. 23.0.0 as docker setup with local storage.

**Comment by alerque** [comment]
I don't think this is Windows specific. I'm on Linux with the 3.4.2 client as well. I think this problem dates back not to updating the client but to updating the server to 23.0.0 which I did yesterday. Today I have two different Linux clients behaving nearly exactly as described above including the tray icon (which works for a few seconds before freezing).

**Comment by alerque** [comment]
Two extra data points:

1. Updating the server to 23.0.1 did not have any effect.

2. The CPU usage is 100% of one core. For a 2 core machine that means 50% total, for my 16 core machine it is totaling about 6%. If this is the same as on Windows then the OP probably has a 4 or 6 core system ;-)

**Comment by alerque** [comment]
Downgrading client to 2.4.1 did not help. Downgrading the server is probably not a smart thing to attempt at this point.

**Comment by alerque** [comment]
@Prandur How for down did you downgrade your client(s)?

**Comment by Prandur** [comment]
@alerque I just deinstalled the client, rebootet and then installed 3.3.6 which works fine right now.
3.4.1 didn't work either for me, so I assumed that it might be related to the 3.4 jump.
But for linux I don't have an answer as my laptops don't have the client installed right now.

**Comment by alerque** [comment]
I'm guessing this is a duplicate of #4106.

**Comment by Prandur** [comment]
At least in part I guess. But the other issue doesn't mention the fact, that the internet explorer won't open anymore when this issue occurs.

**Comment by alerque** [comment]
@Prandur I'm guessing that is just a symptom: if the sync daemon is locked up in some infinite loop the file browser extension is likely to crash when trying to talk to it.

**Comment by prplecake** [comment]
@alerque You're right, that issue does look identical. However it's not only an issue when uploading; but syncing in either direction.

I can confirm that version 3.3.6 does not have the issue.

**Comment by rottmann** [comment]
Same here, downgrade Nextcloud on Windows 10 to 3.3.6.
Linux 3.4.2 works fine.
Server Version 23.0.0

Can't open Nextlcoud dialogs, Nextcloud run in Background high-cpu usage, does nothing, no net traffic.
Right click in explorer freezes explorer.

**Comment by rottmann** [comment]
Client 3.4.3 seems to work now under Windows 10.

**Comment by alerque** [comment]
@rottmann Did the server you are connecting to upgrade to 23.0.3rc1 (or was it manually patched with the hotfix that is scheduled for that release)? See [this PR](https://github.com/nextcloud/server/pull/31171) but they have decided to disable the bulk upload feature by default at the server level because so many clients are showing this bug. I don't think the client has fixed anything. But whoever administers your server may have fixed this by disabling it at that level.

**Comment by rottmann** [comment]
@alerque Server 23.0.2 (i see only the server version from my provider, don't know if they installed a hot fix).

**Comment by alerque** [comment]
@github-actions Your bot action is bordering on trolling. Please re-open.

There have been several updates and this is not confirmed actually fixed upstream, just temporarily dodged because the problem feature is being suppressed.

**Comment by prplecake** [comment]
FWIW I'm not experiencing this issue anymore with version 3.4.4

**Comment by alerque** [comment]
@prplecake Which server version? Remember they added a hack to disable this feature from the server side to the latest releases. That doesn't mean the bug is fixed, just that your server may not be offering the feature that clients are not handling well.

**Comment by prplecake** [comment]
@alerque ah, good point. I had forgotten about that.

I'm running server version 23.0.3 currently.

**Comment by prplecake** [comment]
This issue is rearing it's ugly head again. I ended up downgrading all the way back to 3.3.6 to get things to sync.

Server 25 RC5.

**Comment by alerque** [comment]
@prplecake As far as I know it has never been fixed, some server releases just disabled the buggy offending feature by default. It would be interesting to confirm that bulk uploading has been re-enabled by default in 25-rc5.

Meanwhile are you able to re-open this issue? Even open issues on this repo barely get attention, I doubt our commenting on a closed one is going to bring it to the necessary developer's attention.

**Comment by prplecake** [comment]
I'm unable to reopen this issue.

**Comment by alerque** [comment]
This is probably a close enough duplicate with #4106 that is still open that we can let it go. Also still open in the related server issue https://github.com/nextcloud/server/issues/30424.

**Comment by redispade** [comment]
Workaround by adding 'bulkupload.enabled' => false, in config.php

**Comment by marcx28** [comment]
Another workaround which worked for me (without disabling bulk upload) was to set `useUploadLimit=0` in the configuration file `%AppData%\Roaming\Nextcloud\nextcloud.cfg`

**Comment by BoxedBrain** [comment]
This issue still persists and should be reopened as mentioned by quite a few people.

**Comment by alerque** [comment]
@BoxedBrain This is a duplicate, the open one covering this is #4106 plus the server side issue https://github.com/nextcloud/server/issues/30424.
