### ISSUE TITLE
Unable to sync virtual files on Windows Server 2019

### ISSUE THREAD

**Issue by kamilko** [nextcloud/desktop#4246]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Every attempt to synchronise nextcloud folder on Windows Server 2019 with virtual files mode - crashing nextcloud.exe.

### Actual behaviour
There is possibility with very old version of nextcloud client, that there is no problem with sync. For example if I try ownCloud client, connect to the same account on the same nextcloud server and enable virtual files syncing, whole process is completed without problem (though there is scary information about incompatibility with nextcloud server). ***So it is some kind of regression.***

### Steps to reproduce
1. Install Windows Server 2019 Standard (im using here version installed as openstack instance)
2. Install latest Nextcloud desktop client (the same crash is with every version back to 3.3.0)
3. Have some folder with many files (more than 300 i guess, perfect example is to upload this repository with web interface and then synchronise with desktop client)
4. Connect Nextcloud client to server and start sync
5. After around 300 files synchronised - nextcloud.exe will crash (it doesn't matter if your windows user is Admin or not)

### Client configuration
Client version: 3.4.2

Operating system: Windows Server 2019 Standard x64 Version 1809 (but latest updates still behaves the same)

OS language: en_US (but that doesn't matter - tested also with en_UK and pl_PL - same problem)

Installation path of client:
"C:\Program Files\Nextcloud\"

### Server configuration

Nextcloud version:
22.2.3 Snap version (also tested with every version down until 20)
System: Ubuntu 20.04
Other software: none, instance is only for Nextcloud Server installed with snap.

Storage backend (external storage): None

### Logs

1. Client logfile: 
Command `nextcloud --logdebug --logwindow` gave me empty folder.
`...\AppData\Roaming\Nextcloud\` zipped in the attachments.

2. Web server error log: empty

3. Server logfile: nextcloud log (data/nextcloud.log): empty

[windows_event_log.txt](https://github.com/nextcloud/desktop/files/7994872/windows_event_log.txt)
[Nextcloud_logs.zip](https://github.com/nextcloud/desktop/files/7994873/Nextcloud_logs.zip)

**Comment by uberiain** [comment]
With nextcloud client 3.4.3 I have the same problem:

Nombre de la aplicación con errores: nextcloud.exe, versión: 3.4.3.35137, marca de tiempo: 0x62190d89
Nombre del módulo con errores: CLDAPI.dll, versión: 10.0.17763.2237, marca de tiempo: 0xe14b4abe
Código de excepción: 0xc...

**Comment by tim-tamm** [comment]
same issue (Windows Server 2019 + nextcloud client 3.5.4)

when nextcloud tries to "sync" virtual files (I assume downloading folder and file list to create local structure for virtual files) it runs into an error after a couple of minutes: "xy folder / folder ... Error updating metadata: Couldn't det pin state"

Nextcloud client repeats "syncing" again and after a few times it eventually crashes.

![image](https://user-images.githubusercontent.com/95210050/185739879-68cd609d-cc4a-4056-b29e-e70ce24bc669.png)
