### ISSUE TITLE
Fix-bug-invalid-modification-date inside docker

### ISSUE THREAD

**Issue by robertofabrizi** [nextcloud/desktop#4255]
Hello everyone, I'm trying to fix the mess that was caused by the modification date bug by using [this official guide](https://github.com/nextcloud/desktop/wiki/Fix-bug-invalid-modification-date), but it doesn't work when NC is a docker container (it doesn't have psql installed).

Is there another guide to follow?

Thank you,
RF

**Comment by isdnfan** [comment]
you can either install psql in the container (not best practice but for troubleshooting perfectly valid) or expose your DB port on the docker host and connect using your favorite tool. 

take a look at this SQL query (it's built on MariaDB mayby you need to adopt for Postgres). This collects invalid files and their versions with additional data from the database and could become starting point for further recovery steps.

https://github.com/nextcloud-gmbh/mtime_fixer_tool_kit/issues/23#issuecomment-1033117134

**Comment by robertofabrizi** [comment]
But exposing the postgres port doesn't mean that I can run the script from my laptop, as the script requires not just the db but also the nextcloud files, right?

./solvable_files.sh <path to storage folder without trailing /> <mysql|pgsql> <database host> <database user> <database password> <database name> <list|fix> <noscan|scan>
