### ISSUE TITLE
macOS: NextCloud Desktop menu shows on wrong screen in dual-screen setup 

### ISSUE THREAD

**Issue by BennyE** [nextcloud/desktop#4264]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When I click on the NextCloud menu icon, the Nextcloud menu shows below the icon on the same screen.

### Actual behaviour
When I click on the NextCloud menu icon on the external screen (which is on the right-hand side in my setup) the menu opens on the Macbook integrated (and open) screen instead of the screen/monitor where I clicked the icon. If I click on the item on the integrated screen, it properly shows up below the NextCloud Desktop icon.

Here is a screenshot of the behaviour (left-hand side is the integrated monitor of MBP, right-hand side is the external monitor):
![Nextcloud-Desktop-macOS_notes](https://user-images.githubusercontent.com/5174414/153570771-3a340e94-6379-417c-b2d5-61483d2ee96e.jpg)

Please note that this behaviour didn't exist in previous releases, unfortunately I can't tell you which version I ran before as I don't know it (sorry).

### Steps to reproduce
1. Use an external-monitor, in my case it is connected via HDMI
2. Click on the NextCloud menu icon on the external monitor
3. Notice the menu showing up on the Macbook integrated screen/monitor instead of the external monitor where the icon was clicked

### Client configuration
Client version:

Version 3.4.2 (macOS)

Operating system: 
macOS Big Sur (11.6.3)

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

[ncd-logs.zip](https://github.com/nextcloud/desktop/files/8047656/ncd-logs.zip)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by claucambra** [comment]
Can't reproduce on Catalina, which macOS version are you running? Thanks!

**Comment by BennyE** [comment]
> Can't reproduce on Catalina, which macOS version are you running? Thanks!

Hi @claucambra, macOS Big Sur (11.6.3)

**Comment by BennyE** [comment]
I just updated to macOS Big Sur (11.6.4) and after the upgrade/reboot, the NextCloud Desktop menu shows properly on both screens. I don't know if this was a case of "reboot fixed it", or something was corrected in macOS. I'll close the issue for now, but will continue to monitor the topic. If it comes back, I'll hopefully be able to tell you what caused it (e.g. resume, connect/reconnect of external monitor or whatever else) and open a new issue with reference to this one.

**Comment by ppaulek** [comment]
Same behavious here. macOS 11.6.4 (Big Sur) and NC Client 3.4.2. After disconnecting external display NC client window on complete wrong location on the internal screen and nothing clickable inside.
<img width="1275" alt="Bildschirmfoto 2022-02-23 um 20 08 04" src="https://user-images.githubusercontent.com/43202982/155390025-2d5f0b81-9acc-4cef-b6c5-f875e1cdb781.png">

**Comment by BennyE** [comment]
The issue also returned for me after disconnecting/connecting the external monitor.
Following the comment of @ppaulek, I think it makes sense to reopen this issue.

**Comment by claucambra** [comment]
I think this might be specific to setups with mixed scaling, as external displays have different scaling than internal (especially retina) displays
