### ISSUE TITLE
Nextcloud Client not Chunking (uploads over 100 MB fail)

### ISSUE THREAD

**Issue by metheis** [nextcloud/desktop#4271]
### Expected behaviour
The Nextcloud Client should chunk large files to 10MB so that large files can be uploaded even when the max upload size is smaller than the file size.

### Actual behaviour
When placing files larger than 100 MB into a synced folder, I am hitting cloudflare's 100 MB upload limit, even though I expected the nextcloud client to chunk requests to 10 MB in size per request. Cloudflare allows for uploads up to 100 MB per request. This issue has only happened over the past month or two.

### Steps to reproduce
1. Setup a nextcloud server with a domain in Cloudflare's network. Set the DNS record to proxy through Cloudflare
2. Setup the nextcloud client and connect to the server
3. Try to upload a file larger than 100 MB, and the upload will fail due to hitting the upload limit.

### Client configuration
Client version: 3.4.1

Operating system: Windows 11 22000.493

OS language: Englush (US)

Installation path of client: C:\Program Files\Nextcloud

### Server configuration
Nextcloud version: 22.2.3

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
The file I tried to upload is: mt_20220203.tar.gz
https://gist.github.com/metheis/d5e59e705f501438af82cf9ebfe2f7b1

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by metheis** [comment]
Keeping all else the same, I tried using an older client (3.3.6) and I'm able to upload large files. This definitely seems to have been introduced with recent client versions

**Comment by metheis** [comment]
Merging this issue with https://github.com/nextcloud/desktop/issues/4278

**Comment by metheis** [comment]
### Fix:

Hi everybody, thanks for finding this. I found simply setting the maximum chunk size to 50 MB (half of Cloudflare's 100 MB upload size limit) worked to resolve this issue.

I put together a short guide to fix this issue with the latest stable release ([3.4.4](https://github.com/nextcloud/desktop/releases/tag/v3.4.4), but should work on any client v3.4+). I tried to make it as accessible as possible to follow.

### Windows Fix

Press `Win+R` on your keyboard to open the `Run` application. Past the following in the dialog box:

`%APPDATA%\Nextcloud\nextcloud.cfg`

This will either ask you to pick an application to open `nextcloud.cfg` or will open in your default text editor (unless you have something else set to open .cfg files). If it asks you to pick an application, feel free to use Notepad or any other editor.

Add the following line under the `[General]` section:

`maxChunkSize=50000000`

Save the file, quit Nextcloud desktop, and start it again.

### MacOS Fix

Open a Finder window and press `Command+Shift+G` on your keyboard. This will bring up a 'Go to folder' window. Paste the following in the dialog box:

`$HOME/Library/Preferences/Nextcloud`

Open the `nextcloud.cfg` file. If you do not have a default editor for .cfg files, feel free to open the file with TextEdit.

Add the following line under the `[General]` section:

`maxChunkSize=50000000`

Save the file, quit Nextcloud desktop, and start it again.

### Linux Fix

Open a terminal window and edit the following file:

`nano $HOME/.config/Nextcloud/nextcloud.cfg`

Add the following line under the `[General]` section:

`maxChunkSize=50000000`

Save the file (`Ctl+o`, `Ctl+x`), then quit Nextcloud desktop, and start it again.

**Comment by cainnz** [comment]
@metheis hello there, I am running nextcloud in a docker container and behind a nginx proxy manager via Cloudflare. Question: where do I find the nextcloud.cfg inside nextcloud docker? I look everywhere but I cannot find it. I also look at my mounted "config" volume and cant find the file, if not, where should I entered the "maxChunkSize=5000000" so files above 100MB gets uploaded? thanks in advance

**Comment by brian8544** [comment]
> @metheis hello there, I am running nextcloud in a docker container and behind a nginx proxy manager via Cloudflare. Question: where do I find the nextcloud.cfg inside nextcloud docker? I look everywhere but I cannot find it. I also look at my mounted "config" volume and cant find the file, if not, where should I entered the "maxChunkSize=5000000" so files above 100MB gets uploaded? thanks in advance

In case you still have this issue; since it's a client-side configuration option, for Windows it will be in: (%AppData%\Roaming\Nextcloud\nextcloud.cfg).

**Comment by EnderArchery** [comment]
I'm running into this problem again with nextcloud-client 3.6.0

**Comment by primetime-sudo** [comment]
This was the fix for me in 2024, Windows version 3.12.3

**Comment by primetime-sudo** [comment]
> ### Fix:
> 
> Hi everybody, thanks for finding this. I found simply setting the maximum chunk size to 50 MB (half of Cloudflare's 100 MB upload size limit) worked to resolve this issue.
> 
> I put together a short guide to fix this issue with the latest stable release ([3.4.4](https://github.com/nextcloud/desktop/releases/tag/v3.4.4), but should work on any client v3.4+). I tried to make it as accessible as possible to follow.
> ### Windows Fix
> 
> Press `Win+R` on your keyboard to open the `Run` application. Past the following in the dialog box:
> 
> `%APPDATA%\Nextcloud\nextcloud.cfg`
> 
> This will either ask you to pick an application to open `nextcloud.cfg` or will open in your default text editor (unless you have something else set to open .cfg files). If it asks you to pick an application, feel free to use Notepad or any other editor.
> 
> Add the following line under the `[General]` section:
> 
> `maxChunkSize=50000000`
> 
> Save the file, quit Nextcloud desktop, and start it again.
> ### MacOS Fix
> 
> Open a Finder window and press `Command+Shift+G` on your keyboard. This will bring up a 'Go to folder' window. Paste the following in the dialog box:
> 
> `$HOME/Library/Preferences/Nextcloud`
> 
> Open the `nextcloud.cfg` file. If you do not have a default editor for .cfg files, feel free to open the file with TextEdit.
> 
> Add the following line under the `[General]` section:
> 
> `maxChunkSize=50000000`
> 
> Save the file, quit Nextcloud desktop, and start it again.
> ### Linux Fix
> 
> Open a terminal window and edit the following file:
> 
> `nano $HOME/.config/Nextcloud/nextcloud.cfg`
> 
> Add the following line under the `[General]` section:
> 
> `maxChunkSize=50000000`
> 
> Save the file (`Ctl+o`, `Ctl+x`), then quit Nextcloud desktop, and start it again.

This was the fix for me in March 2024, Windows client 3.12.3

**Comment by Doooder** [comment]
> ### Fix:
> .....
> ### MacOS Fix
> 
> Open a Finder window and press `Command+Shift+G` on your keyboard. This will bring up a 'Go to folder' window. Paste the following in the dialog box:
> 
> `$HOME/Library/Preferences/Nextcloud`
> 
> Open the `nextcloud.cfg` file. If you do not have a default editor for .cfg files, feel free to open the file with TextEdit.
> 
> Add the following line under the `[General]` section:
> 
> `maxChunkSize=50000000`
> 
> Save the file, quit Nextcloud desktop, and start it again.

I cannot seem to find the nextcloud.cfg on any of my Macs.  They are Apple Silicone if that makes a difference.  So if anyone knows where I can fine this setting on my Mac it would be much appreciated!

**Comment by Doooder** [comment]
Ok, I'm just gonna put this here in case someone else with a Mac comes here with the same question.  

Viewing the hidden ~/Library folder

- The hidden '~/Library' folder is located in the 'Finder's' top menu. 

- To view these, go into '**Finder**' and click on '**Go**' on the menu bar. 

- Next, hold down the '**Option**' key on your **_keyboard_**. 

- You'll now see the hidden '~/Library' listed as '**Library**' on the' Go' menu.  

- Click on it to see the content.

**Comment by S1ngl3-x** [comment]
It's still an issue on linux, but works fine on android.

The upvoted answer rescued me after 3 days of blind troubleshooting.

**Comment by S1ngl3-x** [comment]
It seems like it can be fixed on the server side for all clients as well. Add line to `config.php `

`'max_chunk_size' => 78643200,  // Set to approximately 75MB`


So far all good on my side.

**Comment by coding-ray** [comment]
> @metheis hello there, I am running nextcloud in a docker container and behind a nginx proxy manager via Cloudflare. Question: where do I find the nextcloud.cfg inside nextcloud docker? I look everywhere but I cannot find it. I also look at my mounted "config" volume and cant find the file, if not, where should I entered the "maxChunkSize=5000000" so files above 100MB gets uploaded? thanks in advance

Thanks @cainnz  for the clue of Cloudflare.

Cloudflare [stated](https://developers.cloudflare.com/cache/concepts/default-cache-behavior/#upload-limits) that the maximum body size limit behind Cloudflare proxy has been 100MB for free tier since [2020](https://community.cloudflare.com/t/maximum-upload-size-is-limit/418490/2) or earlier. The upload limit for each tier is as follows.

| Free | Pro | Business | Enterprise |
| -- | -- | -- | -- |
| 100 MB | 100 MB | 200 MB | 500 MB (default) |

To bypass the limit, @metheis's [solution](https://github.com/nextcloud/desktop/issues/4271#issuecomment-1159578065) still works on Nextcloud client 3.13.3.

Another solution is to unproxy DNS records that point to Nextcloud server(s).

By the way, if someone cannot upload files larger than 200 MB or 500 MB, they may hit the limit of Cloudflare as well.

**Comment by hermeneuticlens** [comment]
Can confirm this is still an issue for Linux and Windows. Deployed NextCloud Server official Docker. With default settings, any files over 100MB fail to upload, server says "files not found", which is a very unintuitive error message. Added the lines to the local config file and the issues are fixed for both Linux and Windows.

**Comment by S1ngl3-x** [comment]
Perhaps conceptually correct solution would be to expose server ENV Variable "`max_chunk_size`"? Where documentation would mention it's needed to change it to a specific value for some proxies like cloudflared=78643200?

**Comment by Permanently** [comment]
Alternatively, there could just be an option under the Advanced section under Nextcloud settings - seems a bit too common of an issue to be having text configuration files as the solution

**Comment by punkyard** [comment]
maxChunkSize=50000000 is not fixing it for me

**Comment by Potato-007** [comment]
maxChunkSize is only one of many things that need to be adjusted.

you have to continue editing the php config

in my case on macOS this is the path, but it will be differ on yours

sudo pico /usr/local/etc/php/8.3/php.ini

# change
memory_limit = 512M
upload_max_filesize = 16G
post_max_size = 16G

# if using opcachen, then uncomment and change from 8 to 64
opcache.interned_strings_buffer

**Comment by punkyard** [comment]
hi @Potato-007 
and thank you so much for your reply

there is no web server installed on my local machine (macos monterey) so there is no php in /usr/local/etc
my NC instance is online on debian, i'm using NC desktop and it won't sync files bigger than 10Mb

**Comment by Potato-007** [comment]
the reason for your trouble @punkyard is that php is not configured properly - as in my previous post on server side.

php is not in use on client side. contact the admin who manages the server

**Comment by punkyard** [comment]
hi @Potato-007 
I'm the admin and we are using AiO latest 960
do you mean my .yaml is not well configured?

or Shall I warn the AiO about this?

**Comment by Potato-007** [comment]
also, make sure to read the related guide:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html

**Comment by NeZios** [comment]
> > ### Fix:
> > .....
> > ### MacOS Fix
> > Open a Finder window and press `Command+Shift+G` on your keyboard. This will bring up a 'Go to folder' window. Paste the following in the dialog box:
> > `$HOME/Library/Preferences/Nextcloud`
> > Open the `nextcloud.cfg` file. If you do not have a default editor for .cfg files, feel free to open the file with TextEdit.
> > Add the following line under the `[General]` section:
> > `maxChunkSize=50000000`
> > Save the file, quit Nextcloud desktop, and start it again.
> 
> I cannot seem to find the nextcloud.cfg on any of my Macs. They are Apple Silicone if that makes a difference. So if anyone knows where I can fine this setting on my Mac it would be much appreciated!

`nextcloud.cfg` localization file in MacOS is now `/Users/youruser/Library/Preferences/Nextcloud/ ` on Apple Silicon Mac

**Comment by yaxirhuxxain** [comment]
This was a partial fix for me in June 2025 using Windows client 3.16.6 and the latest Docker image from linuxserver/nextcloud.

What worked in my case:

**Step 1:** On the server side, add the following to `config.php`:
```php
'files.chunked_upload.max_size' => 40000000,
```

**Step 2:** Update your Windows client config file (%APPDATA%\Nextcloud\nextcloud.cfg) with: 

```
[General]
maxChunkSize=40000000
```

Note: The exact value `40000000` in both places (`config.php` and `nextcloud.cfg`) is crucial. 

Hope this helps someone. Cheers!

**Comment by davide-96** [comment]
Unfortunately none of the suggested workarounds did the trick for me. However, what I found reading the latest server documentation was the option [files.chunked_upload.max_parallel_count](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#files-chunked-upload-max-parallel-count), which defaults to 5 max parallel tasks. Setting this value to 1 worked for me. I think this parallelism does in fact exceed somehow the maximum upload limit from CF when setting the 'files.chunked_upload.max_size' to 100MB (default).

**Comment by ghost** [comment]
client uploads fail on all platforms because on server side php is not configured properly for nextcloud needs. Nextcloud uses php as an underlying motor.
Depending on your platform (server side) you have to edit the php config file - usually php.ini - and make these changes:

memory_limit = 512M
upload_max_filesize = 16G
post_max_size = 16G

also if you are using Redis for caching change these too:

# only do this after installing and enabling Redis !!!
# uncomment, change and add...

opcache.interned_strings_buffer

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256M
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=32530
opcache.save_comments=1
opcache.revalidate_freq=60
opcache.jit=1255
opcache.jit_buffer_size=128M

if you have multiple versions of php installed, check first which is used by apache first, and change the config of that php config file.

**Comment by weasam** [comment]
> It seems like it can be fixed on the server side for all clients as well. Add line to `config.php `
> 
> `'max_chunk_size' => 78643200, // Set to approximately 75MB`
> 
> So far all good on my side.

Hope this could work globally for all user,  not a easy task to teach all user how to change configiguration on their devices

**Comment by S1ngl3-x** [comment]
> > It seems like it can be fixed on the server side for all clients as well. Add line to `config.php `
> > `'max_chunk_size' => 78643200, // Set to approximately 75MB`
> > So far all good on my side.
> 
> Hope this could work globally for all user, not a easy task to teach all user how to change configiguration on their devices

Ofc , the server configuration isn't specific to a single user.
