### ISSUE TITLE
Syncing status shown all the time (3.4.2)

### ISSUE THREAD

**Issue by jose1711** [nextcloud/desktop#4275]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Sync of files should eventually stop and blue sync-in-progress icon should turn to green checkmark.

### Actual behaviour
Syncing never stops, the client is reporting the following all the time:
![obrázok](https://user-images.githubusercontent.com/1406222/153746924-ce6b3802-e76c-4881-9078-ff9717bbaaa4.png).
However after client's restart the files seem to be transferred to client.

### Steps to reproduce
1. Run nextcloud client
2. Watch how the icon becomes
![obrázok](https://user-images.githubusercontent.com/1406222/153746945-01acb21e-379c-4e31-bc26-326199a6c4ff.png)

### Client configuration
Client version: 3.4.2
Operating system: Arch Linux x86_64
OS language: sk, but set to `C` for purposes of this report
Qt version used by client package (Linux only, see also Settings dialog): 5.15.2
Client package (From Nextcloud or distro) (Linux only): distro package `nextcloud-client 2:3.4.2-1`

Installation path of client:
`/usr/share/nextcloud`

### Server configuration
Nextcloud version: `nextcloud-23.0.1-r0`
Storage backend (external storage): local storage

### Logs
1. Client logfile: 
The following keeps repeating every 30 seconds in client log
```
2022-02-13 10:32:40:541 [ info nextcloud.gui.folder.manager /build/nextcloud-client/src/nextcloud-client/src/gui/folderman.cpp:867 ]:	Etag poll timer timeout
2022-02-13 10:32:40:541 [ info nextcloud.gui.folder.manager /build/nextcloud-client/src/nextcloud-client/src/gui/folderman.cpp:871 ]:	Folders to sync: 1
2022-02-13 10:32:40:541 [ info nextcloud.gui.folder.manager /build/nextcloud-client/src/nextcloud-client/src/gui/folderman.cpp:881 ]:	Number of folders that don't use push notifications: 1
2022-02-13 10:32:40:541 [ info nextcloud.gui.folder.manager /build/nextcloud-client/src/nextcloud-client/src/gui/folderman.cpp:898 ]:	Run etag job on folder OCC::Folder(0x55976bb4fda0)
2022-02-13 10:32:40:541 [ info nextcloud.gui.folder.manager /build/nextcloud-client/src/nextcloud-client/src/gui/folderman.cpp:904 ]:	Can not run etag job: Sync is running
```

2. Web server error log: n/a

3. Server logfile: nextcloud log (data/nextcloud.log): n/a

**Comment by jose1711** [comment]
> Hi, maybe related to my complaint...? #4260

Could be related, at least indirectly. Note that I get this on Linux, different version of client and also the message in the log is slightly different.

**Comment by jose1711** [comment]
Tested with current master - the issue is present as well.

**Comment by jose1711** [comment]
Went back to version 3.3.6 and all is working fine there.

**Comment by joholm2** [comment]
> > Hi, maybe related to my complaint...? #4260
> 
> Could be related, at least indirectly. Note that I get this on Linux, different version of client and also the message in the log is slightly different.

I think this part of your log...
![image](https://user-images.githubusercontent.com/61330925/153847861-a2a1e8d8-95a8-48a2-94ca-bacd1a196052.png)

... matches this part of mine...
![image](https://user-images.githubusercontent.com/61330925/153847982-86b3ab0f-750a-4979-b8cc-d4aca838dca3.png)

...it's just that I have 7 sync folders and you have 1.

**Comment by jose1711** [comment]
Even with the version 3.3.6 there were some strange things going on - a bunch of empty files were keep coming in and conflicts appeared in the client window. Additionally I found some pending uploads and conflicts (even though the local and remote files were the same) in Android client. What I did then:
  - stopped desktop client
  - removed empty files from filesystem
  - removed empty files from nextcloud via browser
  - sorted out conflicts/issues in Android client
  - started the client

No new empty files appeared so I tried update to the latest version (3.4.2) and that finally am in sync. Since I no longer have an issue, closing.

**Comment by apg1980** [comment]
The issue is still present. 
![image](https://user-images.githubusercontent.com/9514965/158055375-3c9a24e9-b525-4fee-8054-1e98f5ae5575.png)
![image](https://user-images.githubusercontent.com/9514965/158055392-19793be6-f8e0-4cf5-9542-5682651beb9e.png)

**Comment by joholm2** [comment]
We upgraded our server to 23.0.2 and now the client seems to work fine...

**Comment by apg1980** [comment]
i am already on 23.0.2

**Comment by apg1980** [comment]
good morning, i tryed several things, repair of the client.
after restart the client, iits synching forever for small files as well.
![grafik](https://user-images.githubusercontent.com/9514965/158545473-48886db5-2a1a-4e49-bad7-f294c0eb62ea.png)
