### ISSUE TITLE
MacOS Limited Permissions

### ISSUE THREAD

**Issue by ghost** [nextcloud/desktop#428]
The Sync app only works if installed with admin permissions.

Users in networks with limited permissions such as some schools or corporations, aren't able to sync their files through the MacOS app. A version of NextCloud MacOS that does not require admin privileges would therefore be very useful. Ideally a simple app that can be dropped into ~/Applications would solve this.

Dropbox is providing such installation method.

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently, there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
