### ISSUE TITLE
(Mac) Client not removing E2E Passphrase after removing account and uninstalling Client

### ISSUE THREAD

**Issue by alexkyb** [nextcloud/desktop#4282]
(I am unsure if I am posting the problem correctly here. Had not found a better place to go.)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Nextcloud Desktop Client (for Mac) removes the E2E Passphrase if the account is removed/ the client is uninstalled.

### Actual behaviour
User-Account was removed from client, and the client was uninstalled. After a new setup (installation and login) the E2E prompt was expected. But was not shown. In the settings menu the old E2E-passphrase was still persistent.

### Steps to reproduce
1. Remove account from the Client
2. Uninstall Mac Client
3.  Reinstall Client and login to account
4. E2E-Prompt is not shown, old Passphrase is still in the settings menu

### Client configuration
Client version: 3.4.2

Operating system: macOs Monterey 12.2.1

OS language: German

Installation path of client: MacOS Drive / Programmfolder

### Server configuration

Nextcloud version: 23.0.0.10

End-to-End Encryption Plugin: 1.8.1

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by alexkyb** [comment]
For People encountering the similar Problem:

The E2E-Passphrase is like the login settings saved in the local Keychain Access-App.
After logout the Account is deleted, the Passphrase persists.
You can easily remove the passphrase in this app by yourself.

**Comment by eibex** [comment]
This issue is not limited to Mac, it happens on Windows too. (unless you clean Appdata/Roaming iirc)

**Comment by eibex** [comment]
still relevant

**Comment by eibex** [comment]
> still relevant

**Comment by eibex** [comment]
Most useless action.
