### ISSUE TITLE
Open Folder to Enhance Conflict Solving

### ISSUE THREAD

**Issue by internettechnik** [nextcloud/desktop#4286]
Allow to navigate to the folder where sync conflicts are reported.

It is much faster and easier for users, if they can open a folder, where conflicts are reported to inspect and solve the conflict (e.g. after reviewing the - possibly non-plaintext - files).

Reproduce: Create a conflict and find a exclamation mark on the left side of reported sync conflicts. Unfortunately, users have no way to quickly open the folder containing both the (local and server) files (one of them renamed/marked as conflicting).

**Comment by camilasan** [comment]
With the current version 3.5.1, if you click on the conflict notification message it open the file conflict dialog.
