### ISSUE TITLE
Enable updater check

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4291]
- [ ] enable updater check by default (opt-out)
  - on our official nextcloud.com downloads
  - on branded clients
- [ ] make sure to inform Linux distributions to disable it
- stable/beta selection 
  - [ ] enable on our official nextcloud.com downloads
  - [ ] disable it on branded clients, Linux distributions

**Comment by digitalcircuit** [comment]
I installed the Nextcloud 3.5.0 desktop client [from the Nextcloud Ubuntu PPA today](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client ) (on Kubuntu 20.04), and the updater section is shown (previously, it was hidden).  As the PPA already provides automatic system-integrated updates, maybe `BUILD_UPDATER` needs to be set to `OFF` for PPA builds?

**Comment by tobiasKaminsky** [comment]
As written above, it is default enabled, and Linux distributions need to disable/opt out it when they do not need it.
I suggest that you open up a bug report on Ubuntu.
