### ISSUE TITLE
Interaction with the interface is usually not possible.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [nextcloud/desktop#4294]
### Expected behaviour
Be able to interact with the interface of 'http://github.com/nextcloud/desktop'.

### Actual behaviour
Interaction is barely possible, because the interace does not accept most response, and what response is accepted is accepted so slowly that utilisation of the interface is barely possible.

### Steps to reproduce
1. Install 'nextcloud' from 'http://src.fedoraproject.org/rpms/nextcloud', or install 'http://dl.flathub.org/repo/appstream/com.nextcloud.desktopclient.nextcloud.flatpakref' of 'http://github.com/flathub/com.nextcloud.desktopclient.nextcloud'.
2. Authenticate the account of the utiliser.
3. Attempt to interact with the subsequent white-and-blue window.

### Client configuration
Client version:

```
PS /> dnf info nextcloud  

Available Packages
Name         : nextcloud
Version      : 22.1.0
Release      : 2.fc36
Architecture : noarch
Size         : 111 M
Source       : nextcloud-22.1.0-2.fc36.src.rpm
Repository   : rawhide

PS /> flatpak info com.nextcloud.desktopclient.nextcloud

          ID: com.nextcloud.desktopclient.nextcloud
         Ref: app/com.nextcloud.desktopclient.nextcloud/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.4.2
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 183.1 MB
     Runtime: org.kde.Platform/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: 467207dfec5e3e6980b53866e182f3bcb80d89802286f5fe6b400b436355ccb0
      Parent: 93031e4a9f669844a463abb6c9621c0422c419f0d6459bdfb5351a6abc065fe2
     Subject: Update desktop.git to 3.4.2 (4742fb39)
        Date: 2022-01-27 16:52:34 +0000
```

Operating system: 'http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso'.
```
PS /> uname -a
Linux BEEDELL-ROKEJULIANLOCKHART 5.17.0-0.rc4.96.fc37.x86_64 #1 SMP PREEMPT Mon Feb 14 12:58:18 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
OS language:
```
PS /> localectl status
   System Locale: LANG=en_GB.UTF-8
       VC Keymap: gb
      X11 Layout: gb
```
Qt version used by client package (Linux only, see also Settings dialog): Not able to acquire.
Client package (From Nextcloud or distro) (Linux only): Request not understood.
Installation path of client: Not known.

### Server configuration
Nextcloud version: 22.1.0
Storage backend (external storage): Not known.

### Logs
1. Client logfile: Not possible to adequately acquire, because the log-window crashed and the alternative did not appear to produce any files.
```
PS /> nextcloud --logdebug --logfile log.txt
QSocketNotifier: Can only be used with threads started with QThread
PS /> nextcloud --logdebug --logwindow
QSocketNotifier: Can only be used with threads started with QThread
QSocketNotifier: Can only be used with threads started with QThread
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
error: Invalid fd passed
```
2. Web server error log: Request not understood.
3. Server logfile: nextcloud log (data/nextcloud.log): Not able to acquire.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
However, intraction with 'http://user-images.githubusercontent.com/42837531/154499820-2c1b17f5-2e68-4d47-a643-028d5fc62712.png', which presents itself as 'com.nextcloud.desktopclient.nextcloud' via 'http://user-images.githubusercontent.com/42837531/154500141-d4dec48c-5975-4751-997f-15bce64fc325.png' is possible if the window invoked via 'xdg-desktop-portal' of 'http://src.fedoraproject.org/rpms/firefox'.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@github-actions, what more must I provide? Do not demand improvement without specification of what is necessary to adhere to that demand.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@github-actions, observe "http://github.com/nextcloud/desktop/issues/4294#issuecomment-1071129463".

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Observe "https://github.com/nextcloud/desktop/issues/4294#issuecomment-1071129463".

**Comment by claucambra** [comment]
Hi @BEEDELLROKEJULIANLOCKHART is this bug still present on the latest version of the client? Please try the AppImage if possible, thanks

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@claucambra, the problem is not present.
