### ISSUE TITLE
Handle "Edit locally" from web

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4297]
- user is in web UI
- finds a file and wants to open it locally (e.g. Collabora is not sufficient, Inkscape for SVG, etc.)
- user clicks "edit locally"
- special link type (tbd: nc://open/$account@Server/$remotePath)

On Desktop:
- client listens to this link
- client opens file if already synced, if not syncs it first, then opens it via native file handling mechanism)
- if account not set up or file not syncable (e.g. folder is excluded by "selective sync") show an understandable error message
- file is being locked while editing this file

**Comment by tobiasKaminsky** [comment]
CC @juliushaertl @eneiluj

**Comment by camilasan** [comment]
1. user clicks "edit locally" - is this in the web ui?
2. special link type (tbd: nc://open/$account/$fileId)?
3. client listens to this link - how do you mean?

**Comment by tobiasKaminsky** [comment]
1. yes, in web.

The idea is to "transfer" the info about the file to open to Desktop client, so that our client then can directly open this file.

Scenario is that you browse online through a huge hierarchy of files and find e.g. a svg image you want to edit on computer.
Instead of redoing the whole browsing to file locally again, you then can click "edit locally".

**Comment by allexzander** [comment]
@claucambra Later I am going to need some help to implement this on mac OS. It seems to be fairly easy for you to do https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x but, of course, I am not a mac expert to be 100% about this.
Most of the code is going to be cross-platform, will just need to add a custom URI handler on mac to trigger the client's exe and pass the link to an **argc**.

**Comment by allexzander** [comment]
In case we'll need to have a customizable URL scheme (something other than **nc**), we could send the desired protocol from the desktop client to the server to make sure the server will be creating URLs using the desired scheme.

As an improvement, we could also use **capabilities** to let the desktop client know this feature is supported.

**Comment by mgallien** [comment]
@tobiasKaminsky are we sure we want to *only* display an error message in case the user would have to modify their selective sync settings ?
that is quite the opposite of helping the user saves time by doing edit locally
not my call but I suppose that the desktop client could figure out which settings need to be modified and could offer to help the user by doing it all on its own

**Comment by tobiasKaminsky** [comment]
I have no idea how many users really use selective sync.

So idea would be:
- clients knows that file is not synced
- shows: file is not yet synced. Do you want to sync the file and its folder?
  - yes: depending on folder size this takes very long, user waits, then it is shown <-- can the file in question synced as first?
  - no: nothing happens

@allexzander how much time would this be?

**Comment by allexzander** [comment]
@tobiasKaminsky I'd say 2-8 hours to implement this. It all depends on if the design team will want other changes after we change this part. Likely, some other design issues will arise. What we are missing now, is the ability to sync just one file. That would solve these design difficulties we have now.

**Comment by claucambra** [comment]
My two cents, but if a user is going to edit something locally it is implicit that the user also wants this file to be stored locally, even if only temporarily. Maybe a smarter way of doing this would be to show a notification at the system level and the tray that the file is going to be synced, and then have an action in the activity tray entry/notification to unsync the file that users can trigger when they are done with it

**Comment by tobiasKaminsky** [comment]
The problem for now is that we cannot only sync this one file, at least not within folder hierarchy.

So for now, I think we keep it like this.
I will take this to next planing meeting as feedback and then we can
- enhance this
- wait for first feedback of users and then do it
- keep it like this
