### ISSUE TITLE
Automatic Update Option Missing 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#4299]
![image](https://user-images.githubusercontent.com/59488153/154564279-60f1de18-2a8b-47a2-b248-fd6a86e262c2.png)

**Comment by claell** [comment]
Same for me, happened since 3.4.1. Is this wanted?

**Comment by andyxheli** [comment]
@claell is this release to https://github.com/nextcloud/desktop/issues/4301 ?

**Comment by andyxheli** [comment]
Just updated to 3.4.3 and looks like the update option is back. @claell can you also confirm

https://github.com/nextcloud/desktop/releases/tag/v3.4.3
