### ISSUE TITLE
Design: Error shows old owncloud logo

### ISSUE THREAD

**Issue by k1l1** [nextcloud/desktop#43]
<img width="356" alt="bildschirmfoto 2017-11-19 um 10 44 38" src="https://user-images.githubusercontent.com/20491467/32989465-f2e42e82-cd16-11e7-90ec-2a652562f2e3.png">

**Comment by michaelstingl** [comment]
Related: https://github.com/nextcloud/client_theming/issues/79

**Comment by camilasan** [comment]
Do you still have this issue @k1l1 with the client 2.3.3?

**Comment by rullzer** [comment]
Fixed on master
