### ISSUE TITLE
Nextcloud macOS app fails to launch

### ISSUE THREAD

**Issue by pferrel** [nextcloud/desktop#4300]
I have Nextcloud 23.0.1 running and installed the sync app on my macOS laptop.

It started syncing and froze so that I could not move the window or cancel its operations.

I rebooted but now the app refuses to launch. When i look in the macOS Activity Monitor I see the Nexcloud App and the headless nextcloud agent.

I have tried removing the app entirely, rebooting so there was no Nextcloud stuff running, and reinstalling but I can never get the GUI for Nexcloud sync app to launch now.

Any ideas how to get out of this situation?

**Comment by ctkcoding** [comment]
I am having a similar issue if not the same one. I upgraded to the latest version and it loads in my toolbar but when I click the toolbar icon it crashes and disappears from the toolbar without opening the toolbar popup window like previous versions, or a app window either.

**Comment by claucambra** [comment]
Could you attach the desktop client's logs to this issue? This will help us narrow down what could be going on here. Thanks!

**Comment by muffl0n** [comment]
I'm experiencing a similar behaviour. When trying to start the client via terminal, I get a segmentation fault
```
-> % /Applications/nextcloud.app/Contents/MacOS/nextcloud --logwindow
[1]    8073 segmentation fault  /Applications/nextcloud.app/Contents/MacOS/nextcloud --logwindow
```
Setting `OWNCLOUD_CORE_DUMP=1` does not produce a core dump:
```
-> % OWNCLOUD_CORE_DUMP=1 /Applications/nextcloud.app/Contents/MacOS/nextcloud
[1]    9902 segmentation fault  OWNCLOUD_CORE_DUMP=1 /Applications/nextcloud.app/Contents/MacOS/nextcloud

-> % l
total 0
drwxr-xr-x  2 svs   wheel    64B Mar  1 09:53 .
drwxrwxrwt  7 root  wheel   224B Mar  1 09:53 ..
```

**Comment by guardiande** [comment]
See #4500 where I had the same symptoms and was able to resolve it.

**Comment by pencaksilat** [comment]
Same issues with new one. I've downloaded correct package (previews version) here https://download.nextcloud.com/desktop/releases/Mac/Installer/
