### ISSUE TITLE
Double check update mechanism

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4301]
When releasing 3.4.3 please check if update mechanism works
Community
- [ ] Linux
- [x] MacOS
- [x] Windows

Branded clients
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by joshtrichards** [comment]
v3.4.3 shipped awhile ago - https://github.com/nextcloud/desktop/releases/tag/v3.4.3

Also indications are auto update functionality was restored: https://github.com/nextcloud/desktop/issues/4299#issuecomment-1053670684

Closing.
