### ISSUE TITLE
Files showing as last changed "365 days ago" not being updated in server

### ISSUE THREAD

**Issue by Mark-Booth** [nextcloud/desktop#4309]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When a file is updated locally, I would expect it to be updated on the server.

### Actual behaviour
When a file is updated locally, it may not be updated on the server.

When this happens, the "File activity" pop up shows "You changed ... 365 days ago".

### Steps to reproduce
1. Trigger whatever it is that causes this.
2. Update the affected file.
3. Watch it not get uploaded to the server.
4. Check the "File activity" pop-up to see "You changed ... 365 days ago".

### Client configuration
Client version:

- 1x Workstation running Nextcloud Desktop Client Version 3.4.2 (KDE). Flatpak automatically updated to 3.4.2, so I didn't have the option to stay with 3.4.1.
- 2x PCs running Nextcloud Desktop Client Version 3.4.1 (Windows). I did not upgrade to 3.4.2 as the server admin had seen this problem after upgrading to 3.4.2 and didn't want me to fall foul of it too. 

Operating system:

- Red Hat Enterprise Linux Workstation 7.9
- Windows 10 Professional 21H2
- Windows 10 Enterprise 21H1

OS language: English (British)

Qt version used by client package (Linux only, see also Settings dialog): org.kde.Platform-3.10.0-1160.49.1.el7.x86_64

Client package (From Nextcloud or distro) (Linux only):
```
$flatpak info com.nextcloud.desktopclient.nextcloud/x86_64/stable
Ref: app/com.nextcloud.desktopclient.nextcloud/x86_64/stable
ID: com.nextcloud.desktopclient.nextcloud
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2022-01-27 16:52:34 +0000
Subject: Update desktop.git to 3.4.2 (4742fb39)
Commit: 467207dfec5e3e6980b53866e182f3bcb80d89802286f5fe6b400b436355ccb0
Parent: 93031e4a9f669844a463abb6c9621c0422c419f0d6459bdfb5351a6abc065fe2
Location: /home/####/.local/share/flatpak/app/com.nextcloud.desktopclient.nextcloud/x86_64/stable/467207dfec5e3e6980b53866e182f3bcb80d89802286f5fe6b400b436355ccb0
Installed size: 183.1 MB
Runtime: org.kde.Platform/x86_64/5.15-21.08
Sdk: org.kde.Sdk/x86_64/5.15-21.08
```

Installation path of client: See Location above (user name redacted here, it is in the private gist if you really need to know it)

### Server configuration

Nextcloud version: 23.0.0

Storage backend (external storage): Local ZFS volume

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: https://gist.github.com/Mark-Booth/094cc6bebbf137c8664c709c82ff0cd4

The file which failed to upload had the following `stat` times:
```
Access: 2022-02-21 17:11:39.227888000 +0000
Modify: 2022-02-21 17:11:39.000000000 +0000
Change: 2022-02-21 17:11:39.208858000 +0000
```

Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log: I can ask for it later if needed.

3. Server logfile: nextcloud log (data/nextcloud.log): I can ask for it later if needed.

### Description

For a while now, I've been having problems with my NextCloud clients not syncing some files with the server properly.

When I change a file, the client quickly shows "Syncing" and then goes to "All synced" but does not show that the file has been uploaded to the server, and when I check the web client, I see only the old version of the file.

If I force an upload by dragging the updated file into the web browser, I see it updated there, but other clients don't download this updated file.

If I duplicate a file, giving it a new name, that file doesn't get uploaded either, but if I duplicate it, rename it and then force an upload by dragging the duplicated file into the web browser, I do see it downloaded by the other clients.

**Comment by Mark-Booth** [comment]
Is there any further information that I can provide to help solve this issue?

**Comment by tflidd** [comment]
1. Other user on this server can sync with their sync client?
2. The synced folders are shared folder? If yes, does it work with different ones
3. Your folder contains `&` and some other special characters. Others had problems synchronizing when they had spaces or points in the beginning or end of filenames and folders. Can you try with a special-character free full path of files?
4. Direct access via webdav (e.g. winscp on windows) works?
