### ISSUE TITLE
Folder with Name "Entwurf 23.2." does not get synced

### ISSUE THREAD

**Issue by tstreibl** [nextcloud/desktop#4310]
### Expected behaviour
Changes in the web interface should be reflected in the desktop client

### Actual behaviour
newly created folder with this specific name does not get synced

### Steps to reproduce
1. Create Folder with the name "Entwurf 23.2." in the web interface
2. Fill folder with files
3. check if desktop sync clients syncs the folder => folder won't show up

### Client configuration
Client version:
Tested with 3.3.6 and 3.4.2 

Operating system: Windows 10

OS language: German

## Comment
probably the dot at the end of the folder name is messing up things. I didn't dig into this.

**Comment by claucambra** [comment]
That's right, file and folder names with a period at the end of them are not synchronised by the desktop client as these cause issues on Windows.

**Comment by PhilippSchlesinger** [comment]
@claucambra there should be a warning and a resolution dialog like in https://github.com/nextcloud/desktop/pull/3760
