### ISSUE TITLE
Some PDF files under 1MB aren't getting synced and no error visible in the activity list

### ISSUE THREAD

**Issue by whimboo** [nextcloud/desktop#4315]
### Expected behaviour
The desktop client should always sync files with the server when they are created on the disk.

### Actual behaviour
The client seems to ignore some files which are under 1MB and doesn't sync them. For brief of a second I can see the blue activity indicator in the Finder, which then hides quickly. Also there is no failure / error listed in the activity list nor a notification shown. That means files won't get synced and will be missed. IMHO this is a serious data loss issue.

### Steps to reproduce
1. Save the [test.pdf](https://github.com/nextcloud/desktop/files/8146573/test.pdf) to a NextCloud shared folder
2. Observe that the file is not getting synced
3. When enlarging the file with additional content so that it reaches 1MB it will be synced

### Client configuration
Client version: 3.4.2
Operating system: MacOS 12.2.1 [Monterey]
OS language: English
Installation path of client: /Applications/Nextcloud.app

### Server configuration
Nextcloud version: 23.0.1
Storage backend (external storage): SSD (ext4)

### Logs
1. Client logfile: [logs.zip](https://github.com/nextcloud/desktop/files/8146631/logs.zip) (sorry but I had to strip the logs given that privacy related content would be transmitted otherwise)
2. Web server error log: none at this point given that DietPi doesn't enable logs on the RasperryPi
3. Server logfile: nextcloud log (data/nextcloud.log): Same as above.

**Comment by azukaar** [comment]
#4201

**Comment by whimboo** [comment]
I actually saw an update notice on the server to version 23.0.2 yesterday. After applying this update the use case that I layed out above seems to work fine now. I did several tries and none of them failed.

Nevertheless I will keep my eyes open for it and will reopen in case it happens again.
