### ISSUE TITLE
File synchronization and sharing

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/desktop#4317]
### Steps to reproduce
1. Upload files.
2. Share files with another user.
3. Turn off Nextcloud Client.
4. Restart Nextcloud Client.

When Nextcloud Client is restarted, the application resyncs the files. The contents of the files for sync is fake and negative:

![obraz](https://user-images.githubusercontent.com/47037905/155883188-27b3701d-6d89-4c4f-95e2-9d2ddc65e574.png)

### Client configuration
Client version: 3.4.2
Operating system: Win 10

### Server configuration
Nextcloud version: 23.0.1

**Comment by andyxheli** [comment]
Also I think thy released a patch on NC 23.0.2

**Comment by Valdnet** [comment]
@andyxheli I updated Nextcloud Client to 3.4.3 and Nextcloud to 23.0.2. I will test :wink:.
