### ISSUE TITLE
Broken link Desktop Client 3.4.3 

### ISSUE THREAD

**Issue by dr4thmos** [nextcloud/desktop#4318]
Trying to download the desktop client 3.4.3 AppImage return 404
https://github.com/nextcloud/desktop/releases/download/v3.4.3/Nextcloud-3.4.3-x86_64.AppImage

**Comment by utolosa002** [comment]
[.AppImage](https://github.com/nextcloud/desktop/releases/download/v3.4.3/Nextcloud-3.4.3-x86_64.AppImage) is missing

**Comment by moppman** [comment]
> [.AppImage](https://github.com/nextcloud/desktop/releases/download/v3.4.3/Nextcloud-3.4.3-x86_64.AppImage) is missing

Hm, strange, it seems to have been deleted at some point after release. I was able to download it yesterday.
`md5sum Nextcloud-3.4.3-x86_64.AppImage 85e05a657ab5c9b9562bd79844bc0788`

**Comment by Haplo164** [comment]
I too came looking for an AppImage.

**Comment by ubeaut** [comment]
Yes I am looking for the missing appimage as well.

**Comment by tflidd** [comment]
Now, I can download a file at the given link. So is this solved?
