### ISSUE TITLE
Macos Client 3.4.3 fails to sync from server to local when file names end with a space character

### ISSUE THREAD

**Issue by fl0f** [nextcloud/desktop#4323]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Client should sync files from server to local folder

### Actual behaviour
Client starts "verification" process and fails before going through sync process due to "operation cencelled" error. 

What I find is that verification process fails on folders names that end with a space character. Ex : "/MyTree/My Folder "

Renaming folder as "/MyTree/My Folder" (note the space character at the end of folder name has been removed) enables the "verification process" to continue untill it finds next folder name ending with a space character. 

### Steps to reproduce
1.
2.
3.

### Client configuration
Client version:3.4.3

Operating system: macos Big Sur 11.2.3

OS language:Fr

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:user Application directory

### Server configuration

Nextcloud version:23.0.2

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by Bigwaf** [comment]
It also fails when the space character is at the beginning of the file/folder name.
(macos 12.2.1, nextcloud.app 3.4.3git (build 9390))

**Comment by fiveangle** [comment]
same here… spins in a tight loop (100% cpu) on launch racking up crash counts in Activity Monitor with no GUI.  Launching manually with cmdline to open log window allows to get UI showing unable to sync file beginning with space char. 

![Screen Shot 2022-03-05 at 06 17 50](https://user-images.githubusercontent.com/2219447/156887526-130a329d-7fa9-4895-9bf9-ea09ae4c09ce.jpg)

Upon rename attempt in Finder to remove space, get error that file already exists. 

![Screen Shot 2022-03-05 at 06 18 44](https://user-images.githubusercontent.com/2219447/156887540-24b0ee2e-7fd1-4475-b587-7216585ec35f.jpg)

**Comment by fiveangle** [comment]
Close known issues without resolution. Genius policy. Makes me rethink relying on this...
