### ISSUE TITLE
MacOS Client ignores MacOS accent color in Finder Favorites Icon

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/desktop#4325]
MacOS Client does not adapt to MacOS accent color. In my case it should be blue instead of black. I'm on MacOS Monterey. This issue does not appear on Big Sur. I use Nextcloud Client version 3.4.2.
<img width="260" alt="accent-color" src="https://user-images.githubusercontent.com/34797349/156469271-0fd9a250-d4e2-4220-871c-17d4e28d5485.png">

**Comment by claucambra** [comment]
Duplicate of #3695 but thanks for reporting
