### ISSUE TITLE
windows client 3.5.0:  expiry date can't be set for shared link

### ISSUE THREAD

**Issue by tstreibl** [nextcloud/desktop#4327]
![grafik](https://user-images.githubusercontent.com/32412085/156615553-69384f0a-74f9-4751-abb3-548952a2dcb6.png)

Impossible to change date in text field.

Bug already existed in 3.4.2 Version
Bug exists in 3.4.3 Version !
Bug still exists in 3.5.0 Version !!
Does anybody care?

Server settings like "expiry in ... days" or "force expiry date" have no effect!

**Comment by tphank** [comment]
It appears that the windows client uses the 'default expiration date' and treats it as if the 'Enforce expiration date' option is set.
per the documentation:

> Check Enforce expiration date to always enforce the configured expiration date on local user and group shares.

Note

Users will not be able to set the expiration date further in the future than the enforced expiration date, although they will be able to set a more recent date. Also note that users will be able to update the expiration date again at a later point. The expiration date is based on the current date and not on the share creation date. The user will be able to extend the expiration date again whenever a previous expiration date is close to be reached.

**Comment by walec51** [comment]
setting the expirations date does not work for many users on different OSes for over 4 month now...

https://github.com/nextcloud/desktop/issues/4068

**Comment by matzl** [comment]
I have the same issue and it is extremely annoying :'( Literally can't do anything with the date.

**Comment by tstreibl** [comment]
> It appears that the windows client uses the 'default expiration date' and treats it as if the 'Enforce expiration date' option is set. per the documentation:
> 
> > Check Enforce expiration date to always enforce the configured expiration date on local user and group shares.
> 
> Note
> 
> Users will not be able to set the expiration date further in the future than the enforced expiration date, although they will be able to set a more recent date. Also note that users will be able to update the expiration date again at a later point. The expiration date is based on the current date and not on the share creation date. The user will be able to extend the expiration date again whenever a previous expiration date is close to be reached.

Tried all the server settings available. The behaviour of the desktop client doesn't change at all. The suggested expiry date is always the actual date. I can't change the input in the text field as shown in the screen shot. I can't change the input even when I try to reconfigure the link.

To make it short and simple. It does not work. It is a bug!
