### ISSUE TITLE
Desktop client failed to load on Windows 10 with AMD RX560 graphic card

### ISSUE THREAD

**Issue by jbuggie** [nextcloud/desktop#4328]
The Nextcloud desktop client just failed silently without loading if the AMD rx560 card is used. No error msg given, just not show up.  I have another card, AMD HD7700 that it works correctly with.  This is under Windows 10. Everything is the same, except swapping in/out the two graphic cards.

**Comment by claucambra** [comment]
Could you provide a copy of your desktop logs? This will help us narrow down what might be happening here

**Comment by jbuggie** [comment]
This is from the event log viewer - the driver is an office windows driver for RX560 

Faulting application name: nextcloud.exe, version: 3.4.50.35140, time stamp: 0x621c3097
Faulting module name: atig6txx.dll, version: 30.0.13023.1012, time stamp: 0x616e31f1
Exception code: 0xc0000005
Fault offset: 0x0000000000018b5d
Faulting process id: 0x1f78
Faulting application start time: 0x01d831c175e20195
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0373652.inf_amd64_97d024528a122d1a\B372726\atig6txx.dll
Report Id: 54ceff8f-9aec-4be1-868a-15fce0f81dfa
Faulting package full name: 
Faulting package-relative application ID:

**Comment by claucambra** [comment]
This seems like an issue with your graphics driver -- the crashing component, atig6txx.dll, is part of the graphics driver, not the Nextcloud client.

I would say try fully uninstalling your graphics driver and then download and install the specific driver version for your RX560. Feel free to reopen this issue if this continues happening after doing these steps.
