### ISSUE TITLE
Result entries for fulltext search can not be opened

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/desktop#4330]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
When clicking an element in the search result which is the result of a fulltext search, it will be opened in the browser.

### Actual behaviour
Nothing happens - the click is ignored.

### Steps to reproduce
1. Install and configure fulltext search on the Nextcloud server
2. Do a search in the desktop client which will return one or more results for fulltext search
3. Click one of the results for fulltext search in the list

Also see https://github.com/nextcloud/files_fulltextsearch/issues/153

### Client configuration
Client version: 3.4.3 (Windows)

Operating system: windows-10.0.19044

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): -

Client package (From Nextcloud or distro) (Linux only): -

Installation path of client: C:\Program Files\Nextcloud

### Server configuration

Nextcloud version: 23.0.2

Storage backend (external storage): -

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 
Since 3.1: Under the "General" settings, you can click on "Create Debug Archive ..." to pick the location of where the desktop client will export the logs and the database to a zip file.
On previous releases: Via the command line: `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
(See also https://docs.nextcloud.com/desktop/3.0/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by arnowelzel** [comment]
Why does no one have a look to this issue?

**Comment by arnowelzel** [comment]
Is there anything I can do to help with this? I reported this more than two months ago and so far nothing happend :-(

**Comment by arnowelzel** [comment]
Update: fulltext search results can be clicked now - but the result links to the wrong URL.

Also see https://github.com/nextcloud/fulltextsearch/issues/804

**Comment by joshtrichards** [comment]
Superceded by #6173
