### ISSUE TITLE
UI problem - different scaled screen resolutions

### ISSUE THREAD

**Issue by hjenkel** [nextcloud/desktop#4337]
### Expected behaviour
Client window should open in a readable and user friendly size

### Actual behaviour
The UI-elements are too large. The window is too small. See picture below.

### Steps to reproduce
Open client main window on primary screen with the following configuration. 

### Client configuration
Windows 10 19043.1415
Client version 3.4.1 (language de-de)
Two screen setup:
Primary: 3420 x 2160 (scaled UI 200%)
Secondary: 1920 x 1080 (scaled UI 100%)

![2022-03-07 16_34_27-](https://user-images.githubusercontent.com/12952206/157068746-85398ff9-f018-4c3c-8fc6-bb1b3a4d1e6a.png)
.

**Comment by PhilippSchlesinger** [comment]
temporary workaround:

in file nextcloud.cfg set option

showMainDialogAsNormalWindow=true

and restart. Now you can resize the window as appropriate.
