### ISSUE TITLE
Stuck on uploading 0B

### ISSUE THREAD

**Issue by turkeyphant** [nextcloud/desktop#4338]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Uploads progress and eventually complete

### Actual behaviour
![image](https://user-images.githubusercontent.com/8129583/157310380-9a68434f-c648-4ece-a58c-6daf266b0ead.png)

### Steps to reproduce
1. Change a file
2. Load NextCloud client
3. Wait

### Client configuration
Client version: 3.4.3
windows-10.0.19043

Operating system: Windows 10

OS language: GB-EN

Installation path of client: Default

**Comment by turkeyphant** [comment]
Now stuck like this:

![image](https://user-images.githubusercontent.com/8129583/157312228-e93d3644-a22f-4047-a97f-163177ae3b1d.png)

**Comment by allexzander** [comment]
@turkeyphant I could not reproduce this. Do you have any logs that you can attach?
