### ISSUE TITLE
Invalid date, many files resynced and modified.

### ISSUE THREAD

**Issue by wolfcry0** [nextcloud/desktop#4341]
My Nextcloud client was struggling to sync today, it kept locking up periodically and taking a very long time to sync. After this I noticed many of my files on both clients and server had invalid timestamps and were all listed as updated recently.

![Portuguesemanofwar-Johndory-qUFs2DrgpA](https://user-images.githubusercontent.com/9290121/157495061-38de819f-d259-4e9e-b199-694a3b5b5ef4.png)
![Ekaltadeta-Metamorphosis-Yc2haCWD36](https://user-images.githubusercontent.com/9290121/157495118-d1f24a8f-fb15-40d0-820a-91d4e23503e6.png)

### Expected behaviour
File sync retains proper modification time on files.

### Actual behaviour
Modification and creation date set to Dec 31 1969, and shows as invalid in Nextcloud web.

### Steps to reproduce
1. Use nextcloud with VFS enabled.

### Client configuration
Client version: 3.4.0 (client states no update available, even though it's an old version).

Operating system: W10 x64

OS language: EN

### Server configuration
Nextcloud version: 23.0.0

### Logs
Can't post publicly as they contain personal info (domain, username)

**Comment by allexzander** [comment]
@wolfcry0 There's been an issue with a timestamp in 3.4.0 and 3.4.2. Unfortunately, you will have to follow this guide https://github.com/nextcloud/desktop/wiki/How-to-fix-the-error-invalid-or-negative-modification-date to fix it manually on the server. There is also an issue with auto-update in 3.4.0 that's been fixed starting from 3.4.2. Currently, you can download the latest DC version from here https://nextcloud.com/install/#install-clients. I strongly recommend you first install the latest desktop client before fixing the timestamp on the server.
