### ISSUE TITLE
Activity url is wrong

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4342]
- right click on a file -> activity
- see https://$server/ocs/v2.php/apps/activity/api/v2/activity/filter?sort=asc&object_type=files&object_id=140430645098bde53c208&format=json
- this gives 304 
- correct would be https://$server/ocs/v2.php/apps/activity/api/v2/activity/filter?sort=asc&object_type=files&object_id=14043064&format=json

--> only internal fileId without server id.

**Comment by claucambra** [comment]
Could you test with #4334 ?

**Comment by tobiasKaminsky** [comment]
Now it shows something, but wrong content.
It shows something like "You successfully logged in using two-factor authentication (U2F device) " 363 days ago on an activity for a file.

**Comment by tobiasKaminsky** [comment]
Not stale…

**Comment by tobiasKaminsky** [comment]
Tested with 3.5.0

**Comment by tobiasKaminsky** [comment]
@claucambra you startet working on this via #4777, but probably this is a bug in fetching activity info.
As a side note: we do not have activities for folders, so do not show there anything.

**Comment by tobiasKaminsky** [comment]
> > As a side note: we do not have activities for folders, so do not show there anything.
> 
> Where did you open the activities for folders?

Nowhere, but one activities and sharing is combined, activities could be shown, but this is not feasible, thus it was more an info / side note than an actual bug/task.

**Comment by claucambra** [comment]
> > I will work on it.
> 
> @claucambra is already working on it in #4929.

Yeah, though as of now there is no placeholder for no activities. Won't be a big task to add it though :)
