### ISSUE TITLE
nextcloudcmd: Should use the GUI versions config files by default

### ISSUE THREAD

**Issue by buhtz** [nextcloud/desktop#4347]
I looked into the `nextcloudcmd` related issues and could not find something like that.
I wonder why I have to setup `nextcloudcmd`. It should run by itself without any explicte configuration because it should use the same configuration that the GUI client uses.

1. It save resources on user side.
2. I would say that running the cmd-version with a different config then the gui version is unusual and should be optional.
3. Using cmd-version with explicit (maybe wrong!) config on the gui's syncfolder could possible corrupt something. If both client version would use the same config files everything should be fine.

**Comment by PhilippSchlesinger** [comment]
`nextcloudcmd` can be used independently from nextcloud gui on separate sync folders, even for (system) users without access to the gui.

A commandline switch to use the gui config should help you.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> A commandline switch to use the gui config should help you.

Would be OK for me.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support

**Comment by Rello** [comment]
Hi,

we do not have that option available and it is currently not on the roadmap. So we need to prioritize here.
But we are always happy to accept support via pull requests.

Regards,
marcel

**Comment by strk** [comment]
@buhtz did you find a solution to your problem ? Switching to a different file synchronization tool would also be valid as a solution to me, who just had the exact problem of corrupting my sync by running the command :(

**Comment by strk** [comment]
@Rello the fact you don't plan to implement an enhancement doesn't necessarily mean others would not contribute such an enhancement if encouraged to do so. Closing the issue doesn't encourage such contributions and does not reflect reality (reality is that the issue DOES exist...)

**Comment by Rello** [comment]
> [@Rello](https://github.com/Rello) the fact you don't plan to implement an enhancement doesn't necessarily mean others would not contribute such an enhancement if encouraged to do so. Closing the issue doesn't encourage such contributions and does not reflect reality (reality is that the issue DOES exist...)

Hello,
but just closing it here does not hinder you from opening a PR.
And it was not of interest of any developer since 2022 until now
