### ISSUE TITLE
"Share in Nextcloud" button in Windows Explorer have no function

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/desktop#435]
Hello,

i try it on a computer with Windows 10 Pro (1703) and on a Windows 10 Home (1803), klick on "Share in Nextcloud" in Windows Explorer:

![image](https://user-images.githubusercontent.com/1249295/41759775-686cc088-75f0-11e8-9f60-fcf05eccf2b6.png)

(German Version) nothing happens. Nextcloud Client is Version 2.3.3 (build 1).

Any ideas?

**Comment by camilasan** [comment]
Hi! Do you have anything in the logs? What is the server version? Thanks.

**Comment by BurtGummer** [comment]
Hi camilasan,

Nextcloud Server is 13.0.4 running on Debian Stretch. In the log /var/www/html/nextcloud/data/nextcloud.log nothing happens if i klick the Buttun. Oh, and i have 2 Nextcloud Accounts in the client (same Server Version, its from work and private), in the first account the button works great, but with the second not. Maybe that's the reason?

**Comment by camilasan** [comment]
Hi, having a second account should not be a problem. This would need further debugging... could you try one of the daily builds at https://download.nextcloud.com/desktop/daily/Windows/?

**Comment by Flexmaen** [comment]
I have this problem if the file is not 100% uploaded.
E.g. if I put a file into the nextcloud folder and want to share it immediately while upload to the cloud still is in progress.

In this case the client should at least provide a message like "Please wait until upload is complete", or even better, create a share-link.

**Comment by mgallien** [comment]
Can you still reproduce this bug with the latest version ?
If this is fixed, can you close this issue ?

**Comment by Flexmaen** [comment]
The options are greyed out now, so I consider this to be fixed.

**Comment by mgallien** [comment]
@Flexmaen cool thanks for the reply
