### ISSUE TITLE
Copying/viewing of error messages

### ISSUE THREAD

**Issue by dennemark** [nextcloud/desktop#4352]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Hi,
sometimes I get a lot of errors within my Nextcloud client (Win 11, newest client version). But it is very difficult to get a full picture of the error messages. Either they are shortened within the Popup-Window, when clicking the tray icon or they are listed within the Nextcloud-Settings window, but not scrollable. It would be nice to have a button to copy or view error messages or the full log, so it is easier to communicate with the server administration.

**Comment by joshtrichards** [comment]
Related: #2518

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
