### ISSUE TITLE
Windows version not correct shown

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/desktop#4376]
In actual version 3.44, the windows 11 version is wrongly shown.
OS Build 22000 means Windows 11 initial version and not Windows 10.
Thanks for fixing.

![grafik](https://user-images.githubusercontent.com/4992106/159549678-cf73f145-7b26-432a-aab3-a5c6ec2f2fa9.png)

**Comment by User65481** [comment]
As far I know this is the build number. It doesn't tells you "Windows 10" but "Windows build 10.0.22000" which is correct.

**Comment by Siggi0904** [comment]
But should be shown user friendly.
