### ISSUE TITLE
Implement file locking

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4382]
Ref: https://github.com/nextcloud/files-clients/issues/2

**Comment by biva** [comment]
Hello @mgallien what a great plan :)

Would you consider to lock a file automatically if it's opened? If I understood the objective correctly, it would basically offer similar advantage as the "Badge" feature of Dropbox. We had long discussions about this feature in https://github.com/nextcloud/desktop/issues/83, maybe this issue can be interesting in the development of this new idea.

Thank you again!

**Comment by mgallien** [comment]
> Hello @mgallien what a great plan :)
> 
> Would you consider to lock a file automatically if it's opened? If I understood the objective correctly, it would basically offer similar advantage as the "Badge" feature of Dropbox. We had long discussions about this feature in #83, maybe this issue can be interesting in the development of this new idea.
> 
> Thank you again!

Thanks for the info
Will make good use of it
