### ISSUE TITLE
[Bug]:  File Sync loop when marking them free from local space 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#4383]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When click om free up local space the sync goes into a syn loop

### Steps to reproduce

1. Right click on the file
2. Click on Availability 
3. Free Local Space
...

### Expected behavior

When click om free up local space the sync goes into a syn loop

### Which files are affected by this bug

.conf, txt, .md

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11, 10

### Package

Client 3.4.4

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Na
```

**Comment by andyxheli** [comment]
When i remove it, it stops when i put it right back and mark it free from local space it goes  into a loop again.

**Comment by andyxheli** [comment]
[log.txt](https://github.com/nextcloud/desktop/files/8343567/log.txt)

**Comment by andreaslink-de** [comment]
This is quite sure the same error as extensively described and reproduced in https://github.com/nextcloud/desktop/issues/4226 by [pzwahlen](https://github.com/pzwahlen). I can also confirm this problem with files <=4kB and I am wondering why this bug did not create more attention as many must be affected by this problem?

**Comment by AndyXheli** [comment]
This was fixed on 3.7.4
