### ISSUE TITLE
[Bug]: No check update button 3.4.1

### ISSUE THREAD

**Issue by tflidd** [nextcloud/desktop#4386]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I run the Desktop client version 3.4.1 on Windows 10. In the general section, there is supposed to be a update/update-check button.
I haven't found a fix for that in any of the recent release notes. Just that you can now choose a release channel.
![image](https://user-images.githubusercontent.com/8111200/160080550-8d4b6acc-63ac-4e42-8867-1e1eecccd8ff.png)

I know that I can download and install an update manually.
I had the same problem on a different machine that is restarted more often, I can't remember the exact version, I think either 3.4.0 or 3.4.1.

### Steps to reproduce

1. use NC client
2. update when available, end up in version 3.4.1
3. restart only when required by updates
4. check general settings page for update button

### Expected behavior

Having an update or check update button.

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 pro 21H2

### Package

Other

### Nextcloud Server version

22.2.6

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
not related to server
```

**Comment by RalfWW** [comment]
same here...

**Comment by tflidd** [comment]
also version 3.4.0:
![grafik](https://user-images.githubusercontent.com/8111200/163663993-bd0bdbfa-7ef2-41b6-9a9c-845bbc872600.png)

**Comment by KSpakes87** [comment]
I have the same issue. Just noticed that my client is way behind on updates.

![image](https://user-images.githubusercontent.com/40448897/206512660-bafe4429-b969-40dc-969c-423e8e721d79.png)

**Comment by tobiasKaminsky** [comment]
I remember that there was one a version, where update check was disabled, by accident.
Can you download latest one from download.nextcloud.com and check if the update button is then there?

**Comment by KSpakes87** [comment]
> I remember that there was one a version, where update check was disabled, by accident. Can you download latest one from download.nextcloud.com and check if the update button is then there?

That's what I ended up doing. I have an update button now.

**Comment by joshtrichards** [comment]
Fixed. I believe maybe via #4217, but in any case. Fixed. :)
