### ISSUE TITLE
[Bug]: Client renames file with leading or trailing space and deletes it on next synchronisation run [DATA LOSS!]

### ISSUE THREAD

**Issue by Tegenwind** [nextcloud/desktop#4387]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After saving a file (or folder) with a leading or trailing space, the client renames the file and proceeds to show a green orb with checkmark next to the file or folder. However, it is not uploaded. 

If a synchronisation run is triggered, the file gets deleted without ever making it to the server, with no way to restore it.

### Steps to reproduce

1. Create a file or folder with leading or trailing space

### Expected behavior

After renaming the file, the client should upload the file.

### Which files are affected by this bug

" super fancy document.docx"

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 12.3

### Package

Appimage

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Not applicable, file doesn't even make it to the server.
```

### Additional info

Occurs only on 3.4.3 and 3.4.4 clients.

**Comment by Tegenwind** [comment]
[nextcloud.zip](https://github.com/nextcloud/desktop/files/8349980/nextcloud.zip)
Log files attached.

**Comment by mgallien** [comment]
@Tegenwind thanks a lot for the test and feedback
I am checking right now as this code has to work flawlessly for the next release

**Comment by Tegenwind** [comment]
Thank you for your response! Over the last few months we've found out we have a lot of users accidentally adding extra spaces before or after filenames so we absolutely need this to work properly.

I've tested 3.5.0RC1 and can confirm the issue is still present there. I'll keep an eye out for RC2!

**Comment by mgallien** [comment]
so https://github.com/nextcloud/desktop/pull/4399 should fix that problem
@Tegenwind thanks for letting us know about it

**Comment by Tegenwind** [comment]
I see #4399 did not make it into 3.5.0 RC2 yet. 

Additionally with this issue I noticed when adding a folder with a leading space that all the files and folders in the parent directory get re-synced/ re-downloaded before the newly added folder is finally deleted. Imagine using a mobile hotspot or other metered connection unaware of this issue. 😅

Thanks for the work on this issue so far though, I hope it can be merged soon!

**Comment by Tegenwind** [comment]
Fixed in RC3 🥳, thank you!

However, I do notice a "fixed" folder still triggers a complete re-sync of the parent folder. I will create a new issue for this bug.
