### ISSUE TITLE
Add Upload & download speed rate on nextcloud window after estimated time 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#4388]
![image](https://user-images.githubusercontent.com/59488153/160166120-1d6dbba5-a369-45ed-a9ca-954faec24df8.png)

**Comment by mgallien** [comment]
@nimishavijay @jancborchardt 
as a mere user of desktop client, I had always wanted to get it (and last time I checked other desktop files/share clients have it on the tray icon

**Comment by nimishavijay** [comment]
This sounds a bit like technical info, and it can be found out from the file size progress and time remaining. But if this is available on all the other clients then I think it should be done.

We could add it after the file progress indication. eg.

7MB of 300MB (500KB/s) · 2 minutes left

Additional feedback: change wording of time remaining to avoid using brackets:
- 2 minute(s) left --> 2 minutes left
similar when there are more than 2 seconds/hours/days etc
- 1 minute(s) left --> 1 minute left
similar when there is 1 second/hour/day etc

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, agree with @nimishavijay's proposal. Also the wording enhancement because we know when it's 1 or multiple minutes. ;)

**Comment by timosturm** [comment]
Could this also be added in the 'settings' window? Also it might be a good idea to get two indicators, one for up and one for download speed because sometimes we have both when syncing two files or more, e.g., (500KB/s :arrow_up: | 200KB/s :arrow_down:).

**Comment by tokun-mobica** [comment]
Hi! I've prepared some [code](https://github.com/nextcloud/desktop/pull/4457) related to this request
Download/upload speed info was already available as a tool tip in the settings window: 
![nc_bandwidth_0](https://user-images.githubusercontent.com/96428544/165108518-46c897fe-5138-4ab4-afff-3af70937b47f.png)
I've updated progress info strings with bandwidth in both the main and the settings windows
![nc_bandwidth_1](https://user-images.githubusercontent.com/96428544/165108541-bf393592-5aaa-494d-b49a-fd3b7aec80f3.png)
I didn't try to put this info on the tray icon yet, also no change in wording of time remaining yet.
Waiting for your feedback

**Comment by nimishavijay** [comment]
Really nice work @tokun-mobica! Left some feedback in the PR :)

**Comment by andyxheli** [comment]
Hi all just wanted to see a status on this :)

**Comment by andyxheli** [comment]
Hi all, any updates on this ?

**Comment by andyxheli** [comment]
Hi @nimishavijay is there any progress on this ?

**Comment by nimishavijay** [comment]
@andyxheli you can check the PR for this issue where there was some feedback #4388 :)

**Comment by andyxheli** [comment]
> @andyxheli you can check the PR for this issue where there was some feedback #4388 :)

Thank you :)

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
