### ISSUE TITLE
[Bug]: Log files getting too large with Windows client

### ISSUE THREAD

**Issue by eqipe-leon** [nextcloud/desktop#4394]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

We have a Nextcloud 23.0.3 server for a customer which uses Nextcloud 3.4.4 Desktop Clients to sync the files to their PCs with Windows 10. The folder size of the log folder (C:\Users\[username]\AppData\Roaming\Nextcloud\logs) is getting very large in a short amount of time. Our customer regularly deletes all files out of this folder, when it gets as big as 100-200 GB. After just a night almost 10 GB appeared again. The folder permissions are set to full-access for the user, Nextcloud is also run as the user.
![grafik](https://user-images.githubusercontent.com/78163372/160645559-722dfde9-63e1-4a5e-a9bf-732ffd5aae86.png)

When the folder is getting very big, a lot of 1-2 GB as well as 400 MB log files can be found. This state in the screenshot is only after one night, so its not as big.
![grafik](https://user-images.githubusercontent.com/78163372/160645574-3a8b69ce-fa3a-4c94-893a-58307adbe16b.png)

We did setup the folder synchronisation from scratch to see if something would change. Now also updated on the latest version of the client, the problem still persists.
![grafik](https://user-images.githubusercontent.com/78163372/160645610-211bba92-bf82-4d8d-bfee-57196f6851fc.png)

### Steps to reproduce

1. Set up folder synchronisation with Nextcloud client.
2. Wait a time.
3. Check C:\Users\[username]\AppData\Roaming\Nextcloud\logs for big log data.

We couldn't reproduce the error though, so it doesn't seem to affect all PCs.

### Expected behavior

Log files should be deleted after a short time or maybe get file size capped to not generate log folders as big as 100-200 GB.

### Which files are affected by this bug

x

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by CoYoNq** [comment]
Same issue here, log directory grows on every restart.
As far i see, logs get gziped after any sync session, but looks like older ones are not deleted.
IMHO maybe, an option to control de log verbosity could help. First sync ones with about 500.000 files generates a ~650mb log file (gziped shrink to ~40mb). Its this really necessary?

**Comment by champli** [comment]
Using Client 3.4.0 on Windows 11, with Nextcloud 24.0.4.1 has same issue. Syncing approx. 600k files, ~60GB of data. Log directory grew to over 200 GB.

**Comment by KoenigDickBauch** [comment]
If Nextcloud start with synchronization, then my computer get very slow. And the logfiles grows and grows.
Please open DebugView from Sysinternals. How in the hell can a release-program use the Debug messages!

**Comment by Rello** [comment]
fixed with next release
