### ISSUE TITLE
[Bug]: macOS: window below menubar icon not displayed at correct location on external monitor

### ISSUE THREAD

**Issue by foss-** [nextcloud/desktop#4395]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Regression in NextCloud Desktop Client v3.5.0 RC1

When clicking the menubar icon when using internal screen everything fine. This is not 100% reproducible. With macOS 12.3.1 I have yet to encounter this problem.

**Currently**

However after connecting external monitor and then clicking the menubar icon on either internal or external monitors menubar the NextCloud window is shown on the left side of the external screen far away from the menubar or the menubar icon.

![160668415-6d38216f-439c-44ce-865b-5ecbb7dc1804](https://user-images.githubusercontent.com/5708172/161428859-6ab5de63-64bc-4c33-83a8-fd27e536546d.png)

### Steps to reproduce

click NextCloud Desktop Client menubar icon

### Expected behavior

NextCloud window should always be shown below menubar icon.

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

12.3

### Package

Other

### Nextcloud Server version

21.0.7

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Freshou** [comment]
Same Problem here on many computers ...
Most of them have retina display on my side... If it can help find the bug !

**Comment by Clashsoft** [comment]
Same problem, see https://github.com/nextcloud/desktop/issues/5121#issuecomment-1546661606

**Comment by Nevarro** [comment]
I have the same problem. It seems to be linked to resolution (and display size) changes between external and internal display. When using Nextcloud on an external display and then unplugging it, trying to use it on the internal display, the menu is above the menu bar an unresponsive. The other way around the menu is far below the menu bar and unresponsive.

**Comment by Clashsoft** [comment]
Can't believe this is still not fixed, because it is so easily reproducible. It happens all the time and requires `killall Nextcloud` as the only (!) fix because they don't even bother to have a regular context (right click) menu.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.

**Comment by Freshou** [comment]
It have been close, but it's still an issue...

**Comment by foss-** [comment]
Sorry but I fail to see the idea behind closing this issue. While it was reported 2 1/2 years ago it is still valid. I have seen this recently on macOS 14.7 with one of the recent stable releases of Nextcloud Desktop. Other users have confirmed this is still a problem in 2024 as well. I can certainly copy paste this into a new issue, but what's the point?
