### ISSUE TITLE
[Bug]: Hidden folders hierarchy sync error: File was deleted from the server ... File could not be located

### ISSUE THREAD

**Issue by avatar1024** [nextcloud/desktop#4396]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After deleting and adding files to a hidden folder which is itself nested into other hidden folders I get the sync errors above.
Looking closely at the error message I have noticed something strange which might be the cause of the problem:

The massage looks like this (also see screenshot for the actual message):
Document/.goo/.foo/filename : File was deleted from the server (File with name Document/.goo/filename could not be located)

![nextcloud_error](https://user-images.githubusercontent.com/18719956/160851847-32d571ea-1d7a-474c-a5f4-67d0c43ec9eb.png)

**As you can see the two paths in the message are NOT the same**, the second path is one folder above in the hierarchy so it seems it is not looking for the file ion the right place.

While this somewhat an exotic case, it feels desirable to report such a bug so that the developers are aware of and so be able to increase the robustness of the sync process further.

I am running NC 23.0.3 and using the Linux Desktop Client 3.4.4 (from the nextcloud dev team ppa repository on KDE Neon)

It started happening after I deleted a couple of files and added a new file in a hidden folder from the file manager on the client side (desktop). Both changes (deletion and addition) got sync to the server and I could see that using the NC web ui. Both folders were perfectly synced. However, the desktop client was showing mistakes saying about that three files (the two deleted and the one added) that they were deleted from the server and could not be located.

If I clicked on “force sync now” then everything looked alright (I could briefly see the sync of three files and the green tick appeared again). But then a moment later the three errors would show up again. Similarly if I “pause sync” then “resume sync” the three errors show up whereas when I do a “force sync now” they disappear (but then reappear a moment later or if I then do a pause + resume)

Since these error showed up I cannot sync that folder any longer, in that if I add new files, either from Desktop or from the web ui, it doesn’t get synced and more errors just show up (even when doing s “force sync now”, the green tick appears but the files don’t actually get synced).

Things I have tried:
occ files:cleanup >> does nothing, it says 0 entry deleted for both file cache and mount.
occ files:scan --all >> after that I get lots more errors on that same hierarchy of hidden folders (so the same errors as above + many others in siblings folders (which are also hidden)

Those files are not an external volume but in the main nextcloud folder.
Those files are in a hidden folder which is itself in a hidden folder
I have never had an issue syncing those folders until recently (though I don’t use those often as they are used for old backups configs for clients so I can’t tell exactly when the issue started).
Also I should add that some of the siblings folders (in that weird folder/.hidden/.hidden/.hidden hierarchy) are syncing just fine. The error only affect some of the folders with no obvious patterns as to why that is.
Changing the directory structure and removing one layer of hidden folders **SOLVES THE ISSUE**. All files got synced properly. But surely this is still an odd behaviour.

### Steps to reproduce

1. Deleted files from the folder / or add files to the folder either from the web ui or file manager
2. Wait for client sync to try syncing or press "pause sync" then "resume sync".

### Expected behavior

File should sync without error

### Which files are affected by this bug

several files

### Operating system

Linux

### Which version of the operating system you are running.

KDE Neon

### Package

Other

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
@avatar1024 you will need to share your logs (server and client) to allow us to understand what is happening
I will also try to reproduce locally

**Comment by avatar1024** [comment]
@mgallien Find attached the log from the server when communicating with the client regarding syncing those files.

Most of the files are screencasting tutorials to help clients debug stuff and so are quite files. I tried to create smaller files using the web ui (hiii.md and the readme.md) in the same folder but those were also failing to sync.

You can see in the log that the path also seems off with a // in the middle of it. You can compared this with the screenshot above regarding the Win7.webm and Win7.m4v files. The correct path is what is shown on the left in the screenshot

[log_server.log](https://github.com/nextcloud/desktop/files/8384701/log_server.log)

I did not find a way to get the client log as I have now resolved the issue by removing the unhidding some folders and the latest client log is only from a few hours ago (that is after the issue got resolved).

Let me know if there is anything else I can do.
