### ISSUE TITLE
Windows 10: Connection closed error for uploads since version 2.3.2

### ISSUE THREAD

**Issue by margau** [nextcloud/desktop#44]
Hello,
since i updated the client to 2.3.2 i can't upload files via the nextcloud client.
It says:
`  19.11.2017 13:20:01,                             Folder/File.pdf,                  Z:\NextCloud,Operation abgebrochen
 19.11.2017 13:20:01,                                      Folder/File2.pdf,                  Z:\NextCloud,Verbindung beendet

`

Server Version is 12.0.3.3, and Upload via Webinterface works without problems.
It seems that there is a connection problem inside the Windows Client.

Before 2.3.2 it worked without problems.

Best regards
margau

**Comment by x34c** [comment]
Same here: File uploads without a problem from android client, cannot be uploaded via windows client. This seems to affect only files about a certain size (4 MB files are uploaded, 14 MB and above are not).

I use client version 2.3.3 in windows 8.1.

**Comment by camilasan** [comment]
Do you also the problem with server 13?

**Comment by tehniemer** [comment]
I'm experiencing the same issue, client on win 10 encounters what's shown below and stops the sync process, on Mac it seems to skip those files and keep syncing.

![Image 1553609200](https://user-images.githubusercontent.com/11021632/55003880-30e5a580-4fa7-11e9-959f-d61276a83d6f.png)

The server is running in docker with Caddy as a reverse proxy, I'm able to access the web interface fine and map drives on windows using webdav also.

**Comment by Mick8576** [comment]
Same problem here. the browser-based uplaod works. the download sync works, but the upload sync with the client on Windows 10 does not work (connection closed) on files larger than about 10 MB.
A solution ?
My configuration:
Nextcloud 18, ubuntu 20.04 and Nginx

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
