### ISSUE TITLE
Ghost-Folder

### ISSUE THREAD

**Issue by Doev** [nextcloud/desktop#4402]
I have a 24/7 running Windows Desktop client. It is setup with an account that have readonly permissions on all (group)folders. Frequently I get an error message:

Translated from german:

"[....foldername....]: Not allowed, cause you have no rights, to add subfolder to this folder.

The clients stops syncing at this point. Its a mess.

### Steps to reproduce

I don't know exactly.

1) create a read only user
2) let the read only user sync everything
3) let some other user move some directories
4) -> (readonly) user get the error message.

### Expected behavior

I expect that the client does only syncing the data and not cretae folders by its one.

### Which files are affected by this bug

I think only subfolders inside group folders.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

21.0.9

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

**Comment by Doev** [comment]
I made a Stresstest. I create a Folder with many subfolders. Then I moved it inside the nextcloud projectfolder from one place to another one.

I get the error:

![grafik](https://user-images.githubusercontent.com/6341785/161083956-6bb1c938-a68a-4a9e-83be-7125821d1527.png)

The full-permission client:
![grafik](https://user-images.githubusercontent.com/6341785/161084313-13ca52ca-b94d-494c-b70c-b7f507d77ef7.png)

And the read-only client:
![grafik](https://user-images.githubusercontent.com/6341785/161084460-c7eae943-d282-4492-b273-4efb4c0401f5.png)

**Comment by camilasan** [comment]
Does it still happen with Nextcloud 23 server? This does look like a server response.

**Comment by Doev** [comment]
This Friday we do an update to our server. I can test it again.

**Comment by Doev** [comment]
No change after the Update. The same problem still happens.

**Comment by Doev** [comment]
Why is the bug report closed?

**Comment by camilasan** [comment]
> No change after the Update. The same problem still happens.

Desktop client 3.5.1? 

We will need the client and server logs. 

This is looking like a response from the server. We had issues before with groupfolder permissions.
