### ISSUE TITLE
[Bug]: server read error causes the client sync to be interrupted 

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/desktop#4407]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

the client stopped syncing due to a server read error in a directory, which is perfectly accessible via WEB interface.

it was not clear that this error stopped syncing the remaining files/directories, which have been syncing without any problems for month.

### Steps to reproduce

1. automatic sync

### Expected behavior

issue a well documented error but continue syncing.

there is no error message on the server side in the log files (all log boxes checked)

### Which files are affected by this bug

"Fa Beteiligungen/Christophs_Dateien/Shared OLD/Shared/Bilder \"

### Operating system

Mac OS

### Which version of the operating system you are running.

12.2.1

### Package

Appimage

### Nextcloud Server version

23.0.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nothing available
```

### Additional info

in the 580MB client log files I found this:

20220402_1417_owncloud.log.1.gz:2022-04-02 14:23:32:119 [ info nextcloud.gui.activity /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-9585/src/gui/tray/activitylistmodel.cpp:402 ]:	Error successfully added to the notification list:  "Server replied with an error while reading directory \"Fa Beteiligungen/Christophs_Dateien/Shared OLD/Shared/Bilder \" : Operation canceled"

I disabled the sync of this folder and sync works again. But it took some considerable time to find out ...

Hint: 
- I have 2 NC installations synced using the NC client. OLD/NEW
- this directory was transferred (moved) on the client side (using finder) from the OLD NC installation to the NEW and the problematic directory contained shared files/directories. they are perfectly accessible on the client side.
- I am using a SAAS NC installation for the NEW NC Cloud - Hence I can not access occ and try to run maintanence:repair.
- I see a trailing blank in the file causing the error.
- the logs directory in the archive is not accessible has rw instead of rwx - had to set it manually

[20220402_1417_owncloud.log.1.gz](https://github.com/nextcloud/desktop/files/8404033/20220402_1417_owncloud.log.1.gz)

**Comment by blackandcold** [comment]
I have maybe the same error only an fresh installed Manjaro (3.4.4)
Updating the server to 23 changed the read error on client side to "operation canceled" but the rootcause is still a Problem reading "Hochzeit/Hochzeitstanz" folder. Renaming the previous one lead to the next beeing stuck.

Activity windows is completely empty.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
