### ISSUE TITLE
[Bug]: Defect pixels in clients main window

### ISSUE THREAD

**Issue by jqdroid** [nextcloud/desktop#4409]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

In the main window some pixels get disturbed over time. Possibly after sleep / resume
![Screenshot_2022-04-04_09:32:09](https://user-images.githubusercontent.com/1104576/161503612-4f20db9e-6ce2-49f9-9c1b-f2bc186cb61c.png)
.

### Steps to reproduce

Open client's main window after it's running for a while. Maybe it's necessary to sleep / resume computer.

### Expected behavior

Window should not get noisy.

### Which files are affected by this bug

none

### Operating system

Linux

### Which version of the operating system you are running.

Kubuntu 21.10

### Package

Appimage

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
