### ISSUE TITLE
[Bug]: Error updating metadata: Couldn't set pin state | Windows 11

### ISSUE THREAD

**Issue by darkis81** [nextcloud/desktop#4410]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When I try to sync my files from Nextcloud to my Windows 11 dev pre release I had some issues and was meet with the error:
Error updating metadata: Couldn't set pin state.
I had OwnCloud installed and was working perfectly before but i decided to migrate over to Nextcloud but then I received these issues.

It was working fine on my other PC (Windows 10) so I decided to reinstall my system and im now not on Windows 11 dev release.
It was working fine for a couple of days but then all of a sudden it stopped working again.
![image](https://user-images.githubusercontent.com/17593241/161515994-9b8f8bf1-ad10-4520-ac07-32fa60831601.png)

### Steps to reproduce

1. Install Nextcloud app on Windows 11
2. Start autosync
3. Error recieved
...

### Expected behavior

No errors when syncing.

### Which files are affected by this bug

Temp Files (Free to remove)

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"q7CXHFOb82F9BGHjW7Ft","level":2,"time":"2022-03-12T18:18:58+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","user>{"reqId":"q7CXHFOb82F9BGHjW7Ft","level":2,"time":"2022-03-12T18:18:58+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userA>{"reqId":"NNvjNvFXsTON7XKy2HpW","level":2,"time":"2022-03-12T18:19:20+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","user>{"reqId":"NNvjNvFXsTON7XKy2HpW","level":2,"time":"2022-03-12T18:19:20+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userA>{"reqId":"CkfFsp5dH80NgSMJAqua","level":2,"time":"2022-03-12T18:19:45+00:00","remoteAddr":"74.207.228.249","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","us>{"reqId":"CkfFsp5dH80NgSMJAqua","level":2,"time":"2022-03-12T18:19:45+00:00","remoteAddr":"74.207.228.249","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","use>{"reqId":"qOOR0XK8VgWTMOgXanPz","level":2,"time":"2022-03-12T18:19:47+00:00","remoteAddr":"172.105.206.169","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","u>{"reqId":"qOOR0XK8VgWTMOgXanPz","level":2,"time":"2022-03-12T18:19:47+00:00","remoteAddr":"172.105.206.169","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","us>{"reqId":"1kgBA7BxtllxR4NtMSVh","level":2,"time":"2022-03-12T18:19:48+00:00","remoteAddr":"168.119.96.54","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","use>{"reqId":"1kgBA7BxtllxR4NtMSVh","level":2,"time":"2022-03-12T18:19:48+00:00","remoteAddr":"168.119.96.54","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","user>{"reqId":"1nxa9lvcAytBlVzcbD6i","level":2,"time":"2022-03-12T18:19:48+00:00","remoteAddr":"172.105.190.118","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","u>{"reqId":"1nxa9lvcAytBlVzcbD6i","level":2,"time":"2022-03-12T18:19:48+00:00","remoteAddr":"172.105.190.118","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","us>{"reqId":"r6aiJhLMIWwDyEbsqlLb","level":2,"time":"2022-03-12T18:22:16+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.>{"reqId":"r6aiJhLMIWwDyEbsqlLb","level":2,"time":"2022-03-12T18:22:16+00:00","remoteAddr":"92.34.48.196","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.t>
```

**Comment by darkis81** [comment]
Windows app debug
https://easyupload.io/85jpu1

**Comment by rodrigoscoelho** [comment]
I'm with the same problem...

![image](https://user-images.githubusercontent.com/6912410/163041027-066b523f-7732-403f-a5c6-a55677d77d46.png)

**Comment by MrBroccoliJP** [comment]
I have been getting the same problem for a week or so now as well. 

It started with files changing upload dates to future or 1970 dates. Figured that out and manually reuploaded files or used command to change them, and now this happens all the time. Doesn't seem to be server sided. It only happens with VFS.

Lemme know if anybody needs logs or something, quite new to bug reports, so I may need some help.

**Comment by TheIceMagmaCube** [comment]
Got here the same problem. Every time you restart the app, sync goes a bit further in files but crashes anyway.
Didn't tried on Windows 10 for now. I think I'll look for a WebDav sync app for now, until this bug is fixed.

**Comment by darkis81** [comment]
Issue persists after Server updated to 23.0.4 and Client version is at 3.4.4.

**Comment by TheIceMagmaCube** [comment]
> Issue persists after Server updated to 23.0.4 and Client version is at 3.4.4.

Checked today, same issue.

**Comment by ThatsSoTrinda** [comment]
Same issue, Windows 11 x64
Client version 3.5.0
Server version 23.0.4 - 23.0.4.1

**Comment by IndigoFloyd** [comment]
I do think it's a problem about system version. You can run your program with the compatibility option (run as Windows 8).

**Comment by darkis81** [comment]
New server version released today and I updated (24.0.0) but problem persisted.
I tried running the app with compatibility option (run as Windows 8) but same problem.

**Comment by BangyStudios** [comment]
Yeah I'm experiencing the same problem. I'm using the OwnCloud client instead as a hot fix, it doesn't have this problem on Windows 11 with virtual file system.

**Comment by TheIceMagmaCube** [comment]
> Yeah I'm experiencing the same problem. I'm using the OwnCloud client instead as a hot fix, it doesn't have this problem on Windows 11 with virtual file system.

Very good tip, it works for me. Guess I'm gonna uninstall Nextcloud app until a patch is published.

**Comment by andmpel** [comment]
Also having the same issue, is this being worked on?

**Comment by SirBogner** [comment]
Also been having this issue for some time now. It especially occurs when the client is trying to syncrhonize hidden files created by Synology DSM. Namely the "@eaDir"-folders. It turns out, Nextcloud only hides folders beginning with punctuation.

Turning of synchronization for folders and files named "@eaDir" in the Nextcloud Client at most fixed the problem. Although it keeps occuring now and then when trying to sync new folders from the server to the client.

**Comment by andmpel** [comment]
I only have been able to resolve this by turning off virtual files and manually selecting the folders I need synced. They have to be offline however which is annoying.

**Comment by darkis81** [comment]
Problem persists, haven't heard anything from the support team.

**Comment by andmpel** [comment]
Updated to most recent snap 24.0.1snap1 and problem still persists.

**Comment by BangyStudios** [comment]
Updated to 3.5.2, problem persists.

**Comment by darkis81** [comment]
3.5.4 today, no solution yet...

**Comment by TheIceMagmaCube** [comment]
You can still use Owncloud Desktop. It works flawlessly for me.

Find the client on the Owncloud website.

**Comment by mgallien** [comment]
could any of affected people test this build with a fix that is in the next stable version due soon
https://cloud.nextcloud.com/s/K4ynRkJJMFDw4xx

**Comment by MrBroccoliJP** [comment]
![image](https://user-images.githubusercontent.com/44526663/188888196-e60b0007-573e-4de9-ada1-f8a6e8980d28.png)

It has been stable so far, It never passed 3000 files before this update so it seems to be fixed, but I'll update you when it's finished 👍

**Comment by MrBroccoliJP** [comment]
> could any of affected people test this build with a fix that is in the next stable version due soon https://cloud.nextcloud.com/s/K4ynRkJJMFDw4xx

@mgallien 

![image](https://user-images.githubusercontent.com/44526663/188966482-f63894c0-9e36-4f62-8a74-3ba7d2fb98db.png)

This issue seems to be fixed for me, sync finished successfully for virtual file support. 98000+ files from internal server and external storage (samba)

**Comment by vasyugan** [comment]
> I am closing it people do not hesitate to ping me in case you still have issues after migrating to 3.6.0 release https://github.com/nextcloud/desktop/releases/tag/v3.6.0

I'm seeing this error message right now, with version 3.13.0 of the client, on Windows 10

**Comment by yatzy** [comment]
Facing this issue on Windows 11, client version 3.12.4
