### ISSUE TITLE
[Bug]: client 3.4.4 resets big folders to "NOT SYNC"

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/desktop#4413]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

for unknown reasons big folders are reset to "not sync" 
it happens already 3 times in the last few days.

### Steps to reproduce

1. restart client (probably)

I was investigating why files have not been synced.

### Expected behavior

DO not reset the configuration

### Which files are affected by this bug

many many as big directories are not synced

### Operating system

Mac OS

### Which version of the operating system you are running.

12.2.1

### Package

Appimage

### Nextcloud Server version

23.0.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
none
```

**Comment by camilasan** [comment]
> for unknown reasons big folders are reset to "not sync"
> it happens already 3 times in the last few days.

Did you change the setting "Ask for confirmation before synchronizing folders larger than"?

Does it still happen with 3.5.1?

**Comment by camilasan** [comment]
> Sorry, can't answer the question any more, I think it happened during/after updating
> I also had to reenter the credentials

so it is working now?

**Comment by ferdiga** [comment]
I said I can not confirm, because it seems to happen during an upgrade, which I can not repeat.
After reentering the account data  it works again. But that's not the way an upgrade should work (loosing credentials)

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by ferdiga** [comment]
I didn't experience the loss of credentials since....
So all good
