### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mactrent** [nextcloud/desktop#4422]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Share dialog not opening on 3.5rc3 (Windows)
The share icon highlights on mouse-over, and the alt-text shows up on hover.  Clicking the button shows no further response.

### Steps to reproduce

1. Open Nextcloud Desktop main dialog
2. Find a notification of file change/update/add
3. Click the Share icon

### Expected behavior

When clicking on the share icon in notifications, the share dialog should open in a new window

### Which files are affected by this bug

Log entry contains no mention of file names

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Enterprise 2004 (OS Build 19041.1415)

### Package

Other

### Nextcloud Server version

22.2.6

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Server logs contain no relevant messages.
```

### Additional info

Relevant sample from client logs:
[ warning nextcloud.gui.application C:\Users\sysadmin\AppData\Local\Temp\2\windows-9899\client-building\desktop\src\gui\owncloudgui.cpp:617 ]:	Could not open share dialog for "" no responsible folder found

**Comment by camilasan** [comment]
Fixed with #4640.
