### ISSUE TITLE
[Bug]: unchecking sync hidden files does not work

### ISSUE THREAD

**Issue by zilexa** [nextcloud/desktop#4423]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The "sync hidden files" checkbox in settings is automatically checked again after you uncheck it.
...

### Steps to reproduce

1. open Nextcloud Desktop Client settings
2. uncheck "sync hidden files"
3. close settings
4.  Reopen settings and notice the box is checked again. 
...

### Expected behavior

After I uncheck it, I expect it to stat unchecked.
...

### Which files are affected by this bug

GUI error

### Operating system

Linux

### Which version of the operating system you are running.

Manjaro GNOME 21.2.5

### Package

Distro package manager

### Nextcloud Server version

23

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This is a GUI bug appearing on multiple Linux distributions for over a year.

**Comment by joshtrichards** [comment]
Sounds basically same as #1346

Let's track progress there.
