### ISSUE TITLE
[Bug]: ambiguous SSL certificate error message

### ISSUE THREAD

**Issue by Asteliks** [nextcloud/desktop#4427]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When trying to configure Nextcloud desktop I get an ambiguous error message saying:
![image](https://user-images.githubusercontent.com/62251475/162636616-3170bedc-8432-44be-89a8-9f6c2d4e6d6a.png)

Problems:
- this error message doesn't tell me much especially what variable in the certificate is expected
- selecting "Trust this certificate anyway" and clicking OK makes the error window reappear

### Steps to reproduce

1. Enter your server link
2. Click next

### Expected behavior

When I get an error prompt I would like to know what is wrong it would also be great if the documentation had proper SSL certificate attributes specified 

### Which files are affected by this bug

NONE

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official SNAP package

### Nextcloud Server version

23.00.03

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tflidd** [comment]
In such cases, you can test your ssl setup with: https://www.ssllabs.com/ssltest/

**Comment by claucambra** [comment]
Can you provide logs for the desktop client? Thanks!

**Comment by claucambra** [comment]
In that case I will close this ticket. If you are able to reproduce this issue again and can provide logs please feel free to reopen. Thanks for reporting!

**Comment by joekerna** [comment]
I have the exact same issue now.

I'm on the latest Nextcloud and I'm trying to access from the server itself. It is a Ubuntu 22.04 system.

I use the FQDN with https from letsencrypt. The certificate is working fine in the browser but the client constantly throws this warning. No matter how often I click "Trust this certificate anyway", the warning reappears.

**Comment by Asteliks** [comment]
@joekerna you will need to get the logs. I have failed to do so and thus they were unable to help me

**Comment by joekerna** [comment]
But which logs? The server logs are empty. I emptied them before starting the desktop client and nothing come up after 4-5 SSL warnings.
Does the client have a logfile?

**Comment by Asteliks** [comment]
@claucambra could you help us out here

**Comment by joekerna** [comment]
Can anybody please reopen this issue? It's so annoying, I've had to stop using the Nextcloud client on my Desktop

**Comment by joekerna** [comment]
> Can you provide logs for the desktop client? Thanks!

where are those logfiles?

**Comment by joekerna** [comment]
I fixed the issue: I had an old relict of libssl1 on my installation. After I removed
_/usr/local/lib/libssl.so_ (pointing to the file below)
_/usr/local/lib/libssl.so.1.1_ 

The client now appears to be using _libssl3_

**Comment by joshtrichards** [comment]
That error is generated by an underlying dependency and maps to a X509 error: `X509_V_ERR_INVALID_PURPOSE`.

It literally means what it says: the certificate being used by the server isn't specified for usage in the current way (e.g. it was created for something other than usage as an HTTPS server certificate... like for email signing or similar).

https://www.openssl.org/docs/man3.2/man3/X509_verify_cert_error_string.html
https://www.openssl.org/docs/manmaster/man5/x509v3_config.html (search for "Key usage")

The error itself isn't coming from the Desktop client per se, but from an underlying library.

From the sounds of it, it might also be triggered by a broken libssl/openssl installation, per @joekerna's comment.

> When I get an error prompt I would like to know what is wrong it would also be great if the documentation had proper SSL certificate attributes specified

All we require is a valid certificate. :-) This error is about a weird edge case - or an indication of a broken underlying client device SSL installation.
