### ISSUE TITLE
UI enhancements: tray window

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#4432]
**Bold is for issues to focus on**

- [x] **Icon in left should be vertically center aligned with the text in its entry**
- [x] **Un-hoverable whitespace between entries doesn't need to be there**
- [x] **Filetype icons could be a bit smaller, thumbnail icons are perfectly sized :)**
- [x] **Overlay icon (Eg. refresh icon on top on filetype icon) could be a bit smaller**
- [x] **Height of the entries too big? Reduce a bit**
- [x] **Share icon on the right:**
    - Size should be the same all the time, right now it is different depending on the length of the text.
    - Colors on hover should be same as server theming like text and icons on the tray window header is.
- [x] Skeleton screen bars should be lighter, similar to unified search skeleton screen in web
- [x] When there is a new item synced and you are scrolled down, the scroll position jumps back up, it should stay at the same position
- [x] Header apps menu y-position should be where header ends (the top of the list is covering the apps icon in the windows, it shouldn't)
- [ ] Card comments icon use the same as the one in server

**Comment by claucambra** [comment]
> Card comments icon use the same as the one in server

Not really sure what this means @jancborchardt could you clarify? thanks!

**Comment by claucambra** [comment]
Now complete
