### ISSUE TITLE
UI enhancements: activities list

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#4433]
**Bold is for issues to focus on**

- [x] **If there are multiple entries with exactly the same wording then show only the most recent one (they are displayed multiple times even though the have the same message, like "Synced readme.md")**
- [x] Fetching activity only on open: Show an entry below "All synced" with icon MDI sync icon and text "Loading more activity"
- [x] Clicking on any openable file should open the file itself in the default application and not the file viewer

**Comment by claucambra** [comment]
Regarding point 3 -- how do we handle activity entries that contain several files? I'm guessing a drop-down of some sort?

**Comment by claucambra** [comment]
Ping? @jancborchardt @nimishavijay

**Comment by nimishavijay** [comment]
> how do we handle activity entries that contain several files? I'm guessing a drop-down of some sort?

Sounds good to me :) we could have an expand-more icon on the right, and when clicked it shows upto 5 entries with a "Show more" button, clicking on which would show 5 more and a "Show more", etc.

What do you think? cc @jancborchardt

**Comment by claucambra** [comment]
Another comment: AFAIK point number 2 is already the case, unless I am misinterpreting

**Comment by claucambra** [comment]
We can consider this completed :)
