### ISSUE TITLE
Overview: UI enhancements 

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#4436]
### Tray menu entry design

- https://github.com/nextcloud/desktop/issues/4432
- https://github.com/nextcloud/desktop/issues/4433

### Search

- https://github.com/nextcloud/desktop/issues/4434

### Talk mentions

- https://github.com/nextcloud/desktop/issues/4435

### Overall

- We recommend AppImage which doesn’t come with file manager integration out of the box. Needs nautilus-nextcloud package installed, but we can’t install it automatically for technical reasons.
   - With the PPA installation method this works, but needs you to use a terminal.

### Status

- If server is below v19 (Status was introduced) or user_status is disabled:
   - No indicator icon should be shown
   - In the heading of the tray menu, the status line is replaced with the instance link
   - In the accounts dropdown, the text line of status is removed (and the name and instance link are moved closer together vertically)
   - Sync status icon is not moved
- Status message line has one space too much on the left when there’s no emoji (probably the hardcoded space between emoji
- Possibility of having the current user status also as separate tray icon
    - Maybe together with a Nextcloud Talk desktop app? (Plan for future, with Electron) → more than a year away
    - Status should be shown in both Files and Talk desktop apps, cause people might only use one (comparison mobile apps)

### Tray menu positioning

- Wayland issue with window positioning – there is no concept of corner positioning. Is seemingly positioned randomly.

### Tray menu general

- Grouping of activity entries
- Paths are truncated → Either wrapping or truncating in the middle, OR showing only filename directly, and
- Case of sync conflicts:
    - Sync conflicts should be shown on top
    - Tray menu closes when clicking on an item
- Mix of items which can be clicked and can’t be clicked → ideally everything should be actionable
- On some Linux distros / desktop environments (GNOME likely) you have a dropdown with text items which include "Open main dialog" to get the tray menu in the first place
- Tray menu sometimes is too large in general (possibly after changing resolution), also the mouse cursor

### Notifications in tray menu

- When another person changed a file, use their avatar in the bottom right
- If another person wrote a comment, or mentioned you in chat, use their avatar as the big icon on the left

- First text line:
   - Files: Only filename, no path
   - Talk: Name of person

- Second text line:
    - Files: "in foldername" (if not in root)
    - Talk: the message

- Third text line:
    - Files: "Deleted 3 min ago", "Edited 2 years ago", etc
    - Talk: no third line

- Actions on right:
    - Operation canceled / 503 service unavailable: Retry icon / button on right, no share
    - File deleted: Versions button
    - Talk message: "View chat" button and "x" dismiss
    - Share icon and dismiss x are too big and dark

### Settings window

- Tab bar: change icons to Material Design
    - Settings: [https://fonts.google.com/icons?selected=Material Icons%3Asettings](https://fonts.google.com/icons?selected=Material%20Icons%3Asettings)
    - Network: [https://fonts.google.com/icons?selected=Material Icons%3Aswap_vert](https://fonts.google.com/icons?selected=Material%20Icons%3Aswap_vert)

- Remove italicizing of own name in "Connected to cloud.nextcloud.com as [Name]"
- In "General" and "Network" sections, remove extra boxes and use whitespace to separate instead
- User names and links might be truncated too early in the tab bar
- Error notice below folder sync summary could be clickable

### Virtual file system

- Possibly show a subline for the radio button like: "Placeholder files are shown until the file is opened. Files are not available offline unless they have been opened before"
- Talk to KDE and GNOME folks to truncate the extra .nextcloud extension part
- Remove "…" in the "Disable virtual file support …" action
- Show- 
Possibly use different icon than the green checkmark if Virtual file support is enabled

#### Downloading

- Maybe more instructions for each platform, once downloaded I had to mark AppImage as executable and then run it.
- If ppa is a better option then could make that more present. Might be a good idea to have separate pages/sections for each platform and give more info about how to install
- unrelated but it also might be a good idea to mention uninstall instructions somewhere

#### Setting up account

- Issue related to wording: https://github.com/nextcloud/desktop/issues/3693
- Minor detail, but the carousel could be changing on its own with the Nextcloud logo fixed on top, I didn't notice the arrows many times
    - Note from Jan: We actually had it automatically switching first, but received feedback that automatic switching is not ideal, especially also for accessibility. Also having the logo fixed on top would result in essentially 2 icons visible at all time, which seems a bit much.
- Sign up with provider: "Invalid token" error sometimes, have to go to the web. When signing up, there isn't feedback when you click on "Log in" and hence you click it again => error
- "Skip folder config" can go to the right of "Back"
- weird looking icons sometimes in the "Choose what to sync" dialogue (??)
- Local folder folder path ("Nextcloud") looks like a button, maybe show the full file path (eg /home/nimisha/Nextcloud) or change it to an input field
    - It is indeed clickable and should look like a button, but yeah probably showing full path is better feedback.
- As soon as you create your account and link folder the main dialogue opens at a seemingly random place on the screen
- When using the AppImage, indicator icons are not showing
- On Windows, indicator icons in the file manager only show up after restart – and not communicated?
    - On Linux, they do not work at all using the AppImage, you need to
    - Use the PPA [https://launchpad.net/\~nextcloud-devs/+archive/ubuntu/client](https://launchpad.net/%5C~nextcloud-devs/+archive/ubuntu/client)
    - Install the "nextcloud-desktop" package there (not nextcloud-client)
    - Additionally install "nextcloud-client-nautilus" (and "python-nautilus"?)
    - Then restart Nautilus

**Comment by tobiasKaminsky** [comment]
I removed this one from "planning evaluation".
Individual tasks, e.g. "status enhancements" can be picked, but not this entire one, as it is way too big.

This can be either a long-running tasks, where we pick up individual tasks an fix them on the fly, or we specifically add some to the board.
