### ISSUE TITLE
Segmentation fault on openSuSE Leap 15.0 only on KDE plasma

### ISSUE THREAD

**Issue by zoman2000** [nextcloud/desktop#444]
* Note
It is working on Gnome (X11). Crashing on KDE plasma(X11 and wayland) only.

* Console output (hostname has been edited)

./nextcloud
[OCC::Application::setupLogging         "################## Nextcloud locale:[en_US] ui_lang:[] version:[2.5.0git] os:[openSUSE Leap 15.0]"
[OCC::{anonymous}::applicationTrPath    Running from build location! Translations may be incomplete!
[OCC::Application::setupTranslations    Using "en_US" translation
[OCC::SocketApi::SocketApi      server started, listening at  "/run/user/1000/Nextcloud/socket"
[OCC::FolderMan::FolderMan      setting remote poll timer interval to 30000 msec
[OCC::AccountManager::loadAccountHelper         Account for QUrl("https://example.host/cloud") using auth type "http"
[OCC::AccountManager::loadAccountHelper         Account for QUrl("https://example.host/cloud2") using auth type "http"
[OCC::FolderMan::setupFolders   Setup folders from settings file
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645b51b70) "1"
[OCC::FolderMan::scheduleFolder         Schedule folder  "1"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645d08c20) "10"
[OCC::FolderMan::scheduleFolder         Schedule folder  "10"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645d16760) "2"
[OCC::FolderMan::scheduleFolder         Schedule folder  "2"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"                               
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645cf59b0) "3"                                                                        
[OCC::FolderMan::scheduleFolder         Schedule folder  "3"  to sync!                                                                                                      
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!                                                                                         
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"                               
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645b579a0) "4"                                                                        
[OCC::FolderMan::scheduleFolder         Schedule folder  "4"  to sync!                                                                                                      
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!                                                                                         
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"                               
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645caafc0) "5"                                                                        
[OCC::FolderMan::scheduleFolder         Schedule folder  "5"  to sync!                                                                                                      
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645c34e00) "6"
[OCC::FolderMan::scheduleFolder         Schedule folder  "6"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645ce0ef0) "7"
[OCC::FolderMan::scheduleFolder         Schedule folder  "7"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645b523d0) "8"
[OCC::FolderMan::scheduleFolder         Schedule folder  "8"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ConfigFile::setupDefaultExcludeFilePaths  Adding system ignore list to csync: "/u02/build/linux/nextcloud/desktop/bin/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal      Adding folder to Folder Map  OCC::Folder(0x563645cb8740) "9"
[OCC::FolderMan::scheduleFolder         Schedule folder  "9"  to sync!
[OCC::FolderMan::scheduleFolder         Folder is not ready to sync, not scheduled!
[OCC::ClientProxy::setupQtProxyFromConfig       Set proxy configuration to use system configuration
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::SyncJournalDb::checkConnect       sqlite3 version "3.23.1"
[OCC::SyncJournalDb::checkConnect       sqlite3 journal_mode= "wal"
[OCC::AccessManager::createRequest      6 "GET" "https://example.host/cloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "e1d1009a-6e88-4257-baa5-862d4a872b41"
[OCC::AbstractNetworkJob::start         OCC::OcsNavigationAppsJob created for "https://example.host/cloud" + "ocs/v2.php/core/navigation/apps" ""
[OCC::AccessManager::createRequest      6 "GET" "https://example.host/cloud2/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "1daae883-2fe7-4452-b24f-b23c7ce5fbb6"
[OCC::AbstractNetworkJob::start         OCC::OcsNavigationAppsJob created for "https://example.host/cloud2" + "ocs/v2.php/core/navigation/apps" ""
Segmentation fault (core dumped)

* core info

(gdb) info frame
Stack level 0, frame at 0x7f3b8cf3e550:
 rip = 0x7f3bc84432c3 in JSC::JSLockHolder::JSLockHolder(JSC::VM&); saved rip = 0x7f3b77270bdf
 called by frame at 0x7f3b8cf3e610
 Arglist at 0x7f3b8cf3e540, args: 
 Locals at 0x7f3b8cf3e540, Previous frame's sp is 0x7f3b8cf3e550
 Saved registers:
  rip at 0x7f3b8cf3e548

(gdb) bt
#0  0x00007f73523e32c3 in JSC::JSLockHolder::JSLockHolder(JSC::VM&) () at /usr/lib64/libQt5WebKit.so.5
#1  0x00007f7310e63bdf in JSCheckScriptSyntax() () at /usr/src/debug/webkit2gtk3-2.20.2-lp150.1.1.x86_64/Source/JavaScriptCore/API/JSBase.cpp:100
#2  0x00007f7311bf529c in webkit_pacrunner::webkit_pacrunner(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, libproxy::url const&) (pacurl=..., pac="", this=0x7f72fc003650)
    at /usr/src/debug/libproxy-plugins-0.4.15-lp150.2.2.x86_64/libproxy/modules/pacrunner_webkit.cpp:125
#3  0x00007f7311bf529c in webkit_pacrunner_extension::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, libproxy::url const&) (this=<optimized out>, pac=..., pacurl=...)
    at /usr/src/debug/libproxy-plugins-0.4.15-lp150.2.2.x86_64/libproxy/modules/pacrunner_webkit.cpp:171
#4  0x00007f734461340f in libproxy::pacrunner_extension::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, libproxy::url const&) (this=0x7f72fc0033d0, pac=..., pacurl=...)
    at /usr/src/debug/libproxy-0.4.15-lp150.2.2.x86_64/libproxy/extension_pacrunner.cpp:40
#5  0x00007f7344617a6a in libproxy::proxy_factory::run_pac(libproxy::url&, libproxy::url const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) (this=this@entry=0x7f72fc000b10, realurl=..., confurl=..., response=std::vector of length 0, capacity 0)
    at /usr/src/debug/libproxy-0.4.15-lp150.2.2.x86_64/libproxy/proxy.cpp:419
#6  0x00007f73446188f2 in libproxy::proxy_factory::get_proxies(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=this@entry=0x7f72fc000b10, realurl="https://example.host/cloud2/ocs/v2.php/core/navigation/apps?absolute=true&format=json") at /usr/src/debug/libproxy-0.4.15-lp150.2.2.x86_64/libproxy/proxy.cpp:216
#7  0x00007f7344618d42 in px_proxy_factory_get_proxies(pxProxyFactory_*, char const*) (self=0x7f72fc000b10, url=<optimized out>) at /usr/src/debug/libproxy-0.4.15-lp150.2.2.x86_64/libproxy/proxy.cpp:463
#8  0x00007f7350ca0e01 in QLibProxyWrapper::run() (this=0x7f7350f46d80 <(anonymous namespace)::Q_QGS_libProxyWrapper::innerFunction()::holder>) at kernel/qnetworkproxy_libproxy.cpp:182
#9  0x00007f734f0c00ce in QThreadPrivate::start(void*) (arg=0x7f7350f46d80 <(anonymous namespace)::Q_QGS_libProxyWrapper::innerFunction()::holder>) at thread/qthread_unix.cpp:368
#10 0x00007f734dec1559 in start_thread (arg=0x7f73127fc700) at pthread_create.c:465
#11 0x00007f734e45d82f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by zoman2000** [comment]
There is a workaround to disable a proxy on a system level.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
