### ISSUE TITLE
[Bug]: Sync client broken on MacOS: Some files couldn't be synced. No logs available.

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud/desktop#4440]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.

Sync client on Mac OS broken for about 2 weeks now in at least the last two versions

Tried to log out log in again, removed sync folder added it again now change. No logs available on server side, client only shows: 

![Screenshot 2022-04-14 at 5 02 06 PM](https://user-images.githubusercontent.com/15004290/163429075-328bd1b4-92c6-4c3b-a042-71fe7b2bd53c.png)

### Steps to reproduce

None

### Expected behavior

A working product

### Which files are affected by this bug

3.4.4 

### Operating system

Mac OS

### Which version of the operating system you are running.

12.2

### Package

Appimage

### Nextcloud Server version

Nextcloud Hub II (23.0.2)

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi, could you provide the logs for the desktop client? Thanks

**Comment by RomyxBaps** [comment]
Apparently i have the same issue.
My directories or files won't sync anymore because the target doesn't exist (??).

I have no logs from the server or the desktop app.
I'm on Mac OS to with the version 3.4.4.

**Comment by RomyxBaps** [comment]
The solution for me was to downgrade the client desktop version to 3.4.1.

**Comment by ph00lt0** [comment]
Most-likely related: https://github.com/nextcloud/desktop/issues/4378

**Comment by ph00lt0** [comment]
https://github.com/nextcloud-snap/nextcloud-snap/issues/2107#issuecomment-1159091698
