### ISSUE TITLE
[Bug]: DPI issue with non-standard (not-96) DPI

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#4442]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

With a 4K screen, 100% scaling, the desktop client gives a rather unusable view of what's going on:
<img width="1271" alt="Screenshot_20220415_161726" src="https://user-images.githubusercontent.com/551757/163598968-b49c3d12-eb6a-4f64-9caf-40dc083abbcc.png">

Scaling is really off here, as you can see, the UI seems to think it has no space while it has plenty.

### Steps to reproduce

Run the client on a 4K 32" monitor without a fixed DPI (automatic DPI setting) which gives:
xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    5280x2560 pixels (931x451 millimeters)
  resolution:    144x144 dots per inch

You can force font DPI in KDE at least, see here below. Setting it to 96DPI fixes the prlbem.
<img width="511" alt="Screenshot_20220415_184112" src="https://user-images.githubusercontent.com/551757/163599196-4a14c59a-be7a-47a7-b644-0e5472aeea63.png">

### Expected behavior

The client can handle a DPI other than 96!

Potentially related or maybe the same: https://github.com/nextcloud/desktop/issues/2354

### Which files are affected by this bug

None, it's not relevant

### Operating system

Linux

### Which version of the operating system you are running.

openSUSE Tumbleweed, KDE Frameworks 5.93, Plasma 5.17.1

### Package

Appimage

### Nextcloud Server version

24RC1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nothing relevant I think
```

### Additional info

[debug.zip](https://github.com/nextcloud/desktop/files/8497121/debug.zip)

**Comment by claucambra** [comment]
Is your system running on the proprietary Nvidia GPU drivers?
