### ISSUE TITLE
[Bug]: cmake is missing default value for `PLUGINDIR`

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/desktop#4443]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When building the nextcloud desktop client on linux the vfs plugins are placed in the incorrect directory where they are not found.

The lib directory looks like :

```
 lib
├──  libnextcloud_csync.so ⇒ libnextcloud_csync.so.0
├──  libnextcloud_csync.so.0 ⇒ libnextcloud_csync.so.3.4.4
├──  libnextcloud_csync.so.3.4.4
├──  libnextclouddolphinpluginhelper.so
├──  libnextcloudsync.so ⇒ libnextcloudsync.so.0
├──  libnextcloudsync.so.0 ⇒ libnextcloudsync.so.3.4.4
├──  libnextcloudsync.so.3.4.4
├──  nextcloudsync_vfs_suffix.so
├──  nextcloudsync_vfs_xattr.so
└──  qt-5.15.3
    └──  plugins
        ├──  kf5
        │   └──  overlayicon
        │       └──  nextclouddolphinoverlayplugin.so
        └──  nextclouddolphinactionplugin.so
``` 

Notice that ``nextcloudsync_vfs_*.so`` files are not inside of the plugins directory where they should be and would be loaded.
This is because ``PLUGINDIR`` which is used to place the files has no longer a default since 3a3ccb0834bdeeda455e872bdf3ac3ea71bc7f90.

Debian places the files next to the plugins for dolphin https://salsa.debian.org/owncloud-team/nextcloud-desktop/-/blob/master/debian/rules#L15-16 which I am going to follow for NixOS where I am currently fixing the package.

### Steps to reproduce

1. Compile the program with ``-DCMAKE_INSTALL_LIBDIR=lib``

### Expected behavior

`PLUGINDIR` should have a reasonable default.

### Which files are affected by this bug

not relevant

### Operating system

Linux

### Which version of the operating system you are running.

NixOS unstable

### Package

Distro package manager

### Nextcloud Server version

not relevant

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
