### ISSUE TITLE
[Bug]: Client does not remove no longer existing shared folders from computer

### ISSUE THREAD

**Issue by wonx** [nextcloud/desktop#4444]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I have found out that when an external folder containing some shares with other users is no longer assigned to a user, the client does not remove the shared folders from the computers to which they were shared.

For instance, Person1 had an external storage with a shared folder with Person2. In the settings, I remove access for the external storage for that person. Person2, on the Nextcloud website will still see the shared folders, but empty. However, the client won't even delete the containing files from the computer. Any attempt to create or rename a file in those folders will end up in an error by the client.

### Steps to reproduce

1. Person 1, using external storage, share ones of its folders with Person 2
2. In Nextcloud Settings, no longer allow Person 1 to use the external storage.
3. Wait until the changes sync for everybody.

### Expected behavior

Person 2 should no longer have access to the shared folder, since Person1 no longer has rights to access it. Nextcloud desktop client should automatically remove the folder which are not shared anymore from the computer.

EDIT: this problem does not happen if the shared folders are unshared before access to the external storage is removed.

### Which files are affected by this bug

Any file or folder synced by nextcloud.

### Operating system

Linux

### Which version of the operating system you are running.

Kubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

23.0.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> EDIT: this problem does not happen if the shared folders are unshared before access to the external storage is removed.

And:

> Person2, on the Nextcloud website will still see the shared folders, but empty.

This is expected behavior IMO.

External Storage can be temporarily unavailable, so it's not expected that would result in deletion.

The *unsharing* event is what would trigger that. 



This is, in any event, a Server matter. 

For example, if you think that removing External Storage access should immediately expire all Shares associated with it.
