### ISSUE TITLE
[Bug]: Cannot set status on Fedora GNOME on Wayland

### ISSUE THREAD

**Issue by janvlug** [nextcloud/desktop#4445]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

It is impossible to set the status on GNOME on Wayland because of strange behavior of the windows and menus.

### Steps to reproduce

1. Open the Nextcloud Desktop main window (I've the option enabled to open in a normal window).
2. Click on the small triangle down next to the user name.
3. Click on the three dots next to the user name.
4. Click on Set status.

I see a window appearing shortly, then all Nextcloud Desktop windows close automatically. It looks like Nextcloud Desktop is restarting.

### Expected behavior

The status window stays on the screen and is functional, and I will be able to set the status in it.

### Which files are affected by this bug

This has noting to do with files.

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 35

### Package

Distro package manager

### Nextcloud Server version

22.2.6

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @janvlug we included a fix for crashing with the user status dialog in release 3.5.2, could you check if you are still facing the same bug on the latest release? Thanks!

**Comment by janvlug** [comment]
Thanks, I will test this as soon as 3.5.2 will be [available](https://bugzilla.redhat.com/show_bug.cgi?id=2103366) in the Fedora repository.

**Comment by janvlug** [comment]
I confirm that this is issue is fixed in version 3.5.2.

**Comment by claucambra** [comment]
Happy to hear this 🙂 I will close the issue now, thanks for reporting it
