### ISSUE TITLE
[Bug]: Nextcloud client on windows writes null to files instead of original content

### ISSUE THREAD

**Issue by dodancs** [nextcloud/desktop#4449]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The Windows version of the Nextcloud client syncs files successfully but replaces file content with null (see attached picture). It happens randomly.

I noticed that the issue mostly happens when I use a Nextcloud client for Ubuntu, and then when I switch back to Windows on a different machine, I can see that random files have been overwritten with null characters.

I tried to force-sync the files on the Windows client, but it says everything is up to date.

The files on the Nextcloud server and the Linux computer are still fine and are not affected by syncing of the Windows client.

![image](https://user-images.githubusercontent.com/1970811/164058821-533efb1c-e6d3-4ee4-8f70-81e049cd1428.png)

### Steps to reproduce

1. Use Nextcloud on Linux (Ubuntu 21.10 desktop)
2. Edit some files
3. Use Nextcloud on Windows (3.4.1, I later updated it to 3.4.4 but it did not do anything)
4. Notice some random files are now un-openable and when you examine their contents, they are full of `null` characters.
5. Shed enormous tears.
6. Grab your backup and replace the files manually.
...

### Expected behavior

The files should be synced properly. I see no reason why the Windows client decides to overwrite the already existing and properly synced files with `null` characters.

### Which files are affected by this bug

Any, I cannot predict which files are going to be destroyed

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro 21H2

### Package

Other

### Nextcloud Server version

22.2.6

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Logs do not show any trace of manipulation of the affected files.
```

**Comment by dodancs** [comment]
Nextcloud client Windows debug archive https://drive.google.com/file/d/1XoP8pXQqpLZU1yyed8_rkodF6vms5KsW/view?usp=sharing

**Comment by dodancs** [comment]
The same happened to me today in Ubuntu.. The server version was fine but the local copy was full of `0x00` characters.

![Screenshot from 2022-07-20 12-58-36](https://user-images.githubusercontent.com/1970811/179966495-fb1ae55d-50bd-42b2-8194-ec39c4b9fd58.png)

**Comment by dodancs** [comment]
Hey! This hasn't happened to me in a long time, so maybe it was fixed along the way in some version. I guess we can close the issue :)

**Comment by joshtrichards** [comment]
Closing per last comment.
Related: #5165
