### ISSUE TITLE
[Bug]: Sharing does not work on Windows

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#4455]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Pressing the sharing button in the tray window does not work. It does not bring up the sharing dialog on windows.

### Steps to reproduce

1. Open tray
2. Press share icon on a file activity

### Expected behavior

When clicking on the share icon, share dialog should be opened.

### Which files are affected by this bug

-

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![image](https://user-images.githubusercontent.com/1869584/164756159-71e8ba0d-d551-4665-9b3e-03bfe9895ecb.png)

**Comment by watercrossing** [comment]
I installed 3.5.0 on two new Win 10 installations yesterday and on neither one does the share dialog button work. I am also missing the Nextcloud context menu entirely on files and folders, regardless of sync status.
