### ISSUE TITLE
[Bug]: Typed domain but failed to connect to internal IP address? 

### ISSUE THREAD

**Issue by bowencool** [nextcloud/desktop#4456]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

nextcloud/server#32431

### Steps to reproduce

nextcloud/server#32431

### Expected behavior

nextcloud/server#32431

### Which files are affected by this bug

nextcloud/server#32431

### Operating system

Linux

### Which version of the operating system you are running.

nextcloud/server#32431

### Package

Appimage

### Nextcloud Server version

nextcloud/server#32431

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nextcloud/server#32431
```

### Additional info

nextcloud/server#32431

**Comment by claucambra** [comment]
Hi, I have transferred your original issue to the server repo, so I will close this one
