### ISSUE TITLE
Upgrade to QT6

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4461]
Upgrading underlying QT part to latest version 6.

Might fix
- #4365 
- #3244 (required step for fixing it)

Ticket for upgrading client updater server is: 
https://github.com/nextcloud-gmbh/customer-client_updater_server/issues/38
https://github.com/nextcloud/client_updater_server/issues/129

**Comment by mgallien** [comment]
would improve our support for newer OS and platforms notably for macOS arm64 platforms (support for the WebView needed for GSS)
would provide native looking qml UI elements for macOS and Windows (think of the share dialog or the settings dialog that should look native)

**Comment by mgallien** [comment]
for reference, the network status detection code changed a lot in Qt (was called bearer management see https://doc.qt.io/qt-6/network-changes-qt6.html)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@mgallien, you state that this would allow the Share Menu to appear native, yet for Windows, not that not necessitate XAML Islands calling the actual name Share menu that "https://blogs.windows.com/wp-content/uploads/prod/sites/3/2021/07/image2.png" depicts?

**Comment by mgallien** [comment]
> @mgallien, you state that this would allow the Share Menu to appear native, yet for Windows, not that not necessitate XAML Islands calling the actual name Share menu that "https://blogs.windows.com/wp-content/uploads/prod/sites/3/2021/07/image2.png" depicts?

you misunderstood me
I am not talking about a share menu but the Nextcloud desktop client share dialog. Currently we do have a native look but we may change the underlying implementation and this improvements could be easier to do with native look when using Qt6

**Comment by mgallien** [comment]
current state
![image](https://github.com/nextcloud/desktop/assets/168967/efb8d083-b9a4-42e8-9868-b1cb06ce6f6a)
only 1 automated test is failing `NetrcParserTest`
I would guess that anything between 5 to 10 days could do it by taking some margins
current move to qt6 is basic porting and we do not really make good use of new available features (not needed to move to qt6)
