### ISSUE TITLE
Lazy scanning when virtual files are enabled

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/desktop#4464]
It would be great to make it possible for the "virtual files" functionality to work more lazily:

- First sync: instead of spanning the entire folder hierarchy, limit to the first level or two, then trigger further scans only when the user actually opens the root folders, like other virtual drive clients currently do.
- Synchronization: as a consequence, only sync the already scanned folders, ignoring changes that are out of that span. 
- There could even be a de-hydration policy like "least recently used" or similar, to keep the synchronization set as small as possible in the long term. 

The basic idea behind this is that :

- the typical user needs to be able to start working on his/her workspace as quickly as possible, without minding about the contents outside those sub-folders. 
- the client should be able to scale reasonably well on big folder hierarchies in order to be competitive (or even viable as a solution). Ideally there should be the same kind of user experience (including responsiveness) when the user has to work on documents in a small share or in a very big one. 

Thanks!

**Comment by marcotrevisan** [comment]
Just for the records... saw this:

https://developer.apple.com/videos/play/wwdc2021/10182/

NSFileProviderReplicatedExtension seems to provide:

- all of the above;
- a nice and native implementation of virtual files out of the box;
- perhaps a reduction of the code needed to implement the NC client on mac, since all of the sync logic is handled by the system.

As a mac user this seems to be the best option at hand right now...

Thanks!

**Comment by marcotrevisan** [comment]
#1337 should close this and is in progress now, yay!

**Comment by PhilippSchlesinger** [comment]
See https://github.com/nextcloud/desktop/issues/4918#issuecomment-1246386007 for a description of a problem with the tray window related to speed issues for inital sync

**Comment by marcotrevisan** [comment]
(closed this because the new macOS implementation basically fulfills this request and I'm using Mac OS)
