### ISSUE TITLE
Folder encryption on OS

### ISSUE THREAD

**Issue by gmkrab** [nextcloud/desktop#447]
What about folder encryption on OS  client level? As example you can view Vipole Client.
(and decrypt with UNLOCK code)

**Comment by GLLM** [comment]
I may be mistaken vbut the client is meant to act as a licent for the server, and not provide some kind of encryption on the local machine.

**Comment by rullzer** [comment]
The client is not designed for this. If you want to have you data on your client encrypted I would suggest you look into full disk encryption or something like that.
