### ISSUE TITLE
[Bug]: Certificate issue on macOS / latest client 5.0git (build 10063)?

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/desktop#4477]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After installing the latest client, a certificate issue occurs telling that there seems to be an error with the certificate chain
<img width="631" alt="Bildschirmfoto 2022-05-03 um 17 28 39" src="https://user-images.githubusercontent.com/42076599/166485542-06ba5451-4a8b-4d8d-9649-33813222785f.png">
<img width="521" alt="Bildschirmfoto 2022-05-03 um 17 28 44" src="https://user-images.githubusercontent.com/42076599/166485550-0d489067-da83-43e4-b737-744c904d7ffe.png">
<img width="647" alt="Bildschirmfoto 2022-05-03 um 17 28 51" src="https://user-images.githubusercontent.com/42076599/166485554-69a6fc08-dbaf-46d5-b7ec-5c8e3f864106.png">

### Steps to reproduce

- Trying to connect to my Nextcloud
- Checking the Certificate: Okay (Let's Encrypt)
- Web works fine, no errors
- Connection-/certificate error when trying to connect to my instance

### Expected behavior

Connecting the client like earlier versions without any issue after the initial connection/configuration dialog. Looking in the browser, the certificate appears to be valid and also the mobile Client (iOS) works without any problem.

<img width="473" alt="Bildschirmfoto 2022-05-03 um 17 27 31" src="https://user-images.githubusercontent.com/42076599/166485826-465b1992-76b5-49cd-a471-546dfbd20d2a.png">

### Which files are affected by this bug

Nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Monterey 12.3.1

### Package

Appimage

### Nextcloud Server version

24.0.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by OliverPifferi** [comment]
Reinstall of the client fixed this for whatever reason.

**Comment by claucambra** [comment]
Hi @OliverPifferi does the server use TLSv1.3? Seems very similar to #3974

**Comment by claucambra** [comment]
> Reinstall of the client fixed this for whatever reason.

That is strange but glad the issue was resolved :)
