### ISSUE TITLE
[Bug]: Desktop client crashes on Talk notification

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/desktop#4479]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Desktop client crashes when receiving a call.
I just got the update of the desktop client to 3.5.0 via the ubuntu package:
https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

![grafik](https://user-images.githubusercontent.com/213943/166559161-bedb9db9-644a-4b1f-a17b-ea2d0b1a02cd.png)

If the screenshot is not enough, I saved some log and a debug archive,
But it reproduces 100% of the time.

### Steps to reproduce

1. Installed 3.5.0 update
2. Stopped the running desktop client
3. Started it again and confirmed 3.5.0 is running
4. Open a public conversation in a private window and called "myself" without logging in on the browser, so a "guest" called.

### Expected behavior

Call notification

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

23.0.4

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing related
```

**Comment by claucambra** [comment]
Hey @nickvergessen I'm unable to reproduce on 22.04 (Wayland) following your steps, could you reproduce and provide the desktop client's logs (and a backtrace if possible)? Thanks!

**Comment by claucambra** [comment]
Nevermind, able to reproduce on a fresh install. Seems to me like there is a package dependency missing here...

**Comment by claucambra** [comment]
Correct, installing `qml-module-qtmultimedia` fixed it -- seems like we need to add this to the `nextcloud-desktop` package's dependencies @ivaradi

**Comment by nickvergessen** [comment]
`apt install qml-module-qtmultimedia` fixes it, yes!

**Comment by nickvergessen** [comment]
>$ aptitude why qml-module-qtmultimedia
>    nextcloud-desktop Hängt ab von qml-module-qtmultimedia

There was an update available today and now the package is installed.
