### ISSUE TITLE
[Bug]: RTF (Rich Text Format) file gets broken when uploading it to Nextcloud and downloading from there again

### ISSUE THREAD

**Issue by claell** [nextcloud/desktop#4480]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I just discovered that under some conditions, an RTF file gets broken for me in a way that it cannot be opened again in MS Word (crash showing a document restore which is not working).

Not sure what causes this and not that much time right now, but wanted to note this, so this is listed somewhere as a potential issue that can happen in some cases.

### Steps to reproduce

1. Upload the RTF file (either using sync client, folder sync activated, no virtual files; or trough Browser)
2. Download through Browser (Firefox used in my case) - Maybe the issue is introduced here
3. Open file again, it is broken

### Expected behavior

Everything works as expexted

### Which files are affected by this bug

RTF

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is unknown.

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

File is confidential, might be able to share it under certain conditions.

Also, this might be a server bug, not related to the Client.

**Comment by claell** [comment]
As this also happens when uploading the file in the browser, I don't think it is related to desktop. So I created https://github.com/nextcloud/server/issues/32267. I guess, this one can be closed.

**Comment by joshtrichards** [comment]
Closing here as this isn't client specific.
