### ISSUE TITLE
[Bug]: Profile picture only loaded when selecting account

### ISSUE THREAD

**Issue by tryallthethings** [nextcloud/desktop#4487]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When having multiple accounts configured, only the profile picture for the first (the one, that is automatically selected when opening the settings window) is loaded. All other profile pictures are only loaded when selecting the respective account. This issue has been present for probably the last 4-5 released desktop client versions.

### Steps to reproduce

1. Open settings window via taskbar. Right click Nextcloud, select "Settings"
2. Only profile picture of first account is loaded:
![image](https://user-images.githubusercontent.com/11146296/166942715-813f80d3-5668-470a-a410-bd1d10b5aec6.png)

4. Click other accounts and the image will be loaded from the server with a slight delay (300-700ms):
![image](https://user-images.githubusercontent.com/11146296/166942999-df1e7b17-261f-476f-b9f6-8eea51234c0c.png)

6. Close settings window
7. Go back to 1 and repeat. Even if the settings window is only closed for just a second.

### Expected behavior

All icons should be loaded right away when opening the settings window.

### Which files are affected by this bug

not a file issue

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 21H1

### Package

Other

### Nextcloud Server version

23.0.4

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing in the logs
```

### Additional info

#4306 is still an issue for me. The generated debug archive is 37.5MB large and I can't upload it to GitHub. Had to split the debug archive into two files again:

[debug_archive_other.zip](https://github.com/nextcloud/desktop/files/8631990/debug_archive_other.zip)

[debug_archive_logs.zip](https://github.com/nextcloud/desktop/files/8631984/debug_archive_logs.zip)

### Nextcloud Client version

3.5.0

**Comment by nursoda** [comment]
This bug is present since 3.1.0 at least, as can seen by this [duplicate bug report](https://github.com/nextcloud/desktop/issues/2731). @Devs, please close one of the bugs as duplicate.

**Comment by nursoda** [comment]
@tryallthethings please close this as duplicate. There is at least one more [duplicate (already closed)](https://github.com/nextcloud/desktop/issues/2881). In it, @er-vin suspects, that "this goes all the way back to 3.0.0."

**Comment by tryallthethings** [comment]
Duplicate of #2731
