### ISSUE TITLE
[Bug]: Cannot download update from settings; clicking the link opens 7 tabs of the download page

### ISSUE THREAD

**Issue by eibex** [nextcloud/desktop#4506]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Clicking the link opens 7 tabs of the download page:
![image](https://user-images.githubusercontent.com/40539455/167380281-8c580aa5-6365-46a6-a1ef-afe45ed3947d.png)
![image](https://user-images.githubusercontent.com/40539455/167380312-0428aafd-5e8a-48bb-831b-812c380f0134.png)

### Steps to reproduce

1. Nextcloud doesn't manage to download the update automatically
2. Click the link for manual download

### Expected behavior

1. Nextcloud downloads automatically
2. If it doesn't manage only 1 tab is opened

### Which files are affected by this bug

n.a.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Client version is 3.4.4

**Comment by andrew-jolley** [comment]
Just to add, this happens on macOS 12.4 as well with Nextcloud 3.5.1

**Comment by eibex** [comment]
Working now for me with 3.5.1 on Win10, not sure what are the steps to reproduce this

**Comment by andrew-jolley** [comment]
Yep agree that issue is gone
