### ISSUE TITLE
[Bug]: Cannot Free up local space from small files (~1kB or less) in Windows

### ISSUE THREAD

**Issue by wonx** [nextcloud/desktop#4509]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

There seems to be an error when freeing up local space using the virtual file system in Windows (does not happen in linux) in the latest 3.5 desktop client.

For small files, with a few kB at most, after right clicking on a file and select to *free up local space*, the desktop client keeps syncing that file indefinitely. For files 5kB or larger the problem disappears. It's easy to replicate by creating a new text file, and keep adding random text inside until the sync works fine again. The same happens for non-text files as well.

Editing or deleting these small files works fine, though.

On the server size, I do not see any reference to that file, indicating that this is likely entirely an issue with the client.

### Steps to reproduce

1. Create new text file and write a couple of lines in it.
2. Wait until it syncs with Nextcloud
3. Right click on the file, and select *Free up local space*
4. Observe how nextcloud desktop client keeps trying to sync the same file over and over again
5. Now add a few more lines to the same file, until it reaches a size of 5kB or larger. 
6. Right click on the file, and select *Free up local space* once again.
7. Observe how now the sync works fine now.

### Expected behavior

Nextcloud should be able to free up the local space for virtual files regardless of the file size.

### Which files are affected by this bug

All of them

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by wonx** [comment]
Still an issue in client 3.5.1 for Windows.

**Comment by trenoduro** [comment]
![image](https://user-images.githubusercontent.com/22579965/171001078-0bc0dc81-2fc6-4a52-95f3-e45a58a408a5.png)

Same for me, but it happens for files a little larger than 1kb too

**Comment by Keden92** [comment]
Windows Client Version 3.5.1 - Issue hits all Files, smaller than the Blocksize of the Client HDD (4.096Byte in my Case). After using the Function "Free up space", the file keeps Accessible, even if the NC-Client is shuted down - it's simply not free'd up - Bigger Files (>= 4096) get an Error Message to check if the Client is running. - Small *.png icons are good test files to reproduce, they get scaled up after "Free up space", because the metadata aren't available anymore, but the file stays. Try'd to clean up Explorer Caches, but it takes no effect.  

My Workaround: Files smaller 4 KB -> "Always keep on this device", to get them out of the SyncLoop.

![NC_ClientBug](https://user-images.githubusercontent.com/36050854/175995179-5d563d84-c7cd-49a9-9bd4-a2601315b717.JPG)

**Comment by bluehacker007** [comment]
Is there a way to bring more attention to this issue? I just upgraded to v3.5.2 on Windows 11 and have the same issue. I noticed that this has also been discussed quite a bit on IssueHint. https://issuehint.com/issue/nextcloud/desktop/4226

**Comment by pzwahlen** [comment]
This actually looks like a duplicate of https://github.com/nextcloud/desktop/issues/4226 which was opened in January. It is still an issue with client 3.5.2 and server 24.0.2.

**Comment by quantumfrost** [comment]
Same issue on 3.5.4

**Comment by Ogloppi** [comment]
I can confirm this issue still affects client version 3.6.0.

**Comment by ngvoicu** [comment]
> I can confirm this issue still affects client version 3.6.0.

I can confirm also.

**Comment by trenoduro** [comment]
Any update on this?

**Comment by DemoFreak** [comment]
Still exists in 3.6.2

**Comment by socialcatde** [comment]
Yes, very small files have that problem for me too. They are on the server though. Just not shown as synced.

**Comment by NeoTheOne** [comment]
I have the same problem, NC24 using 3.6.4.

**Comment by Asrothear** [comment]
Same Porblem
Nextcloud Desktop-Client
Version 3.6.4 (Windows)

Server
Version
Nextcloud Hub 3 (25.0.2)

**Comment by ECARBON77** [comment]
i have this problem too, on fresh nextcloud hub 3 server side and windows client latest version at this day.

**Comment by Stoffel324** [comment]
I still have the same issue

Nextcloud Desktop-Client
Version 3.6.5 (Windows)

Server
Nextcloud Hub 3 (25.0.2)

Really annoying it just repeats this all the time.

![image](https://user-images.githubusercontent.com/9263401/213515958-889c3638-e928-4995-9034-39612540ef4f.png)

It messes with sync of other files.

**Comment by Ap0ph1s-W4ite** [comment]
Version 3.6.6 have the same bug yet.

**Comment by trenoduro** [comment]
This looks fixed in 3.8.1
Can anyone confirm?

**Comment by wonx** [comment]
Hi @trenoduro, I tested it with the files that originally caused this issue, and it seems to be fixed. Thanks.
