### ISSUE TITLE
client does not longer start (leap 15.0)

### ISSUE THREAD

**Issue by tomthecat** [nextcloud/desktop#451]
After a `zypper up` the nextcloud client refuses to start.
`Abgebrochen (Speicherabzug geschrieben)`

QT_DEBUG_PLUGINS=1 nextcloud
`Got keys from plugin meta data ("generic")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib64/qt5/plugins/bearer/libqnmbearer.so"
Found metadata in lib /usr/lib64/qt5/plugins/bearer/libqnmbearer.so, metadata=
{
    "IID": "org.qt-project.Qt.QBearerEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "networkmanager"
        ]
    },
    "className": "QNetworkManagerEnginePlugin",
    "debug": false,
    "version": 330497
}

Got keys from plugin meta data ("networkmanager")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/bearer" ...
loaded library "/usr/lib64/qt5/plugins/bearer/libqconnmanbearer.so"
loaded library "/usr/lib64/qt5/plugins/bearer/libqgenericbearer.so"
loaded library "/usr/lib64/qt5/plugins/bearer/libqnmbearer.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib64/qt5/plugins/iconengines" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib64/qt5/plugins/iconengines/libqsvgicon.so"
Found metadata in lib /usr/lib64/qt5/plugins/iconengines/libqsvgicon.so, metadata=
{
    "IID": "org.qt-project.Qt.QIconEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "svg",
            "svgz",
            "svg.gz"
        ]
    },
    "className": "QSvgIconPlugin",
    "debug": false,
    "version": 330497
}

Got keys from plugin meta data ("svg", "svgz", "svg.gz")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/iconengines" ...
Abgebrochen (Speicherabzug geschrieben)`

Version:
`nextcloud --version
Nextcloud version 2.3.3
Using Qt 5.11.1, built against Qt 5.9.4
Using 'OpenSSL 1.1.0h-fips  27 Mar 2018'`

Journald protocol:
`qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 8469, resource id: 121634821, major code: 18 (ChangeProperty), minor code: 0`

nextcloud --logfile logfile

`[...]
06-26 22:26:25:962 3094 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.23.1"
06-26 22:26:25:962 3094 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
06-26 22:26:25:962 3094 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
06-26 22:26:25:962 3094 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
06-26 22:26:25:962 3094 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
06-26 22:26:25:962 3094 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
06-26 22:26:25:962 3094 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget")
06-26 22:26:25:963 3094 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
06-26 22:26:25:963 3094 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.23.1"
06-26 22:26:25:963 3094 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
06-26 22:26:26:217 3094 OCC::SqlQuery::exec: Sqlite exec statement error: 14 "unable to open database file" in "CREATE TABLE IF NOT EXISTS metadata(phash INTEGER(8),pathlen INTEGER,path VARCHAR(4096),inode INTEGER,uid INTEGER,gid INTEGER,mode INTEGER,modtime INTEGER(8),type INTEGER,md5 VARCHAR(32),PRIMARY KEY(phash));"
06-26 22:26:26:217 3094 OCC::SyncJournalDb::sqlFail: SQL Error "Create table metadata" "unable to open database file"
06-26 22:26:26:217 3094 OCC::SyncJournalDb::sqlFail: ASSERT: "false" in file /home/abuild/rpmbuild/BUILD/nextcloud-client_2.3.3/client/src/libsync/syncjournaldb.cpp, line 220
06-26 22:26:26:217 3094 OCC::SqlDatabase::close: ENFORCE: "_errId == 0" in file /home/abuild/rpmbuild/BUILD/nextcloud-client_2.3.3/client/src/libsync/ownsql.cpp, line 160 with message: Error when closing DB`

uname --all
`Linux xyz 4.12.14-lp150.12.4-default #1 SMP Tue May 22 05:17:22 UTC 2018 (66b2eda) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by juliushaertl** [comment]
Can you verify that the folder that the client tries to sync to has proper permissions for reading/writing? 

Just in case you want to help we now have daily builds with the latest code changes available at https://download.nextcloud.com/desktop/daily/ So if you like, feel free to test those and check if the issue still persists with that.

**Comment by tomthecat** [comment]
Thanks for pointing me in the right direction. I was able to start the AppImage dated 20180702 and found two sync problems which could be resolved by deleting files.
Afterwards, the nextcloud client version from my distribution started again.

**Comment by javierllorente** [comment]
Nextcloud client 2.3.3 works fine on openSUSE Leap 15.0
(I am using the default repositories)
```
javier@linux-q4kl:~> nextcloud --version
Nextcloud version 2.3.3
Using Qt 5.9.4, built against Qt 5.9.4
Using 'OpenSSL 1.1.0h-fips  27 Mar 2018'
```
