### ISSUE TITLE
Group policy to set offline files only for all user accounts on a Terminal Server?

### ISSUE THREAD

**Issue by tromlet** [nextcloud/desktop#4513]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Hey all -

We’ve spun up a Windows Server 2019 x64 instance to replace our aging Windows Server 2008 R2 Terminal Server, and FOR THE MOST PART we like to run on-prem with open-source software. Unfortunately, Ubuntu Linux and LibreOffice are anathema to most people, so we have to have Microsoft stuff in our ecosystem so that people can have the familiarity of Windows and Office to do their work.

Still, we would prefer to use our Nextcloud instance rather than OneDrive to synchronize our files to a nice cloud interface - it would be really nice if I could mandate global settings for all users in the desktop clients, via Windows’ built-in Local Group Policy Editor? Specifically, I’d like to make sure that nobody can force download all their files locally, since their files are going to be downloaded and live on a virtual hard disk.

**Comment by joshtrichards** [comment]
Similar to https://github.com/nextcloud/desktop/issues/5559#issue-1649448858

Let's consolidate tracking and discussion this enhancement in #5559. Feel free to subscribe/upvote/etc there.
