### ISSUE TITLE
Make call notification appear on top of other windows

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/desktop#4523]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
To date, the call notification works well, but, if I have plenty of opened windows, it is hidden in the background, and I have to minimize all windows to find it.

It would be great to have that call notification right on top of other windows, to accept or decline straight away.

**Comment by claucambra** [comment]
Hi, what OS are you running? If on Linux, what desktop (and is it Wayland/X11?) Thanks!

**Comment by maximelehericy** [comment]
Hi Claudio, I am using Windows 11

**Comment by camilasan** [comment]
I have noticed this too on my Linux, Archlinux/KDE, X11.
