### ISSUE TITLE
LDAP & Application Passwords should play nicer

### ISSUE THREAD

**Issue by deajan** [nextcloud/desktop#454]
Hello,

Of what I am understanding, an application password is supposed to help gain access to NextCloud Server without having to specify the real password.

When a LDAP user changes its password, the application password dissappears.
Since the LDAP user is not desactivated (only password has been changed), I think it would be much better to keep the application password working so the client application still can sync, without having to change that application password on every "password change".

There could be an option to make application passwords "permanent" until manual revocation, unless an admin policy forbids to.

Any thoughts ?

**Comment by rullzer** [comment]
We are working on improving this. But this is really a server issue as the client doesn't even know the backend used is LDAP ;)

**Comment by deajan** [comment]
Sorry, opening the isse on the server side :)
