### ISSUE TITLE
Wording in connection wizard

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#456]
The dialog is called the  `Verbindingswizard` here 😄 @jospoortvliet could you correct the sreenshot somehow as it looks quite strange in the article. Also everything is english in the dialog except the title.

![wizard](https://nextcloud.com/media/desktop-client-login-flow.png)

**Comment by rullzer** [comment]
Yeah would require a new VM that is set to english.. anyways not a desktop issue.

**Comment by splitt3r** [comment]
But the wrong wording is still an issue?

**Comment by rullzer** [comment]
No it is not. My VM was set to dutch. So it actually is the correct wording
