### ISSUE TITLE
[Bug]: Since 3.5 on Windows the tray app layout is broken

### ISSUE THREAD

**Issue by ThumbGen** [nextcloud/desktop#4561]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Simple to repro (on 2 different machines, one running Windows 10 the other one Windows 11, both with all updates installed).
We use a branded instance which was working fine with 3.4.x

Click the tray icon and look at the dialog layout:

![image](https://user-images.githubusercontent.com/1526157/169024491-a9e13290-cb2b-4099-b3af-d9902eea7377.png)

### Steps to reproduce

1. Click the tray icon
2. The dialog layout is completely broken

### Expected behavior

The dialog layout should be fine :)

### Which files are affected by this bug

nextcloud.exe

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 and 11

### Package

Other

### Nextcloud Server version

23.0.0

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by dorpauli** [comment]
This dialog is no longer displayed at all in Linux Mint 20.3.

**Comment by dorpauli** [comment]
With the new update, it is now visible in Linux Mint, but the text is black above black. 😄 
![grafik](https://user-images.githubusercontent.com/70518303/169654353-df9963ed-0a63-497b-8321-112ad4f21307.png)

**Comment by camilasan** [comment]
This Windows 10 with light and dark theme running 3.5.1:

![351windows-lighttheme](https://user-images.githubusercontent.com/241266/174813810-ced32ff3-d203-41b7-be1a-4f2baaba216a.png)
![351windows](https://user-images.githubusercontent.com/241266/174813815-71c3c7bb-67f5-4903-84b5-92272d9d225d.png)

do you still see the bugged UI after rebooting? Was this after right running the updater? Did you change the theme in between?

**Comment by ThumbGen** [comment]
@camilasan We have the following:
* we automate building the Desktop Client using https://github.com/nextcloud/client-building
* we apply a custom branding (replacing some icons/images, by copying them over during the building process)
* we take over the deliverables of the build and create our own setup (based on our internal MSI templates)

This was working nice and smooth until 3.5 came. Our setup produces now the output from my screenshot, tested on both Windows 10 and Windows 11.

**Comment by ThumbGen** [comment]
There were changes in Style.qml which were overwritten by our branding. After applying the correct Style.qml the UI looks OK.
Sorry for the incovenience!

**Comment by camilasan** [comment]
Just in case @ThumbGen, @matthieugallien pointed out that it could be related to opengl issues, so here it is a build for Windows that could fix it: https://cloud.nextcloud.com/s/35KNsN2AKfNzRYJ (this is his PR #4582)
