### ISSUE TITLE
Manual written release notes

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/desktop#4565]
I am on of the maintainers of the nextcloud desktop client package on NixOS. When updating the package I usually read the changelog in the releases tab to make there are no breaking changes I need to be aware. But if the changelog section only contains a git short log which I can easily view in the git history then I am not sure if I am missing any breaking change, the update is urgent because of security fixes or only 1 minor change is included. It would be nice to either have a hand written changelog or a link to the summary on help.nextcloud.com which I couldn't find.

**Comment by github-tomster** [comment]
@SuperSandro2000 
this seems to be a 🔥  topic
there is just another [issue ](https://github.com/nextcloud/desktop/issues/4791)
barely 72days behind ⌚ 
and 🥁  there is more data available: https://github.com/nextcloud/desktop/issues/1952 https://github.com/nextcloud/desktop/issues/1506 https://github.com/nextcloud/desktop/issues/1194 in descening order 🧻 
maybe this is usefull to pragmatically solve the issue 🤞🏻 🍀 

**one can read this feedback given in my leisure time for free!**

**Comment by SuperSandro2000** [comment]
I'd would be happy with 10 entries in the changelog with the most significant changes and not every nitty little detail.
