### ISSUE TITLE
[Bug]: Macos 10.13.6, Client 3.5.1, cannot start Nextcloud.app, but worked in 3.5.0

### ISSUE THREAD

**Issue by labor4** [nextcloud/desktop#4567]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I cannot start the Nextcloud.app on High Sierra.
It did start when version was 3.5.0

### Steps to reproduce

- Remove previous Nextcloud.app from /Applications
- Install using pkg installer (3.5.1)
- Double click on app.

No response in Finder.
Starting Nextcloud.app via commandline using path `/Applications/Nextcloud.app/Contents/MacOS/Nextcloud`shows the error under "additional info".

### Expected behavior

start app

### Which files are affected by this bug

Nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

Macos 10.13.6

### Package

Other

### Nextcloud Server version

23.0.4

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Starting Nextcloud.app from CMDline shows this:

```
KellnerMacbook:~ lb4$ /Applications/Nextcloud.app/Contents/MacOS/Nextcloud 
2022-05-18 17:59:14.894 Nextcloud[651:11382] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff5477ff3b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7bad8942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff547bffcc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff5468020d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x00007fff54687304 +[NSArray arrayWithObjects:count:] + 52
	5   Nextcloud                           0x00000001024d4b1b _ZN3OCC30registerNotificationCategoriesERK7QString + 187
	6   Nextcloud                           0x000000010239a59e _ZN3OCC7SystrayC2Ev + 430
	7   Nextcloud                           0x000000010239a055 _ZN3OCC7SystrayC1Ev + 21
	8   Nextcloud                           0x0000000102399ff6 _ZN3OCC7Systray8instanceEv + 54
	9   Nextcloud                           0x0000000102232697 _ZN3OCC14AccountManager13createAccountEv + 279
	10  Nextcloud                           0x000000010222dfe1 _ZN3OCC14AccountManager17loadAccountHelperER9QSettings + 705
	11  Nextcloud                           0x000000010222c586 _ZN3OCC14AccountManager7restoreEv + 1974
	12  Nextcloud                           0x000000010225ceb4 _ZN3OCC11ApplicationC2ERiPPc + 6644
	13  Nextcloud                           0x0000000102262dc5 _ZN3OCC11ApplicationC1ERiPPc + 37
	14  Nextcloud                           0x00000001021f43aa main + 682
	15  libdyld.dylib                       0x00007fff7c6f3015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by claucambra** [comment]
Hi @labor4, I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14, as the UserNotification system required for actionable notifications in macOS is unavailable on versions <10.14. If you need the desktop client and are unable to upgrade your OS, we recommend you stick to version 3.5.0 of the desktop client or lower to retain compatibility

**Comment by labor4** [comment]
@claucambra 
too bad. 3.5.0 has finder extension issues too. 
how long do you expect 3.4.4 to be a compatible option?
is it possible to build the client without these extra needs?
mine is a low-end tech laptop (admin maintenance and docs), so would be a waste for me to take out of the work chain. 

thanks

**Comment by claucambra** [comment]
> @claucambra too bad. 3.5.0 has finder extension issues too. how long do you expect 3.4.4 to be a compatible option? is it possible to build the client without these extra needs? mine is a low-end tech laptop (admin maintenance and docs), so would be a waste for me to take out of the work chain.
> 
> thanks

You could fairly easily copy and paste the original notification code from 3.4.x in place of the new code for notifications in `systray.mm` and build the client that way, you'd just have to remove the call to the specific macOS update notification in `systray.cpp`. I can guide you further if you need. Once those changes are done you'd be able to build the client. You would have to progressively cherry-pick new additions, however, so it's far from ideal.

Though we won't officially support 3.4.4, until there is a change in the synchronisation mechanism (none so far) you should be able to keep using it for now, though obviously you won't be able to take advantage of new features. I'd expect file sync to keep working for some time.

**Comment by labor4** [comment]
O-ou...
thanks.
Are these the GUI notifications in Finder?
Ironically I always disable these in every app.

But looking at the code I sense I am by far underqualified to do this.
I compared the two tags, and as I should have expected, one does not simply "comment out" this dependency 😆, as they are being called from everywhere.

but thank you.

**Comment by rakekniven** [comment]
> I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14

Hello @claucambra , the website does not reflect this correctly. It states minimum version is 10.12 (!). 
Please update it.

**Comment by claucambra** [comment]
> > I'm sorry to say with 3.5.1 we are bumping up our minimum requirements for macOS to 10.14
> 
> Hello @claucambra , the website does not reflect this correctly. It states minimum version is 10.12 (!). Please update it.

There is an open PR for this: https://github.com/nextcloud/nextcloud.com/pull/1648

**Comment by modelcode** [comment]
https://github.com/nextcloud/desktop/releases/download/v3.5.0/Nextcloud-3.5.0.pkg

**Comment by Jaxan** [comment]
I was also struck by this issue. And it is a bit annoying that there is no alert or other feedback telling me what the problem is. It just doesn't work without any message.

Further, I have now installed 3.5.0 which works (thanks!). But anytime Nextcloud starts, it shows me a notification that there is an update, which is misleading.

**Comment by rakekniven** [comment]
> Further, I have now installed 3.5.0 which works (thanks!). But anytime Nextcloud starts, it shows me a notification that there is an update, which is misleading.

There is v3.5.1 out since 17th may. You can disable update check in client settings.
