### ISSUE TITLE
[Bug]: File Manager Overlay Icons not visible in MacOs Monterrey 12.3.1

### ISSUE THREAD

**Issue by n3storm** [nextcloud/desktop#4568]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

With Google Drive enabled:
![imagen](https://user-images.githubusercontent.com/220748/169240805-d88c0e52-23a1-4e98-8f24-5e9ed6417a9d.png)

After Google Drive enabled and Finder restarted:
![imagen](https://user-images.githubusercontent.com/220748/169240999-af11e7aa-6457-4ed9-8875-c48ebcdbdbe8.png)

### Steps to reproduce

1. Install Google Drive
2. Install Nextcloud Desktop
3. Browse to Nextcloud Folder on Finder and synchronization icons will not appear

### Expected behavior

 Browse to Nextcloud Folder on Finder and synchronization icons should appear

### Which files are affected by this bug

all

### Operating system

Mac OS

### Which version of the operating system you are running.

Monterrey 12.3.1

### Package

Other

### Nextcloud Server version

22.2.7

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by cbean** [comment]
I have the same issue, without Google Drive installed.

**Comment by squareclouds** [comment]
same here, nextcloud + google drive, nextcloud icons dont appear

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
