### ISSUE TITLE
Release objectives

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/desktop#457]
Hi,

What are the goals of the 2.5 release

Im massively excited by this update, as it does feel nextcloud client has fallen behind the owncloud development thread, obvious by the fact we are still using a straight fork of an old owncloud version

Im all in as a tester !

ZT

**Comment by camilasan** [comment]
Hi, 

Good to hear :)
I am guessing you saw this: https://github.com/nextcloud/desktop/projects/1
I think the main features and improvements are: end to end encryption, web login, providers and UI changes regarding notifications.

For testing you can download it from https://download.nextcloud.com/desktop/daily/.

Thanks!
