### ISSUE TITLE
[Bug]: Desktop Client on Win Server OS missing virtual files option

### ISSUE THREAD

**Issue by itserrick** [nextcloud/desktop#4576]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Unable to use virtual files option.

Using virtual files plugin: suffix is shown 

### Steps to reproduce

Install Desktop Client
Setup sync, option for virtual files missing

### Expected behavior

Virtual files option to appear since it is a windows desktop client

### Which files are affected by this bug

All folders unable to use virtual files

### Operating system

Windows

### Which version of the operating system you are running.

Server 2012 R2, Server 2016

### Package

Official SNAP package

### Nextcloud Server version

23.0.3

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This might be related to OS check. Prior Desktop client wasn't able to install on Win Server OS, since it checks for Win 10. Possibly the virtual file plugin is still checking and shows not compatible and goes suffix as if system is Linux or Mac.

**Comment by andyxheli** [comment]
You’ll know that Files On-Demand is turned on if you see the status icons next to your files in File Explorer. OneDrive Files On-Demand requires version 1709 or later, or Windows Server 2019, and OneDrive build 17.3.7064.1005 or later.

That's the reason why you cant see Virtual Files on Server 2012 R2 and 2016 Microsoft dose not add at code that Nextcloud desktop needs to enable virtual files 


https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-10-0e6860d3-d9f3-4971-b321-7092438fb38e

**Comment by itserrick** [comment]
@andyxheli Thanks. Didn't realize that limitation. I made the assumption Server 2016=Win10 era. My mistake. Fortunately it's a nice to have feature not a requirement at the moment.

**Comment by andyxheli** [comment]
No problem!! Ran through the same problem! Thats MS for you!!
