### ISSUE TITLE
Empy connection wizzard after closing the client

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#458]
After closing the Nextcloud client it shows an empty connection wizzard for one or two seconds. I´m running the daily build from yesterday on the latest Windows 10.

![connection wizzard](https://user-images.githubusercontent.com/1869584/42093637-4ff4397e-7bad-11e8-83a8-7cbf409ba2b5.png)

**Comment by rullzer** [comment]
Yes I noticed this as well.

I'll look into it..
