### ISSUE TITLE
[Bug]: Nextcloud.exe crashes after start synching. Windows Event viewer shows KERNELBASE.dll exceptions. Virtual File Support related bug.

### ISSUE THREAD

**Issue by mhamra** [nextcloud/desktop#4581]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud.exe 3.5.1.20220517 crashes after start synching.

...

### Steps to reproduce

1. Execute Nextcloud.exe
2. Nextcloud Icon shown in the running applications windows Bar
3. Clicking the Nextcloud icon, a popup windows is shown with a status bar
4. after a couple of seconds, the popup and the windows bar Nextcloud icon are disapearing 
5. An event error is created on windows bar
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

nextcloud.exe

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro

### Package

Other

### Nextcloud Server version

20.0.14

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I've been moving files from OneDrive to Nextcloud folder. Both apps were configured with virtual directories. I don't know in what condition the error started to appear, but once nextcloud.exe started to crash, i had to pause synching to let the application work. So, the crash is related to the synch process.

I've tried to remove the connection, I've created a new connection, I've moved the files from the old connection directory to the new one except files .sync* found on the connection root folder. After starting synching, the same problem arose.

After pausing the synch process, disabling virtual file support and resume synching, nextcloud.exe completed the synch process.

It seems that the bug is related to virtual file support

**Comment by bravedave** [comment]
I found this post useful

- I'm Win11 Pro
- Server is Version 24.0.1
- I'm not moving files, simple install and sync from server

The app was virtually unusable, just crash - sync log was empty, but messages said something could be synced and check the logs …

Checked here, found post, disabled Virtual File Support and it's working as expected

**Comment by camilasan** [comment]
@mhamra We will need the desktop client logs.

**Comment by skylord123** [comment]
I added a new share folder and had enabled virtual files which then led Nextcloud to crash every time a sync started.

I am on the latest version Nextcloud Hub 3 (25.0.4) and using the latest Nextcloud desktop app (downloaded just a few days ago). I was able to quickly disable virtual file on the share folder then it stopped crashing.

Event viewer log:
```
Faulting application name: nextcloud.exe, version: 3.7.4.45221, time stamp: 0x6409eca9
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2546, time stamp: 0xe8e9ac9b
Exception code: 0xc0000005
Fault offset: 0x00000000000358f8
Faulting process id: 0x4064
Faulting application start time: 0x01d95b6ea952d8f9
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2f5a83d8-45e8-4bd0-9bd9-6f9ff1429ec3
Faulting package full name: 
Faulting package-relative application ID: 
```

So this is still an on-going issue.

**Comment by skylord123** [comment]
I tested creating a new share on another drive (D:) to ensure OneDrive wasn't using the directory. This new share works perfectly fine with Virtual Files enabled. This is looking more like a miss-compatibility between OneDrive & NextCloud both using virtual files. It's also possible there is something else going on inside my user directory since I am on a corporate machine.

To everyone having this issue, are you using two file sync clients (OneDrive, DropBox, Nextcloud, etc)?

**Comment by JackyWay** [comment]
I face the same issue when syncing the folder with both clients (CloudNext and Synology Drive).

Faulting application name: nextcloud.exe, version: 3.10.0.45827, time stamp: 0x65047110
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xc0000005
Fault offset: 0x0000000000035ae8
Faulting process id: 0x3888
Faulting application start time: 0x01d9fa7d78e7bc19
Faulting application path: C:\Program Files\Nextcloud\nextcloud.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: bee139cd-295d-4125-8232-84a9cc5e70e0
Faulting package full name: 
Faulting package-relative application ID:
