### ISSUE TITLE
[Bug]: Since 3.5.1 all local folders with Turkish undotted-i (ı) getting scrambled

### ISSUE THREAD

**Issue by alerque** [nextcloud/desktop#4585]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Since 3.5.1 all local folders with Turkish undotted-i (ı) getting scrambled. The existing sync copy sits there, but a second copy of all the directories gets uploaded with a clearly mis-encoded garbage string, creating two sets of files on the server. Additionally local sync errors are shown.

### Steps to reproduce

1. Have existing local & remote directories or files with `ı` in the directory or file name.
2. Update to 3.5.1 and sync.

### Expected behavior

Normal sync with no scrambled duplicates.

### Which files are affected by this bug

1.basım_unused/mujdenin_gucu.mobi

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

23.0.3

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by alerque** [comment]
This appears to be an issue with the server, and is specifically likely to be this one:

https://github.com/nextcloud/server/issues/31212

**Comment by joshtrichards** [comment]
Fixed in nextcloud/server#31212
