### ISSUE TITLE
[Bug]: MSI installer/uninstaller fails to run with `Invalid Drive: D:\`

### ISSUE THREAD

**Issue by Duckle29** [nextcloud/desktop#4586]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

TL;DR: If nextcloud was previously installed on a drive letter that no longer exists in the system, it will fail to run the msi installer/uninstaller entirely

I recently got a new 4TB SSD for my desktop, replacing my 4TB HDD as it was loud and slow.
A part of this upgrade was moving a lot of stuff around, and I decided to let my old HDD have the drive letter `D:` and my new SSD `S:`

After a while I was satisfied and unplugged my HDD, so there's no longer a `D:` drive. I realized I forgot the nextcloud client, so I went to uninstall/install it, however the MSI install immediately fails with the error message `Invalid Drive: D:\`  using microsofts "program install and uninstall trouble shooter" manged to uninstall it, however the installer still expected there to be a `D:` drive

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

Install nextcloud on a secondary drive for example `D:\`
remove or change the drive letter for this drive

try to run the uninstaller / installer

### Expected behavior

At most, maybe an error like:
 _`D:\` is an invalid path, returning to default_

### Which files are affected by this bug

Nextcloud-3.5.1-x64.msi

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

Not relevant

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jpurdy647** [comment]
I reproduced this issue in a different manner and the evnt viewer shows the same issue:

Faulting application name: nextcloud.exe, version: 3.5.1.35429, time stamp: 0x6283a7c6
Faulting module name: KERNELBASE.dll, version: 10.0.22000.675, time stamp: 0x8d5bd3da

1. sync nextcloud / to computer c:/users/my_user/nextcloud
2. add a folder sync of nextcloud /Desktop/ to c:/users/my_user/Desktop
3. Note but ignore the warning about / already being synced
4. Observe crash, at this point I am hoping reinstalling clears the issue

**Comment by joshtrichards** [comment]
I hear what you're saying, but I'm not really sure what we can do about this..

**Comment by Duckle29** [comment]
Hey there.

I should've probably posted more details back then, however the issue isn't really that it fails to un-install. It's that it's unable to install at all after this.

If I recall correctly, i had to re-attach my old HDD, which then let me run the installer and pick my S: drive

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
