### ISSUE TITLE
Ununtu 16.04 build problems

### ISSUE THREAD

**Issue by stelhs** [nextcloud/desktop#459]
Hello,

I have a problem with build nextcloud-desktop client from master branch. 
I build with docker. I tride to build this project in: Ubuntu 16.04, Ubuntu 18.04, Arch, Kubuntu 16.04,  Kubuntu 18.04. In all this cases I have shell integration error:

> CMake Warning at /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:655 (message):
  KDE_INSTALL_BINDIR, KDE_INSTALL_LIBDIR and KDE_INSTALL_INCLUDEDIR should
  either all be absolute paths or all be relative paths.
Call Stack (most recent call first):
  shell_integration/dolphin/CMakeLists.txt:23 (include)

> -- Looking for __GLIBC__
> -- Looking for __GLIBC__ - found
> -- Performing Test _OFFT_IS_64BIT
> -- Performing Test _OFFT_IS_64BIT - Success
> -- Performing Test HAVE_DATE_TIME
> -- Performing Test HAVE_DATE_TIME - Success
> CMake Error at shell_integration/libcloudproviders/CMakeLists.txt:28 (install):
  install FILES given no DESTINATION!
> Call Stack (most recent call first):
  shell_integration/libcloudproviders/CMakeLists.txt:55 (dbus_add_activation_service)

> -- Configuring incomplete, errors occurred!
> See also "/home/user/kubuntu_18.04/build/CMakeFiles/CMakeOutput.log".
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.

In the case of Ubuntu 16.04 I also got error: error while loading shared libraries: libcloudproviders.so.0: cannot open shared object file: No such file or directory

My docker file: [http://sr38.org/Dockerfile](http://sr38.org/Dockerfile)
How can I build last nextcloud desktop client for Ubuntu 16.04 with out KDE?

**Comment by ivaradi** [comment]
Hi,

this is the list of the packages the automated Ubuntu package build depends on:

               cmake,
               debhelper,
               cdbs,
               dh-python,
               extra-cmake-modules (>= 5.16),
               kdelibs5-dev,
               kio-dev,
               libcmocka-dev,
               libhttp-dav-perl,
               libinotify-dev [kfreebsd-any],
               libqt5webkit5-dev,
               libsqlite3-dev,
               libssl-dev (>> 1.0.0),
               zlib1g-dev,
               optipng,
               pkg-kde-tools,
               python-sphinx | python3-sphinx,
               python3-all,
               qt5keychain-dev,
               qtwebengine5-dev,
               qtdeclarative5-dev,
               qttools5-dev,
               qttools5-dev-tools,
               xvfb

So you do need some libraries of KDE to build on Ubuntu 16.04 (or other versions).

**Comment by rullzer** [comment]
You do not need KDE packages. You only need KDE packages when you want to build the dolphin plugin.

This erros on the libcloudproviders stuff. @juliushaertl maybe a check there is missing?

**Comment by juliushaertl** [comment]
Can you check if the output of `pkgconf --variable=session_bus_services_dir dbus-1` returns a directory on your system? Otherwise I'd guess there are some dbus dependencies missing.

**Comment by stelhs** [comment]
Thanks.
I was disabled Dolphin plugin and get success build on Ubuntu 18.04.

**Comment by elcheapo** [comment]
libdbus1-dev is missing from the requirements ...
