### ISSUE TITLE
Appimage not always suitable, can we get an actual install package?

### ISSUE THREAD

**Issue by BartAgterbosch** [nextcloud/desktop#4599]
I don't want to be "that guy", but would it be possible for us to at some point get an actual installer release for linux?
Personal preferences aside, appimage just doesn't always cut it in every case.
For example in my case need a debian installer package, in order to make it show up on my chromebook when using crostini, this might sound like a bit of an edgecase scenario, but I imagine this isn't the only situation someone might end up needing an actual installer package like a .deb instead of a universal portable appimage file.
Appimage is great as a supplement, but not as a basis imo, windows gets a full installer version, macos gets a full installer version, why aren't there any linux installer versions?
I know there are some ways around it with appimage, but they tend to range from janky to horrible

**Comment by Thatoo** [comment]
On debian you can "sudo apt install nextcloud-desktop" and it works well.
So if you want the .deb package, here it is : https://packages.debian.org/bullseye/amd64/nextcloud-desktop/download
