### ISSUE TITLE
Add force sync under main screen

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#4608]
Option 1
![image](https://user-images.githubusercontent.com/59488153/171478626-e2c73dd9-1b75-40e6-9846-f87d543fc1af.png)

Option 2
![image](https://user-images.githubusercontent.com/59488153/171479025-134743d4-2530-43bd-be61-13e0fe4e5ff7.png)

**Comment by camilasan** [comment]
@jancborchardt @nimishavijay what do you thing?

**Comment by andyxheli** [comment]
Hi all, any updates on this?

**Comment by andyxheli** [comment]
Same as https://github.com/nextcloud/desktop/issues/4877
