### ISSUE TITLE
Open files in local application handler from web

### ISSUE THREAD

**Issue by ACiDGRiM** [nextcloud/desktop#4625]
### Feature description
I frequently find it easier to browse files in the web file browser of nextcloud, particularly images where I am able to see thumbnails, however documents also have a benefit here. however if I want to edit the file in a local application I need to download the file and then overwrite the original.

It would be nice if nextcloud desktop registered a uri like "nc://" with windows that passed the webpath to the desktop client which in turn would call the default filetype association program with the virtual file that is linked to the online version.

1.  The User browses the Web UI on his nextcloud instance at http://nc.domain.com/ and locates the file "Documents/Folder/file.odt"
2. Select "open in local application" from the right click menu
3. The Web UI calls a uri "nc://openfile?http%3a%2f%2fnc.domain.com%2fDocuments%2fFolder%2ffile.odt
4. The browser asks for permission to open the uri in the application "Nextcloud"
5. The User accepts the request and the browser calls the system handler for nc:// uri
6. The Operating system passes the uri to nextcloud Desktop
7. NextCloud Desktop looks up virtual file linked to the file in the encoded uri and finds C:\Users\MyName\Nextcloud\Documents\Folder\file.odt
8. Nextcloud then makes an operating system call to launch the file with the default file handler for .odt files
9. Libre Office is launched with the path to file.odt and file changes are sync'd as usual by existing Nextcloud Desktop sync process.

By using the default file handler, any file can be opened, which relies on the operating system to present an application picker if there is no default. No special file type logic is necessary as long as the file exists in a folder that is sync'd by Nextcloudl This does require that a valid signin to the same  instance exist in Nextcloud Desktop.

Some distant future development conceivably could work  even on folders that aren't sync'd with virtual files by downloading the file to a temporary path and watching for changes to re-upload as well as request authentication for editing account files that aren't logged in/sync'd with the Nextcloud Desktop application.

Ultimately, this would minimize the reliance on the OS file browser which has to fully download all files to generate thumbnails.

**Comment by claucambra** [comment]
This has been implemented with the new "edit locally" feature in NC25 / client 3.6.0!

Thanks for your suggestion :)

**Comment by ACiDGRiM** [comment]
Hi, thank you. I see the demo videos and it looks like it works just as I imagined 
I can't see how to use this from the website other than crafting the uri by hand. I'm on NC 27 and desktop 3.6.2

**Comment by claucambra** [comment]
> Hi, thank you. I see the demo videos and it looks like it works just as I imagined I can't see how to use this from the website other than crafting the uri by hand. I'm on NC 27 and desktop 3.6.2
> 
> Edit: I see, I briefly looked at the version and saw 24.0.7 and my mind captured "27"....Disregard.

For security reasons, you can't do this -- the client validates a token with the server to ensure the server asked you to open and edit this file, and not some random malicious actor

**Comment by ACiDGRiM** [comment]
I can confirm this works on Windows well. Thank you. I will note that I had to uninstall and reinstall the desktop-client to get it to register the nc:// uri handler
However I get this error every time

"File %1 could not be locked....Server Replied not implemented"

as a notification when the file is launched.


I will note that the uri handler does work with the Linux AppImage using the experimental VFS, however when it displays the "Opening file for local editing", it does not sync the file let alone launch it. If the file is pre-sync'd and then I retry to edit locally it does work, also I receive the same error that the file could not be locked.

**Comment by mkrecek234** [comment]
Ignore my last comment, with the most recent NC client on macOS it is working nicely already if you click "Open locally" in the context menu. Brilliant.

**Comment by mkrecek234** [comment]
Question: It would be great if I could use a modified internal link that will not open in the browser and show the file or the folder, but immediately try to open the respective link locally on the client PC (if nextcloud app is installed), e.g.:
`https://nextcloud.sampledomain.de/index.php/f/21484?tryOpenLocal=1 `
Any idea?
