### ISSUE TITLE
AppleScript or Shell command to get URL of Finder object 

### ISSUE THREAD

**Issue by bentuna** [nextcloud/desktop#4630]
### Feature description
Is it possible to use a terminal command or AppleScript to get the internal URL of a specified local file inside your nextcloud sync directory? Basically I am looking for a way to do the same thing that is done, when you right-click on a file in macOS Finder and select Nextcloud > Copy internal link.

**Comment by joshtrichards** [comment]
This sounds like a matter for the Nextcloud Help Forum - https://help.nextcloud.com.

We try to keep the repository here clear for bug reports and enhancement ideas.
