### ISSUE TITLE
[Bug]: Desktop client wizard fails to determine directory free size

### ISSUE THREAD

**Issue by AnrDaemon** [nextcloud/desktop#4635]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I think 16GB+ is rather enough to store 2GB of server data. Do you?
![image](https://user-images.githubusercontent.com/6532485/173200454-12a1c49a-a356-4c27-b9e8-ed15f56c4081.png)

### Steps to reproduce

`C:\Users` is a directory junction from `D:\Profiles`.

### Expected behavior

It should ask for free space directly for a directory. Do not try to be smart, do not guess.

### Which files are affected by this bug

sync root

### Operating system

Windows

### Which version of the operating system you are running.

Windows 7

### Package

Other

### Nextcloud Server version

23.0.3

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Not applicable.
```

**Comment by AnrDaemon** [comment]
Actually, `C:\Users` is a junction to `\\?\Volume{6833c423-2223-11e4-b07d-806e6f6e6963}\Profiles`, which is the same thing, which should never concern the application either way.

**Comment by camilasan** [comment]
We do not support Windows 7 anymore:
https://docs.nextcloud.com/desktop/3.5/installing.html#system-requirements

Would you be able to upgrade it?

**Comment by AnrDaemon** [comment]
This is not related to the Windows version. You would have this same behavior anywhere from Windows 2000 to Windows 11.
If you want to check free space in a directory, CHECK THE DIRECTORY ITSELF. Do not assume that free space on the root disk equals free space in some directory of it.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
