### ISSUE TITLE
[Bug]: Busy by file-index, then rename parent dir: parent dir deleted

### ISSUE THREAD

**Issue by labor4** [nextcloud/desktop#4648]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This one may be linked to many other reports, but I wasn't sure I could pinpoint a specific one.

When I **rename a directory and handle its contents** (consisting of big files), **in a quick way**, very often **the whole folder gets deleted**. I had to restore entire projects from backup that way.

It seems, when the client has a lot to do with indexing big files (checksumming? i don't know),
it cannot handle or queue a (parent?) directory rename. It seems to run into a corner where a legit renamed folder is marked obsolete, and deleted.

This means in my experience, that I must absolutely be certain the client is idle and synced, before I rename a directory.
And that I must wait for this to complete, before continuing.

It may also be linked to the fact that I disabled the TRASH bin on the server (if this is a fallback for the client somewhere).

### Steps to reproduce

All this has to do with human handling speed (read: "act within routine"-speed).
I believe the client needs to be busy with tasks for this to happen.

- have a directory DIR-A, with multiple subdirs and files
- throw into DIR-A multiple files in the size of 300MB, (force the client to be busy)
- rename DIR-A to DIR-B
- throw into DIR-B more big files of 300MB (maybe not needed)
- wait
- the icon of DIR-B gets a red cross flag
- after some time (~ 5-20 secs) the whole DIR-B gets deleted, including from server

### Expected behavior

I expect the client to step back from a current interference and wait and re-evaluate the situation, if a parent priority action has happened.

### Which files are affected by this bug

logs not yet ready, need to review them first

### Operating system

Mac OS

### Which version of the operating system you are running.

12.4 Monterey

### Package

Download official release pgk/dmg

### Nextcloud Server version

24.0.1

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
logs not yet ready, need to review them first
```

### Additional info

Server-side, TRASH-bin is disabled

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
