### ISSUE TITLE
[Bug]: "Main Dialog" does not appear on kde-neon (ubuntu 20.04)

### ISSUE THREAD

**Issue by cyBea** [nextcloud/desktop#4660]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

- left-click on the nextcloud-icon in task bar does nothing
- right-click and selecting "Open main dialog" does nothing as well

### Steps to reproduce

I have the same issue on a fresh installation of kde-neon and nextcloud desktop client installed via dev-repo:
`deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu focal main`
and using hack described here: https://github.com/nextcloud/desktop/issues/2722#issuecomment-985399224

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

--

### Operating system

Linux

### Which version of the operating system you are running.

kde-neon (ubuntu 20.04 lts)

### Package

Other

### Nextcloud Server version

does not matter

### Nextcloud Desktop Client version

3.5.1 (KDE)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
login@client:~$ nextcloud --logdebug -l
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
```

### Additional info

- Nothing to be found in debug-folder (Nextcloud-logdir)
- Nothing found using "Create debug archive"
- Installed using following hack: 
- may be related to #4601

**Comment by claucambra** [comment]
It is highly likely that the issue here is caused by issues with Qt versions, in which case it is really not recommended that you use the version of the client from the Ubuntu PPA.

Does the main dialog work correctly with our official AppImage package?

**Comment by cyBea** [comment]
Unfortunately I must confirm that the Appimage is working fine. Appimages are not my favorite installation method.
Thus it is no bug in nextcloud-desktop but my problem since there is no alternative packaging for my distro.
