### ISSUE TITLE
[Bug]:  Could not find a configuration file for package "Qt5" that is compatible   with requested version "5.15".

### ISSUE THREAD

**Issue by fixosoft** [nextcloud/desktop#4664]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
hi good day 
please advise  don't know what to do ...cannot comply desktop client on ubuntu 20.04
gives me an error : 

cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug
******************************
-- Build of crashreporter disabled.
-- GIT_SHA1 fb4785c55de49f2898d152749269628441aae2d6
Compiling with updater
-- Checking for module 'cloudproviders'
--   No package 'cloudproviders' found
CMake Error at src/CMakeLists.txt:7 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.15".

  The following configuration files were considered but not accepted:
    /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8
    /lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake, version: 5.12.8

-- Configuring incomplete, errors occurred!

### Steps to reproduce

1. cmake .. -DCMAKE_INSTALL_PREFIX=~/nextcloud-desktop-client -DCMAKE_BUILD_TYPE=Debug

...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
finish comply

### Which files are affected by this bug

no files

### Operating system

Linux

### Which version of the operating system you are running.

ubuntu 20.04

### Package

Official SNAP package

### Nextcloud Server version

24.0.2

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi fixosoft, you won't be able to compile the client from `master` on Ubuntu 20.04 as it ships with a very old version of Qt (5.12). You will need Qt 5.15 or a later version of Qt 5.

**Comment by claucambra** [comment]
CMake can't find the Qt 5.15 install in your PATH -- you need to make sure that you point CMake to the installed version of Qt, an easy way to do this is by setting the location of your Qt 5.15 installation by setting `-DCMAKE_PREFIX_PATH`.

Be warned that unless you build the desktop client with statically linked libraries the version of the client you compile will likely not work at all, as it will try to use your system's copy of Qt

**Comment by fixosoft** [comment]
understood ))
