### ISSUE TITLE
[Bug]: Cannot copy locally available files to another drive since the source drive does not have enough free space

### ISSUE THREAD

**Issue by klumbe** [nextcloud/desktop#4691]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Files that are already available offline can not be copied to another drive if the source-drive does not have enough free space.
Though the target drive has plenty of free space available, an error message is shown that additional space is required to copy the file.
Checking the given sizes (missing space and full space of the drive) reveals that space on the source drive (where the synced Nextcloud folder is residing) is required.

### Steps to reproduce

0. Have a partition with enough space to store the testing-file exactly once, but not twice
1. Copy a new file into the Nextcloud folder on that full partition
2. Wait for it to sync
3. Try to copy that file to another partition with more than enough space to store the file

It may be required to place the file into a folder which is marked to be not available locally.

### Expected behavior

The file should be just copied since it is available locally and the target drive has enough free space.

### Which files are affected by this bug

takeout-20220630T111359Z-008.zip, takeout-20220630T111359Z-007.zip

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

24.0.1

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

It may be related to the following issue:
https://github.com/nextcloud/desktop/issues/4274

Getting a message that additional space is required on the source drive indicates that the Nextcloud client is trying to redownload the file, though it is already stored on the drive.
When I mark the same file as "Free up local space", the size of the file is removed from the total amount of used space of the partition after a while. This shows that the file was really there.

I can provide the client logs, but I won't push them public.
The following is en excerpt which contains all lines where one of the files I tried is involved:
	Line    277: 2022-07-01 11:17:18:727 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-10303\client-building\desktop\src\libsync\discovery.cpp:354 ]:	Processing "Photos/Google Fotos/takeout-20220630T111359Z-008.zip" | valid: true/true/db | mtime: 1656612509/1656612509/0 | size: 4200150431/4200150431/0 | etag: "1101180678e716d82856a170da8bb5f7"//"" | checksum: "SHA1:02590716441b161076216ae5d1ef42494e354509"//"" | perm: "WDNVR"//"" | fileid: "00337581oc3pf6bctc3m"//"" | inode: 21762/21762/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile | e2ee: false/false | e2eeMangledName: ""/"" | file lock: not locked//not locked
	Line    278: 2022-07-01 11:17:18:727 [ info sync.discovery C:\Users\sysadmin\AppData\Local\Temp\2\windows-10303\client-building\desktop\src\libsync\discovery.cpp:1425 ]:	Discovered "Photos/Google Fotos/takeout-20220630T111359Z-008.zip" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
	Line 367371: 2022-07-01 11:20:48:870 [ info nextcloud.gui.socketapi C:\Users\sysadmin\AppData\Local\Temp\2\windows-10303\client-building\desktop\src\gui\socketapi\socketapi.cpp:362 ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:D:\\Nextcloud\\Photos\\Google Fotos\\takeout-20220630T111359Z-008.zip" from QLocalSocket(0x1f3cf0c0810)
	Line 554338: 2022-07-01 11:31:42:261 [ info nextcloud.gui.socketapi C:\Users\sysadmin\AppData\Local\Temp\2\windows-10303\client-building\desktop\src\gui\socketapi\socketapi.cpp:362 ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:D:\\Nextcloud\\Photos\\Google Fotos\\takeout-20220630T111359Z-008.zip" from QLocalSocket(0x1f3cc44a400)

**Comment by joshtrichards** [comment]
Potentially fixed by #5890.

Are you still experiencing this?

**Comment by joshtrichards** [comment]
Closing due to probable fix and no further follow-up info received after >10 months.
