### ISSUE TITLE
Windows Desktop-Client config file

### ISSUE THREAD

**Issue by TobiasScheinert** [nextcloud/desktop#47]
Hi,

the nextcloud client stores by default its config file under `AppData\Local\Nextcloud\nextcloud.cfg`. The problem is that is folder is not persistent in a [Roaming Profile Environment](https://en.wikipedia.org/wiki/Roaming_user_profile). 

> Windows uses the Local and LocalLow folders for application data that does not roam with the user. Usually this data is either machine specific or too large to roam. The AppData\Local folder in Windows Vista is the same as the Documents and Settings\username\Local Settings\Application Data folder in Windows XP.
[https://technet.microsoft.com/en-us/library/cc766489.aspx](https://technet.microsoft.com/en-us/library/cc766489.aspx)

We are using the client with roaming profiles and want to store the synced files on the users network share. All known workarounds have disadvantages:

- using `--confdir=` as an argument of `nextcloud.exe` works if you start the application manually, but when you select in the configuration `start on system startup` the Registry-Key doesn't contain the `--confdir=` argument. So on the next system startup the client doesn't find the config file.
- We wrote a wrapper which starts the renamed `nextcloud_orig.exe` and adds the argument `--confdir=`. But when you select `start on system startup` in the configuration menu the Registry-Key uses `nextcloud_orig.exe` and not `nextcloud.exe` and bypasses so the wrapper.

Possible solutions:
- Store by default the config file under `%APPDATA%\Nextcloud` (what is from my point of view the right place).
- Create a persistent possibility to configure the default filepath of the config file (e.g. a INI file in the program directory of the client, or a Registry-Key under `HKLM`).

Thank you and best regards
Tobias

**Comment by michaelstingl** [comment]
@TobiasScheinert This might help: https://github.com/owncloud/client/issues/684#issuecomment-247280687

**Comment by TobiasScheinert** [comment]
@michaelstingl yes we know this workaround, but this is also still a (ugly) workaound. This solves only the problem for startup.

The official path for persitent config files in Windows is `%APPDATA%` (`C:\Users\{username}\AppData\Roaming`). So please fix this someday.

Imagine a large (very large) organization with many thousands of users, and we have to tell everyone: you can install the client, but you have to set the following settings manually and change something here in the registry. Come on, that can not be the point.

Greeting Tobias

**Comment by Square252** [comment]
Same issue here. Also a little bit related to #59

The client needs more work to support bigger environments. The client is around for a while but still feels like a hack job for single pc home usage.

**Comment by syzop** [comment]
Owncloud changed from LocalAppData to AppData in December 2017: https://github.com/owncloud/client/issues/684#ref-commit-9699b19
That GitHub issue contains the following patch (among others): https://github.com/owncloud/client/commit/e0a14cac5b03ea41303e1602b79b51fec1f5c1de
Hope this could be picked up by a dev so we can use nextcloud in an enterprise setting without workarounds.

**Comment by TobiasScheinert** [comment]
Today I've tested the new Nexcloud Windows client (v. 2.5.0), and it saves the config data in the "right" (%AppData%) folder. Awesome! Thank you very much!

**Comment by mcerennes** [comment]
hi,
just tested last nextcloud client 2.5.2 on Windows 10 1809. I installled on user session with admin password but "path by default" by Nextcloud client is automatically on admin session if I change it syncro doesn't work.
I have to give admin rights to my user session if i want a normal synchro
can you help me please ?
best
