### ISSUE TITLE
[Bug]: Nextcloud client says to upgrade to 3.5.2 but it is not available

### ISSUE THREAD

**Issue by ysalmon** [nextcloud/desktop#4701]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I am using the 3.5.1 appimage linux version, and it checks for new versions regularly.

Today, it displayed a message about a new version and the About dialog says to download the new 3.5.2 version from https://nextcloud.com/install/.

However, this page's Linux download link refers the 3.5.1 version I already have, not 3.5.2.

### Steps to reproduce

1. Show the About dialog of version 3.5.1.
2. Click the link to https://nextcloud.com/install/

### Expected behavior

The new claimed version should be downloadable through the link provided to download it.

### Which files are affected by this bug

not applicable

### Operating system

Linux

### Which version of the operating system you are running.

KUbuntu 20.04

### Package

Appimage

### Nextcloud Server version

multiple

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by koelle25** [comment]
Yep, the URLs for the download buttons still have to be updated:
![HTML source for the Nextcloud-Client download buttons showing incorrect reference to old release 3.5.1](https://user-images.githubusercontent.com/915514/177329654-3b5f4bc3-09f2-4859-b37d-d849f16e1f3e.png)

**Comment by koelle25** [comment]
Also, the 3.5.2 release is not yet available in the [PPA](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client). I have also mentioned this in #4695.

**Comment by koelle25** [comment]
The download links on https://nextcloud.com/install and on the PPA now have been updated. You can close this issue now :)

**Comment by claucambra** [comment]
Thanks for opening the issue @koelle25 :)
