### ISSUE TITLE
Allowing disable autoupdate from Nextcloudcmd

### ISSUE THREAD

**Issue by julian70400** [nextcloud/desktop#4709]
Hello, actually, we deploy Nextcloud from package managers (like Fusioninventory) on large networks. Our problem is we have to disable autoupdate, because we want to validate each new version with our process.

Actually, the only way to realize this is editing regedit (or nextcloud.cfg, which one is not easly accessible, because some computer are personnal computers).

The best way should be to be able to modify some nextcloud.cfg options through the nextcloudcmd CLI. This will help us to, in our case, easly disable autoupdate, throught cmd windows command line.

Actually, I tryed something like this : **REG ADD "HKLM\SOFTWARE\WOW6432Node\Nextcloud GmbH\Nextcloud" /v skipUpdateCheck /t REG_DWORD /d 1**

But it doesn't change anything client side (3.5.2)

**Comment by joshtrichards** [comment]
You appear to have a typo:

> HKLM\SOFTWARE\WOW6432Node\Nextcloud GmbH\Nextcloud


These are the correct ones:

HKEY_LOCAL_MACHINE\Software\Wow6432Node\Nextcloud\Nextcloud
HKEY_LOCAL_MACHINE\Software\Policies\Nextcloud GmbH\Nextcloud

https://docs.nextcloud.com/desktop/3.10/autoupdate.html#preventing-automatic-updates

P.S. Also see new options added in #2914 for additional settings

**Comment by joshtrichards** [comment]
Related: #5559
