### ISSUE TITLE
[Bug]: Ubuntu Snap removal deletes local filestore

### ISSUE THREAD

**Issue by kylespencer** [nextcloud/desktop#4716]
### Bug description

When using the default desktop client configuration, removing the Snap deletes all synchronized files from the local machine. This is an egregious user experience problem.

### Steps to reproduce

1. Install the Nextcloud desktop client via the Ubuntu Software store, or run "snap install nextcloud-desktop-client" in a terminal.
2. Connect an account using default settings and synchronize some remote files with the local machine.
3. Remove the Nextcloud desktop client via the Ubuntu Software store, or run "snap remove nextcloud-desktop-client" in a terminal.

### Expected behavior

Synchronized files should remain on the local machine despite the removal of the desktop client software.

### Which files are affected by this bug

All

### Operating system

Linux

### Which version of the operating system you are running.

22.04

### Package

Official SNAP package

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Additional info

By default, the Nextcloud desktop client places the local filestore inside the Snap's working directory. This is presumably why the local filestore gets deleted by the Snap removal process. 

In addition, the Snap removal process creates a "snapshot" of the Snap's working directory. If the local filestore is located within the Snap's working directory, this can take an extremely long time and consume a lot of disk space.

**Comment by claucambra** [comment]
@kylespencer The `nextcloud-desktop-client` snap package is not packaged by us -- I recommend reaching out to the packager who created the snap and reporting the issue to them. Thanks for opening the issue!
