### ISSUE TITLE
Allow for server/ip change on account

### ISSUE THREAD

**Issue by Aridean** [nextcloud/desktop#4721]
Hello

So I ran into an issue recently with our internet (modem straight up died) and for reasons unknown, the replacement refused to assign the original IP to the server.

That wasn't a big deal, gave it a new one, issue being there is no way to change the domain/IP in the client. (I can't use the domain name on internal network, so I have to use the internal IP of the server) 
I had to add a new account with the new IP, and remove the old one.

Any chance there could be an option added to change the domain that an account uses to connect?

**Comment by camilasan** [comment]
Have you try to change the url in the config file?
https://docs.nextcloud.com/desktop/3.5/advancedusage.html#configuration-file

This enhancement has been requested in #421.
Please, always check if what you are asking for or reporting isn't already in the list of issues before creating a new one.
