### ISSUE TITLE
Marking a notification as read in the client makes the list jump to the top

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#4724]
Currently when you click "Mark as read" on any e.g. chat notification, the message vanishes and the list jumps to the top, making you lose your location. This is especially annoying when you want to interact with multiple messages.

Instead, it should:
- Stay in place so you keep the location where you were and can mark more messages as read
- Ideally do a quick collapse animation on the entry which is being marked as read so people get feedback on what happens

cc @claucambra

**Comment by tobiasKaminsky** [comment]
Indeed a papercut bug, please do it when time permits. 
(no need to put it on board)

**Comment by claucambra** [comment]
Already opened a PR with a fix, being reveiwed and should hopefully merge soon :)
