### ISSUE TITLE
To few strings to translate on transifex

### ISSUE THREAD

**Issue by rullzer** [nextcloud/desktop#473]
It looks like the transifex resource for the client is not complete.

@MorrisJobke

**Comment by MorrisJobke** [comment]
> It looks like the transifex resource for the client is not complete.

Example please ;)

**Comment by rullzer** [comment]
https://www.transifex.com/nextcloud/nextcloud/client-desktop/ Check the strings there.

And then check the string under https://github.com/nextcloud/desktop/tree/master/translations

**Comment by MorrisJobke** [comment]
> https://www.transifex.com/nextcloud/nextcloud/client-desktop/ Check the strings there.

That is only one part - the others are in here: https://www.transifex.com/nextcloud/nextcloud/client/
