### ISSUE TITLE
[Bug]: Unexpected/Different behavour with "Ask for confirmation before syncing folder larger than..." 

### ISSUE THREAD

**Issue by p-sims** [nextcloud/desktop#4737]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I'm not quiet sure which version update introduced this change in behavior, as I've had lot of sync client issues recently and have had to do lots of client upgrade/downgrades (see #4419, #3012, #4527/#4459). I think it was probably introduced between 3.3.6 and 3.4.4, and is defiantly still present in 3.5.2

It concerns the behavior of "Ask for confirmation before syncing folder larger than..." options in client settings which I've had on for years (since I as on 2.x.x) set at 500MB, but I've now had to turn off to stop all my selective sync settings being lost. 

My understanding on how feature was intended and how it used to work:
- Would only apply to new folders/files the client hadn't seen before and weren't already on the client and the server.

With 3.4.4 and 3.5.2 it seems to behave as:
- Should I try to sync this file/folder?
- <500MB yes and leave ticked in selective sync settings
- >500MB no and untick in selective sync settings

I have about 160GB of files on server of which about 100GB are on my computer too. When I updated to 3.4.4 all of my selective sync settings were lost (which I think was a feature of the update). Since then (up until I unticked the "ask before syncing. . ." option, I've kept having issues where big folders/subfolder would sync fine initial, and then silently stop syncing (and become unticked in selective sync) until you need to access the file via web interface or another device, and it wouldn't be their.

My instinct is that this is a bug as the behavior has changes between client version without (as far as I can see) anything in release notes stating this is a intended change in behavior. 

Personally I found the original behavior really useful, as all my big folder I've confirmed once in selective sync would sync find, but if someone put 10GB of video in a shared folder somewhere it won't automatically be downloaded to my computer and fill up device disk space.

The only related issues I can find is this one from 2018:
https://github.com/nextcloud/desktop/issues/126

This implies others might use this feature to limited client upload/download bandwidth (rather than device disk space) and there for might expect it to behave differently.

### Steps to reproduce

1. Install v5.5.2
2. Sync a folder with sub folders greater than 500MB total
3. Add some files to it (so it's still over 500MB)
4. Check whether these have synced and whether selective sync setting have changed.

### Expected behavior

Should always continue to be synchronized and ticked in selective sync unless a new file/folder appears bigger than 500MB

### Which files are affected by this bug

Only think that matters is the size of a folder/file not what file it is.

### Operating system

Mac OS

### Which version of the operating system you are running.

10.14.6

### Package

Appimage

### Nextcloud Server version

22.2.9

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by camilasan** [comment]
I need to look into it more... it did not sync a big folder silently on the first run and after restarting the client it always did ask as expected and the settings did not change.

#4413 seems to be the same issue (?1)

**Comment by chienbinhso14** [comment]
I have same Problem with  LDAP user backend  + Windows OS.
Currently I'm running 24.0.3 with 3.5.2 client.

**Comment by stueja** [comment]
I experience that issue on MacOS Sonoma/14.5/M1, Nextcloud Desktop 3.13.0. Ask-for-confirmation size is set to 50MB.

Nextcloud Server contains an external storage. Via the web interface, I copied a folder of 80MB from the external storage to the root/home folder.

The folder was silently synced to Nextcloud Desktop.

Please advise whether to open a new issue or keep this one.
