### ISSUE TITLE
AppImage does not work under Arch

### ISSUE THREAD

**Issue by jernst** [nextcloud/desktop#475]
```
./Nextcloud-2.3.3-x86_64.AppImage 
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```
Building and running the AUR package does work: https://aur.archlinux.org/packages/nextcloud-desktop-git.

**Comment by rullzer** [comment]
AH joy must be more package stuff. As it works just fine on Arch here.

Do you have any qt packages installed on your system?

**Comment by jernst** [comment]
`pacman -Qs qt` shows 50 packages. You want a list? I tried installing some extra ones but could not find what was needed. The funny thing is that the AUR-built version works just fine on the same system.

**Comment by rullzer** [comment]
@jernst btw which appimage did you take?

**Comment by jernst** [comment]
The one linked from the nextcloud.com page yesterday, filename Nextcloud-2.3.3-x86_64.AppImage as stated above.

**Comment by rullzer** [comment]
Ah k.
The latest dailies (with more up to date appimages) are in https://download.nextcloud.com/desktop/daily/Linux/ if you are brave enough to try the dailies ;)

**Comment by jernst** [comment]
Nextcloud-2.5.0.20180703-daily-x86_64.AppImage works, I'm only getting a:
```
[8428:8488:0703/121132.065669:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.
```
upon quit. It seems harmless so I'm closing this.

**Comment by rullzer** [comment]
mmm more fun. I'll see if i can look into that.

Thanks for testing!
