### ISSUE TITLE
[Bug]: VFS Client Stuck on Sync Loop when select free up local space

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#4759]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Make folder avalible offline and click on free up local space

https://github.com/nextcloud/desktop/issues/4383
https://github.com/nextcloud/desktop/issues/4226
https://github.com/nextcloud/desktop/issues/4674

### Steps to reproduce

1. Right click Root folder 
2. Click on Make always available locally 
3. Click on Free up local space
...

### Expected behavior

Should remoce all files and not keep syncing
...

### Which files are affected by this bug

txt, md, crt, key, csr, conf, png

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10, Windows 11

### Package

Appimage

### Nextcloud Server version

24.0.3

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

https://user-images.githubusercontent.com/59488153/179811183-00271cbd-7751-44e8-85ef-f494316a2c61.mp4

**Comment by andyxheli** [comment]
@camilasan I'm not sure if you're the correct person to ping but can we please get some feedback on this. There's a lot of open issues about this topic. Its making the whole VFS option pointless when the client keeps syncing data that it shouldn't. Sorry if your not the correct person to ping.

**Comment by andyxheli** [comment]
Hello is there any updates on this

**Comment by andyxheli** [comment]
Still an issue on 3.6.0

**Comment by rgreeott** [comment]
We see this issue to.  NC 24.0.5 and sync client 3.6.2.  Once stuck in the loop, the sync client consumes large amounts of CPU time.

**Comment by AndyXheli** [comment]
Looks like this was fixed in 3.7.4
