### ISSUE TITLE
Client will timeout before bruteforce delay 

### ISSUE THREAD

**Issue by tecbeast42** [nextcloud/desktop#476]
In the following Situation the client will timeout.

System is in full throttle from bruteforce protection.
Client will timeout and report that i can not login.
Actually it could login if it would wait long enough.

Suggestion:
Increase login request timeout to max bruteforce delay.

Observed on Linux.

**Comment by rullzer** [comment]
We lowered the timeout on NC14 a bit.

When do you observer this when setting up you account?

**Comment by tecbeast42** [comment]
I didn't know that NC14 was in production already. I observed this on NC13 when the client tries to login after system reboot. 

If i clear the bruteforce_attempts table the client logs in immediately.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
