### ISSUE TITLE
Create edit account dialog

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#477]
Right now you can't really edit an account - the client will ask you if the password is wrong but if, say, your server URL changed, you have to either edit the config file by hand (and only when the client isn't running as it will overwrite it) or set up a new account.

Not urgent but would be nice to have :sweat_smile:

**Comment by jospoortvliet** [comment]
(it is mostly UI work and there's already code that does create accounts so I assume it makes for a good first issue)

**Comment by rullzer** [comment]
Why would your server url change?

I see this blow up easily as if you point it to a different server and it all of a sudden is completely out of sync the client might start doing weird stuff. If your server url changes just readd your account. This is not something that happens often and I guess for most people not ever at all. I don't see a reason to clutter the UI with options that hardly will be used/tested.

**Comment by jospoortvliet** [comment]
Fair enough.

**Comment by js-d-coder** [comment]
As posted on #636 : 
There is a workaround this issue. You can set the url something `http://raspberry` instead of any IP. Then point the `raspberry` to the IP, which can be set/edit using DNS Changer on Android or editing `/etc/hosts` on Linux... Enjoy. Now I don't have problem accessing my raspberry from android or desktop even if I move onto different network.

**Comment by mr700** [comment]
I was just reporting the same problem. I managed to edit my ~/.config/Nextcloud/nextcloud.cfg . On the phone however, I had to redo almost everything.

The decision here is a little disappointing, this is really the first product I see where you can not edit your account info (email, ftp, calendar)...
