### ISSUE TITLE
[Bug]: Removing a directory containing directory junction results in data loss

### ISSUE THREAD

**Issue by Amunak** [nextcloud/desktop#4770]
### Bug description

Removing a synced directory that contains a directory junction recursively deletes content within that directory junction, resulting in file removal (data loss) outside the Nextcloud-managed (synced) folder.

I feel like #4232 should be a much higher priority.

### Steps to reproduce

1. Have a directory structure with valuable data somewhere on your PC and create an NTFS [Directory Junction](https://en.wikipedia.org/wiki/NTFS_links) in your Nextcloud folder:
```
D:
|-data
| `-subfolder
|   `-valuable data.txt
`-Nextcloud
  `-whatever
    `-junction to D-data
```
2. Wait for it to sync and observe that the junction is (correctly) not synced, so on a synced system or web only an empty folder `whatever/` exists. This to me indicates that Nextcloud knows it's a junction and doesn't want to touch it, which is intuitive and expected.
3. On a different synced system or from Nexctcloud FIles on Web remove folder `whatever`.
4. Observe that folder `D:\\Nextcloud\\whatever` correctly disappeared. More importantly observe that `D:\\data\\subfolder` disappeared as well, and that your valuable data are gone.

### Expected behavior

The directory junction should be removed (unlinked), but the data inside must not be deleted.

Alternatively not deleting the junction or the parent folder and only emitting an error and not syncing the parent folder would be acceptable as well.

### Which files are affected by this bug

whatever

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official install

### Nextcloud Server version

23.0.5

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.

**Comment by Amunak** [comment]
Sooo you created an automated test for this to make sure it'll never happen again, right?

...right??

**Comment by plauderer** [comment]
another issue with junction points have been posted at #7157 
A confirmation that the issue in #4770 was resolved would be nice!

**Comment by CorneliousJD** [comment]
Yes, #7157 is indeed a junction issue again - specifically inside the "Documents" folder there's "My Pictures" and "My Videos" and "My Music" junctions that are causing data loss too -- I am a victim of this and family photos have been lost now, thankfully I do have some backups but this is a very disastrous issue right now

**Comment by tairabiteru** [comment]
Issue is also present in 3.15.0.
