### ISSUE TITLE
Rewrite the share dialog in QML

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#4777]
We have several open issues from the design/server/etc. side regarding desired changes to sharing, or the share dialog itself, open in this repo:

- https://github.com/nextcloud/desktop/issues/3109
- https://github.com/nextcloud/desktop/issues/3085
- https://github.com/nextcloud/desktop/issues/3845
- https://github.com/nextcloud/desktop/issues/3954

Two of these, particularly #3109 and #3845, are currently not doable due to the share dialog being a QWidget rather than a QML component. Other benefits of QMLification would include:

- Better integration with the tray window
- Reuse of existing components used in the tray window
- Far easier visual customisation of components
- Easier extension and addition of new components

The least painful solution would be to rewrite the share dialog in QML -- this would be a bigger task up front to reimplement everything but would pay dividends once this was done.

@mgallien @tobiasKaminsky @jancborchardt

**Comment by tobiasKaminsky** [comment]
This then would look more like tray window, but not any longer OS specific, right?
@jancborchardt I remember that we wanted to stay close to OR look&feel, is this still the case?

**Comment by claucambra** [comment]
@tobiasKaminsky not necessarily, we can make it look any way we want -- QML just makes styling much easier, this styling being OS-like or tray window like

**Comment by tobiasKaminsky** [comment]
I added it to board.
Once it is picked up, we can discuss actual UX and track the subtasks.

**Comment by jancborchardt** [comment]
@claucambra cool, sounds good. Native look is definitely nicer in the long run for that.
