### ISSUE TITLE
Add configuration options to prompt before file/folder deletion

### ISSUE THREAD

**Issue by scrambledleek** [nextcloud/desktop#478]
It may be a useful enhancement to add options to the NextCloud client which brings up a Yes/Yes-to-All/No/No-to-All dialog, with filenames listed in a text box, when syncing deletions.  There could be two options - one for syncing deletions from client to server and one for syncing them from server to client.

I'm suggesting this for a few reasons:
 - New users may mistakenly delete files on their client machine rather than unticking the folder they no longer want in the NextCloud client
 - In the event of the storage on a client being corrupted and files being lost, the NextCloud client would see the files being deleted and then remove then on the server (initial indications are this is what happened on an installation I'm using with a few others)
 - If a user syncs deletions to the server, but another user still wants that data, they have the opportunity to refuse the deletions

Interesting scenarios:
 a) User loses some local files (filesystem issue or accidental deletion).  NextCloud client prompts asking whether the files should be removed from the server.  If user refuses, the lost files will be re-downloaded to the the local storage on the next sync.
 b) User A deletes some local files.  NextCloud client prompts asking whether the files should be removed from the server.  User A accepts.  User B is running NextCloud client.  A prompt comes up asking whether the server-side deletions should be synced locally.  User B declines as the files are still needed.  User B's client will re-upload the files deleted by User A on the next sync.

**Comment by ShapeShifter499** [comment]
I was asking about this exact feature today on the #nextcloud libera.chat irc channel and someone pointed this out to me. My concern stems from one of my computers where I run a folder sync being a bit unreliable recently with SD cards. I don't want to run into an issue where running 'fsck' on a Linux system results in a lot of changed or lost files that get synced by nextcloud without me immediately realizing that has occured.



It would be nice to have an option that one could toggle for a folder sync that would prompt for confirmations when there are changes.

**Comment by Rello** [comment]
this will be continued in https://github.com/nextcloud/desktop/issues/4231
