### ISSUE TITLE
[Bug]: cannot use AD/LDAP account after upgrade from 3.1.1 to 3.5.1

### ISSUE THREAD

**Issue by lmamane** [nextcloud/desktop#4782]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [ ] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After client upgrade from 3.1.1 to 3.5.1, after login/authentication, the QT desktop client was failing with "server returned 404 on PROFIND https://server_url/remote.php/dav/files/login_username (principal login_username not found).

This was fixed by applying the following patch to ~/.config/Nextcloud/nextcloud.cfg

-0\dav_user=
+0\dav_user=the_correct_value

insofar as:

- 3.1.1 failed to write that value to the config file
- 3.1.1 apparently auto-sniffed the correct value at each connection???
- 3.5.1 correctly auto-sniffs the correct value at account creation time (since adding the same account again through the 3.5.1 GUI worked correctly, and wrote the correct value as 1\dav_user in the config file)

thus 3.5.1 should autosniff the correct value, at least on upgrade from 3.1.1, or even better for more robustness each time it is missing from the config file? Not only at account addition time.

For a less geeky work-around, delete the account and re-add it.

### Steps to reproduce

- Upgrade from QT desktop client version 3.1.1 to 3.5.1
- Restart the client
- Reauthenticate as requested on each startup

### Expected behavior

After authentication, things should continue to work as they did in 3.1.1

### Which files are affected by this bug

~/.config/Nextcloud/nextcloud.cfg

### Operating system

Linux

### Which version of the operating system you are running.

Debian 11.4 with some testing packages (such as nextcloud-desktop and QT5)

### Package

Distro package manager

### Nextcloud Server version

19.0.13.1

### Nextcloud Desktop Client version

3.5.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
nextcloud.log doesn't contain anything around the time of the issue.

Apache's access.log contains:

192.168.0.117 - lionel [26/Jul/2022:20:42:12 +0200] "PROPFIND /remote.php/dav/files/2967438F-B0A1-40FC-92CB-499EE0154397/ HTTP/1.1" 207 5942 "-" "Mozilla/5.0 (Linux) mirall/3.5.1-2 (Nextcloud, debian-5.10.0-15-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
192.168.0.117 - lionel [26/Jul/2022:20:42:23 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 304 5456 "-" "Mozilla/5.0 (Linux) mirall/3.5.1-2 (Nextcloud, debian-5.10.0-15-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
192.168.0.117 - lionel [26/Jul/2022:20:42:26 +0200] "GET /status.php HTTP/1.1" 200 5864 "-" "Mozilla/5.0 (Linux) mirall/3.5.1-2 (Nextcloud, debian-5.10.0-15-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
192.168.0.117 - lionel [26/Jul/2022:20:42:26 +0200] "PROPFIND /remote.php/dav/files/lionel/ HTTP/1.1" 404 991 "-" "Mozilla/5.0 (Linux) mirall/3.5.1-2 (Nextcloud, debian-5.10.0-15-amd64 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
```

### Additional info

Sorry, clicking on "Create Debug Archive" in General Settings doesn't do anything. I attach logs from ~/.config/Nextcloud/logs instead

[20220726_2041_owncloud.log.0.gz](https://github.com/nextcloud/desktop/files/9192662/20220726_2041_owncloud.log.0.gz)

**Comment by joshtrichards** [comment]
This looks similar to #3628. Are you still experiencing this?

**Comment by joshtrichards** [comment]
Relevant PRs: 
- #3646
- #3632
- #3541

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
