### ISSUE TITLE
Style tray window controls more natively

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#4785]
Points from design call:

- Make simple controls look more native:

- [ ] Buttons (e.g. activity list item buttons)

- [ ] Text fields/search fields

- [ ] Loading indicators

- [ ] Menu items

- Others I made be missing

Other notes:

- [ ] Hover/focus effect: Not full width, but add a bit of padding (4px or 8px) and rounded corners like 8px, 12px or 16px on systems where this is the case

- [ ] Account and app menu styling: Border radius and entry highlights

- [ ] Could make main text of each entry bold (like macOS and GNOME e.g.)

- [ ] Use native icons where possible (e.g. folders and filetypes)

@jancborchardt @tobiasKaminsky @mgallien

**Comment by claucambra** [comment]
- At some point it would be nice to do a glass style background like on macOS, but this is not possible due to an issue to do with Qt https://www.apple.com/macos/monterey/, issue open at https://bugreports.qt.io/browse/QTBUG-85310

- SF Symbols should be accessible through macOS and does not need to be included https://developer.apple.com/design/human-interface-guidelines/foundations/sf-symbols

- It would be awesome to go fully native; VLC for example uses a shared backend, whereas the UI for macOS is native – but for the moment this is unrealistic

**Comment by tobiasKaminsky** [comment]
How much effort is this roughly for "only" items in first post?

**Comment by claucambra** [comment]
For the work itself, 20 hours or so?

**Comment by claucambra** [comment]
@tobiasKaminsky digging into it this task should become an order of magnitude easier if we move to Qt 6 as post-6.0 versions of QtQuick Controls ship with default styles for macOS and Windows that we can just apply
