### ISSUE TITLE
[Bug]: Nextcloud Client needs deprecated package libgnome-keyring

### ISSUE THREAD

**Issue by kromsam** [nextcloud/desktop#4787]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud Client has a dependency: `libgnome-keyring` that is deprecated. On ArchLinux, the client keeps asking for reauthentication until this package is installed: https://archlinux.org/packages/extra/x86_64/libgnome-keyring/

### Steps to reproduce

1. Install `nextcloud-client`
2. Login
3. Restart system
4. Be asked to login again

1. Install `libgnome-keyring`
3. problem solved

### Expected behavior

At this moment, `libgnome-keyring` is clearly a dependency of the Nextcloud Client. It should be packaged as such.

But as this is a deprecated package, it should be removed from the dependencies for security reasons.

### Which files are affected by this bug

-

### Operating system

Linux

### Which version of the operating system you are running.

ArchLinux

### Package

Distro package manager

### Nextcloud Server version

22.2.3

### Nextcloud Desktop Client version

3.5.2 (Arch)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
This sounds like an issue to take up with the downstream packager: https://archlinux.org/packages/extra/x86_64/nextcloud-client/

P.S. libsecret should be usable as well IIRC. And it appears to be a dependency of qt-keychain-qt5 in ArchLinux
