### ISSUE TITLE
[Bug]: Blurry text in system tray menu

### ISSUE THREAD

**Issue by dbolton** [nextcloud/desktop#4788]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Some text on the system tray menu looks blurry (circled below). 
![image](https://user-images.githubusercontent.com/712270/181661403-21f7418f-81e6-459c-adc9-2a135ea8b497.png)

### Steps to reproduce

1. In system tray, click on Nextcloud icon
2. Click on your username (menu on top left)

### Expected behavior

Text should appear consistently sharp

### Which files are affected by this bug

N/A

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

24.0.3

### Nextcloud Desktop Client version

3.4.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @dbolton could you check if this is still an issue on the latest version of the desktop client (3.5.x)? Thanks!

**Comment by dbolton** [comment]
@claucambra It looks the same to me in 3.5.4.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
