### ISSUE TITLE
Remove outdated ChangeLog file from repository

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#4791]
The file [ChangeLog](https://github.com/nextcloud/desktop/blob/b718c7dd9b18b7d3525c0ed9109cd154a9e55df4/ChangeLog) stops at v2.6.4

The whole v3.x series is not there.

Please remove it.

Or rename it to "ChangeLog - legacy" and add a note to the top which refers to the release page.

**Comment by github-tomster** [comment]
@rakekniven 
one can study on 🗞️ 🕰️ :
https://github.com/nextcloud/desktop/issues/1952
or
https://github.com/nextcloud/desktop/issues/1506
and
https://github.com/nextcloud/desktop/issues/1194

i hope it helps 🤞🏻 🍀 

@camilasan 
[looks like the task is still active ~ 1 573 920 minutes and running](https://github.com/nextcloud/desktop/issues/1194#issuecomment-520421978) 🐹 🎡 

**one can read this feedback given in my leisure time for free!**

**Comment by claucambra** [comment]
> I really thought this file was removed. There is this issue that requests sort of the opposite #4565. Now I am thinking that we should update the ChangeLog.
> 
> @claucambra @matthieugallien @allexzander wdyt?

My 2 cents -- I think it's a good thing to keep and update, most requests to delete it seem to stem from the fact that we haven't touched it in so long (which is fair).

 I don't know what we should do about all the missing versions though :/

**Comment by github-tomster** [comment]
the data from the past years shows: there is little to no interest in that changelog of this software. 🕳️ 
will the effort be worth it? 🤷🏻‍♂️
