### ISSUE TITLE
[Bug]: Linux Desktop version loose token after network reconnect 

### ISSUE THREAD

**Issue by alexander-potemkin** [nextcloud/desktop#4796]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I'm using 3.5.3 Linux version and every time my laptop loose and regain connectivity, NextCloud stops syncing and appears to be offline. None of my actions bring it back online and after some time it shows a window requiring to grant authorization to the app (in the web browser).

 

### Steps to reproduce

1. Open NextCloud
2. Do your things
3. Disconnect your network (iPhone lost network in my case)
4. Reconnect to the internet
5. Done

### Expected behavior

I was expecting it would reconnect once the network is there (like it does on MacOS).

### Which files are affected by this bug

all?

### Operating system

Linux

### Which version of the operating system you are running.

Linux Mint 20.3

### Package

Appimage

### Nextcloud Server version

4.13.2

### Nextcloud Desktop Client version

3.5.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by koenr** [comment]
I can confirm this behaviour on Ubuntu 20.04, Desktop client 3.5.2, kernel ubuntu-5.4.0-122-generic
I have to restart the Nextcloud Desktop client to restore the connection. I didn't see it asking for authorisation, but may be I'm not patient enough.

**Comment by gregor-j** [comment]
The problem doesn't appear with 3.6.0-rc1 anymore on Ubuntu 20.04.

**Comment by Anarch157a** [comment]
Problem still happens on Debian unstable with 3.6.0 AppImage

**Comment by erdnuesse** [comment]
Confirming Nextcloud version 3.6.4git on 6.0 Arch, Issue persists.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
