### ISSUE TITLE
Closing Nextcloud Client leads to crash of Client

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/desktop#480]
Hello,

I did a short test with to of the latest debug versions here:
https://download.nextcloud.com/desktop/daily/Windows/

Using the latest build from last night "Nextcloud-2.5.0.0-Debug-20180704.exe" (Built from Git revision 41ca53 on Jul 4 2018) and also a build some days before, leads to a crash of the Desktop Client, when closing the app in the task bar.

One thing as additional information: Unfortunately I lost my crypto keys the clients asks me for when connecting to my cloud. I just click cancel then and the client works normally for unencrypted data.
But that should not lead to that crash when closing the app.

Regards

**Comment by blu-IT** [comment]
I forgot to mention: It is running on Win 10 Pro x64 plattform.

**Comment by blu-IT** [comment]
Hello,

I tested with latest version 2.5.0daily (build 20180827) built from Git revision 16337b on Aug 27 2018.
Closing nextcloud-client does not lead to a crash anymore (but other problems taht I will open a new issue tickt for), but still opens a box "Verbindungsassistent" (connection assistant).

Regards

**Comment by mgallien** [comment]
This is issue is really old.
If you still have the issue, can you test again with latest version ?
If the problem is fixed, please close this issue.
