### ISSUE TITLE
[Bug]: Sparkle update to 3.5.4 failing

### ISSUE THREAD

**Issue by foss-** [nextcloud/desktop#4809]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

macOS 12.5
3.5.3git (build 11144) installed. Checking for updates shows 3.5.4 is available.

### Steps to reproduce

1. Clicking `Install Update` button
2. See `Update Error! Failed to extract update.`

Also when then pressing `Cancel Update` button the option to check for updates is greyed out until Nextcloud Settings are closed and reopened.

### Expected behavior

Update should be installed

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

12.5

### Package

Other

### Nextcloud Server version

various

### Nextcloud Desktop Client version

3.5.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @foss, this has now been fixed. Thanks for reporting!

**Comment by foss-** [comment]
Confirming - thank you!

**Comment by monochromec** [comment]
Issue surfaced once again when updating from 3.8.1 to 3.8.2 on OSX 13.3.1:

2023-05-19 07:32:43:289 [ debug nextcloud.gui.updater /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-14890/src/gui/updater/sparkleupdater_mac.mm:42 ]	[ -[DelegateObject updater:didFindValidUpdate:] ]:	Found a valid update.
2023-05-19 07:32:47:321 [ debug nextcloud.gui.updater /var/folders/yr/9dx0mtfj7kdf4725tmcz6md80000gp/T/macos-14890/src/gui/updater/sparkleupdater_mac.mm:63 ]	[ -[DelegateObject updater:didAbortWithError:] ]:	Error Domain=SUSparkleErrorDomain Code=3000 "Failed to extract update." UserInfo={NSLocalizedDescription=Failed to extract update.}

Workaround is a complete new install of the desktop client. 

More than happy to provide additional info - jut let me know.
