### ISSUE TITLE
Linux Desktop Client/Server doesn't connect while using selfsigned cert

### ISSUE THREAD

**Issue by bubieszka** [nextcloud/desktop#481]
Hi, following [this](https://help.nextcloud.com/t/connect-to-local-ip-with-invalid-certificate/33654/2) subject I'm unable to use beta desktop client to connect NC server when using SSL certificate.

thx.

**Comment by rullzer** [comment]
Ah right I think we need to set the certificate list also in the webview. I'll see if I can reproduce and fix this.

**Comment by hughwilliams94** [comment]
Any progress on this or a potential workaround? It is a little frustrating not being able to access my files at the moment. Had to use the beta as I was having Qt issues with the stable client.

**Comment by bubieszka** [comment]
Indeed. I'm not working on any workaround at the moment. I'm using mobile and www app , while waiting to fix client/server issue.

**Comment by hughwilliams94** [comment]
Just checking in again, it has been a month and this issue is super frustrating!

**Comment by htot** [comment]
@rullzer Have you been able to reproduce? If not, I can create an account for you on our NC server.
