### ISSUE TITLE
Sync files with any WebDAV server (not just NextCloud server instances)

### ISSUE THREAD

**Issue by ATLief** [nextcloud/desktop#4823]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
The NextCloud client is great and I love using it, but it only seems to work with NextCloud (and maybe OwnCloud) server instances despite otherwise using an open standard (WebDAV/HTTP). There are many situations where you have an existing WebDAV server and can't change the software your server is running (because of legacy/legal requirements, a limited software stack, insufficient computing power, etc), and in those cases you wouldn't be able to use the NextCloud client.

That's really unfortunate, because there doesn't seem to be any comparable cross-platform software for non-NextCloud WebDAV servers. There are lots of WebDAV clients, but not ones that continuously sync files via incremental transfers. This pushes some people towards proprietary file syncing solutions. It would be awesome if the NextCloud client could interface with any generic WebDAV server and WWW-Authentication. Maybe that would even simplify what NextCloud server needs to handle.

**Comment by schworak** [comment]
This would be fantastic! I would love to be able to auto-sync files between a folder and a WEBDAV server besides Nextcloud/Owncloud.

**Comment by jospoortvliet** [comment]
Disclaimer: I'm not a Nc client dev, maybe I'm wrong about this, so take this with a grain of salt.

There is a reason such clients don't exist: without a ton of extra webdav extensions and information, reliable syncing is nearly impossible. It is already quite hard WITH those extensions ;-)

The initial client behind Nextcloud made about a decade ago worked 'just' over webdav, all the changes to the protocol were done one-by-one to make syncing faster and more reliable - and here we are, it's no longer working with 'just' WebDAV.

The sync part was based on csync, look for it, perhaps it can help you. But keep in mind its limitations ;-)

**Comment by claucambra** [comment]
@jospoortvliet is right -- we don't have plans for this as it is difficult enough to get reliable sync working with our extensions to WebDAV
