### ISSUE TITLE
[Bug]: Deleted folders not synced

### ISSUE THREAD

**Issue by TimTrayler** [nextcloud/desktop#4824]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When I delete a folder on my desktop, the files are also deleted on the server but the (now empty) folder stays on the server.

### Steps to reproduce

1. Delete a folder on Windows & wait for it to sync
2. Open the website and see that the folder is still there (but the files are gone)

### Expected behavior

When deleting a folder, I expect NextCloud to also delete the folder and not just the contents.

### Which files are affected by this bug

Folders

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 (Build 22621.317, Insider Release Preview)

### Package

Other

### Nextcloud Server version

24.0.2

### Nextcloud Desktop Client version

3.5.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by TimTrayler** [comment]
1. No, unless I restart sync
2. I own all folders affected
3. Ok

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
