### ISSUE TITLE
[Bug]: Virtual File support doesn't work on bind mount

### ISSUE THREAD

**Issue by Ziris85** [nextcloud/desktop#4835]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I understand that Virtual File support on Linux is experimental at this time, but figured I would report this in case anyone else has encountered this before. I have the Nextcloud client installed on my (Manjaro) system and doing Virtual File syncing to just the default Nextcloud folder in my home directory. When I select `.nextcloud` files from within there, the file is properly fetched and displayed as I would expect. However, I have some bind mounts set up from my Nextcloud folder to other locations in my home directory, and when attempting to open `.nextcloud` files from those locations, the fetch and display action doesn't seem to work. It appears to start to work since I see the Nextcloud app pop up briefly, but nothing happens after that. The bind mounts I have look like:
```
/home/user/Nextcloud/Documents  /home/user/Documents    none    defaults,bind   0 0
```

### Steps to reproduce

1. Set up Nextcloud account with Virtual File support on client
2. Bind mount directory within Nextcloud folder to another location
3. Navigate to bind mount directory
4. Double-click (or otherwise attempt to open) any `.nextcloud` file within

### Expected behavior

Double-clicking the file would have the Nextcloud client fetch and display the file normally.

### Which files are affected by this bug

All .nextcloud files

### Operating system

Linux

### Which version of the operating system you are running.

Manjaro

### Package

Distro package manager

### Nextcloud Server version

24.0.3

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing logged on server from this.
```

**Comment by joshtrichards** [comment]
Hi @Ziris85 - Thanks for the report. I know this was a awhile ago. Are you still able to reproduce this behavior? And if so, does anything appear of interest in the client-side debug logs?

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
