### ISSUE TITLE
[Bug]: X11 connection broke: No error (code 0)

### ISSUE THREAD

**Issue by JackJeisly** [nextcloud/desktop#4837]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello,
Nextcloud-3.5.4-x86_64.AppImage
in Debian 11 with non-free driver for NVidia give me:
```
$ ./Nextcloud-3.5.4-x86_64.AppImage
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 441 requests (441 known processed) with 0 events remaining.
```
Thanks!

### Steps to reproduce

1. I start the Nextcloud-3.5.4-x86_64.AppImage:

`$ ./Nextcloud-3.5.4-x86_64.AppImage`

2. I see:
```
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 441 requests (441 known processed) with 0 events remaining.
```

It all...

### Expected behavior

Application just must work?

### Which files are affected by this bug

Nextcloud-3.5.4-x86_64.AppImage

### Operating system

Linux

### Which version of the operating system you are running.

Debian 11

### Package

Appimage

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by JackJeisly** [comment]
I try 3.6.0-rc1, not effect. ( A see again:

```
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 441 requests (441 known processed) with 0 events remaining.

```
System is updated now.
Debian 11 / xserver-xorg-core (2:1.20.11-1+deb11u2) / nvidia-legacy-390xx / LXDE

**Comment by JackJeisly** [comment]
I try AppImage 3.6.2 - no effect. ( May be problem with 2 monitors and nvidia-legacy-390xx?

**Comment by johann-petrak** [comment]
Seeing this or something similar on Ubuntu 22.04: 

```
./Nextcloud-3.7.3-x86_64.AppImage 
The X11 connection broke: No error (code 0)
X connection to :1 broken (explicit kill or server shutdown).
```
All other X11 and other apps work fine in that session.

**Comment by johann-petrak** [comment]
Is there any chance to get feedback on this or some hint for workarounds or should I just accept that the client will not work for my standard Linux (Ubuntu 22.04)? Is there any alternative that can be used instead?

**Comment by johann-petrak** [comment]
This error disappeared for me after upgrading my GPU driver. 

However, the error message is so cryptic that maybe some other way to provide more helpful information should be implemented. After all, all the other desktop applications (including the owncloud client) did not show any error and apparently did not need the GPU driver at all). Why would a simplistic app like nextcloud need it?

**Comment by brainchild0** [comment]
I confirm. 

I am running Linux Mint 21.2.   I am connecting to a remote system through SSH with X forwarding.

I have installed Nextcloud Desktop from the native package, and it works fine. The version is 3.4.2.

However, when I run the application distributed as AppImage, I receive the same error message (below).

I have tested with AppImage distributions for version 3.4.2, 3.8.2, and 3.9.0-rc1.

---

```
The X11 connection broke: No error (code 0)
X connection to localhost:11.0 broken (explicit kill or server shutdown).
```

**Comment by nuliknol** [comment]
I see posters have problems for App Images, I also have an app image of OpenSCAD, and I am also getting this error, so it must be some sort of permission because App Image does some sort of chrooting and it must be failing to see user's home directory where X files are. I can perfectly run xterm or xclock, but when running app image for OpenSCAD it fails. So ...

**Comment by MattBlissett** [comment]
It might be sufficient to reboot/restart X.  I suspect graphics drivers were upgraded in the background.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
