### ISSUE TITLE
"Sign in via Nextcloud notification" enhancements for macOS

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#4841]
- [x] The "Sign in via Nextcloud notification" notification does not have a primary button. "Approve" should be that one. :)
- [x] When clicking either "Approve" or "Deny", the notification should vanish (be marked as read). Currently it stays there
- [x] It says "Please approve or deny" but there is no "Deny" option. That should be added between "Approve" and "Mark as read"
- [ ] There is a quite long delay in seeing this message. In practice, the Android app displays this immediately, and the desktop client does not, even after waiting 20-30 seconds.
- [ ] Frank reported that on macOS when the message shows the view doesn't scroll up top automatically so you have to scroll manually

![Desktop sign in](https://user-images.githubusercontent.com/925062/183924715-fc5131df-d180-4ed6-8974-613eeb1ce811.png)

cc @claucambra

**Comment by mbousq** [comment]
My 2 cts :

-  notifications to be "always-on-top". Can't check right now, but when I had sync-errors I had to scroll down past all the errors to get to the notification. Would be easier have that notification "pinned" somehow :thinking:

**Comment by jancborchardt** [comment]
@camilasan btw is there any quite long delay in seeing this message? In practice, the Android app displays this immediately, and the desktop client does not, even after waiting 20-30 seconds.

**Comment by jancborchardt** [comment]
@camilasan can confirm, with 3.10.1 it is now basically instant on Ubuntu 20.04. Really amazing, this makes it a looooot more seamless to sign in. :)
