### ISSUE TITLE
After some time tray icon in macOS becomes blurry and opens unresponsive window

### ISSUE THREAD

**Issue by Entmatix** [nextcloud/desktop#4846]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After some time tray icon becomes blurry. Not a big deal, but window that opens when you click on the icon is unresponsive and appears at least for 1/3 out of the screen. Looks like this:

https://0x0.st/o2ad.32.png

After restart of the app it becomes normal for some time (day, half of the day, couple of hours).

### Steps to reproduce

1. Run nextcloud desktop.
2.  Wait for tray icon to become blurry.
3.  Click on tray icon.

### Expected behavior

Tray icon should not be blurry. When clicking on it window should be opened in visual part of the screen. Interactive objects like buttons, links in the window should be responsive.

### Which files are affected by this bug

No files

### Operating system

Mac OS

### Which version of the operating system you are running.

12.4

### Package

Other

### Nextcloud Server version

nextcloud:latest with mariadb 10.5 from hub.docker.com

### Nextcloud Desktop Client version

3.5.4 build 11184

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Entmatix** [comment]
With macOS 13.1 and Nextcloud desktop 3.6.6 I experience the same bug.

**Comment by joshtrichards** [comment]
Is your situation the same as #5121?

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
