### ISSUE TITLE
[Bug]: Overlay Icons not visible on Windows Explorer after upgrade to 3.5.X

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/desktop#4848]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

So i had NC 3.4.4 and all the green check mark where there. Once i updated to 3.5.4 the green checks went away so after doing some reached i had to download and  install Microsoft Visual C++ Redistributable. I did a reboot and green checks are back. This is without VFS 

I also did a fresh install of NC 3.5.4 and the same issue no green checks i downloaded and  installed Microsoft Visual C++ Redistributable

https://help.nextcloud.com/t/missing-sync-icons-in-windows-explorer/6610/50?u=andyxheli

Maybe same as that was reported a log time ago https://github.com/nextcloud/desktop/issues/978

https://github.com/nextcloud/desktop/issues/978#issuecomment-451984491
...

### Steps to reproduce

Please see Bug description
...

### Expected behavior

Bug description
...

### Which files are affected by this bug

All

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10, Windows 11

### Package

Appimage

### Nextcloud Server version

24.0.3

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by andyxheli** [comment]
I had a computer that was running 3.5.1 and same issue.

**Comment by allexzander** [comment]
You may need to reboot after a fresh install. The Explorer.exe may not run this shell integration until reboot, or a simple sign out and sign in. This can explain why it started to work after rebooting, without necessarily installing the redistributable.
AFAIK, we did not have any changes to shell integrations in 3.5.x.

**Comment by andyxheli** [comment]
I've already rebooted and loged off prior to installing the C++ redistributable and that didn't fix the issue. And I've tried this in 10 computers. 

After installing the c++ redistributable on all of the 10 computers the Issue was resolved. 

So there's definitely something wrong with the install especially if I see the same result on multiple computers.

**Comment by allexzander** [comment]
We had another user with an identical issue where overlays were not visible and the context menu "Nextcloud" is also unavailable. The way to diagnose if this is the same problem on Windows 10 is to try and call the `regsvr32` command in an Admin-privileged cmd.exe on either of 2 DLLs from **C:\Program Files\Nextcloud\shellext**. If there is an error dialog, then, the VC redist needs to be installed from here https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022. This solution should be used until we have came up with a better solution in one of the new releases.

**Comment by allexzander** [comment]
Fixes were merged. 3.7.0 will have this working without the need to install VC Redist.
