### ISSUE TITLE
[Bug]: When some files fail to upload, all files in this task will be uploaded again

### ISSUE THREAD

**Issue by hiikii** [nextcloud/desktop#4849]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When I need to upload a large folder (like it has 200G, 6000+ files), it will inevitably have some files that fail to upload, which is fine, but I found that when Nextcloud re-uploads, it always upload the entire folder again.

I don't know if this is a feature or a bug, I'm using the latest Nextcloud Desktop (3.5.4) and Nextcloud Server (24.0.4), to fix the problem I even reinstalled Nextcloud Server and uploaded my files again, but It still happens…

### Steps to reproduce

1. Copy a folder, as long as there are enough files
2. Nextcloud will start uploading normally, but due to network or other problems, some files will fail to upload and need to be re-uploaded
3. Nextcloud will upload those failed files again after the entire sync task is complete
4. After this upload task, the original folder will be uploaded again, even if most of the files have already been uploaded
5. Maybe it's the same problem: if a folder is being copied to the Nextcloud sync directory, NextCloud will start uploading some of the files that have already been copied, but will upload the entire folder again after the copying is complete
...

### Expected behavior

Even if there are some files that failed to upload, all files in the task should not be re-uploaded one or more times.

### Which files are affected by this bug

I tested two folders: Tabby Portable & My Media Folder (with pictures, videos and audio)

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"5WiVuODAE9GFlIHQ6DnW","level":4,"time":"2022-08-12T23:53:39+00:00","remoteAddr":"","user":"hiikia","app":"webdav","method":"PUT","url":"/remote.php/dav/files/hiikia/AmazonS3/Media/3415.jpg","message":"Legacy cipher is no longer supported!","userAgent":"Mozilla/5.0 (Windows) mirall/3.5.4stable-Win64 (build 20220802) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"24.0.4.1","exception":{"Exception":"OC\\ServerNotAvailableException","Message":"Legacy cipher is no longer supported!","Code":0,"Trace":[{"file":"/home/www/html/apps/encryption/lib/Crypto/Encryption.php","line":237,"function":"getLegacyCipher","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->"},{"file":"/home/www/html/lib/private/Files/Stream/Encryption.php","line":286,"function":"begin","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->"},{"function":"stream_open","class":"OC\\Files\\Stream\\Encryption","type":"->"},{"file":"/home/www/html/lib/private/Files/Stream/Encryption.php","line":213,"function":"fopen"},{"file":"/home/www/html/lib/private/Files/Stream/Encryption.php","line":188,"function":"wrapSource","class":"OC\\Files\\Stream\\Encryption","type":"::"},{"file":"/home/www/html/lib/private/Files/Storage/Wrapper/Encryption.php","line":470,"function":"wrap","class":"OC\\Files\\Stream\\Encryption","type":"::"},{"file":"/home/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php","line":301,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->"},{"file":"/home/www/html/lib/private/Files/View.php","line":1175,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/home/www/html/lib/private/Files/View.php","line":1010,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/home/www/html/lib/private/Files/Node/File.php","line":114,"function":"fopen","class":"OC\\Files\\View","type":"->"},{"file":"/home/www/html/lib/private/Metadata/Provider/ExifProvider.php","line":19,"function":"fopen","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/home/www/html/lib/private/Metadata/MetadataManager.php","line":76,"function":"execute","class":"OC\\Metadata\\Provider\\ExifProvider","type":"->"},{"file":"/home/www/html/lib/private/Metadata/FileEventListener.php","line":101,"function":"generateMetadata","class":"OC\\Metadata\\MetadataManager","type":"->"},{"file":"/home/www/html/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OC\\Metadata\\FileEventListener","type":"->"},{"file":"/home/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/home/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/www/html/lib/private/Files/Node/HookConnector.php","line":118,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/home/www/html/lib/private/legacy/OC_Hook.php","line":106,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/home/www/html/apps/dav/lib/Connector/Sabre/File.php","line":472,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/home/www/html/apps/dav/lib/Connector/Sabre/File.php","line":399,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/home/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1137,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/home/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":492,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/home/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/html/apps/dav/lib/Server.php","line":358,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/home/www/html/remote.php","line":166,"args":["/home/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/www/html/apps/encryption/lib/Crypto/Crypt.php","Line":319,"CustomMessage":"--"},"id":"62f6fdde550e1"}
```

### Additional info

When Nextcloud uploads a folder for the first time, Nextcloud Server's logging is normal, but when a re-upload is triggered (this time the whole folder is uploaded again because some files failed to upload), Nextcloud generates a lot of similar logs. I guess it's because the file was uploaded again with no changes?

**Comment by joshtrichards** [comment]
The second run takes about as long as the first attempt, correct?

What does the PROPINFO transaction (for a randomly selected file in the batch) look like just before the same file's matching PUT transaction happens?

Better yet, and chance you can provide a debug log from the client? Feel free to search and replace your username/hostname/folder names/etc if desired.

> When Nextcloud uploads a folder for the first time, Nextcloud Server's logging is normal, but when a re-upload is triggered (this time the whole folder is uploaded again because some files failed to upload), Nextcloud generates a lot of similar logs. I guess it's because the file was uploaded again with no changes?

I assume you're referring to the log entry you provided that contains the below: 

> `Legacy cipher is no longer supported`
> `ServerNotAvailableException`

Those indicate something wrong with your server side Encryption setup. The resulting ``ServerNotAvailableException` would likely prevent successful syncing. You're certain you're only seeing those on the second pass through the batch of files?

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
