### ISSUE TITLE
Make Talk notifications reply-able on macOS

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#4851]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

With #4512 we can do a lot more with notifications on macOS -- including message replies. Seems fairly sensible we should add the capability to reply to Talk messages directly from the notifications

@jospoortvliet @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
This then would be in native/os notification.
Do you have a screenshot how others do this?

**Comment by claucambra** [comment]
> This then would be in native/os notification.
> Do you have a screenshot how others do this?

This is Telegram for macOS (which uses the native mechanisms to do this):

![Screenshot 2022-08-17 at 12 00 38](https://user-images.githubusercontent.com/70155116/185092621-c47b6211-542f-4953-aa67-ea7226473ebd.png)

![Screenshot 2022-08-17 at 12 00 44](https://user-images.githubusercontent.com/70155116/185092642-63bf1124-e393-4155-9cdd-7f3bcf2f4c5f.png)
