### ISSUE TITLE
[Bug]: Nextcloud Setup Buttons hidden behind Windows Taskbar

### ISSUE THREAD

**Issue by thilojaeggi** [nextcloud/desktop#4856]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When installing Nextcloud during the setup screen on the Folder selection window the Buttons to Connect are hidden behind the Windows Taskbar.
It seems the Window is too big?
![Inked2022-08-17](https://user-images.githubusercontent.com/20727326/185325433-9352edf8-8dc2-4d4c-af12-6ba6be438b50.jpg)

### Steps to reproduce

1. Start the Nextcloud Installer
2. Go through the Installer until the Sync Window where you can select which Folder, Virtual Files

### Expected behavior

The Buttons should be visible at the Bottom of the Window to continue the Setup of Nextcloud.

### Which files are affected by this bug

Nextcloud.exe

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 & Windows 11

### Package

Other

### Nextcloud Server version

24.0.3

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jookk** [comment]
<img width="534" alt="bug" src="https://user-images.githubusercontent.com/11217085/197740574-e3ec3767-f8ff-48e8-b7b0-a0eeabccdc6d.png">
I have to rotate screen to configure update settings :D

**Comment by thilojaeggi** [comment]
Any update here, I've seen it again lots of times on client devices.
