### ISSUE TITLE
Crosscompiling problem for windows from OpenSuse Leap 15.0

### ISSUE THREAD

**Issue by stelhs** [nextcloud/desktop#486]
Hi guys, I tride to build NexctCloud desktop for Windows and have a problem with LIBCLOUDPROVIDERS.

I created Docker with OpenSuse Leap 15.0 ([docker file](http://sr38.org/Dockerfile2)).
I have a problem with cloudproviders library. Install this library was not no influence on build process.
I think that special crosscompile library needs for build. For example: mingw32-libcloudprovider needs to be installed and registered in the file [Toolchain-mingw32-openSUSE.cmake](https://github.com/nextcloud/desktop/blob/master/admin/win/Toolchain-mingw32-openSUSE.cmake).
I run cmake with parameters:
` -D CMAKE_TOOLCHAIN_FILE="path/to/Toolchain-mingw32-openSUSE.cmake"  -D WITH_CRASHREPORTER=ON` 

Please see [Error log file](http://sr38.org/log_suse15_0.txt)

I tride to build with original [Dockerfile](https://github.com/nextcloud/desktop/blob/master/admin/win/docker/Dockerfile) it seems that file was obsolete. Because in this version OpenSuse cloudproviders library is absent.

Can you help me with build last NextCloud client (desktop) for Windows?

**Comment by tabp0le** [comment]
See https://github.com/nextcloud/desktop/issues/426

**Comment by stelhs** [comment]
Thanks!
