### ISSUE TITLE
[Bug]: MacOS menu icon remains hidden after removal

### ISSUE THREAD

**Issue by jancbeck** [nextcloud/desktop#4860]
### Bug description

There is no way to bring back the Nextcloud desktop icon in the MacOS menu bar after it's been removed.

### Steps to reproduce

1. On Mac, Hold CMD and drag the menu icon away from the menu bar and let go of the left mouse button [[detailed instructions](https://www.macrumors.com/how-to/rearrange-macos-menu-bar-icons/)]
2. Try to access Nextcloud Desktop settings

### Expected behavior

As far as I know the menu icon is the only way to access NextCloud client on Mac. I would expect that
a. it's not possible to remove the icon
b. there's another way to bring back the menu icon such as the .menu files in /System/Library/CoreServices/Menu Extras

### Which files are affected by this bug

all of them

### Operating system

Mac OS

### Which version of the operating system you are running.

12.5

### Package

Appimage

### Nextcloud Server version

22.2.10

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Reinstalling the desktop client solved the issue.

**Comment by frenchcharly** [comment]
I have encountered the same problem, even removing the app and its .plist files did not resolve the situation.

Maybe this parameter is stored by macOS rather than the NC desktop client?

**Comment by jancbeck** [comment]
Since I created this issue, the icon has come back but I don't know what caused it. I tried reinstalling initially and that did not work. My guess it's either been a recent desktop client update or installing Ventura a couple weeks ago. I never had Hidden Bar or Bartender installed.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
