### ISSUE TITLE
[Bug]: Notification pop up again and again

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#4861]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

There are other bug reports about notification but none of them describe exactly my issue.

I work mainly on the Desktop and don't open the web client that often. Especially I don't want to mark all notifications as read all the time explicitly on the web or the desktop client.

This lead to the situation that notification pop up regularly even from chat messages or other activities which are already from many weeks ago.

I think we need a more "intelligent" way of handling notifications. It is OK that they stay in the list unless I clicked them away. This let me check the list to see if I missed something or to re-read the notification. But the pop up notification should only happens once.

Maybe clicking on the notification could also trigger a "dismiss"-operation but I'm not sure if this is supported by the the notification system of (all) operating systems

### Steps to reproduce

-

### Expected behavior

notification are not shown again and again

### Which files are affected by this bug

-

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 35

### Package

Distro package manager

### Nextcloud Server version

24

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
This is fixed with https://github.com/nextcloud/desktop/pull/4508 :)
