### ISSUE TITLE
incoming call notification should disapear when the call ended or when I picked it up

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#4862]
The new incoming call notification is really nice! 

The only issue I have with it is that it stays open forever. Sometimes I answer a incoming call with my mobile device or with a already open Talk browser tab. In the evening, when I close all my windows and shutdown the PC I see all the incoming calls notification still sitting in the background.

It would be nice if the server would send a notification to the client if a call was ended or if the user joined the call without clicking a button on the notification explicitly and the client would than close the notification again.

**Comment by claucambra** [comment]
This is now the case with #4672 :)
