### ISSUE TITLE
[Bug]: Huge Energy Consumption on Mac (idle)

### ISSUE THREAD

**Issue by JimLoose** [nextcloud/desktop#4872]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The only App on my MacBook Air (M2, 2022) which has huge energy consumption is Nextcloud.app

<img width="346" alt="image" src="https://user-images.githubusercontent.com/195000/187049347-f794721a-6be9-4566-87f6-94c9c4472d25.png">

### Steps to reproduce

You can click on the battery symbol in the upper right corner on your MacOS to see the screenshot or monitor Nextcloud in the Activity Monitor in idle mode

<img width="914" alt="image" src="https://user-images.githubusercontent.com/195000/187049399-1066325d-cb37-4555-a138-7c91d0b31999.png">

### Expected behavior

low energy consumption in idle mode

### Which files are affected by this bug

all

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS Monterey 12.5.1

### Package

Appimage

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

Version 3.5.4 (macOS)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by karlemilnikka** [comment]
I’m experiencing the same issue. 

macOS 12.6 (Intel)
Nextcloud Server 24.0.5
Nextcloud Desktop Client 3.6.0
Server Encryption: enabled
End-to-end encryption: disabled
External user-backend: none

**Comment by anastasi0s** [comment]
Same here, Immense battery drain!

macOS 12.6 M1
Nextcloud Server 24.0.5
Nextcloud Desktop Client 3.6.1git (build 11939)
Server Encryption: disabled
End-to-end encryption: disabled

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
