### ISSUE TITLE
[Bug]: Nextcloud Windows client updates force a system restart

### ISSUE THREAD

**Issue by cmdrwgls** [nextcloud/desktop#4874]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Updating the Windows Nextcloud client forces a system restart.

### Steps to reproduce

1. Start an update
2. System restarts, closing all open windows, WITHOUT asking permission

### Expected behavior

1. Start an update
2. Update completes
3. Updater ASKS if the system should be restarted

### Which files are affected by this bug

None

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

Irrelevant

### Nextcloud Desktop Client version

At least since 3.5, still present on 3.5.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by allexzander** [comment]
@cmdrwgls It should be fixed when updating from 3.5.4 and onwards. Kindly try updating to beta RC2 (you'd need to change the update channel from `stable` to `beta` in the `Settings` dialog).

**Comment by jcjveraa** [comment]
I can confirm that with my use case:

1. My system exhibited the exact same behavior as reported in this issue up to the second-to-last update of the app;
2. I just installed an update and as expected I was asked 'do you want to reboot now, or reboot later'.

Seems to work as expected now in my case. I cannot confirm the version I was on, but this was during the update to 3.6.0.

**Comment by cmdrwgls** [comment]
> @cmdrwgls It should be fixed when updating from 3.5.4 and onwards. Kindly try updating to beta RC2 (you'd need to change the update channel from `stable` to `beta` in the `Settings` dialog).

Apologies, I have not tested this yet, I have no non-production instances to hand.  I appreciate _your_ prompt response even though I neglected one myself.

**Comment by allexzander** [comment]
> > @cmdrwgls It should be fixed when updating from 3.5.4 and onwards. Kindly try updating to beta RC2 (you'd need to change the update channel from `stable` to `beta` in the `Settings` dialog).
> 
> Apologies, I have not tested this yet, I have no non-production instances to hand. I appreciate _your_ prompt response even though I neglected one myself.

No worries. You can download 3.5.4 from here https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.5.4-x64.msi, install it on a clean system (with no prior NC client installation or with a client version older than 3.5.4) and then try to auto-update. You'll get a normal MSI installation wizard flow with no force reboot. I just tried it locally. You can then choose "No" when the reboot prompt appears.
Feel free to close the issue when confirmed as working. Too bad we had this problem present for some versions, but, now we hope this gets much better.

**Comment by cmdrwgls** [comment]
Tested 3.6.0, now asks before restart.  Closing.
