### ISSUE TITLE
[Bug]: Release Nextcloud-3.6.0-rc2-x64.msi actually installs 3.5.82rc2

### ISSUE THREAD

**Issue by michaelarnauts** [nextcloud/desktop#4876]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The release process for RC releases looks like it has a bug.

The x64 version of https://github.com/nextcloud/desktop/releases/tag/v3.6.0-rc2 actually installs 3.5.82rc2.

![afbeelding](https://user-images.githubusercontent.com/1193779/187188480-6e04f639-7d67-4c12-86a3-d71663f67df5.png)

This also causes confusion in the auto-updating of the Desktop Client when configured on the beta channel, since it keeps on asking to update to 3.6.0.

This issue was also the case for the v3.6.0-rc1 release. See https://github.com/nextcloud/desktop/issues/4832#issuecomment-1219294873

### Steps to reproduce

* Download a x64 RC release from GitHub, like https://github.com/nextcloud/desktop/releases/tag/v3.6.0-rc2
* Try to install it
* It installs a 3.5 version.

### Expected behavior

The packaging should be correct.

### Which files are affected by this bug

Nextcloud-3.6.0-rc2-x64.msi

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

N/A

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by BJKle** [comment]
@michaelarnauts 
That’s normal. Only releases will have the actual major.minor version. 

See: https://github.com/nextcloud/desktop/commit/fe7e883f3d1454d33859629216c8c7dd997f7dec

you can close this issue

**Comment by michaelarnauts** [comment]
> @michaelarnauts That’s normal. Only releases will have the actual major.minor version.
> 
> See: [fe7e883](https://github.com/nextcloud/desktop/commit/fe7e883f3d1454d33859629216c8c7dd997f7dec)
> 
> you can close this issue

I understand, but than the auto-update in the app needs to be improved, since it keeps on trying to update to 3.6.0rc2 every restart, but installing the update will never get there due to the wrong version.

**Comment by vithusel** [comment]
> 

I'm going to have to second this. If you run RC installs of Desktop. You'll get hounded with update notifications. You can tell it to ignore it but then you dont get any update notifications at all.

**Comment by claucambra** [comment]
Since we are now on 3.6.1 I will close this issue -- thanks for reporting!
