### ISSUE TITLE
Add start sync button

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/desktop#4877]
### Issue description
We are arount 20 Person use Nextcloud for our company documents. We use the Windows Sync Client to sync all our needed files at our hard disk. Sometimes we work together which mean that if someone is ready with the documents, we get feedback via mail or chat to start the work. 

The problem is, that the sync clien didn't synced the files that fast so we have to start the sync process manuall. Which is only possible at the settings window.

### Feature description
An start sync button at the huge notification window would be nice,

![Sncy Now](https://user-images.githubusercontent.com/8517736/187438888-c463fbb6-e01e-4480-abbf-6166045ab54b.png)

**Comment by Andreas-Kainz** [comment]
#### System Tray right click

![2022-09-26 13_21_37-](https://user-images.githubusercontent.com/8517736/192264049-c0a5d109-e29e-49ef-a187-d56406e2149f.png)

As example the right click at settings dialog has sync pause AND sync now but the right click at the notification center has only sync pause. should be the same between both context menues.

**Comment by Andreas-Kainz** [comment]
Example from another cloud storage app

![image](https://user-images.githubusercontent.com/8517736/192266082-69a54ffc-0597-4932-9389-a415da09536b.png)

**Comment by jancborchardt** [comment]
> The problem is, that the sync clien didn't synced the files that fast so we have to start the sync process manuall.

Sync is our bread and butter, so we should try to not have things like this happen. Cause even if we add a button, people still have to know it is there, and then click it.

Are there any other ways we can improve this, in a more automatic way?

**Comment by tobiasKaminsky** [comment]
Is it upload or download?
If file was changed on server then https://apps.nextcloud.com/apps/notify_push might help.

**Comment by Andreas-Kainz** [comment]
good point @jancborchardt. 

upload is done asap so no issue, but the download of selected folders from other users was done periodly. I would say arount 2 - 5 minutes (I don't know). 

I'm not sure how it work with virtual filesystem, I (we) use in the company the old way by selected folder sync.

**Comment by Andreas-Kainz** [comment]
There is a good reason that the sync client, didn't download all the time. So how would the sync client know, that the user want files from a specific folder up to date?
