### ISSUE TITLE
ntfs partition doesn't show up

### ISSUE THREAD

**Issue by gerhardbeck** [nextcloud/desktop#488]
Hi,
I got a problem with the nextcloud desktop client on Ubuntu 18.04 LTS:
I want to add a folder to the synchronizing options, which is on a
mounted ntfs partition (Arbeit-Persoenlich).
fstab is:
#Arbeit-persönlich
/dev/sda7   /media/Arbeit-Persoenlich   ntfs   defaults   0   2

The problem is that the mounted partition (and other ntfs partitions) is not seen in nextcloud client. See screenshot attached
![bildschirmfoto von 2018-07-08 20-23-57](https://user-images.githubusercontent.com/41069802/42519776-10197f1a-8465-11e8-8d44-c4be1a88ae38.png)

## Details
Browser: Firefox 61.0 (64 Bit)

## JavaScript Console Output

no loading of javascript as there is a no-tracker

## Steps to reproduce

1. Install Nextcloud client on Ubuntu.
2. Open the client and try to add a folder from an ntfs partition

**Comment by LightTemplar** [comment]
Same here. I have a NTFS partition, automounted at startup. It doesn't show up under /media/alexander, as it does in system. 
![image](https://user-images.githubusercontent.com/453783/42717416-0a10076c-8701-11e8-81be-3b718a309171.png)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

**Comment by gerhardbeck** [comment]
works with 2.6.1, thanks
