### ISSUE TITLE
Password updates in desktop and mobile apps?

### ISSUE THREAD

**Issue by tromlet** [nextcloud/desktop#4881]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Nextcloud Desktop should communicate to the user what the issue with logging in is.

I really like Nextcloud, but it is BEYOND unforgiving whenever one sets password expiration - which we do, because our instance is public-facing.

It’s a pretty bad experience for end users, who obviously WILL be connecting to their Nextcloud account across devices and platforms, and the apps don’t seem to prompt users that they need to enter their new password or that credentials are the problem at all - they just… stop working, and then it kind of seems like the desktop apps eternally just… keep trying with the old password, resulting in a disabled account, and then eventually an IP ban.

This makes it incredibly difficult to administer Nextcloud - especially since, as far as I can tell, the logs on the web UI are nowhere near informative enough to tell where or from what app or integration or user or IP address a failed login or problem is coming from.

To give you an idea: One of our users currently has Nextcloud Desktop installed on his machine. It isn’t syncing. It says “Offline”. There is nothing telling HIM his password is expired and he needs to reset it, and left-clicking the three little dots next to his account and left-clicking “Log In” does absolutely nothing. It doesn’t prompt him, it doesn’t do anything.

This is beyond words user unfriendly. I only figured out what its problem was by checking the logs, on the damn filesystem, because the logs in Nextcloud’s web interface provided no information about which user was having this problem, what IP address they were coming from, etc. Phenomenally useless logs on the web UI, and “Brute-force settings” doesn’t address these issues at all.

**Comment by joshtrichards** [comment]
I believe what you're asking for is mostly covered by #5307 so let's consolidate there to see what we can do about improving the user experience on the client side when there are password-related login problems.

> This makes it incredibly difficult to administer Nextcloud - especially since, as far as I can tell, the logs on the web UI are nowhere near informative enough to tell where or from what app or integration or user or IP address a failed login or problem is coming from.

Generally most paths for login failures are logged at the server-level and will include the client IP address - e.g.

https://github.com/nextcloud/server/blob/371aa1bc5d1c5a5be55ac8e9e812817a68a0cc23/lib/private/User/Session.php#L477
