### ISSUE TITLE
[Bug]: Login window is black 

### ISSUE THREAD

**Issue by ElektronikerDev** [nextcloud/desktop#4886]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After entering the server URL (in the setup process), the login dialog of Nextcloud itself opens. However, the nextcloud window is completely black. You can copy the HTML content out and paste it e.g. in Word (and it shows the login html inputs). But the Nextcloud browser doesn't manage to show colors in it and displays everything in black.

A start with the debug mode flag brings the following error:

``2022-09-01 13:47:16:133 [ critical  unknown:0 ]:    ARB::createContext: wglCreateContextAttribsARB() failed (GL error code: 0x502) for format: QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile), shared context: 0x30000 (Der Vorgang wurde erfolgreich beendet.) ``

``2022-09-01 13:47:16:144 [ critical  unknown:0 ]:    GDI::createContext: wglShareLists() failed. (Unknown error 0xc0072054.)``

We are using the following graphics cards: Intel iGPUs with **True Color 32-bit** color depth.

A version test with older nextcloud client versions showed that the login still seemed to work up to version 3.4.4. 

### Steps to reproduce

1. Open a fresh installed nextcloud desktop software
2. Type in a nextcloud url
3. Click on Login
4. And now comes the black login screen.

### Expected behavior

Normally you should see the login window where you can enter username and password.

### Which files are affected by this bug

Login system

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Enterprise 

### Package

Appimage

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

We tried this once with the original client provided by Nextcloud, as well as with a self-compiled version. Both brought the same (not working) result.

**Comment by joshtrichards** [comment]
This may have been addressed by #4582 which was released in v3.6.0 (also possibly #4821).

Are you still experiencing this?

**Comment by joshtrichards** [comment]
Assuming closed after not receiving confirmation after >6 months.
