### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by edvanleeuwen** [nextcloud/desktop#4888]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

File names with leading spaces are not synced.
Please reopen https://github.com/nextcloud/desktop/issues/4164

### Steps to reproduce

File names are not synced.

### Expected behavior

File names synced.

### Which files are affected by this bug

Several

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

23.0.8

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Nextcloud Server logs

```shell
-
```

### Additional info

-

**Comment by Queeq** [comment]
The leading spaces in filenames is a legitimate use case. I have a Windows user myself who does this and because of this bug half of the files is not synchronized.
Desktop client version: 3.6.1
Server: Nextcloud Hub 3 (25.0.0)

**Comment by joshtrichards** [comment]
Closing in favor of #4164 (reopened).
