### ISSUE TITLE
[Bug]: Using a path with umlauts as logDir is broken

### ISSUE THREAD

**Issue by uusijani** [nextcloud/desktop#4890]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Using a path with umlauts as `logDir` causes an incorrectly encoded directory to be created and used as log directory, instead of the specified directory.

### Steps to reproduce

1. Quit the client.
2. Edit `nextcloud.cfg`. Set `logDir=/home/jani/Tänne` (applying appropriately to your home directory)
3. Start the client.
4. `ls /home/jani/Tänne`

### Expected behavior

A listing of new log files residing in `/home/jani/Tänne`.

### Which files are affected by this bug

This question is unclear. The log files are the ones affected.

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 20.04

### Package

Distro package manager

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.4-20220806.084713.fea986309-1.0~focal1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This bizarre and otherwise exhaustingly long issue form is lacking a "What happens instead of my expected outcome" question, so I'm entering it here instead: there are no logs in the specified target directory (it doesn't even exist if you've not created it beforehand). Instead, like in the ye olden days, there is now a directory called `TÃ¤nne` containing the logs. In `nextcloud.cfg` the path has been re-encoded as `logDir=/home/jani/T\xc3\xa4nne/` which is apparently how it should be, since a similarly re-encoded value for a `...localPath` with umlauts in the `[accounts]` section has been working just fine for as long as I can remember using it.

**Comment by claucambra** [comment]
Hi, we just recently rewrote how debug packages are created and stored. Could you try the AppImage package generated here and see if the issue still occurs?

https://github.com/nextcloud/desktop/pull/4768#issuecomment-1239689487

**Comment by uusijani** [comment]
Hi @claucambra, I tested the appimage and the issue still reproduces.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
