### ISSUE TITLE
[Bug]: Windows Desktop Client crashes when synching shared folders when using Virtual Files

### ISSUE THREAD

**Issue by luddinho** [nextcloud/desktop#4894]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When sharing a folder with many files either on the same server instance from user_A to user_B or via federated cloud share from server instance X to server instance Y the windows desktop client crashes after an undefined time from the beginning of the synch of that specific shared folder.

e.g. in my case the folder contains nearly 1000 *.jpg files (each file size approx. 3.5 MB).
Exactly 962 files with a total size of 3.4 GB.

### Steps to reproduce

1. Login to the nextcloud instance X with user_A
2. Create a folder and add 1000 files (each file size aprox. 3.5 MB)
3. Share the complete folder to user_B on the same instance X.
4. Log off user_A from instance X
5. Log on user_B from instance X
6. Accept the share (if not done automatically via default setting)
7. Log off user_B from instance X
8. Start the Windows Desktop Client where user_B is configured (otherwise add user_B to the config)
9. Enable Virtual Files for user_B for the sync between server and desktop
10. Select from the Windows Explorer the shared folder and set via context menu to "Always keep on this device" to start the sync
11. Observe the log file "C:\Users\<USER>\AppData\Roaming\Nextcloud\<INSTANCE_NAME>_sync.log"
12. Cient will start the sync
13. After a couple of succeeded file sync the client crashes and the log file reports the status "3" and the errorString "WindowsError: 5: Zugriff verweigert"
14. Restart the client again, and observe the log file again
15. The same error will happen after a couple of suceeded files (undefined time)

### Expected behavior

Desktop Client must not crash when synching shared folders with virtual files.
Even the folder is shared from the same instance or shared via federated cloud share.

### Which files are affected by this bug

unknown

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro 21H2

### Package

Appimage

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
No server logs available regarding this crash. Only the client will throw the following Error from the log file of the related instance.
"C:\Users\<USER>\AppData\Roaming\Nextcloud\<INSTANCE_NAME>_sync.log"
```

### Additional info

Content of the log file:

timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | X-Request-ID
11:08:05||_TEST_SHARE_LARGE/Picture_423.jpg|64|2|1662364326|ce970a0de2e00459c541e6c5f6b88755|3399418|00188924octz3m9m1ij0|4||200|3399418|1662364326|99f27ff1-b820-4b5e-9520-c39ca5d37bad|
11:08:05||_TEST_SHARE_LARGE/Picture_426.jpg|64|2|1662364331|6b95234a2621a3d3cd908e8fb8e96d79|3405853|00188925octz3m9m1ij0|3|**WindowsError: 5: Zugriff verweigert**|200|3405853|1662364331|34f3118b-3457-49af-9a66-bef668a2888c|

The errorString is reported with "WindowsError: 5: Zugriff verweigert" --> "Access Denied"

**Comment by joshtrichards** [comment]
Hi @luddinho - This was a long time ago. Are you still experiencing this in current versions of the client?

**Comment by luddinho** [comment]
Hi @joshtrichards — Thanks for asking. I did not recognize that behavior again. Honestly I didn’t come up to this scenario sharing such an amount of files with other users.
But I did an analysis and crosschecked on my system **Win11 Pro 23H2** with the **Desktop-Client 3.13.3** connected to a **server instance v29.0.5**.

`user_a` is sharing a bunch of files (random files with a size of 1 to 8 MiB each, about 12 GiB in total) stored plain in a single directory and shared with `user_b`.
Connected both users with the client and triggered for `user_b` the action “Always keep on this device” from the context menu of that shared directory.

Result: I couldn't observe the issue anymore. I repeated this a couple of times via “Free space on Disk” and triggered a new sync to keep the files downloaded on the client again.
The synchronization was successful on every attempt.
**No more errors on my site. It works like a charm!**

![image](https://github.com/user-attachments/assets/d2ef9f10-3857-445f-8ecc-a724b6831902)

![image](https://github.com/user-attachments/assets/9bc5533d-c515-4473-b445-62ba2dded44d)

![image](https://github.com/user-attachments/assets/6c985e1f-cae7-4162-9106-c37855763b06)

![image](https://github.com/user-attachments/assets/6d8da1e8-ec77-4536-b882-9467a75d7860)
