### ISSUE TITLE
[Bug]: wrong position of desktop main window on macOS

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4897]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When opening up the main dialog by clicking on system tray icon, the main dialog window can be partially overlapped by the OS topbar.

### Steps to reproduce

1. Open the main dialog by clicking on system tray icon
2. See partially overlapped main dialog window

### Expected behavior

the main dialog window should be fully visible

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.0

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.82

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
@karlitschek do you have one of the new Macbooks with a notch? Have you found the bug to be reproducible when doing something specific? Any details would help :)

**Comment by karlitschek** [comment]
@claucambra Indeed. But what irritates me is that the windows position is not only wrong by a few pixels which could be explained with the menubar or the notch. The windows sometimes appear slightly below the menubar, sometimes its half below the menubar and sometimes its in the middle of the screen.

**Comment by claucambra** [comment]
> @claucambra Indeed. But what irritates me is that the windows position is not only wrong by a few pixels which could be explained with the menubar or the notch. The windows sometimes appear slightly below the menubar, sometimes its half below the menubar and sometimes its in the middle of the screen.

Could you share your debug archive? We have debug output when the tray window is positioned which should help us figure out which of the geometries used for positioning is borked...

**Comment by claucambra** [comment]
> @claucambra Indeed. But what irritates me is that the windows position is not only wrong by a few pixels which could be explained with the menubar or the notch. The windows sometimes appear slightly below the menubar, sometimes its half below the menubar and sometimes its in the middle of the screen.

That is indeed very weird. Are you also using a secondary monitor alongside your Macbook?
