### ISSUE TITLE
[Bug]: conflict resolution for existing folder when setting up sync connection is broken

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#4904]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The resolution thing for an existing server doesn't work - it detects a folder exists, gives me the options of what to do (overwrite or sync contents) but the 'connect' button will stay grey.

<img width="738" alt="Screenshot 2022-09-06 at 21 57 55" src="https://user-images.githubusercontent.com/551757/188730489-523537c3-0ea8-42e7-8507-3daa7ec50462.png">

### Steps to reproduce

1. create a new account
2. pick a non-empty folder to sync with the server
3. choose a resolution - any - you won't be able to proceed (at least not that I could find out)

### Expected behavior

When you pick a resolution, you should be able to proceed.
...

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

latest

### Package

Other

### Nextcloud Server version

25beta3

### Nextcloud Desktop Client version

3.6RC2

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
not really relevant I think
```

### Additional info

Not sure if client logs etc are relevant?

**Comment by qgjdev** [comment]
This is now again an issue for me on Nextcloud 3.15.3. Haven't had the issue before but when reinstalling my OS and afterwards installing Nextcloud through `ppa:nextcloud-devs/client` and trying to sync an existing folder (which is ~120GB so I'm not willing to move everything and re-syncing manually) I get the exact same problem. 

I've tried a workaround with a backup nextcloud.cfg from which I just copied the necessary lines (folder etc.) but then I'll be prompted to relogin after every reboot.
