### ISSUE TITLE
[Bug]: client app on M1 mac won't launch after reboot

### ISSUE THREAD

**Issue by mgrundkoetter** [nextcloud/desktop#4906]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After first installation of a fresh nexcloud client on an M1 mac, it will launch correctly and everything is working. After a reboot of the system, the app won't launch again and showing an error like reported here: https://help.nextcloud.com/t/macos-client-wont-launch-after-reboot/136662

The "solution" is to set "open with rosetta" in the information dialog of the app in macOS, then it will launch again. I assume the app kind of "forgets" the info it should run on the M1 hardware after the reboot and hence won't launch again. I further assume that this information is provided during the installation process correctly, because it always works after a fresh install of the client (same version).

### Steps to reproduce

1. Install client software on an M1 mac
2. launch the app, this will work
3. reboot the mac
4. launch of the client app will fail with an error
5. right click the app symbol in finder, open "information" dialog, activate "open with rosetta"
6. launch app, it will work now but you will have to log in again

### Expected behavior

The client app should natively work on an M1 mac after reboot without any manual settings.

### Which files are affected by this bug

nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 12.4 Monterey

### Package

Appimage

### Nextcloud Server version

23

### Nextcloud Desktop Client version

3.5.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
I cannot reproduce on my M1 Mac, do any debug logs get generated when the client tries to launch? If so, could you share them? Thanks!

**Comment by mgrundkoetter** [comment]
Sure. Where can find it?

**Comment by claucambra** [comment]
> Sure. Where can find it?

On macOS it is tricky to find the log folder as the system assigns a random temp location each time... 

Your best bet is to try to launch the client without Rosetta first, and once you have tried and the client has failed, to run it with Rosetta using your workaround and then generate a debug archive from the settings dialog

**Comment by farmio** [comment]
Hi 👋!
I have the exact same problem. Here are the debug archives:
[before restart.zip](https://github.com/nextcloud/desktop/files/9541374/before.restart.zip)
[after restart - rosetta.zip](https://github.com/nextcloud/desktop/files/9541375/after.restart.-.rosetta.zip)

**Comment by mgrundkoetter** [comment]
I also have a debug archive but as there is some sensitive information included about our instance (URL, Username, ...), I would like to not share this publicly. I can send it via email somewhere or upload it, but I won't share it here.

**Comment by claucambra** [comment]
@mgrundkoetter feel free to upload your logs here: https://cloud.nextcloud.com/s/FM7cKJ5tYaQg2gp

Might be a bit of an obvious question but -- could yoy try removing the desktop client from your system entirely and then installing a fresh version of 3.6.0?

**Comment by stjosh** [comment]
I am experiencing exactly the same issue with Nextcloud Desktop v3.6 on MacMini M1 and MacOS 12.5.1. When enabling system logs collection in the "Console" application while launching the Nextcloud Client, I am getting the error messages attached. Maybe this helps?

[System Logs.txt](https://github.com/nextcloud/desktop/files/9591538/System.Logs.txt)

**Comment by JSuenram** [comment]
Same issue here.
Ventura 13.1 latest NextCloud-Client

**Comment by nicoh88** [comment]
Same issue here. With Ventura 13.1 and Nextcloud 3.6.6.

After fresh install, all is fine. After a reboot, the app can no longer be opened. Remove and fresh install, all is fine.

I think it is a Time Machine Arch upgrade problem. I upgrade my mac-system from intel x64 to apple m1 arm and have restored my TimeMachine backup. Somewhere in ~/Library or wherever, there will be a config file with the architecture that the app should use when it starts.

**Comment by farmio** [comment]
Hi 👋! 
I just did another try of completely uninstalling the Nextcloud Desktop App - including deleting everything in `/Library` and `~/Library` referencing `com.nextcloud.desktop` and running `sudo pkgutil --forget com.nextcloud.desktopclient` (not that I really know what that even does 😬).
Then I reinstalled 3.7.3 and it seems to be working fine now.

**Comment by stjosh** [comment]
Many thanks @farmio - that resolved the issue for me as well! 😃

**Comment by conradhagemans** [comment]
> Hi 👋! I just did another try of completely uninstalling the Nextcloud Desktop App - including deleting everything in `/Library` and `~/Library` referencing `com.nextcloud.desktop` and running `sudo pkgutil --forget com.nextcloud.desktopclient` (not that I really know what that even does 😬 but it was solving an issue elsewhere so I gave it a shot). Then I reinstalled 3.7.3 and it seems to be working fine now. 🎉

I followed you steps and can confirm that everything works fine now.
Thanks.

**Comment by claucambra** [comment]
Glad to hear a clean install fixed the issue :)

**Comment by headkit** [comment]
Same problem with M3, after wakeup the NExtcloud client crashes.
