### ISSUE TITLE
[Bug]: Synchronise files that use resource fork on HFS file system

### ISSUE THREAD

**Issue by petrus-v** [nextcloud/desktop#4909]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Synchronise font files (likes PostScript Type 1, I know this one is an old one, but you know legacy projects...) between macOs desktop users is not working properly with HFS filesystem.

### Steps to reproduce

[font.zip](https://github.com/nextcloud/desktop/files/9506710/font.zip)

1. Install the joined font (unzip joined archive) on MacOs that use an HFS file system
2. synchronise that file on shared nextcloud directory
3. go to online nextcloud client, you'll notice the file is sync with 0ko without metadata files closed

...

### Expected behavior

when synchronise such file, get synchronised files metadata and ensure other MacOs users got those metadata properly and ready to use (at least for other macOs users).

### Which files are affected by this bug

UniveCon

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS catalina

### Package

Distro package manager

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I'm not an expert on this topic but from what I have understand is that font
on MacOs are saved on the [HFS](https://en.wikipedia.org/wiki/Hierarchical_File_System) [resource fork](https://en.wikipedia.org/wiki/Resource_fork). Nextcloud desktop client synchronise only data from data fork not resource fork.

So sharing font or any other files that have useful data on resource fork are not shared over MacOs users.

**Comment by muelli75** [comment]
Same issue here, Server 24.0.7, Client 3.6.1 (osx-22.1.0)
A quick fix would be nice, thousands of fontfiles are damaged because of that.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by fwcd** [comment]
I'm not sure if the Nextcloud Client syncs resource forks correctly. Ableton Live uses an [`Icon?` file](https://superuser.com/questions/298785/icon-file-on-os-x-desktop) for its projects and these don't seem to sync at all.
