### ISSUE TITLE
Make decision on resync existing folder more explicitly

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#4915]
![image](https://user-images.githubusercontent.com/5836855/189298064-fe869bd2-a6f1-497b-be81-af7b43b7cd4b.png)

As you can see default is "keep local data".
This means, if an user accidentally selects wrong folder, all of those data will be uploaded.

To make the user rethink about it, I tend to have no option selected by default.
This way user needs to select one and chances are higher that they are doing it right.

@jancborchardt or do you have another way to prevent such a scenario? (we know that sometimes user tend to click next, next, finish)

**Comment by Rello** [comment]
Hi,
still valid? I would close it as part of the cleanup. please reopen if you think its still relevant
