### ISSUE TITLE
Integrate file details into the tray window

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#4937]
Thanks to the changes in #4929 we can now integrate file details much more easily into the tray window. 

We can present sharing, file activity, and more within the tray window rather than opening a dialog for these, making the tray window more interactive instead of forcing users to switch back and forth between an external dialog and the tray window

@tobiasKaminsky @jancborchardt 

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Tell us how the feature should work

**Comment by tobiasKaminsky** [comment]
Nice idea!

Is "…" next to such a changed/added file/folder something common on Desktop?
Or how would you show this option?

**Comment by claucambra** [comment]
> Nice idea!
> 
> Is "…" next to such a changed/added file/folder something common on Desktop? Or how would you show this option?

We used to show it but chose to make it less visible as it often only contained one option (Show file activity). My assumption is we would start showing it again as a way to get into the "file details" page @jancborchardt?
