### ISSUE TITLE
Remove close button from the settings

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/desktop#494]
![image](https://user-images.githubusercontent.com/3404133/42688278-ec899f7e-869b-11e8-8c0b-dca48cb6a351.png)

The settings show a close button at the bottom. I don't see a reason why this would be needed, since there should always be an option provided by the operating system/desktop environment to close the window.

@nextcloud/client @nextcloud/designers

**Comment by MorrisJobke** [comment]
> The settings show a close button at the bottom. I don't see a reason why this would be needed, since there should always be an option provided by the operating system/desktop environment to close the window.

I don't have it in the macOS 2.3.3 version 🤔

**Comment by jancborchardt** [comment]
@MorrisJobke you don't have the "Close" button or a window X button?

Agree with @juliushaertl of course :)

**Comment by MorrisJobke** [comment]
I don't have it:

<img width="912" alt="bildschirmfoto 2018-07-16 um 15 37 00" src="https://user-images.githubusercontent.com/245432/42761560-2de98046-890e-11e8-8415-a5a8a6cc84a7.png">

**Comment by ldmpub** [comment]
Hi all,

I have noticed this button removable recently now that I have updated my desktop client and as both an end-user and UX designer I don't agree with the initial statement "there should always be an option provided by the operating system/desktop environment to close the window".

Could you please read my arguments and tell me what do you think?
> Hi,
> 
> I find very confusing to close the client Window by clicking on the upper “Red cross” (under Windows). User don’t know if his click will only Close the window or also Stop the client causing to stop all synchronizations (like in a regular desktop app!).
> 
> Am I the only one to miss a clear “button”, displayed for instance in the bottom right corner. We can call it “Reduce” or “Close” which are non ambiguous(1).
> 
> Waiting for your replies,
> 
> (1) we should not call this new button “Quit” or “Exit”!

Responses can be done here or in my original forum thread (https://help.nextcloud.com/t/why-is-there-no-close-button-is-desktop-client), thanks to share your opinions ;-).

**Comment by florealcab** [comment]
@ldmpub I don't agree. A "Close" button is not less confusing that the X button in the title bar. A lot of applications which are supposed to run in the background (your anti-virus, skype, ...) have also this behavior: you click on the X button of the title bar, but the application does not exits (run in the background).

No need to add a duplicated button :)

**Comment by ldmpub** [comment]
Thanks for your answer.
Does anyone can share is opinion / have other thoughts?

**Comment by ldmpub** [comment]
Hi ( again ;-) ),

I confirm I miss this close button, at least because the "red cross" is too narrow.
Am I really the only one to request a button to close the desktop client?
