### ISSUE TITLE
Windows 10 tried to reboot when installing NC client 2.5.0.0 11.07

### ISSUE THREAD

**Issue by marceljd** [nextcloud/desktop#496]
When installing the new 2.5.0 11.07 Windows 10 client the PC tried to reboot without any warning. NC install blocked the reboot so I could abort. I cannot finish the installer by pushing the button, it does not matter if I add or remove the 'start Nextcloud now' checkbox. 

After rebooting I started the client and provided the credentials, but loggin in does not work. I got the second screen where I could enter the username / password and got stuck on the next one (weiterleiten). I can see a very thin grey line appearing in the upper part of the screen but I cannot scroll up or maximize the screen, I do not know if there is some kind of message there I should reply to.

**Comment by GLLM** [comment]
I have the same issue with the daily builds. I zapp the suggestion to reboot (and do not reboot)  and it works OK afterwards
Still I do not expect this :)
