### ISSUE TITLE
[Bug]: when a case clash during sync occurs, open the browser instead of the file explorer (or provide help to the user)

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#4963]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On some operating systems, it is possible that we cannot sync every file present in the server due to case clash.
For example, `nice image.gif` and `NICE IMAGE.GIF`, will not sync on Windows.
Please improve the management of this conflict such that the user can figure out a solution directly from the desktop client instead of having to separately open a browser, navigate to the proper online folder and figure out a solution.

### Steps to reproduce

1. Upload `nice image.gif` and `NICE IMAGE.GIF` files to folder `Test`
2. Setup desktop client to sync this account with folder `Test`
3. Get an error during sync
4. Open the main dialog
5. Click on the sync error message
6. Gets the file explorer to open and show only one of the conflicting files

### Expected behavior

At step `6` I would expect to be offered ways to solve the issue directly from desktop client (or at least open the browser in the proper folder to solve the conflict manually).

### Which files are affected by this bug

n/a

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

24.0.5

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
related server issue https://github.com/nextcloud/server/issues/34174

**Comment by tobiasKaminsky** [comment]
That sounds like a valid approach.
At step 5 (sync error in activity list) we shall come up with a good explanation:
File cannot be synced because it exists already a file with same name, but different case (?). Clicking on this error message opens up web ui (?) to resolve naming issue.

**Comment by tobiasKaminsky** [comment]
cc @nextcloud/designers  for wording
