### ISSUE TITLE
[Bug] Too small text in tray icon notifications window (Critical)

### ISSUE THREAD

**Issue by unknown-user-account** [nextcloud/desktop#4965]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The text being too small is a security vulnerability in the case of important notifications. Its too small for anyone to read at this resolution/configuration. (Macbook Pro M1 2020 / Windows Server 2022)

The text in the notifications window which appears when you click the Nextcloud system tray icon is too small on my screen. Host: RDP on Windows Server 2022 - stock configuration. Client: Official MS RDP Client from App Store on MacOS Ventura.
...
<img width="581" alt="Screenshot 2022-09-21 at 8 22 01 AM" src="https://user-images.githubusercontent.com/101423993/191502936-cbf69816-ad26-4e14-afbd-19be8186c2cf.png">

### Steps to reproduce

1. Install latest Nextcloud desktop client on Windows Server 2022
2. Configure RDP as normal
3. Install the latest Microsoft RDP client on the latest MacOS  
4. Connect via RDP
5. Click the nextcloud tray icon
6. Observe that the text is too small

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

nextcloud.exe

### Operating system

Windows

### Which version of the operating system you are running.

Windows Server 2022

### Package

Other

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

latest

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
