### ISSUE TITLE
[Bug]: Some files don't get uploaded completely but sync shows as successful

### ISSUE THREAD

**Issue by D34DC3N73R** [nextcloud/desktop#4983]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Some files (typically large files / multi GB) are sometimes not synced entirely. The upload sync is marked as successful, but the file size is dramatically off. 
![image](https://user-images.githubusercontent.com/9123670/192854363-59dcdaba-fc84-4b4d-95c2-1e35185f69dc.png)

![image](https://user-images.githubusercontent.com/9123670/192863290-bb999011-1255-4bb3-aaab-4dc184e711c7.png)

![image](https://user-images.githubusercontent.com/9123670/192855071-731aeaf5-2dad-4d94-8831-78d4a1e9c28d.png)

I would expect some type of file integrity check on file uploads, MD5, checksum etc. Does anything like this happen? How does the client know the file has been uploaded completely?

### Steps to reproduce

I'm not entirely sure how to reproduce this, but it's happened enough times to become a concern.

### Expected behavior

I would expect the desktop clients to verify file integrity with the file uploaded to the server before marking the sync as successful. 

### Which files are affected by this bug

Large files, typically video files (MP4) in my case

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Monterey 12.6

### Package

Distro package manager

### Nextcloud Server version

Nextcloud 24.0.5

### Nextcloud Desktop Client version

3.5.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
client and server logs contain sensitive information. I will DM upon request
```

**Comment by joshtrichards** [comment]
Can you provide the nextcloud.log entries that correspond with transactions associated with one of these problematic files? You provided screenshots of the filename so I presume that part isn't too sensitive. :-)

Without those - which contain the stack traces - or a reliable way to reproduce the issue it's challenging to determine the source of this issue.

Also, I suspect this issue belongs in https://github.com/nextcloud/ios rather than here.

**Comment by CircuitSacul** [comment]
I'm running into this, both with 4gb files (becoming 3.8gb) and smaller ~50mb losing 1-2mb.

I'm using nextcloud AIO. If someone could direct me on how to provide relevant information I would do so.

**Comment by joshtrichards** [comment]
12.9 GiB == ~13.85 GB

Unless you're actually experiencing corruption (i.e. missing file content), this looks to me like just a difference in Gibibyte versus Gigabyte file size reporting.
