### ISSUE TITLE
[Bug]: NextCloud Windows Desktop not compatible with Matrox Graphics multiscreen card

### ISSUE THREAD

**Issue by TxUtc** [nextcloud/desktop#4984]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

NextCloud cannot be launched (background service or foreground) on a Windows 10 PC equipped with Matrox Graphics card.
I tested it for the card Matrox M9140 LP PCIex16, driver version 2.5.0.213 (2/17/2016), card bios version 994-4124, v4.1.4, v2.4.1

The installation process works fine. Just after the reboot, NextCloud background is not launched (whereas autolaunch box was checked during install). Launching manually NextCloud fails to open NextCloud user interface.

### Steps to reproduce

1- Launch Nexcloud on a PC equipped with Matrox Card specified earlier

### Expected behavior

NextCloud should open user interface to ask for the account info for the first launch

### Which files are affected by this bug

not specified

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

3.5.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
No logs generated as NextCloud fails to start.
```

### Additional info

-

**Comment by joshtrichards** [comment]
May have been fixed by #4582 and/or #4821 in v3.6.0.

Are you still able to reproduce this?

**Comment by joshtrichards** [comment]
Closing after >6 months without a response. Presuming fixed.
