### ISSUE TITLE
Windows client keeps crashing

### ISSUE THREAD

**Issue by kwmkjf** [nextcloud/desktop#500]
Hi guys,

I’ve got a problem with a nextcloud client on Windows 10 1607, which wont start. After starting the client the crash reporter pops up. Nextcloud Client version is 2.3.3.1, Nextcloud Server version is 13.0.4.

I could get some logs from the Nextcloud client, but I dont get much Informatioon from it.
[nextcloud.log](https://github.com/nextcloud/desktop/files/2201575/nextcloud.log)

**Comment by morbloe** [comment]
me 2, same with OwnCloud-Client
