### ISSUE TITLE
Introduce URL Handler to give the option to open links localls

### ISSUE THREAD

**Issue by kaystrobach** [nextcloud/desktop#5005]
### Feature description

In order to encourage people to use the internal links feature I want to have an option to open a link from the local filesystem instead of in the web ui.

### Usage flow:

* User A sends User B a link from the desktop containing an internal link
* User B opens it, the browser opens as it is now
* User B klicks on a link / banner / inline alert to send the link to the nextcloud client
* Nextcloud client opens the file locally

### idea for the urlhandler

* `nextcloud://<uri of nextcloudhost>/f/<file uid>`
* It needs to be considered, if the client should verify the call with the nextcloud server to avoid drive by open with a known internal uri, options:
  * notification on the desktop, which asks the user for permission to open the file

### Things to consider

* user security
* ensure only trusted links cause the opening of a file

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by n-bux** [comment]
related thread with same feature requested:
https://help.nextcloud.com/t/nextcloud-desktop-link-to-local-file-in-shared-folder/70164/4

**Comment by claucambra** [comment]
Edit locally has been implemented :)
