### ISSUE TITLE
Context menu 'Nextcloud' not showing up for some folders

### ISSUE THREAD

**Issue by walec51** [nextcloud/desktop#5008]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I have a connected remote folder set up in Nextcloud Desktop. In it there are many subfolders. All of them after right clicking have the "Nextcloud >" option in the popup context menu except one.

More details on: https://help.nextcloud.com/t/context-menu-is-missing-on-some-folders/122448/2

### Steps to reproduce

I don't know how that one folder became different from the other sibling folders.

### Expected behavior

the "Nextcloud >" option in the popup context menu should show up for every folder inside a connected Nextcloud folder

### Which files are affected by this bug

zdjecia

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Are you using Virtual Files?[1] 

Also, you might try this[2] to remove then re-install just the ShellExtensions feature:

```
msiexec /passive /i Nextcloud-x.y.z-x64.msi REMOVE="ShellExtensions"
```

Then reboot for good measure then re-install the shell extensions:

```
msiexec /passive /i Nextcloud-x.y.z-x64.msi ADDDEFAULT="ShellExtensions"
```

[1] Previously some issues for Virtual Files in #3584 
[2] https://docs.nextcloud.com/desktop/3.6/installing.html#features

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.

**Comment by hermeneuticlens** [comment]
I am using Nextcloud client latest 3.14.1 on Windows 11. I followed all your steps and still don't work. Only folders and already locally available files have Nextcloud in the context menu. Online only files do not have Nextcloud in the context menu. The issue has NOT been resolved.
