### ISSUE TITLE
Daily Windows Client not build

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/desktop#502]
Hello Devs!

Sadly the windows client is not beeing visible (& build?) in https://download.nextcloud.com/desktop/daily/

Would be fantastic to have more recent build here to give them a test drive.

Thanks for all ou hard work!

Ralf

**Comment by camilasan** [comment]
Hello

It seems that the last one on July 11 :/ 
Thanks for the heads up!

**Comment by camilasan** [comment]
It is fixed now.
I just built this one to test: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.0-Debug-20180721.exe
