### ISSUE TITLE
Feature request: .gitignore like file for nextcloud

### ISSUE THREAD

**Issue by KomelT** [nextcloud/desktop#5025]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status changes and new comments. 

### Feature description
There should be a way to add a file, let's call it .nextcloudignore, into every folder and Nextcloud should ignore specified files into .nextcloudignore. Basically, desktop client shouldn't upload files selected into that particular file.

**Comment by allexzander** [comment]
Such a feature exists already. You just need to create a `.sync-exclude.lst` file in the corresponding subfolder and add ignored files patterns there.
