### ISSUE TITLE
Larger files never synchronize successfully 

### ISSUE THREAD

**Issue by Ador-able** [nextcloud/desktop#5028]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Slightly larger files never synchronize successfull

### Steps to reproduce

The beginning is always shows that synchronization timeouts。After I tried to add a timeout in nextcloud.cfg configuration items。

`[General]
timeout=60000`。
。After start synchronization.At first can see synchronous speed in interface, it seems that everything is ok。
![屏幕截图 2022-10-11 152027](https://user-images.githubusercontent.com/17660606/195031130-c942c8c5-6c14-402a-989c-882ddcab94e7.png)
But after a while he got stuck。When I turn off the page open again, can't see any information.Cloud synchronization stuck right from here
![屏幕截图 2022-10-11 152208](https://user-images.githubusercontent.com/17660606/195031480-13b4e679-85a1-4864-a3fe-516edf3e1101.png)

This is a log。[20221011_1517_owncloud.log](https://github.com/nextcloud/desktop/files/9752791/20221011_1517_owncloud.log)

### Expected behavior

File the correct sync success

### Which files are affected by this bug

Slightly larger files 

### Operating system

Windows

### Which version of the operating system you are running.

windows 11

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Are you still experiencing this?
If so, are you able to upload large files via the Web UI successfully?
