### ISSUE TITLE
[Bug]: MacOS10.13.6 (High Sierra) desktop client compatible w latest servers not available for download

### ISSUE THREAD

**Issue by dg1sek** [nextcloud/desktop#5029]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
I am running nextcloud server version 24.0.5 (from hub.docker.com image).

One of my machines is a 2011 iMac 27" with Intel i7. This machine is no longer eligible for MacOS updates by Apple and therefore is running an old version of MacOS, 10.13.6. (NB: There seems to be no compatible Xcode from Apple available for download and I cannot compile Nextcloud on this machine on my own.)

The latest version of the desktop client on Nextcloud official download site https://nextcloud.com/install/ 
under MacOS-Legacy (10.10) points to https://github.com/nextcloud/desktop/releases/download/v2.6.5/Nextcloud-2.6.5.20200710-legacy.pkg - The other versions provided on the official download page are not compatible with MacOS10.13. 

However, this rather old version seems to be incompatible with my server version: The synchronisation fails, i.e. the client crashes without indicating any error message. It seems that this hasn't been working for quite a while, probably already with previous server versions, I just had not noticed it until now. 

Would it be possible to provide a more recent binary of the desktop client on the official download site than this old 2.6.5?

### Steps to reproduce

Start nextcloud client on old iMac, tries to synchronise but then exits without any warning.

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
Should synchronize. 

### Which files are affected by this bug

https://github.com/nextcloud/desktop/releases/download/v2.6.5/Nextcloud-2.6.5.20200710-legacy.pkg

### Operating system

Mac OS

### Which version of the operating system you are running.

10.136

### Package

Appimage

### Nextcloud Server version

24.0.5

### Nextcloud Desktop Client version

2.6.5

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @dg1sek, you can find a list of releases at https://github.com/nextcloud/desktop/releases

**Comment by claucambra** [comment]
A bit more detail: versions of the client pre-3.5 should still work fine on macOS 10.13
