### ISSUE TITLE
[Bug]: High CPU Usage while syncing

### ISSUE THREAD

**Issue by hammer065** [nextcloud/desktop#5038]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

While syncing files, Nextcloud Desktop has 100% CPU usage and sync-speed is very slow (3 files about every 30 seconds).
However the server is not the limiting factor.
Using `dtruss`, we can observe that it spams the same `madvise()` syscalls inbetween file operations.

### Steps to reproduce

1. Have Nextcloud Desktop running and online
2. Start _any_ (mass) file operations (upload, move, delete)
3. Notice that while the sync is running, Nextcloud Desktop has 100% CPU usage

### Expected behavior

The file sync should be much faster and Nextcloud Desktop should not spam this many `madvise()` syscalls.

### Which files are affected by this bug

---

### Operating system

Mac OS

### Which version of the operating system you are running.

12.6

### Package

Distro package manager

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.5.3git (build 11144)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Here is an excerpt of the syscall log:
```
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD39C949000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD3920AA000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD39C949000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD3920AA000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD39C949000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD3920AA000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD39C949000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD3920AA000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD39C949000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD3920AA000, 0x20000, 0x9)		 = 0 0
madvise(0x7FD36E163000, 0x10000, 0x9)		 = 0 0
madvise(0x7FD36E218000, 0x20000, 0x9)		 = 0 0
[...]
```

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
