### ISSUE TITLE
[Bug]: missing share action from context menu in Nautilus 43

### ISSUE THREAD

**Issue by paolostivanin** [nextcloud/desktop#5041]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello,
after the update to GNOME 43, the "Share" action is missing from Nautilus' context menu (right click).

```
$ nautilus
Initializing Nextcloud-client-nautilus extension
Using python version sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)
TypeError: MenuExtension_ownCloud.get_file_items() missing 1 required positional argument: 'files'
** Message: 13:45:11.899: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: usershares are currently disabled

TypeError: MenuExtension_ownCloud.get_file_items() missing 1 required positional argument: 'files'
```

### Steps to reproduce

1. install openSUSE Tumbleweed (GNOME)
2. install nextcloud-desktop
3. try to share a file by right-clicking on it

### Expected behavior

There should be a "share" action

### Which version of the operating system you are running.

openSUSE Tumbleweed

### Package

Distro package manager

### Nextcloud Desktop Client version

3.6.0

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by palto42** [comment]
I'm using Solus and after update to Gnome 43 the whole Nextcloud context menu in Nautilus is missing.
@paolostivanin is only the "share" option missing in your case but the NC context menu still present?

**Comment by paolostivanin** [comment]
Yes, you're right, I wasn't very clear. The whole Nextcloud ctx menu is missing.

**Comment by palto42** [comment]
To me it seems that this is actually an issue in the Python package [nautilus-terminal](https://github.com/flozz/nautilus-terminal). There is a relates issue [#82](https://github.com/flozz/nautilus-terminal/issues/82) for this package already.

**Comment by EbonJaeger** [comment]
It is not caused by nautilus-terminal, it just has its own error in the same output. 

In the output given above, the Nextcloud extension is hitting its own error with some API function call. It's also possible that this exrension will hit the same error as the ither extension since Nautilus extensions must use GTK4 as of version 43. It's not clear to me what version this one is using.

**Comment by paolostivanin** [comment]
Exactly. The issue here is:

```
TypeError: MenuExtension_ownCloud.get_file_items() missing 1 required positional argument: 'files'
```

so nautilus-terminal is not part of the problem at all.

**Comment by paolostivanin** [comment]
The problem can be easily fixed by removing `window` from the `get_file_items` method (https://github.com/nextcloud/desktop/blob/8ccb563444127022115fb4e5fb4ac76f0392dd2d/shell_integration/nautilus/syncstate.py#L203)

I tried on my machine and everything works fine.

**Comment by paolostivanin** [comment]
I've opened a PR to fix this issue. If you are using openSUSE Tumbleweed, you should get an update with the fix in a couple of days :smile:

**Comment by palto42** [comment]
> It is not caused by nautilus-terminal, it just has its own error in the same output.

Sorry, was a bit confused by the multiple error messages.

**Comment by palto42** [comment]
> I've opened a PR to fix this issue. If you are using openSUSE Tumbleweed, you should get an update with the fix in a couple of days smile

@paolostivanin  I tried the patch on Solus and it works :)
Regarding your PR I wonder if there should be another one for the current [stable-3.6](https://github.com/nextcloud/desktop/tree/stable-3.6) branch to get it quickly rolled out? Your current PR for the master branch shows some build issues which I assume are just caused by other commits in the master branch not related to this issue/patch.

**Comment by paolostivanin** [comment]
Yes, those tests are failing for unrelated reasons.
I've opened a PR for the stable branch too: https://github.com/nextcloud/desktop/pull/5085

**Comment by paolostivanin** [comment]
There's already a PR open: https://github.com/nextcloud/desktop/pull/4870
