### ISSUE TITLE
Finder extension vs macOS service architecture

### ISSUE THREAD

**Issue by tessus** [nextcloud/desktop#505]
While I do understand that the finder extension is necessary for the overlay icons, the problem is that it only works in Finder. People who are using Path Finder, ForkLift, or any other file manager are left in the dark. And let’s be honest, Finder is one of the worst designed apps on macOS.

I’d like to start a discussion about also providing the actions `Share...`, `Copy private link to clipboard`, and `Send private link by email` as a service. Using the service achitecture these actions would be available to all applications on macOS.

I’m not saying to scrap the finder extension, but merely to add the services as well. The code for these actions already exists, thus making them available as a service should not be very complicated but will increase usability and productivity.

(I've opened a [topic on the forum](https://help.nextcloud.com/t/finder-extension-vs-macos-service-architecture/33977), but haven't received a single comment or reply.)

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently, there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

However, feel free to work on this yourself and provide a pull request for it.
