### ISSUE TITLE
Unexpected local file deletion

### ISSUE THREAD

**Issue by samtygier** [nextcloud/desktop#506]
I have recently started using nextcloud with a large folder on my laptop (approx 80GB, 1 million files), using the linux desktop client nextcloud-client-2.3.3-2.fc28.x86_64. Server is run nextcloud from the snap package stable: 13.0.4snap1.

I noticed a lot of locking errors, nextcloud/server/issues/8239 as files were syncing, however most files did get sync'ed across to the server. I assumed that it would just take a few passes for everything to get sync'd across.

Today I noticed that the desktop client is also deleting files from the local folder. These are files that I have not deleted anywhere. The only other client connected to the account is an android, so it does no syncing. My suspicion is that for the files that where not sync'd due to the locking, the client is now assuming that as they don't exist on the server they need to be removed locally.

**Comment by samtygier** [comment]
Here are a few lines from the .owncloudsync.log file. (I have x'ed out the paths)
[client_folder.log](https://github.com/nextcloud/desktop/files/2226979/client_folder.log)

**Comment by g6094199** [comment]
+1 

I'm seeing the same behavior here. Until now i thought i was the server installation that "looses" the files. I searched for hours but didnt find a problem.
Anyway i see the same upload problems with my NC client (Version 2.3.3). I'm syncing from work (Ubuntu 18.04, NCC Version 2.3.3) to an Android Client (on Lineage) and/or my home (also Ubuntu 18.04, NCC Version 2.3.3).
 On any Ubuntu box are sync problems when i try to upload folders with some files in it (mostly pics). the folders are about 100MB in size. I fact i lost several folders with pics, wihch i could restore from the servers snapshots.

**Comment by skewty** [comment]
I too am having this issue and what seems to be the opposite too.  

After my linux client says it is all synced up, if I delete the local folder, and a sync error / system restart causes the client to restart, the folder I deleted (and its contents) sometimes comes back.

**Comment by rvalle** [comment]
I believe I am also having this issue.

I am new to NextCloud, so as a test, I decede to move my development tree to NextCloud and continue workig as usual. I thought of it as kind of a robustness test. IDEs, compilation, etc.

I am noticing that my files go missing. entire contents of directories go missing. I kind of have the feeling that it is related to IDEs being used on that folder. Perhaps to do with concurrent access to files, or locks or something similar.

I also noticed that files disappear on the client, but they are still on nextcloud, and the drive is reported in green as if the content was synchronized, which is not true.

I will have to revert my test, and move my development tree out of nextcloud for the time being, unless you want me to make any test before.

**Comment by rullzer** [comment]
Could you check if this still happens with rc2?

**Comment by rvalle** [comment]
@rullzer OK, I have installed RC2
Will use it during next week.
Actually I rolled back my test because the number of broken folders was just too many. I also noticed that the client I had installed was the provided with Fedora 28, which I believe is version 2.2

I have now installed the 2.5 RC2, will test during the next week and let you know.

**Comment by rwat1** [comment]
I HAVE THE SAME PROBLEM, OMG I NEED TO REDOWNLOAD 500GB over my terrible internet connection. This is horrendous, how can this be happening? Is this a Beta release, why did I upgrade?

**Comment by rvalle** [comment]
@rwat1 My problem was away after using the latest client (using AppImage) which one are you using?

**Comment by rvalle** [comment]
@rwat1 you are welcome.

I guess the issue here is that nextcloud must ensure repos are updated and the client can auto update or at least issue a warning...
