### ISSUE TITLE
[Bug]: Shared folders are duplicates self if i sahre sub folder of shared folder

### ISSUE THREAD

**Issue by efeArdaYildirim** [nextcloud/desktop#5069]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

If i share folder a folder then if i share sub folder. It look folder and sub folder. I don't wanna see both i wanna see root of shared folder in my root.

### Steps to reproduce

1. create folder
2. create sub folder
3. share main folder
4. share sub folder
5. I don't wanna see sub folder again in my root

### Expected behavior

when share my sub folder

### Which files are affected by this bug

all folders and files

### Operating system

Linux

### Which version of the operating system you are running.

docker

### Package

Other

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
