### ISSUE TITLE
Prevent high request load after notify_push notification

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/desktop#5072]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
This is the client side counterpart of issue https://github.com/nextcloud/notify_push/issues/192 .

I'd like to focus on a particularly nasty side-effect of the reaction to a notification, when there are many clients (>20) and big folders in sync:

1. A client updates a file / folder;
2. A push notification is sent to all connected NC clients;
3. Immediately after, all clients issue a number of PROPFIND requests to get more info and decide what to do;
4. The server load easily spikes to 80-95% of all available cores;
5. Just a few seconds after the first push, another user changes a different file/folder;
6. go to number 2.

The above is going to pile up easily and use up all the available cores when many users are working on a big share.
As a result of that, on a user perspective the clients tend to stay in "synchronizing" state for most of the time and appear very slowly responsive, even if only few small changes really happened in the shares. 

A solution to highly mitigate the above side effects would be to:

- Add more information to the push notification message so that the clients don't always need to ask back additional info (https://github.com/nextcloud/notify_push/issues/192)
- Change the NC client push notification code to make use of the additional info and avoid issuing a bunch of requests (this issue)

Hope this helps, thanks!

**Comment by jospoortvliet** [comment]
We added some batching to the notify-push feature. Is this resolved now or still relevant?

**Comment by roberix** [comment]
Hi. 

Maybe a bit off topic but is the HPB in NC25+ still a thing? Since NC21 there are not much information about this. Is there still major performance gains. 

@jospoortvliet would u know this maybe?

thanks

rob

**Comment by jospoortvliet** [comment]
Hi Roberix, absolutely - nothing has much changed in this regard. I don't think a ton more features have moved in, but it's still used and, for example, our All-in-one Docker image uses it.

I'll now close it, as I guess this is resolved.
