### ISSUE TITLE
[Bug]: Folders show up as synched if PROPFIND-request ended with an OutOfMemory-error

### ISSUE THREAD

**Issue by kimmerin** [nextcloud/desktop#5073]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I've got a couple of OutOfMemory-erorrs like the ones that are already described in https://github.com/nextcloud/server/issues/33032. When I addressed this my client showed me that all synched folders are completely synchronized (green arrow). After increasing the allowed memory-size, one of the folders showed 10,000 missing files and is uploading them, since.

### Steps to reproduce

1. Create a folder with a massive number of files
2. Add this folder to the list of synchronized folders of your client
3. Wait for the synchronization to reach ca. 90%
4. Restart the synchronization (in order to force the client to do a PROPFIND-request on a folder with many entries)
5. Make sure the request ended with an OOM on the server side to see the effect

### Expected behavior

The client should be aware that there was an error instead of assuming everything is OK or at least don't give the impression that the folder is completely synchronized.

### Which files are affected by this bug

apps/dav/lib/Connector/Sabre/PropfindCompressionPlugin.php

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
From the Apache error.log (the nextcloud.log doesn't show anything on that during that time:

[Wed Oct 19 14:43:50.682163 2022] [php:error] [pid 31466] [client 192.168.1.40:50032] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 15386088 bytes) in /var/www/nextcloud/apps/dav/lib/Connector/Sabre/PropfindCompressionPlugin.php on line 68
```

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
