### ISSUE TITLE
[Bug]: Desktop Clients shows private messages even when user is logged out

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/desktop#5078]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This affects NC 24 24.06 in combination with Windows Client 3.6 on Windows 10.

Very often when I was not away from my PC and it went to sleep mode it happens that I start it and while still seeing the windows login screen I get a pop up in the lower right corner from the nextcloud desktop client showing a message that I got on talk.

Event this is not super critical, I still think it is a NoGo that someone else could possibly see a private message that was sent to me without beeing logged in on my windows machine.

### Steps to reproduce

Not 100% sure how to reproduce it. I guess it will be more or less like this:

1) set windows pc to sleep mode.
2) recieve a talk message.
3) wake up windows pc.

### Expected behavior

Nextcloud Desktop Client should not present any popups, when the user is not logged into his windows account.

### Which files are affected by this bug

i dont know

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
This isn't a Desktop client issue, but a configuration one on your computer. Go into your Notifications settings in Windows and turn them off for your Lock screen or customize them however you prefer.
