### ISSUE TITLE
[Bug]: Client doesn't start on Ubuntu 22.10: Memory Access Error

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/desktop#5079]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I updated Ubuntu to 22.10 yesterday. Today Nextcloud client won't start. It pops up shortly in the tray and then disappears.

When I start it in the terminal this happens:

user@computer:~$ nextcloud 

Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

Speicherzugriffsfehler (Speicherabzug geschrieben)

user@computer:~$

### Steps to reproduce

1. Press Windows-Key
2. Type Nextcloud
3. Enter
4. Client starts and crashes

### Expected behavior

It should work normally

### Which files are affected by this bug

All

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.10

### Package

Distro package manager

### Nextcloud Server version

24.0.6.

### Nextcloud Desktop Client version

3.6.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Can you reproduce this using the AppImage (our official release artifact)? If not, may be a packaging issue downstream like #3090 was.

**Comment by kaffeeringe** [comment]
No AppImage works now.

**Comment by joshtrichards** [comment]
Cool. If you wish to stick with distro packages, the PPA may be an option for keeping an up-to-date client.

**Comment by kaffeeringe** [comment]
Thank you for the tip!Am 27.11.23, 15:35 schrieb Josh Richards ***@***.***>:

   
  Cool. If you wish to stick with distro packages, the PPA may be an option for keeping an up-to-date client.
