### ISSUE TITLE
[Bug]: Deleted virtual files instantly reappear

### ISSUE THREAD

**Issue by wonx** [nextcloud/desktop#5082]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When deleting virtual files (files ending in .nextcloud), they reappear a few seconds later. The only way to delete them is to download them to the local storage, and then deleting them.

### Steps to reproduce

1. Enter a folder with virtual files (.nextcloud)
2. Delete them.

### Expected behavior

The files should remain deleted and sync with the server.

### Which files are affected by this bug

All virtual files

### Operating system

Linux

### Which version of the operating system you are running.

Kubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

24.0.2

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by marcotrevisan** [comment]
Same as #4474

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
