### ISSUE TITLE
Replace invalid characters in file name when syncing

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#5095]
It would be nice if the desktop client could replace file names impossible to sync on Windows and other platforms with substitution characters to make it possible to sync all files.
We could extend the current internal sync database to keep track of those substitutions in file names to ensure we can track changes and keep syncing flawlessly.
It is crucial that the user is aware of it and we may need to get user feedback in case the desktop client would need to sync file name changes for files with invalid characters (having been substituted).
We may also want to add a convenient way to get an overview of all files with substituted characters in their names and offer mass renaming feature).

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by Githopp192** [comment]
yes, a very old - but very important bug to be fixed.
Why ? all about DATA CONSISTENCY !

https://github.com/nextcloud/desktop/issues/3152

**Comment by tobiasKaminsky** [comment]
We will go with https://github.com/nextcloud/desktop/issues/5099, which is a manual conflict resolution.
