### ISSUE TITLE
[Bug]: Nested shares can lead to unintended file deletion

### ISSUE THREAD

**Issue by hendrikvomlehn** [nextcloud/desktop#5108]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Renaming or moving folders within a nested share structure can lead to unintended file deletion by the sync client.

By nested share structure, I mean a situation where a folder is shared with a specific user and a subfolder of that folder is shared with the same user as well. This leads to a situation, where that user can reach the files of that subfolder by two different paths in his file tree. This overall situation might be confusing, as recently reported in bug #5069, but adheres to a certain logic and seems intentional to me.

What seems unintentional though, is that changes within the shared subfolder can lead to file deletion by the sync client of other users.

According to my observations this can happen in two ways:

1. a folder within a share is moved into a shared subfolder of that share
2. a folder within a shared subfolder is renamed

I could reproduce situation 1 systematically. For situation 2, the timing of the sync clients seems relevant. I could reproduce this several times, but not systematically.

At least for situation 1, one sync client that is involved seems enough. Moving a folder within the browser interface of user A and sync client of user B running, was enough to have the sync client of user B triggering the file deletion.

I tested this with the recent sync client on MS Windows, both with virtual file system and classic file sync. It happened with virtual files and classic sync.

### Steps to reproduce

Scenario 1:

- Create the following directory structure: Shared Folder; Shared Folder/Sub1; Shared Folder/Sub2; Shared Folder/Sub2/extra dir; some files in Shared Folder/Sub2/extra dir/
- Share the Shared Folder with user X; additionally share Shared Folder/Sub1 with user X
- Have user X run the sync client
- Move extra dir from Sub2 to Sub1
- Sync client of user X deletes the files within extra dir (with the files being moved to trash)

Scenario 2:

- Create the following directory structure: Shared Folder; Shared Folder/sub dir; Shared Folder/sub dir/extra dir; some files in Shared Folder/sub dir/extra dir/
- Share the Shared Folder with user X; additionally share Shared Folder/sub dir with user X
- Share the Shared Folder with user Y
- Have user X and Y run the sync client
- Rename extra dir to something else, but leave it within sub dir
- Occasionally, the sync client of one user deletes the files within extra dir (with the files being moved to trash)

### Expected behavior

folder extra dir should be moved/renamed within all shares, that it occurs in; files should not be deleted

### Which files are affected by this bug

files within extra dir

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

24.0.4

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue.

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
