### ISSUE TITLE
NC server 14.0.0 Beta 1 Build:2018-07-26 crashes Desktop Client 2.5.0daily (build 20180726, MacOS)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/desktop#511]
I just upgraded my NC test instance to the latest 14 beta version and noticed that the Desktop client (2.5.0daily (build 20180726), macOS) immediately crashed.

As soon as the test instance was removed from the client config, the client sync’d nicely towards the production NC 13 instance.

Can anyone confirm?

**Comment by ho1ger** [comment]
Any news on this? I just got the latest version of the client and connected it to the 14 beta server. After entering the e2ee nmemonic, the client crashed again.

**Comment by camilasan** [comment]
The news on it is that we are having problems with the build machine but we already know what the crash is and it is fixed if you directly compile from master. So as soon as we fix the building machine the new builds will work.

**Comment by ho1ger** [comment]
Good to hear! Thanks.

**Comment by doits** [comment]
@camilasan hitting this, too – any timeline when new mac os builds show up?

**Comment by camilasan** [comment]
Sorry for this, but we should have new builds beginning of next week.

**Comment by ho1ger** [comment]
hmmmm, ... yesterday I updated to the version "Built from Git revision 5ce9ae on Oct 18 2018, 02:03:16 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017" and I experience the exact same behavior as before?

@doits: did one of the latest update fix the problem for you?
