### ISSUE TITLE
[Bug]: Fulltext search results are not clicable

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/desktop#5113]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The fulltext search output results are not clickable from the NC desktop client for Windows. The other search items remain clickable.

### Steps to reproduce

1. Check that fulltextsearch is enabled in NC server.
2. Open NC desktop client
3. Type something in the universal search field
4. Observe output results.
5. Try to click on any item under the Fulltext Search category.
6. Observe that nothing happens.
7. Try to click on any item under other category and observe that documents are opening.

### Expected behavior

The clicked item under full text search should lead to opening a window in the default browser with the document according to the results of the search.

### Which files are affected by this bug

fulltext search

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ostasevych** [comment]
![image](https://user-images.githubusercontent.com/5199030/198840881-58ea70dc-3a5a-4b5f-8cc6-7d4984789e6a.png)

**Comment by arnowelzel** [comment]
I can confirm this - happens here as well.
