### ISSUE TITLE
[Bug]: UI freezes when setting user status with multiple accounts on macOS 12.6

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#5119]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The UI freezes when I try to set my user status.

<img width="465" alt="Bildschirmfoto 2022-10-31 um 22 06 58" src="https://user-images.githubusercontent.com/2069590/199110765-2b9dabcf-babd-4234-8168-5fdda6d72c8e.png">

### Steps to reproduce

1. Click on the menu item and the UI will drop down.
2. Select account and select "set user status"
3. Click on "online"
4. UI freezes

### Expected behavior

Select user status and menu will disappear like normal.
Client will continue to interact like normal

### Which files are affected by this bug

The UI is affected and I need to kill the process

### Operating system

Mac OS

### Which version of the operating system you are running.

12.6

### Package

Other

### Nextcloud Server version

25.0.0

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
The server log does not show any related entries.
```

**Comment by jonasgarstick** [comment]
We notice the same behaviour with client 3.6.1 and only one account. It's reproducible on multiple devices.

**Comment by mgallien** [comment]
> Still an issue with v3.6.2 and NC v25.0.1 @mgallien any idea? Best regards to you.

would it be possible for you to reproduce the bug and then send us a debug archive ?
I can create an upload share if you want to privately share it ?
best regards to you @rakekniven

**Comment by mgallien** [comment]
> We notice the same behaviour with client 3.6.1 and only one account. It's reproducible on multiple devices.

@jonasgarstick same question for you, the best would be if you could reproduce the bug and then generates a debug archive ?
same offer for a way to share it privately if you have private data in the logs

**Comment by mgallien** [comment]
@jonasgarstick @rakekniven thanks for reporting
I can indeed reproduce it. I do not need any logs from you. The reproduction steps were enough.

**Comment by claucambra** [comment]
Okay, this should now be fixed with https://github.com/nextcloud/desktop/pull/5213 -- we had fixed this and not backported to the 3.6.x series. Should be included in 3.6.3 :)

**Comment by claucambra** [comment]
> Ok, would be nice to have such fixes backported to latest stable all the time.
> Thanks for the update and for the fix.

This is usually the case, this particular PR also contained cosmetic changes -- we usually reserve those for full releases, hence this not being backported when it contained the fix

**Comment by drankinatty** [comment]
I have experienced this same issue with 27.0.2. Login from one computer. Then login from another computer. Change status. Attempting to logout from 1st computer fails and session hangs and displays the logo with `Error` in the middle of it. On browser restart, will succeed and status shown in dashboard sees status update, but status over icon in menu remains unchanged.
