### ISSUE TITLE
[Bug]:  Group Folders App is auto-disabled during upgrade and causes data loss

### ISSUE THREAD

**Issue by sonaro** [nextcloud/desktop#5120]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

During a major version upgrade, the Group Folders server app was disabled for an unknown reason (needed an update?). While this app was disabled, and after Maintenance mode was turned off, any clients that had access to those group folders and that auto re-sync'd DELETED the client side group folders to match their new nextcloud server permissions since the GF app was disabled.

This is a major issue, for three primary reasons:
- all of the group folders on the client, including any new unsync'd data saved to the client group folders before the next sync action were DELETED permanently and could not be recovered (unless the client had a local, separate backup running concurrently with nextcloud that also includes the Nextcloud local folder/group folders)
- server-side backups were not able to recover lost data for any data that was not fully uploaded yet
--- for instance, if files are written after maintenance started, or if quota was temporarily exceeded
- wasted resources in having to re-download all of the content in the server group folders once the group folders issue was resolved

Associated Server Bug Report:
https://github.com/nextcloud/server/issues/34900

### Steps to reproduce

**NC Client:** 3.3.6 on OSX 12.4 (21F79)
**NC Server:** 20.0.13, upgraded to 24.0.6.1 (Not sure when Group Folder app was disabled, but have all logs)

1.  Turn on Maintenance Mode
2.  Save a new test file to a group folder on a client filesystem that will be sync'd
3.  Successfully update from a previous major release
4.  Turn off Maintenance Mode
5.  Check status of Group Folders App. If it says "Disabled", no action is needed
  -- if Group Folders was not automatically disabled by the server, then click Disable
7.  Wait for the client that no longer has access to the group folders to sync and it will delete the group folders, the group folder sync'd data, and and the unsync'd test file

### Expected behavior

The expected behavior is to have the client side app "unmanage" the group folder and allow the entire folder to persist, rather than delete it, or prompt for further action.  Example:  Show group folder in red in client, but keep the data, unless a remote wipe is performed.  

Or:
- "unmanage" only delete content that was uploaded to the group folder.  Leave the data that was never uploaded yet (only existing copy on the client side).
- prevent new write access to the group folder, upload any pending data before the Group Folder is removed, upload, and then remove the group folder.
- move the un-uploaded data to a different folder that the person can manually merge later on (not advised since client software may be saving to that location automatically)
- at a minimum, immediate action could be to add a data loss warning any time a main folder/Group Folder disappears, or a certain quantity/size of files is deleted.

These are suggestions, and I expect we can discuss best practices that cover all Group Folder data loss circumstances as we investigate.  Assumptions:   The cost of losing data and re-downloading is higher than the cost to store extra data.  Some of these solutions are imperfect since they may create other risks (storing stale data, using more space than needed, etc).

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

12.4 (21F79)

### Package

Appimage

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.3.6. (yes, not the latest but when the issue occurred)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Logs are huge and also contain sensitive data.  Please ask and I can provide relevant sections.
```

### Additional info

These events happened in the past 24hrs.  If there is any way to restore unsync'd deleted Group Folder data on a client, that would be much appreciated.

**Comment by sonaro** [comment]
@camilasan 100% agree with using newer versions of the client, and try to keep systems up to date.  Unfortunately, this particular machine used an older version when the data loss occurred.  I can try to test with the newer version of the client and see if the issue still occurs.  I reported this bug specifically because of the possibility of client-side data loss that backups likely may not cover, and so we could at least isolate where this issue could occur and add warnings to the release notes of older versions, and of course fix future versions too.

**Comment by MrXermon** [comment]
Seems like the same issue happened on my end. Lost a bunch of files which I needed to restore from the backup.

**Comment by sonaro** [comment]
Also, this issue should not be marked as completed unless a known fix has
been implemented.
