### ISSUE TITLE
[Bug]: Crash on startup ( Mac OS X 10.15.7)

### ISSUE THREAD

**Issue by setar** [nextcloud/desktop#5122]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After update from v.3.1.* 
Application Crash every time.
Crash log:
```
Process:               Nextcloud [1835]
Path:                  /Applications/Nextcloud.app/Contents/MacOS/Nextcloud
Identifier:            com.nextcloud.desktopclient
Version:               3.6.1git [build 11939] (3.6.1.11939)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Nextcloud [1835]
User ID:               501

Date/Time:             2022-11-02 13:14:03.103 +0300
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        BE52039B-609B-D87E-5957-DE09BC69A40D


Time Awake Since Boot: 780 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'SUNoFeedURL', reason: 'You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!'
abort() called
terminating with uncaught exception of type NSException

```

### Steps to reproduce

1. just run app

### Expected behavior

i wait stable work ...

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

Mac OS X 10.15.7 (19H2026)

### Package

Distro package manager

### Nextcloud Server version

20.0.14

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

currrent Lagacy Nextcloud-2.6.5.20200710-legacy.pkg  and package from https://nextcloud.com/install/#install-clients
also doing crash
[Nextcloud_2022-11-02-131403_MacBook-Pro-Sergej.crash.zip](https://github.com/nextcloud/desktop/files/9919478/Nextcloud_2022-11-02-131403_MacBook-Pro-Sergej.crash.zip)

**Comment by claucambra** [comment]
Could you try fully removing the desktop client from your system and doing a clean install?

**Comment by setar** [comment]
Remove and Clean install the app give me too same, but i do complety remove ```~/Library/ApplicationSupport/Nextcloud``` and full re-sync my accounts:
and now the work fine !
Thanks.
