### ISSUE TITLE
Enhancement: prefill credentials for web session

### ISSUE THREAD

**Issue by g6094199** [nextcloud/desktop#513]
Hi Guys,

just a small enhancement that bugs me from time to time.

When using the desktop client an clicking on the link for opening the NC web session:

![grafik](https://user-images.githubusercontent.com/37833326/43286568-b83b5c4e-9122-11e8-9239-1752cb6839df.png)

The websession opens but asks for cedentials. Why is this? Is this for security? in dont think it enhances secutiy, the NCC already knows all credentials for the user already so  it would be better, from a user experience few, to automatically log in the user in the websession when he opens it from withing the nexcloud desktop client??!

regards 
sash

**Comment by bpcurse** [comment]
@g6094199 I would agree at first but rethinking this, there is a potential security flaw depending on the use case.

If you log in via browser you have a lot more to access (apps, settings, probably system settings and user management if the user is an admin). Using the client you "only" have access to files (at the current development stage).

I guess that in a private setup where only you have access to the client machine this is not an issue and I would like to see this feature, too :) In a multi user (corporate) setup this might be different.

**Comment by g6094199** [comment]
> I guess that in a private setup where only you have access to the client machine this is not an issue and I would like to see this feature, too :) In a multi user (corporate) setup this might be different.

How can a corporate environment be different? Every user has an personal computer account, so access to other users NC credentials is not possible and forbidden from the companies side. In an case users do share Computer accounts (Internet Cafe? Guest accounts?) you **shouldnt** save **any** credentials in that profile anyway. It doesnt matter if its NC or accounts used in the browser, etc. 

So i see no problem here imho.

Sash

**Comment by camilasan** [comment]
With the new login flow (I think 2.6.x) you should be logged in the browser already. Besides... I don't think this is a problem and it should depend on how you configure your browser (to save or not login data).
