### ISSUE TITLE
[Bug]: (VFS) - Read-only attribute of a previously Locked file is not synchronized in the first time the file is opened on the desktop client

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#5130]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When a shared file is already locked by a user in Nextcloud and another user wants to open the same file for the first time, nextcloud synchronizes the locked file without the read-only attribute and allows the second user to edit the already-locked file

### Steps to reproduce

Scenario: 
- 2 Users: **UserA** and **UserB** have access to **FileA**
- Both users are using nextcloud desktop sync app.
- Temporary files lock application is enabled on the server

1.
**UserA** has **FileA** already synchronized on its computer
**UserB** does not have  **FileA** synchronized 

2.
**UserA** locks **FileA** and starts to editing it

3.
**UserB** opens **FileA** for editing

At this moment, **FileA** is synchronized for **UserB**, however, the Read-only attribute is not set on the file, allowing **UserB** to edit the file.

### Expected behavior

**FileA** should be synchronized for **UserB** with the Read-only attribute set, so that the file would not be edited by both users

### Which files are affected by this bug

Any file accessible by more than one user

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Distro package manager

### Nextcloud Server version

24.0.5

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Mika-6-9** [comment]
Hello.
I think it's closed with https://github.com/nextcloud/desktop/pull/5841
