### ISSUE TITLE
Allow to set default browser

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#5135]
As wished by Frank in our planning meeting:
- currently always default browser is used, when clicking on login, join call, etc.
- some/many apps allow to se their own default browser, which is not necessary the system wide one

ToDo
- add in settings a switcher to change browser
- default is system wide one (e.g. Safari on Mac)
- check if it is possible to retrieve this automatically
- show it only if there is more than one browser, if possible

Screenshot from KDE:
![image](https://user-images.githubusercontent.com/5836855/200251763-0bfc5d14-52a0-4390-a485-7a15825af03b.png)

**Comment by claucambra** [comment]
Sorry for butting in, but, I have trouble understanding -- what is the intended use-case for this? Why would a user want to use a browser other than the default browser to open things in Nextcloud? 

I also struggle to think of any desktop apps that let you select a default browser independently of the system default, are there any relevant examples?

**Comment by allexzander** [comment]
Right now we use Qt's `QDesktopServices::openUrl` method. I am not even sure it is possible/achievable via the standard way on Windows at least. I also don't have a reference to other desktop app that supports this.

**Comment by tobiasKaminsky** [comment]
Frank's use case is:
- default is safari on mac
- talk does not work with safari in a good way, so Firefox is used
- clicking on an incoming call in Desktop opens it in safari

Can you check how long this roughly would take, then I can re-ask, if we still shall do it.

**Comment by claucambra** [comment]
> Frank's use case is:
> 
> * default is safari on mac
> * talk does not work with safari in a good way, so Firefox is used
> * clicking on an incoming call in Desktop opens it in safari
> 
> Can you check how long this roughly would take, then I can re-ask, if we still shall do it.

Isn't this something that should be fixed in Talk? That would make more sense than implementing a questionable workaround in the desktop client for a very questionable use-case

For macOS specifically, this is not even possible without using a deprecated and unsupported API, so, it would not address Frank's issue

**Comment by claucambra** [comment]
> Frank's use case is:
> 
> * default is safari on mac
> * talk does not work with safari in a good way, so Firefox is used
> * clicking on an incoming call in Desktop opens it in safari

For macOS specifically, this is not even doable in a sensible way without using a deprecated API (and these deprecated APIs would only tell us which apps *can* open web URLs, not select/use them to open said URLs, this we would need to implement ourselves)

At best we can implement a tricky way to switch the system default browser, but not sure what the utility of this would be

Does it make sense to implement this workaround in the client over fixing the issue in Talk?

**Comment by tobiasKaminsky** [comment]
@karlitschek I think you mentioned a program on MacOS, that already can handle this.
Can you point us to it?

**Comment by claucambra** [comment]
Would @karlitschek be okay with using something like https://choosy.app ?

**Comment by karlitschek** [comment]
@claucambra Of course this would be ok :-) Whatever you recommend

**Comment by tobiasKaminsky** [comment]
Nice, then let us close it. :clap: @claucambra for finding this nice, more general approach!

**Comment by nazarewk** [comment]
I am actually getting login pages opened in Brave browser even though I have Firefox I default on my NixOS machine. It is annoying as I normally don't use it for anything except a single web page.
