### ISSUE TITLE
"App password" link seems to be obsolete since NC13

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/desktop#514]
#### Issue description
When adding a new account to the current (Windows) desktop client 2.3.3.1, instead of entering user and password, the link above should allow to create a unique password for this client.

The links is: http://192.168.178.29/nextcloud/index.php/settings/personal?sectionid=security#apppasswords
It finally redirects to: http://192.168.178.29/nextcloud/index.php/apps/files/?dir=/&fileid=2
The page, where it should point to is: http://192.168.178.29/nextcloud/index.php/settings/user/security

Tested with Apache, Nginx and Lighttpd webserver and different configurations, so it doesn’t seem to be a webserver/PHP related issue.

#### To derive solution
Reading the links, it indeed looks like it just didn’t get updated after merging user and admin settings with NC13.

#### References
- https://help.nextcloud.com/t/windows-client-app-passwords-link-seems-to-be-obsolete/34116
- https://github.com/Fourdee/DietPi/issues/1933

**Comment by bpcurse** [comment]
Confirmed on current Linux client

**Comment by tabp0le** [comment]
This isn't an issue in 2.5/master. It uses the correct URL.

**Comment by MichaIng** [comment]
Yes the issue has been solved meanwhile. Marking this as closed.
