### ISSUE TITLE
[Bug]: How to remove desktop client on mac

### ISSUE THREAD

**Issue by pszypowicz** [nextcloud/desktop#5144]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I cannot find a procedure to uninstall nextcloud client on mac

### Steps to reproduce

1. Try to uninstall Nextcloud desktop client on mac

### Expected behavior

I want to be able to uninstall desktop client

### Which files are affected by this bug

Nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura 13.0

### Package

Appimage

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
You can do this by deleting the Nextcloud from your `Applications` folder, as well as deleting `~/Library/ApplicationSupport/Nextcloud`
