### ISSUE TITLE
New activities hover text is just duplicated

### ISSUE THREAD

**Issue by rullzer** [nextcloud/desktop#515]
For some reason my screenshot tool fails. But basically when you hover over the activites most of the time the same text is shown as in the activity itself. So then it doesn't help that much.

@camilasan

**Comment by tabp0le** [comment]
New activites f-ed up my theme too. probably related to this. 
![whooa](https://user-images.githubusercontent.com/6798003/43427945-afa4199a-9410-11e8-83ee-dc3e420e518b.png)

**Comment by ad1rie1** [comment]
Yes it can be good to have information about file like emplacement with size. 
Or, for calendar event , information like the date of the meeting

**Comment by Titan-C** [comment]
I want to give this a try. But I can't reproduce. How do you get this behaviour?

**Comment by tabp0le** [comment]
@Titan-C not sure which you are referring to, but for my screenshot, you just have to have a dark qt theme enabled.

**Comment by Titan-C** [comment]
Now I understand. My hover time was to short and I did not see the tooltip showing up. I prepared a PR on this.

**Comment by Titan-C** [comment]
I have no idea on the dark theme, but I don't think is related to this issue.

**Comment by camilasan** [comment]
That is correct and I think the dark theme issue is already fixed.
