### ISSUE TITLE
[Bug]: Unable to sync .var folder using flatpak distro

### ISSUE THREAD

**Issue by mbnoimi** [nextcloud/desktop#5162]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Desktop client doesn't sync `~/.var` folder properly. It only syncs one folder which is:
`~/.var/app/com.nextcloud.desktopclient.nextcloud` !

### Steps to reproduce

- I tried to restart sync process but it didn't affect on the result. 
- I reset sync process by deleting `.var` folder in Server side and "Remove folder sync connection" then adding "Folder sync connection once again but it didn't affect on the result too :frowning: 
- I tried to remove all the ignores but still get same result.

### Expected behavior

sync `.var` folder

### Which files are affected by this bug

.sync-exclude.lst & ~/.var

### Operating system

Linux

### Which version of the operating system you are running.

Mint 21

### Package

Other

### Nextcloud Server version

24.0.7

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

```bash
$ nginx -V
nginx version: nginx/1.22.1
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-CAzFYO/nginx-1.22.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-compat --with-debug --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_sub_module
```
```ini
$ flatpak info --show-permissions com.nextcloud.desktopclient.nextcloud
[Context]
shared=network;ipc;
sockets=x11;wayland;
devices=dri;
filesystems=/home/admino/.themes;host-etc;xdg-run/Nextcloud:create;/home/admino/.var;home;host;xdg-config/kdeglobals:ro;host-os;/usr/share/themes;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
org.kde.kconfig.notify=talk
org.kde.KGlobalSettings=talk
org.kde.StatusNotifierWatcher=talk
org.freedesktop.Notifications=talk
org.freedesktop.secrets=talk
org.kde.*=own

[Environment]
TMPDIR=/var/tmp
GTK_THEME=Mint-Y-Dark-Aqua
QT_STYLE_OVERRIDE=Adwaita-dark
```

**.sync-exclude.lst** (server & client version are matched)

```
app/io.github.kotatogram/data/
app/org.telegram.desktop/data/
app/com.nextcloud.desktopclient.nextcloud/config/
```

**tree of folders:**

```
:~/.var$ tree -d -L 2
.
└── app
    ├── com.github.elth0r0.iqpuzzle
    ├── com.github.git_cola.git-cola
    ├── com.github.micahflee.torbrowser-launcher
    ├── com.github.qarmin.czkawka
    ├── com.github.tchx84.Flatseal
    ├── com.github.unrud.VideoDownloader
    ├── com.github.vkohaupt.vokoscreenNG
    ├── com.nextcloud.desktopclient.nextcloud
    ├── com.rafaelmardojai.Blanket
    ├── com.visualstudio.code
    ├── fr.handbrake.ghb
    ├── io.dbeaver.DBeaverCommunity
    ├── io.freetubeapp.FreeTube
    ├── io.github.kotatogram
    ├── io.github.peazip.PeaZip
    ├── net.cozic.joplin_desktop
    ├── net.filebot.FileBot
    ├── net.supertuxkart.SuperTuxKart
    ├── no.mifi.losslesscut
    ├── org.chromium.Chromium
    ├── org.ferdium.Ferdium
    ├── org.filezillaproject.Filezilla
    ├── org.flameshot.Flameshot
    ├── org.gnome.Cheese
    ├── org.gnome.EasyTAG
    ├── org.gnome.meld
    ├── org.gnome.World.PikaBackup
    ├── org.goldendict.GoldenDict
    ├── org.kde.digikam
    ├── org.kde.krita
    ├── org.kde.okular
    ├── org.keepassxc.KeePassXC
    ├── org.nmap.Zenmap
    ├── org.qbittorrent.qBittorrent
    ├── org.remmina.Remmina
    ├── org.telegram.desktop
    └── rest.insomnia.Insomnia

38 directories

```
**Some attachments**
- [~/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud/.var_sync.log](https://github.com/nextcloud/desktop/files/9982357/var_sync.log)
- Debug Archive is big (46 MB) so I split it into two files:
[nc-debug-archive.zip.001](https://github.com/nextcloud/desktop/files/9982455/nc-debug-archive.001.zip)
[nc-debug-archive.zip.002](https://github.com/nextcloud/desktop/files/9982465/nc-debug-archive.002.zip)

**Comment by joshtrichards** [comment]
As this seems specific to the Flatpak package (which we don't deal with directly in this repo) would you mind opening an issue in their repository about this?

https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues

They're in a better position to isolate any potential bug / offer better advice.

I'll close this here, as I don't think there's anything for us to do, but feel free to comment back with the linked issue to complete the loop / for future visitors and reference.
