### ISSUE TITLE
Text illisible in activity v2

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/desktop#517]
Hello, 
On activity v2 , the text was illisible when is selected on windows 10

![image](https://user-images.githubusercontent.com/1949622/43444535-40123c26-94a4-11e8-9c01-75de2472bb78.png)

**Comment by ad1rie1** [comment]
Hello, 
It a bit more apreciable but the small text "now is illisible : 
![image](https://user-images.githubusercontent.com/1949622/44195869-a4365780-a13a-11e8-91a5-cc8420c77185.png)
I réopen

**Comment by camilasan** [comment]
@jancborchardt ? I would change all the text to dark. That is the easiest for me.

**Comment by jancborchardt** [comment]
@camilasan yes, if that works across the board when selected, that would be fine.

**Comment by jancborchardt** [comment]
Yes, of course for dark themes it should be inverted. Not sure how that's coded but it's possible, right @camilasan?
