### ISSUE TITLE
Encrypt folder from context menu

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#5180]
To have E2E more visible, allow to encrypt folders via context menu.

Requirement:
- e2e is already set up locally

@mgallien can you give me an estimation?

**Comment by mgallien** [comment]
half a day as most needed code is already there ion the settings dialog
if I am being too optimistic it will be 1 day

**Comment by tobiasKaminsky** [comment]
Can you then do this whenever you have time? :)
