### ISSUE TITLE
[Bug]: nextcloud + IDEA/VSCODE File Cache Conflict occurs when I write code

### ISSUE THREAD

**Issue by lllong33** [nextcloud/desktop#5187]
### Bug description

nextcloud + IDEA/VSCODE File Cache Conflict occurs when I write code. It affects my normal operation. In VSCODE, the last few lines of the file are replaced with null characters, and even the last few lines of code are deleted.
![image](https://user-images.githubusercontent.com/29864358/201274828-11d14b2c-8262-464c-b08e-3a41235f024c.png)

### Which version of the operating system you are running.
windows 10 and 11

### Nextcloud Server version

19,0,4,2

### Nextcloud Desktop Client version

3.6.1

------------------------------- 2022-11-18
![image](https://user-images.githubusercontent.com/29864358/202699600-16a76911-fcf1-48dd-a56f-8b091bc962c1.png)

**Comment by TimLisemer** [comment]
Are there any workarounds other than coding outside nextcloud or pausing sync? Like reverting to an older version for example
