### ISSUE TITLE
Activity v2 Calendar events

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/desktop#519]
Hello, 

I see calendar event in the client, it's possible to have a link to the calendar view like the open folder fonctionality ? 

![image](https://user-images.githubusercontent.com/1949622/43444966-68a793e2-94a5-11e8-8781-2d6f5ce538f4.png)

**Comment by camilasan** [comment]
Yes, it is ;-)
Thanks for the reports!

**Comment by er-vin** [comment]
So I checked, and we don't get an URL for the events while going through the `ocs/v2.php/apps/activity/api/v2/activity` endpoint, this is why clicking those entries in the new GUI still don't open them.

@nextcloud/calendar do any of you know if we should talk to a different endpoint to get that information? Or shouldn't the activity item get that URL for a start?

**Comment by tcitworld** [comment]
Not sure what you expect but there's a link in the params since NC 19
https://github.com/nextcloud/server/pull/19039

**Comment by er-vin** [comment]
I'd have to recheck but if I remember correctly in my tests I didn't get it. Thanks for the heads up though, at least it confirms it's supposed to be there.

**Comment by joshtrichards** [comment]
Fixed in #4684
