### ISSUE TITLE
[Bug]: Troubles on Fedora 37 (Workstation edition and Silverblue edition)

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/desktop#5197]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When using the Nextcloud Desktop Edition on Fedora 37 I encountered various issues. Main problem is, that one is not able to open the `Settings` window to configure sync folders. The window is unresponsive and nothing happens, no `Settings` dialog gets opened.

I tested various combinations of Fedora 37 Workstation, Fedora 37 Silverblue, the RPM package of the desktop client as well as the desktop client available on Flathub.

### Steps to reproduce

1. Install Fedora 37 Silverblue
2. Configure Flathub.org as remote repository
3. Install the nextcloud desktop client from Flathub
4. Setup account, but skip folder setup
5. See your successfully account (The top bar adopts the color scheme of my Nextcloud instance, the display name is loaded)
6. Click on your account name and try open `Settings` in the dropdown menu
7. Nothing happens, the window is unresponsive

### Expected behavior

The `Settings` window should open and allow to configure the folders that should be synchronized

### Which files are affected by this bug

This is not related to the synchronization mechanism itself

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 37 Workstation, Fedora 37 Silverblue

### Package

Distro package manager

### Nextcloud Server version

25

### Nextcloud Desktop Client version

3.6.1 (Flathub), 3.6.0-1.fc37 (RPM)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Unrelated, the login works properly, but only the client application is affected.
```

**Comment by etam** [comment]
I have something similar. The nextcloud process burns 100% cpu (one core).

**Comment by stefan-niedermann** [comment]
I have been able to get it working on a virtual machine (using Gnome Boxes, Debian Host) by
1. Installing Fedora Silverblue 37
2. Install all updates
3. Reboot
4. Add Flathub remote
5. Install Nextcloud Desktop client (Flatpak)

I will test those exact steps on my real machine and check whether I can find any differences. In case it works I will close this issue as not reproducible and guess that some update fixed it in the meantime :shrug:  Will keep you updated.

**Comment by stefan-niedermann** [comment]
Did not work unfortunately. I spotted a difference though when installing the client via terminal. The (working) VM showed various Qt runtimes being installed (as expected), while the (not working) real machine seemed to miss those runtime and did not even list it while installing the client...

**Comment by etam** [comment]
In my case I found (using gdb and perf) that it's stuck parsing some multipart http data.
![perf](https://user-images.githubusercontent.com/220752/203638432-5db27de6-bf7b-4edb-bcd7-5649289317d7.svg)

**Comment by stefan-niedermann** [comment]
I have been able to fix this issue for me by setting `allow=per-app-dev-shm` (via Flatseal, but this can also be achieved from the terminal). Closing this issue therefore as it is resolved for me.

@etam I doubt we have the same issue - CPU load is absolutely normal for me. Maybe you want to open a separate one?

**Comment by etam** [comment]
Yep. Turns out solution to my issue was here: https://github.com/nextcloud/desktop/issues/4106#issuecomment-1302732339
