### ISSUE TITLE
Activity v2 text cut when text is too long small screen issue

### ISSUE THREAD

**Issue by ad1rie1** [nextcloud/desktop#520]
Hello, 
 When the text in activity is too long, is cut : 

![image](https://user-images.githubusercontent.com/1949622/43445096-c14083b0-94a5-11e8-9eb2-dbcf4023698a.png)

Unable to see activity on small screen . 
When you pass the cursor on the element, the tooltip is also cut by the screen :D

**Comment by bpcurse** [comment]
In Linux Client 2.5.1 on Manjaro Linux the issue is the same, except that there is no tooltip at all.
(GIT-Revision b37cbe, Dec 4 2018, 15:04:36, Qt 5.11.2, OpenSSL 1.1.1a 20 Nov 2018)

**Comment by er-vin** [comment]
This completely changed with the new systray GUI.
