### ISSUE TITLE
[Bug]: Libreoffice Flatpak cant write to subfolder, but main folder. Cant open files in subfolders

### ISSUE THREAD

**Issue by firefoxlover** [nextcloud/desktop#5203]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I am using a Nexcloud folder with subfolders.

Suddenly I cant open files inside subfolders with Libreoffice (Flatpak version) anymore, only write to the main ~/Nextcloud folder.

When trying to open an existing file in a subfolder, I get "incorrect arguments" as if it was corrupted. 

I didnt rename folders or anything, not even change files. This is not a permission issue, as I can write to the ~/Nextcloud folder.

### Steps to reproduce

1. upload 50GB of files in a different folder
2. try to open a .odt file in another folder, already existing, Libreoffice Flatpak
3. try to save a file into a subfolder
...

### Expected behavior

should work normally, save and read normally in every subfolder

### Which files are affected by this bug

.odt, not .txt only Libreoffice

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 37

### Package

Distro package manager

### Nextcloud Server version

unknown

### Nextcloud Desktop Client version

3.6.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
no access to the server
```

**Comment by joshtrichards** [comment]
Are you using Virtual Files? 

Also, can you copy one of the suspect files from one of those subfolders (using your OS command-line not the client or server) somewhere where you can open it with LibreOffice and confirm it is/isn't truly corrupted?

At first glance, this sounds like it would most likely be Libreoffice (or Flatpak) related.

**Comment by firefoxlover** [comment]
cannot reproduce anymore. It may be a nextcloud problem
