### ISSUE TITLE
[Bug]: v3.6.2 - segmentation fault when starting on NixOS

### ISSUE THREAD

**Issue by tlavoie** [nextcloud/desktop#5228]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Starting the current client listed on NixOS (Linux), v3.6.2. This is on NixOS 22.11, but the same package version is shown for the 22.05 release as well.

I can run the nextcloud desktop client to query its version or get help, e.g. -v or -h. Starting normally, the desktop client crashes with the message, "segmentation fault (core dumped)  nextcloud"

The last part of the current log file has this:
2022-11-28 14:09:00:852 [ info nextcloud.sync.clientproxy /build/source/src/libsync/clientproxy.cpp:98 ]:    Set proxy configuration to use NO proxy
2022-11-28 14:09:00:855 [ debug nextcloud.gui.updater /build/source/src/gui/updater/updater.cpp:124 ][ OCC::Updater::getSystemInfo ]:        Sys Info size:  0
2022-11-28 14:09:00:856 [ debug nextcloud.gui.updater /build/source/src/gui/updater/updater.cpp:138 ][ OCC::Updater::create ]:       QUrl("https://updates.nextcloud.org/client/?version=3.6.2.0&platform=linux&osRelease=nixos&osVersion=22.05&kernelVersion=5.15.79&oem=Nextcloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=git&updatesegment=72")

I checked the URL shown in that last line, and it comes back with a 200 OK response, but Content-Length: 0, Content-Type: application/xml. Since NixOS does its own package management and updates, I'm wondering a couple things:

- Will this always be an empty reply? I haven't checked the logs when this was working for me earlier.
- Since I don't have a core file left behind, I can't validate where it's blown up in the code, but wonder if it is trying to parse a zero-length response as XML, and failing.

I should note that the nexcloudcmd client runs to completion without issues.

### Steps to reproduce

Start the 3.6.2 version of the Nextcloud client on a current NixOS, wait a second for the segmentation fault and program crash.

### Expected behavior

Start up and run normally.

### Which files are affected by this bug

nextcloud's update HTTP request, as shown above

### Operating system

Linux

### Which version of the operating system you are running.

NixOS 22.11

### Package

Distro package manager

### Nextcloud Server version

19.0.13

### Nextcloud Desktop Client version

3.6.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
None relevant, crash happens before server connection
```

**Comment by tlavoie** [comment]
[log.zip](https://github.com/nextcloud/desktop/files/10108101/log.zip)

**Comment by claucambra** [comment]
Hi @tlavoie I doubt it is an issue with the XML file as we have contingencies for this, but I am not sure. Do you know how to get a backtrace through a debugger? It would let us know exactly where the crash is occurring

**Comment by tlavoie** [comment]
Sure thing, hope this helps:

#0  0x00007fffef814750 in QQmlType::QQmlType(QQmlType const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#1  0x00007fffef87ae2c in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#2  0x00007fffef87da31 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#3  0x00007fffef87ddbc in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#4  0x00007fffef87e5e4 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#5  0x00007fffef8795eb in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#6  0x00007fffef7c9e75 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#7  0x00007fffef7cfea7 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#8  0x00007fffef7bdbf5 in QQmlDataBlob::tryDone() () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#9  0x00007fffef81d395 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#10 0x00007fffef81dae2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#11 0x00007fffef81eeb0 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#12 0x00007fffef81f30c in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#13 0x00007fffef81fbb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#14 0x00007fffef7cefa3 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#15 0x00007fffef7d1b0d in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#16 0x00007fffef81d64a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#17 0x00007fffef81dae2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#18 0x00007fffef81eeb0 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#19 0x00007fffef81f30c in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#20 0x00007fffef81fbb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#21 0x00007fffef7cefa3 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#22 0x00007fffef7d1b0d in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#23 0x00007fffef81d64a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#24 0x00007fffef81dae2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#25 0x00007fffef81eeb0 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#26 0x00007fffef81f30c in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#27 0x00007fffef81fbb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#28 0x00007fffef7cefa3 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#29 0x00007fffef7d1b0d in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#30 0x00007fffef81d64a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#31 0x00007fffef81dae2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#32 0x00007fffef81eeb0 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#33 0x00007fffef81f30c in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#34 0x00007fffef81fbb0 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#35 0x00007fffef7cefa3 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#36 0x00007fffef7d1b0d in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#37 0x00007fffef81d64a in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#38 0x00007fffef81dae2 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#39 0x00007fffef81eeb0 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#40 0x00007fffef7d94dd in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#41 0x00007fffef897aef in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#42 0x00007fffef8982b2 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#43 0x00007fffee6916cf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Widgets.so.5
#44 0x00007fffed5b5f5a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#45 0x00007fffed5b9067 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#46 0x00007fffed60e363 in ?? () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#47 0x00007fffed983dfb in g_main_context_dispatch () from /nix/store/vwkcafaqr3awfr4byj3jnz36xvlhbq63-glib-2.72.3/lib/libglib-2.0.so.0
#48 0x00007fffed9840a8 in g_main_context_iterate.constprop () from /nix/store/vwkcafaqr3awfr4byj3jnz36xvlhbq63-glib-2.72.3/lib/libglib-2.0.so.0
#49 0x00007fffed98415f in g_main_context_iteration () from /nix/store/vwkcafaqr3awfr4byj3jnz36xvlhbq63-glib-2.72.3/lib/libglib-2.0.so.0
#50 0x00007fffed60d9c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#51 0x00007fffed5b48db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#52 0x00007fffed3c0adb in QThread::exec() () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#53 0x00007fffef897785 in ?? () from /nix/store/vw8477yjkd4fq1b677vvm3dszxhfrdyx-qtdeclarative-5.15.3/lib/libQt5Qml.so.5
#54 0x00007fffed3c1de1 in ?? () from /nix/store/q5n9l7q89yc70khzpa132w3q9r89603f-qtbase-5.15.3/lib/libQt5Core.so.5
#55 0x00007fffece6bff2 in start_thread () from /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/libc.so.6
#56 0x00007fffeceeebfc in clone3 () from /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/libc.so.6

**Comment by JohnWalkerx** [comment]
Hm, I did an upgrade to nixos 22.11 and the client is working :thinking:

**Comment by tlavoie** [comment]
Indeed, same here as well.On Dec 11, 2022, at 12:18 PM, JohnWalkerx ***@***.***> wrote:﻿
Hm, I did an upgrade to nixos 22.11 and the client is working 🤔

**Comment by JohnWalkerx** [comment]
@tlavoie I think this can be closed?

**Comment by tlavoie** [comment]
Yes, I think so thanks. At least, things have been working for me since
then.

  Cheers,
  Tim
