### ISSUE TITLE
[Bug]: On Linux sway/wayland nextcloud keeps asking to authenticate

### ISSUE THREAD

**Issue by pmatos** [nextcloud/desktop#5235]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud keeps asking to authenticate when it starts. Then, authentication works, and all goes fine until I restart and it asks again. This changed when I moved from Xorg/i3 to Wayland/sway but can't say it's related or just a coincidence.

### Steps to reproduce

1. install sway
2. run nextcloud at start with `nextcloud --background`
3. notice that each time sway starts, nextcloud opens the browser to ask you to login to your server.

### Expected behavior

Login should only happen once per installation.

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

archlinux

### Package

Distro package manager

### Nextcloud Server version

24.0.6

### Nextcloud Desktop Client version

3.6.2git

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
@pmatos You need some sort of wallet/keychain software to store the credentials in (usually KDE Wallet or GNOME Keyring). As long as it is supported by https://github.com/frankosterfeld/qtkeychain it will work. I'm guessing since you are using sway you don't have one of these installed?

**Comment by pmatos** [comment]
@claucambra So... before this felt pretty transparent but I don't remember what I had installed in my previous laptop. So when I start `nextcloud --background`, I would have expected nextcloud desktop to have stored the credentials from my initial login. Is it correct to say that you are telling me that nextcloud doesn't deal with this and somehow the system keychain will store these credentials and they will be checked by nextcloud when it starts?

**Comment by bodograumann** [comment]
So that means the keychain would have to be started beforehand, which explains why it doesn't work for me :-)

**Comment by claucambra** [comment]
> So that means the keychain would have to be started beforehand, which explains why it doesn't work for me :-)

Glad to clear that up! I will close the issue now, if this continues not to work after installing a GNOME keychain/KDE Wallet please feel free to reopen

**Comment by sallyhaj** [comment]
I know this issue has been closed.
I have a relative issue.
Installing gnome-keyring or kde wallet, solve the issue of login/re-login.
I have installed gnome-keyring, but every time I restart, they gnome-keyring asking for the password. Is there a solution for that?
