### ISSUE TITLE
[Bug]: The new installed client will crash when click to start in Win11

### ISSUE THREAD

**Issue by fairok** [nextcloud/desktop#5250]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
When I had installed the client, and click the icon in the desktop to start the APP, the screen will show nothing and the icon will show in the taskbar (gray) in about 2~3 seconds and dispeared.

### Steps to reproduce

1. Fresh install in the Windows Computer (Windows 11)
2. Client the icon to start the APP

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
When clicking the ICON, the APP should start and let me input the server url.

### Which files are affected by this bug

no idea, mybe nextcloud.exe

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 21H2

### Package

Appimage

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

3.6.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
This logs is not happend after this client was installed.

{"reqId":"q795xf0BOS9dYu3DHRSl","level":2,"time":"2022-12-03T03:20:08+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"q795xf0BOS9dYu3DHRSl","level":2,"time":"2022-12-03T03:20:08+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"K51IiEEJj3MXaBozG5GV","level":2,"time":"2022-12-03T03:22:55+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"K51IiEEJj3MXaBozG5GV","level":2,"time":"2022-12-03T03:22:55+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"S4rrF9vorjcBCQwec51Q","level":2,"time":"2022-12-03T03:23:03+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"S4rrF9vorjcBCQwec51Q","level":2,"time":"2022-12-03T03:23:03+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
{"reqId":"S4rrF9vorjcBCQwec51Q","level":3,"time":"2022-12-03T03:23:11+00:00","remoteAddr":"192.168.1.20","user":"--","app":"no app in contex>
```

### Additional info

My Windows Event Logs related the NextCloud.exe:

错误应用程序名称: nextcloud.exe，版本: 3.6.2.36022，时间戳: 0x636cd3ec
错误模块名称: KERNELBASE.dll，版本: 10.0.22000.1281，时间戳: 0xc2fb642a
异常代码: 0xc00000fd
错误偏移量: 0x000000000004b014
错误进程 ID: 0x6e8
错误应用程序启动时间: 0x01d90aa814e57fbc
错误应用程序路径: C:\Program Files\Nextcloud\nextcloud.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 7f5a16f0-30c2-414a-b1e9-b4f51457b034
错误程序包全名: 
错误程序包相对应用程序 ID: 

错误应用程序名称: nextcloud.exe，版本: 3.6.2.36022，时间戳: 0x636cd3ec
错误模块名称: ntdll.dll，版本: 10.0.22000.918，时间戳: 0x57b668f2
异常代码: 0xc00000fd
错误偏移量: 0x000000000002ed4c
错误进程 ID: 0x316c
错误应用程序启动时间: 0x01d90aa807ce50c6
错误应用程序路径: C:\Program Files\Nextcloud\nextcloud.exe
错误模块路径: C:\WINDOWS\SYSTEM32\ntdll.dll
报告 ID: 226fe511-6d2b-43e4-9396-ba80e0ab3245
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by joshtrichards** [comment]
Hi @fairok - Are you still experiencing this with newer versions?

**Comment by joshtrichards** [comment]
Closing after receiving no follow-up info after >6 months.
