### ISSUE TITLE
cmake could not find OpenSSL

### ISSUE THREAD

**Issue by ShinjiLE** [nextcloud/desktop#526]
On OpenSuse Tumbleweed with Installed libopenssl-devel version 1.1.0h-1.1 .

`
-- Build of crashreporter disabled.
-- GIT_SHA1 34acc095c711f158b9deff106b2898535f899659
-- Could NOT find INOTIFY (missing: INOTIFY_LIBRARY_DIR) 
CMake Warning at /usr/share/cmake/Modules/FindOpenSSL.cmake:405 (message):
  VERSION is not a valid OpenSSL component
Call Stack (most recent call first):
  CMakeLists.txt:186 (find_package)

CMake Warning at /usr/share/cmake/Modules/FindOpenSSL.cmake:405 (message):
  1.1 is not a valid OpenSSL component
Call Stack (most recent call first):
  CMakeLists.txt:186 (find_package)

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: VERSION 1.1) (found version
  "1.1.0h")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:412 (find_package_handle_standard_args)
  CMakeLists.txt:186 (find_package)
`

**Comment by camilasan** [comment]
Hi! I am also using openSUSE Tumbleweed and I have installed libopenssl-1_1-devel not libopenssl-devel. Could you try to install it too?

**Comment by ShinjiLE** [comment]
Hi!
I have removed it . No luck . The libopenssl-devel is a dummy-packet it contains only a readme.
libopenssl-1_1-devel was also installed before. But there is no other version available with header-files.

**Comment by ShinjiLE** [comment]
Hello . 
I think i found a solution . 
Within the CMakeLists.txt the required version is wrong specified.
 
[cmake_ssl_version_fix.txt](https://github.com/nextcloud/desktop/files/2256541/cmake_ssl_version_fix.txt)

**Comment by camilasan** [comment]
@ShinjiLE Would you like to create a PR? ;-)

**Comment by camilasan** [comment]
I see you have created one. Why did you close it?

**Comment by ShinjiLE** [comment]
Hi,
the required version is confusing me , because test against qt 5.7 5.8 and 5.9 try to use a OpenSSL 1.0 version ,so it fail with this patch . But the required version should be 1.1 .

**Comment by ShinjiLE** [comment]
Yes it is fixed .
