### ISSUE TITLE
Handle ics Mimetype files to import them directly into NC calendar

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/desktop#5264]
### Feature description
When reserving a meeting from a website ( like doctolib or planity ) the website will ask if you want to import you meeting in : google / yahoo / outlook.com / ical apple ) 

Ical is the only way I see to make import with Netxtcloud

So a solution would be to make the desktop client handling ics files to import them in default calendar first

Today we have to go manually to the webui to import the ics file

**Comment by Rello** [comment]
Hello,

thank you for this suggestion. 
The Nextcloud file client is just there for syncing the files. it is not meant to process any files.
This is currently not on the roadmap.

thank you,
Marcel
