### ISSUE TITLE
Mac VFS without .nextcloud file extension

### ISSUE THREAD

**Issue by xavi-b** [nextcloud/desktop#5281]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

It would be nice having the same feature as Windows on Mac which is "not to have .nextcloud file extension when using VFS" (same way, it's working on Windows where there is no .nextcloud file extension with VFS)

**Comment by tobiasKaminsky** [comment]
We have already an issue for it.
You can follow progress here: https://github.com/nextcloud/desktop/issues/1337
