### ISSUE TITLE
Nextcloud client on Ubuntu asking for password

### ISSUE THREAD

**Issue by mn-web** [nextcloud/desktop#529]
I have installed Ubuntu 18.04.1 LTS. Every time after rebooting my notebook the client is asking for the password.

This only happens when you are installing the client via snap package. Installing via repository solves the problem.

**Comment by tabp0le** [comment]
The snap probably isn't using the keychain properly.

**Comment by samtygier** [comment]
See https://forum.snapcraft.io/t/nextcloud-client-snap-doesnt-remember-password/4270 for discussion and workarounds.

**Comment by Mannshoch** [comment]
I have the same issue but I do not use snap.
I get every time the Nextcloud Website with the login.

**Comment by mn-web** [comment]
With Ubuntu 18.04 LTS everything works fine. On my netbook I've installed Ubuntu MATE 18.04 LTS. And there I have the same problem.

**Comment by Mannshoch** [comment]
What information do you need?

**Comment by misch7** [comment]
Related issue: #230

Closing this here to keep everything in one issue, please also see: https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811
