### ISSUE TITLE
[Bug]: Desktop client temporarily crashes the SSD drives

### ISSUE THREAD

**Issue by f242** [nextcloud/desktop#5292]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The latest client version 3.6.4 temporarily crashes the SSD drives during synchronization from scratch. I checked several times on two SSDs. Working cloud ~4.5Gb and ~7000 files. Internet connection speeds of 500 megabits, sync speeds of be over 300 megabits at peak. The first SSD SmartBuy at 60-70% write speed was falling dramatically, in Task Manager its active time was 100%, and the write speed was counted in kilobytes. The second Crucial SSD had the same behavior, but in addition it also disappeared from the system and returned only after powering off, rebooting did not help. Only version 3.6.0 was able to sync successfully.

### Steps to reproduce

Just start synchronization from scratch, select local disk, select folders to synhcronize and press start.

### Expected behavior

Full sucessfully synchronization 

### Which files are affected by this bug

i don't know

### Operating system

Windows

### Which version of the operating system you are running.

windows 11 22h2

### Package

Other

### Nextcloud Server version

i don't know

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @f242 - Thanks for the report and sorry to hear you had that experience.

> The second Crucial SSD had the same behavior, but in addition it also disappeared from the system and returned only after powering off, rebooting did not help.

This sounds like a hardware issue. There might be some catalyst in the behavior differences of the sync engine in different app versions that triggers this in your environment, but the root cause for this is unlikely to be Desktop client itself.

Power supply issues would be my best guess.
