### ISSUE TITLE
“use of undeclared identifier 'insertSeparator'” When build client on Mac OS

### ISSUE THREAD

**Issue by isshe** [nextcloud/desktop#530]
# 1. Enviroment
* Mac OS 10.13.6
* qt: 5.11.1 (5.10.1, 5.6.2)
* IDE: CLion
* Toolchains:
![image](https://user-images.githubusercontent.com/13636347/43630577-4217917e-9733-11e8-9651-e079f5086811.png)

* CMake:
![image](https://user-images.githubusercontent.com/13636347/43630648-802cbaa2-9733-11e8-8b21-0fdd01738a49.png)

* CMake Options:
```
-DNO_SHIBBOLETH=1
-DCMAKE_PREFIX_PATH=/Volumes/HardDisk/Qt5.11/5.11.1/clang_64
-DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.0h
-DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl@1.1/1.1.0h/include
```

# 2. Error
## 2.1 Error Code
```
/Volumes/HardDisk/Work/Change/Cloud/nextcloud/desktop/src/gui/settingsdialogmac.cpp:162:26: error: use of undeclared identifier 'insertSeparator'; did you mean 'isSeparator'?
        _separators[s] = insertSeparator(_actionsIdx - 1);
                         ^~~~~~~~~~~~~~~
                         isSeparator
/Volumes/HardDisk/Qt5.11/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h:123:10: note: 'isSeparator' declared here
    bool isSeparator(const QPoint &pos) const;
         ^
/Volumes/HardDisk/Work/Change/Cloud/nextcloud/desktop/src/gui/settingsdialogmac.cpp:162:42: error: reference to type 'const QPoint' could not bind to an rvalue of type 'int'
        _separators[s] = insertSeparator(_actionsIdx - 1);
                                         ^~~~~~~~~~~~~~~
/Volumes/HardDisk/Qt5.11/5.11.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h:123:36: note: passing argument to parameter 'pos' here
    bool isSeparator(const QPoint &pos) const;
                                   ^
/Volumes/HardDisk/Work/Change/Cloud/nextcloud/desktop/src/gui/settingsdialogmac.cpp:185:17: error: use of undeclared identifier 'removeSeparator'
                removeSeparator(_separators[s]);
```

## 2.2 Error pic
![image](https://user-images.githubusercontent.com/13636347/43630771-d1179b62-9733-11e8-842c-cd03c0dcfcf9.png)

**thx**

**Comment by camilasan** [comment]
Hi! insertSeparator is a function from 3rdparty/qtmacgoodies. So you need to run in the desktop folder:
```
$ git submodule init
$ git submodule update
```

After that it should work ;-)

**Comment by isshe** [comment]
thank you ;-)

**Comment by isshe** [comment]
Sorry.This problem still exists. 
> I got another problem that makes me think that this problem has been solved.

## 1. Retry step
* re-download `desktop`
* Use 
```
$ git submodule init
$ git submodule update
``` 
instead of 
```
git submodule update --init --recursive
```
* build All
* then, error:
![image](https://user-images.githubusercontent.com/13636347/43719453-57c7c3ba-99c0-11e8-90c7-5593155dcdee.png)

## 2. search `insertSeparator`
* **I can't find `insertSeparator` in `3rdparty/qtmacgoodies/src`**

![image](https://user-images.githubusercontent.com/13636347/43719655-d966f210-99c0-11e8-91c8-82484e955cf1.png)

## 3. `desktop` branch and latest commit
![image](https://user-images.githubusercontent.com/13636347/43719773-31f8abb2-99c1-11e8-8d7a-32409a767d96.png)
![image](https://user-images.githubusercontent.com/13636347/43719809-556a92ea-99c1-11e8-8d2d-d6a191ce066c.png)

**Comment by isshe** [comment]
I tried `CLion` and `Qt Creator`, the errors are the same. 
* In the code：
`MacPreferencesWindow : public QMainWindow` 
-> `class Q_WIDGETS_EXPORT QMainWindow : public QWidget`, 

but `insertSeparator` is in `class Q_WIDGETS_EXPORT QMenu : public QWidget`.
Is this the cause of the problem?

**Comment by camilasan** [comment]
What I am finding odd is that I am able to compile the same code on mac os...but I am running Qt 5.9.5. I So I would say one option would be to try Qt 5.9.5. I can try to run on Qt 5.11 later.

**Comment by isshe** [comment]
# 1. 
So far, I have tried：
* Qt 5.6.2
* Qt 5.9.5
* Qt 5.9.6
* Qt 5.10.1
* Qt 5.11.1

All got the same error.
* error：(This screenshot is qt5.9.5)
![image](https://user-images.githubusercontent.com/13636347/43780165-8f318472-9a8c-11e8-89d2-9b89623bfc50.png)


# 2.
Is it because of Openssh? 
> My openssl is downloaded by brew，not xcode

Cmake can pass，Only after I modified
```
find_package(OpenSSL REQUIRED VERSION 1.1)
```
to
```
find_package(OpenSSL)
```

* pic:
![image](https://user-images.githubusercontent.com/13636347/43780005-36409ee8-9a8c-11e8-8e44-19ee125534fc.png)

Thanks，
isshe，
;-)

**Comment by isshe** [comment]
In the latest version of the `desktop`, I still need to make the following changes to compile：

![image](https://user-images.githubusercontent.com/13636347/45077413-bd219f80-b11f-11e8-8ab0-54d23fef9305.png)

**Comment by camilasan** [comment]
We changed the submodule origin to fix the problem so you have to remove the submodule first and then init it again.

**Comment by camilasan** [comment]
@isshe Sorry, but I missed one part on setting up the submodule properly. Please, pull again from master and it should work now.
