### ISSUE TITLE
[Bug]: Don't lock when using "Edit locally" on folders

### ISSUE THREAD

**Issue by PVince81** [nextcloud/desktop#5308]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The file manager will open the folder.

However, a pop up message also appears saying that the file will be locked for a given time.
This is not necessary and even wrong as we don't want to lock the folder in this scenario.

I'm unsure whether the locking API will do anything when applied on folders. (@juliushaertl might know)

### Steps to reproduce

1. In the web UI create a folder
2. Configure the desktop client to synchronize that account locally
3. In the web UI, click the three dots on the folder
4. Pick "Edit locally" and tell the browser it's ok to open with Nextcloud Desktop

### Expected behavior

The folder opens in the file manager without any note or warning.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

openSUSE Tumbleweed 20221229

### Package

Distro package manager

### Nextcloud Server version

25.0.2 (c.nc.com)

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tobiasKaminsky** [comment]
@claucambra as you implemented the message, as far as I know :)
