### ISSUE TITLE
Windows Desktop Client (Daily build from today) is not able to connect to nextcloud

### ISSUE THREAD

**Issue by vibora** [nextcloud/desktop#531]
Hi,
I'm facing a problem with the today's daily build Windows Desktop client
On my nextcloud I'm using OTP
The client asks me to enter the URL and my credentials, then I'm forwarded to the OTP entry screen entering the OTP and then the client gets stuck showing 'Weiterleiten' (Forwarding).
I had a look at the logs but I can't find any useful information.
Is this a known bug or am I doing something wrong?
I also tried it with an App Password, bit the client keeps telling me that I'm using the wrong password.
What would be the prefered method to log the client in? App Password or following the guided procedure with entering the OTP?

Greetz
D

**Comment by tabp0le** [comment]
Duplicate issue: https://github.com/nextcloud/desktop/issues/279

**Comment by camilasan** [comment]
Hi @vibora could you try one of the latest builds https://github.com/nextcloud/desktop/issues/268?
Maybe this is not a duplicate.

**Comment by vibora** [comment]
Hi @camilasan,
I just tried it with the build from yesterday. The situation is still the same.
It gets stuck on 'Forwarding'

**Comment by vibora** [comment]
I tried it with todays build and it now works for me.
Thanks a lot for fixing it!
Greetz
D
