### ISSUE TITLE
How can I use `nextcloud/desktop` through terminal without GUI?

### ISSUE THREAD

**Issue by avatar-lavventura** [nextcloud/desktop#5313]
I am using Ubuntu node that does not have `desktop` through `ssh`. 
Is it possible to use `nextcloud --background` process without a GUI access (Headless)?

**Comment by Tachi107** [comment]
You could try using the `-platform offscreen` Qt flag, but if you don't want a GUI then you should be using `nextcloud-cmd` (on Debian and Ubuntu you have to install the `nextcloud-desktop-cmd` package)

**Comment by avatar-lavventura** [comment]
Thanks. Can we use `nextcloud-cmd` as a daemon process?  any documentation related to using it will be helpful.

**Comment by avatar-lavventura** [comment]
@Tachi107 Thanks I will investicate from the docs to make it work.  I was manage to make it work using `nextcloud --background` but everytime it was asking for grant permission via opening browser. So it always requires my interaction from browser.

But using daemon process seems like a better option.
