### ISSUE TITLE
Activity v2 dialog

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#533]
Some thoughts about the new activity dialog:

- A lot of free space around the copy button. Are there any hidden elements? Looks really strange now. And it´s way bigger than the close button.
- After copying sth. the copy button reacts really strange while hovering (see screenshot).

![activity](https://user-images.githubusercontent.com/1869584/43684446-596e0ede-98a0-11e8-9d25-b9605b9e8624.png)

**Comment by camilasan** [comment]
There is a margin in the copy button, I guess that is what causes the weird behavior  :/  It might be better to put the button back to where it was. I didn't experience this when I tested it ...would you mind to share which system you have? Win/Mac/Linux? 

Thanks for the report!

**Comment by splitt3r** [comment]
Sorry 🤦‍♂️ i´m using the latests Win 10 version with a recent daily build.
