### ISSUE TITLE
[Bug]: Nextcloud Client 3.6.5 Language Bug for german

### ISSUE THREAD

**Issue by maxmellown** [nextcloud/desktop#5339]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating the desktop client to version 3.6.5, the same sentence is everywhere, using macOS and language german:

<img width="2450" alt="Nextcloud Client 3 6 5 Bug" src="https://user-images.githubusercontent.com/72824907/213425748-8bb582ec-082a-4865-9200-2ea470f3a049.png">

### Steps to reproduce

1. Update Desktop Client to 3.6.5

### Expected behavior

Show normal words

### Which files are affected by this bug

Nextcloud Desktop Client App

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.1

### Package

Other

### Nextcloud Server version

24.0.8.2

### Nextcloud Desktop Client version

3.6.5

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Polynomial-C** [comment]
Same here on Gentoo Linux

**Comment by Deefstomp** [comment]
Windows is also affected in the same way.

**Comment by Polynomial-C** [comment]
This is the offending commit: https://github.com/nextcloud/desktop/commit/467bec3e51227debb7346ff726ba79b9a67fe807

**Comment by simonschwarzmueller** [comment]
Same here on Windows 11, Nextcloud Client 3.6.5, language german

**Comment by darthmarx** [comment]
Same problem here on Windows 11, Nextcloud Client 3.6.5, language german

**Comment by pvtelviz** [comment]
Same on Windows 10 Pro after Client Update - language German

**Comment by Nordcat** [comment]
i guess its broken on Mac/Linux/Windows :-( - maybe the rollout should be stopped at least for Germany ?

**Comment by ffechner** [comment]
Same here on macos 12.6.2 update from Nexcloud Client 3.6.4 to 3.6.5. reinstall of 3.6.4 did not work as a quick fix (3.6.4 Installer did not overwrite the newer version)

**Comment by Toraih** [comment]
same here, win+mac clients - it's annoying this is happening again, it's even worse than last time...

**Comment by madox85** [comment]
Same Problem. MacOS
<img width="446" alt="Bildschirm­foto 2023-01-19 um 17 23 06" src="https://user-images.githubusercontent.com/54234391/213498236-462d097c-de73-4608-88df-7b9b2dfeddfe.png">

**Comment by claucambra** [comment]
Noted, we are investigating

**Comment by maiksicks** [comment]
> reinstall of 3.6.4 did not work as a quick fix (3.6.4 Installer did not overwrite the newer version). 

I just replaced the broken client (3.6.5) with the previous version (3.6.4) from the time machine backup. Works fine.

**Comment by claucambra** [comment]
We have for now pulled the 3.6.5 update from our update server. Looking into what broke and we will update with further news soon

**Comment by Fischmuetze** [comment]
> If you have already installed 3.6.5, downgrading to 3.6.4 will fix the issue.

macOS users have to shutdown the app and delete them in /Applications before start install the 3.6.4. The installation package of 3.6.4 will not overwrite an existing 3.6.5. (without any message)

**Comment by kaekimaster** [comment]
Issue has now also occurred on Windows 10 (10.0.19045 build) after applying the update on the desktop client.

**Comment by allexzander** [comment]
Release 3.6.6 will get published tomorrow.

For now, those of you who are having trouble downgrading to 3.6.4, can already download 3.6.6 with the German language issue fixed from here:

- Linux: https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-3.6.6-x86_64.AppImage
- Windows: https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.6.6-x64.msi
- mac OS: https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-3.6.6.pkg
- mac OS (updater): https://download.nextcloud.com/desktop/releases/Mac/Installer/Nextcloud-3.6.6.pkg.tbz

Apologies for the inconvenience. This was really unexpected bug for me.

**Comment by allexzander** [comment]
3.6.6 got released

**Comment by jhjadmin** [comment]
This is not fixed for me in version 3.6.6
OS is Linux Mint 21 (Ubuntu 22.04)

**Comment by yoyobo** [comment]
@jhjadmin How can I update the l10n package manually? The update to 3.6.6 did not fix the issue for me as well.

**Comment by mgallien** [comment]
> @jhjadmin How can I update the l10n package manually? The update to 3.6.6 did not fix the issue for me as well.



> @jhjadmin How can I update the l10n package manually? The update to 3.6.6 did not fix the issue for me as well.



> @jhjadmin How can I update the l10n package manually? The update to 3.6.6 did not fix the issue for me as well.

@jhjadmin @yoyobo could you provide a screenshot of the issue ?
I do not understand German 😥 so I might be unable to spot the issue

can you also try the last daily build ([Desktop Client Daily Builds](https://download.nextcloud.com/desktop/daily/)) ?

**Comment by yoyobo** [comment]
@mgallien Thanks, I could not reproduce the issue on another client. I had the issue only on one single machine.

**Comment by eehmke** [comment]
I did not have this problem on 3.6.6 and 3.7.1. Today I installed 3.7.2 and it popped up for me for the first time.

**Comment by camouflage81** [comment]
Hi guys, have the same problem.

I just did the latest update of the Windows client (3.7.2).
For me it also only shows "Benötigt keine Übersetzung.....".
All users also have the problem (Windows 10 and 11).
Also newly installed clients bring the same text.

Thanks and greetings

**Comment by allexzander** [comment]
We again got broken translations from bot :( Will have to revert them and do 3.7.3 ;(

**Comment by eehmke** [comment]
Does nobody test new releases? This is no release candidate or prerelease, it is assumed to be stable.

**Comment by allexzander** [comment]
3.7.3 is out with bad translations reverted

**Comment by camouflage81** [comment]
> 3.7.3 is out with bad translations reverted

Looks good.
Problem is no longer present.
Thank you very much.

**Comment by eehmke** [comment]
> 3.7.3 is out with bad translations reverted

Yes the bug is gone with 3.7.3. Compiled from source, looks good.
