### ISSUE TITLE
Desktop Client 2.5.0beta1 share permissions broken and some small visual issues

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#534]
I just tested the first beta of the new Desktop client, it contain many improvements... Nice! :slightly_smiling_face: 

I used the AppImage on Debian sid (Gnome) and noticed some stuff:

1. When I open the share dialog it looks like this:

![image](https://user-images.githubusercontent.com/1589737/43716679-48b4e726-9985-11e8-9553-4d8f0e4d162d.png)

The disabled select box next to the "enable" checkbox looks strange. Maybe we could hide it and only show it when the enabled checkbox is activated? Also that it is a empty square looks a bit strange. Maybe adding a icon (a gear for settings?), text or whatever would make sense?

2. After I shared the file with the group "admin" the dialog looks like this:

![image](https://user-images.githubusercontent.com/1589737/43716802-baa71a2a-9985-11e8-886d-0a972c7d232a.png)

The "can edit" permissions are grayed out, I can't remove them. After I opened the drop-down and add the "can share" permissions the "can edit" permissions are gone.

3. Set Expire date option is gone:

In the web interface I can set a expire date for the group share, this option doesn't exists in the sync client.

**Comment by camilasan** [comment]
For 1 and 2... a lot of things are fixed in #567 
but the build seems to not have the icons set.

On my machine:
![icons](https://user-images.githubusercontent.com/241266/44311629-192fb880-a3eb-11e8-9a70-7c0c99da35e1.png)

3. #568
