### ISSUE TITLE
[Feature Request] Managing Trash-Folder

### ISSUE THREAD

**Issue by Motti91** [nextcloud/desktop#535]
I love using the desktop client on my Windows devices and rarely log on to the Webpage. To be honest I just do it to clean my (server) trash folder.

### Solution
The option to manage your trash folder inside the client.
I think it could fit perfectly inside the "activity" tab on the client. 

Thanks in advance for your effort and for reading
Philipp Modjesch

**Comment by camilasan** [comment]
On NC 14 we have a trash and a versioning api... so in theory your idea is possible.
@jancborchardt will have to think on how that can look like.
@Motti91 thanks for the suggestion :)

**Comment by Motti91** [comment]
Awesome! Thank you for your fast reply and I'll be happy to see this feature in the future version.
Keep up the great work with nextcloud :)

**Comment by jancborchardt** [comment]
@Motti91 actually, the versions and server trash should automatically be truncated based on available space. Does it not @schiessle?

**Comment by schiessle** [comment]
yes, this should be handled automatically. By default 50% of your free space is used for the trash bin and 50% for versions. We re-balance it every time a new version was created or a new file was moved to trash, so that it can happen that you use more then 100% of your quota for some time. Therefore max quota shouldn't be your hard drive  limit. If you don't like the default behavior you can adjust it in your config.php. Check the config/config.sample.php for reference.

**Comment by brianbgness** [comment]
Sounds like to me that Motti91 meant emptying the trashbin.  Or restoring files from the trashbin.

**Comment by jancborchardt** [comment]
Normally a deleted file will be of course in the deleted files / trashbin system of that device. But yes, if it’s from a mobile device or from a different device and you want to restore it, then it would be quite nice to be able to have a "Restore" action whenever there is a "File deleted" activity.

What do you think @camilasan?

**Comment by Motti91** [comment]
What I meant is the option to mange the Trash Folder (of my server) inside the Desktop App. So you can see the deleted files on the server. On the Website I have to login and go to "Deleted Files" to view all Files and delete them from my server. I can't to this in the Desktop app.

For example I delete the Folder "Test" on my PC, its synced on all devices, but I can login to my Cloudwebsite, view my deleted files and restore this folder. Or leave it there (deleted) and suddenly all my disk space on the server is used, because the trash is just full. Yes that nearly happend a few times.

I'd love to see this the need to login to my Website gone, and that I can manage this part inside my Desktop Client :)

**Comment by jancborchardt** [comment]
> Or leave it there (deleted) and suddenly all my disk space on the server is used, because the trash is just full. Yes that nearly happend a few times.

So you don’t need a management interface for the trash folder. :) You need our automatic cleaning of the trash to just work. The trash (and versions) should automatically be cleaned if they would lead to the disk space being full. Please open a new issue in the server repository at https://github.com/nextcloud/server/issues (cc @schiessle)
