### ISSUE TITLE
[Bug]: RC1 encrypt folder - Please wait for the folder to sync before trying to encrypt it.

### ISSUE THREAD

**Issue by nphalem** [nextcloud/desktop#5357]
[nextcloud.log](https://github.com/nextcloud/desktop/files/10475263/nextcloud.log)
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I'm unable to encrypt any of my folders, existing or newly created ones.

I get the following error when I try to encrypt them:
"Please wait for the folder to sync before trying to encrypt it."

Keep in mind that folders are synced.

Tried the steps from [here](https://github.com/nextcloud/end_to_end_encryption/releases/tag/v1.5.2-beta1) to reset the E2E app and try again since people said it helped them solve the [issue](https://github.com/nextcloud/desktop/issues/777).

Nextcloud end-to-end encryption app version: 1.11.1
Nextcloud Server version: 25.0.3
Nextcloud Desktop Client: 3.6.4 (Arch)

If any additional information is needed, I'll do my best to provide it.

### Steps to reproduce

1. Enable end-to-end encryption app
2. Close and open the desktop client
3. Go to settings on desktop client and enable e2e encryption
4. Create a new empty folder
5. Try to encrypt the empty folder

[debug.zip](https://github.com/nextcloud/desktop/files/10475267/debug.zip)

### Expected behavior

Client should get the 

### Which files are affected by this bug

tttt

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux 6.1.7-arch1-1

### Package

Distro package manager

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.6.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend

**Comment by nphalem** [comment]
Did I post at wrong place? Do I need to provide more information? How can I help this getting solved?

**Comment by nphalem** [comment]
I keep getting this error when I try to encrypt any (empty) folder through Nextcloud settings but I'm able to encrypt the folder through Dolphin without any issues.

**Comment by joshtrichards** [comment]
This status just means the client and server haven't recently checked in so the E2EE engine has no way of knowing whether the folder is truly empty (or new). See #291 for reference.

The wording of the message you're seeing has recently been cleaned up slightly to try to indicate whether it's a temporary situation (e.g. connectivity/server maintenance) or something... Else. See #5972.

> I'm able to encrypt the folder through Dolphin.

Wait, how precisely? Dolphin doesn't natively do anything Nextcloud or E2EE related - it uses the Desktop client app.

Are you saying you can create an empty folder from the command-line (and that doesn't work), but if you create the empty in your file manager (Dolphin) it works?

P.S. Just to rule something out: you're not simultaneously using server-side Encryption are you?

**Comment by claucambra** [comment]
Hello, since no new info has been provided for a few months I will go ahead and close the issue. If the issue reappears, please do reopen the issue and we will take a look into it
