### ISSUE TITLE
Sync activity entries

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/desktop#538]
When running a new sync there are some entries at the beginning of the activity stream that don't provide any information what the entries are about:

![image](https://user-images.githubusercontent.com/3404133/43882158-fc0424f6-9bae-11e8-89c6-566e95cc8c06.png)

@camilasan I guess those are successfully synced folders? In that case they should not have an activity icon but rather a sync icon (the two arrows in a circle). Also the entry should probably be a bit more verbose. Something like "Folder name has been synced successfully"

@nextcloud/designers

**Comment by jancborchardt** [comment]
Yes, absolutely. :) Even shorter and more concise:

> Synced **PhotoFrame** (in Shares/Test)

**Comment by camilasan** [comment]
That is it for now, on a new iteration I will merge the 2 lists properly:
![new-list](https://user-images.githubusercontent.com/241266/44570458-3b745e00-a77e-11e8-848f-d96c327198d4.png)
