### ISSUE TITLE
Edit Ignored Files: How to ignore files that match the pattern "#*.dxf"

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/desktop#539]
I'm editing a .dxf file on my NextCloud using FreeCAD. It maintains a temporary file that is named #filename.dxf. 

But if I Edit Ignored Files and add that pattern, it is not retained. I can add the pattern, click OK, and then Edit Ignore Files again and it's missing.

If I use the pattern "\#*.dxf" it sticks. But I'm not sure if that works or not. Either way, the behaviour is off without the \ and seems like a bug.

**Comment by truls** [comment]
I have the same problem but I just tried building the client from git master and its working there. So it'll probably be fixed in the 2.5 release
