### ISSUE TITLE
On mouse over Information on server activity stays single line.

### ISSUE THREAD

**Issue by tacruc** [nextcloud/desktop#54]
### Expected behaviour
On the Server activity Tab, the on mouse over buble for showing the full information needs to get multiline to show full informaton.

### Actual behaviour
It is single line and so hindes information not fitting on the screen. See Screenshot

![grafik](https://user-images.githubusercontent.com/402891/33116294-401a7fc4-cf8a-11e7-86d1-5efde5f24541.png)

### Steps to reproduce
1. Open view
2. Move and hold mouse over a long Notification

### Server configuration
Operating system:
Debian
Web server: 
Apache
Database:
Mysql
PHP version:
7
Nextcloud version:
12

### Client configuration
Client version:
2.3.3beta (build 1) bulid on git revision 57bc79
Operating system:
Windows 10
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):
5.6.2
Installation path of client:
Default

**Comment by DominiqueFuchs** [comment]
Closing this as this is no longer applicable with the new activity tab with client version >= 2.5
