### ISSUE TITLE
Folders and files automatically deleted

### ISSUE THREAD

**Issue by jeanmartin13** [nextcloud/desktop#5400]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Every one or two hours my synchronized files are deleted. I have to restore them from teh deleted files n the web admin page. And I have message in the desktop app saying I deleted those folders, which I never did.

### Steps to reproduce

Nothing perticular to reproduce. Just wait one or two hours and the files and folders are deleted except the "talk" folder.

### Expected behavior

Normally the synced folders or files shlouldn't deleted...

### Which files are affected by this bug

All forlders except talk

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11, Ventura 13.1 and Uuntu 22.04.1

### Package

Appimage

### Nextcloud Server version

Nextcloud Hub 3 (25.0.3)

### Nextcloud Desktop Client version

3.6.6git (build 13475)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[nextCloudClientdebug.zip](https://github.com/nextcloud/desktop/files/10614136/nextCloudClientdebug.zip)

**Comment by jeanmartin13** [comment]
It appens on all the computers I installed nextcloud on. I don't administrate nextcloud myself, this is donne by my web hosting provider (O2switch)

**Comment by jeanmartin13** [comment]
[nextCloudClientdebug.zip](https://github.com/nextcloud/desktop/files/10614141/nextCloudClientdebug.zip)

**Comment by joshtrichards** [comment]
Hi @jeanmartin13 - Are you still experiencing this?

**Comment by claucambra** [comment]
Hello, since no new info has been provided for a few months I will go ahead and close the issue. If the issue reappears, please do reopen the issue and we will take a look into it
