### ISSUE TITLE
[Bug]: 3.7.1 Fileshare dialogue stuck

### ISSUE THREAD

**Issue by Id3aFly** [nextcloud/desktop#5411]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog takes forever to load (in sharing tab) and does not allow to share the file. The wheel is turning and turning (and not doing anything)
![grafik](https://user-images.githubusercontent.com/5712180/217250903-a393a4a6-a7f3-4c29-9675-b18e24bb6a6f.png)

However, the activity tab is working without any issues:
![grafik](https://user-images.githubusercontent.com/5712180/217251131-f154b9f2-279b-4541-a011-bde039035b4e.png)

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display any clickable option, instead the loading wheel is turning forever.
...

### Expected behavior

When clicking on the share dialog, there should be options that allow to share
...

### Which files are affected by this bug

All (e.g. EnglischBewerbungen.zip)

### Operating system

Windows

### Which version of the operating system you are running.

Win 11

### Package

Appimage

### Nextcloud Server version

24.0.8

### Nextcloud Desktop Client version

3.7.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @Id3aFly I was unable to reproduce across multiple accounts and servers with different versions. Did you face the same issue in versions 3.6.x of the desktop client?

If possible, could you also provide a debug archive? thanks!

**Comment by Jerome-Herbinet** [comment]
**I confirm** that this problem occurs in **Windows 11**.
**It also occurs under GNU/Linux** (Ubuntu 20.04 and 22.04 with Gnome and KDE D.E.).
**I'll try to give you some feedback under Windows 10 and OSX.**

![thumb-Clipboard - 9 février 2023 10_15](https://user-images.githubusercontent.com/33763786/217770642-4b75b785-92e2-4e8c-a0f9-2e1a2ff6326a.png)
![thumb-Clipboard - 9 février 2023 09_33](https://user-images.githubusercontent.com/33763786/217770649-daf41ca2-1e50-439d-a66f-024867bc165a.png)
![2023-02-09_10-25](https://user-images.githubusercontent.com/33763786/217771758-a03ab4fa-5394-4e74-a49e-02ae5fcee72a.png)

**Comment by Jerome-Herbinet** [comment]
I've noticed that the problem only occurs with Nextcloud 25 (not with NC 24 for example).

**Comment by Jerome-Herbinet** [comment]
@Id3aFly I think you should rename this issue by removing the Win 11 mention because the problem occurs whatever the used OS. The problem seems to occur only with NC 25 ... but not on every instance. I've just made some tests a few minutes ago. The bug occurs with some test and production instances at work but not with my private instance. Some of my colleagues have the same conclusion : not working with our work instance but not with their personal instance. Very strange. Ive also made a test with LDAP and local user. No behavior difference.
cc : @claucambra

**Comment by claucambra** [comment]
@Jerome-Herbinet If possible, could you also provide a debug archive? thanks!

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet If possible, could you also provide a debug archive? thanks!

@claucambra 
[debug_archive.zip](https://github.com/nextcloud/desktop/files/10697941/debug_archive.zip)

**Comment by dzidek23** [comment]
Came to say that this is not only limited to either Windows 11 or NC25.
I updated the Desktop Client to 3.7.1 x64 on Windows 10 21H2 and with Nextcloud 24.0.9 
Exactly same issue with share settings rotating but not loading.

**Comment by marcosvfc** [comment]
Still not working after last update to Desktop Client 3.7.3 x64 on Windows 11 22H2 and Nextcloud Server 25.0.3. Same issue as described before by others.

**Comment by Id3aFly** [comment]
I removed the "windows" reference in the title.
I don't think this issue occurred in 3.6.x for me, otherwise I would have reported it here.
I will upload logs on the weekend.

Interesting to note is, I use the virtual file feature. What about the others? Do you use this as well or do you regularly sync?

**Comment by dzidek23** [comment]
I use virtual folders but I noticed something interesting. 

![Capture5](https://user-images.githubusercontent.com/70292029/218046315-84147458-2fa4-421a-a80c-7e6d006960f1.PNG)

Although the whole folder has 137MB on the drive nextcloud client does not see that at all.

**Comment by Jerome-Herbinet** [comment]
Test done with the last **3.7.3** release (AppImage for GNU/Linux ; I use Ubuntu 20.04 LTS) : same issue.

![2023-02-10_09-54](https://user-images.githubusercontent.com/33763786/218047207-4bfd6097-3054-4310-8e82-7635b9df07fb.png)

**Comment by Id3aFly** [comment]
@claucambra I just recognized the automatically created debug archive contains private data, as the hostnam and the filenames / paths as well. Is there any way to remove these pieces of information or send it to you privately?

**Comment by EddyLB** [comment]
Same issue with the macOS client 3.7.3 and one Nextcloud server 25.0.3 amongst 7.
I can create a temporary account for debugging is that helps.

**Comment by JohanBoshoffWebAware** [comment]
I also have exactly the same issue on the latest Desktop Client version 3.7.3 on Windows 10 running Nextcloud 24.08.  The previous Desktop version worked just fine.  Since the latest Desktop version all my clients face the same issue, whether they are on Win 10 or Win 11.

Is there any fix available yet?  What else can I provide to assist with this issue?

**Comment by claucambra** [comment]
Hi all, we have a likely fix for the issue here with PR #5442

Those of you on Linux can try the following build including the fixes: https://github.com/nextcloud-desktop-bot/ci-builds/releases/download/PR-5442/nextcloud-PR-5442-af0349c3fa863c2afd71a52226d4cde2c737b1f2-x86_64.AppImage

Please let me know if this fixes the issue :)

**Comment by narcisgarcia** [comment]
Server Nextcloud 31
Client nextcloud-desktop 3.7.3 on Debian GNU/Linux 12 (Stable)

![Image](https://github.com/user-attachments/assets/f803310f-c5c4-4bb0-a5dd-bc896285d4a5)
As it's said here https://help.nextcloud.com/t/desktop-client-3-7-x-share-options-not-working/156136 Client version 3.7.4 fixes problem, but:
¿How do I update nextcloud-desktop and nautilus-nextcloud in Debian 12?
