### ISSUE TITLE
[Bug]: nextcloud after update to 3.7.1 : error while loading shared libraries: libKF5Archive.so.5: cannot open shared object file:

### ISSUE THREAD

**Issue by Emporea** [nextcloud/desktop#5414]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
nextcloud is not starting since update to 3.7.1
When launching from terminal this error is displayed:
nextcloud: error while loading shared libraries: libKF5Archive.so.5: cannot open shared object file:

### Steps to reproduce

install 3.7.1
open
see that nothin opens
...

### Expected behavior

it should work as intened

### Which files are affected by this bug

/

### Operating system

Linux

### Which version of the operating system you are running.

arch - endevouros

### Package

Distro package manager

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jodhus** [comment]
I can confirm I had the same error on Artix Linux (an Arch derivative) and I was able to fix the dependency issue by installing the "karchive" package.

**Comment by jodhus** [comment]
@Emporea: I believe it was an added dependency that wasn't documented so the Arch package wasn't updated to reflect it. See issue #5415 -- macOS users hit the same problem it seems.

**Comment by fabiscafe** [comment]
It was a downtream packaging error

This can be closed, see https://bugs.archlinux.org/task/77423

**Comment by allexzander** [comment]
Fixed in 3.7.3
