### ISSUE TITLE
[Bug]: nextcloud app crashes after update to 3.7.1 

### ISSUE THREAD

**Issue by maffi-git** [nextcloud/desktop#5415]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud app crashes after latest update to 3.7.1 because of a missing library on macOS 10.15.7 -> see crash log excerpt below. 

I tried to install the previous version over it, but still no luck there. 
Deleted Nextcloud and did a fresh install of new version. Still crashes. 
Deleted Nextcloud and did a fresh install of 3.6.6 - Nextcloud works again. Maybe a build-error? 

Here is the start of the error report: 
Process:               Nextcloud [844]
Path:                  /Applications/nextcloud.app/Contents/MacOS/Nextcloud
Identifier:            com.nextcloud.desktopclient
Version:               3.7.1git [build 13765] (3.7.1.13765)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Nextcloud [844]
User ID:               501

Date/Time:             2023-02-07 18:27:32.774 +0100
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/liblzma.5.dylib
  Referenced from: /Applications/nextcloud.app/Contents/Frameworks/libKF5Archive.5.dylib
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs

### Steps to reproduce

1. Update or install 3.7.1 over previous version on macOS 10.15.7

### Expected behavior

No crash

### Which files are affected by this bug

liblzma.5.dylib

### Operating system

Mac OS

### Which version of the operating system you are running.

10.15.7

### Package

Appimage

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.1

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by cwesterfield** [comment]
I am also having this issue on 10.15.7. Same error in the console.

**Comment by FesTGig** [comment]
I have the same issue on 11.7.1

**Comment by Bigwaf** [comment]
Same here on MacOS 10.14.6

**Comment by claucambra** [comment]
Hi all, the cause seems clear but I am having rouble reproducing -- did you update via the updater or via downloading and installing the .pkg? Does installing the .pkg make the issue go away?

**Comment by claucambra** [comment]
For this I would say remove Nextcloud.app completely and then reinstall, see if this works

> > Hi all, the cause seems clear but I am having rouble reproducing -- did you update via the updater or via downloading and installing the .pkg? Does installing the .pkg make the issue go away?
> 
> I started with the updater, and when it didn't start I downloaded the 3.7.1 pkg. That didn't work. I downloaded the 3.6.6 pkg, and that also will not start.

**Comment by Bigwaf** [comment]
Hi claucambra,
here's what I did on my 10.14.6 machine:

- searched for all files with "nextcloud" in their name
- put them to trash
- emptied trash
- installed "Nextcloud-3.7.1.pkg"
- didn't work

- searched for all files with "nextcloud" in their name
- put them to trash
- emptied trash
- installed "Nextcloud-3.6.6.pkg"
- worked again

**Comment by wilya7** [comment]
> For this I would say remove Nextcloud.app completely and then reinstall, see if this works

I had the same problem, MacOS 10.14.6. I did remove all files and .plist concerning nextcloud using AppCleaner, rebooted. Reinstalled from scratch 3.7.1, same crash. Deleted again the app with AppCleaner, installed 3.6.6 (no reboot) it worked again.

**Comment by wilya7** [comment]
> I started with the updater, and when it didn't start I downloaded the 3.7.1 pkg.
> That didn't work.
> I downloaded the 3.6.6 pkg, and that also will not start.

I had initially the same problem. I Tried again, this time using AppCleaner  to clean up any file remaining other then Nexcloud, rebooted (so to be sure there are no Nextcloud processes running in the background) and reinstalled 3.6.6. 

It worked.

**Comment by claucambra** [comment]
Glad to hear at least 3.6.6 is still working.

We are working on a fix for the issue with the library, but for now deleting 3.7.1 and reinstalling 3.6.6 should fix issues. Will update with more soon

**Comment by mrx234** [comment]
Reinstalling 3.6.6 over 3.7.1 did not work for me too, Cmd-I still reported "3.7.1git" for the NC app, even *after* reinstalling! Finally, moving 3.7.1 to the trash and installing 3.6.6 did the job ;)

**Comment by peter-rindfuss** [comment]
With MacOS Big Sur 11.7.3, neither 3.7.0 nor 3.7.1 do work. I was able to re-install 3.6.6 which is ok.

**Comment by argoso** [comment]
Confirm - 3.7.1 not working (on osx 10.15.7), rollback to 3.6.6 works again.

**Comment by claucambra** [comment]
Hi folks, we have built a test version of 3.7.1 with some changes to the bundled KArchive dependency. 

We are looking for feedback on this test package from those affected by the crash on launch -- this package can be downloaded here:

https://cloud.nextcloud.com/s/iqbHG2Yb5yRFTAB

Please let us know if the crash is still present!

**Comment by stjeanp** [comment]
@claucambra - I'm running MacOS 11.7.2 - just installed that new build and it did start up and I'm syncing again.

**Comment by argoso** [comment]
> Hi folks, we have built a test version of 3.7.1 with some changes to the bundled KArchive dependency.
> 
> We are looking for feedback on this test package from those affected by the crash on launch -- this package can be downloaded here:
> 
> https://cloud.nextcloud.com/s/iqbHG2Yb5yRFTAB
> 
> Please let us know if the crash is still present!

Yes, that's works!

**Comment by 1837456** [comment]
Unfortunately not for me, running MacOS 10.14.6:

/Applications/Nextcloud.app/Contents/MacOS/Nextcloud --logwindow
dyld: Library not loaded: @loader_path/libzstd.1.dylib
  Referenced from: /Applications/Nextcloud.app/Contents/Frameworks/libKF5Archive.5.dylib
  Reason: no suitable image found.  Did find:
	/Applications/Nextcloud.app/Contents/MacOS/../Frameworks/libzstd.1.dylib: cannot load 'libzstd.1.dylib' (load command 0x80000034 is unknown)
	/Applications/Nextcloud.app/Contents/Frameworks/libzstd.1.dylib: cannot load 'libzstd.1.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

**Comment by globul69** [comment]
Works fine for me with this new package on Mac OS 11.7.3
Thanks.

**Comment by luisinui** [comment]
I just tried the new package and it worked for me.
Using MacOS V11.7.2

**Comment by claucambra** [comment]
Great to hear this is fixing the issue for a lot of you :)

@1837456 Could you test this new package? I have made some additional modifications that might fix your issue

https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

**Comment by akaster** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Great, thanks. 
Works for me on MacOS 11.7.3

**Comment by StudioBeneden** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Works on MacOs 10.15.7, thank you!

**Comment by mediaxtend** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Works on macOS 11.6.6.
Thanks!

**Comment by 1837456** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Yes, it's working with this package. Thank you very much!

**Comment by marcintosch** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Can confirm, works again on macOS 11.6.8, thanks 👍

**Comment by mrx234** [comment]
> Great to hear this is fixing the issue for a lot of you :)
> 
> @1837456 Could you test this new package? I have made some additional modifications that might fix your issue
> 
> https://cloud.nextcloud.com/s/4KnANRdRAMq26J9

Works on 10.14.6, great!

**Comment by ericbrun-73** [comment]
Thank you ! Work on 11.7.3 again.

**Comment by wilya7** [comment]
MacOS 10.14.6, bug fixed. Thank you so much for your work.

**Comment by peter-rindfuss** [comment]
Works on 11.7.3. Thank you.

**Comment by Flaschenzug** [comment]
> Hi folks, we have built a test version of 3.7.1 with some changes to the bundled KArchive dependency.
> 
> We are looking for feedback on this test package from those affected by the crash on launch -- this package can be downloaded here:
> 
> https://cloud.nextcloud.com/s/iqbHG2Yb5yRFTAB
> 
> Please let us know if the crash is still present!

Oh yes, finally. Thank you so much for the fix!

**Comment by Flaschenzug** [comment]
> Hi folks, we have built a test version of 3.7.1 with some changes to the bundled KArchive dependency.
> 
> We are looking for feedback on this test package from those affected by the crash on launch -- this package can be downloaded here:
> 
> https://cloud.nextcloud.com/s/iqbHG2Yb5yRFTAB
> 
> Please let us know if the crash is still present!

Oh yes, finally it work's again. Thank you so much for the fix!

**Comment by allexzander** [comment]
we rebuilt the desktop client now with proper **karchive** and it is out with 3.7.2 release, let us know if that fixes the issue

**Comment by REggleston27** [comment]
3.7.2 seems to work fine, Thank you
Will keep an eye on it for the next few days and report anything odd

**Comment by jonjonw** [comment]
The issues seems to be back in the 3.7.3 release.

**Comment by peter-rindfuss** [comment]
> The issue seems to be back in the 3.7.3 release.

I cannot confirm this. 3.7.3 works well for me on macOS 11.7.3.

**Comment by wilya7** [comment]
MacOS 10.14.6, just updated to 3.7.3 from inside the app. Everything works as expected.

**Comment by jonjonw** [comment]
> The issue seems to be back in the 3.7.3 release.

I re-installed and it seems to be working now.

**Comment by maffi-git** [comment]
Thank you for fixing! I did the update today and it works again.
