### ISSUE TITLE
[Bug]: German translation of view chat (Chat ansehen) is too long for the button

### ISSUE THREAD

**Issue by binford6000** [nextcloud/desktop#5418]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The german translation of "view chat" (Chat ansehen) is too long for the correspondent button.

### Steps to reproduce

1. Click on the Client icon in menu bar
2. Scroll to a Talk chat

### Expected behavior

German translation and button are displayed correctly.

### Which files are affected by this bug

none

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura 13.2

### Package

Other

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Additional info

<img width="459" alt="grafik" src="https://user-images.githubusercontent.com/29679540/217545867-2d4b9b3c-6f94-4db6-b77f-0211ffd22f4f.png">

**Comment by joshtrichards** [comment]
Fixed via #5275
