### ISSUE TITLE
Desktop app keeps asking for login details each time it starts. (SSO)

### ISSUE THREAD

**Issue by Ryonez** [nextcloud/desktop#542]
The desktop app is essentially unusable when you use SSO to authenticate users.

If you close the app, you **have** to sign in again when you start it next time.
I use an app password for my android client, and that works well. Can't use app passwords for the desktop app, so that option is out.
I've also tried using direct sign on, but all that does is open a broken web page:
![image](https://user-images.githubusercontent.com/16157130/43994505-3917d168-9df2-11e8-91d4-7be405f963cc.png)
Direct Sign on isn't really a solution either, as I have my users use SSO.

I plan to use Nextcloud long term to back up and share important files for my computers, but needing to get my password to sign on each time is a large annoyance for something that shouldn't be asking for it.

The quickest fix I can think of is to allow the use of app passwords for the desktop app.
Some additional info.

Nextcloud Server Version: 13.0.5
Nextcloud Desktop Version: 2.3.3
Keycloak Server Version (SSO): 4.1.0.Final (Community)

**Comment by Ryonez** [comment]
Any ideas? It's been over a week, and this seems like a somewhat critical issue, as the desktop app in not usable.

**Comment by Ryonez** [comment]
This seems to be related to https://github.com/nextcloud/user_saml/issues/167#issuecomment-415744111

Leaving the issue open as this is specific to the desktop client.

**Comment by claell** [comment]
Is this still happening?

**Comment by lenalebt** [comment]
Still happening for me - on 2.6.4 client, with Xfce (Linux). It's quite annoying, not only because I have to log in every time, but also because it keeps creating app passwords on the server, it just does not use them over computer restarts:
![grafik](https://user-images.githubusercontent.com/697104/78389563-34acfe80-75e3-11ea-80ff-4bdc681779be.png)

**Comment by claell** [comment]
Also this might be related to #1292. Have you tried whether it works with normal login to make sure this is only happening with SSO?

**Comment by lenalebt** [comment]
I cannot disable the SSO currently, but before I turned SSO on, this _was_ working correctly - albeit with an older version of the client.

**Comment by MarcusE1W** [comment]
I use a normal password and it does not work for me. I have to sign in again every time using LXQt.

Curiously if I use KDE on the same laptop it works.

**Comment by claell** [comment]
@MarcusE1W Let's track that in #1292. I was rather asking, whether this issue with SSO might be related or have the same cause. But for that probably only users who can test both cases or who have issues with SSO can provide useful feedback.
