### ISSUE TITLE
[Regression][bug]: Sync status is not available for libcloudproviders starting with 3.7 series

### ISSUE THREAD

**Issue by fabiscafe** [nextcloud/desktop#5426]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After the upgrade from 3.6.6, to 3.7.1 the sync status in nautilus on linux got stuck. It appears to never stop syncing. With 3.6.x the circular arrows would disappear after the sync was done.
![grafik](https://user-images.githubusercontent.com/18744080/218035170-0fc4f0bb-d1b1-487e-a861-3ffca34435c2.png)

I can confirm that the sync actually is complete for all of the folders. A reset of nextcloud-client and readding of the accounts didnt helped. This behavior is the same on all (4) of my PCs.

### Steps to reproduce

1. make sure to run nextcloud 3.7.x with libcloudproviders support enabled
2. start nextcloud
3. start nautilus or a GTK file dialog

### Expected behavior

The sync icon should disappear after the sync was completed

### Which files are affected by this bug

Doesnt apply here

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

https://github.com/nextcloud/desktop/commit/61c792c6f4be4083292cef3d963b8ae4557465a7 # fully qualify types in signals and slots
Seems to be the cause of this regression.

**Comment by fabiscafe** [comment]
After a bit of bisecting. I was able to track down the commit.

Last working commit was
401a7778bbc73c014a82aa1bc6096762f6821da6 # [tx-robot] updated from transifex 
[This commit as zipped for archlinux](https://github.com/nextcloud/desktop/files/10710585/nextcloud-client-for-archlinux.zip)

First broken commit was
61c792c6f4be4083292cef3d963b8ae4557465a7 # fully qualify types in signals and slots
[This commit as zipped for archlinux](https://github.com/nextcloud/desktop/files/10710598/nextcloud-client-for-archlinux.zip)

Le'me shameless ping @mgallien in the hope for help.

**Comment by fabiscafe** [comment]
I'm unable to revert this [commit](https://github.com/nextcloud/desktop/commit/61c792c6f4be4083292cef3d963b8ae4557465a7) for testing. Sadly I'm not capable of any programming language to understand the code and fix it myself. :smiling_face_with_tear:

**Comment by mgallien** [comment]
@fabiscafe thanks for reporting and sorry for the trouble
I think I have found the source of the error
not being very familiar with the nautilus and nextcloud integration, I will try to test, but it would be nice if you could also test it
once I have done it, I will link a PR here and that should provide an AppImage for you to test

**Comment by mgallien** [comment]
@fabiscafe please test the AppImage once built from #5451

**Comment by fabiscafe** [comment]
The appimage didn't worked (it doesn't do a thing on start, no visible window no command output on the shell) but I build it myself

I patched current master (ec7fd9542c95d6ca4963f43fc817a6796043d039) as well as 3.7.3 (5f9fa597ee8bb988eae7cab44e6dee674a510554) with your patch and indeed, it shows the sync status again. :+1:  That's awesome!

**Comment by mgallien** [comment]
> The appimage didn't worked (it doesn't do a thing on start, no visible window no command output on the shell) but I build it myself
> 
> I patched current master ([ec7fd95](https://github.com/nextcloud/desktop/commit/ec7fd9542c95d6ca4963f43fc817a6796043d039)) as well as 3.7.3 ([5f9fa59](https://github.com/nextcloud/desktop/commit/5f9fa597ee8bb988eae7cab44e6dee674a510554)) with [your patch](https://patch-diff.githubusercontent.com/raw/nextcloud/desktop/pull/5451.patch) and indeed, it shows the sync status again. +1 That's awesome!

Thanks for the feedback
I am going to need to test this AppImage
