### ISSUE TITLE
[Bug]: Automatically check for updates setting has no effect on macOS

### ISSUE THREAD

**Issue by briankendall** [nextcloud/desktop#5429]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Even after turning off "Automatically check for updates" in Nextcloud's settings, the user will still get pestered by automatic update notifications.

This is related to #5077 and #4711. Neither of those issues were apparently ever properly resolved, even though they are closed.

### Steps to reproduce

1. Turn off "Automatically check for updates"
2. Wait for an update to become available
3. Note that you receive a notification for it even though the setting is turned off

### Expected behavior

Naturally there should be no update notifications when this setting is not checked

### Which files are affected by this bug

N/A

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 10.14 - macOS 12.6.2

### Package

Other

### Nextcloud Server version

N/A

### Nextcloud Desktop Client version

3.7.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Unfortunately due this bug only being verifiably present when there is an update available, it is therefore impossible for me to confirm whether it's present in the latest version of Nextcloud!

However I have experienced it in Nextcloud 3.7.x.

**Comment by claucambra** [comment]
Hi, I wasn't able to reproduce this bug on a copy of 3.7.x. Do you have any logs from when this happens? (or could you provide them the next time this happens?) Could you check if your `nextcloud.cfg` has `skipUpdateCheck` set to false? Thanks!

**Comment by Tegenwind** [comment]
Hi! Thanks for looking into this again :)

Here's a log from my test setup on version 3.7.3. I've left the update notification window open while generating the debug.
[NC373_debug.zip](https://github.com/nextcloud/desktop/files/10943333/NC373_debug.zip)

This is with 'skipUpdateCheck=true', we also have clients using the older 'autoUpdateCheck=false' but the result is the same. In the GUI the update check shows as disabled (or doesn't show at all), but the update still gets offered.

Let me know if there's anything else I can check or provide!

**Comment by SEwebm** [comment]
+1

**Comment by claell** [comment]
I have a similar problem on Windows, I guess: #5639

**Comment by Tegenwind** [comment]
Can confirm, issue is still not fixed.

**Comment by hackt1sch** [comment]
The error still occurs and is particularly annoying as I have to roll out the client updates via MDM. In my case, the user is always asked for an update which he cannot install due to a lack of update admin rights and I cannot switch it off.
