### ISSUE TITLE
Desktop Client App Password for TOTP

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/desktop#543]
When using the Windows Desktop Connection Wizard to log into Desktop Client, I need to use TOTP.

There is a "Click Here" link in the Nextcloud Connection Wizard to request an app password from the Nextcloud web interface.

The link does NOT work as expected…
I am expecting the link to send to `https://*/nextcloud/index.php/settings/user/security`
Instead, the link sends to `https://.../nextcloud/index.php/apps/files/?dir=/&fileid=131`

![image](https://user-images.githubusercontent.com/8312560/43994825-1a106ca2-9d58-11e8-89cf-cc47fd56b726.png)

**Comment by snakyjake1** [comment]
Version 2.3.3 (build 1) for Windows.

**Comment by jayma777** [comment]
Ditto from Nextcloud-2.3.3-x86_64.AppImage w/ TOTP enabled.   

"Click Here" redirects to https://<server>/index.php/apps/files/?dir=/&fileid=7

Copy Link Location from the appimage Client yields:  
`https://<server>/index.php/settings/personal?sectionid=security#apppasswords`

Even copy/paste that link into the browser redirects to the same location.

Is there a solution / workaround for this?
