### ISSUE TITLE
[Bug]: No upload to shared folder possible

### ISSUE THREAD

**Issue by RobinGFT** [nextcloud/desktop#5439]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The new rewritten share dialogue has no option to allow the file upload for users, that can only access the folder per shared link. So far so good, this can be planned and there is the option to "Allow editing". But this doesn't allow the users to upload files. 
However in the webview i have the option to allow file uloads and everything is working fine.

Screenshot in german attached, official nextcloud video to view the dialogue: https://nextcloud.com/de/blog/desktop-client-3-7/ 

![image](https://user-images.githubusercontent.com/40017951/218980634-98a676d3-655e-48b0-a2b2-76d7695c1340.png)

### Steps to reproduce

1. Right click on the folder
2. Click on Share Options
3. The share dialog does not display the option to upload files
4. The option "Allow editing" does not allow uploads

### Expected behavior

When clicking on the share dialog, "Allow file uploads" should be an option.
Otherwise the upload should be allowed with the option "Allow editing"

### Which files are affected by this bug

Folders

### Operating system

Windows

### Which version of the operating system you are running.

Win 10

### Package

Appimage

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Fixed in #5622/#5631 (released in v3.8.2)
