### ISSUE TITLE
Desktop app Widget show mobile view of other apps

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/desktop#5449]
I know that for NextCloud everything is online and you can do the stuff at the web browser. Therefore you have at the desktop app links to all installed apps, like Talk, Task, ...

The issue I have is that this links are nice but not really usefull. 

If I can click for example to the task app the webbrowser open the task app online. But I only want to add there an task or close one. 

If the desktop app widget would show when click on talk, tasks, ... the mobile view of the webpage inside the app. I can do the stuff inside the app. This is what I want and not open the webpage. Therefore I can use the browser direct.

**Comment by Andreas-Kainz** [comment]
Left mobile view
Right mobile view inside the desktop widget

![2023-02-17 10_04_30-Window](https://user-images.githubusercontent.com/8517736/219602428-fd0b6209-e38d-4cc6-8fef-3d37a57fcfb0.png)

**Comment by Rello** [comment]
Hello,
the desktop clients are only focused on syncing and will not include app related features
