### ISSUE TITLE
[Bug]: Client needs reauthentification at each reboot / launch

### ISSUE THREAD

**Issue by Hudratronium** [nextcloud/desktop#5457]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Each reboot / relaunch of the desktop client needs to reauthenticate at the server.
Also the client is, as to be expected, added to the list of clients, resulting in a huge list of entries.

### Steps to reproduce

1.     Start nextcloud client first time
2.     Browser opens that requests login
3.     Authenticate
4.     Close client
5.     Open client

### Expected behavior

After launch the client connects with the stored credentials / app-password to the server.

### Which files are affected by this bug

None

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro

### Package

Other

### Nextcloud Server version

25.0.3.2

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Correlating warings from log-file:
`[ warning nextcloud.sync.credentials.keychainchunk /home/user/src/libsync/creds/keychainchunk.cpp:360 ]:	Unable to read "***_clientCertificatePEM:https://***/:0" chunk "0" "Password entry not found"`
`[ warning nextcloud.sync.credentials.keychainchunk /home/user/src/libsync/creds/keychainchunk.cpp:360 ]:	Unable to read "***_clientKeyPEM:https://***/:0" chunk "0" "Password entry not found"`
`[ warning nextcloud.sync.credentials.webflow C:\Users\sysadmin\AppData\Local\Temp\windows-13808\client-building\desktop\src\gui\creds\webflowcredentials.cpp:484 ]:	Unable to read client key "Password entry not found"`
`[ warning nextcloud.sync.credentials.webflow C:\Users\sysadmin\AppData\Local\Temp\windows-13808\client-building\desktop\src\gui\creds\webflowcredentials.cpp:525 ]:	Unable to read client CA cert slot "0" "Password entry not found"`

**Comment by tflidd** [comment]
> ### Package
> 
> Other

You downloaded the installer from the homepage, right?

The locations it is looking for the config files look a bit strange, it shouldn't be a temporary folder which might explain why it doesn't find anything. Are there config files at the default locations? -> https://docs.nextcloud.com/desktop/3.7/advancedusage.html#configuration-file

In such a case, you could start the client from command line giving the folder of the config file (just a bit further up the document).

**Comment by Hudratronium** [comment]
@tflidd 
Thanks for your suggestion.
I checked the config-files and they are stored at the expected folder  `%APPDATA%\Nextcloud\nextcloud.cfg` .
How ever - looking into the logfiles again: It seems that the user-directory is somewhat bogus.
`C:\Users\sysadmin\...` - there is no user "sysadmin" in the whole system.

Just for the sake of information:
I started the installation with a 'non-admin' account. Afterwards UAC pops up and requests elevated admin-rights for installation. so far that worked like a charm.

**Comment by Hudratronium** [comment]
@tflidd 
The client runs normally on my user account.

**Comment by OlegHahm** [comment]
I have the same issue on Arch Linux.

**Comment by joshtrichards** [comment]
Closing since OP's issue was addressed.

@sibu7 & @OlegHahm: Unless you're on Windows and have the same log entries, look elsewhere as this issue is unrelated.

**Comment by serge-vk** [comment]
The same issue is observed with NextCloud AppImage on Ubuntu 24.04 after the last update to 3.14 a few days ago. The previous version worked normally without any issue. Moreover,  this last update created another problem: after a while if I try opening the settings or the main dialogue, NextCloud freezes and then crashes.
