### ISSUE TITLE
2 different wordings "Edit" and "Open in browser" for one same action (it seems weird and apparently useless)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#5460]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
My request is not for a new feature, but rather a question and a need to rationalise two formulations that lead to the same action. 

From Windows Explorer for example, when you right click to access Nextcloud features, you get : 
- Edit (for "md" files)
- Open in browser (for "odt" files and other such files)

In both cases, this opens the file in the browser ... opening Nextcloud Text for one and Collabora Online (Nextcloud Office) for the other. 

Unless there is an interest in using two different labels that I would not be aware of, I propose to keep only one label for all identical actions, whatever the type of file. This simplifies things, but above all makes them easier to understand (= improved consistency = improved UX).

Explanation screenshots : 

"md" files ("Modifier" in French =  "Edit" in English) : 
![2023-02-22_14-46](https://user-images.githubusercontent.com/33763786/220640766-98b70e7d-ddd3-4a37-a01d-2d7d1b2d88f6.png)

"odt" files ("Ouvrir dans le navigateur" in French =  "Open in browser" in English) : 
![2023-02-22_14-44](https://user-images.githubusercontent.com/33763786/220640832-791811eb-9c50-46d2-b29e-141545602cea.png)

**Comment by nimishavijay** [comment]
Makes sense to me! Both can be unified to "Open in browser" :)

**Comment by jancborchardt** [comment]
Yep, agree with @nimishavijay :)
