### ISSUE TITLE
Search box gets stuck after running the client for some hours

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#5469]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The NC Client search box becomes unresponsive after running the client for some hours (4+ hrs)

The issue appears to happen randomly.

This is also noticed when the computer is hibernated and powered on.

### Steps to reproduce

https://user-images.githubusercontent.com/86367839/221001029-b341abb0-8bc8-4a64-abdd-954fab07b5bf.mp4

### Expected behavior

The NC Client search box should be responsive

### Which files are affected by this bug

NC Client

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Distro package manager

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @vagner-dias - Thanks for the report. Are you still experiencing this?

**Comment by vagner-dias** [comment]
> Hi @vagner-dias - Thanks for the report. Are you still experiencing this?

Hi @joshtrichards - it is fixed here. Thank you!
