### ISSUE TITLE
Error at compilation

### ISSUE THREAD

**Issue by florealcab** [nextcloud/desktop#547]
I try to compile, but it fails with master or 2.5.0-beta1 tag.

This is the error I have:

/home/####/builds/desktop/src/gui/wizard/owncloudsetuppage.cpp:27:10: fatal error: QtSvg/QSvgRenderer: No such file or directory
 #include <QtSvg/QSvgRenderer>
          ^~~~~~~~~~~~~~~~~~~~

How to fix it?

**Comment by tabp0le** [comment]
We need more info. What OS are you compiling on? What OS are you compiling for? What version of QT, OpenSSL, etc? 

At first glance though, it appears you are missing somr dependencies.

**Comment by florealcab** [comment]
I am using KDE Neon (based on Ubuntu 18.04). I compile for it.
Qt version: 5.11.1
openssl version : 1.1.0g
KDE version : 5.13.4 (compiled with dolphin support)

Compiled without libcloudproviders, is it a problem ? Also without inotify, sphinx and pdflatex.

Here the output of my cmake:

[logs.txt](https://github.com/nextcloud/desktop/files/2282794/logs.txt)

Please tell me if you cant other informations.

**Comment by tabp0le** [comment]
@florealcab No, you don't need libcloudproviders, inotify, sphinx or pdflatex for a successful build.

Additionally, those are not actually errors in your build log. Your makefile build is successful. Now you just have to run: $ make install

**Comment by Lartza** [comment]
You need libqt5svg5-dev

**Comment by florealcab** [comment]
@Lartza thank you, I install it and now build pass!

If it's needed for anyone, here is all packages I install on ubuntu 18.04 (sames in 16.04) for make it working with dolphin integration:
libzip-dev
qtdeclarative5-dev
libqt5webengine5-dev
qt5keychain-dev
sqlite3
libsqlite3-dev
libqt5svg5-dev
libkf5config-dev
kio-dev extra-cmake-modules

If you don't need dolphin integration, just skip the two last ones. Note that I skip all optional dependencies except the ones for dolphin (as I only want this optional feature).

I close the ticket as it's solved!

**Comment by camilasan** [comment]
I will update the wiki with this info. Thanks @florealcab !

**Comment by camilasan** [comment]
Updated: https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client :)
