### ISSUE TITLE
[Bug]: Share dialog exhibits infinite loading when link shares are disabled on the server

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#5470]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Separate issue from #5411

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not finish loading

### Expected behavior

Share dialog should work even if link shares are disabled on the server

### Which files are affected by this bug

All shareable files

### Operating system

Mac OS

### Which version of the operating system you are running.

13.2

### Package

Other

### Nextcloud Server version

23.0.12

### Nextcloud Desktop Client version

3.7.X

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshxplore** [comment]
I'm experiencing the same problem on Windows 10 Build 19045.
Selecting "Sharing Options" on the explorer context menu results in an infinite loading screen in the sharing dialog window.

**Comment by claucambra** [comment]
> I'm experiencing the same problem on Windows 10 Build 19045. Selecting "Sharing Options" on the explorer context menu results in an infinite loading screen in the sharing dialog window.

A temporary workaround while the fix is reviewed is to make sure public link shares are enabled and that Resharing is enabled in the Default Share Permissions
