### ISSUE TITLE
[Bug]: Nextcloud application is loading every file when folder is being opened

### ISSUE THREAD

**Issue by christopherjoined** [nextcloud/desktop#5471]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Everytime I open a folder that is being synchronized with my cloud, all files and folders in this folder seem to be loading new.
To be precise, I open the folder and can see the names of the files for a splitsecond, then the titles disappear one at a time and only the icons are visible. After a second all filenames appear back and are usable again.

I tried reinstalling Nextcloud, that didn't make a difference.
![Screenshot (8)](https://user-images.githubusercontent.com/126245387/221159839-8d9165c2-402f-43fa-bd00-12cc8140a8c5.png)

The issue may be related to this one https://github.com/nextcloud/desktop/issues/5404

### Steps to reproduce

I don't know why it happens, it started happening after one of the latest Nextcloud Updates. So I don't know how to reproduce.

### Expected behavior

The files should appear all and shouldn't need time to load.

### Which files are affected by this bug

all in one of my main folders

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

unknown

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by anonbergine** [comment]
I also encounter this issue on Windows 10 with both server and desktop client on latest stable (server updated yesterday, client updated a few days ago).

Upon opening a folder and I have to wait like 30 seconds or more for it to do whatever it's doing before the folder returns to functional state; the name of the first file/folder will be missing, then the other file/folder names start dissapearing - eventually they all reappear. It's incredibly time consuming and frustrating to work with this product.
