### ISSUE TITLE
Client Crash [ fatal default .\src\libsync\owncloudpropagator.cpp:226 ]:	ENFORCE: "_state != Finished" in file   [Bug]: 

### ISSUE THREAD

**Issue by ozz-project** [nextcloud/desktop#5473]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hi There,
currently my client is crashing all the time. The log shows this error… on different files.
i have already deleted the .sync file and started again… still the same
[ fatal default C:\Users\sysadmin\AppData\Local\Temp\windows-13808\client-building\desktop\src\libsync\owncloudpropagator.cpp:226 ]:	ENFORCE: "_state != Finished" in file .....

### Steps to reproduce

locked file should skipped an processed later

[20230224_0918_nextcloud.log.zip](https://github.com/nextcloud/desktop/files/10825280/20230224_0918_nextcloud.log.zip)

### Expected behavior

locked file should be skipped and retried later 

### Which files are affected by this bug

D:/Dokumente/Shared/chromium/User Data/Default/Extension State/000170.log

### Operating system

Windows

### Which version of the operating system you are running.

Windows 22H2 (19045.2604)

### Package

Other

### Nextcloud Server version

25.0.3 

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PatMis16** [comment]
Same issue here on Ubuntu 23.04 ARM (Raspberry Pi4).
