### ISSUE TITLE
[Bug]: set share link expiration date (comes random date)

### ISSUE THREAD

**Issue by HarburGER** [nextcloud/desktop#5495]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

set share link expiration date issue (comes random date)

Video: https://youtu.be/EEIjGCF6fIc

### Steps to reproduce

set share link expiration date issue (comes random date)

Video: https://youtu.be/EEIjGCF6fIc

### Expected behavior

set share link expiration date issue (comes random date)

Video: https://youtu.be/EEIjGCF6fIc

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 Pro 22H2 (build 19045.2604)

### Package

Appimage

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by krwi** [comment]
I'm facing a similar issue with the expiration date field on macOS with client 3.7.4:
The date format is changed from `DD.MM.YY` (German format) to something like `DDM.MYY` on submit.

See screen recording:
https://user-images.githubusercontent.com/1932189/225251291-7af60b01-d70a-4c62-8913-3dbe299f1ffc.mov

This also means: It is not possible to change the default expiration date. Not sure whether this warrants a dedicated issue.

BTW I was expecting a date picker (at least I think there was one in previous versions) when clicking on the date field.

**Comment by desertfuchs** [comment]
Bug still happening in v3.8.2, I can confirm the behaviour. Server version is 26.0.1, OS is Windows 11. When creating a share link for any file, ticking the expiration date box and trying to put in a date in the future, it jumps to a random date years ahead. It is not possible still to set a specific expiration date. In v3.9.0 I don't see in the release notes that it's been fixed yet. Any idea as this is really a big challenge and open since more than 3 months?

**Comment by meisterleise** [comment]
The bug is still present in version 3.9.0.

**Comment by Spheron101** [comment]
Can confirm this. Bug is still present in the V3.9.0.

Will there be a fix in the near future? Our Users heavily use this function. I wanted to update our clients but i can't in cause of this bug. My last known working (Windows-) Version (with functional expiration date field in the client) that we use here is the V3.6.6.

**Comment by tstreibl** [comment]
Again and again the same bug - I'm thick of that. See  #4327

**Comment by meisterleise** [comment]
Does anyone have any idea how to change the NC client to English? This should also fix the error.

**Comment by Spheron101** [comment]
Is there a chance to get this done with the next update?

The issues #5627 #5495 #5659 addressing all, in my opinion, the same bug...

**Comment by derfladi** [comment]
I noticed the same behavior on Mac. But when I choose the 1st of a month (e.g. 01.04.24) it works. But only with the 1st.

**Comment by sacerdos82** [comment]
I can confirm that. The sharing feature is literally unusable in Version 3.9.1 on MacOS.

https://github.com/nextcloud/desktop/assets/4182773/56f3a0f6-7223-4cb0-b83e-0862640af68f

**Comment by meisterleise** [comment]
3.9.2 still not working

**Comment by Spheron101** [comment]
3.9.4 still not working
