### ISSUE TITLE
[Bug]: Always a "synchronizing" icon in Nautilus side panel

### ISSUE THREAD

**Issue by janvlug** [nextcloud/desktop#5496]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I always see the icon of two arrows in the Nautilus side panel on Fedora 37 Linux:
![image](https://user-images.githubusercontent.com/5903208/223121716-cf7ac0d1-1812-444b-ab20-ed1cc35216af.png)

### Steps to reproduce

1. Start Nextcloud Desktop
2. Start Nautilus (GNOME Files)

### Expected behavior

A check mark icon that the synchronization is done, like in the notification area:
![image](https://user-images.githubusercontent.com/5903208/223122151-9bbf633f-bf9b-4ec4-99bd-4277fba4f211.png)

### Which files are affected by this bug

n.a.

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 37

### Package

Distro package manager

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.7.3 (Fedora)

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skipperTux** [comment]
I can confirm this bug on Fedora 37, GNOME Version 43.3 running Wayland, Nextcloud Desktop Client 3.7.3 (Fedora) fedora-6.1.18-200.fc37.x86_64, Nextcloud Hub 3 (25.0.4). It is also not possible to access Nextcloud options in Nautilus, like _Share options_, _Copy public link_, hangs with "sync" icon.
![image](https://user-images.githubusercontent.com/3322442/226169627-a5984139-22e3-438c-ad80-be1e5ea0e672.png)

**Comment by badshah400** [comment]
This is not a solution, but perhaps, as discovered by a fellow sufferer, the following workaround may work for you. The nautilus sidebar item comes from nextcloud-client's libcloudproviders integration. You can disable it by deleting the files:

* `/usr/share/cloud-providers/com.nextcloudgmbh.Nextcloud.ini`
* `/usr/share/dbus-1/services/com.nextcloudgmbh.Nextcloud.service`

This should get rid of the nautilus sidebar item for nextcloud client for good, but of course you will still have synchronisation — including icons and sync menus in nautlius — when you keep the nextcloud client app running.

Hope that helps.

**Comment by janvlug** [comment]
I do not see this issue any more in version: 3.7.4 (Fedora)

So I close the issue.
