### ISSUE TITLE
[Bug]: Desktop client identifying all 2FA recovery code backup files as Ransomware

### ISSUE THREAD

**Issue by oucil** [nextcloud/desktop#5512]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating to the latest client, the latest sync has identified all (4) of my 2FA recovery code backup files as "Ransomware" and is refusing to sync them. 

### Steps to reproduce

I can't provide my 2FA backups for testing, but I would suspect that any standard 2FA backup file will do. 

### Expected behavior

The client should sync these files normally.

### Which files are affected by this bug

Firefox Recovery Codes.txt

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by oucil** [comment]
[NC Client.zip](https://github.com/nextcloud/desktop/files/10937975/NC.Client.zip)
Client debug log file attached.

**Comment by Alkl58** [comment]
[Ransomware protection](https://github.com/nextcloud/ransomware_protection) is done server side, the desktop client is showing the error message from the server in this case.

The protection is done by regex (filename matching) to a configurable list in the settings of the protection.

An example from your logs: `Backblaze Recovery Codes.txt`
This matches with: `Recovery(.{6})\.txt$` from https://github.com/nextcloud/ransomware_protection/blob/master/resources/notes.txt#L264

Test:
![grafik](https://user-images.githubusercontent.com/34812414/224300579-3d53e3d7-0bce-4c89-bf6e-7c711974ca8b.png)

You have two options now:
1. Change the filename, maybe `Backblaze Recovery.txt` would work
2. Modify the "Exclude note file patterns" list (should be configurable over the Nextcloud Admin Panel)

**Comment by oucil** [comment]
@Alkl58 Thanks for the explanation, that makes a lot more sense, and I'd forgotten about the Ransomware plugin alltogether, which I guess is a good thing, set it and forget it.  This seems like a pretty aggressive regex that's going to catch a fair bit of false positives, but at least there are solutions to get around it.  Appreciate the help!
