### ISSUE TITLE
[Bug]: Fulltext search result links are wrong

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/desktop#5514]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When doing a fulltext search in the client, the results are linked but the links are wrong. They do not contain the directory of the file, eventhough the search result displays correct directory.

### Steps to reproduce

1. Do a full text search in the client which will find files in sub folders
2. Try to open the search result
3. The browser will now only open the main file list and not the file referred in the result since the link does not contain the sub folder of the file but only `/`: `https://server.example/apps/files/?dir=/&fileid=1234``

### Expected behavior

When search result is clicked where the file is inside the folder /foo/bar it should be like this:

`https://server.example/apps/files/?dir=/foo/bar&fileid=1234`

### Which files are affected by this bug

N/A

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

25.0.4

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
too big and not relevant for this bug.
```

### Additional info

There was already a pull request (https://github.com/nextcloud/desktop/pull/5279) to introduce linking for fulltext search results. I don't know if it worked better with older versions of Nextcloud.

**Comment by ostasevych** [comment]
Duplicate https://github.com/nextcloud/desktop/issues/5511

**Comment by claucambra** [comment]
Hi, we get these URLs from the Full Text Search component on the server side, so this bug originates from the server module. I opened an issue here: https://github.com/nextcloud/fulltextsearch/issues/729

Feel free to add your report here too.

Since this is an upstream issue I will close the issue here

**Comment by arnowelzel** [comment]
Maybe you should add a tag for "upstream" so it is clear that the problem is **not** fixed but only the issue got closed because the upstream needs to fix it.
