### ISSUE TITLE
[Bug]: Some last made French translation (translated in Transifex) are not used

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#5531]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

First translation : 

![2023-03-17_08-38](https://user-images.githubusercontent.com/33763786/225842464-e72244ed-b8aa-4534-af17-080b05ff13eb.png)

![2023-03-17_08-37](https://user-images.githubusercontent.com/33763786/225842808-3aaa2fc4-fb7f-47db-a381-17e77869db17.png)

Second translation : 

![2023-03-17_08-36](https://user-images.githubusercontent.com/33763786/225842485-bc52cd0b-23df-4826-b0fd-87ce56bc7c38.png)

![2023-03-17_08-43](https://user-images.githubusercontent.com/33763786/225843078-d2c31c53-5d89-4781-b4b5-9939af9f418f.png)

### Steps to reproduce

1. Turn your UI in French
2. Go to main and settings dialog to see what I mean (missing last french translation)

### Expected behavior

Last indicated translation should appear instead

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 20.04 LTS (Gnome)

### Package

Appimage

### Nextcloud Server version

25.0.4 (no matter which version)

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Can be provided if necessary
```

**Comment by mgallien** [comment]
I am a bit confused as I have it translated.
see
![image](https://user-images.githubusercontent.com/168967/225882204-d5bc1e38-4e56-4ec0-be66-30ccd2330402.png)

**Comment by Jerome-Herbinet** [comment]
> I am a bit confused as I have it translated.
> see
> ![image](https://user-images.githubusercontent.com/168967/225882204-d5bc1e38-4e56-4ec0-be66-30ccd2330402.png)
> 

What is your OS ? If GNU/Linux, what kind of package ?

**Comment by Jerome-Herbinet** [comment]
I think it's all fixed. I close the issue.
