### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jerrac** [nextcloud/desktop#5538]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

It is functionally impossible to resolve sync conflict in the Linux AppImage.

The message says, "See below for warnings". But the log of synced files is so long that there is no way to find the warning short of scrolling for who knows how long.

### Steps to reproduce

1. Have a sync with thousands of files.
2. Cause a conflict somehow.
3. Try to find the conflict in the list of synced files to resolve it.

### Expected behavior

There should be a "Resolve conflicts" screen that pops up listing all conflicts. Or at least a way to search the logged actions for the conflict.

### Which files are affected by this bug

Can't find the files effected in the first place.

### Operating system

Linux

### Which version of the operating system you are running.

Debian 11

### Package

Appimage

### Nextcloud Server version

25.0.3

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Additional info

Apologies if this should have gone on the forums first. For whatever reason, your forums take 10+ minutes or more to load. All I get the bouncy dots. Been doing that for months. So I pretty much can't use them. (Yes, I cleared my cache...) 

I'll also add that the UI dialog doesn't let me grab the scroll bar to scroll. Only works with my mouse wheel.

If I'm just missing the option that lets me find the files easily, sorry. I checked all the dialogs I could find for anything and couldn't find it...

**Comment by scotrod** [comment]
Did you found solution for this? I have the exact same problem here - I have over 500k files synced and there is no way I can scroll through all of them to find the issue!

**Comment by jerrac** [comment]
I ended up just not syncing that directory. :\

**Comment by claucambra** [comment]
Resolve conflicts was added in 3.9.0 :) I believe this can now be closed
