### ISSUE TITLE
Windows Client does not adhere to the password requirements of the NC.

### ISSUE THREAD

**Issue by plandreisepp** [nextcloud/desktop#5549]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

If you activate the password in the Windows client in the sharing options, it unfortunately only suggests a password with all lower-case letters, so that you only get an error message listing which specifications are not adhered to. The suggested password is neither displayed nor can it be changed or a password entered. It is therefore not possible to assign a password for file or directory sharing in the Windows client.

### Steps to reproduce

1. In the nextcloud security enforce upper an lower case characters, numeric characters and special characters
2. In the Windows client, tick the Password protection box in the sharing options for a file or directory.
3. The error I described in the bug description appears.

### Expected behavior

The Windows client must suggest a password that corresponds to the password defaults of Nextcloud, otherwise sharing with a password is not possible.

### Which files are affected by this bug

/nextcloud/desktop/releases/download/v3.7.4/Nextcloud-3.7.4-x64.msi

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

26.0.0

### Nextcloud Desktop Client version

3.7.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
-
```

**Comment by dirkpape** [comment]
also on MacOS (desktop client Version 3.9.0 (macOS))

**Comment by plandreisepp** [comment]
The problem was fixed under Windows with version 3.9.1.

**Comment by dirkpape** [comment]
Also fixed wit 3.9.1 for MacOS Desktop :-)

**Comment by claucambra** [comment]
Since this issue has now been fixed, I will close. Thanks for reporting!
