### ISSUE TITLE
Add Nextcloud under New Window 11 Context Menu

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#5551]
Curently under Widnows 11. If a user right clicks on a nextcloud folder to share or do anything nextcloud funtions they would have to go under "Show More Options" Then select nextcloud. Please see video

![image](https://user-images.githubusercontent.com/59488153/228356357-b21e197c-28d0-4a8e-861c-06e84cdd790f.png)

https://user-images.githubusercontent.com/59488153/228356378-281e8b36-961b-46f7-8b05-d48fd4ee22c9.mp4

**Comment by raph-topo** [comment]
Why is this "Not planned"? OP's suggestion is a great improvement to UX of Nextcloud Desktop on Windows 11.

**Comment by mgallien** [comment]
you do realize that this was closed by their author
maybe they had a good reason to do so
