### ISSUE TITLE
[Bug]: Lost all applications icons on Windows 11 after auto update to v3.8

### ISSUE THREAD

**Issue by Loocos** [nextcloud/desktop#5563]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After installing the update and restarting my computer which is on Windows 11, I was surprised to have no more icons to my applications, images, ... 
Only Windows App still have them icons.

![Capture d’écran 2023-04-03 102741](https://user-images.githubusercontent.com/26056280/229454810-34769950-152a-4e57-9c4a-26727c275bff.png)

I've unistalled the client and still have the problem, and I've lost the logs by the way..

### Steps to reproduce

1. Just do the update

### Expected behavior

See my icons apps

### Which files are affected by this bug

All my system

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

25.0.2

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
@Loocos very sorry for that
can you send us a debug archive such that we can have a deeper look at it ?

**Comment by joshtrichards** [comment]
Closing due to no follow-up info received after >1 year.
