### ISSUE TITLE
[Bug]: Sync folder connected over ssh

### ISSUE THREAD

**Issue by AMajor-C** [nextcloud/desktop#5571]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello guys i dont know is that bug or waht but:

### Steps to reproduce

Im trying to use foldersync to backup my sourcecode. Ok. 
Folder that contains the sourcecode on NC server is connected as external storage over ssh. Ok. 
We synced both folders and the desktop app says that all folders are up to date. Ok. 
Changing some file in a IDE.... Desktop app is trying to sync... and we getting PUT error or error without any description cyclic reconnects and with 2 or 3 try it gets success. PROFIT ??? NO! it tryinng to sync the file again and... we getting files conflict... what?! YES! it asks us what file right local or remote.... ok pressing "Local"  and that b*tch does all above again and again and again.... 
What do i wrong?

### Which files are affected by this bug

.cpp

### Operating system

Windows

### Which version of the operating system you are running.

Windows10

### Package

Appimage

### Nextcloud Server version

26

### Nextcloud Desktop Client version

3.8

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
some strange record in the server log:	

Connection closed by server at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#3967	
2023-04-04T16:21:59+0300
Info	PHP	No data received from server at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#3559	
2023-04-04T16:21:59+0300
Info	PHP	Expected SSH_FXP_STATUS at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2462	
2023-04-04T16:21:59+0300

	webdav	TypeError: getimagesizefromstring(): Argument #1 ($string) must be of type string, bool given

webdav	Error: Call to a member function getETag() on null
Error	PHP	Undefined array key 0 at /var/www/ncloud.ainet.us/html/apps/dav/lib/BulkUpload/BulkUploadPlugin.php#94
Info	PHP	Connection closed by server at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#3967	
2023-04-04T16:21:59+0300
Info	PHP	Expected SSH_FXP_STATUS at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2462	
2023-04-04T16:21:59+0300
Info	PHP	Expected SSH_FXP_STATUS at /var/www/ncloud.ainet.us/html/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php#2462
Error	PHP	fopen(sftpread://Projects//CPP/Qt/TFOMS53_Tools/Toolbox-Image.jpg): Failed to open stream: &quot;OCA\Files_External\Lib\Storage\SFTPReadStream::stream_open&quot; call failed at /var/www/ncloud.ainet.us/html/apps/files_external/lib/Lib/Storage/SFTP.php#381	
2023-04-04T16:19:08+0300
Info	PHP	Expected SSH_FXP_HANDLE or SSH_FXP_STATUS at /var/www/ncloud.ainet.us/html/apps/files_external/lib/Lib/Storage/SFTPReadStream.php#111
```

### Additional info

When i do update files using webbrowser recive no errors

**Comment by joshtrichards** [comment]
Hi @AMajor-C - I'm having a difficult time grasping the scenario you're describing.

I would suggest eliminating some variables - such as the testing against local storage rather than an External Storage mount. And also there are log client log files that may have some additional hints. Both topics are covered here: https://docs.nextcloud.com/desktop/3.13/troubleshooting.html#isolating-other-issues

Unfortunately, it's not practical to provide general technical support through this channel. It may make sense to follow-up at the help forum - https://help.nextcloud.com - if you're looking to get feedback on your setup, discuss different ways to approach the problem you're trying to solve, etc.
