### ISSUE TITLE
Ability to dismiss notifications

### ISSUE THREAD

**Issue by pancake-tongs** [nextcloud/desktop#5585]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
The Nextcloud desktop client shows several kinds of notifications in the pop-up window that is displayed when a user clicks on the system tray icon. These can be about any number of things, though the ones that I most often see are related to recent updates to Nextcloud applied server-side. I'm running nextcloud server as a snap, though this isn't directly relevant. It does, however, emit a notification each time there is an update.

See screenshot: [https://imgur.com/e2LWnrA](https://imgur.com/e2LWnrA)

As you can see, the notifications pile up, and cannot be dismissed. Nextcloud desktop client does not show an 'X' button, and in fact doesn't seem to respond to right or left clicks at all on notification entries. Sometimes, I want to check to make sure a recent file has been synced, and I have to scroll through dozens of notifications to reach the first meaningful status messages about recent files. To clear out these notifications, I have to log in to my nextcloud account in a browser, which is an unintuitive and undesirable UX.

I'd like to suggest that a mechanism to dismiss / delete notifications be integrated into the desktop client.

**Comment by jospoortvliet** [comment]
This should be resolved  with the work above, thanks for reporting!

**Comment by pancake-tongs** [comment]
This issue has been subject to a regression and should be reopened. Please see: https://github.com/nextcloud/desktop/commit/c975d40fb8cda8a78d910342276e707677746390

**Comment by benloeffel** [comment]
This issue causes non-dismissible notifications to dominate the activity panel in the Nextcloud Desktop Client (version 3.7.3 on Debian), impacting usability.

![Image](https://github.com/user-attachments/assets/8e0888fb-dc84-45f6-97f9-c12d4c9daa43)

Is there an alternative way to purge these notices?

**Comment by pancake-tongs** [comment]
Hi @jospoortvliet , could I trouble you to reopen this issue please?

**Comment by danineuss** [comment]
I am also pretty sure that this ticket needs to be revisited. I have these notifications from the day that I started using the app that I can not get rid of.

<img width="456" height="500" alt="Image" src="https://github.com/user-attachments/assets/f1c7c188-5457-4d38-9ae3-731bc42920f1" />

Also mentioned here: https://github.com/nextcloud/desktop/commit/c975d40fb8cda8a78d910342276e707677746390

**Comment by yuki-tsubaki** [comment]
This ticket really needs to be revisited. 

I previously didn't have any secret service provider running (causing Nextcloud to re-authenticated each startup) so I had a bunch of app passwords. After I fixed the issue, I wanted to clean up the unused authentication stuff. Little did I know that I would permanently fill the top pages of my notifications with reminders of this trivial action.

This buries the actual notifications about sync events making the feed much less usable.

This mess continues for a bit longer after what is visible and there is no option to dismiss:

<img width="447" height="512" alt="Image" src="https://github.com/user-attachments/assets/e02f214c-adef-46e7-b52f-c5fe68b60986" />


Seeing as @jospoortvliet has not responded in over a year and being reticent to open a new issue for the same things when this still exists and the relevant information about the regression is already linked, it would be nice if @camilasan or @mgallien could reopen this issue.

Thanks for all the work you do for this project.
