### ISSUE TITLE
[Bug]: Nextcloud VFS on Windows always displays "syncing" icon for .lnk files

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#5594]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

.lnk files always have their status icon displayed as "syncing" when in VFS mode on Windows

### Steps to reproduce

1. Sync a folder with VFS mode and have .lnk files synced to the server
2. Observer the status for every other file in a local folder in Windows Explorer and notice the status icon can change from "online only" to "syncing" and so on
3. For .lnk files the status is always "syncing"(refreshing icon)

### Expected behavior

.lnk file needs to have a correct status

### Which files are affected by this bug

.lnk files

### Operating system

Windows

### Which version of the operating system you are running.

All

### Package

Other

### Nextcloud Server version

all

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by allexzander** [comment]
Note: Not sure when we will have time to work on it as .lnk files are now treated as conventional files (not VFS placeholders) due to an issue with `QFileInfo` freezing the desktop client when getting info about .lnk files. This either requires switching to the latest Qt6 patch with that problem solved and then treating .lnk files as virtual file placeholders again or considering the possibility of manually assigning a green checkmark (available offline) status (not sure if that's possible with Cf API for non-virtual files) or hiding a status icon completely.

**Comment by PhilippSchlesinger** [comment]
Maybe related: even ignored files alsways show as "sync pending", see https://github.com/nextcloud/desktop/issues/5524
