### ISSUE TITLE
Client will not connect unless E2E has previously been set up

### ISSUE THREAD

**Issue by tabp0le** [nextcloud/desktop#560]
OK, so here's a weird one.

**Expected Behavior**
- Add account to Nextcloud and have it start syncing immediately

**Actual Behavior**
- Client initially authenticates, adds account, allows folder selection.
- After wizard, it shows as disconnected.
![nc_no_connection](https://user-images.githubusercontent.com/6798003/44106420-7b134670-9fa9-11e8-9d8e-8e43571acd1d.png)

**Logs**
https://pastebin.com/N6DfdRsa

**Affected Platforms**
Linux, Windows, (probably macOS)

**OpenSSL Version**: 1.10h
**QT Version**: 5.11.1
**Nextcloud Branch:** master

To get it to actually work, and add the account, I had to:

- Go into the Android app
- Add encrypted folder
- Set up initial encryption and get pneumonic
- Go back to nc desktop client and remove, then add account again.
- At this point, it popped up with the enter e2e pneumonic phrase prompt.
- Enter e2e phrase, and hit ok
- Client syncs successfully

**Comment by camilasan** [comment]
how did you build it? Is it Debug or Release?

**Comment by tabp0le** [comment]
My apologies, the issue exists in both Debug and Release @camilasan

**Comment by tabp0le** [comment]
**OpenSSL Version**: 1.10h
**QT Version**: 5.11.1

**Comment by camilasan** [comment]
I can't reproduce this error on Linux but I have a similar problem on Windows with Release built.

**Comment by tabp0le** [comment]
I wonder, could having an OpenSSL version of <=1.02 on the server, have any effect on the client?

**Comment by mannp** [comment]
Getting the same issue myself.

**Comment by camilasan** [comment]
Hi! Please try the build https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61352-daily-20180904.exe. This issues should be solved. Thanks!

**Comment by tabp0le** [comment]
I'm trying to test, but unfortunately because of https://github.com/nextcloud/desktop/issues/279 I can't :(

**Comment by tabp0le** [comment]
@camilasan Do you have commits i can cherry-pick so I can try my own build using old login method? I tried merging master, but I don't think your fixes are in there, as it didn't make a difference.

**Comment by camilasan** [comment]
No, what changed is how we build it by passing openssl and qt5keychain paths to cmake:
https://github.com/nextcloud/client-building/blob/master/build.bat

**Comment by tabp0le** [comment]
> 
> 
> No, what changed is how we build it by passing openssl and qt5keychain paths to cmake:
> https://github.com/nextcloud/client-building/blob/master/build.bat

So yeah, this is still an issue. :(

**Comment by camilasan** [comment]
Ok, I can't reproduce it anymore. Could you check for client logs?

**Comment by tabp0le** [comment]
> 
> 
> @tabp0le Ok, I can't reproduce it anymore. Could you check for client logs?

I've attached a log using official nextcloud nightly.
[nc-client-e2e-fail.log](https://github.com/nextcloud/desktop/files/2380315/nc-client-e2e-fail.log)

**Comment by tabp0le** [comment]
This is still an issue in https://github.com/nextcloud/desktop/releases/tag/v2.5.0-rc2

[e2e_error.log](https://github.com/nextcloud/desktop/files/2550292/e2e_error.log)

**Comment by hoellen** [comment]
I had the same issue today, when I installed the new 2.5.0 release (from nextcloud.com) for one of my windows user. After setting up E2E on the iOS client it worked.

**Comment by rugk** [comment]
Can confirm this issue still exists in v2.5.0 on Fedora 29.

**Comment by rugk** [comment]
Indeed, this should be a high-prio issue and is totally blocking any productive use of e2e crypto yet. I think you know it really needs to be fixed. For alpha stage okay, but at least the client's e2e crypto implementation is said to be stable (v2.5.0 with that feature – and this bug – is released as stable).

**Comment by mickare** [comment]
I can confirm that the workaround proposed by @tabp0le works with:
- Nextcloud 14.0.4
- End-to-End Encryption 1.0.5
- Desktop Client 2.5.1git
- Android Client 3.4.1

Therefore it must be an desktop client issue...

**Comment by dirkhusemann** [comment]
Couldn’t get the workaround to work with iOS client.

**Comment by mickare** [comment]
The workaround... now the desktop client refuses to sync files. :ok_man: 
https://gist.github.com/mickare/1e6d25beba436000d144b3ec23e694b1

`GOAWAY received, cannot start a request`

**Comment by Flozi95** [comment]
I'm also geting the Message "GOAWAY received, cannot start a request"

**Comment by schwukas** [comment]
I am experiencing the same problem. Is there any update on this? I'm really eager to try this out :)

**Comment by lars-becker** [comment]
I have the same problem. Current Archlinux with Client Version [2.5.2git](https://github.com/nextcloud/desktop/commit/56c905819ee6d48db136e7b5978bdf2a42677f3f).

**Comment by camilasan** [comment]
Please, try the daily build from tonight, #1420 is merged and it might fix it :)

**Comment by DominiqueFuchs** [comment]
Duplicate of original issue [desktop/#830](https://github.com/nextcloud/desktop/issues/830) and fixed by [desktop/PR#1420](https://github.com/nextcloud/desktop/pull/1420)
