### ISSUE TITLE
[Feature-Request / BUG?] Please make or keep Nextcloud client compatibility to SCIEBO Cloud

### ISSUE THREAD

**Issue by ifrh** [nextcloud/desktop#5600]
> "Sciebo is a non-commercial cloud storage by universities for universities, where you can securely store your research, study and teaching data." ( https://hochschulcloud.nrw/en/index.html )

Currently you can add a SCIEBO account to Nextcloud client ,i.e. Version 3.1.3, (running on Windows 10 - Version 22H2 - 64bit).
Synchronisation works well, until you restart Nextcloud client or your operation system.

After restarting Nextcloud client no connection to SCIEBO is possible anymore.
- If you use main window to reconnect , than Nextcloud crashes.
- If you restart windows you get an error message pointing you to login via main window again, but than Nextcloud client crashes again. 

You have to delete the sciebo account from Nextcloud client and add the account as new again, than synchronisation works until your next start of Nextcloud client.

*Here some screenshots.*

![configure_account_sync_okay](https://user-images.githubusercontent.com/3845055/231683974-f1c0c582-eeb3-4f58-8d8b-a5df5169fd5b.png)
![crash_nextcloud_login](https://user-images.githubusercontent.com/3845055/231684028-becd8e59-3a31-4deb-ba9f-55a421d1b791.png)
![reconnect_error_after_os_restart](https://user-images.githubusercontent.com/3845055/231684048-80c5c140-4f8d-465a-bf4d-165bdc905b89.png)

**Comment by claucambra** [comment]
Hi, could you provide desktop client logs at the time of the crash? Thanks!

**Comment by claucambra** [comment]
Also, version 3.1.3 is ancient at this point -- can you try with the latest version of the desktop client?

**Comment by claucambra** [comment]
Digging into SCIEBO cloud it does not seem to use Nextcloud -- so we can't really ensure compatibility with it. The provider has a suite of desktop and mobile apps that you can use so we recommend you use those

**Comment by ifrh** [comment]
seems that there is a bug report cover same behavior (not only related to SCIEBO)
"Re-Login doesn't work with (old) ownCloud servers" https://github.com/nextcloud/desktop/issues/2111

**Comment by ifrh** [comment]
@claucambra You asked
> Hi, could you provide desktop client logs at the time of the crash? Thanks!
> Also, version 3.1.3 is ancient at this point -- can you try with the latest version of the desktop client?

Updating to Nextcloud Client Version 3.8.0 changed behavior: No crash happen while trying to re-login, which did not work. 
And the window which gets opened have disfunctional actions "link copy" and "open browser".

![grafik](https://user-images.githubusercontent.com/3845055/231878890-be847110-7647-4a57-ab7d-70f686fe0373.png)

That not working actions had been mentioned in the Nov 2020 in https://github.com/nextcloud/desktop/issues/2111#issuecomment-732147180 

> Digging into SCIEBO cloud it does not seem to use Nextcloud -- so we can't really ensure compatibility with it. The provider has a suite of desktop and mobile apps that you can use so we recommend you use those

just for record:
The SCIEBO client 3.2.1.10371 based upon owncloud client 3.2.1 commit 9724d66

**Comment by ifrh** [comment]
Adding as new account after deleting the account, shows that the server is running Version 10.12.0.6.

![grafik](https://user-images.githubusercontent.com/3845055/231884286-540ed988-28b4-42ef-a169-226e468ec011.png)

**Comment by ifrh** [comment]
Workaround, that is deleting `authtype` line from nextcloud.cfg,  mentioned in June 2020 in https://github.com/nextcloud/desktop/issues/2111#issuecomment-647486747 , allows re-using SCIEBO-cloud between two starts of nextcloud client 3.8.0.

It seems to me, that setting `authtype=webflow` is not allowed for clients to communicate with SCIEBO-Server

**Comment by ifrh** [comment]
Just for the record:

SCIEBO infrastructure is moving from owncloud to nextcloud systems.
- https://wwuit-sys.zivgitlabpages.uni-muenster.de/sciebo/docs/de/nextcloud-migration/
