### ISSUE TITLE
Allow “shallow/placeholder” files in desktop client: A marker that a file is there, but not downloaded

### ISSUE THREAD

**Issue by kusmi** [nextcloud/desktop#5601]
We have a rather large nextcloud sync folder (200GB+) and I often deselect sub-folder, so they don’t sync and I can spare some disk-space on my local laptop (e.g. I exclude large video projects, media files, etc)

But when doing so, I have no easy way to find out what I’m missing out (except: I go into my sync settings and see what folders I have deselected… or logging into the web-interface → cumbersome…)

It would be great if nextcloud desktop has a way to place “placeholder” files: So I know the file would be there, but is not synced. And a way to manually trigger a sync for that file, if I ever need it.

iCloud does something similar, it places a “cloud” ☁️ icon next to a file, if it is not downloaded and with a click, I can download it again. And with right-click, a menu pop-up with an action: “remove that files locally and make it a cloud file again”.

<img width="602" alt="iCloud Example" src="https://user-images.githubusercontent.com/448222/231711514-ab3369d1-6e23-4118-a7d1-5ab76b508ce0.png">

**Comment by kusmi** [comment]
OK, It looks like this is the new “virtual files” feature in nextcloud :-) but it does not seem to be enabled in 3.8 yet (at least not on the Mac)

**Comment by PhilippSchlesinger** [comment]
@kusmi 
see issue https://github.com/nextcloud/desktop/issues/1337 for details on FileProvider API (VFS) in macOS.
A build is linked in the announcement comment https://github.com/nextcloud/desktop/issues/1337#issuecomment-1478386641.
Development takes place in PR https://github.com/nextcloud/desktop/pull/5527.

**Comment by claucambra** [comment]
> OK, It looks like this is the new “virtual files” feature in nextcloud :-) but it does not seem to be enabled in 3.8 yet (at least not on the Mac)

You can try the beta now, though be warned it is still not stable 🙂

Since we have virtual files I will now close the issue, thanks for reporting!
