### ISSUE TITLE
[Bug]: Unable to clear 2FA backup Code Notifications via desktop client 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#5606]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

There's no option to clear the backup code notification via desktop client

![image](https://user-images.githubusercontent.com/59488153/235455434-8ca81fb3-567a-4cbf-91a1-1b9ff618d644.png)

...

### Steps to reproduce

Open Desktop client and and see notifications
...

### Expected behavior

Should have an option to clear notifications or clear all notification 
...

### Which files are affected by this bug

All

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11, Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.0

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by AndyXheli** [comment]
https://github.com/nextcloud/desktop/issues/5585

**Comment by jospoortvliet** [comment]
Should be resolved with the work above.
