### ISSUE TITLE
Do not upload MuseScore saving/backup files

### ISSUE THREAD

**Issue by bmarwell** [nextcloud/desktop#5609]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description

Please add the following extensions to the default ignore list:

* `*.mscz_saving`

**Comment by Killea** [comment]
I think we need to add a ignore list configuration tab ins the settings to let the users decide, only blindly adding a file extension is not good enough. Also, the ignored files should have a new icon in the file explorer like the shared folder did, ( the black sharing icon).

**Comment by bmarwell** [comment]
> I think we need to add a ignore list configuration tab in the settings to let the users decide, only blindly adding a file extension is not good enough. Also, the ignored files should have a new icon in the file explorer like the shared folder did, (the shared folder has a black sharing icon)

In general, you are right. But in this case, MuseScore is creating a temporary file for saving and then just moving that file (which will create errors in both MuseScore and NextCloud). So in this particular case, it should be a no-brainer.

For all other non-temporary, non-saving file types, I totally agree with you.

**Comment by joshtrichards** [comment]
> Please add the following extensions to the default ignore list:

I'm not sure it's practical for us to maintain a grand list of every app's temp files. Practically speaking, we can really only target the biggies.

> I think we need to add a ignore list configuration tab in the settings to let the users decide, only blindly adding a file extension is not good enough.

Unless I'm misunderstanding, this is already the case: *Settings->General->Edit Ignored Files*
