### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by liorbraginsky92** [nextcloud/desktop#561]
![screen shot 2018-08-15 at 7 12 54 pm](https://user-images.githubusercontent.com/20610623/44141046-4dc79fce-a0bf-11e8-8a95-5348a33c6a19.png)
when I build project, got error

**Comment by camilasan** [comment]
Hi! Are you running cmake in the build folder?

**Comment by liorbraginsky92** [comment]
No, so I run in the build folder but other error.
![screen shot 2018-08-15 at 7 43 43 pm](https://user-images.githubusercontent.com/20610623/44142486-9fdc080a-a0c3-11e8-8143-d928cb42b2a5.png)

**Comment by camilasan** [comment]
You need to install OpenSSL 1.1.x.

**Comment by liorbraginsky92** [comment]
OpenSSL 1.0.2p  14 Aug 2018
 it's impossible?

**Comment by camilasan** [comment]
It needs to be 1.1.x. You can install it via brew.

**Comment by liorbraginsky92** [comment]
I can't install openssl 1.1.x, pls help me.

**Comment by camilasan** [comment]
I ran into the same problem and this worked for me: brew install openssl@1.1
Could you try it?

**Comment by camilasan** [comment]
Closing due to the lack of response.
