### ISSUE TITLE
[Bug]: Share options for folders uses "Custom permissions" instead of "Bundled permissions" - can only edit and not upload

### ISSUE THREAD

**Issue by avatar1024** [nextcloud/desktop#5615]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello,

Since recently (not exactly sure when but definitely the case with 3.8.0), when I create a share link on a folder via the file manager context menu, I get the share option “edit” (see screenshot 1). This used to correspond to the “edit and upload” option form the Web UI, i.e. when ticked then people with that shared link could upload files into that folder.

This is no longer the case, and is now strictly “edit”, and so people with the shared link cannot upload into it (the + sin is not present). If I look up the sharing properties of this folder in the WebUI the option is indeed only “edit” and not the bundle “edit and upload” (see screenshot 2) as it used to be.

I believe this is not the intended behaviour and is a usability regression. Or at least then upload should also be available as a share option for folder from the context menu.

I've created thread about this on the forum and it was reproduced by another user: https://help.nextcloud.com/t/missing-upload-as-share-option-for-folders-can-only-edit/160371

![share options](https://user-images.githubusercontent.com/18719956/233006238-7d892404-0641-4a01-9b6f-c9ab5ed943c4.png)
![share options_webui](https://user-images.githubusercontent.com/18719956/233006262-b4bd0791-9097-433b-9440-5481144341d8.png)

### Steps to reproduce

1. Open dolphin
2. Right click on a folder
3. Go to Nextcloud context menu and go to Share options
4. Create a share link and go to share option
5. Tick the Allow editing box
...

### Expected behavior

Editing on a folder should allow upload.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

KDE neon 5.27

### Package

Other

### Nextcloud Server version

25.0.5

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Operating System: KDE neon 5.27
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.105.0
Qt Version: 5.15.8
Kernel Version: 6.1.22 (64-bit)
Graphics Platform: Wayland

**Comment by tom2tester** [comment]
Same problem on WINDOWS and macOS clients since the latest 3.7 client versions. I can't specify which version "introduces" this bug, but definitely in 3.7.x!

**Comment by avatar1024** [comment]
Same behaviour in client version 3.8.1

**Comment by avatar1024** [comment]
Seems to me that the default share options should be the "Bundled permissions" (Read only, Allow upload and editing, File drop) and not the "Custom Permissions" (Upload, Edit , Delete)

**Comment by gtntdev** [comment]
same issue here!

**Comment by omel78** [comment]
same issue here!

**Comment by avatar1024** [comment]
I have now checked the behaviour in the android app and there the share option is "Edit and Upload", as it should, and so this issue is only on the desktop client, and indeed a bug.

**Comment by joshtrichards** [comment]
Fixed in #5622/#5631 (released in v3.8.2)
