### ISSUE TITLE
[Bug]: File is locked but users are still able to edit it

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#5618]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When a file is locked, users are still able to edit it using the desktop client

### Steps to reproduce

Scenario:
Two users have access to the same file
- User 1 Locks the file to edit it
- After some seconds the lock is synchronized to user 2
- After that, User2 tries to edit the file and it manages to edit it, even though the file is locked by User1.

### Expected behavior

When a user locks a file to edit it, the file should be set as "read-only" for other users.

As far as I remember this was the behaviour some versions ago. I am not sure why this behaviour changed.

### Which files are affected by this bug

any file

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

25.0.5

### Nextcloud Desktop Client version

3.8.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
See also https://github.com/nextcloud/desktop/issues/4060

**Comment by vagner-dias** [comment]
@mgallien @allexzander 
Do you believe you can bring back the feature which sets the file as read-only when it is locked?

Thank you!

**Comment by mgallien** [comment]
@vagner-dias this would be https://github.com/nextcloud/desktop/pull/5841
