### ISSUE TITLE
[Bug]: Error setting release date

### ISSUE THREAD

**Issue by frankmuellerbadmarienberg** [nextcloud/desktop#5627]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I want to set a release via the Nextcloud client and connect it to a release date, the software does not allow me to enter the date - as before.

It is also not possible to call up the calendar to set the date.

In my opinion, an entry using the keyboard is always changed arbitrarily.

Thank you for your support.

### Steps to reproduce

1.Set Release Date
2.
3.

### Expected behavior

If I want to set a release via the Nextcloud client and connect it to a release date, the software does not allow me to enter the date - as before.

It is also not possible to call up the calendar to set the date.

In my opinion, an entry using the keyboard is always changed arbitrarily.

Thank you for your support.

### Installation method

None

### Nextcloud Server version

24

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
No
```

**Comment by tlueder** [comment]
I'm not sure if this is the same issue I'm facing but it kind of sounds like it.

Setting a expiration date for sharing a file via link is broken.

Sharing a file via link and activate expiration date:
<img width="398" alt="Screenshot 2023-05-05 at 15 23 45" src="https://user-images.githubusercontent.com/5957131/236469687-30ea139a-94b3-4083-b7bd-c98f2fe958d3.png">

And changing the date, here I only changed the 23 to 24 and this is the result.
<img width="404" alt="Screenshot 2023-05-05 at 15 24 09" src="https://user-images.githubusercontent.com/5957131/236469897-05d7c808-5744-4394-a86a-a4af4de3f9ea.png">

**Comment by claucambra** [comment]
Hi @frankmuellerbadmarienberg I am having difficulty understanding what the issue that you're encountering is -- could you provide more details and/or screenshots to clarify? Thanks!

**Comment by unnilennium** [comment]
using nextcloud 3.8.1 on Fedora 37, nextcloud 25.0.3.
I am neither able to set an expiration date. whenever I check the box, the field to enter a date does not display I only get the two arrows circling.
![image](https://github.com/nextcloud/desktop/assets/1259496/eddea882-2196-4644-801c-8f18c3cf3518)

if I set this from the web interface then the field shows and I am then able to set this manually.

**Comment by frankmuellerbadmarienberg** [comment]
In the first screenshot you can see how I entered the expiry date in the corresponding field. In this case, May 28, 2023. By the way, the calendar symbol is not selectable….
In the second screenshot you can see that the entered date changed to 06/30/2030 after I accepted it.
I hope this makes the problem clearer.
![screen1](https://github.com/nextcloud/desktop/assets/131862759/6b440e84-294c-4a55-9d08-9ccf6d7aa335)
![screen2](https://github.com/nextcloud/desktop/assets/131862759/e617c4f5-2eae-4dd7-a67d-2350bb9e1122)

**Comment by unnilennium** [comment]
i have the same issue on nextcloud interface for date decreasing of one day on submission /save of the date

i have submited yesterday a bug against nextcloud-server but it is not anymore in issues

**Comment by tlueder** [comment]
This issue is still unsolved in the latest release(3.9.0).

**Comment by tstreibl** [comment]
How is it possible that this bug does not get fixed? I didn't count, but since approx. 5 releseases this issue is open (at least for the windows version of the client).
More serious: in every version this feature gets changed and does not work again. How can developers change code for a feature without **testing it once** bevor doing the release? 

This is not a joke any more. We use the client in a large team and generate dozend of share links every day. When the expiration date for links can't be configured people sent out their links without any expiration limit. From my point of view this is a sever security issue. I thought nextcloud cares about user data and privacy????

I'm really unhappy because the same pain happened with the upload feature for links, which was not available during the last four releases, although all developers were aware of this fact (I can dig out the issue number if necessary!). It took till release 3.9.0 to close this.

A desctop client which fails in its basic feature (generating share links) is useless.

**Comment by tlueder** [comment]
This is still broken in 3.9.3git (build 17174)

**Comment by tlueder** [comment]
This is still broken in 3.9.3git (build 17174)

**Comment by Spheron101** [comment]
3.9.4 still not working
