### ISSUE TITLE
Nextcloud client fails to start on fresh minimal Debian with i3 and lightdm

### ISSUE THREAD

**Issue by solarchemist** [nextcloud/desktop#563]
On a fresh Debian 9.5 minimal install *without* any desktop environment selected during the OS installation, and i3 window manager installed afterwards (`apt install lightmd i3 xinit`), both the AppImage and the [PPA](https://www.linuxbabe.com/debian/install-nextcloud-desktop-client-debian-9-stretch) fail in this manner:
```
$ nextcloud
XIO:  fatal IO error 2 (No such file or directory) on X server ":50"
      after 429 requests (429 known processed) with 0 events remaining.
```

I found two possibly related issues:
<https://github.com/nextcloud/desktop/issues/308>
<https://github.com/nextcloud/desktop/issues/235>
and two perhaps less related issues:
<https://forums.ni.com/t5/LabWindows-CVI/XIO-fatal-IO-error-11/td-p/2989989/page/3>
<https://github.com/osrf/docker_images/issues/40>

I strongly suspect that this error is due to some Xserver component missing from the `lightdm`+`i3` system (but both systems have `xserver-common` and `xserver-xorg`).
I was able to confirm my suspicion by rerunning the OS installation this time *with* Debian desktop and XFCE selected. On this system, Nextcloud client starts as normal on XFCE, and after `apt install i3`, starts normally on i3 too.

Does anyone perhaps know which packages the `lightdm`+`i3` system needs to make the Nextcloud client work? (Note: XFCE uses lightdm too, so it's very likely some package that XFCE provides).
As for my motivation, I was trying to setup a light-weight system, and although adding XFCE is not a dealbreaker for me, it adds around 1GB in storage to an otherwise 2GB system, and a whole bunch of packages that are unnecessary (except those that aren't, obviously!).

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
