### ISSUE TITLE
Windows 10: Explorer, Share-Icon in Darkmode not visible

### ISSUE THREAD

**Issue by Rimos911** [nextcloud/desktop#5644]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Win10: black Icon of dark Background - Icon not visible

### Steps to reproduce

Windows 10 - enable Darkmode - share a File/Folder - the Background is dark - the Shared-Icon too --> Icon not visible

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

-

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

3.8.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
-
```

### Additional info

Solution: reverse the color of the Share-Icon in the darkmode

![Screenshot 2023-05-03 235205](https://user-images.githubusercontent.com/70541883/236058177-9b05244f-53f9-40f4-80cb-2e0d49506cf1.png)

**Comment by Mika-6-9** [comment]
Hello, idem for lock files
https://github.com/nextcloud/desktop/issues/6105

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by Mika-6-9** [comment]
Hello.
It's still relevant with 3.14.3
