### ISSUE TITLE
Taskbar icon forgets that synchronisation folders are configured while synchronizing

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/desktop#565]
Synchronization is running. After some time (maybe 20-30 minutes) the Nextcloud taskbar icon turns gray and says that no synchronisation folders are configured, even though there are two accounts with multiple folders active: one is synchronizing while the other is waiting for the first one to finish.

### Expected behaviour
The Nextcloud taskbar icon shows that synchronisation is running.
### Actual behaviour
The Nextcloud taskbar icon shows that no synchronization folders are configured.
### Setup
Nextcloud Desktop Client 2.3.2 for Windows.

**Comment by claell** [comment]
@TomTurnschuh Is this still happening? If so, could you provide screenshots?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
