### ISSUE TITLE
[Bug]: Nautilus freezes for a while when synchronizing changes

### ISSUE THREAD

**Issue by narcisgarcia** [nextcloud/desktop#5674]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After moving files and folders (100 MiB or less in 50 items or less) Nextcloud client begins to synchronize them and Nautilus freezes for a whole minute (can't select any item, no control/button or tab responds).
After that minute, all is well synced.

- Used Nextcloud account contains near 20,000 total files.
- Both client computer and server are connected with 1000mbps access (only wired) to Internet.
- Client computer is not affected by i/o bottleneck at the moment of issue.

### Steps to reproduce

1. Select some files with Nautilus file manager
2. Context menu -> Cut
3. Open another tab to go to another folder in same account tree
4. Paste

### Expected behavior

Sync operation should in a background process, not blocking all Nautilus usage.

### Which files are affected by this bug

idk

### Operating system

Linux

### Which version of the operating system you are running.

GNU/Linux Debian 11 (Stable)

### Package

Distro package manager

### Nextcloud Server version

25

### Nextcloud Desktop Client version

3.1.1-2+deb11u1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

"Create Debug Archive" button does nothing.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
