### ISSUE TITLE
[Bug]: Purge activity entries of chat messages

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#5682]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

- receive a chat message
- see it in activity stream
- open web and reply to message
- still see this activity in stream

### Steps to reproduce

see above

### Expected behavior

After chat message is read, corresponding activity entry should be deleted.

### Which files are affected by this bug

/

### Operating system

Linux

### Which version of the operating system you are running.

Arch

### Package

Distro package manager

### Nextcloud Server version

c.nc.c

### Nextcloud Desktop Client version

latest

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by AndyXheli** [comment]
Same as https://github.com/nextcloud/desktop/issues/4825
