### ISSUE TITLE
[Brainstorm] Health status via CLI

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#5684]
Sometimes it can happen that client ends up in a sync problem, which is not an usual one.
Idea now is to brainstorm, if and how we can monitor this and provide a CLI check.

Purpose would be that in an org the sysadmin team could monitor this, or at least check remotely, to see what the problem is.

We should then also check if/what options to "heal" this are possible
- status: show status of sync via output, how many sync conflicts, (-v shows which files)
- force rescan
- drop entire sync and start from scratch (without user has to relogin)
- drop sync folder and restart (hard reset)
- soft reset: only reset local db and try to sync again
- …

@allexzander @camilasan @claucambra @mgallien

**Comment by mgallien** [comment]
- [ ] status: show status of sync via output, how many sync conflicts, (-v shows which files)
  - 3 days including putting the architecture in place and adding automated tests
- [ ] force rescan
  - 1 day
- [ ] drop entire sync and start from scratch (without user has to relogin)
  - 1 day
- [ ] drop sync folder and restart (hard reset)
  - 1 day
- [ ] soft reset: only reset local db and try to sync again
  - 2 days
  - :warning: this is not possible to do if one is running Windows with virtual files
  - we have to make sure this is properly communicated to the user

**Comment by tobiasKaminsky** [comment]
Thanks!
Actual task will be a new issue, probably with only a subset of those ideas.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky me take would be to do the first 4 items from the list and then see what Leopoldina provides as a feedback and if that points towards also having the last option that seems to be a bit tricky from a user-informing perspective given all this is triggered by admins on the users' desktops.

Can you create a new issue for that as you mentioned it and put it in the evaluation column? Thanks in advance
