### ISSUE TITLE
Bump to QtKeychain 0.9.1 / Windows roaming profile issue

### ISSUE THREAD

**Issue by klada** [nextcloud/desktop#569]
Starting with e0a14cac5b03ea41303e1602b79b51fec1f5c1de the desktop client has proper support for roaming profiles on Windows operating systems.

Right now the user still needs to enter the sync password on every logon in a roaming profile environment (as of 2.5.0b1).

For this to work properly the password also needs to be stored in the Windows credencial store with the proper scope. Right now the password is stored with "local machine" scope by QtKeychain. This leads to the following issue:

1. The user configures the client in a roaming profile environment
2. The sync password is stored with "local machine" scope (which means it could also be lost after logout in roaming environments, due to policies)
3. The user logs out
4. The use logs in on a different machine and the sync config is present, but the password is not → password prompt (depending on the roaming policies this might also happen on the same machine)

This is an upstream QtKeychain issue (see frankosterfeld/qtkeychain#121), which has already been fixed in QtKeychain 0.9.1.

**Fix for this issue**

Please update the build toolchain, so QtKeychain 0.9.1 is used for the 2.5 release (also see owncloud/client#6729).

**Comment by camilasan** [comment]
Done. Next daily builds starting with [Nextcloud-2.5.0.61269-daily-20180821.exe](https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61269-daily-20180821.exe) are with Qt 5.11.1 and qtkeychain 0.9.1. 
Thanks for the report!
