### ISSUE TITLE
Improve initial sync of macOS File Provider module for VFS

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#5692]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The initial full enumeration of the subject server done by the file provider module is extremely slow, leading to a large amount of time passing before the user is able to interact with files in the relevant domain

### Steps to reproduce

1. Set up account with file provider module enabled
2. Wait for enumeration of server files to begin
3. Wait for enumeration of server files to end
4. Wait some more

### Expected behavior

Delay between a file provider enumeration beginning and it being responsive should be minimal

### Which files are affected by this bug

All files affected

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS 13.0

### Package

Other

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

Master

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by marcotrevisan** [comment]
Hi @claucambra, 

  just for the records, using the version 2 of the VFS Beta build, I'm finding it slower than version 1 in fetching the file contents. There's a lag (many seconds) before the actual download starts.  
If this is a known behaviour please ignore this message.

Kind regards
