### ISSUE TITLE
Add configuration GUI for File Provider module

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#5693]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Configuration of the file provider module should be possible by end users without having resort to arcane configuration modifications

**Comment by jancborchardt** [comment]
@claucambra what exactly is meant by the file provider module? Which settings and configuration options would need to be displayed with that interface?

**Comment by claucambra** [comment]
> @claucambra what exactly is meant by the file provider module? Which settings and configuration options would need to be displayed with that interface?

The File Provider module is a component of the desktop client on macOS that provides virtual files-like file management. It's specific to macOS and has its own sync engine, connection to the server, and so on. In most ways, it's pretty much a separate desktop client which maintains a communication channel with the main desktop client

**Comment by claucambra** [comment]
Major components to work on:

- [ ] New menu entries for file provider settings window
- [ ] Separate, file-provider specific settings window
- [ ] Enable/disable settings in the GUI
- [ ] File eviction settings (i.e. how long to keep around for)
- [ ] Simple way to acquire debug logs

In my estimation this is 3 weeks of full time work

**Comment by dp466** [comment]
> Major components to work on:
> 
> * [x]  New menu entries for file provider settings window
> * [x]  Separate, file-provider specific settings window
> * [x]  Enable/disable settings in the GUI (per account)
> * [ ]  File eviction settings (i.e. how long to keep around for)
> * [ ]  Setting for file provider initial discovery method
> * [ ]  Simple way to acquire debug logs
> 
> In my estimation this is 3 weeks of full time work

any update on this ? id love to have that feature as the current implementation of the virtual files is almost useless
