### ISSUE TITLE
Build problems under Windows

### ISSUE THREAD

**Issue by MaDua** [nextcloud/desktop#570]
Hi,

at first I want to explain what I did and what tried to get the nextcloud client running:
1. I created a new virtual machine with Windows 10 to get clean environment for my tests

**Installing Qt**
2. I downloaded the Qt installer from https://www.qt.io/download-qt-installer?hsCtaTracking=9f6a2170-a938-42df-a8e2-a9f0b1d6cdce%7C6cb0de4f-9bb5-4778-ab02-bfb62735f3e5
3. In the Qt Setup Wizard I selected Qt 5.11.0 and MinGW 4.9.1 to install.
4. To my PATH variable I added C:\...\Qt\5.11.0

**Installing CMake**
5. I downloaded the Windows win64-x64 Installer from https://cmake.org/download/ and installed it
6. To my PATH variable I added C:\...\Cmake\bin

**Zlib**
7. I downloaded the 64 bit release from https://github.com/maxirmx/Dist_zlib and unzipped the folder
8. To my PATH variable I added C:\...\Zlib\bin and C:\...\Zlib\lib

**QtKeychain**
9. I cloned the repository from https://github.com/frankosterfeld/qtkeychain.git build it and got three files: qt5keychain.dll, qt5keychain.exp, qt5keychain.lib
10. To my PATH variable I added C:\...\QtKeychain\Release which contains these three files

**OpenSSL**
11. The link to the index of OpenSLL provided at https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client does not provide any OpenSSL 1.1.x version. The newest one provided is 1.0.2. So I searched a bit and I downloaded Win64 OpenSSL v1.1.0i from https://slproweb.com/products/Win32OpenSSL.html.
12. To my PATH variable I added C:\...\OpenSSL-Win64\bin which contains openssl.exe, libcrypto-1_1-x64.dll, openssl.cfg and so on

**Git**
13. I downloaded the Git installer from https://git-scm.com/downloads and made no changes in the installer and installed it

**Visual Studio**
14. I installed a VS 2017 Community Edition with the C++ package and the following additional components:
Visual C++ Tools for CMake
Windows 10 SDK for UWP C++
(not sure if that is all)

**Creating the nextcloud poject files**
15. In Git Bash I navigated to /c/.../nextcloud/desktop/
16. I run:
'mkdir build'
17. Navigated to /c/.../nextcloud/desktop/cmake\ and run:
'cmake -G "Visual Studio 15 2017 Win64" .. -DCMAKE_INSTALL_PREFIX=/c/.../nextcloud/desktop/build/ -DQTKEYCHAIN_INCLUDE_DIR=/c/QTKeychain/Release/ -DCMAKE_BUILD_TYPE=Debug -DNO_SHIBBOLETH=1'
18. Done (no errors)

**Build the nextcloud client**
19. In /c/.../nextcloud/desktop/cmake I run:
'cmake --build . --config Debug --target nextcloud'
20. Got the error that file clientsideencryption.cpp and httpcredentials.cpp cannot find keychain.h and qkeychain_export.h, so I copied these two files (and keychain.cpp) from the QtKeychain repository to where the files are localed under desktop/src/libsync and the errors don't occour anymore
21. Run 19. again and now I got over 50 errors like:
&gt;clientsideencryption.obj : error LNK2019: Unresolved external symbol "BIO_read" referenced in function ""class QByteArray __cdecl OCC::'anonymous namespace'::BIO2ByteArray(struct bio_st *)" (?BIO2ByteArray@?A0xd4adced4@OCC@@YA?AVQByteArray@@PEAUbio_st@@@Z)". [C:\Nextcloud_64\desktop\cmake\src\libsync\nextcloudsync.vcxproj]
&gt;clientsideencryption.obj : error LNK2019: Unresolved external symbol "BIO_write" referenced in function ""class QByteArray __cdecl OCC::EncryptionHelper::privateKeyToPem(class QSslKey)" (?privateKeyToPem@EncryptionHelper@OCC@@YA?AVQByteArray@@VQSslKey@@@Z)". [C:\Nextcloud_64\desktop\cmake\src\libsync\nextcloudsync.vcxproj]

I am not sure if this problem comes form OpenSLL or QtKeychain. Do I something missed copying or connect somehow?

Can anyone tell if hat is right what I am doing and if there is any way to get the client build.

Thank you very much in advance

**Comment by MaDua** [comment]
Adding these librarys: https://github.com/David-Reguera-Garcia-Dreg/Precompiled-OpenSSL-Windows/tree/master/openssl-1.1.0e-vs2012/lib to the additional dependencies of nextcloud and nextcloudsync solved the problem.

**Comment by silvamari** [comment]
@MaDua How did you build the qtkeychain files

**Comment by camilasan** [comment]
Hi! Take a look at the build.bat script:
https://github.com/nextcloud/client-building/blob/master/build.bat

**Comment by silvamari** [comment]
![image](https://user-images.githubusercontent.com/32284818/45050920-14127080-b05d-11e8-8bc2-8802e2ad82ba.png)
I have no idea why I am getting this error.

**Comment by keakarsu** [comment]
> 

> 
> 
> ![image](https://user-images.githubusercontent.com/32284818/45050920-14127080-b05d-11e8-8bc2-8802e2ad82ba.png)
> I have no idea why I am getting this error.

_I'm facing with the same error? Is there anybody knows the solution ? 
"Cannot open include file: 'qkeychain_export.h': No such file or directory""

**Comment by mgallien** [comment]
If you still have questions on how to build the desktop client, please go to https://help.nextcloud.com/ 
github issues are not a good way for us to provide support. I am closing this issue
