### ISSUE TITLE
[Bug]: KF5 (KDE archive library) as a requirements

### ISSUE THREAD

**Issue by mariolpantunes** [nextcloud/desktop#5702]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I use Slackware64-current, with only XFCE as my desktop environment (KDE is not installed).
During the last week, I tried to update the nextcloud-desktop application, but the compilations failed since it cannot find KF5Archive.
Previous versions of the application were compiled without any issues.
Is there any flag to disable KF5Archive (KDE as a whole) for the compilation?

### Steps to reproduce

Compiling the nextcloud on a system that does not use or ships KDE (or related libraries)

### Expected behavior

Being able to compile the code in my current system.

### Which files are affected by this bug

CMakeLists.txt

### Operating system

Linux

### Which version of the operating system you are running.

Slackware64-current

### Package

Compiled it myself

### Nextcloud Server version

23.0.1

### Nextcloud Desktop Client version

3.8.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @mariolpantunes it is not possible to compile the client without karchive. This is the only KDE-related dependency and you can install it independently of all other KDE packages

**Comment by pktiuk** [comment]
For others who found this issue: `sudo apt install libkf5archive-dev`

You should add this package to your docs in wiki https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client
