### ISSUE TITLE
Dailybuild: QT5Core.dll missing in WinSetup

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/desktop#572]
Nextcloud-2.5.0.61270-daily-20180822
Windows-setup doesn't install QT5Core.dll, but QT5Cored.dll thus leading to the following import-error during startup:
![image](https://user-images.githubusercontent.com/5834585/44450006-14882180-a5f0-11e8-89f2-8961fdcc511a.png)

bg,
++umgfoin

**Comment by camilasan** [comment]
Done! You can test it: https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61270-daily-20180822.exe

Thanks for the report!

**Comment by umgfoin** [comment]
Dyn.-import-error gone, but [issue #548](https://github.com/nextcloud/desktop/issues/548) appears after account-(re)creation upon initial sync.
Win7x64SP1
