### ISSUE TITLE
Show a NC Icon in Finder

### ISSUE THREAD

**Issue by muuvmuuv** [nextcloud/desktop#573]
When you have a look at Dropbox, they have a custom folder icon and I think NC can have that too.

![screenshot 2018-08-22 at 11 52 28](https://user-images.githubusercontent.com/11534760/44456807-deec3400-a601-11e8-8266-db96af4199ce.png)

**Comment by hiiamok** [comment]
Should be working with #625

**Comment by gpanders** [comment]
I had the cool Nextcloud icon in the Finder sidebar when I first installed it, but for some reason now it is back to the default folder icon (as in the screenshot in the OP).

How can I fix this? I really like the sidebar icon!

**Comment by muuvmuuv** [comment]
LGTM!
