### ISSUE TITLE
[Bug]: Nextcloud client does Not follow automatik light/darkmode switching completely

### ISSUE THREAD

**Issue by spuky** [nextcloud/desktop#5735]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Text color seems not to get switched
...
Started in Dark mode look after switching to light mode...
<img width="576" alt="Bildschirmfoto 2023-05-26 um 22 41 51" src="https://github.com/nextcloud/desktop/assets/271187/ba7e2ed8-821e-4425-966f-d03c406730f9">

Started in Light mode Look after switching to Darkmode:
<img width="576" alt="Bildschirmfoto 2023-05-26 um 22 42 55" src="https://github.com/nextcloud/desktop/assets/271187/69652f50-4094-4c82-ac38-8ff65b5d0eb3">

### Steps to reproduce

1. Start Nextcloud client...
2. Open System Preferences Appearance
3. Switch to the mode that was not set before...
...

### Expected behavior

Client looks the same as when you start it in that mode...
...

### Which files are affected by this bug

sorry no file...

### Operating system

Mac OS

### Which version of the operating system you are running.

Ventura 13.5 Beta (22G5027e)

### Package

Appimage

### Nextcloud Server version

26.0.1

### Nextcloud Desktop Client version

3.8.81 (macOS) 

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Will be fixed by #5715

**Comment by claucambra** [comment]
Now fixed, closing

**Comment by spuky** [comment]
Thanks confirmed fixed in latest beta
