### ISSUE TITLE
[Bug] 3.7.3 Broken Pipe 

### ISSUE THREAD

**Issue by frlan** [nextcloud/desktop#5738]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud is not starting 

```
Thread 1 "nextcloud" received signal SIGPIPE, Broken pipe.
__GI___libc_write (nbytes=80, buf=0x555555bb13f0, fd=17) at ../sysdeps/unix/sysv/linux/write.c:26
26	../sysdeps/unix/sysv/linux/write.c: Datei oder Verzeichnis nicht gefunden.
```

### Steps to reproduce

Don't know how to reproduce

### Expected behavior

Not closing ;)

### Which files are affected by this bug

none

### Operating system

Linux

### Which version of the operating system you are running.

Debian 12.0

### Package

Distro package manager

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Nextcloud version 3.7.3git
Using Qt 5.15.8, built against Qt 5.15.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.8 7 Feb 2023'
Running on Debian GNU/Linux 12 (bookworm), x86_64

**Comment by joshtrichards** [comment]
Hi @frlan 

1. Is this still occurring with newer versions of the client?
2. Can you reproduce this problem with the officially distributed AppImage?

**Comment by frlan** [comment]
@joshtrichards Have not seen it for a while -- and no, I'll use something like AppImage
