### ISSUE TITLE
[Bug]: Nextcloud context menu broken in OSX Big Sur

### ISSUE THREAD

**Issue by whoeveritis** [nextcloud/desktop#5755]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

in OSX Big Sur, NC Sync Client 3.8.2 and 3.9.50 will sync but will not provide the context menu to copy file sharing links, and the green *synced* icon signaling the sync took place is missing too.
...

### Steps to reproduce

1. Install NC Sync 3.8.2 in OSX Big Sur
2. wait for the sync ok icon in menu bar
3. go to your nextcloud synced folder
4. check if you can copy any links with a context menu (right click)

### Expected behavior

When opening the sync folder, files and folders should show a green sync icon net to the file name.
A right click on the file name would allow to copy a private or a public link to that file.
...

### Which files are affected by this bug

all synced files in the NC sync folder

### Operating system

Mac OS

### Which version of the operating system you are running.

11.7.8 Big Sur

### Package

Distro package manager

### Nextcloud Server version

25.0.7

### Nextcloud Desktop Client version

3.9.50

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nextclod server log here
https://wolkenmeer.com/index.php/s/eXJd4Zd5EdJJdj7
```

### Additional info

Client debug archive here
https://wolkenmeer.com/index.php/s/MPEmmWbyBsoaxP5

**Comment by PriscilliaGalarme** [comment]
Hello ;)

I have the same behavior on the 3.9.0 client app on Windows.

Steps to reproduce
    Install NC Sync 3.9.0 on Windows 11
    wait for the sync ok icon in menu bar
    go to your nextcloud synced folder
    use the right click: there are no context menu with share option
