### ISSUE TITLE
Providers: Do not display 'Log in' and 'Register with a provider' once the user clicked on 'Log in'

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#576]
- Only display a back button once the user clicked on 'Log in':

![provider](https://user-images.githubusercontent.com/241266/44526837-7aa2a080-a6e5-11e8-9048-69d1fea4b553.png)

- Remove the buttons 'log in', 'register with provider'.. only show a back button instead:

![provider2](https://user-images.githubusercontent.com/241266/44527039-04526e00-a6e6-11e8-8e66-4669d0bad97c.png)

@juliushaertl: this is a suggestion from @jancborchardt.

**Comment by juliushaertl** [comment]
Ah I missed that part.

>  only show a back button instead

Not sure if that is possible with the QWizard but I'll have a look.

**Comment by IzabelaBakollari** [comment]
When I click 'Register with a provider' takes me to a blank page. Should I open a new issue?

![screenshot_20190225_222054](https://user-images.githubusercontent.com/7606423/53369584-d297b980-394b-11e9-9eae-acaf916dc3d0.png)

**Comment by jancborchardt** [comment]
@IzabelaBakollari yes, best open a new issue for that! :) We need some feedback for people when that page doesn’t load for some reason. (It should load https://nextcloud.com/signup/ )
