### ISSUE TITLE
client login timeout is too short

### ISSUE THREAD

**Issue by pedro77pl** [nextcloud/desktop#579]
If IP is registered in oc_bruteforce_attempts, there is a time penalty for all logins originating from that IP (no matter what user name). Client connection timeout is too short and it tries to reconnect and login again without waiting long enough, falling into a login - retry loop. In the end information about lack of server connection is displayed.

We should have possibility to change connection timeout in options.

**Comment by GoetheG** [comment]
Had thr same issue many times. Hope the coding guys can fix that. Thanks in advance!

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
