### ISSUE TITLE
allowing Windows client to allow folder hard links to sync 

### ISSUE THREAD

**Issue by FINIUS** [nextcloud/desktop#58]
I would suggest to allow syncing of folder hard links to the Nextcloud client. At least as an opt-in feature, so that a copy of a users client folder can be synced without having to rearrange local folder usage nor reconfigure the sync configuration itself.

I use Windows 10 with latest build of Nextcloud Windows client.
 I set up a fresh sync with a new user, removed the default skeleton files and made some new links to local folders within the NextCloud sync directory, like:
mklink /J "C:\Users\john.doe\Nextcloud\Desktop" "C:\Users\john.doe\Desktop"
 The clients sees the link but logs that symlinks are not supported for sync and ignores it. 
<img width="1038" alt="33205011-b39baffa-d105-11e7-9f76-91910b806f93" src="https://user-images.githubusercontent.com/5287181/33212544-fc89cf1c-d123-11e7-92bd-3dfad15dd057.png">

**Comment by jcklpe** [comment]
While I understand why NextCloud doesn't allow symlinks because of the problems they can cause with recursion, an advanced user would sometimes need this feature and I think it would be worth considering, perhaps with a specialized dialog to add that specific link.

**Comment by afonsofrancof** [comment]
I would love to see this implemented as an opt-in.
I have several configuration files for programs that I would rather just symlink so they get updated automatically between my laptop and desktop.
That way, if I make a change to the config file of a program on my desktop, it would sync to nextcloud, which would sync it to my laptop and therefore sync the symlink. That way my config is always updated no matter where I change it from.

**Comment by Rello** [comment]
The clients were enhanced since this request, also to support lnk files. please evaluate if still relevant
