### ISSUE TITLE
[Bug]: Negative values in tray sync progress bar when uploading a folder with a few MBs of files

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#5804]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

A negative value is observed in place where the progress in MBs must be reported to the left of a progress bar in a tray windowa 

### Steps to reproduce

1. Copy a folder with a few MBs of files into the local sync folder
2. Open the tray window and keep track of values near the progress bar
3. Observe negative values after at least half of the folder was uploaded 

### Expected behavior

Correct values must be displayed

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

All

### Package

Appimage

### Nextcloud Server version

all

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by anonbergine** [comment]
Looks like duplicate of https://github.com/nextcloud/desktop/issues/5519

**Comment by allexzander** [comment]
duplicate of https://github.com/nextcloud/desktop/issues/5519
