### ISSUE TITLE
[Bug]: 3.9.0 doesn't show e2ee directories anymore

### ISSUE THREAD

**Issue by eibex** [nextcloud/desktop#5806]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

3.9.0 doesn't show e2ee directories anymore (VFS is enabled)

### Steps to reproduce

1. Open file explorer and navigate to the nextcloud directory

### Expected behavior

I can see all folders, including e2ee ones

### Which files are affected by this bug

folders

### Operating system

Windows

### Which version of the operating system you are running.

11 

### Package

Appimage

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Just to be clear, there are no errors reported

**Comment by eibex** [comment]
Just to be clear, there are no errors reported

**Comment by eibex** [comment]
Disabling and re-enabling VFS fixed this. Not closing the issue for now as multiple restarts of the last days didn't fix it (not sure what caused it while updating to 3.9.0).

**Comment by eibex** [comment]
I have now noticed that changes on E2EE folders aren't correctly picked up by the client. 

I created a test folder and it got created on the server as expected, but once I deleted it, I had to delete it from the server with the iOS app as the desktop app said the directory was correctly synced.

**Comment by bcutter** [comment]
> I have now noticed that changes on E2EE folders aren't correctly picked up by the client.
> 
> I created a test folder and it got created on the server as expected, but once I deleted it, I had to delete it from the server with the iOS app as the desktop app said the directory was correctly synced.

That's not just inside an E2EE folder, but also outside (not encrypted folders). See https://github.com/nextcloud/desktop/issues/5918
