### ISSUE TITLE
[Bug]: Nextcloud-3.9.0-x86_64.AppImage: error while loading shared libraries libdbus-1.so.3: 

### ISSUE THREAD

**Issue by yangboyd** [nextcloud/desktop#5822]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

./Nextcloud-3.9.0-x86_64.AppImage: error while loading shared libraries: /tmp/.mount_Nextcl31FG2c/usr/bin/../lib/libdbus-1.so.3: cannot read file data: Error 103

### Steps to reproduce

./Nextcloud-3.9.0-x86_64.AppImage

### Expected behavior

No Error

### Which files are affected by this bug

Nextcloud-3.9.0-x86_64.AppImage

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.10

### Package

Appimage

### Nextcloud Server version

27

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
No
```

**Comment by yangboyd** [comment]
syslog

Jun 18 23:13:41 kernel: [  759.394069] Nextcloud-3.9.0[3983]: segfault at 0 ip 00000000004075fc sp 00007ffc5cf0d6c0 error 4 in Nextcloud-3.9.0-x86_64.AppImage[400000+2b000]
Jun 18 23:13:41 kernel: [  759.394079] Code: ff ff 49 89 c8 89 d1 48 89 fa 48 89 c7 e8 33 0d 00 00 89 45 ec 83 7d ec 00 74 08 8b 45 ec e9 0f 01 00 00 48 8b 85 78 ff ff ff <48> 8b 00 48 89 85 68 ff ff ff 48 8b 85 68 ff ff ff 48 2b 45 f8 48

**Comment by joshtrichards** [comment]
Closing due to no further follow-up received to last query for >6 months.  This sounds like it was something like a corrupted download or filesystem. Haven't seen similar reports.
