### ISSUE TITLE
[Bug]: notification

### ISSUE THREAD

**Issue by zzj2039** [nextcloud/desktop#5828]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hi, I'm having some problems with the nextcloud desktop client, I often don't receive notification messages, I can only open the main screen to receive them, which is frustrating me

### Steps to reproduce

Install the desktop client, log in, and then notifications don't pop up

### Expected behavior

Receive notifications in time, just like WeChat

### Which files are affected by this bug

no

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.2

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Mika-6-9** [comment]
We updated Nextcloud to version 27 and no more problems

**Comment by jospoortvliet** [comment]
perfect
