### ISSUE TITLE
MacOS FileProvider Ventura 13.4

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/desktop#5830]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
This issue is related to #1337 .
The VFS Beta 2 client seems to work much better under Ventura 13.4 than under Monterey (where it was much less responsive than the Beta 1).
Seems like the FileProvider framework behaves differently among different major versions of Mac OS.
Now under Ventura it seems to be CPU hungry: upon usage of the share in Finder (i.e. opening a folder that was never previously opened, fetching a file contents), the FileProviderExt process tends to eat up to 100% of one core for many seconds.

The logs of FileProviderExt are almost quiet given the amount of CPU used, so it's not easy from a user perspective to guess what's going on but there aren't many requests outgoing (can see it checking the web server logs). Seems pretty much a CPU bound task.

A profiler run would be very useful in such environment (Ventura 13.4 and a fairly populated NC share) as it may help finding a hot spot.

Thanks and regards!

**Comment by Saifudaullah** [comment]
Hi, where can I get VFS Beta 2 client?

**Comment by Saifudaullah** [comment]
hi @marcotrevisan, where can we download the VFS Beta 2 client? I'm unable to find it in https://download.nextcloud.com/desktop/prereleases/virtualdrive/ and also unable to access https://cloud.nextcloud.com/s/8JnmYA8a7xDm9tT.

Can you point me where I can find the installer?

**Comment by marcotrevisan** [comment]
Hi @Saifudaullah,
here is the link to the source comment:  https://github.com/nextcloud/desktop/issues/1337#issuecomment-1547167377

Cheers,

**Comment by Saifudaullah** [comment]
Hi @marcotrevisan i’ve tried to open the link inside the comment, but it says i don’t have the access

**Comment by marcotrevisan** [comment]
The release is out and this issue is not showing up any more.

**Comment by marcotrevisan** [comment]
> Which release contains the virtual file feature?

Please see: https://github.com/nextcloud/desktop/discussions/6656

There you'll find the download link. 
Regards
