### ISSUE TITLE
[Bug]: Need to reauthenticate at each client launch

### ISSUE THREAD

**Issue by canoine** [nextcloud/desktop#5831]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Each time I launch the nextcloud desktop client, all my accounts are disconnected, and I need to re-authenticate inside the application web interface.

[![nextc-01.jpg](https://i.postimg.cc/XYSkH2QR/nextc-01.jpg)](https://i.postimg.cc/XYSkH2QR/nextc-01.jpg)
[![nextc-02.jpg](https://i.postimg.cc/MHnm4gkS/nextc-02.jpg)](https://i.postimg.cc/MHnm4gkS/nextc-02.jpg)
[![nextc-03.jpg](https://i.postimg.cc/pr3Jtkxn/nextc-03.jpg)](ttps://i.postimg.cc/pr3Jtkxn/nextc-03.jpg)

And each new authentication is a new session :
[![nextc-04.jpg](https://i.postimg.cc/9FqBB3tP/nextc-04.jpg)](https://i.postimg.cc/9FqBB3tP/nextc-04.jpg)

As I already said in #5466, all worked well under a 6.1.27 kernel. The problem appears when I reboot on a newly compiled 6.1.28 kernel on the stations. Today, I run a 6.1.31 kernel, with the same bug.

### Steps to reproduce

1. Launch the desktop client
2. Authenticate
3. Stop the client
4. Launch the desktop client
5. Authenticate
6. Stop the client
...

### Expected behavior

The credentials should be kept.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Gentoo stable and up-to-date

### Package

Distro package manager

### Nextcloud Server version

25.0.3, 25.0.4, 25.0.6, 26.0.0, 26.0.1. On two different servers (Gentoo and Debian 8).

### Nextcloud Desktop Client version

3.7.3 and 3.8.0. On two different stations (Gentoo both).

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

If you really want my logs and debug archives, I need to anonymize all the names (domain, files, and so on)...

**Comment by Flowdalic** [comment]
Same here with nextcloud-desktop 3.9.1. Any suggestions on how to debug and approach this issue would be appreciated.

**Comment by Flowdalic** [comment]
See also
- https://github.com/nextcloud/desktop/issues/2573#issuecomment-1632600322
- https://bugs.gentoo.org/912844

**Comment by canoine** [comment]
That's it ! You made my day @Flowdalic . :smiley: 
Adding the "keyring" USE flag for dev-libs/qtkeychain solved the issue.

**Comment by Gahia123** [comment]
> That's it ! You made my day @Flowdalic . 😃 Adding the "keyring" USE flag for dev-libs/qtkeychain solved the issue.

Do you mean add this flag on the client or server side?

**Comment by canoine** [comment]
Hello @Gahia123,
On the client side, on a Xorg/GTK DE. So Qt is needed by the desktop client only. I don't need any DE on my servers.

**Comment by Dominique-M** [comment]
This happens to me under Ubuntu 24.04 with Nextcloud-3.14.0-x86_64.AppImage. (I have no such problem with 3.13.3.) I tried simply connecting and also connecting as an application. In both cases 3.14 asks authentication again at the next launch.

**Comment by raider-com** [comment]
https://github.com/nextcloud/desktop/issues/5831#issuecomment-2351482459
Can second this.
Prior to this, never had this happen between client application upgrades.
With 3.14.0 app image, happens every time on 3 different PCs that got that upgrade

**Comment by gvoigtlaender** [comment]
Same here with Debian Trixie and 3.14.0. Going back to 3.13.4 works fine

**Comment by DLeich** [comment]
Adding my +1 on the experience.  Upgrade to 3.14.0 triggered this behavior.  Happening on all three of my Ubuntu 24.04 systems.
