### ISSUE TITLE
[Bug]: binaries missing in the assets in the new release

### ISSUE THREAD

**Issue by ev75** [nextcloud/desktop#5837]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

We use a powershell script to update the NextCloud client on Windows via the task scheduler since the users don´t have administrator rights. Ever since the new release the binaries are missing in the assets and the client cannot be updated. 

### Steps to reproduce

$webAPIData = Invoke-RestMethod -Uri "https://api.github.com/repos/Nextcloud/desktop/releases/latest"
$assets = $webAPIData.assets

$asset = $assets | where-object { $_.name -match "-x64" -and $_.name -match ".msi" -and $_.name -notmatch ".asc"}
$ver1 = $asset.name.Substring(10,5)

$ver1 will be NULL. 

### Expected behavior

the script is supposed to check the version of the latest release and compare it with the installed version. 

### Which files are affected by this bug

none

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 and 11

### Package

Appimage

### Nextcloud Server version

not relevant

### Nextcloud Desktop Client version

not relevant

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
they are hosted there https://github.com/nextcloud-releases/desktop/releases
in the future they are only to get hosted there 
alternatively they have always been published on download.nextcloud.com/desktop/releases/

**Comment by ev75** [comment]
unfortunately I don´t think this will work with the script. the site used to look like this: https://web.archive.org/web/20220413201559/https://api.github.com/repos/Nextcloud/desktop/releases/latest
