### ISSUE TITLE
resolve conflicts dialogue shows wrong information (dates)

### ISSUE THREAD

**Issue by kleajmp** [nextcloud/desktop#5840]
Is this a bug or am I wrong?
running desktop client v3.9.0 on openSuse

first of all I am super happy that the resolve all conflicts dialogue implementation is finally released.
it works for me when I check "All server versions" to keep all newest versions of all files.

but here is the bug:

- when I really check the dates next to the individual files the **server version column** shows the **older date** (actually **the exact date of the local version**) so these two columns are faulty reversed (!)
- when I select "**keep local version**" the **newest file is overwritten by the older local copy**
- when select "keep server version" a new set of dialogs appear to confirm if I want to delete the older conflicted copy, a button "**yes to all**" would be a great addition.

so the thinks to do in my advice:

- [ ] check the date info which are in my case (both on windows as opensuse client) shown in the wrong (opposite) column
- [ ] add a "yes to all" button in the  "confirm deletion dialogue" after choosing to keep al the newest versions (server version)

here some images to illustrate the bug and the suggested button addition:
![Screenshot_20230622_194304](https://github.com/nextcloud/desktop/assets/12158499/5ff70723-3897-4107-85a0-453a91c327c7)
![Screenshot_20230622_194556](https://github.com/nextcloud/desktop/assets/12158499/65d8beeb-27ce-4f1c-9848-353d5fc7d366)
![Screenshot_20230622_195223](https://github.com/nextcloud/desktop/assets/12158499/3a2eb8a7-e685-4d7b-8706-bc7b2e5bfb52)
![Screenshot_20230622_195512](https://github.com/nextcloud/desktop/assets/12158499/6802ab81-dc3b-4d49-ad1c-ebed03355cfa)

_Originally posted by @kleajmp in https://github.com/nextcloud/desktop/issues/5635#issuecomment-1603135154_

**Comment by mgallien** [comment]
@kleajmp thanks for your report
I will have a look and post my feedback here

**Comment by konradbr** [comment]
Hello,

I confirm this is a #bug and that I am experiencing the same issue. Please see attached screenshot:

![Screenshot 2023-07-16 133409 - Copy](https://github.com/nextcloud/desktop/assets/28401247/08c24789-55bd-4b53-a9dd-9bc876e46087)

This should be tagged #bug and #urgent as it can lead to loss on edited files on clients unless one has figured out what's happening!

Best,

Konrad

**Comment by mgallien** [comment]
fixed by #6043
