### ISSUE TITLE
Linux app doesn't honor certificate override

### ISSUE THREAD

**Issue by egazz** [nextcloud/desktop#586]
I have a Nextcloud instance on a VPS, and it has a self-signed SSL certificate.  The desktop app on Linux gives a warning about the certificate, but then has an option to "trust this certificate anyway" (which is obviously what I want).  But once that's selected and I click OK, it just goes to a webpage with an error saying that the page cannot be displayed due to an invalid SSL certificate.

Is there any way to get it to actually use the override?

I'm running Archlinux x64, kernel version 4.18.4, and I downloaded the AppImage from here within the last couple of days.  (I'll add that I had to extract the AppImage, since it couldn't find FUSE, but I think that may be on my end.)

**Comment by camilasan** [comment]
Hi! Which version of the desktop client you are running?

**Comment by camilasan** [comment]
I understand now it was one the daily builds.

**Comment by egazz** [comment]
Hi, sorry for the delay in reply!  I'm not 100% sure what version, since I don't have the original file anymore and I couldn't find it anywhere in the AppImage.  But I can tell you that I got it from [this page](https://nextcloud.com/install/#install-clients) on August 26.

Here's the console output when I hit the error:

```[3366:3385:0902/185555.690580:ERROR:cert_verify_proc_nss.cc(944)] CERT_PKIXVerifyCert for [IP ADDRESS] failed err=-8172```

**Comment by fwsGonzo** [comment]
I just got the exact same message on Ubuntu 18.10. My certificate is from Let's Encrypt X3 and it's working for us on Windows so far. I'm not entirely sure why it can't verify it, but it won't remember me trusting it either.

**Comment by rullzer** [comment]
Should be fixed once #758 is in
