### ISSUE TITLE
[Bug]: Desktop client sync downs/hogs laptop internet connection

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#5876]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

At regular intervals my internet connection seems to drop. This happens when I am in Talk calls, dropping the connection, or just when using Github or browsing the web.

When I just observed it again, I got this "Unable to connect" error e.g. on Github.com (also on Fast.com for testing). When looking at the Nextcloud desktop client tray icon it was in "syncing" (or checking) state. And **immediately** after using "Exit Nextcloud", the pages were loading again.

![image](https://github.com/nextcloud/desktop/assets/925062/79c0ec1d-21ce-4993-b695-192a1a7186ef)

### Steps to reproduce

1. Use the Nextcloud desktop client on Ubuntu
2. Wait for it to sync
3. Possibly have it block your internet connection

What might be a possible reason is that the download and upload bandwidth is set to "No limit"? This seems to be the default though. I changed it to "Limit automatically" now to test, let me know if I should try something else.

![image](https://github.com/nextcloud/desktop/assets/925062/9f2a645a-bc44-4633-bb9a-400a0e5ce6a2)

### Expected behavior

There is no internet connection outage caused by the desktop app.

### Which files are affected by this bug

No specific file, but it occured right before I exited the Nextcloud client, restarted it and immediately generated the debug archive.

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04.2 LTS

### Package

Distro package manager

### Nextcloud Server version

current on cloud.nc

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Debug archive: [Debug.zip](https://github.com/nextcloud/desktop/files/12001464/Debug.zip)

**Comment by claucambra** [comment]
Hey @jancborchardt the rate limiter should help with reducing the network load caused by client sync, yes -- you should hopefully see some improvement. If not, you can try to manually set a limit in KB/s.

Of course, this will increase the duration of sync

**Comment by jancborchardt** [comment]
This issue unfortunately still occurs with "Limit automatically". :\ And I would expect it to not even happen that hard even if there is "No limit" set, which is the default.

(Manually setting a limit is not really feasible I think, one has to be way too technically apt to know which values to put in there.)

**Comment by tobiasKaminsky** [comment]
Is client actually syncing when you experience this? 
So you see up/download progress?

**Comment by PhilippSchlesinger** [comment]
Does this problem occure regardless if the tray window is shown or not?

**Comment by jancborchardt** [comment]
> Is client actually syncing when you experience this?
> So you see up/download progress?

I see the syncing icon, but not sure about the "actually syncing". I will keep open a network tool on the side.

> Does this problem occure regardless if the tray window is shown or not?

Usually it occurs when the tray window is closed, if that's the question.

**Comment by PhilippSchlesinger** [comment]
> Usually it occurs when the tray window is closed, if that's the question.

That was my question. There is a bug regarding massive (network) slow down https://github.com/nextcloud/desktop/issues/4918 when the try window is open, that's why I asked if it maybe is related to that.

**Comment by jancborchardt** [comment]
No, so I actually always had it with the tray window closed, as it happens at random times. (As said I suspect on sync.)

It could possibly also have something to do with Talk as it more often seems to happen during Talk calls (using the web interface).

**Comment by tobiasKaminsky** [comment]
To rule out Desktop client, maybe you can shut down client during calls?

**Comment by allexzander** [comment]
Could not catch the issue on Windows, but on Ubuntu it is possible to completely break a connection when running Chrome with youtube + desktop client  + speed test, and it does not restore after exiting the desktop client.

@jancborchardt maybe, when you have this issue occurring, you could run some network monitoring tool, e.g. `sudo nethogs` ?
