### ISSUE TITLE
Nextcloud client does not login to nc-server after client-update and client reboot

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/desktop#588]
Hello,

I tested with latest version 2.5.0daily (build 20180827) built from Git revision 16337b on Aug 27 2018.
I noticed that _since_ build 20180823 or build 20180823 problems with connecting / log-in to the server. After a update of the client to one of the latest builds, when the nc-client is started, it is not able to log in and get sync status of files. There is no error message, but sync status remains grey.
Only when I log-out manually (in nc-client) an re-log-in (typing the complete credentials for user and password) the client connects successfully and shows me sync status (green).
This also happens when I reboot my laptop. The complete log-out and log-in process of nc-client has to be done again to get the nc-client working.

OS: Windows 10 Pro 64-bit
NC-Client: 2.5.0daily (build 20180827) built from Git revision 16337b

Regards

**Comment by camilasan** [comment]
Hi! Please try https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61352-daily-20180904.exe. This issue should be solved.
Thanks!

**Comment by blu-IT** [comment]
Hi,

thanks a lot! 

I can confirm that the login works after the update of the client with the last build out of the box!

Thanks for your effort!

Regards
