### ISSUE TITLE
Save the new URL when hitting a permanent redirection 301

### ISSUE THREAD

**Issue by quentingosset** [nextcloud/desktop#589]
I do not know if this ([https://github.com/owncloud/client/issues/5972]()) is already applied to nextcloud ?

Currently if I leave the 301 redirection the desktop client detects the redirection as the synchronization works. However, the url of the account still does not change. so we have to leave the 301 redirect.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
