### ISSUE TITLE
[Bug]: "server" and "client" file versions mixed up in Desktop Client "Solve sync conflicts" dialog

### ISSUE THREAD

**Issue by konradbr** [nextcloud/desktop#5892]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Files show up in the incorrect columns in the "Solve sync conflicts" dialog in NextCloud Desktop for Windows 11: local versions appear in the "server" column, and server versions appear in the "local" column.

Example:

![Screenshot 2023-07-16 133409 - Copy](https://github.com/nextcloud/desktop/assets/28401247/f14f0190-c0b0-4019-8adb-aa09709447d3)

The exact behaviour when attempting to sync cannot be determined. (I believe to have experienced mixed outcomes, thence am not trying to use this functionality until the issue is addressed, in fear of losing newer versions of my files.)

Similar behaviour has been reported here, but the post is not marked as a bug report and the title does not properly describe the issue: https://github.com/nextcloud/desktop/issues/5840

### Steps to reproduce

In Windows 11:

1. Left-click on tray NextCloud icon.
2. Click on blue "resolve conflicts" at the top of the activity list:

![Screenshot 2023-07-16 134853](https://github.com/nextcloud/desktop/assets/28401247/74df0558-8173-4983-a220-6c8e12fe14d6)

### Expected behavior

Behaviour must be similar to that of the single-file deconfliction dialog.

### Which files are affected by this bug

[ConfidentialFiles]

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

25.0

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Alternativend** [comment]
We can confirm this bug here. 

Please provide a fix soon, we already have lost a few files because people choosing the "wrong"  option.

**Comment by mgallien** [comment]
fixed by #6043
