### ISSUE TITLE
[Bug]: Can't rename files on MacOS Ventura (13.4.1) with VFS

### ISSUE THREAD

**Issue by Occhioverde** [nextcloud/desktop#5899]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When renaming a file in the Nextcloud VFS on MacOS Ventura, the new name gets automatically changed to the old one after a couple of seconds.

### Steps to reproduce

1. Right-click on a file in the Nextcloud VFS mount
2. Select "Rename"
3. Type and confirm the new file name
4. Wait for a couple of seconds and see the file being renamed to the old name

### Expected behavior

The new file name should be saved and synched to the server

### Which files are affected by this bug

01.LAVORO/01.STUDIO LEGALE/01.PRATICHE/V[REDACTED]m/R[REDACTED]e - 7[REDACTED]7/DEPOSITO D.I./Archivio.zip

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS Ventura 13.4.1

### Package

Other

### Nextcloud Server version

26.0.3

### Nextcloud Desktop Client version

Nextcloud VFS Beta (2023-03-21)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Relevant log entries from MacOS Console (filtered for "com.nextcloud.cloud.FileProviderExt"):

```
errore	11:00:24.085326+0200	FileProviderExt	Could not move file or folder: https://cloud.avvocatodanielebonomi.it/remote.php/dav/files/dbonomi/01.LAVORO/01.STUDIO LEGALE/01.PRATICHE/V[REDACTED]m/R[REDACTED]e - 7[REDACTED]7/DEPOSITO D.I./Archivio.zip to https://cloud.avvocatodanielebonomi.it/remote.php/dav/files/dbonomi/01.LAVORO/01.STUDIO LEGALE/01.PRATICHE/V[REDACTED]n/R[REDACTED]e - 7[REDACTED]7/DEPOSITO D.I./DOCC. 02-31.zip, received error: "01.LAVORO/01.STUDIO LEGALE/01.PRATICHE/V[REDACTED]n/R[REDACTED]e - 7[REDACTED]7/DEPOSITO D.I./Archivio.zip" is locked
errore	11:00:24.085618+0200	FileProviderExt	Stopping rename of item with ocId 00903736oc7ol3ejaau2 due to error: Il tuo dispositivo non ha potuto connettersi con il server. Potrebbe esserci un problema con il server o con la rete.
```

**Comment by marcotrevisan** [comment]
Is this issue still relevant? 
I can't reproduce it using the 3.13.0-macOS-vfs release.

**Comment by Occhioverde** [comment]
This problem is unfortunately still relevant for the 3.13.2 version of the client on macOS Sonoma, but I'm closing this issue in favor of #6500 as it contains more details and discussions.
