### ISSUE TITLE
Allsync cloud provider

### ISSUE THREAD

**Issue by dimqua** [nextcloud/desktop#590]
There is a new cloud storage provider called [Allsync](https://allsync.com) which is (obviously) uses nextcloud (and probably owncloud too) software without any notice users about this fact. The problem is they distribute "their own" client software such as [Windows](https://allsync.com/d/windows.php) and Android clients based on original nextcloud clients which are licences under GPLv2. But Allsync's developers do not publish any source code of changes they made, so (to my understanding) they violating both the license and copyright law:

![](https://i.imgur.com/6qZkGyr.png)

**Comment by camilasan** [comment]
Thanks for the report! We will check it...

@jospoortvliet Do you know anything about it?

**Comment by jospoortvliet** [comment]
well, you shared the about dialog - which properly credits ownCloud and Nextcloud for their work. If the built is made directly from our git repo with no other changes (or only trivial ones like that link to allsync.cloud and some theming/configuration) and links to our github for the source, they are at worst a little impolite.

Of course, if they have made real changes, code-wise, adding features for example, they have an obligation to share the code behind that, on request. @dimqua - if you see any changes/features, perhaps you can ask them for the code? As a recipient of the binary, that is your right. If there are no changes, I don't want to make a big deal...
