### ISSUE TITLE
[Bug]: Error after Installing Desktop Client 3.9.1 via auto updates

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#5920]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

![image](https://github.com/nextcloud/desktop/assets/59488153/573e1e3c-1494-41da-8fca-3aec61721f99)

### Steps to reproduce

Insatll Nextcloud 3.9.1 via auto update

### Expected behavior

No error
...

### Which files are affected by this bug

n/a

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

27.0.1

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by EmberHeartshine** [comment]
Confirming this on Windows 10 LTSC build 1801. Manually downloading the installer from [here](https://nextcloud.com/install/#install-clients) and running a Repair installation fixed the issue, so it seems to be a problem with whatever binary the auto-updater downloads.

**Comment by Githopp192** [comment]
Nexcloud 26.0.4

![ScreenShot007](https://github.com/nextcloud/desktop/assets/32612067/18c727ca-586e-4625-b934-9f04b950eb7d)

![ScreenShot006](https://github.com/nextcloud/desktop/assets/32612067/d2424268-47cb-45e0-98ed-034437cd285a)

Desktop Agent does not start anymore

**Comment by limatus** [comment]
No issue for me using the auto updater. Windows 11; 22H2; Server 27.0.1

**Comment by Githopp192** [comment]
Yes, do confirm - re-install (with repair option) of Nextcloud-3.9.1-x64.msi did solve this issue.

Matthieu - btw - the officlal repo (https://download.nextcloud.com/desktop/releases/Windows/) does not show-up the 
391 release & also, the officlal Download "https://github.com/nextcloud-releases/desktop/releases/download/v3.9.0/Nextcloud-3.9.0-x64.msi" does still link to the 3.9.0

As for myself - i only allowed "stable releases"

So the question popped up: was/is release 391 a stable one ?
When yes, why it does not appear on the official download repos ?
When no, why my desktop agent suggest to me to install this version ?

![ScreenShot008](https://github.com/nextcloud/desktop/assets/32612067/633183b5-3aba-48ea-ab39-133a23383c83)

**Comment by davidmarshall15** [comment]
Confirming this on Windows 11, went back to 3.9.0 and then had to repair to get the client working.

Windows 11 Pro (22H2)
OS build: 22621.1992

**Comment by bgeneto** [comment]
Confirm several missing dlls with Windows 11 Pro after auto updating Nextcloud client today :-( 

<img width="304" alt="image" src="https://github.com/nextcloud/desktop/assets/473074/0fca07ce-d9d2-4693-9a80-20dbd773de52">

<img width="431" alt="image" src="https://github.com/nextcloud/desktop/assets/473074/8edebc7c-fbeb-4082-af0a-ddd450001000">

**Comment by JVT038** [comment]
For me, it's entrypoint `RSA_pkey_ctx_ctrl` in DLL-file `C:\Program Files\Nextcloud\nextcloudsync.dll` and entrypoint `SSL_SESSION_is_resumable` in DLL-file `C:\Program Files\Nextcloud\Qt5Network.dll`.

**Comment by mgallien** [comment]
the updated packaged is published

**Comment by Githopp192** [comment]
> the updated packaged is published

Thanks Matthieu
