### ISSUE TITLE
[Bug]: v3.9.1 client fails to sync shared folders with greek (possibly other utf-8) characters

### ISSUE THREAD

**Issue by hadjilucasL** [nextcloud/desktop#5922]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Desktop: Windows 11

Was on client 3.9.0, received a share with a folder containing a subfolder with a greek name, e.g. `Δημοσιεύσεις`. Worked fine. Could see all folders.
![image](https://github.com/nextcloud/desktop/assets/295876/c75643f3-8b42-4908-a7bd-8ea7384511d3)

Upgraded to client 3.9.1, received another share with subfolders with greek names. This time subfolders with greek names failed to sync to desktop. Folders were visible online. There was no warning/indication that there was an error on the client side.
![image](https://github.com/nextcloud/desktop/assets/295876/1d6ee9c4-913c-449b-8cb8-ca030519cc0b)

Server running: [Nextcloud Hub 5](https://nextcloud.com/) (27.0.1)

### Steps to reproduce

- Install desktop client 3.9.1, server 27.0.1
- Share a folder containing subfolders with a greek name (possibly other utf8 characters?)
- Person receiving the share sees all subfolders except the ones with greek names

- Re-install client 3.9.0. Unshare and re-share. Subfolders with greek names make appearance again.

### Expected behavior

All subfolders (inc the ones with purely foreign characters) should be visible in the share. Unsharing and sharing again with v3.9.0 client provides expected behavior.

### Which files are affected by this bug

`Δημοσιεύσεις`

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

27.0.1

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info
Can provide debug logs if needed.

**Comment by hadjilucasL** [comment]
Thanks!  It does seem this might be the issue.. although I am not sure why shares were working ok in v3.9.0 🤔

**Comment by cedvan** [comment]
Same for me, since upgrading to 3.9.1. Some files are no longer synchronized.

My music files by artist "Ayọ" are ignored because of the specific o.
All files with an "X-X" in their name are ignored ("In-Between.flac", "Hors-Saison.flac", etc...)

**Comment by PhilippSchlesinger** [comment]
There is a very similar bug https://github.com/nextcloud/desktop/issues/5935

**Comment by cedvan** [comment]
Solution proposed in https://github.com/nextcloud/desktop/issues/5935 solve my problem :D
