### ISSUE TITLE
[Bug]: Missing OpenSSL libraries on Client 3.9.1

### ISSUE THREAD

**Issue by bastien-martin** [nextcloud/desktop#5923]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello,

Updating NextCloud client for Windows 10 (64-bit) from 3.9.0 to 3.9.1 breaks NextCloud Client because of 2 missing files:

- libcrypto-1_1-x64.dll
- libssl-1_1-x64.dll

I've manually put these two files, from OpenSSL 1.1.1.4, on the root NextCloud client directory (C:\Program Files\Nextcloud) and it's working. With OpenSSL 1.1.1.7, it's not working.

Sorry about the French error message 👎 

![libcrypto_missing](https://github.com/nextcloud/desktop/assets/122611104/e84ede55-458e-44b8-8fc3-1e86de42d3ca)
![libssl_missing](https://github.com/nextcloud/desktop/assets/122611104/d71313fa-62cd-4efc-95c5-f5283c31ec57)

### Steps to reproduce

1. On a fresh Windows 10 x64 installation, install NextCloud client 3.9.0
2. Update it from the Client and, optionaly, restart your computer.

(Tried twice, and had the same behavior twice)

### Expected behavior

A NextCloud Client 3.9.1 working.

### Which files are affected by this bug

libcrypto-1_1-x64.dll, libssl-1_1-x64.dll

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

23.0.8

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Duplicates https://github.com/nextcloud-releases/desktop/issues/1, sorry

**Comment by PhilippSchlesinger** [comment]
In https://github.com/nextcloud/desktop/issues/5920#issuecomment-1650540344 it is noted that an updated package has been published.
You can download it here https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-3.9.1-x64.msi
and install it to fix your installation.

**Comment by bastien-martin** [comment]
Fixed typo in version, it's 3.9.0 to 3.9.1 and not 1.9.0 to 1.9.1
