### ISSUE TITLE
[Bug]: libcrypto-1_1-x64.dll not found 

### ISSUE THREAD

**Issue by Liffecs** [nextcloud/desktop#5925]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating the stable release, Nextcloud cannot install itself because the dll libcrypto-1_1-x64.dll cannot be found. See German image. (My OS is German)
libssl-1_1-x64.dll not found.
![image](https://github.com/nextcloud/desktop/assets/135852107/96197ef9-78bd-4c5d-943e-1e38abcd6550)
![image](https://github.com/nextcloud/desktop/assets/135852107/16ded7af-764a-4e12-81bf-f9c8406fe813)

### Steps to reproduce

1. install an old Nextcloud Desktop instance 
2. use it for a while.
3. do the update

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

Nextcloud Desktop self

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

26.x.x

### Nextcloud Desktop Client version

none (it's broke ^^)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Not necessary, because only the client itself has the problem.
```

### Additional info

Not necessary, because only the client itself has the problem.
The zip archive is empty. But to create the issue you need one. Therefore I have zipped a MIT license ^^.

[empty.zip](https://github.com/nextcloud/desktop/files/12171428/empty.zip)

**Comment by Liffecs** [comment]
The server is up to date (Ubuntu 22.04 and Nextcloud).
The problem is only related to the update of the local client.

**Comment by SP4RT4N3R** [comment]
These error Notifications can be solved by simply installing the DLLs into Nextcloud folder.
then there gets another problem

**Comment by Liffecs** [comment]
> These error Notifications can be solved by simply installing the DLLs into Nextcloud folder. then there gets another problem

I have uninstalled Nextcloud (desktop). So the data in ``%APPDATA%`` and the local files from the sync I kept. When I reinstall that went the installation process

**Comment by PhilippSchlesinger** [comment]
See https://github.com/nextcloud/desktop/issues/5924#issuecomment-1651290712

**Comment by Liffecs** [comment]
> See [#5924 (comment)](https://github.com/nextcloud/desktop/issues/5924#issuecomment-1651290712)

Nice. then I close this duplicate :)
