### ISSUE TITLE
Activities design review

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#5933]
- [x] File sharing: not all files have the option to share or view details (bug?)

- [x] The progress bar for  'sync now' is too high and it should only show up if the sync will take more than ~2 seconds. Only the spinner is enough when it is so quick.
- [x] Show 'Synced' activities: only things you did locally, not changes from the server (what comes back as activities)
    - Avatar should be shown when there is an activity: 'John edited file'. → https://github.com/nextcloud/server/issues/16207
    - All activities that need interaction needs to be on top: does the 2fa notification is coming via push notification?
- [x] when new item, scroll automatically to top

**Comment by jancborchardt** [comment]
To add:
- Also investigate if it is possible to show the notification for "Log in via notification" quicker. Currently the possible wait time is up to 5 minutes cc @mgallien

**Comment by tobiasKaminsky** [comment]
Show icons: https://github.com/nextcloud/server/issues/16207

**Comment by allexzander** [comment]
@jancborchardt Should this happen always?

- when new item, scroll automatically to top

I can already expect how the user might get annoyed when in search for one of the older items and not being to reach it cause the auto-scrolling is happening during intensive sync/lots of notifications from the server

**Comment by allexzander** [comment]
@jancborchardt as for:

- The progress bar for 'sync now' is too high and it should only show up if the sync will take more than ~2 seconds. Only the spinner is enough when it is so quick.

~2 seconds sounds a bit vague and unreliable + too much hardcoded, there can be shorter or longer intervals before sync actually starts, which will result in inconsistent behavior. What if we instead display the progress bar once we know that there are some files (at least 1) that will get synced, during the discovery? This will then look like that once the number is more than 0:
![image](https://github.com/nextcloud/desktop/assets/12224014/42bac11a-85fd-41d9-9619-6e7e78b5b023)

The downside is, for a few seconds (from ~5 to ~20), we will be seeing this:
![image](https://github.com/nextcloud/desktop/assets/12224014/8db7f713-1b90-435e-904a-18ff4d2319df)

Maybe, the text should be changed to something like "Preparing sync" or "Discovering", while the scrollbar can not be displayed. What do you think?

Also, what do you think of progress bar height now? Does it look not too high anymore on my screenshots?

**Comment by jancborchardt** [comment]
@allexzander here’s my feedback :) 

> We do NOT display the dots button for activities that are not files or folders, also for those that are for action "file_deleted", and for those that do not have a path that we can use to open them locally.
> Do you have any examples of false positives for mentioned scenarios?

Yeah, actually when opening the system tray, most of the sync entries do not seem to have a 3 dot menu, like here (there’s many more entries below like this):
![image](https://github.com/nextcloud/desktop/assets/925062/5adefe40-f2d1-4f2d-a413-852a774bab1b)


> Should this happen always?
> > when new item, scroll automatically to top
> I can already expect how the user might get annoyed when in search for one of the older items and not being to reach it cause the auto-scrolling is happening during intensive sync/lots of notifications from the server

No, this is specifically about: When the view was previously scrolled to the top (or within a few pixels of it, probably good to add that as a buffer), then new notifications should continue the autoscrolling.
The view should indeed not scroll if you are down in the list and new stuff comes up on top. For that we could have a "New activity" bubble on the top like we have for "Unread mentions" in Talk:
![image](https://github.com/nextcloud/desktop/assets/925062/22ca43d7-d3dc-4d68-b710-8971417384cf)


> ~2 seconds sounds a bit vague and unreliable + too much hardcoded, there can be shorter or longer intervals before sync actually starts, which will result in inconsistent behavior. What if we instead display the progress bar once we know that there are some files (at least 1) that will get synced, during the discovery?

Right, this sounds good, as well as changing the initial text to "Preparing sync".
Could you make the progress bar height and border-radius look like the HTML progress bar? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

**Comment by allexzander** [comment]
@jancborchardt 
Here is how the new progress bar with rounded borders looks:
![image](https://github.com/nextcloud/desktop/assets/12224014/60eaf775-323d-4b97-9986-9520cee9a940)
Hope, this is ok.

**Comment by jancborchardt** [comment]
@allexzander much better! Can the filled area also be a different color, like primary of the operating system, or of the Nextcloud?

**Comment by allexzander** [comment]
@jancborchardt Hope the below color is fine, it will be the same as the header when it is changed:
![image](https://github.com/nextcloud/desktop/assets/12224014/3eaa97ca-c270-4d3e-a48d-a1798231cea3)

**Comment by allexzander** [comment]
@jancborchardt

> No, this is specifically about: When the view was previously scrolled to the top (or within a few pixels of it, probably good to > add that as a buffer), then new notifications should continue the autoscrolling.
> The view should indeed not scroll if you are down in the list and new stuff comes up on top. For that we could have a "New > > activity" bubble on the top like we have for "Unread mentions" in Talk:

What do you think? This button disappears over 2.5 seconds if not hovered such that it does not hang there indefinitely. When hovered - disappearing gets canceled but restarts again when the mouse leaves the button.

https://github.com/nextcloud/desktop/assets/12224014/15d3551a-9468-4d6b-9483-3c49ee85ed2c

**Comment by allexzander** [comment]
I am wondering if we now even need the "when a new item, scrolls automatically to top" without clicking a button, or is the button enough for the user to be able to scroll only if needed?

**Comment by nimishavijay** [comment]
Looks nice already! :) I have 2 points from my side:
- [ ] With the 0.25 opacity I am worried about accessibility, because the contrast doesn't seem like it's enough. I would say that it can stay full opacity, and it not hovered for 5 seconds it could disappear 
- [ ] Since it is scrolling to top, we could add this up arrow icon ([expand-less on MDI](https://fonts.google.com/icons?selected=Material%20Icons%3Aexpand_less%3A)) to the left of the button (nice-to-have, but not a blocker for this PR)
