### ISSUE TITLE
[Bug]: The Windows client ignores any files with a Chinese filename

### ISSUE THREAD

**Issue by DearMusic903** [nextcloud/desktop#5938]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Any files with Chinese filenames are being ignored on the Windows Desktop Client.

This issue is gone after rolling back to 3.9.0

I have been using NextCloud for three years now and have had no issues with any files with file names from any country until the latest Windows client updates.

This issue is only on Windows desktops, it works fine on Android or the web client.

Edit: [According to Reddit user u/Polarsy](https://www.reddit.com/r/NextCloud/comments/15dtlw4/comment/ju4yrha/), the Hungarian characters, such as "ő" in a filename is behaving the same way as what I am experience

### Steps to reproduce

Add a file to a sync folder and name it 123.txt -> successfully synced
Rename the file into 你好.txt -> log shows that I have deleted 123.txt which I did not delete
Delete 你好.txt and add a file 哈摟.txt -> log shows absolutely nothing

Create a folder called "你好" and create any files in the folder in any language, including English, will result in no logs at all and file not synced

Create files or folders with Chinese names on the web client it will not be synced to the desktop client.

### Expected behavior

Files with file names in Asian languages should also be synced.

### Which files are affected by this bug

Any file with Chinese file name, even a newly created text file.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

27.0.1

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

No server log related to this issue. The Chinese files are completely ignored.

**Comment by jjasoncool** [comment]
Same issue on windows 10

Version Windows 10 Pro
Version 20H2
Installed on ‎2022/‎01/‎25
OS Build 19042.844
Experience Windows Feature Experience Pack 120.2212.551.0

**Comment by teerasade** [comment]
Same issue with Thai filename

Version Windows 10
Nextcloud Desktop Client Ver. 3.9.1

Need to roll back to NC Client Ver. 3.9.0 and everything works just fine.

**Comment by PhilippSchlesinger** [comment]
There is a very similar bug https://github.com/nextcloud/desktop/issues/5935

**Comment by lssong99** [comment]
I got same issue. Here is a log sample for affected file:

Client 3.9.1
Windows: Windows 11, build 23511.ni_prelease.230722-2325

Basically all files/folders with Chinese characters has this issue and sync cannot be progress. 

Other sympthon:
1. If the file with Chinese filename is created/updated on PC, then it will NOT sync to server with error as log below
2. If the file with Chinese filename is created/updated on Server, then it WILL sync to client Windows PC with no issue.



```2023-07-31 22:34:03:903 [ info nextcloud.sync.propagator.root.directory C:\Users\sysadmin\AppData\Local\Temp\2\windows-16700\client-building\desktop\src\libsync\owncloudpropagator.cpp:1454 ]:	scheduleSelfOrChild OCC::PropagatorJob::Running pending uploads 0 subjobs state OCC::PropagatorJob::Running
2023-07-31 22:34:03:903 [ info nextcloud.sync.propagator C:\Users\sysadmin\AppData\Local\Temp\2\windows-16700\client-building\desktop\src\libsync\owncloudpropagator.h:215 ]:	Starting CSyncEnums::CSYNC_INSTRUCTION_IGNORE propagation of "My Photos/230327 中文" by OCC::PropagateIgnoreJob(0x1daedae34e0)
2023-07-31 22:34:03:903 [ warning nextcloud.sync.propagator C:\Users\sysadmin\AppData\Local\Temp\2\windows-16700\client-building\desktop\src\libsync\owncloudpropagator.cpp:284 ]:	Could not complete propagation of "My Photos/230327 中文" by OCC::PropagateIgnoreJob(0x1daedae34e0) with status OCC::SyncFileItem::FileIgnored and error: "The filename cannot be encoded on your file system."
2023-07-31 22:34:03:903 [ warning nextcloud.gui.activity C:\Users\sysadmin\AppData\Local\Temp\2\windows-16700\client-building\desktop\src\gui\tray\usermodel.cpp:863 ]:	Item  "My Photos/230327 中文"  retrieved resulted in  "The filename cannot be encoded on your file system."```

**Comment by Renari** [comment]
I only noticed this start happening when I recently updated the desktop client.

**Comment by tibor-banfalvi** [comment]
I experienced the same with Hungarian national characters in file name: ő and ű. Nextcloud desktop client does not sync files and directories with these characters in file/directory name.

Windows: Windows 11 22H2, build 22621.2070 (with latest patches)
Windows Feature Experience Pack 1000.22659.1000.0
Nextcloud Desktop Version: 3.9.1 (Windows) 3.9.1stable-Win64 (build 20230725)

**Comment by allexzander** [comment]
Can I assume this starts to happen in 3.9.1 and does not happen in 3.9.0? @tibor-banfalvi @Renari ?

**Comment by tibor-banfalvi** [comment]
@allexzander Yes, I didn't have any problems in earlier version. I have no problem on NC desktop V3.4.0 on my Windows 10 pc.

**Comment by Renari** [comment]
> Can I assume this starts to happen in 3.9.1 and does not happen in 3.9.0? @tibor-banfalvi @Renari ?

Can confirm, reverting to 3.9.0 fixed the issues for me.

**Comment by h9419** [comment]
> Can I assume this starts to happen in 3.9.1 and does not happen in 3.9.0? @tibor-banfalvi @Renari ?

Can confirm, reverted back to 3.9.0 for now and everything works

**Comment by lnp5131** [comment]
The same is happening for anything in Russian. 3.9.1

**Comment by nerozero** [comment]
Experiencing same issue after updating to 3.9.1 version. Any unicode characters in the filename preventing file to be synchronized from/to server (both ways)

**Comment by allexzander** [comment]
3.9.2 release that was just published fixes the issue, however, if a folder with such files was already synced with 3.9.1, one would need to enforce folder resync by creating an empty file in it in the client or on the server

**Comment by allexzander** [comment]
UPDATE: All the conversation will be continued in https://github.com/nextcloud/desktop/issues/5935
