### ISSUE TITLE
[Bug]: Pre-locked file is not set as read-only on the first time is synchronized

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#5942]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Scenario:

In this scenario, there are two users, A and B, who both have access to a shared file. User A has downloaded the file, making it available offline (indicated by a checkmark icon in the file explorer). User B, on the other hand, has not downloaded the file, so it remains in the cloud (indicated by a cloud icon in the file explorer).

User A locks the file and begins editing it. However, despite the file being locked, user B double-clicks on the file and is able to edit it as well. This is because the file had not been previously synchronized, and as a result, it was not set as read-only during the initial synchronization process.

In summary, the feature that automatically sets locked files as read-only works perfectly for files that were pre-synchronized (downloaded), but it does not work for files that have not been previously synchronized (remain in the cloud).

### Steps to reproduce

User A has the file available offline  (has the checkmark icon on it, in the file explorer)
User B has NOT the file available offline (has the cloud icon on it, in explorer)

1. User A locks the file and starts to edit it
2. After that, user B double click on the file and manage to edit it

### Expected behavior

The file should not be editable for user B on the first synchronization

### Which files are affected by this bug

Any file

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.3

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by vagner-dias** [comment]
Hello, @mgallien

After the pull request below, I ran a specific scenario (described above) and found that the feature does not work on it:
https://github.com/nextcloud/desktop/pull/5841

**Comment by mgallien** [comment]
@vagner-dias thanks
I see now that we will fetch the data without updating the metadata of the virtual file such that locking change will not be seen

**Comment by mgallien** [comment]
@vagner-dias thanks
I see that apparently we do not propagate read-only to virtual files without data
The locked flag is seen and the lock icon shown but the read-only property of the file is not updated
