### ISSUE TITLE
[Bug]: Password protection option is (but shouldn't be) visible for internal shares

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#5947]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Tested on GNU/Linux (Ubuntu) and Windows 11.
The password protection option is available for internal shares (shares that you make with other users), but as you certainly, this is not consistent (and it's not supposed to be possible to password protect an internal share).

![2023-08-01_15-25_1](https://github.com/nextcloud/desktop/assets/33763786/beb09d83-7c12-4ce8-966b-e4a92b33b147)
![2023-08-01_15-25](https://github.com/nextcloud/desktop/assets/33763786/8471b910-2e48-4944-8c61-74083b9a5c09)

That said, we can not go further (impossible to validate password protection), but it creates a lot of confusion among users.

### Steps to reproduce

1. Go to the sharing properties modal of an internal share 
2. Notice the password protection option

### Expected behavior

Password protection option should never appear for internal shares.

### Which files are affected by this bug

Don't know

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11, and GNU/Linux (Ubuntu). Not tested on OSX.

### Package

Other

### Nextcloud Server version

26.0.4

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Can be provided if necessary
```

### Additional info

Can be provided if necessary as well as Desktop Client Logs

**Comment by jancborchardt** [comment]
Yup absolutely, that shouldn't be there. cc @tobiasKaminsky for scheduling.
