### ISSUE TITLE
[Bug]: Syncing files with special characters like "üöäß" is not working with nextcloud-client 3.9.1

### ISSUE THREAD

**Issue by liszca** [nextcloud/desktop#5954]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

No Sync of files with Special Characters in their name with nextcloud-client 3.9.1

### Steps to reproduce

Under Windows 11:

1. Create a txt file without any of the following characters in the filename: ßüöä -> it does sync without issues
2. Rename the file to for example ßüöä.txt -> it is not syncing error message is shown but no hint about character problem.
3. To solve the issue I installed nextcloud-client 3.8.2

### Expected behavior

sync files with special characters

### Which files are affected by this bug

ßüöä.txt

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

26.0.3

### Nextcloud Desktop Client version

3.9.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
couldn't find anything in server logs, i believe the client just refuses to sync files with special characters.
```

### Additional info

This problem existed in early Version of the client, but got solved. 
Looks like the issue is back.

**Comment by PhilippSchlesinger** [comment]
There are very similar bugs https://github.com/nextcloud/desktop/issues/5935 and https://github.com/nextcloud/desktop/issues/5938.

**Comment by xrkolovos** [comment]
we have this issue with Greek Characters.
3.8.2 works fine
