### ISSUE TITLE
Nextcloud client docker version

### ISSUE THREAD

**Issue by GUNT0815** [nextcloud/desktop#5977]
### Actual situation

- running nextcloud-aio in docker on a server
- running differenct nextcloud clients on different computers in the network

### Issues

- many sync activities
- admin/update work on different computers in the network

### Future situation

- run Nextcloud-client in docker and sync on a specific share on the server "nc-sync"
- allow computers in the network to accesss the specific share "nc-sync"
- > only one sync
- > only one admin item

### Solution

- Nextcloud project to provide an official  Nextcloud client on docker (Nextcloud org is a trusted company)

PS: For mobile devices this solution is also an alternative to a nextcloud client installation by using wireguard/vpn plus a network/file browser.

**Comment by isdnfan** [comment]
There is [nextcloudcmd](https://docs.nextcloud.com/desktop/latest/advancedusage.html#install-nextcloudcmd) already which you can use to build a scenario you describe. 

In general I don't think this approach is good. Nextcloud (Hub) is much more than just files. It includes contacts, calendar, collaborative file editing. all this features remain untouched or become harder to use when you introduce "another" sync instance.

**Comment by mgallien** [comment]
@GUNT0815 
you can already use webdav protocol to access your files on your nextcloud server without having to run such a complex setup
