### ISSUE TITLE
Error opening external site from desktop client

### ISSUE THREAD

**Issue by DerFranke** [nextcloud/desktop#5983]
### Steps to reproduce
1. Install the app
2. Configure an external site (https://site.example.net), position: Header, tick the redirect option and set a custom icon.
3. Go into the desktop sync client and open the external site with it (restart the client if you don't see it)

### Expected behaviour
The site should open in the browser and the icon should be displayed in the client.

### Actual behaviour
You get an error with "site not found", because the browser tries to open "https://cloud.example.net/https://site.example.net".
Also the icon gets not desplayed in the client.

### Server configuration

**Operating system:** Ubuntu 22.04
**Web server:** Apache 2.4
**Database:** PostgreSQL 14.7
**PHP version:** 8.2.5
**Nextcloud version:** 26.0.1
**App version:** 5.1.0
**Where did you install Nextcloud from:** https://download.nextcloud.com

### Client configuration
**Browser:** Brave
**Operating system:** Windows 10

**Comment by b3nks** [comment]
The Bug is still there. #6386

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/server43204
Fixed
