### ISSUE TITLE
[Bug]: website links not updated despideclient update notification

### ISSUE THREAD

**Issue by olaulau** [nextcloud/desktop#5999]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
the download links on nextcloud website are not updated (currently pointing to 3.9.0 on each platform), despite desktop notifications for 3.9.3 : https://nextcloud.com/fr/install/
whereas files seems to be available : https://github.com/nextcloud-releases/desktop/releases/

### Steps to reproduce

just go to nextcloud website, try to download desktop client
version is stick to 3.9.0

### Expected behavior

having link pointing to latest versions (3.9.3)

### Which files are affected by this bug

https://nextcloud.com/fr/install/

### Operating system

Linux

### Which version of the operating system you are running.

debian testing

### Package

Appimage

### Nextcloud Server version

25

### Nextcloud Desktop Client version

3.9.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Closing - remedied awhile ago.
