### ISSUE TITLE
Login with Nextcloud desktop client fails after update of SSL certificate on server

### ISSUE THREAD

**Issue by snoopymat** [nextcloud/desktop#600]
**Incorrect behavior:**
Nextcloud desktop client states: "Keine Verbindung zu Nextcloud auf https://mix.xyz.org:55443 Operation abgebrochen" (with white font on red background).
(Translated by myself: "No connection to Nextcloud on https://mix.xyz.org:55443 Operation canceled")
Therefore no syncing of files occurs.
(Log states: "AccountState connection status change:  "Undefined" -> "Credentials Wrong"" -> see below)
Logout (DE: "Abmelden") and login (DE: "Einloggen ...") again did not help.

**Assumption:**
I suppose, that this error is associated with the following: 
I had updated the Let's encrypt SSL certificate on the Nextcloud server 8 days ago. I am <del>99 % sure</del> 50 % sure [updated -> see my comment below], that the login error is related to the certificate update.
**My setup:**
Nextcloud desktop client:
Version 2.3.3, under Ubuntu 18.04/64 bit, installed from ppa:nextcloud-devs/client. Same behavior on another host under Xubuntu 18.04/64 bit.
Nextcloud server:
Version 11.0.1 (stable). On Raspberry Pi with Raspbian GNU/Linux 8 (jessie); web server is nginx.
**What works:**
The following clients do work (i. e. login is possible):
Login via Firefox works.
Sync of calendar and address book with Thunderbird on same Ubuntu host works.
Sync of calendar and address book with app DAVdroid 2.0.2-ose on Android works.
Invoking "https://mix.xyz.org:55443/remote.php/webdav" in Firefox: Entering credentials required. After entering them web site shows: "This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client."

**BTW:** App Nextcloud 3.2.3 under Android has a similar problem (since update of SSL certificate): It requires permanently entering login data. But this is another bug.

**Logging:**
Content of Log window of Nextcloud desktop client:
08-29 21:28:30:395 3647 OCC::Account::resetNetworkAccessManager: Resetting QNAM
08-29 21:28:30:399 3647 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
08-29 21:28:30:399 3647 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
08-29 21:28:30:405 3647 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
08-29 21:28:30:406 3647 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://mix.xyz.org" + "status.php" "OCC::ConnectionValidator"
08-29 21:28:30:772 3647 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("needsDbUpgrade", QVariant(bool, false))("productname", QVariant(QString, "Nextcloud"))("version", QVariant(QString, "11.0.1.2"))("versionstring", QVariant(QString, "11.0.1")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x5575acad7470)
08-29 21:28:30:775 3647 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://mix.xyz.org:55443/status.php")  with version  "11.0.1" ( "11.0.1.2" )
08-29 21:28:30:777 3647 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl("https://mix.xyz.org:55443") has server version "11.0.1.2"

08-29 21:28:30:779 3647 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"
08-29 21:28:30:781 3647 OCC::HttpCredentials::fetchFromKeychain: -------- -----> QSslCertificate("", "", "1B2Y2M8AsgTpgAmY7PhCfg==", (), (), QMap(), QDateTime( Qt::TimeSpec(LocalTime)), QDateTime( Qt::TimeSpec(LocalTime))) QSslKey(PrivateKey, OPAQUE, -1)
08-29 21:28:30:782 3647 OCC::AccountState::setState: AccountState state change:  "Getrennt" -> "Konfigurationsfehler"
08-29 21:28:30:783 3647 OCC::FolderMan::slotAccountStateChanged: Account "max@mix.xyz.org:55443" disconnected or paused, terminating or descheduling sync folders

08-29 21:28:30:799 3647 OCC::Account::resetNetworkAccessManager: Resetting QNAM
08-29 21:28:30:800 3647 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
08-29 21:28:30:800 3647 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
08-29 21:28:30:801 3647 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
08-29 21:28:30:802 3647 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://mix.xyz.org" + "status.php" "OCC::ConnectionValidator"
08-29 21:28:31:079 3647 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("needsDbUpgrade", QVariant(bool, false))("productname", QVariant(QString, "Nextcloud"))("version", QVariant(QString, "11.0.1.2"))("versionstring", QVariant(QString, "11.0.1")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x5575ad034a70)
08-29 21:28:31:081 3647 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://mix.xyz.org:55443/status.php")  with version  "11.0.1" ( "11.0.1.2" )
08-29 21:28:31:083 3647 OCC::ConnectionValidator::setAndCheckServerVersion: QUrl("https://mix.xyz.org:55443") has server version "11.0.1.2"

08-29 21:28:31:085 3647 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-29 21:28:31:086 3647 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://mix.xyz.org" + "/" "OCC::ConnectionValidator"

08-29 21:28:33:391 3647 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
08-29 21:28:33:392 3647 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
08-29 21:28:33:521 3647 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!

*end*

**Comment by snoopymat** [comment]
**Workaround**:
I deleted the account max@mix.xyz.org on my nextcloud server and created a new account max@mix.fritz.box.
mix.xyz.org is a DynDNS sub-domain which points to my nextcloud server. 
fritz.box is my home network and mix.fritz.box is the inside name of my nextcloud server. (My router model is a so-called Fritz!Box.)
This way it works. But now I cannot access my nextcloud server from outside.

Correction of my **assumption** above:
Now I am assuming, that the cause of the error is not the LE certificate, but 
a) either a timing problem, because in the error case (mix.xyz.org) the data go from my computer in my home network to my router to the internet back to my router to my nextcloud server. In the working case all traffic is inside my home network.
b) or a problem with the LE certificate, which I had created for mix.xyz.org and not for mix.fritz.box. (In Firefox I had to make an exception due to this difference between name of server and name in certificate.)

BTW: The error with the login loop of the Android app Nextcloud still exists, also with the inside name.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
