### ISSUE TITLE
Unable to login with Mac App after moving to new domain

### ISSUE THREAD

**Issue by OverByThere** [nextcloud/desktop#602]
I can login successfully through the website, however using the app, I get the following error:
```
index.php/login/flow might be temporarily down or it may have moved permanently to a new web address.
```
<img width="952" alt="screen shot 2018-08-30 at 09 44 24" src="https://user-images.githubusercontent.com/6248551/44841852-41fe4c00-ac3c-11e8-84a6-f3241a406c20.png">
The only note is that the SSL cert is valid for another domain, but I did accept it on the screen beforehand as allowed.

Mac App: Version 2.5.0beta1 (build 20180803)
Nextcloud: Version 13.0.5

**Comment by OverByThere** [comment]
This may be related to #582 - the cert is from Lets Encrypt for another domain, so I have to 'trust' it when connecting. I feel the context isn't being passed over?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
