### ISSUE TITLE
Client Main Menu broken (black color, link invisible)

### ISSUE THREAD

**Issue by fraktal-sb** [nextcloud/desktop#6066]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

when opening the nexcloud client from Windows 11 the header shows a black bar on the top. The link at the right/top corner to the menu exists, but is invisible; see attached screenshot

![2023-09-16 10_31_57-Clipboard](https://github.com/nextcloud/desktop/assets/69430537/f641eb36-90c3-402a-8949-8ab319662824)

### Steps to reproduce

open the client; you will see the window as described before and with the screenshot before

### Expected behavior

There should be all elements visible (not hidden) and the black color is certainly not wanted

### Which files are affected by this bug

Nextcloud-3.9.4-x64.msi

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

t-online server version (unknown)

### Nextcloud Desktop Client version

3.9.4

### Is this bug present after an update or on a fresh install?

both: normal update and fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Toraih** [comment]
btw same problem on macos-clients in version 3.10

**Comment by fraktal-sb** [comment]
workaround: returning to Nextcloud-3.8.2-x64.msi with deinstall and install solves the problem

![2023-10-30 17_11_26-Clipboard](https://github.com/nextcloud/desktop/assets/69430537/718f9865-1068-4b5d-8ac5-72e4ddfbdaee)

**Comment by NateSmith-RC** [comment]
> btw same problem on macos-clients in version 3.10

+1

**Comment by fraktal-sb** [comment]
Problem seems to be solved (3.11). Now the main menu color is not black but not the "nextcloud- blue". It has the "color of my provider" t-online. Which is OK.
![2023-12-18 07_47_36-Nextcloud](https://github.com/nextcloud/desktop/assets/69430537/580ba8fa-ad3a-4f4c-9e71-5de4528926da)
