### ISSUE TITLE
[Bug]: read-only status with windows 10 and 3.10 Desktop Client version

### ISSUE THREAD

**Issue by Mika-6-9** [nextcloud/desktop#6071]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [ ] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The propagate locked status to read-only or read/write is now working with the 3.10 client on windows 11.
But with Windows 10, it's not working at 100%.
With Windows 10, file locking (Excel/Word) works well, but you can open a locked file (Excel/Word) and save changes without an alert message.
The read only status is not here.

(see https://github.com/nextcloud/desktop/pull/5841)

### Steps to reproduce

1. User A open a excel/word file
2. The file is lock
3. User B open the file on windows 10
4. The file is not read-only
5. Make changes
6. Save the file
7. It works

### Expected behavior

Idem with windows 11, when a file is locked, the user with windows 10 have the read-only status when he tried to open it.

### Which files are affected by this bug

Word and Excel

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

25.0.1

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
did you tested what happen for user B when also trying to lock the file when editing it ?
there is always going to be a race between the B user opening the file and there sync client discovering the server changes and the fact the file is already locked
only solution is to have proper behavior when user B tries to lock an already locked file

**Comment by vagner-dias** [comment]
I ran a test using windows 11 as "User A" and everything works fine here.

I only see this scenario if the same users is logged on both computers

**Comment by Mika-6-9** [comment]
I'm sorry, I don't have time to do additional tests this week, but if I have a slot, I'll test and get back to you.
Can I put logs or something to see what's not working?

**Comment by Mika-6-9** [comment]
Hello.
Some tests carried out on Windows 10.
We reinstalled the client and it works
