### ISSUE TITLE
[Bug]: File Locking - When a User Opens a Office file loses the connection the file gets locked indefinitely

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/desktop#6078]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

If a User Opens a Office file loses the connection the file gets locked indefinitely

### Steps to reproduce

User A opened an Office file, effectively locking it. However, the same user abruptly shut down the computer. Several hours later, the file remains locked.

### Expected behavior

A mechanism should be in place to detect when the user is no longer online and automatically unlock the file.

### Which files are affected by this bug

Any office file

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

26.0.5

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by vagner-dias** [comment]
@mgallien - I've recently come across this scenario involving file locking.

Regards

**Comment by jospoortvliet** [comment]
This is what the time-out for file locks is for, it's not something the desktop client can fix. A 30 min or 60 min time-out is wise.

https://github.com/nextcloud/files_lock#settings for how to set it.

It might make sense to set this as default, but either way - as the desktop isn't running, it can't fix this.

**Comment by robertofabrizi** [comment]
> This is what the time-out for file locks is for, it's not something the desktop client can fix. A 30 min or 60 min time-out is wise.
> 
> https://github.com/nextcloud/files_lock#settings for how to set it.
> 
> It might make sense to set this as default, but either way - as the desktop isn't running, it can't fix this.

Is there a way to set this via docker-compose? Thank you!
