### ISSUE TITLE
[Bug]:  Segmentation fault on Ubuntu 23.04

### ISSUE THREAD

**Issue by jhonny-oliveira** [nextcloud/desktop#6080]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I have packaged nextcloud-desktop 3.10.0 on Ubuntu 22.04 (jammy) with the available debian recipe for 3.9.0. To the extend of my testing the client seems to work fine on this Ubuntu version.

Then, I attempted to use the same packages on Ubuntu 23.04 (lunar). "Sign in" seems to work fine, just like before, but clicking "Sign up with provider" crashes the client with a "Segmentation fault (core dumped)". See full error below.

I decided to rebuild the packages on Ubuntu 23.04, but the result is even worse. Now, nextcloud immediately crashes.

```
$ nextcloud --logdebug
QSocketNotifier: Can only be used with threads started with QThread
[6087:6087:0100/000000.507917:ERROR:zygote_linux.cc(607)] Zygote could not fork: process_type renderer numfds 3 child_pid -1
[6087:6087:0100/000000.508000:ERROR:zygote_linux.cc(639)] write: Broken pipe (32)
Segmentation fault (core dumped)
```

### Steps to reproduce

1. Click on "Sign up with provider"

### Expected behavior

The provider sign up dialog should show up, instead of crashing.

### Which files are affected by this bug

n/a

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 23.04

### Package

Compiled it myself

### Nextcloud Server version

n/a

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
cannot reproduce
I tried with the unofficial [flatpak package](https://flathub.org/apps/com.nextcloud.desktopclient.nextcloud) and it is running fine
maybe you are missing some dependencies

**Comment by zak39** [comment]
Hi :wave: 

I have the same problem on my Ubuntu 24.04.

How can I solve this issue? :pray:

**Comment by bronger** [comment]
> Hi 👋
> 
> I have the same problem on my Ubuntu 24.04.
> 
> How can I solve this issue? 🙏

I am currently affected by this. (Version 3.16.7 on Debian.) How did you solve this?
