### ISSUE TITLE
Missing Assets on GitHub Release page

### ISSUE THREAD

**Issue by andredb90** [nextcloud/desktop#6085]
Is it possible to publish the .MSI and .PKG installers again on the github release page?

This used to be the case until the release of 3.9.0-rc2 and broke our automatic deployment workflows.

**Comment by mgallien** [comment]
I would suggest just following the link as explained in the readme
https://github.com/nextcloud/desktop/blob/master/README.md#-download-binaries

**Comment by andredb90** [comment]
Exactly what I was missing. - Thank you so much!
