### ISSUE TITLE
Uploading conflict files and dealing with them

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#609]
@jospoortvliet 's idea.

Do we have an issue for this on the server? I am guessing 'dealing with them' means dealing with them on the server.

**Comment by michaelstingl** [comment]
Here you can find the docs for the client side:
https://docs.nextcloud.com/desktop/2.5/conflicts.html#uploading-conflicts-experimental

**Comment by the-sane** [comment]
@camilasan I too would like to see this feature exposed to users in the client settings.  This is the default for dropbox and anyone coming to Nextcloud from dropbox will be familiar with this behavior.

With users potentially having multiple devices connected to Nextcloud, it doesn't make sense to assume that the device they're currently on is the one they want to perform conflict resolution on.  Perhaps they're on a portable device with a small screen and would prefer to analyze the conflicting files on a desktop with a larger screen.  Or, perhaps the conflict is generated on a windows device but the user has access to a linux device with tools like vimdiff and ediff which are better equipped for conflict resolution.  In order for this to be possible, both copies of the conflicting file would need to be uploaded to the server.

The rationale that other users in a shared folder situation might be confused by seeing conflicting copies synced is valid, so an option should be provided in the settings.

**Comment by b-pfl** [comment]
I totally agree. A client setting would be ideal for this. Until then, the documentation should also be clear that the setting needs to be done on the client system and we should provide instructions on how to do this for the individual operating systems!

**Comment by berbigou** [comment]
hello, I'd like to bump up this idea from b-pfl:
> I totally agree. A client setting would be ideal for this. Until then, the documentation should also be clear that the setting needs to be done on the client system and we should provide instructions on how to do this for the individual operating systems!
> Finally, should the environment variable be renamed to NEXTCLOUD_UPLOAD_CONFLICT_FILES?

it's a 1-year old post, but I encountered this issue: unclear documentation about Nextcloud Sync Files Client dealing with conflicts in [https://docs.nextcloud.com/desktop/2.3/conflicts.html], client setting needed SHARPLY, extra info needed 

On Windows 10 as admin, you have to go open Win menu, type SystemPropertiesAdvanced.exe, launch it as admin, click environment variables, add a new System Variable, type OWNCLOUD_UPLOAD_CONFLICT_FILES with value 1.

I don't know where to post this request (I'm new to NextCloud) with all those keywords. I hope Google will take those up and bring someone here who will find this helpful... (Yes, I'd like to be a super-hero...)

**Comment by schobernoise** [comment]
Hey there, 2,5years in the future: Does anyone have any more info on this? The environment variable, which I changed on the server (Debian 11) would not really make much of a difference... the android client still won't automatically upload conflicting files. Which is a bummer, because it is in every case a conflict when you change a file on your phone, since it then differs from the version on the server.

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
