### ISSUE TITLE
I have a working FreeBSD port but have some questions

### ISSUE THREAD

**Issue by bceverly** [nextcloud/desktop#61]
Hi all,

I'm working on getting a FreeBSD port of this project and have successfully done so (I'll work on an OpenBSD port after that).  The challenge that I have to doing both of these is that the way our ports infrastructure works, it grabs a release branch, applies any patches to it and then builds it.

Unless I'm really git-challenged this morning, however, I'm not seeing any release branches in the repo.  Am I looking in the wrong place?  If not, any chance that a project leader could cut a release branch that I could use to put the finishing touches on my ports?  I'll have a pull request to get approved that has my (minor) changes to get the FreeBSD version of this working.

Thanks!

**Comment by rullzer** [comment]
Cool stuff!!

There are no release branches yet so that is why you don't see them yet. We hope to have some soon ;)

**Comment by rullzer** [comment]
@bceverly please join #nextcloud-client on freenode and we can discuss there.

**Comment by arrowd** [comment]
@bceverly there are a lot of releases now, can you move this forward?

**Comment by arrowd** [comment]
I guess, this can be closed now.

**Comment by probonopd** [comment]
Is there a way around this?

```
% uname -v
FreeBSD 12.1-RELEASE r354233 GENERIC

% sudo pkg install libinotify
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (0 conflicting)
The most recent versions of packages are already installed

% make -j4 
(...)
[ 18%] Building CXX object src/libsync/CMakeFiles/nextcloudsync.dir/vfs/suffix/vfs_suffix.cpp.o
[ 18%] Building CXX object src/libsync/CMakeFiles/nextcloudsync.dir/creds/httpcredentials.cpp.o
[ 18%] Linking CXX shared library libnextcloudsync.so
ld: error: unable to find library -linotify
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mgallien** [comment]
Closing as I believe there is a working FreeBSD support.
