### ISSUE TITLE
Folder sync list display not updating

### ISSUE THREAD

**Issue by hanscomps** [nextcloud/desktop#611]
When renaming a share folder or adding new shares the client folder list (tree view) does not reflect the update.  The background sync DOES happen as expected and Activity shows changes, only the UI is not updated.
Need to quit and restart client to see updates. 
[Arch Linux, v2.3.3]

**Comment by hanscomps** [comment]
Hi.  No did not yet use latest builds, will fire up the backup server and try, thanks.
This issue is not in the Activity UI thou, it is in the main "list view" (not sure what it is officially called).

**Comment by luopa** [comment]
@hanscomps Are you referring to the Folder List presented by the desktop sync client?

I observe the same behaviour:

**Comment by luopa** [comment]
corresponding issue within owncloud/client: https://github.com/owncloud/client/issues/6337

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
