### ISSUE TITLE
[Bug]: Thumbnails not showing under desktop client in VFS mode

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/desktop#6118]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Please see below picture this happed on Windows 11 running Desk client  3.10.0 this seems to happen with all pic files and video files i also have a macbook pro running 3.10.0 but no VFS, normal sync and thubnails show up properly

Windows 10 Screenshot 

![image](https://github.com/nextcloud/desktop/assets/59488153/bc6176db-fbb6-47dc-ab15-bc11c7f75030)

### Steps to reproduce

Upload files click on nextcloud app to open menu 

### Expected behavior

![image](https://github.com/nextcloud/desktop/assets/59488153/859a7f25-fc68-4cd5-824d-98517274f353)

### Which files are affected by this bug

jpg,mp4, mov, etc

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Appimage

### Nextcloud Server version

27.1.2

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by AndyXheli** [comment]
Still an issue on 3.11.0

**Comment by joshtrichards** [comment]
On the VFS system, do they show in Explorer?

**Comment by AndyXheli** [comment]
Yes works on Explorer

**Comment by PhilippSchlesinger** [comment]
I can also confirm this issue with the tray window.
Probably unrelated: on the VFS system, the shell integration with windows explorer basically works, but also has issues in some multiuser conditions as described in https://github.com/nextcloud/desktop/issues/5301.

**Comment by AndyXheli** [comment]
Still an issue with 3.14.1
