### ISSUE TITLE
Can't build on Windows 11

### ISSUE THREAD

**Issue by EMRodrigoGarcia** [nextcloud/desktop#6119]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Can't compile the desktop client on Windows 11

### Steps to reproduce

1. Install Qt from the Qt unified online package, selecting the MinGW and MSVC options: 
![imagen](https://github.com/nextcloud/desktop/assets/65778055/8d174d2b-30dc-49a2-ab72-7e59da2777b1)
2. Install OpenSSL
3. Install CMake
4. Install QtKeychain, zlib and KF5Archive via VCPKG
5. Install Visual Studio 15.9.27 2017 Community, selecting "Development for desktop with C++" enabled with these options: 
![imagen](https://github.com/nextcloud/desktop/assets/65778055/b2da076d-9b4e-4832-8f9a-3068be0a070f)
6. Clone the repo, mkdir build, cd build
7. CMake-GUI, generator is Visual Studio 15 2017 x64, configure & generate
[cmake_configure_log.txt](https://github.com/nextcloud/desktop/files/12830492/cmake_configure_log.txt)
8. cmake --build . --config Debug --target install (fails due to linking)
[cmake_compile_log.txt](https://github.com/nextcloud/desktop/files/12830509/cmake_compile_log.txt)

I have also tried to compile via MinGW Makefiles, steps are the same until the 6th: 
7. CMake-GUI, generator is MinGW Makefiles, configure - stops because it doesn't find Windows SDK 10.0.22621.0 (even though VS generation finds and uses that SDK?)
[cmake_configure_mingw_log.txt](https://github.com/nextcloud/desktop/files/12830560/cmake_configure_mingw_log.txt)

### Expected behavior

It should build the application.

### Which files are affected by this bug

NCOverlay.cpp

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Compiled it myself

### Nextcloud Server version

25.0.4 Enterprise

### Nextcloud Desktop Client version

Latest master commit

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
The docs have been updated for Windows builds since your report:

https://github.com/nextcloud/desktop/blob/master/doc/building.rst
