### ISSUE TITLE
Better virtual file support for MacOS, rather than .nextcloud files

### ISSUE THREAD

**Issue by alanyoungCN** [nextcloud/desktop#6120]
### Feature description
In Windows the virtual file works well and files are stateful. One can see all files and download them when needed rather than download them all after logging in. But in MacOS, this feature is under experiment for long and the implement  (use .nextcloud file) is not elegant. Maybe we can use [File Provider API](https://developer.apple.com/documentation/fileprovider/) to refactor this feature?

**Comment by marcotrevisan** [comment]
It's in progress #1337 #5693 

I think you can safely close this.
