### ISSUE TITLE
[Bug]: There are unresolved conflicts: Click for Details - Shows no details when clicked if Sync is in progress

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/desktop#6146]
- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

# Context
I have installed a Nextcloud Server 27 clean. 
I have installed the desktop client latest version as an AppImage (Help says it's 3.10)
I have copied a LOT of files into my local Nextcloud folder
It is syncing. 

The Server and Client are on the same LAN. 
The server is running on up to date Ubuntu (22.04.3 LTS)
The Client is running up to date Linux Mint (21.2)

# Image

![image](https://github.com/nextcloud/desktop/assets/7296506/5d9d166e-87d2-43a5-a250-c02e27f3af25)

# What happens

if I click the golden bar this popw up:

![image](https://github.com/nextcloud/desktop/assets/7296506/8ec8a566-0332-4606-9b63-6573266c2faf)

# What should happen

The conflicts should be shown

# When are they shown

I think, though pending further testing, that they are reliably shown after the sync is complete, but during the sync they are not.

# Why is it a bug?

Well, if you're not going to show them, fine then don't show the message saying Click here to see them. And if you choose to show the message with Click here to see them, then do show them. The two behaviours simply need to be consistent, their failure to be so, is IMHO a UI bug.

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

- Starts a Sync 
- Hope for Unresolved Conlict 
- Click Here while it's Syncing,

### Which files are affected by this bug

Can't as they aren't listed ;-)

### Operating system

Linux

### Which version of the operating system you are running.

Mint 21.2

### Package

Appimage

### Nextcloud Server version

27.1.2

### Nextcloud Desktop Client version

3.10

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I can provide a Desktop Client Log Report on request, I just made one.

To be honest, I don't even know why I'm seeing conflict errors. It's a fresh server, fresh client, empty local directory, that I dropped some 3GB of files into, and it's taking a lifetime to sync up even though it's on the same LAN and not hair pinning (as in the URL goes over the LAN not out to the WAN and back in).

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support

**Comment by bernd-wechner** [comment]
Haven't seen this issue recently no.
