### ISSUE TITLE
Exclude string from being shown on Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#616]
https://github.com/nextcloud/desktop/blob/9d021d004d37d4ae15059bffc8e7642757933431/src/gui/folderwizardtargetpage.ui#L110

Link to Transifex:
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/140295856

**Comment by rakekniven** [comment]
@mgallien will fit a "notr" here as well?

**Comment by rakekniven** [comment]
@FlexW will fit a "notr" here as well?

**Comment by mgallien** [comment]
@rakekniven thanks for taking care of translations.

Did you open a PR for that ?
I may have miss it.
It would be helpful if you could do it because you know what to change and I may get lost doing it myself.

**Comment by rakekniven** [comment]
This has been done in the meantime. Sorry for the noise. Closing here.
