### ISSUE TITLE
[Bug]: Unchecking synchronized subfolder without local delete

### ISSUE THREAD

**Issue by q2apro** [nextcloud/desktop#6169]
### Bug description

Bug: Local files get deleted on first sync when folder is not ticked with checkmark. From usability standpoint this must be handled differently. Never ever delete local files if they are not synched yet. There must be a dialog to choose what to do with those folders. – Same issue like NextCloud with OwnCloud, discussed here: https://github.com/owncloud/client/issues/2502 - Maybe Nextcloud can be first to get rid of this "usability bug".

### Steps to reproduce

Set up a folder to be synchronized with the server.
Click on "Choose What to Sync" for that folder.
Uncheck subfolders that you do not want to synchronize anymore.

### Expected behavior

If I select a folder ("A") to synchronize with server and later decide not to synchronize one of its subfolders ("A.B"), I might not want local files to be deleted. Just because I don't want something to be synchronized anymore doesn't necessarily mean I want it to be removed from my local machine.

### Which files are affected by this bug

Folders that are not checked - they get deleted from the local harddrive!

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official SNAP package

### Nextcloud Server version

Latest

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I have found some posts from an interesting discussion from the help forums: [Unchecked folders will be REMOVED from your file system](https://help.nextcloud.com/t/unchecked-folders-will-be-removed-from-your-file-system/12335)

> Again I want to stress, this CANNOT be the way this works, or users will be losing files constantly and won’t know why. NO WAY any solution should remove local files. The LOCAL files should ALWAYS be the master.
> NO SOLUTION should delete local files simply because a checkbox is unchecked
> I am never going to convince developers there why this is such a bad idea, so I simply will not use this product.
> I have reviewed several cloud systems. Absolutely none work the way NextCloud works. They can’t. No one would use them. No one would take the risk. There is a scenario where someone could uncheck a folder, delete the local files, not know what to do, and so delete the account on the nextcloud server, thereby permanently losing their files.

This user is absolutely right.

---

Everyone who starts using the Nextcloud Desktop Client must be informed that this is a centralized backup-sync solution where the server is the master.

It cannot be that when you do your first Desktop client sync, that certain folders get removed from your local harddrive. NEVER remove data that has not been synced yet. Or ask the user what he wants to do with those folders.

But do not just remove them.

⚠️ This is a severe bug that can have severe legal issue.

**Comment by q2apro** [comment]
> if the local data actually gets deleted before the synchronisation is complete, which I never expirienced, [...](https://help.nextcloud.com/t/unchecking-synchronized-subfolder-without-local-delete/172874/6)

This is like saying "I never had a car accidents, so therer are no car accidents." (!) 🙈 

<br>

# My Scenario that was leading to the BUG

1. Setting up Nextcloud
2. Setting up Computer A with desktop client to sync harddrive D:
3. Computer A synced to Online-Storage
4. Setting up Computer B with desktop client to sync harddrive D:
5. Computer B had existing data on D: which was confidential (computer A should not get it), so of course, I unchecked the folder in the desktop client
6. Result: Nextcloud desktop client **deleted** my confidential folder

Is it not clear enough that this is a severe bug?!

**Comment by Rello** [comment]
Hello,

thank you for opening the request.
The client has improved a lot since the ticket was opened.
Can you support us and check if it is still relevant? In this case we appreciate a new ticket or a comment here.
Thank you for your support
