### ISSUE TITLE
Storage with mount id 9 is not available

### ISSUE THREAD

**Issue by gerroon** [nextcloud/desktop#617]
Linux/Windows 2.3.3, Nextcloud 13.0.5.2, Debian Testing, PHP Version 7.1.20-1

I have mounted a folder as SMC/CIFS external. I can browse the folder and its files in the web ui but the desktop clients are borking , as seen from the NC log.

Client Log

```
Error while loading the list of folders from the server.
Error transferring https://xx.xx.org/NC/remote.php/dav/files/USER/NOTES/ - server replied: Service Unavailable
```

Server log 

{"reqId":"znrCTc0SgycvomekRKUN","level":4,"time":"2018-09-02T00:01:43+00:00","remoteAddr":"192.168.2.100","user":"USER","app":"webdav","method":"GET","url":"\/NC\/remote.php\/dav\/files\/USER\/NOTES\/3D\/BBBBB\/BBBBB_Scripts.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Storage with mount id 9 is not available\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild('NOTES')\\n#1 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/USER\\\/Zi...')\\n#2 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(71): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/USER\\\/Zi...')\\n#3 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(103): Sabre\\\\DAV\\\\Tree->getNodeForPath('files\\\/USER\\\/Zi...')\\n#4 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(878): Sabre\\\\DAV\\\\Tree->nodeExists('files\\\/USER\\\/Zi...')\\n#5 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#8 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(287): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(35): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/remote.php(164): require_once('\\\/media\\\/DRIVE\\\/...')\\n#12 {main}\",\"File\":\"\\\/media\\\/DRIVE\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":225}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"13.0.5.2"}

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
