### ISSUE TITLE
Dont forbid separate local sync location for remote subfolders while Nextcloud root being already synced to its own location

### ISSUE THREAD

**Issue by sadr0b0t** [nextcloud/desktop#618]
Hello, I want to have one subfolder (let it be "autoupload" - photos synced from phone) synced to its own dir on local filesystem (let it be /home/user/nexcloud-auto) and all other files (Nextcloud root) synced to some other location (let it be /home/user/nextcloud-root).

If I do on new connection:
1. Add sync folder > local folder = /home/user/nexcloud-auto > remote folder = /autoupload > ok
2. Add sync folder > local folder = /home/user/nextcloud-root > remote folder = / (Nextcloud root minus autoupload dir) > ok

(In short: add subfolder sync to its own location, then add Nextcloud root sync to some other location)

I get exactly what I want: both folders are synced at the same time. I can even have same remote folder synced to 2 different locations with same client on local filesystem in this way.

But if I just change the order of above operations: first add Nextcloud root to sync list (even with autoupload subdir sync switched off), then I try to add separate location for autoupload dir in the way above, the client won't allow me to do this saying that I already have location to sync Nextcloud root so now I can't sync any of its subfolders separately.

So what I see from the above:
1. The limitation of having only one local location for one remote subfolder seems to be strained. Even though this might be not a common usecase (to have one remote folder being synced to 2 different locations), I don't see any reasons why this should be explicitly forbidden.
2. Trying to force this limitation leads to additional inconveniences with common usecases (having separate location for one remote folder while syncing the whole root to some other place).
3. I have showed above how this limitation can be avoided (in a hacky way though), so technically Nextcloud engine actually already CAN sync same remote folder to multiple local locations with no problems, the limitation seems to be applied only in GUI.

So I suggest that this limitation can be just accurately removed.

**Comment by maprambo** [comment]
I agree. A confirmation dialogue instead could be an option. 
My use case: I want to have my Nextcloud's documents folder synced with my local documents folder, same with pictures - but still get all shared files (which first appear in Nextcloud's root) and other folders locally, too. So I'd appreciate a "default/fallback" sync option - but a confirmation instead of a strict limitation is good enough for now.

**Comment by sadr0b0t** [comment]
I have just updated to 2.5 and it seems like this issue is now resolved. Very thank's!
