### ISSUE TITLE
Implement support for sharing in File Provider VFS files

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#6197]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Virtual files in the File Provider system should support sharing just like their traditional sync engine counterparts

**Comment by tobiasKaminsky** [comment]
Duplicate of https://github.com/nextcloud/desktop/issues/6200
