### ISSUE TITLE
Linux Appimage giving false info

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/desktop#620]
I have the latest Appimage running. It states that there are some issues with files. Looking at the activity tab it shows there are conflict files, the server version was downloaded and the local version renamed to ...-confilct.XX However, when browsing to my my local folder, there is no conflict files available? Where is it getting the info from, and how can I fix this "false info".

**Comment by hanserasmus** [comment]
Dunno if there was somehow an update pushed (not sure how Appimage Beta works) but the issues seem to have gone away. It does not show there are conflict files anymore. It may have been an update, or a reboot that did the trick, not sure.

**Comment by camilasan** [comment]
I will leave this issue open, just in case you experience it again or someone else... Thanks!
