### ISSUE TITLE
[Bug]: Can't login "The password has expired, please use the lost password function to reset it"

### ISSUE THREAD

**Issue by mthld** [nextcloud/desktop#6204]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

It's impossible to login on Nextcloud Desktop on a fresh client installation, or to use a previously installed one. However, everything is working as expected on the web interface.

### Steps to reproduce

1. Install Nextcloud Desktop
2. Follow the login process with success
3. Get the following error

<img width="561" alt="Screenshot 2023-11-07 at 10 02 57" src="https://github.com/nextcloud/desktop/assets/41020854/caf7b93d-021d-4df7-9b77-72584160c5a6">

### Expected behavior

People should be able to use the Nextcloud Desktop client, especially when their credentials are valid and not expired. The error message should also be more informative.

### Which files are affected by this bug

/remote.php/dav/files/username/

### Operating system

Mac OS, Windows, Linux

### Which version of the operating system you are running.

macOS Sonoma 14.0, Windows 10, Windows 11, Ubuntu 22.04

### Package

Official for Windows, Brew for macOS and Ubuntu package for Linux

### Nextcloud Server version

27.1.3

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"HBlMrQUT9ogeEweWeG7i","level":3,"time":"2023-11-07T08:56:43+00:00","remoteAddr":"REDACTED","user":"--","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/REDACTED/","message":"OC\\User\\LoginException: The password has expired, please use the lost password function to reset it","userAgent":"Mozilla/5.0 (Windows) mirall/3.4.2stable-Win64 (build 20220127) (Nextcloud, windows-10.0.22621 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"27.1.3.2","exception":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"OC\\User\\LoginException: The password has expired, please use the lost password function to reset it","Code":0,"Trace":[{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":179,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":135,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/apps/dav/lib/Server.php","line":365,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/home/REDACTED/REDACTED/nextcloud/remote.php","line":172,"args":["/home/REDACTED/REDACTED/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/REDACTED/REDACTED/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","Line":146,"message":"OC\\User\\LoginException: The password has expired, please use the lost password function to reset it","exception":{},"CustomMessage":"OC\\User\\LoginException: The password has expired, please use the lost password function to reset it"}}
```

### Additional info

Everything was working since Nextcloud 21, doing upgrades carefully and updating the Nginx example configuration file each time. I'm not sure if it's a desktop or a server (https://github.com/nextcloud/server/issues/41320) bug in the end...

```
$ sudo nginx -v
nginx version: nginx/1.25.3
```

```
$ sudo php8.2 -v
PHP 8.2.12 (cli) (built: Oct 27 2023 13:01:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
```

```
$ dpkg -l | grep postgresql
rc  postgresql-14                  14.7-1.pgdg110+1                                   amd64        The World's Most Advanced Open Source Relational Database
ii  postgresql-15                  15.4-2.pgdg110+1                                   amd64        The World's Most Advanced Open Source Relational Database
ii  postgresql-client-15           15.4-2.pgdg110+1                                   amd64        front-end programs for PostgreSQL 15
```

**Comment by joshtrichards** [comment]
Whatever is going on, it appears to be server related so I'll close out the issue here in the desktop repository. 

Follow-ups can continue in existing issue: nextcloud/server#41230
