### ISSUE TITLE
[Bug]: Window gets detached from menubar icon (macOS Sonoma)

### ISSUE THREAD

**Issue by vco1** [nextcloud/desktop#6217]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After some time (i.e. not immediately after start up) the window gets detached from the menubar. If that happens, all options in the window are unaccesible.

### Steps to reproduce

1. Click on menubar icon
2. Window shows up in the middle of the screen, not directly under the manubar icon.
3. None of the options in the Nextcloud Desktop Clinet are working anymore.

### Expected behavior

Window appears directly under the menubar and options are available.

### Which files are affected by this bug

None - UI issue

### Operating system

Mac OS

### Which version of the operating system you are running.

Sonoma 14.1.1

### Package

Appimage

### Nextcloud Server version

27.1.3

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by c4539** [comment]
I'm experiencing the same issue.
Might be related to using an external display.

**Comment by carlchen2007** [comment]
Same issue for me, still there after reinstall!

**Comment by flightmansam** [comment]
I have this issue too. It is so annoying. Only way I can fix it is to restart nextcloud.

**Comment by SmoothMC** [comment]
same here with a MacMini M1

**Comment by Murgeye** [comment]
This issue is really annoying. I have recorded a short screencast to show the issue:

https://github.com/nextcloud/desktop/assets/16648242/94bc929c-a4ef-4b76-90f5-df2c02e44257

**Comment by flightmansam** [comment]
I am tempted to try and fix this. It is literally the only flaw of nextcloud I have experienced.

**Comment by phoerious** [comment]
Same here. Worst thing about this: the window doesn't react to clicks, so the only way to restart the client is to kill the process.

**Comment by accolon** [comment]
Same (or very similar) problem here. In my case, the window is partially moved outside the visible screen to the top (use the macOS menu bar in the screenshots below as visual anchor).

I can reproduce the problem by connecting my MacBook Pro 16" (Sonoma 14.2.1, NC Desktop Client 3.11) to an external display once. Afterwards, the position is wrong when using the MBP's internal display. It's fine again on the external display, though.

Right:
<img src="https://github.com/nextcloud/desktop/assets/126886/9b6d806a-fd3f-4272-bb62-74164bb0c8ee" width=50%>

Wrong:
<img src="https://github.com/nextcloud/desktop/assets/126886/e596a27c-e7c5-4eb1-a9e8-7a9bb76ae006" width=50%>

**Comment by punkyard** [comment]
hi
I have almost the same the Monterey - menu stays under the menubar or gets mixed with it:

<img width="597" alt="Capture d’écran 2024-02-06 à 10 37 32" src="https://github.com/nextcloud/desktop/assets/59349105/54435833-c55b-4939-bf95-5b78322a3cf8">


<img width="371" alt="Capture d’écran 2024-01-23 à 17 12 22" src="https://github.com/nextcloud/desktop/assets/59349105/f54c0764-af34-4f84-ac17-80ec62930a78">

**Comment by trololirko** [comment]
+1 here. Same issues with the detached and non clickable menubar...

**Comment by bnussbau** [comment]
+1 here. After connecting the notebook to Thunderbolt display, window is not positioned correctly anymore. Outside of the screen, or in the middle. Nothing is clickable anymore, therefore you need to terminate the process and restart.

**Comment by karlemilnikka** [comment]
I have the same issue and I can trigger it by rescaling my MacBook display’s resolution. When going from a higher resolution to a lower resolution, the Nextcloud app’s dropdown-mimicking window gets rendered too high up on the display making it inaccessible. Force quitting and restarting the app solves the issue.

macOS 14.6.1 with Nextcloud Desktop client 3.13.2. 

<img width="687" alt="Skärmavbild 2024-08-20 kl  12 04 44" src="https://github.com/user-attachments/assets/b3c99730-0372-49fe-9c31-5c63ac5ad816">

**Comment by flightmansam** [comment]
This seems to be way down the priority list for devs. I was going to work on this but moved to asahi Linux and have lost interest myself...

**Comment by punkyard** [comment]
> This seems to be way down the priority list for devs. I was going to work on this but moved to asahi Linux and have lost interest myself...

That's a harsh thing to read. Postponing to November 2027 would have at least left me a hope 😥

**Comment by punkyard** [comment]
great improvement lately (AiO 9.4.1)
thanks!

**Comment by claucambra** [comment]
This has been fixed thanks to the change to Qt 6 in 3.14.0, thanks for your reports
