### ISSUE TITLE
Windows: Client uses ancient OpenSSL version

### ISSUE THREAD

**Issue by klada** [nextcloud/desktop#622]
The Windows client (daily build) is built against OpenSSL 1.0.1h from **2014**, which contains many security vulnerabilities.

Please update the OpenSSL version to a more recent one of the 1.0.x series.

Additional information: https://www.openssl.org/news/vulnerabilities-1.0.1.html

**Comment by rakekniven** [comment]
Just seen this today as well. 

AFAIU it is just about the names of dlls, or?

Just checked OC's client on my windows machine and it is using new named files.

**Comment by rullzer** [comment]
This is on our todo to look into. However both our windows skillz are suboptimal.

**Comment by PhilLab** [comment]
![grafik](https://user-images.githubusercontent.com/1710255/53050205-16487a00-3499-11e9-8554-19d5fc0b1698.png)

4,5 years are centuries in security years, IMHO . And as @klada linked to, there are known vulnerabilities

**Comment by rakekniven** [comment]
@PhilLab Can you help the desktop team to update the libs?

**Comment by rakekniven** [comment]
Another vote from our forums.

**Comment by misch7** [comment]
Hey,

have you seen our latest builds already? They are not outdated anymore ;-)

For the current 2.5.3 release: It's built with a current version and security fixes: OpenSSL 1.0.2s (2019-05-28)

![client-win-2 5 3-ssl-part](https://user-images.githubusercontent.com/48932272/63067216-243dfb80-bf0e-11e9-8ec9-9384ff643091.png)

What matters here is the sub-release 's' of May 28. The 1.0.x versions receive security updates till the end of this year.

**Comment by rakekniven** [comment]
Great! 
Damn, I missed the v2.5.3 release.
Just did the update and hooray, I got a newer ssl lib.

Thank you.

**Comment by misch7** [comment]
@rakekniven You're welcome :-)

Good news: The next Windows release will include OpenSSL 1.1.1c with TLS 1.3 support 😸 

For details see: https://github.com/nextcloud/desktop/issues/906#issuecomment-522713258

Time to close the issue 😼
