### ISSUE TITLE
[Bug]: macOS Desktop.app 3.10.1git (build 18409) | deleting virtualfile issue

### ISSUE THREAD

**Issue by sl-lebrit** [nextcloud/desktop#6224]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Deleting a VirtualFile doesn't delete both the VirtualFile on Mac and the actual file on server but does a little crazy thing…

### Steps to reproduce

1. VirtualFiles [experimental] feature must be active
4. The synchronisation starts and completes without any problems, except that the creation of some 300,000 1kb files with the extension '.nextcloud' in my ~/Nextcloud folder takes more than four hours.
5. I would like to delete a file (both locally and on the server) so I move a virtualfile (.nextcloud) to the recycle bin and empty the bin
6. 

### Expected behavior

**Expected behavior** 
After emptying the recycle bin, files will be permanently deleted everywhere.

**What happens**
The actual file on server isn't deleted and a new instance of the virtual file is back in its original place again

**Runaround**
The only way to delete a file is **Making it always available locally**, then deleting it and emty the bin. No problem if the file is small but, in case it's a very large file, the operation is tedious

![Deleting virtualfiles](https://github.com/nextcloud/desktop/assets/79972942/113c113d-6dc0-48f3-bd78-59890e59f8e3)

### Which files are affected by this bug

all *.nextcloud virtualfiles

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Monterey 12.7.1 (21G920)

### Package

Other

### Nextcloud Server version

27.1.3

### Nextcloud Desktop Client version

3.10.1git (build 18409)

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
NOTHING ABOUT THE DELETING IS LOGGED ON SERVER NOR LOCALLY.
```

**Comment by sl-lebrit** [comment]
I forgot to say that I've never used the VirtualFiles feature before
Stefano

**Comment by marcotrevisan** [comment]
Hi @sl-lebrit, this was described in #4474
The development of the Mac OS VFS client is still not finished so if you use the current client, you'll still encounter those glitches when virtual files mode is on.

**Comment by marcotrevisan** [comment]
Perhaps this issue can safely be closed and kept watch on #1337 and #5693 instead. 
It won't be long before we start getting beta releases of the Mac VFS client to test.

**Comment by sl-lebrit** [comment]
Sorry for the time wasted answering. The search I did with the key "VirtualFile" returned nothing.However, this problem is not relevant if documented.Please close the issueBuona serata,——————————Stefano LesandriniOn 15 Nov 2023, at 17:00, marcotrevisan ***@***.***> wrote:﻿
Perhaps this issue can safely be closed and kept watch on #1337 and #5693 instead.
It won't be long before we start getting beta releases of the Mac VFS client to test.

**Comment by marcotrevisan** [comment]
@sl-lebrit sorry I can't close it, I don't have such permissions, but you can close it for sure (your view should include the Close button).

Regards, Marco

**Comment by sl-lebrit** [comment]
Closed as per your suggestion.
