### ISSUE TITLE
[Bug]: Client keeps resetting folder sync settings and syncs _everything_ instead

### ISSUE THREAD

**Issue by moedn** [nextcloud/desktop#6229]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

My desktop sync client is set up for multiple accounts and selective sync settings and has been running for years without any issues. Since about a month these selective sync settings seem to reset themselves and since today this is happening for two accounts, on two different nextcloud server versions (which haven't changed lately, so I assume it's on the client side).

Example: I have a large folder on the server side with let's say 30 subfolders and only want to sync 4 of them. When I hit "apply" the connection is established, folders are synced, all good. Then, silently, the client starts syncing all other subfolders as well although they don't appear as selected in the sync client's settings. When I restart the client, all folders are selected. Resetting the configuration (deleting all data locally, deleting the folder connection, adding the folder connection anew, downloading the data via the client) doesn't change the behavior.

This is especially annoying since the sync fills up my disc until it is full and the sync stops – and this happened repeatedly on mobile data and got a little pricy. 

### Steps to reproduce

1. create a selective folder connection (= only sync selected subfolders)
2. sync, everything looks fine
3. at some point all other subfolders are synced as well…
4. and the sync settings (= selection which folders to sync) have changed to all

### Expected behavior

sync only the selected subfolders

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

Fedora Linux 38

### Package

Distro package manager

### Nextcloud Server version

27.1.2

### Nextcloud Desktop Client version

3.10.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
asked the admin for an export
```

### Additional info

happy to help with local logs; please just tell me where I can export them :)

**Comment by moedn** [comment]
update: I tried a workaround, adding only the the subfolders I want to sync completely as a connection, but the client started syncing _the whole_ cloud instead. So it's seemingly not only resetting the folder sync settings but also ignoring them all along

just uninstalled the client and there's 2 files I can't delete, in the folder where synced subfolders are:

![image](https://github.com/nextcloud/desktop/assets/45949491/4f0dd34b-c2db-45a4-98e4-65fee5322afa)

hope that helps

**Comment by phil8900** [comment]
We are seeing the same behaviour with Nextcloud Server 27.1.3 in combination with Nextloud Client 3.10.1.

**Comment by moedn** [comment]
I deleted the locally created folders I didn't want to sync and the client (naturally, but didn't come to my mind) deleted the folders on the server… so looks like the folder sync settings are just completely bypassed

**Comment by moedn** [comment]
I just found [this comment](https://github.com/nextcloud/desktop/pull/6143/commits/bd2613cdbab7cdeca7b8f3c0acfc5d41950bad1e) in the commits for #6143 that has been fixed for [v3.10.2](https://github.com/nextcloud/desktop/releases/tag/v3.10.2)

I might give it a try next week or so and see if the update solves this issue (for me at least)
