### ISSUE TITLE
[Bug]: Filese won't update until system is rebooted

### ISSUE THREAD

**Issue by charliehoward** [nextcloud/desktop#6232]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Once the system boots up NextCloud will download or upload any recent changes but I then make a change to a file it won't be uploaded until I next reboot, the same goes for changing the file on another device, it won't download that change on the Linux system until I reboot.
For example, if I save a screenshot to NextCloud on my Linux desktop that file won't be uploaded until I reboot the system

### Steps to reproduce

1. Start NextCloud and download/upload any recent changes.
2. Make a change to any file either on the host system or another system
3. The change won't upload/download until the next restart of the system

### Expected behavior

The file I change should be uploaded/downloaded instantly 

### Which files are affected by this bug

Everything

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04.3 LTS

### Package

Distro package manager

### Nextcloud Server version

27.1.2

### Nextcloud Desktop Client version

3.4.2-1ubuntu1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
My server is externally hosted so I don't have access to logs, but this only happens on this one device so it's client side not server side
```

### Additional info

I also can't create a debug log, clicking create does nothing

**Comment by joshtrichards** [comment]
> I also can't create a debug log, clicking create does nothing

What about one of the alternative approaches for accessing the client debug logs? (Ctrl-L, command line, etc.)

https://docs.nextcloud.com/desktop/3.4/troubleshooting.html#log-files

Also is this a brand-new installation or some behavior that recently started for you?

> My server is externally hosted so I don't have access to logs, but this only happens on this one device so it's client side not server side

So this the only desktop device in-use presumably?

P.S. Even without shell access, there's still a chance server logs are available from Admin settings->Logging in the web user interface.

**Comment by charliehoward** [comment]
> > I also can't create a debug log, clicking create does nothing
> 
> What about one of the alternative approaches for accessing the client debug logs? (Ctrl-L, command line, etc.)

Yeah I can't get any of those to work

> Also is this a brand-new installation or some behavior that recently started for you?

It's been happening for a while, maybe a month or two, I did try a reinstall but that didn't solve anything

> So this the only desktop device in-use presumably?
 No, I have 3 Windows machines, all of which work fine

**Comment by joshtrichards** [comment]
> Yeah I can't get any of those to work

Can you elaborate? 

> It's been happening for a while, maybe a month or two, I did try a reinstall but that didn't solve anything

So this is new behavior? Maybe something else is going on with your system. Unfortunately without logs we're kind of flying blind. It's all ancient version of the client.

**Comment by charliehoward** [comment]
Do they not make a newer version of the client?

**Comment by joshtrichards** [comment]
Yes. The current version is 3.10.x. Your using the old built-in one in your OS. May want to try the AppImage of a more current release.

**Comment by charliehoward** [comment]
Looks like that solved it. Using AppImages isn't really something I do on Linux, seems a very Windows way to do things
