### ISSUE TITLE
Files over 10 MB break when uploading again to S3 Primary Storage

### ISSUE THREAD

**Issue by wmeneses** [nextcloud/desktop#6239]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hello, with version 3.10 recently closed the case of not being able to upload files larger than 10MB, in S3 with the update everything seems normal, because the user can upload files with this size or larger to their folders.

But, if he does it in a folder shared by another user just at the moment that he makes sync the file does not arrive to the server, but the database assumes that it was uploaded, causing an error 500.

It is corrected by uploading the file manually from the web. I have returned the client to 3.9 and everything works perfect.

### Steps to reproduce

- 
![imagen](https://github.com/nextcloud/desktop/assets/5956910/05d41686-13d1-42a6-82c0-8b43601c3675)
uploading a file larger than 10MB to a shared folder

### Expected behavior

no problem in the previous version

### Which files are affected by this bug

files larger than 10MB

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 /11

### Package

Appimage

### Nextcloud Server version

27.1.3

### Nextcloud Desktop Client version

stable 3.10

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by wmeneses** [comment]
AWS HTTP error: Client error: `PUT https://server-nextcloud.storage.googleapis.com/urn%3Aoid%3A78428932?partNumber=3&uploadId=ABPnzm6jI_bMuIHfnekVr8OnkyTxWqzLy9-zNhVRaMBsL1sWD1HJ6d2wOnmGHzL
CPm462e4` resulted in a `400 Bad Request` response:\n<?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requeste (truncated...)\n NotImplemen
ted (client): A header or query you provided requested a function that is not implemented. - <?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provid
ed requested a function that is not implemented.</Message><Details>UploadPartCopy is not implemented for multipart uploads.</Details></Error>\n- Part 2: Error executing \"UploadPartCopy\" on \"https://m
abella-nextcloud.storage.googleapis.com/urn%3Aoid%3A78428932?partNumber=2&uploadId=ABPnzm6jI_bMuIHfnekVr8OnkyTxWqzLy9-zNhVRaMBsL1sWD1HJ6d2wOnmGHzLCPm462e4\"; AWS HTTP error: Client error: `PUT https://m
abella-nextcloud.storage.googleapis.com/urn%3Aoid%3A78428932?partNumber=2&uploadId=ABPnzm6jI_bMuIHfnekVr8OnkyTxWqzLy9-zNhVRaMBsL1sWD1HJ6d2wOnmGHzLCPm462e4` resulted in a `400 Bad Request` response:\n<?x
ml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requeste (truncated...)\n NotImplemented (client): A header or query you provided requested a
 function that is not implemented. - <?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Messag
e><Details>UploadPartCopy is not implemented for multipart uploads.</Details></Error>\n- Part 4: Error executing \"UploadPartCopy\" on \"https://server-nextcloud.storage.googleapis.com/urn%3Aoid%3A7842
8932?partNumber=4&uploadId=ABPnzm6jI_bMuIHfnekVr8OnkyTxWqzLy9-zNhVRaMBsL1sWD1HJ6d2wOnmGHzLCPm462e4\"; AWS HTTP error: Client error: `PUT https://server-nextcloud.storage.googleapis.com/urn%3Aoid%3A7842
8932?partNumber=4&uploadId=ABPnzm6jI_bMuIHfnekVr8OnkyTxWqzLy9-zNhVRaMBsL1sWD1HJ6d2wOnmGHzLCPm462e4` resulted in a `400 Bad Request` response:\n<?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImple
mented</Code><Message>A header or query you provided requeste (truncated...)\n NotImplemented (client): A header or query you provided requested a function that is not implemented. - <?xml version='1.0'
 encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Message><Details>UploadPartCopy is not implemented for multipa
rt uploads.</Details></Error>\n"}}

**Comment by joshtrichards** [comment]
Can you please provide the full stack trace from your Nextcloud server at the time period of the upload? A sample of a couple of the entries immediately preceding it would be helpful as well.

Also, can you clarify that these two statements accurately summarizes your bug report?

- non-shared folders uploads work fine (with large files)
- shared folder uploads break (with large files)

Lastly, what are your Desktop client chunk parameter settings?

**Comment by wmeneses** [comment]
tail -f nextcloud.log | grep error:
[track error.txt](https://github.com/nextcloud/desktop/files/13445794/track.error.txt)


If I upload a file larger than 10 MB to my nextcloud folder, I have no problem, if I upload the same file to a folder I have shared error 500, it never seems to reach the server, but the database assumes it does.

My client has no extra settings... I have disabled server side chunks, but nothing happens.

if I install the previous version everything is fixed, and the files upload without any problem (even the ones I couldn't upload before).

**Comment by wmeneses** [comment]
This bug is still not fixed in the new version 3.10.2, I was hoping that it would be fixed, I have decided not to use this client anymore, and I will stay with raidrive (Webdav) even if it is not opensoucse and has ADS. 

this client, and I will stay with raidrive (Webdav) even if it is not opensource and has ADS.

Thank you very much!

**Comment by wmeneses** [comment]
This error appears again forcing me to acquire a commercial webdav client, I can not upload files larger than 10MB in shared folders when my primary storage is s3, if I try to upload a file to an external drive where I have shared a folder with XFS format it works fine.
I have tried with the latest client version
