### ISSUE TITLE
[Bug]: Synchronized folders appear as double on Fedora 39 with GNOME

### ISSUE THREAD

**Issue by xplosionmind** [nextcloud/desktop#6243]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

As displayed in the screenshot any folder directory is displayed twice.

![Screenshot from 2023-11-25 13-54-15](https://github.com/nextcloud/desktop/assets/42862428/742e9e6d-2e96-47aa-8599-cc6176b3dd5d)

### Steps to reproduce

1. Open the Terminal and run `sudo dnf install nextcloud-client`
2. Open the system file manager and notice the issue in the sidebar

### Expected behavior

There should be only one bookmark in the sidebar for each synchronized folder

### Which files are affected by this bug

It is not about files

### Operating system

Linux

### Which version of the operating system you are running.

Fedora 39

### Package

Distro package manager

### Nextcloud Server version

27.1.4

### Nextcloud Desktop Client version

3.10.1 (Fedora)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

**Comment by cfanatic** [comment]
I have the exact same problem with the sidebar integration on Debian.

I run Nextcloud Desktop Client 3.10.0 (Debian).

Please get it fixed, problem has been persistent since months.

**Comment by cfanatic** [comment]
Hi @xplosionmind 

I figured out how to resolve this issue.

Please check: [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056327](url)

The patch attached to Message #10 explains that `/usr/share/cloud-provider directory` needs to be removed if `libcloudproviders 0.3.3+` is installed on the system.

This solution works for me.

**Comment by xplosionmind** [comment]
Thanks a lot for your comment, @cfanatic!

I missed the issue mentioned in the Debian bug tracker. Hence, **this issue is a duplicate of #6218**: I am closing this issue and use that as the main reference.

Since I installed `nextcloud-client` as a `.rpm` package, and since I do not really know how to meddle with rpm packages, I think I will wait for this issue to be fixed upstream (unless you are so kind to guide me through the steps).

**Comment by xplosionmind** [comment]
Update: I removed a few lines from `/usr/share/applications/com.nextcloud.desktopclient.nextcloud.desktop`, as suggested in [this comment](https://github.com/nextcloud/desktop/issues/6218#issuecomment-1818390412). It works for me.
