### ISSUE TITLE
[Bug]: Unknown error or Access denied during syncing on Win 10 (maybe AVAST is blocking the syncing)

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/desktop#6245]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Hi! I have several users using local cloud through the NC Desktop Client syncing. And one of them is constantly getting error and complaining that syncing is not working. Trying to understand what is happening I deleted the syncing folder, created it again, created user on that laptop. It helps but partially. Later I found that the user uses Avast antivirus on his win10 laptop.

### Steps to reproduce

1. User B creates a file on remote PC, syncs it with the cloud.
2. User A syncs the cloud automatically with his local laptop.
3. User B modifies file on a remote PC, syncs it with the cloud.
4. User A catches Unknown Error or Access denied error with cross, all syncing is stuck.
5. User A removes manually the file, which is indicated in the error, and syncing continues.
...

### Expected behavior

First of all, syncing SHOULD NOT stop if there's a problem with some file. It should just indicate a problem and continue syncing of all other files.

Secondly, I did a small research and found that ... local antivirus AVAST may block the correct syncing, however, I need more argument, that it is true.

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Appimage

### Nextcloud Server version

27.1.4

### Nextcloud Desktop Client version

3.10.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
none
```

**Comment by joshtrichards** [comment]
If you have several users and this is the only one impacted, it does sound more likely something specific to this user's environment. A virus scanner could certainly be one culprit. How about disabling it and trying to reproduce the problem?

You may want to post on the Nextcloud Help Forum to get some feedback - https://help.nextcloud.com

**Comment by ostasevych** [comment]
> If you have several users and this is the only one impacted, it does sound more likely something specific to this user's environment. A virus scanner could certainly be one culprit. How about disabling it and trying to reproduce the problem?
> 
> You may want to post on the Nextcloud Help Forum to get some feedback - https://help.nextcloud.com

Yes, you are right. This is specific to Avast issue.
