### ISSUE TITLE
Client crashes after expanding an unavailable shared folder

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/desktop#627]
I´m using the current daily build + Nc 14 RC2. One of the instances which shared a folder with my instance is currently not available. The client marks the folder correctly in the windows explorer but after clicking the expand button in the settings it crashes:

![expand](https://user-images.githubusercontent.com/1869584/45149951-0844bc80-b1cb-11e8-96db-562893d44826.png)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
