### ISSUE TITLE
Mac OS X 10.15 and Nextcloud

### ISSUE THREAD

**Issue by piotr58** [nextcloud/desktop#6276]
Hello,

Just to let you know that Mac OS X 10.15.7 easily supports version 3.10.0 of the Nextcloud client. There's no need to install the legacy version 2.6.5 shown as the only one available for versions 10.10+ to 12.

Have a nice weekend!

**Comment by maffi-git** [comment]
I cannot confirm this for Version 3.11. 
The app is not executable and states it requires at least macOS 12. Are you really sure, you are running 3.10?

**Comment by joshtrichards** [comment]
See #6176 

I guess v3.10.0 "worked" for some, but was not supported. It completely stopped working I guess in >=v3.10.1.

**Comment by Ivan64** [comment]
I had to reinstall NC v3.10.0. I did try to install the legacy version for macOS 10.10+ but that did not work.

I'm running macOS 10.15.7
