### ISSUE TITLE
[Bug]: Legacy version for macOS cannot be installed

### ISSUE THREAD

**Issue by fuzzykiller** [nextcloud/desktop#6277]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When trying to install the macOS client legacy version, an error appears: 

> “Nextcloud-2.6.5.20200710-legacy.pkg” can’t be opened because Apple cannot check it for malicious software.

This is apparently caused by the notarization info on this file is too old or something. I’m not a macOS developer, sorry if the terms are inaccurate.

```
# spctl -a -vvv -t install Nextcloud-2.6.5.20200710-legacy.pkg 
Nextcloud-2.6.5.20200710-legacy.pkg: rejected
source=Unnotarized Developer ID
origin=Developer ID Installer: Nextcloud GmbH (NKUJUXUJ3B)
```

### Steps to reproduce

Download legacy client from Nextcloud homepage, attempt to open the `.pkg` file.

### Expected behavior

Client should install.

### Which files are affected by this bug

n/a

### Operating system

Mac OS

### Which version of the operating system you are running.

11.7.9 (20G1426)

### Package

Other

### Nextcloud Server version

latest aio

### Nextcloud Desktop Client version

2.6.5

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
See #6179 step 2 in the reproduction steps for how to address that.

There's only so much that can be done about legacy clients which aren't even officially supported...
