### ISSUE TITLE
Can not create a new account on a local domain with custom cert

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/desktop#628]
1. Set up nextcloud on your maschine `https://localhost`
2. Start the client and add a new account
3. Trust your custom cert
4. Click "Next"
5. :boom: it's stuck

> ![bildschirmfoto von 2018-09-06 14-21-52](https://user-images.githubusercontent.com/213943/45157376-49e06200-b1e1-11e8-9bd1-798477ce9420.png)

**Comment by nickvergessen** [comment]
cc @juliushaertl @rullzer

**Comment by camilasan** [comment]
You mean self signed certificate?
If yes, this is a known issue. PR #630.

**Comment by nickvergessen** [comment]
Yes, that sounds very much like it

**Comment by rullzer** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/758

**Comment by hawawy2000** [comment]
I have the same problem as how to fix it
