### ISSUE TITLE
Windows 11 support?

### ISSUE THREAD

**Issue by tflidd** [nextcloud/desktop#6301]
There are questions about the Windows 11 support since the web page only provides a client for Windows 10.
https://help.nextcloud.com/t/nextcloud-doesnt-run-on-windows-11/176672

From documentation, anything since Windows 8.1 should be good:
https://docs.nextcloud.com/desktop/3.11/installing.html#system-requirements

**Comment by AndyXheli** [comment]
yes Windows 11 is supported.

**Comment by dugite-code** [comment]
The image from the Nextcloud website that's causing the confusion: ![e149c8725a3179bad4c586a3cc5ff983fcdca487_2_690x333](https://github.com/nextcloud/desktop/assets/12742064/ffb1cc35-ba29-4718-90f4-5f9d5c9dfd5a)

**Comment by tflidd** [comment]
It was fixed today.
