### ISSUE TITLE
Implement trash container support in File Provider module

### ISSUE THREAD

**Issue by claucambra** [nextcloud/desktop#6303]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by joshtrichards** [comment]
#5995 ? :-)

**Comment by claucambra** [comment]
> #5995 ? :-)

huh! must have missed this, thanks for pointing it out
