### ISSUE TITLE
[Bug]: In General Tab, version information is missing in 3.11

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/desktop#6305]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

In General Tab, version information is missing in 3.11

### Steps to reproduce

Open the General tab in Settings

### Expected behavior

Version information is shown
![ksnip_20231218-211014](https://github.com/nextcloud/desktop/assets/85954408/b98c0af9-1359-4ada-bc84-f7516d719ce9)
![ksnip_20231218-213130](https://github.com/nextcloud/desktop/assets/85954408/5d37b4dd-1fcf-4faf-adc4-ba34e1b6b2db)

### Which files are affected by this bug

none

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu Desktop 22.04

### Package

Other

### Nextcloud Server version

27.1.5

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by klou** [comment]
Same, Windows x64 3.11.0 client.

**Comment by alexanderdd** [comment]
Same, on Linux Mint 21.3 (based on Ubuntu Jammy), using the PPA https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

**Comment by pmarini-nc** [comment]
Not solved yet in 3.11.1

**Comment by klou** [comment]
Looks like fixed by #6459 (3.12.1). 

Can probably be closed.

**Comment by pmarini-nc** [comment]
@allexzander , can you please explain why the information is now much reduced? As shown in the screenshot in the issue description, before the information about the OS, the kernel and a "more info" link was provided.

**Comment by joshtrichards** [comment]
Fixed in #6459 

@pmarini-nc As to your question, looks like it was a design decision - see #5142
