### ISSUE TITLE
[Bug]: Windows client does not sync files, which are deleted from server

### ISSUE THREAD

**Issue by JP95Git** [nextcloud/desktop#6307]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

If you enable E2E and upload some files and folders, these end up encrypted in a folder like 
/web/nextcloud.myhostname.org/data/user1/files

If you delete some files and folders using tools like WinSCP, the windows client does not reupload the deleted files. I got a green checkmark, so it thinks all files are still there.

### Steps to reproduce

1. See description

### Expected behavior

The windows client should reupload deleted files on server.

### Which files are affected by this bug

all files

### Operating system

Windows

### Which version of the operating system you are running.

Win 10 22H2

### Package

Other

### Nextcloud Server version

27 (because E2E does no longer work in 28)

### Nextcloud Desktop Client version

The version before Nextcloud-3.11.0-x64.msi (because the lastest does not detect E2E)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> If you delete some files and folders using tools like WinSCP, the windows client does not reupload the deleted files. I got a green checkmark, so it thinks all files are still there.

So you're deleting files from the Nextcloud Server's `datadirectory` outside of Nextcloud?

This isn't a Desktop client matter. You need to read up on how the Nextcloud Server handles files being modified within its file repository by external processes. In short: you shouldn't do this, but if you do you'll need to trigger file scans on the server.

Closing this this isn't a bug. Please see the Nextcloud Server Admin Manual - https://docs.nextcloud.com and/or query the Nextcloud Help Forum - https://help.nextcloud for assistance.
