### ISSUE TITLE
error while loading shared libraries: libQt5DBus.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/desktop#631]
Running Ubuntu 18.04.01

Worked fine a week ago

Fresh install of Ubuntu today and getting the error while loading shared libraries: libQt5DBus.so.5: cannot open shared object file: No such file or directory

However, libQt5DBus5 IS installed on my system

appimage works fine, however, though it's not my preferred solution

**Comment by camilasan** [comment]
Which Qt version is being used in Ubuntu 18.04?

**Comment by ashgoodman** [comment]
Qt5.9

**Comment by camilasan** [comment]
And which version of the client is it? How did you install it?

**Comment by ashgoodman** [comment]
The version in the PPA as provided here: https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

**Comment by ivaradi** [comment]
The PPA has not changed for ages, so it must be something else on your system.

Could you check, if the file ```/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5``` is present, and is a symlink to ```libQt5DBus.so.5.9.5``` (or something like that), which is also present, and is a regular file of a non-zero length. (On my system, which is also  an Ubuntu 18.04.1, its MD5 sum is ```1fd4c38278a8270077585b413a624385```, but we may be on slightly different versions of the packages).

**Comment by camilasan** [comment]
Thanks @ivaradi :)

**Comment by ashgoodman** [comment]
@ivaradi  Yes, it appears to be
![libqtscreen1](https://user-images.githubusercontent.com/21287394/45335826-a6fa6000-b5b3-11e8-8397-369f1c7714d1.png)


![libqtscreen2](https://user-images.githubusercontent.com/21287394/45335828-a9f55080-b5b3-11e8-867a-3c1c6ee75213.png)


![libqtscreen3png](https://user-images.githubusercontent.com/21287394/45335833-b1b4f500-b5b3-11e8-99d2-d77e2b9cc682.png)

**Comment by ivaradi** [comment]
@ashgoodman strange.... Could you open a terminal, issue the command ```ldd /usr/bin/nextcloud``` and copy the output here?

**Comment by ivaradi** [comment]
@ashgoodman you mentioned above, that you installed the PPA version, which is neither the snap, nor the appimage version... If you want to use the PPA version, you do not need the snap or the appimage version (and their presence might even cause some conflicts or mysterious errors).

The PPA version should install its dependencies automatically, yet a number of libraries is missing from your system (though not ```libQt5DBus.so.5``` you mentioned in your original post). For example, ```libQt5Widgets.so.5``` is in the package ```libqt5widgets5```, which the PPA package depends on.

Could you try reinstalling the client package with ```sudo apt-get install --reinstall nextcloud-client```?

**Comment by ashgoodman** [comment]
@ivaradi still giving the same error

`nextcloud: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

**Comment by ashgoodman** [comment]
`nextcloud: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

**Comment by ivaradi** [comment]
```libQt5Core.so.5``` is in the package ```libqt5core5a```. Could you check if you have that package installed (e.g. by ```dpkg -s libqt5core5a | grep Status```) and if the files ```libQt5Core.so.5``` and ```libQt5Core.so.5.9.5``` can be found in ```/usr/lib/x86_64-linux-gnu/```?

**Comment by ashgoodman** [comment]
@ivaradi 

`dpkg -s libqt5core5a | grep Status`

`Status: install ok installed`

All packages found

![libqtscreen4](https://user-images.githubusercontent.com/21287394/45410887-6da21d00-b6a5-11e8-862e-e21f57d1b937.png)

Also, I feel I should say thanks for all your help on this, even if we ultimately don't get it fixed it's appreciated.

**Comment by ashgoodman** [comment]
@ivaradi 

yes, they are

**Comment by ashgoodman** [comment]
`dpkg -s libqt5core5a | grep Status`

**Comment by ivaradi** [comment]
@ashgoodman 

Is the ```LD_LIBRARY_PATH``` environment variable set? If so, what is its value?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
