### ISSUE TITLE
All of my folder sync connections disappeared

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/desktop#632]
After smooth usage for a long time, every one of my folder sync connections disappeared from the desktop client, without a trace. This happened after a regular system restart.

Over the years I've put a lot of work into making that list, please help me restore it.

**Comment by camilasan** [comment]
Hi! I am sorry to hear you had this problem. 
First of all: which OS you are using?
Did you search for the nextcloud.cfg file in your system?
Which version of the client you are running?

**Comment by leafcutterant** [comment]
I don't have a Nextcloud folder in "Roaming". Only in "Local".

**Comment by leafcutterant** [comment]
Meanwhile, I would need to sync some folders. Would adding folders (the list is empty now) reduce the chance of being able to recover the old list?

**Comment by camilasan** [comment]
But did you search to check if you have more than one config file? I don't think changing the new one will change anything. Did you update your Windows? That is why it restarted?

**Comment by leafcutterant** [comment]
Yes, I searched the whole drive. Only one cfg file. Windowsn was not updated, I just restarted it to update some color settings.

**Comment by camilasan** [comment]
Did you loose data? Or just the configuration?

**Comment by leafcutterant** [comment]
Only the config is lost. Files, as far as I've ascertained, are intact.

**Comment by camilasan** [comment]
At the moment I don't see other way but for you to add the folders again, sorry.
"Hopefully" someone else will have the same problem but will be able to give more details.

**Comment by leafcutterant** [comment]
Alright - thank you.

In other issues I saw you referred people to early builds of the new version (2.5.x). Would you recommend that to me? Will I encounter such things with less probability there?

**Comment by camilasan** [comment]
This issue is quite odd. 
You can try the newer version but use a test account and test data.

**Comment by tonybecker** [comment]
This has happened on at least three of my desktop clients.  All are running 2.5.1 or 2.5.2 on Windows 10. They had been successfully syncing with a locally hosted server, Nextcloud 14.0.6, for months. For clients that were on 2.5.1, upgrading to 2.5.2 and recreating the sync connection list did not solve the problem - they disappeared again.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
