### ISSUE TITLE
[Bug]: Nextcloud won't load virtual files fast enough in the LAN. Desktop Client should use LAN to transfer instead of WAN.

### ISSUE THREAD

**Issue by Majestic7979** [nextcloud/desktop#6321]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

<img width="339" alt="image" src="https://github.com/nextcloud/desktop/assets/128995501/e2da2ed9-6f5b-4d7b-a085-eccb931f0040">

I run Nextcloud behind a reverse proxy with TLS (Let's Encrypt) and my own domain name.

It's set up on Windows 11 to serve virtual files, so that it can stream as needed.

However, I am noticing that when I go open footage I have stored on the server, even though both server and desktop workstation are in the same subnet in my LAN, the virtual file is downloaded by the Nextcloud client over the WAN, severely limiting the speed. Over the gigabit LAN I should get around 90MBps. Over the 100Mbps WAN Upload connection I am obviously limited to just around 10MBps. That's a 10x reduction in speed for absolutely no reason whatsoever.

Why won't Nextcloud developers fix WAN sync issues? This application is so massive now, every so often you guys will release new features while neglecting the core principle of storage which is that you are able to easily access and manipulate your files. None of which are true with the Windows virtual files method because streaming them over the WAN while the server and the workstation are in the same LAN subnet is just retarded. There should be a way to tell the desktop sync app "hey app, this is my cloud domain for you to authenticate, but here is also my LAN IP and port for the nextcloud instance so you can do syncs with faster speeds when you're in the same subnet as the server" and have the sync client transparently handle the way it connects, preferring LAN over WAN wherever possible.

### Steps to reproduce

Self explanatory per description.

### Expected behavior

I expect the desktop client to allow me to specify internal (LAN IP:port) and external (fqnd) for the Nextcloud instance and choose LAN for sync to take advantage of full-duplex Gigabit speed instead of being limited to my WAN upload while simultaneously "robbing me of internet capacity" for a sync that really should be occurring locally over the same subnet.

### Which files are affected by this bug

All

### Operating system

Windows

### Which version of the operating system you are running.

Win 11

### Package

Other

### Nextcloud Server version

28.0.1

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Majestic7979** [comment]
> While reading you ticket i think you should have a look at the https://nextcloud.com/contribute/code-of-conduct/. Regarding your problem. You should habe a look at Split DNS. This problem should be solved at your network and not in the desktop client code.

My conduct is because of replies like yours who always push the blame to the customer. I won't do anything in my DNS. Other cloud sync apps have a LAN mode that don't put the onus on the customer. Dropbox for instance. If they can figure it out, Nextcloud should too.

**Comment by joshtrichards** [comment]
> who always push the blame to the customer

This is open source software. You're not a "customer" and I'm afraid none of us owe you anything (I'm a volunteer).

Anyhow, the above response was accurate. Though I'm also unclear why your topology has you going out a WAN link if your proxy is local to you, since your router just should be bouncing you right back. You might be constrained by the router being in the middle, but it should not be going out your WAN link (unless you've outsourced your proxy to maybe something like Cloudflare)
