### ISSUE TITLE
[Bug]: File Upload slows down when tray-windows is opened

### ISSUE THREAD

**Issue by mabeck007** [nextcloud/desktop#6325]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

File Upload-Speed reduces to approx 1/10th of the Speed when the Tray-Window is opened. As soon as the Tray-Window is closed or the Settings-Page (Main Window) is opened, the Upload-Speed speeds up to maximum network bandwith.
![nextcloud_fast](https://github.com/nextcloud/desktop/assets/66473868/26340e2d-ebd7-4135-a957-a210e0e39c27)
![nextcloud_slow](https://github.com/nextcloud/desktop/assets/66473868/30e61d70-f599-4505-94c4-40a40fc7baa3)

### Steps to reproduce

1. Create a big file for Upload (I've used fsutil)
2. Open Task Manager to track the network load
3. as the upload is starting -> click on the Nextcloud tray icon to open the tray window -> upload-speed is decreasing 

### Expected behavior

Consistant Upload-Speed

### Which files are affected by this bug

example.txt

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 - Build 22621.2861

### Package

Appimage

### Nextcloud Server version

27.1.5.1

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by PhilippSchlesinger** [comment]
This is a duplicate of https://github.com/nextcloud/desktop/issues/4918

**Comment by mabeck007** [comment]
> This is a duplicate of https://github.com/nextcloud/desktop/issues/4918

Oh, thanks!

**Comment by PhilippSchlesinger** [comment]
@mabeck007 so you may close this bug and maybe add valuable details to #4918
There is also a possible fix provided in https://github.com/nextcloud/desktop/issues/4918#issuecomment-1637504707 by disabling the syncing icon animation.

**Comment by roberix** [comment]
Solved with 3.12.4

**Comment by mabeck007** [comment]
Tested with 3.13.0 -> problem solved
