### ISSUE TITLE
[Linux] Possibility to get connection status from the app

### ISSUE THREAD

**Issue by Yaakoss** [nextcloud/desktop#6328]
I use a window tiling manager (Qtile) and i do not use systray. I would like to have a possibility to get a connection status from the app for example by invoking 
`nextcloud --connection-status`
`Status: Connected` or Disconnected or Error

That would allow to implement a widget that shows the status of the connection.

**Comment by joshtrichards** [comment]
Duplicate of #6345 (it contains a bit more traffic)
