### ISSUE TITLE
Difference with last release version (2.3.3)

### ISSUE THREAD

**Issue by mj-mehdizadeh** [nextcloud/desktop#633]
Hi
i clone the last version of `master branch` and run it,
the last version Broken the selected folder Icon after few moments and I saw some other bugs.
but the **2.3.3** does not have This problems
and it seems there are more options in **2.3.3** which is older.

which branch have all of options and no bug?
which branch is much better for develop?

**Comment by camilasan** [comment]
Hi, all the changes that are coming on 2.5 are in master. You should create a branch from master for development. Are you using Linux, Mac OS or Windows?
If you find any bugs, please report it if there isn't already an issue opened for it.

**Comment by mj-mehdizadeh** [comment]
the `Nextcloud-2.5.0.61251-Debug-20180803-beta1.exe` Broke Folder sync icon
but the `nextcloudv2.3.3` does not have This problem
![p1](https://user-images.githubusercontent.com/11937510/45262856-442e8a80-b434-11e8-890b-2a22414783e7.PNG)
_this is screenshot of v 2.5_

--------
and there is some tab in the `nextcloudv2.3.3`, but there is not in `Nextcloud-2.5.0.61251`
![p2](https://user-images.githubusercontent.com/11937510/45262917-68d73200-b435-11e8-8183-e5e07dbd8676.PNG)
_this is screenshot of v 2.5_

**Comment by camilasan** [comment]
> and there is some tab in the nextcloudv2.3.3, but there is not in Nextcloud-2.5.0.61251
Yes, we merged the activities with the notifications. This is the new UI.

> the Nextcloud-2.5.0.61251-Debug-20180803-beta1.exe Broke Folder sync icon
but the nextcloudv2.3.3 does not have This problem
And please, use the beta2 or one of the latest daily builds because we already have fixed the icons.

**Comment by JarbyDev** [comment]
and what about the Not Synced Tab?
