### ISSUE TITLE
[Bug]: Add account button disappeared

### ISSUE THREAD

**Issue by geez0x1** [nextcloud/desktop#6358]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

There is no (more) button to add another account in my NC client. I currently have three and want to add a fourth.

### Steps to reproduce

1. 'Open main dialog' from tray icon
2. Click on currently active account, see list of accounts
3. Do not see a button to add another account
4. Also notice the GUI is pretty damn broken (invisible buttons, colouring, etc)

### Expected behavior

Find the button to add an account (and the GUI to not be this broken)

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 23.10

### Nextcloud Desktop Client version

3.11.0 (flatpak)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4) with `flatpak update`. Also tried `flatpak install --reinstall`, to no avail.

### Additional info
In the following screenshot, I've indicated where I was expecting to find the "Add account" button (I recall it being here before), as well as the missing (but clickable) buttons for things like Talk, at the top. Other white blocks are my redactions for privacy, but the text behind them is grey-on-grey, hard to read, suggesting problems with a dark theme.
![Screenshot from 2024-01-18 10-55-57_edit](https://github.com/nextcloud/desktop/assets/7889615/0d8c46ac-627b-44f2-89eb-8bc3c8a700e4)

**Comment by joshtrichards** [comment]
Duplicate of #6167 

See there for the situation. It's Flatpak specific.

**Comment by franga2000** [comment]
I have the same problem outside of Flatpak, it's not even installed. Tried deleting `.cache/Nextcloud` and `.config/Nextcloud`, set up the first account again and the issue is still there. I'm running KDE Plasma 6 on Wayland and I've tried various values of `QT_QPA_PLATFORM` and `QT_QPA_PLATFORMTHEME` with no luck.

![image](https://github.com/nextcloud/desktop/assets/3891092/72ba1a98-f2c9-4136-9b62-bd98d6fb2721)

**Comment by superSTA101** [comment]
> I have the same problem outside of Flatpak, it's not even installed. Tried deleting `.cache/Nextcloud` and `.config/Nextcloud`, set up the first account again and the issue is still there. I'm running KDE Plasma 6 on Wayland and I've tried various values of `QT_QPA_PLATFORM` and `QT_QPA_PLATFORMTHEME` with no luck.
> 


I have done the same steps as well with no luck. I am running Arch linux KDE Plasma 6 and I'm using the `nextcloud-client` package from arch repos.

**Comment by Etienne-TR** [comment]
I have the same problem on Plasma 6 and nextcloud-client 3.13.0 on Solus OS.

I also tried with flathub nextcloud-client version but the problem remained.

**Comment by lensum** [comment]
This problem also appears when installing from fedoras repositories (using `dnf`). Even when installing the client as flatpak, [the previous fix does not work anymore](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/130#issuecomment-2098886888) (tested the CLI-version myself), so it's probably a new problem. Also, as previously mentioned, it is not limited to flatpak anymore and appears with installation from the Arch and Fedora repos as well.

Question remains: is it a Nextcloud problem or does the problem lie somewhere else? Seeing that it appears under Gnome, Plasma and on Arch and Fedora, I would assume that it's a Nextcloud problem, but I might be off here.

**Comment by lionking102** [comment]
Same Problem here with Fedora 40 - Plasma 6.
Did anyone find a solution, yet?

**Comment by stueja** [comment]
Same problem on Arch Linux, KDE Plasma 6, installed via pacman, no flatpak.

**Comment by franga2000** [comment]
`nextcloud-client-git` from the Arch AUR does not have this problem, so it might be that this is caused by different build flags or something

**Comment by IPlayZed** [comment]
I am on Arch Linux, using 3.12.3 from Flathub, adding the QT_QPA_PLATFORMTHEME=kde does NOT solve this issue!

**Comment by mandrewsan** [comment]
Same issue. Fedora 40, KDE 6.1.1. Downloaded from Fedora repo via dnf.

**Comment by BBArikL** [comment]
Building against QT6 seems like it is solving this issue when using the client directly from the distribution package manager (see https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/pull/164) and maybe this issue should be deferred to each distribution packagers ((Arch)[https://archlinux.org/packages/extra/x86_64/nextcloud-client/] and (Fedora)[https://packages.fedoraproject.org/pkgs/nextcloud-client/nextcloud-client/])

**Comment by Polux49** [comment]
Same issue. 
Manjaro + Kde Plasma, with package `extra/nextcloud 29.0.2-1` (not Flathub).

**Comment by IPlayZed** [comment]
Is there a way to force verbose output from the sync client? Maybe it reports what the problem is.

**Comment by toxpal** [comment]
Same problem here on all computers with KDE Plasma (not using Flatpak).

**Comment by toxpal** [comment]
> `nextcloud-client-git` from the Arch AUR does not have this problem, so it might be that this is caused by different build flags or something

Or there's a bug in recent versions of NC client. nextcloud-client-git is version 3.13.0, while "normal" version is 3.13.2 (newer). In other hand, I don't know when exactly this issue started, maybe it was in "normal" version for a long time too...

**Comment by IPlayZed** [comment]
> Is there a way to force verbose output from the sync client? Maybe it reports what the problem is.

I still hold my point that unless we get verbose output, we can not identify what causes this regression. I do not have the setup to check this now or in the foreseeable future.

**Comment by JYPDWhite** [comment]
I also have the same problem KDE, Plasma, native nextcloud client (no flatpak) I'm happy to deliver logfiles when someone tells me what kind of logfiles are needed and how to generate them.

**Comment by Pikari0** [comment]
Same here, KDE Plasma on Manjaro, installed with pacman.

When I launch it from cli, this is the log I see, don't knwo if it's related:
> nextcloud.gui.application: Migrating old config from "/home/[username]/.local/share/Nextcloud" to "/home/[username]/.config/Nextcloud"
> nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/[username]/.local/share/Nextcloud" to "/home/[username]/.config/Nextcloud" )
> nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log", "NextcloudMossroy_sync.log")
> nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed

So I removed _/home/[username]/.local/share/Nextcloud_ for them, thinking it will help, but the client keeps recreating the folder and the .log :thinking:

**Comment by IPlayZed** [comment]
@Pikari0 this is not related to QT errors.

**Comment by toxpal** [comment]
Bug seems to be fixed in v3.13.3 (KDE Plasma 6)

**Comment by JYPDWhite** [comment]
Can approve. Bug fixed in v3.13.3 with KDE Plasma on Wayland.

**Comment by drp4positive** [comment]
I have the same issue. Ubuntu 24.04. LTS, Nextclopud Client 4.0.1. daily. WHat can i do to solve this?

**Comment by drp4positive** [comment]
> I have the same issue. Ubuntu 24.04. LTS, Nextclopud Client 4.0.1. daily. WHat can i do to solve this?

Updated to the same version. It working now.
