### ISSUE TITLE
Provide ability to edit Nextcloud instance URL without having to remove the account

### ISSUE THREAD

**Issue by js-d-coder** [nextcloud/desktop#636]
I am on Ubuntu 16.04 using `nextcloud-client` version `2.3.3-20180415.190957~xenial1`.  
I have my Nextcloud instance on my raspberry pi. I use it on different networks, consequentially, the IP address of raspberry pi changes, in such case I have to remove the account and add again just to change IP address I have added in Nextcloud client software.  
It would be great if I could just edit the URL that points to Nextcloud instance, from Nextcloud client settings.  
Thanks!

**Comment by GoetheG** [comment]
@js-d-coder Have the same issue here too. If there’s is a reason for just changing the link, I have to follow your steps in order to set Nextcloud right. Hope this’ll change in Nextcloud 14.

**Comment by camilasan** [comment]
Sorry, this was already discussed at https://github.com/nextcloud/desktop/issues/477.

**Comment by js-d-coder** [comment]
There is a workaround this issue. You can set the url something `http://raspberry` instead of any IP. Then point the `raspberry` to the IP, which can be set/edit using DNS Changer on Android or editing `/etc/hosts` on Linux... Enjoy. Now I don't have problem accessing my raspberry from android or desktop even if I move onto different network.
