### ISSUE TITLE
[Bug]: Issue with sharing VM share from host (which is onedrive dir)

### ISSUE THREAD

**Issue by HumanG33k** [nextcloud/desktop#6367]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I currently can't synchronise some share directories. 
I suspect file system type issue. 

### Steps to reproduce

1My use case is quite complex : 
- I currently have a windows host 
- OneDrive is setup for a directory : myOneDrive
- I share that dir (myOneDrive) to a virtualbox mount (myLinuxDir) for a Linux vm 
- I try to sync that directory (myOneDrive)

### Expected behavior

I uspect all file are well sync with my server

### Which files are affected by this bug

all files in the dir and the dir 

### Operating system

Linux

### Which version of the operating system you are running.

parrot last stable version 

### Package

Distro package manager

### Nextcloud Server version

26

### Nextcloud Desktop Client version

3.7.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> I currently can't synchronise some share directories.
> I suspect file system type issue.

This isn't a support channel. If you need support troubleshooting this, try:

Nextcloud Help Forum https://help.nextcloud.com or 
https://nextcloud.com/enterprise

> I share that dir (myOneDrive) to a virtualbox mount (myLinuxDir) for a Linux vm

When you post on the Help Forum, make sure to include more details about how this is mounted within Nextcloud Server and also whether it is accessible via the Web UI.
