### ISSUE TITLE
[Bug]: Error when uploading files larger than 10MB when using a shared folder in S3 primary Storage again x3

### ISSUE THREAD

**Issue by wmeneses** [nextcloud/desktop#6399]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Uploading files larger than 10MB in shared folders with s3 compatible

This error appears again forcing me to acquire a commercial webdav client and abandon this product definitively, I can not upload files larger than 10MB in shared folders when my primary storage is s3, if I try to upload a file to an external drive where I have shared a folder with XFS format it works fine.

I have tried with the latest client version
...

### Steps to reproduce

1. I copy the file to a folder that has been shared with me, the folder is part of my primary storage.
2. The client returns the error "Uploadpartycopy is not implemented for multipart uploads".
3. If I copy this file outside the shared folder, it copies correctly.
I have tried adding 'useMultipartCopy' => false, in the configuration but the problem persists.
...

### Expected behavior

That it works every day more than 1000 files are uploaded and it is complicated when this happen
...

### Which files are affected by this bug

files with 10MB

### Operating system

Windows

### Which version of the operating system you are running.

windows 11

### Package

Official SNAP package

### Nextcloud Server version

28.0.1

### Nextcloud Desktop Client version

3.11.1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
<Message>A header or query you provided requeste (truncated...)\n NotImplemented (client): A header or query you provided requested a function that is not implemented. - <?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Message><Details>UploadPartCopy is not implemented for multipart uploads.</Details></Error>\n- Part 9: Error executing \"UploadPartCopy\" on \"https://server-nextcloud.storage.googleapis.com/urn%3Aoid%3A88233742?partNumber=9&uploadId=ABPnzm7EZ1bO_u5wrAI7Xdap89yD8icLAgzTbjPal72d_4aleRSRuxs-HZfdVB-SAmxqb1U\"; AWS HTTP error: Client error: `PUT https://server-nextcloud.storage.googleapis.com/urn%3Aoid%3A88233742?partNumber=9&uploadId=ABPnzm7EZ1bO_u5wrAI7Xdap89yD8icLAgzTbjPal72d_4aleRSRuxs-HZfdVB-SAmxqb1U` resulted in a `400 Bad Request` response:\n<?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requeste (truncated...)\n NotImplemented (client): A header or query you provided requested a function that is not implemented. - <?xml version='1.0' encoding='UTF-8'?><Error><Code>NotImplemented</Code><Message>A header or query you provided requested a function that is not implemented.</Message><Details>UploadPartCopy is not implemented for multipart uploads.</Details></Error>\n"}}
```

### Additional info

I bought a webdav client and it works perfectly, but I don't expect to buy more than 1000 licenses. 

![next](https://github.com/nextcloud/desktop/assets/5956910/7b9f2e50-66ef-4818-8250-f1b6ce1affdb)

**Comment by wmeneses** [comment]
I have reverted to version 3.9.4 and it works correctly.

**Comment by mgallien** [comment]
@wmeneses the error you see is being reported by your server
this is because newer releases of the client will try new APIs from server to upload to s3 object storage without intermediate copy within the server
To further analyze this issue, I will need a debug archive from you (and may also need more info from the configuration of your server (at least, the version of your server is going to be needed).

**Comment by joshtrichards** [comment]
To my knowledge GCS only supports Multipart Upload, but not Multipart Copy. Other S3 platforms don't necessarily have the same problem so this is Google/GCS not being fully compatible with AWS S3.

>  I have tried adding 'useMultipartCopy' => false, in the configuration but the problem persists.
> 28.0.1

That parameter is in >=v28.0.2

**Comment by joshtrichards** [comment]
Closing due to no follow-up received + see last two comments. They should be helpful. I don't believe there is a bug of any sort in the client that has anything to do with this. Don't hesitate to reach out here if you have evidence otherwise.

If still stick, I suggest checking in at the help forum - https://help.nextcloud.com.
