### ISSUE TITLE
i18n: Need context, sentence needs improvement

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#6408]
https://github.com/nextcloud/desktop/blob/b0183cef6b70a8aba39ff022271c98ae0ec82cd6/src/libsync/updatee2eefolderusersmetadatajob.cpp#L121

folder user -> user folder?

Please improve grammar

**Comment by mgallien** [comment]
@rakekniven I will see internally
The `user` here is an user having access to the folder that is a shared folder with end-to-end encryption.
Does this may work for you:
"Could not add or remove user %1 to access folder %2"
