### ISSUE TITLE
[Bug]: Since 3.11.0, empty Info field when built WITHOUT Updater

### ISSUE THREAD

**Issue by squid-f** [nextcloud/desktop#6413]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On the Settings section, at the bottom, there is an Info section providing, for instance, the client version.
Since 3.11.0, this section contains no info at all when Nextcloud Desktop is built without the updater (-DBUILD_UPDATER=False). It is not fixed with 3.11.1
If built with the Updater, all info are here, plus the ability to check for update.

With 3.10.4, I confirm the info on version is displayed
![nc-desktop 3 10 4 wo-updater](https://github.com/nextcloud/desktop/assets/11743181/0ffe6dc5-76b2-40da-9652-e33ccc410aa3)

3.11.1 without Updater
![nc-desktop 3 11 1 wo-updater](https://github.com/nextcloud/desktop/assets/11743181/10a712a3-787a-4c57-af44-358fd5525f1a)

3.11.1 with Updater
![nc-desktop 3 11 1 w-updater](https://github.com/nextcloud/desktop/assets/11743181/b5dbd317-c444-45f9-91c6-1679d6480925)

### Steps to reproduce

1. Build from source without the updater (-DBUILD_UPDATER=False)
2. Launch Nextcloud Desktop and do the basic settings
3. Go to the Settings window and look at the Info section at the bottom

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
Nextcloud Desktop Version information is handy and what would be the reason not to display it any more, even if automatic update is not set?

### Which files are affected by this bug

n/a

### Operating system

Linux

### Which version of the operating system you are running.

Mageia 9 x86_64 Plasma

### Package

Distro package manager

### Nextcloud Server version

27.1.6

### Nextcloud Desktop Client version

3.11.1

### Is this bug present after an update or on a fresh install?

Either way, when going for 3.11.x

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
My best guess is #6150 which merged About+Updates in the UI. The `BUILD_UPDATER` stuff from #1847 will have to be adapted by someone.

**Comment by squid-f** [comment]
Hi. Solved with 3.12.2, apparently.
