### ISSUE TITLE
[Bug]: No more release information displayed in the settings panel since about 3.10 (at least under GNU/Linux)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/desktop#6449]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Everything is in the screenshot
...
![2024-02-15_19-05](https://github.com/nextcloud/desktop/assets/33763786/29ef9ea1-c917-4650-b20e-744b72669bcd)

### Steps to reproduce

Everything is in the screenshot

### Expected behavior

Information should appear in this block.

### Which files are affected by this bug

None

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04 (Gnome), Linux Mint 21.3 (Cinnamon)

### Package

Distro package manager

### Nextcloud Server version

27.1.5

### Nextcloud Desktop Client version

3.12.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Can be provided if necessary.
```

### Additional info

Can be provided if necessary.

**Comment by marcotrevisan** [comment]
Hi, can this be covered by https://github.com/nextcloud/desktop/pull/6459 ?

**Comment by Jerome-Herbinet** [comment]
> Hi, can this be covered by #6459 ?

@marcotrevisan thanks for this ; I just tested the generated appimage and the information appear again ; so the 3.12.1 release will be the good one 🙂

**Comment by allexzander** [comment]
thanks @marcotrevisan and others, yes, it is merged to 3.12 and will be released in 3.12.1
