### ISSUE TITLE
[Bug]: No flatpak of Nextcloud client since version 3.11.0

### ISSUE THREAD

**Issue by w1n5l0w** [nextcloud/desktop#6469]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Since version 3.11.0 there hasn't been an flatpak of the current versions of Nextcloud Desktop Client in flathub: https://flathub.org/apps/com.nextcloud.desktopclient.nextcloud

Neither for version 3.11.1, nor for version 3.12.0

### Steps to reproduce

Install/update flatpak of Nextcloud Desktop Client.

### Expected behavior

There is a flatpak for each new  version of Nextcloud Desktop Client.

### Which files are affected by this bug

all

### Operating system

Linux

### Which version of the operating system you are running.

Doesn't matter

### Package

Other

### Nextcloud Server version

Doesn't matter

### Nextcloud Desktop Client version

3.11.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
See https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/issues

We don't handle those releases here.
