### ISSUE TITLE
Nextcloud Desktop dailys have not been build

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/desktop#647]
Hey Folks,

Nextcloud Desktop dailys have not build properly last day(s) ...
  | Linux/ | 2018-09-09 22:45 | - |  
  | Mac/ | 2018-06-20 12:07 | - |  
  | Windows/ | 2018-09-05 01:12 | - |  

Thanks for fixing! :-)

**Comment by camilasan** [comment]
Thanks for the head up. Mac had a known issue but it is fixed now and there is a build for today. Linux looks fine. I am checking what is up on Windows right now.

**Comment by nextgen-networks** [comment]
@camilasan Thanks for your fast feedback and ongoing efforts to provide us users an great tool!

**Comment by camilasan** [comment]
This is what breaks on Windows: https://github.com/nextcloud/desktop/pull/594

**Comment by camilasan** [comment]
Problem solved.
https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61359-daily-20180911.exe
