### ISSUE TITLE
[Bug]: Outdated notifications keep showing in the tray menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#6474]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Outdated notifications that I already read in the web interface some days ago are still shown in the desktop client. There were more before above as well before I cleaned up a bit.
![image](https://github.com/nextcloud/desktop/assets/925062/3b049e6a-d519-4a8e-abcd-4e1ae30af9a3)

### Steps to reproduce

1. Be on vacation for a week
2. Go through e.g. your Talk notifications in the web interface
3. Later notice a lot of the notifications are still there in the desktop tray menu

### Expected behavior

When notifications are dismissed in the web interface (or other apps) or its relevant conversations are read elsewhere, the notifications should also vanish in the desktop client.

### Which files are affected by this bug

Not about a file, but the tray menu

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04.4 LTS

### Package

Appimage

### Nextcloud Server version

Current on cloud.nc

### Nextcloud Desktop Client version

3.12.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tobiasKaminsky** [comment]
@camilasan can you check this? :)
