### ISSUE TITLE
i18n: Need context for "Evict materialised files"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#6477]
https://github.com/nextcloud/desktop/blob/094947bfb150faaa07a963f164e4ce8e5ba58e9a/src/gui/macOS/ui/FileProviderEvictionDialog.qml#L31

What does that mean?
Please enlight us and add a comment to source file.

**Comment by claucambra** [comment]
On macOS virtual files, the user can choose to manually remove locally-downloaded copies of virtual files. Under the macOS File Provider nomenclature these locally-downloaded copies are "materialised" copies, and the removal of the "materialised" copies can be "evicted"
