### ISSUE TITLE
Display problem once an error occurs

### ISSUE THREAD

**Issue by GekoCH** [nextcloud/desktop#648]
Once an error occurs during synch I can't read the remeining snych time and files count anymore since thos lines are written in white as well:
Here you can't really read the text below the bar
![image](https://user-images.githubusercontent.com/3285638/45276934-6a503b00-b4c5-11e8-9179-d4ef55952400.png)

However if I photoshop the image t looks like this
![image](https://user-images.githubusercontent.com/3285638/45276989-b3a08a80-b4c5-11e8-957d-9d3a779117e8.png)

Now I can read the remaining time etc. 
So it is definitely a styling problem once an error occurs

**Comment by camilasan** [comment]
Hi! Which version of the Desktop client and on which OS?

**Comment by GekoCH** [comment]
the used version is: 2.3.3

**Comment by tobiasKaminsky** [comment]
This happened also on 2.5.0 for me:
![image](https://user-images.githubusercontent.com/5836855/48946524-4fbb2900-ef2e-11e8-8a0c-2a5382691e9d.png)

The text is now white on white, but when you hover on it, the background becomes grey and you can see the text again.

**Comment by er-vin** [comment]
Looks like this should be solved already.

**Comment by misch7** [comment]
Solved in #1695 :)
