### ISSUE TITLE
[Bug]: Cursor gets scaled in size when it hovers over the app

### ISSUE THREAD

**Issue by K4LCIFER** [nextcloud/desktop#6516]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When I hover my mouse over the Nextcloud Desktop opp, it gets scaled up ~5 times its normal size.

Here's what the mouse normally looks like:

![image](https://github.com/nextcloud/desktop/assets/7829231/5003170b-5803-4840-8a5b-2549ad578a85)

Here's what it looks like when I hover over the app:

![image](https://github.com/nextcloud/desktop/assets/7829231/b96c52d7-e007-4225-b804-3bce0d68e9fa)

### Steps to reproduce

1. Open Nextcloud Desktop
2. Hover cursor over the app
3. Observe that its enlarged

### Expected behavior

I would expect my cursor to remain the same size when I hover it over the app.

### Which files are affected by this bug

N/A

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux, Kernel v6.7.8-arch1-1, KDE Plasma v6.0.1, Qt v6.6.2

### Package

Other

### Nextcloud Server version

N/A

### Nextcloud Desktop Client version

3.12.0 (Flatpak)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
N/A
```

### Additional info

In case this is an upstream bug, I submitted [this bug report](https://bugs.kde.org/show_bug.cgi?id=482805) to KDE as well.

**Comment by SadmL** [comment]
My cursor turns black

Arch Linux, Kernel v6.8.8-arch1-1, KDE Plasma v6.0.4, Qt v6.7.0

nextcloud-client 2:3.13.0-2 (Arch repository) 
![03-05-24_08-42](https://github.com/nextcloud/desktop/assets/30765190/0a9733fe-96bc-4099-b59b-324777c8f7ca)
![03-05-24_08-42-1](https://github.com/nextcloud/desktop/assets/30765190/57e48681-7b08-467d-9902-a71b82c74f67)

**Comment by K4LCIFER** [comment]
[This is a KDE bug](https://bugs.kde.org/show_bug.cgi?id=482805).

**Comment by K4LCIFER** [comment]
[This is a KDE bug](https://bugs.kde.org/show_bug.cgi?id=482805).
