### ISSUE TITLE
[Bug]: External Drive sync freezes Nextcloud Client and Windows Explorer

### ISSUE THREAD

**Issue by coolkau** [nextcloud/desktop#6527]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud deskop freezes and blocks of windows explorer when syncing with external drives.
...

### Steps to reproduce

1. Set up sync located on a network drive 
2. When client is starting to sync on that external drive the desktop client freezes. Also new windows explorer windows are not opening, and any windows explorer network access is blocked. Windows explorer works immediately again after killing the nextcloud client. 

...

### Expected behavior

Not frozen app
...

### Which files are affected by this bug

01-01 Andersens Märchen - Die Nachtigall.flac

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 and 11

### Package

Appimage

### Nextcloud Server version

Dont know, external supplier

### Nextcloud Desktop Client version

3.4 to 3.12 (tried multiple versions)

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

- This is a problem which persists with multiple External Drives (SMB on Rasperri PI, Fritzbox Share)
- Persists also on Win 10 and Win 11 on all my computers
- Problem was occasionally occuring for quite a while, i.e. the app temporarily froze. However, only recently this is a persistent issue blocking off any network drive useage
- Client Logs did not  show any error, just stopped logging during filesync on nas drive -- happy to provide logs on any log-level needed. Though it is hard to get the logs before the app freezes.  
- Seems to be related to recent windows updates, as an "long time not used computer" seemed to work without freezing until the update and restart. (cannot double check as as now the computer is up-to-date)

**Comment by starmanager01** [comment]
Hi, did you check the defragmentation on your external drives? I had a simular problem with the performance from a external Drive and figure out the fragmentation is way to high.

**Comment by joshtrichards** [comment]
> Set up sync located on a network drive

This seems to be more a configuration/local environment matter. I would not recommend using a sync client in this way (syncing to local storage that isn't really local). You're creating layers and layers of potential problems. 

I suggest posting over at the help forum - https://help.nextcloud.com - to troubleshoot things a bit there and maybe discuss some alternative approaches for your use case.

**Comment by coolkau** [comment]
I guess for Laptops and Mobile devices with small local hard drives NAS drives are the obvious, simple choice not have an external harddrive.  

The only alternative really is to run a Nextcloud client on the NAS which has its own issues such as that the Linux client does not resume after an upload error. So you have to log in multiple times a day to check if the sync is stalled.

It is a shame that this kind of crucial thing that worked for years is broken now and wont be fixed. But I also appreciate that private use folks like me dont pay the bills and you need to focus on business customers who have other means to go around issues like this and have other problems.
