### ISSUE TITLE
Error while setting the maximum protocol version

### ISSUE THREAD

**Issue by freezed** [nextcloud/desktop#653]
## Details

Desktop client could not connect to server after an OS update :
> Error while setting the maximum protocol version

Access via web browser is OK

Client :
* nextcloud-client v 2.3.3 (via `http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0/`)
* Debian testing (Buster)

Server : 
* Nextcloud server v 12.0.4

## last APT log
```
Start-Date: 2018-09-10  09:17:09
Commandline: apt upgrade
Upgrade: libsoup-gnome2.4-1:amd64 (2.62.2-2, 2.64.0-2), iso-codes:amd64 (3.79-1, 4.1-1), libcpanel-json-xs-perl:amd64 (4.05-1, 4.06-1), dconf-editor:amd64 (3.28.0-1, 3.30.0-1), qt5-gtk-platformtheme:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libnumbertext-data:amd64 (1.0-2, 1.0-3), libqt5dbus5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libqt5sql5-sqlite:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), gimp-data:amd64 (2.10.6-2, 2.10.6-3), libqt5widgets5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libnm0:amd64 (1.12.2-2, 1.12.2-3), network-manager:amd64 (1.12.2-2, 1.12.2-3), python3-httplib2:amd64 (0.9.2+dfsg-1, 0.11.3-1), libsoup2.4-1:amd64 (2.62.2-2, 2.64.0-2), libqt5xml5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libqt5printsupport5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libqt5concurrent5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), gimp:amd64 (2.10.6-2, 2.10.6-3), libnumbertext-1.0-0:amd64 (1.0-2, 1.0-3), libqt5gui5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libnautilus-extension1a:amd64 (3.26.3.1-1, 3.30.0-1), libqt5core5a:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libgimp2.0:amd64 (2.10.6-2, 2.10.6-3), libqt5network5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7), libqt5sql5:amd64 (5.11.1+dfsg-6, 5.11.1+dfsg-7)
```

I assume that one of those package is related to the issue.

## Steps to reproduce

State is permanent

**Comment by hdino** [comment]
I can confirm this.
Client:
- Nextcloud client v 2.5.0 (git).
- Debian testing (Buster)

Server:
- Nextcloud server v 14.0.0

**Comment by hdino** [comment]
The package libqt5network5 v 5.11.1+dfsg-7 is broken in testing. If you upgrade to [5.11.1+dfsg-8](https://packages.debian.org/sid/libqt5network5) the client works again.

**Comment by freezed** [comment]
Try firstly to downgrade the package as mentioned in the [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907774#15), but afraid by breaking dependencies, I upgrade it and everything back in order. Thanks.
For memories & newbies, here the steps :

1. Adding _debian/stretch_ source to `apt/source.list`
2. `sudo apt update`
3. `sudo apt-get install libqt5network5=5.11.1+dfsg-8`
4. removing _debian/stretch_ source to `apt/source.list`
5. `sudo apt update`
6. `sudo apt-get install nextcloud-client`
