### ISSUE TITLE
Update mimetype icons

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/desktop#6564]
based on https://github.com/nextcloud/files-clients/issues/46#issuecomment-1997473329 and https://github.com/nextcloud/server/issues/44340

* Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A)
* Document: [description](https://fonts.google.com/icons?selected=Material%20Icons%3Adescription%3A) in `#49abea`
* Spreadsheet: [file-table-box](https://pictogrammers.com/library/mdi/icon/file-table-box/) in `#9abd4e`
* Presentation: [file-presentation-box](https://pictogrammers.com/library/mdi/icon/file-presentation-box/) in `#f0965f`
* Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#b39114`
* PDF: [picture-as-pdf](https://fonts.google.com/icons?selected=Material+Icons+Round:picture_as_pdf:&icon.query=pdf)
* Image: [image](https://fonts.google.com/icons?selected=Material+Icons+Round:image:&icon.query=image)
* Video: [movie](https://fonts.google.com/icons?selected=Material+Icons:movie:&icon.query=video)

**Comment by tobiasKaminsky** [comment]
@allexzander @claucambra do we use them somewhere?
I assume that we use OS default ones within Windows Explorer / Finder.
And in activity stream we receive the icons from server, right?

**Comment by allexzander** [comment]
@tobiasKaminsky

We are receiving from the server for activities (https://github.com/nextcloud/desktop/blob/master/src/gui/tray/activitydata.cpp#L184) and for VFS we also receive from the server via file preview, but yes, in the Explorer/Finder we use OS default, and I am not sure if it will be possible to replace OS default ones with custom ones (lots of work but the investigation is needed first), yet, on Windows, I assume this will break most user's expectations if Nextcloud will totally replace the default icons that are displayed by other software.

I would be glad to have a concrete example with a screenshot of where we need to replace them in the desktop client, for me to be able to have a better idea ad a more precise answer.

**Comment by AndyScherzinger** [comment]
To be closed with "unplanned" than because there is no case to implement them except for the scenarios where this already happens being shipped by the server 👍
