### ISSUE TITLE
So many update ?

### ISSUE THREAD

**Issue by tutle** [nextcloud/desktop#6569]
Hello, it's fine to have a so active software maintenance but update of nextcloud PC client are proposed very often (sometimes 2 in one month) and it's very intrusive because you have to restart the computer after update.
Thanks anyway for this amazing software I can't leave without.

**Comment by joshtrichards** [comment]
You can disable automatic updates if you have some other preferred approach to making sure you stay reasonably up-to-date: See the docs: https://docs.nextcloud.com/desktop/latest/

**Comment by AndyXheli** [comment]
@tutle how can you call this an enhancement? You should be grateful Nextcloud is updating their software to stay up with technology and security and implant new features. If you don't like the updates turn them off and install manually or updates your client via MDM.

**Comment by joshtrichards** [comment]
Not really sure there's much else that is actionable to do here:

- turn off updates if desired
- optimizing how/when restarts are required is already being tracked elsewhere - e.g. #5369 

I'll close this issue out to avoid duplication, but I encourage you follow that issue, @tutle. If I've misunderstood or you disagree, don't hesitate to reply so we can re-open.

**Comment by courtesysoft** [comment]
This is a huge problem that caused me to not adopt nextcloud. All other things were great.
It has the most obnoxious updating behavior of any windows program i've seen to date in 25 years.

Users of the client software should not have to go through a multi process step every week.
