### ISSUE TITLE
[Bug]: system tray cut off when changing displays

### ISSUE THREAD

**Issue by zises** [nextcloud/desktop#6572]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

the system tray menu items are cut off when changing displays.
...

### Steps to reproduce

On a mac,
1. Launch Nextcloud with the system tray visible.
2. Set an external monitor to the primary screen.
3. Remove external monitor.
4. Tray dialogue and functions are cut off and no longer visible.

### Expected behavior

The full menu of the system tray should be available.
...

### Which files are affected by this bug

desktop experience

### Operating system

Mac OS

### Which version of the operating system you are running.

14.4

### Package

Appimage

### Nextcloud Server version

tab.digital hosted

### Nextcloud Desktop Client version

3.12

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jbfriedrich** [comment]
Even with only one display I have the issue that that the menu either appears in the middle of the screen and is not clickable or is otherwise askew and cannot be clicked. Will file another issue soon, but I think this is a bigger issue with macOS.

**Comment by jospoortvliet** [comment]
it's a known issue which will only be fixed once the client moves to Qt 6. This is scheduled to happen in one of the upcoming releases - I also hope it'll be sooner rather than later. With some luck before summer. But there's an issue and tracking already so if you don't mind I'll close this one - this task is definitely tracked.
