### ISSUE TITLE
[Bug]: Windows deskto client upload and download speed is much slower than browser

### ISSUE THREAD

**Issue by tgly307** [nextcloud/desktop#6615]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The share dialog is looking incomplete.
...
I am using the 3.12.3 version of the client and the 28.0.4 version of the server. There is no speed limit setting on the client, but when uploading and downloading, the speed is significantly slower than the browser. My local area network speed is 1G, and the browser transmission can basically reach this speed, but the client's speed does not exceed 50m.

### Steps to reproduce

1. install client and server
2. connect client and server
3. copy some large files(>100m) to nextcloud folder
4. when start auto upload, the speed is slow than web.
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...
client upload speed is equal with web

### Which files are affected by this bug

a mp4 file more than 100m

### Operating system

Windows

### Which version of the operating system you are running.

Win11

### Package

Other

### Nextcloud Server version

28.0.4

### Nextcloud Desktop Client version

3.12.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tgly307** [comment]
I also try server 27.1.1 and client 3.12.3, the same situation

**Comment by PhilippSchlesinger** [comment]
@tgly307 It is maybe worth taking a look at https://github.com/nextcloud/desktop/issues/4918 and especially https://github.com/nextcloud/desktop/issues/4918#issuecomment-1507960102.

**Comment by tgly307** [comment]
> @tgly307 It is maybe worth taking a look at #4918 and especially [#4918 (comment)](https://github.com/nextcloud/desktop/issues/4918#issuecomment-1507960102).

oh thx very much, this is indeed this problem

**Comment by tgly307** [comment]
same as #4918

**Comment by tgly307** [comment]
same as #4918
