### ISSUE TITLE
VFS - Auto-delete local files after some time or quota

### ISSUE THREAD

**Issue by tomdereub** [nextcloud/desktop#6616]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
Using VFS, nextcloud will sync every file accessed at least one time. So the space taken on the disk by the cache will grow up.
The only way for now to reduce the cache size is to manually "free up local space". It can be done only on synced files or folders, or at the sync level on the whole synced folder. And there is no discrimination between files that have just been accessed, and folders that have been manually set to "always keep offline" (toujours rendre disponible localement), I can't free up "automatic cache" but keep synced the folders manually synced.

My feature request :
- be able to set a "quota" for the cache size, for example 50 Go, and when the quota is reached, nextcloud frees up cache starting by the files that have been accessed for the longest time.
- do not free up the files and folders that have been manually set to "always keep offline". Maybe this files must not be counted in the cache quota ?

**Comment by PhilippSchlesinger** [comment]
This is a duplicate of https://github.com/nextcloud/desktop/issues/4336

**Comment by tomdereub** [comment]
That's right sorry, I had not found this issue.
