### ISSUE TITLE
[Bug]: two empty file break the entire sync process

### ISSUE THREAD

**Issue by gixita** [nextcloud/desktop#6659]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When creating 2 new EMPTY files, any changes in any files are not sync (the sync process is fully broken for that folder)
With version 3.4.2 Using virtual files plugin: suffix ubuntu-6.5.0-28-generic

### Steps to reproduce

touch file1.md
touch file2.md
echo "content" > file3.md

### Expected behavior

file3.md should be synced with the content "content"

### Which files are affected by this bug

*

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 22.04

### Package

Distro package manager

### Nextcloud Server version

27.1.8

### Nextcloud Desktop Client version

3.4.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
No server logs regarding the issue
```

**Comment by PhilippSchlesinger** [comment]
@gixita The client version you use is more than three years old, the recent version is 3.12.3.

**Comment by gixita** [comment]
Thank you my bad. Tested with the new version and the bug is not there anymore.
Sorry for that
