### ISSUE TITLE
Could NOT find INOTIFY

### ISSUE THREAD

**Issue by hdino** [nextcloud/desktop#669]
### Expected behaviour
Compilation without errors.

### Actual behaviour
CMake shows the error "Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR)"

### Remark
As far as I know, inotify has become part of libc (cf. [Debian package search](https://packages.debian.org/search?searchon=contents&keywords=sys%2Finotify.h&mode=path&suite=stable&arch=any)) and therefore doesn"t need to be linked against anymore. However, [FindINotify.cmake](https://github.com/nextcloud/desktop/blob/d0b6a611f22158da7ad08578555b3cf4ee1e25c6/cmake/modules/FindINotify.cmake#L16) shipped with the desktop client still tries to find the lib and thus fails.

(Also see [this old issue](https://github.com/nextcloud/client_theming/issues/25))

**Comment by camilasan** [comment]
It has been done.
