### ISSUE TITLE
Client doesn't use SAML/SSO setting 

### ISSUE THREAD

**Issue by maghog** [nextcloud/desktop#671]
The client is using SAML authentication even if the setting "Use SAML auth for Nextcloud desktop clients" is disabled.

<img width="523" alt="saml" src="https://user-images.githubusercontent.com/1148924/45425399-87d5fe00-b699-11e8-8c19-f422705f783a.png">

Client version: Nextcloud-2.5.0.61360-daily-20180912.exe
Operating system: Windows 10
OS language: Swedish

### Server configuration
Operating system: Ubuntu 16.04 LTS
Web server: Apache
Database: MySQL
PHP version: 7.0.30
Nextcloud version: 14

**Comment by maghog** [comment]
Same behavior for RC1.

**Comment by rullzer** [comment]
Ah that is a legacy setting on the user_saml app.
In the new client you just authenitcate in the webview and all is taken care of in the background

**Comment by claell** [comment]
@maghog @rullzer what is the status of this issue?

**Comment by mgallien** [comment]
> @maghog @rullzer what is the status of this issue?

This is a server issue and there is nothing we can do on client side.
Let's close it and feel free to bring that to the server issues tracker. You can probably link to this issue to help giving context.
