### ISSUE TITLE
Downgrading from daily release to stable deletes config

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/desktop#673]
Windows 7

I started to use 2.5.0.61353-daily-20180905 in hopes of avoiding a bug, but then I was advised against it for stability reasons and downgraded to 2.3.3.1. I uninstalled the newer version as the installer recommended. In the process I lost my server settings and folder sync settings. The server was set in an earlier install of  2.3.3.1, before I tried the daily. The folders were set in the daily.

I didn't lose anything when upgrading, so I thought it won't be a problem when going backwards.

**Comment by zippytiff** [comment]
I also saw this....

but strangly when I then installed the 2.5.x client, everything came back.... I guess 2.5.x is using a new location for settings?

ZT

**Comment by leafcutterant** [comment]
Good to know.

The client should behave with an upgrade in mind. See my proposal: #962

**Comment by mgallien** [comment]
Downgrading is not supported and I do not expect that we would integrate fixes to support that.
Sorry, I prefer to close the issue.
