### ISSUE TITLE
[Bug]: Segmentation Fault with new VFS on MacOS

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#6730]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Tried v3.13.0 from https://github.com/nextcloud/desktop/discussions/6656 and after installation it does not start and gives `Segmentation fault: 11` after start

### Steps to reproduce

1. Install https://github.com/nextcloud-releases/desktop/releases/download/v3.13.0/Nextcloud-3.13.0-macOS-vfs.pkg
2. Start app
3. Seg fault is shown at console

### Expected behavior

App should work like always

### Which files are affected by this bug

nextcloud.app

### Operating system

Mac OS

### Which version of the operating system you are running.

13.6.6

### Package

Appimage

### Nextcloud Server version

29.0.0

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Javihache** [comment]
Same problem here. I uninstalled Nextcloud, cause the sidebar icon is just a folder and thought I could solve that by reinstalling. Now Nextcloud 3.13 is not starting at all.

**Comment by Javihache** [comment]
I solved the issue removing all plists and other files in ~/Library, then installing 3.13 standard and finally installing 3.13 with VFS support. However the icon in the Finder Sidebar under Locations still shows a standard folder icon.

**Comment by claucambra** [comment]
> I solved the issue removing all plists and other files in ~/Library, then installing 3.13 standard and finally installing 3.13 with VFS support. However the icon in the Finder Sidebar under Locations still shows a standard folder icon.

We cannot fix this, and it is the reason we have both a standard files client and a virtual files client on macOS; we have to pick between either providing the virtual files via File Provider APIs or being able to use the old Finder Sync API to decorate standard sync files and folders
