### ISSUE TITLE
[Bug]: On SUSE Linux, Virtual File support only works with AppImage, not the repo install

### ISSUE THREAD

**Issue by woiwoiwoiwoi** [nextcloud/desktop#6737]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I recently had to switch from Debian Unstable to OpenSUSE Tumbleweed. Virtual File support worked perfectly for the past year or so on Debian, but on SUSE the Nextcloud client crashes if it is turned on.

This applies to the version installed from the OpenSUSE Tumbleweed repository (on Debian, I also used the repository version). When using the AppImage of the Nextcloud Desktop client, virtual file support seems to be working fine.

However, I prefer the repo version since it comes with file explorer integration (and looks slightly better). To get file explorer integration with the AppImage, `nautilus-extension-nextcloud` needs to be installed, which then installs `nextcloud-desktop` anyway. So the client ends up being installed twice on the same system and the repo version needs to be removed from startup applications. This all feels a little hacky.

### Steps to reproduce

1. install Nextcloud Desktop client on SUSE: `sudo zypper install nextcloud-desktop`
2. launch  client
3. quit client
4. add `showExperimentalOptions=true` to `$HOME/.config/Nextcloud/nextcloud.cfg`
5. launch client
6. add a regular sync connection, since there is no option to enable virtual file support in this window (it used to be there on Debian)
7. in client settings, click on three dots next to the just created sync connection and click on `Enable virtual file support`
8. client crashes
9. after client relaunch, virtual file support is still not enabled

### Expected behavior

Client should not crash and virtual file support should stay enabled.

### Which files are affected by this bug

virtual files

### Operating system

Linux

### Which version of the operating system you are running.

OpenSUSE Tumbleweed

### Package

Distro package manager

### Nextcloud Server version

28.0.5

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @woiwoiwoiwoi, we do not package the SUSE package -- we officially recommend using the AppImage.  I would recommend you open an issue with the SUSE packagers

**Comment by woiwoiwoiwoi** [comment]
Hi @claucambra and thank you for responding. I am using the AppImage at the moment, so that's fine. But am I correct in understanding that file explorer integration does not come with the AppImage? Because that is my only real issue with the AppImage: that I have to still install `nextcloud-desktop` anyway (for file explorer integration) and then the application is installed twice AND the repo version needs to be removed from startup applications.
