### ISSUE TITLE
[Bug]: Read-Only permission after adding Downloads folder to Nextcloud-synchronisation

### ISSUE THREAD

**Issue by guckuck** [nextcloud/desktop#6741]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The problem happened on two different devices with Windows 10 and Window 11.

I added the Downloads-Folder as a seperated synchronisation-folder to the desktop client. After a while the downloads-folder was read only. It was not possible to add new files and folders. It was also not possible to change the persmission back to read/write (with and without admin privileges). Even after removing the folder from the desktop client (synchronisation) so folder was still read only.

I found this work-around to enable write-access again: https://answers.microsoft.com/en-us/windows/forum/all/unable-to-delete-folder-as-administrator-requires/ae5b6cf6-dae5-49b9-83db-1435d41749a9?page=2

```
Ok I found the answer:
First, rename the file so that it has an unknown extension
In the advanced permissions, change the owner to everyone
Then move the files to a folder you have full control of
Go back to permissions and set the owner as your account name
close the window
Go back to permissions and enable inheritance
you can then delete the file
Repeat for every file you wish to delete
```

The Downloads-Folder is a system folder. It was not a good idea to delete the folder.

Yesterday I had this problem on the Windows 10 device. After fixing the problem yesterday I tried it again and since than, the synchronisation works without any problems.

Today I tried it on the Windows 11 device with the same problem. I also added the Downloads-Folder to the synchronisation. After a while the same problem.

### Steps to reproduce

1. Add the downloads-folder (c:\users\name\Downloads) to the desktop-client as a new folder-syncronisation (root folder on the Nextcloud-Server)
2. The synchronisation starts synching without problems.
3. After a while I get the error message from Desktop Client that the folder is read only.

### Expected behavior

No changing persmissions to the folder.

### Which files are affected by this bug

Autoruns.zip

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10, Windows 11

### Package

Appimage

### Nextcloud Server version

28.0.5

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Madrich** [comment]
Shared (read-only) folders from an other NC user are syncronized but read-only too. After sync issues this files can not be deleted. need to go to Win secure mode and delete them in the console. Terrible.

**Comment by SofianeLasri** [comment]
I also have this problem with pictures and videos folders.

**Comment by epidemiaf1** [comment]
We had this issue as well in both Windows 10 and Windows 11 Pro machines. I'm not sure how we get to the point in which the folder changes to read only, but it is caused by an ACE in the folder permissions ACL explicitly denying access to all users in the computer for the user's profile path (./Documents, ./Desktop, etc.). Since the logged in user is also a member of the $COMPUTERNAME$\Users group, the deny ACE takes precedence over the other ACE that provides Full Control to the user's own profile. We synchronize the user's desktop, documents and pictures folder with the NextCloud Desktop Client. The fix is just to remove the conflicting ACE from the Advanced Permissions in the Security tab of the Folder Properties.

**Comment by Mysli0210** [comment]
I have this issue too, though only with one particular folder containing raw images nested in folders.

So nextcloud desktop client for windows sets computername\Users to deny write access under advanced permissions.

I did set up auditing on the folder, as i thought it to be malware trying to block me from my photos, but it turned out to be nextcloud.exe doing the deed.

**Comment by Christian-HW** [comment]
Similar issue on MacOS.

We use the virtual files with different folders for departments.
Some of these folders are set to read only, so we can fetch files, but not change them.

After updateing to 3.13.0 we got permission errors and the sync process would halt.

The issue seemed to be that we couldn't write the .nextcloud files anymore inside our read only folders.
The permission to write in these folders had been removed on file system level, if you gave back the write permissions it would work again until someone renamed or added new files/folders.

We downgraded the version to 3.12.5 and gave back the permissions via chmod to temporarily fix this issue.

I hope an answer here is okay, if not let me know and i open a new issue specific for mac.

**Comment by Gauss23** [comment]
+1 @Christian-HW , same issue here with folders which are shared from other users and have an automated retention policy. When files are removed automatically on the server the client is not able to remove the files from the client because the folder is read only. This was not the case with older client versions. Please fix. Thank you.

**Comment by CHECKERCE** [comment]
i also have this issue. after adding the pictures, documents, videos and music folders to sync with nextcloud i have no write access to any of these folders anymore. i gave everyone full permission but still the same.

after removing the folder-sync i still have no permission and cant add the folder to sync anymore because nextcloud also says i have no write permission

**Comment by slater0013** [comment]
A few users experimenting the same issue here :( NC28 / client 3.13 !

Desktop or Downloads folder read-only even after deleting the sync in nextcloud client.

GS

**Comment by shilin-da** [comment]
Sync stuck with errors whenever a new subfolder X with files created in a read-only share:
1. Client sync the folder X and makes it readonly (in a local filesystem).
2. Client fail to sync any files into X due to its readonly status.

`chmod --recursive u+w X` solves the problem for a particular folder. Unfortunately I had to downgrade to 3.12.3

**Comment by Angels-dev** [comment]
I had this issue too with my Documents folder and the same client version 3.13.0.

I solved it by removing the folder sync and following [this forum thread](https://answers.microsoft.com/en-us/windows/forum/all/permissions-seem-to-be-screwed-up/62b09370-af81-4cd4-be56-3b50b42c2c55) to repair the permissions : 
**(It will reset the permissions to inherit from the parent folder!)**

1. Press Windows + S key together to open Search.
2. Now type CMD and select Run as administrator.
3. Accept the UAC prompts.
4. Type the following command: `CD C:\Users\...` (Go to your user folder)
5. Then: `ICACLS Documents /T /Q /C /RESET` (Replace "Documents" with the folder whose permissions you want to reset.)
6. Restart the PC

I tried to re-add the folder sync but the same issue happened so I guess I will wait before using it again.

**Comment by Gamesprominer** [comment]
The weird thing is, i have the same issue like you Guys. But my Nextcloud Desktop Client works normally without issues.
For some reason it seems to have more permission than i myself

**Comment by Madrich** [comment]
This is still not fixed. In my opinion a major bug. I can not use nextcloud desktop client properly anymore. Looking for alternatives. Any ideas?

**Comment by Christian-HW** [comment]
Same on Mac OS.
Tried Updating and reinstalling.
Permission denied errors as soon as it starts to sync a read-only folder. The folder stays empty with no .nextcloud files.

**Comment by slater0013** [comment]
> This is still not fixed. In my opinion a major bug. I can not use nextcloud desktop client properly anymore. Looking for alternatives. Any ideas?

> Same on Mac OS. Tried Updating and reinstalling. Permission denied errors as soon as it starts to sync a read-only folder. The folder stays empty with no .nextcloud files.

Hello, updated clients to 3.13.2 ? It won't fix the broken folder permissions, I guess !

GS.

Any steps to reproduce the bug ?

**Comment by borekon** [comment]
The same happens to me. Freshly installed windows 10 and the last version of NC client available on their website.
The curious part is that it only happens with Documents folder.
This solution did the trick, but the folder went back to read nly again (or some kind of issue with permissions):
> 1. Press Windows + S key together to open Search.
> 2. Now type CMD and select Run as administrator.
> 3. Accept the UAC prompts.
> 4. Type the following command: `CD C:\Users\...` (Go to your user folder)
> 5. Then: `ICACLS Documents /T /Q /C /RESET` (Replace "Documents" with the folder whose permissions you want to reset.)

**Comment by git-kick** [comment]
I am facing the issue frequently and recurringly.
My workaround is to delete the "deny" entry in the folder > properties > security > extended dialog.

The strange thing is: I never had that issue until recently, when I migrated my Nextcloud server from Ubuntu-VM-Hansson to Windows-DockerDesktop-AiO - perhaps it may be a problem related to WSL? (still, I cannot imagine how it could affect the ACL on the client).

@everybody having the issue: did you also observe it with a server *not* running on Windows (and involving WSL)?

**Comment by borekon** [comment]
> I am facing the issue frequently and recurringly. My workaround is to delete the "deny" entry in the folder > properties > security > extended dialog.
> 
> The strange thing is: I never had that issue until recently, when I migrated my Nextcloud server from Ubuntu-VM-Hansson to Windows-DockerDesktop-AiO - perhaps it may be a problem related to WSL? (still, I cannot imagine how it could affect the ACL on the client).
> 
> [@everybody](https://github.com/everybody) having the issue: did you also observe it with a server _not_ running on Windows (and involving WSL)?

I've been using nextcloud server in a LXC container in proxmox for five years or so. Nextcloud clients on 3 machines with Windows (started in 7, upgraded to 10, also in freshly 10 and 11) and webdav in some linux machines. Never had this problem. The only difference is that the Windows 11 problematic client is in English language with english keyboard, but swiched it to Spanish with language pack from regional settings.

**Comment by git-kick** [comment]
Okay, thank you @borekon 
So my suspicion that it is a WSL (only) issue is wrong and I see no strong argument to move away from my DockerDesktop setup.

**Comment by borekon** [comment]
Closed....but fixed??

**Comment by SofianeLasri** [comment]
no it's not
