### ISSUE TITLE
Desktop Client 2.3.3.1 not working with SAML and multiple certs

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/desktop#676]
Environment
==========
Windows 10 as client, Desktop Client 2.3.3.1 for Windows, NC 14, SAML enabled.
Have multiple ADFS certs assigned to a user.

Problem Description
================
When there are multiple certs assigned to a user in an ADFS environment and SSO is configured, the desktop client does not open the certificate chooser window (which is a pop), like for example the IE does when logging in. 
Seems that popups/alert windows are blocked or not opened by the client.

Usually this window comes up, there should be a second window/popup showing where the user selected the cert, but it doesn't. Though this might be a corner-case. But I had this during a customer support session today.

![image](https://user-images.githubusercontent.com/295122/45562885-f65abd80-b84b-11e8-9b68-c1b21227e7c6.png)

How to reproduce
===============
Try to login with a user which has multiple ADFS certs assigned via SAML in the desktop client on windows. The screen as shown above appears but no option to select a certificate, which usually opens in a new window (i.e. when signing in via web browser into NC).

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by mathiasconradt** [comment]
This came up in an environment that I don't have access to anymore > 2yrs ago, therefore I can't really test/validate.
