### ISSUE TITLE
[Bug]: issues with rename file with invalid name dialog

### ISSUE THREAD

**Issue by mgallien** [nextcloud/desktop#6760]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The dialog has 2 cancel buttons.
When clicking on OK button to trigger a renaming, the user has no immediate feedback thinking that they did not click until the operation is done.
see 
![image](https://github.com/nextcloud/desktop/assets/168967/0563572c-3881-4d7f-82a6-a068de0b7344)

### Steps to reproduce

1. Create a group folder with trailing and leading space in the name
2. Try to sync it via desktop client on windows
3. This folder cannot be synced
4. Clicking on the warning opens a dialog to rename (impossible for group folder root folder)
5. Dialog has issues and rename cannot be done

### Expected behavior

If a folder cannot rename, just tell it to user
A dialog should not have 2 cancel buttons
Upon clicking on a button, immediate feedback should be given

### Which files are affected by this bug

n/a

### Operating system

Windows

### Which version of the operating system you are running.

windows 10

### Package

Other

### Nextcloud Server version

28.0.5

### Nextcloud Desktop Client version

master branch

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
issues from master
2 cancel buttons is a regression only on master
@tobiasKaminsky

**Comment by tomdereub** [comment]
Same issue with nextcloud 28.0.6 and nextcloud desktop client 3.13.1 on windows 10, using VFS : 
![image](https://github.com/nextcloud/desktop/assets/16243499/813a96cb-2be1-4ce3-b184-2acb94ab1607)

**Comment by mgallien** [comment]
closing as not reproducible anymore
