### ISSUE TITLE
[Bug]: Client won't connect, show very generic error when user's password is expired

### ISSUE THREAD

**Issue by Extarys** [nextcloud/desktop#6766]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The client would say it's disconnected and open the Grant access page in Firefox. After granting permission without any error, the client would show a WebDav retrieval error. I tryed with multiple versions of the client before trying to log into the account from a privaste window and noticed the password was expired.

I search for a couple of hours, seeing a lot of users having a similar issue in the past couple of years. In my case, it was a password expired issue.

### Steps to reproduce

1. Setup the client on a computer and sync some files
2. Make sure you are logged into your nextcloud instance in the web browser
3. Wait for the user's password to expire
4. The client icon will turn gray in the tray icon and the browser auth window will open at every windows startup
5. Open the client and try logging in if no window opened
6. Webpage asks to confirm you want the client to have access to your files
7. Confirm/Grant access
8. The webpage says it's successful
9. Client shows error getting webdav directory
10. Restart the computer and start from step 4

### Expected behavior

Nextcloud client should popup a couple of days earlier than the password expiration date to ask the user to change it.

If the password is already expired, the client should notify the user that they need to reset their password before attempting to connect the client. The webpage when connecting a client should also warn the user.

### Which files are affected by this bug

.

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Other

### Nextcloud Server version

28.0.0

### Nextcloud Desktop Client version

13.3.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Sounds like #5307, correct?
