### ISSUE TITLE
[Qt6][Windows][Bug]: Some kind of timeout when starting to sync (file download fails) 

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#6768]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Set up a new folder connection to the server and start syncing files. More than 50% of the time, some files will fail to sync with an error displayed as a timeout of network connection. This happens with and without virtual files (you need to try to download a file with VFS in order for this to happen).

### Steps to reproduce

1. Install a desktop client build built with Qt6
2. Setup a new folder connection and start syncing files
3. Observe the issue

### Expected behavior

Syncing works as expected similar to how it works with Qt5 build.

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

All Windows

### Package

Other

### Nextcloud Server version

all

### Nextcloud Desktop Client version

3.13.50

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by allexzander** [comment]
@mgallien

**Comment by mgallien** [comment]
@tobiasKaminsky blocking bug for any release based on master branch

**Comment by mgallien** [comment]
Closed by https://github.com/nextcloud/desktop/pull/6987
