### ISSUE TITLE
Files with empty file names are handled strangely

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/desktop#677]
I have files that don't have a proper file name, only an extension (e.g. when you drag-and-drop save pictures from a browser, this happens often: `.jpg`). If such a file is in a synced folder, it gets a yellow exclamation mark symbol from Nextcloud. This makes me think it's not uploaded, which is not true, because the file is in fact synced.

Such pictures also can't be previewed on the web UI, but I guess that's a different issue.

I propose making Nexctloud's marking of the file consistent with its handling of the file.

**Comment by camilasan** [comment]
@leafcutterant Please, use the bug report template. Which version of the desktop client you are are running? Which Operating System? Etc
Thanks!

**Comment by leafcutterant** [comment]
Sorry for missing this request.

### Client configuration
Client version: 2.3.3.1

Operating system: Windows 7

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
