### ISSUE TITLE
[Qt6][Windows][UI]: Folder connection dialog appears broken and is hard to use 

### ISSUE THREAD

**Issue by allexzander** [nextcloud/desktop#6770]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When running a build created with Qt6 on Windows, if I try to setup a new folder connection in the Settings dialog, the folder connection UI appears broken (it is too small and it is collapsed) and is hard to use.set up

### Steps to reproduce

1. Run a Qt-6 built build
2. Open the Settings dialog and click "Add new folder"
3. Observe the broken widget (UI)

### Expected behavior

UI must be usable and non-collapsed, similar to how it works on Qt5

### Which files are affected by this bug

all

### Operating system

Windows

### Which version of the operating system you are running.

All Windows

### Package

Other

### Nextcloud Server version

all

### Nextcloud Desktop Client version

3.13.50

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by allexzander** [comment]
@mgallien

**Comment by mgallien** [comment]
Closing it as not reproducible
