### ISSUE TITLE
`App token login name does not match`

### ISSUE THREAD

**Issue by stfast** [nextcloud/desktop#6783]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

MacOS VFS not working

### Steps to reproduce

1. Upgrade to Nextcloud 29
2. Installing Nextcloud-3.13.0-macOS-vfs.pkg desktop package

### Expected behavior

MacOS VFS sync should work.

### Which files are affected by this bug

All files

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Sonoma

### Package

Appimage

### Nextcloud Server version

29.0.1

### Nextcloud Desktop Client version

3.13.0git (build 22493)

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
{"reqId":"ZlWlLYRKmwoFGdCgwVCaxAAAABE","level":3,"time":"2024-05-28T09:34:37+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"GET","url":"/ocs/v1.php/cloud/capabilities","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
{"reqId":"ZlWlLoRKmwoFGdCgwVCaxQAAAAk","level":3,"time":"2024-05-28T09:34:38+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"GET","url":"/ocs/v1.php/cloud/capabilities","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
{"reqId":"ZlWlLoRKmwoFGdCgwVCaxgAAABM","level":3,"time":"2024-05-28T09:34:38+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"GET","url":"/ocs/v1.php/cloud/capabilities","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
{"reqId":"ZlWlLoRKmwoFGdCgwVCaxwAAAA4","level":3,"time":"2024-05-28T09:34:38+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"GET","url":"/ocs/v1.php/cloud/capabilities","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
{"reqId":"ZlWlLoRKmwoFGdCgwVCayAAAAAs","level":3,"time":"2024-05-28T09:34:38+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"GET","url":"/ocs/v1.php/cloud/capabilities","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
{"reqId":"ZlWlLjKYlJZA6EfwdAblQQAAAEs","level":3,"time":"2024-05-28T09:34:38+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/FDD17349-A32D-4411-8E0E-A71BAA44509F","message":"App token login name does not match","userAgent":"Nextcloud-macOS/FileProviderExt","version":"29.0.1.1","data":{"tokenLoginName":"fast@domain.com","sessionLoginName":"FDD17349-A32D-4411-8E0E-A71BAA44509F","app":"core","user":"FDD17349-A32D-4411-8E0E-A71BAA44509F"}}
```

### Additional info

![image](https://github.com/nextcloud/desktop/assets/1120689/f554135b-1d7a-4a2f-b1e1-279d68119018)
![image](https://github.com/nextcloud/desktop/assets/1120689/2065f206-9b1c-430d-afa6-68a55a248295)

**Comment by claucambra** [comment]
Hi @stfast could you also send us the normal debug archive for the desktop client? Thanks!

**Comment by stfast** [comment]
Actually they are one post above.

Here is archive file.

[Nextcloud-Desktop-debug_archive.txt.zip](https://github.com/user-attachments/files/15988918/Nextcloud-Desktop-debug_archive.txt.zip)

**Comment by stfast** [comment]
Guys, after all VFS PR with HUB 8, this is embarrassing, still not working  ...

**Comment by claucambra** [comment]
Hello @stfast I am sorry I haven't had the time to fix this yet, I am patching the virtual files module as quickly as I can

Your log files say your username is `FDD17349-A32D-4411-8E0E-A71BAA44509`; I am guessing this is incorrect? Are you using LDAP or some alternative user backend on your server instance?

Thanks for providing information

**Comment by stfast** [comment]
> Hello @stfast I am sorry I haven't had the time to fix this yet, I am patching the virtual files module as quickly as I can
> 
> Your log files say your username is `FDD17349-A32D-4411-8E0E-A71BAA44509`; I am guessing this is incorrect? Are you using LDAP or some alternative user backend on your server instance?
> 
> Thanks for providing information

Yes, this is LDAP user ID from LDAP backend and everything is correct, since normal desktop sync does work, but not VFS one.

**Comment by stfast** [comment]
Anything? Nextcloud 30 approaching and still not fixed.

**Comment by joshtrichards** [comment]
Can you elaborate a bit on how you're authentication from the VFS version of the client?

I have a feeling this is specific to LDAP or an interaction with LDAP and the Login flow or app tokens:

https://github.com/nextcloud/server/blob/45f8d2afc9d8eca53401e43d8c432e7bd43bb430/lib/private/User/Session.php#L781-L787

Though I've no idea at the moment why you'd only encounter it with VFS mode.

Is your non-VFS client (that doesn't have this problem) configured exactly the same in terms of authentication?

**Comment by thejulian** [comment]
I have the same error.
Standard file sync is working (with same account, same backend - LDAP, same server).

**Comment by frene7ik** [comment]
Same here. I also tried with an app password but got identical results.

**Comment by stfast** [comment]
Upgraded to Nextcloud 30, now changed error mesaages in debug archive:

Sending extension account ID FDD17349-A32D-4411-8E0E-A71BAA44509F@nextcloud.domain.com
Successfully started Realm db for NextcloudFileProviderKit
Set up enumerator for user: user@domain.com https://nextcloud.domain.com
with serverUrl: https://nextcloud.domain.com/remote.php/dav/files/user@domain.com
Set up enumerator for user: user@domain.com https://nextcloud.domain.com
with serverUrl: https://nextcloud.domain.com/remote.php/dav/files/user@domain.com
Sending extension account ID FDD17349-A32D-4411-8E0E-A71BAA44509F@nextcloud.domain.com
1 depth read of url https://nextcloud.domain.com/remote.php/dav/files/user@domain.com
did not complete successfully, error: 
		The server was unable to complete your request.		If this happens again, please send the technical details below to the server administrator.		More details can be found in the server log.
"Finishing enumeration for user: user@domain.com https://nextcloud.domain.com

[NC-30.txt](https://github.com/user-attachments/files/17096329/NC-30.txt)

**Comment by osiktech** [comment]
I ran into the same issue just a couple of days ago. Took me a while to find this issue here.

I am using LDAP as user backend and my username is a generated uuid. To fix this issue, I stopped my nextcloud, dumped the database, replaced the UUID with my email address in the dump, imported the dump back to my database, started the nextcloud server again and linked the nextcloud client and everything was working.

I only took this approach because this is my personal instance and I have backups of everything. so before any one takes this road, I cannot stress enough the fact, my backups, test the backups, and only if everything works, try my approach.

due to the change of the username, you most probably need to reconnect any DAV related connections. so be very careful!!!!

**Comment by stfast** [comment]
Still, VFS macOS desktop sync does work for LDAP users with default LDAP UUID Internal Username, which is default LDAP behavior with only Expert LDAP options override for new users.

As you see from desktop client debug archive, user is authenticated, but client's server URL shoud be with UUID

https://nc.domain.com/remote.php/dav/files/FDD17349-A32D-4411-8E0E-A71BAA44509F

and not with username (LDAP userPrincipalName in our case)

https://nc.domain.com/remote.php/dav/files/user@domain.lan

I have checked WebDav and it works only with UUID as username as pointed in "Files/Files settings" WebDav URL:

![Image](https://github.com/user-attachments/assets/37fe5f4f-740f-4bd2-80b6-1ee6b4b01f42)

This is from attached desktop client debug archive:

Not fetching item for identifier: NSFileProviderRootContainerItemIdentifier
as account not set up yet.
Authenticated! Nextcloud account set up in File Provider extension.
User: user@domain.lan at server: https://nc.domain.com
Successfully started Realm db for NextcloudFileProviderKit
Set up enumerator for user: user@domain.lan https://nc.domain.com
with serverUrl: https://nc.domain.com/remote.php/dav/files/user@domain.lan
Set up enumerator for user: user@domain.lan https://nc.domain.com
with serverUrl: https://nc.domain.com/remote.php/dav/files/user@domain.lan
1 depth read of url https://nc.domain.com/remote.php/dav/files/user@domain.lan
did not complete successfully, error: 
		The server was unable to complete your request.		If this happens again, please send the technical details below to the server administrator.		More details can be found in the server log.
"Finishing enumeration for user: user@domain.lan https://nc.domain.com
with serverUrl: https://nc.domain.com/remote.php/dav/files/user@domain.lan 
with error 
		The server was unable to complete your request.		If this happens again, please send the technical details below to the server administrator.		More details can be found in the server log.
Set up enumerator for user: user@domain.lan https://nc.domain.com

[NC-30.0.1.txt](https://github.com/user-attachments/files/17624714/NC-30.0.1.txt)

**Comment by claucambra** [comment]
@stfast thanks for posting this, I realised this a few days ago too (opened https://github.com/claucambra/NextcloudFileProviderKit/pull/24 which fixes this)

**Comment by stfast** [comment]
OK, now with Nextcloud Desktop version 3.15.0, LDAP login is working and server and client errors are gone.

 But how is this supposed to work?

On first sync "Virtual file sync" does not get to synced status.

![Image](https://github.com/user-attachments/assets/f47b2497-0811-4178-87de-fdefd61268b9)

When you quit and than start Nextcloud Desktop client again, than suddenly it is "All Synced":

![Image](https://github.com/user-attachments/assets/d5094a06-2c34-4f26-b793-da25824a8261)


Folder with Sync Connection have 5.9 Gb of data even if you quit Nextcloud Desktop client:

$ du -sh .
5.9G	. 

and there is none files to evict

![Image](https://github.com/user-attachments/assets/e68d7afa-5d28-4faf-a572-5a80e25408f8)


If we summarize, macOS "Virtual file sync" still not working.

**Comment by stfast** [comment]
OK, I dug it deeper and found macOS VFS location on this kind of a path

open ~/Library/CloudStorage/Nextcloud-user@ldapdomain.lan.us@nc.server.com/

![Image](https://github.com/user-attachments/assets/e2ea72c8-acab-4414-ab50-8dfc892617c8)


If you quit Nextcloud.app and start , Nextcloud folder from Locations in Finder dissapears.

You have to be kind of an expert yourself to put this path back to the Finder, since ~/Library/* folder is hidden by default 

There should be some configuration for VFS mount path as it is "Folder Sync Connection" for classic sync.
