### ISSUE TITLE
[Bug]: Synchronisation error - Permission denied

### ISSUE THREAD

**Issue by loulous24** [nextcloud/desktop#6796]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On Linux, when synchronising a file that has been modified by someone else and is only shared with read-only permission, the synchronisation gives an error, "permission denied".

It is because the Nextcloud client sets the permission of the file to read-only and is not able to write it again locally when it is modified.

### Steps to reproduce

1. User A create a file
2. Share the file to user B with read-only permission
3. User B synchronises the file
4. Use A modifies the file
5. User B has an error "permission denied" when doing the synchronisation again.

### Expected behavior

The client should set the permissions to read-write, modify the file and set again the local permissions to read-only.

### Which files are affected by this bug

All files with read-only permission that are modified by someone else

### Operating system

Linux

### Which version of the operating system you are running.

Fedora Linux 39

### Package

Appimage

### Nextcloud Server version

28.0.3.2

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jstephenson** [comment]
I'm experiencing this with the current version of the desktop client on Linux as well. Items are synced with read-only filesystem permissions, and the Nextcloud client is then unable to modify them as it should.
