### ISSUE TITLE
Feature - Halt sync before modifying/deleting/moving too much data

### ISSUE THREAD

**Issue by warnerbryce** [nextcloud/desktop#68]
Hello to the Nextcloud GitHub Community 

I would like to know if the feature/enhancement i propose can be a good one, and can be implemented.

On the Nc/Oc client, to have a new option in the General TAB : 
- Halt sync and ask what to do, when X Gb have been modified - 
Where you remplace X by a number you want. 

Imagine that i got a bad ransomware and in my nextcloud and i have a shared folder with my team really important and quite big lets say 10Gb. Nextcloud will sync the bad files and will give them to the team. 
The solution, go inside the Web version, go into Trashbin folder, and recover. Then wait for everyone to get the good sync, and also repair the client who is infected by the ransomware. It's a lot of work for the server, it has to recover 10Gb from  the trashbin, then to give 10Gb of files to many users i have in the team.
Whereas, if i put a threshold of 5Gb with this feature, my whole nextcloud files will be attacked by the ransomware, but it won't sync because i will get an alert : "There is more than 5Gb who have been modified since last sync, are you sure you want to sync ? - Yes, continue to sync  - No, pause my instance and let me verify"
The server won't get 10Gb of encrypted files, won't have to recover from trashbin, won't have to give the files back to the entire team.

This is an example with a ransomware, but i got it twice with user who make a misclick and move/delete a big folder somewhere else and broke a day of working because the team have to sync well before continuing to work. I know that when you share a folder you can block deletion, but it works only on the entire folder and won't fit in all situations of team works.

So it is possible that the Nc Client could put a window alert on the front screen and halt the sync waiting for an answer of the user ?

I have started a topic on the help community : https://help.nextcloud.com/t/nc-client-halt-sync-before-a-lot-of-files-will-be-deleted-modified/23938/8

Thank you

**Comment by timreeves** [comment]
This sounds like a VERY good idea to me!

**Comment by tacruc** [comment]
I wonder if a number of files would be the more useful as boarder than the size. Otherwise if you work with pictures and sidecard files one could delete all small sidecard files without the client to ask but deleting 4 rae pictures would create a warning.

**Comment by AndrewBucklin** [comment]
How about an option in the sync client:

**_Ask for confirmation before synchronizing deletions of more than ___ files_**
(where ___ is a numeric value)

**Comment by manches** [comment]
Hi just lost 200G with no reason with the NC client.
More wired is that on the NC server still as the data in the original folder and on the NC client the folder is still marked ask sync....
Probably with this feature, it is more safer these things

**Comment by subsembly** [comment]
Also I really would want to have this feature! We too had to struggle with accidental deletes of large amounts of data. At least put up a warning and ask for confirmation in the NC client if non-empty folders are deleted.

**Comment by subsembly** [comment]
Additional idea: If the NC client asks for confirmation when deleting non-empty folders. The question should be: "Do you really want to delete the folder and all its content on the Nextcloud server? Click on NO in order to disable synchronization for this folder" Thus nothing will be lost on the server and the user can do whatever is needed for local recovery.

**Comment by Highview-Lucas** [comment]
There definitely needs to be some kind of checks and balances. 

I have a user with two devices. On one he setup several Gb of "stuff" (curriculum items for a bunch of classes, etc)
When he fired up the second device for some reason NC decided that was the "source of truth" and promptly deleted everything he'd added from the first machine.

It was in the trash bin, but it was also a lot of GB of data, and suddenly needed to be synced to two machines again.

**Comment by stonymahony** [comment]
Hey everybody,
is there anything new on this, what is the status?

This feature would definitely be super useful!

**Comment by manches** [comment]
Looks like there is no movement.

The feature is like the option of asking when sync files more larger than 500M but it is more complex because you have to check and count all the files before deleting

**Comment by jose1711** [comment]
i also like the idea. would probably be handy in cases like these: https://help.nextcloud.com/t/urgent-security-issue-in-nginx-php-fpm/62665

**Comment by torkleyy** [comment]
An alternative to the proposed feature that does not involve setting arbitrary limits (and should be rather easy to implement):

Add an opt-in option to never delete any files, and instead only move them to the trash bin.

**Comment by warnerbryce** [comment]
@torkleyy yeah good point. The only REAL delete that can occur is when you untick folders from the nextcloud sync tab.

**Comment by fl0f** [comment]
Hi everybody, 
I experiment that problem with multiple clients impacted by a one user committing mistaken deletes (or moves data from sync folder to local folder). I can get it back from the server trash (from web client) but it takes hours to sync again all the 30Gb data simultaneously on all clients.

I would be very interested by a feature that could detect some "mass" (trigger value in Gb ?) delete from server and ask user before doing.

**Comment by MaBaTa** [comment]
Hello Everyone,

I just have lost ~400GB of data permanently because of an error that would be prevented by something like this.
One of the Programms on one of my Clients decided to delete files an folders randomly, the Client synct it to the Server and all other Clients also deleted the data.
Sadly the Trashbin of the Server has some kind of overflow which was smaller than the deletions and about 400GB are gone now :(

I know i sould had some kind of backup, but in never thought of an error like this and had only hardware falue in mind.
With 3 clients and the server who had a full copy i felt kind of save.

So i would love a featue like this because i don't want to experience something like this again.
And also if i had a Backup it would have taken a very long time to resync to all clients, which is out of proportion to the seconds it takes to delete this much data.

If i can help in any kind to make this feature, please let me know.

**Comment by Rello** [comment]
This will be continued in https://github.com/nextcloud/desktop/issues/4231
