### ISSUE TITLE
[Bug]: Mac: Upload of folder with trailing space failed silently

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/desktop#6807]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

- create a folder with a trailing space "test "

### Steps to reproduce

1. create folder
2. probably see a warning

### Expected behavior

mac should be able to upload it

### Which files are affected by this bug

all with trailing spaces?

### Operating system

Mac OS

### Which version of the operating system you are running.

?

### Package

Distro package manager

### Nextcloud Server version

/

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

For more info, please ask @jancborchardt

**Comment by joshtrichards** [comment]
Related: #4390
