### ISSUE TITLE
Latest client (and old) wont sync random folders.

### ISSUE THREAD

**Issue by bootlegger17** [nextcloud/desktop#681]
# Create a bug report to help us improve

### Expected behaviour
Additional folder should be seen by the client and syncronised.

### Actual behaviour
All old folders are synced, but the latest one is not.  Client program closes (latest version 2.5.0.61361), but older ones stay loaded (2.3.x)

### Steps to reproduce
1. Got historic list of folders labelled 3 thru to 7
2. Add new folder 8
3. Contents added.
4.  Run nextcloud desktop sync - does not show new folder to sync.  Strangely total MB used matches at top level, but tally of sub folders does not.  nextcloud client clean install wont pull folder 8 through either.

![webclient](https://user-images.githubusercontent.com/11878313/45700566-cf123200-bb64-11e8-8cfd-d73d667a5ec4.jpg)
![client](https://user-images.githubusercontent.com/11878313/45700570-d1748c00-bb64-11e8-8485-8af925cea870.jpg)

### Client configuration
Client version: 2.5.0.61361

Operating system: Windows 7 

OS language: EN

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\Nextcloud\

### Server configuration

Operating system:

Web server:

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
