### ISSUE TITLE
[Bug]: macOS CheckUpdate Update Error

### ISSUE THREAD

**Issue by intdel** [nextcloud/desktop#6814]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When checking for update on macOS nextcloud client, I am getting an error.

<img width="604" alt="image" src="https://github.com/nextcloud/desktop/assets/8001528/dec502e5-4e67-499f-99e3-6618daa1ad64">

### Steps to reproduce

1. Open Settings
2. Check for Updates

### Expected behavior

It checks for updates successfully

### Which files are affected by this bug

sparkleupdater_mac

### Operating system

Mac OS

### Which version of the operating system you are running.

14.5

### Package

Appimage

### Nextcloud Server version

29.0.1

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jameskimmel** [comment]
I have had the same error in 3.13.0 standard. 
Installed 3.13.0 VFS and the error persists.

**Comment by AlexanderZuehr** [comment]
I do also have this problem, what logs are needed to fix it?

**Comment by intdel** [comment]
Thanks for the quick fix. I can confirm it works.

**Comment by martinjgrunwald** [comment]
I just updated to 3.14.0 and I am getting this exact error

**Comment by vapaa** [comment]
I also have the error with MacOS 14.7 and the Nextcloud desktop client 3.14.0.

**Comment by henrygermany** [comment]
Same Error on 14.6.1 with Nextcloud Desktop client 3.14.0

**Comment by vapaa** [comment]
that was a good tip, I changed the update channel to "stable" and no longer got an error message. However, after I changed it back to daily, the error message came back. At least with the workaround "set to stable" I no longer get an error message.

**Comment by foss-** [comment]
As the remaining issue is something different than what was reported in the issue here and which has been fixed, why not report a new issue for the remaining problem?
