### ISSUE TITLE
[Bug]: Cannot access Settings with more than 5 Nextcloud Instances

### ISSUE THREAD

**Issue by unrockstar1988** [nextcloud/desktop#6815]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I added a 6th Nextcloud to the Desktop Synchronization Client (Mac) and could not access the "Settings"/"Einstellungen"-Button afterwards. The height of the Overlay seems to be limited and if list of clouds gets too long the "Settings"-Option disappears. I couldn't find any other way to access the settings.
Before
<img width="392" alt="Nextcloud_Issue" src="https://github.com/nextcloud/desktop/assets/47254339/42ffdf1a-84b0-4a3a-9064-89aab1234ad3">
After
<img width="493" alt="Nextcloud_Issue2" src="https://github.com/nextcloud/desktop/assets/47254339/5d71ade7-eedd-444b-be7b-0e28c63dd06a">

### Expected behavior

I would expect that the Overlay grows in size so that I can access the settings. Otherwise there could be another way to access the Settings.

### Operating system

Mac OS

### Which version of the operating system you are running.

macOS Sonoma

### Package

Appimage

### Nextcloud Server version

any

### Nextcloud Desktop Client version

3.2.4

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

**Comment by claucambra** [comment]
Hi @unrockstar1988 desktop client 3.2.4 is extremely old and we strongly recommend you upgrade to a more recent version

Since 3.2.4 this overlay was modified to be able to scroll
