### ISSUE TITLE
[Bug]:  Installing AppImage on Ubuntu 24.04 makes laptop unbootable

### ISSUE THREAD

**Issue by bobhendrikx** [nextcloud/desktop#6829]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When i install the AppImage Nextcloud-3.13.0-x86_64 on my laptop (by making the image executable and running it) the laptop will hang on next boot. 

### Steps to reproduce

I run Ubuntu 24.04 on a Macbook Pro 2015. 
1) Install the AppImage Nextcloud-3.13.0-x86_64 
2) do `sudo chmod +x Nextcloud-3.13.0-x86_64.AppImage` to make it executable
3) run the image `./Nextcloud-3.13.0-x86_64.AppImage` 
4) Connect it to my homeservers Nextcloud instance by logging in via the browser redirection
5) Sync folders
7) When rebooting, Ubuntu hangs on the boot process. 

I tried it multiple times with fresh Ubuntu install, and it happens consistently after installing Nextcloud AppImage. 
Unfortunatly it is difficult to see in the output of the boot process what exactly is going wrong. Some noteable logs are:

[DEPEND] Dependency failed for sssd-nss.soc... SSSD NSS Service responder socket.
[DEPEND] Dependency failed for sssd-autofs... SD AutoFS Service responder socket.
[DEPEND] Dependency failed for sssd-pac.soc... SSSD PAC Service responder socket.
[DEPEND] Dependency failed for sssd-pam-pri... M Service responder socket.
[DEPEND] Dependency failed for sssd-pam.soc... PAM NSS Service responder socket.
[DEPEND] Dependency failed for sssd-ssh.soc... SSSD SSH Service responder socket.
[DEPEND] Dependency failed for sssd-sudo.so... SSSD SUDO Service responder socket.
kaudit_printk_skb: 126 callback suppressed
[   8.947799] ieee80211 phy0: brcmf_inetaddr_changed: fail to get arp ip table err: -52

### Expected behavior

Installing the Nextcloud Desktop client should not make laptop unbootable

### Which files are affected by this bug

?

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 14.04

### Package

Appimage

### Nextcloud Server version

21.0.0

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by bobhendrikx** [comment]
It turns out the problem was installing fuse (`apt install fuse`)
This is a known problem for Ubuntu, and one should install `libfuse` instead to make the AppImage work without breaking the Ubuntu Desktop.

**Comment by SprickW** [comment]
This solved it for me:

If it is Ubuntu 24.04, you need to run the following command install the FUSE library:

sudo apt install libfuse2t64

If it is Ubuntu 22.04, you should use this command:

sudo apt install libfuse2
