### ISSUE TITLE
Nextcloud Desktop daily for Windows has not been build

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/desktop#683]
Hey Folks,

Nextcloud Desktop daily for Windows has not build properly last day(s) ...

  | Linux/ | 2018-09-20 05:45 | - |  
  | Mac/ | 2018-06-20 12:07 | - |  
  | Windows/ | 2018-09-13 01:47 | - |  

Thanks for fixing! :-)

**Comment by camilasan** [comment]
Hi, Thanks again for the heads up!
Just fixed it.

**Comment by camilasan** [comment]
https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.0.61368-daily-20180920.exe

**Comment by nextgen-networks** [comment]
@camilasan windows daily seems not to be updated again - would it be possible to give it polite punch ;-)

Thanks in advance!

**Comment by camilasan** [comment]
Yes, @nextgen-networks, thanks :) I am building the latest atm and then it should continue working for the next few weeks...

**Comment by camilasan** [comment]
https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.2.5216-daily-20190304.exe
