### ISSUE TITLE
[Desktop app] .ink files is showing as constantly syncing

### ISSUE THREAD

**Issue by brice-shadow** [nextcloud/desktop#6847]
# Reproduction
**Reproducible ?**
- [x] Yes.
- [ ] No.

**Regularity ?**  
- [x] Always.
- [ ] Sometimes.
- [ ] Unable to reproduce.

**Regression ?**
- [ ] Yes.
- [x] No.
- [ ] New Feature.
 
**Steps to reproduce ?**

**Scenario 1**
1. Go to web app
2. Upload a .ink file
3. Start Shadow Drive desktop app
4. Check sync folder

**Expected results:** Should show the file as synced

**Obtained results:** File is shown as syncing constantly

**Scenario 2**
1. Copy .ink file in the sync folder
2. Check in web app if .ink 

**Expected results:** Should show the file as synced in the sync folder

**Obtained results:** File is shown as syncing constantly in sync folder + properly shows up in web app

![Image](https://github.com/nextcloud/desktop/assets/173074264/d7ade2c5-c7ae-48e4-b198-8a2d4c564c52)

# Environment and versions
 
| Client Environment | VM Environment |
| ------------------- | --------------- |
| 3.13.0 | Windows |

**Comment by tobiasKaminsky** [comment]
PR: https://github.com/nextcloud/desktop/pull/6629

Not yet released
