### ISSUE TITLE
[Desktop App Linux ONLY] No context menu

### ISSUE THREAD

**Issue by brice-shadow** [nextcloud/desktop#6848]
# Reproduction
**Reproducible ?**
- [x] Yes.
- [ ] No.

**Regularity ?**  
- [x] Always.
- [ ] Sometimes.
- [ ] Unable to reproduce.

**Regression ?**
- [ ] Yes.
- [x] No.
- [ ] New Feature.
 
**Steps to reproduce ?**

- Go to sync folder
- Do a right click on any files

**Expected results:** Should show Shadow Drive option in the context menu

**Obtained results:** There's no Shadow Drive option in the context menu

![Image](https://github.com/nextcloud/desktop/assets/173074264/c67d1df8-56b0-47a5-a4d3-1d3fe3f2d096)

# Environment and versions
 
| Client Environment | VM Environment |
| ------------------- | --------------- |
| 3.7.4 | Ubuntu 18.04.6 LTS |
| 3.13.0 | Ubuntu 18.04.6 LTS |

**Comment by tobiasKaminsky** [comment]
There is one "solution":
Install official Nextcloud sync client via package manager, as this then install the needed libraries and thus also a branded client works.
