### ISSUE TITLE
Notifications are not "removed"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/desktop#685]
### Steps
1. Receive a notification on the desktop client
2. Go to the web interface and manually remove the notification
3. On the next notification pull the notification should be removed as it is not in the returned list anymore

### Actually
at 3. the notification is still there.

**Comment by camilasan** [comment]
Hi Joas, Are you running one of the daily builds?

**Comment by nickvergessen** [comment]
I run beta and update every 2-3days
