### ISSUE TITLE
Option to launch web interface vanishes when adding second account

### ISSUE THREAD

**Issue by m1cm1c** [nextcloud/desktop#687]
### Expected behavior
For each account, there should be an option to open the corresponding web interface.

### Actual behavior
No option for opening a web interface is shown.

### Steps to reproduce
1. Start out with a newly installed Nextcloud client.
2. Add an account. You are now provided the option to open the web interface corresponding to that account when clicking onto the Nextcloud client's symbol in the system tray.
3. Add a second account. The option described above is gone.

### Client configuration
Client version: 2.3.3

Operating system: Ubuntu 16.04 64 bit running Unity 7.4.5 and kernel 4.4.0-135-generic 

OS language: English (U.S.)

Qt version used by client package (Linux only, see also Settings dialog): Wasn't able to find this in the settings window.

Client package (From ownCloud or distro) (Linux only): `http://ppa.launchpad.net/nextcloud-devs/client/ubuntu`

**Comment by camilasan** [comment]
Hi! Could you try the same in one of our daily builds with a test account?
https://download.nextcloud.com/desktop/daily/
Thanks!

**Comment by maghog** [comment]
Tested with Nextcloud-2.5.0.61375-daily-20180927.exe and it works as expected.

**Comment by camilasan** [comment]
May I close this issue then? @m1cm1c @maghog ?
Thanks.

**Comment by maghog** [comment]
Ok for me...

**Comment by m1cm1c** [comment]
You're right. The problem does not occur with the current daily build. When running the current daily build, the account description unfolds when you hover over it, providing the above-mentioned functionality. This does not happen with the PPA version I'm currently running.
