### ISSUE TITLE
[Bug]: Virtual Files not Syncing automatically

### ISSUE THREAD

**Issue by JWandscheer** [nextcloud/desktop#6886]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

With Virtual Files enabled on MacOS, the Client does not sync changes from the Server automatically. I currently have just 4 files in My Nextcloud instance and running the MacOS Desktop Client with Virtual Files Support. I uploaded a photo to the online interface. In the Classic Sync folder, the file appears almost instant, in the virtual files folder it does not appear, even after waiting around 30 Minutes. If i pause and resume the synchronization, it doesn' appear either. I have to do a restart of the client to make the file appear. This happens for both "enable fast sync" enabled and disabled.

### Steps to reproduce

1. Install Desktop Client with virtual file support
2. Wait for the initial sync
3. Upload a file to the online interface
4. The file does not appear in the virtual files folder

### Expected behavior

The virtual files should be correctly synced.

### Which files are affected by this bug

.png, .jpeg, .docx, ....

### Operating system

Mac OS

### Which version of the operating system you are running.

MacOS Sonoma (14.5)

### Package

Appimage

### Nextcloud Server version

29.0.2.2

### Nextcloud Desktop Client version

3.13.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Client Logs for Virtual Files:
Not providing enumerator for container with identifier NSFileProviderWorkingSetContainerItemIdentifier yet as account not set up
Could not get notifyPush websocket [..…].de, polling.
Finished reading serverUrl: [...] for user: [...].de
Finished recursive change enumeration of working set for user: [...].de. Enumerating items.
Processed 1 new or updated metadatas, 0 deleted metadatas.

**Comment by claucambra** [comment]
Hi @JWandscheer does your server have `notify_push` configured and enabled?

**Comment by JWandscheer** [comment]
@claucambra you are right, the plugin is not enabled. I am not the administrator of the server, but will get in contact with them.

**Comment by JWandscheer** [comment]
Yes, it means you need to enable notify_push to make the virtual file sync work.

**Comment by sman-dk** [comment]
Since Virtual files is the default when downloading for MacOS shouldn't notify_push then be enabled by default on the server including an update that would enable it on all existing server instances?

**Comment by konradbr** [comment]
I can confirm I am experiencing the same issue. Or when working with a colleague: when he or I add a file locally, it gets pushed to the server, but not downloaded to our instance. I also frequently encounter "The file couldn't be opened." errors when trying to download the entire folder which is not syncing.

**Comment by konradbr** [comment]
Note that I _do_ have notify_push enabled (we host our own NextCloud instances).

**Comment by r2evans** [comment]
> Yes, it means you need to enable notify_push to make the virtual file sync work.

Um, what? I do not have `notify_push` installed or enabled, I have the macos client installed and running with VFS, successfully.

Though I like the premise of it, the `notify_push` app seems a bit unstable, and I'm not thrilled atm with opening another port on my firewall to support it. Until that app is stable, if nextcloud forces its use, I'll likely disable the desktop client completely and find an alternative to syncing files, as there are enough concerns with VFS integration that make larger nextcloud instances difficult.
