### ISSUE TITLE
Need file whitelist along with blacklist [ignored files]

### ISSUE THREAD

**Issue by skewty** [nextcloud/desktop#689]
I don't want to include hidden files except if the folder is called `.git`.  How would I do that?
I am trying to sync messy staging environments between my work and home.  Sadly I can't really do this nicely.

My current setup for this workstation is:
  nextcloud:/Projects
  local:~/Projects
  which means my local target folder is ~

If I include hidden by default I get a bunch of things I don't want / need and am constantly syncing for little gain.

**Comment by Rello** [comment]
Hello,
we only have extensive blacklisting with wildcards. whitelisting is not planned at the moment
