### ISSUE TITLE
googledrive: not synching reliably

### ISSUE THREAD

**Issue by SGatBugs** [nextcloud/desktop#69]
Ubuntu 17.10 or Win10, Client 2.3.2

external storage googledrive is not synching relibably, Often files are not downloaded by the client, which are already in googledrive or are newly uploaded to googledrive via a different way than nextcloud client. Nextcloud server is showing the missing files in the web interface.

**Comment by lsbbs** [comment]
I have here this issue:
The desktop client version 2.3.3 (installed from the ppa on Ubuntu 16.04) is syncing only directories. When it tries to sync files the server is throwing a 500 internal error.

Feb  5 18:38:50 mzao ownCloud[2399]: {webdav}
Exception: {"Exception":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable","Message":"The start offset (14140) exceeded the size of the entity (-2)","Code":0,"Trace":"#0 [internal function]: 
Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/srv\/nxcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#3 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): 
Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/srv\/nxcloud\/apps\/dav\/lib\/Server.php(258): 
Sabre\\DAV\\Server->exec()\n#5 \/srv\/nxcloud\/apps\/dav\/appinfo\/v2\/remote.php(33): 
OCA\\DAV\\Server->exec()\n#6 \/srv\/nxcloud\/remote.php(162): require_once('\/srv\/nxcloud...')\n#7 {main}","File":"\/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":160}

And then I am getting also:

Feb  5 19:00:21 mzao ownCloud[2358]: {webdav} Exception: {"Exception":"Google_Service_Exception","Message":"Error calling GET https:\/\/www.googleapis.com\/drive\/v2\/files?q=title%3D%27Sanawari+Empire+Bar.%27+and+%270AHuahQCCyDOtUk9PVA%27+in+parents+and+trashed+%3D+false: (403) User Rate Limit Exceeded","Code":403,"Trace":"#0 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Http\/REST.php(62): Google_Http_REST::decodeHttpResponse(Object(Google_Http_Request), Object(Google_Client))\n#1 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Task\/Runner.php(174): Google_Http_REST::doExecute(Object(Google_Client), Object(Google_Http_Request))\n#2 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Http\/REST.php(46): Google_Task_Runner->run()\n#3 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Client.php(593): Google_Http_REST::execute(Object(Google_Client), Object(Google_Http_Request))\n#4 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Resource.php(240): Google_Client->execute(Object(Google_Http_Request))\n#5 \/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Drive.php(1872): Google_Service_Resource->call('list', Array, 'Google_Service_...')\n#6 \/srv\/nxcloud\/apps\/files_external\/lib\/Lib\/Storage\/Google.php(127): Google_Service_Drive_Files_Resource->listFiles(Array)\n#7 \/srv\/nxcloud\/apps\/files_external\/lib\/Lib\/Storage\/Google.php(372): OCA\\Files_External\\Lib\\Storage\\Google->getDriveFile('Sanawari Empire...')\n#8 \/srv\/nxcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(220): OCA\\Files_External\\Lib\\Storage\\Google->file_exists('Sanawari Empire...')\n#9 \/srv\/nxcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(220): OC\\Files\\Storage\\Wrapper\\Wrapper->file_exists('Sanawari Empire...')\n#10 \/srv\/nxcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php(241): OC\\Files\\Storage\\Wrapper\\Wrapper->file_exists('Sanawari Empire...')\n#11 \/srv\/nxcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(220): OC\\Files\\Storage\\Wrapper\\Availability->file_exists('Sanawari Empire...')\n#12 \/srv\/nxcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(220): OC\\Files\\Storage\\Wrapper\\Wrapper->file_exists('Sanawari Empire...')\n#13 \/srv\/nxcloud\/lib\/private\/Files\/View.php(1159): OC\\Files\\Storage\\Wrapper\\Wrapper->file_exists('Sanawari Empire...')\n#14 \/srv\/nxcloud\/lib\/private\/Files\/View.php(552): OC\\Files\\View->basicOperation('file_exists', '\/googledrive\/Sa...')\n#15 \/srv\/nxcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(285): OC\\Files\\View->file_exists('\/googledrive\/Sa...')\n#16 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(105): OCA\\DAV\\Connector\\Sabre\\Directory->childExists('Sanawari Empire...')\n#17 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php(878): Sabre\\DAV\\Tree->nodeExists('files\/ta\/google...')\n#18 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#19 \/srv\/nxcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#20 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(466): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#21 \/srv\/nxcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#22 \/srv\/nxcloud\/apps\/dav\/lib\/Server.php(258): Sabre\\DAV\\Server->exec()\n#23 \/srv\/nxcloud\/apps\/dav\/appinfo\/v2\/remote.php(33): OCA\\DAV\\Server->exec()\n#24 \/srv\/nxcloud\/remote.php(162): require_once('\/srv\/hostingdat...')\n#25 {main}","File":"\/srv\/nxcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Http\/REST.php","Line":110}

The Android client version 2.0.1 is working fine. Also in Nextcloud all files are accessable without any problems.

**Comment by camilasan** [comment]
Is this happening with the latest server? Do you have the client logs?

**Comment by lsbbs** [comment]
Am 17.05.2018 um 12:54 schrieb Camila Ayres:
> Is this happening with the latest server? Do you have the client logs?

Now I updated to 13.02 and getting when enabling google drive as
external storage:
Error: This app can not be enabled because it makes the server unstable

Also a kind of solving the problem....

**Comment by lsbbs** [comment]
Am 17.05.2018 um 15:59 schrieb Camila Ayres:

> This is then an issue on the server side.

With the latest version of Nextcloud 12 the client showed only: Server
reported an internal error. Nothing else.
The server errors and that it is working with the Android are in my
initial post.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

**Comment by camilasan** [comment]
if you still have this problem, please re-open the issue.

Thanks!
