### ISSUE TITLE
[Bug]: notifications not displayed

### ISSUE THREAD

**Issue by stop5** [nextcloud/desktop#6901]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Notifications are not displayed in the Nextcloud desktop app.

### Steps to reproduce

1. setup desktop
2. Optional: open nextcloud in the browser to see the notification there
3. on the server: occ notification:generate \<user\> test
4. if you opened the browser, you see the notification there, but not in the desktop app

### Expected behavior

the notification should appear via the desktop notifications or at least appear in the mainwindow of the desktop app

### Which files are affected by this bug

no files affected

### Operating system

Linux

### Which version of the operating system you are running.

Arch Linux

### Package

Distro package manager

### Nextcloud Server version

27.1.11

### Nextcloud Desktop Client version

3.13.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

no issue on Serverside. The Notifications are received in the desktop, but it doesn't display them

**Comment by stop5** [comment]
![grafik](https://github.com/nextcloud/desktop/assets/6901125/f8b35281-7102-406f-9d8b-a7b006848539)

**Comment by stop5** [comment]
[debug.zip](https://github.com/user-attachments/files/16169247/debug.zip)

**Comment by joshtrichards** [comment]
> on the server: occ notification:generate <user> test

`occ notification:test-push <user>`

**Comment by stop5** [comment]
When i use `sudo -u www-data /srv/nextcloud/occ notification:test-push sebastian` i get the following output:
`No devices found for user`
The Browser immidiatly plays the notification sound and i can see the notification. The desktop client does not even react after i stop the client and start it manually.

**Comment by stop5** [comment]
@joshtrichards just to note: it gave the message with and without the browser window(firefox, latest version in arch at the moment)
