### ISSUE TITLE
[Bug]: 3.13.2 is not downloadable from website

### ISSUE THREAD

**Issue by groengpx** [nextcloud/desktop#6902]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

3.13.2 is not downloadable from the website, while 3.13.0 is,
while client gives a message that 3.13.2 is available.

### Steps to reproduce

1. Start desktop client.
2. Client (3.13.1) gives notification that 3.13.2 is available.
3. Download the client from https://nextcloud.com/install/
4. 3.13.0 is downloaded.

### Expected behavior

Downloading 3.13.2.

### Which files are affected by this bug

Downloader

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 20.04 LTS Focal Fossa

### Package

Appimage

### Nextcloud Server version

29.0.3.4

### Nextcloud Desktop Client version

3.13.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
https://github.com/nextcloud-releases/desktop/releases

https://github.com/nextcloud/desktop/releases

**Comment by AussieCodeKing71** [comment]
Similar issue, auto updater says new version 3.13.2 available, but when I update, it only installs version 3.13.0. When I press update manually the page it takes me to (https://nextcloud.com/install) only provides a link to 3.13.0 (https://github.com/nextcloud-releases/desktop/releases/download/v3.13.0/Nextcloud-3.13.0-x64.msi)

![Screenshot 2024-07-12 141719](https://github.com/user-attachments/assets/715987be-0295-4400-83bb-992beb19acae)

**Comment by melroy89** [comment]
Same for Linux AppImage, somebody is forgetting to update the links on the download page..!?? Anybody????

**Comment by Flow86** [comment]
Same here, auto update always installs 3.13.0, and then tells me a new update is available. had to go to the github page manually and download 3.13.2. Happened to me on all 3 of my computers

**Comment by Gowann** [comment]
Hi,
I'm not sure if this is the right place to indicate that but I also noticed the following URL "https://download.nextcloud.com/desktop/releases/Windows/latest" doesn't point to the last version (currently 3.13.2). 
As I'm used to apply a script to update nextcloud desktop automatically on many computers with this specific url and It is still redirected to v3.13.1.
