### ISSUE TITLE
v3.13.2 was re-tagged

### ISSUE THREAD

**Issue by dotlambda** [nextcloud/desktop#6903]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

That's a complete no-go.

### Steps to reproduce

https://github.com/NixOS/nixpkgs/pull/326093

### Expected behavior

n/a

### Which files are affected by this bug

n/a

### Operating system

Linux

### Which version of the operating system you are running.

NixOS

### Package

Distro package manager

### Nextcloud Server version

n/a

### Nextcloud Desktop Client version

n/a

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mgallien** [comment]
sorry that we had to change the tag after discovering issues in the initial tagged version
