### ISSUE TITLE
Drag & Drop / Move operation in Windows clients brings a sync error on Nextcloud Desktop Client version: 3.13.2 (not in earlier versions)

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/desktop#6917]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Windows 11 Pro:

By Drag & Drop operation from a file, which is inside the Nextcloud Sync Folder to a location, which is also inside the Nextcloud Sync Folder (of course another sub-Folder), the there is an error reported by the Nextcloud Windows Agent.

![image](https://github.com/user-attachments/assets/2205e686-5782-46fd-8575-012cd4843b6c)

and the following error:

![image](https://github.com/user-attachments/assets/c1af0c7d-0d38-483e-9a10-061066f2e5b7)

...

### Steps to reproduce

1. Drag & Drop operation from a file, which is inside the Nextcloud Sync Folder to a location, which is also inside the Nextcloud Sync Folder (of course another sub-Folder)
2. An error is reported
3. There is no sync operation - file not be moved (from drag & drop operation)
    Same results, when do a normal "cut" - operation by windows explorer.
4. When manually pressing the "sync now" button on the Nextcloud Agent Gui, the operation will succeed.
...

### Expected behavior

There should be no sync error by moving a file to another place inside the Nextcloud Folder in Windows 11.
This error i never saw on previous versions of Nextcloud Desktop Client versions

### Which files are affected by this bug

IMG_1799.jpg

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 Home 22H2

### Package

Other

### Nextcloud Server version

27.1.11.3

### Nextcloud Desktop Client version

3.13.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
This bug exists since upgraded to Nextcloud Desktop-Client 3.13.2 (earlier versions were NOT affected)
```

**Comment by fuelfoundry** [comment]
Also experiencing this on Mac Client v3.13.2. Thought it was due to the server upgrade to 29, but also upgraded the client at the same time. Deployed a new server, issue persists. Moving files to a temp directory out of the Nextcloud folder and back in is an alternate workaround to circumventing the bug.

**Comment by fuelfoundry** [comment]
This may or may not help, was able to resolve this through:

- Backup/Duplicated NC folder (i.e. ./NAME-Archive)
- Deinstall NextCloud client completely: Remove (and backup first) all NC related configuration files (ie nextlcoud.cfg, etc...)
- Reboot, reinstall, launch Nextcloud
- During initial configure, ensure directory is set to your previous/existing NextCloud target folder
- NextCloud will provide an option to wipe the target directory and sync down when you point at the existing data folder containing existing files.  Go this route (after ensuring your backup is sound).
- Sync 100% down from the server, once completed, all issues which previously existed, cleared up, which additionally including a weird bug, where copying multiple files lead the client freezing up.  

Theory: A discrepancy between a local cache and the server data formed, resulting in this behaviour.

**Comment by Githopp192** [comment]
@fuelfoundry thanks, but your proposal  - but the ultimative solution for such errors cannot be to wipe and re-install everything

i think the solution must come from the software developers in a new (fixed) version.

**Comment by Githopp192** [comment]
Can confirm this bug also on mac .. drag & drop not possible by finder anymore

**Comment by Githopp192** [comment]
Nextcloud Server version
29.0.4

Nextcloud Desktop Client version
3.13.3

Issue seems to be fixed ==> well done :-)
