### ISSUE TITLE
Client 2.3.3.1 sync with external storage (SMB) stops when one file is inaccessible

### ISSUE THREAD

**Issue by git-dd** [nextcloud/desktop#693]
user logs in with ldap and tries to sync from external storage (SMB)

### Expected behaviour
sync all files and folders that are accessible and leave out those which are not accessible

### Actual behaviour
when you configure the client to sync a folder structure it stops as soon as there is an inaccessible file (no read rights for the user) with "503 Service Unavailable" and doesn't sync the rest

### Steps to reproduce
1. create a folder structure on an external storage
2. change the rights of one file within this structure, so that the user can't access it
3. try to sync the whole structure with the nextcloud client (windows or mac - same problem)
4 . -> it will stop the synchronization process as sonn as it gets to the file, that is inaccessible

### Client configuration
Client version: 2.3.3.1 (also tried "2.5.0.61251-Debug-20180803-beta1")

Operating system:
Windows 10 / Mac

OS language: German

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: Ubuntu 16.04.5 LTS

Web server: Apache/2.4.18

Database: mysql  Ver 15.1 Distrib 10.2.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version: PHP 7.0.32-0ubuntu0.16.04.1

NextCloud version: 13.0.6

Storage backend (external storage): Windows Server 2016, accessed via SMB3

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!

**Comment by vizion8-dan** [comment]
Hi, sorry for reopening this. I have seen this behavior on Nextcloud 20.0.7 with an actual 3.x client on Windows.
Besides versions, exact same thing as topic starter described. The inaccessible file in our case was a filename containing an "#", resulting in a 503 and stopped syncing.

**Comment by vizion8-dan** [comment]
Hi @camilasan! AFAIK I can not reopen this issue, should I open a new one? (I think this fits in here or might at least be related)

We use the exact setup with nc 20.0.7, LDAP, and an SMB-share. The problem still occurs on a current Nextcloud client version.

We also came across this issue when a file on the SMB share (which is an external storage in Nexcloud and shared and synced to the nextcloud-client of users "A" - "Z") is kept open elsewhere (by user "A" directly via SMB) and another user "B" tries to, for example rename the parent directory (of this file) on his nextcloud-client.

I know, this must fail as the file/path should be locked and thus not be changeable/writeble.  Actually this stops the whole sync-process on the client in an endless loop.

I think it would be better to present the user an error message and keep syncing the rest.
