### ISSUE TITLE
[Bug]: Release 3.12.7 and V3.13.x - Excel says "Overwrite changes"

### ISSUE THREAD

**Issue by Mika-6-9** [nextcloud/desktop#6933]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

![image](https://github.com/user-attachments/assets/175ec14e-c91a-41cb-9aef-b09cb104d787)

### Steps to reproduce

Save Excel file

### Expected behavior

no message

This is a known bug which is normally resolved by https://github.com/nextcloud/desktop/pull/6212

When we look at the PRs, we see:
![image](https://github.com/user-attachments/assets/20d67ab7-17cd-4fda-832f-6a7473484df3)
Does the red cross mean that this PR is not pushed in the code of this release? (I don't know Github too well)

Otherwise, if this PR is included in the code of this release, this does not correct this problem.

### Which files are affected by this bug

Excel

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official SNAP package

### Nextcloud Server version

27.1

### Nextcloud Desktop Client version

3.12.7

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by tomdereub** [comment]
Same here with nextcloud 28.0.6 and nextcloud desktop 3.13.3 on windows 10.
When the bug occurs, in my case always with excel, it seems that the lock file ~$nameoffile.xlsx isn't created. So without the lockfile, excel can't know if the file has been modified by someone else or not.
Now I don't understand why excel sometimes doesn't success to create the lock file on sync folders.
I can give some logs if it helps, and if you explain how to do.

**Comment by Mika-6-9** [comment]
Hi
For information, still current with version V3.13.4 (not tested with V3.14 or 3.14.1 because these versions do not seem stable to me)

**Comment by tomdereub** [comment]
Still current with version 3.14.3.

**Comment by Mika-6-9** [comment]
Yes

**Comment by Mika-6-9** [comment]
https://github.com/nextcloud/desktop/pull/7572

**Comment by mgallien** [comment]
> Also with 3.15 Could this have something to do with changes in files that are not recognized by Nextcloud client. This issue is not the only issue I have with Nextcloud. Moving files using the windows file Explorer between Nextcloud folders is also giving problems.

If you have issues with renaming files or moving files or folders, please do not post it here and report it separately such that one has a chance to investigate your report and maybe solve a bug for all.

**Comment by mgallien** [comment]
@Mika-6-9
thanks for the hint about this issue
closing as #7572 is the fix for this

**Comment by GHBLoos** [comment]
> > Also with 3.15 Could this have something to do with changes in files that are not recognized by Nextcloud client. This issue is not the only issue I have with Nextcloud. Moving files using the windows file Explorer between Nextcloud folders is also giving problems.
> 
> If you have issues with renaming files or moving files or folders, please do not post it here and report it separately such that one has a chance to investigate your report and maybe solve a bug for all.

There already is an issue for that (#6151 ). Because I had both issues, I thought maybe there was a relation between the two issues.

**Comment by GHBLoos** [comment]
Currently at 3.15.2 and I haven't seen the 'overwrite' message for a while. I will post here when it shows up again (or not).

**Comment by JlXFjudAxpzHnK9** [comment]
I have the same bug with 3.15.3:
![Image](https://github.com/user-attachments/assets/0edb0aa6-ebf5-4040-b40c-1c02b04ad8eb)
![Image](https://github.com/user-attachments/assets/3342ed3b-3950-4795-af96-d59f8811924c)

**Comment by Mika-6-9** [comment]
With version 3.15.3, I only received this message once in about two months of use, but I don't know why. That's not much, but why was there a message, there shouldn't be one.
(With NC 29.0.10)
