### ISSUE TITLE
AppImage: fails to start with libssl related error msg

### ISSUE THREAD

**Issue by sk1p** [nextcloud/desktop#694]
Trying to start the `Nextcloud-2.3.3-x86_64.AppImage` I get the following error message:

```
Auto configuration failed
139873363961792:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139873363961792:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139873363961792:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139873363961792:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
```

This is on Debian sid, and a few weeks ago this used to work fine. It appears the latest libssl packages of Debian are not compatible with the Nextcloud client:

```
$ dpkg -l | grep libssl
ii  libssl-dev:amd64                          1.1.1-1                         amd64        Secure Sockets Layer toolkit - development files
ii  libssl-doc                                1.1.1-1                         all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.2:amd64                         1.0.2o-1                        amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                           1.1.1-1                         amd64        Secure Sockets Layer toolkit - shared libraries
```

Let me know if you need more information, and thanks for building Nextcloud!

cc @TheAssassin

**Comment by TheAssassin** [comment]
"Works fine on my machine". Seems like the system SSL lib is used indeed. libssl broke their API on a non-major release, I guess. `1.0.x` != `1.1.x`, for some reason we will never understand.

Obvious but non-ideal solution: bundle it.

Better solution: it seems the AppImage binary was linked to something like `libssl.so.1`, which is an alias to the "latest" version. Perhaps it could be linked to some "more version specific" name, e.g., `libssl.1.0.0`. Investigation needed.

CC @probonopd this is one of these Linux desktop platform issues...

**Comment by sk1p** [comment]
This may be the job for a linter, that takes an appimage as input and checks for common linking errors like this.

**Comment by probonopd** [comment]
Like this? https://github.com/AppImage/AppImages/blob/master/appdir-lint.sh

**Comment by camilasan** [comment]
Hi, like in other issues, I would suggest you to try one of our daily builds.

**Comment by sk1p** [comment]
Thanks @camilasan - the [daily build](https://github.com/nextcloud/desktop/wiki/Daily-Builds) works indeed!

**Comment by probonopd** [comment]
> But we could use the script as inspiration for linuxdeploy's future "AppDir verification/linting".

Please extend this existing script, don't start a new one. Because this one is what we are actively using, e.g., for AppImageHub testing.

**Comment by TheAssassin** [comment]
@probonopd linuxdeploy will test different aspects. And a little bit of redundancy never hurts in terms of testing.

@camilasan would you please release a new version soon then? The 2.3.3 build is really outdated, and users have issues.

**Comment by mgallien** [comment]
Can you still reproduce this bug with the latest version ?
If this is fixed, can you close this issue ?

**Comment by sk1p** [comment]
Works for me.
