### ISSUE TITLE
[Bug]: Please re-open issue 5094, bulk upload still triggers 100%CPU client usage and hangs 

### ISSUE THREAD

**Issue by alerque** [nextcloud/desktop#6941]
Issue #5094 was closed over a year ago, but dozens of reporters have confirmed that it is not actually fixed. I don't know how the ongoing comment activity hasn't triggered any developer attention (perhaps it got muted by the relevant issue triage folks?), but even if nobody can figure out what is going on I believe the issue should be re-opened until the actual root cause is found and fixed.

Windows, Mac, and Linux clients (all versions) are still affected by this bug when bulk uploads are enabled.

**Comment by kupietools** [comment]
Thank you @alerque for bringing extra notice to this. I would be a big help to me if this issue was fixed.

**Comment by alerque** [comment]
This issue doesn't need triage. The triage system needs triage—that's why I had to open this issue to link back to another one.

And actually not just one, there are at least half a dozen duplicates of this issue linking back to at least two largish threads.

**Comment by joshtrichards** [comment]
Let's take this to #6990 for now.
