### ISSUE TITLE
Make desktop clients look more native: use native icons

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#6944]
### TODO:
-  All items usually have icons
 ![Image](https://github.com/nextcloud/desktop/assets/42591237/215ba9d5-5b23-44eb-9795-c30cb1d71817) 
- the dropdown is usually rather 3 dots: 
![Image](https://github.com/nextcloud/desktop/assets/42591237/17eaeee3-382f-49d9-94dd-cf4f08de5f6a) 
![Image](https://github.com/nextcloud/desktop/assets/42591237/a39790e1-601d-48b7-8c69-de7bb2cc91f9)

### Change it for:
- [ ] Mac
- [ ] Windows
- [ ] Linux

See #6639

**Comment by jancborchardt** [comment]
Also related, this existing issue on discussing about icons for the settings dialog: https://github.com/nextcloud/desktop/issues/5177

**Comment by Rello** [comment]
the icons were changed but we do not have further possibilities here.
To show platform specific icons, we would need to ship several custom QT builds with different icon sets, which is not something we want. 
The next level of "native" will be achieved with the native clients.
