### ISSUE TITLE
 Make desktop clients look more native: use native buttons 

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#6945]
### TODO:
- Adjust button style to be native (basic button look, only slight rounded corners, not pill-style, no color).

### Change it for:
- [ ] Mac
- [ ] Windows
- [ ] Linux

See #6639

**Comment by Rello** [comment]
![Image](https://github.com/user-attachments/assets/31eb885f-281c-4d4e-8393-e4b349a20173)
This was done with the QT implementation
