### ISSUE TITLE
32 bit linux AppImage?

### ISSUE THREAD

**Issue by KaMiila** [nextcloud/desktop#695]
I have an old 32 bit linux system that cannot support qt5.  Upgrading this system will not happen, so please no converstion telling me to update the system.  The AppImage file is only in 64 bit.  I am asking why 32 bit machines are being neglected from this project (especially old machines)?  I require a desktop client application to sync my older machines to my nextcloud sever, but cannot find one as the linux desktop application requires (IMO) a bleeding edge version of qt5 that has a lot of difficulties (if not impossibilities) compiling on older systems.  Can you please provide a 32 bit linux binary?  Or is there some other option I can use to sync data?  A script perhaps?

**Comment by michaelstingl** [comment]
Pre-2.4 versions from the upstream project are available for 32-bit:
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop:client-2.3.4&package=owncloud-client

**Comment by camilasan** [comment]
Hi @KaMiila, did you check our forums at help.nextcloud.com? At the moment we don't provide it, but other people might have a solution for it.

**Comment by natrius** [comment]
Isn't the x86 for 32bit? https://download.nextcloud.com/desktop/releases/Linux/

**Comment by camilasan** [comment]
I am sorry, but I don't think we can provide a Desktop client that uses such an old version of Qt. 32 bit maybe... but not Qt4.
