### ISSUE TITLE
Add TOTP 2FA support to Desktop Client

### ISSUE THREAD

**Issue by ArvindNair001** [nextcloud/desktop#696]
### Expected behaviour
To ask for TOTP code while login in

### Actual behaviour
Shows error message Server connection forbidden, Also signin credentials from web is not working as it does not thing.

### Client configuration
Client version: 2.3.3

Operating system: Arch Linux (Gnome 3.30)
OS language: English (US)

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2

Client package (From ownCloud or distro) (Linux only): AUR(git)

### Server configuration

Operating system: Ubuntu server 16.04 LTS

Web server: Apache 2

Database: MySQL

PHP version: 7

Security: 2FA enabled

**Comment by criwe** [comment]
You need to use the app password instead of the standard web password.

**Comment by camilasan** [comment]
Hi, Could you try one of our daily builds? 2FA is available with our new web login.
https://download.nextcloud.com/desktop/daily/Linux/

**Comment by fwsGonzo** [comment]
I have the same problem. Will try one of the daily builds.

**Comment by ArvindNair001** [comment]
Thanks..!! It works great
