### ISSUE TITLE
sync client stop syncing if files are not accessible

### ISSUE THREAD

**Issue by jankowa** [nextcloud/desktop#698]
I have external file storage with smb/cifs. If some of the files are are not accessible but listet because of ownerships/rights inside the underlying file system, nextcloud sync client stops syncing with error:

|Operation canceled|

The sync client starts immediately to sync again and there is never a synced state. I would expect that access rights are honored and sync is completed even if some files or folders are not accessible.

Nextcloud Server: 14.0.0
Platform: Debian Linux 9.x (Server and Client)
Nextcloud Sync-Desktop Client Version 2.3.3-20180415.190957

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
