### ISSUE TITLE
[Bug]: Main Dialog color scheme nearily illegible (gray on gray)

### ISSUE THREAD

**Issue by redwing-bb** [nextcloud/desktop#6984]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On Bazzite Linux, running Gnome under Wayland, using the Nextcloud Desktop flatpak, the main dialog window appears gray on gray and is difficult to read. 

### Steps to reproduce

Install Bazzite Linux Gnome version, install Nextcloud Desktop, run Nextcloud Desktop, click the nextcloud icon in the top bar, select "Open main dialog" from the menu.

### Expected behavior

The scheme for the main dialog should produce legible text and a clear UI. 

### Which files are affected by this bug

com.nextcloud.desktopclient.nextcloud

### Operating system

Linux

### Which version of the operating system you are running.

Bazzite (FROM Fedora Silverblue 40)

### Package

Other

### Nextcloud Server version

29.0.4

### Nextcloud Desktop Client version

3.12.3

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by redwing-bb** [comment]
![Screenshot from 2024-08-01 13-30-21](https://github.com/user-attachments/assets/6e187bb8-b784-4965-806b-2c6c3d2efbf8)

**Comment by redwing-bb** [comment]
launching from CLI (flatpak run com.nextcloud.desktopclient.nextcloud) the client produces the following output: 

        QSocketNotifier: Can only be used with threads started with QThread
        qt.qpa.qgnomeplatform: Could not find color scheme  ""
        nextcloud.gui.application: Migrating old config from "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud"
        nextcloud.gui.application: Failed to move the old config directory to its new location ( "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/data/Nextcloud" to "/home/redwing/.var/app/com.nextcloud.desktopclient.nextcloud/config/Nextcloud" )
        nextcloud.gui.application: Will move the individual files ("Nextcloud_sync.log")
        nextcloud.gui.application: Fallback move of  "Nextcloud_sync.log" also failed

**Comment by mgallien** [comment]
https://download.nextcloud.com/desktop/daily/linux/

**Comment by redwing-bb** [comment]
Tested with the latest daily, linux-20240812.AppImage and can confirm that the themeing problem is not present in current builds, thanks.

![image](https://github.com/user-attachments/assets/91f05f41-7131-498c-8ac4-26185dd04828)
