### ISSUE TITLE
`make doc-man` fails

### ISSUE THREAD

**Issue by yan12125** [nextcloud/desktop#699]
### Expected behaviour
`make doc-man` builds man pages `nextcloud.1` and `nextcloudcmd.1`

### Actual behaviour
Neither is built

### Steps to reproduce
1. `cmake .`
2. `make doc-man`
```
$ LANG=C make doc-man
Running Sphinx v1.8.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
pickling environment... done
writing... WARNING: "man_pages" config value references unknown document nextcloud.1
WARNING: "man_pages" config value references unknown document nextcloudcmd.1

build succeeded, 2 warnings.

The manual pages are in man1.
Built target doc-man
```

### Client configuration
Client version: git-master

Operating system: Arch Linux x86_64 up-to-date

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2

Client package (From ownCloud or distro) (Linux only): built from source

Installation path of client: N/A - build issue

### Server configuration
N/A - client issue

**Comment by Aentfs** [comment]
I'm closing the issue because the pr should have fixed the problem. If the problem still exists on the master branch, feel free to reopen it and I will take another crack at it.
