### ISSUE TITLE
windows client consumes up 80 percent cpu if files are open

### ISSUE THREAD

**Issue by anolting** [nextcloud/desktop#70]
hi,
the windows client is consuming up to 80% if it tries to sync exclusively opened files like MS Outlook it does with its .pst/.ost files. The client should not try to sync those files before they closed. Here it´s actually around 60 percent.
![grafik](https://user-images.githubusercontent.com/12763750/33239770-68f797ca-d2a9-11e7-83d4-06e91f569bcc.png)

**Comment by camilasan** [comment]
Do you have the same with the latest version of the client?

**Comment by anolting** [comment]
Hi Camila,
It's not more that high, but still to high: ~30% and the sync process is blocked by the .pst file. This drain the battery and when I hear the speed of the laptop fan, I assume that the CPU is under much more load as the task manager indicates.

The file handling should be improved to detect properly open files with a lock and should sync the files after lock has been released.
![grafik](https://user-images.githubusercontent.com/12763750/40249802-74d8371c-5ad4-11e8-97a3-7234d48c7125.png)

**Comment by flexsrgc** [comment]
Hello,
same issue here - i have started Telegram-Desktop-Client all Day.
CPU is most time at 25%
Without reboot nextday sometimes at 75%
When i close Telegram, it works normal. Use 0-25% CPU for sync.

System: win7
next-cloud-client v2.3.3
Open Files: Telegram-Desktop-Client 

#=#=#=#=# Propagation starts 2018-11-16T11:40:40 (last step: 6218 msec, total: 6218 msec)
||Telegram/tdata/working|INST_NEW|Up|1542364717||0||3|Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.|0|0|0|||INST_NONE|

**Comment by anolting** [comment]
Update: starting with NC client 2.5 the CPU usage fell down to 0% even when files are locked.
Good job.
Best regards, Alex
