### ISSUE TITLE
Usage of libsecret

### ISSUE THREAD

**Issue by mase76** [nextcloud/desktop#701]
Hi!
Does the client use libsecret? When I remove the deprecated libgnome-keyring, the
client does not remember my login.

**Comment by camilasan** [comment]
Hi! We use qtkeychain library. I believe there is a similar issue open already.

**Comment by mase76** [comment]
When I build with libsecret installed, it works as it should.

**Comment by Germano0** [comment]
> Hi! We use qtkeychain library. I believe there is a similar issue open already.

Can you please show us the the URL?
I reached this bugreport while investigating on https://bugzilla.redhat.com/show_bug.cgi?id=1652973
