### ISSUE TITLE
Daily builds MacOS missing

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/desktop#702]
Regular daily builds for MacOS stopped at 9.9.2018
Is there a specific reason?

Available youngest  builds as of 03.10.2018:
https://download.nextcloud.com/desktop/daily/Mac/Updates/
`Nextcloud-qt5.9.2-2.5.0.20180909daily.pkg.tbz | 2018-09-09 20:13 | 126M `

https://download.nextcloud.com/desktop/daily/Windows/
`Nextcloud-2.5.0.61451-daily-20181003.exe | 2018-10-03 01:14 | 83M `

++umgfoin.

**Comment by rullzer** [comment]
I'll have a look once I'm back home. Seems the build mac has some issues on the new network.

**Comment by camilasan** [comment]
https://download.nextcloud.com/desktop/daily/Mac/Installer/Nextcloud-qt5.9.2-2.5.0.20181008daily.pkg
