### ISSUE TITLE
3.14RC1 Mac OS: sync icons not showing

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#7056]
Hi team,

Mac OS: 3.14Rc1 is often not showing icons and share menu in synced folders (while the sync process seems to proceed as usual). Seems to happen pretty reliably after sleep of laptop.

debug archive (internal link): https://cloud.nextcloud.com/index.php/f/10268210

**Comment by claucambra** [comment]
Duplicate of #5193 so closing, but thanks for the debug archive :)
