### ISSUE TITLE
"Error: Could not create named generator Visual Studio 15 2017 Win64" when trying to compile with Ubuntu 18.04

### ISSUE THREAD

**Issue by pachulo** [nextcloud/desktop#706]
I'm trying to compile the desktop client with Ubuntu 18.04, but I found some issues:

- In this section https://github.com/nextcloud/desktop/wiki/System-requirements-for-compiling-the-desktop-client#linux there's an error; the package `libqt5webengine5-dev` does not exists in ubuntu, its equivalent is `libqt5webkit5-dev`

- When trying to generate the build files with cmake as explained here https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client#311-generate-the-build-files I get this error:
```
CMake Error: Could not create named generator Visual Studio 15 2017 Win64

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.
```
For what I've read it's a problem with the `cmake` version, but is `3.10.2` in Ubuntu 18.04:

- https://packages.ubuntu.com/search?keywords=cmake&searchon=names&suite=all&section=all

Shouldn't that be enough?

Thanks!

**Comment by pachulo** [comment]
Yeah, it seems that is working now!
What about the package name in the Wiki? For what I've seen now it seems that the correct package should be `qtwebengine5-dev`, not `libqt5webkit5-dev` as I said in my first comment.

**Comment by camilasan** [comment]
I had to look up about it myself and I found this: https://forum.qt.io/topic/83394/installing-qt5-webengine-ubuntu-16-04

Did you try to install it with the Qt installer - the open source one from https://www.qt.io/download?

**Comment by pachulo** [comment]
No, I did not use the Qt installer but the distro packages, because I understood that was what the instructions were stating.

Besides that, I'm trying to get a working snap for this, so installing the packages from the repos is the best way for it.

**Comment by camilasan** [comment]
Ok, I really don't know about snap. But as I recall now I got that instructions for Ubuntu from someone else in an issue. Let me look for it.

**Comment by camilasan** [comment]
Here: https://github.com/nextcloud/desktop/issues/547#issuecomment-418472271
Maybe we can ping @florealcab about it.

**Comment by florealcab** [comment]
I don't use ubuntu but KDE Neon (based on ubuntu). It has the libqt5webengine5-dev package, I don't know it's equivalent for ubuntu unfortunately
