### ISSUE TITLE
[Bug]: Unknown error

### ISSUE THREAD

**Issue by camilasan** [nextcloud/desktop#7074]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When syncing sometimes the client will display useless error to the user like 'Unknown error'.

![error](https://github.com/user-attachments/assets/93a8d9ff-61de-4678-8631-f85ffabbdfa2)

### Steps to reproduce

1. Sync the client
2. Check for syncing errors
3.  The error displayed is not useful or actionable

### Expected behavior

The error should help the user to solve the issue.

### Which files are affected by this bug

None

### Operating system

macOS

### Which version of the operating system you are running.

latest

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

latest

### Nextcloud Desktop Client version

3.14.0-rc1

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/47853
