### ISSUE TITLE
Nextcloud client show notifications from "owncloud" instead of "Nextcloud"

### ISSUE THREAD

**Issue by rcpao** [nextcloud/desktop#708]
### Expected behaviour
Nextcloud client should show notifications from "Nextcloud".

### Actual behaviour
Nextcloud client show notifications from "owncloud".

![img_20181007_154510](https://user-images.githubusercontent.com/3468574/46588109-73441600-ca4b-11e8-8d38-e0f10bf521d9.jpg)

### Steps to reproduce
1. Let screensaver activate.
2. Create some Nextcloud activity such as uploading pictures.
3. Press Shift to see the activity notification from Nextcloud client identifying itself as "owncloud".

### Client configuration
Client version:
Version 2.3.3

Operating system:
VERSION="18.04.1 LTS (Bionic Beaver)"

OS language:
en

Qt version used by client package (Linux only, see also Settings dialog):
Version 2.3.3. For more information please visit nextcloud.com.
By Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, Olivier Goffart, Markus Götz and others.
This release was supplied by the Nextcloud GmbH
Copyright 2012-2017 ownCloud GmbH
Licensed under the GNU General Public License (GPL) Version 2.0.
Nextcloud and the Nextcloud Logo are registered trademarks of Nextcloud GmbH in the European Union, other countries, or both.

Client package (From Nextcloud or distro) (Linux only):
deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic main

Installation path of client:
/usr/bin/nextcloud

**Comment by camilasan** [comment]
I am quite sure this is fixed in master. Could you try one of the daily builds with a test account and let me know https://download.nextcloud.com/desktop/?  Thanks.

**Comment by almereyda** [comment]
Nextcloud Desktop 2.3.3 / 57bc7918d7b0650c116f3512787f7677d4e5ab17 from the Fedora repositories shows the same behaviour.

**Comment by mjanssens** [comment]
Running Nextcloud Desktop client 2.5.1 on openSuse Tumbleweed with Gnome Shell.
Notifications are now using "Nextcloud" as wel as a correct icon.
I think we can close this issue.
Thanks
