### ISSUE TITLE
i18n: String uses only placeholders

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/desktop#7095]
Is this meant to be translated? 

https://github.com/nextcloud/desktop/blob/d2cfa240d457288a4db48466f49896da5b36435a/src/gui/owncloudgui.cpp#L434

Reported at Transifex.

Git blame brings me to @nilsding @mgallien

**Comment by nilsding** [comment]
my thought was that other translations might have a need to reorder that.  if there's no need for that I can change that to a plain `QString` too.

**Comment by nilsding** [comment]
It's the folder to be synced, followed by a status message (e.g. _Syncing 25MB (3 minutes left)_, _Waiting to start syncing._, _Last sync was successful._)

**Comment by nilsding** [comment]
got it, will add an example comment :)
