### ISSUE TITLE
[Bug]: Settings panel not respecting system theme (no Dark mode)

### ISSUE THREAD

**Issue by UnderEu** [nextcloud/desktop#7125]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating client to 3.14.0, the settings panel is not respecting the system theme, in other words the window is using white theme while the system is using Dark theme.

### Steps to reproduce

1. Install 3.14.0 client
2. Open settings panel

### Expected behavior

Client follows the system theme (Dark, for the matter) instead of being stuck on the white one.

### Which files are affected by this bug

No stored file

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu MATE 22.04

### Package

Other

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

[Debug.zip](https://github.com/user-attachments/files/17005598/Debug.zip)

**Comment by DireMunchkin** [comment]
I'm also affected on Windows 10.

**Comment by mgallien** [comment]
@UnderEu could you please test with other Qt using application ?
I am curious about which Qt UI style you are using. Can you provide a screenshot ?

**Comment by UnderEu** [comment]
> [@UnderEu](https://github.com/UnderEu) could you please test with other Qt using application ? I am curious about which Qt UI style you are using. Can you provide a screenshot ?

![Image](https://github.com/user-attachments/assets/693bcb08-5c25-4781-9623-b0cab36ae052)

Some of the Qt apps I have installed in the screenshot, alongside Nextcloud Client settings panel

MATE version: 1.26.0
OS version: 22.04.5
Theme: Yaru-purple-dark

Client version (currently): 3.14.1
Source: ppa:nextcloud-devs/client

**Comment by SwallowYourDreams** [comment]
Same issue for me on

Linux Mint 21.3 (based on Ubuntu 22.04)
Cinnamon DE 6.0.4 (Theme: Mint-Y-Dark-Red)
Nextcloud client 3.14.1 (ppa:nextcloud-devs/client)
Nextcloud server 30.0.0

Other qt-based applications (e.g. KeepassXC, VLC, Transmission) are unaffected.

**Comment by Rello** [comment]
Hello,

QT has different kind of dependencies and shortcomings in some areas.
As this window is not in daily view and it is technically working properly, we do not have a change planned at the moment.

Regards,
Marcel

**Comment by UnderEu** [comment]
> [...] As this window is not in daily view and it is technically working properly, we do not have a change planned at the moment.


To make a ridiculous analogy: because I have some health conditions that won't show any symptoms unless I eat or drink something specific, if the food maker is aware of the possibility of such condition with these specific people, feedback must be collected and issue should be addressed in some way (by me or them, ideally both).



I understand your point: in fact I don't keep looking at the client window all day long but it looked perfectly fine before v3.14 and now it doesn't - the reason this bug exists. If is this a distro dependency issue + you don't have the time to work on it for whatever reason? Fine, remove v3.14 from "jammy" PPA and then it's totally on me one of these two things: 1. Downgrade and rely on the older client version (not ideal, especially when it comes to security); or 2. Update my distro at some point and hope the client works as intended in the newer version.

I am not asking you to support each and every DE on each and every OS version for each and every client app you're releasing, but if you decided not to fully support the OS version I'm using, even if the core functionality is perfectly fine, make everyone aware of the directions you're taking and don't make packages available for systems you don't intend to officially support. I am not a developer, I have no capabilities nor time available to work with source code, to read and understand each and every change that leaded to this dependency change but until (if) anyone else will make this effort and work on any kind of fix, it's better than saying "we won't take care of this" and keep this available for eveyone in a broken state - yes, it's only on visuals but it's still broken.


This is only my opinion

**Comment by Rello** [comment]
Hello,
thank you for your feedback.

here is the other angle on this: we know that there are some shortcomings in the current client and we are putting more resources in into this now. 
But to be effective we also need to visibility on the todos based on the priority. And 1000 open (partly 3 years old) tickets do not help to keep focus on the real important tasks.
So I have to apply some filtering to be able to work effectively on the client overall

**Comment by SuperCowProducts** [comment]
@UnderEu thanks for reporting, interesting to know this is simply a missing issue as it is affecting others: we now have somewhere to start if one wanted to try implementing a solution.
