### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PhMetzger** [nextcloud/desktop#7126]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

On Ubuntu 22.04.5 LTS, 3.14 crash at startup...

I had to install qt6-qpa-plugins to solve it.

Not solving [#7123](https://github.com/nextcloud/desktop/issues/7123)

Message at startup

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abandon (core dumped)

``` 

### Steps to reproduce

1. Right click on the file
2. Click on Share Options
3. The share dialog does not display the option to share by e-mail
...

### Expected behavior

When clicking on the share dialog, share by e-mail should be an option.
...

### Which files are affected by this bug

-

### Operating system

Linux

### Which version of the operating system you are running.

 Ubuntu 22.04.5 LTS

### Package

Distro package manager

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.14

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by craisp** [comment]
I had the same "xcb" error, but manually installing `qt6-qta-plugins` didn't solve it for me. Nextcloud Desktop does not start and does not give me any hint, what might be the problem:
```
nextcloud --logwindow
[1]    8531 IOT instruction (core dumped)  nextcloud --logwindow
```

```
nextcloud --version
Nextcloud version 3.14.0-20240914.150754.d8fcb9273-1.0~jammy1
Using Qt 6.2.4, built against Qt 6.2.4
Using Qt platform plugin 'xcb'
Using 'OpenSSL 3.0.2 15 Mar 2022'
Running on Pop!_OS 22.04 LTS, x86_64
```
