### ISSUE TITLE
[Bug]: macOS update fails

### ISSUE THREAD

**Issue by jameskimmel** [nextcloud/desktop#7130]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Nextcloud fails to update from 3.13.4 to 3.14.0

### Steps to reproduce

1. Search for updates
2. try to install update 3.14.0

### Expected behavior

install update

### Which files are affected by this bug

n/a

### Operating system

macOS

### Which version of the operating system you are running.

macOS 14.6.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.13.4

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

<img width="683" alt="Bildschirmfoto 2024-09-16 um 15 49 24" src="https://github.com/user-attachments/assets/969e8821-1612-4a79-8f00-b2fd12b73d52">

after that there is also an update error text:

<img width="674" alt="Bildschirmfoto 2024-09-16 um 15 43 45" src="https://github.com/user-attachments/assets/2924ba76-16f5-4c9c-8228-4549ef81a7e5">

**Comment by jameskimmel** [comment]
Manually updating to 3.14.0 by downloading the file works. 

But the updater seems to broken after the update
<img width="698" alt="Bildschirmfoto 2024-09-16 um 15 54 20" src="https://github.com/user-attachments/assets/11aa64e4-5e41-4ff1-af37-cb75e4a61db8">

**Comment by mgallien** [comment]
this is fixed now
sorry

**Comment by jameskimmel** [comment]
The update error is still there.
