### ISSUE TITLE
Q_NULLPTR is not used.

### ISSUE THREAD

**Issue by tuxmaster** [nextcloud/desktop#714]
I have take a look into the current master.
And instead of Q_NULLPTR 0 is used on many header files.
But Qt recommends using of Q_NULLPTR.

**Comment by camilasan** [comment]
Hi, @tuxmaster, feel free to give it a try and update the code. Thanks!

**Comment by codeling** [comment]
If only compilers with c++11 support are used, wouldn't `nullptr` be the better choice?

**Comment by tuxmaster** [comment]
Q_NULLPTR is an alias. So it will use nullptr on an modern compiler and  NULL on old one.

**Comment by mgallien** [comment]
We now requires c++14 and use `nullptr` directly. Closing this issue
