### ISSUE TITLE
[Bug]: Synchronization Failure for Large Folders in Nextcloud macOS App (Version 3.15)

### ISSUE THREAD

**Issue by jowi24** [nextcloud/desktop#7147]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I am encountering an issue with the Nextcloud macOS synchronization app (version 3.15). When attempting to sync large folders, the synchronization process fails, displaying an error message ("Server stopped accepting new streams before this stream was established"), and the sync is aborted. This issue seems to occur consistently with larger directories.

After troubleshooting, I downgraded the app to version 3.11, where the synchronization of the same large folders completes successfully without any errors. This indicates that the issue is likely introduced in version 3.15.

### Steps to reproduce

Install Nextcloud macOS app version 3.15.
Attempt to synchronize a large folder (several GB in size).
Observe that the synchronization process fails with an error message, and syncing is aborted.

### Expected behavior

Sync large folders without error.

### Which files are affected by this bug

no specific file

### Operating system

macOS

### Which version of the operating system you are running.

14.6.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

29.0.5

### Nextcloud Desktop Client version

3.15

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Workaround: Downgrading to Nextcloud macOS app version 3.11 resolves the issue, allowing large folders to sync correctly.

**Comment by pintycar** [comment]
Same issue in Windows 11 Pro... I almost went mad today trying to diagnose it thinking that it must have been the update from 29.0.6 to 30.0.0. It turns out it was the desktop client. Version 3.13.4 works absolutely fine, 3.14.0 shows the issues described above.

**Comment by PhilippSchlesinger** [comment]
@jowi24 this seems to be a duplicate of https://github.com/nextcloud/desktop/issues/7136

**Comment by jowi24** [comment]
Closed as duplicate of #7136
