### ISSUE TITLE
Removing permissions leaves files on sync clients

### ISSUE THREAD

**Issue by ffried** [nextcloud/desktop#7150]
Let's take the following situation

Folder `X`:
   - `Group A`: full access
   - `Group B`: read access

Subfolder `X/Y`:
   - `Group A`: full access
   - `Group B`: read access

Desktop `Client 1` is used by `User U` who is in `Group B`. `Client 1` has synced `X` and `X/Y`.

Now when explicitly **denying** `Group B` to access to Subfolder`X/Y`, the Desktop `Client 1` does not remove Subfolder `X/Y` locally. However, any changes made to the contents of `X/Y` will (obviously) fail to sync.

The only workaround is to selectively disable `X` in the sync preferences and wait for it to be removed. Then re-enable `X` to get only the contents `User U` is allowed to see.

**Environment:**
- NextCloud Server 17.0.2
- GroupFolders 5.0.5
- NextCloud Desktop Mac 2.6.2stable

**Comment by Rello** [comment]
Hello,
thank you for reporting this issue. 
This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.

**Comment by provokateurin** [comment]
https://github.com/nextcloud/groupfolders/pull/3326 could be a potential fix 🤔
