### ISSUE TITLE
group folder stopped syncing from Mac client to server

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/desktop#7151]
I pushed a 50GB directory into a group folder on a MAC 10.12.6  nextcloud desktop 3.1.1.
many files and directories have been  "shared" individually before, but this shouldn't matter as files with same name should be able to reside in different directory structures.

after  ~2GB syncing it stopped
I saw the message sync stopped (or similar)
Finder shows the all  files correctly some of them marked as synced, but many are not synced.

Please How can I convince nextcloud to sync the remaining files and directories?

restart sync doesn't do it. - it seems to look only on the server side ?
enough space everywhere, quota unlimited.

could it be a timeout?
Sometimes the external IP of the desktop changes - I am currently in a hotel - may be a reason.

**Comment by Rello** [comment]
Hello,

thank you for reporting this issue. 

This issue was reported long time ago on old versions and we improved a lot since then.
If the error shows up again, please open an issue for the current versions.
