### ISSUE TITLE
[Bug]: Text not readble with dark mode enabled

### ISSUE THREAD

**Issue by TobiGr** [nextcloud/desktop#7155]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The text is not readable at all in the main window. 

![grafik](https://github.com/user-attachments/assets/6f1712ef-db89-4ab1-bd5d-8ef640b856f0)

### Steps to reproduce

1. Use Windows 10 with enabled dark mode
2. click on tray icon or start the desktop client
3. The text color in the main window for NextCloud desktop is not readable.

### Expected behavior

Blackish text color

### Which files are affected by this bug

how should i know?

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official Windows MSI

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by nuke1984** [comment]
same here, in win10 and ubuntu 20.04. please make a readable dark theme or at least an option to maintain light theme for nextcloud desktop app.
