### ISSUE TITLE
[Bug]: Main window will not open on Windows

### ISSUE THREAD

**Issue by timinator2020** [nextcloud/desktop#7156]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating the client to 3.14, the main dialog no longer shows when clicking on the icon in the system tray. Also, after editing settings the whole app will occasionally crash and need to be restarted.

### Steps to reproduce

1. Click on the Nextcloud icon in the Windows system tray
2. That's it. The main window should open, but doesn't.
...

### Expected behavior

When clicking on the Nextcloud icon in the Windows system tray the main window should open.
...

### Which files are affected by this bug

all files, or maybe none?

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11 Home 23H2

### Package

Official Windows MSI

### Nextcloud Server version

29.0.6

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

There seems to be an issue that has the same symptoms [here](https://github.com/nextcloud/desktop/issues/7123), but that is for Linux and is already closed. My issue is with the Windows client and my Nextcloud directory seems to have Qt6 libraries already, so I don't think it's the same issue (although it may have the same root cause). 

I have had to go back to 3.13.4 since 3.14 would occasionally crash and I couldn't tell if the client was syncing or not.  If needed, I can reinstall 3.14 and gather logs.

**Comment by webneo82** [comment]
Same here on 4 different Windows 11 computers (version 23H2) since upgrading Nextcloud client to version 3.14.0.

**Comment by petiard** [comment]
Same here on Windows 11 Home version 23H2 after upgrading Nextcloud client to version 3.14.0.

**Comment by back21ness** [comment]
Troubleshooting the same issue on several computers now that are running Windows 11 23H2.

After Nextcloud clients auto-updated to v3.14 it just starts and than just closes by itself in 5-10 seconds...

Server version 29.0.5.

**Comment by RVieiraConde** [comment]
I have the same problem, the client does not open when clicking on the icon in the bar, and in dark mode, when adding a new folder, the configuration window is unconfigured
Server version 30.0.0.

![Captura de ecrã 2024-09-19 103727](https://github.com/user-attachments/assets/7da1012d-2189-43c3-bca0-c40a1aaf9a37)
![Captura de ecrã 2024-09-19 103737](https://github.com/user-attachments/assets/081ecbae-feb1-4987-93b0-f2569f42faa2)

**Comment by mgallien** [comment]
we are working on this already
we will merge fixes for the next release as soon as we can
sorry

**Comment by mgallien** [comment]
people please stay on topic
I would hate to have to lock the conversation
this is only about the main dialog not showing up on start on windows

**Comment by mgallien** [comment]
> Troubleshooting the same issue on several computers now that are running Windows 11 23H2.
> 
> After Nextcloud clients auto-updated to v3.14 it just starts and than just closes by itself in 5-10 seconds...
> 
> Server version 29.0.5.

this would be a different issue
this issue is about the desktop client running fine but the UI not showing up

**Comment by micas83** [comment]
Same issue here on 3 PCs (win10 & win11), reverted back to 3.13

**Comment by nspader** [comment]
Same here with 2 PCS

**Comment by pierremorallet** [comment]
Same issue on Windows 10 Entreprise Version 22H2 Build 19045.338 with Nextcloud desktop client v3.14.0. I will try to revert back to an older version. I have some sync conflict to resolve and I don't know how to do this without the main windows.
Note that I tried also to access to the main windows by right clicking on the icon, then selection "open the main windows" in the menu. Same issue.

**Comment by clamp2x** [comment]
I am also experiencing the same issue with the 3.14.0 client version. Nextcloud does not start automatically with Windows, and even when I launch it manually, it immediately closes. I have the 3.13.3 client version, so I rolled back to that version and am currently using it.

**Comment by PasswordIs0000** [comment]
Having the same issue on Windows 11. Just answering here to get a notification from Github :)

**Comment by nuke1984** [comment]
same here on Win10 Build 19045

**Comment by back21ness** [comment]
Daily I am getting new requests from users who updated to v3.14 and now Nextcloud is not working anymore for them.

Why does not Nextcloud pull this update so that it does not get through auto update option to users?
Why is this version still being downloaded from the main website at nextcloud.com?

Strange stuff. I would expect broken updates to be removed so that issues do not spread further to the end users and admins.

**Comment by SavasTheodoropoulos** [comment]
Having the same issue on Windows 11 23H2.

**Comment by ShockHouse5** [comment]
Copying over the workaround:

If you exit Nextcloud, then open Nextcloud, the "Open main dialog" works after that. So it seems like only the initial launch (launch on startup?) exhibits the issue.

**Comment by petiard** [comment]
> Copying over the workaround mentioned here: #7143
> 
> If you exit Nextcloud, then open Nextcloud, the "Open main dialog" works after that. So it seems like only the initial launch (launch on startup?) exhibits the issue.

I confirm (Windows 11 Home).
François

**Comment by mgallien** [comment]
hello all
@timinator2020 and other
I have a custom build with a fix for this bug
could you test it ?
https://cloud.nextcloud.com/s/GegKZ9igm3brEsK
please keep in mind that this build just got tested for this particular issue not for general QA

**Comment by ShockHouse5** [comment]
@mgallien can confirm for Windows 10 that your build fixed the issue. On startup the main dialog opens as expected. 

> hello all @timinator2020 and other I have a custom build with a fix for this bug could you test it ? https://cloud.nextcloud.com/s/GegKZ9igm3brEsK please keep in mind that this build just got tested for this particular issue not for general QA

**Comment by PasswordIs0000** [comment]
It works again for me in the newest NextCloud version. Thanks!
