### ISSUE TITLE
[Bug]: 3.14.0 massive sync issues with E2E encrypted files

### ISSUE THREAD

**Issue by bcutter** [nextcloud/desktop#7204]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When using 3.14.0 and trying to upload a file to an E2EE folder, it will fail.

I completely reset the E2EE for my affected user: issue remained.
Downgraded to v3.13.4: issue completely solved, like it works for https://github.com/nextcloud/desktop/issues/7171 too.

I spent two hours on trying to fix this, also running into another 3.14.0 specific issue (https://github.com/nextcloud/desktop/issues/7205). E2EE with NC is annoying as hell as it breaks every few weeks or at best months. I'm now at a point where I simply can't trust any NC (endpoint) update anymore. No idea how 3.14.0 could be released with so fundamental issues not fixed (not tested enough?).

### Steps to reproduce

1. Update to 3.14.0
2. Upload a file to an E2EE folder
3. Client will refuse to upload, nothing in server logs.

### Expected behavior

Uploading E2EE stuff works as with older client versions.

### Which files are affected by this bug

2024-09.pdf

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

28.0.10

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Should be mentioned at https://github.com/nextcloud/desktop/issues/7191.
Tested with two Windows 11 endpoints, one with normal sync and one with VFS sync, both with same behaviour/output.

**Comment by mgallien** [comment]
@bcutter Could you test again with the 3.14.1 release ?

**Comment by mgallien** [comment]
@bcutter I have no idea why you have this issue and if that could be related to other solved issues in 3.14.1.
You providing such feedback would be very important for us to understand what is happening for you.

**Comment by bcutter** [comment]
I think this issue can be checked quite easily. I'll report back.

**Comment by bcutter** [comment]
Quick check with one (of two previously with 3.14.0 affected) Windows endpoint on 3.14.1: sync in all directions (create, change, delete) working fine again.

**Comment by bcutter** [comment]
Confirmed working again with 2nd (previously with 3.14.0 affected) Windows endpoint. Closing this for now.
