### ISSUE TITLE
[Bug]: Folder selection config randomly removed

### ISSUE THREAD

**Issue by michel-thomas** [nextcloud/desktop#7209]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Sometimes, settings about checked and unchecked folders are reseted and revert to "all checked".
Impact is many files and folders are downloaded but user laptop has limited disk storage.

### Steps to reproduce

1. Launch OS (MacOS 12.4)
2. Work as usual
3. Nextcloud-client settings are back to "all checked" and nextcloud-client starts to download all files

### Expected behavior

Settings remains until explicit change and "Apply" button

### Which files are affected by this bug

all

### Operating system

macOS

### Which version of the operating system you are running.

MacOS 12.4 - Darwin version 21.5.0

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

29.0.4

### Nextcloud Desktop Client version

3.13.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Nothing relevant found
```

### Additional info

Frequency is not regular, it happens twice a day or sometimes all is ok during  a week.

I try to read logs and find something about this unconfiguration, but I don't know where to start, neither which keywords would be useful. Thanks a lot if you have quick analysis tips.

Log files are at: https://cloud.lydra.fr/s/PBjpbopmgXtSQrX

**Comment by mgallien** [comment]
@michel-thomas could you test again using our latest release 3.14.1 ?

**Comment by michel-thomas** [comment]
> [@michel-thomas](https://github.com/michel-thomas) could you test again using our latest release 3.14.1 ?

Ok, I ask the user to test latest version. Thks

**Comment by michel-thomas** [comment]
Client updated to 3.14.0 (and then 3.14.3) and now it works, but facing [other problem](https://github.com/nextcloud/desktop/issues/7136) I wasn't able to confirm the correction quickly.

**Comment by PatrickJosh** [comment]
I am facing the same or a similar problem on Fedora Linux 41 with Nextcloud client version 3.14.2daily.

I noticed that it happens when I try to open the client by using the desktop shortcut and it does not open the UI. Then, I can see that there are two Nextcloud processes on on my machine at the same time, one `/usr/bin/nextcloud --background` and one `/usr/bin/nextcloud`. Apparently, the foreground process is unable to communicate with the existing background process and then proceeds as if there was no other process running. However, the database in which the selective sync config is saved (`.sync_xxxxxxxxxxxx.db`) is still locked by the other exisiting process and thus, the new process overwrites it with an empty config.

I have, however, been unable to make this reproducible.

**Comment by sirnacnud** [comment]
I am also running into this as well on Fedora both 40 and 41. Currently also using 3.14.2.

After setting up an initial sync of only one folder, I let it complete. I then exit the desktop client. Then next time I launch the desktop client, it automatically tries to sync every folder I have in my Nextcloud and excludes the one I already synced.

I can reproduce this every time.
