### ISSUE TITLE
[Bug]: dark mode issues on windows 11

### ISSUE THREAD

**Issue by Byter3** [nextcloud/desktop#7215]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The pop-up window's UI is completlty broken.
![kép](https://github.com/user-attachments/assets/26f70320-f565-484b-84a4-d885b525e7cd)

### Steps to reproduce

Open up the pop-up window

### Expected behavior

UI not broken

### Which files are affected by this bug

a screenshot

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

29.0.4

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ThaDaVos** [comment]
It's broken in multiple ways - it even stops opening after a while and one needs to exit the application and restart it to have the UI open again (Settings UI can still be opened, but one cannot resolve conflicts from there)

**Comment by LMRW** [comment]
> It's broken in multiple ways - it even stops opening after a while and one needs to exit the application and restart it to have the UI open again (Settings UI can still be opened, but one cannot resolve conflicts from there)

Is this one tracked? This one is driving me and clients nuts

**Comment by lucidnx** [comment]
I can confirm both issues mentioned here:
1. UI broken
2. unable to open UI
+ ocasional crash when trying to open UI.

How can somebody release so much broken build?

**Comment by LMRW** [comment]
I'll always be grateful for open source software but I do think nextcloud need to reflect on this and offer an explanation on what happened here as I agree this is totally ridiculous

**Comment by ThaDaVos** [comment]
The issue of not being able to open it is already tracked but also seems to be solved it latest daily (09-26)
https://github.com/nextcloud/desktop/issues/7156

**Comment by Gimzie** [comment]
I'm having similar issues with the new UI on Linux (EndeavorOS) with Nextcloud 3.14.0. It appears to be trying to use the system theme or something, but is missing icons and in general looks very broken/unfinished. I'm not sure what theming it was using in previous versions, but I find it personally preferable because it was consistent across devices.

That's in addition to the multitude of syncing/connection closed errors that the application has been throwing with the new version.

![image](https://github.com/user-attachments/assets/8e4ea552-b4e5-49a1-88a7-f64d7037d313)

**Comment by nmbgeek** [comment]
Same
![image](https://github.com/user-attachments/assets/6acd9909-f6c2-491a-8f13-4e5dbec4f863)

**Comment by ostasevych** [comment]
3.14.1 is not helpful anyway 

![image](https://github.com/user-attachments/assets/fc0baca5-54cc-45a9-b8e0-b3cc068166ba)

**Comment by ostasevych** [comment]
3.14.1 is not helpful anyway on Win10.

My kind suggestion is to keep 3.13.x branch, and place 3.14.x to dev or unstable in order not to confuse users and stop that aggressive self-updating from 3.13 to 3.14.

**Comment by ThowZzy** [comment]
Can second that too !
![image](https://github.com/user-attachments/assets/2d0fc0b1-771f-4c7c-b278-25f45e585835)

**Comment by mgallien** [comment]
please people be patient
we are well aware of those issues but we had to prioritize other fixes to be included in 3.14.1 release
we would very much welcome wider testing of our release candidate during our release process as we cannot ensure issues are discovered without your help
some of the issues in 3.14.0 were never reproduced by the team even if many people were impacted (especially the issue with http2)

**Comment by PeterTucker** [comment]
![Image](https://github.com/user-attachments/assets/08c16421-b89e-4542-ae33-53af4558ca3f)
Nextcloud UI (3.14.1) is completely broken in Windows 10 (21H2 19044.4894).

**Comment by mgallien** [comment]
pending fix https://github.com/nextcloud/desktop/pull/7270

**Comment by mgallien** [comment]
test build from stable-3.14 branch for people interested in testing it
https://cloud.nextcloud.com/s/7rm65tyMDLN4CkF

**Comment by PeterTucker** [comment]
@SavageCore, according to @Rello the fix is coming in the next couple of days... https://github.com/nextcloud/desktop/issues/7269#issuecomment-2472627041

**Comment by PeterTucker** [comment]
@Rello New Dark Fix works great. Thanks guys!

**Comment by arnovdk** [comment]
I can confirm that the fix works well on Windows 10 22H2. Your work is very much appreciated!
