### ISSUE TITLE
No Windows when with startup client

### ISSUE THREAD

**Issue by Moonl1ghter** [nextcloud/desktop#722]
Hello,

I'm having a bug with the Nextcloud-Client on Ubuntu 18.04. It still works fine on my Windows machine.
Using the latest version from the PPA.

Whenever I'm running the client it shows up in htop, takes up ram but no window launches, so can't edit settings etc.

I have attached a log file when running the program.

Hope somebody can help me,

Kind regards

Moonlighter
[nc.log](https://github.com/nextcloud/desktop/files/2476733/nc.log)

Edit: Fixed some typo's.

**Comment by mgallien** [comment]
This is a limitation of the Ubuntu desktop that does not provide a systray to display an icon.
We are working to improve that but normally if you start the application again you should see a window.
