### ISSUE TITLE
[Bug]: Can't upload large files since update to 13.4.0

### ISSUE THREAD

**Issue by gary-grandt** [nextcloud/desktop#7221]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I have installed the new version of the desktop client under Windows. 
Since then I have had problems uploading files larger than a few kB.

I only get the meaningless error message in the client that the file could not be uploaded and the connection was interrupted.

As a cross-check I have installed the client in version 13.3.4 again and the problems are gone.

I have 2 servers and both are running Nextcloud.
One with 29.0.7 and one with 29.0.4.
Both have exactly the same problems with the new client.

### Steps to reproduce

Installing 13.4.0 on Windows -.-
Habe das selbe Problem mit 4 verschiedenen Rechnern.
(In verschieden Netzwerken, mit Windows 10 & 11)

### Expected behavior

Installing 13.4.0 on Windows -.-
I have the same problem with 6 different computers.
(In different networks, with Windows 10 & 11)

### Which files are affected by this bug

File > 10 kB

### Operating system

Windows

### Which version of the operating system you are running.

10 & 11

### Package

Official Windows MSI

### Nextcloud Server version

29.0.7 & 29.0.4

### Nextcloud Desktop Client version

3.14.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

BadRequest Erwartete Dateigröße von 7353646 bytes, aber 6561792 bytes gelesen (vom Nextcloud-Client) und geschrieben (in den Nextcloud-Speicher). Dies kann entweder ein Netzwerkproblem auf der sendenden Seite oder ein Problem beim Schreiben in den Speicher auf der Serverseite sein.

**Comment by mgallien** [comment]
this is resolved with the 3.14.1 release that was published today
