### ISSUE TITLE
[Bug]: nextcloudcmd prejudiced against users named david

### ISSUE THREAD

**Issue by davidc** [nextcloud/desktop#7233]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Following upgrade, nextcloudcmd has begun refusing to sync with the error

```
Error! Please specify only the base URL of your host with username and password. Example:
http(s)://username:password@cloud.example.com
```

Investigating the source finds this naive substring check in src/cmd/cmd.cpp line 348:

```
    if (options.target_url.contains("/webdav", Qt::CaseInsensitive) || options.target_url.contains("/dav", Qt::CaseInsensitive)) {
```

Naturally, since my username is david, the string `nextcloudcmd -s /home/david/Documents/ 'https://david@mycloud.com'` contains the substring `/dav`

### Steps to reproduce

1. Have a username that begins `dav` or `webdav`
2. Try to sync with nextcloudcmd

### Expected behavior

I should not have to change my username in order to sync.

### Which files are affected by this bug

n/a

### Operating system

Linux

### Which version of the operating system you are running.

Debian 12

### Package

Distro package manager

### Nextcloud Server version

29.0.7

### Nextcloud Desktop Client version

3.7.3git

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by claucambra** [comment]
Hi @davidc thanks for bringing this up. I promise we do not have any issues with Davids!

I have pushed #7286 to fix this problem
