### ISSUE TITLE
[Bug]: Text unreadable in Nextcloud pop-up 

### ISSUE THREAD

**Issue by JVT038** [nextcloud/desktop#7234]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

![image](https://github.com/user-attachments/assets/40fab1ac-2d71-43c1-af08-272db0429179)

The text is not readable.

I saw that this was already reported in #7155, but that issue has been closed (while it still exists for me)

### Steps to reproduce

1. Open Nextcloud tray app
2. See error

### Expected behavior

I expect to see a proper, readable pop-up instead of this.

### Which files are affected by this bug

No file, it's just an UI issue

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10 22H2

### Package

Official Windows MSI

### Nextcloud Server version

30.0.0

### Nextcloud Desktop Client version

3.14.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Xendiadyon** [comment]
I also have this issue, in the status windows or when creating a new Sync:
![grafik](https://github.com/user-attachments/assets/ba7c93a2-de58-4449-80db-0a522bfbb1f4)
![grafik](https://github.com/user-attachments/assets/9784ef86-ed15-4628-be67-f77651e2a40d)
![grafik](https://github.com/user-attachments/assets/0de1693d-ee1a-4e52-ae07-d2afe5cd5c06)

I am using Windows 11 with dark theme.
Unfortunately, not every Nextcloud element seems to understand that we are in the dark mode.

In Nextcloud Desktop Client version 3.14.1, but existed already in previous versions.


Is there a possibility to turn of Dark Theme for Nextcloud Client (while still using Dark Theme for Windows?)
I cannot find any setting in the options...
![grafik](https://github.com/user-attachments/assets/95c45908-7f16-4528-9fea-fce35f22d0e4)

**Comment by Xendiadyon** [comment]
#7215

**Comment by gallbotond** [comment]
Same issue here. Looks like the scrollbar also doesn't show properly.
![{F6649753-5FE2-4A62-9A35-AAD2F582EB10}](https://github.com/user-attachments/assets/95dea510-dc61-499d-9afc-22a5d7f8c9cf)

**Comment by MartinWagenbach** [comment]
I have the same issue too.

![Image](https://github.com/user-attachments/assets/9951adfc-5ad8-45dd-a90a-a008d8d7adca)

**Comment by Phlipinator** [comment]
Same Issue here as well!
[Image](https://github.com/user-attachments/assets/8ecebc62-7b5b-479e-9ee5-d74a36c3faa5)
Doesn't seem to chaneg with dark/light mode in windows, however I have only quickly checked this.

**Comment by Jerome-Herbinet** [comment]
Some remaining bugs with 3.14.2 with Linux Mint 21.3 Cinnamon (dark theme UI)
![Image](https://github.com/user-attachments/assets/47acf151-0842-45c2-95e8-2ac9d639ffe4)

**Comment by PrimeGhostDE** [comment]
> > Doesn't seem to chaneg with dark/light mode in windows, however I have only quickly checked this.
> 
> this will be fixed with 3.14.2 this week.

Has not been changed with this version.

**Comment by JVT038** [comment]
> > Doesn't seem to chaneg with dark/light mode in windows, however I have only quickly checked this.
> 
> this will be fixed with 3.14.2 this week.

I tried 3.14.2 and this issue has not been fixed yet. It is still unreadable, whether Windows 10 is in dark mode or light mode.

**Comment by Jerome-Herbinet** [comment]
@claucambra and / or @mgallien, any idea ?

Additional information : it seems that with Linux, the Flatpak version (not tested with AppImage) has a better display than regular deb package.

**Comment by kszwaba** [comment]
The problem also occurs in:
Linux Mint 21.3
nextcloud-desktop  3.14.2-20241021.144050.4eec4f3d3-1.0~jammy1 
with dark theme enable in QT6
![Image](https://github.com/user-attachments/assets/6bb3cb96-56ac-478c-9464-5a5a697d67aa)
![Image](https://github.com/user-attachments/assets/a8f43365-5ccf-4bf3-9401-d4b6981d5d20)

**Comment by JVT038** [comment]
So in 3.15 the UI has definitely improved:
![Image](https://github.com/user-attachments/assets/df35e25c-2d1d-42bf-b6af-494862e0bbb2)

And I guess that since the text has now become readable, this issue can be closed.
