### ISSUE TITLE
[Bug]: stable-3.12 builds are not working (how to reproduce release builds?)

### ISSUE THREAD

**Issue by cluck** [nextcloud/desktop#7249]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

A am looking to rebuild _nextcloud.exe_ with some code changes as a drop-in replacement file for the Windows Nextcloud 3.12.x Client as installed from https://github.com/nextcloud-releases/desktop/releases, that is, keeping all external dependencies like Qt5 unchanged. Given that the many dependencies are intimidating, I was hoping to leverage an existing CI to create a test build.

I am using Github Actions in a fork, which does work in principle, but fails specifically on the stable-3.12 branch: both macOS and Windows fail with build system bugs.

Given that the branch is still actively receiving backports, I wonder if you intend to maintain them in a working condition?

Anyway, my personal motivation for reporting this is to find _any_ working CI to obtain a patched release binary to validate fixes for https://github.com/nextcloud/desktop/issues/7166 in the field without investing a day or three building my own build environment.

1. _macOS Build and Test / macOS Build and Test (pull_request)_ fails:
```
CMake Error: The source directory "/Users/runner/work/nextcloud-desktop/nextcloud-desktop/downloads/git/dev-utils/kshimgen" does not exist.
```

1. _Windows Build and Test / Windows Build and Test (pull_request)_ fails in step _Install Craft Master with Nextcloud Client Deps_:

```
2024-09-30T15:38:16.3830780Z          		 "-o" "D:\_\43a0f8a1\Python-3.11.7\Python\deepfreeze\deepfreeze.c"
2024-09-30T15:38:17.7853592Z          Traceback (most recent call last):
2024-09-30T15:38:17.7867472Z            File "D:\_\43a0f8a1\Python-3.11.7\Tools\scripts\deepfreeze.py", line 460, in <module>
2024-09-30T15:38:17.7868191Z              def generate(args: list[str], output: TextIO) -> None:
2024-09-30T15:38:17.7953987Z          TypeError: 'type' object is not subscriptable
```

### Steps to reproduce

One way is probably for a maintainer to re-run the GitHub Actions.

Another way:
1. Fork nextcloud/desktop to a personal account
2. Checkout stable-3.12
3. Branch to stable-3.12-test and commit some insignificant change
4. Maybe remove most of the .github/workflows except Windows and macOS related
5. Create pull request from stable-3.12-test into stable-3.12
6. Watch the CI steps fail after some 30min-50min

### Expected behavior

CI jobs would pass.

### Which files are affected by this bug

/other

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Other

### Nextcloud Server version

29.0.6

### Nextcloud Desktop Client version

3.12.7

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Nextcloud Server logs

```shell
No additional info
```

### Additional info

No additional info

**Comment by mgallien** [comment]
@cluck may I ask why you are trying to build 3.12 branch ?
You have probably noticed that at least regarding build macOS and windows github actions are building fine in other stable branches

**Comment by cluck** [comment]
3.12.7 is the most recent release on Windows which doesn't crash.

**Comment by mgallien** [comment]
@cluck there is no issue building 3.12, 3.13 or 3.14 branches
there is an issue with the CI windows workflow because no one had time to make it work with the qt5 branches for KDE's Craft and craft blueprints
manual setup of the dependencies is obviously working or we could not do any release.
there is nothing secret or hidden there
anyway, this is not a bug but a request for support
can you please move to the Nextcloud forum (https://help.nextcloud.com) ?
