### ISSUE TITLE
plist ignored server side

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/desktop#725]
hi

Is .plist a server side apache ignore ?

My client (2.5.x) gets a 404 not found in client activity log

Thanks

ZT

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
