### ISSUE TITLE
[Bug]: 3.14.0+ MacOS pkg size increased dramatically

### ISSUE THREAD

**Issue by m1ron0xFF** [nextcloud/desktop#7254]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Starting from 3.14.0 release MacOS pkg size increased to 303M from 61M in 3.13.4, see https://download.nextcloud.com/desktop/releases/Mac/Installer/

<img width="634" alt="image" src="https://github.com/user-attachments/assets/092f2c3d-0d58-43dd-9ae5-05d2340cffff">

### Expected behavior

I expect the package size to be the same as previously

### Which files are affected by this bug

Nextcloud-3.14.0.pkg,  	Nextcloud-3.14.1.pkg

### Operating system

macOS

### Package

Official macOS 12+ universal pkg

### Nextcloud Desktop Client version

3.14.0

**Comment by claucambra** [comment]
Hello @m1ron0xFF with the move to Qt 6 we have now re-added support for logging in via the in-built web view in the desktop client on macOS. This was previously removed on Qt 5 builds after the introduction of Apple Silicon, as the Qt5 web engine did not support arm64

This framework accounts for a significant chunk of the size increase (~224MBs) but has always been seen as required
