### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by jahway603** [nextcloud/desktop#7255]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** Nextcloud desktop client 3.14.1

**Is your feature request related to a problem? Please describe.**
The application is very bright and causes eye strain & it does not contain an option to switch to a "Dark Theme".

**Describe the solution you'd like**
Implement an option to switch to a "Dark Theme".

**Describe alternatives you've considered**
Squinting my eyes because of how bright it is.

**Additional context**
N/A

**Comment by Toorero** [comment]
![Image](https://github.com/user-attachments/assets/e1170d91-5e0d-48f9-bc60-be410b9a2f94)
![Image](https://github.com/user-attachments/assets/807e4943-f80e-43f0-8826-a9a01955b448)

**Comment by Toorero** [comment]
Already working for me. You just have to set a dark QT theme I guess. I'm currently using [Flatremix](https://drasite.com/flat-remix-gtk) together with the [QGtkStyle](https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle) and

**Comment by jahway603** [comment]
@Toorero Thank you for your response & the helpful thumbs down, but the inherited QT dark theme is not working for me.

I'm using Artix with SwayWM & I do have a QT dark theme already setup using `qt5ct` which I do see being applied correctly to other QT applications, such as `qt5ct` itself and `caja`.

`fastfetch` shows the following for QT set themes:
- Theme: Windows [Qt]
- Icons: Vimix-Doder-dark [Qt]

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/desktop/issues/7255#issuecomment-2390363626

@jahway603, your title is that of an FR. If the included theme isn't functioning, then that's a bug report, not a feature request.

**Comment by Toorero** [comment]
> `fastfetch` shows the following for QT set themes:
> 
>     * Theme: Windows [Qt]
> 
>     * Icons: Vimix-Doder-dark [Qt]

For me, it shows:

* Theme: Flat-Remix-GTK-Blue-Light-Solid [GTK2/3/4]
* Icons: Flat-Remix-Blue-Dark [GTK2/3/4]

After digging through the [README.md](https://github.com/nextcloud/desktop/blob/master/README.md?plain=1#L38) it seems the project is using Qt6 since version 3.14 rather than Qt5 as I proclaimed. Maybe your setup for Qt6 is insufficient, and your theme is only being applied to Qt5 applications? Also think I have not setup QGTKStyle for Qt6 (yet) so there is that. I'm unsure how dark-theme switching is implemented using Qt only, since I rely on Gnome to do the magic somehow. Are you just setting a fixed Qt theme, and it applies to other application (using Qt6) but not Nextcloud, so Nextcloud falls back to the default (light) theme?

**Comment by Toorero** [comment]
> [@Toorero](https://github.com/Toorero) Thank you for your response **& the helpful thumbs down**

You're welcome. In my opinion, it's not the job of every individual application to offer a light/dark-theme switch as your feature-request implies, so there is that. 

Also, as the issue discussion and my example shows. There are *external* ways to theme Nextcloud if you are displeased with the default light theme it provides, and everything seems to boil down to either a misconfigured system or a theme *somehow* unsupported by Nextcloud.

**Comment by jahway603** [comment]
@Toorero Thank you for shedding the light that this project has been using Qt6 instead of Qt5. After using the `qt6ct` application, I now have the working dark theme that I was expecting after configuring it in `qt5ct` (as I had with `caja`).

@Toorero In my opinion, if an application wants to value visual accessibility, then they would prioritize offering a light/dark-theme and a switch between the two.

@RokeJulianLockhart There was not an included theme, which is why this was opened as a FR and not as a bug report.

@Toorero @RokeJulianLockhart  Anyhow, this Issue now resolved and perhaps others in the future will benefit from the contents we've all shared here.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/desktop/issues/7255#issuecomment-2414685659

@yahway603, I presume you're using Windows? On my desktop environment, Qt automatically adapts to the system theme, which affects NextCloud. Consequently, I was surprised that it didn't function for you. I can solely *presume* that on Windows, Qt doesn't automatically switch between colour schemes by default.

**Comment by jahway603** [comment]
> > [#7255 (comment)](https://github.com/nextcloud/desktop/issues/7255#issuecomment-2414685659)
> 
> @yahway603, a lack of an included theme isn't a bug. Imagine if every application developer was burdened by needing to include their own theme!
> 
> ~I presume you're using Windows? On my desktop environment, Qt automatically adapts to the system theme, which affects NextCloud. Consequently, I was surprised that it didn't function for you. I can solely _presume_ that on Windows, Qt doesn't automatically switch between colour schemes by default.~

Yes, Artix Linux is clearly Windows.

**Comment by RokeJulianLockhart** [comment]
> Yes, Artix Linux is clearly Windows.

@jahway603, surely the rationale for me `<strike>`-ing that paragraph is fairly obvious? XD

**Comment by jahway603** [comment]
> > Yes, Artix Linux is clearly Windows.
> 
> [@jahway603](https://github.com/jahway603), surely the rationale for me `<strike>`-ing that paragraph is fairly obvious? XD

I understand and was just having some fun with you :)

**Comment by RokeJulianLockhart** [comment]
Apologies. I'm just jealous because I couldn't think of a witty response myself.
