### ISSUE TITLE
Feature request: max upload and download speed

### ISSUE THREAD

**Issue by PureTryOut** [nextcloud/desktop#726]
It would be nice to be able to set a maximum allowed upload and download speed on the client (preferably separate). Right now it just maxes out my connection and it causes some other things to stutter, most notably videos and audio playing in my browser. This happens on a 50/50 Mbit connection on the client so line speed shouldn't be a problem.

This is also useful if you want to upload files, but want to give priority to a different program like a torrenting client.

**Comment by michaelstingl** [comment]
Please check `Bandwith Limiting` settings on the `Network` tab:
https://docs.nextcloud.com/desktop/2.3/visualtour.html#network

**Comment by PureTryOut** [comment]
I... I'm blind. How did I ever miss this. Thanks and sorry for this completely dumb question :man_facepalming:
