### ISSUE TITLE
Webflow login doesn't work behind proxy

### ISSUE THREAD

**Issue by haffmans** [nextcloud/desktop#729]
I want to use the Nextcloud desktop client (daily build) behind a company proxy. Previously I had my client configured to use http authentication. The app password got revoked and I was unable to login (clicking Login would immediately result in the client being logged out again). When recreating the account it wants to use the Webflow login, but this fails:

~~~
This site can’t be reached
The connection was reset.
Try:
- Checking the connection
- Checking the proxy and the firewall
ERR_CONNECTION_RESET
~~~

I can access the server from the browser without problems. I have set up the correct proxy settings in Nextcloud (from the logs it seems other requests are working fine).

### Expected behaviour
Web login flow should show login page

### Actual behaviour
The login page cannot be reached from the embedded browser.

### Steps to reproduce
1. Be behind a company http (client) proxy, configure this in Nextcloud client's settings
2. Attempt to add an account
3. Fill in the server address and click next

### Client configuration
Client version: Version 2.5.0daily (build 20181016).
Operating system: Windows 10
OS language: English
Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: Ubuntu Linux (using official Docker fpm image)
Web server: nginx
Database: MySQL
Nextcloud version: 14.0.1

### Logs

```
[OCC::AccessManager::createRequest 	2 "" "https://nextcloud.example.com/status.php" has X-Request-ID "6c84d773-b625-4e08-b406-19b8de151026"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://nextcloud.example.com" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Nextcloud","version":"14.0.1.1","versionstring":"14.0.1"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x1b7a47fdd80)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://nextcloud.example.com/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://nextcloud.example.com/remote.php/webdav/" has X-Request-ID "19b93ddb-a85c-4a81-93ea-ddb02958f657"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://nextcloud.example.com" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://nextcloud.example.com/remote.php/webdav/" has X-Request-ID "223bc6c6-6848-4fe4-a63a-3256ab6576cf"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://nextcloud.example.com" + "" "OCC::Account"
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://nextcloud.example.com/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://nextcloud.example.com/index.php/login/flow"
```

**Comment by rullzer** [comment]
Ah right. Proxy. Let me see if I can tell the webengine to use the properly.

**Comment by brtptrs** [comment]
I can confirm this Problem.
Also with V 2.5.1 and daily builds
The same problem und Windows and Linux clients

**Comment by brtptrs** [comment]
It also happens when trying to connect ta server version 15.0.1

**Comment by visglz** [comment]
Also happens on Ubuntu 18.04 with newest patches, nextcloud client 2.5.1, server version 15.0.4 and an authenticating proxy.

BTW: As an workaround is there a way to add an account without using the wizard?

**Comment by rullzer** [comment]
It should :tm: be fixed in the RC. However. I heared some people are still having issue. But it works on all the proxies I have thrown at it....

**Comment by stylersnico** [comment]
Still the same problem in April, any news on this?

**Comment by methyphobia** [comment]
Using Wireshark I found out that the initial Nextcloud Client Setup **does not** send proxy credentials to the proxy while connecting. This occurs although the appropriate parameters in the proxy section (type=3, needsAuth=true, correct credentials) are set in the nextcloud.cfg file. It looks like they're being ignored during the first login. After the client is set up, synchronization through proxy works fine as the necessary credential fields are filled. Maybe this helps finding the issue. I used Windows 10 and NC Client 2.5.2.

![nextcloud-proxy](https://user-images.githubusercontent.com/32457692/59418938-31cdec80-8dca-11e9-8390-fa4f50187578.png)

**Comment by ilinuxadmin** [comment]
I have the same issue.
Any workarounds?


> Using Wireshark I found out that the initial Nextcloud Client Setup **does not** send proxy credentials to the proxy while connecting. This occurs although the appropriate parameters in the proxy section (type=3, needsAuth=true, correct credentials) are set in the nextcloud.cfg file. It looks like they're being ignored during the first login. After the client is set up, synchronization through proxy works fine as the necessary credential fields are filled. Maybe this helps finding the issue. I used Windows 10 and NC Client 2.5.2.
> 
> ![nextcloud-proxy](https://user-images.githubusercontent.com/32457692/59418938-31cdec80-8dca-11e9-8390-fa4f50187578.png)
