### ISSUE TITLE
Windows client not syncing files ending up with INKApi Error

### ISSUE THREAD

**Issue by mkudlacek** [nextcloud/desktop#73]
Hello,
 I have installed Nextcloud client on Windows 7. It is fully synced with server, but when I try to add certain files, the client just says:

Error transferring, server replied INKApi Error

The files are quite small, not greater than 1MB. Some TXT files are synced, but PDF files end up with this error. When I rename the file, Nextcloud tries to sync again but ends up with the same error.

Versions of software:

Server: Debian 8.9, 64bit, fully updated
Nextcloud server: 12.0.3
Web server: apache2  2.4.10-10+deb8u11
SQL server: MySQL 5.5.58-0+deb8u1

Client: Windows 7, 32bit
Nextcloud client: 2.3.3 (build 1)

Detail of the client log:

![image](https://user-images.githubusercontent.com/146914/33308272-0a0e9b24-d41a-11e7-874e-563ff5261e3a.png)

There are no errors in nextcloud.log on the server.

Thanks for your help in advance.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client (running on a supported platform), please re-open the issue.

Thanks!

**Comment by mkudlacek** [comment]
I have migrated to the Seafile because of this issue 3 years ago...
