### ISSUE TITLE
download section for clients has an expired certificate, downloads not possible

### ISSUE THREAD

**Issue by fvzwieten** [nextcloud/desktop#733]
### Expected behaviour
Able to download client software

### Actual behaviour
Certificate expired

### Steps to reproduce
1. goto https://download.nextcloud.com/desktop/releases/Windows/Nextcloud-2.3.3.1-setup.exe
2.
3.

### Client configuration
Client version:

Operating system:
Windows

OS language:
10

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by rullzer** [comment]
Thanks for noticing. I have asked our sysadmins to look into why this wasn't autorenewed. Should work again now.
