### ISSUE TITLE
No package of nextcloud-client seem to exist for Kubuntu cosmic

### ISSUE THREAD

**Issue by carlonluca** [nextcloud/desktop#735]
### Expected behaviour
It would be great to have the newest version of nextcloud available in the ppa for Ubuntu cosmic.

### Actual behaviour
It seems the ppa does not provide a version for cosmic. Installation fails with: "E: Unable to locate package nextcloud-client". I also do not see it here: https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client/+packages.

Operating system: Kubuntu Cosmic 18.10.

**Comment by tribut** [comment]
The Version from bionic appears to work, but this is making it unnecessarily hard to upgrade or install.

**Comment by carlonluca** [comment]
I see in the repo there is already a cosmic package being built in the script. By looking a bit deeper I see it is in the beta ppa. That one works properly for me! Thank you nextcloud team!
