### ISSUE TITLE
[AppImage] Desktop client produces a lot of warnings

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/desktop#736]
### Expected behaviour
No Warnings for `Login failed`

### Actual behaviour
Desktop client works as expected. But I have a lot of Login failed warnings when desktop client runs. (see screenshot)

### Client configuration
Client version: (AppImage) 2.5

Operating system: ArchLinux

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From Nextcloud or distro) (Linux only): 5.11

Installation path of client: /home/user/AppImages/Nextcloud.AppImage

![nextcloud_client_warning](https://user-images.githubusercontent.com/16517095/47288392-3a34a580-d5f6-11e8-86ca-c67d31d4ec49.jpg)

**Comment by artemanufrij** [comment]
current RC version has still this bug

**Comment by claell** [comment]
I guess in normal circumstances this warning does not appear, so it might be caused by some specific things in your setup or the server you use. Are you sure that these warnings should not be displayed?

**Comment by mgallien** [comment]
Can you still reproduce this bug with the latest version ?
If this is fixed, can you close this issue ?
