### ISSUE TITLE
Please reopen: [Bug]: Menu interface became all white (3.14 - Win10) #7139

### ISSUE THREAD

**Issue by bobbolous** [nextcloud/desktop#7378]
Following Bug was marked as closed as the issue seems to have disappeared for the original poster.
Others and myself still have this issue. Please reopen the issue:
https://github.com/nextcloud/desktop/issues/7139

**Comment by twity1337** [comment]
There is an open issue #7269

**Comment by mgallien** [comment]
@twity1337 is true
thanks for finding the duplicate
I am closing this one
the dark mode issue is only solved currently for Windows 11 and we plan to also fix it on Windows 10 but need more time
