### ISSUE TITLE
Tray menu doesn't open consistently

### ISSUE THREAD

**Issue by armaccloud** [nextcloud/desktop#739]
### Expected behaviour
The menu should open when clicking on the tray icon

### Actual behaviour
The menu doesn't open, or very inconsistently

### Steps to reproduce
1. Click on the tray icon to open the menu
2. Verify the menu doesn't open

### Client configuration
Client version: 
2.3.3 (build 1)

Operating system:
elementaryOS 5.0 Juno (but also happened on 0.4, Loki)

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.9.2

Client package (From Nextcloud or distro) (Linux only):
appimage

Installation path of client:
/home/arno/snap/nextcloud-client
/home/arno/snap/nextcloud-client/current
/var/lib/snapd/sequence/nextcloud-client.json

**Comment by armaccloud** [comment]
**Screenshot**
![screenshot from 2018-10-22 20-33-28](https://user-images.githubusercontent.com/9272078/47311345-c2886a00-d639-11e8-95ed-5e746c870805.png)

**Screencast**
[Nextcloud Tray Icon.mp4.zip](https://github.com/nextcloud/desktop/files/2502665/Nextcloud.Tray.Icon.mp4.zip)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
