### ISSUE TITLE
Change font colour of progress indicator to a more readable one

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/desktop#74]
Hello,

using Nextcloud Client 2.3.3.1 on Windows 10, I can barely see the text that shows the progress of the sync. Another problem is that this progress information is only viewable if the mouse is placed over the otherwise white area.

I made two screenshots to show the problem (the first with the mouse pointer over the area and the second without):

![image](https://user-images.githubusercontent.com/10073629/33336910-b38e4472-d471-11e7-8211-4ef2d2d29450.png)

![image](https://user-images.githubusercontent.com/10073629/33336795-5d0f479a-d471-11e7-8c68-bad81de3772d.png)

**Comment by juliushaertl** [comment]
Seems to be fixed on master:
![image](https://user-images.githubusercontent.com/3404133/41767955-4e02bf8e-760b-11e8-99d7-1e568dffe305.png)
