### ISSUE TITLE
Building with TOKEN_AUTH_ONLY fails

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/desktop#740]
### Expected behaviour
Setting -DTOKEN_AUTH_ONLY=ON for cmake should configure the client with token authentication only.

### Actual behaviour
Build fails with
`src\libsync\networkjobs.cpp(32): fatal error C1083: Cannot open include file: 'QPainter': No such file or directory`

This is caused by `src/libsync/CMakeLists.txt` including Qt5::Widgets only for `NOT TOKEN_AUTH_ONLY`. Furthermore HttpCredentials are only included when `TOKEN_AUTH_ONLY` is OFF, but `networkjobs.cpp` always includes `httpcredentials.h`.

### Steps to reproduce
1. Use cmake with -DTOKEN_AUTH_ONLY=ON
2. cmake --build . --target all

### Client configuration
Client version: 2.5.0-beta2

Operating system: All

Qt version used by client package (Linux only, see also Settings dialog): 5.11.1

**Comment by claell** [comment]
How is the status of this @rullzer @misch7?
