### ISSUE TITLE
Client silently crashing

### ISSUE THREAD

**Issue by peteruithoven** [nextcloud/desktop#741]
### Expected behaviour
The Nextcloud client keeps running in the background.

### Actual behaviour
Every few days it silently crashes and I have to restart it. 
(I've never had a gui crash while using it)

### Steps to reproduce
I've not been able to reproduce this issue consistently. But I've got the last logfile lines after a few crashes.

### Client configuration
Client version: 
2.3.3-20180415.190957~bionic1

Operating system: 
elementary OS 5.0 (Ubuntu 18.04 LTS)

OS language: 
English

Qt version used by client package (Linux only, see also Settings dialog):
I didn't see this version number in settings > General, please clarify. 
libqt5core5a: 5.9.5+dfsg-0ubuntu1
libqt5gui5: 5.9.5+dfsg-0ubuntu1

Client package (From Nextcloud or distro) (Linux only):
APT-Sources: http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic/main amd64 Packages

Installation path of client:
`/usr/bin/nextcloud`

### Server configuration
Operating system:
16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)

Web server:
Caddy 

Database:
mysql  Ver 15.1 Distrib 10.0.36-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )

Nextcloud version:
Nextcloud 14.0.1

Storage backend (external storage):
none

### Logs

1. Client logfile: 
 Last few lines of /tmp/nextcloud.log after a couple of crashes:
https://gist.github.com/peteruithoven/1abfad0d95bbded5f2c3bf82b3b75a59

**Comment by mgallien** [comment]
This issue is quite old.

Are you still able to reproduce it ?
If the bug is fixed, please close this issue.

**Comment by peteruithoven** [comment]
Not really, but I've been keeping the app open to keep a better eye on it. 
Seeing it got zero "upvotes" let's close it for now.
