### ISSUE TITLE
nextcloud client does not synchromize files after restoration of old version with versios plugin 

### ISSUE THREAD

**Issue by DTux69** [nextcloud/desktop#743]
### Expected behaviour
The file restored be synchronize.

### Actual behaviour
nextcloud-client keep the old version before restoration

### Steps to reproduce
1. restore a file on the server side ( 2_06_fiche_d_entretien_d_evaluation.odt in the logs )
2. force synchronization of nextcloud client
3. the file is not synchronized ( see logs below )
4. to resolve, i need to deactivate the synchronization of the directory, and re enable it, that's force reloading of all directory.

### Client configuration
Client version:
2.3.2
Operating system:
Linux / Mageia

OS language:
French

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
Mageia package

Installation path of client:

### Server configuration

Operating system:
Linux / Mageia

Web server:
Apache

Database:
Mysql

PHP version:
5.6.38
Nextcloud version:
12.0.6

Client logs:
10-24 11:00:38:934 0x29fe468 _csync_detect_update: Database entry found, compare: 1538559397 <-> 1538559397, etag: (null) <-> ec81e6a26bf65f51c7cdad555571c2b1, inode: 2884416 <-> 2884416, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
10-24 11:00:38:934 0x29fe468 _csync_detect_update: file: Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/ExplicationEI.pdf, instruction: INSTRUCTION_NONE <<=
10-24 11:00:38:934 0x29fe468 csync_walker: file: /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/EI.pdf [inode=2884415 size=0]
10-24 11:00:38:934 0x29fe468 _csync_detect_update: Database entry found, compare: 1537955734 <-> 1537955734, etag: (null) <-> 9ec78a55c7e92dd42f66adf33cd5f2ba, inode: 2884415 <-> 2884415, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
10-24 11:00:38:934 0x29fe468 _csync_detect_update: file: Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/EI.pdf, instruction: INSTRUCTION_NONE <<=
10-24 11:00:38:935 0x29fe468 csync_walker: file: /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/2_06_fiche_d_entretien_d_evaluation.odt [inode=2884412 size=0]
10-24 11:00:38:935 0x29fe468 _csync_detect_update: Database entry found, compare: 1538557668 <-> 1538557668, etag: (null) <-> 722341015a51e7eb045f666850e0e7c3, inode: 2884412 <-> 2884412, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
10-24 11:00:38:935 0x29fe468 _csync_detect_update: file: Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/2_06_fiche_d_entretien_d_evaluation.odt, instruction: INSTRUCTION_NONE <<=
10-24 11:00:38:935 0x29fe468 csync_walker: file: /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/Guide EI + Fiche EI à remplir.pdf [inode=2884417 size=0]
10-24 11:00:38:935 0x29fe468 _csync_detect_update: Database entry found, compare: 1538556653 <-> 1538556653, etag: (null) <-> 45388b422671701a4605afeb8cf0f3b2, inode: 2884417 <-> 2884417, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
10-24 11:00:38:935 0x29fe468 _csync_detect_update: file: Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel/Guide EI + Fiche EI à remplir.pdf, instruction: INSTRUCTION_NONE <<=
10-24 11:00:38:935 0x29fe468 csync_ftw:  <= Closing walk for /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/Social/Entretien individuel with read_from_db 0
10-24 11:00:38:935 0x29fe468 csync_ftw:  <= Closing walk for /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/Social with read_from_db 0
10-24 11:00:38:935 0x29fe468 csync_walker: file: /home/axel/Nextcloud/Cuisine itinérante/gestion des activites/CLEMENCE/repartition halles.ods [inode=2884430 size=11487]
10-24 11:00:38:935 0x29fe468 _csync_detect_update: Database entry found, compare: 1539876985 <-> 1539876985, etag: (null) <-> c1fbd7a106af8476f4ad766725a43da0, inode: 2884430 <-> 2884430, size: 11487 <-> 11487, perms:  <-> RDNVW, ignore: 0****
-------
------
------
10-24 11:00:41:002 0x261afb0 _csync_merge_algorithm_visitor: INSTRUCTION_NONE               server file: Cuisine itinérante/gestion des activites/CLEMENCE/CLEMENCE/CLEMENCE/Social/Entretien individuel/2_06_fiche_d_entretien_d_evaluation.odt

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?
