### ISSUE TITLE
The server deletes a file, the file will be deleted on windows, which is a fatal BUG for user. Because any server-side problems may lead to the deletion of the local file, which is disastrous

### ISSUE THREAD

**Issue by aibotez** [nextcloud/desktop#7430]
The file will be deleted on window if it be deleted on sercloud, which is only a logical choice for synchronization, but for the user, this is a fatal BUG, the modification of the local file must be careful, otherwise any server-side problems may lead to the deletion of the local file, which is disastrous.

**Comment by claucambra** [comment]
Hello @aibotez this behaviour is intentional as we want the local state and remote state to match each other. We do not consider this a bug and would in fact consider it a bug if this was not the case

If you are worried about deletions of files on the server wiping your local files, deleted files on the server will be stored in the trash from where they can be recovered

**Comment by aibotez** [comment]
Thank you very much for your reply and clarification, but I still hope to add the function of one-way synchronization, which will undoubtedly make the data more secure, which is also your claim.


Thanks again, and I hope you can consider this suggestion, which will make nextcloud even more perfect





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nextcloud/desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月29日(星期二) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nextcloud/desktop] The server deletes a file, the file will be deleted on windows, which is a fatal BUG for user. Because any server-side problems may lead to the deletion of the local file, which is disastrous (Issue #7430)





 
Hello @aibotez this behaviour is intentional as we want the local state and remote state to match each other. We do not consider this a bug and would in fact consider it a bug if this was not the case
 
If you are worried about deletions of files on the server wiping your local files, deleted files on the server will be stored in the trash from where they can be recovered
