### ISSUE TITLE
[Bug]: update check not finding 3.14.2

### ISSUE THREAD

**Issue by foss-** [nextcloud/desktop#7449]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

macOS 15.1
Nextcloud desktop 3.14.1
Update channel: stable

Update check not finding 3.14.2. Check now results in info: 

`You’re up to date! - Nextcloud 3.14.1 is currently the newest version available. (You are currently running version 3.14.1daily.)`

### Steps to reproduce

Open General Settings > Info > Check Now

### Expected behavior

3.14.2 update should be found and installed

### Which files are affected by this bug

N/A

### Operating system

macOS

### Which version of the operating system you are running.

macOS 15.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

269.0.5

### Nextcloud Desktop Client version

3.14.1

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Torqu3Wr3nch** [comment]
Came here looking for the same issue (but on Windows).

**Comment by foss-** [comment]
For what it's worth issue is persisting with 3.14.3.
