### ISSUE TITLE
[Bug]: A large number of files have been deleted... dialog keeps reappearing

### ISSUE THREAD

**Issue by MaximeMaW** [nextcloud/desktop#7450]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

After updating to Nextcloud Desktop 3.14.2 and cleaning my Nextcloud Desktop folder, the following message appears:

![Image](https://github.com/user-attachments/assets/207e06c3-d984-4ad2-8f98-b55e051161a4)

I click "Proceed with deletion", but a few minutes later, the dialog appears again. How to make it disappear.

### Steps to reproduce

Upgrade from 3.14.1 to 3.14.2.
Stop client
Wipe .db files at the root of the folder
Start client, wait for synchronization to resume.
All files are properly synced 🙏 , but this dialog keeps reappearing.

### Expected behavior

Show only this dialog once.

### Which files are affected by this bug

not relevant

### Operating system

Windows

### Which version of the operating system you are running.

Windows 11

### Package

Official Windows MSI

### Nextcloud Server version

28.0.11

### Nextcloud Desktop Client version

3.14.2

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### Additional info

According to the forum, this bug seems new to users in version 3.14.2. I am not the only one affected. https://help.nextcloud.com/t/a-large-number-of-files-error-message-keeps-reappearing/207659

**Comment by ThibautPlg** [comment]
Hi,
I stumbled upon this problem this morning. I ended up killing my desktop client, upgrading to 3.14.3 and restarting. 
Problem went as it came. Not sure if 3.14.3 fixed it or if that's luck.

(Ubuntu 22)

Regards,
