### ISSUE TITLE
Right-clicking the system tray very rarely works for the AppImage

### ISSUE THREAD

**Issue by ajvsol** [nextcloud/desktop#746]
### Expected behaviour
Right-clicking the system tray icon should open the context menu, including having the ability to quit the application. 

### Actual behaviour
Nothing happens. Perhaps 1 out of 200 clicks will actually cause it to open. No identified correlation as to what makes it finally work. 

### Steps to reproduce
1. Use the latest AppImage on Kubuntu 18.04 LTS
2. Try to right-click the system tray icon for Nextcloud

### Client configuration
Client version: 2.3.3

Operating system: Kubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.9.2

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: /media/veracrypt1/Cloud/

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
