### ISSUE TITLE
Client ignores folder and syncs everything to root directory

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/desktop#747]
### Expected behaviour
Client should sync to the chosen folder and not to the root directory.

### Actual behaviour
Client syncs everything to root directory.

### Steps to reproduce
1. Create 2 accounts with the same user.
2. Have one account sync one set of folders.
3. Have the second account sync single folder only to mounted local storage folder.
4. Second account syncs to root folder.

### Client configuration
Client version: Latest

Operating system: Win 10

To be clearer about this issue: I have my Nextcloud client syncing with my normal server data folder and everything works fine. I decided to mount another drive on local storage and am using that to sync a single very large folder that I don't want syncing to my main data drive. Therefore I added a second account to the Nextcloud client with the same user. Account 1 syncs everything EXCEPT that folder; Account 2 syncs ONLY that folder.

The problem is that Nextcloud syncs Account 2 to the root directory of the Account 1, completely ignoring the folder designation I made.

When I do this in reverse - create a file on the secondary folder and let Nextcloud sync it FROM that folder, it works fine; when I do it the other way, i.e sync TO that folder, the client creates the file in the root directory.

The only thing I can think of is that maybe the client doesn't like having 2 different set of sync folders for the same user? If that's the case, then this isn't a bug I guess. If not, i.e. if I should be able to set up a variety of different folder syncing setups for the same user, then this is a bug.

Thanks.

**Comment by mgallien** [comment]
This bug is quite old and I think it has been fixed. Can you please test with the latest version ?
If the bug is fixed, please close the issue.
