### ISSUE TITLE
[Bug]: MacOS Vfs uses wrong uid when using LDAP Accounts

### ISSUE THREAD

**Issue by paddif** [nextcloud/desktop#7480]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

When using vfs on MacOS with a Cloud Configured with LDAP login, it uses the LDAP Login instead of the UID within Nextcloud, wich results in a 404 error

### Steps to reproduce

1. Setup Nextcloud with LDAP
2. Configure Virtual File Sync
3. Try open VFS in MacOS

### Expected behavior

VFS in MacOS should use the Users UID instead of the LDAP login name e.g.
patrick.frey(LDAP) 2ED8C975-5A77-4157-829C-D86F1068EA84 (NEXTCLOUD)

### Which files are affected by this bug

-

### Operating system

macOS

### Which version of the operating system you are running.

15.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

30.0.1

### Nextcloud Desktop Client version

3.14.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell
Set up enumerator for user: patrick.frey https://cloud.***.de
with serverUrl: https://cloud.***.de/remote.php/dav/files/patrick.frey
Sending extension account ID 2ED8C975-5A77-4157-829C-D86F1068EA84@cloud.***.de
1 depth read of url https://cloud.***.de/remote.php/dav/files/patrick.frey
did not complete successfully, error: 
		Der Server konnte die Anfrage nicht fertig stellen.		Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.		Weitere Details können im Server-Protokoll gefunden werden.
"Finishing enumeration for user: patrick.frey https://cloud.***.de
with serverUrl: https://cloud.***.de/remote.php/dav/files/patrick.frey 
with error 
		Der Server konnte die Anfrage nicht fertig stellen.		Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.		Weitere Details können im Server-Protokoll gefunden werden.
Sending extension account ID 2ED8C975-5A77-4157-829C-D86F1068EA84@cloud.***.de
Set up enumerator for user: patrick.frey https://cloud.***.de
with serverUrl: https://cloud.***.de/remote.php/dav/files/patrick.frey
Sending extension account ID 2ED8C975-5A77-4157-829C-D86F1068EA84@cloud.***.de
1 depth read of url https://cloud.***.de/remote.php/dav/files/patrick.frey
did not complete successfully, error: 
		Der Server konnte die Anfrage nicht fertig stellen.		Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.		Weitere Details können im Server-Protokoll gefunden werden.
"Finishing enumeration for user: patrick.frey https://cloud.***.de
with serverUrl: https://cloud.***.de/remote.php/dav/files/patrick.frey 
with error 
		Der Server konnte die Anfrage nicht fertig stellen.		Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an deinen Server-Administrator.		Weitere Details können im Server-Protokoll gefunden werden.
Sending extension account ID 2ED8C975-5A77-4157-829C-D86F1068EA84@cloud.***.de
```

### Additional info

![Image](https://github.com/user-attachments/assets/76b9bf3b-1f38-4a1d-88c0-6ddb7c2613d0)

**Comment by claucambra** [comment]
Hi, this has now been fixed in the core library for macOS vfs: https://github.com/claucambra/NextcloudFileProviderKit/pull/24

This fix will be included in the next bugfix release of the desktop client

Thank you for opening the issue!
