### ISSUE TITLE
Feature Request: support HTTP/2

### ISSUE THREAD

**Issue by helmut72** [nextcloud/desktop#752]
Please support HTTP/2. Thank you.

**Comment by cyBea** [comment]
As far as I can see in my server logs it is already implemented:
`<IP> - <login> [12/Jan/2019:21:xx:xx +xx00] "PUT /remote.php/dav/files/<login>/<path_to_file> HTTP/2.0" 204 464 "-" "Mozilla/5.0 (Linux) mirall/2.5.1git (Nextcloud)"`

**Comment by helmut72** [comment]
Not with the current stable version (2.5.1 20181204) for macOS:
`PROPFIND /remote.php... HTTP/1.1" 207`

Access from a webbrowser shows this:
`GET /index.php... HTTP/2.0" 200`

**Comment by cyBea** [comment]
I can confirm this: works with linux-client, but not with macos-client as of today:

`<IP> - <login> [14/Jan/2019:21:xx:xx +xx00] "PUT /remote.php/dav/files/<login>/<path_to_file> HTTP/1.1" 201 0 "-" "Mozilla/5.0 (Macintosh) mirall/2.5.1final (build 20181204) (Nextcloud)"`

**Comment by j-ed** [comment]
HTTP/2 seems also not being supported on Windows clients yet:
```
<IP> - - [22/Jan/2019:15:24:16 +0100] "PROPFIND /remote.php/dav/files/<login>/ HTTP/1.1"
   207 387 "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)"> ...
```

**Comment by helmut72** [comment]
Still HTTP/1.1 with Desktop Client 3.0.1 (macOS):

`"GET /ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh) mirall/3.0.1git (build 3355) (Nextcloud)`

With any current Browser it's HTTP/2.0:

`"GET /login HTTP/2.0" 200 4358 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15"`

**Comment by mgallien** [comment]
HTTP/2 is supprted by Nextcloud desktop client.
It is disabled by default. It can be activated with environment variable `OWNCLOUD_HTTP2_ENABLED` defined to `1`.
We may activate it by default once the default installation of the server activates it.
