### ISSUE TITLE
First Start with e2e with multiple accounts: confusion with mnemonics

### ISSUE THREAD

**Issue by augustseptember** [nextcloud/desktop#753]
### Expected behaviour
Each account needs a mnemonic. It shows up at first start. One small window per account in which you should read the username.

### Actual behaviour
No username is shown. Which Mnemonic belongs to which account?

### Steps to reproduce
1. Exit the running client (2.3.3) with 3 configured user accounts
2. Start the AppImage (2.5) the first time
3. 

### Client configuration
Client version: 2.5

Operating system: Ubuntu 18.04

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): 
Built from Git revision 58302e on Oct 26 2018, 11:03:15 using Qt 5.11.0, OpenSSL 1.0.2g 1 Mar 2016

Client package (From Nextcloud or distro) (Linux only): AppImage (https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.0.20181026-rc1-x86_64.AppImage)

Installation path of client: ~/Downloads/Nextcloud-2.5.0.20181026-rc1-x86_64.AppImage 

### Server configuration

Operating system: Ubuntu 16.04

Web server: Apache

Database: MariaDB

PHP version:

Nextcloud version: 14.03

Storage backend (external storage): No

**Comment by er-vin** [comment]
Hello,

I think this issue is properly addressed with PR #1241 so closing now.

Regards.
