### ISSUE TITLE
2.5 Linux: Unable to login via apptoken

### ISSUE THREAD

**Issue by MinIsMin** [nextcloud/desktop#755]
Using the Linux test version 2.5 I'm unable to login via username-apptoken.
Pressing the login button doesn't do anything and no request to the server is made.
The stable version worked fine.

Logs: https://paste.ee/p/WLnNZ

Client version: `2.5.0-20181030.015244~cosmic1`
Operating system: `Ubuntu 18.10`
OS language: `German`
Qt version used by client package: nothing displayed in settings, I suppose Qt5
Client package: Nextcloud beta ppa
Installation path of client: `/usr/bin/nextcloud`

**Comment by rullzer** [comment]
This is a server bug. Fixed with https://github.com/nextcloud/server/pull/12177

Also, any reason you use an apptoken and not normal login+pass+second factor? THen an apptoken is automatically generated.

**Comment by MinIsMin** [comment]
Thanks for fixing.
Reason? Just testing the client.

**Comment by rullzer** [comment]
@MinIsMin thanks for testing :)

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/12177 is in and will be backported. So with your next server update it should work.
