### ISSUE TITLE
[Bug]: flatpak image seems to miss "Bus Session DBUS" permission

### ISSUE THREAD

**Issue by alexgarel** [nextcloud/desktop#7556]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I am using the [flatpak version of NextCloud desktop](https://flathub.org/apps/com.nextcloud.desktopclient.nextcloud) on ubuntu 24.04.01, with gnome  Shell 46.0

My owncloud client was showing it offline, and I had no way to login to my acount: when I clicked the account login menu, nothing was happening.

So I gave a look at permissions using FlatSeal.
After I added Bus Session DBUS permissions, it started to work again.

![Image](https://github.com/user-attachments/assets/b75b9e57-7197-49fb-84a8-b528531838cb)

### Steps to reproduce

1. Have an installed flatpak desktop version on Ubuntu 24.4.1 that was synchronizing
2. See it's not anymore…
3. open main window
4. try to login to your account… nothing happens

Or maybe:
1. Install flatpak on a recent Ubuntu distribution
2. try to login to your service (I think it won't work even at this step)

### Expected behavior

Synchronization should continue.

DBus permission should have been set by flatpak package.

### Which files are affected by this bug

unable to answer…

### Operating system

Linux

### Which version of the operating system you are running.

Ubuntu 24.10.1

### Package

Community FlatPak

### Nextcloud Server version

29.0.7.1

### Nextcloud Desktop Client version

3.14.3daily

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by mgallien** [comment]
this is not maintained by us and is a pure community project maintained in https://github.com/flathub/com.nextcloud.desktopclient.nextcloud
best is to reach out there
even better would be for you to create a PR changing the flaptack manifest if you know how to do it
