### ISSUE TITLE
Desktop client PPA needs Cosmic release file

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/desktop#757]
The PPA here : https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

Does not have a "Release" file for Cosmic. So I can't use this PPA with 18.10 now, and I'll have to disable it until the Release file is made, because it breaks my package manager environment.

Any chance we can get this addressed please? :)

**Comment by splitt3r** [comment]
See the note in the PPA description. It says you should switch to http://ppa.launchpad.net/nextcloud-devs/client-beta/ubuntu/dists/cosmic/.

**Comment by BloodyIron** [comment]
@splitt3r eep! I missed that, sorry!
