### ISSUE TITLE
[Bug]: Client does not update theme when switching Windows theme from dark mode to white mode

### ISSUE THREAD

**Issue by djamn** [nextcloud/desktop#7574]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

I installed v3.15.0 and have enabled white mode in Windows 10. The Desktop client is also in white mode.

Then I switch to dark mode and the client successfully switched to the dark mode theme.

However, when switching back to white mode theme, the Desktop client still uses dark mode theme until closing and reopening the client.![Image](https://github.com/user-attachments/assets/306269a9-3f71-42dc-97d2-d3555f6772ba)

### Steps to reproduce

1. Have white mode enabled
2. Open client (it just have to run in background)
3. Switch to dark mode
4. Switch back to white mode

### Expected behavior

When switching back to white mode it should change the theme back to white mode

### Which files are affected by this bug

styling

### Operating system

Windows

### Which version of the operating system you are running.

Windows 10

### Package

Official Windows MSI

### Nextcloud Server version

29.0.5

### Nextcloud Desktop Client version

3.15.0

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 3.3.6 to 3.4.0)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [x] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by Rello** [comment]
Hello,

this is a known issue with QT & Win10 and there is currently unfortunately nothing we can do about it.
As switching back and forth is not done regularly, we have to live with it until fixed in QT.
sorry for that
