### ISSUE TITLE
[Bug]: Client removes group foldes in the blink of an eye, then needs an hour to sync it down again when the remote group folders app crashes!

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/desktop#7577]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This is actually bothersome and scary.

There's an issue with group folders that occurs sometimes during upgrades.  Here is just one such thread (but I find many):

https://help.nextcloud.com/t/groupfolders-gone-after-upgrade-to-28-0-2/180603/4

Now to be sure, that is a group folders issue and bug IMHO. BUT there is a clear bug also IMHO in the NextCloud client regarding its response to a disappearing remote group folder.

The client just removes the folder. Blink of an eye and it's gone. Many GB of local data, puff, up in the air. 

Then when you've fixed the groupfolders app on the remote server it starts syncing again to bring the group folder down:

![Image](https://github.com/user-attachments/assets/2e286376-41ef-4e3f-a4df-7fc7330d042c)

Both very very inefficient and scary and dangerous.  The local client should have a clear safety feature (possibly optional and opt in) like I saw Joplin and Floccus introduce. Namely, if there is a sudden huge change remotely (a whole multi GB folder missing), do not delete the local data, move it to a safety zone if need be ideally one from which it can be recovered if that folder reappears. 

That is, the client should have a failsafe for remote service glitches.  

I had to wait overnight to resync from a LAN link! Crazy slow and concerning but that isn't the issue. The issue is that it deleted the group folder in the blink of an eye when the groupfoldeers app went nutty.  It should instead have put it in a holding bay somewhere with a simple local filesystem move (instant) in case the groupfolders app came good again, which it did, in which case, restore it and sync on that as any basis for change.

Now I have enabled Move removed files to trash for now:

![Image](https://github.com/user-attachments/assets/e42aea7f-dbdf-4ab6-807e-07cc4af01ce3)

which might help me in future. But this isn't to my mind the same thing really as safeguarding against very sudden huge changes and the option to Ask for confirmation before synchronising new folders larger than (500MB) option should have caught this but didn't! And that is itself a bug IMHO.

The client debug archive is at: https://mega.nz/file/8fxxlZ4A#Li2vYNlSxxkv0RSkBNV3kt-7sT1C5mZ-hML1dk9COrQ
(for a while, anyhow).

### Steps to reproduce

Not easy to reproduce.  Maybe disable the groupfolders app and see if that triggers the same response.

### Expected behavior

I expect the client never to remove a whole folder without asking for permission or keeping it in a cache for optional restore. It's most scary the way it just deleted all the data locally. Imagine if it was gone from the server too because of some glitch. 

### Which files are affected by this bug

HoGS

### Operating system

Linux

### Which version of the operating system you are running.

Linux Mint 22

### Package

Official Linux AppImage

### Nextcloud Server version

29.0.9

### Nextcloud Desktop Client version

3.14.3

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 3.4.2 to 3.4.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by mgallien** [comment]
@bernd-wechner 
I am sorry for the troubles you have with groupfolders app.
This kind of events is the reason we added the "Move removed files to trash".
We do not plan any further changes there as any improvements there would be very difficult.
I see that you are using AppImage and as we do not yet implement a so-called "virtual files feature", your files have their data on the client side.
Now, imagine you were using Windows virtual files feature, the local files are just pure placeholder without data. What is the point of keeping them if they disappear server side ?
You cannot do anything with them.
I would love to provide this on all platforms and especially free and open source workspace (think about Gnome, KDE Plasma, ...). That would prevent keeping local files without the server file being available. I would prefer to spend my time on virtual files for Linux than trying to work around a bug in a server app.

**Comment by bernd-wechner** [comment]
What I think is worth fixing mind you is that folder removes, even to tag, honour the "ask for confirmation" setting when it's set, based on the size of the folders contents (in tuto), not just the folder letter which is a tiny thing 😉
