### ISSUE TITLE
[Bug]: FileProviderExt fails to authenticate when connecting to FileRun server

### ISSUE THREAD

**Issue by hrdwdmrbl** [nextcloud/desktop#7590]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

# Context

There are 2 folders: 

1) The "regular" folder within my home `~` 
2) The "VFS" folder on the sidebar (which is actually this `~/Library/CloudStorage/Nextcloud`, right?)

# The problem

I cannot navigate the "VFS" folder in Finder. Clicking it shows a spinner forever.
AND
Clicking on the "Sign In..." button in the top-right of Finder shows an empty dialogue that will hang forever. Cannot exit it. Requires restarting Finder.

### Aside: What does work

I _am_ able to navigate the "regular" folder and navigate around. Clicking on any .nextcloud file does cause Nextcloud app to download the file and then I can open it.

### Steps to reproduce

Click on the Nextcloud (VFS) Location in the Finder sidebar -> Spins forever
ALSO
Click on the "Sign In..." button and a dialogue will hang forever

### Expected behavior

I should see my files

### Which files are affected by this bug

All

### Operating system

macOS

### Which version of the operating system you are running.

15.1.1 (24B91)

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

Unsure

### Nextcloud Desktop Client version

3.15.0

### Is this bug present after an update or on a fresh install?

Yes

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

Not server logs, but Console.app logs show a lot of 

"Error Domain=NSFileProviderErrorDomain Code=-1000 "You need to authenticate before accessing this item." UserInfo={NSLocalizedDescription=You need to authenticate before accessing this item.}"

### Additional info

# Solutions that I have tried

Several times I have:

1. Tried to reset Finder by deleting its plist file.
2. Restarted
3. Removed the connection from Nextcloud and re-added it.
4. Re-installed Nextcloud
5. Enabled and disabled VFS

### Screenshots

VFS folder

![Screenshot 2024-11-29 at 16 04 33](https://github.com/user-attachments/assets/3d6053f4-52d9-410f-9c17-fd3ac1d7c54f)
![Screenshot 2024-11-29 at 16 05 20](https://github.com/user-attachments/assets/88f010b4-5b68-4cd3-a28e-2ddc453a8747)

"Regular" folder
![Screenshot 2024-11-29 at 16 08 19](https://github.com/user-attachments/assets/fb8d1253-2fc0-49b3-a4f7-dffeaafdc73c)

### Logs

The biggest error that I see is `2024-11-29 16:07:34:885 [ warning default qrc:/qml/src/gui/tray/MainWindow.qml:99 ]:	qrc:/qml/src/gui/tray/MainWindow.qml:99: ReferenceError: appsMenu is not defined`

### Additional context

Things used to work about a month ago

**Comment by claucambra** [comment]
Hello @hrdwdmrbl could you send me a debug archive? Having the full logs would really help get to the bottom of this :)

**Comment by claucambra** [comment]
I have now opened https://github.com/claucambra/NextcloudFileProviderKit/pull/30 in the library that handles authentication in the virtual files component for macOS of the desktop client. We now match the behaviour of the classic side of authentication/sync and as a nice bonus it should work with Filerun :)
