### ISSUE TITLE
http3/QUIC support

### ISSUE THREAD

**Issue by Commandcracker** [nextcloud/desktop#7597]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 2.15.0

Are there any plans for http3/QUIC support ?

**Comment by tflidd** [comment]
Even http/2 is not fully deployed yet (or not at all?): https://github.com/nextcloud/desktop/issues/5326

**Comment by Commandcracker** [comment]
So this will only be relevant when http2 is stable.

**Comment by tflidd** [comment]
> So this will only be relevant when http2 is stable.

I don't know. http/2 is already supported server side, just not all clients can handle it. If we can easily enable http3 to make it work on a few clients, this might still be worth it.

**Comment by PetziAt** [comment]
Quic support would be really awesome. Currently syncs with syncthing are much faster. Adding quic support is a gamechanger for a couple of usecases in enterprise environments. Awaiting quic support for a long time. Server setups are ready. ;)
