### ISSUE TITLE
File Manager Overlay Icons not visible in macOS Mojave 10.14 or 10.14.1

### ISSUE THREAD

**Issue by mm8974** [nextcloud/desktop#762]
### Expected behaviour
I expect to see File Manager Overlay icons on files and folders inside of a Nextcloud sync folder as referenced here - https://docs.nextcloud.com/desktop/2.3/navigating.html#file-manager-overlay-icons

### Actual behaviour
After upgrading to macOS Mojave 10.14, the icons disappeared.  When I upgraded I was running 2.3.3 build 84 and just today I installed the macOS client version 2.5.0rc1 (build 20181026). No luck either. 

Interesting change - after installing the 2.5.0rc1 client and before rebooting, I could see the right-click menu but after a reboot the 'Nextcloud' right-click menu disappeared in addition to the overlay icons.  To recover the right-click menu, I had to to a 'Force Quit' on the Finder and 'Relaunch' it.  Once that was done, the Nextcloud right-click  menu was back but the icons are still missing.

### Steps to reproduce
Start the Finder and browse to a Nextcloud folder

### Troubleshooting steps tried:
Confirmed in System Preferences that the Nextcloud extension is activated > Quit and restarted Nextcloud app > turned off Dark Mode > Rebooted computer > upgraded from Mojave 10.14 to 10.14.1 > upgraded client from 2.3.3 to 2.5.0rc1 = Same results.  No overlay icons in Nextcloud Finder folders.

Operating system:

OS language:
English

### Server configuration
Operating system:
    Linux
Web server:
   Apache 2.4
Database:
   MySQL
PHP version:
   5.6
Nextcloud version:
  13.0.5

**Comment by michaelstingl** [comment]
Workaround: 🍎 > Force Quit … > Finder – (needed after every reboot)

Seems this only happens when the client is "autostarted" from the system. After installing the 2.5.0rc1, the client was started manually.

BTW Same for OneDrive:
https://answers.microsoft.com/en-us/msoffice/forum/all/os-x-mojave-onedrive-finder-integration/57413b30-5ae5-4253-8580-282afb3e1d73

**Comment by binarious** [comment]
> Workaround: 🍎 > Force Quit … > Finder – (needed after every reboot)

Doesn't work for me on 10.14.1. Still no overlay icons nor a "Share with Nextcloud" in the context menu of files in my Nextcloud folder.

**Comment by mm8974** [comment]
> > Workaround: 🍎 > Force Quit … > Finder – (needed after every reboot)
> 
> Doesn't work for me on 10.14.1 with 2.3.3. Still no overlay icons nor a "Share with Nextcloud" in the context menu of files in my Nextcloud folder.

I am currently running the macOS client version 2.5.0rc1.  I had a right-click Nextcloud but no overlay icons.  I now have both and this is what I did:
   - 🍎 > Force Quit … > Finder     (This step is probably not needed.)
   - 🍎 > System Preferences > Extensions > Finder Extensions > remove the checkmark from "Nextcloud Extensions"
   - 🍎 > Force Quit … > Finder
   - Check in the Finder to confirm that there is no right-click option or overlay icons.
   - 🍎 > System Preferences > Extensions > Finder Extensions > add the checkmark to "Nextcloud Extensions"
   - 🍎 > Force Quit … > Finder
   - Check Finder now.  I have both.

**Comment by anybodesign** [comment]
Hello,
I'm running the latest version, 2.5.1 final, with macOS 10.14.2
The client app is opened at system startup. After I close a session, when I login again, no more Finder extension (share with nextcloud) nor green dots on folders :)
I have to manually relaunch the Finder (right-click + alt -> Relaunch) to make everything work again.

**Comment by jonasgarstick** [comment]
> Hello,
> I'm running the latest version, 2.5.1 final, with macOS 10.14.2
> The client app is opened at system startup. After I close a session, when I login again, no more Finder extension (share with nextcloud) nor green dots on folders :)
> I have to manually relaunch the Finder (right-click + alt -> Relaunch) to make everything work again.

Same here.

**Comment by squareclouds** [comment]
same here guys, pretty annoying

**Comment by benediktlechner** [comment]
same here.
client (Version 2.5.1final (build 20181204), Mac OS 10.14.3 ) works only if not loaded at system startup

**Comment by antonyjsmith** [comment]
Same here, two different machines both same config:

Version 2.5.1final (build 20181204), Mac OS 10.14.3

**Comment by HigH-HawK** [comment]
macOS Mojave (10.14.4) - Nextcloud app 2.5.2git (build 20190319)

When I open the finder, it shows the Nextcloud folder in my favourites sidebar but no icon to it. The icon is just a grey square with rounded edges. I tried the above workarounds without success.

I even tried reinstalling the app without success.

**Comment by jonasgarstick** [comment]
> macOS Mojave (10.14.4) - Nextcloud app 2.5.2git (build 20190319)
> 
> When I open the finder, it shows the Nextcloud folder in my favourites sidebar but no icon to it. The icon is just a grey square with rounded edges. I tried the above workarounds without success.
> 
> I even tried reinstalling the app without success.

![overlay-icons](https://user-images.githubusercontent.com/17829368/57217550-3812c100-6ff3-11e9-8eb6-3391baf6caea.png)

We were talking about these green overlay icons not the Nextcloud symbol in the sidebar. You are right, the symbol is just a grey square even after a forced finder reboot. That's not nice but the functionality of the overlay icons should work also for you.

**Comment by HigH-HawK** [comment]
Oh dear I may have mistaken the subject here. You are right, these are working for me. Sorry for the confusion

**Comment by croessner** [comment]
Same problem. No context menu and no overlay icons

Latest Mohave and 2.5.1 client here

**Comment by Mojo90** [comment]
Same for me:

Client version: `Version 2.5.2git (build 20190319)`
Operating System: `macOS Mojave 10.14.3 (18D109)` (Dark Mode)
OS language: English

I even do not see the nextcloud sharing item which is shown in the doc [here](https://docs.nextcloud.com/desktop/2.5/navigating.html#sharing-from-your-desktop).

That is how it looks for me: 
<img width="446" alt="Screenshot 2019-06-09 at 23 17 17" src="https://user-images.githubusercontent.com/2122156/59164418-c0ade100-8b0c-11e9-808f-1719d5432c03.png">

**Comment by mm8974** [comment]
@Mojo90 @croessner @michaelstingl  @antonyjsmith 

Yesterday, I found a Dropbox tech support link that indicates that the missing overlay icons in the macOS finder "Nextcloud Extensions" could be caused by 3rd party finder extensions such as OneDrive.  As a result, I am now testing and only allowing Dropbox and Nextcloud "Finder Extensions" to be enabled.  So far the overlay icons are visible and working as designed.

https://www.dropboxforum.com/t5/Installs-integrations/Smart-sync-icons-missing/td-p/322123

- macOS > System Preferences > Extensions > Finder Extensions - review all software injecting finder extensions and disable them all except for Nextcloud.  
- Then...  exit and restart the Nextcloud software
- Check Finder for Overlay icons (green circle with checkmarks or three dotted triangle).  If not, then...
- Restart the finder using "Force Quit"
- Check Finder again.

Please test and let me know how it works for you.

Server - 14.0.8
Desktop for Mac client 2.5.2
macOS Mojave 10.14.4

**Comment by Mojo90** [comment]
@mm8974 
Thanks for this hint, you are right when only Nextcloud is activated it works without any problems. I have Dropbox and OneDrive installed as well.

**Comment by FlexW** [comment]
Does the issue still apply?

**Comment by uselpa** [comment]
I do still have issues though. Mac is a Macbook Air (M1, 2020) running Bug Sur 11.6.1.

The Finder Sync Icons do no longer appear next to the file name. The context menu works though. Restarting the Finder, and updating to 3.3.6 did not change anything (was on 3.3.5 before).

System.log says
```
Nov  8 07:41:40 pumbam1 com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.nextcloud.desktopclient.20154884.23905981(501)> [778]
Nov  8 07:41:40 pumbam1 com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.FinderSyncExt.486D3304-F33E-461B-BDDB-D8EC3FD837F4[971]): Service exited due to SIGKILL | sent by FinderSyncExt[971]
Nov  8 07:41:41 pumbam1 Nextcloud[983]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Nov  8 07:41:45 pumbam1 com.apple.xpc.launchd[1] (com.nextcloud.desktopclient.FinderSyncExt.155EFAC9-0B97-4CF0-89C8-252F4D23EED1[874]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
```

The above file does indeed not exist:
```
pu@pumbam1.fritz.box 503 /System/Library/Frameworks/OpenGL.framework/Resources/GLRendererFloat.bundle $  ll
total 0
drwxr-xr-x   2 root  wheel  restricted   64B Jan  1  2020 .
drwxr-xr-x  13 root  wheel  restricted  416B Jan  1  2020 ..
```

**Comment by uselpa** [comment]
I found it. Another application (https://objective-see.com/products/whatsyoursign.html) seemed to block the overlay icons.

Sorry for the noise.

**Comment by Ninjalope** [comment]
Was there ever a resolution to this? I'm on a M1 Mac air 2020 facing the same problem. I have no other cloud storage clients installed on this machine. I have reinstalled the nextcloud client. The Icons are appearing on my windows machine.

**Comment by uselpa** [comment]
In my case (see https://github.com/nextcloud/desktop/issues/762#issuecomment-963015198), it was a conflicting Finder extension. So I'd suggest you disable them one by one to find out. I never bothered to find out whether the culprit was Nextcloud or the other extension, I just ditched the other one.

**Comment by Ninjalope** [comment]
Yes because of that I have completely removed every other cloud service (including icloud). However, I decided to run through every single extension and remove them one by one and test. Apparently an extension I was using to create new files through the context menu was the culprit. Odd because this new file extension doesn't use status icons at all. Weird! Anyway thanks for the lead!

**Comment by wojosc** [comment]
I just encountered the same problem with a Nextcloud Desktop Client Version 33.0.2 (macOS running on cocoa) on macOS Sequoia Version 15.7.4 (24G517).
I have two accounts linked and when in any of them this

<img width="1016" height="296" alt="Image" src="https://github.com/user-attachments/assets/49a556a2-3871-43db-933d-8c7a72b3a1e3" />

is turned on the icons will now show. Turning it off on both will bring it back.
