### ISSUE TITLE
2.5 documentation update needed for macOS Finder right-click menu

### ISSUE THREAD

**Issue by mm8974** [nextcloud/desktop#763]
The documentation at this URL:
https://docs.nextcloud.com/desktop/2.5/navigating.html#sharing-from-your-desktop

needs to have the text updated and screenshots updated for the new naming of the right-click menu and new options under that menu.

thanks!
<img width="550" alt="nextcloud right-click - a folder shared with nextcloud" src="https://user-images.githubusercontent.com/30050718/47816980-2128a480-dd1a-11e8-99b8-67bcd3de4c98.png">
<img width="636" alt="nextcloud right-click options in macos finder" src="https://user-images.githubusercontent.com/30050718/47816982-2128a480-dd1a-11e8-845a-03264343b097.png">

**Comment by TP75** [comment]
**Agreed.** However, please consider the more general issue _What is the current Client Manual?_ #839 One would expect the availability of a documentation for both the 2.3 and the 2.5 NC Client.
