### ISSUE TITLE
[Bug]: MacOS VFS - Virtual Files aren't virtual

### ISSUE THREAD

**Issue by metaxy** [nextcloud/desktop#7633]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

Virtual Files are just normal files. There is no context menü and no sync indicator in finder.

![Image](https://github.com/user-attachments/assets/1b41a32a-1a3f-47f5-83df-965736d41ad4)

### Steps to reproduce

1. Install nextcloud pkg
2. Login
3. Activate Virtual Files and let it sync

![Image](https://github.com/user-attachments/assets/1f6a605a-319f-46c7-b211-126e4b9f084a)
![Image](https://github.com/user-attachments/assets/d7581e1a-fff9-4bc3-81d4-4f5860bd80eb)
![Image](https://github.com/user-attachments/assets/a42aba50-616a-4e2e-b462-7a9f280ca550)

### Expected behavior

1. The files should be virtual, having a cloud icon and a working context menü

### Which files are affected by this bug

all

### Operating system

macOS

### Which version of the operating system you are running.

macOS 14.6.1 and macOS 15.1.1

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

30.0.2.2

### Nextcloud Desktop Client version

3.15.0

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

### Additional info

![Image](https://github.com/user-attachments/assets/a2029e6b-f9be-4d96-9e85-6ea16d911b07)

[debug.zip](https://github.com/user-attachments/files/18079322/debug.zip)

**Comment by claucambra** [comment]
Hi, you seem to be looking in the wrong location for the virtual files. You can read more in the documentation here: https://github.com/nextcloud/desktop/wiki/Virtual-files-client-for-macOS
