### ISSUE TITLE
Mac Client 2.5 RC1 Swedish translation missing in Finder right-click menu

### ISSUE THREAD

**Issue by maghog** [nextcloud/desktop#767]
Missing Swedish translation in macOS Finder menu.
Can't find untranslated strings (Copy public link to clipboard, Open in browser) at transifex.com.

![menu](https://user-images.githubusercontent.com/1148924/47855670-8dbca580-dde5-11e8-871c-0c1dcb468022.png)

**Comment by rullzer** [comment]
Please join at https://www.transifex.com/nextcloud/nextcloud/dashboard/ to help with translations.

ALl the new stirngs are there now

**Comment by maghog** [comment]
Same problem with RC2

**Comment by rullzer** [comment]
> Same problem with RC2

Well yes nobody translated the string yet. Please join https://www.transifex.com/nextcloud/nextcloud/client/ to help translate :)
