### ISSUE TITLE
[Bug]: no finder-extension with nextcloud vfs on macos

### ISSUE THREAD

**Issue by thejulian** [nextcloud/desktop#7686]
### ⚠️ Before submitting, please verify the following: ⚠️

- [x] This is a **bug**, not a question or a configuration issue.
- [x] This issue is **not** already reported on Github (I've searched it).
- [x] Nextcloud Server and Desktop Client are **up to date**. See [Server Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) and [Desktop Releases](https://nextcloud.com/install/#install-clients) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

The Nextcloud Client VFS Version on MacOS doesn't have the finder extension available.

### Steps to reproduce

Install Nextcloud Client VFS on MacOS. Check System Settings --> General --> Login Items & Extensions --> Finder (I) --> No Nextcloud Extension
![Image](https://github.com/user-attachments/assets/58a47df7-36c9-4f7b-81db-d4f674b57f14)

Installing NOT-VFS shows extension.

### Expected behavior

VFS should also have the Finder extension.

### Which files are affected by this bug

-

### Operating system

macOS

### Which version of the operating system you are running.

15.2

### Package

Official macOS 12+ universal pkg

### Nextcloud Server version

30.0.4

### Nextcloud Desktop Client version

3.15.2

### Is this bug present after an update or on a fresh install?

Fresh desktop client install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [ ] Default internal user-backend
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Server logs

```shell

```

**Comment by claucambra** [comment]
Hi @thejulian you can find the relevant VFS extension settings under File Providers in the Extensions section of the settings

Please note that classic sync folders will not have finder sync integration due to macOS limitations. You can read more about this in our documentation here: https://github.com/nextcloud/desktop/wiki/Virtual-files-client-for-macOS
