### ISSUE TITLE
cannot specify mounted drive as local sync folder

### ISSUE THREAD

**Issue by mluerig** [nextcloud/desktop#770]
### Expected behaviour
specifying a mounted drive as local sync folder (e.g. from root: /mnt/hd2)

### Actual behaviour
mnt folder (and a bunch of other folders) not showing up. I manually type the directory path into the bar, and it will finish the process. but then it doesn't work, as indicated by
i) "unable to initialize a sync journal" as a msg in the folder sync connection
ii) I cannot rightclick + open folder

somehow the client doesn't seem to be able to access that drive. it works if I, for example, chose a folder on from the "home" folder (that one is visible in the client-explorer)

### Steps to reproduce
1. make new sync connection
2. specifiy folder
3. nothing happens

### Client configuration
Client version: 2.3.3

Operating system: Ubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):[where do I find this?]

Client package (From Nextcloud or distro) (Linux only): [where do I find this?]

Installation path of client: /snap/bin/nextcloud-client

**Comment by mahlum** [comment]
Hi,

i think that you tried this with snap. Just use the ppa like described [here](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client). 

Best regards

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
