### ISSUE TITLE
NC Windows Client Timeout

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/desktop#771]
### Expected behaviour
Windows Desktop client should connect.

### Actual behaviour
Get a Connection Timeout error.

### Steps to reproduce
1. Nothing it's totally random. It will be working for days then suddenly times out permanently.
2.
3.

### Client configuration
Client version:2.5.0rc1 (also tried on stable version - same issue)

Operating system: Win10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system: Ubuntu Bionic

Web server: Apache

Database: Mysql

PHP version: 7

Nextcloud version: 14.0.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
([OCC::Application::setupLogging 	"################## Nextcloud locale:[en_US] ui_lang:[en_US] version:[2.5.0rc1 (build 20181026)] os:[Windows 10 (10.0)]"
[OCC::Application::slotParseMessage 	Running for 405.659 sec
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::AccessManager::createRequest 	2 "" "https://xxx/status.php" has X-Request-ID "xxx"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://xxx + "status.php" "OCC::ConnectionValidator"
[OCC::AbstractNetworkJob::slotTimeout 	Network job timeout QUrl("https://xxx/status.php")
[OCC::CheckServerJob::onTimedOut 	TIMEOUT
[OCC::FolderMan::slotAccountStateChanged 	Account "xxx@xxx" disconnected or paused, terminating or descheduling sync folders
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::AccessManager::createRequest 	2 "" "https://xxx/status.php" has X-Request-ID "xxx"

I searched in the Issues but couldn't find any solution that worked.

Just to be clear, I have no problem with my NC connection in a browser - connects perfectly fine at the exact same time the Desktop client is saying it has no connection. I can browse to status.php no problem. My Nextcloud apps all connect perfectly. It's a bug somewhere in the Desktop client.

To go even further, nslookup and ping both work fine from this same machine to my NC server as well.

My server is behind an Nginx reverse proxy if that matters. Here's the conf - again, works perfectly for everything except the Desktop client which randomly times out and can never recover from it:

upstream nextcloudup {
server x.x.x.x;
keepalive 80;
}
	 
 server {
    
	listen xxx ssl http2;
    server_name xxx;
access_log off;
	
	ssl_certificate      xxx.pem;
    ssl_certificate_key  xxx.pem;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS; # Score=90 (recommended)
	ssl_dhparam         xxxdhparam.pem; # openssl dhparam -out dhparam2048.pem 2048
    ssl_ecdh_curve       secp384r1; # optional

	location /{
	proxy_pass http://nextcloudup;
    proxy_buffering off;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
	proxy_set_header  X-Forwarded-Proto https;
    proxy_request_buffering off;
    client_max_body_size 0;
    proxy_read_timeout  36000s;
    proxy_ssl_session_reuse off;
add_header Strict-Transport-Security "max-age=15552000; includeSubDomains";	
         access_log off;    
   }
}

**Comment by mobamoba** [comment]
Okay I think I tracked down a bit of this bug and perhaps it's the source of other people's random timeouts as well: the Windows Desktop app doesn't respect Windows DNS priority settings. My DNS order in Windows is 8.8.8.8 then 1.1.1.1 then my Domain Server (192.168.x.x) then my router's DNS (192.168.x.x).

Nextcloud always picks my Domain Server (which isn't setup to be used as a real DNS). Every other Windows program respect the DNS order except Nextlcoud. I have no idea why Nextcloud is defaulting to LAN DNS that's at the bottom of the list rather than an external DNS that's at the top of the list, but that's what it's doing and that's the reason for the timeout.

If I disable 192.168.x.x in my DNS, the timeout goes away. When I reenable it, Nextcloud picks that incorrect DNS to use and doesn't try any of the others on the list.

At any rate, hope that points you in the direction of the bug. Thanks.

**Comment by mobamoba** [comment]
Maybe it's an upstream bug? All I know is that, when using a packet sniffer-type program to try to track down why Nextcloud was the only app that couldn't connect, I saw that it was connecting using the wrong DNS unlike everything else on my system and, once I was able to force the app to use the correct DNS (by disabling that LAN DNS in Windows), Nextcloud connected fine. As I mentioned, it shouldn't have been using that DNS at all since it's last on the priority list and nothing else on my system uses other than occasionally.

I tried using the Owncloud app and it did the same thing. I wonder if this DNS issue is the source of other people's intermittent timeout problems.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
