### ISSUE TITLE
Quick question: Does the client Ignore list recognize subfolders?

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/desktop#772]
I know that I can ignore a directory named "node_modules" but can I have it ignore a specific node_modules directory by writing something like ".vscode/extensions/node_modules"?

**Comment by jospoortvliet** [comment]
I suggest to try it ;-)

In either case, please ask questions on help.nextcloud.com!

**Comment by jcklpe** [comment]
Thank you and apologies. I will go create a thread on the forum. (btw, great job on the forums! I have been doing some stuff with mediawiki and OnlyOffice the last couple of months too and their forums are abysmal! OnlyOffice isn't even properly using https so it gets a warning message from the browser all the time). 

I have tried doing this but it's hard for me to tell if this feature is supported or I'm just getting the specifics of my syntax wrong.
