### ISSUE TITLE
RC1 encrypt folder - Please wait for the folder to sync before trying to encrypt it.

### ISSUE THREAD

**Issue by maghog** [nextcloud/desktop#777]
Desktop Client 2.5 RC1 for Mac and Windows.
Server 14.0.3

Try to encrypt folder:
Please wait for the folder to sync before trying to encrypt it.
All folders are synchronized...

<img width="425" alt="skarmavbild 2018-11-02 kl 10 12 18" src="https://user-images.githubusercontent.com/1148924/47906410-7800bc00-de89-11e8-9e97-dfe895c4ce39.png">

**Comment by zeigerpuppy** [comment]
I am also having this problem with Version 2.5.0daily (build 20181026).
OS X 10.11.6
Also on Nextcloud v14.0.3

**Comment by maghog** [comment]
Same with RC2

**Comment by shwebstart** [comment]
Same Problem with Version 2.5.0v2.5.0 (build 20181112).
Windows 10 - 1803 Build 17134.407
Nextcloud 14.03 server installation

**Comment by SnejPro** [comment]
I solved the problem for me by deactivating the E2E-Plugin, deleting all files and databaseentrys of the plugin and wiping the whole client configuration on Windows.

Afterwards, I have reconnect the Client to the Server, got a new E2E-Key. Now it works.

**Comment by shwebstart** [comment]
@SnejPro 
Which databaseentrys  of the end_to_end_encryption app did you delete?
Thanks.

**Comment by SnejPro** [comment]
@shwebstart the whole table with this name

**Comment by blu-IT** [comment]
Same problem with Windows 10 Pro (x64), NC 14.04 and NC-client version 2.5.1daily (build 20181205).

**Comment by blu-IT** [comment]
Still same problem with Windows 10 Pro (x64), NC 14.04 and NC-client version 2.5.1.5041-daily (build 20190129).
Encrypting a new folder with the Android client v. 3.5.0 RC1 works and the desktop client recognizes encrypted folders, but encrypting a new folder with desktop client is not possible.

**Comment by evilSwanson** [comment]
Same problem.
Version 2.5.2 on Ubuntu 18.04.
According to my provider the server version is 16 and E2EE is activated.

**Comment by er-vin** [comment]
I can't reproduce it anymore on master. Feel free to open again if it shows up on future 2.7 releases.

**Comment by john-2000** [comment]
Sorry to ask but I am experiencing this on NC 20.0.1 and Client 3.02 on ubuntu 20.10 - is there a way to fix it?

**Comment by er-vin** [comment]
Well, as I mentioned we don't reproduce it anymore. If you still have it, please open a new ticket, follow the issue template and provide us as much information as possible (with client debug logs in particular). Thanks in advance.

**Comment by functioneer** [comment]
Same problem here.  

Nextcloud client 3.0.3.15941 on Windows 10 64bit 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041

NextCloud Server
snap list nextcloud
Name Version Rev Tracking Publisher Notes
nextcloud 20.0.1snap1 24051 latest/stable nextcloud? -

Distributor ID: Ubuntu
Description: Ubuntu 20.04.1 LTS
Release: 20.04

Thank you.

**Comment by psi-4ward** [comment]
Same here. Tried https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590 after upgrading to 20

**Comment by FlexW** [comment]
@Gerdal I don't hit that problem. Could you provide us steps to reproduce the problem? Otherwise we are not able to fix it.

**Comment by Gerdal** [comment]
I have already set encryption. Because I got many 409 errors and files in this dir weren't uploaded to server, I have disabled the e2ee app, deleted the encrypted dir and files, reactivated the e2ee app, created new directory with the same name as before and now this dir can't be encrypted anymore. When I create another directory with different name - this also can't be encrypted anymore. I've tried to delete sync settings from desktop app and setup sync again. Directories mentioned before can't be encrypted anyway. But, no problem, I'm migrating my data to another cloud. Server side encryption in nextcloud - many problems, e2ee also... I'm using stable channel release but I feel like I'm on beta or daily version. Every update brings many problems, especially since version 20.

**Comment by janvlug** [comment]
I have this issue now on Fedora 36 with Nextcloud Desktop version: Version 3.4.4 (Fedora)
Nextcloud end-to-end encryption app version: 1.8.1
Nextcloud Server version: 22.2.6

**Comment by nphalem** [comment]
@FlexW Issue is still present. I'm unable to encrypt any of my folders, existing or newly created ones.

I get the following error when I try to encrypt them:
"Please wait for the folder to sync before trying to encrypt it."

Keep in mind that folders are synced.

Nextcloud end-to-end encryption app version: 1.11.1
Nextcloud Server version: 25.0.2
Nextcloud Desktop Client: 3.6.4 (Arch)

If any additional information is needed, I'll do my best to provide it.
