### ISSUE TITLE
NextCoud spams Nemo log with socket error

### ISSUE THREAD

**Issue by ChrisDeath** [nextcloud/desktop#784]
In Cinnamon (Linux Desktop) Nemo is used as file manager. If you look at its log it spams the log with following entry every second:

`
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket. [Errno 2] No such file or directory
`
### Expected behaviour
No Log occures

### Actual behaviour
The mentioned error message occurs. But Nemo keeps working. The "synced marker" on folders are not displayed, don't know if intended under linux.

### Steps to reproduce
1. Install Nextcloud Desktop Client
2. Open Nemo (to see log: Terminal and then call "nemo ."
3. see terminal output

### Client configuration
Client version: 2.3.3 GIT-Revision 57bc79

Operating system:
Manjaro Linux, Cinnamon 3.8.9, Kernel 4.19.0-4-MANJARO

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.11.2, OpenSSL 1.1.1 11 Sep 2018

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
using AUR: https://aur.archlinux.org/packages/nextcloud-client/

### Logs

```
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket. [Errno 2] No such file or directory
```

**Comment by juliushaertl** [comment]
This seems to be a bug of your distributions package. The file manager integration is not using the proper socket path, which should be /run/user/1000/Nextcloud/socket.

**Comment by ChrisDeath** [comment]
Strange that you know how it should be, but not how it gets there. But i was so nice to dig into it, just to help you out here:
https://github.com/nextcloud/desktop/commit/98785590025b6b349c7a26db6b2bb22d15773591#diff-66e7fdaaa4eea7c61cfbfbe1fe52c5c6

This change was not present in version 2.3.3. So it seems to that it was/is a bug of the source code itself. Is 2.5.0 RC already releasable or do you need to do a backport patch?

**Comment by juliushaertl** [comment]
@ChrisDeath The 2.3.3 client was built from a different repo. We already had the values you are mentioning there: https://github.com/nextcloud/client_theming/blob/master/nextcloudtheme/OEM.cmake

Since you are using the aur package, have you made sure, that the optional `nemo-python` dependency is installed?

**Comment by ChrisDeath** [comment]
Hi
nemo-phyton is installed.
In AUR the source is given with https://github.com/nextcloud/client_theming/archive/v2.3.3.tar.gz 
As far as i understand that belongs to this repo here, right?
It then calls:
```cmake -D OEM_THEME_DIR="${srcdir}/client_theming-${pkgver}/nextcloudtheme" ../client \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc/${pkgname}```

Looks fine for me as nextcloudtheme include the OEM.cmake. I may will check 2.5.0 RC2 in a VM if it fixes the issue.

**Comment by ChrisDeath** [comment]
Hi
i tested https://aur.archlinux.org/packages/nextcloud-desktop/ (2.5.0) and it works without spaming and even adding the checkmarks on folder/file icons.
Thanks for your support.
