### ISSUE TITLE
[Windows] File Explorer - Integrate a Cloud Storage Provider: Drop down sub paths

### ISSUE THREAD

**Issue by JarbyDev** [nextcloud/desktop#787]
I would like to know if Nextcloud Windows Sync will be implementing this, this has been already implemented on Owncloud Windows Client,  See Thread Below

https://github.com/owncloud/client/issues/5295

**Comment by juliushaertl** [comment]
This will be available in the upcoming 2.5.0. Feel free to give the prerelease a try: https://download.nextcloud.com/desktop/prereleases/Windows/

**Comment by JarbyDev** [comment]
I tried the 2.5RC2, I did many tests and is working perfectly. Thx
