### ISSUE TITLE
RC2 client syncs files at the same level of a selected folder

### ISSUE THREAD

**Issue by CommonBlob** [nextcloud/desktop#791]
### Expected behaviour
When selecting a folder to syncronise from external storage within the client, this folder should be syncronised.  

### Actual behaviour
When selecting a folder it correctly syncronises this folder, but it also syncs any files that are at the same level as this.

Root
x Subfolder 1
  Subfolder 2
  File1
  File2

If I was to select Subfolder 1 above that I selected, it would also sync file1 and file2 incorrectly.

### Steps to reproduce
1.  Setup Nextcloud 14.0.3
2. Enable SMB and a share to a Windows file system
3. Connect a client and select a folder to sync that has some files at the same level
4. see that the files are incorrectly synced

### Client configuration
Client version: 2.5 RC2 +

Operating system: Windows 10 1803

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

### Server configuration

Operating system: Ubuntu 18.04

Web server: NGINX 1.15.6

Database: MariaDB 10.3

PHP version: 7.2-FPM

Nextcloud version: 14.0.3

Storage backend (external storage): Windows Server 2016

**Comment by CommonBlob** [comment]
Further more, we have discovered that any new folders at the folder level are set to sync automatically, even though they are not selected.

In the example above, if i was to create Subfolder 3, it would be set to automatically sync to the client incorrectly.  Only subfolders and files of subfolder 1 should be selected.

This is causing 10's of GBs of data to sync down to a number of our users.

**Comment by karagian** [comment]
Had to find out how this thing works, and it seems that what actually happens, is the exact opposite of what you may think is happening... When saving the folder selection settings, what is actually written to a sqlite database, is a list of all the folders that have been **excluded** from syncing (not checked) and not the other way around as one might normally think. That said, if a new folder is created somewhere in scope, the folder is automatically synced...

**Comment by CommonBlob** [comment]
Interesting.  Dont want to jump to conclusions on why doing this seems odd, but it does sound odd.  We are now setting our clients back up to sync folders with individual sync connections to avoid this happening.  But Id much rather it worked like I had originally thought.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
