### ISSUE TITLE
2.5-rc2 Windows interface goes completely blank

### ISSUE THREAD

**Issue by brianbgness** [nextcloud/desktop#793]
### Expected behaviour
Windows client interface should not go blank

### Actual behaviour
The body of the user interface goes completely blank.  But the client is still syncing normally.  Here is the window; it's all white inside.  The fix is to quit the client and restart it.

![snip110618](https://user-images.githubusercontent.com/24630430/48091683-39d40700-e1bf-11e8-972d-8576ac38777a.PNG)

### Steps to reproduce
1. Run Windows 2.5-rc2 client
2. Wait overnight
3. Return in morning to this

I cannot find any errors anywhere.  Overnight my server goes into maintenance mode, then stops httpd, and mariadb before backing up.  Perhaps this glitch is related to the server returning online after the backup?   Please ask if you need further information.

**Comment by CommonBlob** [comment]
Not sure if its related, but with multiple screens and Displaylink we get this and believe this is a bug with QT.  I found this bug report that describes the issue:

https://bugreports.qt.io/browse/QTBUG-65882

Have you got multiple monitors? If so, do you get this when they are not connected?

**Comment by brianbgness** [comment]
Yes, my Lenovo x250 laptop is docked to a Lenovo docking station using Displaylink.  But only with one monitor.  The glitch seems random.  It does not occur every day.  I'll report back to you when I have more information to share.

**Comment by pzwahlen** [comment]
Same story here on 2.5.1 on Windows 10. I'm using a docking station and it might be that the problem happens after dock/undock.

The interface opens completely blank, however as soon as you click on a "button" (like the top-left account), then the interface comes back and is 100% functional.

**Comment by camilasan** [comment]
We definitely don't have this issue anymore. I don't recall now when it was fixed.
To check that please install 3.1.2.
