### ISSUE TITLE
Nextcloud client 2.5 RC2 does not work with KDE password manager / KWallet

### ISSUE THREAD

**Issue by eehmke** [nextcloud/desktop#799]
### Expected behaviour
Passwords should be taken from the password manager automatically

### Actual behaviour
I have to enter the password each time manually. Until RC1 this worked fine.

### Steps to reproduce
Upgrade from RC1 to RC2

### Client configuration
Client version: 2.5 RC2

Operating system: Linux Mint 18.3
KDE and KDE Wallet installed

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.11.0

Client package (From Nextcloud or distro) (Linux only):
Nextcloud-2.5.0.20181105-rc2-x86_64.AppImage

Installation path of client:
/usr/local/bin

Nextcloud version: 14.0.3

**Comment by eehmke** [comment]
Solved with version 2.5 final.

**Comment by eehmke** [comment]
I have the same problem again with 2.5.2. The client seems to start before the password manager. When I then close the client and restart it, it gets the password and runs fine.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
