### ISSUE TITLE
No file manager integration and overlay icons in Debian (with 2.3.3 and 2.5.0 daily Linux appimage )

### ISSUE THREAD

**Issue by magicvince** [nextcloud/desktop#804]
In file manager (nautilus or nemo) there's no overlay icons and menu to share files and repertories

Client version: Linux Appimage 2.3.3 or 2.5.0 daily (Built from Git revision aff749 on Jun 22 2018, 10:15:32 using Qt 5.9.3, OpenSSL 1.0.2g 1 Mar 2016)

Operating system: Linux Mint Dedian Edition 3 Cindy (a custom Debian 9 Stretch)

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.9.3

Client package (From Nextcloud or distro) (Linux only): from Nextcloud

Installation path of client: /home/user/Applications/Nextcloud

### Server configuration
Same issue with onwcloud 10 to nextcloud 13

### Logs

Log file empty

**Comment by juliushaertl** [comment]
@rullzer I guess there is no way to have app images ship a file that is then lateron moved to the nautilus/nemo plugin directory, right?

**Comment by jancborchardt** [comment]
For the record, this is the hacky way to fix Nautilus integration:
```
sudo apt install python-nautilus
wget -O ~/.local/share/nautilus-python/extensions/syncstate-Nextcloud.py "https://raw.githubusercontent.com/nextcloud/desktop/master/shell_integration/nautilus/syncstate.py"
```
But we should really have a proper way to do this automatically …

**Comment by helmo** [comment]
The debian package from the [ppa](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client) is not adding that file either.

There is a separate [nautilus-owncloud package in the official Ubuntu repositories](https://packages.ubuntu.com/bionic/nautilus-owncloud)
