### ISSUE TITLE
captive portals should be detected and handled

### ISSUE THREAD

**Issue by markum** [nextcloud/desktop#81]
At the moment the desktop sync client does not handle captive portals very well. It reports a certificate error, showing the certificate of the captive portal which has to clicked away. It would be better if the client recognised that there is a captive portal and just wait until it was handled by the os and then retry. It could also trigger the login page of the portal, but that is nice to have. The main issue is that there is always these annoying messages to click away. I am using Ubuntu 16.04 is that matters.

**Comment by jancborchardt** [comment]
@camilasan @rullzer this is indeed quite annoying and I get this every time in hotels, cafés, airports, trains etc with captive portals.

It’s something we got used to and always click away. But it’s a really scary and difficult to understand error window.

**Comment by michaelstingl** [comment]
see also previous discussion in the upstream project https://github.com/owncloud/client/issues/3120

**Comment by jaller94** [comment]
The redesign of that window seems like a different task to me.
In order to keep the portal detection on point, I suggest to limit this issue to it.

**Comment by jancborchardt** [comment]
@camilasan what do you think? This happens each and every time you are at in a train, at a hotel, at an airport, in a café etc.

**Comment by arthurlogilab** [comment]
I would also benefit from this type of handling of certificates for a usecase where the nextcloud is behind a VPN, so before I connect I get an invalid certificate and after I connect the client stays "logged out"

**Comment by jancborchardt** [comment]
@camilasan @misch7 @DominiqueFuchs also ref for the Desktop hackweekend. :) I think this is a really quick win to make the desktop client less scary and not appear to be broken when it’s not.

**Comment by vasyugan** [comment]
> 
> 
> I would also benefit from this type of handling of certificates for a usecase where the nextcloud is behind a VPN, so before I connect I get an invalid certificate and after I connect the client stays "logged out"

And why this is just a nuissance for us, it is a real problem with many of my non tech savvy users. Their client is suddenly disconnected from the server, on Windows the systray icon is typically hidden, so they don't even notice that the icon has changed to gray, and many of them wouldn't even understand what this means. We really need the client to handle this intelligently in the background.

**Comment by davidc** [comment]
It definitely needs to retry automatically, I keep finding I've not been syncing for days because I once passed a coffee shop a week ago. Nothing besides the hidden grey icon is informing me that I'm not in sync, and why should I have to keep remembering to look for that?

**Comment by mgallien** [comment]
this is something that will be much easier once we have finished moving to Qt6 as the code there for detecting network state is able to provide the information of the presence of a captive portal
that should make us able to trigger your default browser to login and then the desktop client would restart by itself the network requests
