### ISSUE TITLE
Update icons to the new background

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/desktop#810]
Desktop:
![image](https://user-images.githubusercontent.com/3404133/48348844-bfa1f780-e682-11e8-827e-d856e77d9322.png)

Android:
![image](https://user-images.githubusercontent.com/3404133/48348776-908b8600-e682-11e8-9b9e-e82b5dcf1554.png)

iOS:
![image](https://user-images.githubusercontent.com/3404133/48348795-9ed9a200-e682-11e8-9c17-7e59a5ed95c2.png)

**Comment by rullzer** [comment]
Let me summon @jancborchardt !

**Comment by JanDragon** [comment]
Are these the new icons or the old ones?

**Comment by JanDragon** [comment]
And what does the new logo look like?

**Comment by juliushaertl** [comment]
@JanDragon The logo is still the same, just the icon background has changed, as you can see in the iOS/Android icons.

**Comment by jancborchardt** [comment]
The current icon files are in the promo repo at https://github.com/nextcloud/promo

the logo you need is the round one with background, as we should uniformly move to round icons (except iOS cause they of course are mandated by Apple):
![](https://raw.githubusercontent.com/nextcloud/promo/master/nextcloud-icon-background-round.png)
https://github.com/nextcloud/promo/blob/master/nextcloud-icon-background-round.png

For the installation wizard, the background is available:
- with blue background: https://github.com/nextcloud/promo/blob/master/background-4k.png
- or transparent: https://github.com/nextcloud/promo/blob/master/background-4k-transparent.png

If you need a specific format or modifications, let me know the size. :)

**Comment by DominiqueFuchs** [comment]
As I just updated #22 and now noticed this one: @jancborchardt is the info with the round logo as default for the app still up2date? Just asking because the promo repo README sound to me as is it would be the square one. However, I can happily work on this while completing the tile issue.

**Comment by jancborchardt** [comment]
@DominiqueFuchs hi, thanks for the inquiry! Yes, the info is still up to date, icon should be round. :)

Will you be at the conf in Berlin later this month? https://nextcloud.com/conf-2019/

**Comment by DominiqueFuchs** [comment]
Alright, I'll take a look into bundling and source refinements for the windows package regarding the updated logo.

Thanks for the hint! @misch7 also pointed that out in another issue, sadly I noticed this too late to arrange some time for this. Looking forward to next year, sounds like a great opportunity to get in touch :)
