### ISSUE TITLE
Problems trying to create a snap for 2.5.0

### ISSUE THREAD

**Issue by pachulo** [nextcloud/desktop#814]
Hi! I've been trying to create a snap for the new version of the desktop client.

I install it wiht `sudo snap install nextcloud-client_2.5.0_amd64.snap --devmode`
It compiles and installs OK, but when trying to start it does a core dump and fails:
```
$ nextcloud-client
Qt: Session management error: None of the authentication protocols specified are supported
Avortat (s'ha bolcat la memòria)
```

This happens if I install the snap with no previous version installed.
If I update the version that is in the snap store with the one I compiled it starts OK, but it does not seem functional: folders don't sync and I can't really configure anything.

[Here is the code to create the snap](https://github.com/pachulo/desktop/blob/create-snap-package/snap/snapcraft.yaml), which is is based in [the old one](https://github.com/nextcloud/client_theming/blob/master/linux/snap/snapcraft.yaml).

Here are the logs and the download links from the builds: https://launchpad.net/~pachulo/+snap/nextcloud-desktop-pachulo

**Comment by e-alfred** [comment]
Maybe @kyrofa can help with that? A new release of the Nextcloud client as a Snap would be great.

**Comment by pachulo** [comment]
OK, I found a solution, I now need to create a PR for the new snap version.
