### ISSUE TITLE
Add ability to copy direct link

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#815]
The server has this nice 'copy direct link' button:
 ![screenshot_20180718_132308](https://user-images.githubusercontent.com/551757/42878530-b74b4074-8a8d-11e8-923d-aee896761deb.png)
(the little notepad)

I'd love to see it too in the desktop client share dialog :racing_car:

**Comment by stalker314314** [comment]
There is 'copy direct link' menu, but it is hidden in drop-down menu in sharing dialog. Sole fact that you filed this issue means that it definitely can be more visible, I just wanted to comment so people looking at this issue are aware. Issue either should be closed, or renamed as "Make copy link more prominent" :)

![pic](https://user-images.githubusercontent.com/188751/52183486-3b35bf80-2800-11e9-937b-b3a659126b90.png)

**Comment by camilasan** [comment]
> Issue either should be closed, or renamed as "Make copy link more prominent" :)
> 
> ![pic](https://user-images.githubusercontent.com/188751/52183486-3b35bf80-2800-11e9-937b-b3a659126b90.png)

What do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
@stalker314314 @camilasan the "Copy link" there is not the same as the "Internal link" @jospoortvliet is referring to.

However, the implementation of that needs to be properly discussed, which is happening in https://github.com/nextcloud/server/issues/12877
(The "internal link" was added a long time ago without proper design discussion, which now results in confusion like people copying the internal link, thinking others not on that Nextcloud can open it.)

**Comment by FlexW** [comment]
@jancborchardt @jospoortvliet @camilasan What is the status of this? Should we close this issue?

**Comment by jancborchardt** [comment]
We have it in the right-click menu, but the sharing dialog doesn't have it like the web interface or mobile apps, where "Internal link" is an extra entry.

For feature parity that would be the 100% solution. :)
