### ISSUE TITLE
Share dialog alignment

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/desktop#817]
The UI elements in the new share dialog are a bit unaligned.

![image](https://user-images.githubusercontent.com/3404133/48401627-dd766780-e729-11e8-9260-683eb80de80b.png)

- The share input field should fill all the available width-
- Same for the share link label (Enable checkbox and 3-dots menu shold be right aligned)
- Label of the share list seems to be cut off to early
- Different padding of the share list and the other elements looks a bit odd

**Comment by rullzer** [comment]
@jpnurmi if you are up for more UI fixes :wink: :)

**Comment by jpnurmi** [comment]
Sure, I can take a look after work :)

**Comment by jpnurmi** [comment]
Hmm, what's the best way to test changes to ShareDialog? Any shortcut to avoid having to go through the shell integration?

**Comment by camilasan** [comment]
@jpnurmi  I recall having to do the following:

$ sudo chmod 777 /usr/lib64/qt5/plugins/
...compile & install...
$ sudo cp ~/$INSTALL_DIR/share/kservices5/nextclouddolphinactionplugin.desktop /usr/share/kservices5/

**Comment by jpnurmi** [comment]
@camilasan Thanks, I got the shell integration working, but it was a bit slow to test from within Dolphin (for some reason it takes time for Nextcloud to show up in Dolphin). I ended up calling `slotShowShareDialog()` to force a share dialog show up for testing on startup. :)

**Comment by jpnurmi** [comment]
The progress indicator in the middle of the dialog is tricky. It pushes the content below and makes the dialog size jump back and forth. Would it be an option to move it out of the way to the top right corner, for example?

**Comment by jpnurmi** [comment]
Current | Alternative
:-------------------------:|:-------------------------:
![share-dialog](https://user-images.githubusercontent.com/140617/48640001-ae841e00-e9d5-11e8-81ee-89eede9ab0eb.gif) | ![share-dialog2](https://user-images.githubusercontent.com/140617/48640004-b04de180-e9d5-11e8-9e30-498c28d2e930.gif)

**Comment by rullzer** [comment]
Let me summon @jancborchardt 

The right one looks a lot more clean IMO

**Comment by jpnurmi** [comment]
A singular progress indicator could be combined with a tooltip that explains what is in progress, but it's not perhaps the most intuitive and easy to discover option.

Alternatively, we could have multiple progress indicators, each embedded into the respective entry field. It could look pretty nice if the confirmation buttons would be as side actions inside the editors, and if they would turn to progress indicators when a related job is in progress. I'll post a mockup later. :)

**Comment by juliushaertl** [comment]
@jpnurmi That looks really nice :+1: This way we also have a better indication what the progress is about.
