### ISSUE TITLE
Default theme on KDE when using Appimage has invisible 3-dot menu

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#825]
Version 2.5.0, app image, Plasma Desktop:
![screenshot_20181113_210207](https://user-images.githubusercontent.com/551757/48439762-61ab0800-e787-11e8-86a4-3b8668625c11.png)
(the 3-dot menu I just clicked is invisible, both when selected or unselected)

**Comment by jancborchardt** [comment]
Can confirm on Ubuntu GNOME, no matter if using regular or dark theme:
![nextcloud desktop app 3 dot menu icon missing](https://user-images.githubusercontent.com/925062/49099070-ce86cd80-f270-11e8-86cc-e45dfcec9782.png)

**Comment by claell** [comment]
Is this Linux specific? Did you also use the AppImage @jancborchardt?

**Comment by jancborchardt** [comment]
This seems to have been fixed since some time, can’t reproduce it anymore. :)
