### ISSUE TITLE
icon on mac OS Mojave

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/desktop#828]
V 2.5.0.rc2 click on Dock 

![18-11-14 11-10-50 0730](https://user-images.githubusercontent.com/8616947/48476128-7d9dc080-e7fe-11e8-9968-ec1086995a98.jpg)

**Comment by MorrisJobke** [comment]
I have the same issue - once I clicked it it's normal again. I also have this with one other macOS application. Until the very first click on that icon the background is black.

**Comment by MorrisJobke** [comment]
cc @camilasan @rullzer

**Comment by er-vin** [comment]
Quite old, seems to be fixed already.
