### ISSUE TITLE
Client 2.5.0git could not connect after granted access

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/desktop#830]
### Expected behaviour
Upgrading from 2.3.3 restart pc and everything works like before

### Actual behaviour
Connection to nextcloud server do not work with version 2.5. After installation and restarting it ask me to login an hangs up while trying to connecting (images and apps are loaded), but get not connected.

### Steps to reproduce
1. Remove old installation (2.3.3)
2. Install version 2.5.0git
3. 

### Client configuration
Client version:
2.5.0git via ubuntu repository 

Operating system:
Ubuntu 18.04

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
from nextcloud deb

Installation path of client:
default path

### Server configuration

Operating system:
Offizial docker container

Web server:
fpm

Database:
mysql

PHP version:
official docker contaienr 14.0.3-fpm

Nextcloud version:
14.0.3

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

<details><summary>1. Client logfile</summary>

Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

(nextcloud:4804): Gtk-WARNING **: 19:47:54.703: Theme parsing error: gtk.css:385:8: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.703: Theme parsing error: gtk.css:385:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nextcloud:4804): Gtk-WARNING **: 19:47:54.703: Theme parsing error: gtk.css:453:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:623:68: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:636:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:648:67: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:660:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:669:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:681:68: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:691:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:704:67: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:715:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:724:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:744:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:754:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:775:69: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.704: Theme parsing error: gtk.css:819:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:933:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:943:74: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:956:58: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:967:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:976:74: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1019:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1133:71: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1143:73: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1156:58: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1167:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.705: Theme parsing error: gtk.css:1176:73: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.706: Theme parsing error: gtk.css:1295:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2103:58: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2264:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2270:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2277:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2324:67: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2333:69: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2342:69: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2351:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2391:54: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.708: Theme parsing error: gtk.css:2396:56: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.709: Theme parsing error: gtk.css:2909:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.710: Theme parsing error: gtk.css:3218:17: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(nextcloud:4804): Gtk-WARNING **: 19:47:54.712: Theme parsing error: gtk.css:4439:58: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.713: Theme parsing error: gtk.css:4463:72: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.713: Theme parsing error: gtk.css:4474:74: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.713: Theme parsing error: gtk.css:4483:71: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.713: Theme parsing error: gtk.css:4492:74: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.713: Theme parsing error: gtk.css:4500:74: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.714: Theme parsing error: gtk.css:4901:55: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5365:68: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5374:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5383:67: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5392:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5400:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5447:9: Not using units is deprecated. Assuming 'px'.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5447:9: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5674:16: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.715: Theme parsing error: gtk.css:5674:16: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6359:14: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6359:14: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6364:10: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6364:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6378:23: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6386:14: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6386:14: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6388:15: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(nextcloud:4804): Gtk-WARNING **: 19:47:54.717: Theme parsing error: gtk.css:6438:13: The 'icon-shadow' property has been renamed to '-gtk-icon-shadow'

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6551:16: The 'outline-radius' property has been renamed to '-gtk-outline-radius'

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6574:52: The :prelight pseudo-class is deprecated. Use :hover instead.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6627:14: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6627:14: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6937:10: Not using units is deprecated. Assuming 'px'.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.718: Theme parsing error: gtk.css:6937:10: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7284:12: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7284:12: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7292:14: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7292:14: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7301:16: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7301:16: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7306:14: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7306:14: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7370:68: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7379:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7388:67: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7397:70: Using one color stop with linear-gradient() is deprecated.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7405:12: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7408:16: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7408:16: Expected a string.

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7416:12: not a number

(nextcloud:4804): Gtk-WARNING **: 19:47:54.719: Theme parsing error: gtk.css:7416:12: Expected a string.
</details>

2. Web server error log:

Shows no errors

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by CordlessWool** [comment]
Ok now I see some logs on server side: 

Error | end_to_end_encryption | Can't create public key: could not sign the CSR, please make sure to submit a valid CSR | 2018-11-14T20:17:31+0100
-- | -- | -- | --
Error | PHP | openssl_csr_sign():  cannot get CSR from parameter 1 at  /var/www/html/custom_apps/end_to_end_encryption/lib/SignatureHandler.php#60


It seem a problem with the encryption module. I disabled it and the connection and sync works fine. But when I enable the e2e encryption module again and restart the desktop sync client it fails again.

**Comment by hillebr** [comment]
I´m just facing the same issue - maybe its related to: https://github.com/nextcloud/server/issues/8884
...will try it later the day with a newly created user.

HTH

René

**Comment by hillebr** [comment]
...confirmed!
After deleting (backup contacts, calendars before if appropriate) and recreating the user (and syncing files back from local folder) I can completely connect to my NextCloud instance with enabled e2e encryption module.
The e2e encryption module works flawlessly on desktop client & mobile device after syncing the encryption passphrase on both devices.

HTH

René

**Comment by mickare** [comment]
I could not get it working and I had to disable e2e.

The client refuses to connect to my nextcloud instance.
Client Log Output: https://gist.github.com/mickare/36ca4cf633c5316fd675d8c752d9686c

@hillebr How did you cleanly recreate the user? I tried it several times but could not get it working.

**Comment by hillebr** [comment]
Firt make a backup of your contacts (vcard) an calendars (ical) then disconnect your desktop client and move over to your instance
Within your NextCloud directory (e.g. /var/www/html/nextcloud) execute: 
sudo -u www-data php occ -vv user:list
to show existing users and then:
sudo -u www-data php occ -vv user:delete hillebr
(to delete user hillebr on debian system)
If you are on other distribution you maybe have to change the web user (www-data on debian based systems)
The create a new / the same user via web interface, import contacts and calendars and add the new/same account to the desktop client with sync retaining the existing files in your folder.

HTH

René

**Comment by mickare** [comment]
Thank you for the detailed description.

Unfortunately I am on a managed nextcloud instance, meaning I do not have access to the system. :(
I have to contact the support then...

thx nevertheless

**Comment by plrunner** [comment]
> At the document foundation, we have been able to reproduce the issue.
> Link to our internal bug report: https://redmine.documentfoundation.org/issues/2658
> Btw, we are still unsure whether this could be related to the E2E module. I'm waiting for TDF sysadmins to answer this question.

Very same problem here, and I do not have e2e, so I think it's not related to i.

**Comment by wget** [comment]
@plrunner In the meantime I received an answer from TDF admins, we are not running the E2E encryption module.
But we have a SAML implementation using LemonLDAP::NG

**Comment by plrunner** [comment]
I use LDAP authentication.

**Comment by DavidDohmen** [comment]
This problem also affects us. We're not using the e2e module either. Not LDAP authentication.
Let me know, if I can run any tests or provide logs, if it helps with the solving the problem.
Our current work around is using the ownCloud desktop client, which is quite ugly.

**Comment by pascal-niklaus** [comment]
@DavidDohmen and others that don't use e2e: are you sure it is not simply 'overwriteprotocol’ => ‘https’ missing in config.php in the docker container? I had the same phenomenon (owncloud working, nextcloud not working), and this made the difference.

**Comment by DavidDohmen** [comment]
@pascal-niklaus, thanks for your suggestion. I just tried it out but it doesn't fix the problem. Still looping at the "Grant access" screen...

**Comment by AdrianBan** [comment]
I'm facing the same issue. Couldn't find an workaround. Any updates?

**Comment by beje2k15** [comment]
Hello,

I'm also affected wit ha fresh install of nextcloud. It appears to be an issue with https-only installations (like in my case).
Once you click on "Grant Access" in the setup process you're stuck. When you click back on the bottom of the window you can see that the scheme changed from https to http. Of course this will not work if your webserver is not listening on port 80.

After I noticed this I was able to find a workaround:
- enable http acces in your webserver
- Use the client to connect to your server. After you finished this you will see in the main window "connected with http://...".
- shutdown the client and edit .config/Nextcloud/nextcloud.cfg and change the the url from http to https
- restart the client. At this point you will need to reenter your credentials and this time the scheme is not changing back to http
- Now you can disable http access in your webserver again (perhaps you can do this after you sucessfully logged in the first time, however I did not try it)

This must be a client issue as I add an HTST in my webserver for nextcloud and in nextclouds config.php "overwrite.cli.url" is set to https://

Client version is nextcloud/desktop@56c905. Serverversion is 15.0.5

**Comment by HudsonProdigy** [comment]
We are still having same issue with both the mac and windows desktop clients. We can not switch to http as our instance is federated with SAML app through our ADFS server and ADFS will not return response to http, it must be https endpoint.

**Comment by DominiqueFuchs** [comment]
Fixed by #1420

**Comment by wget** [comment]
Hello everyone,
I confirm this is fixing the issue we had at The Document Foundation. I think we can close now.
https://github.com/nextcloud/desktop/issues/830#issuecomment-449589408

**Comment by er-vin** [comment]
Hello,

Closing it now as advised.

Regards.
