### ISSUE TITLE
systemtray right click menu acting weird in 2.5

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/desktop#833]
Version 2.5 of the desktop client for Linux in Plasma Desktop is acting pretty odd. Every 3rd or fourth time I right-click it, the layout has changed, showing changing apps from multiple accounts in the menu. A few screenshots (note that this just happens on repeatedly right-clicking the systray!):
![screenshot_20181115_125625](https://user-images.githubusercontent.com/551757/48551437-dd1acf80-e8d5-11e8-8035-ee8fafe025a8.png)
Note top level items for 'Activity' and 'Mail'. They don't do anything when clicked. The first account has no longer a sub menu!
![screenshot_20181115_125649](https://user-images.githubusercontent.com/551757/48551459-ead05500-e8d5-11e8-83a3-857c30457e16.png)
Syncing activities show up. pause syncing or quitting the client no longer possible :dash: 
![screenshot_20181115_125704](https://user-images.githubusercontent.com/551757/48551477-f459bd00-e8d5-11e8-9609-6c9037a9bc96.png)
Customers, CRM and Deck show up as top level. First account is now a centered header!
![screenshot_20181115_125741](https://user-images.githubusercontent.com/551757/48551518-0a677d80-e8d6-11e8-8d6e-752605040014.png)
let's look in the sub menu. Ah, quit and log out are distributed options now :smile_cat: Help has been centered (the client has decided it matters a great deal now!) and open folder 'Writing' is suddenly a sub menu. I'll look what's in there later, but remember, almost every right-click gives a new menu layout so I can't be sure if I can :rocket: 
![screenshot_20181115_125757](https://user-images.githubusercontent.com/551757/48551534-13584f00-e8d6-11e8-8de1-4bec29e9b9fd.png)
Subtle changes, Deck became more important than Help :birthday: 
![screenshot_20181115_125921](https://user-images.githubusercontent.com/551757/48551597-46024780-e8d6-11e8-8fa2-7291aeb9d957.png)
Looking in the Writing submenu, it's fun in there, too. Customers, a centralized logout option/header and the settings!

So how to reproduce this? The client has been running for a while, clearly it is time related - it didn't do that immediately after startup. I had to click a few times before 'quit' would show up, but now, after restarting it, all looks good again:
![screenshot_20181115_130112](https://user-images.githubusercontent.com/551757/48551682-882b8900-e8d6-11e8-9539-ff4d01211778.png)

So yes, you have to keep the client running to get this :tada: I'm sorry for who has to debug this, given it can't be reproduced quickly: only by letting the client run for a longer time.

It will be confusing for a user, but most items ARE there in one of the menus and restarting the client helps as work-around, so I don't think it is a killing issue.

**Comment by m4lvin** [comment]
For me (KDE Plasma under Debian 9) the tray menu of 2.5 only flickers for a second and I have to be *really* quick to click anything. Interestingly, when my computer is offline, the menu stays open.

**Comment by nliautaud** [comment]
Windows 10 here, the 2.5 client right-click *Apps* entry appear after a small delay, moving the next menu entries further down. It creates "Content Jumping" issues and the last option is partially off-screen. 

|![2018-11-16 20_22_37-](https://user-images.githubusercontent.com/761761/48642946-9a90ea00-e9de-11e8-821a-6ff5980da695.png)|![2018-11-16 20_21_37-](https://user-images.githubusercontent.com/761761/48642949-9cf34400-e9de-11e8-8d8a-3a3cb438cd0e.png)|
|--|--|

**Comment by sryze** [comment]
Same problem, it's pretty annoying - when you want to click on Quit and suddenly the button goes away right before you click on it, and you end up clicking on Pause Sync. Sometimes the quit button goes off screen completely.

**Comment by sryze** [comment]
I've created a pull request that should fix this issue: https://github.com/nextcloud/desktop/pull/1477

**Comment by claell** [comment]
This should have been fixed with #1477. @jospoortvliet and others experiencing this, can you confirm?

**Comment by m4lvin** [comment]
I can confirm that I no longer have this problem under KDE with client version `2.5.1-3+deb10u1` from Debian buster.

**Comment by claell** [comment]
@m4lvin to me it looks that the issue you experienced was unrelated to this issue, correct me if I am wrong.

**Comment by er-vin** [comment]
That menu is gone in the new systray GUI.
