### ISSUE TITLE
Since update to 2.5.0: Client does not start anymore

### ISSUE THREAD

**Issue by nils-schween** [nextcloud/desktop#835]
Hello everyone,

since today's update I am unable to start the NextCloud client.

### Actual behavior
Every time I click on the NextCloud Icon, or type "nextcloud" into a terminal I receive the following error message:

[1115/154647:ERROR:icu_util.cc(162)] Invalid file descriptor to ICU data received.
[1115/154647:FATAL:content_main_runner.cc(714)] Check failed: base::i18n::InitializeICU(). 
#0 0x7f5fc69a7f1e <unknown>
#1 0x7f5fc69bec3e <unknown>
#2 0x7f5fc5bb04ad <unknown>
#3 0x7f5fc5072efd <unknown>
#4 0x7f5fc50743a5 <unknown>
#5 0x7f5fc5078cd5 QtWebEngineCore::WebEngineSettings::initDefaults()
#6 0x7f5fca3c875b <unknown>
#7 0x7f5fca3c88c8 QWebEngineProfile::QWebEngineProfile()
#8 0x55e070e124c7 OCC::WebView::WebView()
#9 0x55e070dfcf07 OCC::WebFlowCredentialsDialog::WebFlowCredentialsDialog()
#10 0x55e070dfa8d4 OCC::WebFlowCredentials::askFromUser()
#11 0x55e070de674e OCC::AccountState::slotInvalidCredentials()
#12 0x55e070de702f OCC::AccountState::slotConnectionValidatorResult()
#13 0x7f5fc166ebaf QMetaObject::activate()
#14 0x55e070e236d3 OCC::ConnectionValidator::connectionResult()
#15 0x55e070d23fdd OCC::ConnectionValidator::reportResult()
#16 0x55e070d27b2d OCC::ConnectionValidator::checkAuthentication()
#17 0x7f5fc167b308 <unknown>
#18 0x7f5fc166fbb3 QObject::event()
#19 0x7f5fc44d705c QApplicationPrivate::notify_helper()
#20 0x7f5fc44dc516 QApplication::notify()
#21 0x7f5fc164038b QCoreApplication::notifyInternal()
#22 0x7f5fc16955ed QTimerInfoList::activateTimers()
#23 0x7f5fc1695af1 <unknown>
#24 0x7f5fbee78197 g_main_context_dispatch
#25 0x7f5fbee783f0 <unknown>
#26 0x7f5fbee7849c g_main_context_iteration
#27 0x7f5fc16967cf QEventDispatcherGlib::processEvents()
#28 0x7f5fc163db4a QEventLoop::exec()
#29 0x7f5fc1645bec QCoreApplication::exec()
#30 0x55e070d05b5d main
#31 0x7f5fc076f830 __libc_start_main
#32 0x55e070d05fa9 _start

[1]  + 12572 abort (core dumped)  nextcloud

### Expected behaviour
I expect the client to open and to synchronize my data.

### Steps to reproduce
1. Update your client. 
2. Logout.
3. Start your client again.

### Client configuration
Client version:
2.5.0git

Operating system:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
With GNOME Version 3.18.5

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
Using Qt 5.5.1, built against Qt 5.5.1
Using 'OpenSSL 1.0.2g  1 Mar 2016'

Client package (From Nextcloud or distro) (Linux only):
I am using the following ppa
ppa:nextcloud-devs/client
https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client

Installation path of client:
/usr/bin/nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
Note: I replace the domain with "mydomain"

```[OCC::Application::setupLogging 	"################## Nextcloud locale:[de_DE] ui_lang:[] version:[2.5.0git] os:[Ubuntu 16.04.5 LTS]"
[OCC::Application::setupTranslations 	Using "de_DE" translation
[OCC::SocketApi::SocketApi 	server started, listening at  "/run/user/1000/Nextcloud/socket"
[OCC::FolderMan::FolderMan 	setting remote poll timer interval to 30000 msec
[OCC::AccountManager::loadAccountHelper 	Account for QUrl("https://cloud.mydomain.de") using auth type "webflow"
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::ownCloudGui::setupContextMenu 	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
[OCC::AccessManager::createRequest 	6 "GET" "https://cloud.mydomain.de/ocs/v2.php/core/navigation/apps?absolute=true&format=json" has X-Request-ID "f3f8c5ea-d420-487e-8d9c-d3a8e1cdd4ab"
[OCC::AbstractNetworkJob::start 	OCC::OcsNavigationAppsJob created for "https://cloud.mydomain.de" + "ocs/v2.php/core/navigation/apps" ""
[OCC::FolderMan::setupFolders 	Setup folders from settings file
[OCC::ConfigFile::setupDefaultExcludeFilePaths 	Adding system ignore list to csync: "/etc/Nextcloud/sync-exclude.lst"
[OCC::FolderMan::addFolderInternal 	Adding folder to Folder Map  OCC::Folder(0x5640061f0620) "1"
[OCC::FolderMan::scheduleFolder 	Schedule folder  "1"  to sync!
[OCC::FolderMan::scheduleFolder 	Folder is not ready to sync, not scheduled!
[OCC::ownCloudGui::slotSyncStateChange 	Sync state changed for folder  "https://cloud.mydomain.de/remote.php/webdav/" :  "Not yet Started"
[OCC::SyncJournalDb::checkConnect 	sqlite3 version "3.11.0"
[OCC::SyncJournalDb::checkConnect 	sqlite3 journal_mode= "wal"
[OCC::ClientProxy::setupQtProxyFromConfig 	Set proxy configuration to use system configuration
[OCC::WebFlowCredentials::fetchFromKeychain 	Fetch from keyhchain!
[OCC::AccountState::slotCredentialsFetched 	Fetched credentials for "https://cloud.mydomain.de" attempting to connect
[OCC::WebFlowCredentials::createQNAM 	Get QNAM
[OCC::ConnectionValidator::systemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://cloud.mydomain.de/status.php" has X-Request-ID "27aea649-fd61-4aa6-a0a8-a8f3c149dcb4"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://cloud.mydomain.de" + "status.php" "OCC::ConnectionValidator"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(NoError)
[OCC::WebFlowCredentials::stillValid 	"Unbekannter Fehler"
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Collegium Academicum","version":"13.0.1.1","versionstring":"13.0.1"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x564006105100)
[OCC::ConnectionValidator::slotStatusFound 	** Application: ownCloud found:  QUrl("https://cloud.mydomain.de")  with version  "13.0.1" ( "13.0.1.1" )
[OCC::ConnectionValidator::setAndCheckServerVersion 	QUrl("https://cloud.mydomain.de") has server version "13.0.1.1"
[OCC::AccountState::slotConnectionValidatorResult 	AccountState connection status change:  OCC::ConnectionValidator::Status(Undefined) -> OCC::ConnectionValidator::Status(CredentialsNotReady)
[OCC::AccountState::slotInvalidCredentials 	Invalid credentials for "https://cloud.mydomain.de" asking user
[OCC::AccountState::setState 	AccountState state change:  "Getrennt" -> "Zugangsdaten werden abgefragt"
[OCC::FolderMan::slotAccountStateChanged 	Account "myuser@cloud.mydomain.de" disconnected or paused, terminating or descheduling sync folders
[unknown 	Qt WebEngine ICU data not found at /usr/share/qt5/resources. Trying parent directory...
[unknown 	Qt WebEngine ICU data not found at /usr/share/qt5. Trying application directory...
[unknown 	Qt WebEngine ICU data not found at /usr/bin. Trying fallback directory... The application MAY NOT work.```


Thank you very much for your help,
Nils Schween

**Comment by rullzer** [comment]
@ivaradi could it be that you need to depend on more qt packages?

**Comment by ivaradi** [comment]
@rullzer yes, or at least to depend on ```libqt5webengine5``` instead of ```libqt5webenginecore5```.

@nils-schween could you try installing the ```libqt5webengine5``` package?

**Comment by nils-schween** [comment]
Thank you for your replies.

@ivaradi I installed the package libqt5webengine5. And launched nextcloud. The the error, posted above, reappeared. After this I purged the nextcloud client (sudo apt purge nextcloud-client, sudo apt autoremove) and reinstalled it. But the problem stays. I purged libqt5webengine5, libqt5webenginecore5 and the client. I reinstalled everything, rebooted and they there it was again: the above error :(

Unforunately, the issue stays unresolved. I would be very thankful for further suggestions.

Once thank you for your replies,
Nils

**Comment by nils-schween** [comment]
Thank you,

@ivaradi I created the symbolic link and this changes the situation. Now the client starts and asks me to grant access: "You are about to grant Mozilla/5.0 (Linux) mirall/2.5.0git (Nextcloud) access to your Collegium Academicum account."

Granting access causes the client to hang. 
`
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 1 bufs 4 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 1 bufs 4 relocs 0
nouveau: ch13: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch13: krec 0 pushes 0 bufs 2 relocs 0
nouveau: ch13: buf 00000000 00000003 00000004 00000004 00000000
nouveau: ch13: buf 00000001 00000006 00000004 00000000 00000004
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7fca0b33cf1e <unknown>
#1 0x7fca0b33d2f9 <unknown>
#2 0x7fca08b334b0 <unknown>
#3 0x7fca0bd6b73b <unknown>
#4 0x7fca0c2e172d <unknown>
#5 0x7fca0c2ea0f6 <unknown>
#6 0x7fca0c2eaa22 <unknown>
#7 0x7fca0c359f35 <unknown>
#8 0x7fca0c2b8cdf <unknown>
#9 0x7fca0c2b8fa2 <unknown>
#10 0x7fca0bf30113 <unknown>
#11 0x7fca0beb8420 <unknown>
#12 0x7fca0aaa5fa2 <unknown>
#13 0x7fca0bf1630d <unknown>
#14 0x7fca0bf15e2d <unknown>
#15 0x7fca0beb4c08 <unknown>
#16 0x7fca0bf1d62b <unknown>
#17 0x7fca0bf3004a <unknown>
#18 0x7fca0c2ba423 <unknown>
#19 0x7fca0c2ba4eb <unknown>
#20 0x7fca0bf30653 <unknown>
#21 0x7fca0beb82a0 <unknown>
#22 0x7fca0aaa5efb <unknown>
#23 0x7fca0bf1630d <unknown>
#24 0x7fca0bf20549 <unknown>
#25 0x7fca0bf15e2d <unknown>
#26 0x7fca0beb4c08 <unknown>
#27 0x7fca0bf1d62b <unknown>
#28 0x7fca0bf316e8 <unknown>
#29 0x7fca0a9a904b <unknown>
#30 0x7fca0a9b52a8 <unknown>
#31 0x7fca0b1bd987 <unknown>
#32 0x7fca0b0d3af2 <unknown>
#33 0x7fca0b0cb283 <unknown>
#34 0x7fca0a3093a6 <unknown>
#35 0x7fca0b1b8341 <unknown>
#36 0x7fca0b3b06a9 <unknown>
#37 0x7fca0bad5c6a <unknown>
#38 0x7fca0bad64cc <unknown>
#39 0x7fca0b3b06a9 <unknown>
#40 0x7fca0b35a1d8 <unknown>
#41 0x7fca0b35ae49 <unknown>
#42 0x7fca0b35b322 <unknown>
#43 0x7fca0b35d359 <unknown>
#44 0x7fca0b36fca2 <unknown>
#45 0x7fca0b359485 <unknown>
#46 0x7fca0b0dd347 <unknown>
#47 0x7fca0a544221 <unknown>
#48 0x7fca0a544774 <unknown>
#49 0x7fca0a543ce1 <unknown>
#50 0x7fca099de0c9 QtWebEngine::processMain()
#51 0x000000400953 <unknown>
#52 0x7fca08b1e830 __libc_start_main
#53 0x0000004009a9 <unknown>
  r8: 0000000000000000  r9: 00007fffcb6c2f20 r10: 00007fffcb6c46c0 r11: 0000000000000004
 r12: 00007fffcb6c34a8 r13: 0000000000000000 r14: 0000000000000001 r15: 0000000000000001
  di: 00007fffcb6c3350  si: 0000000000000001  bp: 00007fffcb6c34ac  bx: 0000000000000000
  dx: 00007fffcb6c3380  ax: 0000000000000000  cx: 0000000000000000  sp: 00007fffcb6c3460
  ip: 00007fca0bd6b73b efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace] `

I started it again and again. And sometimes I directly get a segmentation fault.

A screenshot of the new situation.

![bildschirmfoto von 2018-11-16 11-04-59](https://user-images.githubusercontent.com/37382794/48615191-7f978900-e990-11e8-8bfa-58b3d6f9c273.png)

Nils

**Comment by ivaradi** [comment]
@nils-schween Please, remove the symlink created under `/usr/share/qt5/resources/`, and try to update the `libqt5webengine5` package. It may not work just as I write it, but it should within a few hours. The version of the new package should end in `xenial4` and it should install the file (not a symlink) `/usr/share/qt5/resources/icudtl.dat`. Hopeully, segfaults will not appear anymore and the initial configuration wizard can be executed properly.

**Comment by nils-schween** [comment]
@ivaradi Unfortunately, I have bad news. I did as you said. I removed the symlink in /usr/share/qt5/resources/ and purged the nextcloud client. I re-installed it. And the following packages were installed: 
nextcloud-client (2.5.0-20181111.015125~xenial1)
libnextcloudsync0 (2.5.0-20181111.015125~xenial1) 
libqt5keychain0:amd64 (0.5.0-1build1~gcc5.1) 
libqt5webenginewidgets5:amd64 (5.6.4-1~xenial4) 
nextcloud-client-l10n (2.5.0-20181111.015125~xenial1) 

But the segmentation fault reappeared.
`nouveau: kernel rejected pushbuf: Datei oder Verzeichnis nicht gefunden
nouveau: ch12: krec 0 pushes 2 bufs 4 relocs 0
nouveau: ch12: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch12: buf 00000001 00000006 00000004 00000000 00000004
nouveau: ch12: buf 00000002 00000028 00000002 00000000 00000002
nouveau: ch12: buf 00000003 0000003b 00000004 00000004 00000000
nouveau: ch12: psh 00000000 000002b1d8 000002b254
nouveau: 	0x20056080
nouveau: 	0x000000d5
nouveau: 	0x00000000
nouveau: 	0x00000040
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x20046086
nouveau: 	0x00000100
nouveau: 	0x00000100
nouveau: 	0x00000000
nouveau: 	0x01720000
nouveau: 	0x2002608c
nouveau: 	0x000000cf
nouveau: 	0x00000001
nouveau: 	0x20056091
nouveau: 	0x00000400
nouveau: 	0x00000100
nouveau: 	0x00000100
nouveau: 	0x00000000
nouveau: 	0x01920000
nouveau: 	0x80006223
nouveau: 	0x2004622c
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000100
nouveau: 	0x00000100
nouveau: 	0x20046230
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: 	0x00000000
nouveau: 	0x00000001
nouveau: ch12: psh 00000000 000002b254 000002b27c
nouveau: 	0x20046234
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x00000000
nouveau: 	0x200406c0
nouveau: 	0x00000000
nouveau: 	0x00215000
nouveau: 	0x0000008c
nouveau: 	0x1000f010
[1]    2373 segmentation fault (core dumped)  nextcloud`

Hmm... Anyway thank you for your help. If you have any other ideas, that would great.
Nils

**Comment by ivaradi** [comment]
@nils-schween well, actually, this is good news :), since this is a completely different failure, presumably meaning that the program runs beyond the original one.

It seeems to be a known bug in QtWebEngine: https://bugreports.qt.io/browse/QTBUG-41242. This bug report includes a patch as well, which I have ported to the version built for Xenial. I have uploaded the source package to Launchpad and it is being built as I write it. It should be ready in a few hours. Please, upgrade to it (the version should ends with `xenial6`), and try the client again.

But, just to make sure. What is the version of the `libqt5webengine-data` package? Is there a file `/usr/share/qt5/resources/icudtl.dat`?

**Comment by nils-schween** [comment]
@ivaradi That's great :) I will directly reinstall the nextcloud-client. But before doing this, I will answer your questions. I checked if there is the file /usr/share/qt5/resources/icudtl.dat and - yes - it's there. Furthermore you asked for the version of the package libqt5webengine-data, here is the output of 
dpkg -s libqt5webengine-data:

> Package: libqt5webengine-data
> Status: install ok installed
> Priority: optional
> Section: libs
> Installed-Size: 33085
> Maintainer: Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
> Architecture: all
> Multi-Arch: foreign
> Source: qtwebengine-opensource-src
> Version: 5.6.4-1~xenial4
> Description: Web content engine library for Qt - Data
>  QtWebEngine provides a Web browser engine that makes it easy to embed content
>  from the World Wide Web into your Qt application.
>  .
>  This package contains the arch independent parts of QtWebEngine libraries.
> Homepage: https://doc.qt.io/qt-5/qtwebengine-index.html

And right now I will re-install the client. I will let you know if it works.
Thanks a lot!!
Nils

**Comment by ivaradi** [comment]
@nils-schween Thanks for the update and for testing the client on Xenial. I am now closing this issue.

**Comment by gw0** [comment]
On Debian 9 in KDE with Xenial package I was still experiencing issues. A quick workaround is to start with forced software OpenGL (from https://bugreports.qt.io/browse/QTBUG-41242):

```
$ QT_XCB_FORCE_SOFTWARE_OPENGL=1 nextcloud
```
