### ISSUE TITLE
Show proper username in systray context menu for AD users

### ISSUE THREAD

**Issue by tribut** [nextcloud/desktop#836]
### Expected behaviour
The context menu on the appindicator/systray should use the proper username.

### Actual behaviour
In the context menu, the GUID is shown instead of the username.

![screenshot from 2018-11-15 17-13-53](https://user-images.githubusercontent.com/719105/48565996-09484780-e8fa-11e8-99fd-4690eac457c5.png)

The actual username is shown when hovering over the user name in the main window. I would have expected that to be used.

![screenshot](https://user-images.githubusercontent.com/719105/48566356-e5d1cc80-e8fa-11e8-877b-3390d451df7e.png)

### Steps to reproduce
1. Link Nextcloud to AD
2. Start Desktop client and login
3. Observe Context Menu

### Client configuration
Client version: 2.5.0git

Operating system: Ubuntu cosmic

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.11.1

Client package (From Nextcloud or distro) (Linux only): Nextcloud

Installation path of client: n/a

**Comment by FredericLespez** [comment]
I can confirm this bug with latest client (Nextcloud Official AppImage 2.5.1final build 20181204) under Linux (Debian Buster).
The bug is not restricted to AD users but LDAP users in general. 

The context menu should use the user's Display Name.
