### ISSUE TITLE
Icons in macOS Finder Favorite pane are wrong

### ISSUE THREAD

**Issue by rgigante** [nextcloud/desktop#837]
### Expected behaviour
Icons should be represented correctly rather than being plain dark-gray squares

### Actual behaviour
The icons in the macOS Finder Favorite pane are plain dark-gray squares 

### Steps to reproduce
1. install and add your nextcloud home folder to the favorite pane on the left

### Client configuration
Client version: 2.5.0

Operating system: High Sierra 10.13.6

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
Built from Git revision 371001 on Nov 12 2018, 01:03:46 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: /Applications/nextcloud.app

**Comment by FlexW** [comment]
Does this issue still apply?
