### ISSUE TITLE
Search /nextcloud at initial client setup

### ISSUE THREAD

**Issue by MrManor** [nextcloud/desktop#84]
I would think that this a minor bug, but confuses novice users and is harder to type on a mobile

### Steps to reproduce
1. Server is available at [server.domain]/nextcloud and redirects requests http to https, and  / to /nextcloud
2. Install desktop client
3. When asked for server, enter [server.domain]

### Expected behaviour
Client should search something like 

https://[server.domain]/
http://[server.domain]/
https://[server.domain]/nextcloud
http://[server.domain]/nextcloud
https://[server.domain]/owncloud
http://[server.domain]/owncloud

I think that in all cases redirects should be followed and search stop at the first location available   

### Actual behaviour
Message that no Nexcloud was found at [server.domain]/owncloud 

I think I see the same behavior on both desktop and android clients.

**Comment by DominiqueFuchs** [comment]
Client should not care about protocol redirections in terms of automated guessing. However, with the latest stable client redirections (including protocol from http->https) work fine and are transparently applied when the user enters the adress (connection is established and saved with https address).

Regarding the URL path: one could argue that automated URL guessing can lead the user in totally wrong directions when not double-checking the result. Assuming there may be different NC instances on the server with different URLs (subdomains and / or redirects) it may be the best to rely on the fact that the user should indeed know which exact URL to enter here.

If not voted against it, I'll close this issue soon.
