### ISSUE TITLE
Client 2.5.0 installs on 32 bit Windows, but only 64 bit binaries are installed

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/desktop#840]
### Expected behaviour
Nextcloud Client 2.5 should install on 32 bit Windows installations and install the right binaries.

### Actual behaviour
Nextcloud Client 2.5 installs, but only 64 bit binaries are installed on Windows, resulting in a non-woring installation.

### Steps to reproduce
1. Install the 2.5 client
2. Try to start it

### Client configuration
Client version: 2.5

Operating system: Windows 7 32-bit

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: C:\Programs/Nextcloud

**Comment by coyotenq** [comment]
Confirmed in here. Same issue too (Windows 7 32 bits Spanish)
The installer works fine, but drops a 64 bit executable, so, error occurs.

**Comment by therfman** [comment]
Confirmed on Windows 10 32-bit English,  Is the previous version installer available to restore functionality until this bug is fixed?  Not being able to access NextCloud on this machine after a reinstall is problematic.

**Comment by obitbef** [comment]
https://download.nextcloud.com/desktop/releases/Windows/

**Comment by avrosen** [comment]
Same issue here. After installing the latest official client on Win10 32bit application can't be started with the following windows error message "This App Can’t Run On Your PC".
Happy to provide further insight if this can help to fix the issue.

**Comment by JK74** [comment]
same here for W8.1pro N Dutch install. even with the 2.5.1 or the daily build from dec.11

**Comment by tigernero79** [comment]
Are you new to install 2.5.1 on 32-bit windows systems?

to date I have to use version 2.3.3.1 for windows 10 to 32 bit

**Comment by donvipre** [comment]
2.5.1 on 32-bit Windows systems still does not work. Tested it today. "This software is not suitable for your computer"

**Comment by EmadFathy** [comment]
I confirm this issue in 2.5.0 and 2.5.1, Please fix it, We need the 32bit version.

**Comment by KarelWintersky** [comment]
Same issue.

**Comment by jasgot** [comment]
Just tried daily - https://download.nextcloud.com/desktop/daily/Windows/Nextcloud-2.5.1.61659-daily-20181211.exe

It no worky either.

**Comment by jasgot** [comment]
Went back to 2.3.3.1 (found it in my folders) to restore functionality.

**Comment by anduz** [comment]
I'm having the same issue.
Will there be a fix or is 32bit OS unsupported in current releases?

**Comment by meisterleise** [comment]
I would like to know too if this is gonna to be fixed or if 32 bit will be unsupported from now on.
Thanks a lot!

**Comment by krombel** [comment]
I and most other users which see this issue recognize the lack of x32 bit support in the latest release.

I would suggest to simply **upvote this issue** (react on issue description with :+1:) as I did. Repeated messages, that you are affected might help as rememberer, but upvotes on the first message help to triage the most important issues (and therefore when planning the next development steps).

So upvote. And then reconsider writing a comment. In most cases upvoting is enough.
Thanks

**Comment by SunDancerGE** [comment]
Same here.

**Comment by KarelWintersky** [comment]
triage don't needed. Needed FIX.

**Comment by slydder101** [comment]
Same issue for me as well!

**Comment by CAXAline** [comment]
I confirm. Same problem. I can not run on Windows 7 32-bit

**Comment by guruz** [comment]
Try the ownCloud client instead, it is compatible: https://github.com/owncloud/client/releases/tag/v2.5.2-rc2 (and still on 32bit AFAIK)

**Comment by jospoortvliet** [comment]
an ownCloud employee posted some advertising for their client. While it might work, I want to point out that using the ownCloud client is untested (and thus risky) and it lacks functionality. We will look into building a 32 bit version of our client!

**Comment by meisterleise** [comment]
> an ownCloud employee posted some advertising for their client. While it might work, I want to point out that using the ownCloud client is untested (and thus risky) and it lacks functionality. We will look into building a 32 bit version of our client!

Well, I'm not an owncloud employee. I just switched from owncloud to nextcloud and now I must conclude that there is a very big issue with the client app and have to tell my clients that they can't use the nextcloud client app.

I use the owncloud client app for the nextcloud in a complex structur of 3 Clouds and it works with no harm. In fact is has less interruptions in transfer then the nextcloud client.

Will my post now also be censored?

**Comment by donvipre** [comment]
@meisterleise: you can simply use an older version for now. And please click on upvote in the first post :)
thank you very much.

**Comment by meisterleise** [comment]
> @meisterleise: you can simply use an older version for now. And please click on upvote in the first post :)
> thank you very much.
I've done that already.
Older Version: I don't need the older version. I'm using a mac. But all the users of my cloud download the new version and wonder why it don't work. The best would be, Nextcloud would no longer offer the current version for download! Or they would indicate in bold letters that the version is for 64 bit only (although -wouldn't help- most users don't know about that).

**Comment by guruz** [comment]
@jospoortvliet I didn't post an ADVERTISTING for the ownCloud client, I tried to help the people on this public GitHub. That's what Open Source is about, people helping each other.

If you don't want people to use the working ownCloud client with the Nextcloud server, then maybe you should stop breaking your user's desktop clients. 

I hope this post doesn't get censored like the previous one.

**Comment by camilasan** [comment]
> I didn't post an ADVERTISTING for the ownCloud client, I tried to help the people on this public GitHub. That's what Open Source is about, people helping each other.

Yes, right :unicorn: 
I am glad you have time for this. Good for you!

**Comment by jospoortvliet** [comment]
@guruz that wasn't "helping", telling people "try the ownCloud client" on every bug in our repo isn't helpful in any way. So please just stick to the oC repo and don't comment here at all anymore. I have blocked you now and hidden all comments as I haven't seen a single constructive comment from you in our repo in, well, EVER.

**Comment by meisterleise** [comment]
@jospoortvliet 
Okay, I think you're right. He was a troll.
Nevertheless – perhaps you could stop making the actual version available for download, because people download a version that don't work and they dont know why.

**Comment by EmadFathy** [comment]
Please fix the issue.

**Comment by readonly24** [comment]
10 weeks and still no solution? What's so hard?

**Comment by fabzgy** [comment]
I just had the same problem with one of my users. Would be really good to have a 32 Bit installer working. On the Website I can t even find a link for older versions of the client. Has anyone an idea which is the newest NC-Client still working with a 32-Bit Windows System?

**Comment by meisterleise** [comment]
> I just had the same problem with one of my users. Would be really good to have a 32 Bit installer working. On the Website I can t even find a link for older versions of the client. Has anyone an idea which is the newest NC-Client still working with a 32-Bit Windows System?

2.3.3.1
https://download.nextcloud.com/desktop/releases/Windows/

**Comment by agarek** [comment]
Is there any switch for installation proccess to force instal 32bit binaries??? 3 months since issue reported and neither latest daily build is not able install correct binaries in 32bit windows??? Shame!

**Comment by AdrianBan** [comment]
Confirmed today the issue.
ASUS T100TAM with Windows 8 32 bits. Is not working.

**Comment by kalicouk** [comment]
18-03-2019 and I can confirm that the install from Nextcloud's website still installs the 64 bit version onto a 32 bit Windows PC.

Grrrr!  Anyone got a solution?  Why is it taking Nextcloud so long to just change the downloads on the website?

**Comment by KarelWintersky** [comment]
> Anyone got a solution? 

only install 2.5.2 version

**Comment by frankivax** [comment]
> > Anyone got a solution?
> 
> only install 2.5.2 version
> 
> > Why is it taking Nextcloud so long
> 
> 'cause it ugly open-source

En win 7 de 32b la version 2.5.2 se instala pero no inicia
>Solucion:
>Instalar la version:  Nextcloud-2.3.3.1

**Comment by btreb** [comment]
Even with 2.5.2 no 32bit binaries are installed on Windows 10 x86 32bit

**Comment by meisterleise** [comment]
> Even with 2.5.2 no 32bit binaries are installed on Windows 10 x86 32bit

It's a tragedy. I think they never planed to make the client 32-bit compatible. They even didn't tell us.

**Comment by meisterleise** [comment]
@ChristophWurst 
Why did you close this thread? I didn't notice that the bug would have been fixed.

**Comment by croulibri** [comment]
I am also facing this issue.

Does that means the 32-bits version of Nextcloud desktop will stop at 2.4?

**Comment by EmadFathy** [comment]
Five months and no response.. is Nextcloud dying ?

**Comment by rndsoft** [comment]
Hello, I have the same issue : tried to install NextCloud client on a Windows 10, 32 bits version and it fails  with "This App Can’t Run On Your PC".
I must clarify something: it's a 32-bit Windows on an x64 architecture. I can't upgrade to the 64-bit version because the machine is not powerful enough (small Netbook with 2GB of memory)

I think we can understand that Windows 32 bit support is abandoned, but perhaps would it be better to announce it clearly on the download page, as for the MacOs client ?

Nevertheless : thanks for all the good work.

**Comment by bioruffo** [comment]
Can also confirm this issue.
For now I followed @meisterleise 's advice (thank you) and installed the 2.3.3.1 version from 
https://download.nextcloud.com/desktop/releases/Windows/

**Comment by rndsoft** [comment]
> Can also confirm this issue.
> For now I followed @meisterleise 's advice (thank you) and installed the 2.3.3.1 version from
> https://download.nextcloud.com/desktop/releases/Windows/

Thanks you for the advice, it seems the only solution for know.

**Comment by genspk06** [comment]
Can please somebody tell if the 2.3.3.1+ versions contain critical security fixes? half a year past and still nothing, so I'm worried

**Comment by TeddyKopernikus** [comment]
still an issue in current daily build

**Comment by Happyfeet01** [comment]
Still the same issue ob Windows 10 32bit

**Comment by polytan02** [comment]
Same issue here, please can we get a fix ? This is really frustrating :(

**Comment by Happyfeet01** [comment]
Feedback on Twitter https://twitter.com/nextclouders/status/1124603895819296768?s=21

**Comment by misch7** [comment]
Hey all,

I built the Desktop Client for 32-bit Windows a few hours ago:
https://schuster.ms/nextcloud-win32/

Tested on Windows 10 (1709), more testing on older systems would be appreciated! ;-)

Thanks and have fun!

**Comment by Happyfeet01** [comment]
Oh thanks. That is fast :-)

**Comment by e-alfred** [comment]
@misch7 Awesome work! Can you publish some build instructions? This would be very helpful.

**Comment by starox** [comment]
@misch7 Thank you very much for your work.
I installed it on windows 10 build 1803 flawlessly (minus warning for non signed app from windows).
I haven't test it extensively for the moment, it works as usual.

Thank you again

**Comment by misch7** [comment]
Thanks for your feedback! :-)

@e-alfred Yepp, that's really sad and I'm still confused why there is no vital response to that.

I'll post a reference to my build instructions as soon as I have them ready. ;-)

@starox Thx! (Even though I considered code signing to make my release more trustworthy the expense was currently unreasonable for that yet, since I have no certificate at hand.)

By the way I stumbled across the SSL issue just a minute ago:
#622 

Another reason not use the old 2.3 client was the outdated OpenSSL version in it. I compiled the 32-bit version with the more secure OpenSSL v1.0.2r (and libcrypto 1.1.1b).

**Comment by KarelWintersky** [comment]
Anybody knows: 

is client version 2.5.2 (32bit) compatible with Nextcloud Server version 14.0.10 ?

**Comment by misch7** [comment]
@KarelWintersky I used Nextcloud Server 15.0.5 for testing my 32-bit build.

General rule of thumb: If it works with the 2.5.2 stable 64-bit build, it should also work with the 32-bit build.
If you try to connect the client to an unsupported server it should show a message warning you about the issue. This happened to me for example when I migrated from ownCloud to Nextcloud, still using the Desktop Sync Clients of ownCloud with the new Nextcloud Server. I got the message but everything was working. It depends on the specific (in)compatibilties of the corresponding client vs. server versions.

So I would suggest to give it a try, perhaps select some test folders only for sync and get back to us with the result! *fingers crossed* :-)

**Comment by avrosen** [comment]
Just installed on Win10 32bit ver 1809. Saw a whole bunch of suspected virus warnings by my scanner but beside that it works fine so far with Nextcloud 15.0.7.

Big thx @misch7 for your extra work.

**Comment by e-alfred** [comment]
@misch7 @camilasan Maybe you can integrate your build instructions/set up into the official client so the official client can support both 32- and 64-bit? The installer of the official client still has the problem of not checking if it is executed on a 32-bit system and simply installing the wrong binaries without any check.

**Comment by camilasan** [comment]
> @camilasan Is this still the place?:
> https://github.com/nextcloud/client-building

Yes.

> If so, I could try to migrate my 32-bit stuff into it and adapt the NSIS script to check for the right installation environment.

That would be amazing :tada: 

> Sadly I just found this repo after nearly having a working client. Could have saved me some time.^^
> For my built I heavily modified the NSIS script from the client repo because it was outdated. So half of the work is already done.
> 
> There are more questions: The instructions there (and the current x64 release of the client) include Debug DLL's like Qt5CoreD.dll which further requires the debug versions of the VC runtime's DLL's.
> 
> Are they intended to end up in the release package?

They should be removed. 

> 
> For testing the 32-bit client I left them intentionally out of the Nextcloud folder and everything went fine. So I decided to not include them in my release and I further built zlib myself and picked all DLL's by hand to eleminate the need for the VC 12.x runtime libs.

Ok.
> 
> Till I have feedback and know more I'm continuing with the work on my build instructions so everybody can reproduce a 32-bit build.

Thanks so much :heart:

**Comment by misch7** [comment]
> 
> > If so, I could try to migrate my 32-bit stuff into it and adapt the NSIS script to check for the right installation environment.
> 
> That would be amazing 🎉
> 

Great, count me in! :rocket:

Thanks :) :heart:

**Comment by ychaouche** [comment]
Would be nice to have the build instructions to reproduce here. Thanks and nice work you !

**Comment by misch7** [comment]
As promised after a vast amount of work and perhaps a little over-escalation 😹 :

https://github.com/misch7/nextcloud-client-building

A new build system and instructions. Happy building! :-)

**Comment by misch7** [comment]
If you like to try out ready-built client installers with 32- and 64-bit support, here‘s where my daily test builds get uploaded to:
https://nextcloud-builds.schuster.ms/desktop/daily/Windows/
2.5.3 builds on Win 10 VM, stable-2.5.2 on Win 7 VM, signed with a test key. 😉
Have fun! 😊

@camilasan : Get in touch with me if I can be of any help to support you integrating the new build scripts into your bulid environment. Tried to modify everything in way to help you save time building, so you can focus on client programming. 😼

**Comment by polytan02** [comment]
So is the issue now sorted with the official client ?
Can we actually install the official build on win32 computers please ?

**Comment by polytan02** [comment]
@misch7 Thanks for your great support, but how do we know which one of your builds is a stable release please ?

**Comment by polytan02** [comment]
@e-alfred Hi, please could you change title of this issue by "Client 2.5.x doesn't install on x86 platforms as client building tools are broken" ?

Maybe this thread doesn't get attention because it says 2.5.0 and not 2.5.x (currently they are on 2.5.3)

**Comment by pagaille** [comment]
> I built the Desktop Client for 32-bit Windows a few hours ago:
> https://schuster.ms/nextcloud-win32/

Hi @misch7, are you aware that your nextcloud client triggers Avast's antivirus ? 

Nextcloud is doing a bad job here by making users rely on outdated or unsecure (nothing personnal @misch7) source of software.

**Comment by misch7** [comment]
@polytan02 The initial 32-bit-only build on my website (https://schuster.ms/nextcloud-win32/) is the stable one and the only build using a custom update URL so the client won't get replaced by a 64-bit-only version from the official sources. The second link contains combined installer builds with unmodified sources and update URL's and also signed with a testing key not valid on other systems. Anyways daily builds should never be considered stable.

@pagaille I'm aware that certain scanners will complain since my build is similar to the official one and may trigger some fake alerts. It neither outdated (more recent OpenSSL & Qt versions!) nor insecure (well that's up to your trust). It's just not officially signed and ideally you would an official version, published and signed by Nextcloud.
Good news is, they are already integrating my build scripts so there will be an official 64- and 32-bit combined release in the (hopefully) near future.
Of course I already considered trust and signing as an issue prior publishing my first build. But I decided to share it so everybody could benefit from my work. The rest is up to you. ;-)

**Comment by krab** [comment]
Nextcloud-2.5.2-setup.exe from official website its 32 bit executable but contains 64 bit nextcloud binaries, 64 bit Qt and x64 visual studio redistribute package. So its clearly made for 64bit only windows.

Installer shouldn't run on 32 bit systems either, they just have to add Error box and close installer. Or better build for 32/64 bit separately and put 2 installers on website.

**Comment by Happyfeet01** [comment]
Use the installer from @misch7

**Comment by camilasan** [comment]
Hi All, the daily builds and the last release (2.5.3) are now using @misch7 scripts, which means the installer works on 64 bit and 32 bits. So I am closing this ticket...
