### ISSUE TITLE
Client 2.5.0. crashes on conflicted files

### ISSUE THREAD

**Issue by cyablo** [nextcloud/desktop#842]
I recently upgraded from Nextcloud Client 2.3.3 to 2.5.0. The new Version started to complain about unsolved conflicts on one of my synced Folders and crashes shortly after, every time.

The folder that causes the Problem holds data that is constantly changing (surveillance cams). I had no problems with Client 2.3.3 syncing it. As soon as I disable the Sync for this Folder, 2,5,0 runs just fine.

Btw.: Current daily build has the same problem.

### Client:
Client version: 2.5.0v2.5.0 (build 20181112)
Operating system: Windows Server 2016
OS language: German
Installation path of client: C:\Program Files (x86)\Nextcloud

### Server:
Operating system: Debian 8 fully patched
Web server: Apache 2.4.10
Database: MySQL 5.5.62
PHP version: 5.6.38
Nextcloud version: 13.0.7

### Logs

Client log: https://gist.github.com/cyablo/b14bd417cb3c522be8fdda8449e030ef

**Comment by berkutta** [comment]
Mine also seems to have a very similiar issue. My client also crashes after updating 2.3.3->2.5 while syncing a directory with a ton of little files in it.

**Comment by cyablo** [comment]
If was thinking about deleting the share and letting it upload all the files fresh from the start to prevent conflicts and maybe solve the crash, but we are talking about > 300 GB of data. This would take ages.

**Comment by cyablo** [comment]
FYI: Deleting the Share from the Client and Folder on the Server and reconfigure them  to let the Client resync from scratch does not help either. Still crashing.

**Comment by cyablo** [comment]
Still crashing with latest nightly:

https://gist.github.com/cyablo/224639b50a9a7af4a0047110ec7952cf

**Comment by cyablo** [comment]
2.5.1 is still crashing. This is really annoying because I can't sync my surveillance Videos!

**Comment by cyablo** [comment]
Also crashing with latest daily:

`[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Lokale Datei hat sich während der Synchronisation geändert. Die Synchronisation wird wiederaufgenommen."
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file c:\nextcloud\desktop\src\libsync\owncloudpropagator.cpp, line 834
[OCC::PropagateItemJob::scheduleSelfOrChild 	Starting INSTRUCTION_IGNORE propagation of "db/index (conflicted copy 2018-11-15 232545).dat" by OCC::PropagateIgnoreJob(0x20c2f55c950)
[OCC::PropagateItemJob::done 	Could not complete propagation of "db/index (conflicted copy 2018-11-15 232545).dat" by OCC::PropagateIgnoreJob(0x20c2f55c950) with status 5 and error: "Konflikt: Serverversion heruntergeladen, lokale Kopie umbenannt und nicht hochgeladen."
[OCC::ActivityWidget::slotItemCompleted 	Item  "db/index (conflicted copy 2018-11-15 232545).dat"  retrieved resulted in  "Konflikt: Serverversion heruntergeladen, lokale Kopie umbenannt und nicht hochgeladen."
[OCC::ActivityWidget::slotItemCompleted 	Item  "db/index (conflicted copy 2018-11-15 232545).dat"  retrieved resulted in error  "Konflikt: Serverversion heruntergeladen, lokale Kopie umbenannt und nicht hochgeladen."
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Konflikt: Serverversion heruntergeladen, lokale Kopie umbenannt und nicht hochgeladen."
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file c:\nextcloud\desktop\src\libsync\owncloudpropagator.cpp, line 834`

**Comment by magneticflux-** [comment]
I'm having the same issue syncing files that are being modified. This is the log, just before the application segfaults:

```
[OCC::PropagateItemJob::done    Could not complete propagation of "%MY_FILE%.mkv" by OCC::PropagateUploadFileNG(0x55872905a4c0) with status 3 and error: "Local file changed during syncing. It will be resumed."
[OCC::ActivityWidget::slotItemCompleted         Item  "%MY_FILE%.mkv"  retrieved resulted in  "Local file changed during syncing. It will be resumed."                                
[OCC::ActivityWidget::slotItemCompleted         Item  "%MY_FILE%.mkv"  retrieved resulted in error  "Local file changed during syncing. It will be resumed."                          
[OCC::ActivityListModel::addErrorToActivityList         Error successfully added to the notification list:  "Local file changed during syncing. It will be resumed."                                                                
[OCC::PropagatorCompositeJob::slotSubJobFinished        ASSERT: "i >= 0" in file /build/nextcloud-client-EoHczf/nextcloud-client-2.5.2/src/libsync/owncloudpropagator.cpp, line 834
```

I'm using the latest beta 2.5.2 to see if that would fix it, but it still happens on the latest stable.

**Comment by cyablo** [comment]
2.5.3 daily still crashing on changing files...

**Comment by DominiqueFuchs** [comment]
The log files indicate that the issue discussed here was resolved by #1427 

In case you're still struggling with this issue feel free to try the daily build (fix is merged in master, not yet in a stable release - following soon)

**Comment by cyablo** [comment]
Whit latest WIndows-Client nightlies, the bug seems to be back (or a similar one). CLient crashes when trying to sync a directory with changing files.

**Comment by vansante** [comment]
Same here, some of my customers experience a crash on 2.6.x clients with the following log lines last:

```
[OCC::PropagateItemJob::done 	Could not complete propagation of "Familie foto's/2020/DSC_2286.NEF" by OCC::PropagateUploadFileV1(0x2ce418b7520) with status 1 and error: "Operation canceled"
[OCC::ActivityWidget::addError 	Item  "Z:\\Pictures"  retrieved resulted in  "Operation canceled"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in  "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in error  "Operation canceled"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Operation canceled"
[OCC::PropagateItemJob::done 	Could not complete propagation of "Familie foto's/2020/DSC_2286.NEF" by OCC::PropagateUploadFileV1(0x2ce418b7520) with status 3 and error: "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in  "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in error  "Operation canceled"
[OCC::ActivityListModel::addErrorToActivityList 	Error successfully added to the notification list:  "Operation canceled"
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file C:\stack\windows\desktop\src\libsync\owncloudpropagator.cpp, line 835
[OCC::PropagateItemJob::done 	Could not complete propagation of "Familie foto's/2020/DSC_2286.NEF" by OCC::PropagateUploadFileV1(0x2ce418b7520) with status 6 and error: "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in  "Operation canceled"
[OCC::ActivityWidget::slotItemCompleted 	Item  "Familie foto's/2020/DSC_2286.NEF"  retrieved resulted in error  "Operation canceled"
[OCC::ActivityListModel::addIgnoredFileToList 	First checking for duplicates then add file to the notification list of ignored files:  "Familie foto's/2020/DSC_2286.NEF"
[OCC::PropagatorCompositeJob::slotSubJobFinished 	ASSERT: "i >= 0" in file C:\stack\windows\desktop\src\libsync\owncloudpropagator.cpp, line 835
```

**Comment by vansante** [comment]
FYI: I was able to prevent this error by setting the server's `chunkingParallelUploadDisabled` capability to `true`.

This suggests to me that there is something wrong when multiple threads are uploading the same file.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?

**Comment by cyablo** [comment]
tbh, no. I moved lately and my homelab is not up and running yet.

**Comment by magneticflux-** [comment]
I can't test because I moved to an external mount instead of syncing local files.

**Comment by mgallien** [comment]
Thanks, let's keep it open until the bot closes it and please if you ever still encounter issues with the desktop client open a new issue
