### ISSUE TITLE
Window position not correctly restored

### ISSUE THREAD

**Issue by stephanedupont** [nextcloud/desktop#844]
### Expected behaviour
On Windows, clicking on the close icon and minimizing the client to the system tray, then clicking on the icon on the system tray should bring the window back to its position before closing/minimizing it

### Actual behaviour
The position is changed. I'm used to having the client on the bottom right of my screen, with a little space between the right of the client and the right border of the screen, and a little space between the bottom of the client and the system tray. When clicking on the icon in the system to bring back the client, the client is more to the right and especially more to the bottom than before closing it. A small section of the client is now under the system tray.

### Client configuration
Client version: 2.5.0v2.5.0 (build 20181112)
Operating system: Windows 10
OS language: French

**Comment by mgallien** [comment]
Can you test with the latest version ?
If it is solved, can you close the ticket ?
