### ISSUE TITLE
Windows Desktop Client not able to connect to local server due to SSL

### ISSUE THREAD

**Issue by ghkuf** [nextcloud/desktop#849]
### Expected behaviour
Desktop client should be able to connect to local (intranet) Nextcloud server though HTTPS even if the certificate is not matching the local address.

### Actual behaviour
If I try to login from the desktop client the first time to my Nextcloud server on https://192.168.178.180 I first get a popup warning about the not matching certificate - which is okay. If I now accept this certificate as trusted it seems this is ignored as I get a 'Site not reachable - https://192.168.178.180/index.php/login/flow' with ERR_CERT_COMMON_NAME_INVALID.

The logs show that the certificate errors are somehow ignored and the reauth is started but this is not working due to the untrusted SSL connection and the browser window poping up shows the 'Site not reachable' error.

### Client configuration
Client version: 2.5.0

Operating system:
Win10 64

### Server configuration
Operating system: Ubuntu
Web server: apache
Nextcloud version: 14.0.3

###

I currently use the owncloud desktop client against my Nextcloud server and now wanted to migrate to the nextcIoud desktop client and this fails. So the owncloud desktop client seems to behave different in this case.

**Comment by spalinger** [comment]
I got exactly the same problem! I hope it will be fixed asap.

**Comment by krfgbhoiaeuzr** [comment]
same problem, searched for hours before finding this issue.. so nothing can be done atm?

**Comment by spalinger** [comment]
Apparently you have two options:
- You keep having the last release installed (which is not on github anymore).
- You buy a new router with can handle hairpinning.

**Comment by leighss** [comment]
Same problem as well,

**Client configuration**
Client version: 2.5.1-2
Operating system:
Manjaro

**Server configuration**
Nextclud Box 
Raspberry Pi 
Snappy

**Comment by cdoenges** [comment]
I see the same issue on macOS with client 2.5.1final (build 20181204).

**Comment by KingCartman** [comment]
Same issue

**Comment by user23498723452** [comment]
> Same issue on Manjaro Linux

I made a comment at https://github.com/nextcloud/desktop/issues/997#issuecomment-453787921 about this, since I have no idea if the Windows code is the same as the linux code.  My comments are peppered all over the related issues.

Please do what you can if your issue is the same.

**Comment by MikeZuluUSA** [comment]
Same Issue with the local access to my cloud using a LetsEncrypt certificate.
Win10x64
Desktop Client Version 2.5.1final (build 20181204)

It worked before perfectly!

**Comment by julpec** [comment]
Same for me
NC server 19
Debian buster
Server behind a proxy
All the other access are good (no problem with web interface)
