### ISSUE TITLE
File synchronisation is very unreliable

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud/desktop#850]
### Expected behaviour
All files should get uploaded

### Actual behaviour
I copied a folder which is 675,3 MB big to my Nextcloud directory. It took some seconds and Nexcloud Desktop said everything is up to date and it is done.

On the server the folder is not 675,3 MB, but only 2 MB in size. A lot files are missing.

This is not the first time such a thing is happening to me. Yesterday it forgot to download some files and said it is done, which was wrong.
So for me the client is pretty unreliable. It forgets to down-/upload some files.

I'm using the AppImage version 2.5.0.
Also tried the 'nextcloud-client' package from AUR, which is currently version 2.5.0. Same problem.

I also tried the owncloud client version 2.5.1 (from Archlinux repos). The funny thing is: with the owncloud client it works. It uploads / downloads everything. Only nextcloud client has this problem.

### Steps to reproduce
1. Install Nextcloud client (AppImage or AUR package) on Manjaro Linux KDE
2. Install Nextcloud Server (in my case on raspberry pi, the snap version)
3. Copy a big folder into the directory which should get synched to the server.

### Client configuration
Client version: 2.5.0

Operating system: Manjaro Linux KDE

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.11.0

Client package (From Nextcloud or distro) (Linux only): AppImage or 'nextcloud-client' package from AUR

Installation path of client: (AppImage)

### Server configuration

Operating system: Ubuntu Server 18.04

Web server: (from snap)

Database: (from snap)

PHP version: (from snap)

Nextcloud version: (from snap) (13.0.7)

Storage backend (external storage): on micro sd card of pi

### Logs

1. Client logfile: 
[log.txt](https://github.com/nextcloud/desktop/files/2591885/log.txt)

Edit: I replaced my server with "myserver.com" in the logfile.
To better find it, the folder I tried to sync is named "LMMS-Manjaro".

**Comment by cowai** [comment]
@Bleuzen Any weird folder names or something like that? Have you tried other data sets with similiar amount of files/data?

**Comment by Bleuzen** [comment]
Possible, don't know anymore. This bug is some months old.
From that time to now, I:
 - Updated my Nextcloud Server (using version 15 now)
 - Updated the Client (using the Archlinux 2.5.1 package now)

I didn't get such 'silent not all files are synced' error anymore, but a new one, I often face this error now when having many small new files to up/download:
https://github.com/nextcloud/desktop/issues/1025
