### ISSUE TITLE
New version Client: 'There are unresolved conflicts' and yellow '!' icon

### ISSUE THREAD

**Issue by leighss** [nextcloud/desktop#851]
Xubuntu 18.04
Client 2.5.0git
[RPi based Box with Snappy Nextcloud]

After the new client installed (2.5.0git) all still works but instead of the green ticks I now have yellow ‘!’ marks with the message, ‘There are unresolved conflicts. Click for details.’

However, these ‘unresolved conflicts’ are all just ‘File/Folder is on the ignore list’ or ‘File/Folder is ignored because it’s hidden’, which before update of client were noted but green ticks were returned

I have, and always have had, the ‘Sync hidden files’ box unticked
I tried ticking this but it still showed the same (with only ‘File/Folder is on the ignore list’ errors as expected)

Is this behaviour now normal?

Surely, if files are supposed to be ignored then a warning isn’t necessary?

Not the end of the world but I do miss the satisfaction factor of seeing nice plump green ticks

From [forum](https://help.nextcloud.com/t/new-version-client-there-are-unresolved-conflicts/41354) someone else also has this problem on Kubuntu 18.04

**Comment by brianbgness** [comment]
@leighss Some of my Windows users had the same thing occur when upgrading from v2.3.3 to v2.5.  The fix for us was to go into 'Edit Ignored Files' and then press 'Restore Defaults'.

**Comment by augustseptember** [comment]
related to https://github.com/nextcloud/desktop/issues/566

**Comment by leighss** [comment]
That means I have duplicated the bug so I should close this one I guess?

**Comment by leighss** [comment]
Same as  #566
