### ISSUE TITLE
Low resolution tray icon

### ISSUE THREAD

**Issue by despens** [nextcloud/desktop#855]
### Expected behaviour
Tray Icon for nextcloud client should look nice

### Actual behaviour
Icon has low resollution
![selection_2018-11-18_22 10 10](https://user-images.githubusercontent.com/571494/48678091-ef6b6680-eb7e-11e8-8dc2-e820320fb7be.png)

### Client configuration
Client version: 2.5.0git

Operating system: Ubuntu 18.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): no info

Client package (From Nextcloud or distro) (Linux only):  `nextcloud-client/bionic,now 2.5.0-20181111.015125~bionic1 amd64 [installed]`

Installation path of client: `/usr/bin/nextcloud`

**Comment by ahvth** [comment]
The resolution appears to be correct when using the "(k)statusnotifieritem/appindicator support" extension, but too low when using Ubuntu's built-in appindicator extension. This would indicate to me that a bug should be filed with the Ubuntu team suggesting that they avoid up-sizing their systray icons, or that nextcloud ship an icon built to integrate with ubuntu's GNOME systray implementation. Don't know why Ubuntu has to always be different :smiley_cat:

**Comment by despens** [comment]
![selection_2019-01-04_07 46 43](https://user-images.githubusercontent.com/571494/50676507-fe09c200-0ff4-11e9-99bf-ee69b72015a9.png)

Apparently fixed in version 2.5.1git

Perfect, thanks!

**Comment by despens** [comment]
![selection_2019-01-04_14 15 36](https://user-images.githubusercontent.com/571494/50689760-3a581500-102b-11e9-99e3-702926037790.png)

I'm sorry to go backwards here, but upon the next system start the icon was low res again. :man_shrugging:

**Comment by skewty** [comment]
I have **Kstatusnotifieritem/appindicator support** extension running in gnome 3.32 (ubuntu 19.04 vanilla gnome package) and it is still low res.  

@ahvth did you have to uninstall the Ubuntu one to get the higher res icon?

**Comment by ahvth** [comment]
@skewty What's changed since my post is the kstatusnotifier plugin. Now they hypersize everything just like Ubuntu's plugin. So I guess the onus is on nextcloud now to work with that :(

**Comment by emichael** [comment]
I just installed the desktop client on 18.04 and am experiencing the same issue.

**Comment by IgorWalkers** [comment]
It`s the same on Gnome Fedora 30 with kstatusnotifier. Any solutions yet?

**Comment by skewty** [comment]
Here is how it looks on 20.04 (which will arguably be the largest linux desktop install userbase)

![Screenshot from 2020-03-21 10-53-32](https://user-images.githubusercontent.com/9087223/77233130-a5bfd100-6b62-11ea-85ae-9d3b84690fa7.png)

Notice how it is not only "low res" but also "stretched" looking.

**Comment by camilasan** [comment]
Is this still the case on 3.1.2?

**Comment by despens** [comment]
Looks crisp for me now in Gnome 3.36.8!
