### ISSUE TITLE
Hard dependency on QtWebEngine precludes porting on all Qt-supported platforms

### ISSUE THREAD

**Issue by mmuman** [nextcloud/desktop#856]
Building should not require such hard-to-port huge dependency just to display a few forms.

Haiku does have a very functional Qt5 port, but we do not have QtWebEngine, because porting a fork of Chromium while we don't even have a port of Chromium in the first place, and it's already time-consuming to maintain a WebKit port (and we do have QtWebKit btw), would take years.

There are likely other OSes around that could potentially get a Qt port but can't afford QtWebEngine.

I actually managed to get the owncloud client working in just a few hours…

### Client configuration
Client version: https://github.com/nextcloud/desktop/pull/852

Operating system: [Haiku](http://haiku-os.org/)

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2-4

**Comment by mmuman** [comment]
Ok, so as I heard it's used for 2FA, but still, the OC client use of QtWebKit is disabled with NO_SHIBBOLETH.
Maybe it's just an oversight and moving the package detection in the if block will work…

**Comment by rullzer** [comment]
The OC client does not use the auth flow we have. Making it possible to use the uath flow without qtwebengine is something we have discussed but has no priority right now.

**Comment by bodograumann** [comment]
Seems work is now ongoing. See #932 and #1808.

**Comment by tbn97** [comment]
Is there any Jul 2020 update on this? - My Haikubook would be "daily driver ready" if this NC client were to make it to Haiku.  👍

**Comment by bodograumann** [comment]
There is a current discussion in https://github.com/nextcloud/desktop/pull/2204. No outcome yet though.

**Comment by rodneyrod** [comment]
@mmuman looks like some updates happened recently, might be working now?

**Comment by FlexW** [comment]
QtWebEngine is now a optional dependency. I will close this issue.

**Comment by mmuman** [comment]
Oh great, I'll definitely try to have a look this summer then!

**Comment by tbn97** [comment]
@mmuman - I'd be keen to hear the outcome once you have a look at this - a Haiku NC client would be awesome!

**Comment by extrowerk** [comment]
Haiku have a QtWebengine port now, i have built the latest git sources:
![2022-05-20_lFxyKydUnhcHaVuS](https://user-images.githubusercontent.com/5569059/169550095-ff8a7cd9-ddb4-40e5-835a-0f8b916af05c.png)
Sadly inotify is not supported on Haiku, at least according to my information. Maybe there is an alternative for that, i don't know.
The Client however seems to be working, but without inotify it doesn1t recognize any changes, so it doesn't upload anything.

**Comment by mmuman** [comment]
> I'd be keen to hear the outcome once you have a look at this - a Haiku NC client would be awesome!

Busy currently but I'll definitely have a look!

> Haiku have a QtWebengine port now, i have built the latest git sources: Sadly inotify is not supported on Haiku, at least according to my information. Maybe there is an alternative for that, i don't know. The Client however seems to be working, but without inotify it doesn1t recognize any changes, so it doesn't upload anything.

I already have node_monitor support implemented for the owncloud port, no reason it wouldn't work here too.

**Comment by extrowerk** [comment]
> > Haiku have a QtWebengine port now, i have built the latest git sources: ![2022-05-20_lFxyKydUnhcHaVuS](https://user-images.githubusercontent.com/5569059/169550095-ff8a7cd9-ddb4-40e5-835a-0f8b916af05c.png) Sadly inotify is not supported on Haiku, at least according to my information. Maybe there is an alternative for that, i don't know. The Client however seems to be working, but without inotify it doesn1t recognize any changes, so it doesn't upload anything.
> 
> this is still Qt5 ? do you know if that would also works with Qt 6 ?

I think i used Qt5, haven't tested against Qt6.
