### ISSUE TITLE
Upload or download are really slow when changing network

### ISSUE THREAD

**Issue by gabrielklein** [nextcloud/desktop#857]
### Expected behaviour
I have uploaded ~100Go of data on a new installation of Nextcloud (~60'000 files).
(Photos, movies, documents)

I have multiple network
- Work network (fast upload) - ipv4
- Home network (slow upload and download) - Wired and wireless - ipv6 and ipv4
- Phone proxy (android) (fast upload and download) - ipv4

I go in "sleep mode" when moving work<->house.
I expect to be able to move from one network to another without problems.

### Actual behaviour
Tell us what happens instead

Upload (and probably download) was really slow.

Lot of errors, "freeze" while scanning files.
The apache server timeout after some time. (seen from the client logs)
Impossible to upload files after some time.

I did a lot of "pause sync", "force sync now" - but it made things worst. 

### Walkaround

Kill the client or restart the computer every time the connection changes.
killall nextcloud

I was able to upload ~20Go of data in 2-3 hours when I was struggling uploading a few GO of data the days before.

### Steps to reproduce
1. Have lot of data to be uploaded to server
2. Change the network (wired, wireless, both, ...)

### Client configuration
Client version: Version 2.5.0git

Operating system: Ubuntu 18.10 64 bits

OS language: English

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: default location

### Server configuration

Operating system: Ubuntu Server 18.4 64 bits

Web server: Apache 2

Database: MySql 5.7.24

PHP version: 7.2

Nextcloud version: 14.0.3 (new installation)

Storage backend (external storage): Mechanical Hard Disk

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
Freeze (too many files)

2. Web server error log:
No error

3. Server logfile: nextcloud log (data/nextcloud.log):
No error except some "filelock"

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
