### ISSUE TITLE
"Copy public link to clipboard" fails if link is not yet created

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#858]
I just tried the new "Copy link to Clipboard" file manager action the first time. The folder wasn't shared yet so what I expect is that it first gets shared and then the link is copied to the clipboard, but the link i got was `https://mynextcloud/index.php/s/`.

I checked the share dialog and saw that the link share was created correctly. After clicking once more on "Copy public link to the clipboard" file manager action the correct link was copied, e.g. `https://mynextcloud/s/fhdskjfhk`.

It looks like a race condition or a general error in the order in which first the link share gets created and then the link gets retrieved and copied to the clipboard.

**Comment by shaan7** [comment]
@schiessle are you still facing this problem? I just tested on Nextcloud client 2.5.2 and I got the correct link. I deliberately used a slow connection so that sharing takes time. For few seconds the clipboard didn't have anything, and after that I got the correct link.

**Comment by biva** [comment]
Hello, I justed installed 2.5.2 (build 20190319) and I don't see the feature: "copy public link to clipboard". I just have this feature for private link :(
Is it on a beta version?

**Comment by biva** [comment]
Hello, am I the only one who doesn't see this context menu? Thanks for your support :)

**Comment by biva** [comment]
I see the context menu now, with 2.5.3

**Comment by camilasan** [comment]
It has been fix in 2.6.5 or 2.6.4.

**Comment by camilasan** [comment]
I just tested with the latest desktop client and I couldn't reproduce it anymore.

**Comment by Killerusha** [comment]
Failed to copy CalDAV link to clipboard nextcloud. What can be wrong?
