### ISSUE TITLE
Not saving right URL

### ISSUE THREAD

**Issue by derbenx** [nextcloud/desktop#862]
I just wanted to suggest a slight change to the PC client app or to make it an option. 

I use a website url to forward all calls to a dynamic IP, Example:
https://mydomain.com/NC/params?*
this server returns a 307 temporary redirect to the current dynamic IP like so:
https://123.123.123.123/NC/params?*

This works fine, except that the Next Cloud pc client remembers the dynamic IP url and not the domain that I entered on setup, so whenever the IP changes I have to delete and setup my user info again.
Can we have it remember the domain entered and not the resolved redirect? (or an option to do so would be awesome for the next app release!)

Thanks, love the program!

### Actual behaviour
- PC app remembers http://123.123.123.123/NC

### Expected behaviour
- it should remember http://myDomain.com/NC
 
### Steps to reproduce
1.  Setup a webserver that forwards all traffic via a 307 redirect to another url/ip. (or ask me to set one up for testing)
2.  Setup a PC client to point to the URL
3. Note how the client saves the redirect, not what was entered.

### Environment data

Nextcloud client version:  Version 2.3.3 (build 1)

Operating system: 7 pro

OS language: en

Installation path of client: default

### Server configuration
Shouldn't be needed...
Operating system: Mint
Web server: apache
Nextcloud version: latest

**Comment by derbenx** [comment]
Follow up, changing the nextcloud.cfg to point to the right URL seems to work fine. So, I guess just patching the client to save what was typed in is all that is needed, because saving a temporary redirect is probably not the ideal route.

I'd settle for a way to just edit the URL in the GUI... even that's better than setting up a new account. ;)

**Comment by FlexW** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently, there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
