### ISSUE TITLE
Syncing a file in an E2E encrypted folder fails to lock file 403

### ISSUE THREAD

**Issue by fkjogu** [nextcloud/desktop#864]
### Expected behaviour
Uploading a file in an end to end encrypted folder should be able to acquire a lock an sync the file to the server.

### Actual behaviour
The syncing stales with an error that no lock file can be acquired. See log of the desktop client below in the link.

On the server side I do not register suspicious logs, apart from when trying to access the encrypted folder in the web browser. 

### Steps to reproduce
1. Create an E2E folder with the Android client
2. Start desktop client, enter Mnemonic
3. Add file in the Android client (works fine)
4. Add file in the desktop client (fails)

### Client configuration
Client version: 2.5.0 (rev 371001)

Operating system: Archlinux

OS language: english

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2

Client package (From Nextcloud or distro) (Linux only): nextcloud-client

### Server configuration

Operating system: nixos

Web server: nginx

Database: sqlite3

PHP version: 7.1.2

Nextcloud version: 14.0.3

### Logs

https://gist.github.com/fkjogu/4b9480f123090928d1bb111002a71dd3#file-nextcloud-desktop-log

**Comment by allexzander** [comment]
Fixed in https://github.com/nextcloud/desktop/pull/2853 and will be released in 3.2
