### ISSUE TITLE
Nextcloud Client 2.5 Initial Sync on Xubuntu 1804

### ISSUE THREAD

**Issue by greenorca** [nextcloud/desktop#867]
Nextcloud Sync hangs usually after Screensaver was active and I logged on again. Sometimes client recovers, sometimes client completely breaks. Seems to be a problem with GUI client and Screen savers (XFCE?)...
Sync works like a charm with nextcloudcmd.

### Expected behaviour
Sync should work regardless of Screensavers, Blank screens or even system suspends.

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. A fresh Xubuntu 1804 install with Nextcloud Client 2.5(installed from PPA).
2. An existing Nextcloud-Directory on the users home-dir with 160GB of data (user profile existed already before reinstalling OS)
3. install Nextcloud-client 2.5 from PPA
4. connect to Nextcloud Server, it starts to sync. Eventually one entire core is occupied...
5. wait until screensaver shows up
6. Login
7. Nextcloud-Client GUI displays errors like "an error occurred while opening a  folder Operation canceled; Saving Logfiles may even 

### Client configuration
Client version:
2.5 from official PPA
Operating system:
XUbuntu1804 with all updates

OS language:
english

Qt version used by client package (Linux only, see also Settings dialog):
5.9.5 I guess
![nextcloud_error_folder_open_2018-11-20_15-46-31](https://user-images.githubusercontent.com/11660472/48792415-81e14680-ecf4-11e8-99db-31900b1bc988.png)
Client package (From Nextcloud or distro) (Linux only):
from Nextcloud PPA

Installation path of client:
default

### Server configuration

Operating system:
Ubuntu 1604 based (odroid, arm)
Web server:
Apache 
Database:
MariabDB 10.0
PHP version:
7.2
Nextcloud version:
14.0
Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)
for a big dump of client log, pls see https://green-orca.hopto.org/index.php/s/nbffytMTzyYJ87J

2. Web server error log:
should not be necessary for other clients work

3. Server logfile: nextcloud log (data/nextcloud.log):
should not be necessary for other clients work

**Comment by trev-dev** [comment]
Having the same issue with nextcloud 2.5.1-2 on Arch Linux.

**Comment by mgallien** [comment]
Can you still reproduce this issue ?
Can we close it if it is fixed ?

**Comment by trev-dev** [comment]
@mgallien I cannot speak for @greenorca but I have not had this issue for ages now.

**Comment by greenorca** [comment]
Did not occur to me anymore. However, I'd rather test it....
