### ISSUE TITLE
I'm asked to log in to NC every time I start a new desktop session

### ISSUE THREAD

**Issue by decibyte** [nextcloud/desktop#870]
Ubuntu 18.10
NC client 2.5.0daily (build 20181113)

This is probably somewhat related to #713, which I was affected by. Now I'm able to log in to Nextcloud again, but every time I start a new desktop session (e.g. after a restart of the computer), I'm asked to log in to NC again, which is a bit annoying. I'd much prefer if my NC login/session lasted across desktop sessions, as it used to do.

**Comment by rullzer** [comment]
@decibyte strange.

You say desktop sessions. It does work if you close your client and restart it within the same desktop session?

**Comment by decibyte** [comment]
@rullzer, I just tested that, and yes: If I close the client and open it again, I'm still logged in.

**Comment by decibyte** [comment]
Okay, I did some more testing:

Close client, open again: I'm still logged in to Nextcloud.
Log out of desktop session, log in to desktop again: I'm still logged in to Nextcloud.
Reboot machine, log in to desktop: I'm shown a Gnome dialog asking to unlock my GPG key. Doing that: I'm still logged in to Nexcloud.
Reboot machine, log in to desktop, cancelling the GPG unlock dialog, I'm shown the following two windows:
![No longer logged into Nextcloud](https://blackfin.cannedtuna.org/nextcloud-login.png)

Maybe this works as intended? I'm just not used to having the Nextcloud client session protected by a wallet locked by my GPG key.

**Comment by decibyte** [comment]
> Ok so we do not enforce your wallet to be protected by your gpg key. We just ask 'store it in the keychain'.

Yeah, I realised that. Sound good if you can make it a bit more friendly and informative. Thanks for looking into this :)

**Comment by Wivik** [comment]
Hello,
I'm getting the same behavior but I don't have any warning about GPG.
Fedora 30
Nextcloud version 2.5.2git
Git revision 56c905819ee6d48db136e7b5978bdf2a42677f3f
Using Qt 5.12.1, built against Qt 5.12.1
Using 'OpenSSL 1.1.1b FIPS  26 Feb 2019'

To reproduce : 
- Close the sync client
- Relaunch it
=> will ask a login to my Nextcloud server

I tried to launch the client in command line with logdebug options but nothing relevant inside it.

**Comment by misch7** [comment]
Closing this here to keep everything in one issue, please see: https://github.com/nextcloud/desktop/issues/1292#issuecomment-560008811
