### ISSUE TITLE
App doesn't fully respect desktop theme

### ISSUE THREAD

**Issue by luntik2012** [nextcloud/desktop#871]
Steps:
- Click the lock button to the left from "Connected to https://...." label.
- Hover any active item
You'll see some new popup. This popup doesn't respect desktop environment theme, it is white, I cannot see what is there.

Theme is adapta nokto eta, archlinux
> This release was supplied by Nextcloud GmbH
> Built from Git revision 371001 on Nov 17 2018, 11:57:22 using Qt 5.11.2, OpenSSL 1.1.1 11 Sep 2018

I cannot paste screenshots, thank you, microsoft
https://ibb.co/cBS27A

**Comment by jancborchardt** [comment]
This is also a more general thing, but if you have the dark theme enabled in macOS or GNOME, the desktop client does not use that. Would it be possible to do it? @camilasan @jpnurmi

**Comment by er-vin** [comment]
This is already solved per commit 7abb9cd above.
