### ISSUE TITLE
Create some view for files with conflicts

### ISSUE THREAD

**Issue by vitaliis** [nextcloud/desktop#872]
### Problem statement

Right now it is very difficult to identify where files with conflicts are.
Therefore it is difficult to find and resolve these conflicts.

Some UI is needed to find such files.

### Possible solution 1
Add another tab next to "Account" and "Activity". Then you have the whole main window to display information about conflicts. This has a disadvantage of being always there and not only when it is needed. Moreover seeing "Conflicts" tab next to activities is not a very nice thing. It might be also a bad sign that conflicts is one of the core concepts, which is normally not true and must be an occasional thing to happen.

### Solution 2
On the first tab (the one next to "Activity"), where the list of all folders is:
add a box with all conflicting files. It can be a list of conflicts which is hidden by default. A spoiler (or however such element is called) element can be used. After a click at it, it will unfold and show the complete list. Actually, exactly in the place where current message appears saying "There are unresolved conflicts. Click for details".

**Comment by rullzer** [comment]
Yes I noticed this as well in regards to https://github.com/nextcloud/desktop/issues/566

Conflict files are things that need attention. 

We can do a few things.

1. Sort them up top in the activity view
2. When there are sync conflicts have another tab pop up that only lists conflict files

CC: @jancborchardt @camilasan @jpnurmi @juliushaertl

**Comment by jancborchardt** [comment]
Sync conflicts should be listed up top in the activity view, as also specified in the past.

There should not be a separate tab. Rather:
- There should be a notification symbol (red circle like we have for notifications on the server) on the activity icon.
- There should be a desktop notification about the conflict, clicking it should open the settings dialog with activity tab open (if possible).
- Any sync conflicts should be reflected with the warning state icon for the tray.

**Comment by vitaliis** [comment]
Does it have to be on the activity tab? From my experience you don't take any actions directly there at the activity tab as there is no possibility to do so.

Right now the message about conflicting files is displayed right below the sync folder where a conflict happened, e.g.:
![image](https://user-images.githubusercontent.com/1839541/48920071-f522be00-ee96-11e8-8171-f96c9a8b140a.png)

Why not unfold it there in place and show a list of conflicts to resolve after a click on "Click for details"?! And be able to fold them back (hide) also clicking at the same place, but maybe just changing the text. The same way as it is done with sub-folders which you sync. See example below:
![image](https://user-images.githubusercontent.com/1839541/48920103-33b87880-ee97-11e8-9f65-36a249e88c07.png)

Scrolling in this case might become an issue with usability because there is no smooth scrolling, which is a bit weird. At least on Linux Mint. But this is a separate issue.

**Comment by jancborchardt** [comment]
Let’s continue in **Activity tray and activity list design improvements #889** to not have 3 different issues about basically the same thing. :)
