### ISSUE TITLE
Unshare action should be in 3-dot-menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#878]
In the share dialog, currently we show the "Unshare" action (trash bin icon) directly in each row.

As this is a destructive action and could easily lead to misclicks, and because the regular view should be as simple as possible, it is better placed at the end of the 3-dot menu list – just like we also do it on the server and in the mobile apps.

(See the gifs at https://github.com/nextcloud/desktop/pull/847 for reference. :)

cc @jpnurmi @camilasan

**Comment by er-vin** [comment]
This is already solver via the PR mentioned.
