### ISSUE TITLE
"Open in browser" just opens an empty Firefox tab with certain Nextcloud instances

### ISSUE THREAD

**Issue by rugk** [nextcloud/desktop#879]
Description of problem: The context menu entry "Open in browser" in the Nautilus integration just opens a new Firefox window (even though my Firefox is already open!) and shows the default page there/about:newtab.

Version-Release number of selected component (if applicable): 2.5.0git

How reproducible: Always.

Steps to Reproduce:
1. Right-click on dir.
2. -> Nextcloud
3. -> "Open in browser"

Actual results:
New Firefox window with about:newtab.

Expected results:
Direct me to my Nextcloud instance in a new tab in my existing Firefox window.

Additional info:
Should not this just be a simple firefox <URL> call? I mean Firefox usually does all this stuff and redirect it to my existing window, so I am really surprised about this bug.

----

originally reported downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1651818

**Comment by juliushaertl** [comment]
I cannot reproduce this here on my Arch system. Firefox opens the correct page.

**Comment by rugk** [comment]
Okay, tested with epiphany (GNOME Web) and I see the problem there. My URL is of the folowing type:

```
expected: https://someserver.sub.domain:4444/nextcloud/index.php/f/485
     got: https://:4444/nextcloud/index.php/f/485
``

It totally missed the domain part. I guess it is related to the port or so…

**Comment by rugk** [comment]
@juliushaertl I do have provided the info, I guess you can remove the "needs info" label. :smile:

**Comment by camilasan** [comment]
I think this is fixed. Please try with 3.1.2. If it still happens, please re-open the issue.
