### ISSUE TITLE
Don't send notification about "notification"

### ISSUE THREAD

**Issue by BAKFR** [nextcloud/desktop#884]
Nextcloud desktop send some (desktop) notifications about a server notification.
It forces the user to open the nextcloud window to see the content of this notification.  

### Expected behaviour

The content of the server notification should be included in the desktop notifications.
Something like:

> **Nextcloud - Action required**
> nextcloud.bajoo.fr: an upgrade to Nexcloud 14.0.4 is available

### Actual behaviour

![screenshot](https://user-images.githubusercontent.com/1631475/48956583-1b5a6380-ef54-11e8-9c2f-7320ed19419b.png)

The desktop notification tell me there is something to check, but I must open the nextcloud window to see the message. This step should be unnecessary.

### Client configuration
Client version: 2.3.3
Operating system: Linux
OS language: French
Qt version used by client package (Linux only, see also Settings dialog): Qt 5.11.1
Client package (From Nextcloud or distro) (Linux only): Gentoo packages

**Comment by camilasan** [comment]
Hi! Could you please try the latest client? We did quite some improvements on Notifications and activities  and the notification gives more information but you still need to go to the activities list if you need to do something....

**Comment by jancborchardt** [comment]
The issue still exists depending on notifications. For example here a notification about a private message:
![desktop app private message should show directly](https://user-images.githubusercontent.com/925062/51323763-5ca95400-1a69-11e9-90c5-77c30ac90e45.png)

Instead it should show

> **Arthur Schiwon**
> Hi Jan blabla bla bla this is the message text directly

And the server address is not so important.

**Comment by PTrottier** [comment]
Similarly, I receive notifications about missed notifications (see included image), which I did see but the system doesn't register that.
![notifications](https://user-images.githubusercontent.com/31802216/230082025-510103a8-dc2b-45c6-b73f-3d6982711e70.png)

Is it possible to disable them?

Would you prefer my query be in a separate issue?

**Comment by jospoortvliet** [comment]
This now works, at least in Linux. I think it's operating system dependent - some OS'es don't allow this.
