### ISSUE TITLE
Minor typo in activity tray

### ISSUE THREAD

**Issue by criwe** [nextcloud/desktop#885]
### Expected behaviour

Text should be "Synchronisiert path/file

### Actual behaviour

![destop_client_typo](https://user-images.githubusercontent.com/7531138/48961352-efe77100-ef73-11e8-9021-7c68e8b8cb0d.jpg)

(space missing)

### Steps to reproduce
1. Sync some files...

### Client configuration
Client version: 2.5.0

Operating system: Win7

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From Nextcloud or distro) (Linux only): n/a

Installation path of client: C:\Program Files (x86)\Nextcloud\

### Server configuration
no relevant for that issue

**Comment by lavigne958** [comment]
After a quick look at the source code this seems to be fixed see commit: d564279254
It was fixed with the issue #1068
