### ISSUE TITLE
Windows client 2.5.0 cannot connect after moving nc files to subfolder

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/desktop#886]
Hi,

to get a clean extra files list I moved all files of the nc installation to a subfolder called nc.
Updating configuration and connecting with website and android client works fine.
Only with the windows client 2.5.0 I cannot connect to the server.

Error log at trying to connect:

`{"reqId":"HUxGSsjJOvYcuffCVONg","level":3,"time":"2018-11-21T16:43:51+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/nc\/\/index.php\/login\/flow","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nc\\\/index.php\\\/login\\\/flow) cannot be processed by the script '\\\/nc\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client39\\\/web136\\\/web\\\/nc\\\/lib\\\/base.php(951): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/clients\\\/client39\\\/web136\\\/web\\\/nc\\\/index.php(42): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client39\\\/web136\\\/web\\\/nc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":733}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.0v2.5.0 (build 20181112) (Nextcloud)","version":"13.0.5.2"}`

NC Version: 13.0.5.2
Windows Version: Windows 10 Build 1803
Server: Debian 3.2.89-2 x86_64
PHP version: 7.1.19

**Comment by brtptrs** [comment]
We also get this error on NC14, but only sometimes. I've just seen it on an Ubuntu client Version 2.5.1 with NC 14.0.2. while attempting to create an account.
After breaking off the first login attempt  starting over the login succeeded.

**Comment by mgallien** [comment]
Can you still reproduce this issue ?
Can we close it if it is fixed ?
