### ISSUE TITLE
Offer to import ownCloud settings on first launch

### ISSUE THREAD

**Issue by jlfranklin** [nextcloud/desktop#894]
### Expected behaviour
After installing the Nextcloud desktop client on a machine that already has ownCloud's client installed, the Nextcloud client should read the ownCloud settings and offer to import the accounts and sync locations.

### Actual behaviour
The user invited to (re-)create the accounts and sync points.

### Steps to reproduce
1. Install ownCloud's client
2. Set up a couple accounts and sync points, say one for work, one personal, and one for a local meetup group.
3. Install the Nextcloud client.
4. Find yourself doing step 2 again.

### Client configuration
Client version:
"Built from Git revision 371001 on Nov 12 2018, 01:03:46 using Qt 5.9.2, OpenSSL 1.0.2m 2 Nov 2017"

Operating system: macOS Sierra

OS language: English

**Comment by jlfranklin** [comment]
Bumping to prevent stale-bot from snacking on the bug.

**Comment by claucambra** [comment]
Hello, this has now been a part of the desktop client for a few releases -- on first launch you will be prompted to import OC accounts :)
