### ISSUE TITLE
Ability to stop slideshow movement - accessibility issue

### ISSUE THREAD

**Issue by llune** [nextcloud/desktop#895]
### Expected behaviour
<img width="862" alt="image" src="https://user-images.githubusercontent.com/6073336/49037435-7db49d80-f1ba-11e8-8e93-7e5f91117e3e.png">

There should be a play/pause button to stop and relaunch the animation.

Movement can be highly disturbing for some people. Some users experience distraction or nausea from animated content thus preventing them from performing an action.

### Actual behaviour
The slideshow is moving without any possibility to stop it.

### Client configuration
* Client version: 2.5 - build 20181112
* Operating system: MacOS 10.14.1
* OS language: French

**Comment by jancborchardt** [comment]
Good point. What do you think about doing it like on the mobile app, where we don’t do the animation by default, but allow swiping (or clicking in this case) to switch to the next slide?

We could use some indicator circles below to indicate which slide we are at, just like we do in [Android on first run](https://github.com/nextcloud/android/pull/2881):
![](https://user-images.githubusercontent.com/5836855/44032547-b1ca5f48-9f07-11e8-87a1-dfad41cf25b7.png)

**Comment by llune** [comment]
Hi!

I think it would be far better indeed to have something that the user can control and decide to move like this slider 👍

**Comment by jancborchardt** [comment]
Cool!

@camilasan @rullzer maybe it's even possible to do it with the white text on blue background for consistent style? And it won't look so grey in grey. :)

**Comment by rullzer** [comment]
I do not think removing the whole animation makes sense. Being able to stop it sure.

There is a big difference on mobile. You can easily swipe. However on desktop this is not the case. Removing the animation most likely results in 99% of the people not seeing the other slides. Which then would mean we could just as easily remove them.

**Comment by llune** [comment]
Maybe you don't have to use a slider?

Just put the 4 infos on the desktop client. It seems there's plenty of room for it and you're sure people will get all the information.

**Comment by jancborchardt** [comment]
> Just put the 4 infos on the desktop client. It seems there's plenty of room for it and you're sure people will get all the information.

@llune this will result in information overload unfortunately.

---------------------------------------

@rullzer you are right, yes. We could add arrows on the right and left (ideally just graphics and not button-styled), and clicking any of them manually will stop the slideshow. What do you think?

**Comment by camilasan** [comment]
This is fixed and merged in master #1149
