### ISSUE TITLE
Default settings dialog size too large

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#897]
By default, the settings dialog is very big:
![nextcloud window too big](https://user-images.githubusercontent.com/925062/49099559-0e01e980-f272-11e8-9de0-e94685884d36.png)

This is the smallest possible size I can make it, and it’s perfect!
![nextcloud window size smallest possible](https://user-images.githubusercontent.com/925062/49099558-0d695300-f272-11e8-8d95-958e0db25655.png)

A smaller dialog looks less imposing and less complicated, so let’s use the small size by default. :) @camilasan @jpnurmi

**Comment by er-vin** [comment]
Seems this is already the case here. If I kill all the dialog size related settings and restart, it's sized to the minimum possible layout already.
