### ISSUE TITLE
Treating symlinks to folders seems badly broken in version 2.5.0

### ISSUE THREAD

**Issue by alexeymuranov** [nextcloud/desktop#899]
# File-eating bug

### Expected behaviour

Either no modifications, or complete update to the latest versions both ways (synchronisation).

### Actual behaviour

When the local synchronised folder contains a symlink to a folder while the remote synchronised folder contains an actual folder with the same name in the same location, strange things happen.  A whole folderful of files can disappear without trace, or the synchronisation can happen only localwards.

I could reproduce disappearance of files in my existing folder, but not in a freshly created setup.

There were other strange and hard to reproduce behaviours: like not being able to synchronise an actual remote folder with a local folder symlink normally, while creating a new file in the remote folder would trigger synchronisation.  I do not know how to describe or reproduce it, i can only summarise that it looks badly broken.  (I do not know what the "correct" behaviour should be when there is a folder on one side and a symlink on another, but I am sure that not this one.)

### Steps to reproduce

1. Synchronise a `synch_r` folder on a Nextcloud server with a `synch_l` folder on a personal machine.
2. Create in `synch_l` a symlink `test` to another folder `external`.
3. Create in `synch_r` an actual subfolder  `test`.
4. Try to create a file in `external` an observe that it will not be synchronised with the remote folder.
5. Try to create a file in `synch_r/test` and observe it to appear in the local `external`.

I also observed a behaviour that i didn't mange to reproduce from scratch yet, but constantly observed in my existing setup: the contents of a folder that was symlinked from inside a synchronised local folder was wiped out without trace on each synchronisation.  Apparently it was related to the existence of an actual subfolder with the same name and in the same location in the remote synchronised folder.

### Client configuration

Client version: 2.5.0-20181111.015125~bionic1

Operating system: Ubuntu 18.04

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by alexeymuranov** [comment]
It seems that file disappearance is confirmed in another scenario: https://github.com/nextcloud/desktop/issues/876#issuecomment-489875611.

**Comment by FlexW** [comment]
Does the issue still apply?
