### ISSUE TITLE
Client not able to authenticate when using SSO

### ISSUE THREAD

**Issue by iMarkus** [nextcloud/desktop#9]
I am using Apache server for authentication and SSO. After this the client always prompts for login credentials and is not able to do the authentication.

App: SSO & SAML authentication using REMOTE_USER

Also app passwords are not working.

**Comment by camilasan** [comment]
Do you still have this problem? If yes, please, post your logs. Thanks.

**Comment by claell** [comment]
@iMarkus Is this still relevant with current client versions?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
