### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/desktop#900]
Compilation ran correctly, but when I try to access the help command on the built binary, I get this error:
```
jan@Rechenknecht:~/desktop-install/bin$ ./nextcloud
./nextcloud: symbol lookup error: ./nextcloud: undefined symbol:
_ZN3OCC18AbstractNetworkJob10onTimedOutEv
```

### Client configuration
Client version: latest master
Operating system: Ubuntu 18.04.1 LTS

I also get this error when trying to open it through the file manager, even though it’s set to executable (also note the file type icon looks like a text file and not like an executable?):
![executable error](https://user-images.githubusercontent.com/925062/49147063-ebb8ac00-f303-11e8-8823-7b93eb7a345e.png)

**Comment by camilasan** [comment]
Solution:
- add export LD_LIBRARY_PATH="/usr/lib64:/$DESKTOP_CLIENT_INSTALL/lib64" to .bashrc.

**Comment by jancborchardt** [comment]
@camilasan could this even be automatically done during `make install`?
