### ISSUE TITLE
Cannot get Desktop Client 2.5.0 finalising synchronization Nextcloud 14

### ISSUE THREAD

**Issue by chuckincloud** [nextcloud/desktop#902]
### Expected behaviour
Accessing synchronization options with any login on macOS and Windows 10.

### Actual behaviour
Nextcloud Connection Wizard (Nextcloud Desktop) freezes after login on the "Redirecting" screen.
I can see that a connection process is running as in the user "activity" section it displays that a Sync Client seems to be paired. However, there's no feedback and the sync process gets stuck on the "redirecting" screen.
It does not happen wether i try to connect using the admin account.

### Steps to reproduce
1. Installing Nextcloud Desktop Client
2. Using my server address
3. Entering my login/pwd

### Client configuration
Client version: 2.5.0

Operating system: macOS (High Sierra, Mojave), Windows 10

OS language: english, french

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Operating system: Ubuntu

Web server: 

Database:

PHP version:

Nextcloud version: 14.0.4

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by janvlug** [comment]
This is probably a duplicate of issue #279.

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed, can you close the issue ?
