### ISSUE TITLE
Missing Properties causes Sync_error in Windows Client 2.5

### ISSUE THREAD

**Issue by MrGorillaz** [nextcloud/desktop#903]
### Expected behaviour
The Windows Client should syncronize my files 

### Actual behaviour
The Client will get: 
A HTTP transmission error happened. The server file discovery reply is missing data.

### Client configuration
Client version:
2.5.1
Operating system:
Windows 10
OS language:
German

Somehow i fixed this by:

11-28 13:52:27:054 [ warning sync.discovery ]:	Missing properties: "Servicetechnik_ST1" 2 0 1543409545 "M" "" "-0000001oc3jkbyldutc"
11-28 13:52:27:054 [ warning sync.csync.updater ]:	opendir failed for  - errno 10011
11-28 13:52:27:055 [ warning sync.engine ]:	ERROR during  csync_update :  "Es hat sich ein HTTP-Übertragungsfehler ereignet. Es fehlen Daten der Server-Antwort zur Dateisuche"

I disabled the shares with the Missing properties and the client works fine again.

But with a older version 2.3 it was no Problem.

I am using the latest nextcloud Release 14.04.2.

So i Guess its something with the Missing Properties..

**Comment by mgallien** [comment]
Can you test with the latest version ?
If the bug is fixed please can you close the issue.
