### ISSUE TITLE
Missing a space caracter in Activity tab

### ISSUE THREAD

**Issue by ldmpub** [nextcloud/desktop#907]
### Expected behaviour
Add a space between first word "Synchronisé" and filename (note: "Synchronisé" is "Synced" in english)
=> see attached screenshot:
![missing space](https://user-images.githubusercontent.com/1452146/49256592-b8733b80-f42f-11e8-901d-dbea5ede566b.jpg)

### Actual behaviour
It's hard to read activity without spaces between words ;-(.

### Steps to reproduce
1. Add a new file
2. Look at activity tab in the desktop client.

### Client configuration
Client version: Version 2.5.0v2.5.0 (build 20181112)
Operating system: Windows
OS language: French but it's not french specific.

**Comment by ldmpub** [comment]
After a self brainstorm, I think we could handle this by just adding an automatic space in the code but we can also "rethink" the layout of the Activity tab because the current format: "Action" + "file name" + "when" (below) is not applicable for all languages.

**Proposal 1: change strings by adding a placeholder to make a full translatable sentence.** For instance in french (see above) the summary "Synchronisé [file]" is not handy, it should be more like in the web UI something like "Fichier [file] synchronisé".

**Proposal 2: display activity in a table** with 1 column by item, I suggest => File name + Action + when (+Actor?).

Thanks in advance to share your toughs.

**Comment by ldmpub** [comment]
Additional info, a space seems to be present in the code since 24 Aug: https://github.com/nextcloud/desktop/blob/647df7bcee5b0f6000fc63590753095e85c0ce6d/src/gui/activitywidget.cpp#L182 but I don't see it despite my desktop client version is from November => I don't understand?!

Thanks for your answers.

**Comment by IAmNotImportant** [comment]
The problem lays in translation file (`translations/client_fr.ts`), where it it missing a space:
https://github.com/nextcloud/desktop/blob/b37cbea5cc12b01d9baa0e36a996c873acdeea00/translations/client_fr.ts#L522

The translation is managed using Transifex: I edited the item there (currently # 97, it will probably change in future), however it only saved it as a suggestion. I assume you did the translation (as the user has the same handle), you'll probably know better what to do to fix it now.

**Comment by ldmpub** [comment]
Hi, thanks, I have approved, in Transifex, your suggestion with a trailing space character.
**It's really a strange way to solve this issue: adding a space at the end of sentence is not common** + it may require additional work for all translators + it's far from responding to the remark I raised here https://github.com/nextcloud/desktop/issues/907#issuecomment-443414817

**Comment by IAmNotImportant** [comment]
I guess it shouldn't be much of a problem to change this part of code
https://github.com/nextcloud/desktop/blob/b37cbea5cc12b01d9baa0e36a996c873acdeea00/src/gui/activitywidget.cpp#L182
as it `prepend`s the word and space to the string. I'm currently not able to do full pull-fix-push-merge stuff (and I'm not sure how the whole translation process works), but it should be relatively easy to do.

**Comment by ldmpub** [comment]
Hi, any update?

This display bug is still there and makes the activity tab not easy to read for users ... the fix seems to be so easy to perform on the code side I don't understand why it is still opened ;-(.

**Comment by camilasan** [comment]
We do not have this widget anymore.
