### ISSUE TITLE
Button for accepting a share in activities view does not work

### ISSUE THREAD

**Issue by augustseptember** [nextcloud/desktop#910]
### Expected behaviour
Getting an "invitation" for a federated share. After clicking on "Accept"  in the activities view the share should get synced
![nc2 5-federatedshare](https://user-images.githubusercontent.com/6906270/49227631-cef6a400-f3e9-11e8-9eaa-c89deeafc34b.png)

### Actual behaviour
Nothing happens. But when I click on the three dots menu and choose accept - then it works.

### Steps to reproduce
1. Get a federated share invitation
2. Go to Activities view in the desktop client
3. Click on "accept"

### Client configuration
Client version: 2.5

Operating system: Ubuntu 18.04

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): Can't find the information in the settings dialog of version 2.5 (i know it was there before)

Client package (From Nextcloud or distro) (Linux only): Nextcloud ppa

Installation path of client: `whereis nextcloud`
`nextcloud: /usr/bin/nextcloud /usr/lib/x86_64-linux-gnu/nextcloud /usr/share/nextcloud`

### Server configuration
Nextcloud version: 14.04

**Comment by augustseptember** [comment]
And another issue is related to https://github.com/nextcloud/desktop/issues/566
you have to scroll through all the ignored file entries in the activities list to find the "accept" button. You can see the scrollbar in the screenshot from above. The "accept" entry should be on top of the list (like the conflict entries should).

**Comment by camilasan** [comment]
We have completely redesigned this view.
