### ISSUE TITLE
Installer design issue on Windows 10

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/desktop#911]
The app icon (top left corner) is showing a 🛑 instead of the Nextcloud logo. The Nextcloud logos in the installer are very blurry.

**OS:** Windows 10

@camilasan 

<img width="661" alt="bildschirmfoto 2018-11-30 um 12 22 25" src="https://user-images.githubusercontent.com/19711361/49286585-e2ae1300-f49a-11e8-98ec-646809d0e126.png">

**Comment by camilasan** [comment]
To be sure I just checked it and the current installers have the icon.
