### ISSUE TITLE
client ask for password even if kwallet is open

### ISSUE THREAD

**Issue by icf20** [nextcloud/desktop#912]
### Expected behaviour
auto login

### Actual behaviour
![image](https://user-images.githubusercontent.com/17784575/49329691-106e8700-f583-11e8-8822-ae80fd7ac749.png)

### Steps to reproduce
1 kwallet 5.52.0-1 is open
2 password is saved on the kwallet
3 start nextcloud 2.5.0-4
get this
![image](https://user-images.githubusercontent.com/17784575/49329691-106e8700-f583-11e8-8822-ae80fd7ac749.png)

### Client configuration
Client version:

Operating system: arch

OS language: en

Qt version used by client package (Linux only, see also Settings dialog): 5.11.2-3

Client package (From Nextcloud or distro) (Linux only): distro

Installation path of client: /usr/bin/nextcloud

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
