### ISSUE TITLE
Windows client crashes on start behind proxy (Qt5Core.dll)

### ISSUE THREAD

**Issue by bcutter** [nextcloud/desktop#915]
### Expected behaviour
Start the desktop client and use it

### Actual behaviour
Desktop client starts and crashes after few seconds

### Steps to reproduce
1. Update from v2.3.x to current v2.5.0 (build 20181112)
2. Run client behind a system proxy

### Client configuration
Client version: v2.5.0 (build 20181112)

Operating system: Windows 10 x64

OS language: German

Installation path of client: Y:\Programs

### Logs

Crash description according Windows problem report see below:

```
Beschreibung
Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.5.0.61560, Zeitstempel: 0x5be959aa
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.11.1.0, Zeitstempel: 0x5b234a4c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001e134a
ID des fehlerhaften Prozesses: 0x4484
Startzeit der fehlerhaften Anwendung: 0x01d47ffbd8342cfa
Pfad der fehlerhaften Anwendung: Y:\Programme\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: Y:\Programme\Nextcloud\Qt5Core.dll
Berichtskennung: c1f58e48-8971-48ad-82b0-f2c605d04c75
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

```Template for output < 10 lines```

**Additional information:**
- Only crashes when using/being connected through system proxy via Ethernet.
- When switching to Wifi or Mobile Broadband the client starts as usual.
- Already had some Qt5.....dll issues when installing (and being connected) via system proxy. Was fixed (and update successfull) when installing via Wifi (= no system proxy).

**Already tried:**
- Deleted all possibly related entries for Nextcloud client stored in the Windows credential manager --> no change
- Deleted all proxy entries in nextcloud.cfg

Any ideas? Possibly related to https://github.com/nextcloud/desktop/issues/540 ?

**Comment by bcutter** [comment]
Unfortunately no response so far. And therefore of course not fixed in new v2.5.1 yet... :-(

Hoping to make it into the next release, now every two weeks *wohoo* :-)

**Comment by stvdk** [comment]
Hi,

I have the same problem here on Windows 7 behind a proxy.
Running as admin will cause the client not to crash! But that is no solution for me.

I will investigate what's the different in proxy-settings.

regards

**Comment by stvdk** [comment]
Adding AppCrash description:
<code>
Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	nextcloud.exe
  Anwendungsversion:	2.5.1.61652
  Anwendungszeitstempel:	5c0674e1
  Fehlermodulname:	Qt5Core.dll
  Fehlermodulversion:	5.11.1.0
  Fehlermodulzeitstempel:	5b234a4c
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	00000000001e134a
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	14f6
  Zusatzinformation 2:	14f63a15ea3be1673aeaf7cd220c213d
  Zusatzinformation 3:	2ebf
  Zusatzinformation 4:	2ebf658c9bc7449b9a81de1d735f13a7
</code>

regards

**Comment by bcutter** [comment]
Update: With desktop client v2.5.2 (2.5.2.5231) the behaviour remains the same. No progress on this, quite frustrating!
```
Beschreibung
Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.5.2.5231, Zeitstempel: 0x5c90e346
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.11.1.0, Zeitstempel: 0x5b234a4c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001e134a
ID des fehlerhaften Prozesses: 0x2358
Startzeit der fehlerhaften Anwendung: 0x01d4f04fc90bb60a
Pfad der fehlerhaften Anwendung: Y:\Programme\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: Y:\Programme\Nextcloud\Qt5Core.dll
Berichtskennung: 94420388-a9c5-4e6f-b5d6-832763f6aa1e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by bcutter** [comment]
Same behavior with latest 2.5.3 release. Is ANYONE taking care of this? Very frustrating... it‘s been more than 9 month (the baby would’ve arrived already :-) ).

**Comment by Volker-K** [comment]
Some more problems with system wide proxy settings in https://github.com/nextcloud/desktop/issues/901 and https://github.com/nextcloud/desktop/issues/1046 
New installations on Windows behind a proxy won't even connect to any nextcloud instance w/o client specific proxy settings.

**Comment by angelopasotto** [comment]
I had this problem (crash reporting Qt5Core.dll) when I changed by mistake the name of the folder I was syncing, then I restored the original name and problem disappeared.

**Comment by bcutter** [comment]
@angelopasotto: Nope, can’t confirm that. Would be too easy... the folder is just called „Nextcloud“.

**Comment by bcutter** [comment]
This issue seems to be fixed with latest stable 2.6.0 release.

**Comment by Floflobel** [comment]
Not fix in 2.6.1

**Comment by laarisyko** [comment]
Hi, we have the same problem here for 2.6.1stable for Windows. It runs for several hours and it mainly crashs during idel time. If it has to sync something it does not crash normally. This issue basically makes it imposible to work with the sync client, we already had several double editing problems during our daily work. Is there a workaorund even before the next version will be released?

The windows crash report says the following:
Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.6.1.6017, Zeitstempel: 0x5dc0b373
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.12.5.0, Zeitstempel: 0x5d6ebdfc
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000028978
ID des fehlerhaften Prozesses: 0x3db0
Startzeit der fehlerhaften Anwendung: 0x01d5aa7db907ccf9
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Berichtskennung: 05eb1916-2ecc-4f51-be13-d0c257265069
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by laarisyko** [comment]
Hi @Floflobel, it seems that you found a solution. Could you please let me know more about the details?  I don't really understand what you mean with: 

> to solve the problem I have remove the configuration into %appdata%

Many thanks 👍

**Comment by saftigall** [comment]
> Hi @Floflobel, it seems that you found a solution. Could you please let me / us know about the details? I don't really understand what you mean with:
> 
> > to solve the problem I have remove the configuration into %appdata%
> 
> Many thanks 👍

Hi@laarisyko , the %appdata%-folder is located in you user's home, e.g. C:\Users\JohnDoe\AppData\
Nextcloud config files are located in %appdata%\Roaming\Nextcloud and %appdata%\Local\Nextcloud

I had the same problem ("Name des fehlerhaften Moduls: Qt5Core.dll") caused by the Windows Firewall Ransomware protection. After disabling this feature Nextcloud worked like a charm again.
