### ISSUE TITLE
End-to-End Encryption enabled automatically

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#917]
I'm just sitting in front of my computer and without interacting with the sync client this window pops up:

![image](https://user-images.githubusercontent.com/1589737/49366906-cbfdfb00-f6ea-11e8-823a-4680e98b8325.png)

I didn't enabled any end-to-end encryption. Could it be triggered by someone else enabled end-to-end encryption on a shared folder?

**Comment by MorrisJobke** [comment]
> I didn't enabled any end-to-end encryption. Could it be triggered by someone else enabled end-to-end encryption on a shared folder?

Just to clarify: on the server e2ee app was enabled again (was disabled in a past upgrade).

**Comment by tobiasKaminsky** [comment]
> Could it be triggered by someone else enabled end-to-end encryption on a shared folder?

This should not be possible right now, as it is not supported at all.
If someone can really share a e2e folder, than this is a bug right now.

**Comment by schiessle** [comment]
Discussing this with @tobiasKaminsky I think the client detects the new capability tries to fetch an existing key from the server (which makes sense, because if the user has some encrypted folders they want to access it). But in case there is no existing key, the initial creation should not be triggered and instead postponed until the user enabled encryption for one folder.

**Comment by tobiasKaminsky** [comment]
Now it happened to me also.
As I have 4 accounts, I now do not know for which account the mnemonic is…
--> please also include account name into this dialog

**Comment by rullzer** [comment]
There is a ticket already about this somewhere. This was how is was specified:
See https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#adding-an-end-to-end-encrypted-device and https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#further-devices

We could improve here sure. But it is not high on the list of things to fix.

**Comment by augustseptember** [comment]
@tobiasKaminsky had the same confusion about the mnemonics: https://github.com/nextcloud/desktop/issues/753

**Comment by jancborchardt** [comment]
Also, this should not just pop up, but only when it’s relevant. For me it showed when I connected the account, where it’s very irrelevant.

It should show only when I either want to encrypt a folder myself, or receive an encrypted folder as a share and want to open it.

Otherwise we ask people to write something down that they will not care about at that moment and then not have anymore when they really need it.

**Comment by er-vin** [comment]
Hello,

I think this issue is properly addressed with PR #1241 so closing now.

Regards.
