### ISSUE TITLE
Linux client/nautilus context menu entry 'Nextcloud' missing on folders with umlauts (äöü)

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/desktop#920]
In nautilus file manager the context menu entry "Nextcloud" is missing on files/folders containing umlauts (öäü, maybe some more)

Create a folder e.g. "Kennwörter" -> context menu entry missing
Rename to "Kennwoerter" -> context menu is there

OS: Ubuntu 18.04.1 LTS (with latest updates)

$ nautilus --version
GNOME nautilus 3.26.4

Desktop client from ppa https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client
$nextcloud --version
Nextcloud version 2.5.1git
Using Qt 5.9.5, built against Qt 5.9.5
Using 'OpenSSL 1.1.0g  2 Nov 2017'

**Comment by tagru** [comment]
I executed nautilus with flag --no-desktop and the following error was seen

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 230, in get_file_items
    return self.ask_for_menu_items(files)
  File "/usr/share/nautilus-python/extensions/syncstate-Nextcloud.py", line 237, in ask_for_menu_items
    socketConnect.sendCommand(u'GET_MENU_ITEMS:{}\n'.format(filesstring))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 17: ordinal not in range(128)
```

On startup, there was also this method, but I don't know if the python version is important for this issue.
```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Initializing Nextcloud-client-nautilus extension
Using python version sys.version_info(major=2, minor=7, micro=15, releaselevel='candidate', serial=1)
```
Hope this helps.

**Comment by rugk** [comment]
Even worse, it also affects Emojis… 😱 (…sorry… yes… for… that…)

**Comment by rugk** [comment]
BTW, downstream reported [at Fedora here](https://bugzilla.redhat.com/show_bug.cgi?id=1678485).

**Comment by lupa18** [comment]
Same here with Linux Mint 19 Tara

**Comment by lupa18** [comment]
Hello, is there any possibility to help in fixing this?

**Comment by lupa18** [comment]
Is this software alive? 

For non-English speaking is important that this works well. How do you explain to users that they can use common symbols that they use in their natural speaking like accents?

**Comment by errotu** [comment]
I can confirm that this bug still exists in client v2.6.0git.

**Comment by ruedigerkupper** [comment]
Actually, it is enough if there's an umlaut anywhere in the filepath: If a folder name contains an umlaut, you can't share any file below that folder, even if the file name itself only contains ASCII.

**Comment by versotym** [comment]
Open /usr/share/nautilus-python/extensions/syncstate-Nextcloud.py and at the very beginning change `import sys`
to
`import sys
reload(sys)
sys.setdefaultencoding('utf-8')`

**Comment by versotym** [comment]
Open /usr/share/nautilus-python/extensions/syncstate-Nextcloud.py and at the very beginning change 
```
import sys
```
to
```
import sys  
reload(sys)  
sys.setdefaultencoding('utf-8')  
```

**Comment by lupa18** [comment]
Hello @versotym ! thanks, here with nemo, the file is at: /usr/share/nemo-python/extensions

I made the change, then restart nemo and nc client, and now the extension is not working.

**Comment by lupa18** [comment]
WTF ! that did the trick ! thanks @versotym !!

Are u going to do a PR here?

**Comment by versotym** [comment]
Glad it helped! Just did a PR #1907

**Comment by lupa18** [comment]
Hey, if we all subscribe to PR will be more visible?

**Comment by DJCrashdummy** [comment]
unfortunately this bug occurs for all languages, if you eg. use a `#` within the path.

**Comment by supremesyntax** [comment]
Tested with v3.2.0 on ubuntu 20.04. It is working. Closing this. Anyone feel free to comment if this still affects you.

**Comment by ruedigerkupper** [comment]
Confirming that it's fixed.
