### ISSUE TITLE
Individual bandwidth limits for accounts or disable limiting per account

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/desktop#921]
### Feature request
It should be possible to set individual up-/download speed limits for different accounts or as an alternative - probably easier to implement? - option: Disable rate limiting per single account.

### Use case description
For enhanced security I've set up a private nextcloud server in my home network that is isolated against external connections. Other nextcloud server instances I'm using are accessible through the internet.

The home network uses an internet connection that is shared with other tenants, so setting a bandwith limit in the client is necessary. Regarding the communication within the private network to the private Nextcloud instance I do not care about limits (or would set them much higher).

The problem is: Greater data volumes are transferred to and from the private server inside the private 
network. If I set a bandwith limit adapted to the internet connection these tasks take virtually forever.

**Comment by camilasan** [comment]
I think this is a good case to try the virtual file system: https://help.nextcloud.com/t/help-test-our-desktop-client.
