### ISSUE TITLE
[Windows] Silent install of Nextcloud Client 2.5.0 exits with error code 1223

### ISSUE THREAD

**Issue by feltel** [nextcloud/desktop#922]
### Expected behaviour
Installation in silent mode should run and exit with error code 0

### Actual behaviour
Installation exits with error code 1223. Reported same error in 2015 against ownCloud Client 2.0.1 (https://github.com/owncloud/client/issues/3831). Error was fixed and installation worked since then. After switching to Nextcloud I packaged it for our software deployment and ran into the same issue as back then with the ownCloud client.

### Steps to reproduce
1. open elevated prompt
2. run "echo %errorlevel%, should return 0
3. run "start /wait \path\to\installer\nextcloud-setup.exe /S"
4. running "echo %errorlevel%" returns 1223

### Client configuration
Client version: 2.5.0.61560

Operating system: Windows 10 1803 x64, latest cummulative update

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: %programfiles(x86)%\Nextcloud

**Comment by johnripper1** [comment]
Due to the absense of an MSI installer, the unattended install was always a mess.

If it is installed: configure your software distribution to accept 1223 as sucessful installation.

Die the same here.

**Comment by feltel** [comment]
Sorry for being late but other projects needed some action. 

Accepting error code 1223 in my scripts as successful would be kind of last resort. As the same problem was there in the ownCloud client (and being fixed) I assume it is fixable also in the Nextcloud client, which uses the same codebase. Am I wrong?

**Comment by joerifeyen** [comment]
We implemented the new client 2.5.2 and also noticed that the exit value is 1223 when successful. In our software distribution tool we had to define exit value 1223 as success value. This is a bug in the installer.

**Comment by ulfkosack** [comment]
Same exitcode on client version 2.6.0

**Comment by colttt** [comment]
an old bug still not fixed?!

**Comment by johnripper1** [comment]
no.

**Comment by misch7** [comment]
Hey,

we fixed the issue in the installer script. Due to some weird bug the installer returned 1223 from the success function.

You may try it with one of our recent daily builds:
https://download.nextcloud.com/desktop/daily/Windows/nextcloud-2.7.0.6016-daily-20191104-Release.exe

The fix will get into the upcoming 2.6.1 release.
