### ISSUE TITLE
Gnome shell crashes when syncing a lot of files and hovering over the progress bar

### ISSUE THREAD

**Issue by augustseptember** [nextcloud/desktop#924]
### Expected behaviour
Maybe just show only 3 filenames which actually get synced, when pointing with cursor on the progress bar

### Actual behaviour
I assume the client tries to show me all files that get synced in the info text that shows up, when hovering the progress bar:
![nc2 5 1](https://user-images.githubusercontent.com/6906270/49608502-15737200-f999-11e8-99e1-decf6754321f.png)
Was not able to screenshot the yellow text that shows on hovering...

I could reproduce the crash of the gnome shell only 3 times then it worked again... 

### Steps to reproduce
1. Register new user
2. Start to sync several gb of data, wait until several files are synced
3. Go to settings
4. Point your cursor over the progress bar
5. Gnome shell crashes

### Client configuration
Client version: 2.5.1

Operating system: Ubuntu 18.04

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):
? (cannot see it in settings dialog, since 2.5)

Client package (From Nextcloud or distro) (Linux only):
official ppa

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
