### ISSUE TITLE
Wont sync files after 413 request entity too large error

### ISSUE THREAD

**Issue by GekoCH** [nextcloud/desktop#925]
### Expected behaviour
I have a large folder with a lot of pictures that should be synced to the cloud

### Actual behaviour
I synced a folder with 1200 images (one image around 20mb)
I got a some errors: 413 request entity too large error

So after rebooting the system it synced again and told me that all files were synced but after investigation those files that were marked by the 413 request entity too large errors won't get synced anymore. I can't force them to synchronize again

### Client configuration
Client version: 2.5

Operating system: Win 10

**Comment by gacpac** [comment]
In my case, I updated from the 2.3.3 client and it started giving me that error. I also have a setup behind a reverse proxy with Unraid.

It doesn't happen in my android app, iPhone app or the web. Only happens at the Client using the latest 2.5.1

**Comment by gacpac** [comment]
[log nextcloud.txt](https://github.com/nextcloud/desktop/files/2897086/log.nextcloud.txt)

This is my log

**Comment by ChadBailey** [comment]
Can confirm also experiencing this behavior.... activity log reports "(skipped due to earlier error, trying again 22 hour(s))". Would be nice to be able to force a retry once server config issue is resolved.

**Comment by kylepaulsen** [comment]
I'm no expert, but this is what I figured out:

Look for a hidden .db file in the root nextcloud folder you chose to sync from. It might be named something like: `._sync_4c7450a8f62e.db`

If you quit nextcloud and either move this file out (or delete it) and then restart nextcloud, it should resync all failed files. Keep in mind this .db file has some settings data you might have set up.

Alternatively you can use a sqlite database viewer/editor like https://sqliteonline.com/ and load up that database file. You can run `DELETE FROM 'blacklist';` as a command to remove all error logs from that DB file (these are the records that prevent the client from trying to resync right away). Place the edited db file back and run nextcloud and it should try syncing the failed files again.

**Comment by tuomassalo** [comment]
I can confirm that @kylepaulsen's workaround also works on macos Catalina, which conveniently ships a sqlite client. Here's what I did:

1) quit the Nextcloud client
2) open a terminal window
3) run `sqlite3 my-nextcloud-folder/._sync_123567890ab.db`
4) type `delete from blacklist;`
5) type `ctrl-d` to exit the client
6) reopen Nextcloud client

**Comment by raleonardo** [comment]
Hi
Having the same issue with NC desktop for mac 3.1.3
`trying again in 19 hours..`

I already set 
```
                client_max_body_size        10G; 
                client_body_buffer_size     400M;
```
in nginx.

Any idea how to force sync these files?

**Comment by gacpac** [comment]
my problem was also regarding the reverse proxy from swag that had some old config, causing this to happen.

**Comment by enricocirne** [comment]
> I'm no expert, but this is what I figured out:
> 
> Look for a hidden .db file in the root nextcloud folder you chose to sync from. It might be named something like: `._sync_4c7450a8f62e.db`
> 
> If you quit nextcloud and either move this file out (or delete it) and then restart nextcloud, it should resync all failed files. Keep in mind this .db file has some settings data you might have set up.
> 
> Alternatively you can use a sqlite database viewer/editor like https://sqliteonline.com/ and load up that database file. You can run `DELETE FROM 'blacklist';` as a command to remove all error logs from that DB file (these are the records that prevent the client from trying to resync right away). Place the edited db file back and run nextcloud and it should try syncing the failed files again.

Where can I find this hidden file exactly? I do have the same issue. client_body_max is set to 0 in all config files, but I still get the request entity to large error. I am using the Android App FolderSync to use 2 way synchronisation between my DCIM folder on my smartphone and the DCIM folder on my nextcloud. 

Pleas help, Thank You!!
Eric

**Comment by Sazuneko** [comment]
I'm having the same "413 request entity too large" error, I have client_max_body_size 0; set so it should not be even setting a max file size. Is there some sort of external factor that could cause this?
