### ISSUE TITLE
Lag between designating folder as E2E and files actually being encrypted

### ISSUE THREAD

**Issue by mossy-nw** [nextcloud/desktop#926]
### Expected behaviour
Any time after a folder is designated as end-to-end encrypted (and folder icon changes to lock icon) all files copied to that folder will be end-to-end encrypted.

### Actual behaviour
There is some lag (seconds to minutes) between designating a folder as end-to-end encrypted (folder icon changes to lock icon) and actually encrypting any files copied to that folder.  There is also no indication to the user that some files in an encrypted folder remain in plaintext on the server.

### Steps to reproduce
1. designate a folder as E2E encrypted
2. immediately copy files to that folder
3. check on E2E disabled client (in my case, 2.3.3 from Fedora 29 dnf repo) to see whether files are encrypted or not.  Depending on the amount of time since designating a folder as E2E encrypted, some files will still appear in plaintext, with no indication to the encrypting user (of version 2.5.0, 2.5.1)

### Client configuration
Client version:
Version 2.5.1final (build 20181204), first observed in 2.5.0

Operating system:
Fedora 29 Linux

OS language:
English US

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.11.0

Client package (From Nextcloud or distro) (Linux only):
Nextcloud

Installation path of client:
/home/user/

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
