### ISSUE TITLE
Issue with external user backend [IMAP-Authentication] (NC Client 2.5.0/2.5.1)

### ISSUE THREAD

**Issue by alexanderheckel** [nextcloud/desktop#929]
### Expected behaviour
I'm using 14.0.4 and have local users and the external users extension enabled. However login with IMAP credentials works fine for Web-UI and iOS-APP but there seems to be a issues with the desktop client. The initial setup of the desktop client with IMAP credentials works (= initial sync) but subsequent login attemps of the desktop client are failing - using the credentials of the local user works fine for the same account. Any suggestions? What else is required from my side to assist in solving the issue?

### Actual behaviour

After ~5 minutes the desktop client gets disconnected when using IMAP credentials.

### Steps to reproduce

1. Create a local user
2. Enable and configure a external users backend (IMAP)
3. Setup Desktop Client with IMAP credentials

### Client configuration

Client version: 2.5.0, 2.5.1
Operating system: OSX 10.14, Win10

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
