### ISSUE TITLE
Latest client crashes periodically

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/desktop#930]
Hi, I'm running multiple systems with Windows 10 Enterprise 2016 LTSB and the current stable desktop client version 2.5.0 (build 20181112). I've been noticing that after the system has been running for several days, I return to a dialog titled "Nextcloud" with the header "Nextcloud has stopped working" and text "A problem caused the program to stop working correctly. Please close the program."
![image](https://user-images.githubusercontent.com/5169868/49734712-34049200-fc53-11e8-9eaa-a837b976e8cc.png)
This is the information I found in the windows application error log
```
Faulting application name: nextcloud.exe, version: 2.5.0.61553, time stamp: 0x5be014a3
Faulting module name: ucrtbase.dll, version: 10.0.14393.2457, time stamp: 0x5b7e2a7e
Exception code: 0xc0000409
Fault offset: 0x000000000006eabe
Faulting process id: 0x3b88
Faulting application start time: 0x01d48b2f5f84295e
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: bd28a9a0-00d2-4c3b-b9f0-e99a1fca534f
Faulting package full name: 
Faulting package-relative application ID: 
```
I noticed a couple other people seem to have the same issue on a different version of Windows: https://help.nextcloud.com/t/nextcloud-desktop-client-stopped-working-2-5-0-build-20181112-when-trying-to-sync/41177

**Comment by GoetheG** [comment]
Have a similiar issue.

**Comment by linucksrox** [comment]
I'm still seeing the issue with the current 2.5.1 version.

**Comment by linucksrox** [comment]
Just tried again yesterday with the latest daily build 2.5.1.5026 (built January 15, 2019) and it crashed in less than 30 minutes. Installed at 3:56PM and crashed at 4:23PM.

This time it completely locked up Windows and I had to force shutdown. 😢 

Application log entry:
```
The program nextcloud.exe version 2.5.1.5026 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 1480
 Start Time: 01d4aea714b6dc9e
 Termination Time: 19
 Application Path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
 Report Id: 1638b62f-1a9e-11e9-8791-000c299763b0
 Faulting package full name: 
 Faulting package-relative application ID: 
```

**Comment by rakekniven** [comment]
> To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Could you check for more information?

**Comment by linucksrox** [comment]
There is nothing listed in there besides a suggestion to enable Windows SmartScreen, and also nothing listed when I look at Archived Messages.

**Comment by linucksrox** [comment]
I'm still experiencing this issue here. This is a log from yesterday:
```

Faulting application name: nextcloud.exe, version: 2.6.1.6017, time stamp: 0x5dc0b373
Faulting module name: Qt5Core.dll, version: 5.12.5.0, time stamp: 0x5d6ebdfc
Exception code: 0xc0000409
Fault offset: 0x0000000000028978
Faulting process id: 0x2d44
Faulting application start time: 0x01d59891f78eb53b
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Report Id: 140416bf-ec3f-4b2c-9785-e12a5009680f
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Grolown** [comment]
I get the same issue on the latest version as well.

```
Faulting application name: nextcloud.exe, version: 2.6.4.15215, time stamp: 0x5e5eb93a
Faulting module name: Qt5Core.dll, version: 5.12.5.0, time stamp: 0x5d6ebdfc
Exception code: 0xc0000409
Fault offset: 0x0000000000028978
Faulting process id: 0x2320
Faulting application start time: 0x01d5f71b26185cce
Faulting application path: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Faulting module path: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Report Id: fe0be3d3-2f7e-4306-ab7a-6f2a5e4f6636
Faulting package full name: 
Faulting package-relative application ID: 
```

**XML Details**
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-12T12:13:22.105998500Z" /> 
  <EventRecordID>10847</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>articuno</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>nextcloud.exe</Data> 
  <Data>2.6.4.15215</Data> 
  <Data>5e5eb93a</Data> 
  <Data>Qt5Core.dll</Data> 
  <Data>5.12.5.0</Data> 
  <Data>5d6ebdfc</Data> 
  <Data>c0000409</Data> 
  <Data>0000000000028978</Data> 
  <Data>2320</Data> 
  <Data>01d5f71b26185cce</Data> 
  <Data>C:\Program Files (x86)\Nextcloud\nextcloud.exe</Data> 
  <Data>C:\Program Files (x86)\Nextcloud\Qt5Core.dll</Data> 
  <Data>fe0be3d3-2f7e-4306-ab7a-6f2a5e4f6636</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by linucksrox** [comment]
@Grolown are you also running Windows 10 Enterprise 2016 LTSB? I wonder if it's specific to this Windows version or more general.

**Comment by Grolown** [comment]
I am running Win10 Pro

<img width="251" alt="Screen Shot 2020-03-13 at 10 59 11 AM" src="https://user-images.githubusercontent.com/33235545/76632691-fd828a80-6519-11ea-8625-5afa3f717efd.png">

**Comment by boistordu** [comment]
I have the same problem since always

**Comment by boistordu** [comment]
And yes it's the latest windows 10 Pro., stable version not insider. 
So do we have any lead why after a few days of uptime, sometimes less than 24 hours, nextcloud is crashing ?  
Because it's very irritating to not have the ability to trust oue data transfer software

**Comment by boistordu** [comment]
It's not related to our antivirus or any protection either.
I have those crashes, whcih are maybe different from the first one in 2018.
I have those crashes on all of my hosts. They have some datashare in common so maybe there is a lead there but the security is not one of them since I4have various antivirus protection on my different hosts which goes from trend micro to kaspersky or bitdefender. So there is no interaction with a protection program.
So maybe another kind of program interaction or a crash under specfic condition but we need to determine which ones then....
Does anybody has a lead on this? It's really frustrating to have to connect remotely to be sure that the client is still running.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

**Comment by Grolown** [comment]
when I had this issue I downgraded and the issue went away. I have been running the latest version for a while now (not sure when it auto updated) and I have not seen this issue again. It may be resolved.

**Comment by linucksrox** [comment]
I have been keeping up to date with the latest versions and haven't had any issues with crashing in a long time so I would think it's safe to close this issue.
