### ISSUE TITLE
Received signal 11 SEGV_MAPERR

### ISSUE THREAD

**Issue by icf20** [nextcloud/desktop#931]
```
nextcloud
qt5ct: using qt5ct plugin
** Message: 20:14:10.420: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f368800b98e <unknown>
#1 0x7f3688004713 <unknown>
#2 0x7f368800b905 <unknown>
#3 0x7f36815efe00 <unknown>
  r8: 00005617126c2ff0  r9: 0000000000000003 r10: 0000000000000000 r11: 00000000000000b8
 r12: 00007ffd250c7b90 r13: 00007ffd250c7bb0 r14: 0000000000000001 r15: 0000561711dce590
  di: 0000561711dce590  si: 00005617126c2ff0  bp: 00007ffd250c7b60  bx: 0000561711d86e50
  dx: 0000561711dce5a0  ax: 0000561711e1cf20  cx: 0000561711dce5a0  sp: 00007ffd250c7b18
  ip: 0000000000000000 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

distro archlinux
nextcloud version https://www.archlinux.org/packages/community/x86_64/nextcloud-client/

steps
1 open
2 put password
3 click login
4 crash

**Comment by icf20** [comment]
installing gnome-keyring "solves" the issue but that should not happen given that qtkeychain is installed

**Comment by Strit** [comment]
I have the same issue. It started happening when qt got updated to 5.12.0.

**Comment by g0rbe** [comment]
For me, the `gnome-keyring` not solved the problem

**Comment by cpotron** [comment]
I have the same issue on Arch. Temporarily, you can use the **AppImage version** of the desktop client by downloading and make it executable. It works juste fine for me : [https://nextcloud.com/install/#install-clients]

**Comment by louwers** [comment]
Arch Linux users can use https://aur.archlinux.org/packages/nextcloud-client-appimage-daily/ for the appimage version.

**Comment by Strit** [comment]
> Arch Linux users can use https://aur.archlinux.org/packages/nextcloud-client-appimage-daily/ for the appimage version.

Which is just a workaround, not a fix. :slightly_smiling_face:

**Comment by Strit** [comment]
Awesome. 

I hope this project will take it and apply it upstream, so all can benefit. :slightly_smiling_face:

**Comment by gsalvatella** [comment]
Same error here. Using the daily build is indeed a workaround for Arch users :) Let's see if the fix goes upstream asap
