### ISSUE TITLE
Build without qt-webengine

### ISSUE THREAD

**Issue by theova** [nextcloud/desktop#932]
Hello,

Thank you very much for your efforts on providing such a good cloud application. 

I saw that the nextcloud client depends on qt-webengine. As this software is 
[considered to be nonfree](https://lists.gnu.org/archive/html/directory-discuss/2017-11/msg00014.html) the hole client cannot be free. For a more informations about free software see [fsf.org](https://www.fsf.org/about/what-is-free-software).

I would kindly ask you how I can  build the client without qt-webengine?

Furthermore: Do the [daily images](https://download.nextcloud.com/desktop/daily/Linux/) contain the nonfree parts with qt-webengine?

(OS: [Parabola GNU/Linux-libre](parabola.nu))

**Comment by FrostKnight** [comment]
I second this, and also add, that I had problems with Nitrokey's appimage for the very same reason as the Nextcloud desktop appimage.  My point being I get this error:
[redacted!
@redacted! ~]$ ./Nextcloud-2.5.0.AppImage
./Nextcloud-2.5.0.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by ./Nextcloud-2.5.0.AppImage)
./Nextcloud-2.5.0.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclbNcT8M/usr/bin/../lib/libnextcloudsync.so.0)
./Nextcloud-2.5.0.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclbNcT8M/usr/bin/../lib/libocsync.so.0)
./Nextcloud-2.5.0.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclbNcT8M/usr/bin/../lib/libqt5keychain.so.1)
./Nextcloud-2.5.0.AppImage: /usr/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /tmp/.mount_NextclbNcT8M/usr/bin/../lib/libQt5WebEngineWidgets.so.5)

My OS is Hyperbola GNU/Linux-Libre

**Comment by doronbehar** [comment]
BTW I've started using [Rclone](https://rclone.org/webdav/) which works a little bit differently but has no qt5 dependecies at all.

**Comment by FrostKnight** [comment]
> BTW I've started using [Rclone](https://rclone.org/webdav/) which works a little bit differently but has no qt5 dependecies at all.

It is a bit too hard for me though. Sadly...

**Comment by papjul** [comment]
I second @doronbehar.
As a Gentoo user, it would additionally save me hours of compilation.
Can we at least have a choice between qtwebengine and qtwebkit?

**Comment by sroracle** [comment]
[Here is a patch](https://code.foxkit.us/sroracle/packages/raw/bcc457430e844a29909b105a03a040b0bb994b10/user/nextcloud-client/no-webengine.patch) that will let you build the client without WebEngine, setting the default back to HTTP / Basic auth. Someone familiar with CMake can adapt this and make it a build time configuration option.

**Comment by FrostKnight** [comment]
I would love to see this added sroracle, wouldn't be me too add the code though, never done something like that before.

**Comment by theova** [comment]
Thanks @sroracle for this patch!
[Here](https://labs.parabola.nu/issues/2107#note-7) is a modified `PKGBUILD` for Parabola (may work for other Arch derivativies as well).

It would be great to see this patch included upstream. Is there any chance to see this happen?

**Comment by FrostKnight** [comment]
Any chance you could make an appimage of that and have it bypass whatever qt I am using? I have an old qt, but the current appimages keep depending on what *I* have not what's *in* the appimage.

**Comment by FrostKnight** [comment]
ps, thanks sroracle for making that patch!

**Comment by theova** [comment]
> Any chance you could make an appimage of that and have it bypass whatever qt I am using? I have an old qt, but the current appimages keep depending on what _I_ have not what's _in_ the appimage.

No, sorry. I don't know how to do this.

**Comment by FrostKnight** [comment]
Well, its possible, I had a problem like this with nitrokey-app also. And they figured out how to fix that bug. :) 
Maybe you should ask them... and yes they have an appimage too. ;)

**Comment by FrostKnight** [comment]
> > Any chance you could make an appimage of that and have it bypass whatever qt I am using? I have an old qt, but the current appimages keep depending on what _I_ have not what's _in_ the appimage.
> 
> No, sorry. I don't know how to do this.

The nitrokey people know how to fix that bug, can you ask them how they fixed it? so an appimage that works can be made? 
Also, can we stop only support the latest LTS qt5? and instead support the last two LTS qt5 builds?

**Comment by Malkierian** [comment]
Sorry to necro this, but I figured, since it's still open, I might as well, instead of creating a whole new issue.  Anyway, I really need this, as WebEngine isn't available on Raspbian.  I haven't tried building the entire system from source yet, but I have my doubts.  It's really unfortunate, though, because I need to be able to develop on my Pi remotely, and my internet provider is a reseller, so opening a port on my router for sftp connections isn't an option, and neither is LogMeIn or Dropbox (no clients for Raspbian), and Nextcloud is the only cloud sync service I've been able to find that even has a history of being usable on Raspbian (I have tried MegaSync, but it's hit or miss on the synchronization, and often takes minutes to register a change, so it's unusable for my purposes).

**Comment by FrostKnight** [comment]
Is there a way to bypass the qt5 requirements check? If so could someone tell me.

**Comment by schoelle** [comment]
webengine is not available in OpenBSD, and there are little efforts in porting the package, as the porting of Chrome already needs hundreds(!) of patches. I fully support making this dependency optional.

**Comment by theova** [comment]
Has anyone already managed to create a batch for version 2.6.1 ? @sroracle ?

**Comment by sroracle** [comment]
@cogitri adapted it for 2.6.0, but Alpine has since dropped the patch since they appear to have webengine working now. https://github.com/alpinelinux/aports/blob/5589ebabf15ac1225b9ef6ac0082fcf47601201f/community/nextcloud-client/remove-qtwebengine.patch

**Comment by Cogitri** [comment]
Yup, we've patched QtWebengine into shape

**Comment by theova** [comment]
Thank you! The patch works for 2.6.1 as well :-)

**Comment by theova** [comment]
Parabola GNU/Linux-libre includes nextcloud-client without qt-webengine. The package can be found [here](https://www.parabola.nu/packages/libre/x86_64/nextcloud-client/) and should be installable on any Arch-like distro.

**Comment by FrostKnight** [comment]
Two problems for me anyways... one I don't use openssl, i use libressl, two, is it available via appimage? 
Also, how do you install from a non pkgbuild from parabola.nu?

**Comment by sspreitzer** [comment]
I have switched from source based compiling to the AppImage version on my gentoo, because nextcloud-client pulls in the qtwebengine with its >130MB of sources. Not being able to optionally build the desktop client against qtwebengine is bad. As well as pulling in 130MB for a simple 3 step authentication mechanism is in my humble opinion disproportionate and should be changed.

**Comment by FlexW** [comment]
It's now possible to build without qwebengine.
