### ISSUE TITLE
Mac client (2.5.1) extensions work once only

### ISSUE THREAD

**Issue by thaispice** [nextcloud/desktop#936]
**Environment:**
MacOs Mojave 10.14.1
NextCloud client 2.5.1final (build 20181204)
Not set to dark mode

**Steps to reproduce:**
1. Clean install of client i.e. I used AppCleaner to hopefully remove everything and manually deleted the nextcloud directory and files
2. Installed latest client Version 2.5.1final (build 20181204)
3. Everything looks good after installation:
<img width="784" alt="screenshot 2018-12-11 at 17 02 20" src="https://user-images.githubusercontent.com/8299896/49813372-a1a1e280-fd67-11e8-9a44-7943de7dcbad.png">
<img width="487" alt="screenshot 2018-12-11 at 17 01 45" src="https://user-images.githubusercontent.com/8299896/49813447-c0a07480-fd67-11e8-8ad3-6b8ec132689d.png">
4. Reboot Mac - no extensions:
<img width="803" alt="screenshot 2018-12-11 at 17 05 37" src="https://user-images.githubusercontent.com/8299896/49813548-f6455d80-fd67-11e8-9c19-3c608ea664e9.png">
<img width="417" alt="screenshot 2018-12-11 at 17 13 16" src="https://user-images.githubusercontent.com/8299896/49813603-1543ef80-fd68-11e8-94e7-2a9672150c46.png">
5. Have attached the system.log via console for nextcloud entries

Let me know if you need anything else and thank you for your work on this

[console.log](https://github.com/nextcloud/desktop/files/2668369/console.log)

**Comment by thaispice** [comment]
FYI: I also tried installing the latest daily build (same issue)

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/nextcloud/desktop/issues/762

**Comment by claell** [comment]
@thaispice can you please confirm, whether this is a duplicate of #762?

**Comment by FlexW** [comment]
Does this issue still apply?
