### ISSUE TITLE
Moving files between a e2e folder and a regular folder

### ISSUE THREAD

**Issue by schiessle** [nextcloud/desktop#940]
Normally we trigger a webdav move if a file gets moved from folder A to folder B. This doesn't work if a E2E folder is involved. Right now we try a "move" which will result in an error.

We have two options:

# First Option

## Moving a file/folder from a E2E folder to a regular folder:

1. upload the file/folder to the new location like it was a new file/folder
2. lock the e2e folder
2. get the metadata file from the e2e folder
3. remove the moved file/folder from the metadata file
4. delete the file/folder from the server
5. upload the updated meta data file.
6. unlock the e2e folder

## Moving a file from a regular folder to a E2E folder

1. lock the e2e folder
2. get the metadata file
3. encrypt the file
4. update the metadata file
6. upload the encrypted files
7. update the meta data file
8. unlock the E2E folder
9. delete the file from the regular folder.

Basically moving between E2E folders and regular folders has to be handled as  a"delete of the old file/folder" and  a "upload of a new file/folder".

### Advantage

Works as transparent as most people expect it

### Disadvantage

We lose the file ID. That's not a problem for shares, since within a E2E folder we forbid sharing anyway. So it is even the desired behavior that it is no longer shared. But we also lose meta data like comments, etc which might be an issue as soons as people can add comments at the clients.

# Second Options

Forbid this kind of move operations and block them completely

### Advantage

Works always, no problems with changing file ID's, etc

### Disadvantage

Might be confusing for the user if the client undo move operations.

cc @tobiasKaminsky @marinofaggiana because this might or might not be an issue on mobile as well. I think on Android we solved the problem by not allowing to move files out or into a E2E folder, not sure about IOS.

**Comment by tobiasKaminsky** [comment]
> Android we solved the problem by not allowing to move files out or into a E2E folder

Yes, this is the current situation. On mobile it is a bit easier than on desktop, as you can simply forbid this…

**Comment by marinofaggiana** [comment]
Yes @schiessle  in iOS is forbid move file from/to E2EE folder, but I can copy / paste a file, this is a good and simple method for bypassed the move ;)
