### ISSUE TITLE
Using 100% CPU, unresponsive, not syncing files.

### ISSUE THREAD

**Issue by rolandixor** [nextcloud/desktop#942]
### Expected behaviour
It should run in the background normally, and when you try to open the system tray, settings, recently synced files, etc, it should work.

### Actual behaviour
It's stuck at 100% CPU on a single thread.

### Steps to reproduce
1. Run `nextcloud`.
2. If it uses the Kde/Gnome keyring, unlock it.
3. Try to do anything with the sync client - nothing happens.

### Client configuration
Client version: 2.5.1

Operating system:
Ubuntu 18.10

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
Can't get to the settings interface so I can't tell.

Client package (From Nextcloud or distro) (Linux only):
From Nextcloud.

Installation path of client:
/usr/bin

I didn't include server details as I use two different servers, one with Nextcloud 14 and the other with 15 beta, both run Ubuntu. It doesn't seem to be related to the server.

Not sure if this is useful, but this is what shows up repeatedly when running `strace nextcloud`:

stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=344, ...}) = 0

**Comment by solick** [comment]
I have the same problem with MacOS client 2.5.1.
Tried several complete fresh setups but always after 24+ hours still comparing my 56 GB and no download. Crashing and after restart client hangs. Very disappointing but at the moment nextcloud is simply not usable for me

**Comment by rolandixor** [comment]
Latest git build seems to have fixed this, so it may be fixed in the next point release.

**Comment by rolandixor** [comment]
Still getting this issue. It won't sync anything.

**Comment by rolandixor** [comment]
Still having this issue, and with the latest build in the PPA, it got so bad I had to downgrade by using the snap version. It locks up the system, and sometimes uses two threads (150% CPU!)

**Comment by faulix** [comment]
I have the same issues with Mac OS X and 2.5.1.

Debug showed me that the client went through all files to check whether they changed or not and during this it didn't respond. Don't know the programming, but is it possible that the GUI requests are added to the job list and it's just stuck with the file scanning (too many jobs)?

**Comment by valikvicious** [comment]
Strangely enough, setting `export TZ=:/etc/localtime` as per fixed the CPU utilization issue for me in 2.5.2 version.

**Comment by faulix** [comment]
@valikvicious did you change the source code or how to fix this?

**Comment by valikvicious** [comment]
@faulix 
> did you change the source code or how to fix this?

I just launched the nextcloud client from terminal as follows:
`$ export TZ=:/etc/localtime && nextcloud &`

**Comment by toweih** [comment]
Experiencing the very same problem for 2.5.1 on Debian Buster/SID - Linux 4.19.0-4-amd64 even if I set TZ like proposed above.

Reproducer:
1) running nextcloud client
2) fresh boot or going to awake from sleep
3) CPU runs up to 300% and drops back to normal as soon as the network-connection is successfully established.

**Comment by toweih** [comment]
The problem only occurs when I use an address specified in /etc/hosts. When I remove this entry (I used it to enfornce IPv4) I do not experience any problems anymore. 

Maybe the client checks for proper network-connection by looking up an IP and is going rampage when it properly resolves the IP without being able to connect to the cloud??

**Comment by manuelwallrapp** [comment]
I have the same issue 100% CPU usage on Mac Os X with NextCloud Client 2.5.3.rc2. The Client hung up, I need to kill it.

**Comment by kartoffelheinz** [comment]
Having the same problem on latest Debian Stretch. Starting the Nextcloud client using "env TZ=:/etc/localtime nextcloud" seems to fix the high CPU Usage and considerably speeds up initial syncs / syncs with lots of changed files.

**Comment by wolfspyre** [comment]
is something similar to this likely to bring any performance lift to mac / win clients?

**Comment by baermb** [comment]
> The problem only occurs when I use an address specified in /etc/hosts. When I remove this entry (I used it to enfornce IPv4) I do not experience any problems anymore.
> 
> Maybe the client checks for proper network-connection by looking up an IP and is going rampage when it properly resolves the IP without being able to connect to the cloud??

I see this issue in a fedora 30 environment.  My nextcloud client is using an ssh tunnel on localhost.  If the tunnel is down with the network up and nextcloud tries to sync, a core of the CPU gets maxed out until a tunnel is connected or Nextcloud is closed.
