### ISSUE TITLE
Feature Request: map as drive

### ISSUE THREAD

**Issue by rootbdfy** [nextcloud/desktop#945]
I think it would be really cool feature. Because webdav realisation in Windows very ugly (problems with reconnection, problems after reboots, problems on some files) - it completely unusable over wifi conection. And on linux davfs2 sometimes errors hapen (even on small files).
Getting an alternative to the [seadrive](https://www.seafile.com/en/help/drive_client/) would be nice.

**Comment by duesseldorferjung** [comment]
Good Day @rootbdfy, I was facing the same issues and wanted to raise a similar request. After looking through the open topics i tried the virtual driver feature provided in a techreview.
https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration/
Just testing it on Windows 10.

**Comment by rajo** [comment]
Hi there - does anybody know what the current state of this is? I can only find a blogpost from 2019 and the tech preview also from 2019. But no installation hints or current software release? Is this even developed currently or maybe already part of the actual software release?

**Comment by womeier** [comment]
@mgallien as I understand, this is now present in Windows and the issue can be closed.

**Comment by roberix** [comment]
Hi.

I still would find it very useful. VSF which I think @womeier is referring to as solution is not solving all use cases.

A simple map as drive function which would replace the horrible windows WEBDAV implementation would be much appreciated.

With best regards

Rob

**Comment by Rello** [comment]
Hello,
we introduced VFS for our clients into a selected sync folder. we do not support virtual drive letters at the moment.

Regards,
Marcel
