### ISSUE TITLE
selective sync tree does not show folders whose names end with a dot

### ISSUE THREAD

**Issue by mbunkus** [nextcloud/desktop#947]
The Nextcloud desktop client does not show any folder whose name ends in a dot, e.g. `Photos 2018 Jan.-Mar.`

### Expected behaviour

All folders should be visible and selectable regardless of their name.

### Actual behaviour

Only folders whose name does not end in a dot are shown and thereby selectable.

### Steps to reproduce

1. Ensure a connection is configured in the client.
2. On the server, create a folder with a dot at the end of its name, e.g. `Test.`
3. In the client, open the selective sync tree and browse to the folder. You won't be able to find it.
4. On the server, rename the folder to a name without the dot at the end of its name, e.g. `Test`
5. Restart the client, go to selective sync, browse the tree and observe that you can see the renamed folder now.

### Client configuration
Client version: 2.5.1 (but has been happening for quite some time now, over multiple client & server upgrades)

Operating system: Windows 10 Pro 1803  64-bit

OS language: US English

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
