### ISSUE TITLE
Client 2.3.3 crashes after a period without synchronisation

### ISSUE THREAD

**Issue by hjohanns** [nextcloud/desktop#948]
This is not on latest version I will move to last version and retry but it is not entirely under my control.

### Expected behaviour
Client should not crash
### Actual behaviour
Client crashes regularly, and in two instances there is the same waiting time just before it crashes.

### Steps to reproduce
1. Start client on Windows
2. Let it replicate normally
3. Client crashes at a (seemingly) random time.

### Client configuration
Client version: 2.3.3

Operating system:
Nextcloud 2.3.3 (build 1) on Windows 10
sqlite3 version "3.16.1"

OS language: French
### Server configuration
NC 13.0.6.1 on Linux 64 bits, with apache
### Logs
Crash1: Note the 2661 s right before the crash
[crash1.log](https://github.com/nextcloud/desktop/files/2682577/crash1.log)
Crash2: Note the 2661 s right before the crash
[crash2.log](https://github.com/nextcloud/desktop/files/2682579/crash2.log)

Isn't it strange that the crash occurs twice when a particular wait limit is reached? 
If I am correct, 2661s counted in 10th of millisecond would reach 31bits of length, so if there is a signed 32 bits integer in the code, it would overflow. Is there a way to check this in the code? Or if someone has an idea of the code area I can check myself without having to learn large portions. 
Thanks for any suggestion, hj

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
