### ISSUE TITLE
macOS sync client (only) yields error when userID contains spaces (NC13, current sync client for macOS)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/desktop#949]
On a current NC13, I CAN use userIDs with spaces without issues. I also CAN use such users on Windows, Linux and Android NC sync clients. Not so in macOS, at least not if 2FA (TOTP) is active:

If used with username/password/TOTP, then the client hangs(!) after having entered the token in the embedded "Grant access" workflow. If used with username/app-pin the login succeeds but I end up here:
![image](https://user-images.githubusercontent.com/8425483/50046446-ab974e80-00a3-11e9-9896-4bfb5ca53b00.png)

What's weird here is that none of my clouds uses the path "/nextcloud" which is contained in the error message. So, this looks like the client searches for default paths. Correct would be /nc in this particular case.

While I captured the client log (see below) I got this error message in the Terminal:
objc[9116]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9e7b4210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x13bd2ddc8). One of the two will be used. Which one is undefined.

I am happy to provide a test account for the devs here, please pm me if that would be helpful.

### Client configuration
Client version: Version 2.5.1final (build 20181204)
Operating system: macOS 10.14.2
OS language: German
Installation path of client: Applications ;-)

### Server configuration
Operating system: debian 8.11
Web server: Apache 2.4.10
Database: MySQL 5.5.62
PHP version: 5.6.38
Nextcloud version: 13.0.8
Storage backend (external storage): internal

### Logs
1. Client log: I use gist for the first time, so I hope that's correct in this way:
https://gist.github.com/nursoda/26cb90cdaff5a8b519dd538a78a891e8
2. Web server error log: empty
3. Server logfile: empty

### Related bugs
This issue MIGHT be related to these bugs:
https://github.com/nextcloud/desktop/issues/279
https://github.com/nextcloud/desktop/issues/934

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
