### ISSUE TITLE
0xc000007b

### ISSUE THREAD

**Issue by merkleID** [nextcloud/desktop#951]
Hi.
Simply put, NC crashes every time I try to start it and exits with error code 0xc000007b.
This happens since I updated from 2.3.3 to current 2.5.1
I tried to reinstall Visual C++ libs but had no effects.

System: 2008R2

Thanks,
Luca

**Comment by Joshbwr** [comment]
Ran into the same issue. Did you find a fix?

**Comment by lucaonelogin** [comment]
Not yet.
Tried almost everything with VB libraries and other stuff.
Waiting for a 2.5.(x>1) version to see if works.

**Comment by maxxer** [comment]
2.6.5 still happening, on Win7
