### ISSUE TITLE
Initial setup of windows client - / leads to unclear error

### ISSUE THREAD

**Issue by fl2ma** [nextcloud/desktop#952]
### Expected behaviour
Prompt for username/password.

### Actual behaviour
Error message "server couldn't complete request"

### Steps to reproduce
1. Installed client and entered self-hosted domain for Login in format:
https://domain.tld/nextcloud/
2. Press 'next'

### Client configuration
Client version:
2.5.1final (build 20181204)

Operating system:
Windows 10 64bit

OS language:
German

Installation path of client:
D:\Programme

### Server configuration
Nextcloud version: 15.0.0

Storage backend (external storage):

### Summary
If you end your domain with "/" (e.g. https://domain.tld/nextcloud/) it ends with an undescriptive error message. If you leave it out (https://domain.tld/nextcloud) it works perfectly fine.
Suggestion: if domain ends with /index.php, that part gets automatically cropped, maybe that's possible for / too?

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
