### ISSUE TITLE
Nextcloud Client 2.5.1 uses wrong URL after Setup

### ISSUE THREAD

**Issue by thelaoshi** [nextcloud/desktop#953]
### Expected behaviour
Nextcloud Client successfully added the account

### Actual behaviour
after login/pass nextcloud client reports 404 errors, because it tries to use a wrong url
My server is hosted in a subpath on the server like www.domain.de/nextcloud.
The client connects to the instance and then asks (as expected) for username/token.
But after entering the data the client looses the connection and in the server logs I can see, that the client tries to use URLs like www.domain.de/ withour the nextcloud path.
Then of course the client throws 404 errors, because its the wrong URL.

With the "old" 2.3.x. client the same thing works perfectly well.

### Steps to reproduce
1. add account
2. enter username / token
3. finish

### Client configuration
Client version: 2.5.1

Operating system: Windows 10 Pro

OS language: German

Installation path of client: default

**Comment by alerque** [comment]
I've been trying to trace something that might be related to this. It's hard because my client is persistently crashing (ala #941), but I keep noticing in my server logs that the crashing clients are trying to use URLs that look like:

    https://domain.tld/remote.php/dav/files/<username>

and are met with 404's, while working clients seem to use UUID's instead like this:

    https://domain.tld/remote.php/dav/files/<user_uuid>

Are you sure your 404 errors are due to the base path and not this?

**Comment by lexelby** [comment]
I found a workaround:

1. Go through the initial setup wizard.
2. Nextcloud will tell you it can't connect (and display the wrong url).
3. Quit Nextcloud.
4. Edit `~/.config/NextCloud/nextcloud.cfg` and fix the URL
5. Start nextcloud again.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
