### ISSUE TITLE
Ubuntu 18.10 Gnome GUI some status button doesn't works

### ISSUE THREAD

**Issue by Herlderlord** [nextcloud/desktop#955]
Hi,
Sorry for my english, I will try to exprime myself as best i can. 

### Expected behaviour
When i click on "Ouvrir Nextcloud dans le navigateur" (en: open nextcloud on the navigator) or on "Ouvrir le dossier local 'Nextcloud'" (en: open the local file 'Nextcloud') i would like this works well and open the link or the file on the corresponding software - default navigator or default file explorer. Theses buttons are on the menu of the nextcloud's status icon on the right of the Gnome GUI's top bar.

### Actual behaviour
When i click on one of them, nothing happens. The same for "Aide..." button (Help). However, it works well for "Paramètres..." button (Settings)
 
### Steps to reproduce
1. Open the Logs Catcher (https://docs.nextcloud.com/desktop/2.3/troubleshooting.html)
2. Click on the nextcloud's icon on the top/right of ubuntu
3. Click on "Ouvrir Nextcloud dans le navigateur" or "Ouvrir le dossier local 'Nextcloud'"

### Client configuration
Client version: 2.3.3+gitab40efe (from Ubuntu store)

Operating system: Ubuntu 18.10

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): How can i know it ?

Client package (From Nextcloud or distro) (Linux only): ?

Installation path of client: /usr/bin/nextcloud-client ???? I've just installed it using the default software of Ubuntu (market ? Store ? I don't know how to call it). 

### Server configuration

Operating system: Ubuntu 18.04

Web server: httpd apache2 (docker image)

Database: default sqlite

PHP version: 7.2.13 (cli)

Nextcloud version: docker run nextcloud, i suppose it's 15. 

Storage backend (external storage): ... ?

### Logs

1. Client logfile: 
https://gist.github.com/Herlderlord/a98ebc8febddc13d2d5bc94bd64f4a15 

2. Web server error log: Where is the file on my docker container ? 

3. Server logfile: nextcloud log (data/nextcloud.log): nothing in /var/www/html/data/nextcloud.log (on my docker)

PS: I know there's close opened issues but i don't master enough english to understand if they're talking specifically about the same issue or not. 

Best regards.

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
