### ISSUE TITLE
Installer forces Windows reboot without prompting

### ISSUE THREAD

**Issue by jernejs** [nextcloud/desktop#956]
### Expected behaviour
Installer prompts for reboot if needed

### Actual behaviour
Windows reboots without warning

### Steps to reproduce
1. Run Nextcloud-2.5.1-setup.exe and proceed through the Setup wizard
2. while the installation is in progress, Windows suddenly reboots

### Client configuration
Client version: 2.5.1

Operating system:
Windows 10 x64 1809

OS language:
Slovenian

Installation path of client:
default

I suspect the reboot is triggered by the VC runtime installer.

**Comment by marcbritten** [comment]
This just happened to me the other night when I installed.  I was no prepared

**Comment by maltehi** [comment]
Same here! Also using those Nextcloud and Windows versions (except for the language). Happened three out of three times.

In one of the cases the reboot was actually triggered but then blocked by the Nextcloud installer itself, according to Windows, and the installation finished. Only in that case I had also used an account with admin privileges to log in while another regular account was still active in the background. Not sure if it's related.

**Comment by michaelstingl** [comment]
duplicate for https://github.com/nextcloud/desktop/issues/831 ?
