### ISSUE TITLE
Segmentation fault on sync

### ISSUE THREAD

**Issue by adrian-amaglio** [nextcloud/desktop#958]
### How I installed my client
1. copied the .conf/Nextcloud folder from working installation to new one
2. Installed the nextcloud-client archlinux package
3. started nextcloud client
4. The account are not logged in and loging in trigger a segfault
5. I deleted the .conf/Nextcloud folder and reinstalled the package
6. tried to reconnect manually
7. Still segfault

#### With a non empty local folder
1. Start Nextcloud client
2. Add a new server
3. Login to the server
4. Choose what to sync
5. Choose to do a clean sync (remove local content)
6. validate
The synchronisation screen appears for half a second and the nextcloud client do a segfault but have erased my local content.

#### With an existing database but not connected
1. On the "Account access" screen clic connect with app token
2. Enter username and token
3. Press login
Segfault

#### With an existing database but not connected
1. On the "Account access" screen, enter credentials
2. Clic connect with login
3. The login connection fail (because server config is broken)
4. The "Account access" screen come back for a second
Segfault

### Try and retry
After about 10 connection try. The synchronization screen appears but cant connect, and eventually, the login screen pops up.

### Client configuration
Client version: 2.5.1git

Operating system: Archlinux up to date
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 5.12.0
Client package (From Nextcloud or distro) (Linux only): nextcloud-client arch package
Installation path of client:

### Server configuration

Operating system: debian 8 and not to date at all
Web server: nginx as reverse proxy to official docker image (apache+nextcloud)
Database: postgresql
PHP version:
Nextcloud version: 13.0.0.14
Storage backend (external storage): local files

### Logs

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`

[client output on terminal](https://gist.github.com/adrian-amaglio/87d8dc305cea9921c8b0af530998e109 )
[Logfile (--logfile)](https://gist.github.com/adrian-amaglio/3515878366f3b51305e9b091a735dcd1 ) Just have replaced the server name by `nextcloud-server.com`.

**Comment by yan12125** [comment]
The Arch Linux nextcloud-client package is updated to 2.5.1-2 today. In this version a potential crash is fixed. You may want to try it out.

**Comment by adrian-amaglio** [comment]
It is fixed ! Thank you for your work. :)
