### ISSUE TITLE
Sync scheduling

### ISSUE THREAD

**Issue by cybexr** [nextcloud/desktop#96]
Some working dir is under frequently read&write, NC-client will always do checking and uploading, it's unneccessary some times . 
Add scheduled-time synchronization feature to NC-client will make it more kindly.  :-)

**Comment by stratege1401** [comment]
Yes, i agree.

I use the synch feature to save EBP and LAW folder to my nextcloud server.
Unfortunately, during business hours ( eg 10h-23h ) those software are in use, and there is a lot of read/writes access due to their specific DB management and files backups.. The sync app is simply trying to cop with them and kept trying to transfert files who are changing every few seconds.
I would love to be able to schedule synch between 01h to 08h only. 

This is a must have enhancement for pro peoples !

-- if possible.

Thanks

**Comment by ickyfeet** [comment]
This would be tremendous.  We have live events at remote sites and have had nextcloud clobber the live stream because of syncing.  Being able to schedule when nextcloud syncs would be fantastic.

**Comment by Windyo** [comment]
Bumping this request as well :)

**Comment by camilasan** [comment]
There is this PR open #1453 that should cover it.

**Comment by tomdereub** [comment]
It seems that this feature request is doubled : https://github.com/nextcloud/desktop/issues/96. It's maybe better to close one to keep just one discussion ?
Too bad that @esguti 's PR is closed and not continued, we're really waiting for this feature for professional usage.
An other feature close to this one that could be really useful to reduce bandwidth usage, when some files are changed very often : be able to launch one shot synchronization. I'll describe my use case to show the differences and interest of this : 

In my organisation, we are sometimes working on big files (building BIM models), that can reach up to 1 Go. We save the file quite often (every 5 to 10 minutes), so if we let the client run, it will try to upload 1 Go every 5 minutes and then download it on every computer that's synchronizing this file (could be 5 other persons working on the same project). So a huge and unnecessary bandwidth usage. To avoid this I see 2 solutions : 
- **scheduled time synchronisation** proposed in this feature request : you set period of time when the client sync. I can set for example 8 to 9 am and 5 to 6 pm, so it won't synchronize during the day, it's already much better. But during sync time, it will sync continuously, so if I'm working on this kind of file I still have the problem. And if the synchronisation is not finished in one hour, it will stop incomplete.
- **one shot sync** : 2 ways : manual or scheduled : 
     -» manual : just suspend all syncs, and with a right click on the icon, be able to launch a one shot complete synchronisation. The client sync one time every folder pair, and the suspend synchronization again. This full sync could last 5 minutes or 5 hours, no matter, depending on what's to synchronize and connection speed, but it will make a complete sync.
     -» automatic : be able to schedule one shot synchronisations : for example, I want the client to sync one time at 8 am and one time at 6 pm. Or to make one full sync every hour, etc..., but between 2 sync it stays suspended.

For now we are managing it manually (suspending sync and reactivating it some times), but it's far from optimal, and if many people forget to suspend, it can saturate the server.

I'm no dev, but if I can help in some way (could be financially), just tell me.

**Comment by Deckweiss** [comment]
For anybody who is looking for a workaround in the meanwhile:

I have created a bash script that parses the nextcloud config and syncs all folders via `nextcloudcmd`. So you can setup everything from the nextcloud desktop client, then close it and run my script when you want to sync everything. https://github.com/Deckweiss/Nextcloud-Oneshot-Sync

!!Only works on `Linux` and with the nextcloud desktop client connected via `KDE-wallet` !!

**Comment by Rello** [comment]
I am closing this as this is currently not planned based on customer demand

**Comment by Windyo** [comment]
?
I mean you can close this but "completed" I don't think so. 
The lack of customer demand is mostly because you guys have made clear that asking anything is shouting at the wind. 
Just mark Amit as won't fix or something, because otherwise anyone looking at issues searching for this will think it's done when it isn't. 
Ticket statuses have meaning.
