### ISSUE TITLE
Sync client 2.5.1 (ubuntu) cannot create connection to local IP 

### ISSUE THREAD

**Issue by HATEthePLOT** [nextcloud/desktop#960]
When creating a new connection in the NC Sync Client (version 2.5.1; ubuntu 18.04; installed from ppa advertised by nextcloud homepage), internal IPs stall the setup process. Where I expect the window to enter user credentials, only a grey background appears. 
When entering the FQDN of my server, everything works fine.

### Expected behaviour
After entering my server's internal IP (e.g. 192.168.1.2/nextcloud) I would expect a window to type in login data.

### Actual behaviour
After entering my server's internal IP (e.g. 192.168.1.2/nextcloud), a click on "next" brings be to an empty, grey page. I cannot enter user credentials.

### Steps to reproduce
1. Create a new connection to an internal IP
2. Click next
3.

### Client configuration
Client version: 2.5.1

Operating system: Ubuntu 18.04

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): not displayed in Settings dialog

Client package (From Nextcloud or distro) (Linux only): ppa:nextcloud-devs/client

Installation path of client:

### Server configuration

Operating system: ubuntu / ubuntu

Web server: ubuntu server 18.04

Database: MariaDB 10

PHP version: 7.2

Nextcloud version: 14.0.4

Storage backend (externa storage): none

### Logs

[OCC::AccessManager::createRequest 	2 "" "https://192.168.1.175/nextcloud/status.php" has X-Request-ID "34d30204-4b3a-4fa2-9c3d-53ee0d7812fc"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://192.168.1.175/nextcloud" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::SslErrorDialog::trustConnection 	SSL-Connection is trusted:  true
[OCC::Account::slotHandleSslErrors 	"SSL-Errors happened for url  \"https://192.168.1.175/nextcloud/status.php\" \tError in  QSslCertificate( DELETED BY THREAD INITATOR ) \n " Certs are known and trusted! This is not an actual error.
[OCC::CheckServerJob::finished 	No SSL session identifier / session ticket is used, this might impact sync performance negatively.
[OCC::CheckServerJob::finished 	status.php returns:  QJsonDocument({"edition":"","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"Nextcloud","version":"14.0.4.2","versionstring":"14.0.4"})   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x55d024a72ce0)
[OCC::DetermineAuthTypeJob::start 	Determining auth type for QUrl("https://192.168.1.175/nextcloud/remote.php/webdav/")
[OCC::AccessManager::createRequest 	2 "" "https://192.168.1.175/nextcloud/remote.php/webdav/" has X-Request-ID "e159cdc1-3255-472d-b1a5-79fc1be4e22a"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://192.168.1.175/nextcloud" + "" "OCC::Account"
[OCC::AccessManager::createRequest 	6 "PROPFIND" "https://192.168.1.175/nextcloud/remote.php/webdav/" has X-Request-ID "68c91e5b-841f-4238-b469-e3113cd9ba25"
[OCC::AbstractNetworkJob::start 	OCC::SimpleNetworkJob created for "https://192.168.1.175/nextcloud" + "" "OCC::Account"
[OCC::Account::slotHandleSslErrors 	"SSL-Errors happened for url  \"https://192.168.1.175/nextcloud/remote.php/webdav/\" \tError in  QSslCertificate( DELETED BY THREAD INITATOR ) \n " Certs are known and trusted! This is not an actual error.
[OCC::DetermineAuthTypeJob::checkBothDone 	Auth type for QUrl("https://192.168.1.175/nextcloud/remote.php/webdav/") is 3
[OCC::WebViewPage::initializePage 	Url to auth at:  "https://192.168.1.175/nextcloud/index.php/login/flow"
[unknown 	Uncaught ReferenceError: jstProcess is not defined

**Comment by earth08** [comment]
me too have same problem,
i cannot connect my nextcloud client with nextcloud server on local ip.
please someone confirm it and please review this problem.

**Comment by natrius** [comment]
Got the same, maybe this is related? Check out: https://github.com/nextcloud/desktop/issues/888

**Comment by tommyhlw** [comment]
same issue
wrote my solution here https://github.com/nextcloud/desktop/issues/863#issuecomment-468027666

**Comment by natrius** [comment]
@earth08 @tommyhlw @AlNotSteve @debarshiray @6i6i @pemuelle79 

For some reason i just found out when i drop a local IP there to connect to my server it automatically adds https:// in front. I now just deleted the s so its **http://** and i could finally proceed to log in again, permit firefox login and now its working again. I was able to log in with firefox all along. Maybe you guys check that out too.

**Comment by HATEthePLOT** [comment]
No, Sync-Client refuses to connect nonetheless.
In windows 10 with Client 2.5.0 I get an error message 

> Diese Website ist nicht erreichbar
> Die Webseite unter https://192.168.1.175/nextcloud/index.php/login/flow ist möglicherweise vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben.
> ERR_CERT_COMMON_NAME_INVALID

(Own translation:)

> This website is not available
> The website under https://192.168.1.175/nextcloud/index.php/login/flow possibly is not reachable or it has been moved permanently
> ERR_CERT_COMMON_NAME_INVALID


Has there been, at some point, a change to the client that it refuses to connect if the SSL-certificate does not check out correctly? I am asked to add an exception for the certificate (that is created for my FQDN) which I allow.

**Comment by HATEthePLOT** [comment]
> 
> 
> same issue
> wrote my solution here [#863 (comment)](https://github.com/nextcloud/desktop/issues/863#issuecomment-468027666)

Does not work either

**Comment by camilasan** [comment]
Hi! Could you try the latest RC https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.2.20190205-rc1-x86_64.AppImage? Thanks!

**Comment by HATEthePLOT** [comment]
> Hi! Could you try the latest RC https://download.nextcloud.com/desktop/prereleases/Linux/Nextcloud-2.5.2.20190205-rc1-x86_64.AppImage? Thanks!

This RC solves the problem. Thank you. When will it be stable?

**Comment by camilasan** [comment]
@HATEthePLOT this week. thanks for testing it. I will close the issue then.
