### ISSUE TITLE
Proposal: sensible handling of user profile data

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/desktop#962]
There really should be a sensible, systemic way of handling user profile data (folder sync connections, settings, ignored files list, etc.).

1. The installer should make sure it doesn't remove profile data, or ask the user explicitly and do so only with consent.

2. The installer or the client should anticipate the presence of profile data from any previous versions and import/accommodate it without the loss of any information or features.

3. The client, before attempting to import, overwrite or modify anything, should make a backup of the profile data.

4. Problems upon importing the profile data should be communicated to the user and they should be advised to revert to the previous version, mentioning that they can also proceed if they don't mind the loss of their data.

5. The client should make regular backups of the profile data to a folder that is removed only by explicit user consent upon uninstallation.

6. The user should be able to import and export their profile data in a compact way (see [Mozbackup](https://sourceforge.net/projects/mozbackup/)).

**Comment by rwat1** [comment]
ABSOLUTELY!

over 150GB of my key photos (wedding photos) and key documents (all my class documents for school) was all WIPED from my computer. I was freaking out, losing my mind, and thank goodness I could re-download them all,but the FOLDER sync configuration files is ALL messed up, I don't even know if the folder sync configuration is set up correction.

Now onwards to 48 hours of downloading my files again. Need to do the same with my parent's 300GB worth of files too, holy crap this is a disaster.

**Comment by leafcutterant** [comment]
Sorry for your loss, comrade. I think Nextcloud has been making great progress on the web-side, but the desktop client, and in many aspects, the mobile client as well is a huge let-down. I'm seriously considering moving away from this platform, though not sure what would be a good alternative.

**Comment by leafcutterant** [comment]
As you could read in my issue #963, that very upgrade was what caused profile data loss for me and inspired this proposal.

This far, no response from Nextcloud on either issue. I didn't get a solution or dev attention or any of my issues in this repo. I can't find it now but somewhere the support personnel wrote that when they deal with the desktop client, they focus their support to business clients and not regular users. I find this somewhat infuriating because I'm on a paid plan at my provider.

**Comment by hirkah** [comment]
>     1. The installer should make sure it doesn't remove profile data, or ask the user explicitly and do so only with consent.

The user should be asked to remove or keep profile data. I uninstalled and reinstalled and was surprised that profile data was still there.

**Comment by leafcutterant** [comment]
@hirkah so be it! I'm all for more user freedom.

My formative experience has been that I lost data, thus the approach.  I agree with giving the user the option to delete, but the default/encouraged option should be to keep it. Easier to avoid irreversible problems that way.

**Comment by Rello** [comment]
The client has improved a lot since the ticket was opened.
If it is still relevant, please create a fresh ticket.
Thank you for your support
