### ISSUE TITLE
Updating from 2.3.3 to 2.5.1 loses folder sync connections, settings and ignored files list

### ISSUE THREAD

**Issue by leafcutterant** [nextcloud/desktop#963]
What the title says. Always have backups, folks.

I expand on this issue here: #962

### Client configuration
Client version: 2.3.3 b1, 2.5.1

Operating system: Windows 7

**Comment by rwat1** [comment]
I LOST over 150GB of files, all deleted from my computer for absolutely no reason. Now I need to re-download all these key critical files. It's SUPER weird.

What happened??? I am super super disappointed, it just happened random. Thank god I can re-download them, but I have no clue if the folder sync connections are working correctly.

**Comment by leafcutterant** [comment]
@rwat1 no, my probllem was different as you can see in the title, and  the folder sync connections, settings and ignored files list still disappear when you upgrade from 2.3.* to 2.5.*.

But don't sweat, Nextcloud devs don't give a single flying [fuck](https://github.com/nextcloud/desktop/issues/677) what [problems] (https://github.com/nextcloud/desktop/issues/673)users [report](https://github.com/nextcloud/desktop/issues/632). Right, @camilasan? I guess if I would go to the forum and beg on my knees or harass the living shit out of them, then *maybe* they would be willing to take a look at it, but I'm absolutely positive they wouldn't spend more than 5 minutes  before dismissing the issue to oblivion.

Because, you know, devs are busy people, they need to focus on [integrating machine learning-based security](https://nextcloud.com/blog/nextcloud-16-introduces-machine-learning-based-security-and-usability-features-acl-permissions-and-cross-app-projects/) into Nextcloud, they don't have time for frills like ensuring the basic functions of the desktop client.

This might sound harsh to people like you and me who poured so much money into Nextcloud paid plans that I wouldn't feel comfortable discussing it publicly, but when you're the flagship file sync solution of the whole world of open source software, you've got to have priorities and stick to them. If you don't, people won't use Nextcloud, they will return to Google Drive and Dropbox, and that's something to avoid, at all costs.

**Comment by freechelmi** [comment]
Just came along this issue on W10.
@leafcutterant : please mind your way of talking , we are on free software project here, either propose a PR or buy a subscription.

I understand why 2.5.X needs to reauth the user ( POST login flow) but why it does not try to migrate the old user settings ?

**Comment by leafcutterant** [comment]
> or buy a subscription.

As I've said, I've been on a subscription for years. Also, I don't think you should evaluate someone's reasoning based on how much money they paid.

**Comment by freechelmi** [comment]
Sorry, as you bought a subscription I understand your anger.

I meant that fixing bugs priority is not always easy to decide.

I'm also affected by this problem as we are stuck on 2.3.X client for now because of that

**Comment by knezi** [comment]
I encountered a similar issue. All connections but one disappeared. However, the connections stayed in `nextcloud.cfg` and restarting the app one connection is restored (such that, on second run, there are two connections, then three...)

All previously synced files are present, but  they are downloaded again.

I can provide logs if wanted.

I'm on Arch Linux, x86, it happend after upgrade from 2.6.5 to 3.0.1.

**Comment by camilasan** [comment]
It has been fixed. See #2279.
