### ISSUE TITLE
Unreasonable CPU usage

### ISSUE THREAD

**Issue by zhccsd** [nextcloud/desktop#964]
### Expected behaviour
0 CPU Usage

### Actual behaviour
10%-15% CPU Usage

### Steps to reproduce
1.Start Nextcloud 2.5.1final
2.Do nothing

### Client configuration
Client version:2.5.1final
Operating system:Windows 7
OS language:Chinese Simplified
Installation path of client:C:\Program Files (x86)\Nextcloud

### But
If i open "Add User" window,select "Apply from provider",wait for the web page loaded,then CPU usage became 0

### Guess
Then i guess this might be the same QtWebengine issue i meet before.
Unfortunately i didn't find any useful information about that issue.
The only thing i find is:If you used QtWebengine in app but not realy show it ,you get high cpu usage.

### Here is my approach
create a window,and in its constructor:
```
setWindowFlags(Qt::FramelessWindowHint | Qt::WindowMinimizeButtonHint);
setAttribute(Qt::WA_TranslucentBackground);
setFixedSize(1, 1);
QWebEngineView *view = new QWebEngineView(this);
view->setVisible(false);
view->load(QUrl("about://blank"));
connect(view, &QWebEngineView::loadFinished, [&]()->void
{
    hide();
});
```
Then it did the trick.

Hope this helps

**Comment by kobuki** [comment]
I also have this issue on Win7 x64. Seeing that this issue is more than 6 months old and there's no patch, what is the recommended course of action? Use an older client? Wait for a release with a fix?

**Comment by ksv82** [comment]
In 2.5.2git (build 20190319) on win7 x64 same behavior.

**Comment by tobizviz** [comment]
Same behavior here using Qt version 5.11.1 and Nextcloud client version 2.5.2

**Comment by kobuki** [comment]
For the time being I downgraded my client to the 2.3.3 build 1 version where the problem doesn't exist. It's a bit sad that the current client seems a bit abandoned.

**Comment by danaivehr** [comment]
@zhccsd thank you for a workaround 

> "Add User" window,select "Apply from provider",wait for the web page loaded

It helps me.

Though It is sad, that for a year this bug still stays in code.

**Comment by kobuki** [comment]
> "Add User" window,select "Apply from provider",wait for the web page loaded

@danaivehr could you help me with this setting please? Where can I find it? Web GUI, or in the desktop app settings? I can't figure out.

**Comment by danaivehr** [comment]
@kobuki open main window from tray, then click on "Account" button in the top right, select "Add", and in the opened window click "Apply from provider". Then you can just close that window doing nothing in there.

**Comment by kobuki** [comment]
@danaivehr thanks, but I see no option "Apply from provider" in the latest Windows desktop client. However, after freshly installing 2.5.3 and logging in, the problem disappeared for me, there's no more CPU hogging while the sync app sits idly. It uses 0% CPU as expected.

**Comment by kobuki** [comment]
Unfortunately the issue is back in 2.5.3. I've just checked the CPU usage of all processes and the NC client uses the CPU between 4-7% when sitting idly in the background. Maybe I'll try the 2.6.x series when they come out of RC.

**Comment by danaivehr** [comment]
I have to downgrade to 2.3.3.1, which can be found here: https://download.nextcloud.com/desktop/releases/Windows/ 

Issue is not there on 2.3.3.1

**Comment by kobuki** [comment]
@danaivehr: Yes, I have already mentioned it a few posts above yours. However that version is more than 2 years old and a lot of fixes are included in the newer versions.

**Comment by bjoernv** [comment]
If you start NC with `nextcloud --logwindow` the log windows shows nearly constant activity for shares with some thousand files. The user would expect, that the client sleeps between two synchronization runs.

**Comment by kobuki** [comment]
The latest 2.6.1 client still uses around 4-5% CPU when idling and sitting in the tray which is not acceptable for an idle client. Please do something about it. It's a 4-core i7 processor. I can only imagine what happens on smaller ones.

**Comment by samsk** [comment]
Still the same on latest 2.6.2, but after Account->Add new->Register...->Close the load goes to ~0 from constant 6-7% before. Funny&Annoying bug.

**Comment by Addy771** [comment]
Still happening on 2.6.3 and windows 7 64-bit

**Comment by Addy771** [comment]
Still happening with 2.6.4 client. 7-8% CPU usage constantly. 

When I use the "Register with provider" workaround, CPU usage is down to 0-1%.

**Comment by kobuki** [comment]
Funny. It has escaped my attention before, but I can confirm that the aborted registration does work as workaround. CPU usage is practically zero when the client is idle. It should not be that hard to fix...

**Comment by camilasan** [comment]
I see this issue as an outdated version of #2379.
