### ISSUE TITLE
Can't upload large file "connexion closed"

### ISSUE THREAD

**Issue by iniOr** [nextcloud/desktop#966]
### Expected behaviour
Sync a 400+ mb file

### Actual behaviour
Sync fails throws error "filename: connexion closed"

### Steps to reproduce
1. Copy a 400+ mb file into a folder
2. Nextcloud client begins upload then go backward (progress bar)
3. Throw error "connexion close"
4. No issue at all with 2.3.3

### Client configuration
Client version: 2.5.1

Operating system: Linux Mint 19.1

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 2.5.1 git

Client package (From Nextcloud or distro) (Linux only): ii  nextcloud-client                                                 2.5.1-20181204.111806~bionic1                               amd64        Nextcloud desktop sync client

No issue at all while using 2.3.3 so server is out of scope.

Client log: https://pastebin.com/Dj3qyz32

**Comment by iniOr** [comment]
issue is present since 2.5.0.

**Comment by nonamedotc** [comment]
I have since tried adjusting my server settings with PHP-FPM. No change in behavior. Client version 2.3.3 works, 2.5.x does not work.

**Comment by iniOr** [comment]
Hi, on my side it was a server-side issue that prevented upload of larges files.
