### ISSUE TITLE
defer sync until file access?

### ISSUE THREAD

**Issue by marcbritten** [nextcloud/desktop#968]
I was wondering if it was possible to enhance the desktop client to allow you to specify "don't sync until I try to use the file" for folders.   An addition to the low disk space feature set.

I have a somewhat large shared folder on our nextcloud server that holds a lot of business documents.  I have a laptop that has a smallish SSD.  And while I don't always need these files, when I do its preferable that I access them easily.

Right now I uncheck it in the client config and access everything through the web, which is cumbersome (download, edit, upload).

This would be kind of the opposite of OneDrives "always keep on this device" menu option.

Thanks for the great software.

**Comment by camilasan** [comment]
We have implemented it: https://help.nextcloud.com/t/help-test-our-desktop-client.
