### ISSUE TITLE
QT Session manegament error

### ISSUE THREAD

**Issue by mmartinortiz** [nextcloud/desktop#97]
## Details

- Ubuntu 17.10 using Wayland
- Nextcloud version 2.3.3 (Installed via snap)
- Using Qt 5.5.1, built against Qt 5.5.1
- Using 'OpenSSL 1.0.2g  1 Mar 2016'

## Terminal Output

```
Qt: Session management error: None of the authentication protocols specified are supported
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.243\" (uid=1000 pid=25764 comm=\"nextcloud \") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=952 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
QNetworkManagerInterface::QNetworkManagerInterface(QObject*) nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.243\" (uid=1000 pid=25764 comm=\"nextcloud \") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=952 comm=\"/usr/sbin/NetworkManager --no-daemon \")"
"Object path cannot be empty"
Gkr-Message: secret service operation failed: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.394" (uid=1000 pid=25764 comm="nextcloud ") interface="org.freedesktop.DBus.Peer" member="Ping" error name="(unset)" requested_reply="0" destination="org.freedesktop.secrets" (uid=1000 pid=1921 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")
```

## Steps to reproduce

1. Install nextcloud-cient via snap
2. Open the client and configure your nextcloud account
3. Sleep the computer
4. Awake from sleep

The same issue happens if I restart the computer.

**Comment by daniellandau** [comment]
I have the same issue, but Ubuntu 16.04 with XFCE, no Wayland. Also client installed via snap.

I get the prompt for a password, after which the Nextcloud icon appears in the system tray, but I don't get the main window at all. On first run after installing I did get the main window, but now it is totally unusable as the window doesn't open.

**Comment by daniellandau** [comment]
Hmm, if I hit cancel on the password prompt, I do get the main window. From there I can log in and change settings.

**Comment by daniellandau** [comment]
Ping @kyrofa

**Comment by mbernasocchi** [comment]
same here. on ubuntu 17.10 with gnome and X

**Comment by CaptPicardFR** [comment]
nextcloud-desktop
same here for debian 10 with xfce, installed via official deb or also by zesty or bionic. 
ok with session unroot but not validating credential who use web interface (counter to nextcloud-client on debian 9 without problem who use a applicatif field to fill)  freeze in loop without fully validating

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
