### ISSUE TITLE
Win Desktop does Copy Folder after Move Folder in Web UI

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/desktop#973]
### Expected behaviour
In the Web UI, I move a folder. I expect the folder to sync properly and move to the new location within my Win Desktop.

### Actual behaviour
First, the Win Desktop throws an error, unable to sync. Then it seems to recover itself and starts syncing. It does a copy rather than a move. I am showing both folders, the original location and the new location. I check the Web UI and only see the files in the new location. The Web UI did Move the files correctly. What's worse is the Win Desktop is showing the files from the original location with green check mark, yet the files do not show up on the Web UI. So now I have 2 copies on my desktop with green check marks and only a single copy in the Web UI. 

### Steps to reproduce
1. Have some folders on Win Desktop that are synced with green check marks
1. Move a folder From Photos to Documents within the Web UI. Both of these folders are properly synced in Win Desktop showing green check marks.
2. The folder moves correctly in Web UI
3. The Win Desktop throws error, then does a Copy rather than a Move. 
4. Web UI shows only one folder. The one moved to a new location. 
5. The Win Desktop shows both folders. The folder in it's original location and the folder in the new Moved location. Both with green check marks.

### Client configuration
Client version: 2.51 latest

Operating system: Win 10

OS language: 

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only): 

Installation path of client:

### Server configuration

Operating system:

Web server: nginx

Database: mariadb

PHP version:7.2

Nextcloud version: 15

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
