### ISSUE TITLE
Segfaults after a short time

### ISSUE THREAD

**Issue by muellert** [nextcloud/desktop#974]
I am runing

ii  nextcloud-client                     2.5.1-20181204.111806   amd64 

on my Debian Stretch system. The first sync seems to succeed, but it crashes a short time thereafter.

### Expected behaviour
Tell us what should happen

No crash should occur.

### Actual behaviour
Tell us what happens instead

Nextcloud crashes a few minutes after having been started.

See this strace from such an event:

...
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 304) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 0) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\2\0\0\0\0\0\0\0", 16)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 52) = 0 (Timeout)
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 500) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 0) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\2\0\0\0\0\0\0\0", 16)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 301) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 0) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\2\0\0\0\0\0\0\0", 16)         = 8
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 49) = 0 (Timeout)
stat("/home/toni/.config/Nextcloud/nextcloud.cfg", {st_mode=S_IFREG|0640, st_size=3440, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/home/toni/.config/Nextcloud/nextcloud.cfg", {st_mode=S_IFREG|0640, st_size=3440, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/home/toni/.config/Nextcloud/nextcloud.cfg", {st_mode=S_IFREG|0640, st_size=3440, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=3687, ...}) = 0
poll([{fd=3, events=POLLIN}, {fd=5, events=POLLIN}, {fd=9, events=POLLIN}, {fd=13, events=POLLIN}, {fd=17, events=POLLIN}, {fd=21, events=POLLIN}], 6, 494) = 1 ([{fd=5, revents=POLLIN}])
read(5, "\1\0\0\0\0\0\0\0", 16)         = 8
write(5, "\1\0\0\0\0\0\0\0", 8)         = 8
+++ killed by SIGSEGV +++

### Steps to reproduce
1. $ nextcloud &
2. wait a few minutes
3. boom!

### Client configuration
Client version:

2.5.1-20181204.111806   amd64 

Operating system:

Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

OS language:

$ env|grep -i lang
LANGUAGE=en_US:en
LANG=en_US.UTF-8
$ env|grep -i lc_ 
LC_CTYPE=en_US.utf8
LC_TIME=en_US.utf8
LC_COLLATE=en_US.utf8
LC_MESSAGES=en_US.utf8
$

Qt version used by client package (Linux only, see also Settings dialog):

$ ldd /usr/bin/nextcloud|grep -i qt
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f520ccf7000)
	libQt5WebKitWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5 (0x00007f520ccb1000)
	libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007f520cc76000)
	libQt5Concurrent.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5 (0x00007f520cc6c000)
	libqt5keychain.so.1 => /usr/lib/x86_64-linux-gnu/libqt5keychain.so.1 (0x00007f520b299000)
	libQt5WebEngineWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5 (0x00007f520cc2e000)
	libQt5WebEngineCore.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5 (0x00007f5206215000)
	libQt5WebChannel.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5 (0x00007f520cc0f000)
	libQt5Quick.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007f5205e28000)
	libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007f5205a2e000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f52053cb000)
	libQt5WebKit.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5 (0x00007f5202f69000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f5202df9000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f52028c0000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f52023f1000)
	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f52012d6000)
	libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007f520cbb1000)
	libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f51f8cdc000)

Client package (From Nextcloud or distro) (Linux only):

Taken from the OpenSuse Build service:

deb http://download.opensuse.org/repositories/home:/ivaradi/Debian_9.0_update/ /

Installation path of client:

/usr/bin/nextcloud

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

https://gist.github.com/muellert/8b98b1ed765d0390d5630e48a876a84b

2. Web server error log:

nothing applicable

3. Server logfile: nextcloud log (data/nextcloud.log):

nothing applicable

**Comment by DominiqueFuchs** [comment]
Please provide information about further segfault occurences in #241 , thanks!
