### ISSUE TITLE
Missing overlay icons in fresh Windows 10

### ISSUE THREAD

**Issue by unix0r** [nextcloud/desktop#978]
Hey guys, i have installed the nextcloud client version 2.5.1 on two Windows Machines and cant see any overlay icons in the windows explorer.
I even tried it with a fresh installed Windows 10 Pro x64 Version in a virtual Machine! No icons.
![bildschirmfoto von 2018-12-26 22-45-05](https://user-images.githubusercontent.com/4679329/50457974-f2b4f780-095f-11e9-938b-ba35618e905f.png)

Tried a couple of things from this thread: https://help.nextcloud.com/t/missing-sync-icons-in-windows-explorer/6610

But its not working.

The command:
`regsvr32.exe “C:\Program Files (x86)\Nextcloud\shellext\OCOverlays_x64.dll”`

throws an "file not found" error, but the file is available in this directory.

The registry folder: (HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers) also does not contain any OC Keys:
![bildschirmfoto von 2018-12-26 22-29-30](https://user-images.githubusercontent.com/4679329/50457683-c8fad100-095d-11e9-9d78-ec6910d3bfc7.png)

The command
`reg delete "HKEY_CLASSES_ROOT\CLSID\{0960F090-F328-48A3-B746-276B1E3C3722}" /f`
also throws an key not found error.

Uninstalling Microsoft One Drive and deleting the keys in the above picture didnt bring any help.

Regarding Dependency Walker, there are a lot of dependencys missing?:
![bildschirmfoto von 2018-12-26 22-52-04](https://user-images.githubusercontent.com/4679329/50458100-e5e4d380-0960-11e9-8094-d110e8a3b397.png)

Any ideas ?

**Comment by Valiantiam** [comment]
I'm also having this issue.

![image](https://user-images.githubusercontent.com/5394853/50521077-7ddddc80-0a89-11e9-9db8-28bc4f44d454.png)

I would expect it to look like this, which is working correctly on my work PC with a synced folder I have there called "nextcloud"
![image](https://user-images.githubusercontent.com/5394853/50521110-b7aee300-0a89-11e9-9e59-7f1809c0a6ec.png)

**Comment by unix0r** [comment]
Checked the dependency of the overlay.dll with https://github.com/lucasg/Dependencies

and it says 
MSVCP120.dll
MSVCR120.dll

are missing.
Installing/Updating the visual c++ Microsoft Visual C++ Redistributable für Visual Studio 2017 in x86 and x64 didnt bring any help.

**Comment by svenb1234** [comment]
Same issue here. The client installs without any error messages but apparently fails to check whether all DLLs it depends on are actually installed.

For me not only the overlay icons are missing but the whole file manager integration, i.e. there is no nextcloud item in the context menu.

**Comment by unix0r** [comment]
> For me not only the overlay icons are missing but the whole file manager integration, i.e. there is no nextcloud item in the context menu.

On the fresh Windows 10 Installation in a virtual machine, the file manager integration (Right Click Context Menu) is also not available.
Either is the Nextcloud Shortcout in the favorites of the Windows Explorer installed.

But on another client computer, the Context Menu is available and Nextcloud is also registered as a shortcut in favorites of the windows explorer. But the overlay icons are missing!

Looking forward for some reaction of the devs.

**Comment by unix0r** [comment]
Just tested it with the older installations for windows, but the icons were still missing for me.
But, installed the owncloud client and the icons appeared also for the nextcloud folder!

Maybe, because the nextcloud client is more or less new, most users are upgrading from the owncloud client to the nextcloud client. And not that many new installations with the nextcloud client are happening directly. So there are not so many users getting this issue with missing icons, because of another installed software (nextcloud/owncloud client) that provides the icons.

Maybe some issues in the installer packaging process for windows?

**Comment by jstdoit** [comment]
I'm suffering the same problem too...Thanks for any help.

**Comment by rullzer** [comment]
I can't trigger this on a clean VM. But I do not have a proper windows test setup to verify more in depth.

@camilasan can you have a look? Or @juliushaertl ?

**Comment by juliushaertl** [comment]
I cannot reproduce this on my running vm either, I'll try to setup a clean one.

**Comment by camilasan** [comment]
Hi! Did you reboot the machine after installing/updating the desktop client?

**Comment by unix0r** [comment]
@camilasan Of course

**Comment by jstdoit** [comment]
just install ` Microsoft Visual C++ Redistributable ` saved me.

**Comment by unix0r** [comment]
@jstdoit What exact version did you install?

On my VM these versions were installed:
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
Microsoft Visual C++ 2017 Redistributable (x64) - 14.14.26406

Just removed them, installed nextcloud-desktop-client.2.5.1 version and got 
Microsoft Visual C++ 2017 Redistributable (x64) - 14.14.26406.
But no icons.
Updated to
Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27027
and still no icons after reboot.

Also tried it with Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.23026, but still nothing happend.

**Comment by jstdoit** [comment]
I forgot the version, after add the VC++ support, then run these commands in `cmd.exe`:
```bat
regsvr32 "C:\Program Files (x86)\NextCloud\shellext\OCOverlays_x64.dll"
taskkill /f /im explorer.exe
start explorer.exe
```

remember replace the exact `OCOverlays_x64.dll`'s path for your own installation directory

Just have a try.

**Comment by unix0r** [comment]
Well, just installed 
 Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27027 and
 Microsoft Visual C++ 2017 Redistributable (x86) - 14.16.27027.

Trying to register the dll fails with:
![bildschirmfoto von 2019-03-06 13-01-17](https://user-images.githubusercontent.com/4679329/53879965-0e97e200-4010-11e9-8d2a-dcc357d6c9a6.png)

I'm running a x64 version of windows.

**Comment by jstdoit** [comment]
congrats! maybe the nextcloud's win installation package should notify user to install `Microsoft Visual C++  Redistributable ` though. @unix0r

**Comment by camilasan** [comment]
@jstdoit the thing is, our installer is supposed to install it for you, it is embedded in it. Clearly, I will have to review that...

**Comment by nfp0** [comment]
I also have this issue.
Even on a clean VM, the icons and context menus don't show up.

Running `regsvr32.exe “C:\Program Files (x86)\Nextcloud\shellext\OCOverlays_x64.dll”` yields the error bellow.

![image](https://user-images.githubusercontent.com/11202422/54074409-0a76f900-428a-11e9-90a0-131fe7f4ecbc.png)

**Comment by nfp0** [comment]
Ok, I don't know what happened, but even though I got the error in my previous post, after rebooting Windows, the icons and context menus are back.

**Comment by nfp0** [comment]
I've reinstalled the Nextcloud desktop app and after rebooting Windows, the icons and menus are back!

**Comment by stebo23** [comment]
I am using a Windows 10 Pro 64bit and I am missing the icons, too. I did a fresh install of the Client (Version 2.5.1final (build 20181204).) several times and several reboots, but it did not help.

**Comment by zfernezir** [comment]
Solved: Windows 10, fresh install, Nexcloud client 2.5.2, icons and context menu missing
Instaled ownCloud-2.5.4.11654.11466 client on the same machine. Restart. Did not start ownCloud client, but icons & context menu for Nextcloud appear.

**Comment by rkohser** [comment]
I had the same issue. Installing vcredist 2013 solved it, and enabled to properly register the shell extensions. I can see the icons now.
vcredist 2013 can coexist with 2017.

**Comment by rwat1** [comment]
@nfp0 @stebo23 @zfernezir @camilasan @unix0r @Valiantiam @svenb1234 @jstdoit @rullzer 

I found that @rkohser worked for me. So I first followed @jstdoit  by installing VC 2017:
 [Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27027](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)  and that didn't workk.....

So I followed @rkohser instruction by installing VC 2013:

[Microsoft Visual C++ 2013 Redistributable (x64)](https://support.microsoft.com/en-us/help/4032938/update-for-visual-c-2013-redistributable-package) 

YAY!! I got my icons and shell back!!! WOOT!!

**Comment by rkohser** [comment]
I just followed the track started by @unix0r, writing that MSVCP120.dll was missing.
VS2013 was supplying MSVC 12.0 compiler, so i tried its redist package.
Happy that it worked out for you.

**Comment by rwat1** [comment]
I hope everyone can also check out my new Wikipedia page on Shell Overlay Icons.

https://en.wikipedia.org/wiki/List_of_Shell_Icon_Overlay_Identifiers

There is only 15 overlay icons (4 are reserved by Windows), so effectively 11 overlay icon spaces. I made a list for everyone so they can choose which ones are most important to them.

**Comment by tux1337** [comment]
Windows handles only the first 15 overlay extension entrys. If the Registration in an admin prompt with 
`regsvr32.exe “C:\Program Files (x86)\Nextcloud\shellext\OCOverlays_x64.dll”`
was successful and the Icons does not appear after an restart of Explorer.exe, consider that you have more than 15 Icons registered. 

You Fan find an how to in this [blog post](https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/)

**Comment by rwat1** [comment]
@tux1337 Windows OS itself reserves 4 icon overlays, so effectively it's 11 overlay icons available for other programs. (15-4=11).  [Source](https://support.microsoft.com/en-us/help/3106961/registered-icon-overlay-handlers-aren-t-used-by-windows-shell)

**Comment by DJCrashdummy** [comment]
this is somehow crazy... :dizzy_face:
on a Win10x64 Pro testing VM (which never got in touch with dropbox or any other cloud-/sync-software) i installed the [`nextcloud-client`](https://chocolatey.org/packages/nextcloud-client) 2.5.2.5231 (via chocolatey.org) and neither the overlay icons nor the context menu were there. :disappointed: exacly as @svenb1234 described at https://github.com/nextcloud/desktop/issues/978#issuecomment-452582418.

- installing a bunch of different *Visual C++ Redistributable* packages didn't change anything.
- after registering the dll manually, described at https://github.com/nextcloud/desktop/issues/978#issuecomment-470078088, at least the overlay icons showed up.
- but then after installing [`owncloud-client`](https://chocolatey.org/packages/owncloud-client) 2.5.4.11415 (via chocolatey.org), as mentioned at https://github.com/nextcloud/desktop/issues/978#issuecomment-459704912, also the nextcloud context menu appeared, even without a reboot or starting the owncloud-client even once.

---

so IMHO here are at least 2 issues mixed:

1. the *overlay dropbox*-topic which is really stupid (thanks MS and dropbox! :angry:)... but i have no idea how it should/can be solved on the nexcloud side.
1. but if you are *"missing overlay icons **and the context menu** in a fresh windows 10"*, it is an *integration*-issue where you can't blame dropbox.
so please @camilasan, have a look at the owncloud-client and why it makes the nextcloud-client work as it is supposed to work, without a 2nd client i don't use/need.

**Comment by rkohser** [comment]
From the global README build instructions, it seems the client is compiled with the "Visual Studio 15 2017 Win64" cmake generator. 
But I assume from this line  
https://github.com/nextcloud/desktop/blob/v2.5.2/shell_integration/windows/OCShellExtensions.sln#L3
that the Shell Extensions are build with Visual Studio 2013, so that's why you need Microsoft Visual C++ 2013 Redistributable (x64) to make it run. 

That's why the nextcloud client needs both 2017 and 2013 redistributables. That's weird.

**Comment by DJCrashdummy** [comment]
@rkohser i was tempted to write that this does not solve the problem... but indeed it seems to do so, **if** you install the *Visual C++ Redistributables* **before** installing the nextcloud-client! :tada:
so probably the owncloud-client installer doesn't do it any better... just the nextcloud-client installer (or even both) are handling it's dependencies not correctly.

**Comment by arenaq** [comment]
I could try to install older versions, edit registers, whatever. But when I simply rebooted the computer the icons appeared and the issue was gone.

**Comment by MatthieuPERIN** [comment]
Just an update, the issue is still present when installing the 2.6.0 version on a fresh windows 10 pro 64 bits.

To be fair the "Shortcuts"/"Quick Launch Shortcut (N/A)" choice is greyed at componnent choice during the installation ... so the installer seems to know their is an issue 😄

**Comment by mr-manuel** [comment]
A fresh install of `Version 2.6.4stable-Win64 (build 20200303)` has still the same problem. No overlay icons are shown.

**Comment by nfp0** [comment]
I've just installed 2.6.4 and the icons show. I don't know what causes this.

**Comment by devel0** [comment]
Tried with win10 with nextclud-2.6.4 ; the way to make it work for me was to open at least one time the left pane explorer icon of nextcloud expanding the tree, then icons appeared and remains either after reboot
![image](https://user-images.githubusercontent.com/13405008/80695100-b35b6580-8ad5-11ea-8601-021ecff9b678.png)

**Comment by rwat1** [comment]
@everyone 

If you are experiencing issues with your shell overlay icons missing, it might be due to the fact that Windows can only support 11 shell overlay icons at a time (15 icons overall, but OS reserves 4 icons for itself). So with only 11 shell icons, you need to prioritize if you have OneDrive, DropBox, GoogleDrive, TortiseSVN, etc...

I created a Wikipedia page that lists out what Shell Icons's names, their function, for each of the services.
https://en.wikipedia.org/wiki/List_of_Shell_Icon_Overlay_Identifiers

I was able to have Shell Icons for NextCloud, OneDrive, DropBox, and Google Drive, so it fits under the 11 shell icon limit.

**Comment by kermit-frog** [comment]
[Solved] 
I had the same problem all the time. I don´t know how or why my solution worked, but it did. 

1. Download [ShellExView v2.01 - Shell Extensions Manager by Nirsoft](https://www.nirsoft.net/utils/shexview.html)
2. Search for "ownCloud overlay handler" and "OCContextMenuHandler Class" (in case context menu is missing too like it was for me)
3. Make sure all of the six (in my case) entries have the switch on "Diabled" -> "No"
4. Restart Computer

![2020-06-05 12_30_24](https://user-images.githubusercontent.com/25160261/83866782-a19a5d00-a728-11ea-9c4c-1fda1c40c872.png)

For some reason the switches were on "Disabled" -> "Yes" on my computer, so switching them on "No" and restarting the computer made the overlay icons and the context menu visible. 

Hope this helps for some of you.

**Comment by unix0r** [comment]
@kermit-frog Just tried your solution with a fresh installed Windows 10 2004 in a virtualbox.
After the installation of nextcloud, the extensions mentioned in your post were already set to "Disabled" "No".

But the problem is still there, no icons, even on a fresh installed Windows System.

**Comment by misch7** [comment]
Could you try one of our recent daily builds?
https://download.nextcloud.com/desktop/daily/Windows/nextcloud-2.7.0.15523-daily-20200611-Release.exe

I've upgraded our build system this week to use Visual Studio 2019 and now we ship the newer Visual Studio 2015-2019 combined runtime.

While debugging I noticed that this could be somehow related to the old 2017-only VC runtime.

**Comment by unix0r** [comment]
![Bildschirmfoto von 2020-06-11 17-38-29](https://user-images.githubusercontent.com/4679329/84407081-a79dab80-ac0a-11ea-850b-b5b33d7bca7a.png)

Just tried the daily build and starting nextcloud brings this error.

**Comment by misch7** [comment]
> Just tried the daily build and starting nextcloud brings this error.

That's weird, thanks for reporting. Guess I'll try to reproduce this on a fresh Win 10 VM too.

**Comment by misch7** [comment]
@unix0r It's the installer, failing to install the VC Runtime and then also failing to register the shell extension DLL responsible for handling the overlay icons.

Below are details how to manually fix it but I've already updated our installer and did a rebuild of our last daily, it worked on a fresh Win 10 VM and the overlay icons were shown after a reboot:
https://download.nextcloud.com/desktop/daily/Windows/nextcloud-2.7.0.15525-daily-20200613-Release.exe

What I did to fix it:

- After installation I did a reboot, nothing changed.
- Manually installed the VC Runtime from the NC folder:
    `C:\Program Files\Nextcloud\vc_redist.x64.exe`
- NC works but overlay icons are still not shown (reboot doesn't help)
- Manually registered the DLL:
    Run `cmd` as Administrator in `﻿﻿C:\Program Files\Nextcloud\shellext`:
    `regsvr32 OCOverlays.dll`

Of course this is just a manual workaround and not to be the usual handwork ;-)

I've changed our installer script, noticed that MS changed their Runtime's filenames, like:
`vcredist_x64.exe` -> `vc_redist.x64.exe`

**Comment by unix0r** [comment]
The new installer is working. 
The icons are displayed after a reboot. 
After the reboot there is a cmd window opening and its not closing itself. But the icons are there.
Thank you :-)

Closed.

**Comment by bgeneto** [comment]
Still not working for me... using Windows 11 21H2 and Nextcloud client v3.5.4. 
Problem only solved by manually installing Visual C++ Redistributable latest from [here](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) and rebooting the PC.
