### ISSUE TITLE
Improvement for messages needed

### ISSUE THREAD

**Issue by anolting** [nextcloud/desktop#982]
### Expected behaviour
Nextcloud client 2.5.1 on Win 10 shows constantly an error message when it tries to sync an already opened file.

### Actual behaviour
For the first time to display an error message for this file is fine but not always and especially not if you have acknowledged the message in Windows or Windows Information hub.
It also make sense to make displaying messages (types) configurable.

### Steps to reproduce
1. install nc client 2.5.1 on win 10
2. configure a profile and point it to a folder where an already opened (locked) file reside like ann outlook pst file
3.

### Client configuration
Client version:
2.5.1
Operating system:
win 10
OS language:
de_DE
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):
Nextckoud
Installation path of client:

### Server configuration

Operating system:

Web server:

Database:

PHP version:

Nextcloud version:

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
