### ISSUE TITLE
Nextcloud-14.0.4.2 with nginx-1.14.1_5 failed with infinite loop after login

### ISSUE THREAD

**Issue by jerome-diver** [nextcloud/desktop#983]
### Expected behaviour
Aftr login, redirection on app/files should show the web page

### Actual behaviour
Instead, from firefox or any other web browser, there is an infinite loop and web browser stop it with error: "The page isn’t redirecting properly"

### Steps to reproduce
1. install nextcloud-14 from FreeBSD-11.2 (andphp-7.2)
2. install and configure nginx with example provided by official nextcloud manual online
3. start nextcloud (config process is just fine), then login with your new first admin user

### Client configuration
Client version: web browser firefox

Operating system: Archlinux

OS language: 

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client: web ui

### Server configuration
same than example provide by nextcloud official manual pages for no sub-directory access

[nginx and config.php files](https://gist.github.com/jerome-diver/abd31f236f0617325589fb1e7eb0f774)

Operating system: FreeBSD-11.2

Web server nginx-1.14.1_5

Database: Postgresql-9.6

PHP version: 7.2

Nextcloud version: 14.0.4.2

Storage backend (external storage):

### Logs

just see on web dev tools from firefox that same redirection to https://cloud.mydomain.tk after login is redirected to https://cloud.mydomain.tk/app/files and go in an infinit loop as long as firefox stop it with error message: "The page isn’t redirecting properly"

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

no error on any nginx log files.

3. Server logfile: nextcloud log (data/nextcloud.log):

nextcloud log is empty (run with levellog 2)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server).

If you still have this problem with the latest server, please re-open the issue at https://github.com/nextcloud/server.

Thanks!

**Comment by jerome-diver** [comment]
thank you for your answer and interest after this 2 years i publicate this. Good luck.
