### ISSUE TITLE
Nextcloud Desktop crashes by full sync

### ISSUE THREAD

**Issue by snoppiz** [nextcloud/desktop#984]
### Expected behaviour
I started a full sync with an empty folder at my desktop.
I host a nextcloud server in my local network.
I expected that all files are downloaded and located at my desktop.

### Actual behaviour
Synchronization process started and checking process of remote files are completed.
The error occurred, while downloading multiple doc files. To many files are open.

### Steps to reproduce
1. I tried the process three times and it failed every time.

### Client configuration
Client version:
Version 2.5.1git
Operating system:

Archlinux kde-latest:
Linux hostname 4.19.12-arch1-1-ARCH #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018 x86_64 GNU/Linux
OS language:
en_us
Qt version used by client package (Linux only, see also Settings dialog):
using Qt 5.12.0, OpenSSL 1.1.1a 20 Nov 2018
Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
/usr/bin

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

Application: nextcloud (nextcloud), signal: Segmentation fault
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fd5117e2b40 (LWP 7141))]

Thread 8 (Thread 0x7fd4f560b700 (LWP 7192)):
#0  0x00007fd51de21c21 in poll () at /usr/lib/libc.so.6
#1  0x00007fd51d57f540 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fd51d57f62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fd51e4f35c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fd51e49c58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007fd51e2e05c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007fd51e2e19cc in  () at /usr/lib/libQt5Core.so.5
#7  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fd4f7716700 (LWP 7176)):
#0  0x00007fd51de274ed in syscall () at /usr/lib/libc.so.6
#1  0x00007fd51e2e3d75 in QSemaphore::acquire(int) () at /usr/lib/libQt5Core.so.5
#2  0x00007fd51e4c852a in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#3  0x00007fd51f4cdd03 in  () at /usr/lib/libQt5Network.so.5
#4  0x00007fd51f4302ff in  () at /usr/lib/libQt5Network.so.5
#5  0x00007fd51f416bfe in  () at /usr/lib/libQt5Network.so.5
#6  0x00007fd51f4151e7 in  () at /usr/lib/libQt5Network.so.5
#7  0x00007fd51e4c8b62 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x00007fd51ee65e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#9  0x00007fd51ee6d671 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#10 0x00007fd51e49d8f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#11 0x00007fd51e4a0998 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#12 0x00007fd51e4f3fd4 in  () at /usr/lib/libQt5Core.so.5
#13 0x00007fd51d57da2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007fd51d57f5e9 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007fd51d57f62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x00007fd51e4f35a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#17 0x00007fd51e49c58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#18 0x00007fd51e2e05c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#19 0x00007fd51e2e19cc in  () at /usr/lib/libQt5Core.so.5
#20 0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#21 0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fd5056e1700 (LWP 7146)):
#0  0x00007fd51de21c21 in poll () at /usr/lib/libc.so.6
#1  0x00007fd51d57f540 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fd51d57f62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fd51e4f35c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fd51e49c58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007fd51e2e05c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007fd51e2e19cc in  () at /usr/lib/libQt5Core.so.5
#7  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fd505ee2700 (LWP 7145)):
#0  0x00007fd51de21c21 in poll () at /usr/lib/libc.so.6
#1  0x00007fd51d57f540 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fd51d57f62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fd51e4f35c4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#4  0x00007fd51e49c58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#5  0x00007fd51e2e05c9 in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007fd529291ba6 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007fd51e2e19cc in  () at /usr/lib/libQt5Core.so.5
#8  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fd507ebe700 (LWP 7144)):
#0  0x00007fd51dd1dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fd50c5abc24 in  () at /usr/lib/dri/i965_dri.so
#2  0x00007fd50c5ab948 in  () at /usr/lib/dri/i965_dri.so
#3  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fd50f5a1700 (LWP 7143)):
#0  0x00007fd51de21c21 in poll () at /usr/lib/libc.so.6
#1  0x00007fd517328630 in  () at /usr/lib/libxcb.so.1
#2  0x00007fd51732a2db in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fd51068696b in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007fd51e2e19cc in  () at /usr/lib/libQt5Core.so.5
#5  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fd5117d7700 (LWP 7142)):
#0  0x00007fd51dd1dafc in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fd51e149cd1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#2  0x00007fd51e149cd1 in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007fd5218def54 in  () at /usr/lib/libQt5WebKit.so.5
#4  0x00007fd5218df079 in  () at /usr/lib/libQt5WebKit.so.5
#5  0x00007fd51e150063 in std::execute_native_thread_routine(void*) (__p=0x557866a0a360) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#6  0x00007fd51dd17a9d in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007fd51de2cb23 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7fd5117e2b40 (LWP 7141)):
[KCrash Handler]
#6  0x00007fd52913102e in OCC::PropagateDownloadFile::startDownload() () at /usr/lib/libnextcloudsync.so.0
#7  0x00007fd529131ddd in OCC::PropagateDownloadFile::startAfterIsEncryptedIsChecked() () at /usr/lib/libnextcloudsync.so.0
#8  0x00007fd51e4c83e0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#9  0x00007fd529158121 in OCC::PropagateDownloadEncrypted::folderStatusReceived(QString const&, bool) () at /usr/lib/libnextcloudsync.so.0
#10 0x00007fd51e4c83e0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#11 0x00007fd5291933d7 in OCC::GetFolderEncryptStatusJob::encryptStatusFolderReceived(QString const&, bool) () at /usr/lib/libnextcloudsync.so.0
#12 0x00007fd529187a27 in OCC::GetFolderEncryptStatusJob::finished() () at /usr/lib/libnextcloudsync.so.0
#13 0x00007fd529109fa4 in OCC::AbstractNetworkJob::slotFinished() () at /usr/lib/libnextcloudsync.so.0
#14 0x00007fd51e4c83e0 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#15 0x00007fd51f42addf in  () at /usr/lib/libQt5Network.so.5
#16 0x00007fd51f4cfa92 in  () at /usr/lib/libQt5Network.so.5
#17 0x00007fd51e4c8b62 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#18 0x00007fd51ee65e34 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x00007fd51ee6d671 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#20 0x00007fd51e49d8f9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#21 0x00007fd51e4a0998 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#22 0x00007fd51e4f3fd4 in  () at /usr/lib/libQt5Core.so.5
#23 0x00007fd51d57da2f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x00007fd51d57f5e9 in  () at /usr/lib/libglib-2.0.so.0
#25 0x00007fd51d57f62e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#26 0x00007fd51e4f35a9 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#27 0x00007fd51e49c58c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#28 0x00007fd51e4a4896 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#29 0x0000557865b21479 in main ()
[Inferior 1 (process 7141) detached]

**Comment by hanslfc** [comment]
I am having a similar issue, though I am using kernel 4.15.0-39-generic on Xubuntu.

**Comment by snoppiz** [comment]
### Conclusion ###
At my case:
I experiences those problems. 
If the desktop-client has a latest version and the nextcloud-server stuck at version 13.
I installed a new nextcloud-server to version 17.1 and this issue, does not appear anymore.
