### ISSUE TITLE
Additional Folder Sync Connections not using Target Folder URL

### ISSUE THREAD

**Issue by joewashear007** [nextcloud/desktop#987]
### Expected behaviour
1. Set up a new folder sync connection with local folder (i.e. `C:\Users\<user>\Music`  ) and server Folder (i.e `/Music`)
2. Folder Properly Synced

### Actual behaviour
Sync say it is working... but any sub folder in the directory is not synced. Looking that the logs and using fiddler, there are a lot of PROPFIND that are 404. Looking at the request more, they are using the wrong url. 

Using Fiddler Requests, I see two requests
The first is in the checking for updates files...
`PROPFIND /remote.php/dav/files/joseph/Music/Train/Train` HTTP/1.1 - 207 OK

`PROPFIND /remote.php/webdav/Train/Train` HTTP/1.1 - 404 BAD
Playing with request, if I add the `Music` fodler, is appears to work 
`PROPFIND /remote.php/webdav/Music/Train/Train` HTTP/1.1 - 207 OK

I think that a URL is being built wrong,  looks like a string concatingation issue. I never had this working on the 2.5.x clients. I though it was my server needing to have an update, but that hasn't worked.

### Steps to reproduce
1. Create a folder on the server. Place a file in the that folder. Also create a sub folder with a file.
2. Setup a folder sync pair to that new folder
3. The sub folder will never sync

### Client configuration
Client version:
2.5.1 daily: https://github.com/nextcloud/desktop/commit/a7b16e3c28433561bcce4a5c187ecd852260c90c

Operating system:
Windows 10 

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:
*default*

### Server configuration

Operating system:
Centos (using the docker image) Web server:

Database:
maridb

PHP version:

Nextcloud version:
15.0.0.10

Storage backend (external storage):
n/a

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:
NONE

3. Server logfile: nextcloud log (data/nextcloud.log):
NONE

**Comment by GieltjE** [comment]
This behaviour is reproducible by using the "Add folder sync connection" to a different disk, it rewrites calls to "/remote.php/webdav/<deepest-folder-name-only>" instead of including the proper path

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client and server to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
