### ISSUE TITLE
from source - starting gui-client fails: libnextcloudsync.so.0 not found

### ISSUE THREAD

**Issue by najtin** [nextcloud/desktop#988]
`$ (...)/nextcloud/desktop/build/build/bin/.nextcloud
./nextcloud: error while loading shared libraries: libnextcloudsync.so.0: cannot open shared object file: No such file or directory`

expect it run fine because file exists in 
`$ (...)/nextcloud/desktop/build/build/lib/`

OS: Ubuntu Mate LTS 18.04

Nextcloud: latest commit at time of cloning: https://github.com/nextcloud/desktop/commit/d6b34323c57a14b36d691534225f931694072736

used instruction on https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client for compilation

install path was custom ( in a homefolder)

**Comment by yan12125** [comment]
I believe you need to set LD_LIBRARY_PATH to run an installation in a custom folder.

**Comment by najtin** [comment]
do you have a hint for me how this would be done? what does LD mean here?

**Comment by najtin** [comment]
thank you very much for the hint the solution is:

add the path of the lib folder in your build folder to the file at `/etc/ld.so.conf.d/x86_64-linux-gnu.conf`

in my case `(...)/nextcloud/desktop/build/build/lib`

than `sudo ldconfig`

found here: https://www.linuxbabe.com/cloud-storage/compile-nextcloud-linux-client-ubuntu-16-04-16-10

i think this should be mentioned in the wiki
