### ISSUE TITLE
wiki compile instructions: unnecessary rsa-key verification

### ISSUE THREAD

**Issue by najtin** [nextcloud/desktop#989]
https://github.com/nextcloud/desktop/wiki/How-to-compile-the-desktop-client
unnecessary 
`git clone git@github.com:nextcloud/desktop.git`

should be 

`git clone https://github.com/nextcloud/desktop`

because
 - the the RSA fingerprint can not easily be verified. 
 - https is (right now) always a single-point of failure and has to be trusted anyways.

it is also the by github recommended setting

**Comment by camilasan** [comment]
It was fixed.
