### ISSUE TITLE
nextcloud desktop do not prevent multiple instances

### ISSUE THREAD

**Issue by ftoledo** [nextcloud/desktop#991]
I run the latest desktop client on xfce4 (debian stretch).
Sometimes the application start as 2 instances instead of only one.

I think that the app must prevent this behavior and ensure to start unique instance.

thanks!

![captura de pantalla_2019-01-02_21-32-27](https://user-images.githubusercontent.com/95441/50619193-85acdf00-0ed6-11e9-9ac6-658b7c755299.png)

**Comment by camilasan** [comment]
Hi, Could you try to run the most recent desktop client to check if you still have this issue? The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients).

If you still have this problem with the latest desktop client, please re-open the issue.

Thanks!
