### ISSUE TITLE
Client 2.5.1 does not sync with Owncloud anymore

### ISSUE THREAD

**Issue by s-hemer** [nextcloud/desktop#994]
Since client 2.5.1 (from nextcloud ppa), the single leftover access to an Owncloud instance (don't have any version info, maybe 10.0.10) refuses to login. The extra window opens but does not show the weblogin screen as for the Nextcloud instances. It just displays "Login Error Errorcode:" but no actual code.

For the previous version everything worked fine. Of course, I understand that one can argue "use the Owncloud client for Owncloud instances" or "move the instance to Nextcloud" but for my case both is not possible that easy (have to argue with the IT, server is from external partner) and in general I wouldn't want to install two clients anyway. So the question arises how big the effort is to gain/keep compatibility again

Can you comment on that?

**Comment by stratege1401** [comment]
I am sorry, but i dont really understant the question, as nextcloud and owncloud have forks. Sooner or later, this behaviors was meanted to happen on the client side, and sooner or later too on the server side.

This is like normal, now, you must choose the red puill, or the blue pill ...  Having both is not possible, unless i watch the bad movie !

**Comment by s-hemer** [comment]
Didn't I already stated that I understand your argumentation/I may even argue the same way? 

That's why I also did not asked for a fix or solution! I just wanted to note that behaviour as it may be just a small thing that was not noticed until now. Of course, I need to decide but for now, I have 3 nextcloud instances that I access with the recent client and one recent owncloud instance from a partner company I do not want to install a dedicated client for (which is, for now, 99% the same).

**Comment by stratege1401** [comment]
I dont want to be rude, or insulting.

- First off, i am an user, like you. Not a dev.
- Also, i completely understand your situation right now.
- but unfortunatly, want you want is kind of irrelevant because, again, sooner or later the code between ownserver and ncserver will have too much gap between them.

What if own decide to use only that king of stuff, the bleu one.
And NC decide to use the red one ...

The later, the harder !!!

**Comment by FlexW** [comment]
It is not supported to use the ownCloud server with the Nextcoud client.
