### ISSUE TITLE
Timeout while trying to connect to Nextcloud

### ISSUE THREAD

**Issue by MarkusKramer** [nextcloud/desktop#996]
I'm unable to connect to my nextcloud server using the Linux desktop client. My server (the reverse proxy) is using a custom SSL certificate.

### Expected behaviour
Should connect and ask to confirm custom SSL certificate.

### Actual behaviour
Error "Timeout while trying to connect to Nextcloud at https://a.b.de/abc/status.php"

### Client configuration
Client version: 2.5.1-1.1
Operating system: opensuse tumbleweed
Client package (From Nextcloud or distro) (Linux only): from distro

### Server configuration
Operating system: Ubuntu 18.04
Web server: Apache
Nextcloud version: 15.0.0

```
[OCC::OwncloudSetupWizard::slotSystemProxyLookupDone 	No system proxy set by OS
[OCC::AccessManager::createRequest 	2 "" "https://a.b.de/abc/status.php" has X-Request-ID "3343d564-0b73-450f-82a7-02168284b483"
[OCC::AbstractNetworkJob::start 	OCC::CheckServerJob created for "https://a.b.de/abc" + "status.php" "OCC::OwncloudSetupWizard"
[OCC::AbstractNetworkJob::slotTimeout 	Network job timeout QUrl("https://a.b.de/abc/status.php")
[OCC::CheckServerJob::onTimedOut 	TIMEOUT
```

Using
```
curl -v -k https://a.b.de/abc/status.php
```
I get
```
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"15.0.0.10","versionstring":"15.0.0","edition":"","productname":"Nextcloud"}
```
Thus, I'm pretty sure I don't have an issue with my networking. This setup has also previously worked with owncloud without issues.

**Comment by MarkusKramer** [comment]
Sorry, the issue was due a problem with IPv6.

**Comment by jstdoit** [comment]
> Sorry, the issue was due a problem with IPv6.

great! i fix the problem by disable IPv6
