### ISSUE TITLE
Weakness in spotting server-side file removal

### ISSUE THREAD

**Issue by hjohanns** [nextcloud/desktop#998]
In my setup, clients write data into a local synced directory. In order to manage aging and space limitation, this data is tagged, and then the files_retention app is used to eliminate it after some time (some weeks).
The files_retention app works at the server level, and it is expected that the files are then removed from the client, but the mechanism breaks easily with large quantity of data.

### Expected behaviour
When the files_retention app acts to delete data from the server, the expectation is that at next sync the same data is removed from the client local storage.

### Actual behaviour
It has to be said that the mechanism works for small quantities of data. The data is effectively removed at next sync.
The problem is with larger quantities of data, that this mechanism interacts with the fact that synchronisation is automatically turned off by the client when the amount to sync exceeds a certain threshold (500MB in our case). 
When synchronisation is turned back on, the mechanism sees files present on the client and absent on the server, and considers the client files as new files, so it copies them back on the server.
![autoexcludefromsync](https://user-images.githubusercontent.com/3250893/50734722-a493c580-11a3-11e9-8132-7a11654a5f93.png)
![optionunsynclargedirs](https://user-images.githubusercontent.com/3250893/50734724-acec0080-11a3-11e9-9bd8-3f673dbf8828.png)

### Steps to reproduce
1. Setup a NC server with a NC client on Windows
2. Create a large synced directory (larger than the setting shown in the screenshot). 
3. Sync turns off automatically for that directory
4. Delete some content from that directory on the NC server with the browser interface
5. Turn sync back on for the directory, files are copied again on the server.

### Client configuration
Client version: Windows 2.3.3 (build 1)

Operating system: Windows 10

OS language: French

Installation path of client: C:/Program Files (x86)/Nextcloud

### Server configuration

Operating system: Linux Ubuntu 18.04

Web server: Apache 2.4.29

Database: Mysql 8.0.13

PHP version: 7.2

Nextcloud version: 13.0.6

Storage backend (external storage): Local server disks

### Logs

Need to collect the logs with the client (TODO)

**Comment by FlexW** [comment]
Sorry for the later answer. Does this problem still exist with the newest version (3.2.0 at the moment)?

I don't understand why the 500mb limit might be a problem. Could you explain your theory more precise?
