### ISSUE TITLE
Nectloud-Client does not Connect to Server

### ISSUE THREAD

**Issue by Topfi** [nextcloud/desktop#999]
Hello, Community,

since a few days I have the problem that my Nextcloud client does not synchronize my data anymore. There is not a direct error message. It only shows "No connection to Nextcloud on https://nc.exmaple.online".
In the browser I can use the Nextcloud without any problems. My Nextcloud runs in a Dockercontainer behind a Reverse Proxy (Traefik).  The SSL certificates are all valid.
I reinstalled the program once and deleted all regedit entries and folders.
Even after a new installation the error occurs again.
I also tested it on another client and it doesn't work there either.

Does any of you have an idea?

Greetings Topfi

### Client configuration

Client version:
 Nextcloud Version 2.5.1final (build 20181204)

Operating system:
Windows  10 Pro Version 1809 (Build 17763.195)

Installation path of client:
C:\Program Files (x86)\Nextcloud

Synchronization Path:
E:\nextcloud

### Server configuration

Operating system:
Nextcloud runs in a docker container.

Web server:
Traefik Docker Reverse Proxy with Let's Encrypt

Database:
Type: mysql
Version: 10.3.11
Size: 1,3 MB

PHP version:
Version: 7.2.13
Memory limit: 512 MB
Maximum execution time: 3600
Maximum upload size: 511 MB

Nextcloud version:
Version: 15.0.0.10

Storage backend (external storage):
localhost

### Logs
[https://gist.github.com/Topfi/1c5316a3a3f2c8824cca99477f960bc0](url)

**Comment by Germano0** [comment]
in your client config file nextcloud.cfg there is a flag called `authType=`, try to changed it to `authType=webflow`

**Comment by Volker-K** [comment]
Are you using a proxy on your windows client? Desktop Clients 2.5.x doesn't realize if there's a system wide proxy configured.

**Comment by mgallien** [comment]
Do you still experience this bug ?
Looks like the last releases may have fix your problem.

**Comment by sunmetis** [comment]
Hi . Same here 999, even with Chown .. after docker compose , back to 999 how to solve this s..?
